### ISSUE TITLE
Deprecate MSAL v2 API in MSAL v3

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1001]
This is following our std. procedure for helping migrate:
* Move methods/properties to migration aid and remove functionality. 
* Provide simple info on what to do instead and link to aka.ms
* Build error

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
