### ISSUE TITLE
Fundamentals: Add API compat to build definitions

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1003]
Add api compat task to build definitions to unintended catch api changes

**Comment by bgavrilMS** [comment]
Not needed for 3.0.4 - we need to focus on features and fixes that affect the public API only so that we can remove the -preview tag.

**Comment by jmprieur** [comment]
@trwalke : is it something that you started? (if my memory is right).

**Comment by trwalke** [comment]
@jmprieur Yes I did but it was deprioritized once we started working on MSAL GA

**Comment by trwalke** [comment]
duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/670
