### ISSUE TITLE
Move all the error codes to MSAL.Error

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1004]
**Is your feature request related to a problem? Please describe.**
Some of the error messages are constants in the exception classes whereas other are constants in the new `MsalError` class. We should have only one mechanism (errors in the exception types preferred when it makes sense).

**Describe the solution you'd like**
Move the error codes from MsalError to the right Exception class if that makes sense

**Describe alternatives you've considered**
Move the constants from the Msal Exceptions to the MsalError class.

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1039

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
