### ISSUE TITLE
Deprecate UIParent and move static methods to different class

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1005]
Deprecate UIParent and move static methods to different class (e.g. IsSystemWebViewAvailable())

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1041

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
