### ISSUE TITLE
API Cleanup: remove ApiConfig and AppConfig namespaces

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1006]
ApiConfig and AppConfig are needed to construct and use the product.  These should just be in Microsoft.Identity.Client namespace and not in sub namespaces for discoverability.

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1015

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
