### ISSUE TITLE
Move ClientCredential to internal

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1007]
There is no longer a need for the ClientCredential class to be public.  We can do one of the following:

- Obsolete the class (so we can mark it [Obsolete]) and create a new ClientCredentialInternal class which is internal in order to replace the functionality
- Move the class to internal (makes it harder for Obsolete / Migration notes)

**Comment by jmprieur** [comment]
I would prefer the first option to help the migration

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
