### ISSUE TITLE
Silently renewing token in Authorization Code flow

### ISSUE THREAD

**Issue by crow-ua** [AzureAD/microsoft-authentication-library-for-dotnet#1008]
### Documentation Related To Component:
Acquiring tokens

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
I'm using OpenIdConnect in conjunction with MSAL in my ASP.NET Core application. First-time sign in works just fine - the user is redirected to AD login and after consent is given, middleware receives code which is successfully traded to access+id tokens (`OpenIdConnectResponseType.CodeIdToken`). They are cached.
But after token expires `AcquireTokenSilentAsync` throws `AADSTS65001` indicating we need to authorize again. Since we don't want the end user to sign in every hour, refreshing token on the back-end silently is preferred. And the problem with this is - `AuthenticationResult` does not contain `RefreshToken` that can be passed to `(app as IByRefreshToken).AcquireTokenByRefreshToken(scopes, refreshToken)` method (`MsalTokenResponse` in the internals of MSAL does since payload received from AAD contains "refresh_token" field).
I understand (not propagating refresh token to MSAL result) is  (kind of?) intentional, but it is not very clear how to do silent refresh in this scenario working. There is a chance of some misconfiguration that causes silent renew to fail, but it would be nice to have it clarified as well. Off-the-cuff there is a "backup" solution to use ADAL for initial sign-in, grab refresh token and pass it to back-end (some kind of OOB flow), but it's ugly.
@jmprieur

**Comment by jmprieur** [comment]
@crow-ua 
could you please have a look at https://github.com/azure-samples/ms-identity-aspnetcore-webapp-tutorial ?

The trick is that AcquireTokenByAuthorizationCode caches the access token and the refresh token, and then it can be used for ever by a call to AcquireTokenSilent

**Comment by jmprieur** [comment]
cc: @henrik-me FYI

**Comment by crow-ua** [comment]
@jmprieur I'm using your another [sample](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph).
The middleware indeed calls `AcquireTokenByAuthorizationCodeAsync`
```
var cca = new ConfidentialClientApplication(_azureOptions.ClientId, _azureOptions.BaseUrl + _azureOptions.CallbackPath, new ClientCredential(_azureOptions.ClientSecret), new SessionTokenCache(identifier, memoryCache).GetCacheInstance(), null);
var result = await cca.AcquireTokenByAuthorizationCodeAsync(code, scopes);
```
Then in `Controller` I want to silently refresh token:
```
// btw is this a best practice to recreate the application every time? TokenAcquisition class sort of implies it is
var cca = new ConfidentialClientApplication(_azureOptions.ClientId, _azureOptions.BaseUrl + _azureOptions.CallbackPath, new ClientCredential(_azureOptions.ClientSecret), new SessionTokenCache(identifier, memoryCache).GetCacheInstance(), null);
// because we are using the same cache that is in the middleware, account is present
var accounts = await cca.GetAccountsAsync();
 if (accounts != null)
 {    
     var result = await cca.AcquireTokenSilentAsync(scopes, accounts.First());
 }
```
On the last line I see few various issues, namely `AADSTS65001: The user or administrator has not consented to use the application with` returned when token has expired. What is particularly weird, that if I instantly do subsequent `cca.AcquireTokenSilentAsync(scopes, accounts.First(), authority, forceRefresh:true);` call, it silently succeeds. 
So, in order of achieving working silent token refresh scenario I either need to call `AcquireTokenSilentAsync` with `forceRefresh=true` every time or do the above described `Acquire-exception-Acquire force refresh` chain. I don't think either of those options are viable.
p.s. I've debugged in Fiddler, refresh_token is always present in the AD response payload.

**Comment by jmprieur** [comment]
@crow-ua 
Which audience are you using? AAD only? (MyOrg or AnyOrg) or AAD + MSA (Work and School accounts or Microsoft personal accounts)

In the sample what happens is that you get an MsalUIRequiredException, and it's sent back to the client to have the consent presented to the user, and then the next time everything is fine. 

are you saying that you write the following:

```CSharp
 if (accounts != null)
 {    
   try
   {
     var result = await cca.AcquireTokenSilentAsync(scopes, accounts.First());
   }
   catch(Exception)
  {
      result = await cca.AcquireTokenSilentAsync(scopes, accounts.First());
  }
 }
```
and that this works?

**Comment by crow-ua** [comment]
> Which audience are you using?

common
>In the sample what happens is that you get an MsalUIRequiredException, and it's sent back to the client to have the consent presented to the user

That totally makes sense for me. I'm struggling with having consent exception when consent has been already given.
> the following

Second call is with forceRefresh:
```
if (accounts != null)
 {    
   try
   {
     var result = await cca.AcquireTokenSilentAsync(scopes, accounts.First());
   }
   catch(Exception)
   {
      // "AADInstance": "https://login.microsoftonline.com/{0}/v2.0", "TenantId": "common"
      var authority = string.Format(CultureInfo.InvariantCulture, _azureOptions.AADInstance, _azureOptions.TenantId);
      result = await cca.AcquireTokenSilentAsync(scopes, accounts.First(), authority, true);
   }
 }
```
The problem with this approach is, second acquire can still fail when we revoked access which implies adding yet another try/catch which is totally ugly. 
p.s. We debugged this flow more a little bit, and noticed first acquire sometimes "refresh" token 2 minutes prior to expiration (does the operation, but returns the same token).

**Comment by henrik-me** [comment]
@crow-ua : Seems like what you are saying is that the acces token returned after refreshing the token is the old one and not the new one, is that correctly understood?
If so can you pls. create a separate issue on that?
