### ISSUE TITLE
Make DeviceCodeResult serializable

### ISSUE THREAD

**Issue by PlanetWilson** [AzureAD/microsoft-authentication-library-for-dotnet#1013]
I would like to suggest that DeviceCodeResult is changed so that there are public setters on the properties and a public parameterless constructor.

As it is one cannot instantiate your own DeviceCodeResult meaning it cannot be stored and re-hydrated later to check whether the Access Token is available in a device code flow scenario. 

Device code flow is an inherently disconnected scenario where the user goes off and logs in independently of your application. So you cannot call ctx.AcquireTokenByDeviceCodeAsync to ask for the Access token unless you have the actual original DeviceCodeResult object to hand.

**Comment by bgavrilMS** [comment]
If you call AcquireTokenSilent before AcquireTokenByDeviceCode, it will first look for a token in the token cache. The results of AcquireTokenByDeviceCode will always be stored in MSAL's cache. 

Have a look at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token#recommended-call-pattern-in-public-client-applications-with-msalnet-3x and at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization
