### ISSUE TITLE
Question: Is Prompt.ForceLogin Supposed to Show Consent Request UI If Required Also?

### ISSUE THREAD

**Issue by myokeeh** [AzureAD/microsoft-authentication-library-for-dotnet#1022]
I'm running into AADSTS65001 error for a new user account. Previous behavior from ADAL, I believe, was if UI was presented, consent request was displayed right after.

Is `Prompt.ForceLogin` also supposed to show consent request IF not previously granted? I understand `Prompt.Consent` exists, but don't want to request it if already granted.

**Comment by myokeeh** [comment]
@jmprieur where is it answered?

**Comment by jmprieur** [comment]
@myokeeh I probably selected the wrong label in GitHub: sorry for that (the UI sometimes plays trick on me)
What is your scenario? can you elaborate a bit more?

**Comment by myokeeh** [comment]
I'm finding myself asking the user to log in twice. Once for "user_impersonation" scope and a "user.read" scope for Microsoft Graph (for getting user Firstname, Lastname, account photo, etc). For the Microsoft Graph log in, if the user has never used logged in, I have to present an interactive log in to prompt consent.

`Prompt.Consent` seems to do it, but consent UI isn't presented with `Prompt.ForceLogin`.

By the way, is there a way to combine these "scopes"?

```
IPublicClientApplication pca = PublicClientApplicationBuilder.Create(clientId)
                        .WithRedirectUri(redirectUri)
                        .Build();

                       string[] scopes = { resourceId + "/user_impersonation" };
                       var users = await pca.GetAccountsAsync();
                       var user = users.FirstOrDefault();
                       msalar = await pca.AcquireTokenSilent(scopes, user)
                                      .ExecuteAsync();
```

```
IPublicClientApplication pca = PublicClientApplicationBuilder.Create(clientId)
                    .WithRedirectUri(redirectUri)
                    .Build();

                string[] scopes = { "user.read" };
                var users = await pca.GetAccountsAsync();
                var user = users.FirstOrDefault();

                try
                {
                    msalar = await pca.AcquireTokenSilent(scopes, user)
                                      .ExecuteAsync();
                }
                catch (MsalUiRequiredException ee)
                {
                    if (ee.Message.Contains("AADSTS65001"))
                    {
                        //present UI to have user consent
                        msalar = await pca.AcquireTokenInteractive(scopes, null)
                                          .WithAccount(user)
                                          .WithPrompt(Prompt.Consent)
                                          .ExecuteAsync();
                    }
                }
```

**Comment by jmprieur** [comment]
Thanks for the update @myokeeh !
