### ISSUE TITLE
TypeInitializationException in PublicClientApplication on Xamarin.iOS

### ISSUE THREAD

**Issue by Dismissile** [AzureAD/microsoft-authentication-library-for-dotnet#103]
I am trying to create a new instance of the PublicClientApplication class and I keep getting an exception:

'The type initializer for 'Microsoft.Identity.Client.Internal.PlatformPlugin' threw an exception.'

It looks like it is failing at:

at Microsoft.Identity.Client.Internal.PlatformPlugin.LoadPlatformSpecificAssembly()
at Microsoft.Identity.Client.Internal.PlatformPlugin.InitializeByAssemblyDynamicLinking()
at Microsoft.Identity.Client.Internal.PlatformPlugin..cctor()

This is a Xamarin.iOS application, not Xamarin.Forms.

**Comment by kpanwar** [comment]
Next preview release will be issuing a single binary per platform, so this issue will never happen.

**Comment by Dismissile** [comment]
Do you have an ETA on that preview release?

**Comment by kpanwar** [comment]
Not at the moment.
