### ISSUE TITLE
GetAccounts does not work in a multi-cloud enviroment

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1030]
**Which Version of MSAL are you using ?**
MSAL 3.0.2 preview

**Platform**
all

**What authentication flow has the issue?**
GetAccounts

**Repro**

1. Create a Public Client App with the Public Azure Cloud
1. Acquire a token intractive, using the DE Azure Cloud
1. Perform a GetAccounts

Expected: no accounts should be returned because the PCA is scoped to the Public Cloud
Actual: the DE account is returned, with the env set to "login.microsoftonline" This leads to exceptions later on.

Note: GetAccounts should not perform instance discovery

@jmprieur - the solution we came up with is the following: 

1. If all the accounts in the cache are AzurePublic, we will not perform instance discovery. Otherwise, we will.
1. Filter the accounts by the "preferred cache environment" (i.e. "login.windows.net" or whatever the instance discovery tells us)

**Alternative solutions:** 

1. GetAccounts to return ALL accounts and use the "preferred cache env" in the IAccount.Enviroment field (this is a breaking change and would also probably need API review)
2. GetAccounts to perform instance discovery (we've had push back from the community around this)
3. Store instance discovery metadata in the token cache (this is not a breaking change but requires a lot of work and API review)

Note: we should also give guidance on using multi-cloud, i.e. create a PCA for each cloud.

**Comment by bgavrilMS** [comment]
@MarkZuber @crmann1 - tracking bug for the multi-cloud issue

**Comment by bgavrilMS** [comment]
@MarkZuber  - this is ready for review, please have a look!

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
