### ISSUE TITLE
AcquiteTokenInteractive with Account and prompt set to Select_Account is confusing

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1031]
**Which Version of MSAL are you using ?**
3.0.2-preview

**Platform**
netfx

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**

```csharp
await PublicClientApplication
                    .AcquireTokenInteractive(scopes, null)
                    .WithAccount(CurrentUser)
                    .WithPrompt(Prompt.SelectAccount)      // probably others too         
                    .ExecuteAsync();
              
```

**Expected behavior**
We should not allow the user to make this call. It's probably just a bad configuration. Just throw "don't use WithAccount or WithLoginHint and prompt behavior SelectAccount or ForceLogin etc.

**Actual behavior**
If the user selects a different account than the one passed in, we throw a rather cryptic exception saying: 
_"Returned user identifier does not match the sent user identifier when saving the token to the cache."_

This is confusing because I don't necessarily know what a token cache is (e.g. on mobile), it exposes internal implementation details ("when saving to the token cache") etc.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by ChainReactive** [comment]
I just started integrating MSAL v3 into my UWP app and posted a [related issue](https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/issues/20).  The offending `WithAccount`/`WithPrompt` combination that you mention is included in the v3 sample's `SignInButton_Click` handler.  Does your advice apply to the sign-in scenario?  I'm a newbie here, but it does seem strange that the sample calls `WithAccount` with a likely `null` value for `account`.

@bgavrilMS What do you think of the [v3 sample app code](https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/tree/jennyf/v3)?  I was counting on it indicating best practice, but now I'm not so sure.  Do you think that lines [29](https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/blob/fc41c987d348aad9288e227591f25caf34333fb6/active-directory-b2c-wpf/MainWindow.xaml.cs#L29), [33](https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/blob/fc41c987d348aad9288e227591f25caf34333fb6/active-directory-b2c-wpf/MainWindow.xaml.cs#L33), and [47](https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/blob/fc41c987d348aad9288e227591f25caf34333fb6/active-directory-b2c-wpf/MainWindow.xaml.cs#L47) are all unnecessary?  It seems that `SignOutButton_Click` clears the cache, and `Window_Loaded` silently logs in upon app launch if the cache isn't empty, so it will always be empty in ``SignInButton_Click``.

**Comment by bgavrilMS** [comment]
@ChainReactive Hi Adrian, thx for the feedback. Let me try to address these separately: 

1. It's always a good idea to pass a login hint when performing an interactive login - it's a nicer user experience. Personally, I liked the experience where if there was a single account in the browser cache (not MSAL's cache), and you provided that as a hint, it would take the user directly to the password input. Still, the new experience is still ok - if you provide a long hint, the STS will show an account picker and will pre-select the tile with the login_hint. 

2. I see where you're going at with the cache always being empty in SIngInButton. We're not WPF developers, so we will make subtle mistakes like that. I do think however that it's important to showcase the pattern of: 

- acquire token silent (i.e. from the cache, very fast)
- on failure, acquire token interactive 

I'd rather leave the subtle mistake that has a very small perf impact there in order to enforce this pattern.

**Comment by ChainReactive** [comment]
@bgavrilMS Thanks for the clarification in 2.  You've confirmed that my code calls `WithAccount` when needed.  It makes no difference to me at this point but, from the perspective of someone using the samples to understand MSAL, I can tell you it's nice when a sample captures an API's subtleties.  The sample's `CallApiButton_Click` method captures said pattern so there's really no need to repeat it in `SignInButton_Click`.

I just thought of a contradiction in the API.  Perhaps you can explain how it works.  According to `WithPrompt`'s docs, "The default is `Microsoft.Identity.Client.Prompt.SelectAccount`".  But how can that be the default?  If you call `WithAccount` with a non-null `account` but without also calling `SelectAccount` to change away from the default, then it's the nonsensical combination of account and prompt.  Or does calling `WithAccount` implicitly change the prompt?

**Comment by jmprieur** [comment]
This is an old issue, @bgavrilMS, and I have not seen any recent complain about this.
Proposing to close.
