### ISSUE TITLE
B2C with login.microsoft.com authority is saving to cache using the wrong env

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1037]
**Which Version of MSAL are you using ?**
MSAL 3.0.3 preview

**Platform**
b2c

1. Acquire a token interactive using the authority login.microsoftonline.com/tfp/...
2. Look at the token cache

Expected: env should be login.windows.net
Actual: env is login.microsoftonline.com

Impact: login.windows.net is the "preferred cache env", so this is violating the server instance metadata. Other MSALs might look ignore the tokens or the accounts in this case. Also a unit test is failing because of it.

**Comment by bgavrilMS** [comment]
Root cause is the fact that we don't we sometimes perform instance discovery and sometimes we do not for that authority.

**Comment by bgavrilMS** [comment]
Impact: extra network call

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
