### ISSUE TITLE
Intermittent test failure B2CMicrosoftOnlineCreateAuthority

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1038]
Root cause is a static list that we keep on the B2CAuthority class with some allowed hostnames. 
Depending on the order of the tests, a test might add to that list and B2CMicrosoftOnlineCreateAuthority might pass. 

If you run it on its own, it will fail.

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
