### ISSUE TITLE
Logging in users from multiple clouds fails

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1048]
**Which Version of MSAL are you using ?**
MSAL 3.0.2-preview

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

**Repro**
1. Interactive Login with a German clould user in the German cloud
2. Interactive Login with a Public cloud user in the public cloud, using the same client id

Expected: login should work 
Actual: Public cloud user is not found

Root cause: 

- we perform [instance discovery](https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.de%2Fcommon%2Foauth2%2Fv2.0%2Fauthorize) and cache the result for all clouds
- in fact, we don't even need to perform intance discovery in order to figure out the OpenId discovery endpoint - the endpoint is constructed by appending /.well-known/openid-configuration to the authority url (according to the OpenID spec, (section 4)[https://openid.net/specs/openid-connect-discovery-1_0.html])

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
