### ISSUE TITLE
Signing key rollover

### ISSUE THREAD

**Issue by titobf** [AzureAD/microsoft-authentication-library-for-dotnet#105]
I just got an email from Microsoft about a signing key rollover: [Signing key rollover in Azure Active Directory](https://azure.microsoft.com/en-us/documentation/articles/active-directory-signing-key-rollover/?WT.mc_id=azurebg_email_Trans_1150_Azure_AD_Certificate_Rollover_EN%20ONLY#vs2015)

Does this library handles that? I'm new to the subject. Thanks in advance

**Comment by kpanwar** [comment]
This library does not handle/assist in key rolling. It is completely a server side operation and client library is agnostic to it.
