### ISSUE TITLE
Update B2C documentation about preferred_username in idToken

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1054]
### Documentation Related To Component:
Username field shows "missing from the token response" because IdToken for B2c does not return a field here. This needs to be documented in MSAL wiki.

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Comment by jennyf19** [comment]
[done](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#preferred_username-missing-from-the-token-response)
with [mitigation section](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#mitigation-for-missing-from-the-token-response)

**Comment by jmprieur** [comment]
thanks @jennyf19
