### ISSUE TITLE
AcquireTokenInteractive should not throw on NetCore when using a CustomWebUI

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1058]
MSAL 3.0.3-preview

User this code on .NetCore 

```csharp
await pca
                .AcquireTokenInteractive(s_scopes)
                .WithCustomWebUi(someWebUI)
                .ExecuteAsync(new CancellationTokenSource(_interactiveAuthTimeout).Token)
                .ConfigureAwait(false);
```

Expected: this should work 
Actual: 

System.PlatformNotSupportedException: 'On .NET Core, interactive authentication is not supported. Consider using Device Code Flow https://aka.ms/msal-net-device-code-flow or Integrated Windows Auth https://aka.ms/msal-net-iwa'

**Comment by bgavrilMS** [comment]
I propose we fix this before removing the -preview tag as well. It's an easy fix, we just need to improve the validation and move it somwhere else. Feel free to propose a new milestone if you disagree @jmprieur

**Comment by jmprieur** [comment]
yes, go ahead @bgavrilMS 
this bugs defeats a bit the purpose of the custom Web UI on that platform :)

**Comment by jennyf19** [comment]
Included in [MSAL.NET 3.0.6-preview release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.6-preview)
