### ISSUE TITLE
How should multiple tokens be handled using MSAL?

### ISSUE THREAD

**Issue by AnnejanBarelds** [AzureAD/microsoft-authentication-library-for-dotnet#106]
I'm working on an ASP.NET Core MVC app that uses the new AAD v2 endpoint and MSAL to obtain tokens for both a WebAPI (using the same ClientID as the MVC app itself) and the Graph API in order to access user emails.

The combination of two tokens in one client app gave some trouble. The main problem I had was that AAD seems to return a token with scope Mail.Read, even though I'm requesting one for scope [insert ClientID here]. So this token cannot be used to access the WebAPI (because audience validation fails). If the Mail.Read scope is excluded from the initial signin request, I seem to be able to get a correct token, but once the application requests a token for scope Mail.Read, it's no longer able to request a token for scope [insert ClientID here]. I got it to work by passing the IdToken instead of the Access Token to the WebAPI (which is allowed since the MVC app and the WebAPI share the same ClientID), but it still somehow feels weird.

Judging from the traffic that is sent over the wire, it seems that MSAL is creating a request that contains the correct scope, but it is using the most recent Refresh Token it received from AAD. So if the client requests a token with scope Mail.Read at some point, it will use the refresh token it receives in response for the next request - even when the next request is for a different scope for which a different Refresh Token is available. In response, it will receive a new access token with another scope than was requested.

Is this behavior intended and am I doing something wrong or expecting the wrong things?

Of course I can share some code to repro the issue.

Edit: typo

**Comment by kpanwar** [comment]
you can pass Mail.Read as additional scope. to the API.
