### ISSUE TITLE
GetAccountAsync(userId) returns null

### ISSUE THREAD

**Issue by ferronsw** [AzureAD/microsoft-authentication-library-for-dotnet#1061]
**Which Version of MSAL are you using ?**
MSAL 3.03

**Platform**
.Net Core 2.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [X ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**

**Repro**

```csharp
var account = await _app.GetAccountAsync(userId);
```

**Expected behavior**
I should expect it to return the user account.

**Actual behavior**
It returns null

**Possible Solution**
I looked up all account with `var accounts = await _app.GetAccountsAsync();`.
The user I was looking for is found in the returned results.

I looked at the [source code](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/Microsoft.Identity.Client/ClientApplicationBase.cs) and discovered that account.HomeAccountId.Identifier is used to find the expected account. When I looked at this value I discovered that it doesn't only contains the userId, but also the tenantId (like userId.tenantId). 
The account.HomeAccountId.ObjectId only contains the userId. So account.HomeAccountId.Identifier is not correct or the account.HomeAccountId.ObjectId should be used to get the account you want.

**Additional context/ Logs / Screenshots**
![image](https://user-images.githubusercontent.com/19926383/55936848-c0da4f00-5c37-11e9-837e-3f87877cc294.png)

**Comment by jmprieur** [comment]
@ferronsw what are your repro steps? 
You write you are in a Web App, but where do you use this code? what is userId?

Also did you look at this tutorial: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 ? In particular https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph.

You might be interested in https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/0aef6f10839648ba37cfed545b9202145bd99bcd/Microsoft.Identity.Web/ClaimPrincipalExtension.cs#L13-L23 ?

**Comment by ferronsw** [comment]
I build it from this [sample](https://github.com/microsoftgraph/aspnetcore-connect-sample/tree/master/MicrosoftGraphAspNetCoreConnectSample)

I use this code in the GraphAuthProvider class like provided in the sample.

**Comment by jmprieur** [comment]
Thanks for your quick answer @ferronsw 
the sample you used seems to have been updated recently, but exposes (in Extensions) which are now part of ASP.NET Core. 
- How hard would it be to start from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph. ?
- Moving forward, I think I need to send a PR for the Graph sample you used.

**Comment by zulander1** [comment]
I am having the same issue, used the exact same sample...

**Comment by henrik-me** [comment]
@ferronsw @zulander1 : did you try starting from the sample @jmprieur pointed out above? (Please re-open if you would need us to help)

@jmprieur : If we need to update a sample, then pls. re-open or consider if creating an issue in the Sample repo is a better approah.
