### ISSUE TITLE
Fundamentals: Enable B2C UI automations on iOS

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1069]
The B2C UI automation tests on iOS are all ignored. They should be running w/the Android tests.

**Comment by jmprieur** [comment]
@henrik-me. do we know why they are ignored?

**Comment by jennyf19** [comment]
@jmprieur it's because the UI Ids are different on iOS then Android.

**Comment by henrik-me** [comment]
Updating priority. Should be part of the next release after 4.0.

**Comment by jennyf19** [comment]
Local accounts are not working due to bug on Xamarin.UITest w/iOS, as elements are placed on the same text field.

**Comment by jmprieur** [comment]
this is now available with MSAL.NET 4.1
