### ISSUE TITLE
Caching of token on UWP does not work with UniversalWindowsPlatform library 5.2.2

### ISSUE THREAD

**Issue by jsturtevant** [AzureAD/microsoft-authentication-library-for-dotnet#109]
After making the initial call to  ```AcquireTokenAsync``` which returns successfully and has a token, making a subsequent call to ```AcquireTokenSilentAsync``` fails with message "Failed to acquire token silently. Call method AquireToken".

The project.json file that causes this issue for a UWP application is:

```
{
  "dependencies": {
    "Microsoft.Identity.Client": "1.0.304142221-alpha",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "Xamarin.Forms": "2.1.0.6529"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

### Reproducing
If  you use the project at https://github.com/Azure-Samples/active-directory-b2c-xamarin-native you will see it work successfully.  I have forked the project and updated the libraries to reproduce the error here: https://github.com/jsturtevant/active-directory-b2c-xamarin-native.  Should be able to clone repo and reproduce. Note you will have to put in your own B2C keys.  You can also see the [last commit](https://github.com/jsturtevant/active-directory-b2c-xamarin-native/commit/dc90e24c209382d45a20d31194bb8ba2b4637363) to see the changes need to reproduce.

**Comment by kpanwar** [comment]
I have filed this issue in CoreCLR repo. https://github.com/dotnet/coreclr/issues/6483

**Comment by kpanwar** [comment]
This is a Corefx issue
