### ISSUE TITLE
[UAP] Browser cookies are not kept even if https:\\sso is used

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1093]
**Which Version of MSAL are you using ?**
MSAL 3.0.5-preview

**Platform**
uap

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

**Repro**

1. Do not specifiy a redirect URI -> urn:obo... is used - this is inconsistent with ADAL, which will default to https:\\sso on UAP
2. Manually configure "https:\\sso" as a redirect uri
3. Get the app Uri by running this piece of code

```csharp
            var redirectURI = Windows.Security.Authentication.Web.WebAuthenticationBroker.GetCurrentApplicationCallbackUri();
```

4. Register that uri in the portal
5. Acquire token interactive

**Expected behavior**
Token to be issued and the browser should be "shared", i.e. it should show previous users that used the browser.

**Actual behavior**
  AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '9058d700-ccd7-4dd4-a029-aec31995add0'. 

Note: this scenario works in ADAL and it is documented.

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1186

**Comment by bgavrilMS** [comment]
I believe this is fixed?

**Comment by jennyf19** [comment]
@bgavrilMS [yes](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1557)

**Comment by jennyf19** [comment]
fixed.
