### ISSUE TITLE
Update Documentation for Android

### ISSUE THREAD

**Issue by dansiegel** [AzureAD/microsoft-authentication-library-for-dotnet#1094]
### Documentation Related To Component:

Currently the docs for Android specify that you must add the following to your AndroidManifest

```xml
<activity android:name="microsoft.identity.client.BrowserTabActivity">
	<intent-filter>
		<action android:name="android.intent.action.VIEW" />
		<category android:name="android.intent.category.DEFAULT" />
		<category android:name="android.intent.category.BROWSABLE" />
		<data android:scheme="msal{client_id}" android:host="auth" />
         </intent-filter>
</activity>
```

This should be updated to suggest that you may consider doing something in code such as:

```cs
[IntentFilter(new[] { Intent.ActionView }, 
    Categories = new[] { Intent.CategoryBrowsable, Intent.CategoryDefault },
    DataHost = "auth",
    DataScheme = Constants.DataScheme)] // where the constant is msal{client_id}
public class MSALActivity : BrowserTabActivity
{
        
}
```

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

It's really a lot easier for developers to swap out Constants files than write scripts to do regex replacements in app Manifests. Similarly it should be investigated if there is a way we can achieve something similar from code for iOS.

Documentation & Samples should be helping to guide people towards best practices and not bad practices.

**Comment by jmprieur** [comment]
@dansiegel 
Would powershell Scripts like this ones work for you?
https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/msal3x/AppCreationScripts/AppCreationScripts.md

**Comment by jmprieur** [comment]
@dansiegel I just realized what you wrote (sorry long day!). you mean we can actually write this already today and therefore remove the need to change the Android manifest? that's awesome!

**Comment by dansiegel** [comment]
Actually just submitted an issue for Xamarin.iOS on the Attribute usage... but what I posted should actually work right now for Android since they already have all of the Attribute usage. In essence if I never touch the AndroidManifest, but just add an Activity in code like I showed

**Comment by jmprieur** [comment]
Awesome! thanks for sharing!
cc: @jennyf19 @bgavrilMS @danieldobalian FYI

**Comment by TiagoBrenck** [comment]
Hi @dansiegel, I am trying to find the iOS issue that you submitted about Attribute usage but I cant find it. Would you still have the link for it?

**Comment by jennyf19** [comment]
@TiagoBrenck found [it](https://github.com/xamarin/xamarin-macios/issues/5916)

**Comment by jmprieur** [comment]
Closing as the docs where updated in docs.ms: See https://docs.microsoft.com/azure/active-directory/develop/msal-net-xamarin-android-considerations#update-the-android-manifest

**Comment by tipa** [comment]
@jmprieur just found this issue as I was confused by the docs when going through them.
In the XML example, it says to write different values than in the code example - so what is the correct way of doing it now?
![image](https://user-images.githubusercontent.com/2863198/102724955-76b5d600-4313-11eb-87fa-cee3d131bb85.png)
![image](https://user-images.githubusercontent.com/2863198/102724961-7b7a8a00-4313-11eb-8a9f-87feed751c11.png)
