### ISSUE TITLE
Fundamentals: CacheCompat tests should login and verify multiple accounts

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1097]
CacheCompat logs in one user.  We have lots of "firstordefault" style logic within cache (and cache fallback with msal reading adal cache) where we could possibly pick the wrong account if our lookup (upn/homeaccountid/etc) doesn't match properly.

So we need the CacheCompat tests to login multiple users and then ensure later that the multiple users are all ATS'd from the cache.

Also, for ADAL, ensure that we login a user that has ClientInfo and one that doesn't have ClientInfo so that we hit VisualStudio's case where the migration wasn't finding the proper account since HomeAccountId is empty when there's no ClientInfo.

**Comment by MarkZuber** [comment]
no lab support for creating multiple accounts, provided API doesn't work (401 unauthorized).  infrastructure for the individual tests is in place to test multiple accounts.

**Comment by bgavrilMS** [comment]
Closing this as we are moving to broker based SSO
