### ISSUE TITLE
ADAL Fallback failing based on HomeAccountId lookup that won't work

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1100]
MSAL 3.0.5-preview

When we need to do ADAL fallback from MSAL, we were doing the lookup based on account.HomeAccountId or requestParameters.LoginHint. But an ADAL account will never have a HomeAccountId (by design) and we need to be able to look up by Account.UserName instead.

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1096

**Comment by jennyf19** [comment]
Included in [MSAL.NET 3.0.6-preview release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.6-preview)
