### ISSUE TITLE
Providing externally acquired token to TokenCache

### ISSUE THREAD

**Issue by zvrba** [AzureAD/microsoft-authentication-library-for-dotnet#1103]
**Is your feature request related to a problem? Please describe.**
Scenario: Java UI application authenticates the user with the AD and acquires tokens. The access and refresh tokens are passed to a C# back-end through environment variables (both are desktop applications, i.e., public clients).  In C#, I'd like to use AcquireTokenSilent so that TokenCache handles refresh. However, there's no obvious way of adding tokens to the TokenCache. There are Serialize and Deserialize methods, but Java libraries do not implement serialization and the format is undocumented. (Also, there are security issues with writing token cache to the file; these are eschewed when passing token through environment variables).

**Describe the solution you'd like**
TokenCache should have methods for adding access and refresh tokens that have been acquired out of band.

**Describe alternatives you've considered**
#667 suggests using On Behalf Of flow. I haven't tried it, but it feels anyway "wrong" to use methods meant for use by confidential clients. Are there any other suggestions?

**Comment by jmprieur** [comment]
@zvrba 

Can you please try the following code:

```CSharp
string refreshToken = ...; // bring your refresh token
IByRefreshToken byRefreshToken = app as IByRefreshToken;
var result = await byRefreshToken.AcquireTokenByRefreshToken(scopes, refreshToken)
                                                     .ExecuteAsync();
```

That's a feature we added to help servers (Web App / Web APIs) to migrate from ADAL 2.x, but it seems you have another scenario where it could help.
For details, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#adalnet-v2x-migration-to-msalnet-v3x for details.

Note that you don't need to bring the access token (the refresh token is enough). 
Also if you are not interested in the result, you don't need to have the assignement
Finally, I believe (if I remember correctly) that scopes can be empty

**Comment by zvrba** [comment]
Hi, I tried what you suggested but, unfortunately it did not work: `AcquireTokenByTokenRefresh` throws "MsalUiRequiredException: AADSTS65001: The user or administrator has not consented to use the application with ID … Send an interactive authorization request for this user and resource.".

![image](https://user-images.githubusercontent.com/630366/56486577-5d261080-64d8-11e9-8e58-203165196aad.png)

The administrator HAS consented to the application, as shown in the screenshot. I also tried to sign in the user interactively (open a webpage, then paste the code in the UI app to receive the token and refresh token), and the consent dialog for the user did not even pop up.

This is the sample code:

```
            var pc = PublicClientApplicationBuilder.Create("XX-XX-XX-XX-XX")
                .WithAuthority("https://login.microsoftonline.com/quineusers.onmicrosoft.com")
                .WithRedirectUri("https://login.microsoftonline.com/common/oauth2/nativeclient")
                .Build();
            var pcr = pc as IByRefreshToken;
            //var tr = pcr.AcquireTokenByRefreshToken(new string[] { "https://graph.microsoft.com/.default" }, RefreshToken).ExecuteAsync().Result;
            var tr = pcr.AcquireTokenByRefreshToken(null, RefreshToken).ExecuteAsync().Result;
```
I tried setting the scope to what I originally ask for (the commented-out line), to an empty array or to null, but the end result is the same; it doesn't work because it thinks it needs interactive auth.

**Comment by zvrba** [comment]
UPDATE: I got it working; the parameter to WithAuthority was wrong. I am testing with a user whose home tenant is different from the app's tenant, but the user is added as a guest user to the app's tenant. I was passing the user's home tenant instead of the app's tenant; passing the app's tenant works.

I pass "null" for scopes which returns two scopes, one of them being "APP-ID/.default". Let's see now whether I can use the token to access BLOB storage or database.

**Comment by jmprieur** [comment]
Thanks for the update @zvrba 
yes, if you don't pass any scope, MSAL returns a scope which is if the app itsefl; It's advised you ask for the scope for the blob storage.

Can we close this issue?

**Comment by zvrba** [comment]
Yes, thanks for your help.
