### ISSUE TITLE
DeserializeMsalV3 on ITokenCache should have option to clear in memory cache

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1109]
DeserializeMsalV3 is currently a merge operation with existing in-memory data.  We need an option to be able to clear the in memory state and then deserialize the content in.

**Comment by jennyf19** [comment]
fixed in [3.0.8](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.8)
