### ISSUE TITLE
Documentation and Sample for showcasing UI Extensibility for Linux

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1115]
### Documentation Related To Component:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1114

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ X ] needs example

### Description Of The Issue
Ensure that when we add a sample for Linux for ICustomWebUI

**Comment by bgavrilMS** [comment]
Sample [here](https://github.com/bgavrilMS/msal-interactive-netcore/blob/master/README.md), needs a review and to be moved to Azure-Samples

**Comment by henrik-me** [comment]
@bgavrilMS : Not sure exactly where it's easiest to provide feedback. Can the sample be added to an existing netcore sample app? Perhaps as a step 1 or step 2? (I believe we have one for net-core desktop already)
Also perhaps it should show more details on how to run the sample on Mac as well as Linux?

**Comment by henrik-me** [comment]
Added a few suggestions here: https://github.com/bgavrilMS/msal-interactive-netcore/pull/1

**Comment by jmprieur** [comment]
@bgavrilMS @henrik-me 
I would propose to add this part of the Desktop incremental tutorial. what do you think?

**Comment by bgavrilMS** [comment]
Sounds good, although in 4.1 we will have UI on Linux via System Browser.

**Comment by bgavrilMS** [comment]
This is documented here (feel free to review) https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Using-the-System-Browser

**Comment by bgavrilMS** [comment]
Also https://aka.ms/msal-net-os-browser
