### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by ZaZiiZu** [AzureAD/microsoft-authentication-library-for-dotnet#1116]
**Which Version of MSAL are you using ?**
MSAL 2.7.1

**Platform**
net4.5+

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

**Is this a new or existing app?**
The app is in development, but I haven't upgraded MSAL.
Bug just appeared recently (yesterday?), and also happens on much older revisions of my app.

**Repro**
Using the MSAL to manually log in sometimes, like 50/50 chance, drops the "Script Error" message on me.

**Possible Solution**
I've seen read about a similar issue here, and as I suspected, the problem is most likely with the cnd-provided javascript that's being accessed here.

**Additional context/ Logs / Screenshots**
![image](https://user-images.githubusercontent.com/38053200/56814740-1883d780-6840-11e9-9cd3-0abe827daada.png)

The error-code mentions the "getCurrentView"-property of an undefined or null-reference.

**Comment by bgavrilMS** [comment]
Acknowledged, I started seeing this as well today. Note that MSAL itself is not responsible for the web content, it is only hosting the browser (i.e. the problem will not go away if you use a different MSAL version). This is an AAD service issue. I will raise an incident with the service and update the thread.

**Comment by bgavrilMS** [comment]
Are you using the public cloud or a national sovereign cloud? (if you don;t know, it's probably public)

**Comment by ZaZiiZu** [comment]
AAD service? Alright, got it. Thanks for forwarding the issue.

I'm probably using the public cloud, since sovereign cloud doesn't ring a bell - even after googl'ing it.

**Comment by bgavrilMS** [comment]
Hi @ZaZiiZu - I have engaged with the service team and they have acknowledged the incident. Thank you for reporting this!

The product team is looking at this. It looks like if you press "Yes"  (i.e. continue to run scripts on the page), the authentication succeeds, so at least there is a workaround. The service team is looking at this as a high priority problem.

**Comment by clintoncherry** [comment]
Am also getting this issue using MSAL with WPF client. Has there been any update?

**Comment by bgavrilMS** [comment]
Current ETA for fix is end of this week.

**Comment by bgavrilMS** [comment]
Service team has updated me that the fix has been rolled out. Thx again for reporting.
