### ISSUE TITLE
Non-isolated signout for apps sharing the token cache 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1119]
**Which Version of MSAL are you using ?**
3.0.7

**Platform**
all

**What authentication flow has the issue?**
RemoveAccount

**Repro**

1. Configure a few apps to share the same token cache
2. Login with the same account into several of them
3. Logout from one of them via `RemoveAccount`
4. Call `GetAccounts` from other apps

**Expected behavior**
GetAccounts should return the account so that the other apps can acquire a token silently

**Actual behavior**
GetAccounts returns 0 accounts

Note: To achieve the expected behavior we'd need to not delete account metadata (email, names), which potentially needs a privacy review. I propose we close this as a "known issue" since there is no advantage for apps to share the token cache. This does not affect FOCI.

**Comment by jmprieur** [comment]
Closing this issue as it's being discussed by the bigger team.
