### ISSUE TITLE
Fundamentals: Cancellation is not verified sufficiently

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1120]
**Which Version of MSAL are you using ?**
3.0.7

**Platform**
all

1. Configure an acquire token (pca or cca) with a cancellation token

```csharp
 .ExecuteAsync(cancellationToken)
```

2. During execution, from another thread, invoke cancellation

```csharp
cancellationToken.Cancel();
```

**Actual**: most of the time, cancellation is not obeyed (especially on non-interactive flows)

**Expected**: we should not make network calls when cancellation is requested, we should not write to the cache, we should propagate the cancellation token to all cancellable operations, except if they produce side effects (like writing to the cache)

The docs should also be more on the fact that cancellation is not guaranteed.

**Comment by jmprieur** [comment]
@bgavrilMS : How would you suggest we move this forward?
any recommendation of which docs to change? (All the ExecuteAsync with cancellation token? new article?

**Comment by jmprieur** [comment]
@henrik-me proposing to act on the case by case basis based on feedback. I don't think that we are ever going to do a non-specific task like this one.

**Comment by henrik-me** [comment]
@jmprieur : agree
