### ISSUE TITLE
Internal symbol publishing (symchk) not working for MSAL/Extension bits

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1127]
**Which Version of MSAL are you using ?**
MSAL 3.0.8

**Platform**
net45, netcore

VS needs symbols verifiable by symchk for watson and post mortem analysis.  We publish the symbols in Azure DevOps but for some reason they're not propagating to the symbol servers in the right way for VS symchk process to pick them up.  Lee Culver has been helping us out and we need to follow up with him to get this resolved for current and future publishes of the MSAL/ADAL and extensions releases.

**Comment by MarkZuber** [comment]
Sent email to monica rosellini and lee culver (and a few others) today to get further details.   It sounds like this might require some type of corpnet activity (dropping the binaries/symbols on a share somewhere for the process to work for VS symbol archiving).  Will ping back to this task once we get responses on next steps.

**Comment by bgavrilMS** [comment]
We publish symbols on NuGet which should be enough.

The process to publish and index symbols for VS is not compatible with hosted build agents because it requires a connection to corpnet. MSAL needs to be built and signed on hosted agents for security purposes.
