### ISSUE TITLE
B2C + validateAuthority should fail gracefully

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1130]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
3.0.8

**Platform**
all

**What authentication flow has the issue?**
b2c

**Repro**

See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/669

```csharp
var pca = ... 
.WithAuthority("https://mytenant.b2clogin.com/tfp/mytenant.onmicrosoft.com/b2c_1_signupin")
```

**Expected**
This call should fail gracefully because it sets validate authority to true

**Actual**
Obscure server error AADSTS50049 Unknown or invalid instance (see customer bug)

**Comment by jennyf19** [comment]
@bgavrilMS Actually, I think it fails with this error "An error response was returned by the OAuth2 server, but it could not be parsed. Please inspect the exception properties for details." We shouldn't be getting any more STS errors w/B2C.

**Comment by bgavrilMS** [comment]
We fixed this a while back
