### ISSUE TITLE
README still references that we're in Preview for MSAL

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1131]
### Documentation Related To Component:
README

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x ] error(s) in example
- [ ] needs example

### Description Of The Issue
README still references that we're in preview.  need to update wording now that we've reached GA.

Important Note about the MSAL Preview
This library is suitable for use in a production environment. We provide the same production level support for this library as we do our current production libraries. During the preview we may make changes to the API, internal cache format, and other mechanisms of this library, which you will be required to take along with bug fixes or feature improvements. This may impact your application. For instance, a change to the cache format may impact your users, such as requiring them to sign in again. An API change may require you to update your code. When we provide the General Availability release we will require you to update to the General Availability version within six months, as applications written using a preview version of library may no longer work.

**Comment by jmprieur** [comment]
Thanks for the heads-up, @MarkZuber 
I've proposed changes.
