### ISSUE TITLE
MSAL Exception after upgrading from msal 2.7.1 to 3.0.8: Returned state from authorize endpoint is not the same as the one sent

### ISSUE THREAD

**Issue by mehamm** [AzureAD/microsoft-authentication-library-for-dotnet#1133]
Version: MSAL 3.0.8

Platform: Xamarin.IOS

**What authentication flow has the issue?**
* Mobile
    * [x] Interactive

This is a new app or experiment

Upgraded to MSAL 3.0.8 from MSAL 2.7.1.  Authentication was working prior to this upgrade and is working on the xamarin.android version of this app but not on the xamarin.ios version.

Setup 
IPublicClientApplication PCA = PublicClientApplicationBuilder
                .Create(App.ClientID)
                .WithIosKeychainSecurityGroup("com.mykeychaingroup.testapp")
                .WithB2CAuthority(App.Authority)
                .Build();

I receive MSAL Exception: "Returned state {XXXX...} from authorize endpoint is not the same as the one sent {YYYY...}" when making the following call:
AuthenticationResult ar = await PCA.AcquireTokenInteractive(App.Scopes)
                        .WithParentActivityOrWindow(this)
                        .ExecuteAsync();

**Comment by jmprieur** [comment]
@mehamm : do you have a correlation ID that you could share? (member of the exception, or in the body)

**Comment by mehamm** [comment]
Ok, I've figured out!

I had two places in my app where I was calling for authentication.  When I edited that app to convert to MSAL 3.0.8, I had configured one call correctly using .WithB2CAuthority and the other call was missing this.  The problem was on my end.  See below:

Correct configuration:
IPublicClientApplication PCA = PublicClientApplicationBuilder
.Create(App.ClientID)
.WithIosKeychainSecurityGroup("com.mykeychaingroup.testapp")
.WithB2CAuthority(App.Authority)
.Build();

Incorrect configuration:
IPublicClientApplication PCA = PublicClientApplicationBuilder
.Create(App.ClientID)
.WithIosKeychainSecurityGroup("com.mykeychaingroup.testapp")
.Build();

This issue has been resolved.

Thanks for your quick response.

**Comment by bgavrilMS** [comment]
This might be a threading issue. Whenever we make a call to AAD to request an authorization code, we add a parameter called "State" to the request. When AAD responds with a code, it adds this "State" parameter back. This is a security measure. 

Somehow, the state parameter that was received is wrong. I think what happened is that 2 authentication requests were made and the responses got mixed up. 


1. How often do you get this error
2. Can you confirm if are making multiple requests at the same time
3. Can you post or send some logs https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by mehamm** [comment]
Ok, I've figured out!

I had two places in my app where I was calling for authentication. When I edited that app to convert to MSAL 3.0.8, I had configured one call correctly using .WithB2CAuthority and the other call was missing this. The problem was on my end. See below:

Correct configuration:
IPublicClientApplication PCA = PublicClientApplicationBuilder
.Create(App.ClientID)
.WithIosKeychainSecurityGroup("com.mykeychaingroup.testapp")
.WithB2CAuthority(App.Authority)
.Build();

Incorrect configuration:
IPublicClientApplication PCA = PublicClientApplicationBuilder
.Create(App.ClientID)
.WithIosKeychainSecurityGroup("com.mykeychaingroup.testapp")
.Build();

This issue has been resolved.

Thanks for your quick response.

**Comment by bgavrilMS** [comment]
Got it, so you were creating 2 PCAs and you were issuing requests at the same time. The iOS view controller that was intercepting the result was getting confused. This is a good troubleshooting script, thanks for posting!

**Comment by mehamm** [comment]
That's exactly it.  I made a call in AppDelegate and then again in my Main View.

Hope this helps anyone that may do the same thing.

**Comment by xuehong-geng** [comment]
I have had the same problem when I do sign-in in the OnAppear. In iOS, after signed in, the focuse move back to the page where the original request send from and the OnAppear was called again. That caused second sign-in request be send out before the first one complete.
Using inter-threading locking to prevent re-enter sign-in will fix this problem.
The android is correct because the focuse move back to the original page after sign-in completed somehow.

**Comment by Depechie** [comment]
@xuehong-geng can you show some code example? I have the same problem with trying to sign in in OnAppearing on iOS
