### ISSUE TITLE
Incomplete example Client-credential-flows

### ISSUE THREAD

**Issue by PeterSkov88** [AzureAD/microsoft-authentication-library-for-dotnet#1135]
### Documentation Related To Component:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ X] error(s) in example
- [ ] needs example

### Description Of The Issue
To get the username/password example on the page i had to add 
.WithAuthority(authority) where the authority was https://login.microsoftonline.com/<my organisations unique host>. 
If I did not do this I got the following error:

"AADSTS700016: Application with identifier '<my client id>' was not found in the directory 'microsoft.com'. ...

Might be good to explain how to fins the <organisation unique host> part as well.

**Comment by jmprieur** [comment]
Thanks @peterhee 
I've added `WithTenantId` calls.

Feel free to reopen if that's not what you meant.
