### ISSUE TITLE
Typo in example and better explain authority/scope

### ISSUE THREAD

**Issue by PeterSkov88** [AzureAD/microsoft-authentication-library-for-dotnet#1136]
### Documentation Related To Component:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication
### Please check those that apply

- [ X] typo
- [ ] documentation doesn't exist
- [ X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
In the example you write (multiple times): 
PublicClientApplicationBuild.Create(clientId)
It should be:
PublicClientApplicationBuilder.Create(clientId)

Might also explain how I find my authority-url if it is possible somewhere in the Azure Portal.

**Comment by bgavrilMS** [comment]
Thanks @PeterSkov88 I have updated the docs!

As for the authority, I don't think this is available in the portal. There are some overloads of .WithAuthority that you can use that make discovery easy. Also some docs on our wiki: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#authority-instance--audience
