### ISSUE TITLE
TeamId missing in Keychain Access Group for default configuration

### ISSUE THREAD

**Issue by arek-avanade** [AzureAD/microsoft-authentication-library-for-dotnet#1137]
**Which Version of MSAL are you using ?**
MSAL 3.0.8

**Platform**
xamarin iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password (tested on this one but applies to all mobile flows)
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
New app

**Repro**
When acquiring token on iOS, there is an error saying: 

> The application does not have keychain access groups enabled in the Entitlements.plist. As a result, there was a failure to save to the iOS keychain. The keychain access group 'com.xxx.yyy' is not enabled in the Entitlements.plist. See https://aka.ms/msal-net-enable-keychain-groups for more details on enabling keychain access groups and entitlements.

When adding this group (based on bundle ID), Visual Studio automatically adds TeamId prefix, however MSAL doesn't add TeamId prefix in this case, only if custom keychain group id is provided when configuring PublicClientApplication.

**Expected behavior**
Should add TeamId always.

**Actual behavior**
Doesn't add TeamId in default configuration,.

**Possible Solution**
Fixing iOSTokenCacheAccessor.SetiOSKeychainSecurityGroup method to always include TeamId.

**Additional context/ Logs / Screenshots**
None

**Comment by trwalke** [comment]
Hi @arek-avanade This is a known issue and will be resolved soon. in the meantime, please use WithIosKeychainSecurityGroup() as it will automatically append the keychain access group to the team ID

**Comment by arek-avanade** [comment]
@trwalke Ok, good to know. Shall we keep this open or close it in that case?

**Comment by bgavrilMS** [comment]
@arek-avanade - I marked this issue as resolved via a tag. When we release, we will close it.

**Comment by jennyf19** [comment]
@arek-avanade  Fixed in [MSAL 4.0.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.0.0)
