### ISSUE TITLE
JsonWebToken is not set on .NET Core

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1139]
MSAL does not handle the X509 cert on NET_CORE...only NETSTANDARD & DESKTOP...since this is a conf client flow, should be on net core.

Error coming back from ests was:
{"error":"invalid_client","error_description":"AADSTS700027: Client assertion contains an invalid signature. [Reason - The key was not found., Please visit 'https://developer.microsoft.com/en-us/graph/graph-explorer' and query for 'https://graph.microsoft.com/beta/applications/5.....6f845d' to see configured keys]

**Comment by henrik-me** [comment]
removing Fixed label. Really should improve for other platforms and ensure we have the right level of tests

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1151

**Comment by jennyf19** [comment]
Fixed in [MSAL 4.0.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.0.0)
