### ISSUE TITLE
MsalServiceException: AADB2C90159

### ISSUE THREAD

**Issue by Skirtek** [AzureAD/microsoft-authentication-library-for-dotnet#1143]
Version: MSAL 2.7.1
Platform: Xamarin Forms

What authentication flow has the issue?
Registration account in app with usage of authentication in AD B2C to get token

Please check those that apply

- [ ]   typo
- [ ]   documentation doesn't exist
- [x]   documentation needs clarification
- [ ]   needs example

Description Of The Issue
Getting Microsoft.Identity.Client.MsalServiceException: AADB2C90159: A self-asserted verification request has failed with reason 'Failed to send verification request'. Correlation ID: 1191eb0a-7522-4aa7-b98b-275f775d3d9b

Thus, the user can not be verified and register into app.
Again, error code is not described in docs. Therefore, it is difficult to investigate a solution to the problem

**Comment by jennyf19** [comment]
@Skirtek Is this with a custom policy?

**Comment by Skirtek** [comment]
@jennyf19 Yes, it is custom policy with custom UI.

**Comment by jennyf19** [comment]
@Skirtek Based on the B2C logs, it looks like the client is offline or it, for some reason, cannot reach the server. The error message is not helpful at all. B2C has it on their backlog to improve it. 

Is the error intermittent? It shouldn't be happening too frequently.

**Comment by Skirtek** [comment]
Thank you for this explanation. It sounds very convincing! :) That's right, the error occurred only once for one user.

**Comment by jennyf19** [comment]
@Skirtek closing as external. thanks.
