### ISSUE TITLE
AcquireTokenSilent should not make calls to the network

### ISSUE THREAD

**Issue by stanboerekamp** [AzureAD/microsoft-authentication-library-for-dotnet#1144]
**Which Version of MSAL are you using ?**
MSAL 3.0.8

**Platform**
xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Repro**
Execute this method when no internet connection is available.
```csharp
var authResult = await _application.AcquireTokenSilent(Scopes, firstAccount).ExecuteAsync();
```

**Expected behavior**
Return Authresult/Token from cache, like iOS.

**Actual behavior**
Application throws: Java.Net.UnknownHostException
```{Java.Net.UnknownHostException: Unable to resolve host "login.microsoftonline.com": No address associated with hostname ---> Java.Lang.RuntimeException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)    --- End of inner exception s…}```

**Possible Solution**
.

**Additional context/ Logs / Screenshots**
I use the following code to check for an existing account:
```csharp
var accounts = await _application.GetAccountsAsync();
var firstAccount = accounts.FirstOrDefault();
```
This returns the existing account like expected.
The scopes are also always set.

**Comment by bgavrilMS** [comment]
I think you are offline. In some cases, GetAccountsAsync needs to make a network call.

**Comment by stanboerekamp** [comment]
This only occurs when I am offline. There are no problems when online, but I still want my app to function offline.
GetAccountsAsync works just fine offline and does not throw the exception, AcquireTokenSilent does.

Executing AcquireTokenSilent when offline on iOS returns the AuthResult from cache like expected.

**Comment by bgavrilMS** [comment]
I don't think this ever worked, as we need to make some discovery calls in order to validate the authority. May I ask what is your scenario ?

**Comment by stanboerekamp** [comment]
This used to work in 2.7.1 and not throw a native exception. This code executes in a Core project (.net standard 2.0 shared code).

The scenario:
My app needs to function offline as well as online, so I use some kind of caching implementation for caching users. The app caches data using a GUID as a key, and I use IAccount.HomeAccountId.ObjectId for the GUID of the logged in user. I can make a workaround and not make a call when no internet is available, and just use the FirstOrDefault account from GetAccountsAsync, but I would have to make this change for it to work on Android only.

The problem is the native Java.Net.UnknownHostException in my core project. I can't check the type of the exception without adding a reference to Mono.Android.dll (which i don't want to do).

**Comment by jmprieur** [comment]
@bgavrilMS : I would think it's fixed as well?

**Comment by bgavrilMS** [comment]
Yes, we might need something to track the work of storing instance metadta in the token cache, but we can talk about that later.

**Comment by BurkusCat** [comment]
Hi @bgavrilMS, I am seeing this error in a production version of our app sometimes in Microsoft.Identity.Client 4.34.0. It seems to be causing crashes for a few hundred users. The vast majority of reports are Android 9, 10, 11 but most of our users fall within this bracket so it makes sense most of the crashes are on those versions.

``` java
libcore.io.ForwardingOs.android_getaddrinfo
ForwardingOs.java, line 74
Java.Lang.RuntimeException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
O
```

``` csharp
JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
HttpsURLConnectionInvoker.Connect ()
AndroidClientHandler+<>c__DisplayClass44_0.<ConnectAsync>b__0 ()
Task.InnerInvoke ()
Task.Execute ()
AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState)
AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts)
HttpManager.ExecuteAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, System.Net.Http.HttpMethod method, Microsoft.Identity.Client.Core.ICoreLogger logger, System.Threading.CancellationToken cancellationToken)
HttpManager.ExecuteWithRetryAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, System.Net.Http.HttpMethod method, Microsoft.Identity.Client.Core.ICoreLogger logger, System.Boolean doNotThrow, System.Boolean retry, System.Threading.CancellationToken cancellationToken)
HttpManager.SendPostAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, Microsoft.Identity.Client.Core.ICoreLogger logger, System.Threading.CancellationToken cancellationToken)
HttpManager.SendPostAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Collections.Generic.IDictionary`2[TKey,TValue] bodyParameters, Microsoft.Identity.Client.Core.ICoreLogger logger, System.Threading.CancellationToken cancellationToken)
OAuth2Client.ExecuteRequestAsync[T] (System.Uri endPoint, System.Net.Http.HttpMethod method, Microsoft.Identity.Client.Internal.RequestContext requestContext, System.Boolean expectErrorsOn200OK, System.Boolean addCommonHeaders)
OAuth2Client.GetTokenAsync (System.Uri endPoint, Microsoft.Identity.Client.Internal.RequestContext requestContext, System.Boolean addCommonHeaders)
TokenClient.SendHttpAndClearTelemetryAsync (System.String tokenEndpoint, Microsoft.Identity.Client.Core.ICoreLogger logger)
TokenClient.SendTokenRequestAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] additionalBodyParameters, System.String scopeOverride, System.String tokenEndpointOverride, System.Threading.CancellationToken cancellationToken)
SilentRequestHelper.RefreshAccessTokenAsync (Microsoft.Identity.Client.Cache.Items.MsalRefreshTokenCacheItem msalRefreshTokenItem, Microsoft.Identity.Client.Internal.Requests.RequestBase request, Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters authenticationRequestParameters, System.Threading.CancellationToken cancellationToken)
CacheSilentStrategy.RefreshRtOrFailAsync (System.Threading.CancellationToken cancellationToken)
CacheSilentStrategy.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
SilentRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken)
ClientApplicationBaseExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenSilentParameters silentParameters, System.Threading.CancellationToken cancellationToken)
```
