### ISSUE TITLE
Issue after updating the package to 3.0.8 in Xamarin 

### ISSUE THREAD

**Issue by soooraj** [AzureAD/microsoft-authentication-library-for-dotnet#1145]
![image](https://user-images.githubusercontent.com/47883772/57619832-38790200-7587-11e9-9831-e561641189a4.png)

After updating the Microsoft.Identity.Client to 3.0.8. I am getting a pre populated text in the login page ("missing+from+the+token+response) . Attaching the image for your reference.

**Comment by jennyf19** [comment]
@soooraj when are you seeing this login page? has a user already signed in previously? Just w/iOS?

**Comment by soooraj** [comment]
I can see this during fresh login. The issue is there in both Android and iOS;

**Comment by jennyf19** [comment]
@soooraj which version did you update from? v2.x to 3.0.8 or v3.x to 3.0.8? 
By "fresh login", do you mean the app was uninstalled, then updated and then reinstalled on the device?

Thanks.

**Comment by soooraj** [comment]
It was 3.x to 3.0.8. I updated the code based on the official sample

**Comment by jennyf19** [comment]
@soooraj thanks. and which sample are you using?

**Comment by soooraj** [comment]
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

**Comment by jennyf19** [comment]
@soooraj I tried w/the latest version of MSAL (4.0) w/the sample and did not repro what you saw. Would you mind trying it out again? The sample is updated to 4.0 currently.

**Comment by jennyf19** [comment]
@soooraj any update on this? I'm not able to repro.

**Comment by henrik-me** [comment]
@soooraj : Closing. Please re-open if you have additional information
