### ISSUE TITLE
MSAL is unable to find refresh token for ADFS 2019 account

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1147]
Which Version of MSAL are you using ?
3.0.8

Platform
net45

What authentication flow has the issue?
Silent authentication

Repro
Make an interactive acquire token call for an ADFS 2019 account.
make a silent call for a different resource or set force refresh to true.

Expected behavior
MSAL should find a refresh token in the cache acquire a new access token by refreshing the refresh token.

Actual behavior
The cache does not find the refresh token.

**Comment by jennyf19** [comment]
Fixed in [MSAL 4.0.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.0.0)
