### ISSUE TITLE
Missing sendx5c flag in AcquireTokenSilentAsync

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1149]
Reported issue for ADAL which needs addressing in MSAL to enable move to MSAL: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1568

**Which Version of ADAL are you using ?**
3.19.8

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
Web App OBO

**Is this a new or existing app?**
The app is in production, uses the same version of ADAL, but started seeing this issue

**Expected behavior**
Given that we can send the x5c via AcquireTokenAsync using a IClientAssertionCertificate overload, I would expect to be able to do the same with AcquireTokenSilentAsync, but this is not currently the case.

**Actual behavior**
The sendx5c flag is not available in any overload of AcquireTokenSilentAsync.

**Possible Solution**
Add the sendx5c flag to IClientAssertionCertificate overload of AcquireTokenSilentAsync

**Comment by jennyf19** [comment]
Fixed in [MSAL 4.0.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.0.0)
