### ISSUE TITLE
.Net Native tool chain build error

### ISSUE THREAD

**Issue by JoelMendoza** [AzureAD/microsoft-authentication-library-for-dotnet#1153]
Greetings,
Any assistance with the behavior below would be greatly appreciated:

**Version:**
- Microsoft.Identity.Client -Version 3.0.8

**Platform:**
- UWP, Visual Studio 2019

**What authentication flow has the issue?**
*Other? - please describe;
- When building the solution for release (with .Net Native tool chain checked), the build fails with the following errors:

Type 'Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform' was not included in compilation, but was referenced in method 'MicrosoftGraphAuthenticationHelper.GetUserTokenAsync(string, string, PromptBehavior)'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.

Type 'Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform' was not included in compilation, but was referenced in method 'MicrosoftGraphAuthenticationHelper.<GetUserTokenAsync>d__31.MoveNext()'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.

Method 'MicrosoftGraphAuthenticationHelper.<GetUserTokenAsync>d__31.MoveNext()' will always throw an exception due to the missing method 'PlatformParameters..ctor(PromptBehavior, bool)' in assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.

**Is this a new or existing app?**
- This is a new application

**Expected behavior**
- For the application to build in release mode and be able to package it for Windows Store upload.

**Actual behavior**
- The release build fails with the errors above.

**Possible Solution**
**Additional context/ Logs / Screenshots**

**Comment by bgavrilMS** [comment]
Microsoft.IdentityModel.Clients.ActiveDirectory is a namespace from ADAL (our legacy SDK). But you seem to be using MSAL. 

Where does `MicrosoftGraphAuthenticationHelper.GetUserTokenAsync` come from ? PromptBehavior is an ADAL object.

**Comment by JoelMendoza** [comment]
Thanks for your quick reply, I did a search and this is what turned up (attached screenshot).  I did confirm that I have `Microsoft.Toolkit.Uwp.Controls.Graph` referenced in my project.  And `Microsoft.Toolkit.Services` is a dependency of `Microsoft.Toolkit.Uwp.Services`.

![MicrosoftGraphAuthenticationHelper GetUserTokenAsync](https://user-images.githubusercontent.com/2185838/57865715-19b77d00-77cc-11e9-9cff-8bcf2f6777fe.jpg)

**Comment by JoelMendoza** [comment]
Thanks for helping me look more closely into this, it turns out that I am not using these packages, removed them and the release build was successful.  It looks like these packages need to be updated to use MSAL instead of ADAL.  I'll contact the respective teams for them to take a look.

**Comment by bgavrilMS** [comment]
Cool, thanks Joel!
