### ISSUE TITLE
iOS acquiretokensilent test failing due to test app UI

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1154]
**Which Version of MSAL are you using ?**
3.0.8

**Platform**
xamarin iOS

**What authentication flow has the issue?**
silent auth

**Is this a new or existing app?**
xamarin ios test app

**Repro**
run appcenter test with acquire token silent test enabled for iOS

**Expected behavior**
app should acquire a token for one resource to get a multi resource refresh token.
The app should then acquire a token for a different resource and receive a second access token

**Actual behavior**
Error is thrown saying "User was not selected"

**Possible Solution**

**Additional context/ Logs / Screenshots**
[LOG.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/3189177/LOG.txt)
![Screenshot_1](https://user-images.githubusercontent.com/30090357/57890412-74f96780-77ec-11e9-9216-00e2aada9508.png)

**Comment by jmprieur** [comment]
@trwalke is this issue fixed now? if yes, you might want to close it?

**Comment by trwalke** [comment]
@jmprieur no, not fixed yet.

**Comment by jmprieur** [comment]
@trwalke: isn't it highest priority to fix the failing test, than doing the new feature work?

**Comment by jmprieur** [comment]
this is now fixed and available in MSAL.NET 4.1
