### ISSUE TITLE
Coding Style: method overload parameter ordering convention

### ISSUE THREAD

**Issue by rayluo** [AzureAD/microsoft-authentication-library-for-dotnet#117]
The current [2 PublicClientApplication constructors](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/1.0.304142221/src/MSAL.PCL/PublicClientApplication.cs#L53-L62) contain one or two parameters but they are in different order: PublicClientApplication(string clientId) and PublicClientApplication(string authority, string clientId). The general practice is to [be consistent in the ordering of parameters in overloaded members](http://stackoverflow.com/a/14841274/728675).

Same issue also exists in [ConfidentialClientApplication constructors](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/1.0.304142221/src/MSAL.PCL/ConfidentialClientApplication.cs#L57-L70).

**Comment by kpanwar** [comment]
fixed.
