### ISSUE TITLE
Clarification needed for 'on behalf of' pages

### ISSUE THREAD

**Issue by filipliwinski** [AzureAD/microsoft-authentication-library-for-dotnet#1171]
### Documentation Related To Component:
on behalf of

### Please check those that apply

- [x] documentation needs clarification

### Description Of The Issue
There are two versions of *on behalf of* page in wiki:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of-2.x

Both of them have the same caption:

> This page is for MSAL **2.x**
>  If you are interested in MSAL **3.x**, please see on behalf of 2.x

For the first one should be:

> This page is for MSAL **3.x**
>  If you are interested in MSAL **2.x**, please see on behalf

**Comment by jmprieur** [comment]
Thanks for catching this, @filipliwinski 
this is fixed.
I let you close the issue when you have verified it?
