### ISSUE TITLE
API naming for client credentials flow

### ISSUE THREAD

**Issue by dstrockis** [AzureAD/microsoft-authentication-library-for-dotnet#118]
API feedback: I was trying to do the client credentials flow, and it wasn't obvious to me that `AcquireTokenForClient` was the method I was supposed to use.
I tried to use `AcquireTokenSilentAsync` for quite a while, since that was the old pattern
Had to look at the source code to figure it out
Side comment: it should probably have `...Async` appended as well

**Comment by kpanwar** [comment]
fixed.
