### ISSUE TITLE
Update AcquireTokenSilent api to handle single accounts

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1180]
The acquireTokenSilent API currently has 2 overloads:
acquireTokenSilent(scopes, account)
acquireTokenSilent(scopes, loginHint)

These two methods require that you provide details of the desired account in order for the cache to find the correct AT/RT. However, there are scenarios where the application will only ever have a single account(mobile scenarios for example). In these scenarios, it shouldn't be necessary to acquire the account from the PCA or CCA just to pass it into this api. If there is only one account in the cache, the user should have a way to easily acquire a token silently without needing to pass in details of the account.

**Describe the solution you'd like**
Introduction of a new method acquireTokenSilentWithSingleAccount(scopes) to simply the code for single user applications.

The current methods will remain AcquireTokenSilent(scopes, account)
and AcquireTokenSilent(scopes, loginHint) respectively, but their XML comment with reference the new method.

For single account applications, instead of:

```csharp
var accounts = await app.GetAccountsAsync();
var account = accounts.FirstOrDefault()
try
{
 result = app.AcquireTokenSilent(scopes, acccount);
...
```

the code will look like:

```csharp
try
{
 result = app.AcquireTokenSilentWithSingleAccount(scopes);
}
catch(MsalClientException ex) when ex.ErrorCode == MsalError.AmbigiousAccount)
{
 // This is a developer mistake, the application was not really single account ...
}
...
```

**Comment by jmprieur** [comment]
@trwalke : we should not change the name/signature of the existing methods (we don't want to break the existing applications, just make it easier to use MSAL.NET in the single account case

adding @shoatman for his feedback as yesterday he pinged me about work in progress on the mobile platforms with which we should probably align

**Comment by jmprieur** [comment]
@trwalke : I've updated the description of the issue. Please check.

**Comment by henrik-me** [comment]
@jmprieur : Shouldn't we just close this instead?

**Comment by jmprieur** [comment]
@henrik-me : yes, I agree
