### ISSUE TITLE
Add .WithDefaultRedirectUri() method to the PublicClientApplicationBuilder to simplify's developer's life

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1186]
**Is your feature request related to a problem? Please describe.**

1. Currently on Desktop applications, MSAL.NET uses the `urn:ietf:wg:oauth:2.0:oob` per default as a Redirect URI. However, the recommendation is now to use `https://login.microsoftonline.com/common/oauth2/nativeclient` for desktop applications. We could update all the samples to change the app registration and add a call to `.WithRedirectUri("https://login.microsoftonline.com/common/oauth2/nativeclient")`:

  ```CSharp
  PublicClientApplicationBuilder.Create(appID)
  .WithRedirectUri("https://login.microsoftonline.com/common/oauth2/nativeclient")
  .Build();
  ```
  but how are developers going to remember this URI?

2. We want to provide a better experience in UWP applications by enabling SSO with the browser. This supposes to use a URI which value is WebAuthenticationBroker.GetCurrentApplicationCallbackUri(). Again difficult to remembers, and we'd probably not want app developers to have to call this in their code (See #1093)

3. In the case of .NET Core applications which want to do interactive, using a RedirectUri of "http://localhost" enables MSAL.NET to choose a port to serve the interactive authentication rendered by the system browser.

**Describe the solution you'd like**

We want to provide a new API on `PublicClientApplicationBuilder`
```CSharp
var app = PublicClientApplicationBuilder.Create(clientId)
.WithDefaultRedirectUri()
.Build();
```

The default URI would be:

Platform  | Redirect URI  
---------  | --------------
desktop app (.NET FW) | `https://login.microsoftonline.com/common/oauth2/nativeclient` 
UWP | value of `WebAuthenticationBroker.GetCurrentApplicationCallbackUri()`
.NET Core | `https://localhost`

Once the application is built the default URI should be accessible through app.[Config]{).[RedirectUri](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.iappconfig.redirecturi?view=azure-dotnet#Microsoft_Identity_Client_IAppConfig_RedirectUri)

**Describe alternatives you've considered**
- Offering constants (but would not apply to UWP

**Additional context**
In addition to the dev and test work:
- the XML comment of [ApplicationOptions_RedirectUri](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.applicationoptions.redirecturi?view=azure-dotnet#Microsoft_Identity_Client_ApplicationOptions_RedirectUri) needs to be amended to specify that `.WithDefaultRedirectUri()` overrides the default
- the following samples need to be updated (code and README):
  - https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2
  - The 3 TodoListClient of https://aka.ms/msidentity-aspnetcore-webapi
  - https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop
  - https://github.com/azure-samples/active-directory-xamarin-native-v2
  - https://github.com/Azure-Samples/active-directory-b2c-xamarin-native
- the following quickstarts need to be updated (code and docs.ms doc)
  - https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-windows-desktop
  - https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-uwp
  - TodoListClient of https://github.com/azureadquickstarts/appmodelv2-nativeclient-dotnet

**Comment by jmprieur** [comment]
@jennyf19 : this is the spec for `.WithDefaultRedirectUri()`

**Comment by jennyf19** [comment]
@jmprieur Thank you.

**Comment by jmprieur** [comment]
this is now available in MSAL.NET 4.1
