### ISSUE TITLE
Add .WithClientAssertion to support client assertions

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1188]
ADAL supports ClientAssertions. We will need to support the same in MSAL.
See more:

- [ADAL FAQ](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL-.NET-Q-&-A#what-overload-of-acquiretoken-should-i-call)
- [ADAL ClientAssertion Description](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows#clientassertion-in-adalnet)

Note: This looks very similar to UserAssertion

**Describe the solution you'd like**
We should follow the new model of .With in the API
With Claims:
```csharp

Dictionary<string, string> claims = new[] 
{
 { "client_ip", ipAddres}
};

IClientAssertion clientAssertion = CreateClientAssertion(certificate, claims);
var app = ConfidentialClientApplicationBuilder.Create(clientId)
                      .WithClientAssertion(clientAssertion))
                      .Build();
```

With Signed assertion:
```csharp
string SignedAssertion = 
          string.Concat(token, ".", UrlEncodeSegment(credential.Sign(certificate, token)));

IClientAssertion clientAssertion = CreateClientAssertion(SignedAssertion);
var app = ConfidentialClientApplicationBuilder.Create(clientId)
                      .WithClientAssertion(clientAssertion))
                      .Build();
```

**Describe alternatives you've considered**
N/A

**Additional context**
We have a current ask from customers for adding this to be able to move to MSAL.

**Comment by henrik-me** [comment]
@jmprieur

**Comment by jmprieur** [comment]
@henrik-me : something like ^^

**Comment by bgavrilMS** [comment]
Shouldn't this go through an API review? 
I don't understand what the constructor with certificate and claims is supposed to do and how it is different than the .WithCertificate option.

**Comment by trwalke** [comment]
This is different from the .WithCertificate option because we allow the user to pass in their own claims to be signed by the certificate rather than signing a predefined set of claims for the authentication call.

I dont think this should go through the api review as we are simply bringing MSAL to parity with ADAL. However, it may be warranted since we are allowing the user to pass in the claims(Dictionary<string, string> claims) which is not done in ADAL.
@henrik-me thoughts on this?

**Comment by jmprieur** [comment]
@trwalke : I think we should got through API review. the shape of the API might be different from ADAL. I like @bgavrilMS's proposal actually. What about?

```csharp
Dictionary<string, string> additionalClaimsToSign = new[] 
{
 { "client_ip", ipAddres}
};

var app = ConfidentialClientApplicationBuilder.Create(clientId)
                      .WithCertificate(clientAssertion, additionalClaimsToSign)
                      .Build();
```

With custom signed assertion:

```csharp
string SignedAssertion = 
          string.Concat(token, ".", UrlEncodeSegment(credential.Sign(certificate, token)));

IClientAssertion clientAssertion = CreateClientAssertion(SignedAssertion);
var app = ConfidentialClientApplicationBuilder.Create(clientId)
                      .WithSignedClientAssertion(clientAssertion))
                      .Build();
```

**Comment by jmprieur** [comment]
this is now available in MSAL.NET 4.1

**Comment by lbaralgeen** [comment]
UrlEncodeSegment??   Where did get this function?  google does not know about it.

**Comment by trwalke** [comment]
@lbaralgeen this function is created by us. see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0d53f3e80e29f9c6d172e069c10e02d71e24f65e/src/client/Microsoft.Identity.Client/Internal/JsonWebToken.cs#L67

Have you seen this?
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Assertions
