### ISSUE TITLE
Change json serialization behavior to ignore null

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1189]
**Is your feature request related to a problem? Please describe.**
For certain older auth libraries there is an issue with null handling in json thus we should move to not adding fields which values is null. Especially important is the handling of foci_id.

**Describe the solution you'd like**
Ensure the json serializer doesn't write values to the json for which the values are null.

**Describe alternatives you've considered**
N/A

**Additional context**
https://stackoverflow.com/questions/6507889/how-to-ignore-a-property-in-class-if-null-using-json-net

**Comment by jmprieur** [comment]
@MarkZuber : I believe this is fixed?

**Comment by MarkZuber** [comment]
Yes.  It’s fixed.

________________________________

**Comment by jmprieur** [comment]
this is now fixed and available in MSAL.NET 4.1
