### ISSUE TITLE
Adjust the parameters of AcquireTokenByAuthorizationCodeAsync(...) & GetAuthorizationRequestUrlAsync(...)

### ISSUE THREAD

**Issue by rayluo** [AzureAD/microsoft-authentication-library-for-dotnet#119]
Per a CR discussion, we would like to:
- [x] change the order of [first 2 parameters here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/3c220d082f4c33037673857aee88751830e18ccd/src/MSAL.PCL/ConfidentialClientApplication.cs#L106-L107) into `code, scope`. Same applies to other overloading methods.
- [ ] Add overloading methods to support a new optional parameter `redirectUri`
- [ ] Add optional parameter `state` for [GetAuthorizationRequestUrlAsync() method](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/3c220d082f4c33037673857aee88751830e18ccd/src/MSAL.PCL/ConfidentialClientApplication.cs#L201)

**Comment by kpanwar** [comment]
@rayluo - for "Add overloading methods to support a new optional parameter redirectUrl" - which API are you referring to? Also, can you please remind me the use case for adding redirect uri as an API parameter?

**Comment by kpanwar** [comment]
@rayluo - for " Add optional parameter state for GetAuthorizationRequestUrlAsync() method" -- Why can't the developer use extraQueryParameter to pass in the state value, if needed?

**Comment by rayluo** [comment]
Q: For "Add overloading methods to support a new optional parameter redirectUri" - which API are you referring to? Also, can you please remind me the use case for adding redirect uri as an API parameter?

A: Hmm, it has been a while, but I believe we were talking about the [AcquireTokenByAuthorizationCode methods](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/3c220d082f4c33037673857aee88751830e18ccd/src/MSAL.PCL/ConfidentialClientApplication.cs#L106-L118). The [oauth2 spec indicates that it is a required field in some circumstance](https://tools.ietf.org/html/rfc6749#section-4.1.3), so it would be important enough to become a dedicate parameter.

Q: For "Add optional parameter state for GetAuthorizationRequestUrlAsync() method" -- Why can't the developer use extraQueryParameter to pass in the state value, if needed?

A: Sure, technically they could just use `extraQueryParameter` as a fallback; we may want to document the usage in this case, or can the develops simply assume the content of `extraQueryParameter` would need to follow the `foo=bar&foo=baz` convention?
On the other hand, the [oauth2 spec explicitly recommends the use of `state`](https://tools.ietf.org/html/rfc6749#section-4.1.1), so the `state` seems significant enough to justify its showing up as a dedicate parameter too.

**Comment by kpanwar** [comment]
@rayluo - Fix the bug that you assigned me. :) make sure you check with vittorio first on the API change.

**Comment by rayluo** [comment]
So to document the offline conversation about the "state" and the "redirect_uri": They are not classified as REQUIRED in the OAuth2 spec. Here in MSAL dotnet we choose to not provide explicit support in API surface.
