### ISSUE TITLE
Telemetry classes have empty XML comments

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1191]
**Which Version of MSAL are you using ?**
MSAL 4.0 rc

**Repro**
Look at the XML comments of the telemetry classes

**Expected behavior**
There is a description of the comment, possibly an aka.ms link to an article about telemetry

**Actual behavior**
They are empty

**Comment by jennyf19** [comment]
fixed in [MSAL 4.0.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.0.0)
