### ISSUE TITLE
GetAuthorizationRequestUrl ExecuteAsync with no cancellation token has bad signature

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1193]
**Which Version of MSAL are you using ?**
3.0.8

**Platform**
all Confidential CLient 

**What authentication flow has the issue?**
GetAuthorizationRequestUrl 

Other? - please describe;

**Repro**

```csharp

// This works
            Uri url = await cca.GetAuthorizationRequestUrl(scopes)
                 .ExecuteAsync(CancellationToken.None);

// This fails to compile
       Uri url = await cca.GetAuthorizationRequestUrl(scopes)
                 .ExecuteAsync();
```

**Expected behavior**
ExecuteAsync on this object should return an Uri on both overloads (ExecuteAsync() and ExecuteAsync(CancellationToken)

**Actual behavior**
ExecuteAsync() returns an AuthenticationRequest

**Comment by bgavrilMS** [comment]
@jmprieur @henrik-me - fix is trivial, propose we take it for 4.0.0 or 4.0.1

**Comment by jmprieur** [comment]
Go ahead. This is a breaking change (even if the previous one was useless)
BTW, this issue is a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1184 ?

**Comment by bgavrilMS** [comment]
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1184
