### ISSUE TITLE
Fundamentals: Ensure we have standard/cross library cache tests in the repo

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1199]
**Expected behavior**
All tests described for basic cache compat should be part of the list of unit tests.
https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=%2FUnifiedSchema%2Ftestcases&version=GBdev

All tests should be green, and the test should be clearly marked as "UnifiedSchema_Validation", ensuring we can properly report on the state of these tests.

**Comment by MarkZuber** [comment]
fixed and merged.
