### ISSUE TITLE
Duplicated lines, presumably caused by copy and paste error?

### ISSUE THREAD

**Issue by rayluo** [AzureAD/microsoft-authentication-library-for-dotnet#120]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/662a12c251811f332a14bb6ea196e23793f3bf4f/src/MSAL.PCL/ConfidentialClientApplication.cs#L181-L182

**Comment by kpanwar** [comment]
looks like it.

**Comment by kpanwar** [comment]
fixed
