### ISSUE TITLE
On Android, Embedded WebView doesn't get resized or panned when soft keyboard is overlayed

### ISSUE THREAD

**Issue by tranb3r** [AzureAD/microsoft-authentication-library-for-dotnet#1219]
**Which Version of MSAL are you using ?**
MSAL 4.0.0

**Platform**
Xamarin Forms on Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
This is a new app.

**Repro**

```csharp
await _publicClientApplication
    .AcquireTokenInteractive(Scopes)
    .WithLoginHint(email)
    .WithParentActivityOrWindow(_parentActivityOrWindow)
    .WithUseEmbeddedWebView(true) // true for embedded, false for system webview
    .ExecuteAsync();
```
On the sign-in or sign-up interactive form, tap on any of the input field (username, password...).
The soft keyboard will appear.
Depending on the webview type (embedded or system), the behavior is not the same:
- when using system webview: the form scrolls up, so that the keyboard does not hide the input field
- when using embedded webview: the page is not panned or resized, and the keyboard hides some input fields (at the bottom).

**Expected behavior**
When using embedded webview, the view should be panned or resized when the keyboard is shown.

**Actual behavior**
When the keyboard appears, it hides some of the input fields at the bottom of the view.

**Possible Solution**
No idea...

**Screenshots**
![msal](https://user-images.githubusercontent.com/12516566/59598100-b76bd800-90fb-11e9-833f-a0e04b196758.jpg)

**Comment by jennyf19** [comment]
@tranb3r Thanks for reporting this and for the screen shots and detailed repro information. Will update here when we have more information.

**Comment by tranb3r** [comment]
@jennyf19 Any progress on this issue ? Thanks :)

**Comment by jennyf19** [comment]
@tranb3r no update at the moment. thanks for the reminder.

**Comment by tranb3r** [comment]
@jennyf19 @iambmelt  Any update ? Thank you.

**Comment by jennyf19** [comment]
@tranb3r Thanks for the continued reminders on this. I tried it out this morning, and if I add this to the android manifest (and rebuild), the page gets resized:
`android:windowSoftInputMode="adjustResize|stateVisible|stateAlwaysHidden"`

Let me know if it works for you as well and is what you are looking for.

**Comment by tranb3r** [comment]
No, it does not work for me. 
But I think I've figured out why: windowSoftInputMode is not working when using windowTranslucentStatus in app theme (which is my case).
So, thanks for pointing me in the right direction. I'll figure out a way to manage it properly.

**Comment by tranb3r** [comment]
I'm closing this ticket since it's clear now that it has nothing to do with msal.

**Comment by jennyf19** [comment]
@tranb3r thanks for the update. Can you post back here when you figure it out for your app? In case others run into a similar issue? Thanks. Glad you are unblocked

**Comment by tranb3r** [comment]
The solution is quite simple: make sure to use a theme that do not set windowTranslucentStatus=true.
The tricky part is that if you need to override the application's main theme, this has to be done on the AuthenticationAgentActivity (an internal class) instead of the BrowserTabActivity:
`<activity android:name="microsoft.identity.client.platforms.android.embeddedwebview.AuthenticationAgentActivity" android:theme="@style/MsalTheme" />`

Hope it helps !

**Comment by jmprieur** [comment]
Thanks @tranb3r : is it something that we should set in MSAL itself (if at all possible)

**Comment by tranb3r** [comment]
> Thanks @tranb3r : is it something that we should set in MSAL itself (if at all possible)

@jmprieur Are you thinking of a better solution ?
Since the faulty behavior is caused by the app's theme, I'm not sure if there's any other solution than overriding the theme for msal's activity...

What bothers me is that AuthenticationAgentActivity is an internal class, which means I should not have to touch it.
But for some reason, modifying BrowserTabActivity's theme has no effect at all... the override has to be done on AuthenticationAgentActivity.
