### ISSUE TITLE
`TokenCache.SerializeAdalV3` returns `null` even with a populated in-memory cache

### ISSUE THREAD

**Issue by mjcheetham** [AzureAD/microsoft-authentication-library-for-dotnet#1222]
**Which Version of MSAL are you using ?**
MSAL 4.0.0

**Platform**
.NET Framework 4.6.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

**Is this a new or existing app?**
The app is in pre-production, we want to move from ADAL to MSAL, but this issue would prevent us from doing so.

**Repro**

```csharp
public static void Main(string[] args)
{
  var pca = PublicClientApplicationBuilder
            .Create("872cd9fa-d31f-45e0-9eab-6e460a02d1f1")
            .Build();
  pca.UserTokenCache.SetAfterAccess(OnAfterAccess);

  var scopes = new[] { "499b84ac-1321-427f-aa17-267ca6975798/.default" };
  var result = pca.AcquireTokenInteractive(scopes)
    .ExecuteAsync()
    .Result;

  string at = result.AccessToken;
  Debug.Assert(at != null, "Access token should not be null");
}

private static void OnAfterAccess(TokenCacheNotificationArgs args)
{
  var adalData = args.TokenCache.SerializeAdalV3();
  Debug.Assert(adalData != null, "ADAL data should not be null"); // FAILURE
  File.WriteAllBytes("C:\adal.cache", adalData);

  var msalData = args.TokenCache.SerializeMsalV3();
  Debug.Assert(msalData != null, "MSAL data should not be null");
  File.WriteAllBytes("C:\msal.cache", msalData);
}
```

**Expected behavior**
Both the ADAL and MSAL bytes are not `null`.

**Actual behavior**
The ADAL bytes are `null`.

**Additional context / Logs / Screenshots**
Git Credential Manager wants to move to MSAL, and part of that means we need to be able to read and write to older ADAL v3 cache files. We will not be able to make the transition to MSAL if we are unable to write ADAL v3 caches.

**Comment by bgavrilMS** [comment]
This is a Family client ID and so the RT that is retrieved is a family RT. MSAL will not serialize it in the ADALv3 format, because ADAL does not know about FOCI (Family of client ID). 

I can add a small fix for MSAL to write an normal RT back to the ADAL cache though, but not sure if it makes any difference.

**Comment by mjcheetham** [comment]
> This is a Family client ID and so the RT that is retrieved is a family RT. MSAL will not serialize it in the ADALv3 format, because ADAL does not know about FOCI (Family of client ID).

Correct. This is a 1P application that supports the 'family'.

> I can add a small fix for MSAL to write an normal RT back to the ADAL cache though, but not sure if it makes any difference.

This would be a useful fix for 3P applications which don't have the 'family' concept, and also for 1P applications that share client IDs.

**Comment by bgavrilMS** [comment]
No 3rd party user impact, non-supported scenario for 1st party (FOCI is not supported by ADAL). Closing.

**Comment by drago-draganov** [comment]
For our first party, we are looking at migration of the persisted cache. A smooth rollout assumes that we have both ADAL and MSIL serialized tokens at the same time. SerializeAdalV3 returning null doesn't help here.
