### ISSUE TITLE
Error in example of Acquire Token Interactively in Wiki

### ISSUE THREAD

**Issue by AlexandreArpin** [AzureAD/microsoft-authentication-library-for-dotnet#1223]
### Documentation Related To Component:
Acquiring Tokens Interactively

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [X] error(s) in example
- [ ] needs example

### Description Of The Issue
:wave:

There's currently an error in the first example

```
string[] scopes = new string["user.read"];
```

Should be 

```
string[] scopes = new string[] {"user.read"};
```

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively

**Comment by jennyf19** [comment]
@AlexandreArpin fixed. great catch. thanks.
