### ISSUE TITLE
Azure AD B2C error trying to sign in / change Password

### ISSUE THREAD

**Issue by rkshnair** [AzureAD/microsoft-authentication-library-for-dotnet#1225]
I am using Microsoft.Idendity.Client(V4.0.0) library along with Xamarin for login to Azure AD B2C account.

Previously I was using external browse(chrome) for opening the login window. And yesterday I changed the code like given below.

```
var result = await _authenticationClient.AcquireTokenInteractive(_settings.Scopes)
                    .WithParentActivityOrWindow(ParentActivityOrWindow)
                    .WithPrompt(Prompt.ForceLogin)
                    .WithUseEmbeddedWebView(true)
                    .ExecuteAsync();
```

I have changed the behavior to open the embedded browser for login by adding the `.WithUseEmbeddedWebView(true)` configuration.

After changing this, I am getting an error page(intermittently) saying that "Bad Request - Header Field too long"

HTTP Error 400 - Request Header field is too long.

Attaching the error image for your reference.

![59831160-7e24a980-9341-11e9-91b0-f810d62763d7](https://user-images.githubusercontent.com/3647522/59870070-0c764b00-9395-11e9-9ab0-d8a0deb40b88.png)

Could you please let me know why this issue is coming and how I can resolve it. Do I need to consider for something else, in case if I am using EmbeddedWebView.

Also I have noticed that It is not coming every-time. Seems like something weird happen with my code.

Please help.

**Comment by jennyf19** [comment]
@rkshnair Are you using login.microsoftonline.com or b2clogin.com?

**Comment by rkshnair** [comment]
I am  using **b2clogin.com** something like this,

https://xxxxb2c.b2clogin.com/tfp/xxxxb2c.onmicrosoft.com/

**Comment by jennyf19** [comment]
@rkshnair you might have cookies accumulating from multiple log-ins (is this for a test/dev account or from a customer?) [b2clogin.com](https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin) has the benefit of "Space consumed in the cookie header by Microsoft services is reduced", because when using login.microsoftonline.com this was a bigger issue with cookies accumulating.

do you have a correlation id from a failed request that we can use to look up the logs on the B2C side?

**Comment by rkshnair** [comment]
It is a QA account from customer. I will try to reproduce this again and will update you the details. By the way, from where I can take the correlation id. I haven't tried this before.

**Comment by jennyf19** [comment]
@rkshnair The correlation id will be in the [logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#with-msalnet-3x). you can email them if you rather (jeferrie@microsoft.com)

MSAL.NET does not handle the cookies, so you would have to implement something, but first, let's look at the logs.

also, do you know which policy is being used when this error happens? If you run the logs w/Pii enabled, we should see the authority, which will give us the policy, if you are not sure.

**Comment by rkshnair** [comment]
Sadly.. Right now I am not getting the error. I will try to send the details once I reproduce the issue.

**Comment by jennyf19** [comment]
@rkshnair that's okay...when it does, just ping me here or send an email with the logs. thx.

**Comment by jennyf19** [comment]
@rkshnair any update on this?

**Comment by rkshnair** [comment]
I have added the below code when the user try for re-login and everything works fine for me.
```
 public Task ClearCookiesAsync()
        {
            var context = Android.App.Application.Context;

            if (Build.VERSION.SdkInt >= BuildVersionCodes.LollipopMr1)
            {
                System.Diagnostics.Debug.WriteLine("Clearing cookies for API >= LollipopMr1");
                CookieManager.Instance.RemoveAllCookies(null);
                CookieManager.Instance.Flush();
            }
            else
            {
                System.Diagnostics.Debug.WriteLine("Clearing cookies for API < LollipopMr1");
#pragma warning disable CS0618 // Type or member is obsolete
                var cookieSyncMngr = CookieSyncManager.CreateInstance(context);
#pragma warning restore CS0618 // Type or member is obsolete
                cookieSyncMngr.StartSync();
                var cookieManager = CookieManager.Instance;
                cookieManager.RemoveAllCookie();
                cookieManager.RemoveSessionCookie();
                cookieSyncMngr.StopSync();
                cookieSyncMngr.Sync();
            }

            return Task.FromResult(true);
        }
```

**Comment by bgavrilMS** [comment]
Thanks for following up @rkshnair !
