### ISSUE TITLE
CCA.AquireTokenSilent and cache access?

### ISSUE THREAD

**Issue by dmcweeney** [AzureAD/microsoft-authentication-library-for-dotnet#1227]
**Which Version of MSAL are you using ?**
4.0.0

**Platform**
Asp.Net Core 2.2

**What authentication flow has the issue?**
* Web App
    * [ ] Authorization code
    * [x ] OBO

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Expected behavior**
I would have expected the cache to get loaded just once for the following sequence as described...

**Actual behavior**
The cache load code gets called 3 times resulting in 3 cache loads

**Repro**

I have just finished upgrading from MSAL 2.5 to MSAL 4.0 to take advantage of the new async 
cache access methods and noticed something strange, and just wanted to validate that MSAL is working correctly.

In my case I have a multi-tenant web application and the AquireTokenSilent sequence is as follows:

Create ConfidentialClientApplication...

```
	ConfidentialClientApplicationBuilder
		.Create( theClientId )
		.WithAuthority( theAuthority )
		.WithRedirectUri( theRedirectUri )
		.WithClientSecret( theClientSecret ) ;

	Set the logging delegates
	Set 3 x cache access async delegates

```
I then call `CCA.GetAccountAsync( accountId )`, which triggers a call to load the cache for the user. 

My BeforeAccessAsync code is called to load the cache (First Time)
My AfterAccessAsync code is called with HasStateChanged = False  (First Time)

(Note the `TokenCacheNotificationArgs.AccountId` is not set so I have to pull the accountId via HttpContextAccessor.)
So TokenCache is now loaded for the current user.

I then call `CCA.AcquireTokenSilent( requestedScopes, account )`, which results in the following:

```
(False) *** MSAL Logging *** MSAL MSAL.NetCore with assembly version '4.0.0.0', file version '4.0.0.0' and informational version '4.0.0+7a3d943ca58f9b146b1b2b94d1825d36bfa5d003'. TelemetryCorrelationId(decfe7a0-7f8b-47c8-bf11-3240ff4558f0)
(False) *** MSAL Logging *** === OnBehalfOfParameters ===
LoginHint provided: False
User provided: True
ForceRefresh: False

(True)  *** MSAL Logging *** 
=== Request Data ===
Authority Provided? - True
Client Id - ********** theClientId *************
Scopes - User.ReadBasic.All
Redirect Uri - **** theRedirectUri
Extra Query Params Keys (space separated) - 

(True) *** MSAL Logging *** === Token Acquisition (SilentRequest) started:
	Authority: https://login.microsoftonline.com/********************************/
	Scope: User.ReadBasic.All
	ClientId: ********** theClientId *************
	Cache Provided: True
GetMetadataEntryAsync - response from cache? True

(False) *** MSAL Logging *** Looking up access token in the cache.

```
My BeforeAccessAsync code is called to load the cache (Second Time)
My AfterAccessAsync code is called with HasStateChanged = False  (Second Time)

```
(False) *** MSAL Logging *** Filtering by home account id item count before 1 after 1
(False) *** MSAL Logging *** Tenant id: ***** the tenant id redacted *****
(False) *** MSAL Logging *** Filtering by tenant id item count before 1 after 1
(False) *** MSAL Logging *** Matching entry count -1
(False) *** MSAL Logging *** Matching entry count after filtering by scopes - 1
(False) *** MSAL Logging *** Access token is not expired. Returning the found cache entry. [Current time (06/24/2019 09:57:30) - Expiration Time (06/24/2019 10:56:17 +00:00) - Extended Expiration Time (06/24/2019 10:56:17 +00:00)]

```
My BeforeAccessAsync code is called to load the cache  (Third Time)
My AfterAccessAsync code is called with HasStateChanged = False (Third Time)

`(False) *** MSAL Logging *** === Token Acquisition finished successfully. An access token was returned with Expiration Time: 06/24/2019 10:56:17 +00:00 ===
`

AquireTokenSilent sequence finished.

**Question** - is AquireTokenSilent supposed to be calling the BeforeAccessAsync and AfterAccessAsync a second time after it has found a correct cache entry?

**Question 2** - the CCA.GetAccountAsync and CCA.AcquireTokenSilent combo results in 3 cache reads - would this be expected behaviour too?

Thanks

Donal

**Comment by bgavrilMS** [comment]
Hi Donal, 

I can explain most of the token cache accesses, I think we can (and should) optimize one of them. 

ClientCredentialRequest.ExecuteAsync - 2 cache accesses

- this looks in the AppTokenCache. You don't need to call AcquireTokenSilent in this flow!
- so it first tries to see if an access token already exists in the cache => cache access
- if not, it makes a network call to AAD, AAD sends back tokens, MSAL will persist them to the cache => cache access

GetAccounts (1 cache access) 

- GetAccounts will load accounts that have refresh tokens associated with them. So we need to load all accounts and all refresh tokens from the cache. 

AcquireTokenSilent (potentially 4 accesses, should be 3 or even 2)

- load all access tokens from the cache (cache access 1)
- if non match, or expired, try to locate a refresh token. First, load some app metadata (cache access 2), then load all the RTs (cache access 3). 
- if an RT is found, we go to AAD to request a fresh AT. We then save it (cache access 4). 

@dmcweeney - what is your concern, are you having perf issues? What sort of cache storage do you use?

I logged a bug around AcquireTokenSilent access - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1230

**Comment by dmcweeney** [comment]
@bgavrilMS we are using Azure Redis for token cache storage. My concern is why would the cache be accessed 3 times for the same set of data. OR am I doing something really silly to cause this or did I miss a piece of documentation or guidance! It also seems crazy that there are 3 redis cache reads for every graph api call.

What also concerned me is that **after** the MSAL log line:

`(False) *** MSAL Logging *** Access token is not expired. Returning the found cache entry. [Current time (06/24/2019 09:57:30) - **Expiration Time (06/24/2019 10:56:17 +00:00)** - Extended Expiration Time (06/24/2019 10:56:17 +00:00)]
`

User token cache is read from again... and then MSAL uses the token matched as per the above log line (my assumption based on expiration time). This cache read seems to be unnecessary.

`(False) *** MSAL Logging *** === Token Acquisition finished successfully. An access token was returned with **Expiration Time: 06/24/2019 10:56:17 +00:00** === `

Thanks, Donal

**Comment by bgavrilMS** [comment]
I agree Donal, that is another case where a token cache access can be avoided. I updated the bug to reflect this. 

If a valid AT is found, our current logic is to then load Id Tokens from the cache (second access)

Generally MSAL so far has a strategy of making a cache call for each piece of information it requires. This is like making separate SELECT * calls to a database, instead of sending a bigger SELECT * .. JOIN ... that would avoid touching it multiple times. 

PS: I don't think you're doing anything wrong, but feel free to post more of your code if you want us to look at it.

**Comment by dmcweeney** [comment]
@bgavrilMS glad I asked the question... looking forward to the bug fix.
