### ISSUE TITLE
Why does the Windows integrated authentication flow require federation?

### ISSUE THREAD

**Issue by roederja2** [AzureAD/microsoft-authentication-library-for-dotnet#1228]
The seamless sign on feature (seamless SSO) does not require federation and essentially achieves the same thing. So why does the Integrated Windows authentication flow require federation when seamless SSO does not?

See: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication

Update: In ADAL this seems to have worked without federation in the past, but no more: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1478

**Comment by henrik-me** [comment]
@bgavrilMS @rayluo : can you pls. help investigate

**Comment by rayluo** [comment]
I believe the first question, "seamless SSO should not require federation", is the same topic that one of our [internal work item](https://identitydivision.visualstudio.com/DevEx/_workitems/edit/360185) mentioning the "federation lie".

I can not comment much on [ADAL .Net issue 1478](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1478), but if it "worked in the past but no more" and we could not find the reason from client-side, we might want to double check [how the service-side enables that aforementioned "federation" behavior for a particular SKU and version number (this is an internal link)](https://msazure.visualstudio.com/DefaultCollection/One/_git/ESTS-Main/pullrequest/1154581?_a=files&path=%2Fsrc%2FProduct%2FMicrosoft.AzureAD.WebFE.Controllers%2FUserRealm%2FUserRealmController.cs), to rule out that possibility.

**Comment by jmprieur** [comment]
@trwalke : I believe that this is fixed? can you please confirm?

**Comment by jmprieur** [comment]
@roederja2 : proposing to close this issue as I believe it's fixed. Feel free to reopen if you disagree.
