### ISSUE TITLE
Acquire Token Methods w/o Access to HttpContext.Current 

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-dotnet#123]
Inside`ConfidentialClientApplication.cs`, three of the `AcquireToken` methods call `RunAsync()` which appears to spawn a new thread that does not have access to `HttpContext.Current`.  Other methods that don't have this issue use `RunAsync().ConfigureAwait(false)` instead.  When the next `AcquireToken` call goes into the cache, it generates an Exception b/c it does not have access to the Session. 

Methods Affected: `AcquireTokenForClientCommonAsync`, `AcquireTokenOnBehalfCommonAsync`, `AcquireTokenByAuthorizationCodeCommonAsync`

**Comment by kpanwar** [comment]
Fixed in dev.
