### ISSUE TITLE
Xamarin Forms 4 + MSAL.Net: build error when referencing net standard assembly

### ISSUE THREAD

**Issue by luisabreu** [AzureAD/microsoft-authentication-library-for-dotnet#1233]
Version: Latest stable
Plaform: Xamarin Forms project (net standard + android project)

Problem: error building solution: error XA2002: Can not resolve reference: `Microsoft.Identity.Client`, referenced by 'net standard assembly'

Reproducing the problem:

1. Open VS 2019
2. Create a new project
3. Choose Mobile App (Xamarin.Forms), empty template
4. Update the Xamarin Forms nuget package to the latest version (4.0
5. Add the msal.net nuget package to all the projects (Microsoft.Identity.Client, version 4.0.0)
6. Add some code that uses the MSAL.Net lib to the net standard project (for instance, declare a variable inside the App ctor: IPublicClientApplication pca = null;)
7. Build the solution

In my case, it will always end up throwing an error:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1962,2): error XA2002: Can not resolve reference: `Microsoft.Identity.Client`, referenced by `App1`. Please add a NuGet package or assembly reference for `Microsoft.Identity.Client`, or remove the reference to `App1`.

Btw, I've also asked about this on stackoverflow: https://stackoverflow.com/questions/56770826/msal-netxamarin-forms-build-error-when-adding-the-latest-microsoft-identity-cl

The site shows the csproj for the standard and android projects that reproduce this bug.

Thanks.

**Comment by bgavrilMS** [comment]
Are you using VS 2017 or VS 2019?

**Comment by bgavrilMS** [comment]
I replied on SO as well -  can't repro the bug using a vanilla project as you describe. In your SO question, there's another project that you use, and it seems the error is comming from there.

**Comment by luisabreu** [comment]
Hello.

I've added a comment to the stackoverflow entry. I'm also putting that info here:

1. I'm using VS 2019. 
2. I've added references to the MSAL.Net Nuget package to all the projects (ie, I've added the reference to the net standard project that has the xaml pages, to the android and to the ios projects). The 1st csproj that is listed on the stackoverflow post is the net standard project that has the xaml files. I've tried to follow the sample https://github.com/Azure-Samples/active-directory-xamarin-native-v2 (it seems like the msal.net nuget package is added to all the projects in that sample...)

**Comment by bgavrilMS** [comment]
Can you build and run the sample? It is an older xforms template that it uses, but the project dependencies will be the same.

**Comment by jmprieur** [comment]
@luisabreu did you check, in the xamarin .csproj, that the HintPath is right? I've sometimes seen NuGet to mess-up the HintPath for Xamarin projects.

**Comment by luisabreu** [comment]
Yes, I can build the sample and it does run. However, it's still using Xamarin.Forms 2.5 (instead of the latest 4.0)...Btw, just updating the Xamarin.Forms package in that demo solution is enough for breaking it (with a different error, though)

I see no hint path in either csproj file created from VS 2019 (unlike the csproj found on the sample, which does have a hint for the Microsoft.identity.Client assembly reference ...)

**Comment by luisabreu** [comment]
Hello again guys,

Just to give more info, here's a simple project that is not working on my machine. I'm also sending the detailed output of the build.
I've also tried clearing the local nuget caches. Unfortunately, the result is always the same.

Any pointers on how to solve this? Thanks

[msal-Output-Build.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/3338395/msal-Output-Build.zip)

[MsalBuildIssue.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/3338388/MsalBuildIssue.zip)

**Comment by bgavrilMS** [comment]
I am able to build and even deploy the app on an Android emulator. Could you try from a different machine?

![image](https://user-images.githubusercontent.com/12273384/60337101-063a2d00-999a-11e9-9415-a3d811e555d4.png)

**Comment by luisabreu** [comment]
Hello again.

I have just tried and it seems to work...does this mean that I should reinstall vs again? Any ideas on what might have happened on this machine?

**Comment by bgavrilMS** [comment]
I am not sure Luis. From my own experience, when I installed VS 2019 side by side with VS 2017, it broke UWP  and sadly I had to reinstall the entire OS. It looks like some installation scenarios were not super well tested...

**Comment by bgavrilMS** [comment]
I'm going to close the issue as external, but feel free to reopen or open a new one if you encounter more problems.

**Comment by luisabreu** [comment]
Sure...Removing and reinstalling vs was not enough to solve this...

**Comment by bgavrilMS** [comment]
That's not cool :(. Yeah, I ussually have to do a clean install (i.e. reinstall Windows) if I get into deep VS installation issues. The VS guys have done a lot of work to test these scenarios, but problems still remain sometimes.

**Comment by Simba-Mupfunya** [comment]
To anyone who is facing this issue, please dont reinstall the OS just add references to the individual framework libraries from your nuget cache or any other physical repository you have access to with the corresponding Microsot.Identity.Client.dll

**Comment by jmprieur** [comment]
Thanks @Simba-Mupfunya 
See also https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-2.6.0-released#msalnet-helps-you-build-multi-platform-applications-more-easily

**Comment by adospace** [comment]
@Simba-Mupfunya Could you please clarify how to solve the issue without reinstall the OS? I'm facing the exactly same issue described here, thx

**Comment by Simba-Mupfunya** [comment]
@adospace First I downloaded the package via nuget "microsoft.identity.client 4.7.1" and then I manually added the reference to Microsoft.Identity.Client.dll located in the nuget package folder to my projects (i.e Shared + Targets) and that did the trick for me. As to why this worked, im not quite sure as technically any nuget reference package should automatically be copied to your obj/bin folder
