### ISSUE TITLE
Azure AD B2C with SSO implementation in Xamarin Forms 

### ISSUE THREAD

**Issue by soooraj** [AzureAD/microsoft-authentication-library-for-dotnet#1239]
Is it possible to implement Single Sign On along with Azure AD B2C. 
If yes,
Could you please suggest some sample / Documentation about the same. 

I am trying to implement the same in my Xamarin Application.

**Comment by henrik-me** [comment]
I recommend reading the wiki:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively
that will walk you through b2c details as well as point to a sample.

You can find the same sample by searching Azure-Samples: 
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

**Comment by soooraj** [comment]
I cannot see anything related to SSO in the link / sample provided by you. It is a generic B2C sample could you please verify.

**Comment by jmprieur** [comment]
What do you mean by SSO, @soooraj. SSO with what? 
Can you please provide repro steps? what do you do? what is expected? what does not work?

**Comment by soooraj** [comment]
I have 3 apps, If I login to any one of the app and the token is active. I need to restrict the user to Login again and again for other apps. 

I was just wondering is there any way to implement this in Azure AD B2C with Identity Client. I know after every successful login the sdk is persisting the account details.

So what will happen if I try to login using **AcquireTokenSilent** through other app. When it come to the other app I only have the token I got from First App login. So the account details will  be null there in the second app.

If there is any sample or documentation to handle such situations please provide. 
I am simply trying to implement Single Sign On (SSO) in my multiple enterprise apps.

**Comment by jmprieur** [comment]
Thanks for the clarification, @soooraj 
I believe that this is a current limitation with B2C. @valnav @parakhj can you please confirm?
cc: @jennyf19

**Comment by soooraj** [comment]
@henrik-me @jmprieur @jennyf19 : Since the marked answer is not complete, could you please reopen the issue?

**Comment by henrik-me** [comment]
@soooraj : re-opening

I expect that your 3 apps have different app id's/client id's. The cache is based on the client id. The user will therefor have to sign-in to the 3 different apps. One option would be to combine your 3 apps into one app. Microsoft identity protection does not currently support linking different app id's. Only work around that I know if would be that your 3 apps uses the same app id.

@jmprieur : Not sure I understand what would be specific to B2C here?

**Comment by jmprieur** [comment]
B2C makes it worse as you cannot even get a token for a 2nd API without re-signing in.

**Comment by valnav** [comment]
@soooraj - given a b2c policy, you can restrict sso to an app, policy or tenant.

Can you review this and see if it helps - https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-token-session-sso

**Comment by soooraj** [comment]
@valnav I don't want to add any restriction, Instead I am trying to validate the token with the SDK/Library. That means, If I am already login to one app I may keep my token into some shared storage. And in my other apps I will take this token and validate. But right now SDK is not allowing me to validate.

**Comment by henrik-me** [comment]
@soooraj : What do you mean by validating? Do you mean using the token for another API call? or do you mean opening the token to validate what's in the token?

**Comment by soooraj** [comment]
In simple word multiple applications going to share the same token, So validating in this context would be calling AcquireTokenSilent() from Secondary App.

I am ok to share the same resources in both app.

**Comment by jmprieur** [comment]
@soooraj : did you manage to get SSO?

**Comment by jmprieur** [comment]
I believe the question is answered?

**Comment by soooraj** [comment]
@jmprieur The impression I got from the discussion was, it is not possible. If that is the answer the yes. I got the answer.
