### ISSUE TITLE
Supportability: MsalException message should contain the framework and version for easier debugging

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1245]
**Is your feature request related to a problem? Please describe.**
ICMs and github issues often contain exception stack traces, but no logs, no version and no target framework (tfm)

Requirements

- Improve the stack trace enable easier debugging.
- Improve Error Message to make it easier to find the location in the code
- Reduce back and forth communication

**Describe the solution you'd like**
MsalException messages should be prefixed with version and tfm

**Exception Message Format:** 
MSAL.%Target%.%Version%.%UniqueId%: %Message%

**Alterntive or additionally:**
Override .ToString() to enable this, enhacing the stracktrace

**Comment by jmprieur** [comment]
#supportability!
