### ISSUE TITLE
Default Redirect URI for System Browser on .NET Core

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1246]
**Is your feature request related to a problem? Please describe.**
This feature is an improvement on https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1186. Currently, when using WithDefaultRedirectUri() on .NET Core the default redirect URI will be set to "http://localhost". It may not be the best idea to set the default redirect uri to local host on .net core but a better idea is to have the default redirect URI depend on the use of the system browser.

**Describe the solution you'd like**
WithDefaultRedirectUri(), on .NET Framework and .NET Core should set the redirect URI to "https://login.microsoftonline.com/common/oauth2/nativeclient" when the embedded webview is used an "http://localhost" when the system browser is used.

**Describe alternatives you've considered**
If there is no good way to detect the state of the system browser setting perhaps a WithLocalHostRedirectURI() method can suffice as it will allow the user to specify when to use a local host redirect URI.

Be sure to update the comment on the WithDefaultRedirectUri() api
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/267661399c81cddb0f3687a8e19fac6603a12ded/src/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs#L74

**Comment by jmprieur** [comment]
Proposing to handle this part of the work on the embedded web view on .NET Core
@bgavrilMS

**Comment by jmprieur** [comment]
@bgavrilMS : is there any chance we can do that now that the webView2 is there?

**Comment by bgavrilMS** [comment]
Yes, we can do this.

**Comment by butkandrius** [comment]
What is the status? Is there any chance to use it in console application with custom redirect uri?

**Comment by bgavrilMS** [comment]
We can't implement this without introducing a breaking change, so we will close this. 

@butkandrius - what are you trying to do? Are you using the system browser on a console app? Just add `.WithRedirectUri("http://localhost")` and register `http://localhost` redirect URI.

**Comment by butkandrius** [comment]
I am trying to achieve this flow https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
with console app and I need to somehow get `auth_code `from redirected uri after microsoft sign in.

**Comment by bgavrilMS** [comment]
MSAL will do all of that for you. MSAL is a higher level library, it implements the protocols and does not expose all the nitty gritty details for you. 

MSAL will: 

- pop up a browser for you
- cache the tokens for you (with a bit of help)

What you need to do: 

- register an app in the Azure Portal > AAD > App Registration Portal
- configure a redirect URI

Please start from a sample as it explains everything: 

https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/tree/master/1-Calling-MSGraph/1-1-AzureAD

**Comment by butkandrius** [comment]
It works fine with this, but I need to get `auth_code` from redirect URI (so I could pass this to external authentication middleware) but it seems it's hard to get that using console app as it can not access that redirected page query parameter and a better idea is to have win forms for that. Any way, thanks for info @bgavrilMS
