### ISSUE TITLE
Provide a better documentation to help customers migrate from MSAL 2.x to MSAL 3.x/4.x

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1248]
### Documentation Related To Component:

MSAL.NET provides migration help (obsolete attributes), but some customers want to understand the change of coding style (to the builder pattern) ahead of doing the modification. This issue is about providing a better documentation to help customers migrate from MSAL 2.x to MSAL 3.x/4.x

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs improvement and be surfaced
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
We've started https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-2.x-to-MSAL.NET-3.x, but:
1) it's not completed (for Confidential clients)
2) It needs to provide links to the conceptual documentation
3) It needs to be surfaced better. Maybe moved to docs.ms

### Bonus
Another page with the same kind of docs to migrate from ADAL 5.x to MSAL 4.x would be useful.

**Comment by luismanez** [comment]
very needed yes! specially the TokenCache changes. Thanks for open this issue
