### ISSUE TITLE
You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile49',

### ISSUE THREAD

**Issue by khilscher** [AzureAD/microsoft-authentication-library-for-dotnet#125]
In VS 2015 Enterprise, Update 3 with Xamarin installed (Windows 10 O/S). Created a new Xaml Xamarin.Forms project with Portable Class Library. When installing MSAL NuGet pkg, the following error appears, even after removing "Windows Phone 8.1" from PCL targets (see attached screen capture).  

"Could not install package 'Microsoft.Identity.Client 1.0.304142221-alpha'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile49', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

The workaround described at https://github.com/microsoftgraph/xamarin-csharp-connect-sample/wiki/Set-up-a-Xamarin-Forms-project-to-use-the-MSAL-.NET-SDK also doesn't clear the error.

![image](https://cloud.githubusercontent.com/assets/13604100/20933694/1f210a58-bb96-11e6-8430-89da4e9aac11.png)

**Comment by jamescro** [comment]
In the past, the Xamarin Forms template didn't have the Windows Phone Silverlight 8.1 build target checked by default. Since that target is now checked by default, you have to uncheck that one along with the Windows Phone 8.1 target. Kevin has verified that this works for him, and I've updated the guidance in the wiki.

**Comment by kpanwar** [comment]
Windows Phone 8.1 or SL 8 is not supported
