### ISSUE TITLE
Silent authentication when migrating from ADAL to MSAL results in AADSTS65001

### ISSUE THREAD

**Issue by cormacpayne** [AzureAD/microsoft-authentication-library-for-dotnet#1267]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

ADAL: 3.19.5
MSAL: 3.0.8

**Platform**

.NET Standard 2.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [x] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**

Existing app in production, upgraded to latest version of MSAL.

**Repro**

Writing to the ADAL cache in the old product

```cs
var audience = environment.GetEndpoint(resourceId);          // e.g., https://management.core.windows.net/
var context = new AuthenticationContext(
    AuthenticationHelpers.GetAuthority(environment, tenant), // e.g., https://login.microsoftonline.com/common
    environment?.OnPremise ?? true, 
    tokenCache as TokenCache ?? TokenCache.DefaultShared);
var result = context.AcquireTokenAsync(audience, AuthenticationHelpers.PowerShellClientId, new UserPasswordCredential(account.Id, password));
```

Migrating the contents of the ADAL cache to MSAL

```cs
byte[] adalData;
try
{
    adalData = File.ReadAllBytes(adalCachePath);
}
catch
{
    return;
}

var client = PublicClientApplicationBuilder.Create(clientId).Build();

// Next two lines leverage MSAL extensions library to register cache to single sign-on token cache with cross-platform read/write capabilities
var cacheHelper = InitializeCacheHelper(clientId);
cacheHelper.RegisterCache(client.UserTokenCache);

try
{
    client.UserTokenCache.DeserializeAdalV3(adalData);
}
catch
{
    return;
}
```

Attempting to silently authenticate using each account in the MSAL cache

```cs
var accounts = client.GetAccountsAsync().ConfigureAwait(false).GetAwaiter().GetResult();
foreach (var account in accounts)
{
    var scopes = new string[] { string.Format("https://{0}/{1}", account.Environment, ".default") };
    try
    {
        var token = client.AcquireTokenSilent(scopes, account).ExecuteAsync().ConfigureAwait(false).GetAwaiter().GetResult();
    }
    catch
    {
        continue;
    }
}
```

**Expected behavior**

When the call to `AcquireTokenSilent` is made, the appropriate token is retrieved and stored into the new cache.

**Actual behavior**

The following exception is thrown when calling `AcquireTokenSilent`:

```
AADSTS65001: The user or administrator has not consented to use the application with ID '1950a258-227b-4e31-a9cf-717495945fc2' named 'Microsoft Azure PowerShell'. Send an interactive authorization request for this user and resource.
```

**Possible Solution**

N/A

**Additional context/ Logs / Screenshots**

Same behavior occurs when interactive and device code login are used in the old product (ADAL).

**Comment by cormacpayne** [comment]
@jmprieur Hey Jean-Marc, let me know if there's anything you need from me for this issue 😀

**Comment by henrik-me** [comment]
@cormacpayne : We'll look into this. Sorry for the delay. Any reason you are not using the lastest MSAL?

**Comment by cormacpayne** [comment]
It looks like I was using the wrong endpoint for the scope -- changing it to `https://management.core.windows.net` instead of `account.Environment` (which resolved to `https://login.microsoftonline.com`) fixed the issue.

@henrik-me I'm using the same version of MSAL (and the extensions library) that VS is going out with.
