### ISSUE TITLE
Using common tenant results in cache lookup failure

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#127]
- Use common endpoint to acquire token for a user
- Cache entry is created with tenant specific authority
- Call acquire token silent and it will make another network call instead of returning the cached token

**Comment by htuomola** [comment]
This is closed so not sure if I should comment here or open a new issue but I can still reproduce this when using on-behalf flow (`ConfidentialClientApplication.AcquireTokenOnBehalfOfAsync`), with code checked out from 1.1.0-preview tag version. Calling the method twice returns two different tokens with two different issued-at times. 

It seems that the matching cache entry gets filtered out in here:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/77891b760cf194991f1ab9939c5e3282de226055/src/Microsoft.Identity.Client/TokenCache.cs#L321

wherein `item.Authority` has value `https://login.microsoftonline.com/<tenantID>/`
but `requestParams.Authority.CanonicalAuthority` equals `https://login.microsoftonline.com/common/`. Not quite sure which way this should work but it also seems that the Authority is always set to tenant ID value on saving:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/77891b760cf194991f1ab9939c5e3282de226055/src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs#L195

Passing authority with tenant ID to the client constructor bypasses the problem so using that as a workaround.

**Comment by kpanwar** [comment]
Can you please file a separate issue for this?

**Comment by htuomola** [comment]
Created #496.
