### ISSUE TITLE
[Bug] ExtraScopesToConsent is not working as expected for accounts outside of the home tenant

### ISSUE THREAD

**Issue by ashikns** [AzureAD/microsoft-authentication-library-for-dotnet#1277]
**Which Version of MSAL are you using ?**
MSAL 4.1.0

**Platform**
netcore console app, possibly existent on android too

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
This is a new app or experiment

**Repro**
Register two applications in Azure portal - Client and Server. In Client add __http://localhost__ as a redirect uri for public client (to enable .net core os browser). In server expose an api with the format __api://*server_application_id*/user_impersonation__.

```csharp
var pca = PublicClientApplicationBuilder.Create("<client application id>")
    .WithDefaultRedirectUri()
    .Build();

await pca.AcquireTokenInteractive(new[] { "User.Read", "Files.Read" })
    .WithExtraScopesToConsent(new[] { "api://<server application id>/user_impersonation" })
    .WithSystemWebViewOptions(new SystemWebViewOptions { OpenBrowserAsync = SystemWebViewOptions.OpenWithEdgeBrowserAsync })
    .ExecuteAsync();

var accounts = await pca.GetAccountsAsync();
var account = accounts.FirstOrDefault();

await pca.AcquireTokenSilent(new[] { "User.Read", "Files.Read" }, account).ExecuteAsync();
await pca.AcquireTokenSilent(new[] { "api://<server application id>/user_impersonation" }, account).ExecuteAsync();
```

**Expected behavior**
Both acquire token silent calls succeed.

**Actual behavior**
On the second acquire call, i.e on trying to acquire a token for the server application it throws an error *AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
Trace ID: a356c4c1-c5bc-4318-be7c-a806cdda1f01
Correlation ID: 8def64e5-98ab-4037-a223-6bf17cb7acab*.

**Possible Solution**
If the server api scope is passed directly in *AcquireTokenInteractive* instead of via *ExtraScopesToConsent* it works correctly. It should work always though I'm assuming.

**Comment by jmprieur** [comment]
@ashikns, I agree that this should work, but I suspect that there is a provisionning issue. 
To narrow down the issue, I've 2 questions:
- you use the default authority ("common"). Which audience did you register for your app? Does it work with a tenanted authority (https://login.microsoftonline.com/tenantId or https://login.microsoftonline.com/domain)? 
- Did you try to invert the scopes and extra scopes to consent? (asking a token for the service and extra scopes to consent to for graph)

**Comment by ashikns** [comment]
@jmprieur 
- Both applications are set to allow login by any microsoft work or personal account.
- Yes it works if I ask token for the service. This is what I tried to describe in the Possible Solution section.

**Comment by jmprieur** [comment]
Thanks for confirming, @ashikns. I need to check on the Azure AD side
When you got this error were you login with an account from the same tenant as where the app was created? or a different tenant?

**Comment by ashikns** [comment]
Logging in from an account under the same tenant works. Personal accounts don't work. I have not tried with accounts from other tenants but our client reported that doesn't work either.

**Comment by jmprieur** [comment]
Thanks for @ashikns 
My recommendation for the moment is to use the Web API for the scope. I'll check with the service people what we can do.

**Comment by nibdev** [comment]
If somebody has the same problem, i found a workaround (at least for my configuration / system).

Put all your scopes in the ExtraScopes...

```
await pca.AcquireTokenInteractive(new string[0])
    .WithExtraScopesToConsent(new[] { "User.Read", "Files.Read", "api://<server application id>/user_impersonation" })
    .WithSystemWebViewOptions(new SystemWebViewOptions { OpenBrowserAsync = SystemWebViewOptions.OpenWithEdgeBrowserAsync })
    .ExecuteAsync();
```

**Comment by bgavrilMS** [comment]
THis has been fixed by AAD.
