### ISSUE TITLE
[Feature Request] Throw on Declined scopes

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1278]
**Is your feature request related to a problem? Please describe.**
user asks a token for scopes A, B, C
user gets a token for scopes A, B

How can this happen?

- C has been declined (for example, it is an application scope requested in the name of a user - see bug https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/743) 

Why is this a problem?

1. MSAL saves the AT with scopes A, B (i.e. it trusts the server, not the user)
2. `AcquireTokenSilent` will not find an access token for scopes A, B, C. So it will refresh the RT for one. 

This means that all `AcquireTokenSilent` will hit AAD with a refresh_token flow. 

**Describe the solution you'd like**
A solution has already been agreed on for MSALs. 

If the requested scopes are not a subset of granted scopes, an error will be passed to the calling application. Shane’s document calls this DeclinedScopeException for now. The received token will be cached under the granted scopes, and the developer can call ATS() with the granted scopes (list available from the exception) for the token. No network call will be made in this case, as the token already lives in the cache. 

If the granted scopes are a superset of the requested scopes, everything proceeds as normal. The extra returned scopes are silently cached and are available for future use. This will not cause a cache miss on future hits, and will be tested. 

After receiving a declined scope error, the developer has 2 methods that they can call: getScopes() (already exists) and getDeclinedScopes(). Both will return a list of the scopes that were granted and declined respectively.

**Comment by henrik-me** [comment]
@bgavrilMS : I'm not sure this was finally confirmed

**Comment by henrik-me** [comment]
This is a breaking change. Considering having an opt-in option for change of behavior to avoid making this a breaking change (can then decide to make it on by default as part of a major version update). For now placed this in the "Future Major Version Update" until we agree on the potential opt-in option.

**Comment by bgavrilMS** [comment]
Makes sense Henrik. We currently have feature flags, but don't have a way to expose them to the user. I doubt this feature will interest anybody, so we can just schedule it as part of our next major release.

**Comment by henrik-me** [comment]
ack, thanks.
