### ISSUE TITLE
Java cache tests failing on Azure DevOps build machines

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1286]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 4.1.0 / MSAL 4.2.0

Java cache tests are failing on the azure devops machine.  Looks like maven is missing on the image.  Tests are disabled until this is resolved.  This bug is to track that these tests are disabled.

**Comment by trwalke** [comment]
very strange, according to the details of the hosted agent maven 3.6.1 should be installed
https://identitydivision.visualstudio.com/IDDP/_settings/agentqueues?queueId=90&view=details

![image](https://user-images.githubusercontent.com/30090357/61817805-40b1b100-ae04-11e9-9911-18ee0d46497c.png)

**Comment by jmprieur** [comment]
@MarkZuber @SomkaPe is it still the case?

**Comment by henrik-me** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1464

**Comment by jennyf19** [comment]
Included in [4.6 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.6)
