### ISSUE TITLE
OBO Flow through a PublicClientApplication

### ISSUE THREAD

**Issue by fuocor** [AzureAD/microsoft-authentication-library-for-dotnet#1289]
**Which Version of MSAL are you using ?**
3.0.7

**Platform**
netcoreapp3.0 on windows 10

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [x ] OBO
* Web API
    * [x ] OBO

**Is this a new or existing app?**
New application underdevelopment

**Repro**
I have a public client application that will access a server application (confidential client)
The user logs in to the client applicaiton
```
        protected async Task<IClientRuntimeContext> LoginUser(string userName, string password)
        {
            var publicClientApplication = _clientTestHost.ClientServiceProvider.GetRequiredService<IPublicClientApplication>();
            var scopes = new[] { "https://chorus.richf01.ossiaco.com/user_impersonation" };
            var authResult = await publicClientApplication.AcquireTokenByUsernamePassword(scopes, userName, password.ToSecureString()).ExecuteAsync();
            var jwtToken1 = new JwtSecurityToken(authResult.AccessToken);
            var jwtToken = new JwtSecurityToken(authResult.IdToken);

            using var client = CreateHttpClient("3.0.0");
            var additionalHeaders = new NameValueCollection
            {
                { HttpConstants.HttpHeaders.Authorization, $"Bearer {authResult.AccessToken}" }
            };
            var result = await client.GetAsync(GatewayRestUris[0], additionalHeaders);
            return await result.GetRestResponse<IClientRuntimeContext>();
        }

```
I need the server application to lift off the jwt token and store it for use in an obo flow. I'vetried the following:
```
    var jwtToken = new JwtSecurityToken(request.JwtToken);
    var scopes = new[] { "https://graph.microsoft.com/offline_access" };
    var requestedScopes = scopes ?? jwtToken.Audiences.Select(a => $"{a}/.default");
    var confidentialClient = ServiceProvider.GetRequiredService<IConfidentialClientApplication>();
    var oboToken = await confidentialClient
        .AcquireTokenOnBehalfOf(requestedScopes, userAssertion)
        .ExecuteAsync();
```
but am getting:
```
AADSTS700023: Client assertion audience claim does not match Realm issuer.
Trace ID: 79089aa6-6c60-499f-9ca4-621dc98f2700
Correlation ID: d0b714d5-03b7-4184-b3ce-2024f4177113
Timestamp: 2019-07-24 19:13:01Z
```
My guess is that the server application cannot take ownership of the token identity issued by the client. I have tried sending the IdToken rather than the AccessToken without success.

**Expected behavior**
The ability for the server application to obtain a token that it can hold for an OBO flow.

**Actual behavior**
Exception

**Comment by jmprieur** [comment]
@fuocor, please have a look at:
- this scenario landing page: [Scenario: Web API that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-overview)
- this sample [ASP.NET Core Web API tutorial](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph)
to understand the way to use OBO, and some reusable libraries to do so.

These illustrate exaclty what you want to do.

BTW, you'd probably want to update to MSAL.NET 4.2.1?

**Comment by fuocor** [comment]
thanks for the reply, but my scenario not exactly what is described.

I have a PublicClientApplication calling web API who then wants to call another web API.
The guy in the middle needs the OBO flow but cannot acquire it using the access or id token supplied by the PublicClientApplication.

rich

**Comment by jmprieur** [comment]
@fuocor what would be the flow available for the guy in the middle?
See [Authentication flows and application scenarios](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios) ?

If none, then can you draw a picture with what is possible?

**Comment by fuocor** [comment]
![scenarios-with-users](https://user-images.githubusercontent.com/15656129/61885607-1a574880-aecc-11e9-95f0-a0d61ce48abf.png)

The user signs in to the PublicClientApplication on the left which sends a token to the service in the middle in order to use it for calls the downstream service.

All the applications are in the same active directory tenant, and I've tried sending the access token and id token from the PublicClientApplication but when I try to acquire the OBO in the middle service I get:

```Client assertion audience claim does not match Realm issuer.```

**Comment by jmprieur** [comment]
@fuocor  . I think you mismatch the scopes. Can you please share the scopes that you used in your public client application to get a token for your middle tier application? and then in your middle tier application to call your Web API?

Ideally, share the acquire Token calls you've used

Did you you try the OBO samples I pointed you to ? (and did you read the README.md) ?

**Comment by fuocor** [comment]
I have worked with OBO using direct rest calls without issue. I will post an example this afternoon.

**Comment by fuocor** [comment]
I figured out the problem. 
The PublicClientApplication has to request an access token for a scope from the web API (ie. not "https://graph.microsoft.com/.default"). 
That access token can be use used by the Web API ConfidentialClient to execute the OBO from which a graph token can be aquired.

**Comment by jmprieur** [comment]
Thanks for confirming you had a scope mismatch
