### ISSUE TITLE
MSAL for Integrated Windows Authentication Kerberos

### ISSUE THREAD

**Issue by sameer-kumar** [AzureAD/microsoft-authentication-library-for-dotnet#1291]
I've my asp.net mvc dotnet application running in IaaS boxes. Authentication is handled via on-prem AD using Kerberos and Ping federation. Is there any workflow supported using MSAL for IWA and web applications? 
I see this doc [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos)) but it demonstrates desktop application but not web application.

The intent is to use one library for IaaS/AD/IWA as well as PaaS/AAD/OpenID.

**Comment by jmprieur** [comment]
@yordan-msft : does it make sense to support IWA in confidential clients apps?

**Comment by yordan-msft** [comment]
I don't think so. Authentication occurs is in user agent (browser).

**Comment by jmprieur** [comment]
Thanks for confirming @yordan-msft 
@sameer-kumar : I'm tempted to close this as wont fix.
Could you please describe a bit more what your scenario is? you also have single sign-on in Web Apps?  (See https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2).

**Comment by sameer-kumar** [comment]
I'm working on writing an authentication/authorization security library for our LOB apps. Currently, all our apps are hosted in IaaS IIS boxes. These apps uses AD windows authentication. In near future, we will start migrating these web apps to Azure app service. One there, these apps would use AAD instead of AD. AAD is syncd with AD already. I read about MSAL and it's workflow but not sure if I can use it for AD windows authentication too so that our apps would use one single library for AD as well as AAD authentication. Does it make sense?

**Comment by jmprieur** [comment]
Yes, the federated case is supported by MSAL. Net

**Comment by sameer-kumar** [comment]
So, can I use MSAL.Net for IaaS/AD/IWA for web apps? Do you have any sample for those scenarios?

**Comment by jmprieur** [comment]
@sameer-kumar : I see what you mean.
Actually, I don't think yo need to use MSAL for this. I'd think that this case would be a good candidate for App Services  Authentication / Authorization (Easy Auth).
@SaeedAkhter-MSFT : can you please confirm?
