### ISSUE TITLE
[Feature Request] Remove requirement for including /tfp/ for B2C

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1293]
**Is your feature request related to a problem? Please describe.**
If you are using B2C, you have to pass in this authority:
`https://{tenantName}.b2clogin.com/tfp/{tenant}/{policyName}`

Most B2C users do not use `/tfp/` anywhere in their code, so it doesn't make sense to require it for MSAL libraries as part of the authority. Leads to confusion.

**Describe the solution you'd like**
Braindump:
- Remove .`WithB2CAuthority` and use introduce `.WithAuthority(string authority, string trustFrameworkPolicy)`, which would look like this: 

`.WithAuthority("https://catsCity.b2clogin.com", "b2c_sisu")`
All B2C policies (including custom) are prefixed w/`b2c`. We'd have to have the policy included to know what to target. 
- Revisit previous proposal: 

`.WithB2CAuthority("https://catsCity.b2clogin.com")`

`.WithTrustFrameworkPolicy("b2c_sisu")`

- `.WithB2CAuthority(https://{tenantName}.b2clogin.com/{tenant}/{policyName})` 

- `.WithAuthority(https://{tenantName}.b2clogin.com/{tenant}/{policyName})` and look for `b2c` in the policy to determine it's b2c

- In the case of custom domains, the domain name and the tenant name might be different, so require this as the authority for b2c:
`.WithAuthority("https://cats.com/petsUnlimited.onmicrosoft.com", "b2c_sisu")`

**Additional context**
We have to know the authority and the **policy** for b2c. So any proposals must include those two parameters.

**Comment by jennyf19** [comment]
@jmprieur and I synced on this...we are leaning towards something like this:

- Remove `.WithB2CAuthority` and use introduce `.WithAuthority(string authorityBase, string trustFrameworkPolicy)`, which would look like this:

`.WithAuthority("https://catsCity.b2clogin.com", "b2c_sisu")`

And have `.WithTrustFrameworkPolicy(string trustFrameworkPolicy)` on the AT builders, as MSAL will already know the authority base, so developers can just target a specific policy.

@jmprieur Feel free to add or comment as necessary.

**Comment by henrik-me** [comment]
Does anyone but B2C use this terminology? Will this (ever) be relevant for AAD/MSA?

**Comment by jennyf19** [comment]
@henrik-me You're referring to TrustFrameworkPolicy? I'm not sure, but can find out.

**Comment by valnav** [comment]
With external identities- we are bringing trustFramework to AAD. Initially only for 1 policy in AAD for Vibranium

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmprieur** [comment]
@jennyf19 @henrik-me @bgavrilMS ; we could already remove the need for /ftp when we see b2clogin.com ? 
proposing it for 4.4.1

**Comment by jennyf19** [comment]
@jmprieur I think i sent you an email on this. We need /tfp/ for login.microsoftonline.com, so i don't see the reason to change now. we will need to discuss the best way to do this...also, our b2c devex group decided to table any changes to the authority input right now.

**Comment by jmprieur** [comment]
ok @jennyf19. I thought that I created it as an outcome of the group. But maybe not. I don't remember.
Closing it, then.

**Comment by jennyf19** [comment]
@jmprieur okay. we will get to this later. :)
