### ISSUE TITLE
[Unsupported scenario] OBO for Service Principal fails using MSAL (client info is null)

### ISSUE THREAD

**Issue by skhushalani** [AzureAD/microsoft-authentication-library-for-dotnet#1297]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

MSAL.net v 4.2.1

**Platform**

.Net Core 

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [x] OBO

Other? - please describe;

**Is this a new or existing app?**

This is a new app using Service Principal OBO for the first time.

**Repro**
Flow : 
Service Principal(SP) ---> Web Api A ---> Web Api B

Using OBO flow to convert a token with audience as web api A to token with audience web api B for service principal SP throws a MSALException "client info is null" even though if you install fiddler and check, the underlying service call succeeds.

The following flow works correctly using the same version of MSAL library (4.2.1): 
User ---> Web Api A ---> Web APi B

The Service Principal OBO scenario also works correctly using ADAL.net (5.1.0) 

```csharp
var scopeForWebApiA = new string[] { "https://<tenantname>.onmicrosoft.com/<web_api_A_app_name>/.default" };

            // acquire token for web api A using a Service Principal
            var servicePrincipalClient = ConfidentialClientApplicationBuilder
                .CreateWithApplicationOptions(new ConfidentialClientApplicationOptions()
                {
                    ClientId = "<clientID>",
                    ClientSecret = "<secret>"
                })
                .WithAuthority(AzureCloudInstance.AzurePublic, "<tenantID>")
                .Build();

            var tokenForWebApiA = servicePrincipalClient.AcquireTokenForClient(scopeForWebApiA.ToList()).ExecuteAsync().Result;

            // client for web api A
            var confidentialClientWebApiA = ConfidentialClientApplicationBuilder
                .CreateWithApplicationOptions(new ConfidentialClientApplicationOptions()
                {
                    ClientId = "<web_api_A_clientID>",
                    ClientSecret = "<web_api_A_secret>"
                })
                .WithAuthority(AzureCloudInstance.AzurePublic, "<tenantID>")
                .Build();

            var scopeForWebApiB = new string[] { "https://<tenantname>.onmicrosoft.com/<web_api_B_app_name>/.default" };

            // OBO for service principal from Web Api A to Web Api B
            var spOBOToWebApiB = confidentialClientWebApiA
                .AcquireTokenOnBehalfOf(
                scopeForWebApiB.ToList(),
                new UserAssertion(tokenForWebApiA.AccessToken))
                .ExecuteAsync()
                .Result;
```

**Expected behavior**
Get new token for SP with audience as WebApiB and appId as WebApiA and oid of SP.

**Actual behavior**
Underlying service call succeeds*checked using fiddler) but client throws an error.

MSALException - client info is null

   at Microsoft.Identity.Client.Core.ClientInfo.CreateFromJson(String clientInfo)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.CacheTokenResponseAndCreateAuthenticationResultAsync(MsalTokenResponse msalTokenResponse)
   at Microsoft.Identity.Client.Internal.Requests.OnBehalfOfRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenOnBehalfOfParameters onBehalfOfParameters, CancellationToken cancellationToken)

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by jmprieur** [comment]
@skhushalani : This is expected: OBO *for service principals* is not a supported scenario yet in 3rd party applications.
