### ISSUE TITLE
[Bug] With FOCI enabled windows integrated auth does not return foci ID

### ISSUE THREAD

**Issue by crmann1** [AzureAD/microsoft-authentication-library-for-dotnet#1298]
**Which Version of MSAL are you using ?**
4.2.0

**Platform**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
desktop

Other? - please describe;

**Is this a new or existing app?**
VS

**Repro**
 var publicClient = PublicClientApplicationBuilder.Create(clientID WITH FOCI)
                                      .WithAuthority(AzureCloudInstance.AzurePublic, AadAuthorityAudience.AzureAdMultipleOrgs)
                                      .Build();
                   var resource = "https://graph.microsoft.com";
                   string[] scopes = { resource + (resource.EndsWith("/", StringComparison.OrdinalIgnoreCase) ? string.Empty : "/") + ".default" };
                   var builder = publicClient.AcquireTokenByIntegratedWindowsAuth(scopes);
                   var result = await builder.ExecuteAsync();

**Expected behavior**
Result that comes back should have the foci id in it so that the correct mapping in the foci table can be made

**Actual behavior**
no foci id is returned, breaks foci

**Comment by bgavrilMS** [comment]
As far as I know, this is by design. FOCI was invented to circumvent the need for interactive auth, however IWA is not interactive so FOCI is not needed. The server will not send us "foci=1". 

How are you affected? Is it a perf issue or are you seeing other failures?

**Comment by jmprieur** [comment]
@bgavrilMS : the refresh tokens which does not have FOCI overrides the ones which has foci=1 ..

**Comment by bgavrilMS** [comment]
Have you observed this in the token cache? We store foci and non-foci refresh tokens different keyes in the cache.

**Comment by bgavrilMS** [comment]
Discussed with @jmprieur and I understand what is happening. 

The server will only send the FOCI=1 flag on `AcquireTokenInteractive` and `AcquireTokenSilent` via refresh token. But if you use any other flow (e.g. IWA, ROPC or Device Code Flow) in conjunction, then the server does not send this flag. MSAL will then assume that the app is not part of the family and mark it as such, which breaks SSO.

Solution would be to set AppMetadata only in response to `AcquireTokenInteractive` and `AcquireTokenSilent`


CC @rayluo  @SomkaPe

**Comment by rayluo** [comment]
Thanks for the nudge. I would personally vote for "for server to send Foci=1 in all flows" because that would be semantically more correct: a family app is a family app, it should not suddenly "become" or behave as a non-family app only because it uses a different flow.

The other way, "(for the app/sdk) to set AppMetadata only in response to `AcquireTokenInteractive` and `AcquireTokenSilent`", looks like a workaround; and it essentially means the client-side explicitly chooses to consider all other flows do not have foci behavior. Such a choice is not aligned to the intrinsic foci nature, and it would become fragile/incorrect, when the service side potentially/eventually introduces foci behavior for other flows in the future.

**Comment by jmprieur** [comment]
@bgavrilMS : I believe you had proposed a work around? or do thing need to change service side?

**Comment by bgavrilMS** [comment]
This is something that EVO needs to implement.

**Comment by jmprieur** [comment]
Done for MSA.
AAD in progress.

to be tested.

**Comment by bgavrilMS** [comment]
Not currently in production. Tracking issue https://identitydivision.visualstudio.com/Engineering/_workitems/edit/781973

**Comment by bgavrilMS** [comment]
This has been resolved - Integrated Windows Auth returns the FOCI flag. I've tested the End to End.

**Comment by jmprieur** [comment]
Thanks @bgavrilMS

**Comment by rayluo** [comment]
Confirmed with Bogdan, "FOCI is now returned in Integrated Windows Auth. (we) do not expect any client-side changes".
