### ISSUE TITLE
IConfidentialClientApplication.GetAccounts() does not return any accounts if static In-Memory-TokenCache was reset 

### ISSUE THREAD

**Issue by nweseloh** [AzureAD/microsoft-authentication-library-for-dotnet#1300]
**Which Version of MSAL are you using ?**
MSAL 4.2.1

**Platform**
.NET Core

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [x] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**

1. Clone the sample: https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp.git
2. Checkout the jennyf/msal4.1  branch 
3. update NuGet package to MSAL 4.2.1
4. Run the sample
5. Sign in 
6. Stop the sample. This clears the static in-memory token cache (MSALStaticCache).
7. Run the sample again 
8. Note that you'll be shown as 'Signed In' (cookies are still valid), /Home/About shows correct claims  (auth cookie still exists)
9. Call /Home/Api 
10. IConfidentialClientApplication.GetAccountsAsync() does not return any account 
11. In consequence, cca.AcquireTokenSilent throws an MsalUiRequiredException when called with account parameter = 'null' 
12. User needs to log in again to acquire a new access token for the API. 

Repro code: line 48 ff. in
https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp/blob/master/WebApp-OpenIDConnect-DotNet/Controllers/HomeController.cs 

```csharp
var scope = AzureAdB2COptions.ApiScopes.Split(' ');
string signedInUserID = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;

IConfidentialClientApplication cca =
    ConfidentialClientApplicationBuilder.Create(AzureAdB2COptions.ClientId)
        .WithRedirectUri(AzureAdB2COptions.RedirectUri)
        .WithClientSecret(AzureAdB2COptions.ClientSecret)
        .WithB2CAuthority(AzureAdB2COptions.Authority)
        .Build();
    new MSALStaticCache(signedInUserID, this.HttpContext).EnablePersistence(cca.UserTokenCache);

    var accounts = await cca.GetAccountsAsync();
                
    AuthenticationResult result = await cca.AcquireTokenSilent(scope, accounts.FirstOrDefault())
        .ExecuteAsync();
```

**Expected behavior**
ConfidentialClientApplication retrieves a valid account (and, afterwards, a fresh access token) if user is still authenticated by cookie (even if the static cookie cache was refreshed & the user tokens are no longer in cache) 

**Actual behavior**
User is required to re-login at b2clogin.com in order to acquire a new access token.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Please fix the IConfidentialClientApplication implementation or update the sample code - to show how to avoid this issue in demo code. 
I am aware that we could avoid this by using a persistent cache (SQL Server etc.) in production, but we prefer simple in-memory caching for demo apps.

**Comment by jmprieur** [comment]
@nweseloh : As you wrote yourself, if you use an in-memory cache, then each time the app is restarted, the memory is lost. 

We have been providing all kind of caches in this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-2-TokenCache, and we advise you rather look at that sample which already shows how to sign-in with B2C. (calling a Web API from the signed-in app is coming): See https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C

cc: @TiagoBrenck @kalyankrishna1
