### ISSUE TITLE
[Bug] Perf degradation in Confidential Client flow

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1301]
Copy of
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1630

Evaluate if this issue also exists in MSAL

ADAL version: 5.0.5
ADAL version where this doesn't repro: 3.13.7

```csharp
X509Certificate2 aadCert = CertificateManager.Instance.FindCertificateByThumbprint(AAD_CERT_THUMBPRINT, StoreName.My);
ClientAssertionCertificate clientAssertionCert = new ClientAssertionCertificate(WebAppClientId, aadCert);
UserAssertion userAssertion = new UserAssertion(userAccessToken, USER_ASSERTION_TYPE, userName);
result = await authContext.AcquireTokenAsync("https://graph.microsoft.com", clientAssertionCert, userAssertion);
```

Our most recent deployment shows that dependency call as taking longer and longer over time, eventually resulting in our service being unable to handle any more requests. Strangely enough other calls to AcquireTokenAsync, for other resources don’t seem to exhibit that behavior. 

We noticed the below O(n*m) loop that was added 4 months ago to Microsoft.IdentityModel.Clients.ActiveDirectory (https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/commit/034f0876ccf4f478ff4eefc462af07628c0497fb), it seems like a good performance opportunity as accounts is literally getting constructed a few lines earlier as a List and constructing it as a Dictionary instead would provide O(n+m) performance.

Note - in the code above, the customer notices they have some 2000+ accounts  (line 107).

**Comment by bgavrilMS** [comment]
Following up with the customer, this needs more investigation. Most likely  external.

**Comment by bgavrilMS** [comment]
As discussed with customer, this occurs in ADAL when the default Shared cache is used. MSAL does not have this concept - by default a new in-memory TokenCache is used per PCA or CCA instance.
