### ISSUE TITLE
[Bug] Set exception on TCS so it is thrown in correct place

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1304]
**Which Version of MSAL are you using ?**
MSAL 3.0.8, MSAL 4.2.1

**Platform**
Net45

Set exception on TCS so it is thrown in correct place given VS/Watson crash reports.

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1302

**Comment by jennyf19** [comment]
Included in [4.3.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.3.0) release
