### ISSUE TITLE
Customize the Embedded WebView screens in Xamarin

### ISSUE THREAD

**Issue by joemather** [AzureAD/microsoft-authentication-library-for-dotnet#1308]
How do we customize the embedded webview screens in Xamarin.Android and Xamarin.iOS?

Specifically, I'd like a top bar that matches the styling of the other screens in my app.

On Android, AuthenticationAgentActivity doesn't have a support Toolbar and there doesn't seem to be a way to add one.  On iOS, MsalAuthenticationAgentUINavigationController is there, but it doesn't seem customizable.

I don't want to change anything about the webview itself.  But I would like to customize the controls around it.  Is this possible?

**Comment by henrik-me** [comment]
@joemather : We currently do not support customizations and have no current plans of doing this. Can you pls. share a bit more on what kind of customizations you would like, e.g. as Mocks?

CC: @jmprieur

**Comment by jennyf19** [comment]
@joemather If you're looking to customize the UI, you can look into [AAD B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/) which allows you to customize the log-in screen. Not sure if that is an option for you though.
