### ISSUE TITLE
[Feature Request] More Docs/Explanation on Logging - Add Logging Result Samples

### ISSUE THREAD

**Issue by FrankHu-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#1311]
**Is your feature request related to a problem? Please describe.**
**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

No, this is not related to an issue. This is a doc feature request asking for more information in regards to the logging. Could you all please provide more information in regards to logging? For example some sample logs of what the result of the logging would end up looking like? 

**Describe the solution you'd like**
**A clear and concise description of what you want to happen.**

Just some logging examples and possibly some more information in regards to how to save the logs and how the default logging works. Does this need to be implemented by the user utilizing the MSAL library or is this done by default by the library?

**Describe alternatives you've considered**
**A clear and concise description of any alternative solutions or features you've considered.**
N/A

**Additional context**
**Add any other context or screenshots about the feature request here.**

Git Reference : https://github.com/MicrosoftDocs/azure-docs/issues/35898

**Comment by bgavrilMS** [comment]
I updated our wiki with more details, including example logs 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging
