### ISSUE TITLE
On behalf of flow returning AADSTS50013: Assertion failed signature validation

### ISSUE THREAD

**Issue by msminski** [AzureAD/microsoft-authentication-library-for-dotnet#1317]
Hi:
We have been trying to make a transition from ADAL to MSAL.

While validating my On-Behalf-Of flow, our call was returning "Assertion failed signature validation."

Full error message from the call:
{"AADSTS50013: Assertion failed signature validation. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: 'FAA38DEAC2FDDFC470BFCE7449B7BF597C50AED3', Found key 'Start=06/21/2019 00:00:00, End=06/21/2021 00:00:00']\r\nTrace ID: 1f8d9f66-072e-4b77-8b49-84182f413000\r\nCorrelation ID: ae332ee3-77ee-42c8-85a4-ea2593af7542\r\nTimestamp: 2019-08-02 20:42:53Z"}

Details about the call:
1. We are making this call using ConfidentialClientApplication.
2. UserAssertion we pass in for AcquireTokenOnBehalfOf is created using the RootAccessToken we've obtained using via AcquireTokenByAuthorizationCode. 
3. Using jwt decoder, I could tell we are getting V1 token from AuthCode flow.
4. Our test app is using Office Roaming cert and client id, and scope used for on-behalf-of flow is another service we own(Office Recent Document)

Please let me know if other details would be helpful.
Thanks in advance

[Posted content of token, request and response were removed as it did contain our test account email, ip address. Keeping the removed content in separate space to investigate if it could be problematic.]

**Comment by jmprieur** [comment]
@msminski : please contact "Identity DevEx DotNet Team" directly as this is 1P.

**Comment by jmprieur** [comment]
@msminski : the user assertion you are using is a token for Graph (the scope (scp) is "user.read"). You need to pass-in a token for the Web API that performs the On-behalf-of flow. Please see https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

**Comment by msminski** [comment]
Thanks @jmprieur 
I will make sure to contact above alias next time.
Will go through the documentation you've posted and then contact the alias if I need further clarification.

**Comment by jmprieur** [comment]
@msminski : I'm assuming this is working fo you and therefore closing. Feel free to reopen if I'm wrong
