### ISSUE TITLE
Azure AD Single Tenant not working

### ISSUE THREAD

**Issue by robiharid** [AzureAD/microsoft-authentication-library-for-dotnet#1319]
I am trying to sign onto my Xamarin app using my @company.com email address. However, signing in gives me this issue:

Message:  AADSTS50194: Application 'id'(AppName) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant. 

My App Registration has the app profile set to a single tenant. Why is it asking me for multi-tenant access for emails within the same org directory?

How can I see what email address single-tenant allows, as I want to check if there are any discrepancies between azure

**Comment by bgavrilMS** [comment]
Hmm, I'm not sure I saw this error before. If you go to your application registration, have a look at the manifest, what does the signInAudience say? 

`	"signInAudience": "AzureADandPersonalMicrosoftAccount",`

Also, are you allowed to change this value from the UI? 

![image](https://user-images.githubusercontent.com/12273384/62532901-5e880880-b83d-11e9-8d6a-408eafea0df5.png)




**Potential solution**

 Anyway, to get back to your issue, in MSAL, configure a tenanted authority instead of `common`. You'll find the tenant id in the portal (it's a guid). 

```charp
 IPublicClientApplication pca = PublicClientApplicationBuilder
                            .Create("<client-id>)
                            .WithAuthority(AzureCloudInstance.AzurePublic, "<your-tenant-id>")
                            .Build()
```

**Comment by bgavrilMS** [comment]
You can find out more about authorities here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#authority-instance--audience

**Comment by robiharid** [comment]
> `"signInAudience": "AzureADandPersonalMicrosoftAccount",`

Perfect, thank you!

The signInAudience originally said AzureADMyOrg, I had to change to ADandPersonal but now it is back to MyOrg after I used your fix!

Side question: Where can I change the Access Token expiration? Is this done from App Registrations? 

My code looks like this:
`
                    if (TokenForUser == null || expiration <= DateTimeOffset.UtcNow.AddMinutes(5))
                    {

                        authResult = await App.IdentityClientApp
                            .AcquireTokenInteractive(App.Scopes)
                            .WithParentActivityOrWindow(App.ParentWindow)
                            .ExecuteAsync();

            TokenForUser = authResult.AccessToken;
            expiration = authResult.ExpiresOn;
                    }
`

**Comment by bgavrilMS** [comment]
I am not sure where you can change that, but I don't think you should worry too much: 

- MSAL will handle token expiration for you, you don't even need to check
- MSAL will use a refresh token to fetch brand new access tokens silently as long as you call `AcquireTokenSilent`

Check https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token#recommended-call-pattern-in-public-client-applications for details

**Comment by bgavrilMS** [comment]
Closing the issue for now, feel free to reopen if the original ask is giving you problems
