### ISSUE TITLE
Invalid object identifier accessing members list in Graph groups

### ISSUE THREAD

**Issue by robiharid** [AzureAD/microsoft-authentication-library-for-dotnet#1321]
I am trying to read the list of users in my organization. 

I have successfully authenticated as a user in my organization through the AcquireTokenInteractive method. and I am passing in my AuthProvider to the GraphClient.

I get the error: Invalid Object Identifier following the docs here: https://docs.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-1.0&tabs=csharp

My code:

`_graphClient = AuthenticationHelper.GetAuthenticatedClient();

                var members = await _graphClient.Groups["{id}"].Members.Request()
                    .GetAsync();`

Error:

> exception={"Code: Request_BadRequest\r\nMessage: Invalid object identifier '{id}'.\r\n\r\nInner error\r\n"}

Is this app permission issue? Do I need Directory.AccessAsUser.All admin permissions? Is it possible to read all org data as a normal user?

**Comment by jmprieur** [comment]
If you want to read all the users in your org, you'll probably want to use Users.ReadBasic.All, and use the /users ? 

BTW this is not an MSAL.NET question, but a Microsoft Graph question ...

**Comment by robiharid** [comment]
> If you want to read all the users in your org, you'll probably want to use Users.ReadBasic.All, and use the /users ?
> 
> BTW this is not an MSAL.NET question, but a Microsoft Graph question ...

Thank you very much - apologies for mixing it up. Will post next time in Graph github. The users list is currently only retrieving 100 users. We can page data through the query string (https://docs.microsoft.com/en-us/graph/paging) but how can we do that through C#?

`
                var users = await _graphClient.Users
                    .Request()
                    .GetAsync();`

**Comment by jmprieur** [comment]
closing as this is not an MSAL.NET issue
