### ISSUE TITLE
[Bug] Claims not sent to /authroize endpoint 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1328]
**Which Version of MSAL are you using ?**
4.3

**Platform**
all

**Problem**
According to the OIDC spec https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter claims is a parameter relevant to the /authorize endpoint. 

MSAL only sends this param to the /token endpoint. 

```csharp
pca.AcquireTokenInteractive(...).WithClaims(claims);
```

Actual: claims param sent in request to the **/token** endpoint but not to the **/authorize** endpoint
Expected: claims param needs to be sent to both

**Comment by bgavrilMS** [comment]
Spec on claims: https://identitydivision.visualstudio.com/DefaultCollection/IDDP/_git/first-party-docs/pullrequest/537?_a=files&path=%2Fdocfx-src%2Fdevex%2Fsdks%2Fclientcapabilities.md
 
Claims should actually be sent to both /authorize and /token endpoints

**Comment by jmprieur** [comment]
@bgavrilMS @henrik-me @shoatman : does it have an impact on AdditionalClaimsToConsentTo?

**Comment by jmprieur** [comment]
makes MSAL.NET OIDC compliant

**Comment by henrik-me** [comment]
Included in the 4.4.0 release
