### ISSUE TITLE
[Bug] Passwordless Experience not working when .WithLoginHint() used

### ISSUE THREAD

**Issue by rhep49** [AzureAD/microsoft-authentication-library-for-dotnet#1329]
**Which Version of MSAL are you using ?**
MSAL v4.3.0

**Platform**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
This is a new app or experiment

**Repro**

Prerequisite: User being logged in has the new "Passwordless" experience enabled and configured in their tenant.

```csharp
 publicClientApplication = PublicClientApplicationBuilder.Create(ClientId).Build();

            // username is in email format
            var result = await publicClientApplication.AcquireTokenInteractive(scopes)
                                                      .WithPrompt(Prompt.ForceLogin)
                                                      .WithLoginHint(username)
                                                      .ExecuteAsync();
```

**Expected behavior**
1. MSAL window to should open with users email pre-populated (may need to select work/school account or personal)
2. User should be shown a number to verify on their MS authenticator app
3. Once verified via the app the user should be logged in.

**Actual behavior**
1. MSAL window to opens with users email pre-populated (may need to select work/school account or personal)
2. User is prompted for a password
3. Once password is entered, user must grant access via MS authenticator app.
4. After confirming access in app, user is logged in.

**Possible Solution**
If Passwordless authentication is not supported with the .WithLoginHint() method documentation should reflect this.

**Additional context/ Logs / Screenshots**
The Passwordless experience works as expected when a login hint is not provided.

**Comment by bgavrilMS** [comment]
@rhep49 - does this work as expected when you do not set .WithLoginHint ?

**Comment by bgavrilMS** [comment]
Or when you do not set .WithPrompt(ForceLogin) ?

**Comment by rhep49** [comment]
@bgavrilMS  Passwordless does not work when the .WithLoginHint() method is used. If i exclude the method call (see below) the Passwordless experience works as expected.
```
 publicClientApplication = PublicClientApplicationBuilder.Create(ClientId).Build();

            // username is in email format
            var result = await publicClientApplication.AcquireTokenInteractive(scopes)
                                                      .WithPrompt(Prompt.ForceLogin)
                                                      .ExecuteAsync();
```

**Comment by bgavrilMS** [comment]
Is this the recommended pattern to enable passwordless? Is this documented?

I am asking because the authentication flow is handled by AAD directly, MSAL is just hosting the browser. I will need to log a bug on the service for this.

**Comment by rhep49** [comment]
Passwordless is still in preview: 
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-authentication-passwordless-phone

I haven't seen any documentation in regards to recommended patterns for passwordless & the interactive flow.

**Comment by bgavrilMS** [comment]
So if you exclude the param, it will be set to Prompt.SelectAccount by default, i.e. the user will be presented with a list of accounts and they have to select one. Potentially they will skip authentication because they have already authenticated and there is a browser cookie to prove it (it's all secure). 

If I understand correctly, your scenario is that you want users to ALWAYS perform authentication, but not have to enter passwords?

**Comment by rhep49** [comment]
Yes, our goal is to provide a Passwordless authentication experience with minimal interaction for a user known to our system. Our software runs on a shared computer and we do not want to remember user credentials for security reasons.

Example Scenario:
1. We obtain a username from a separate process in our application (user scans smart card and we map it to a username for example)
2. We call the MSAL library to authenticate (with the login hint)
3. User selects the number displayed by AAD on their phone
4. User is granted access

**Comment by rhep49** [comment]
I was able to reproduce the issue calling AAD directly via Chrome. If I pass login_hint in the URL I am prompted for a password.

[https://login.microsoftonline.com/<TenantID>/oauth2/authorize?
client_id=<ClientID>
&response_type=id_token
&redirect_uri=http%3A%2F%2Flocalhost%3a12345
&response_mode=form_post
&scope=openid
&state=12345
&login_hint=<passwordless enabled user email>
&nonce=7362CAEA-9CA5-4B43-9BA3-34D7C303EBA7](url)


If I remove the login_hint parameter I am asked for username/email but then the passwordless experience executes as expected.

[https://login.microsoftonline.com/<TenantID>/oauth2/authorize?
client_id=<ClientID>
&response_type=id_token
&redirect_uri=http%3A%2F%2Flocalhost%3a12345
&response_mode=form_post
&scope=openid
&state=12345
&nonce=7362CAEA-9CA5-4B43-9BA3-34D7C303EBA7 ](url)

**Comment by bgavrilMS** [comment]
Makes sense @rhep49 - I created a bug on the internal tracker on the AAD service. I'll keep the thread updated once they reply.

**Comment by bgavrilMS** [comment]
I managed to track down the engineering team responsible for Passwordless and they are aware of the issue and it is on their backlog. I'll update this thread when I learn about updates. 

Consider finding an workaround like not using login_hint until then. Or log an ICM Incident if you'd like to escalate this.

**Comment by jennyf19** [comment]
@rhep49 still waiting for sever side. 
@bgavrilMS will update the thread.

**Comment by henrik-me** [comment]
P3 as we can't fix this in the library.

**Comment by tFable** [comment]
Hey @henrik-me , @bgavrilMS . We are still observing this issue. Is this on the radar to fix in the near future?

Our use case is Managed Apple ID's ("Apple ID for Business".) Passwordless is skipped and we need to login with the Password flow. When doing a trace, it looks like Apple is including the "login_hint=" as a query parameter when POSTing to Azure AD.

**Comment by bgavrilMS** [comment]
@tFable - I see the issue on the AAD service on our internal tracker and I asked for an update.

**Comment by bgavrilMS** [comment]
We do not have the capacity track service issues using this GitHub issues page. This enhacement has been worked on and is possibly fixed by now. Please open issues directly on the service from the Azure Portal support pages.
