### ISSUE TITLE
[Bug] CCA CreateWithApplicationOptions forces use of ClientSecret, won't allow just Certificate usage

### ISSUE THREAD

**Issue by dilansudharaka** [AzureAD/microsoft-authentication-library-for-dotnet#1332]
**Which Version of MSAL are you using ?** 4.3.0

**Platform**
net46

**What authentication flow has the issue?**
 Web App
    * [ ] Authorization code

**Is this a new or existing app? Existing single tenant app. We were using ADAL so far, and working on migrating to MSAL.

**Repro**
We use OIDC and we do not have clientsecrets, instead we use certificates. So do not pass ClientSecret in the request.

Receives the ID Token first. 
Then try to get Access Token using the IDToken. However getting the below error.
{"Value cannot be null.\r\nParameter name: clientSecret"}

at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithClientSecret(String clientSecret)
   at AadOnboarding.Core.MsalOpenIdAuthenticationOptionFactory.<>c__DisplayClass28_0.<GenarateAuthenticationOptionForEnvironment>b__4(AuthorizationCodeReceivedNotification context) in E:\GIT\AD\AppModel\src\AadOnboarding\AadOnboarding\Core\MsalOpenIdAuthenticationOptionFactory.cs:line 268
   at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__1a.MoveNext()

```csharp
ConfidentialClientApplicationOptions confidentialClientoptions = new ConfidentialClientApplicationOptions()
                        {
                            ClientId = clientId,
                            TenantId = tenantId,
                            AadAuthorityAudience = AadAuthorityAudience.AzureAdMyOrg,
                            LogLevel = LogLevel.Verbose,
                            RedirectUri = this.GetRedirectUrl()
                        };
X509Certificate2 clientCert = this.authClient.GetCertificate(graphcertName);
IConfidentialClientApplication app = ConfidentialClientApplicationBuilder
                                .CreateWithApplicationOptions(confidentialClientoptions)
                                .WithAuthority(environmentAuthorityUrl, true)
                                .WithCertificate(clientCert)
                                .Build();

**Expected behavior**
I am expecting receive Access Token.

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes  

**Possible Solution**
<!--- Only if you have suggestions on a fix for the bug -->

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by MarkZuber** [comment]
This looks like it's a bug with the CreateWithApplicationOptions where we force a ClientSecret usage.

**Comment by bgavrilMS** [comment]
I agree, @dilansudharaka - can you try to use the Builder for all those options. There are methods on the builder for each of them (.Create(<clientID>), .WithRedirectUri, .WithAudience, .WithLogging)

**Comment by bgavrilMS** [comment]
MSAL 4.3.1 released
