### ISSUE TITLE
[Bug] NameNotFoundException: com.android.chrome

### ISSUE THREAD

**Issue by Skirtek** [AzureAD/microsoft-authentication-library-for-dotnet#1334]
**Which Version of MSAL are you using ?**
MSAL v4.0.0

**Platform**
Xamarin Forms 4.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
The app is in production, and I have not upgraded to a new version of MSAL

**Repro**
1. Uninstall Chrome from rooted device
2. Try to log in/register in mobile app which is using MSAL library

**Expected behavior**
Method IsChromeEnabled should not throw exception and return false which should force open system browser.

**Actual behavior**
When user hasn't Chrome on his phone PackageManager throws NameNotFoundException: com.android.chrome. I can't uninstall Chrome on any device, so I'm a little bit scared that this user can not log in into application. 

**Possible Solution**
Method IsChromeEnabled in AndroidPlatformProxy should catch exception and return false

**Comment by bgavrilMS** [comment]
Are you sure it's the Username / Password flow that you're using here? I'm pretty sure we don't call IsChromeEnabled except on Interactive flow. Username / Password is when your app collects the credentails on its own and passes them to MSAL (we discourage this for security reasons).
