### ISSUE TITLE
[Bug] Java.Net.SocketException: Socket closed

### ISSUE THREAD

**Issue by Skirtek** [AzureAD/microsoft-authentication-library-for-dotnet#1336]
**Which Version of MSAL are you using ?**
MSAL v4.0.0

**Platform**
Xamarin Forms 4.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
The app is in production, and I have not upgraded to a new version of MSAL

**Repro**
1. Just try to log in/register in mobile app which is using MSAL library. Non-deterministic error.

**Expected behavior**
Every method which uses socket should not use it after closing it. 

**Actual behavior**
Some method is trying to access socket after closing it which throws Java.Net.SocketException: Socket closed. I'm worry that user is not able to log in into app.

**Additional informations**
Stack trace - https://pastebin.com/raw/S0nmcXSJ

**Comment by bgavrilMS** [comment]
Hi @Skirtek - that exception seems to come from deep in the Android code. I believe it is indicative of a temporary network failure. MSAL just uses an HttpClient to contact AAD.

I suggest you add a retry policy before calling MSAL (pretty much any call that you need to await potentially accesses the network).

**Comment by bgavrilMS** [comment]
This may also be helpful: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/exceptions#retry-policy

**Comment by Skirtek** [comment]
Thank you for your advice! Should I use method from library, write my own method or configure something in Azure?

**Comment by bgavrilMS** [comment]
MSAL doesn't offer retry policies and AAD doesn't offer this kind of functionality, so I would write my own. There are some good open source ones, e.g. Polly.
