### ISSUE TITLE
Implementing permanent/persistent cookies in MSAL 4.x

### ISSUE THREAD

**Issue by youdhbir** [AzureAD/microsoft-authentication-library-for-dotnet#1340]
We're in the process of migrating from using ADAL to MSAL for asp.net core web application (.net core 2.2) and have a requirement to persist authentication cookie. We could do it in ADAL by setting expiry on sign in event like below but similar implementation in MSAL is not working. Can you please guide. Thanks.

ADAL Implementation:
------------------------
            services.AddAuthentication(sharedOptions =>
                {
                    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                })
                .AddAzureAd()
                .AddCookie(options =>
                {
                    options.Events.OnSigningIn = (context) =>
                       {
                           context.CookieOptions.Expires = DateTimeOffset.UtcNow.AddDays(_settings.CookieExpiryInDays);
                           return Task.CompletedTask;
                       };
                });
-------------------------------

MSAL Implementation:
-----------------
   services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => configuration.Bind("AppSettings:AzureAd", options))
                .AddCookie(options =>
                {
                    options.Events.OnSigningIn = (context) =>
                    {
                        context.CookieOptions.Expires = DateTimeOffset.UtcNow.AddDays(_settings.CookieExpiryInDays);
                        return Task.CompletedTask;
                    };
                });

**Comment by bgavrilMS** [comment]
@kalyankrishna1 @TiagoBrenck  - is this something you ran into ?

**Comment by jmprieur** [comment]
@youdhbir did you set the session cookie as essential?

```CSharp
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<CookiePolicyOptions>(options =>
    {
        options.CheckConsentNeeded = context => true; // consent required
        options.MinimumSameSitePolicy = SameSiteMode.None;
    });

    services.AddSession(opts => 
    {
        opts.Cookie.IsEssential = true; // make the session cookie Essential
    });
   ...
```

**Comment by TiagoBrenck** [comment]
@bgavrilMS  I haven't run into this yet

**Comment by youdhbir** [comment]
Hi @jmprieur - I tried after your suggestion but it's still generating session cookies. Even, debug doesn't hit this line of code.

services.Configure<CookiePolicyOptions>(options =>
    {
        options.CheckConsentNeeded = context => true; // consent required
        options.MinimumSameSitePolicy = SameSiteMode.None;
    });

services.AddSession(opts =>
            {
                opts.Cookie.IsEssential = true; // make the session cookie Essential
                opts.Cookie.Expiration = TimeSpan.FromDays(15); //add date expiry
            });

**Comment by bgavrilMS** [comment]
@jmprieur - can you help? I am not familiar with cookie config

**Comment by dennisbappert** [comment]
The referenced article explains on how to set the cookie options by implementing SignInAsync which is part of the [RemoteAuthenticationHandler ](https://github.com/aspnet/AspNetCore/blob/d8381656429addead2e5eb22ba1356abfb419d86/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs) class (line 140). You can modify the passed AuthenticationProperties by implementing the OnTicketReceivedHandler:

```csharp
OnTicketReceived = context =>
{
    context.Properties.IsPersistent = true;
    context.Properties.ExpiresUtc = DateTimeOffset.UtcNow.AddDays(7);

    return Task.FromResult(0);
}
```

**Comment by youdhbir** [comment]
Thanks a lot @dennisbappert. It worked.
