### ISSUE TITLE
[Bug] OBO flow always tries to get a token from the cache

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1349]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
4.3.1

**Platform**
ConfidentialClient

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [x] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**

```csharp
// All our samples suggest to use the pattern ATS then OBO i.e. 
try 
{
 // AcquireTokenSilent ...
}
catch 
{
 // AcquireTokenOnBehalfOf
}

```

**Expected behavior**
AcquireTokenOnBehalfOf should never look in the token cache

**Actual behavior**
AcquireTokenOnBehalfOf looks in the cache for an AT, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/46c7ab85572de6e5fcdd5fd794d0d47069b62720/src/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs#L41

The comment there is 
```
            // look for access token in the cache first.
            // no access token is found, then it means token does not exist
            // or new assertion has been passed. We should not use Refresh Token
            // for the user because the new incoming token may have updated claims
            // like mfa etc.
```

**Comment by bgavrilMS** [comment]
@henrik-me @jmprieur @jennyf19 - as far as I remember calling OBO without AcquireTokenSilent works fine for our customers.

OBO will make a specialized search in the cache, as it searches for an access token associated with the current assertion. I am not sure we should be calling AcquireTokenSilent here, we even have a comment in our code explaining the reason why AcquireTokenSilent is discouraged: 

`Look for access token in the cache first.
 If no access token is found, then it means token does not exist
 or new assertion has been passed. 
 We should not use Refresh Token
 for the user because the new incoming token may have updated claims
 like mfa etc.`

@yordan-msft - could you advise on this matter please?

**Comment by bgavrilMS** [comment]
CC @SomkaPe as you've looked at OBO in detail

**Comment by yordan-msft** [comment]
I thought we had a plan to address this issue. Basically need to make sure that tokens in the cache are obtained using same access token. 
Did something change?

**Comment by jmprieur** [comment]
This is what Microsoft.Identity.Web does, @yordan-msft 
but not MSAL.

**Comment by bgavrilMS** [comment]
If we use AcquireTokenSilent pattern, token in the cache will be used irrespective of the original access token. Our samples showcase this. 

If we use AcquireTokenOBO, MSAL.NET will query the cache like AquireTokenSilent but will also use `hash(original_access_token)` for the lookup.

If we were to fix this issue, we should make `AcquireTokenSilent` not return OBO access tokens (these have an assertion hash associated). I believe this is not a breaking change. 

@jmprieur - thoughts?

**Comment by yordan-msft** [comment]
Makes sense to me. That's why AcquiteTokenOBO exists, right?

**Comment by bgavrilMS** [comment]
@jmprieur, @henrik-me - this will require a 2 phase effort: 

1. Update Microsoft.Identity.Web to no longer use AcquireTokenSilent (this can be done today).  CC @jennyf19 
2. Update the docs to state that AcquireTokenOBO should not be used in conjuction with AcquireTokenSilent

**Comment by SomkaPe** [comment]
As far as I remember Microsoft.Identity.Web do cache look up based on incoming access token.
In the same way as web application do cache lookup based on session id.
I do not think that persisting all tokens for client application in one cache instance is a viable option because : 
1. Obo service can be used by applications on behalf of thousands or even millions of users.
2. Msal cache is not capable of handling so many users : 
 a. frequent serializations | de-serializations 
 b. cache lookup is O(N)

That is why filtration of entities in cache based on incoming access token is not a good pattern.
Instead cache should be persisted per incoming access token, which works fine with silent + interactive calls pattern

@jennyf19  @henrik-me @jmprieur  @yordan-msft
