### ISSUE TITLE
Incorrect DeviceFlow Wiki Sample

### ISSUE THREAD

**Issue by martinstenhoff** [AzureAD/microsoft-authentication-library-for-dotnet#1350]
### Documentation Related To Component:
MSAL .NET DeviceFlow Wiki Sample

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue
The Device Flow sample code on the Wiki page [Device Code Flow](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow) is incorrect. Regardless of whether app.AcquireTokenSilent is successful or not it's followed by a call to app.AcquireTokenWithDeviceCode.

```
// All AcquireToken* methods store the tokens in the cache, so check the cache first
 try
 {
  result = await app.AcquireTokenSilent(scopes, accounts.FirstOrDefault())
       .ExecuteAsync();
  // MISSING A "return result;" HERE
 }
 catch (MsalUiRequiredException ex)
 {
  // A MsalUiRequiredException happened on AcquireTokenSilent. 
  // This indicates you need to call AcquireTokenInteractive to acquire a token
  System.Diagnostics.Debug.WriteLine($"MsalUiRequiredException: {ex.Message}");
 } // SHOULD NOT END THE BLOCK HERE AS WE WANT TO DO AcquireTokenWithDeviceCode INSIDE THIS BLOCK

 try
 {
  result = await app.AcquireTokenWithDeviceCode(scopes,
      deviceCodeResult =>
  {
...
```

**Comment by bgavrilMS** [comment]
I've updated the wiki, please have a look.

**Comment by bgavrilMS** [comment]
I've updated the wiki, please have a look.

**Comment by martinstenhoff** [comment]
Yes, looks correct now.
