### ISSUE TITLE
[Feature Request] Add Interactive Login Error Handling

### ISSUE THREAD

**Issue by FrankHu-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#1355]
**Is your feature request related to a problem? Please describe.**

The feature being requested is for the AcquireTokenInteractive method to have some sort of overloaded method that can handle errors that are being thrown back from ESTS in the webview/browser. 

MSDN Thread Reference : https://social.msdn.microsoft.com/Forums/en-US/cf5149a5-05c6-4ba1-9295-f561a4edd3b9/microsoft-interactive-signin-returning-error-to-caller-instead-of-showing-it-to-the-user?forum=WindowsAzureAD

**Describe the solution you'd like**

Some implementation so that there is more control over the user experience during the interactive login flow. 

**Describe alternatives you've considered**

The exceptions wiki page's implementations for error handling have been considered per the msdn thread. Also explained is handling the error being thrown after the user has navigated back to the application. 

**Additional context**

It could be possible to scrape the URL from the browser during the login process to handle if it contains an AADSTS error right? It should be possible to handle when an aadsts error is returned from the browser. Although the solution wouldn't be very elegant.

**Comment by jmprieur** [comment]
@henrik-me @SaeedAkhter-MSFT : we should have a discussion with the service on how we can let MSALs get the errors that are shown in the UI, but not surfaced in MSALs because there is no service exception => MSAL just returns a "User canceled" exception when the end user closes the popup Windows.

To repro, for instance, use an inexisting clientID.

**Comment by henrik-me** [comment]
I think this makes sense. Would like to explore ideas for how evo would provide this information to the libraries regardless of "browser" (embedded vs. system vs. broker). I suppose temporarily for the embedded web view we could dump the html to the log. More likely we would have to be able to make a call to evo to suppose non embedded browser scenarios. Sounds like a fun conversation.

**Comment by bgavrilMS** [comment]
Not an MSAL issue, as there is no server side support.
