### ISSUE TITLE
On premises example: authenticate & get claims from ADFS using ASP.NET core with MSAL.NET

### ISSUE THREAD

**Issue by SumeetABB** [AzureAD/microsoft-authentication-library-for-dotnet#1356]
### Documentation Related To Component:
MSAL.NET on premises example

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
On premises example to authenticate & get claims from ADFS using ASP.NET core with MSAL.NET.

**Comment by jennyf19** [comment]
fyi: @jmprieur

**Comment by jmprieur** [comment]
Duplicate of https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/171
