### ISSUE TITLE
Xamarin.Forms UI Test app.WaitForElement always times out

### ISSUE THREAD

**Issue by markti** [AzureAD/microsoft-authentication-library-for-dotnet#1359]
**Which Version of MSAL are you using ?**
MSAL 4.2.1 

**Platform**
Xamarin.Forms

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
New app, login works but trying to add UI Test Automation.

**Repro**
Try and add a simple UI Test that tapes the logonIdentifier input tag and enters an email

```csharp
        [Test]
        public void RegistrationStarts()
        {
            app.Screenshot("Welcome screen.");

            app.WaitForElement(c => c.WebView());
            app.Tap(c => c.WebView().Css("input#logonIdentifier"));
            app.EnterText("sample@example.com");

        }
```

**Expected behavior**
Username field should populate with "sample@sample.com"

**Actual behavior**
app.WaitForElement(c => c.WebView()); Times out

**Comment by jennyf19** [comment]
@markti - which platform is having the issue? are you using AppCenter? AppCenter tests can only run w/the embedded webview, not system browser.

**Comment by jmprieur** [comment]
@markti , do you have an update?

**Comment by henrik-me** [comment]
@markti: Closing. Please re-open if this issue persists
