### ISSUE TITLE
[Feature Request] Android shared_prefs should not be used with plain text.

### ISSUE THREAD

**Issue by awasilik** [AzureAD/microsoft-authentication-library-for-dotnet#1361]
**Is your feature request related to a problem? Please describe.**
Android app security is compromised by storing access and refresh token in SharedPreferences as plain text documents.

**Describe the solution you'd like**
Tokens should be encrypted like in example github [Secure Preferences](https://github.com/ophio/secure-preferences)

**Describe alternatives you've considered**
Tokens should not be stored in SharedPreferences, instead there could be used more secure place such as AccountManager.

**Additional context**
Tokens are now stored in:
 /data/data/<package_name>/shared_prefs 

com.microsoft.identity.client.accessToken.xml
com.microsoft.identity.client.refreshToken.xml

**Comment by jmprieur** [comment]
+ @shoatman FYI

**Comment by bgavrilMS** [comment]
This should really be opened on the [MSAL Android](https://github.com/AzureAD/microsoft-authentication-library-for-android) GitHub page to get traction - the decisions around token caching are taken by the Android team. 

The current thinking is that SharedPreferences files are only available to the app and to any admin (sudo) user. 

Is there an attack pattern that was identified?

**Comment by awasilik** [comment]
Our pen testers team identified this issue as vulnerability which could potentially expose sensitive user data. We do not need admin access to retrieve those tokens.

**Comment by jmprieur** [comment]
@shoatman : do you plan to do something on MSAL.Android? (@awasilik : we need to have SSO between the MSAL libraries)

**Comment by bgavrilMS** [comment]
Decision is to open up custom token cache serialization, similar to how we do it on UWP.

**Comment by bgavrilMS** [comment]
Note that the phone needs to be jailbroken to access those files.

**Comment by iulico-1** [comment]
No plan to enhance our security posture on jailbroken the phone.

**Comment by pdallat-pcs** [comment]
Any updates??

**Comment by Skarzag** [comment]
Also got a negative pentest result because of this.
