### ISSUE TITLE
DevOps pipeline builds need 

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#1373]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmprieur** [comment]
@MarkZuber I suppose that we can close this issue; it does not describe wha the DevOps pipeline needs :)

**Comment by bgavrilMS** [comment]
It needs some attention and Mark is looking at yaml builds, so it's in progress :)

**Comment by bgavrilMS** [comment]
Probably this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1374
