### ISSUE TITLE
[Feature Request] Migrate tests to use new LAB API

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1375]
The current lab api is no longer in development so all of the new feature request that we make end up on the new lab api. Therefore, we need to update the lab infrastructure project to use the new api so that we can take advantage of all of the new features added by the lab team.

**Comment by jennyf19** [comment]
This is included in the [4.5.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.5.0).
