### ISSUE TITLE
[Bug] Missing AcquireTokenInteractive response

### ISSUE THREAD

**Issue by joaorsfonseca** [AzureAD/microsoft-authentication-library-for-dotnet#1381]
**Which Version of MSAL are you using ?**
How can i check this?

**Platform**
xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
This is a new app or experiment

**Repro**

**App.xaml.cs**
```csharp
PCA = PublicClientApplicationBuilder
	.CreateWithApplicationOptions(new PublicClientApplicationOptions()
	{
		ClientId = OAuthSettings.ClientId,
		TenantId = OAuthSettings.TenantID
	})
	.WithRedirectUri($"msal{OAuthSettings.ClientId}://auth")
	.Build();

AuthenticationResult authResult = await App.PCA.AcquireTokenInteractive(scopes)
	.WithParentActivityOrWindow(AuthUIParent)
	.ExecuteAsync();
AcessToken = authResult.AccessToken;
```

**Expected behavior**
Receive Token AuthenticationResult object

**Actual behavior**
No output on after AcquireTokenInteractive execution

**Possible Solution**

**Additional context/ Logs / Screenshots**
I have two applications using the same code.. But in one of them i can't get the AuthResult from AcquireTokenInteractive.
I can perform the login but after that, nothing happens.

Thanks in advance

**Comment by bgavrilMS** [comment]
Did you setup a callback so that MSAL can get back control when the browser finishes authenticating? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-Android-specifics#ensuring-control-goes-back-to-msal-once-the-interactive-portion-of-the-authentication-flow-ends

**Comment by joaorsfonseca** [comment]
@bgavrilMS i was in fact missing the OnActivityResult callback!!!
Thanks
