### ISSUE TITLE
Part 2: Modify iOS broker to handle iOS 13 changes

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1396]
iOS 13 has made changes around the authenticator's ability to verify applications. Currently, MSAL.NET relies on the sourceApplication to verify requests, this will need to be modified.

Will include handling an application token, storing it in keychain and sending in the broker responses.

Urgency consideration: Will do ADAL.NET work first and then come back to Part 2.

See also [Issue Part 1](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1357) and [PR Part 1](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1383)

**Comment by henrik-me** [comment]
@jennyf19 : Is this the same as: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1395 ?

**Comment by jennyf19** [comment]
@henrik-me yes. I already made an issue for this and one on adal. But thanks

**Comment by jennyf19** [comment]
Included in [4.6 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.6)
