### ISSUE TITLE
[Question to the community] would it make sense for MSAL.NET to join the .NET Foundation and expose its maturity level?

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1401]
**Context**
The .NET Foundation is starting a new pilot program to increase quality and user confidence in open source projects, using a new project maturity model.  A four levels [maturity ladder](https://github.com/dotnet-foundation/project-maturity-model/blob/master/maturity-profiles.md) defines project quality, in terms of health and practices.

**Question to the community**
Would you see value in MSAL.NET participating in the pilot?

**Comment by DiegoFaFe** [comment]
[Link changed](https://github.com/dotnet-foundation/project-maturity-model/blob/master/maturity-profiles.md)

**Comment by pushpindersingh** [comment]
MSAL.NET would be a good candidate for the maturity ladder for many reasons, Can I contribute for this project?

**Comment by jennyf19** [comment]
@pushpindersingh Yes. We appreciate outside contributions.
cc: @jmprieur for details

**Comment by pushpindersingh** [comment]
@jennyf19 thanks for encouragement... @jmprieur look forward for details

**Comment by jmprieur** [comment]
@pushpindersingh. A good start would be to read https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Contributing-overview

Feel free to contact me directly if you have any question or want to discuss (Jean-Marc.Prieur at microsoft.com)
