### ISSUE TITLE
[Bug] Device Code Flow fails with misleading error message if app is misconfigured

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1407]
**Which Version of MSAL are you using ?**
MSAL 4.4.0

**What authentication flow has the issue?**
    * [x] Device code flow (browserless)

**Repro**

1. Register an app and do not change the "Allow public client flows" setting which enables Device Code Flow, IWA and ROPC
2. Use MSAL to perform Device Code Flow 

**Expected behavior**
Friendly exception explaining the issue

**Actual behavior**
MSALClientException with code "code_expired"

**Comment by jennyf19** [comment]
Included in [4.6 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.6)
