### ISSUE TITLE
Reg: Get Access Token  and Refresh Tokens from Graph SDK C#

### ISSUE THREAD

**Issue by yChakradhar** [AzureAD/microsoft-authentication-library-for-dotnet#1416]
Hello Team,

Do we have an option to receive Access Token along with Refresh Tokens from Graph API C# SDK?

Regards,
Chakradhar

**Comment by bgavrilMS** [comment]
Yes, MSAL will fetch Refresh Tokens for you automatically and it will manage them. Refresh Tokens are not exposed to you directly, but are using when you perform `AcquireTokenSilent`.

**Comment by jennyf19** [comment]
@yChakradhar [See our documentation on `AcquireTokenSilent`](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-acquire-token-silently) for more info on what @bgavrilMS is referring to.

**Comment by yChakradhar** [comment]
Hi Team,
We have implemented the logic written in the attached file, but when we call the "AADAppContext.GetAccountsAsync()" method it is not returning 0 accounts. Please review the SignInUser method code and let me know if I am doing anything wrong. Please help me.
[SignInHelperClass.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/3693879/SignInHelperClass.txt)


Thank You.
Chakradhar

**Comment by bgavrilMS** [comment]
Hi - please have a look at a sample first such as the one @jennyf19  pointed you at and pay attention to the token cache serialization. All our samples show how to access graph and showcase Acquire Token Silent and cache serialization.

If you are still having problems, try to isolate the issue and we will answer. Also please add more details such as your platform (.net core?)
