### ISSUE TITLE
[Feature Request] Ability to implement transient fault handling/resiliency around MSAL calls

### ISSUE THREAD

**Issue by udlose** [AzureAD/microsoft-authentication-library-for-dotnet#1417]
**Is your feature request related to a problem? Please describe.**
The ability to implement any kind of resiliency around MSAL calls is lacking at best.  The only thing I can see is this example which uses a less than ideal implementation of a retry mechanism: [https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/retry-after](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/retry-after)

This implementation is less than ideal as it does not leverage the IHttpClientFactory resiliency pattern as described here by Microsoft - [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)

**Describe the solution you'd like**
I'd like to have the ability to use the IHttpClientFactory resiliency pattern so that I can add some Polly wrappers for resiliency policies.  I assume that MSAL possibly intended to abstract away any Http implementation details - which is great in theory.  However, the fact that it has done so does not allow for a clear maintainable and reusable pattern for resiliency.

**Describe alternatives you've considered**
Making direct Http calls using IHttpClientFactory to:
1. OAuth2 Token API to obtain an access token for the GraphAPI
2. Caching the token (using memory or distributed)
3. Then the graph API and passing the access token as a Bearer token in Authorization header for the HttpRequest to GraphAPI

**Comment by jennyf19** [comment]
Thanks @udlose 
fyi @henrik-me @jmprieur

**Comment by bgavrilMS** [comment]
Hi @udlose  - we are looking at this topic. Please have a look at this page I wrote on the subject: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability

- We are thinking of building a circuit breaker in MSAL. 
- MSAL already has the ability of consume an HttpClientFactory but can't consume it directly (by default) because the .NET HttpClientFactory is pretty high up the food chain of dependencies and consuming it would cause diamond dependency problems. We are thinking of introducing it from our extension lib Microsoft.Identity.Web (not yet published to NuGet)

Any feedback much appreciated.

**Comment by udlose** [comment]
Hi @bgavrilMS,

Thank you for your consideration. I did end up solving this problem via use of the extension method `WithHttpClientFactory()`, using my own strongly-typed `HttpClient`, custom `DelegatingHandler` and [Polly.NET](https://github.com/App-vNext/Polly).  Given the ability to do this via this pattern below, I'm not sure adding a Circuit-Breaker to MSAL would add much value unless you went all-in and supported similar policies as are available in Polly (only one of which is the Circuit Breaker).  In my specific case, I didn't need a CircuitBreaker - only a Retry and Timeout Policy.  My use case was to use MicrosoftGraphSDK and have MSAL do the Auth for it.

The code I wrote went something like this - feel free to use if you find it useful in any way:

1. Wire up custom strongly-type HttpClient via IHttpClientBuilder`. In my startup.cs:
`            services.AddHttpClient<IMsalApiClient, MsalApiClient>()
                .AddHttpMessageHandler<MsalDelegatingHandler>()     // need a delegating handler to intercept requests to MSAL services
                .AddPolicyHandlerFromRegistry("MsalPolicy");
`

2. Implement a Polly `PolicyRegistry` singleton and inject:
`        public static IServiceCollection AddTransientFaultPolicies(this IServiceCollection services, IConfiguration configuration, ILoggerFactory loggerFactory)
        {
            var registry = new PolicyRegistry();

            //MSAL (Microsoft.Identity.Client)
            PolicyFactory.AddMsalPolicy(registry);

            // add the Policy Registry to the service configuration so that we can call
            // 'AddPolicyHandlerFromRegistry()' on the HttpClientBuilder from IHttpClientFactory
            services.AddPolicyRegistry(registry);

            //Polly transient fault registry (used by clients that do not have HttpClients - e.g. database connections, etc.)
            //services.AddSingleton<IReadOnlyPolicyRegistry<string>>(registry);

            return services;
        }
`

3. Add a factory class to create transient-fault policy:
`    public static class PolicyFactory
    {
        public static void AddMsalPolicy(PolicyRegistry registry)
        {
            const string policyKey = "MsalPolicy";
            var policy =
                Policy.Handle<Exception>().OrTransientHttpError()
                    .RetryAsync(1, onRetry: RetryHandler)
                    .WrapAsync(PolicyFactory.TimeoutAsync(2))   //timeout goes inside so each retry is checked for timeout
                    .WithPolicyKey(policyKey);

            registry.Add(policyKey, policy);
        }

        private static IAsyncPolicy<HttpResponseMessage> RetryAsync(int numberOfAttempts = 1) =>
            HttpPolicyExtensions.HandleTransientHttpError().RetryAsync(numberOfAttempts, onRetry: RetryHandler);

        private static IAsyncPolicy<HttpResponseMessage> TimeoutAsync(int timeoutInSeconds = 2) =>
            Policy.TimeoutAsync<HttpResponseMessage>(TimeSpan.FromSeconds(timeoutInSeconds), onTimeoutAsync: TimeoutHandler);

        private static Action<DelegateResult<HttpResponseMessage>, int, Context> RetryHandler =>
            (outcome, retryAttempt, context) =>
            {
                LogRetry(context, retryAttempt, outcome);
            };

        private static Func<Context, TimeSpan, Task, Task> TimeoutHandler =>
            (context, timespan, task) =>
            {
                LogTimeout(context, timespan);
                return Task.CompletedTask;
            };

        private static void LogTimeout(Context context, TimeSpan timespan)
        {
            var httpRequestMessage = context.GetHttpRequestMessage();
            IEnumerable<string> headerCorrelationIds = null;
            httpRequestMessage?.Headers.TryGetValues("X-Correlation-ID", out headerCorrelationIds);
            var logger = context.GetLogger();
            var message =
                $"X-Correlation-Id: {headerCorrelationIds?.FirstOrDefault()}{Environment.NewLine}" +
                $"PolicyKey: {context.PolicyKey} at OperationKey: {context.OperationKey}: " +
                $"execution timed out after {timespan.TotalSeconds} seconds for {httpRequestMessage?.Method} to {httpRequestMessage?.RequestUri}.";
            logger?.LogWarning(message);
        }

        private static void LogRetry(Context context, int retryAttempt, DelegateResult<HttpResponseMessage> outcome)
        {
            var httpRequestMessage = context.GetHttpRequestMessage();
            IEnumerable<string> headerCorrelationIds = null;
            httpRequestMessage?.Headers.TryGetValues("X-Correlation-ID", out headerCorrelationIds);
            var logger = context.GetLogger();
            var message =
                $"X-Correlation-Id: {headerCorrelationIds?.FirstOrDefault()}{Environment.NewLine}" +
                $"PolicyKey: {context.PolicyKey} at OperationKey: {context.OperationKey}: " +
                $"execution failed after {retryAttempt} attempt(s) when executing {httpRequestMessage?.Method} to {httpRequestMessage?.RequestUri} " +
                $"with exception: {outcome.Exception}";
            logger?.LogError(message);
        }

}
`

4. Add a class for extending Polly's `Context`:
`    public static class PollyContextExtensions
    {
        private const string HttpRequestMessageKey = "HttpRequestMessage";
        private const string LoggerKey = "ILogger";

        public static ILogger GetLogger(this Context context)
        {
            if (context.TryGetValue(LoggerKey, out object logger))
            {
                return logger as ILogger;
            }

            return null;
        }

        public static Context WithLogger(this Context context, ILogger logger)
        {
            context[LoggerKey] = logger;
            return context;
        }

        public static HttpRequestMessage GetHttpRequestMessage(this Context context)
        {
            if (context.TryGetValue(HttpRequestMessageKey, out object httpRequestMessage))
            {
                return httpRequestMessage as HttpRequestMessage;
            }

            return null;
        }

        public static Context WithHttpRequestMessage(this Context context, HttpRequestMessage httpRequestMessage)
        {
            context[HttpRequestMessageKey] = httpRequestMessage;
            return context;
        }
    }
`

5. Back in startup.cs, wire up DI for my strongly-typed HttpClient and custom DelegatingHandler:
`            //MSAL
            // IGraphAuthProvider uses a cache for tokens so it needs to be a singleton
            services.AddSingleton<IGraphAuthProvider, GraphAuthProvider>();
            services.AddTransient<MsalDelegatingHandler>();
`

6. Add custom DelegatingHandler to intercept the requests that go thru the strongly-typed HttpClient that is handed to MSAL via `WithHttpClientFactory()`:
`    public class MsalDelegatingHandler : DelegatingHandler
    {
        /// <summary>
        /// Sends an HTTP request to the inner handler to send to the server as an asynchronous operation.
        /// </summary>
        /// <param name="request">The HTTP request message to send to the server.</param>
        /// <param name="cancellationToken">A cancellation token to cancel operation.</param>
        /// <returns>
        /// The task object representing the asynchronous operation.
        /// </returns>
        /// <remarks>This method allows for the interception of HttpClient calls to
        /// the services provided by Microsoft.Client.Identity (MSAL).</remarks>
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, 
            CancellationToken cancellationToken)
        {
            var methodBase = MethodBase.GetCurrentMethod();
            var contextName = $"{methodBase.DeclaringType?.FullName}.{methodBase.Name}";
            var transientFaultContext = PolicyHelper.GetTransientFaultContext(null, contextName);
            transientFaultContext.WithHttpRequestMessage(request);
            request.SetPolicyExecutionContext(transientFaultContext);

            return base.SendAsync(request, cancellationToken);
        }
    }
`

7. Add a Helper class to create and customize the Polly Context to be passed to Policy delegates:
`    public static class PolicyHelper
    {
        public static Context GetTransientFaultContext(IDictionary<string, object> contextDictionary,
            string callingMethodName)
        {
            contextDictionary = contextDictionary ?? new Dictionary<string, object>();
            return new Context(callingMethodName, contextDictionary);
        }
    }
`

8. Create a strongly-typed HttpClient and interface:
`    /// <summary>
    /// This class provides an absatraction over the HttpClient used by MSAL as described
    /// here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/httpclient
    /// and
    /// here https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-provide-httpclient
    /// </summary>
    public class MsalApiClient : ApiClientBase, IMsalApiClient
    {
        public MsalApiClient(HttpClient httpClient) : base(httpClient)
        {
        }

        public HttpClient GetHttpClient()
        {
            return HttpClient;
        }
    }

    public interface IMsalApiClient : IMsalHttpClientFactory
    {
    }
`

9. Create a custom AuthProvider and interface:
`    public interface IGraphAuthProvider
    {
        string Authority { get; }

        Task<string> GetUserAccessTokenAsync(string userId);

        //Task<AuthenticationResult> GetUserAccessTokenByAuthorizationCode(string authorizationCode);

        Task<AuthenticationResult> GetUserAccessTokenByBearerTokenAsync(string bearerToken);
    }

    /// <summary>
    /// Originally based on an example from Microsoft - https://github.com/microsoftgraph/aspnetcore-connect-sample/tree/master/MicrosoftGraphAspNetCoreConnectSample
    ///
    /// THIS CODE HAS BEEN MODIFIED TO FIT OUR IMPLEMENTATION!
    /// </summary>
    public class GraphAuthProvider : IGraphAuthProvider
    {
        private readonly IConfidentialClientApplication _app;
        private readonly string[] _scopes;

        public GraphAuthProvider(IConfiguration configuration, IMsalApiClient msalApiClient)
        {
            var azureOptions = new AzureAdOptions();
            configuration.Bind("AzureAd", azureOptions);

            // More info about MSAL Client Applications: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications
            _app = ConfidentialClientApplicationBuilder.Create(azureOptions.ClientId)
                    .WithClientSecret(azureOptions.ClientSecret)
                    .WithAuthority(AzureCloudInstance.AzurePublic, Guid.Parse(azureOptions.TenantId), false)
                    .WithHttpClientFactory(msalApiClient)
                    .WithRedirectUri(azureOptions.BaseUrl + azureOptions.CallbackPath)
                    .Build();

            Authority = _app.Authority;

            _scopes = azureOptions.GraphScopes.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
        }

        public string Authority { get; }

        // Gets an access token. First tries to get the access token from the token cache.
        // Using password (secret) to authenticate. Production apps should use a certificate.
        public async Task<string> GetUserAccessTokenAsync(string userId)
        {
            var account = await _app.GetAccountAsync(userId);
            if (account == null)
            {
                throw new ServiceException(new Error
                {
                    Code = "TokenNotFound",
                    Message = "Custom message from GraphAuthProvider:GetUserAccessTokenAsync(): User not found in token cache. Maybe the server was restarted."
                });
            }

            try
            {
                var result = await _app.AcquireTokenSilent(_scopes, account).ExecuteAsync();
                return result.AccessToken;
            }

            // Unable to retrieve the access token silently.
            catch (Exception e)
            {
                var error = new Error
                {
                    Code = nameof(GraphErrorCode.AuthenticationFailure),
                    Message = "Caller needs to authenticate. Unable to retrieve the access token silently."
                };
                throw new ServiceException(error, e);
            }
        }

        /// <summary>
        /// Internally, this calls out to https://login.microsoftonline.com/31a07f61-c94a-4f98-a304-574bfc2be1ba/oauth2/v2.0/token
        /// </summary>
        /// <param name="bearerToken"></param>
        /// <returns></returns>
        public Task<AuthenticationResult> GetUserAccessTokenByBearerTokenAsync(string bearerToken)
        {
            // use 'AcquireTokenOnBehalfOf' instead of 'AcquireTokenByAuthorizationCode' since this is a WebApi
            // see: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of
            var userAssertion = new UserAssertion(bearerToken);
            return _app.AcquireTokenOnBehalfOf(_scopes, userAssertion).ExecuteAsync();
        }

        //public Task<AuthenticationResult> GetUserAccessTokenByAuthorizationCode(string authorizationCode)
        //{
        //    //this puts the token in the cache according to 
        //    // https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.iconfidentialclientapplication.acquiretokenbyauthorizationcode?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Identity.Client.IConfidentialClientApplication.AcquireTokenByAuthorizationCode);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet
        //    return _app.AcquireTokenByAuthorizationCode(_scopes, authorizationCode).ExecuteAsync();
        //}
`

10. Create a custom repository and interface for MS Graph SDK abstraction:
`    public class GraphRepository : IGraphRepository
    {
        private static readonly string _userPropertyNames; 
        private readonly IGraphAuthProvider _authProvider;
        private readonly IGraphApiClient _graphApiClient;

        static GraphRepository()
        {
            // configure this list only once upon static initialization
            var userProperties = new[]
            {
                "accountEnabled",
                "givenName",
                "surname",
                "id",
                "displayName",
                "jobTitle",
                "userPrincipalName",
            };

            _userPropertyNames = string.Join(",", userProperties);
        }

        public GraphRepository(IGraphAuthProvider authProvider, IGraphApiClient graphApiClient)
        {
            _authProvider = authProvider;
            _graphApiClient = graphApiClient;
        }

        public async Task<ApiProxyResult<Microsoft.Graph.User, string>> GetUser(Models.User.UserRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            if (string.IsNullOrWhiteSpace(request.Email))
                throw new ArgumentException("Value cannot be null or whitespace.", nameof(request.Email));

            var result = new ApiProxyResult<Microsoft.Graph.User, string>();
            try
            {
                var graphSdkClient = GetAuthenticatedClient(request);

                // this eventually calls out to MS Graph Api, but first calls out
                // to MSAL to get an Authorization access token
                result.SuccessData = await graphSdkClient
                    .Users[request.Email]
                    .Request()
                    .Select(_userPropertyNames)
                    .GetAsync();

                result.IsSuccess = true;
            }
            catch (ServiceException e)
            {
                string message;
                switch (e.Error.Code)
                {
                    case "Request_ResourceNotFound":
                    case "ResourceNotFound":
                    case "ErrorItemNotFound":
                    case "itemNotFound":
                        message = $"User '{request.Email}' was not found.";
                        break;
                    case "ErrorInvalidUser":
                        message = $"The requested user '{request.Email}' is invalid.";
                        break;
                    case "AuthenticationFailure":
                    case "TokenNotFound":
                        message = e.Error.Message;
                        break;
                    default:
                        message = $"An unknown error has occurred: {e}";
                        break;
                }

                result.ErrorData = message;
            }

            return result;
        }

        private GraphServiceClient GetAuthenticatedClient(Models.User.UserRequest request)
        {
            var authProvider = GetAuthenticationProvider(request);
            return new GraphServiceClient(authProvider, _graphApiClient);
        }

        private DelegateAuthenticationProvider GetAuthenticationProvider(UserRequest request)
        {
            return new DelegateAuthenticationProvider(
                async requestMessage =>
                {
                    // Get user's id for token cache.
                    var identifier = request.ClaimsIdentity.FindFirst(Startup.ObjectIdentifierType)?.Value
                                     + "."
                                     + request.ClaimsIdentity.FindFirst(Startup.TenantIdType)?.Value;

                    //TODO - customize Token caching for Redis

                    // Put the token into the built-in MSAL token cache first
                    //NOTE: we don't care about it's returned AuthenticationResult object
                    await _authProvider.GetUserAccessTokenByBearerTokenAsync(request.BearerToken);

                    // Passing tenant ID to the sample auth provider to use as a cache key
                    var accessToken = await _authProvider.GetUserAccessTokenAsync(identifier);

                    // Append the access token to the request
                    requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                });
        }
    }

    public interface IGraphRepository
    {
        Task<ApiProxyResult<Microsoft.Graph.User, string>> GetUser(Models.User.UserRequest request);
    }
`

Let me know if you have any feedback.

**Comment by bgavrilMS** [comment]
Thank you for considering IHttpClientFactory, please let me know if you have other suggestions on how to integrate with libraries such as Polly.

**Comment by udlose** [comment]
@bgavrilMS I'm confused.  This solution is integrated with Polly.

**Comment by udlose** [comment]
bump

**Comment by udlose** [comment]
understood.  I was confused by your comment:

> please let me know if you have other suggestions on how to integrate with libraries such as Polly.

since my solution *was* integrating with Polly.  I completely understand that you shouldn't have dependencies on an external library.
