### ISSUE TITLE
[Bug] iOS 13: Broker response nonce does not match the request nonce sent by MSAL.NET

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1421]
Using iOS 13 and MSAL.NET 4.4.0, customers have reported the following error from the broker response:
`Microsoft.Identity.Client.MsalServiceException
  Message=Broker response returned error: Broker response nonce does not match the request nonce sent by MSAL.NET.Please see https://aka.ms/msal-net-ios-13-broker for more details.`

The issue has been fixed and will be in the next MSAL.NET release (4.4.1), planned for end of week of Oct. 7.

**Comment by Harshad-Altudo** [comment]
Is there any timeline when a new version will be released with this fix?

**Comment by jmprieur** [comment]
Normally we want to release this on Monday,  @Harshad-Altudo

**Comment by jennyf19** [comment]
@Harshad-Altudo This is included in the [4.5.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.5.0).

**Comment by Harshad-Altudo** [comment]
@jennyf19  it's working Thanks for Quick reply 👍

**Comment by jmprieur** [comment]
Thanks for confirming @Harshad-Altudo
