### ISSUE TITLE
[Bug] MSAL should not stop developers from adding reserved scopes

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1422]
**Which Version of MSAL are you using ?**
MSAL 4.4

**Platform**
all

**What authentication flow has the issue?**
Client Credentials and all others.

- See discussion here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1403
-  Gist of it - In client credentials on ADFS, <resource>/.default does not work. Instead, users need to add "openid"

**Actual**: MSAL throws a client exception stating that users should not add their own reserved scope "openid"
**Expected**: MSAL should not throw, instead it should just merge scopes

**Comment by bgavrilMS** [comment]
CC @jmprieur

**Comment by jennyf19** [comment]
This is included in the [4.5.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.5.0).
