### ISSUE TITLE
[Doc] Port exhaustion can occur in web app scenarions

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1425]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
msal 4.4.0

**Platform**
net45, netcore, netstandard

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [x] Authorization code
    * [x] OBO
* Web API
    * [x] OBO

**Repro**

We create an `HttpClient` with each `PublicClientAppliation` or `ConfidentialClientApplication`. This is a problem on Web App scenarios, where we create one for each session. This leads to a port leak. See more details in the ADAL issue: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1665

**Comment by jmprieur** [comment]
We cannot do anything meaningful on the library side. But we'll provide guidance to use HttpClientFactories

**Comment by jmprieur** [comment]
Documentation is done.
@jmprieur to create a work item to do better in the product

**Comment by jennyf19** [comment]
Included in [4.6 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.6)
