### ISSUE TITLE
Question: MSAL for UWP in PREVIEW on Tweet

### ISSUE THREAD

**Issue by myokeeh** [AzureAD/microsoft-authentication-library-for-dotnet#1434]
I'm a little confused. What does this tweet's graphic mean by UWP in PREVIEW?

https://twitter.com/azuread/status/1182347099695763456?s=20

Hasn't it been GA for .NET (UWP) for a while now?

**Comment by bgavrilMS** [comment]
Yes, MSAL.NET is GA for a few good months now. This includes the UWP target.

**Comment by jmprieur** [comment]
@myokeeh. Thanks for the heads-up.
We are going to fix the photo in the tweet
