### ISSUE TITLE
[Bug] Client Credential flows fail when using the UserKeySet key flags.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1444]
**Which Version of MSAL are you using ?**
4.5.0

**Platform**
net framework 4.7.2

**What authentication flow has the issue?**
Client Credential Flows

**Repro**
Try acquiring a token using the .WithCertificate() api on the confidential client application using a certificate with the X509KeyStorageFlags.UserKeySet and or the X509KeyStorageFlags.EphemeralKeySet. (I have a cert that repros this)
```csharp
var AdminCert = new X509Certificate2(adminCertLocation, password, X509KeyStorageFlags.UserKeySet);
```

**Expected behavior**
MSAL should successfully create a signed JWT using the provided cert and acquire a token.

**Actual behavior**
MSAL throws a cryptographic error “Invalid Provider”. This is working in ADAL though and .Net Core MSAL.  The private key property shows as null on the x509certificate2

**Possible Solution**
use the following code to create a an rsa crypto service Provider to sign the assertion instead of accessing the PrivateKey property on the x509certificate2.
```
var rsa = RSACertificateExtensions.GetRSAPrivateKey(Certificate);
```

**Comment by jennyf19** [comment]
Included in [4.6 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.6)
