### ISSUE TITLE
broker_nonce_mismatch

### ISSUE THREAD

**Issue by markbeij** [AzureAD/microsoft-authentication-library-for-dotnet#1446]
I'm trying to get my app working with MS Authenticator on iOS 13 with the latest iOS API

Environment
* Xamarin.Forms 3.6.0.709228
* MSAL 4.4.0
* Xcode 11
* Physical device with iOS 13.1.2

MSAL.Xamarin.iOS.4.4.0.0.MsalServiceException:
ErrorCode: broker_nonce_mismatch
Microsoft.Identity.Client.MsalServiceException: Broker response returned error: Broker response nonce does not match the request nonce sent by MSAL.NET.Please see https://aka.ms/msal-net-ios-13-broker for more details.

I checked the link, but don't see anything I could have missed.
So what could explain a nonce mismatch?

**Comment by bgavrilMS** [comment]
Hi @markbeij - this is a bug in MSAL 4.4. Please upgrade to MSAL 4.5, it will have been fixed.

**Comment by bgavrilMS** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1421

**Comment by markbeij** [comment]
Thanks, MSAL 4.5 fixed it

**Comment by jmprieur** [comment]
Thanks for confirming, @markbeij
