### ISSUE TITLE
[Bug] Xamarin.Android typeload exception with MSAL 4.5.0

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1449]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
4.5.0

**Platform**
android only

**Repro**
1. Update to latest VS (RTM)
2. Create a new XForms solution
3. Add MSAL 4.5.0 (just add the nuget packge)
4. Run

VS 16.3.5
Xamarin: 16.3.0.277
Xamarin.Android.SDK 10.0.3.0

UNHANDLED EXCEPTION:
10-16 13:18:43.263 I/MonoDroid(23861): System.TypeInitializationException: The type initializer for 'Attribute' threw an exception. ---> System.TypeLoadException: Could not resolve type with token 01000022 from typeref (expected class 'Microsoft.Identity.Client.Ref.Resource' in assembly 'Microsoft.Identity.Client, Version=4.5.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae')
10-16 13:18:43.263 I/MonoDroid(23861): at Android.Runtime.ResourceIdManager.UpdateIdValues () [0x00097] in <11a340ccc8de43f09c97400139266ef5>:0
10-16 13:18:43.263 I/MonoDroid(23861): at Xamarin.Forms.Platform.Android.Resource+Attribute..cctor () [0x012a2] in D:\a\1\s\Xamarin.Forms.Platform.Android\Resources\Resource.Designer.cs:1579
10-16 13:18:43.263 I/MonoDroid(23861): --- End of inner exception stack trace ---
10-16 13:18:43.263 I/MonoDroid(23861): at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
10-16 13:18:43.263 I/MonoDroid(23861): at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.ActionBarHeight () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:476
10-16 13:18:43.263 I/MonoDroid(23861): at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0001a] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:392
10-16 13:18:43.263 I/MonoDroid(23861): at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:198
10-16 13:18:43.263 I/MonoDroid(23861): at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.40(intptr,intptr,bool,int,int,int,int)
10-16 13:18:43.278 W/zygote64(23861): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable

**Comment by bgavrilMS** [comment]
**Workaround** - downgrade MSAL to 4.4 on the Android head but keep the iOS at 4.5. You can also keep the shared project at 4.5, it doesn't really matter.

At runtime, the Android will use MSAL 4.4 and iOS will use MSAL 4.5. This should be fine because the 4.5 release has virtually no impact on Android code paths.

**Comment by mastermoe01** [comment]
I have the same issue, it seems @bgavrilMS workaround works for me for now though.

**Comment by norton287** [comment]
I'm having the same issue and reverting the package works.

**Comment by jennyf19** [comment]
@WilliamWatterson86 @mastermoe01 @norton287 
@bgavrilMS has a fix for this. We are running a new release build now, if you would like to try it out before we officially release, please send me an email: jeferrie@microsoft.com

**Comment by jennyf19** [comment]
Fixed in [4.5.1 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.5.1)

**Comment by WilliamWatterson86** [comment]
@jennyf19 @bgavrilMS sorry for the delay getting back to you. V4.5.1 works well! Thanks for getting this out so quickly :)

**Comment by bgavrilMS** [comment]
Thanks for confirming @WilliamWatterson86 !

**Comment by mastermoe01** [comment]
@jennyf19 4.5.1 also worked for me! thank you!
