### ISSUE TITLE
[Bug] AcquireTokenADFSV2019InteractiveNonFederatedTest fails consistantly

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1460]
**Which Version of MSAL are you using ?**
4.5.1

**Platform**
All

**Expected behavior**
test should run successfully

**Actual behavior**
the test fails because the lab query that the test uses does not have a matching account that is returned by the lab

**Possible Solution**
Request the lab to add an additional account that matches the query
(Cloud user backed by the ADFS2019 lab)
query: "https://msidlab.com/api/user?usertype=cloud&federationprovider=adfsv2019"

**Comment by jmprieur** [comment]
@jennyf19 if you want to check it. No obligation,
