### ISSUE TITLE
Question - Where can I find Release Notes?

### ISSUE THREAD

**Issue by udlose** [AzureAD/microsoft-authentication-library-for-dotnet#1461]
I'm not able to find Release Notes for updates to the Microsoft.Identity.Client nuget package.  Do they exist anywhere?  TIA

**Comment by jennyf19** [comment]
@udlose Like these [release notes](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases) or the [changelog.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/changelog.txt)? we also have blog posts for some of the releases, in the side bar under ["News"](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-4.3)....or is there something else you are looking for? Any suggestions on a more searchable place to find them are appreciated as well.

**Comment by jmprieur** [comment]
@udlose : they are also all referenced from the roadmap: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki#roadmap

**Comment by udlose** [comment]
@jennyf19 , @jmprieur 
Thanks. I'd normally expect to find the Release Notes on the default page for the GitHub site. If not the Release Notes themselves, then at least a link to them.

**Comment by jmprieur** [comment]
Thanks for the feedback; @udlose 
I've updated the README.md to make it clearer

**Comment by bgavrilMS** [comment]
@jmprieur - for example out see https://www.nuget.org/packages/Moq/

**Comment by jennyf19** [comment]
Thanks @bgavrilMS
