### ISSUE TITLE
[Infra] Update Roslyn analyzer to latest version (reverting mitigation)

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1463]
Moving back to the latest Roslyn analyzer as the regression has now been fixed.

**See also:**
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1430

**Comment by henrik-me** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1462

**Comment by jennyf19** [comment]
Included in [4.6 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.6)
