### ISSUE TITLE
[Feature Request] Run all the tests with MSA as well as AAD (when suitable)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1471]
**Is your feature request related to a problem? Please describe.**
We don't run MSA tests enough. Find out if we can do something in the infrastructure to run tests with both kind of accounts (when suitable = no IWA, UP, Daemon)

**Comment by jmprieur** [comment]
PR is https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1511

**Comment by jennyf19** [comment]
in 4.8.1 release
