### ISSUE TITLE
[Feature Request] Migrate from MyGet to Github packages

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1472]
**Is your feature request related to a problem? Please describe.**
We should migrate our publising from MyGet to GitHub packages 

- See https://github.blog/2019-05-10-introducing-github-package-registry/ to understand how to join the beta.
- Open questions: which identity to use to push to package? aadidigt maybe? What do you think @henrik-me ?

**Comment by jmprieur** [comment]
Let's use aadidgit

**Comment by bgavrilMS** [comment]
We definitely migrated off MyGet

**Comment by trwalke** [comment]
During triage we decided to close but if there is a customer need for daily builds we can do this.
