### ISSUE TITLE
[Bug] ApplicationOptions do not offer the same options as the builder methods WithXYZ

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1479]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 4.5

**Platform**
all

1. Take a look at the [public class](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/2ba904f67c814e36ed2363615e85e04cd7794699/src/client/Microsoft.Identity.Client/AppConfig/ApplicationOptions.cs#L15) `ApplicationOptions` and the derived [ConfidentialClientApplicationOptions](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/2ba904f67c814e36ed2363615e85e04cd7794699/src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationOptions.cs#L10) and [PublicClientApplicationOptions](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/2ba904f67c814e36ed2363615e85e04cd7794699/src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationOptions.cs#L10)

2. There are fewer possibilities of configuring the app via `Options` than there are with builders `WithXYZ`. 

For example the following are **missing** from the options: 

- validateAuthority flag
- enableBroker flag

- client assertion

- keychainSecurityGroup string
- defaultRedirectUri flag
- useCorprorateNetwork (UWP flag)

We also need a unit test that ensures that the builders are kept in sync with the options, i.e. any options that are "string" or "bool" should be present in the 2 ways of configuring the app.

**Comment by jmprieur** [comment]
Thanks @bgavrilMS 
- I don't think that we'd want to have the validateAuthority flag. We'd rather want to have a collection of known authorities moving forward
- Good point for enableBroker, keychainSecurityGroup and useCorporateNetwork and defaultRedirectUri.

For the certifcates, so far the idea has been that we'd only want to have in the Options things that we can serialize and read from a config file, but I must say that I missed having the cert in the options. Mark was suggesting having a Certificate provider though.

**Comment by henrik-me** [comment]
Marking as feature request, though as we extend the API the config should follow. Agreeing on the KnownAuthorities config instead of the boolean.

**Comment by jmprieur** [comment]
We would take:
- enableBroker flag
- keychainSecurityGroup string

But this is mobile that we won't prioritize this quarter
