### ISSUE TITLE
[Feature Request] Support ADFS 2019 device authentication during acquire token interactive

### ISSUE THREAD

**Issue by maordadush** [AzureAD/microsoft-authentication-library-for-dotnet#1483]
**Is your feature request related to a problem? Please describe.**
I'm trying to require a particular device trust level: either authenticated, managed, or compliant for my application web api in ADFS 2019. 
So when I'm requiring token, the adfs server denies the request: MSIS9211: Access is denied for the received OAuth request.

**Describe the solution you'd like**
As part of the flow authentication, I would like to make the adfs server set DeviceCookie.

**Describe alternatives you've considered**
The user is navigating to the idpinitiatedsignon page and signing in, consequently the device cookie is created. after the user acquires token interactive with the device cookie so the adfs server can check the device access policies successfully.

**Comment by jmprieur** [comment]
@maordadush : can you please share repro steps?

**Comment by maordadush** [comment]
I have an air gapped environment with adfs 2019 server, web api application and windows 10 client.
I created native application accessing a web api application group in the adfs server and created the following access rule: permit users from devices with authenticated trust level.
When the native client acquired token interactive, the client got this error: 
MSIS9622: Client authentication failed. Please verify the credential provided for client authentication is valid. however when I navigated to the idpinitiatedsignon adfs page and signed in using IE and then ran the native client its worked because I noticed in fiddler that native client came with device cookie that was created before when I navigated to the idpinitiatedsignon adfs page.
Thanks!

**Comment by henrik-me** [comment]
@reed1995 : I'll follow up with TravisQ.

**Comment by maordadush** [comment]
@henrik-me this is the adfs access control policy rule:
![image](https://user-images.githubusercontent.com/8192075/67902617-45f46980-fb72-11e9-896f-6ff798d470cf.png)
I would like to get a device token as I get user token when I call AcquireTokenInteractive method, but if I dont have the device token the adfs server denies the request.
Thanks!

**Comment by bgavrilMS** [comment]
This feature request should be made to ADFS.
