### ISSUE TITLE
[Feature Request] Consider bumping the mininal .NET FW version to 4.6 or 4.7+

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1485]
**Is your feature request related to a problem? Please describe.**
Currently MSAL.NET proposes a net45 platform, however it’s out of support/not patched/does not use latest cryptography.

We should consider 4.7+ or 4.6 and up (because those library versions are free of known vulns and patched)

**Describe the solution you'd like**
Change the .NET framework target to 4.7.2?
Jm to look at service side telemetry to understand the impact

**Comment by bgavrilMS** [comment]
I assume this is a major version upgrade? 

We should not jump to 4.7.2, that seems excessive. I believe many of our customers are still on 4.6.x. 4.6.x should have better cypto support.

**Comment by jmprieur** [comment]
You're right @bgavrilMS that's a major version upgrade unless we provide an additional target (but why would we do that?)

**Comment by bgavrilMS** [comment]
Well to be fair, customers are not affected by out decision directly. Our "net45" target should be interpreted as "whatever your app compiles to, but not lower than net45". So if an app is built and ran against net47, the crypto used by MSAL will be from .net 47. 

This said, by providing such a low bar, we encourage developers not to upgrade their apps. 

I'm all for bumping this version, but we should take the opportunity to investigate: 

- what min version we should get our netstandard to 
- how can we integrate with Wilson

**Comment by bgavrilMS** [comment]
We need to move to at least 4.6.1 to be able to work around cert issues, which are becoming very difficult to support.

**Comment by bgavrilMS** [comment]
@jmprieur - currently set to 4.6.1, please let me know if you have data related to others.

**Comment by jmprieur** [comment]
This is not information we have, @bgavrilMS. Let's go with 4.6.1.

**Comment by bgavrilMS** [comment]
This was done some time ago.
