### ISSUE TITLE
[Feature Request] Send the Refresh Token on Interactive Requests

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1486]
## Why?
An application wants to iterate through the tenants in which an account is a user (or a guest user). For each tenant, the app attempts an `AcquireTokenSilent` and if UI is required, `AcquireTokenInteractive`. This will be the case for the fist tenant, but also for each of the tenants where MFA is required (as the user will have to perform MFA in these tenants)

1. The application gets an access token for each tenant (for the same account), and some tenants require MFA (which means the user sees a prompt)
2. The application wants to use the access tokens.

### Current behavior:
Today, the user is prompted again if the tenant requiring MFA is not the last, because the refresh token associated with the account only has the mfa claim for this last tenant

### Desired behavior
To avoid the user to be prompted, we'd want to keep all the mfa claims for each tenant in the refresh token. To achieve this goal, the application or MSAL.NET needs to pass 2 headers to Azure AD (See below)

It seems that this is a very specific scenario, involving several tenants for the same accounts (that is using AcquireTokenSilent / AcquireTokenInteractive) with a .WithTenantId or a .WithLoginHint, and therefore we might want to scope down sending the headers in that case only ?

## What needs to be done?
MSAL.NET should send the refresh token on the interactive request and the silent request as part of the `x-ms-sso-RefreshToken` header when `.WithTenantId` is used. This will enable the authorization server to combine the MFA claims in a refresh token, so users are not prompted for MFA on multiple tenants. MSAL.NET should store the combined refresh token in the cache for future silent requests.
also, send the header: `x-ms-sso-Ignore-SSO=1`

**Comment by bgavrilMS** [comment]
Future of public client is WAM, which does not expose RT.
