### ISSUE TITLE
[Feature Request] Token cache serialization for Mac

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1487]
**Is your feature request related to a problem? Please describe.**
Token cache serialization for Mac. Goes into the extension library. https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet

**Describe the solution you'd like**
- .NET Core
- Xamarin.Mac? (not supported directly in the extension library, but supported through Net Standard)

**Comment by jmprieur** [comment]
It's in the extension library.

**Comment by bgavrilMS** [comment]
This now works via the extension library: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet
