### ISSUE TITLE
[Feature Request] Expose WithSendX5C() api on more confidential client authentication flows for Subject Name + Issuer Auth

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1490]
**Is your feature request related to a problem? Please describe.**
Customers want to use the subject name + issuer authentication with various confidential client authentication flows including the "AcquireTokenByAuthorizationCode()" and AcquireTokenByRefreshToken() flows. These two flows do not have access to WithSendX5C() method to enable SN+I auth.

**Describe the solution you'd like**
add WithSendX5C() to the "AcquireTokenByAuthorizationCode()" and AcquireTokenByRefreshToken() flows

Perhaps it is a good idea to enable this on all Confidential client apis in MSAL?

**Comment by jennyf19** [comment]
In 4.7.0 release
