### ISSUE TITLE
[Bug] Device Code Flow throws if the user does not enter their creds in the external browser within 2 mins

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1495]
**Which Version of MSAL are you using ?**
MSAL.NET 4.6.0

**Platform**
.NET Core

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ x] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
Yes, you can use https://github.com/azure-samples/active-directory-dotnetcore-devicecodeflow-v2, which is preconfigured.

**Repro**
- Clone https://github.com/azure-samples/active-directory-dotnetcore-devicecodeflow-v2
- Run the console app
- wait for at least 2 mins to enter the code in the browser where you navigate from the URL provided by the console app.

**Expected behavior**
MSAL.NET polls for 15 mins

**Actual behavior**
- After 2mins, MSAL.NET throws an exception.

```
AADSTS50196: The server terminated an operation because it encountered a loop while processing a request
```

**More information**
- This seems to be a service error, probably due to a service change in the service change (loop-breaking): for this feature to stay below the threshold, we need the MSAL to poll at most 4 times / minute for the first 5 minutes (ideally less), and then 1 time per minute afterwards
~- However, the library can do better and obey the `interval` value returned in the Device Authorization response: See https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#device-authorization-response~

**Comment by jmprieur** [comment]
@henrik-me : i'm tempted to take this one in 4.8, unless you disagree
(obey the **interval** parameter from the Device Authorization response)

**Comment by jennyf19** [comment]
@jmprieur We seem to be honoring the `interval` [value.](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Internal/Requests/DeviceCodeRequest.cs#L90)..but I saw the same behavior as you...will follow up.

**Comment by jennyf19** [comment]
@jmprieur I talked w/Adrian, and seems to be a bug on server side w/the loop breaking logic having a too low limit for legitimate polling. They will confirm soon.

**Comment by jmprieur** [comment]
ETA for fix on the service side in 2-3 weeks from now
