### ISSUE TITLE
iOS build errors in Azure DevOps

### ISSUE THREAD

**Issue by mtanml** [AzureAD/microsoft-authentication-library-for-dotnet#1497]
**Which Version of MSAL are you using ?**
4.7.0

**Platform**
Xamarin Android, Xamarin iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;
iOS builds in Azure DevOps

**Is this a new or existing app?**
Existing

**Repro**

**Expected behavior**
Successful builds for iOS in Azure DevOps

**Actual behavior**
Build error:   MTOUCH : error MT2002: Failed to resolve "System.Collections.Generic.Stack`1" reference from "mscorlib, Version=2.0.5.0, Culture=neutral,

**Possible Solution**

**Additional context/ Logs / Screenshots**
The issue started to appear when we updated to version 4.5.1, and also occurs in 4.7. We rolled back to 4.4 and the build was successful.

**Comment by jmprieur** [comment]
@mtanml:  Did you try to add a step to install .NET Core 3.0 in your build definition?
![image](https://user-images.githubusercontent.com/13203188/68844405-05e0cb00-06ca-11ea-9c84-1ec12a30829e.png)

If this does not work for you, can you please share some repro steps with us?

**Comment by mtanml** [comment]
Hi Jean Marc,

Using .net core 3.0.100 was one of the first things we tried, which gave us ~1100 errors about a missing reference:

App.xaml.cs(15,12): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral

Thanks,
Marc

**Comment by jmprieur** [comment]
@mtanml can you repro this issue with one of our samples? https://github.com/Azure-Samples/active-directory-xamarin-native-v2 for instance?
