### ISSUE TITLE
[Feature Request] Add additional information to Exception during network timeouts

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1498]
**Describe the solution you'd like**
Many of the ICMs that we get are a result of some network connectivity issue. Most customers simply file an ICM when this happens because they see that MSAL throws the network exception from the http client. When encountering network connectivity issues, it will be a good idea to add additional information to the exception to help alleviate the number of ICMs that come our way that are not a result of MSAL code. One idea is to perform a quick ping to the endpoints where the application is trying to connect to to see if the connections are healthy. We can then put that information in the exception message so that customers will know if the network is still working after the failed authentication attempt.

Perhaps customers will see that additional pings also failed and will investigate their network connections before filing an ICM.

**Comment by jmprieur** [comment]
Also related to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1445

**Comment by jmprieur** [comment]
Many exceptions can indicate a timeout.
No recent support cases on this
Now we pass all headers and body.

Let's park until more concrete spec
