### ISSUE TITLE
[Feature Request] Offer System Browser on pure .Net Standard to help Powershell

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1502]
MSAL should provide the System Browser implementation . Today, from pure .net standard, we throw an exception when developers try to use interactive auth. This is mainly to offer a good exception for Xamarin devs, who sometimes fall on using MSAL .netstandard by mistake.  

However, Powershell (the app) and Powershell module developers also use .Net Standard. So we should provide them with the System Browser.

**Comment by henrik-me** [comment]
We have designed the library in a way that doesn't "support" using the standard library directly besides for development of shared code. If you are building your own assembly loader then for these scenarios customers should be using the netcore dll and not the netstandard dll. Not sure why they can't use the netcore dll instead.

**Comment by bgavrilMS** [comment]
Ok, also note that since the 4.7.1 release, MSAL uses HttpListener class, which is not available in netstandard 1.3 - so achieving this would imply bumping to netstandard 1.4
