### ISSUE TITLE
[Feature Request] Remove RT if suberror is "bad_token" to avoid overloading ESTS

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1505]
If the RT has expired or has been tampered with, ESTS will return a "bad_token" suberror. MSAL does not currently take action on it, but it should delete the RT. The reason for this is explained by Dejan: 

_Based on our investigations into busy client loops, we know that some apps tend to sit in loops in the background and try to acquire token silently even though the auth library is returning an error. If the library knows that the RT is bad and the call will never succeed, we can cut these loops locally and not talk to the server. Loops like this have contributed to significant livesite outages in the past._

**Comment by jmprieur** [comment]
@shoatman do you have any perspective on why we should not do that?

**Comment by shoatman** [comment]
No.  bad_token is a bad_token and can be deleted.  With that said, I would expect to see something similar if you attempted to send an RT from WW to a sovereign cloud.  So I'd also add some tests to ensure that RTs are only ever being sent to the cloud that issued them.

**Comment by trwalke** [comment]
Resolved in [4.11.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.11.0)
