### ISSUE TITLE
[Bug] Interactive auth with Edge system browser sometimes hangs

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1506]
**Which Version of MSAL are you using ?**
MSAL 4.7

**Platform**
netcore or net classic

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**

Configure interactive auth to use the system browser and also configure it to use Edge.

```csharp
  var options = new SystemWebViewOptions()
{
     OpenBrowserAsync = SystemWebViewOptions.OpenWithEdgeBrowserAsync
};

var cts = new CancellationTokenSource();
authTask = pca.AcquireTokenInteractive(s_scopes)
                        .WithSystemWebViewOptions(options)
                        .ExecuteAsync(cts.Token);
```

**Actual behavior**
Sometimes the browser hangs at an url similar to: 
`https://login.microsoftonline.com/common/reprocess?ctx=rQIIAW2Q`

Eventually an MsalClientException occurs, stating: 

`Could not extract the query from the authorization response - check Pii enabled logs for details`

This happens about 50% of the time.

**Possible Solution**
It looks like the TCP listener is invoked, but no data is available. Calling `ReadAsync` seems to block. After some time or if the browser is refreshed, the tcp listener reads 0 bytes.

**Comment by bgavrilMS** [comment]
P1 as it is blocking customers (Storage Explorer in particular)

**Comment by bgavrilMS** [comment]
CC @crmann1

**Comment by jmprieur** [comment]
@bgavrilMS : we did not ship 4.8 yet? we might just want to mark it as fixed (and keep it open)

**Comment by bgavrilMS** [comment]
I merged the fix and it looks like GitHub closes the associated issue...

**Comment by bgavrilMS** [comment]
I think this is because GitHub inspects the PR comments and if it finds smth like "fixes bug xxx" then it automatically closes bug xxx. Smart, but not customizable ... :)

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by jmprieur** [comment]
oh, ok. thanks for the explantion, @bgavrilMS !

**Comment by jmprieur** [comment]
Released today in MSAL.NET 4.7.1
