### ISSUE TITLE
TokenCache Deserialize not working properly Microsoft.Identity.Client with 1.1.4-preview002 upgraded to 4.7.0.

### ISSUE THREAD

**Issue by nrajasekar7** [AzureAD/microsoft-authentication-library-for-dotnet#1512]
Hi @bratsche @RamonPage @vladzaharia @boumenot @yinaa 
**Which Version of MSAL are you using ?**
MSAL 4.7.0

**Platform**
net461

**What authentication flow has the issue?**
* Desktop WPF
    *  Interactive Silent

**Is this a new or existing app?**
 The app is in production, and I have upgraded to a new version of MSAL but gettting issue in development itself.
I had using Microsoft.Identity.Client with 1.1.4-preview002 and upgraded to 4.7.0.

**Repro**
Logged in the application with the old application which uses v1.1.4 and save the user cache by serializing the file with old version.
Upgraded the package to 4.7.0 and try to re launch the application.
Now the application throws error when deserializing the old user cache using deserializemsalv3.

**Expected behavior**
It should deserialize the old format and save in to new format.

**Actual behavior**
MSAL V3 Deserialization failed to parse the cache contents. Is this possibly an earlier format needed for DeserializeMsalV2? (See https://aka.ms/msal-net-3x-cache-breaking-change)

**Possible Solution**
I tried to use deserializemsalv2 when the exception occurs, but the compile time shows as obsolete error.
 https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-3-released#example-code-demonstrating-how-it-will-be-possible-in-msal-31-to-share-sso-across-all-versions.

it still shows error. and MsalUnexpectedCacheFormatException could not find error coming when i tried with the above link.

![image](https://user-images.githubusercontent.com/10460244/69318796-4b306a00-0c81-11ea-9bbd-870f21fa1668.png)

Thanks,
Rajasekar

**Comment by jmprieur** [comment]
@nrajasekar7. This never was a supported scenario. We have not committed to have the token cache serialization compatible from version 1.x, which was a preview version. 

The supported cache upgrade scenarios are documented here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-3-released#support-plans-for-serialization-formats
(knowing that MSAL 4.x uses the MSAL 3x format).

**Comment by nrajasekar7** [comment]
@jmprieur Thank you for the prompt response and explanation.

I did the same and asked user to choose their identity again.

Regards,
Rajasekar
