### ISSUE TITLE
[Bug] Tokens obtained using .WithB2CAuthority do not have the optional claims

### ISSUE THREAD

**Issue by ahmadizm** [AzureAD/microsoft-authentication-library-for-dotnet#1516]
**Which Version of MSAL are you using ?**
4.0.30319

**Platform**
net472

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
new app

**Repro**

Web API registration manifest on Azure: Add:
"optionalClaims": {
		"idToken": [],
		"accessToken": [
			{
				"name": "upn",
				"source": null,
				"essential": false,
				"additionalProperties": [
					"include_externally_authenticated_upn"
				]
			}
		],
		"saml2Token": []
	},

This has its api exposed to a native app registration on the same B2C directory. The native app registration, in turn, has a permission to this api

In the native app, we try to log into the native app registration, and we correctly get an access token that can be used to call the api. This is done as follows (interactive case):

```csharp
IPublicClientApplication app = PublicClientApplicationBuilder.Create(Common.ClientId)
                .WithB2CAuthority(Common.AuthoritySignUpSignIn)
                .WithLogging(Log, LogLevel.Verbose, false) //PiiEnabled set to false
                .Build();
```

Then
```csharp
                        authResult = await app.AcquireTokenInteractive(Common.ApiScopes)
                                            .WithParentActivityOrWindowIfValid(_ParentWindowHandle)
                                            .WithPrompt(Prompt.SelectAccount)
                                            //.WithAccount(accounts.LastOrDefault())
                                            .ExecuteAsync();
```

**Expected behavior**
Like the regular Azure AD, we would like to have the "upn" claim in the access token. Once we figure this one out, we hope to use this to have preferred_username in the token, so we can use WithAccount that is commented out above, without getting the error "Missing from token response." Also, we would like to be able to include "roles" claim defined in web api app registration manifest in the token.

**Actual behavior**
When using B2C (.WithB2CAuthority), the optional claim is not in the token. Note again that with regular AD [.Create(ClientId).WithTenantId(TenantId).WithAuthority(Authority)], this works.

**Possible Solution**

**Additional context/ Logs / Screenshots**

**Comment by henrik-me** [comment]
@ahmadizm, did you use a policy to add the claim to your b2c scenario?

This page gives some inputs on how to add claims using a policy: 
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-create-custom-attributes-profile-edit-custom

**Comment by ahmadizm** [comment]
No, I did not. So defining custom claims will replace modifying app manifest in b2c, or that is necessary in addition to manifest changes?
