### ISSUE TITLE
[Bug] Deserializing MSAL access tokens is broken

### ISSUE THREAD

**Issue by BenGoldberg** [AzureAD/microsoft-authentication-library-for-dotnet#1520]
Hi there,

We recently have run into an issue deserializing our access tokens. They have been working perfectly until today it seems. As far as I can tell we haven't made any changes to our code related to MSAL, so I'm not sure what's going on. Our BeforeAccess method looks like so:

```
var token = await _model.GetItemAsync<MicrosoftOAuthToken>(Query.Where(nameof(MicrosoftOAuthToken.UserId), userId));
if (token != null)
{
    try
    {
        args.TokenCache.DeserializeMsalV3(_encryptor.DecryptAsBytes(token.Value));
    }
    catch (MsalClientException)
    {
        // This will only be necessary for a little, once all the active clients have refreshed
        // their access token it will be using MsalV3 and we can drop this code.
        //
       args.TokenCache.DeserializeMsalV2(_encryptor.DecryptAsBytes(token.Value));
    }
}
```

Both deserializing calls are throwing. The V3 version throws this:

> MSAL V3 Deserialization failed to parse the cache contents. Is this possibly an earlier format needed for DeserializeMsalV2?

V2 throws this:

> Value cannot be null. (Parameter 'environment')

I believe all of our tokens are of the V3 format now though, so it shouldn't even be throwing the first exception. We've noticed that if we authenticate with a new user, the access token will work, but all of the existing tokens saved in our database no longer work. Any help would be much appreciated!

**Which Version of MSAL are you using ?**
MSAL 4.7.1

**Platform**
netcoreapp3.0

**Comment by jmprieur** [comment]
@BenGoldberg. 
Which kind of app do you have? Is it a Web app / Web API?  Do you use a specific cache technology? did you start from a sample? 
which version of MSAL did you update from?

**Comment by henrik-me** [comment]
@BenGoldberg : do you have a repro?

**Comment by henrik-me** [comment]
@BenGoldberg Closing as we need more information to proceed. Please re-open when you have time to provide the additional information.
