### ISSUE TITLE
How to Customize UserToken Serialization for iOS and Android (Xamarin)?

### ISSUE THREAD

**Issue by olegbaev** [AzureAD/microsoft-authentication-library-for-dotnet#1526]
Is it possible to customise Token Cache serialisation for **iOS/Android Xamarin** MSAL libraries?

According to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Token-cache-serialization this is _“NOT available on mobile platforms (UWP, Xamarin.iOS, Xamarin.Android) because MSAL already defines a secure and performant serialisation mechanism.”_

In our case due to high security requirements we shall **explicitly** control persistence of access and refresh tokens on the local device, unfortunately this is not possible with MSAL. 

I am realising that currently a local persistence of these tokens in MASL may seem to be secure enough for mobiles, however it **would be greatly appreciated if you provide a way to customise Token Cache serialisation for Xamarin iOS/Android libraries** for solutions where the current default is not good enough. I would imagine that it should be technically possible to remove this restriction for mobile.

Thanks in advance,
Oleg

**Comment by jmprieur** [comment]
We currently don't expose the extensibility for Xamarin.iOS and Xamarin.Android, but we could. you would be on your own, though.

**Comment by olegbaev** [comment]
Many thanks in advance - looking forward to see this enhancement in the next release of  MSAL :)

**Comment by jmprieur** [comment]
@olegbaev  can you please tell us more about your scenario, so that we can prioritize this feature?

**Comment by bgavrilMS** [comment]
@jmprieur - we currently use the KeyChain on iOS and SharedPreferences on Android. I believe that at least for Android there are better mechanisms that can be used, especially in newer versions of the OS. @olegbaev - where did you think of storing the token cache? 

Note that we already allow UWP users to oerride the default, I believe we should allow people to override the default on any platform. CC @henrik-me

**Comment by henrik-me** [comment]
@bgavrilMS @jmprieur : imo we should enable the extensibility on all platforms. Though it will also mean that it will not likely be easily possible for apps to share tokens securely between iOS native and Xamarin iOS and the same for Android.

**Comment by olegbaev** [comment]
@jmprieur - answering your question: **generally speaking secure storage of data on mobile largely depends on factors as:**
- platform 
- particular version of OS (especially on Android - the local storage was quite different for old versions)
- RELEASE or DEBUG build
- flags that instruct to include this storage data into backups  
**The point that I was making - there may/will be additional requirements to customise the storage (ex. encrypting the content at the application level).**
Also application developers with high level security requirements (ex. banking or medical data apps) need to control/understand **explicitly** where the most sensitive data such as tokens persisted on the device - these apps normally go via security reviews and security testing processes where we can't just blindly assume the the "default" implementation  is sufficient.

**Hence the original request to enable the storage extensibility on all platform is the best solution**

@henrik-me - I don't quite understand "_it will not likely be easily possible for apps to share tokens securely between iOS native and Xamarin iOS and the same for Android"_ - can you please explain what it means? If you mean that we need to have access to this storage from **both**  Xamarin Native project (Xamarin.iOS or Xamarin.Android) and also from the sharable project (ex. ".NET standard" project) of the **same** iOS or Android application then this problem is resolvable in one or another way (ex. dependency injection).
In the end the custom storage needs to be implemented by the application developers  in the platform Xamarin Native projects (separately for Xamarin.iOS or Xamarin.Android) and made accessible in the sharable project if needed. 
Thanks to everybody for considering this enhancement.

**Comment by henrik-me** [comment]
@olegbaev : Thanks for asking the clarifying questions. 

I'm not talking about sharing code between Xamarin apps and building a shared module.

The extensibility available in .NET is not available for native libraries on the respective platforms. For native I mean obj-c sharing with  Xamarin iOS and Android Java sharing with Xamarin Android. If you don't have that requirement/expectations then supporting extensiblity for Xamarin targets is certainly something we can do.

**Comment by olegbaev** [comment]
Thanks, @henrik-me.

Confirming that we don't have the requirement/expectations for obj-c sharing with Xamarin iOS and Android Java sharing with Xamarin Android.

I would think that other Xamarin developers will not have it either - with Xamarin we are working 99.5% with C#. For the remaining 0.5% I can't imagine any realistic scenarios when the token has to be sharable with the native code...

**Comment by henrik-me** [comment]
@olegbaev : thanks.

**Comment by jmprieur** [comment]
@shoatman : I would like to have your opinion on this one.

**Comment by DamianMehers** [comment]
FWIW if this were available I too would have used it, so that I can transfer the credentials to an Apple Watch app paired with the iPhone.

**Comment by jmprieur** [comment]
@olegbaev would that work for you if we encrypted the token cache on Xamarin.Android (when the OS supports it?)

**Comment by olegbaev** [comment]
@jmprieur, although encrypting the token cache on  Xamarin.Android will fortify security of the local token I feel that there are **many** usecases where delelopers will need more control over the local tokens. From my experience for mobile domain this is essential, we can't just rely on the third-party library (even a respectable library like yours) to handle this - we need to understand in **details** where are those secrets. Mobile devices live in the hostile world where sometimes they are lost/stolen, hence deep control over the local security is critical.

**Comment by bgavrilMS** [comment]
We have discussed about this feature internally and have decided to against it, because cache location and schema should be under MSAL's control. In the past, when developers have control over location / schema, this was causing problems when multiple apps where trying to use the same location .

**Comment by bgavrilMS** [comment]
We are rejecting this to be inline with the MSAL.ANdroid and MSAL.ios. We are working on aligning token cache encryption at rest with them.
