### ISSUE TITLE
Issue signing in on Android and when can we expect an update to the nuget-package?

### ISSUE THREAD

**Issue by siebigteroth** [AzureAD/microsoft-authentication-library-for-dotnet#153]
Hi,

I've trouble signing in on Android, because the sign in only works on the this attempt. The first two attempts don't return a token result. The login windows appears, where the user can sign in to the Azure AD's login website. But after that, the sign in fails. It works fine on the third attempt, where the library returns a token result and not null.

I'm using the current version from nuget (Microsoft Authentication Library 1.0.304142221-alpha) and I authenticate my users against an Azure B2C AD. I've tested by Xamarin.Forms/ Android application on Android 6 and 7. It works fine on Windows 8.1 and iOS.

I've seen that you made several improvements in the last weeks. And I'd love to try these.
When can we expect and update to the nuget package, mentioned above? :)
Is there any timeline or when can we expect a stable version of this great library on nuget?
Is further work planned from Microsoft on this library?

Keep up the great work and thanks in advance 👍

**Comment by kpanwar** [comment]
I am sorry but we don't have a date planned for next release yet.

**Comment by kpanwar** [comment]
I will reopen this in case the issue still exists after our E2E
