### ISSUE TITLE
Failing OBO Integration Test[Bug] 

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1530]
the Integration test named "OBO_WithCache_MultipleUsers_Async" is not working in azure DevOps. 

Error:
Test method Microsoft.Identity.Test.Integration.HeadlessTests.OboTests.OBO_WithCache_MultipleUsers_Async threw exception:
Microsoft.Identity.Client.MsalServiceException: Service is unavailable to process the request

**Comment by jmprieur** [comment]
@trwalke 
where is the Web API deployed? It's probably not running.

**Comment by bgavrilMS** [comment]
Fix

**Comment by bgavrilMS** [comment]
Test is running
