### ISSUE TITLE
Failing android app center tests

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1535]
The android app center tests are not working due to a error that occurs in all tests.

![image](https://user-images.githubusercontent.com/30090357/70253020-3f3fb000-1737-11ea-96ce-f80f3810077e.png)

checking the logs will show this message:
"The type initializer for 'Microsoft.Identity.Test.LabInfrastructure.LabUserHelper' threw an exception"

**Comment by bgavrilMS** [comment]
newtonsoft.json again?

**Comment by trwalke** [comment]
@bgavrilMS I believe so, same error. it works locally but now it wont run in appcenter

**Comment by trwalke** [comment]
This issue is no longer appearing in the tests
