### ISSUE TITLE
Xamarin iOS build certificate and Password need to be reset

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1536]
Due to the loss of access to the keyvault, when the xamarin iOS build task in azure devops runs, it fails build the project because it cannot sign the package with the ios signing certificate because the password for the cert is no longer available.

The Xamarin iOS build cert will need to be recreated and added to the azure devops UI automation build.

**Comment by jmprieur** [comment]
Redo

**Comment by henrik-me** [comment]
Please re-create cert and get the pipeline updated.

**Comment by neha-bhargava** [comment]
Fixed in [MSAL 4.12.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.12.0)
