### ISSUE TITLE
Get Device Id on Sign In

### ISSUE THREAD

**Issue by ferronsw** [AzureAD/microsoft-authentication-library-for-dotnet#1541]
I don't know if this is the right place to post this question. So if it isn't please let me know.
When a users signs in to my app I wan't to know there device id (only for Azure AD Joined devices). 
This Id is available in the sign in log under the device info tab of the Enterprise Application.

Is there a way to get this value on sign in?

**Comment by jmprieur** [comment]
@ferronsw : what is your scenario? is it a mobile app? do you use the system browser?

**Comment by ferronsw** [comment]
We have a web application (used in a browser) where we want to show, hide or block functionality when the device is trusted, compliant or not trusted at all (no deviceId avaiable).

**Comment by ferronsw** [comment]
using OpenID Connect

**Comment by ferronsw** [comment]
I did some tests and it looks like that by default only Microsoft Edge supplies the deviceid to the application, when using an Azure joined device.

**Comment by jmprieur** [comment]
@ferronsw : which other browsers did you test?

**Comment by ferronsw** [comment]
Chrome and FireFox. Chrome works when you install the "Windows 10 Accounts" extension.
