### ISSUE TITLE
[Feature Request] Migrate PKey Auth implementation to MSAL.NET

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1543]
PKey auth is needed to handle device authentication on mobile devices where browsers do not support client TLS and broker is not being used. The implementation should result in the the same behavior as ADAL.NET.

We can and should do the same for desktop. This is required for certain CA scenarios. Basic idea is we return not supported as that is what CA policies are asking for.
Align with support in other desktop libraries e.g.: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/720166

NOTE: System browsers will not be supported. Users will have to use the broker instead.

E2E validation:
Step-by-step policy configuration to get the optional-device-authentication:

1.	Create a CA policy for a particular user/app. In my example it’s All users / Sharepoint Online.
2.	Select Conditions -> Device State -> Configure: “Yes”
  a.	‘Include’ tab is selected with ‘All device state’
3.	Go to the exclude tab
  a.	Select any (or both) checkboxes
4.	Choose Grant Control = MFA.

With this configuration we are saying that all users going to Sharepoint should perform MFA, except if their device is compliant or Hybrid Domain joined.
So, what we do in ESTS is to attempt a best-effort device authentication to get the device properties, and would skip this policy if the device is compliant or hybrid domain joined.

When we attempt a device authentication in the silent endpoint (/token endpoint) we would expect a response with either the device certificate or with empty details. If it’s empty, we would just fallback to the MFA challenge.
The problem with Xamarin apps is that they are not responding with an empty device info, they just appear to be stuck in the client, and we never have a chance to perform MFA.

**Comment by henrik-me** [comment]
We should ensure to expand this to all platforms as certain CA policies needs us to return not supported  as a response to the protocol.

**Comment by jmprieur** [comment]
If the client does not answer to the challenge to the protocol, there is an exception. We need to return an empty value. We need to do it for Mobile, Desktop, UWP, and .NET Core.
This is only when using the embedded web view

**Comment by jmprieur** [comment]
On hold waiting for the test environment to be ready in the Lab

**Comment by cheenamalhotra** [comment]
Will this feature need any changes in consuming libraries or it will be implicitly handled by MSAL?

**Comment by trwalke** [comment]
No changes needed, MSAL will automatically start detecting PKey Auth challenges and respond to them assuming the proper device cert is available.
