### ISSUE TITLE
[Feature Request] Encrypt token cache in shared preferences on Xamarin.Android when the OS enables it

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1544]
**Is your feature request related to a problem? Please describe.**
Enable encryption at rest for the token cache to make more difficult for an adversary to use the data stored in the cache for malicious purposes.

Note: MSAL.Android native encrypts the token cache when possible on Android devices.

**_Notes on the security aspect:_**
 - Adding encryption at rest is categorized as Defense in depth.
 - Shared preferences on Android are meant to be only visible to the application (or application group) that creates them, however in practice on rooted devices, these values are easy to read.

**Comment by bgavrilMS** [comment]
There are 2 aspects to consider here: 

1. What encyption logic to use - MSAL.Android's (about 1000 lines of Java code) or [Xamarin.Essentials](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) (about 300 lines of C# code) ? The advantage of Xamarin.Essentials logic is that it's already written in C# and there are tests for it. I assume both have passed crypto board scrutiny as they are pretty low level. 

2. Migration from the old location to the new location. I think the simplest will be to do smth like: 

- when PCA is created (not on every Acquire* call), look in the old storage and if data is found, migrate it to the new storage and delete the old storage.

**Comment by henrik-me** [comment]
+1 to be inspired from Xamarin.Essentials and for the migration proposal.

**Comment by WilliamWatterson86** [comment]
@bgavrilMS We recently had an external company perform a pen test on our apps and this came up.  So hopefully the changes planned for v4.9 will help with this one.

Here was the result of the test:

Description:
The device stores sensitive information without making use of encryption in the shared preferences. In this instance, this sensitive information included the refresh token used to generate a new authorisation bearer header on the onmicrosoft.com domain. 

An attacker who had access to the shared preferences file, could potentially create a new authorisation bearer header and use it to authenticate and interact with the back-end API as the user of the mobile application.

Solution:
Storage of sensitive information should be avoided or reduced to the minimum required by the application functionality. Shared area of the filesystem cannot be used to store this information and encryption must be used even when information are stored in private area of the filesytem.

**Comment by jmprieur** [comment]
Discussing the possibility of having an opt-in flag and leave the migration aspect in 4.?
Or let developer specify their own persistence (if they have super stick security requirements).

**Comment by stevehansen** [comment]
Any updates on this, we also got this from our pentest that the tokens were stored in plain text, the documentation mentions that it should have been using "secure storage", we tried to use the TokenCache hook but that just crashed our application:

```
System.PlatformNotSupportedException: 'You should not use these TokenCache methods on mobile platforms. They are meant to allow applications to define their own storage strategy on .net desktop and non-mobile platforms such as .net core. On mobile platforms, MSAL.NET implements a secure and performant storage mechanism. For more details about custom token cache serialization, visit https://aka.ms/msal-net-serialization'
```

Running on MAUI for .NET 7

**Comment by localden** [comment]
I am trying to understand the attack vector here - if the phone is locked and the device is encrypted, key exfiltration should not be possible, no?

Assuming that the vector here is more along the lines of "malicious app installed on the device tries to exfiltrate tokens from the filesystem cache," I like the suggested approach of "feature flagging" this change, enabling customers to opt-in for a more secure storage of tokens (that will auto-migrate the cache to the new format). Could we potentially add something like `.WithEncryptedTokenCache(KeyToEncrypt)` to the PCA builder for this?

**Comment by stevehansen** [comment]
@localden that was mostly the idea that I tried, following the MSDN documentation about the ITokenCache and had code like this:

```c#
internal static class TokenCacheHelper 
{ 
    private const string CacheKey = nameof(CacheKey); 
 
    public static void EnableSerialization(ITokenCache tokenCache) 
    { 
        tokenCache.SetBeforeAccess(BeforeAccessNotification); 
        tokenCache.SetAfterAccess(AfterAccessNotification); 
    } 
 
    private static readonly string CacheFilePath = Path.Combine(FileSystem.CacheDirectory, "msalcache.bin3"); 
    private static readonly object FileLock = new(); 
 
    private static void BeforeAccessNotification(TokenCacheNotificationArgs args) 
    { 
        lock (FileLock) 
        { 
            args.TokenCache.DeserializeMsalV3(File.Exists(CacheFilePath) 
                ? GetCrypto().Decrypt(File.ReadAllText(CacheFilePath)) 
                : null); 
        } 
    } 
 
    private static void AfterAccessNotification(TokenCacheNotificationArgs args) 
    { 
        // if the access operation resulted in a cache update 
        if (args.HasStateChanged) 
        { 
            lock (FileLock) 
            { 
                // reflect changes in the persistent store 
                File.WriteAllText(CacheFilePath, GetCrypto().Encrypt(args.TokenCache.SerializeMsalV3())); 
            } 
        } 
    } 
 
    private static Crypto GetCrypto() 
    { 
        byte[] password; 
 
        var storeKey = SecureStorage.GetAsync(CacheKey).GetAwaiter().GetResult(); 
        if (string.IsNullOrEmpty(storeKey)) 
        { 
            password = RandomNumberGenerator.GetBytes(32); 
            SecureStorage.SetAsync(CacheKey, Convert.ToBase64String(password)).Wait(); 
        } 
        else 
            password = Convert.FromBase64String(storeKey); 
 
        return new(password); 
    } 
} 
```

Where our Crypto class is what we used in the rest of the app to encrypt data. But you can't use the hook at the moment on mobile platforms:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/TokenCache.Notifications.cs#L183

**Comment by bgavrilMS** [comment]
This is correct, we actively prevent folks from using token cache extensibility on mobile, in the idea that MSAL just does it for you. 

I agree that MSAL could do a better job, the problem is that moving to a different cache mechanism involves some sort of cache migration to read from old unencrypted location.

**Comment by bgavrilMS** [comment]
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1361

**Comment by Lucasian20** [comment]
Any news on the progress of this request - shouldn't these files really be stored in secure storage, rather than shared preferences without encryption. We also have had a pen test highlight this as a vulnerability. I also noticed that these files do not delete in shared preferences when logging out by deleting Accounts so I have had to delete/clear them manually.

**Comment by pdallat-pcs** [comment]
Any update??

**Comment by Skarzag** [comment]
Hello ! We just got an external pentest highlighting this issue 😅
