### ISSUE TITLE
TokenCacheKey constructors that take in AuthenticationRequestParameters

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/microsoft-authentication-library-for-dotnet#155]
One of the refactors we did in ADALObjC was methods that take in request parameters and explicitly return a key for (SR)RT, MRRT or FRRT. This made developer intent quite a bit clearer in the code, and subsequently considerably more readable. I'd highly recommend copying the pattern over.

**Comment by kpanwar** [comment]
not required as we only have 1 type of RT.
