### ISSUE TITLE
[Feature Request] Update json serialization library to System.Text.Json

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1550]
Replace json serialization/deserialization to use
https://www.nuget.org/packages/System.Text.Json/

**Comment by bgavrilMS** [comment]
This is not achievable because System.Text.Json does not support all the frameworks MSAL is built againt: 

| TFM | MSAL | System.Text.Json |
| - | - | - |
| net classic | 4.5 | 4.6.1 | 
| net standard | 1.3 | 2.0 |
| UAP | 10 | 10.0.16 | 
| Android | 9 | 10 |

**Comment by bgavrilMS** [comment]
The TFMs are no longer relevant and we should explore moving to system.text

**Comment by pmaytak** [comment]
Related [migration doc](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-6-0).
