### ISSUE TITLE
[Bug] Xamarin.IOS App Authentication not working due to Keychain Security Group

### ISSUE THREAD

**Issue by yonathanseleshi** [AzureAD/microsoft-authentication-library-for-dotnet#1562]
**Which Version of MSAL are you using ?**

Microsoft.Identity.Client 4.7.1

**Platform**

Xamarin Forms 4+, Xamarin.IOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [*] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

This app is in development and I upgraded from Microsoft.Identity.Client 2.7.1 to 4.7.1

**Repro**

 PublicClient = PublicClientApplicationBuilder
                .Create(ClientID)
                .WithIosKeychainSecurityGroup("com.microsoft.adalcache")
                .WithRedirectUri("msal[tenantid]://auth")
                .Build();

authResult = await PublicClient.AcquireTokenInteractive(WebAPIScope)
                                   .WithAuthority("[login ur]>")
                                   .WithParentActivityOrWindow((UIKit.UIViewController)App.ParentWindow)
                                   .ExecuteAsync();

**Expected behavior**

The Authentication Should show Interactive browser window upon failure to locate existing token in the cache

**Actual behavior**

App works fine on simulator and crashes when run on device the first time.  I get this message in Visual Stuido Mac:

================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

The following times the app does not crash but simply does not complete the authentication process and I get this error:

Error Domain=NSOSStatusErrorDomain Code=-34018 "Client explicitly specifies access group com.microsoft.adalcache but is only entitled for (
    "CXRPI73SD2.com.microsoft.adalcache",
    "CXRPI73SD2.com.<my appidentifier>",
    "CXRPI73SD2.com.<my appidentifier>",
    "com.apple.token"
)" UserInfo={NSDescription=Client explicitly specifies access group com.microsoft.adalcache but is only entitled for (
    "CXRPI73SD2.com.microsoft.adalcache",
    "CXRPI73SD2.com.<my appidentifier>",
    "CXRPI73SD2.com.<my appidentifier>",
    "com.apple.token"
)}

**Possible Solution**

I have checked my entitlements and info.plist.  Everything seems to be setup properly per the documentation and again everything is working on the simulator

**Comment by jmprieur** [comment]
@yonathanseleshi 
- did you read https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations ?
- what did you use for `[login ur]>` ?

**Comment by yonathanseleshi** [comment]
> @yonathanseleshi
> 
> * did you read https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations ?

Yes, I read 
> * what did you use for `[login ur]>` ?

"https://login.microsoftonline.com/[tenant id]"

The authentication worked just fine on the simulator using the code above, but failed on my team's iPads with the error described above.

I'm not sure if there is something I'm missing for it to work on the device.  Here is what's in my AppDelegate:


       public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {

            SQLitePCL.Batteries_V2.Init();
            global::Xamarin.Forms.Forms.Init();
            new FreshEssentials.iOS.AdvancedFrameRendereriOS();


            LoadApplication(new App());

            App.ParentWindow = null;

            return base.FinishedLaunching(app, options);
        }



        public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
        {
            if (url.Scheme.Contains("oravision"))
            {
                OptikamHelper.RecordMeasurements(url.AbsoluteString);
                App.Current.MainPage.Navigation.PopToRootAsync();
    
            }
            else
            {
                AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(url);
            }

            return true;
        }

**Comment by jennyf19** [comment]
@yonathanseleshi What do your entitlements look like? Sometimes you also have to right click the properties of the project and manually add the entitlements:
![image](https://user-images.githubusercontent.com/19942418/72050359-c8399200-3275-11ea-850d-04ee93cdf364.png)

If you have a basic repro you want to share, that works as well.
cc: @aiwangmicrosoft

**Comment by yonathanseleshi** [comment]
> @yonathanseleshi What do your entitlements look like?


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>
		<string>$(AppIdentifierPrefix)[App's Bundle Identifier]</string>
	</array>
</dict>
</plist>

> If you have a basic repro you want to share, that works as well. Also, does this work on a device?

This is a Xamarin.Forms/iOS App.  When my app launches it begins the authentication sequence with 

PublicClient = PublicClientApplicationBuilder
.Create(ClientID)
.WithIosKeychainSecurityGroup("com.microsoft.adalcache")
.WithRedirectUri("msal[tenantid]://auth")
.Build();

authResult = await PublicClient.AcquireTokenSilent(WebAPIScope, firstAccount).ExecuteAsync();

then if that fails it calls:

authResult = await PublicClient.AcquireTokenInteractive(WebAPIScope)
                   .WithAuthority("https://login.microsoftonline.com/[tenant id]")
                    .WithParentActivityOrWindow((UIKit.UIViewController)App.ParentWindow)
                    .ExecuteAsync();

I don't think it even reaches the authentication code.  I suspect there is an issue with the attempts to use the iOS Keychain Security Group on the iPad. 

This only works on the iOS Simulator not on the device.  I deployed it directly from Visual Studio onto my iPad and via AppCenter to another user's iPad and neither worked. 

I rolled back to version 2.7.1 yesterday and the Authentication is working again on device.

**Comment by jennyf19** [comment]
@yonathanseleshi thanks for the additional details. Can you send me the logs for a failed request?
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging
 Thank you

**Comment by yonathanseleshi** [comment]
> @yonathanseleshi thanks for the additional details. Can you send me the logs for a failed request?
> https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging
> Thank you

 I rolled back to version 2.7.1 to get the app working again.  I didn't save any logs.  I'll switch back to 4.7.1 and post the logs.

**Comment by jennyf19** [comment]
@yonathanseleshi closing, but please reopen if the issue persists.
