### ISSUE TITLE
[Documentation] Add an aka.ms link on method using x5c to link to 1P doc

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1568]
### Documentation Related To Component:
Add an aka.ms link in the XML documentation of methods that use the x5c parameter
The proposal is to use https://aka.ms/msal-net-sni so that first party partner learn about the way to use this API to roll over certificates using Subject Name Issuer (SNI)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Comment by jennyf19** [comment]
Released in [4.8.2](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.8.2)
