### ISSUE TITLE
Xamarin iOS always requires sign in web UI

### ISSUE THREAD

**Issue by JonJam** [AzureAD/microsoft-authentication-library-for-dotnet#157]
I have an Xamarin iOS app using Microsoft.Identity.Client version 1.0.304142221-alpha connected to an AD B2C production instance set up with a separate Sign Up and Sign In policies.

The PublicClientApplication instance is created within the iOS project.

Currently the application always requires users to sign in using the Web UI, even after previously signing up or logging in. This can be re-produced using the following steps:

1. Launch the app.
2. Login.
3. After successfully logged in, press the Home Button.
4. Double press the Home button and swipe up on the App to remove.
5. Re-launch the app.

**Expected Results**
AcquireTokenSilently succeeds and user is signed in.

**Actual Results**
AcquireTokenSilently fails and user has to sign in using AcquireTokenAsync (Web UI).

**Comment by kpanwar** [comment]
Are you making acquireTokenSilent call for the same policy that you had used to call acquireToken?

**Comment by JonJam** [comment]
@kpanwar Yes I am- code below:

  private async Task SignInSilently()
        {
            AuthenticationResult authenticationResult = await this.application.AcquireTokenSilentAsync(
                new string[] { "CLIENT ID" },
                (string)null,
                "https://login.microsoftonline.com/AUTHORITY.onmicrosoft.com/",
                "B2C_1_SiIn",
                false);
        }

        public async Task SignIn()
        {
            AuthenticationResult authenticationResult = await application.AcquireTokenAsync(
                new string[] { "CLIENT ID" },
                (string)null,
                UiOptions.SelectAccount,
                null,
                null,
                "https://login.microsoftonline.com/AUTHORITY.onmicrosoft.com/",
                "B2C_1_SiIn");
        }

**Comment by jherby2k** [comment]
Agreed this issue seems to only affect the simulator, not actual devices.
