### ISSUE TITLE
[Feature Request] Improve ROPC experience by providing better errors and default authority

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1574]
See bug #1572 for details

The default authority (aad/common) does not work with ROPC because live accounts do not support ROPC (and never will). Developers are having problems with this, as the error message from Evo is not clear (see bug #1572 for details). 

A better experience can be provided by: 

1. Throw an MSAL client exception if the authority tenant is `common` or `consumenrs` 
2. Default to `/organizations` tenant if user does not specify an authority

**Comment by jmprieur** [comment]
Thanks @bgavrilMS 
2. might be better
