### ISSUE TITLE
Error message : field not found: microsoft.identity.client.ui behavior.select account

### ISSUE THREAD

**Issue by thomas-julien** [AzureAD/microsoft-authentication-library-for-dotnet#1579]
**Which Version of MSAL are you using ?**
MSAL 3.0.0

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ]  Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;
```csharp
*Program.cs*
                graphClient = GraphServiceClientProvider.GetAuthenticatedClient();
                cal = new CalendarController(graphClient);
                RunAsyn().GetAwaiter().GetResult();

*GraphServiceClientProvider.cs*

        public static GraphServiceClient GetAuthenticatedClient()
        {
            if (graphClient == null)
            {
                // Create Microsoft Graph client.  
                try
                {
                    

                    IPublicClientApplication clientApplication = PublicClientApplicationBuilder.Create(clientId).Build();
                    InteractiveAuthenticationProvider authProvider = new InteractiveAuthenticationProvider(clientApplication, scopes);

                    graphClient = new GraphServiceClient(authProvider);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine("Could not create a graph client: " + ex.Message);
                    throw ex;
                }
            }
            return graphClient;
        }

**Comment by bgavrilMS** [comment]
@thomas-julien - please fill in the form with all the details about the bug. You just pasted some code.

**Comment by jennyf19** [comment]
@thomas-julien also, can you update to the latest version of MSAL and see if it repros there as well? thanks.

**Comment by thomas-julien** [comment]
All the code here : https://mega.nz/#F!ANoXCKzT!Zssq6WJ1RohTpC9kjLy5GA
I'm trying to recover, add ,delete and show events of microsoft calendar. It's my first time on using microsoft AzureAD and its APIs. So i don't know how this error  was made.

**Comment by bgavrilMS** [comment]
Here's a sample that shows you how to get a token for the Graph using interactive authentication. We strongly advise you not to use "username/password" ROPC flow. 

https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2

Once you are able to get a token, you can integrate this with the Graph SDK easily. Note that this repo is for MSAL, i.e. getting the tokens. We do not handle Graph operations, but we will get you a token for Graph :)
