### ISSUE TITLE
[Bug] Interactive broker flow is broken if broker app not installed

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1583]
**Which Version of MSAL are you using ?**
msal 4.7.1

**Platform**
ios, android

1. Developer asks for broker to be used
2. Broker is not installed on device

Expected: a flow where user is asked to install broker
Actual: Broker Install URL is null and experience is broken (not exactly sure how, this bug is based on observing code flow). 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs#L72

**Comment by jmprieur** [comment]
@bgavrilMS : normally Azure AD will trigger the installation, and send back a URL to check. Is it that we don't retrieve it?

**Comment by bgavrilMS** [comment]
Yes, by reading the code it seems that there are 2 corner-case scenarios: 

1. Developer wants to use the broker, but it isn't installed (this one is buggy)

2. Developer does **not** want to use the broker, but AAD (via Conditional Access) tells MSAL that it NEEDS to use the broker. The way that this is done is that AAD returns a special authorization code that contains the broker URI.
2.1. If a broker is installed, then MSAL will invoke the broker
2.2 If a broker is not installed, MSAL will guide the user to install the broker. The broker URI is required.

Use case 1 and use case 2.2 share the same code path, but there is not authorization code, so the broker URI is null. 

PS: I will update our test plan with these 3 tests
