### ISSUE TITLE
[Bug] Xamarin.Android authentication fails since 4.8.0

### ISSUE THREAD

**Issue by tipa** [AzureAD/microsoft-authentication-library-for-dotnet#1585]
**Which Version of MSAL are you using ?**
MSAL 4.8.0 (bug not present with v4.7.1)

**Platform**
Xamarin.Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Repro**
```
authResult = await clientApplication.AcquireTokenInteractive(Scopes)
   .WithParentActivityOrWindow(myActivity)
   .ExecuteAsync();
```

**Expected behavior**
User can enter login credentials and `AcquireTokenInteractive` method returns with `authResult`

**Actual behavior**
`AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs` throws exception and `AcquireTokenInteractive` does not return with a value

**Additional context/ Logs / Screenshots**
![image](https://user-images.githubusercontent.com/2863198/72796021-e5d80580-3c3e-11ea-8217-c12c09097a75.png)

**Comment by bgavrilMS** [comment]
Thanks for reporting @tipa, we did some work to integrate the Android broker and our Android integration tests obviously need some work :).

**Comment by bgavrilMS** [comment]
@jmprieur @henrik-me - this and https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1586 suggest we need to do a full test pass on Xamarin scenarios. I suggest we unlist version 4.8.0 from NuGet, as it is likely not usable.

**Comment by Daniel-NP** [comment]
Just wanted to post the same issue. Good to know that it's not my fault. @bgavrilMS I agree with you, unlisting would make sense.

**Comment by jmprieur** [comment]
@bgavrilMS I agree that we should unlist 4.8.0, but we also have to re-update the samples (which were updated to 4.8.0)

**Comment by bgavrilMS** [comment]
Well the samples will continue to work, minus the Xamarin sample which we didn't update anyway. Once we release 4.8.1 we will update the samples to that. Unlisting is more like hiding, the package is still there.

But I agree that it might be safer to revert the samples.

**Comment by bgavrilMS** [comment]
Unlisted 
![image](https://user-images.githubusercontent.com/12273384/72810635-e4fe9e00-3c55-11ea-85fb-f3d2b826ce7c.png)

**Comment by jennyf19** [comment]
@tipa @Daniel-NP issue has been fixed and merged into master. we are working on getting a release out. thanks for reporting this.
