### ISSUE TITLE
[Bug][VS] System Default Browser - Chrome sometimes does not display the success message

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1587]
**Which Version of MSAL are you using ?**
4.7.1

**Platform**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
This is VS

**Repro**

1. Configure the system default browser on .net 45
2. Make sure the default browser is Chrome. This bug does not repro with any other browser, especially Edge
3. Run the flow

**Expected behavior**
a. User is logged In 
b. Success Message is displayed

**Actual behavior**
a. User is logged in
**b. standard 404 message is displayed**

**Impact**: VS would like to use a redirect instead of the success message to teach users how to handle multiple identities

**Possible Solution**
It may be that MSAL waits for too long before responding with a 200 OK message to the browser.

**Comment by bgavrilMS** [comment]
CC @crmann1

**Comment by bgavrilMS** [comment]
@crmann1 - I can't seem to be able to repro this. Do you have a machine where this repros?

**Comment by jmprieur** [comment]
@crmann1 : closing for now. Feel free to reopen if you have a repro
