### ISSUE TITLE
[Issue] - NuGet Package - Errors caused by 4.8.0 package unlisting

### ISSUE THREAD

**Issue by sujayvsarma** [AzureAD/microsoft-authentication-library-for-dotnet#1592]
Sometime ago, the team published a `4.8.0` version of the Microsoft.Identity.Client package on NuGet. But the package was unlisted a couple of days ago. However, tools like Visual Studio and `build  restore` find this package and produce an `NU1605` hard-fail error while performing a restore packages & build step.  This is causing quite some consternation.

![Screenshot](https://user-images.githubusercontent.com/7371750/72965587-c11c9300-3de2-11ea-8ee2-d9ec8742dd58.png)

Recommended solution:
If there will be no immediate bumped build, recommend republishing existing `4.7.1` as `4.8.1` to mitigate.

**Comment by bgavrilMS** [comment]
Ack @sujayvsarma, I did not realize this implication. We are actively testing 4.8.1 now.

**Comment by bgavrilMS** [comment]
I just tested with a netcore (SDK 3.1) project in Visual Studio 16.5, with `msbuild /t:restore` and with `dotnet restore` and I did not get any warnings. What env did you use ?

We would not be able to publish 4.7.1 as 4.8.1 because in 4.8 we have added new public APIs which would be removed by the "fake" 4.8.1, thus constituting a breaking change.

**Comment by sujayvsarma** [comment]
Am not the one that configured it, but the build set up is supposed to auto update minor versions if available (that is, 4.7 -> 4.8 will cause an update+restore, but 4.7->5.0 will not do anything). That is what essentially broke the build at our end. 

I believe the team has now taken a temporary hard dependency on 4.7.1 until this is resolved. 

PS: Curious why the version was unlisted ? I took a private copy of our project source, updated it to 4.8 and tried it, flows where we were actively using the library features seemed to work fine.

**Comment by sujayvsarma** [comment]
My Visual Studio [2019 Community Edition, 16.5 Preview 2.0] did find the unlisted 4.8 when I tried to update some *other* packages. but when I just updated the csproj with the 4.8 and hit CTRL+S, it restored 4.8 just fine, and I was able to update other packages after that.

Basically:
- Add N-1 versions of other packages to a project
- now add the 4.7.1 Microsoft.Identity.Client package
- In VS, go into "Manage NuGet Packages for Solution"
- Switch to "Updates"
- it will show you updates for everything except the Microsoft.Identity.Client package
- Select everything, hit UPDATE

It will spin for a while and fail. You will see NU1605 as an ERROR in your Error List window.

Edit your .csproj file, and change the version number against Microsoft.Identity.Client to 4.8, save and restore -- without going into the "Manage NuGet Packages for Solution" window. It will restore and install 4.8 into your project. Now open the "Manage NuGet Packages for Solution" window and hit UPDATE from there, everything will update fine.

Weird huh?

**Comment by sujayvsarma** [comment]
Tagging @mavasani as it could be an issue in the VS "Manage NuGet Packages for Solution" window.

**Comment by bgavrilMS** [comment]
@sujayvsarma - the reason we unlisted 4.8.0 is a bug when MSAL is used from Xamarin.Android - this is described - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1585

Otherwise, we're pretty confident that MSAL outside of iOS and Android is fine...

**Comment by karann-msft** [comment]
Speaking on behalf of the nuget team, unlisting a package has no impact on any project that already references it. Unlisting does not prevent restoring the package. It is purely a search and discovery concept.

**Comment by sujayvsarma** [comment]
@karann-msft - this issue has nothing to do with Nuget.

**Comment by sujayvsarma** [comment]
This is an issue with the VS [or the ecosystem that performs the package discovery, restore/update] and not with core Nuget or with this ADAL library. I will refile the issue in appropriate repos / ticket centers after I determine which one is the most appropriate. Towards that end, I am already in conversation with folks I consider relevant to continuing this discussion.

Therefore, I respectfully close this issue in **this** repo.
