### ISSUE TITLE
[Bug] MSAL confirmation dialog in Xamarin iOS

### ISSUE THREAD

**Issue by JohnLivermore** [AzureAD/microsoft-authentication-library-for-dotnet#1594]
We are using the Microsoft MSAL library to authenticate our users.  When a user needs to login, they are shown this dialog each time.  Is there a way to disable this prompt so the login experience is more seamless?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/9BNA0.png

**Comment by jennyf19** [comment]
@JohnLivermore This pops up anytime the app uses SFAuthenticationSession or ASWebAuthenticationSession, we cannot change what is displayed there, as that is the point of the pop up. From Apple's developer site: " users are prompted by a dialog to give explicit consent, allowing the application to access the website’s data in Safari. When the webpage is presented, it runs in a separate process, so the user and web service are guaranteed that the app has no way to gain access to the user’s credentials. "

Closing as by-design, we have no control over this dialog.

cc: @jmprieur
