### ISSUE TITLE
[Documentation] Update code in wiki which refers to UIParent

### ISSUE THREAD

**Issue by JohnLivermore** [AzureAD/microsoft-authentication-library-for-dotnet#1595]
### Documentation Related To Component:
WIKI located here...

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
In the wiki it states...

![image](https://user-images.githubusercontent.com/1489667/73006559-772ab180-3dd0-11ea-8ad5-2a7dc20d9a01.png)

It says use AppDelegate.cs, but App.UIParent doesn't exist (tried in FinishedLaunching method).

Where do you add this code?  The Wiki should probably be updated?

**Comment by jennyf19** [comment]
@JohnLivermore this is outdated...thanks for bringing it to our attention

**Comment by JohnLivermore** [comment]
I was wondering if using an embedded/system browser might make a difference in that iOS prompt that displays.  Can you provide guidance on how to use the system browser or embedded window?  Or if you are certain that won't solve this 'prompt' issue (you answered my question earlier today), then just let me know!

**Comment by jennyf19** [comment]
@JohnLivermore you'll only see the prompt with the system browser, which is on by default in MSAL.NET.

Here's what you'll need for the [parent window](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withparentactivityorwindow)

and how to enable [embedded webview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withuseembeddedwebview)

When using embedded webview, you will lose the browser SSO, which the system browser provides and if doing Google Auth (w/B2C), you will not be able to use the [embedded webview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#google-auth-and-embedded-webview)

Will get the doc updated later today.

**Comment by ps-rpopola** [comment]
Just and FYI, if you're using Apple Sign In, you'll need to use the embedded browser as for some reason the system browser hangs and doesn't actually load the b2c web site.

**Comment by ps-rpopola** [comment]
Just and FYI, if you're using Apple Sign In, you'll need to use the embedded browser as for some reason the system browser hangs and doesn't actually load the b2c web site.

**Comment by jennyf19** [comment]
@ps-rpopola yes, thanks...have updated my response above.

**Comment by JohnLivermore** [comment]
thanks for the clarification

**Comment by jennyf19** [comment]
@JohnLivermore [documentation updated](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#developer-options). thanks again.
