### ISSUE TITLE
Xamarin iOS app with AD B2C Google social provider results in 403 error.

### ISSUE THREAD

**Issue by JonJam** [AzureAD/microsoft-authentication-library-for-dotnet#161]
I have an Xamarin iOS app using Microsoft.Identity.Client version 1.0.304142221-alpha connected to an AD B2C production instance set up with a separate Sign Up and Sign In policies; as well as Google Social Provider.

Currently when trying to sign up with Google, a Google error page is displayed with the information:

403: That's an error
Error: disallowed _useragent

This is probably due to changes made by Google for OAuth detailed here: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by kpanwar** [comment]
Google is blocking the trident control used in desktop apps. It will be soon b e resolved from Google's end.
