### ISSUE TITLE
Providing Nonce

### ISSUE THREAD

**Issue by mikeliddle** [AzureAD/microsoft-authentication-library-for-dotnet#1612]
We're working on a project using AAD App Authentication and OpenIDConnect access tokens, and are wanting to enforce nonce to prevent replay attacks on tokens. We noticed that the identity docs support nonce, but don't see an exposed way to add nonce to the authorization request.

**Comment by jmprieur** [comment]
MSAL.NET uses a state that acts as a nonce. Do you need more, @mikeliddle ?

**Comment by mikeliddle** [comment]
State and nonce are very different.

See this article: https://stackoverflow.com/questions/46844285/difference-between-oauth-2-0-state-and-openid-nonce-parameter-why-state-cou

Basically State protects the end user from CSRF attacks, but Nonce is used to bind a token with a client, which helps to prevent token replay attacks. Likewise, the implicit and hybrid flows for OIDC mandate a nonce value, which are generated by the client application, so saying state acts as nonce isn't sufficient, no.

**Comment by jmprieur** [comment]
Thanks @mikeliddle 
My suggestion would be to use the [WithExtraQueryParameters](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractacquiretokenparameterbuilder-1.withextraqueryparameters?view=azure-dotnet#Microsoft_Identity_Client_AbstractAcquireTokenParameterBuilder_1_WithExtraQueryParameters_System_String_) API

Something like
```CSharp
AcquireTokenXXX(scopes)
         .WithExtraQueryParameters(new Dictionary<string,string> { {"none", nonValue} })
         .ExecuteAsync();

```

**Comment by mikeliddle** [comment]
We tried that during the application builder stage, but when we inspected the ID token, it does not contain the nonce. Does it make a difference if you add the query param to the application object or the Acquire call?

**Comment by jmprieur** [comment]
@mikeliddle : yes. Extra query parameters are really an extensibility point. As you mentioned, in the protocol docs, the nonce is sent when acquiring the token.

**Comment by Alan-Jowett** [comment]
Something doesn't match here. Trying this in the browser, I hit this endpoint (line breaks for readability):
https://login.windows-ppe.net/426c7629-1a11-43c9-af1f-cbbdd3af6ce1/oauth2/authorize?
client_id=769cc236-2a91-415c-9e7e-7fa795fd4827
&response_type=id_token
&response_mode=fragment
&scope=openid
**&nonce=MyRandomNonce**

After logging in, it redirects me to:
https://localhost/#
id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik9vTjZScnpSdldaSUFZTDhiNHNFd2lRdkY4cyIsImtpZCI6Ik9vTjZScnpSdldaSUFZTDhiNHNFd2lRdkY4cyJ9.eyJhdWQiOiI3NjljYzIzNi0yYTkxLTQxNWMtOWU3ZS03ZmE3OTVmZDQ4MjciLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvNDI2Yzc2MjktMWExMS00M2M5LWFmMWYtY2JiZGQzYWY2Y2UxLyIsImlhdCI6MTU4MTAzMTU0MSwibmJmIjoxNTgxMDMxNTQxLCJleHAiOjE1ODEwMzU0NDEsImFpbyI6IkUyUmdZT0RWVGd3NGQvV2J4ZU1MUWw5bWhBV0hGT2VyNTlyZHZ0SE85VHpDbzNmTi9Pa0EiLCJhbXIiOlsicHdkIl0sImZhbWlseV9uYW1lIjoiTW9ua2V5IiwiZ2l2ZW5fbmFtZSI6IlRlbmFudCIsImlwYWRkciI6IjIwOC41NC4yMzMuMTUxIiwibmFtZSI6IlRlbmFudCBNb25rZXkgQWNjb3VudCIsIm5vbmNlIjoiTXlSYW5kb21Ob25jZSIsIm9pZCI6IjQ0NjBhZjgwLTFkZTItNDNhNS05YjBmLWM2YTU3MDY2MWM3OCIsInN1YiI6Imt1bjBKRHVETzl2dGdlUGZLVnZrTFc1bUNwZDFQZzhGbm1BVTBycUh3S1kiLCJ0aWQiOiI0MjZjNzYyOS0xYTExLTQzYzktYWYxZi1jYmJkZDNhZjZjZTEiLCJ1bmlxdWVfbmFtZSI6ImFkbWluQGFsYW5qbzIwMDF2Mi5jY3NjdHAubmV0IiwidXBuIjoiYWRtaW5AYWxhbmpvMjAwMXYyLmNjc2N0cC5uZXQiLCJ1dGkiOiJLVGZJZkJpNDRrVy10X2ZoS2pOQUFBIiwidmVyIjoiMS4wIn0.\<signature removed\>
&session_state=\<session state remove\>

Decoding this token shows:
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "OoN6RrzRvWZIAYL8b4sEwiQvF8s",
  "kid": "OoN6RrzRvWZIAYL8b4sEwiQvF8s"
}.{
  "aud": "769cc236-2a91-415c-9e7e-7fa795fd4827",
  "iss": "https://sts.windows-ppe.net/426c7629-1a11-43c9-af1f-cbbdd3af6ce1/",
  "iat": 1581031541,
  "nbf": 1581031541,
  "exp": 1581035441,
  "aio": "E2RgYODVTgw4d/WbxeMLQl9mhAWHFOer59rdvtHO9TzCo3fN/OkA",
  "amr": [
    "pwd"
  ],
  "family_name": "Monkey",
  "given_name": "Tenant",
  "ipaddr": "208.54.233.151",
  "name": "Tenant Monkey Account",
  **"nonce": "MyRandomNonce"**,
  "oid": "4460af80-1de2-43a5-9b0f-c6a570661c78",
  "sub": "kun0JDuDO9vtgePfKVvkLW5mCpd1Pg8FnmAU0rqHwKY",
  "tid": "426c7629-1a11-43c9-af1f-cbbdd3af6ce1",
  "unique_name": "admin@alanjo2001v2.ccsctp.net",
  "upn": "admin@alanjo2001v2.ccsctp.net",
  "uti": "KTfIfBi44kW-t_fhKjNAAA",
  "ver": "1.0"
}.

I would expect this to be equivalent to:
>var ClientId = "769cc236-2a91-415c-9e7e-7fa795fd4827";
>var TenantId = "426c7629-1a11-43c9-af1f-cbbdd3af6ce1";
>var clientApp = PublicClientApplicationBuilder.Create(ClientId).WithAuthority($"https://login.windows-ppe.net/{TenantId}/").WithDefaultRedirectUri().Build();
>var result = await clientApp.AcquireTokenWithDeviceCode(Scopes, PromptForDeviceCode).WithExtraQueryParameters("nonce=MyRandomNonce").ExecuteAsync();
Console.WriteLine(result.IdToken);

So, what gives...

**Comment by jmprieur** [comment]
@henrik-me @bgavrilMS @jennyf19 @trwalke 
is WithExtraQueryParameters only applied to the /token endpoint?

**Comment by Alan-Jowett** [comment]
Hmm, this seems to be only an issue with the DeviceCode flow...

>var ClientId = "769cc236-2a91-415c-9e7e-7fa795fd4827";
>var TenantId = "426c7629-1a11-43c9-af1f-cbbdd3af6ce1";
>
>var clientApp = PublicClientApplicationBuilder.Create(ClientId).WithHttpClientFactory(new Factory()).WithAuthority($"https://login.windows-ppe.net/{TenantId}/").WithRedirectUri("http://localhost").WithExtraQueryParameters("nonce=MyRandomNonce").Build();
>var result = await clientApp.AcquireTokenInteractive(Scopes).ExecuteAsync();
Console.WriteLine(result.IdToken);

Results in this token:
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9vTjZScnpSdldaSUFZTDhiNHNFd2lRdkY4cyJ9.eyJhdWQiOiI3NjljYzIzNi0yYTkxLTQxNWMtOWU3ZS03ZmE3OTVmZDQ4MjciLCJpc3MiOiJodHRwczovL2xvZ2luLndpbmRvd3MtcHBlLm5ldC80MjZjNzYyOS0xYTExLTQzYzktYWYxZi1jYmJkZDNhZjZjZTEvdjIuMCIsImlhdCI6MTU4MTA0Mjc2OCwibmJmIjoxNTgxMDQyNzY4LCJleHAiOjE1ODEwNDY2NjgsImFpbyI6IkFUUUF5LzhSQUFBQXJtOTNEYnNvS3d1WlVlTG9vOUZzY29EUXNONFk2dzh5TlQxV0NiblFrMXBWb1VId0NzZExyY3VWdGN6OHU2dzgiLCJuYW1lIjoiVGVuYW50IE1vbmtleSBBY2NvdW50Iiwibm9uY2UiOiJNeVJhbmRvbU5vbmNlIiwib2lkIjoiNDQ2MGFmODAtMWRlMi00M2E1LTliMGYtYzZhNTcwNjYxYzc4IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW5AYWxhbmpvMjAwMXYyLmNjc2N0cC5uZXQiLCJzdWIiOiJrdW4wSkR1RE85dnRnZVBmS1Z2a0xXNW1DcGQxUGc4Rm5tQVUwcnFId0tZIiwidGlkIjoiNDI2Yzc2MjktMWExMS00M2M5LWFmMWYtY2JiZGQzYWY2Y2UxIiwidXRpIjoiWUJtVDFSSmtta0d3MkVFSkVDcENBQSIsInZlciI6IjIuMCJ9.

{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "OoN6RrzRvWZIAYL8b4sEwiQvF8s"
}.{
  "aud": "769cc236-2a91-415c-9e7e-7fa795fd4827",
  "iss": "https://login.windows-ppe.net/426c7629-1a11-43c9-af1f-cbbdd3af6ce1/v2.0",
  "iat": 1581042768,
  "nbf": 1581042768,
  "exp": 1581046668,
  "aio": "ATQAy/8RAAAArm93DbsoKwuZUeLoo9FscoDQsN4Y6w8yNT1WCbnQk1pVoUHwCsdLrcuVtcz8u6w8",
  "name": "Tenant Monkey Account",
  **"nonce": "MyRandomNonce",**
  "oid": "4460af80-1de2-43a5-9b0f-c6a570661c78",
  "preferred_username": "admin@alanjo2001v2.ccsctp.net",
  "sub": "kun0JDuDO9vtgePfKVvkLW5mCpd1Pg8FnmAU0rqHwKY",
  "tid": "426c7629-1a11-43c9-af1f-cbbdd3af6ce1",
  "uti": "YBmT1RJkmkGw2EEJECpCAA",
  "ver": "2.0"
}.[Signature]

**Comment by henrik-me** [comment]
We can and should validate the nonce. 

Aside: Python does this:
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/933f94dd3cf352fde13f753d1bcb46060756097a/msal/oauth2cli/oidc.py#L58

@rayluo @SomkaPe : thoughts?

@jmprieur  Extra query parameters are send both to the authorize end-point and the token endpoint afair.

**Comment by Alan-Jowett** [comment]
@henrik-me I am not sure what you mean by having MSAL validate the nonce? Our tentative plan calls for having the client generate a nonce as a SHA256 of the TLS master key (https://tools.ietf.org/html/rfc5246#section-8.1) which is a somewhat stable secret that remains the same across TLS reconnects, but is not spoof-able by a MITM.

Flow would be something like this:
1. Client connects to server over TLS.
2. Server sends back 401 / Bearer challenge to client.
3. Client computes nonce from TLS master key.
4. Client sends token request to STS, with "nonce=\<sha256 of TLS master key\>"
5. STS replies with token.
6. Client sends token to server.
7. Server computes nonce from TLS master key and compares it the nonce in the token.
8. Nonce matches, client is allowed to proceed.

**Comment by henrik-me** [comment]
Ack. We should allow you to specify the nonce and do nonce validation.

**Comment by Alan-Jowett** [comment]
Thanks for the link, I appreciate it. POP tokens are are great for providing application layer security outside of the TLS channel (it appears as if they can protect an HTTP request rather than just the TLS channel).

POP tokens would be prohibitively expensive when used to protect web-sockets or similar streaming protocols as each segment would need to be signed. 

Our goal here is closer to traditional TLS/DTLS channel binding.

**Comment by rayluo** [comment]
* Unlike an access token which will always be sent to a server and then be validated there, an Id Token is usually consumed immediately by the client that requested it (in order to render a UI etc.). In that sense, when/if MSAL (which runs on client-side) already helps to obtain an Id Token, MSAL can and likely should provide support for validating the nonce. @Alan-Jowett your [step 6, 7 & 8 in this message](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1612#issuecomment-583558963) seems like a different pattern, though.
* The OIDC specs only defines nonce for AuthCode/Implicit/Hybrid flow. That's why @Alan-Jowett [did not observe a nonce when using Device Flow](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1612#issuecomment-583558963). In other words, if your end-to-end solution would potentially use Device Flow (or Username Password flow, for that matter), you won't have a `nonce` to depend on.

**Comment by jmprieur** [comment]
Closing as this was answered
