### ISSUE TITLE
Minimum Android version

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#1619]
What will be the minimum Android  version required for MSAL.net when broker support is released ?

**Comment by bgavrilMS** [comment]
I am not aware of a minimum version requirement. MSAL communicates with the broker and with AccountManager, both of which are pretty standard and old. @trwalke - are you aware of a version limitation?

**Comment by trwalke** [comment]
@harmjonker This will depend more on the Android broker that you use. The company portal broker required android 5 or higher. Microsoft authenticator requires android 4.4 or higher. So long as you meet these requirements MSAL should be able to authenticate with the broker

**Comment by trwalke** [comment]
@harmjonker Also, you need to ensure that you have installed either Intune Company Portal (Version 5.0.4689.0 or greater) or Microsoft Authenticator (6.2001.0140 or greater) to work with MSAL broker when released in 4.9
