### ISSUE TITLE
[Enhancement] iOS broker logic should verify redirect URI and provide good error message

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1620]
**Which Version of MSAL are you using ?**
4.7.1

**Platform**
xamarin.ios

**What authentication flow has the issue?**
interactive  + broker 

**Repro**
According to the MSAL.ObjC [docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/redirect-uris-ios): 

`MSAL will verify if your redirect URI registers correctly, and return an error if it's not.`

**Actual**: MSAL.NET does not perform such a verification. If redirect URI is not set correctly, broker simply remains on screen and developers do not understand what needs to be done.

Note: I think that you can check at runtime the URL scheme configured in Info.plist and cross reference it to the RedirectUri.

**Comment by neha-bhargava** [comment]
Fixed in [MSAL 4.17.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.17.0)
