### ISSUE TITLE
[Bug] Android Broker fails when redirect uri contains /

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1622]
**Which Version of MSAL are you using ?**
4.9.0-preview (not yet released)

**Platform**
android

**Impact**: about 40% of developers would encounter this (there are 64 chars in base64, one of which is /, and about 28 chars in that signature. So there's a 28/64 = ~0.4 chance of this occurring). 

**Repro**

1. Configure Android broker 
2. When calculating the apk signature, ensure it contains a / character. Contact me for a keystore file that contains this if needed, although bug is easily fixed without

**Expected behavior**
Broker to work

**Actual behavior**
Broker fails with "invalid redirect uri" error

**Possible Solution**
Bug is in the parsing logic [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/bb65754a757e1a25a9793f2004f323ba0e438405/src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs#L358), which does not take into account that the path might contain /

**Comment by jennyf19** [comment]
[PR](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1625)

**Comment by trwalke** [comment]
released in 4.9.0
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.9.0
