### ISSUE TITLE
[Bug] Xamarin iOS Broker -> System.Security.Cryptography.CryptographicException: Bad PKCS7 padding. Invalid length 0

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1628]
**Which Version of MSAL are you using ?**
4.7.1

**Platform**

xamarin iOS + Broker

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
In `BrokerKeyHelper`, if the [NSData key is null](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Platforms/iOS/BrokerKeyHelper.cs#L30), we try to add the record created earlier, but the two keys (Service and Account) are the same, so a DuplicateItem error is throw. If we try to do `SecStatusCode.Update(record, secRecord)`, there is a new error because secRecord has a few field -> ValueData, so it's best to just delete the original record and add the new one. I was able to repro this by setting the key to null.

Then, later, a `System.Security.Cryptography.CryptographicException: Bad PKCS7 padding. Invalid length 0.` error is thrown

**Comment by IlyaSemenchenko** [comment]
Hi @jennyf19 we got the same error on our test device with MSAL 4.9.0 version.
Are you going to complete PR and fix the issue?
Thanks

**Comment by jennyf19** [comment]
@IlyaSemenchenko can you send me an email? we are unable to repro this and will send you a private build to try. thanks. (jeferrie@microsoft.com)

**Comment by IlyaSemenchenko** [comment]
Hi @jennyf19 , as you already have a fix for the issue, when could we expect new version with the fix?

**Comment by jennyf19** [comment]
Fix is out today in [4.11 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.11.0)
