### ISSUE TITLE
[Documentation] No scopes in access token when using AcquireTokenForClient

### ISSUE THREAD

**Issue by jt000** [AzureAD/microsoft-authentication-library-for-dotnet#1630]
### Documentation Related To Component:
`ConfidentialClientApplicationBuilder AcquireTokenForClient(string[] scopes)`
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
When using AcquireTokenForClient with ClientSecret the JWT that is returned in the access token does not have any "scp" claims defined. All the documentation I've seen says that it should have the scope defined in "authorized client application" scopes when using "/.default" as is the case when using AcquireTokenOnBehalfOf or AcquireTokenInteractive.

For example, take the following code:
```
var app = ConfidentialClientApplicationBuilder.Create(ClientId)
    .WithTenantId(Tenant)
    .WithClientSecret(ClientSecret)
    .Build();
var token = await app.AcquireTokenForClient(Scopes).ExecuteAsync();
```
The `token.AccessToken` when converted from base64 in jwt.io appears like the following:
![image](https://user-images.githubusercontent.com/8368448/74385000-7f1eb580-4dc0-11ea-8e98-01db89113eaa.png)

Should the jwt contain the `scp` claim? If not, then could the documentation be updated to confirm this?

**Comment by jmprieur** [comment]
you are right @jt000 when you are using the client credentials flow, the token does not contain scopes (which are for user delegated permissions), but contains app `roles`.
See [Protected web API: Verify scopes and app roles](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-verification-scope-app-roles) and in particular [Verify app roles in APIs called by daemon apps](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-verification-scope-app-roles#verify-app-roles-in-apis-called-by-daemon-apps).

See also how to register these app roles in the Web API [Exposing application permissions (app roles)](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-registration#if-your-web-api-is-called-by-a-daemon-app)
