### ISSUE TITLE
[Bug] Can't consent to admin permissions when authority is set to AzureAdAndPersonalMicrosoftAccount

### ISSUE THREAD

**Issue by peombwa** [AzureAD/microsoft-authentication-library-for-dotnet#1631]
**Which Version of MSAL are you using ?**
4.8.1

**Platform**
Windows + PowerShell

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [x] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Repro**

```csharp
string ClientId = "{CLIENT-ID}";
// Scopes that require admin consent.
List<string> Scopes = new List<string> { "AuditLog.Read.All", "GroupMember.Read.All" };
IPublicClientApplication pca = PublicClientApplicationBuilder
		  .Create(ClientId)
		  // Setting authority audiance to AadAuthorityAudience.AzureAdMultipleOrgs works correctly.
		  .WithAuthority(AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount)
		  .WithDefaultRedirectUri()
		  .Build();

var tenatId = pca.AppConfig.TenantId;

var accounts = await pca.GetAccountsAsync();

AuthenticationResult authResult = null;
try
{
	authResult = await pca.AcquireTokenSilent(Scopes, accounts.FirstOrDefault())
		.ExecuteAsync();
}
catch (MsalUiRequiredException ex)
{
	authResult = await pca.AcquireTokenWithDeviceCode(Scopes,
			deviceCodeResult =>
			{
				Console.WriteLine(deviceCodeResult.Message);
				return Task.FromResult(0);
			}).ExecuteAsync();

	Console.WriteLine(authResult.Account.Username);
}
```

**Expected behavior**
Since Device Code Flow now [supports Microsoft personal accounts](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow#device-code-flow-with-microsoft-personal-accounts) as of MSAL.NET 4.5, setting AAD authority audience to `AzureAdAndPersonalMicrosoftAccount` should allow me to consent to permissions that require admin consent when I'm signed in as an admin of a tenant.

**Actual behavior**
`MsalServiceException AADSTS70011` is thrown: The provided value for the input parameter 'scope' is not valid. The scope 'AuditLog.Read.All GroupMember.Read.All offline_access profile openid' does not exist.

**Possible Solution**
Only fail when a user account e.g. MSA can't consent to admin permissions and not based on the authority set on a client app.

**Additional context/ Logs / Screenshots**
Interestingly, setting authority to `AzureAdMultipleOrgs` allows me to consent to permissions as an admin, but that means users with MSA accounts won't be able to use the app.

**Comment by jmprieur** [comment]
@peombwa 
In organizations, there are tenant admins who can allow users or apps to access all the resources of a given type in the tenant (for instance all the AuditLogs). For personal accounts, it would not make sense that an hotmail account have access to the audit logs of all MSA accounts. 

You pointed to the fact that there are scopes which don't make sense for consumers (there are also scopes which only make sense for consumers, BTW)

Now you might think of an MSA account which is a guest in a tenant. However in that case, the tenant ID or domain must be specified. Guest scenarios only work in single tenant applications.

**Comment by peombwa** [comment]
@jmprieur Thanks for the answer! Asking users to specify a tenant ID or domain works for our scenario.

I'll mark this as closed.

**Comment by darrelmiller** [comment]
@jmprieur  With MSAL 4.4, organizational admin users of the Graph PowerShell modules were able to consent to scopes such as  AuditLog.Read.All without explicitly specifying the tenant.   They cannot do that any more since we updated MSAL.NET.  The changes in MSAL 4.5+ are breaking to existing users of MSAL.NET for the device code flow scenario where the apps are using the common authority.  This works fine with interactive flow.  I don't see why it shouldn't also work for device code flow.

**Comment by jmprieur** [comment]
@darrelmiller : are you saying that MSAL 4.4 still work but MSAL 4.5 does not in this scenario? 
@bgavrilMS @trwalke @henrik-me

**Comment by darrelmiller** [comment]
Yes.  This code fails before giving a code with MSAL.NET higher than 4.4. and succeeds with 4.4

```

            var app = PublicClientApplicationBuilder.Create("<clientIdWithMultipleOrgsAndMSA")
                    .Build();

            var result = app.AcquireTokenWithDeviceCode(new string[] { "AuditLog.Read.All" }, async r => {
                Console.WriteLine("Device code:" +  r.UserCode);
            }).ExecuteAsync().Result;
            Console.WriteLine(result.AccessToken);
```
