### ISSUE TITLE
[Feature Request] Update mobile test apps to provide a better user experience when debugging

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1635]
**Is your feature request related to a problem? Please describe.**
We need to update our mobile test apps to provide a visual indicator of any error so that it is easier for us to diagnose bugs. 

**Describe the solution you'd like**
Pop up a dialog box with any exceptions caught and their stack trace.
Update the log page to include exceptions and stack traces as well.

**Comment by bgavrilMS** [comment]
You can use 

`await DisplayAlert ("Alert", "You have been alerted", "OK");`

to get a popup - would this work? It needs to be on the main thread. 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups
