### ISSUE TITLE
[Bug] Facing error while trying to use OBO authentication flow for native / console application

### ISSUE THREAD

**Issue by 3xpl01tc0d3r** [AzureAD/microsoft-authentication-library-for-dotnet#1636]
Hi,

I am trying to develop a console application which can send an read messages from Teams on behalf of a User.
Currently it is required to use Username & Password based authentication flow for accessing the Graph API to send and read messages from Teams. 
I want to avoid Username password based authentication flow if possible and leverage OBO based authentication flow using ClientSecret.

Below is the code snippet which I am trying to use to leverage OBO based authentication flow.
 
```
IConfidentialClientApplication app;
app = ConfidentialClientApplicationBuilder.Create("clietid").WithClientSecret("clientsecret").Build();

string[] scopes = new string[] { "https://graph.microsoft.com/.default" };

AuthenticationResult result = null;
result = await app.AcquireTokenForClient(scopes).ExecuteAsync();
Console.WriteLine("Token acquired");

UserAssertion ua = new UserAssertion(result.AccessToken);
AuthenticationResult result1;
result1 = await app.AcquireTokenOnBehalfOf(scopes, ua).ExecuteAsync();
```

I am getting the below error while using the above code snippet

```
Microsoft.Identity.Client.MsalUiRequiredException: 'AADSTS50013: Assertion failed signature validation. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: '1E50B4475DAC931359D564309A3385FFAB7FB431', Found key 'Start=12/26/2019 00:00:00, End=12/25/2024 00:00:00']
Trace ID: 99f5767a-032c-444e-9b54-5094ae202501
Correlation ID: 1b8cd4fa-68a0-4065-8fe7-86658cbd2a34
Timestamp: 2020-02-12 17:58:49Z'
```

Please help / suggest how can I fix this issue.
Is there some sample console application which uses OBO authentication flow which leverages ClientSecret for authentication ?

**Comment by jmprieur** [comment]
@3xpl01tc0d3r 

````CSharp
result = await app.AcquireTokenForClient(scopes).ExecuteAsync();
```
is using Client credentials (daemon app, requesting tokens for itself, not on behalf of a user), and therefore the token `result.AccessToken` is an app token, not a user token

then in

```CSharp
UserAssertion ua = new UserAssertion(result.AccessToken);
```

you are trying to build a user assertion from an app token, which does not make sense since there is no user.

If you want to use OBO, you need to have a user. 

The way to acquire tokens for a user in console apps is described in

https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet

**Comment by 3xpl01tc0d3r** [comment]
Hi,

When calling `var accounts = await app.GetAccountsAsync();` I get 0 as count value means I am not able to fetch any account info. 
Is it possible to get the account details with ClientSecret or it is mandatory to get the token Interactively ? If yes is there a way to avoid interactive login and login with username & password authentication flow.

Below is the code snippet 

```
IConfidentialClientApplication app;
app = ConfidentialClientApplicationBuilder.Create("clietid").WithClientSecret("clientsecret").Build();

string[] scopes = new string[] { "https://graph.microsoft.com/.default" };

AuthenticationResult result = null;
var accounts = await app.GetAccountsAsync();
IAccount account = accounts.FirstOrDefault();
result = await app.AcquireTokenSilent(scopes,account)
```

I am getting the below error while using the above code snippet

`Microsoft.Identity.Client.MsalUiRequiredException: 'No account or login hint was passed to the AcquireTokenSilent call.'`

**Comment by jmprieur** [comment]
This is expected; client credentials (AcquireTokenForApp) gets tokens for the app, not the user, and therefore there are no user accounts

**Comment by jmprieur** [comment]
Closing as this was answered
