### ISSUE TITLE
[Bug] Token not being passed to GraphServiceClient

### ISSUE THREAD

**Issue by isaacrlevin** [AzureAD/microsoft-authentication-library-for-dotnet#1640]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
4.8.2

**Platform**
net472 WPF

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
This is a new app or experiment

**Repro**

```csharp
// Provider I created to get interactive token
        public async Task AuthenticateRequestAsync(HttpRequestMessage request)
        {
            AuthenticationResult authResult = null;
            var accounts = await _application.GetAccountsAsync();
            var firstAccount = accounts.FirstOrDefault();

            try
            {
                authResult = await _application.AcquireTokenSilent(_scopes, accounts.FirstOrDefault())
                .ExecuteAsync();
            }
            catch (MsalUiRequiredException ex)
            {
                    authResult = await _application.AcquireTokenInteractive(_scopes)
                       .WithParentActivityOrWindow(new WindowInteropHelper(Application.Current.MainWindow).Handle)
                       .ExecuteAsync();               
            }
            if (authResult != null)
            {
                request.Headers.Authorization = new AuthenticationHeaderValue("bearer", _authToken);
            }
        }
}

// code that calls the Presence Graph API
var graphResult = await _graphServiceClient.Me.Presence.Request().GetAsync();
```

**Expected behavior**
I would expect the token obtained by the provider to be attached to any GraphServiceClient call and I get presence status

**Actual behavior**
 I get a 401 when calling the Presence API because there is no token in the header

**Possible Solution**
I can call the Presence Api via a Token added HttpClient (samples do this) but the fact I am able to do my preferred approach with other providers (DeviceCodeFlow for instance) makes me think this should be supported behavior

**Additional context/ Logs / Screenshots**
Here is a repo with code that has a working DeviceCodeFlow working as expected
https://github.com/isaacrlevin/PresenceLight/blob/master/src/PresenceLight.Core/Graph/DeviceCodeFlowAuthorizationProvider.cs

**Comment by bgavrilMS** [comment]
That's a lot of code @isaacrlevin - maybe you can norrow down the repro ? MSAL is only invoked in `AuthenticateRequestAsync`. Can you remove the exception handling around `AcquireTokenInteractive` and report back on the exceptions?

**Comment by isaacrlevin** [comment]
Issue related to Graph SDK, moving big over there
