### ISSUE TITLE
[Investigate] Determine if disabling certificate revocation list checking is bad practice in the Android Broker scenarios

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1642]
Investigate weather or not there will be an potential security issue if we enable broker support on MSAL.NET with the broker signature verification not checking against certificate revocation lists. 

We have a new build warning in MSAL with the new android broker implementation:
`Warning IA5352: Do Not Change X509ChainPolicy. RevocationMode to NoCheck`

Coming from [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/8c76874be3cc2a6280199d9889c2486413f81f5f/src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs#L425)

Should speak with the MSAL android team to determine how they handle certificate revocation.

**Comment by bgavrilMS** [comment]
Could you then please disable the warning in the code? You have to use a pragma (#) and provide a reason.

**Comment by trwalke** [comment]
Resolved in [4.11.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.11.0)
