### ISSUE TITLE
Working with React Native

### ISSUE THREAD

**Issue by michaelfsarkis** [AzureAD/microsoft-authentication-library-for-dotnet#1644]
Can I use the package with React Native? if yes, is there any sample code to use? 

Thanks

**Comment by bgavrilMS** [comment]
This package is a .NET package and published to NuGet. I don't think you can invoke .net code from React Native (happy to be proven wrong). 

Have you looked at the MSAL for javascript ? https://github.com/AzureAD/microsoft-authentication-library-for-js
