### ISSUE TITLE
[Documentation] bug in code samples for creating token using certificate?

### ISSUE THREAD

**Issue by ali-hamud** [AzureAD/microsoft-authentication-library-for-dotnet#1650]
### Documentation Related To Component:
Not sure.

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows#code-snippet

current sample:
X509Certificate2 certificate = ReadCertificate(config.CertificateName);
var app = ConfidentialClientApplicationBuilder.Create(config.ClientId)
           .WithAuthority(AzureCloudInstance.AzurePublic, "{tenantID}")
           .WithCertificate(config.ClientSecret)
           .Build();

Bug:
certificate is not in use. should we pass it to .WithCertificate() method?

**Comment by bgavrilMS** [comment]
Fixed the docs. Yes, you need to pass the certificate there. `WithCertificate` needs an X509Certificate2 parameter anyway, so you can't accidentally pass in a secret.

**Comment by bgavrilMS** [comment]
Thanks for reporting!
