### ISSUE TITLE
[Bug] MSAL does not pass in claims to the brokers

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1651]
**Version**
4.8.2

**Platform**
Android, iOS

Neither iOS nor Android brokers are being given user configured claims, although brokers support claims.
iOSBroker has [some logic related to claims](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/7a7b5a1c6d3769740a10afb83184a2c91befc324/src/client/Microsoft.Identity.Client/Platforms/iOS/iOSBroker.cs#L111), but the E2E does not work. 
Android broker has no logic related to claims.

**Comment by jmprieur** [comment]
@trwalke @aiwangmicrosoft : what is the severity of this bug?
cc: @bgavrilMS

**Comment by trwalke** [comment]
@jmprieur This will be a big issue for anyone who needs to pass claims to the broker so i think this is moderatly high severity. P2 seems appropriate. this will be shipping in the next release
