### ISSUE TITLE
[Documentation][Update] Remove wiki docs referencing MSAL v2...leads to confusion.

### ISSUE THREAD

**Issue by dansiegel** [AzureAD/microsoft-authentication-library-for-dotnet#1657]
### Documentation Related To Component:

AAD B2C Specifics

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example
- [x] out of date

### Description Of The Issue

The current documentation in the WIKI for the AAD B2C Specifics currently documents the older way to configure the PublicClientApplication. This should be updated to show the newer builder pattern.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-Specifics-MSAL-2.x#instantiating-the-application

**Comment by jennyf19** [comment]
Thanks @dansiegel

**Comment by jmprieur** [comment]
Actually this is a MSAL 2x specific page
the MSAL 3.X and above is https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics

**Comment by jennyf19** [comment]
@jmprieur yes, but we should remove v2. i don't think we need those anymore. what do you think?

**Comment by jennyf19** [comment]
@jmprieur yes, but we should remove v2. i don't think we need those anymore. what do you think?

**Comment by dansiegel** [comment]
you are right... didn't even notice that it was a v2 specific page... I do think @jennyf19's idea is probably the right way to go... having documentation laying around for v2 and v3+ gets too confusing and will lead people to the wrong docs.

**Comment by jmprieur** [comment]
@jennyf19 : yes. the question is what page pointed to v2.0 ?

**Comment by jennyf19** [comment]
@dansiegel how did you find the v2.0 page? was it linked from somewhere else?

**Comment by dansiegel** [comment]
that's a great question... I'm not quite sure exactly what brought me there... I have a lot of open tabs... it was probably a combination of Google + whatever the Wiki naturally shows
