### ISSUE TITLE
[Documentation] Custom token cache in MSAL v3

### ISSUE THREAD

**Issue by drzdbd1** [AzureAD/microsoft-authentication-library-for-dotnet#1658]
### Documentation Related To Component:

TokenCache
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x ] needs example

### Description Of The Issue

I'm using ConfidentialClientApplicationBuilder to build ConfidentialClientApplication for my daemon app, is there a way I can provide a custom TokenCache impelmentation?

Reason I'm asking is it seems like the default TokenCache class uses a SemaphoreSlim(1,1) to lock so  parallelism is very bad, I would like to have a multi reader single writer semaphore for my app. Thanks!

**Comment by jmprieur** [comment]
@drzdbd1 : I advise you have a look at the following token cache providers for confidential clients: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web/TokenCacheProviders

See also https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web#token-cache-serialization

**Comment by drzdbd1** [comment]
@jmprieur Thanks for the reply. 

However, I think these hooks are used for custom token serialization, not the TokenCache implementation itself. I think internally the concurrent requests would still be constrained by SemaphoreSlim(1,1) - only one thread is allowed to read the token at a time, I wonder why it was designed this way and how it would scale?

**Comment by jmprieur** [comment]
We have have token cache implementations for:
- public client applications: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Cross-platform-Token-Cache
- confidential client applications: https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization

**Comment by jmprieur** [comment]
Closing as this was answered
