### ISSUE TITLE
AquireTokenSilentAsync always fails on UWP

### ISSUE THREAD

**Issue by jherby2k** [AzureAD/microsoft-authentication-library-for-dotnet#166]
Following your Xamarin.Forms example, the UWP solution always fails to aquire a token silently. Droid and iOS work fine (well, iOS simulator doesn't, but there is an issue logged for that already). UWP fails every time though both on a Windows phone 10 simulator, and on a Windows 10 desktop. Not sure about Windows Phone hardware since I don't have a WP10 device, so tested platforms are all x86.

**Comment by kpanwar** [comment]
can you share the logs?

**Comment by k-viktor-p** [comment]
This is reproduced with the version of the package Microsoft.NETCore.UniversalWindowsPlatform higher than 5.1.0. If you need more details, write.

**Comment by kpanwar** [comment]
We have moved to new project structure model that will eliminate several of these issues and offer a true .NetCore support.
