### ISSUE TITLE
[Bug] Brokers and webviews should be consistent when user cancels authentication

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1663]
**Which Version of MSAL are you using ?**
4.9

**Platform**
android, ios

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Expected behavior**
When MSAL does not use the broker, it uses a WebUI. If the user hits cancel, then MSAL generates an `MsalClientException` with error code `authentication_cancelled`
Brokers should do the same.

**Actual behavior**
Brokers behave differently - they will throw an `MsalServiceException` with different error codes (iOS with whatever code comes from the broker, Android hardcodes a single code). 

It looks like on Android this does nothing https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1661

**Comment by bgavrilMS** [comment]
Fixed by @trwalke with https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1666

**Comment by trwalke** [comment]
released in 4.9.0
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.9.0
