### ISSUE TITLE
[Bug] WithBroker and WithUseEmbeddedWebView should be mutually exclusive

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1664]
**Which Version of MSAL are you using ?**
4.9

**Platform**
android, ios

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

```csharp
var app = PublicClientApplicationBuilder.Create(msalClientId)
                .WithBroker()
                .Build();

var authResult = await app
                        .AcquireTokenInteractive(GetADScopes())
                        .WithParentActivityOrWindow(parentActivity)
                        .WithUseEmbeddedWebView(true)
                        .ExecuteAsync();
```

**Comment by jmprieur** [comment]
Why did you close it @bgavrilMS ? you might want to add an explanation?

**Comment by bgavrilMS** [comment]
Yes, sorry, I should have provided an explanation here. 

One of the flows behind InteractiveRequest with broker is: 

1. If WithBroker is set to true
2.  Attempt to invoke the broker and get the token
3.  If this fails, e.g. if broker is not installed, the use a web view 

So it actually does make sense for the user to specify both of these.
