### ISSUE TITLE
[Bug] WithUseEmbeddedWebView and Android - activity title is always 'Sign in'

### ISSUE THREAD

**Issue by steffos** [AzureAD/microsoft-authentication-library-for-dotnet#1665]
MSAL.NET 4.8.2

Android

When using .WithUseEmbeddedWebView(true) and Android, activity title is always 'Sign in' regardless if I'm opening the window with purpose to perform another policy such as 'Reset password'

![image](https://user-images.githubusercontent.com/1426950/75362634-55ce5100-58b9-11ea-8d35-7f92bc78703d.png)

**Repro**
Use .WithUseEmbeddedWebView(true) on an Android project and perform a 'Reset password' policy.

Activity title in upper left corner is always 'Sign in' regardless of what policy I use. 

Seems like it's hard coded: 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/b929e1fc87c4273e73a91701a7984a194e0d4d45/src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/AuthenticationAgentActivity.cs#L17

**Possible Solution**
Being able to submit a custom activity title when opening with WithUseEmbeddedWebView on Android.

**Comment by jennyf19** [comment]
this was fixed in 4.18. Please update to the latest version of MSAL.
