### ISSUE TITLE
How to add PIN-based authorization?

### ISSUE THREAD

**Issue by gonzobrains** [AzureAD/microsoft-authentication-library-for-dotnet#1667]
Hi,

I am writing a Xamarin mobile app.  I have gone through the sample that connects to the Graph API via AcquireTokenInteractive().  What I'd like to do at this point is provide a way to authenticate using a PIN instead of AD username/password.  How can I accomplish this?

Thanks,
Jeff

**Comment by jmprieur** [comment]
@gonzobrains : this is not something that you'll control from the library, but that the tenant administrator will control using conditional access policies (for your app, or users, or platforms).

See https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview

**Comment by gonzobrains** [comment]
Thank you for your rapid response.  I figured this was the case; I just don't know where to go to figure out how to implement this on the backend as I don't know if that is something already implemented by Azure/OAuth2/etc.

I think the idea would be to initially have the user authenticate with AD username/password but add PIN-based as an extra layer of security while the token is still valid (hence the reason I thought this may be done on the mobile app side).

**Comment by jmprieur** [comment]
@gonzobrains : in the Azure AD world this is entierely driven by Azure AD (and therefore by policies). The client only displays the HTML page sent by Azure AD.

**Comment by jmprieur** [comment]
Closing as this was answered
