### ISSUE TITLE
Support for Azure Mobile apps and B2C via MSAL

### ISSUE THREAD

**Issue by nhwilly** [AzureAD/microsoft-authentication-library-for-dotnet#167]
Working with others in the Azure Mobile Apps space, I've learned that apparently it's not possible to use ADAL with B2C and it's not possible to use MSAL with B2C and Azure Mobile Apps.

So we have to use the server authentication flow in this instance.  That's now what I wanted, but acceptable, except...

If I have a site running MVC with an `<authentication>` entry in the web config, any call to a protected resource which should result in a 401 to the native client, instead redirects via 302 to the B2C login page, which then returns a 200 to the native client.  That just ain't right.  The AJAX people have been fighting this for ages.

So the best answer is a native SDK that will allow me do client things on the client.  MSAL, right?

Only MSAL won't work with B2C and Azure Mobile Apps.

Can anyone comment on this, correct me (please, correct me) or talk about timelines for when this might work?

And yes, I'm using Xamarin Forms.

Thanks...

**Comment by jherby2k** [comment]
I'm using MSAL with B2C and an Azure Mobile App (Xamarin.Forms). Took a bit of digging to figure out the syntax... here's my signin method:

        internal async Task<string> SignInAsync()
        {
            try
            {
                AuthenticationResult authResult;
                try
                {
                    // If silent authentication failed, prompt for credentials
                    authResult = await _authenticationClient.AcquireTokenAsync(
                        new[] { _clientId },
                        string.Empty,
                        UiOptions.ForceLogin,
                        string.Empty,
                        null,
                        _authority,
                        _signUpSignInPolicy);
                }
                catch (MsalException e)
                {
                    // If the user clicked "Forgot your password?"
                    if (e.Message.Contains("AADB2C90118"))
                    {
                        authResult = await _authenticationClient.AcquireTokenAsync(
                            new[] { _clientId },
                            string.Empty,
                            UiOptions.SelectAccount,
                            string.Empty,
                            null,
                            _authority,
                            _passwordResetPolicy);
                    }
                    else
                        throw;
                }

                var result = await CompleteSignIn(authResult);

                return result;
            }
            catch (MsalException)
            {
                //Allow cancelation / the back button
                return null;
            }
        }

        async Task<string> CompleteSignIn(AuthenticationResult result)
        {
            await _mobileServiceClient.LoginAsync(
                MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory,
                new JObject { ["access_token"] = result.Token });

            ClaimsResult = new JwtParser(result.Token).Claims;
            OnAuthenticationChanged();

            return _mobileServiceClient.CurrentUser.MobileServiceAuthenticationToken;
        }

**Comment by nhwilly** [comment]
Thanks, that looks interesting.   Does the back end verify the access token properly?  I thought that was the problem with this approach.  I'll run this past the guy who wrote a book on ZUMO and see if this makes sense to him.  He mentioned checking with other folks at MS and they concluded it wasn't ready yet because there were differences in the authentication flow between B2C and ZUMO.

**Comment by jherby2k** [comment]
It accepts the authentication just fine, yeah. Works great. No idea if its validating it properly, but if its not that is a serious security issue with ZUMO right?

There is a sample somewhere of this, I believe on a MS site. I had no idea it wasn't supported, if that is indeed the case.

**Comment by nhwilly** [comment]
Well, here's what I was told:

https://github.com/adrianhall/develop-mobile-apps-with-csharp-and-azure/issues/30

And I believe if you want to validate it manually, you have to have the private key.  You can get the public key from an endpoint.

That's when I quit looking.

If you call an app service endpoint that's marked with the `Authorize`  attribute, you should find out pretty quickly if the JWT is authenticated or not.  I've been watching the streaming logs (set to `verbose`) from the app service and it tells me when the JWT passes or fails.  You could look at that.

**Comment by kpanwar** [comment]
Access tokens are meant for the resource. Client application should not be looking into or validating the token. It is the resource/backend's responsibility to validate the tokens.

**Comment by nhwilly** [comment]
@kpanwar Sorry I wasn't clear.  Token validation has to take place on the back end.  Otherwise secrets are in the wild.

When Adrian Hall mentioned that the MS team said MSAL wouldn't work, I just quit investigating.  Even though examples exist for Xamarin forms (client side only) and Vittorio says it works.

When I get something to work that the development teams tells me won't work (or is the subject of debate on that same team), I get worried that it might stop working at any moment and without notice.

I'm old and have the programming scars to prove it.  :)
