### ISSUE TITLE
Add support for authentication with FIDO2.0 security keys  

### ISSUE THREAD

**Issue by libbro2006** [AzureAD/microsoft-authentication-library-for-dotnet#1670]
One of the top requests for passwordless with FIDO2 auth is for admins to be able to log into Powershell with their security keys. 

Much like any other web-authentication flow, if the user has a FIDO2 credential and is on a PC running Windows 1903 or higher, a user should be able to "Sign in with a security key" and login via WebAuthN to their Microsoft account. 

Please reach out to me via internal resources for more details/questions. 

![Powershell Auth dialog](https://user-images.githubusercontent.com/40281215/75597906-f99c3600-5a4c-11ea-8491-cc2f88eb0071.png)

**Comment by jmprieur** [comment]
@libbro2006 : why did you remove the scenario in the template? 
I'm assuming this is a desktop application?
Is it using the embedded web view or the system browser?

**Comment by bgavrilMS** [comment]
This should work with system browser but not with embedded browser until we implement https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues?q=is%3Aissue+is%3Aopen+edge

**Comment by jmprieur** [comment]
Closing as duplicate of #1339
