### ISSUE TITLE
[Bug] Issue with on behalf of flow via MS ADFS 2019

### ISSUE THREAD

**Issue by mremkiewicz** [AzureAD/microsoft-authentication-library-for-dotnet#1678]
Not sure if this is a bug or configuration issue.

**Which Version of MSAL are you using ?**
MSAL 4.8.2

**Platform**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [X ] OBO

Other? - please describe;

**Is this a new or existing app?**
This is a new app to understand and document the pattern in our environment.

**Repro**
I have a Web Api (.Net 4.5) calling a Web Api (.Net 4.5). I'm getting the following exception when executing the following:

 AuthenticationResult result = await app.AcquireTokenOnBehalfOf(scopes, userAssertion)
                .ExecuteAsync().ConfigureAwait(false);

Here is the full function:
```csharp
            var authContext = ConfidentialClientApplicationBuilder.Create(mServiceCredentialOptions.ClientId)
                .WithAdfsAuthority(mAuthorityOptions.Authority)
                .WithClientSecret(mServiceCredentialOptions.ClientSecret)
                .Build();

            var bootstrapContext = (string)principal.Identities.First().BootstrapContext;
            var userAssertion = new UserAssertion(bootstrapContext, "urn:ietf:params:oauth:grant-type:jwt-bearer");
            AuthenticationResult result = await app.AcquireTokenOnBehalfOf(scopes, userAssertion)
                .ExecuteAsync().ConfigureAwait(false);

```

**Expected behavior**
I'm expecting an access token for the endpoint that I'm calling.

**Actual behavior**
Full exception:

"ExceptionMessage": "MSIS9601: The 'resource' parameter is missing in the request. Send the 'resource' parameter that contains the resource identifier's value.",
    "ExceptionType": "Microsoft.Identity.Client.MsalServiceException"

**Additional context/ Logs / Screenshots**
I'm finding this entry in ADFS eventlog:

Encountered error during OAuth token request. 

Additional Data 

Exception details: 
Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthAuthorizationMissingResourceException: MSIS9226: Received invalid OAuth request. The 'resource' parameter is missing or found empty. The 'resource' parameter must be provided specifying the relying party identifier for which the access is requested.
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthOnBehalfOfContextBase.ValidateCore()

The scopes passed into the function is:
@"urn:Enterprise:PolicyInformation//openid",  @"urn:Enterprise:PolicyInformation//user_impersonation"

I have tried some many combinations (single forward slash, using the Client Id, etc.)

Captured the network trace and saw this:
client_id=b5342232-4b42-4206-8cd0-5972e8420d42&client_info=1&client_secret=**Removed**&scope=offline_access+openid+profile+urn%3AEnterprise%3APolicyInformation%2Fopenid+urn%3AEnterprise%3APolicyInformation%2Fuser_impersonation&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=**Removed**

Noticed that the scope included additional scopes that I didn't ask for.  Is this correct?

**Comment by bgavrilMS** [comment]
What version of ADFS are you using? 

It is ok for MSAL to add more scopes. We always request "offline_acess", "openid" and "profile" - these are required for MSAL to work.

**Comment by mremkiewicz** [comment]
We are using AD FS on Windows Server 2019 version 1809 (OS Build 17763.1039)

**Comment by mremkiewicz** [comment]
Here are the configurations for the services in ADFS.  Policy Detail service (policydetailconfig.txt) is the calling the Enterprise Policy Information service (epiconfig.txt).

Let me know if you need anymore information.

[policydetailconfig.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/4299333/policydetailconfig.txt)
[epiconfig.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/4299335/epiconfig.txt)

**Comment by adrienbarde** [comment]
hi everyone, i have exactly the same issue with **ADFS 2016** when i use **on behalf of flow**

**Comment by bgavrilMS** [comment]
@adrienbarde - MSAL does not support ADFS 2016 (I believe it's 2016 is better known as ADFS v4). MSAL only supports ADFS 2019.
ADAL supports ADFS v2, v3 and v4.

**Comment by adrienbarde** [comment]
> @adrienbarde - MSAL does not support ADFS 2016 (I believe it's 2016 is better known as ADFS v4). MSAL only supports ADFS 2019.
> ADAL supports ADFS v2, v3 and v4.

OK thank you for your reply

**Comment by adrienbarde** [comment]
> @adrienbarde - MSAL does not support ADFS 2016 (I believe it's 2016 is better known as ADFS v4). MSAL only supports ADFS 2019.
> ADAL supports ADFS v2, v3 and v4.

finally we updated ADFS to 2019 but I still get the error "MSIS9601: The 'resource' parameter is missing in the request. Send the 'resource' parameter that contains the resource identifier's value."

**Comment by jmprieur** [comment]
Did you apply service pack KB 4490481 to Windows Server?
See details in https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-adfs-support#msal-connects-directly-to-ad-fs

**Comment by adrienbarde** [comment]
> @adrienbarde: Did you apply service pack KB 4490481 to Windows Server?
> See details in https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-adfs-support#msal-connects-directly-to-ad-fs

Yes the service pack is installed. I Tried to add WithExtraQueryParameters but i still got the error

```
app = ConfidentialClientApplicationBuilder.Create(_azureAdOptions.ClientId)
                .WithClientSecret(_azureAdOptions.ClientSecret)
                .WithAdfsAuthority(authority)
                .WithRedirectUri(currentUri)
                .WithExtraQueryParameters(new Dictionary<string, string>
                {
                    { "resource", "xxxxxx-xxxxx-xxxxxx-xxxxx" }
                })
                .Build();
```

**Comment by adrienbarde** [comment]
Here is my Fiddler trace 

![image](https://user-images.githubusercontent.com/5081583/77306965-bace6880-6cf8-11ea-95b6-96588a1fb351.png)

**Comment by mremkiewicz** [comment]
From my perspective, I didn't find the 4490481 hotfix installed.  However, I did install KB4541331, based on the Microsoft Update Catalog and how I interpret the catalog, KB4541331 supersedes 4490481 hotfix.  Correct me if I'm wrong.

With that said, I am still getting the same error:
"MSIS9601: The 'resource' parameter is missing in the request. Send the 'resource' parameter that contains the resource identifier's value."

**Comment by jmprieur** [comment]
@trwalke : do you have an idea?

**Comment by trwalke** [comment]
This looks more like a configuration issue on the ADFS side. I am not familiar entirely with the configuration of ADFS for Identity. Ill contact the folks in ADFS for more assistance.

**Comment by bgavrilMS** [comment]
Just updating the thread with details from discussions we had over email: 

- ADFS team confirms this is a known issue
- there is a workaround (details below) so most this issue will not be fixed via a servicing fix

Workaround is to replace the `scope` POST param with a `resource` POST param when contacting the /token endpoint. MSAL does have a somewhat longwinded way of doing this by allowing developers to use [their own HttpClient](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/httpclient)

**Comment by jamboharris** [comment]
I've also hit this issue -> latest MSAL & ADFS 2019 & same error message.

Can I just confirm:

- This bug isn't going to be fixed?  (or am I misunderstanding?)
- The workaround is to replace the `scope` param (AND it's data) with a `resource` param holding different data?
- I'm struggling to understand what I should send in the resource param.  I need to access the ADFS graph using on-behalf-of - any pointers gratefully received!

Thanks for any help

**Comment by mremkiewicz** [comment]
@jamboharris The workaround given to me is to downgrade to ADAL and use it instead of MSAL.  In my scenario, this worked.  Not sure when this will be fixed.

**Comment by bgavrilMS** [comment]
As far as I understand this bug has been fixed.

**Comment by ddops2468** [comment]
@bgavrilMS - Can you please share the solution with us? I can't seem to make this work in ADFS 2019 and MSAL.net (with core 3.1).  Always get error MSIS9226 from AD FS when using the on behalf of flow.

**Comment by bgavrilMS** [comment]
@ddops2468 - there was a fix in ADFS itself, which you get via an OS update. Sadly, I cannot find the email with the details / KB number. Consider opening a bug on ADFS itself for details.

The workaround that was confirmed by others is to add a missing param manually, by intercepting HTTP traffic in your app. Smth like: 


```csharp

internal class FixOBOClientHandler : HttpClientHandler
{
  protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage msg, CancellationToken ct)
  {
        var body = HttpUtility.ParseQueryString(await request.Content.ReadAsStringAsync);
        // some parsing to detect if this is OBO
        // some parsing to extract the scope
        // replace "scope" with "resource"
  }
}

```
Then inject this HTTP handler via a client factory like as per https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-provide-httpclient
