### ISSUE TITLE
Selecting different account in the broker with ADFS as identity provider

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#1679]
Do you guys also run tests like changing between accounts within the same domain, where ADFS is identity provider for Azure AD login ?
We experience some weird behavior when changing account, coming back with a previous account into MSAL acquiretokens calls.

**Comment by bgavrilMS** [comment]
Hmm, could you give us a few more details like some repro steps please? When you say accounts, do you mean that you are logging in interactively in AAD, then trying to use the IAccount object to login silently to ADFS? Or are you talking about the experience in the browser?

In the MSAL token cache, all objects (tokens and accounts) are indexed by enviroment, i.e. the host part of the authoirty URI. So for public AAD this would be "login.microsoftonline.com" and for ADFS it would be different, e.g. "myadfs.instance.com/adfs". As for the browser experience, we don't control that, but if you give us some repro steps we will log a bug to the AAD server folks.

**Comment by bgavrilMS** [comment]
Application starts with select-account screen  (as per preview release the acquiresilent call crashes we direct the acquiretoken call to the account select step)  

![Screenshot_20200305-214431_Company Portal](https://user-images.githubusercontent.com/55669455/76024828-0d073f80-5f2c-11ea-8c21-a5a72eeec7a6.jpg)
=> I choose 'Account toevoegen'  (add new account)

It then shows an ADFS screen (as least I think this is an AFDS screen) with only one of the accounts. 
![Screenshot_20200305-214441_Company Portal](https://user-images.githubusercontent.com/55669455/76024961-463faf80-5f2c-11ea-96db-8c66d69cbd2f.jpg)

I choose 'Ander account gebruiken'  (use different account) and  I then enter a new account name (truus.ea11@nslogin.nl)

![Screenshot_20200305-214522_Company Portal](https://user-images.githubusercontent.com/55669455/76025090-8010b600-5f2c-11ea-9bda-fb19616b0096.jpg)

After clicking 'Volgende' ( Next) control returns to my app with the harm.jonker@nslogin.nl account as selected account, no further login of truus.ea11@nslogin.nl

**Comment by bgavrilMS** [comment]
This seems like a broker issue. @trwalke  - have you encountered this?

**Comment by harmjonker** [comment]
I have been called by KPN, our provider of the ADFS service for NS.
He explained ADFS keeps a session with duration of one hour to prevend re-login in different applications from the desktop workstations.  This session is the reason that logging in with another account within an hour will always return the logged with that session. Somehow, this session info is also taken into account with the flows from MSAL/Authenticator.
Is this intended behavavior ?
