### ISSUE TITLE
Update to http telemetry schema v2

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1681]

**Comment by bgavrilMS** [comment]
The doc describing this is still open, with several questions on it. There are no acceptance tests either - I proposed one. IMO, this is not ready to be worked on. 

CC @jmprieur @henrik-me

**Comment by trwalke** [comment]
Resolved in [4.11.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.11.0)
