### ISSUE TITLE
[Bug] CryptographicException when using Android Broker

### ISSUE THREAD

**Issue by tipa** [AzureAD/microsoft-authentication-library-for-dotnet#1683]
**Which Version of MSAL are you using ?**
MSAL 4.9.0

**Platform**
Xamarin Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL

**Repro**

```csharp
await PublicClientApplicationBuilder.Create("...")
            .WithBroker()
            .Build()
            .GetAccountsAsync();
```

**Expected behavior**
No exception

**Actual behavior**
`System.Security.Cryptography.CryptographicException: 'MonoBtlsPkcs12.Import failed.'

**Additional context/ Logs / Screenshots**
VS 2019 16.5.0 Preview 5.0
Xamarin.Android 10.2.0.100

**Comment by trwalke** [comment]
Hello Tipa, so far I have been unable to reproduce this. Do you have any logs or a full stack trace? A repro app would be great if possible.

Thanks

**Comment by tipa** [comment]
It's kind of a weird exception. I currently cannot reproduce it with a blank app, but I can provide you the stack trace that I am getting in my app:
```
  at Mono.Btls.MonoBtlsObject.CheckError (System.Boolean ok, System.String callerName) [0x00006] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/System/Mono.Btls/MonoBtlsObject.cs:95 
  at Mono.Btls.MonoBtlsObject.CheckError (System.Int32 ret, System.String callerName) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/System/Mono.Btls/MonoBtlsObject.cs:103 
  at Mono.Btls.MonoBtlsPkcs12.Import (System.Byte[] buffer, Microsoft.Win32.SafeHandles.SafePasswordHandle password) [0x0002e] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/System/Mono.Btls/MonoBtlsPkcs12.cs:117 
  at Mono.Btls.X509CertificateImplBtls.ImportPkcs12 (System.Byte[] data, Microsoft.Win32.SafeHandles.SafePasswordHandle password) [0x0003e] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/System/Mono.Btls/X509CertificateImplBtls.cs:261 
  at Mono.Btls.X509CertificateImplBtls..ctor (System.Byte[] data, Microsoft.Win32.SafeHandles.SafePasswordHandle password, System.Security.Cryptography.X509Certificates.X509KeyStorageFlags keyStorageFlags) [0x00047] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/System/Mono.Btls/X509CertificateImplBtls.cs:103 
```

Will try to narrow down the problem tomorrow to see what actually makes the difference.

**Comment by tipa** [comment]
![image](https://user-images.githubusercontent.com/2863198/76130788-6181ec00-600c-11ea-8ab5-90b8cda28b8c.png)

**Comment by tipa** [comment]
After multiple hours of debugging I finally found out that deleting the **.vs  + obj + bin** folders resolved the issue. I have no idea why, but it fixed the issue for me in 3 separate projects. Hope this helps anyone who is experiencing the same issue.

**Comment by tipa** [comment]
You can reproduce the problem with the project attached. Make sure you have all these checkboxes set:
![image](https://user-images.githubusercontent.com/2863198/76142843-ccb1d980-6071-11ea-9af3-48131b7d7cd9.png)
[App1.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/4301768/App1.zip)

**Comment by trwalke** [comment]
Hi Timo, which version of android are you using to reproduce this? Also, is this running in a simulator or on an actual device? 

Can you also try making an acquire token interactive call right before you do the getAccountsAsync? I want to see if other broker apis will trigger the same error.

**Comment by tipa** [comment]
It happens on both emulator and physical device, deployed on Android 9 & Android 10. See my initial post for Xamarin.Android and VS19 info.

When I just keep hitting "Continue" in VS, the broker eventually shows up, I think the problem mainly (or even exclusively) happens for `GetAccountsAsync`

Are you having problems reproducing the problem? As I said, it is likely an issue that needs to be resolved by the Xamarin or Mono team as the exception happens in the constructor of `X509Certificate`, but the instance is still created.

**Comment by trwalke** [comment]
yes, I am unable to reproduce this but I want to get a few more details on what exactly is happening here. so you are saying that this doesn't happen when you do acquireTokenInteractive() without GetAccountsAsync? I would expect that it should because every call to the broker makes the same signature check which constructs the X509Certificate

**Comment by tipa** [comment]
When I just call acquireTokenInteractive() it happens as well.

**Comment by henrik-me** [comment]
@trwalke to add more details on why P2

**Comment by trwalke** [comment]
The customers that have reported this have indicated that this issue does not interfere with the functionality of the authentication scenarios, setting priority to P2

**Comment by henrik-me** [comment]
@trwalke please add more details on where this exception is thrown and what code is not executed.

**Comment by henrik-me** [comment]
@trwalke : is this a debug only scenario? if yes, please close.

**Comment by henrik-me** [comment]
@tipa ^^

**Comment by keerthinathganjam** [comment]
Were you able to fix the issue ? I Am also getting the exact same issue. Are there any fixes for the same?

**Comment by henrik-me** [comment]
@keerthinathganjam : which version of MSAL are you using? Do you have a repro?

**Comment by keerthinathganjam** [comment]
@henrik-me : I tried in multiple verions i tried with 4.16.0 and latest 4.23.0 as well. its same issue when i set .WithBroker(true), If i remove this middleware it works, How ever For setting conditioanl Access broker app has to be enabled.

public AuthService()
        {
            _pca = PublicClientApplicationBuilder.Create(ClientID)
                .WithIosKeychainSecurityGroup(AppId)
                .WithRedirectUri(RedirectUri)
                .WithAuthority("https://login.microsoftonline.com/common")
                .WithBroker(true)
                .Build();
        } 


I will upload my project to a git repo with reprodusing the issue in a while

**Comment by keerthinathganjam** [comment]
https://github.com/keerthinathganjam/MSAL-Xamarin-Sample here it the sample where issue can be reproduce.

Note you may have to update the Client Id, App Id and Hash with your client ids

string RedirectUri
        {
            get
            {
                if (DeviceInfo.Platform == DevicePlatform.Android)
                    return $"msauth://{AppId}/<<SignatureHash>>";
                else if (DeviceInfo.Platform == DevicePlatform.iOS)
                    return $"msauth.{AppId}://auth";

                return string.Empty;
            }
        }

        readonly string AppId = "io.thewissen.msalsample";
        readonly string ClientID = "<<ClientId>>";
        readonly string[] Scopes = { "User.Read" };

![image](https://user-images.githubusercontent.com/12542938/100973770-298ae380-3561-11eb-9840-af68a14c813a.png)

**Comment by keerthinathganjam** [comment]
I was follwing this blog https://www.thewissen.io/implementing-msal-authentication-in-xamarin-forms/, i have made few changes to the code from their sample like adding .WithBroker(true) and adding my Client Id, App Id and Signature Hash

**Comment by keerthinathganjam** [comment]
I was follwing this blog, the sample i have provided is from the same blog. HOwever i have made some chnges to the same like adding .WithBroker(true), Updgading the "Microsoft.Identity.Client" to latest Version i.e.,"4.23.0" and udating the Azure Client ID AppId and Signature Hash which i configured in my Azure AD App Registrations

**Comment by jmprieur** [comment]
@keerthinathganjam if you uninstall the app from the device and redeploy it, do you still see the same issue?

**Comment by keerthinathganjam** [comment]
@jmprieur Yes i have tried unistalling the app from the device and redeploying it, but still having the same error.

**Comment by jmprieur** [comment]
Thanks for the update, @keerthinathganjam

**Comment by tipa** [comment]
I decided to give the `WithBroker()` option another try and the problem still persists  - it's kinda annoying to hit these exceptions when debugging.
Are you still unable to reproduce this issue or is this just not on your priority list right now?

**Comment by bgavrilMS** [comment]
I think the exception is not coming from our code, but somewhere in Xamarin. It does not affect the operation of MSAL.
