### ISSUE TITLE
[Documentation] Method WithReplyUri does not exist

### ISSUE THREAD

**Issue by tipa** [AzureAD/microsoft-authentication-library-for-dotnet#1684]
### Documentation Related To Component:
Xamarin.Android Broker

### Please check those that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue
The docs mentions `WithReplyUri` [in several places](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/search?q=WithReplyUri&type=Wikis), however the method is not present. I assume `WithRedirectUri` is meant?

**Comment by bgavrilMS** [comment]
Yes, `WithRedirectUri` is meant.

**Comment by bgavrilMS** [comment]
Thank you for reporting this @tipa , fixed.
