### ISSUE TITLE
MSAL Token Cache for Packaged Desktop Application

### ISSUE THREAD

**Issue by wjvii** [AzureAD/microsoft-authentication-library-for-dotnet#1688]
In reading through the documentation it states that MSAL handles the token cache for Android, iOS and UWP but not Desktop apps. My question is, how does MSAL handle token caching for desktop apps that are packaged for the store and have a package identity. Does it handle it like the desktop app or more like the UWP app. As a side note, we are using the Windows Application Packaging Project type to package the desktop application.

Thank you in advance.

**Comment by jmprieur** [comment]
For desktop apps, the recommendation is to use:
- either your own token cache serialization. See https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/msal3x/active-directory-wpf-msgraph-v2/TokenCacheHelper.cs
- or leverage a more productized extension library bringing cross platform token cache. See https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Cross-platform-Token-Cache

**Comment by wjvii** [comment]
Thank you so much. This extension library looks easy enough to use. I just wasn't certain if having it "packaged" changed anything about how the MSAL token cache would work.

Thank you again.

**Comment by jmprieur** [comment]
@wjvii : I'm not familiar with the Windows Application Packaging Project, but I would think it's a question of making sure that your packaged app can write at the location on disk where you want to serialize your token cache. (maybe make it possible in the manifest?)
