### ISSUE TITLE
[Bug] Federated user: Integrated Windows Auth is not supported for managed users

### ISSUE THREAD

**Issue by Thacai** [AzureAD/microsoft-authentication-library-for-dotnet#1690]
**Which Version of MSAL are you using ?**
MSAL 4.9

**Platform**
net472

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [X] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**

This is the ground work for a new app
**Repro**

```csharp
            IPublicClientApplication client = PublicClientApplicationBuilder.Create(clientId)
                                                .WithDefaultRedirectUri()
                                                .WithAuthority(AzureCloudInstance.AzurePublic, tenant)
                                                .Build();
           
            try
            {
                var parameterbuilder = client.AcquireTokenByIntegratedWindowsAuth(scopes);
                var authresult = await parameterbuilder
                                       .ExecuteAsync();
            }
            catch (Exception ex)
            {
                //always exception: Integrated Windows Auth is not supported for managed users 
                throw;
            }
```

**Expected behavior**
Expecting an AuthenticationResult containing an useable bearer token. as my user is federated.

**Actual behavior**
Throws MsalClientException: Integrated Windows Auth is not supported for managed users

**Additional context/ Logs / Screenshots**
The definition of a managed user is a user that only exists in AAD, but my user is federated:
![image](https://user-images.githubusercontent.com/4174649/76210329-3235cf80-6204-11ea-8972-38c65732f934.png)

"Funny" thing is it was working 1 month ago, but have since tried to troubleshoot this in collaboration with our own AAD experts, but have yet to find a reason/solution to this issue, so any pointers etc would be much appreciated. 

***Logs***
```
4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) MSAL MSAL.Desktop with assembly version '4.9.0.0'. CorrelationId(b592fe39-e602-4c0a-856e-61d9ad975ce0)
MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) 
=== Request Data ===
Authority Provided? - True
Scopes - <snip>>/user_impersonation
Extra Query Params Keys (space separated) - 

MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) === Token Acquisition (IntegratedWindowsAuthRequest) started:
	
Authority Host: login.microsoftonline.com
MSAL Verbose False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False
MSAL Info False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Fetching instance discovery from the network from host login.microsoftonline.com
MSAL Verbose False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True
MSAL Verbose False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) [Instance Discovery] After hitting the discovery endpoint, the network provider found an entry for login.microsoftonline.com ? True
MSAL Info False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Resolving authority endpoints... Already resolved? - FALSE
MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Logged in user detected
MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Sending request to userrealm endpoint.
MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) 
MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Exception type: Microsoft.Identity.Client.MsalClientException
, ErrorCode: integrated_windows_auth_not_supported_managed_user

   at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<FetchAssertionFromWsTrustAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__14.MoveNext()
Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in mscorlib.dll

**Comment by srishtipurohit** [comment]
> **Which Version of MSAL are you using ?**
> MSAL 4.9
> 
> **Platform**
> net472
> 
> **What authentication flow has the issue?**
> 
> * Desktop / Mobile
>   
>   * [ ]  Interactive
>   * [x]  Integrated Windows Auth
>   * [ ]  Username Password
>   * [ ]  Device code flow (browserless)
> * Web App
>   
>   * [ ]  Authorization code
>   * [ ]  OBO
> * Web API
>   
>   * [ ]  OBO
> 
> Other? - please describe;
> 
> **Is this a new or existing app?**
> 
> This is the ground work for a new app
> **Repro**
> 
> ```cs
>             IPublicClientApplication client = PublicClientApplicationBuilder.Create(clientId)
>                                                 .WithDefaultRedirectUri()
>                                                 .WithAuthority(AzureCloudInstance.AzurePublic, tenant)
>                                                 .Build();
>            
>             try
>             {
>                 var parameterbuilder = client.AcquireTokenByIntegratedWindowsAuth(scopes);
>                 var authresult = await parameterbuilder
>                                        .ExecuteAsync();
>             }
>             catch (Exception ex)
>             {
>                 //always exception: Integrated Windows Auth is not supported for managed users 
>                 throw;
>             }
> ```
> 
> **Expected behavior**
> Expecting an AuthenticationResult containing an useable bearer token. as my user is federated.
> 
> **Actual behavior**
> Throws MsalClientException: Integrated Windows Auth is not supported for managed users
> 
> **Additional context/ Logs / Screenshots**
> The definition of a managed user is a user that only exists in AAD, but my user is federated:
> ![image](https://user-images.githubusercontent.com/4174649/76210329-3235cf80-6204-11ea-8972-38c65732f934.png)
> 
> "Funny" thing is it was working 1 month ago, but have since tried to troubleshoot this in collaboration with our own AAD experts, but have yet to find a reason/solution to this issue, so any pointers etc would be much appreciated.
> 
> _**Logs**_
> 
> ```
> 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) MSAL MSAL.Desktop with assembly version '4.9.0.0'. CorrelationId(b592fe39-e602-4c0a-856e-61d9ad975ce0)
> MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) 
> === Request Data ===
> Authority Provided? - True
> Scopes - <snip>>/user_impersonation
> Extra Query Params Keys (space separated) - 
> 
> MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) === Token Acquisition (IntegratedWindowsAuthRequest) started:
> 	
> Authority Host: login.microsoftonline.com
> MSAL Verbose False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False
> MSAL Info False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:10 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Fetching instance discovery from the network from host login.microsoftonline.com
> MSAL Verbose False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True
> MSAL Verbose False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) [Instance Discovery] After hitting the discovery endpoint, the network provider found an entry for login.microsoftonline.com ? True
> MSAL Info False (False) MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Resolving authority endpoints... Already resolved? - FALSE
> MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Logged in user detected
> MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Sending request to userrealm endpoint.
> MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) 
> MSAL 4.9.0.0 MSAL.Desktop Microsoft Windows NT 10.0.18363.0 [03/09/2020 11:40:11 - b592fe39-e602-4c0a-856e-61d9ad975ce0] (AuthTest: 0.0.0.0) Exception type: Microsoft.Identity.Client.MsalClientException
> , ErrorCode: integrated_windows_auth_not_supported_managed_user
> 
>    at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<FetchAssertionFromWsTrustAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<ExecuteAsync>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__14.MoveNext()
> Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in mscorlib.dll
> ```

I am facing the same challenge and i thought it is due to microsoft tenant has changed their policy internally. But looks like it is MSAL lib issue. Please share solution if you got any.

**Comment by bgavrilMS** [comment]
This is ussually a configuration issue. The IWA protocol only works if the user is seen as "federated". 

MSAL will make a discovery call like (the one below is using my username):

`https://login.microsoftonline.com/common/userrealm/bogavril@microsoft.com?api-version=1.0`

And you can see that the response sees the user as Federated: 

```
{
ver: "1.0",
account_type: "Federated",
domain_name: "microsoft.com",
federation_protocol: "WSTrust",
federation_metadata_url: "https://msft.sts.microsoft.com/adfs/services/trust/mex",
federation_active_auth_url: "https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed",
cloud_instance_name: "microsoftonline.com",
cloud_audience_urn: "urn:federation:MicrosoftOnline"
}

**Comment by Thacai** [comment]
@bgavrilMS in my case my user is hybrid ad joined (inital screenshot), hence federated, but discovery call returns:
`{"ver":"1.0","account_type":"Managed","domain_name":"danfoss.com","cloud_instance_name":"microsoftonline.com","cloud_audience_urn":"urn:federation:MicrosoftOnline"}`

We had this issue raised directly to microsoft aswell, and even with the above "managed" user, it seems we're no longer getting this exact issue (now we're moving on to conditional access issues instead) but i do see this issue resolved for my case, even though no configuration changes were done.

**Comment by ryfow** [comment]
I think I may be running into this too although I'm getting "unknown_user_type" instead of "integrated_windows_auth_not_supported_managed_user" My account_type shows as managed in discovery response.

**Comment by ryfow** [comment]
Take the following with a grain of salt because I don't know what I'm talking about, but...

I think the issue is that you need your domain to be federated in the sense that Azure AD redirects login requests to an AD FS server. The AD FS server can do windows integrated auth with the desktop and tell Azure AD that the user is authenticated. If there's no AD FS doing the magic, IntegratedWindowsAuth isn't going to work.

**Comment by bgavrilMS** [comment]
The suggested approach is to use WAM, which can login the current Windows user silently in most cases. It even works for personal accounts. See https://aka.ms/msal-net-wam

Otherwise, if the user does not appear as "federated" it is a config issue, please see the Troubleshooting steps https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication

**Comment by rupinderkang-teck** [comment]
I am also having the same issue.  Error I am getting is MsalClientException: ErrorCode: integrated_windows_auth_not_supported_managed_user Microsoft.Identity.Client.MsalClientException: Integrated Windows Auth is not supported for managed users

My code was working 1 week before and it suddenly stopped working. Nothing has changed in our code or organizational settings. In my code I am using non interactive authentication method AcquireTokenByIntegratedWindowsAuth
