### ISSUE TITLE
[Feature Request] AcquireTokenInteractive in select account dialog to offer only accounts related to requested tenant

### ISSUE THREAD

**Issue by fabicz** [AzureAD/microsoft-authentication-library-for-dotnet#1705]
**Is your feature request related to a problem? Please describe.**
When I restrict login to my application only to users of specific tenant, I'm still presented with select account dialog and other account's are there.

**Describe the solution you'd like**
I would like to be presented only accounts that can login (are from same tenant)

**Sample code**
```
            var clientApplication = PublicClientApplicationBuilder.Create(clientId)
                .WithAuthority(AzureCloudInstance.AzurePublic, tenantId)
                .WithDefaultRedirectUri()
                .Build();

            var scopes = new[] { "https://vault.azure.net/.default" };
            var accounts = await clientApplication.GetAccountsAsync().ConfigureAwait(false);

            AuthenticationResult result;
            try
            {
                result = await clientApplication.AcquireTokenSilent(scopes, accounts.FirstOrDefault())
                            .ExecuteAsync().ConfigureAwait(false);
            }
            catch (MsalUiRequiredException)
            {
                result = await clientApplication.AcquireTokenInteractive(scopes)
                    .ExecuteAsync().ConfigureAwait(false);
            }
```

**Select account dialog**
![account_selection](https://user-images.githubusercontent.com/1735576/76626651-d89e0f80-6539-11ea-9bfc-ac0515364966.png)

When I choose "marekn@microsoft.com" I get:
![account_tenant_mismatch](https://user-images.githubusercontent.com/1735576/76626838-2e72b780-653a-11ea-9bdc-f8cccab8c6f6.png)

**Comment by bgavrilMS** [comment]
Hi @fabicz - MSAL does not control the content of this dialog - the AAD service owns it. I this you have a good point, but we cannot action it. 

Please open an issue / support case through the Azure Portal so that it reaches the right audience.
