### ISSUE TITLE
[Feature Request] Improve AcquireToken handling for Confidential client flows for expired secrets

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1709]
**The challenge**
When a secret changes the MSAL cache will still have a Access token which would typically have a lifetime of 1h. This means the secret will be in the MSAL cache for up to 1h and the resource may reject the token as they have implemented instant revocation.

**Adding to the confusion**
The AcquireToken call for Confidential Client doesn't used a cache lookup and there is no way for the application developers to control this lookup. This means they could be providing the new secret to the call to MSAL but MSAL will still for some period of time give the cached token back. 

**Solution thoughts**
 - Clear the cache entry and do a new service call if the secret used is not the same as the one used for the cache entry.
 - Make it easy to self delete a cache item based on a response from a resource provider
 - Should not require a major version bump

**Comment by jmprieur** [comment]
@henrik-me : we now have ForceRefresh on all the confidential client flows (AcquireTokenForClient, OBO and AcquireTokenSilent). Given that AcquireTokenByAuthCode does not look at the cache and should not, I think we could close this one?
Don't you think that would be enough?

**Comment by henrik-me** [comment]
@jmprieur, I'm ok closing. tldr; #discoverabilty/supportability concern otherwise ok with me.

Though it requires that the developer knows to use force refresh, and they may not always be aware. I'm assuming we return where we got the data from  in the authresult so I assume we are ok (if people discovers this).
