### ISSUE TITLE
[Bug] WithProofOfPosession produces a token of type POP, whereas the Wilson 6.0 expects PoP

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1711]
**Which Version of MSAL are you using ?**
4.9

**Platform**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Expected behavior**
Send PoP

**Actual behavior**
Sends POP

**Comment by bgavrilMS** [comment]
Hmm, the validating service that we use for integration testing  does not seem to complain about this. I guess Wilson tightened the rules. @GeoK - are there plans to update the validation service to use Wilson 6? Or I could contribute to the project if pubic?

**Comment by jmprieur** [comment]
Actually Wilson does a case insensitive match, so this works (my bad @bgavrilMS )
but in the Middleware grooming meeting we've advised that MSAL.NET sends "PoP". Not super urgent.

**Comment by GeoK** [comment]
@bgavrilMS Both Wilson and SAL and lax on the validation side. Extra spaces and different casing are forgiven. The [spec](https://tools.ietf.org/html/draft-ietf-oauth-signed-http-request-03#section-4.1) defines "PoP" as the authentication scheme.

**Comment by trwalke** [comment]
Resolved in [4.11.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.11.0)
