### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ankitk20** [AzureAD/microsoft-authentication-library-for-dotnet#1713]
**Which Version of MSAL are you using ?**
MSAL 4.9.0

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [x] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**

**Repro**

```csharp
authResult = clientApp.AcquireTokenByAuthorizationCode(scope, code).ExecuteAsync().Result;
```

**Expected behavior**
AAD token should get generated only for the specified scopes

**Actual behavior**
AAD token is getting generated for all the scopes in the AAD app

** Fiddler trace**

![image](https://user-images.githubusercontent.com/13991339/76842515-65114080-6860-11ea-9615-24cc22750ec0.png)

**Comment by bgavrilMS** [comment]
Hi @ankitk20 - this is by design and is an optimisation that AAD implemented. I'm not 100% sure, but I think it applies to all authentication flows. 

How is this affecting you?

**Comment by ankitk20** [comment]
If this is by design then, why is there a need to pass scope as a parameter to the method?

**Comment by bgavrilMS** [comment]
For consent purposes - the user still needs to consent on the required scopes. But access tokens will have all effective scopes. https://docs.microsoft.com/en-gb/azure/active-directory/develop/v2-permissions-and-consent#scopes-and-permissions
