### ISSUE TITLE
[Bug] when used on the acquireTokenParameterBuilder, WithAuthority() does not change the authority sent in broker requests.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1716]
**Which Version of MSAL are you using ?**
4.9.0

**Platform**
xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**
make an interactive request to android broker for "https://login.microsoftonline.com/organizations"
by using the WithAuthority() api on the acquireTokenParameterBuilder
```csharp
            var authResult = await ClientApplication
                .AcquireTokenInteractive(scopes)
                .WithUseEmbeddedWebView(false)
                .WithAuthority("https://login.microsoftonline.com/organizations")
                .ExecuteAsync();
```

**Expected behavior**
MSAL should send a request to the broker with the authority specified in the WithAuthoriry() api

**Actual behavior**
MSAL sends the request to broker with the default common endpoint instead. 

**Workaround**
use the WithAuthority() api that is available on the client application builder.
```CSharp
            var app = PublicClientApplicationBuilder.Create(clientID)
                                                    .WithAuthority("https://login.microsoftonline.com/organizations")
                                                    .Build()
```

**Comment by jmprieur** [comment]
@trwalke 
I don't think that using /organizations in .WithAuthority on an acquireToken method is a valid scenario. .WithAuthority is only to specify a tenant, I would think?
What scenario are you trying to achieve? what authority was passed in the app builder?

**Comment by trwalke** [comment]
Quick question, shouldn't the value set in AcquireTokenParameterBuilder.WithAuthority(value) be honored in brokered authentication regardless of the scenario?
