### ISSUE TITLE
[Bug] CryptographicException when using CNG certificate

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1726]
**Which Version of MSAL are you using ?**
4.10

**Platform**
net45 (does not repro on netcore)

**Repro**

ClientCreds with a certificate generated from ADFS 2019 or any CNG certificate
Simplest is to run the integration test `ClientCreds_WithCertificate_Adfs_Async` which will download such a certificate...

Expected: MSAL should fetch a token
Actual: Cryptographic Exception 

System.Security.Cryptography.CryptographicException: Invalid provider type specified.
    X509Certificate2.get_PrivateKey()
    NetDesktopCryptographyManager.GetCryptoProviderForSha256(X509Certificate2 certificate) line 92
... rest of stack trace is not important ...

**Note**: 

1. Wilson is able to handle this certificate!
2. There seems to be a known issue with CNG type certs but not sure how to get around it. Wilson seems to be able to get around it just fine... The exception occurs when accessing the PrivateKey property.

## How to fix this

Wilson knows how to handle these certs. We need to use the same logic in both Wilson and MSAL, but we cannot take a depdency on Wilson. 

As part of fixing this issue, we need to asses the possibility of using a github submodule for the shared logic.

## Workaround

1. Create a signed assertion manually like [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/ae08125657b90289ed886eb7d725d3045b1634d7/tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs#L487) - using Microsoft.IdentityModel.JsonWebTokens nuget package. Just make sure the audience value is set to the token endpoint, which is: 

`"{authority}oauth2/v2.0/token"` for AAD and B2C 
`"{authority}oauth2/token"` for ADFS

So for example if your authority is `https://login.microsoftonline.com/12345-56789` the the token endpoint is `https://login.microsoftonline.com/12345-56789/oauth2/v2.0/token` - this is the `aud` value.

2. Instead of using `.WithCertificate` use `.WithClientAssertion` and pass in the string from previous step ([example](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/ae08125657b90289ed886eb7d725d3045b1634d7/tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs#L474))

This is what MSAL internally should be extracting from that certificate, but it is unfortunately failing because on .net classic we need to support APIs all the way down to .net 4.5 that are very buggy. We cannot take a dependency on Microsoft.IdentityModel.JsonWebTokens as it is a breaking change.

**Comment by bgavrilMS** [comment]
Quite a few bugs around certificate usage in MSAL now ... @henrik-me @trwalke  Perhaps it's time to bite the bullet and upgrade to use Wilson?

**Comment by jmprieur** [comment]
yes, that would be a good optimization if this works for all platforms? (or would we have two code paths)?

**Comment by bgavrilMS** [comment]
Well we would use Wilson for 2 things: Client Creds and PoP, which are really only present on .net classic and .net core;

Wilson has bindings for .net classic 4.5 and .net standard 2.0

So in the short term, we could move to use Wilson without changing our supported frameworks. In the longer term we might have to take a breaking change if we will want to support PoP on UWP for example, or if we want things to work better on pure .netstandard (for things like Unity).

**Comment by jmprieur** [comment]
Let's do that, then, and if we see the value, let's move to 5.0 (given that it's only about platforms)

**Comment by henning-krause** [comment]
Just stumbled accross because I got this exact error when using certificates created with PowerShell New-SelfSignedCertificate cmdlet, which uses CNG to create certificates.

**Comment by bgavrilMS** [comment]
@henning-krause - I added a workaround, please let me know if that works.

**Comment by henning-krause** [comment]
@bgavrilMS I found another workaround. I you specify `-KeySpec KeyExchange` as a parameter for `New-SelfSignedCertificate`, it will revert to the CAPI provider and create legacy certificates. That works.

**Comment by bgavrilMS** [comment]
@trwalke - I think we need to do what Wilson. Its logic is capured in 2 files: 

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/06cae9a6d422dac7b76f1db9de032b98c1d8c836/src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs#L48

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/06cae9a6d422dac7b76f1db9de032b98c1d8c836/src/Microsoft.IdentityModel.Tokens/RsaCryptoServiceProviderProxy.cs#L43

These files have seen very little change in the past 1 year, so I am thinking that copying the logic should be sufficient.

**Comment by bgavrilMS** [comment]
Also see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1937#event-3546620587 for an example of how to create this type of cert.

**Comment by bgavrilMS** [comment]
Upon further investigation, it seems that Wilson is also not able to handle these certs on .net 45. So the way to move forward here is to add also target .net 461 as make a simple code change.
