### ISSUE TITLE
[Feature Request] Show url in sign-in dialog/window hosting the embedded browser

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1733]
The “Sign in to your Microsoft account” does not show the URL being requested. There is no way to tell if this is a legitimate request or if I am being phished/compromised somehow.

**The issue is described in more details here:**
https://developercommunity.visualstudio.com/idea/904445/security-issue-sign-in-to-your-microsoft-account-d.html

**Current:**
![image](https://user-images.githubusercontent.com/34380746/77953823-89b6e080-7282-11ea-9f4f-84448692bdaa.png)

**Expected:** 
Show the requested URL and certificate to ascertain that the displayed interface is being loaded from the expected MSFT resource.

**Comment by jmprieur** [comment]
@henrik-me : and we agree that 
1) this is in the embedded web view?
2) that would be an opt-in behavior?

**Comment by jmprieur** [comment]
@henrik-me 
I'm tempted to won't fix this one. Visual Studio has many ways of using sign-in now, including the system web view and Device code flow where the user can see the sign-in URL, and with WAM this won't even be an option
Do you agree?

**Comment by bgavrilMS** [comment]
Agreed.

**Comment by henrik-me** [comment]
ack. closing.
