### ISSUE TITLE
[Bug] AcquireTokenSilent on ADFS always hits the STS

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1739]
**Which Version of MSAL are you using ?**
4.10

**Platform**
all

**Repro**

```csharp
AcquireTokenInteractive with scope "User.Read" or with no scopes
AcquireTokenSilent with the same scope
```

**Expected behavior**
AcquireTokenSilent should hit the cache

**Actual behavior**
refresh_token flow is used to get a new AT every time

**Additional context/ Logs / Screenshots**
It looks like ADFS /token response lists the scopes only as "openid", even if MSAL requests "openid", "profile" "offline_access" and "user.read"

**Comment by jmprieur** [comment]
@bgavrilMS @henrik-me do we consider this to be an MSAL.NET bug? or an external issue?

**Comment by bgavrilMS** [comment]
This is an ADFS bug, because they should behave like AAD.

**Comment by bgavrilMS** [comment]
Will not fix this.
