### ISSUE TITLE
Exception in token acquisition when going through a proxy with credentials (HTTP response 407 Authentication Required)

### ISSUE THREAD

**Issue by eprofeta** [AzureAD/microsoft-authentication-library-for-dotnet#1743]
I am using  IClientApplicationBase.AcquireTokenSilent and IPublicClientApplication.AcquireTokenInteractive in a Windows desktop app (based on 
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-windows-desktop). 
The initial request sent:
CONNECT login.microsoftonline.com:443 HTTP/1.1
Host: login.microsoftonline.com
If sent through a proxy with username/password, the proxy will first return (as expected)
HTTP/1.1 407 Proxy Auth Required
Connection: close
Proxy-Authenticate: etc.

At this point, the AcquireToken APIs will throw:
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

I would like to know if there are ways to change the behavior so that AcquireTokenInteractive prompts the user for username/password (as in a browser - client app provides the dialog), and AcquireTokenSilent uses cached username/password.
My understanding is that all that's needed is for the AcquireToken APIs to include the header 
Proxy-Authorization: <type> <credentials> in subsequent calls (or the initial).

**Comment by bgavrilMS** [comment]
Which call exactly is returning the 407 error? It may help to capture a Fiddler trace. Is it the call to /authorize endpoint (which is not handled by MSAL) or some other call ?

**Comment by eprofeta** [comment]
[4524_Full.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/4439749/4524_Full.txt)

**Comment by eprofeta** [comment]
The code is (snippet)
IPublicClientApplication clientApplication = PublicClientApplicationBuilder.Create(clientID)
                .WithAuthority(authorityURI)
                .Build();
AuthenticationResult authResult = await clientApplication.AcquireTokenInteractive(scopes).ExecuteAsync();

**Comment by bgavrilMS** [comment]
MSAL provides an extensibility point so that you can inject your own HttpClient, which you can configure with your proxy, including proxy auth.

As for when the browser pops up, there aren't really that many options. The embedded browser which you use is really just Edge. I would assume your browser is already configured to use this proxy?

**Comment by eprofeta** [comment]
Attaching stack trace for 
AuthenticationResult authResult = await clientApplication.AcquireTokenSilent(scopes, user).ExecuteAsync();
[StackTraceForAcquireSilent.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/4439779/StackTraceForAcquireSilent.txt)

**Comment by eprofeta** [comment]
Yes browser is already configured. Would the HttpClient option work for both interactive and silent acquisitions?

**Comment by bgavrilMS** [comment]
Yes, if the browser is already configured, configuring the HttpClient should do the trick.

**Comment by eprofeta** [comment]
OK. I will explore this direction. Thanks!

**Comment by jmprieur** [comment]
Closing as this was answered
