### ISSUE TITLE
[Feature Request] Support for .NET Standard 2.0/2.1

### ISSUE THREAD

**Issue by silkfire** [AzureAD/microsoft-authentication-library-for-dotnet#1744]
Is there any reason why this package is stuck at .NET Standard 1.3 and not being multi-targeted together with the more current .NET Standard 2.0 or 2.1?

**Comment by bgavrilMS** [comment]
MSAL does a things which are tightly coupled with the framework: pops up browsers, stores tokens securely and a bit of cryto work. 

As such, we've decided to target a lot of frameworks explicitly and provide the best experience for each of these platforms. For example, on .net classic we can host a browser in a win forms pane. On .net core, we can only use the system browser. Some defaults are also different (e.g. see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser)

Our main use .net standard is as an interface for Xamarin projects, which by default have a "shared" (netstandard) library. Or secondary use of netstandard is to support less used frameworks like Unity, for which we do not have bandwidth to provide a full experience. Thirdly - we don't want to introduce breaking changes such as bumping support from 1.3 to a more recent 2.x.

So the question really is - what framework is your app targeting? Why do you need netstandard 2.1?

**Comment by jmprieur** [comment]
@silkfire : which framework is your app targeting? what is your scenario?
(closing as you have not answered, but feel free to answer and I'll reopen)
