### ISSUE TITLE
[Documentation] IWA for MSA always fails because MSAL ignores 406 (bad content) error

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1748]
**Which Version of MSAL are you using ?**
4.10

**Platform**
net45, netcore

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**

Attempt IWA flow for an MSA user

**Expected behavior**
IWA could work?! (MSA user is reported as federated ...). Not sure about expected behaviour.

**Actual behavior**
When calling the ws-fed endpoint, MSAL adds a bad header `Accept: application/json` (it's bad because the response is XML, not json). MSA correctly sends back a 406 (Not Acceptable) error. 

Without this header, an actual response is provided, but MSAL does not seem to be able to parse it.

Note: AAD is more "resilient" and sends us the XML nevertheless 

**Possible Solution**
do not add `Accept: application/json` when expecting XML back!

**Comment by henrik-me** [comment]
Triage: MSA is not expected to work with IWA, however with WAM support we should be able to get tokens for some scopes/resources. @jmprieur to update docs.

**Comment by jmprieur** [comment]
@henrik-me @bgavrilMS 
I've updated the wiki: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication
I'll update docs.ms when WAM is released on the platforms we want to release it

**Comment by henrik-me** [comment]
Work done. For better experience customer should use WAM.
