### ISSUE TITLE
[Feature Request] OIDC metadata cache should ignore tenants

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1750]
**Which Version of MSAL are you using ?**
4.11

**Platform**
all

**Scenario**

1. AcquireToken* using tenant1
2. AcquireToken* using tenant2

**Expected behavior**
A single call to OIDC metadata should be performed

**Actual behavior**
2 calls are performed (one for each tenant)

**Possible Solution**
We have discussed with the server-side folks and they have agreed that we can cache by environment only.

It might be possible to not call OIDC at all as we only use the /token and /authorize endpoint URIs, which have a standard format. But if an STS does not support /authorize, we would not know about it in a nice way (i.e. some STS-es return "unsupported"). Not a big deal though.

Still undecided: do we want to allow developers to bypass this behaviour and get the per-tenant metadata? Perhaps this can be a separate task?

**Comment by bgavrilMS** [comment]
@jmprieur @henrik-me - I think I'm going to go one step further and not call OIDC at all? This is what Java does.  I talked to Jason about possible impact on cross-cloud scenarios, and there shouldn't be any. Thoughts?

We can add an option to toggle this later on, if needed, smth like: 

`.WithOIDCDiscovery(Discovery.PerTenant)` with possible values `None` (default), `PerTenant` and `PerAuthority`.

**Comment by jmprieur** [comment]
@bgavrilMS  In which cases would we skip it? for Azure AD?
Do we care if we don't get the issuer aliases? (I though they were needed to know the preferred one?

**Comment by henrik-me** [comment]
@jmprieur we would always skip it. Suggesion from Bogdan is though to potentially add functionality that would enable calling the OIDCDiscovery endpoint. Not having to make this call is a huge performance gain. We don't really need anything from there any way... will be a benefit in many scenarios. Not sure if there will be any sort of impact with the work for the CloudInstanceAware feature? @bgavrilMS Which end-point do we talk to for that info?

**Comment by henrik-me** [comment]
Aside: ADAL does this per Authority today.

**Comment by bgavrilMS** [comment]
I am proposing to skip the call to get the OIDC metadata: 

https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

We only use the `authorization_endpoint` and `token_endpoint` from there

The logic around instance metadata (i.e. aliases and authority validation) remains the same.

**Comment by jmprieur** [comment]
Thanks for explaining.  Yes: that would always work for Azure AD.
We'd need to check for national clouds though ?

**Comment by bgavrilMS** [comment]
I don't think that for national clouds it is different ... https://login.microsoftonline.de/common/v2.0/.well-known/openid-configuration

I need to check for B2C and ADFS. But typically these 2 endpoints (token and authorize) are formed by adding the suffix `oauth2/v2.0/authorize` to the authority.

**Comment by bgavrilMS** [comment]
For now, I will implement caching per cloud and we can revisit this if needed.

**Comment by bgavrilMS** [comment]
Yordan has expressed opposition to this. Will have a conversation with him first. May be that we can only implement this for some flows but not others...
