### ISSUE TITLE
[Documentation] HttpClient factory needs an example

### ISSUE THREAD

**Issue by Debro012** [AzureAD/microsoft-authentication-library-for-dotnet#1751]
### Documentation Related To Component:
Need detailed documentation or example for implementing IMsalHttpClientFactory.

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
My application will be used behind a firewall, and I need to utilize a proxy to make all web requests. In utilizing .Net Core 2.1, I am not aware of proxy configuration which can be applied to the whole project, so I need to direct all http/https calls to the proxy. For MSAL, the only option I find is via IMsalHttpClientFactory. However, the documentation at the following locations do not provide clear examples on how to move forward: 

- https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-provide-httpclient

- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/httpclient

**Comment by bgavrilMS** [comment]
I added an example at: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/HttpClient

Could you take a look please?

**Comment by Debro012** [comment]
> I added an example at:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/HttpClient
> 
> Could you take a look please?

This is EXACTLY what I needed. Thank you for the example and the quick reply!

**Comment by bgavrilMS** [comment]
Good to hear it works. @jmprieur - could we get the msdn docs updated as well?
