### ISSUE TITLE
[Bug] AndroidManifest.xml hardcoded android:scheme issue

### ISSUE THREAD

**Issue by JohnLivermore** [AzureAD/microsoft-authentication-library-for-dotnet#1754]
We are using the Microsoft.Identity.Client package (4.7.1) for leveraging the MS identity platform.  As part of the setup for this, you need to add a line to your AndroidManifest.xml file with ...

![image](https://user-images.githubusercontent.com/1489667/78827675-19f2d500-79a9-11ea-8d8e-c0a098f9851b.png)

However, this is a hardcoded value that we need to change during our build process.

Can someone provide guidance on how to handle this?  Ideally we would want to store the msalxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx value in a configuration file.  Then, during runtime we could swap in the correct value overriding what comes from AndroidManifest.xml.

**Comment by henrik-me** [comment]
@JohnLivermore : did you look at https://developer.android.com/studio/build/manifest-build-variables

**Comment by JohnLivermore** [comment]
Thanks.  That is what I am looking for, but I don't have a build.gradle file.  Where would that come into play or where would I find that for a Xamarin project?

**Comment by henrik-me** [comment]
@trwalke @neha-bhargava

**Comment by henrik-me** [comment]
@JohnLivermore : I believe the [Xamarin GitHub](https://github.com/xamarin) might be a better place for your questions.
