### ISSUE TITLE
[Documentation] Add Examples for Razor Pages

### ISSUE THREAD

**Issue by mskilling** [AzureAD/microsoft-authentication-library-for-dotnet#1755]
I am new to web app creation and I would like there to be some examples of using this authentication library with razor pages. All examples seem to be MVC usage and with my limited knowledge I am not sure how to implement differently for razor pages.
I am writing a web app that authenticates with a Microsoft account and then needs to connect to an SQL database on behalf of the user signed in, it does not seem obvious to me exactly how this needs to be done with this library.

**Comment by bgavrilMS** [comment]
@kalyankrishna1 @TiagoBrenck @jmprieur  can answer this question better. 

My limited understanding is that Razor is similar to the view part of MVC. Integration with AAD is done more at controller level and via configuration of the services, which remain largely the same.

**Comment by TiagoBrenck** [comment]
@mskilling do you need to acquire an access token as well?

**Comment by mskilling** [comment]
Thanks for responses.
I thought it looked very similar to MVC setup, it is not clear to me where in the razor setup I need to get the access token for the SQL connection, whether in the data context or the page model?
I am probably asking the wrong questions with my inexperience, so ideally for me would be a full example of a razor pages application that connects to SQL database on behalf of a signed in user. I see various examples but can't quite put it all together.
Thanks.

**Comment by TiagoBrenck** [comment]
Well, MSAL is a library that will help you authenticate with AAD, and acquire access token for resources on AAD as well. The reason I asked about acquiring an access token on Blazor, is because we havent come with a solution to it yet, and there are no Blazor samples using MSAL so far.

**Comment by mskilling** [comment]
@TiagoBrenck I do need an access token for a Razor application, but not for a Blazor application, I don't know if that would be different?

**Comment by TiagoBrenck** [comment]
@mskilling that wouldn't be different. From what we tested and worked so far, is just the sign-In part.

**Comment by mskilling** [comment]
So, is it not possible for me to get an access token for an Azure SQL database on-behalf-of the signed in user right now? Can I do this with an MVC app but not with a Razor app?

**Comment by TiagoBrenck** [comment]
With an MVC app you can use MSAL to acquire an access token on-behalf-of the signed user without a problem. I highly recommend you to follow this sample first:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph
