### ISSUE TITLE
[Feature Request] Prevent HttpClient port exhaustion 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1756]
**Which Version of MSAL are you using ?**
4.11

**Platform**
net45, netcore

Affects confidential clients

**Repro**

1. Do not provide a custom IHttpFactory
2. Many threads AcquireToken (e.g. web site at scale)

**Expected behavior**
MSAL should work 

**Actual behavior**
After some time, an exception from HttpClient occurs complaining about port exaustion.

**Possible Solution**
There is a solution on .net classic described here https://softwareengineering.stackexchange.com/questions/330364/should-we-create-a-new-single-instance-of-httpclient-for-all-requests

For .net core, the solution is to use IHttpClientFactory, which needs to be adapted. Microsoft.Identity.Web should showcase how to do this. A better default for MSAL needs some investigation.

**Comment by henrik-me** [comment]
@bgavrilMS, regarding .netcore, are there somethings we can do better by default in the library (and perhaps will make it easier for Identity.Web and others to do the right thing and or their custom thing)?

**Comment by bgavrilMS** [comment]
I'll have a look at this. We could add a simplified version of `IHttpClientFactory`, or even a static `HttpClient`.

**Comment by jmprieur** [comment]
See https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect/pull/38 for how the usage of SuggestedCacheKey and HasToken simplifies the token cache serialization in confidential client applications

cc: @bgavrilMS @jennyf19 @pmaytak @henrik-me @trwalke @neha-bhargava
