### ISSUE TITLE
[Bug][Spelling] API WithInstanceDicoveryMetadata missing an s

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1757]
**Which Version of MSAL are you using ?**
Latest

**Issue**
WithInstanceDicoveryMetadata should be _WithInstanceDiscoveryMetadata_
[Typo (and then copy/pasted in multiple locations)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/search?q=WithInstanceDicoveryMetadata&unscoped_q=WithInstanceDicoveryMetadata)

This introduced a misspelling in the WithInstanceDiscoveryMetadata API
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/75ef92a90a1aef2b411b89ad5b4bb3c483305ebb

**Expected:**
The API is correctly spelled

**Actual:**
The API is missing an s

**Comment by bgavrilMS** [comment]
Proposal:

Create new method with same signature
Hide the bad method from IntelliSense
Obsolete the bad method

**Comment by neha-bhargava** [comment]
Fixed in [MSAL 4.12.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.12.0)
