### ISSUE TITLE
Unable to find implementation of microsoft login for windows form applications

### ISSUE THREAD

**Issue by KrishnaAgrawal5** [AzureAD/microsoft-authentication-library-for-dotnet#1758]
I am facing problems while acquiring token using AcquireTokenInteractive in windows forms. No login window pops up.

I have tried using  result = await _clientApplication.AcquireTokenInteractive(_scopes)
                             .WithParentActivityOrWindow(new WindowInteropHelper(this).Handle)
                            .ExecuteAsync();

But it gives error on 'this' stating cannot convert to System.Windows.Window

Any help in this subject is highly appreciated as I am new to this. Thanks

**Comment by bgavrilMS** [comment]
Can you get rid of `.WithParentActivityOrWindow(new WindowInteropHelper(this).Handle)` first and check out the experience ?

`WithParentActivityOrWindow` on a WinForms app simply ensures that the browser pops up in the center of the app. If you do not use this method, the browser will be centred on the screen.

On WindowsForms, you can pass any `IWin32Window` object, and the `Control` class implements this interface. So for example, your main form can be passed in.

**Comment by KrishnaAgrawal5** [comment]
Thanks for your quick reply  @bgavrilMS 
I tried without `.WithParentActivityOrWindow(new WindowInteropHelper(this).Handle)` this and the window just gets stuck and nothing happens. Please find below my updated request:
`result = await _clientApplication.AcquireTokenInteractive(_scopes).ExecuteAsync();`

**Comment by bgavrilMS** [comment]
How do you call AcquireTokenInteractive ? On a button click ? 

If the app gets stuck, it's usually a UI thread problem.

Here's an WinForms app that I use with MSAL: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4d32fdc3cdf71bb6b71baf03bbe55e4cbafd2caa/tests/devapps/DesktopTestApp/MainForm.cs#L153

**Comment by KrishnaAgrawal5** [comment]
Yes I am calling on button click.

Can you suggest me the changes that needs to be done. I am using Microsoft.Identity.Client package

**Comment by bgavrilMS** [comment]
Are you using .net classic or .net core?

**Comment by bgavrilMS** [comment]
I'm not sure where you get stuck with this. I just created a very simple WinForms app, added a button and changed the Form1.cs as follows: 

```csharp
public partial class Form1 : Form
    {
        private readonly IPublicClientApplication _pca;


        public Form1()
        {
            InitializeComponent();

            _pca = PublicClientApplicationBuilder
                .Create("1d18b3b0-251b-4714-a02a-9956cec86c2d")
                .Build();
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            try
            {
                var accounts = await _pca.GetAccountsAsync();
                var result1 = await _pca.AcquireTokenSilent(new[] { "User.Read" }, accounts.FirstOrDefault()).ExecuteAsync();
            }
            catch (MsalUiRequiredException)
            {

                var result2 = await _pca.AcquireTokenInteractive(new[] { "User.Read" })
                    .ExecuteAsync();
            }
        }
    }

```

Works fine for me.

**Comment by KrishnaAgrawal5** [comment]
I am using .Net framework. 

I tried this sample code with a new windows form application and it works there. Thanks you so much for this.

Let me check with my original application once.

**Comment by KrishnaAgrawal5** [comment]
In my original application I am trying to upload files to onedrive.
For files upto 4MB in size I am using below request which works fine:
`var uploadedFile =await client.Me.Drive.Root
                                                          .ItemWithPath(fileName)
                                                          .Content
                                                          .Request()
                                                          .PutAsync<DriveItem>(fileStream);`

But for files larger than 4MB I am facing issue:
`var uploadSession = client.Me.Drive.Root
                                        .ItemWithPath(fileName)
                                        .CreateUploadSession()
                                        .Request()
                                        .PostAsync()
                                        .Result;`
Here while trying to fetch token the UI is getting hanged up.

**Comment by bgavrilMS** [comment]
Probably a threading issue that you need to figure out yourself (e.g. consider not using `.Result`). It seems to me that MSAL is working fine for WinForms apps.
