### ISSUE TITLE
[Question] Why is the interactive dialog in framework so tall?

### ISSUE THREAD

**Issue by dmeatte-aq** [AzureAD/microsoft-authentication-library-for-dotnet#1760]
**Which Version of MSAL are you using ?**
3.x

**Platform**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ x ] Interactive

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**
The window height for an [interactive sign in dialog is set to 70% of the screen height](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/aef655d4575d5c4849de9f8a1df0ff7ac38affe6/src/client/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs#L307). That seems really arbitrary and looks weird on larger screens. Why was this done? 

```csharp
// Window height is set to 70% of the screen height.
int uiHeight = (int)(Math.Max(screen.WorkingArea.Height, 160) * 70.0 / DpiHelper.ZoomPercent);
```

You can recreate this behavior with [this sample repo](https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2).

**Expected behavior**
A window that fits the contents of the window.

**Actual behavior**
A window that is three times too large.
![image](https://user-images.githubusercontent.com/44836981/79261734-4487d680-7e5e-11ea-895c-3cb1e83aa89d.png)

**Possible Solution**
Explain why this size was chosen, or possibly size the window to the contents

**Comment by bgavrilMS** [comment]
Looks like a bug to me. No idea "why this was done", that code is probably 5-10 years old :)

**Comment by dmeatte-aq** [comment]
👍 Looks like I may make a go at a fix then. Thanks.

**Comment by bgavrilMS** [comment]
Awesome, let me know if you have problems building MSAL. I would suggest that you do not build the xamarin and uwp stuff, otherwise you'll have to install a ton of VS modules. You can disable by commenting some lines [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Directory.Build.props#L8). You may have to do "msbuild /t:restore" from a developer command prompt. 

Otherwise, it's more or less standard stuff. That part of the code isn't unit tested.

**Comment by jmprieur** [comment]
Moving to P3 as this as been a long time, and we did not have more complain
@dmeatte-aq do you have a fix?

**Comment by dmeatte-aq** [comment]
I’m afraid I don’t have a fix. Priorities changed and I never got the chance.

**Comment by jmprieur** [comment]
Thanks for the update, @dmeatte-aq !
