### ISSUE TITLE
[Feature Request] [ConfidentialClient] Enable applications to schedule token refresh intervals easily

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#1763]
Note: General functionality may also be relevant for Public Client, and thus scenarios with refresh tokens available where MSAL could potentially do more.

Our current recommendation is described under  [Pro-Active Token renewal](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability#pro-active-token-renewal). 

**Is your feature request related to a problem? Please describe.**
The issue is that several applications and high availability services would like to proactively have tokens available for the moment the user needs a token and thus they would like in the background to perform the requests for Access Tokens ensuring it's available when needed. 

A recent request of this has been filed in the Azure SDK's: https://github.com/Azure/azure-sdk-for-net/issues/5930

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**
See the issue and the conversation in the Azure SDK issue linked above.

**Comment by henrik-me** [comment]
@bgavrilMS @jmprieur

**Comment by Petermarcu** [comment]
@chrisamert as FYI who opened the original issues that we closed in favor of this one.

**Comment by bgavrilMS** [comment]
Let me bring up a few points to open up the discussion: 

1. Refreshing involves higher COGS. Not only would we be asking for tokens more often, but we'd be asking for tokens for users who will never log in ever again.

2. MSAL cannot perform background operations. I think higher level libraries / frameworks need to schedule in the background. If MSAL starts spinning up long running operations, it may cause problems in web app / web apis. Something for Microsoft.Identity.Web to think about.

3. We do have a mechanism called "refresh in" where AAD will tell us when to refresh the token, e.g. expiration=3600 refresh_in=1800. Then when application calls `AcquireTokenSilent`, and the refresh_in interval has elapsed, MSAL will try to refresh the token. If it fails, it still has a fresh token. Notice the subtle difference between "MSAL refreshes the token for the current user" vs "MSAL refreshes the tokens for all users". But if user does not make a request in the 1h default expiration, no token referesh occurs.

Technically it would be very easy to expose this mechanism and make "refresh in" configurable by developers. 

4. AccessTokens are per tenant, refresh tokens are tenant agnostic (per account). An account can be present in multiple tenants. So 1 refresh token can lead to many calls. Some users (e.g. IT consultants) are present in 30+ tenants.

5. If MSAL refreshes all its refresh tokens at once, it will cause a lot of requests to AAD - potentially causing availability issues and causing AAD to respond with 503 error / Retry-After 60s.

**Comment by pmaytak** [comment]
@bgavrilMS, +1 to valid points.
I like the approach of allowing a user to customize the `refresh_in` value. We'd also have to have a minimum time limit for refreshes.

**Comment by bgavrilMS** [comment]
### RefreshIn approach

**Pros**: Simple to use, no need for background operations etc.
**Cons**: if user doesn't login for 1h, a refresh_token flow is performed when he/she logs in.

### GetCacheEntriesNearExpiry approach

`IEnumerable<(IAccount, TenantId)> GetCacheUserEntriesNearExpiry(TimeSpan timeToExpiry)` and / or a variant where the input param is the percentage (e.g. at 2/3 expiry)

This should information should be enough for applications to schedule token refreshes via

`AcquireTokenSilent(account).WithTenant(tenant).WithForceRefresh(true)`

**Pros** Can be used to refresh all tokens
**Cons** Apps need to schedule refresh; If too many refreshes happen at once, AAD will throttle the app.

**Comment by henrik-me** [comment]
Should probably be combined with the throttling functionality somehow, with support for persisting throttling information at least for the lifetime of the process. Also should consider preventing tokens not near expiry from being refreshed (e.g. only if with-in 5 minutes of expiry). Should generally have an API that will not encourage the use of ForceRefresh.

**Comment by jmprieur** [comment]
Controlled by the IDP.
Will reopen if there are customers requests
