### ISSUE TITLE
[Feature Request] Update app center test app to use the latest android SDK and OS

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1765]
**Is your feature request related to a problem? Please describe.**
Android and iOS is updating continuously and we want to ensure that we have coverage for the latest and greatest software on our mobile platforms. The SDK used by the xamarinDev and xamarin appcenter apps should be updated to use the latest xamarin forms as well.

**Describe the solution you'd like**
All Xamarin test apps should be updated to use the latest Xamarin forms packages. Xamarin appcenter tests should be updated to support the latest android 10 and iOS 13 versions. these tests should be enabled as part of the nightly run as well as the ui automation build on PRs into master.

**Comment by bgavrilMS** [comment]
we no longer run these tests.
