### ISSUE TITLE
[Bug] Safari Save Password prompt is not being retained on screen - iOS 13+

### ISSUE THREAD

**Issue by SravanthiKare** [AzureAD/microsoft-authentication-library-for-dotnet#1766]
**Version:** MSAL 4.11.0
**Xamarin iOS:** 13.16.0.3
**XCode: ** 11.4
**iOS Version:** 13.3, 13.4
**Authentication Flow:** Mobile - UserName Password

**Actual Statement:**
We have a requirement to enable user to Save Password using iPhone's Autofill option. Once Autofill option is enabled on iPhone, B2C Login Screen (Safari) will prompt user to Save Password. It is working as expected till iOS 12 version. But from iOS 13 version, B2C Login Screen is not waiting user to take an action on SavePassword prompt. It is immediately closing the browser.

**Expected behavior**
In iOS 13 as well, user should be allowed to Save Password in B2C Login Screen.

Please suggest some workaround for this issue.

**Comment by jmprieur** [comment]
@SravanthiKare 
Thank sof raising this issue.
This is not an issue with the library, but, maybe with the B2C service. I'm going to draw their attention to it.
Were you using the system browser? or the embedded web view? (Did you use `.WithEmbeddedWebView(useEmbeddedWebView)` when building the public client application, and if yes, which value)

**Comment by jmprieur** [comment]
cc: @aiwangmicrosoft

**Comment by SravanthiKare** [comment]
@jmprieur 
We are using system browser(not embedded browser) specifically for this feature. .WithEmbeddedWebView(useEmbeddedWebView) value is false.

**Comment by jmprieur** [comment]
@SravanthiKare are you sure that this is not a new privacy feature of Safari? (that you would need to opt-in to?)
@brandwe @oldalton

**Comment by SravanthiKare** [comment]
@jmprieur 
I am not quiet sure on any such privacy feature on Safari in iOS 13.*
I think in iOS 13 they have added password autofill.

**Comment by bgavrilMS** [comment]
I am closing this issue because it is not an SDK issue. Please open a bug on the service, as they control the content in the browser. You can do this though the Azure Portal support pages.
