### ISSUE TITLE
[Documentation] Add customer testimonials and experiences when moving to MSAL.NET to give confidence to newer customers looking to migrate.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1768]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
Some customers are hesitant to move to MSAL.NET due to the fact that it is a very new product and does not have enough of a well known history with large partners that shows MSAL.NET's stability and reliability. Customers want to know of the past experiences of previous customers when migrating from ADAL.NET to MSAL.NET so they can predict the effort required to complete the work and what kind of stability they can expect from the product. This documentation should include the experiences of all of the customers we helped migrate.

**Comment by neha-bhargava** [comment]
Fixed in [MSAL 4.17.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.17.0)

**Comment by jmprieur** [comment]
Started in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki#testimonials
