### ISSUE TITLE
[Feature Request] Add ability to disable ADAL CacheFallbackOperations

### ISSUE THREAD

**Issue by petrochuk** [AzureAD/microsoft-authentication-library-for-dotnet#1770]
**Feature plan**
1. Measure improvement (start with baseline and explore improvements for a small and large cache sizes)
2. Flag to disable ADAL cache fallback (.WithDisableAdalCache - suggestions welcome)
  a. Include this flag in the ApplicationOptions
3. Add telemetry (in .net specific section) to let us know if this feature is used or not.

_Will not be doing:
Auto detect if adal fallback is used, if not disable after first cache call (as Bogdan suggested)_

**Customer challenge:**
Some legacy ADAL operations are very CPU and memory intensive. For example WriteAdalRefreshToken deserializes entire token cache from byte array to Json, adds item and then serializes Json back to byte array. There should be ability through application configuration to disable CacheFallbackOperations and LegacyCachePersistence for applications that do not need it

Our current work around:

`
            // Clearing old ADAL cache prior to each token request to save memory and CPU
            app.UserTokenCache.SetBeforeAccess((args) => args.TokenCache.DeserializeAdalV3(null));
`

**Comment by bgavrilMS** [comment]
I would love to implement this and even set this behaviour as default.

**Comment by jmprieur** [comment]
i agree, @bgavrilMS that we should implement it. 
What about:
`.WithSerializeAdalCache(bool? serialializeAdalV3Cache = null)`

Behavior depending on `serialializeAdalV3Cache`
| serialializeAdalV3Cache | Behavior |
|  ---- | ----- |  
| `null` |  depends on the platform (see below)  | 
| `true` |  Serializes the ADAL cache  |
| `true` |  Serializes the ADAL cache  |

I'm not sure about using `false` by default as this would be a breaking change, but we could be clever:
- serialize by default for Xamarin.iOS, Xamarin.Android, UWP where we provide cache serialization
- do not serialize for .NET Core and .NET Framework where developers need to customize token cache serialization, and throw with a meaningfull exception if `DeserializeAdalV3` and `SerializeAdalV3` are called ?

**Comment by henrik-me** [comment]
@jmprieur : Seems like your table has a small bug as there are 2 entries for true, also I don't understand null (perhaps an enum if we really need more options). 
nit: How about WithAdalCacheSerialization(false) ? 
Also we should add an attribute ensuring we fix this to be the default behavior for the next major version. Also most of our samples should set this especially for web scenarios.

**Comment by jmprieur** [comment]
Ok @henrik-me 

`.WithSerializeAdalCache(bool serialializeAdalV3Cache=false)`

**Comment by bgavrilMS** [comment]
I'm wondering if we can do something smarter here. We provide 2 methods to manipulate the ADAL cache: 

`void DeserializeAdalV3(byte[] adalV3State);`
`byte[] SerializeAdalV3();`

We can detect to see if these are called after the first cache read / write. If they are not, we can disable ADAL caching. 

How does this sound?

**Comment by bgavrilMS** [comment]
Proposing to take this in next sprint, as it is impacting perf and has been asked by several customers

**Comment by jmprieur** [comment]
@henrik-me @bgavrilMS @pmaytak 
That sounds like a good win for performance?

cc: @jennyf19 @trwalke @neha-bhargava

**Comment by henrik-me** [comment]
Let's prioritize this work as part of performance. @pmaytak .
@jmprieur, perhaps no one is using it ... some telemetry might help tell us if we can remove it completely? And perhaps we can mark these as deprecated?

**Comment by jmprieur** [comment]
@henrik-me. Yes let's start by letting developers disable it
I'm not aware of any telemetry? Are you suggestion we add some?

**Comment by henrik-me** [comment]
@jmprieur, yeah was thinking part of this work we should add telemetry as well to explore how many are actually using it (how many times do we disable it after the first run), if data says 100% then perhaps we should just disable it by default.

**Comment by henrik-me** [comment]
@jmprieur : 
I suggest for now the feature is: 
1. Flag to disable ADAL cache fallback (.WithDisableAdalCache - suggestions welcome)
2. Auto detect if adal fallback is used, if not disable after first cache call (as Bogdan suggested)
3. Add telemetry (in .net specific section) to let us know if this feature is used or not.

@pmaytak

**Comment by jmprieur** [comment]
@henrik-me @pmaytak should we also have a boolean option in the ApplicationOptions?

**Comment by jennyf19** [comment]
Do we know the performance differences between current version and disabling the ADAL cache fallback? just bypass the ADAL cache fallback to get a basic perf line and/or trying the customer work around.

**Comment by henrik-me** [comment]
@jennyf19, that's part of the task to explore.

**Comment by jennyf19** [comment]
right, i sorry, i meant like doing that now, versus later, after the implementation is done.

**Comment by pmaytak** [comment]
Makes sense. I'll work on the perf assessment next.

**Comment by pmaytak** [comment]
@petrochuk PR https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2309 has some improvements to this ADAL cache feature plus some perf measurements. Branch [pmaytak/adal-cache-fallback](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/pmaytak/adal-cache-fallback) has the changes, if you would like to pack it and try it out. Alternatively I can also provide a private Nuget package.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).

cc: @petrochuk
