### ISSUE TITLE
GetAccounts always returns 0 accounts if broker is not installed

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#1775]
If we do a acquiretoken request with broker=true, what is the exact behavior in case there is no broker installed ? 
I thought it would do the login without broker, but in the 4.11 release we notice that it fails to get a token. Is the intended behavior that it indeed fails and one should retry with broker=false?

**Comment by bgavrilMS** [comment]
Is this Android or iOS , or both?

As far as I remember, if the broker is not installed, MSAL will attempt to use a browser. Note that on Android the redirect uri might be different in this case, so you need to register 2 redirect uris. Or use  the embedded browser via `.WithUseEmbeddedWebUi(true)`.

CC @trwalke as he's looking in this general area now

**Comment by harmjonker** [comment]
We are only developing for Android at the moment and do use .WithUseEmbeddedWebUi. I will look for log fragment to show the case. We don't see it falling back to the browser.

**Comment by alexander-papen** [comment]
Before calling AqcuireTokenSilent(), we query the accounts using GetAccountsAsync()
The returned account is passed as argument to the AquireTokenSilent call.

However, GetAcountsAsync() does not provide any account, see logs:

MSAL Warning False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 28 [04/22/2020 11:10:12] (UnknownClient: 0.0.0.0) No Authenticator found on the device.
MSAL Error False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 28 [04/22/2020 11:10:12] (UnknownClient: 0.0.0.0) Android broker is not installed so no accounts will be returned.

Next an AqcuireTokenInteractive is called. 
Although the documentation says that the MSAL lib will redirect the user somehow to the installation location of the broker application,  in fact the WebView login is displayed and the user can login.
It is _'assumed'_ that the MSAL lib wil work now without broker functionality, and the account returned from MSAL lib will be stored/cached by the MSAL lib.

It is expected that the next call to query the accounts, will return the account that was previously loggedin. 
But in stead GetAccountsAsync() returns no accounts. see logs (same as above): 

MSAL Warning False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 28 [04/22/2020 11:12:49] (UnknownClient: 0.0.0.0) No Authenticator found on the device.
MSAL Error False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 28 [04/22/2020 11:12:49] (UnknownClient: 0.0.0.0) Android broker is not installed so no accounts will be returned.

**Comment by bgavrilMS** [comment]
Thanks for the details @alexander-papen - I think you are right, this is a scenario we overlooked. 

@trwalke - can we close the loop here with the Android folks? In my opinion, GetAccountsAsync should get both Authenticator and local accounts and merge them. But I do not want to reinvent the wheel...

@aiwangmicrosoft - we're struggling here to find out what is the expected behaviour in these scenarios and we could really use a spec for the scenario:

- developer configures UseBroker but broker is not installed
- what happens to GetAccounts / RemoveAccount / AcquireTokenSilent 

CC: @jmprieur @henrik-me

**Comment by bgavrilMS** [comment]
@aiwangmicrosoft  - is there any progress on this? Can you please help define expected scenario here and confirm with Android team?

**Comment by aiwangmicrosoft** [comment]
Synced offline with @trwalke - he has enough clarity to move forward with this issue and we will work together to get me up to speed on the broker and how to best augment the existing spec for brokers on Android today.

**Comment by trwalke** [comment]
released in 4.13.0
