### ISSUE TITLE
[Bug] Clicking on username to login does nothing [MSIX, Ping federate]

### ISSUE THREAD

**Issue by mjfusa** [AzureAD/microsoft-authentication-library-for-dotnet#1776]
**Which Version of MSAL are you using ?**
MSAL 4.10.0 
https://www.nuget.org/packages/Microsoft.Identity.Client/4.10.0

**Platform**
net46, with Application Packaging Project (MSIX)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
This impacts several Win32 / .NET FW 4.6 apps where we are using the Application Packaging project to distribute the app using an MSIX package.

**Config**
AAD + Ping Federation
Register test app with AAD
Include client id, directory id and redirect uri into test code 

**Repro**
Create .NET FW Consult app

```csharp
            var directoryId = "d6ff488b-0bf9-4193-aa92-c61a297ee6f4";
            var clientId = "2cdc0d2b-26f0-48b9-874b-26d7d1c02081";
            var redirectUri = "http://localhost";


            var app = PublicClientApplicationBuilder.Create(clientId)
                .WithLogging(Program.MyLoggingMethod, LogLevel.Verbose, enablePiiLogging: false, enableDefaultPlatformLogging: true)
                .WithRedirectUri(redirectUri)
                .WithAuthority(AzureCloudInstance.AzurePublic, directoryId)
                .Build();
            var accounts = await app.GetAccountsAsync();
            var authResult = await app.AcquireTokenInteractive(new string[] { "user.read" })
                .WithAccount(accounts.FirstOrDefault())
                .WithPrompt(Prompt.SelectAccount)
                .ExecuteAsync();

            var token = authResult.AccessToken;

            Console.WriteLine($"Token: {token}");
            Debug.WriteLine(token);
            Debug.Flush();
   
```

**Expected behavior**
User is able to click on user name as displayed in login web form. Access token is returned.
**Actual behavior**
User can click on user name as displayed in login web form, but nothing happens. Access token is not returned.
Note this works as expected if system browsers is used instead of MSAL webview. We can't be dependent on external web browser and don't want to change our code to get it to work in MSIX package.
Note: This only repros if Ping federation is part of auth flow.

**Comment by bgavrilMS** [comment]
Hi @mjfusa - MSAL does not control the web pages used to log the user in. MSAL just opens a browser and navigates to the authroization endpoint, where the server controls the flow. This way, the server can decide things like - is 2FA needed, password expiration flows etc. 

So this looks like a server bug and your best bet is to contact them directly (e.g. open a free support case from Azure Portal etc.). They will most likely need: 

- a Fiddler trace (which will contain correlation ID)
- or a correlation ID (details [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#correlation-id))

Let me know if this works for you. We can open an incident from our side as well, but what usually ends up happening is that the team who owns this needs more details etc. so it's better to have direct contact.

**Comment by jmprieur** [comment]
See also https://github.com/MicrosoftDocs/azure-docs/issues/49182

**Comment by mjfusa** [comment]
@jmprieur When running as MSIX, does MSAL use the UWP Token Cache Serialization?

**Comment by bgavrilMS** [comment]
Yes, by default MSAL on UWP will serialize its cache to LocalAppData. You can override that, for example serialise only in memory or to some other secure storage: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization

**Comment by mjfusa** [comment]
@bgavrilMS This may be an MSAL issue as the problem only occurs when using the embedded browser. I was able to repro differences in the login page depending on if the app is running as straight Win32 or as MSIX. See attached.
[MSAL Win32 Desktop vs same app running as MSIX packaged app.docx](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/4531937/MSAL.Win32.Desktop.vs.same.app.running.as.MSIX.packaged.app.docx)

**Comment by bgavrilMS** [comment]
There are 2 levels of caching that happen with authentication. The first one is based on HTTP cookies, and it is handled by the server that issues tokens (STS). The developer and MSAL have little control over this, you can influence this behaviour using `.WithPrompt` which you already use. The actual browser that is being used may behave differently - in the WIn32 Desktop we use the WinForms WebBrowser control. In the UWP project (the MSIX is UWP based), we use a control called WAB (windows authentication broker). WAB has been deprecated in favour of WAM, and it is in our roadmap to move to WAM, but this is a large feature to tackle and has not been scheduled yet. You can integrate with WAM directly though - see this sample on how to do it: 

https://github.com/azure-samples/active-directory-dotnet-native-uwp-wam

AFAIK, WAM does not work with live accounts.

The second level of caching is handled by MSAL - the tokens are stored in the cache and you can call `AcquireTokenSilent` to authenticate the user silently. This we have full control of. Typically the pattern of logging in is: 

```csharp
try 
{
     var accounts = await app.GetAccountsAsync();
     AcquireTokenSilent(scopes, account);
}
catch (MsalUiRequiredException)
{
   AcquireTokenInteractive()
}
```
Perhaps relying on MSAL's token cache will provide the desired experience ?

**Comment by mjfusa** [comment]
Thx @bgavrilMS - one note is that in this scenario I'm running a Win32 desktop app in an MSIX context using the [Windows Application Packaging project](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net). In this case, the desktop MSAL library is being using (not UWP). The expectation is the behavior would be the same. I believe the difference in behavior is the root cause if this issue.
A few run time differences I found:
⌂| MSIX | WIn32
-- | -- | --
x-client-OS | Microsoft   Windows NT 10.0.18362.0 | Microsoft   Windows NT 6.2.9200.0
User Agent (diff) | Windows   NT 10.0 | Windows   NT 6.2
INetCache | C:\Users\mikefra\AppData\Local\Packages\dc2ede0c-08a2-4c30-8a65-1188abdca2ce_4qsx37q5cykvg\AC\INetCache\CT74JT28\ux.old.converged.login.pcore.min_9_8sd1spckud1tj2ezftqq2[1].js | C:\Users\mikefra\AppData\Local\Microsoft\Windows\INetCache\IE\H7V0VFOD\ux.old.converged.login.pcore.min_9_8sd1spckud1tj2ezftqq2[1].js

Repro project here: https://github.com/mjfusa/MSIX-SSO-IssueSample

**Comment by mjfusa** [comment]
[proposed Label] AppConsult

**Comment by neha-bhargava** [comment]
@mjfusa I cloned the sample you created and I could not see a difference in the behavior between IssueSample and IssueSample-Installer. Do you still see a difference in behavior? Please confirm.

**Comment by neha-bhargava** [comment]
Closing this due to no response. Please reopen if the issue is still there.

**Comment by mjfusa** [comment]
@neha-bhargava Yes - this still repros for me. I don't see MSAs (e.g. mike.francis@live.com) when run as MSIX-Installer.

**Comment by mjfusa** [comment]
@neha-bhargava  Can you please reopen?

**Comment by kalyankrishna1** [comment]
@mjfusa , please capture the interaction between your app setup and the AAD STS in a  tool like fiddler and share with us. The setup you have will require quiet a bit of effort for us to set up to reproduce and this will delay resolution efforts . 
The STS response and rendering should be throwing a few errors/warnings but most importantly has correrelation ids that we need to start troubleshooting.

**Comment by JamesHHoustonII** [comment]
I am having the same issue the code copied and pasted has ask for escape characters but that leads to a different error about the name of my application. This error is preventing me from moving forward with app development. 

![CacheFilePath error 1](https://user-images.githubusercontent.com/10920521/88405328-b8f2df80-cd94-11ea-9a82-e1980cbc3758.jpg)

![CacheFilePath error 2](https://user-images.githubusercontent.com/10920521/88405356-c27c4780-cd94-11ea-8962-7b4943b3de6d.jpg)

**Comment by dbanta6** [comment]
Hi all, just wondering if there is any further updates on this issue.  Thanks!

**Comment by bgavrilMS** [comment]
The webview used by MSAL is very old and javascript errors will occur. Recomendation is to move to WAM: https://aka.ms/msal-net-wam
