### ISSUE TITLE
[Feature Request] PKCE should use 96 random bytes instead of 43 for added security

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1777]
**Is your feature request related to a problem? Please describe.**
Defence in depth

**Describe the solution you'd like**
MSAL's PKCE implementation uses a code verifier of 43 bytes. This is the minimum described in the spec RFC 7636.
To benefit from added entropy, MSAL should use the maximum described in the spec, i.e. 96 bytes

For more details see the comments on this PR https://github.com/microsoft/Git-Credential-Manager-Core/pull/102/files

**Comment by henrik-me** [comment]
@bgavrilMS : About a year ago we had similar alignment for the state parameter. Should be a relatively simple API PR to ensure all libraries aligns.

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
