### ISSUE TITLE
[Bug] MsalClientException UserMismatchSaveToken sometimes thrown in web apps

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1778]
**Which Version of MSAL are you using ?**
4.11

**Platform**
.net

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [x] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
This affects apps in production

**Repro**

UserMismatchSaveToken  error code sometimes happens.

**Comment by bgavrilMS** [comment]
Fixed by https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1769

**Comment by neha-bhargava** [comment]
Fixed in [MSAL 4.12.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.12.0)
