### ISSUE TITLE
App targeting Android 8.1 not possible

### ISSUE THREAD

**Issue by tomcurran** [AzureAD/microsoft-authentication-library-for-dotnet#1785]
**Which Version of MSAL are you using ?**
MSAL v4.12

**Platform**
Xamarin.Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
Reproducible in the XamarinDev.Android dev app included in this library.

**Repro**
Use XamarinDev.Android dev app and set TargetFrameworkVersion to v8.1. 

As a full repro, I have updated the app [here](https://github.com/tomcurran/microsoft-authentication-library-for-dotnet/commit/f100238ea9b804ab7800ee222c58b7fe1796f021) to use the nuget package. To get the app to compile comment out `AuthenticationContinuationHelper`. Run the app and press acquire. You will get an exception PlatformNotSupportedException from netstandard13 dll. Log message added below.

**Expected behavior**
Android target when compiling app with Android v8.1.

**Actual behavior**
netstandard targetted when compiling app with Android v8.1. Any Android specific APIs such as `AuthenticationContinuationHelper` are not available compile time.

**Additional context/ Logs / Screenshots**

> [Error] - (True) MSAL 4.12.0.0 MSAL.CoreCLR N/A [04/27/2020 10:42:45 - 971f40e1-6f6d-4b2a-afd9-a1594121ee73] (UnknownClient: 0.0.0.0) System.PlatformNotSupportedException: Possible Cause: If you are using an XForms app, or generally a netstandard assembly, make sure you add a reference to Microsoft.Identity.Client.dll from each platform assembly (e.g. UWP, Android, iOS), not just from the common netstandard assembly
  at Microsoft.Identity.Client.Platforms.netstandard13.WebUIFactory.CreateAuthenticationDialog (Microsoft.Identity.Client.UI.CoreUIParent parent, Microsoft.Identity.Client.Core.RequestContext requestContext) [0x00000] in <e2e6292129c541ebb5ea25ff779992ab>:0 
  at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.CreateWebAuthenticationDialog () [0x0006c] in <e2e6292129c541ebb5ea25ff779992ab>:0 
  at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync (System.Threading.CancellationToken cancellationToken) [0x00011] in <e2e6292129c541ebb5ea25ff779992ab>:0 
  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync (System.Threading.CancellationToken cancellationToken) [0x00178] in <e2e6292129c541ebb5ea25ff779992ab>:0 
  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x000fa] in <e2e6292129c541ebb5ea25ff779992ab>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x0017e] in <e2e6292129c541ebb5ea25ff779992ab>:0  - True
Possible Cause: If you are using an XForms app, or generally a netstandard assembly, make sure you add a reference to Microsoft.Identity.Client.dll from each platform assembly (e.g. UWP, Android, iOS), not just from the common netstandard assembly

**Comment by tomcurran** [comment]
Seems related to #941

**Comment by bgavrilMS** [comment]
Hi @tomcurran - although this is not a great user experience, it is expected. Can your app not use Android SDK 9? This is not the same as the runtime Android version, which will not be impacted - i.e. your app can still target old versions of Android. Runtime != SDK.


What's happening is that MSAL is multi-targetted and supports Android 9 and NetStandard 1.3. Because your application uses Android SDK 8.1, NuGet makes the decision to reference MSAL.Netstandard DLL, which does not define AuthenticationContinuationHelper or any other Android objects.

**Comment by tomcurran** [comment]
@bgavrilMS Thanks for responding so quickly. The app I'm working on could use TargetFrameworkVersion 9.0. However, as is common with enterprise apps, they are large and it can require significant effort to make changes like this. On experimentation, there were additional issues that needed to be resolved to target 9.0.

Libraries like [Xamarin.Essentials](https://www.nuget.org/packages/Xamarin.Essentials) appear to be set up to have multiple Android targets. Is that something that you would consider or using a lower target?

**Comment by bgavrilMS** [comment]
We have it on our roadmap to add support for Android 10, and keep supporting Android 9. We used to support Android SDK 8, but were forced to give that up some time ago. I believe the last version of MSAL that supports Android 8 is https://www.nuget.org/packages/Microsoft.Identity.Client/2.7.1;

**Comment by tomcurran** [comment]
Ok, thanks Bogdan. I'll close the issue then.
