### ISSUE TITLE
[Bug] When ValidateAuthority is false, bypass instance discovery call

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#1791]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

Latest

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**

**Repro**

```csharp
IPublicClientApplication pca = PublicClientApplicationBuilder
                            .Create(s_clientIdForPublicApp)
                            .WithAuthority(new Uri("https://login.fake.com/common/"), false)
                            .WithLogging(Log, LogLevel.Verbose, true)
                            .WithRedirectUri("http://localhost") // required for DefaultOsBrowser
                            .Build();
```

**Expected behavior**
Should bypass the instance discovery call when flag is passed as false

**Actual behavior**
Still validates the authority and errors out with "invalid_instance" error code.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by henrik-me** [comment]
When fixing this, utests should be improved to cover these scenarios, possibly also an addition to e2e testing.

**Comment by bgavrilMS** [comment]
We have an E2E test that verifies behaviour when validate=true, should be easy to repurpose for validate=false as well.
