### ISSUE TITLE
[Investigate] Investigate performance of broker authentication scenarios and Identify areas for improvment

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1796]
**Which Version of MSAL are you using ?**
Latest

**Platform**
xamarin android, xamarin iOS

**What authentication flow has the issue?**
all brokered authentication flows

We need to investigate the performance of the authentication scenarios on Android and iOS to determine how long each section of the authentication flow takes. We can use this data to look for areas of opportunity to improve performance for the scenarios.

We should also compare the performance of ADAL and MSAL to get a baseline of how MSAL compares to ADAL today.

**Comment by bgavrilMS** [comment]
When acquiring a token silently, MSAL goes directly to the broker. However, MSAL should first try to see if there is an access token in its cache first. MSAL's local cache should be significantly faster than talking to the broker. 

We should implement / fix https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1820 before measuring perf.

**Comment by bgavrilMS** [comment]
Added measuring logic, now waiting for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1820 to be fixed as it should improve perf ...

**Comment by henrik-me** [comment]
planning: Next step is to find next improvements

**Comment by neha-bhargava** [comment]
With same scope as used in acquire token interactive with broker and with force refresh true time taken to acquire token silent:

**AcquireTokenSilentViaBrokerAsync in 909 ms**
ValidateBrokerRedirectURI in 8 ms
**InitiateBrokerHandshakeAsync in 383 ms**
IsBrokerInstalledAndInvokable in 10 ms
VerifyAuthenticator in 9 ms
IsBrokerInstalledAndInvokable in 10 ms
VerifyAuthenticator in 8 ms
**GetAccountsAsync in 861 ms**
**InitiateBrokerHandshakeAsync in 364 ms** 
IsBrokerInstalledAndInvokable in 15 ms
VerifyAuthenticator in 13 ms
IsBrokerInstalledAndInvokable in 18 ms 
VerifyAuthenticator in 15 ms 

Observation: InitiateBrokerHandshakeAsync is consuming a lot of time.

**Comment by bgavrilMS** [comment]
How long does this take for MSAL.Android? I doubt we can go faster than them :)

**Comment by bgavrilMS** [comment]
Won't fix.
