### ISSUE TITLE
Deprecation of login.microsoftonline.com

### ISSUE THREAD

**Issue by plemm98** [AzureAD/microsoft-authentication-library-for-dotnet#1803]
### Documentation Related To Component:
Set redirect URLs to b2clogin.com for Azure Active Directory B2C
https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin

### Please check those that apply

- [X] documentation needs clarification
- [X ] needs example

### Description Of The Issue
I spend an hour reading this issue : "AD B2C - tenant.b2clogin.com is not providing same abilities as login.microsoftonline.com for existing AD B2C code"

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1771

After reading this post, my understanding is that the following code is using the Graph to retrieve an access token for a specific application.

            try
            {
                authContext = new AuthenticationContext(Authority);
                clientCredential = new ClientCredential(ClientId, AppKey);
                var result = await authContext.AcquireTokenAsync(ExternalAppResourceId, clientCredential);
                return result.AccessToken;
            }
            catch (Exception)
            {
            }

The authority in the previous sample is using "login.microsoftonline.com". My undertsanding is that, base on "JasSuri" comment, the "login.microsoftonline.com" that i'm using is not gonna be deprecated on December 4 2020 (https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin). The one that is beeing deprecated is the one using a B2C "POLICY ID". So, this powershell to obtain an access token for an application should still work in 2021, because it's not using a "Policy ID"? 

$body=@{
    client_id="*******************************************"
    client_secret="****************************************"
    scope="https://graph.microsoft.com/.default"
    grant_type="client_credentials"
}

$tenantId="5a2a681a-1***5-4**1-a43b-fd0***04d82c6"

Invoke-WebRequest -Uri "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token" -ContentType "application/x-www-form-urlencoded" -Body $body -Method Post

I hope i'm right. Otherwise, can you provide me an example showing me how to do it? Or maybe, explain me what i'm missing!

**Comment by bgavrilMS** [comment]
I think you are right. The code sample you are showing is of ADAL fetching token on **behalf of an application** (based on the certificate). This endpoint will continue to be supported and that sample will continue to work.

The endpoint that is deprecated is "login.microsoftonline.com" in the context of authentication of users through the B2C policies / experiences. There you should use the "b2clogin" alternative. 

I believe the reason for this was that there were too many cookies associated with  "login.microsoftonline.com" and was crashing people's browsers. Solution was to route all B2C traffic via this new authority.

**Comment by jennyf19** [comment]
@plemm98 what @bgavrilMS said plus customers didn't want to have "microsoft" anywhere in the login url, so b2clogin is the alternative or a custom domain. 

Does [this documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin) help you moving from login.onmicrosoft.com to *.b2clogin.com?

**Comment by jennyf19** [comment]
closing, but please reopen if needed @plemm98
