### ISSUE TITLE
[Bug] The broker changes the correlation ID

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1805]
**Which Version of MSAL are you using ?**
4.13

**Platform**
iOS (possibly Android as well)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive / Silent + Broker

Other? - please describe;

**Is this a new or existing app?**
Prod app

**Repro**

Customer encountered this in logs: 

[0:] [5/5/2020 2:50:59 PM].[ThreadID 5]:[MSAL: Warning: (True) MSAL 4.13.0.0 MSAL.Xamarin.iOS 13.3.1 [05/05/2020 21:50:59 - f54df534-7661-43ac-b805-ca82bd235fff] (UnknownClient: 0.0.0.0) Returned correlation id 'f117a4ac-95b1-xxxxxx' does not match the sent correlation id 'f54df534-7661-xxxx']

**Expected behavior**
Correlation IDs need to be stable for teams to be able to track outages. 

**Actual behavior**
The broker changed the correlation ID  

Note: this is a supportability issue

**Comment by bgavrilMS** [comment]
It is possible that this is external.

**Comment by bgavrilMS** [comment]
We should test that AcquireTokenInteractive and AcquireTokenSilent preserve the correlation ID that is passed via `.WithCorrelationId`

**Comment by trwalke** [comment]
Resolved in [4.15](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.15.0)
