### ISSUE TITLE
how to refresh the access token without using refresh token?

### ISSUE THREAD

**Issue by sangavi008** [AzureAD/microsoft-authentication-library-for-dotnet#1811]
Our server based application is using basic authentication, planning to migrate to Oauth method.
Where in my code i m getting the username and password of the users and generating the access token. and doing sync of outlook appointments. 
using PublicClientApplicationBuilder ,

app = PublicClientApplicationBuilder.Create(app_id)
                .WithAuthority(AzureCloudInstance.AzurePublic, tenant_id)
                .Build();
            AuthenticationResult result = null;          
                var securePassword = new SecureString();
                foreach (char c in Password)        // you should fetch the password keystroke
                    securePassword.AppendChar(c);

                result = await app.AcquireTokenByUsernamePassword(ewsScopes,
                                                                 user,
                                                                securePassword)
                                 .ExecuteAsync();

Using this above code, i am able to validate the users and generating the token and sync is also working.

But the problem is after 1 hr program is throwing the 401 authentication issue. Because access token expires every 1 hr. 
I wanted to refresh the access token somehow to remove this error and sync operation should continue to work. I was planning to increase the lifetime of access token by token policy which is mentioned in the microsoft blog. https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes 
But After May 30, 2020 no new tenant will be able to use Configurable Token Lifetime policy to configure session and refresh tokens. The deprecation will happen within several months after that, which means that we will stop honoring existing session and refresh tokens polices. You can still configure access token lifetimes after the deprecation. 
So what is the way to refresh the access token after 1 hr or is there any way to set the lifetime to 1 day.``

**Comment by bgavrilMS** [comment]
MSAL refreshes tokens for you, but you need to call `AcquireTokenSilent` before calling `AcquireTokenUsernamePassword` or `AcquireTokenInteractive`.

All our samples [show this](https://docs.microsoft.com/en-gb/azure/active-directory/develop/sample-v2-code).

The Username/Password sample code: https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2/blob/master/up-console/PublicAppUsingUsernamePassword.cs#L68

**Comment by sangavi008** [comment]
Thank you for your quick response. 
What my understanding is, first goes to AcquireTokenUsernamePassword  and generate the token after one hr then it goes to AcquireTokenSilent to refresh the access token.
I have one point to clarify here. Since my application is Server based application. Initially i ask for user credentials and create the instance with generated token for Exchange  and later on it do the background sync to outlook [office365].
since sync operation is a background job in my application. for every hour do i need to call this method explicitly to generate the token? or it does in the background automatically to generate the access token ?

**Comment by bgavrilMS** [comment]
I am not sure I understand the architecture of your application. If you application is server side, you can use a secret or a certificate to obtain tokens on behalf of the application itself. Have a look at the daemon app samples. If you have a website, have a look at the web app / web api samples. 

But to answer your question - MSAL does not do anything in the background, so you have to call it. `AcquireTokenSilent` does the following: 

- checks the token cache (which by default is in memory, but you can persist it)
- if an access token is found and it has more than 5 min until expiry - return it
- otherwise, find the refresh token and use it to get a fresh access token
- if no refresh token is found, throw MsalUiRequiredException. This is how you know that you need to call `AcquireTokenByUsernamePassword`

**Comment by sangavi008** [comment]
I have reviewed the link. As you suggested, Instead of taking credentials from your user, i can introduce the secret key concept in my application which is feasible also.
But only point i stuck is refreshing access token in the background.
I can give you the overview of my application:
Application acts like a middle man between system which maintain the user data and Exchange [Office 365]. My application which helps to sync the user data between this.So Sync is a continuous background job. In scenario, calling the method every one hr to generate the new access token would not be the feasible option and it affect the performance also.So would you suggest some way which can suit in this case.

**Comment by bgavrilMS** [comment]
@kalyankrishna1 - can you help, I do not know what to suggest here...

**Comment by bgavrilMS** [comment]
@TiagoBrenck - could you take a look at this scenario please?

**Comment by TiagoBrenck** [comment]
@sangavi008 how often would this sync operation be triggered? You said that every hour is not feasible, so how long would that be?

Also, if using client credentials is a possibility for you, then I think that could be the solution depending on how often this operation will be called.

**Comment by sangavi1001** [comment]
@TiagoBrenck, my application acts like middleman  designed to do the sync operation between outlook and user data maintained system. its like  background job so whenever the appointment created by the users it triggers. 
As per the current code it calls the access token generation method initally while I start the application service. After 1hr token expires and failing the background  sync operation . Again if I restart the service of the application then it is working.. And also application is designed to restart the services every 24hrs. So I am just checking the way how can I retain the access token for 24 hrs. I came across the microsoft blog about configuration of access token policies.  https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes After 30th May it is going to be deprecate.so I am not sure I can go with this approach. 
Hope I clarified about the scenario. Could you please suggest some way to retain the access token for 24 hrs.?

**Comment by kalyankrishna1** [comment]
To change the lifetimes of the tokens please refer to[ Configure authentication session management with Conditional Access](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime)

**Comment by sangavi008** [comment]
@kalyankrishna1 As per the link i tried with Sign in frequency method i have made the configuration changes in Azure. First 1 hr it worked properly but after 1 hr it failed and received the authentication error. Would you advise more ?

**Comment by jmprieur** [comment]
Closing as this was answererd
