### ISSUE TITLE
Test Android X

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1813]
After this [PR merges to master](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1745), we need to run a release build to test the following:

- [ ] Android 9 + interactive/silent auth
   - [ ] Embedded webview
   - [ ] System browser
- [ ] Android 10 + interactive/silent auth
   - [ ] Embedded webview
   - [ ] System browser
- [ ] Broker Android 9 + interactive/silent auth
- [ ] Broker Android 10 + interactive/silent auth
- [ ] Create a Xamarin Android app from scratch w/new package
  - [ ] Embedded webview
  - [ ] System browser
- [ ] Update Xamarin samples 
    -  [ ] [B2C Xamarin](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native)
    -  [ ] [Xamarin](https://github.com/Azure-Samples/active-directory-xamarin-native-v2)
- [ ] Send the build to a few customers who are interested in testing before official release

**Comment by bgavrilMS** [comment]
I copied the tests to the original issue as I've merged the PR.
