### ISSUE TITLE
Microsoft.Identity.Client.MsalException: An exception has occurred

### ISSUE THREAD

**Issue by chrisekobo** [AzureAD/microsoft-authentication-library-for-dotnet#1814]
Version: MSAL 4.10.0
Platform: Xamarin Forms

Sometimes I receive Microsoft.Identity.Client.MsalServiceException: AADB2C: An exception has occurred. Correlation ID: 3371da50-f0a1-4351-b4ae-a38835ec5437 Timestamp: 2020-05-10 07:54:41Z in my logs.
I'm using standard SignUpInPolicy user flow to login users of my app and in the most cases login works perfectly. But sometimes this error occures with no more details.

**Comment by jennyf19** [comment]
@chrisekobo which identity provider(s) are you targeting when this happens? If you can provide a more recent correlation id, we can try to look it up in the b2c server and see what happened.

**Comment by chrisekobo** [comment]
This is the most recent correlation id. We don't have a new one in our logs :(. In our app we are using three identity providers: local account, google, facebook. In our logs at this moment we don't have any information about idp user was using.

**Comment by bgavrilMS** [comment]
It would be great to get more logs if you wish us to investigate what happens on the SDK side. 

If this is a server-side issue (and it looks like it is), the best would be to open a support case - afaik these are free. The correlation ID and the date of when this happened should be enough for those guys to investigate what happened.

**Comment by chrisekobo** [comment]
@bgavrilMS  you mean to open a support case or AD B2C in Azure? I'm afraid there are not free. To open a technical case for my subscription I should upgrade my plan to paid.

**Comment by bgavrilMS** [comment]
I'm fairly sure you can open a free support case if you go to "Azure Active Directory" (not the B2C one) ... 
![image](https://user-images.githubusercontent.com/12273384/82046426-c317a400-96a8-11ea-969a-945d7fbc4a70.png)

If you have more application logs I can take a look to see if the problem is in the SDK. But if you application only sometimes encounters this issue, it looks more like a service bug.

**Comment by chrisekobo** [comment]
I have no more logs connected to this error. Maybe it is a service bug as you suggest. 
We will add more logging to our app to have more information in the future.

Thank you  @ennyf19  and @bgavrilMS  for your help.

**Comment by jennyf19** [comment]
@chrisekobo Here's how to add [msal logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#at-a-glance) which will include the correlation id. If you get one, feel free to email me and we can see if the b2c team can help.

**Comment by chrisekobo** [comment]
@jennyf19  I'll use msal logs. LogLever Error will be enough for you to to investigate in the future? At this momemnt I don't want to set LogLevel to Info because Iwill put these logs for every user in one centralized place and I don't want to have a mess of logs.

**Comment by Skirtek** [comment]
@jennyf19 Should we provide you logs with LogLever Info or Error?

**Comment by bgavrilMS** [comment]
@Skirtek - if you can set the LogLevel to Verbose when you repro the issue, that will give us the most info. 

If you can set the "Pii" flag to true that would be better - as the exception messages are stripped out otherwise.

**Comment by Skirtek** [comment]
@bgavrilMS Thank you for your response! Could you tell me what is minimum level of logging which will be valuable for you to provide answer? It will be problematic for us to store that much logs somewhere.

**Comment by bgavrilMS** [comment]
I think Info would be enough until you can repro the issue, then you can stop collecting logs.

**Comment by jennyf19** [comment]
@Skirtek Info is enough, as @bgavrilMS said, we just need the correlationId.

**Comment by chrisekobo** [comment]
I guees that not only correlation id :) because correlation id was provided by us at the initial post of this issue :)

**Comment by jennyf19** [comment]
@chrisekobo true...good point. we just need a more recent one.
