### ISSUE TITLE
[Bug] Missing documentation and sample on how to fallback to system webview if broker is not present

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1822]
**Which Version of MSAL are you using ?**
4.13

**Platform**
android

**Repro**

1. Configure the broker, including a redirect uri
2. Use a device without broker

**Expected behavior**
The system web view should be used by MSAL because the broker is not present

**Actual behavior**
Developers cannot use the system web view because of redirect uri mismatch (redirect URI for broker is different than for SWV). 

**Possible Solution**
Talking to Android folks, it looks like there is a solution that is based on using intent filters.

**Comment by trwalke** [comment]
Resolved in [4.15](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.15.0)
