### ISSUE TITLE
Provide more accurate Windows OS information in client info headers

### ISSUE THREAD

**Issue by onsubmit** [AzureAD/microsoft-authentication-library-for-dotnet#1824]
**Is your feature request related to a problem? Please describe.**
This feature request is in response to a Microsoft internal customer-reported [incident](https://icm.ad.msft.net/imp/v3/incidents/details/185949148/home). The customer noticed that when making requests on Windows Server 2012, in the sign-in activity logs, they would see OS = Windows 8 instead. After internal discussion, it was determined this was due to MSAL.NET using `Environment.OSVersion.ToString();` to report the OS version, which returns the exact same value for Win8 and Win2K12. [Source](https://docs.microsoft.com/en-us/windows/win32/sysinfo/operating-system-version).

`Environment.OSVersion` is also not a reliable way to accurately determine the real OS. The recommended approach is to use the [version helper APIs](https://docs.microsoft.com/en-us/windows/win32/sysinfo/version-helper-apis).

**Describe the solution you'd like**
MSAL.NET should follow the recommendations in the docs to more accurately report the OS to avoid confusing downstream effects.

**Describe alternatives you've considered**
None

**Additional context**
ping anyoung@microsoft for more context

**Comment by jennyf19** [comment]
Thanks for the info @onsubmit

**Comment by jmprieur** [comment]
Thanks @onsubmit !

**Comment by henrik-me** [comment]
@onsubmit : can you pls. specify exactly what you would like MSAL to return for each of the platforms of interest?

**Comment by onsubmit** [comment]
@henrik-me sent you mail internally

**Comment by bgavrilMS** [comment]
We also use this logic wrongly in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1849
Fix should not be difficult.

**Comment by jmprieur** [comment]
See also information in the duplicate https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2303

**Comment by bgavrilMS** [comment]
This has been fixed in MSAL 4.30
