### ISSUE TITLE
Create Xamarin forms dev sample app for manual testing (iOS/Android/UWP)

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#183]
Create Xamarin forms dev sample app for manual testing (iOS/Android/UWP). See iOS sample app for feature reference.

**Comment by SomkaPe** [comment]
We need to add dev sample apps for the following -
1) Xamarin Forms (iOS, Android and UWP)
2) Desktop App

**Comment by kpanwar** [comment]
@SomkaPe - Lets close this issue after your next PR. I think the app is in great shape and any more changes would simply warrant as enhancements.
