### ISSUE TITLE
[Bug] Username/password field doesn't allow copy/paste with sign-in dialogue on MacOS

### ISSUE THREAD

**Issue by jwosty** [AzureAD/microsoft-authentication-library-for-dotnet#1835]
**Which Version of MSAL are you using ?**
Microsoft.Identiy.Client 4.13.0

**Platform**
Xamarin.Mac

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
The app is in production

**Repro**
Try to paste a password into a login flow and notice it bleeps at you and doesn't let you do it, forcing you to type it out by hand. This is problematic for anyone who uses a password manager and has long randomly-generated passwords.

**Expected behavior**
Clipboard password should now be pasted into the password field. This works on Windows.

**Actual behavior**
Username/password field doesn't allow copy/paste.

**Comment by jennyf19** [comment]
@jwosty Thanks for the info. MSAL does not control the UI dialogue that is presented by the authorization server. I'll try to find the right person to answer this. appreciate you bringing it up.

**Comment by jwosty** [comment]
@jennyf19 thank you, I appreciate that

**Comment by jennyf19** [comment]
@jwosty talked w/the MacOS UI guys, and they say the page renders a simple textbox and there is no logic to intercept the prevent the user attempting to paste in a password. It could be environmental, such as the app, platform, or OS.
Also, if you can provide a video of the experience, that would be helpful and a zip file or link to repro code that we can try out for ourselves.
Feel free to email me any of the above, or link here in the issue (just be aware of linking sensitive info). jeferrie@microsoft.com

**Comment by jennyf19** [comment]
@jwosty what's the status on this one? feel free to close if it's been resolved. thanks.
