### ISSUE TITLE
[Bug] MSAL Xamarin.iOS is freezing and timing out during interactive authentication.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1836]
**Which Version of MSAL are you using ?**
4.13

**Platform**
xamarin iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL, but started seeing this issue

A customer is reporting an issue with interactive authentication on Xamarin iOS which started occuring recently in their existing application. The customer has found a potential solution and is asking us to investigate and provide feedback on the workaround below.
From Customer:

> Customers app has recently started to have an issue with only iOS ( about 2 weeks ago but has been in production for over 6 months ) -- works just fine in Android.  This is not a B2C application.  The issue they are having is it appears that when the user is attempting to sign-in on an iOS device, the user just gets a white screen and the app appears to freeze.  They do eventually get a timeout 

**Repro**

**Expected behavior**
Application shows the sign in screen during interactive authentication and allows the user to sign in successfully

**Actual behavior**
UI Freezes and eventually the authentication request times out with the following error:

> Microsoft.Identity.Client.MsalServiceException:** 'Request to the endpoint timed out.'MSAL logging is showing this information: ( earlier logs removed for the sake of space ):
Thread started:  #42[0:] [5/5/2020 2:51:01 PM].[ThreadID 39]:[MSAL: Warning: (False) MSAL 4.13.0.0 MSAL.Xamarin.iOS 13.3.1 [05/05/2020 21:51:01 - f54df534-7661-43ac-b805-ca82bd235fff] (UnknownClient: 0.0.0.0) Refreshing the RT failed. Is AAD down? True. Is there an AT in
 the cache that is usable? False][0:] [5/5/2020 2:51:01 PM].[ThreadID 39]:[MSAL: Warning: (False) MSAL 4.13.0.0 MSAL.Xamarin.iOS 13.3.1 [05/05/2020 21:51:01 - f54df534-7661-43ac-b805-ca82bd235fff] (UnknownClient: 0.0.0.0) Failed to refresh the RT and cannot use existing AT (expired or
 missing).][0:] [5/5/2020 2:51:02 PM].[ThreadID 39]:[pii-Start*************************************************][0:] [5/5/2020 2:51:02 PM].[ThreadID 39]:[MSAL: Error: (True) MSAL 4.13.0.0 MSAL.Xamarin.iOS 13.3.1 [05/05/2020 21:51:02 - f54df534-7661-43ac-b805-ca82bd235fff] (UnknownClient: 0.0.0.0) MSAL.Xamarin.iOS.4.13.0.0.MsalServiceException:ErrorCode: request_timeoutMicrosoft.Identity.Client.MsalServiceException: Request to the endpoint timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.  at System.Net.Http.NSUrlSessionHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x001d4] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/Foundation/NSUrlSessionHandler.cs:462
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts)
 [0x0017e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:506
  at Microsoft.Identity.Client.Http.HttpManager.ExecuteAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, System.Net.Http.HttpMethod method)
 [0x000c5] in <faf341e55f3845358612c4aad282b8f1>:0   at Microsoft.Identity.Client.Http.HttpManager.ExecuteWithRetryAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, System.Net.Http.HttpMethod
 method, Microsoft.Identity.Client.Core.ICoreLogger logger, System.Boolean doNotThrow, System.Boolean retry) [0x0013b] in <faf341e55f3845358612c4aad282b8f1>:0

**Possible Solution**
From customer: 

> I believe I uncovered the issue… MSAL provides the ability to inject an alternate Message Handler.. So, the code I used to do that is:
```CSharp
//this is the Workaround to allow iOS to work without a timeout. Builder is the PublicClientApplicationBuilder
if (Device.RuntimePlatform == Device.iOS)
            {
                builder = builder.WithHttpClientFactory(new IosMsalHttpClientFactory());
            }
 ```
 

> Simple implementation of MsalHttpClientFactory to new up the managed handler instead of the native handler..

 ```CSharp
    public class IosMsalHttpClientFactory : IMsalHttpClientFactory
    {
        public HttpClient GetHttpClient()
        {
           return new HttpClient(new HttpClientHandler());
        }
    }
```

> This immediately fixed the problem and we have not seen a timeout yet. Early days but every request to no requests timing out seems like a good bet..
I had a feeling that NSUrlSessionHandler is not stable after I had a problem with another internal component that used the native handler posting data back to our backend.. of the
 payload was over 100,000 bytes (approx.) the post would fail with a cancellationexception… I know that the Xamarin team recommend using NSUrlSessionHandler but in these two cases it would appear that it has become unstable in later releases of (I assume) Xamarin.ios??
 because our last production version did not have this issue which would have been built on an older version of Visual Studio..

**Comment by bgavrilMS** [comment]
I propose to close this. If we have other reports of this happening, we should consider moving away from the Xamarin recommended native http handler to the managed http handler.

**Comment by smalgin** [comment]
I have this happening when starting app in emulator or on device after significant delay(in my case it was about 2 weeks break).
First startup takes forever, then it works as expected for a while.

Timeouts always will happen, it's inevitable so we need to design our code to manage them properly.

First, add (maybe configurable) timeout to http client via factory method:

   ```
public class MsalHttpClientFactory : IMsalHttpClientFactory
    {
        public HttpClient GetHttpClient()
        {
            var handler = new HttpClientHandler();
            var client = new HttpClient(handler);
            client.Timeout = TimeSpan.FromSeconds(5);
            return client;
        }
    }
```
Then use  .WithHttpClientFactory(new MsalHttpClientFactory())

That's probably the safest way to work around this issue. If you can wait, wait. If you have UI, do not wait more than 5 seconds.
If you have to wait more than 5 seconds, use 'loading' page.
