### ISSUE TITLE
[Bug] wrong client type in the documentation of ConfidentialClientApplicationBuilder functions

### ISSUE THREAD

**Issue by csadam** [AzureAD/microsoft-authentication-library-for-dotnet#1839]
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client v4.13.0

**Platform**
.net

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [x] Authorization code
    * [x] OBO
* Web API
    * [x] OBO

**Repro**

View the documentation of the **Return Value** for [ConfidentialClientApplicationBuilder.Create(String) Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplicationbuilder.create?view=azure-dotnet).  
 View the documentation of **Parameters** and **Return Value** for [ConfidentialClientApplicationBuilder.CreateWithApplicationOptions(ConfidentialClientApplicationOptions) Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplicationbuilder.createwithapplicationoptions?view=azure-dotnet).

**Expected behavior**
The description of the **Return Value** should be: 

> A ConfidentialClientApplicationBuilder from which to set more parameters, and to create a confidential client application instance

The description of the **Parameters** should be: 
> Confidential client applications configuration options

**Actual behavior**
The description of the **Return Value** currently is: 
> A ConfidentialClientApplicationBuilder from which to set more parameters, and to create a public client application instance

The description of the **Parameters** currently is: 
> Public client applications configuration options

**Possible Solution**
Change the "`public client`" to "`confidential client`" in the documentation of these two functions. In `src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs` at lines 29, 31 and 52.

**Comment by jennyf19** [comment]
Thanks @csadam nice catch.
