### ISSUE TITLE
Applications consuming MSAL should be unit-testable

### ISSUE THREAD

**Issue by duncanpMS** [AzureAD/microsoft-authentication-library-for-dotnet#184]
Testability is an important part of the developer experience. Developers who use the MSAL package in their applications should be able to unit test those applications e.g. to test that their app correctly handles obtaining tokens/MSAL exceptions.

Developers should be able to mock out calls to the MSAL components so they can simulate success and failure cases.

**Comment by kpanwar** [comment]
This is a non-goal of the library to offer interfaces for unit testing. Every interface or public non-sealed class offers an extensibility point that cannot be scaled as an API surface. There are nuget packages that offer a wrapper over Adal to do so. I would encourage the community to do the same for MSAL.
