### ISSUE TITLE
Keep Xamarin dependencies updated in MSAL

### ISSUE THREAD

**Issue by joemc3** [AzureAD/microsoft-authentication-library-for-dotnet#1841]
I am running a Xamarin Forms project and like to keep it updated, but the dependencies on Identity Client and other packages are out of sync.  I have to keep some of my dependencies back many versions.  The specific offending dependency in this case is  Xamarin.Android.Support.Collections

Microsoft.Identity.Client:
Microsoft.Identity.Client 4.14.0 -> Xamarin.Android.Support.CustomTabs 28.0.0.1 -> Xamarin.Android.Support.Collections (= 28.0.0.1)

One conflict (amongst others)
Xamarin.Forms.Maps 4.6.0.800 -> Xamarin.Android.Support.v4 28.0.0.3 -> Xamarin.Android.Support.Media.Compat 28.0.0.3 -> Xamarin.Android.Support.VersionedParcelable 28.0.0.3 -> Xamarin.Android.Support.Collections (= 28.0.0.3)

Is it possible to update to 28.0.0.3 Xamarin Android dependencies?  Or at least >= 28.0.0.1?

The only other alternative is keeping my project packages woefully old.

Thanks!

**Comment by jennyf19** [comment]
Thanks @joemc3 Feel free to propose a PR if you want.

**Comment by bgavrilMS** [comment]
Focus is now on Maui. Please propose PR and we will help if it is still an issue.
