### ISSUE TITLE
[Question] Avoid loading cache multiple times

### ISSUE THREAD

**Issue by mllab-nl** [AzureAD/microsoft-authentication-library-for-dotnet#1843]
**Which Version of MSAL are you using ?**
microsoft.identity.client 4.12.0

**Platform**
netcore

**What authentication flow has the issue?**
* Web App
    * [x] Authorization code

**Repro**

var account = await app.GetAccountAsync(accountIdentifier);
var result = await app.AcquireTokenSilent(scopesToRequest, account).ExecuteAsync();

As result of the code above function set using SetBeforeAccessAsync will be called 2 times.
Based on current TokenCacheNotificationArgs I can not see how one can deduce if the cache is already loaded and avoid loding it for further requests. 

Can not use ITokenCache.DeserializeMsalV3 on app creation since it is Obsolete.

I am most likely missing something. 
Could you please explain/point to examples on how initialize the cache once for the lifetime of the app object  ? 

**Possible Solution**
Not very pretty workaround is: 
		private static bool WasLoaded(ITokenCacheSerializer tokenCache)
		{
			return tokenCache.SerializeMsalV3().Length > 1000;
		}

**Comment by bgavrilMS** [comment]
Hi @mllab-nl 

Both of the calls you mention: 

`var account = await app.GetAccountAsync(accountIdentifier);`
and
`var result = await app.AcquireTokenSilent(scopesToRequest, account).ExecuteAsync();`

make MSAL load the token cache from disk. We do not give you the option to load only once, I suppose we could, but it would be a new feature / perf optimization. The thinking behind this is that you can have 2 or more apps that share the same token cache and clinent ID. 

To serialize the token cache for example to a file, encrypted with DPAPI (Windows only) have a look at this sample code: https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/msal3x/active-directory-wpf-msgraph-v2/TokenCacheHelper.cs

If you are interested in a solution that works for .net core on all operating systems, have a look at https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet

**Comment by mllab-nl** [comment]
Hi Bogdan!

Thank you for a quick answer.
Do you plan to expose any indication of whether the cache was already loaded in to the function registered with SetBeforeAccessAsync ? 
Then the user can decide when to load/reload the cache. 

Currently TokenCacheNotificationArgs does not expose any state that can be consulted except of this ugly 
private static bool WasLoaded(ITokenCacheSerializer tokenCache)
{
return tokenCache.SerializeMsalV3().Length > 1000;
}

**Comment by bgavrilMS** [comment]
@mllab-nl - can you tell me a bit more about your scenario? Do you see performance issues with the current implementation ?

**Comment by mllab-nl** [comment]
We are have a multi-tenant distributed web app.
SQLServer distributed cache is used to persist token caches
It is quiet an overkill to fetch 8 kb+ data(Token cache size for one user) each time twice when I need to get a token.
I do not see any reason to do that and personally would not expect that this will happen for this, widely used code snippet:
var account = await app.GetAccountAsync(accountIdentifier);
var result = await app.AcquireTokenSilent(scopesToRequest, account).ExecuteAsync();

**Comment by bgavrilMS** [comment]
I'm still thinking how we could achieve this, I think it needs a bit of experimentation. An `app` has an in-memory `token cache` which gets syncronized from the persistence (SQL server in your case). 

In desktop scenarios this is pretty simple, because there is only 1 token cache and we can simply load it at the beginning and make sure we persist it when the application stops. This can easily be achieved from the outside: 

```csharp

bool loaded = true;
OnBeforeAcccess()
{
      if (!loaded)
      {
              ReadCache();
              loaded = true;
      }
}
```

But in Web App / Web Api scenarios, this is trickier because of object lifetimes. @jmprieur - thoughts?

**Comment by bgavrilMS** [comment]
I think one workaround you can use is to not call `GetAccountsAsync` and instead call `AcquireTokenSilent(scopes, username);`

I think it should be possible to figure out the username on asp.net core at least.

**Comment by jmprieur** [comment]
Yes this would be the prefered_username claim when using the v2.0 endpoint (therefore getting a v2.0 ID Token).
This will work well in single-tenant scenarios. Not sure for multi-tenants scenarios. I guess it would as well.

**Comment by mllab-nl** [comment]
Nice suggestion guys!
The cache will be loaded once to get a token. 
If I I have a process that executes 100 activities that require a token, cache will be loaded 100 times.

**Comment by jmprieur** [comment]
@mllab-nl, yes. your web app is probably multi users?

**Comment by mllab-nl** [comment]
Yes. Multiple users from multiple domains

**Comment by bgavrilMS** [comment]
I wonder if this can be solved by using 2 levels of cache - one that has a low latency like a session cache plus the SQL server cache. @henrik-me has seen this architecture used by some internal service I believe and can comment.

**Comment by mllab-nl** [comment]
Would it be easier to make it possible to implement this function ? 
private static bool WasLoaded(TokenCacheNotificationArgs args)
{
}

**Comment by henrik-me** [comment]
@mllab-nl 
Can you guarantee that the cache hasn't been modified by anyone else?
Even if no, does it matter for the token you are using? How long should the TTL for the cache be, that is when is hasBeenLoaded no longer to be true? Always?
Are you only talking about confidential client scenarios?

My suggestion is to have a 2 layer cache, one memory (with the TTL you like on the items) and one sql server (in this case). If the token is in the memory cache there is no need to do the network call. 

Aside: Some even use a 3 layered cache (injecting Redis between memory and the other persisted storage).

**Comment by mllab-nl** [comment]
Hey Henrik,

Good questions.
Let me clarify one thing before I will answer those. 

Please correct me if I am wrong. 
It looks like you are suggesting to keep the serialized cache data somewhere in memory/redis/SQL and **each time** I need to get the token to do the following:
1. Deserialize those bytes into a TockenCache
2. Get the token 
3. Discard the TokenCache ? (I will have to rebuild it anyway when I need to get another token)  

Do I understand you correctly ?

**Comment by henrik-me** [comment]
I'm talking about Cache and cache fallback to each layer. If found in L1 use the token from L1, if not go to L2, etc. 

TTL for each cache layer is something you specify, e.g. 5 minutes, 10 minutes or the AT lifetime or... this should be set based on environment. e.g. if you have multiple nodes and all can modify the same cache entry you may have to consider a lower TTL.

There is no need to discard the token cache. Cache eviction policies will ensure token entries gets properly evicted based on the TTL you specify.

However yes, there is serialization/deserialization happening when you are not able to find the token in what is already in the cache you have locally (and if you are not new'ing up a new CCA object you can use the token available in the object cache, and thus no need to spend time additional time serializing/de-serializing, however that is an optimization which is way less than what you gain from using an in memory layer as L1 and your sql layer as L2)

**Comment by mllab-nl** [comment]
>and if you are not new'ing up a new CCA object you can use the token available in the object 
cache

Henrik this is exactly the core of this question. How do you do that ?

**Comment by bgavrilMS** [comment]
Not a big problem on PublicClient where the current account can be kept around in memory. 
On ConfidentialClient the newer APIs do not rely on GetAccount(s)
