### ISSUE TITLE
'keep me logged in'

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#1844]
When logging in in Microsoft Identity Service, sometimes there is a checkmark 'keep me logged in'.  As far as I understand this sets the session token timeout and ensures that you have to login less frequently. How this work with MS Authenticator login ?
Sometimes we notice that you have to relogin after a couple of days.

**Comment by jennyf19** [comment]
@harmjonker The checkmark you refer to controls the session cookie in the system browser. It is not related to the tokens in the MSAL cache. I'm not sure if the Authenticator App handles this scenario is logging in w/the system browser... @shoatman @iambmelt can you provide more info here? Thanks.

**Comment by bgavrilMS** [comment]
I would expect you not having to re-login. Could you give us some logs for when the re-login is requested?

**Comment by bgavrilMS** [comment]
@harmjonker - I'm going to close this but please reopen if you see fit. We would need to look at broker logs to understand why a re-login is needed. Broker logs are obtained by clicking on the 3 dot button > Help > Send Logs. You'll get a short ID which you can send to us and we can extract the logs.

**Comment by harmjonker** [comment]
I agee.  We have some instances of unexpected login and will follow the procedure you described to figure out what is happening.
