### ISSUE TITLE
[Feature Request] Support Android for Work which does not allow AccountManager manipulation

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#1847]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

**Platform**

xamarin android
**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;
Customer developed Mobile app to login using AAD accounts (using MSAL.net, Xaramin platform). Also integrated with Broker. 
They are trying to Block the "Add and Remove accounts" on their Android for Work enrolled device and with this setting when they use broker to login, the login fails. When they do not use the broker the login goes through

Details can be found here: https://icm.ad.msft.net/imp/v3/incidents/details/187321930/home

**Is this a new or existing app?**

**Repro**
Can be reproduced using sample app with broker on Android for Work enrolled test device as listed in the ICM.

**Expected behavior**
The sign in should work with broker.

**Actual behavior**
Error is thrown while trying to sign in with broker.  

**Possible Solution**
Something similar was done to MSAL native android: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/898/files

**Additional context/ Logs / Screenshots**
Logs can be found here:
 https://icm.ad.msft.net/imp/v3/incidents/details/187321930/home

**Comment by bgavrilMS** [comment]
Not sure this is a P1, how many customers is it affecting? How common is this scenario?

**Comment by bgavrilMS** [comment]
@aiwangmicrosoft - can you help us understand this scenario and how common it is?

**Comment by bgavrilMS** [comment]
@henrik-me - I am not sure how we should handle the associated ICM. I do not feel there is enough information to repro and do a bug fix right now. It may be that the scenario of this "Enterprise Android" is not supported by MSAL.NET  :(

**Comment by trwalke** [comment]
@bgavrilMS I asked her to make a p1 based on the fact that there is a scenario that is blocked. however, I changed my mind mostly because this will only affect people using android for work who turn on a specific setting that blocks accounts from being added to the account manager. Probably not that many people

**Comment by bgavrilMS** [comment]
Do you know if there is any workaround, such as adding some extra permissions for this? 

CC @rpdome

**Comment by trwalke** [comment]
@bgavrilMS Android seems to have implemented something along the lines of a workaround in this PR here (https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/898)

Not sure exactly what it is doing yet as I have not had a chance to look into this yet. Might be worth reaching out to android to get their perspective on how to resolve this issue.

**Comment by neha-bhargava** [comment]
@bgavrilMS  As per my conversation with @rpdome, there is no way to fix this in dotnet but the workaround is something like the PR link I have pasted. It will pop up a dialog(the OS will pop this dialog and we have no control over it) indicating you cannot add an account and throw an exception. We can catch that exception in MSAL and handle it by not signing in through broker. @rpdome Please correct me if my understanding is wrong.

**Comment by rpdome** [comment]
Yes, it's pretty much the limitation of this (broker communicating) mechanism. The PR above is to make sure you 'cancel early' so that the user won't see the OS pop-up.

The long-term solution would be what @kreedula is working on, assuming that it works on Xamarin.

**Comment by henrik-me** [comment]
@bgavrilMS @neha-bhargava @trwalke : assuming the investigation is done and this should be marked as an enhancement and not a bug?

**Comment by bgavrilMS** [comment]
MSAL.Android (native) uses several methods to communicate with the broker: 

- AccountManager
- Bounded Service (problem is that it isn't well supported in Xamarin and on some phones it is disabled when battery is low)
- ContentProvider (spec is [here](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/1554)) - still under design

Link pasted shows how to detect if AccountManager is supported, but we still need to do work to add a new communication method. We looked at the bounded service before and it was a no-go. 

The only workardound I see right now is to use MSAL.Android directly instead of MSAL.Xamarin (i.e. generate your own bindings etc.). Or configure Android Enterprise to allow `AccountManager.AddAccount`.

This is blocking at least one large enterprise.

**Comment by stevenli510** [comment]
Thank you guys.
The enterprise IT is using the the setting "add & remove account" to prevent users from adding their personal account into their work profile. To me, the security team is unlikely to allow unblock this setting.
The impacted app was developed with Xamarin, I'm not sure if the dev team is willing to migrate to MSAL.Android. The reason why they want the broker auth is to perform the device auth. So the device can be managed by CA policy. Is there any way to allow Xamarin app to read the device cert and submit it during the sign-in like a browser? If we can use the TLS to pass the device auth, it might be a workaround.

**Comment by bgavrilMS** [comment]
Device auth can only be performed using a broker (Authenticator or Company Portal) as far as I know :(

MSAL will only add a accounts of type `com.microsoft.workaccount` - is there a way to unblock only this account type? 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/9bc6b04e25685aecf38d5e072136d9c02d9223cc/src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs#L84

**Comment by stevenli510** [comment]
According to the public released documentation of Android for Work, there is no such setting to only allow the specific account type. For detail, we may need checking with Google about the details.
Here is the doc for enterprise policy:
**modifyAccountsDisabled**
https://developers.google.com/android/management/reference/rest/v1/enterprises.policies

**Comment by bgavrilMS** [comment]
Just setting expectations here - we are unlikely to get this done anytime soon. 
The best experience to avoid these kind of issues would be to call directly MSAL for Android - https://github.com/AzureAD/microsoft-authentication-library-for-android

The native library will have fixed some of these issues.

**Comment by bgavrilMS** [comment]
This has been fixed. We are using content provider now.
