### ISSUE TITLE
[Enhancement] Even on Win10 MSAL tries to extract a PKAuth key, which is a perf hit

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1849]
**Which Version of MSAL are you using ?**
4.14

**Platform**
net45 only

**Repro**

This is related to bug #1848 BUT is not the root cause of #1848 !

MSAL tries to determine if it's running on Win 7, 8 or 8.1, but the verification is wrong - see screenshot from my Win 10 machine:

![image](https://user-images.githubusercontent.com/12273384/83013774-7a9ba700-a015-11ea-8fdd-a08d4366599d.png)

You can read why `Enviroment.GetVersion()` is actually deprecated here: https://stackoverflow.com/questions/31885302/how-can-i-detect-if-my-app-is-running-on-windows-10

I think we need to make a call to read the registry to get the version of Windows.

**Expected behavior**
Exit the PKAuth logic faster.

**Actual behavior**
1. MSAL checks if the OS is supported. It should say "no" but it says "yes" on Win 10
2. MSAL tries to pull out the device key by reading certs etc. 
3. MSAL fails to pull out device key
4. MSAL reponds with "I can't perform PKAUth"

Step 2-3 can be avoided

**Possible Solution**

**Comment by bgavrilMS** [comment]
@trwalke

**Comment by bgavrilMS** [comment]
Probably as designed.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
