### ISSUE TITLE
What is the organizational default expiration time for refresh_tokens

### ISSUE THREAD

**Issue by bcarthic** [AzureAD/microsoft-authentication-library-for-dotnet#1850]
Our scenario uses a personal live account, we needed to get the access token for the internal live account in the server. Our tenant is Microsoft organization and we are using third party app. We cant use username and password since it is not supported for personal accounts.

So we thought use refresh_token to get access token to access the resource.

What is the expiration for Refresh token in Microsoft organization? What is the organizational default value. I see from the document that it is sliding window of 14 days to 90 days. But couldn't find in Get-AzureADPolicy.

**Comment by bgavrilMS** [comment]
The default in 90 days, with a sliding window. 
Our SDK (MSAL) does not expose the refresh token. It performs the scenario you are talking when you call `AcquireTokenSilent` - this will return you either an existing, non-expired access token (from the token cache managed by MSAL) or it will refresh the RT, update the cache and give you the AT. 

MSAL works with personal live accounts. 

Please have a look at the sample page for details https://docs.microsoft.com/en-gb/azure/active-directory/develop/sample-v2-code

**Comment by bcarthic** [comment]
@bgavrilMS Thanks for the answer, I see the expiration time can be changed by organization/tenant admins. So how do I find Microsoft organization default value for RT expiration time?

**Comment by bgavrilMS** [comment]
I will answer you over email.
