### ISSUE TITLE
WithExtraScopeToConsent is documented by not able to use

### ISSUE THREAD

**Issue by konjac** [AzureAD/microsoft-authentication-library-for-dotnet#1852]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 4.14

**Platform**
netcore

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
    * [x] Client secret
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**

**Repro**

![image](https://user-images.githubusercontent.com/2101973/83389603-0ef57780-a423-11ea-94f9-b0af1fe04e0e.png)

**Expected behavior**
WithExtraScopeToConsent should be a public method

**Actual behavior**
No WithExtraScopeToConsent.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by henrik-me** [comment]
ExtraScopesToConsent only makes sense in interactive flows as UI needs to be shown for the user to concent. Thus this functionality doesn't apply to confidential client applications using client secrets. 

Can you please share the scenario?

**Comment by jmprieur** [comment]
Closed as answered
