### ISSUE TITLE
[Question] How does in-memory cache mechanism work for confidential client app app

### ISSUE THREAD

**Issue by asith-w** [AzureAD/microsoft-authentication-library-for-dotnet#1853]
How does in-memory cache mechanism work for confidential client app app like below .what details are store in cache .is there any documentation 

```
var app = ConfidentialClientApplicationBuilder.Create("client-id")
    .WithAuthority(AzureCloudInstance.AzurePublic, AadAuthorityAudience.AzureAdMultipleOrgs)
    .WithClientSecret("secret")
    .Build();

var result = await app.AcquireTokenForClient(new[]{"https://graph.microsoft.com/.default"})
    .WithAuthority(AzureCloudInstance.AzurePublic, Guid.Parse("target-tenant-id"))
    .ExecuteAsync();
```

**Comment by jmprieur** [comment]
@asith-w : if your confidential client application is a Web app or a Web API, please have a look at Microsoft.Identity.Web which provides token cache serialization implementations.
Never use the default cache.

See https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization

**Comment by bgavrilMS** [comment]
@jmprieur - for client credential flow, it is recommended to serialize the cache but it is not a hard requirement. The reason is that there is no Refresh Token with this flow. So upon expiration of the Access Token (1h), MSAL will go to AAD and fetch a new Access Token. 

@asith-w `AcquireTokenForClient` fetches a token from the in memory **app cache** on its own. 

It's still a good idea to serialize the cache to improve availability though in scenarios when you scale up the service and use several machines. This will decrease the number of calls made to AAD and also the decrease the changes that AAD will throttle you.

**Comment by asith-w** [comment]
@jmprieur i am writing  app like daemon service using worker service template [such as this](https://github.com/ardalis/CleanArchitecture.WorkerService/blob/master/src/CleanArchitecture.Worker/Worker.cs)
 for me, below confidential client app has been properly managing cache tokens including for different tenants. is there are any reasons to avoid default in-memory cache ?
 
@bgavrilMS is there way to know which keys are using for cache ?   
actually i wanted to cache below GraphServiceClient objects as MSAL  cache tokens per tenant and was looking to map cache item and relevant GraphServiceClient 


```
var tenantIds = new List<string>{
	 "x-x-x-x1",
	 "x-x-x-x2",
	 "x-x-x-x3",
	  ..
         ..
};

IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder.Create("client-id")
        .WithAuthority(AzureCloudInstance.AzurePublic, AadAuthorityAudience.AzureAdMultipleOrgs)
        .WithClientSecret("secret")
        .Build();

foreach (var tenantId in tenantIds)
{
     var result = await confidentialClientApplication.AcquireTokenForClient(new[] { "https://graph.microsoft.com/.default" })
	.WithAuthority(AzureCloudInstance.AzurePublic, Guid.Parse( tenantId  ))
	.ExecuteAsync();
 

     var graphServiceClient = new GraphServiceClient(new 
     DelegateAuthenticationProvider((requestMessage) =>
    {
	requestMessage
		.Headers
		.Authorization = new AuthenticationHeaderValue("bearer", result.access_token);
	return Task.FromResult(0);
    }));
var users = await graphServiceClient.Users.Request().GetAsync()

}
```

**Comment by jmprieur** [comment]
@asith-w daemon apps use only the app token cache. An in-memory cache is fine if you don't have millions of tenants.
