### ISSUE TITLE
[Bug] [Internal] Stop using deprecated Android methods

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1854]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
4.14.0

**Platform**
Android

**Repro**
Some of the Android system calls are marked as deprecated. Look for the link to this bug for occurences.

**Expected behavior**
Tested functionality on SDK 28 and 29 (Q) and seems fine. However, we should upgrade in case next SDK removes these methods.

**Actual behavior**
Disabled deprecation warning

Android team is on point for this - tracking issue https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/851

**Comment by jmprieur** [comment]
Moving to P3 as we'd want to reconsider vs the native wrapper.

**Comment by bgavrilMS** [comment]
won't fix
