### ISSUE TITLE
[Bug] JwtSecurityToken related help

### ISSUE THREAD

**Issue by nikitadzambre** [AzureAD/microsoft-authentication-library-for-dotnet#1859]
MSAL Version: 4.8.2
Platform: .NET 4.6.2

Authentication Flow: WEB API OBO
This is an existing app. I installed 'Microsoft.Identity.Client' library to test calling Graph API. My application already has Delegated Directory.Read.All permissions to access Graph API.

This is an API app service, which is authenticated using AAD. I want to call Graph API from my API. Since my app has delegated permissions, I was looking at [this link](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of) to understand how a token can be generated for the Graph API.

But I see the 'JwtSecurityToken' needs to be passed to UserAssertion to AcquireTokenOnBehalfOf method. I am not sure how to obtain this 'JwtSecurityToken'. Can you please help  me understand that? Is it supposed to be in the ClaimsPrincipal.Current.Identities.First().BootstrapContext? I get the 'bootstrapContext' as null when I log in to my application.

**Comment by jmprieur** [comment]
@nikitadzambre 
OBO is illustrated in the following sample: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

The principle is also explained here: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-app-configuration?tabs=aspnetcore, but if you use ASP.NET Core, we strongly recommend you use Microsoft.Identity.Web.

**Comment by nikitadzambre** [comment]
Thanks @jmprieur. I tried changing the Startup.Auth.cs to enable the 'SaveSigninToken' as true
![image](https://user-images.githubusercontent.com/29609199/83661585-30697700-a57b-11ea-9e51-619540fc5760.png)

But I still see the context below as null when I login to our API
BootstrapContext context = ClaimsPrincipal.Current.Identities.First().BootstrapContext as BootstrapContext;

Do I need to make any more changes for the bootstrapcontext to show up?

**Comment by jmprieur** [comment]
@TiagoBrenck @kalyankrishna1 @Shama-K would you mind having a look at that sample?
Thanks!

**Comment by TiagoBrenck** [comment]
@jmprieur I checked the sample and it is working properly.

@nikitadzambre Could give us a bit more of details? 
 - Did you create a scope for your web api, and configured it on your client app?
 - DId you follow the instructions for the [.default](https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#configure-authorized-client-applications-for-service-todolistservice-obo-sample-v2) scope and used it on your client app?
 - Is your client app able to acquire an access token for the web api (using .default scope)?

Thanks

**Comment by nikitadzambre** [comment]
I got the 'GroupMember.Read.All' and 'User.Read.All' Application permissions for my app and now I am able to call Graph API with these Application permissions.
