### ISSUE TITLE
[Bug] ADAL token cache exception comming from MSAL

### ISSUE THREAD

**Issue by Shristi12345** [AzureAD/microsoft-authentication-library-for-dotnet#1862]
**Which Version of MSAL are you using ?**
4.14

Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

**Platform**

**What authentication flow has the issue?**
  Mobile

**Is this a new or existing app?**
This is the existing aoo and  we are planning to release it in production

			string[] scopes = new[] {this.resourceUri+"/.default" };
			string username = this.authConfig.Username;
			IAccount accoun = null; ;
;			IEnumerable<IAccount> accounts = await this.pc.GetAccountsAsync();
			List<IAccount> accountarray = accounts.ToList();
			foreach(IAccount acc in accountarray)
			{
              if(acc.Username.Equals(username))
				{
					accoun = acc;
				}
			}
            AuthenticationResult authResult = null;
            try
            {
                IAccount firstAccount = accounts.FirstOrDefault();
				IAccount firtAccount = null;
				if (firstAccount != null && (firstAccount.Username.ToLower()).Equals(username))
				{
					authResult = await this.pc.AcquireTokenSilent(scopes, firstAccount).ExecuteAsync();
				}
				else if (accoun != null)
				{
					authResult = await this.pc.AcquireTokenSilent(scopes, accoun).ExecuteAsync();
				}
				else
				{
					authResult = await this.pc.AcquireTokenSilent(scopes, firtAccount).ExecuteAsync();
				}
				
            }
            catch (MsalUiRequiredException ex)
            {
                try
                {
					authResult = await this.pc.AcquireTokenInteractive(scopes).WithParentActivityOrWindow(App.PlatformAuthHandler.Activity()).WithLoginHint(username).WithPrompt(Prompt.ForceLogin).ExecuteAsync();
				}
                catch (Exception ex2)
                {
                   
                }
            }

```

**Expected behavior**
User A Signin interactively
UserB Sign in interactively
UserB signOut
User A silent sign succesully


**Actual behavior**
When User A try to sign in silent
12:34:19.339 I/mono-stdout( 5438):   at Microsoft.Identity.Client.Internal.Requests.SilentRequest+<ExecuteAsync>d__9.MoveNext () [0x00329] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 [0:] App Flow: [SignInFailure] [Exception: MSAL.Xamarin.Android.4.14.0.0.MsalClientException:     ErrorCode: invalid_adal_cache Microsoft.Identity.Client.MsalClientException: The ADAL cache is invalid as it contains multiple refresh token entries for one user. Mitigation: Delete the ADAL cache. If you do not maintain an ADAL cache, this may be a bug in MSAL.   at Microsoft.Identity.Client.Cache.CacheFallbackOperations.GetAdalEntryForMsal (Microsoft.Identity.Client.Core.ICoreLogger logger, Microsoft.Identity.Client.Cache.ILegacyCachePersistence legacyCachePersistence, System.Collections.Generic.IEnumerable`1[T] environmentAliases, System.String clientId, System.String upn, System.String uniqueId) [0x00067] in <62c5f81aa08b40f6a5628154f09a4f0a>:0   at Microsoft.Identity.Client.TokenCache+<Microsoft-Identity-Client-ITokenCacheInternal-FindRefreshTokenAsync>d__67.MoveNext () [0x0027a] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 --- End of stack trace from previous location where exception was thrown ---   at Microsoft.Identity.Client.Cache.CacheSessionManager+<FindRefreshTokenAsync>d__10.MoveNext () [0x000e8] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 --- End of stack trace from previous location where exception was thrown ---   at Microsoft.Identity.Client.Internal.Requests.SilentRequest+<FindRefreshTokenOrFailAsync>d__16.MoveNext () [0x00074] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 --- End of stack trace from previous location where exception was thrown ---   at Microsoft.Identity.Client.Internal.Requests.SilentRequest+<RefreshRtOrFailAsync>d__13.MoveNext () [0x000fa] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 --- End of stack trace from previous location where exception was thrown ---   at Microsoft.Identity.Client.Internal.Requests.SilentRequest+<ExecuteAsync>d__9.MoveNext () [0x00329] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 --- End of stack trace from previous location where exception was thrown ---   at Microsoft.Identity.Client.Internal.Requests.RequestBase+<RunAsync>d__14.MoveNext () [0x001dd] in <62c5f81aa08b


MSAL throws this eception

**Comment by bgavrilMS** [comment]
Could you please describe the repro steps and add the actual exception details?

**Comment by bgavrilMS** [comment]
Exception is 

`ADAL cache is invalid as it contains multiple refresh token entries for one user. Mitigation: Delete the ADAL cache. If you do not maintain an ADAL cache, this may be a bug in MSAL`

**Comment by bgavrilMS** [comment]
Does not repro.
