### ISSUE TITLE
[Feature Request] Enable developers to provide a custom implementation of IClientAssertionCertificate with SN+I

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1867]
**Is your feature request related to a problem? Please describe.**
Customers are looking to utilize a custom implementation of IClientAssertionCertificate which is able to perform "SN+I". There was a decision made at the beginning of the implementation of this feature to disallow SN+I with custom IClientAssertionCertificates. [Here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/68d7dea3643e075be85abbca1ab88ba614465541/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/ClientCreds/JsonWebToken.cs#L220)

**Describe the solution you'd like**
Allow customers to implement their own version of IClientAssertionCertificate with support for SN+I.

**Describe alternatives you've considered**
Throw an exception to indicate that the custom implementations of IClientAssertionCertificate are not able to use SendX5C()

**Additional context**
comment from customer:
"I have built a IClientAssertionCertificate object so that I can sign remotely AAD token requests in key vault, but to sign with keys that are auto rotated I need to pass the X5C data in the JWS header, which only works (in the current code) if I have a ClientAssertionCertificate, not a IClientAssertionCertificate.  Could you guys add a Certificate property to the IClientAssertionCertificate interface so that it can be used here instead of the ClientAssertionCertificate and then update this code to use it like that if the sendX5C property is set?

I’m looking at line 229 and 234.

Or at least throw an exception that sendX5C and IClientAssertionCertificate aren’t compatible."

Customer states that the main reason they avoid using the provided ClientAssertionCertificate implementation because it requires local secrets to sign the assertion.

**Comment by bgavrilMS** [comment]
Not sure I understand the scenario fully, because the code you mention is very old, MSAL 3.x or 2.x? `IClientAssertionCertificates` does not exist in MSAL 4.x

Can the be achived by using `WithClientAssertion` instead? This is essentially an extensibility point allowing users to transform a certificate into an assertion using whatever mechanism they wish. Can it be adapted for SNI ?

**Comment by trwalke** [comment]
This is actually an ADAL bug. moving there

**Comment by jmprieur** [comment]
@trwalke @bgavrilMS @jennyf19 @pmaytak @henrik-me 
Given that all AcquireTokenXX methods in Confidential client apps support .WithSendx5c, and can be passed .WithClientAssertion, I think we can close this issue as non-repro.

**Comment by IdeaHunter** [comment]
Bump!

The beauty of IClientAssertionCertificate was that you could use custom signing mechanism without paying attention to how create a token
For example for Azure Vault hardware based certificate(RSA-HSM) the code would be following
```cs
    public class KeyVaultClientCert: IClientAssertionCertificate
    {
        private readonly KeyClient keys;
        private readonly SecretClient secret;
        private readonly CertificateClient certs;
        private readonly TokenCredential tokenCreds;

        public KeyVaultClientCert(string appId, KeyClient keys,  CertificateClient certs, TokenCredential tokenCreds)
        {
            ClientId = appId;
            this.keys = keys;
            this.certs = certs;
            this.tokenCreds = tokenCreds;
        }

        public string ClientId { get; }

        public string Thumbprint
        {
            get
            {

                var cert = certs.GetCertificate(Constants.AzureVaultKeyNames.ClientAppOnlyCert);
                return Convert.ToBase64String(cert.Value.Properties.X509Thumbprint);
            }
        }

        public byte[] Sign(string message)
        {
            return SignAsync(message).Result;
        }

        public async Task<byte[]> SignAsync(string message)
        {
            var jwk = await keys.GetKeyAsync(Constants.AzureVaultKeyNames.ClientAppOnlyCert);
            using (var hasher = new SHA256CryptoServiceProvider())
            {
                var rawDataBytes = Encoding.UTF8.GetBytes(message);
                var digest = hasher.ComputeHash(rawDataBytes);
                var crypto = new CryptographyClient(jwk.Value.Id, tokenCreds);
                var signature = await crypto.SignAsync(SignatureAlgorithm.RS256, digest);
                return signature.Signature;
            }
        }
    }
```

As you may notice, no jwt info whatsoever beside signing algo, just pure assertion signing, would be nice to have it back without doing all the work the lib already could do
