### ISSUE TITLE
MSAL Bug within Unity. Authentication through Unity for HoloLens 2

### ISSUE THREAD

**Issue by Sebastian7112** [AzureAD/microsoft-authentication-library-for-dotnet#1878]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

*** Apologies if this issue is meant for another board / repo.

Currently using the latest version of Microsoft Identity Client 4.14.0

**Platform**

Platform: UWP --> Hololens 2

**What authentication flow has the issue?**
* Desktop / Mobile
    *** [ ] Interactive**
Interactive is causing the issue

Other? - please describe;

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL

**Repro**

```csharp
var your = (code) => here;

using System.Collections;
using System.Threading.Tasks;
using UnityEngine;

#if !UNITY_EDITOR && UNITY_WSA
using System.Net.Http;
using System.Net.Http.Headers;
using System.IO;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Collections.Generic;
using System;
using System.Linq;

using Microsoft.Identity.Client;
#endif

namespace Ada
{
    public class AdaSignin : MonoBehaviour
    {
        public string graphAPIEndpoint = "https://graph.microsoft.com/v1.0/me";
        string[] scopes = new string[] { "user.read" };

        // Start is called before the first frame update
        async void Start()
        {
            await Authenticate();
        }

        private async Task Authenticate()
        {
#if !UNITY_EDITOR && UNITY_WSA
            AuthenticationResult authResult = null;
            Debug.Log("Getting the Public Client");
           // ApaAdaInfo is a class in which we get the ClientId and TenantId
            var app = AppAdaInfo.PublicClientApp;
            Debug.Log("app: " + app);
            Debug.Log("Client ID: " + app.AppConfig.ClientId);

            var accounts = await app.GetAccountsAsync();
            Debug.Log("Accounts: " + accounts);
            Debug.Log("Entering for loop");
            foreach (var account in accounts)
            {
                Debug.Log("Account..." + account);
            }
            var firstAccount = accounts.FirstOrDefault();

            try
            {
                Debug.Log("Calling acquire token async");
                Debug.Log("First Account: " + firstAccount);
                Debug.Log("Scopes: " + scopes);
                Debug.Log("Value of scopes: " + scopes[0]);
                authResult = await app.AcquireTokenSilent(scopes, firstAccount).ExecuteAsync();
            }
            catch (MsalUiRequiredException ex)
            {
                // A MsalUiRequiredException happened on AcquireTokenSilent.
                // This indicates you need to call AcquireTokenInteractive to acquire a token
                Debug.Log("MsalUiRequiredException: " + ex.Message);

                try
                {
                    Debug.Log("Calling acquire interactive");
                    Debug.Log("Trying Interactive: " + scopes[0]);
                    // This is where the Exception occurs.
                    authResult = await app.AcquireTokenInteractive(scopes).ExecuteAsync();
                }
                catch (MsalException msalex)
                {
                    Debug.Log("MSAL Exception: " + msalex);
                }
            }

            if (authResult != null)
            {
                Debug.Log(authResult);
            }
#endif
        }
    }
}

```

**Expected behavior**
The signin portal for microsoft is suppose to appear.
**Actual behavior**
Nothing occurs, app launches within the hololens and that is it.

**Additional context/ Logs / Screenshots**
![Capture](https://user-images.githubusercontent.com/66624447/84313599-c0d42880-ab34-11ea-982a-75f51da81866.JPG)

**Comment by bgavrilMS** [comment]
Sadly we don't really support Unity at the moment, but there were some attempts to get it going from the community - see similar bugs in the repo. 

@jmprieur @henrik-me for awerness, maybe get some help from CxP on this important scenario?

**Comment by Sebastian7112** [comment]
Hey Bogdan,

Someone from the team decided to give our program a run and it seems like the error is occurring due to our different Windows OS. Mine is running on 10.0.19 vs. 10.0.18.

Now that we are running on windows 10.0.18 we encounter this error. Has anyone ever seen this exception within the library? 

![Capture](https://user-images.githubusercontent.com/66624447/84444180-2d235a80-ac0f-11ea-8e27-ef2959b91234.JPG)

**Comment by bgavrilMS** [comment]
The first exception is normal, the second one, from newtonsoft, is an issue with that library + MSAL. Other folks have reported it - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1812

**Comment by jmprieur** [comment]
Closing as duplicate
