### ISSUE TITLE
Session Values Lost on Redirecting back to call back URL

### ISSUE THREAD

**Issue by din-prajapati** [AzureAD/microsoft-authentication-library-for-dotnet#1879]
Hello Folks,

**BackGround** : User once logged in to the our Web Application (using App level credential) will be presented with with Mail System they want to use based on that user will be redirected to respective authorization server (exchange or google) to authenticate (using login / password of their mail system) and the auth server will return an access token back.

I have came cross one strange thing after redirecting back from OpenID OAuth flow from Microsoft Login to our application. our Application Session get lost;

I tried with OWIN platform as well as Manual redirect to Authorization end point in both the scenario Session are not persist.

Could you please let us know how could i resolve this issue so that on callback url i can fetch get our application session.

**Comment by jmprieur** [comment]
@din-prajapati : 
- Is it B2C? 
- did you have a look at the ASP.NET Core Web App incremental tutorial?
Maybe this folder: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

note that there is a number of sub-folders. you should find a solution there.

**Comment by din-prajapati** [comment]
Thanks for you reply. 

Sorry i should have write underlying technology. Our application is in ASP.NET web form and ASP.NET MVC.

Also, Does it make the difference for B2B or B2C Scenario ?

**Comment by jennyf19** [comment]
@din-prajapati apologies for us taking awhile to get to your issue. 
Do you have a repro or a link to a repro that we can use to try and reproduce this issue and see your code set-up?

**Comment by henrik-me** [comment]
Marking as resolved, please provide additional details for us to help troubleshoot and reopen.
