### ISSUE TITLE
Android login forms clearing on mobile orientation change

### ISSUE THREAD

**Issue by mdgreene123** [AzureAD/microsoft-authentication-library-for-dotnet#188]
I have a Xamarin forms app connected to an AD B2C production instance set up with a sign in policy.

While on the Azure sign in page, any form input is cleared on orientation change. This has only been tested on iOS and Android (iOS works as expected)

Launch the app
Navigate to Azure Login
Insert text in any field
Switch phone orientation

Expected Results: Text is persisted through orientation change

Actual Results: Form text is cleared

**Comment by kpanwar** [comment]
We will be moving to system webview or chromeTabs in the next release. This will be a non-issue then.
