### ISSUE TITLE
[Enhancement] ADFS authority validation is not spec compliant

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1885]
**Which Version of MSAL are you using ?**
4.15

**Platform**
all

**Repro**

**Expected behavior**
ADFS authority validation should perform a discovery call to a global endpoint.

**Actual behavior**
no global DRS call is made 

**Possible Solution**
The spec is [here](https://microsoft.sharepoint.com/:w:/r/teams/aad/devex/_layouts/15/Doc.aspx?sourcedoc=%7BF0EB0F6F-2B78-42A2-B44F-01DA1D6015E2%7D&file=ADFS%20Authority%20Validation%20-%20Original%20Spec.docx&action=default&mobileredirect=true&wdLOR=c22AE0924-0124-3D40-8BD4-435F36B291C7&cid=55F6763D-6E90-4588-A0AD-AF062981A3E4).
MSAL.NET actually has [unit tests ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/9b67ed9c78c85cd490523558bf09580cc19f119f/tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/AdfsAuthorityTests.cs#L23) for the spec, but they were disabled...

**Comment by bgavrilMS** [comment]
@neha-bhargava - I think this would be a good work item for you to work on in 4.16

**Comment by bgavrilMS** [comment]
ADFS validation algorithm works on the premises that a login hint exists. If a login hint is not passed or for the client credentials flow, MSAL is supposed to fail if the validate_authority flag is true. This is a breaking change and we need to reconsider this work item when we are ready to bump the major version.

**Comment by henrik-me** [comment]
planning: Neha to get the latest status

**Comment by neha-bhargava** [comment]
There was a meeting to discuss this and it was stated that for ADFS 2019 the DRS discovery is not applicable. So, what we do currently in MSAL is compliant with it. Closing it until there is some change in the security compliance. @henrik-me @bgavrilMS
