### ISSUE TITLE
[Feature Request] GetAccounts with user flow filter for B2C scenarios

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1889]
**Is your feature request related to a problem? Please describe.**
In B2C, each user flow has its own tokens and therefore its own accounts. MSAL does not provide a method to filter accounts only to one flow, which would be needed for `AcquireTokenSilent` to pick the correct tokens.

**Describe the solution you'd like**
`GetAccountsAsync(string userFlow)` is needed to get accounts that are only relevant for the given user flow. 

**Describe alternatives you've considered**

**Additional context**

**Comment by bgavrilMS** [comment]
Fixed by https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1869

**Comment by trwalke** [comment]
Resolved in [4.15](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.15.0)
