### ISSUE TITLE
[Bug] MSAL Broker can sometimes fail to properly look up an account when using broker.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1899]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
4.14

**Platform**
xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

"The scenario is for an OrgId and an MSA accounts having the same email address. Even though only 1 of the 2 accounts is shown in Authenticator or the account picker, requesting a token silently using the actual IAccount object instead of a loginHint works fine on iOS with and without broker and on Android without broker.
 
However, if Authenticator is installed, requesting a token for one or the other account always returns the same account (it seems to depend on the order the accounts were added to the broker)
It behaves as is the silent token request to the broker is made for a loginHint and not an account (or the account being sent has been looked up by email).
 
Is that something that sounds plausible? Do you know what I could be looking for (maybe in the Authenticator logs) to confirm whether this is an issue with our app, MSAL or Authenticator?"

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Repro**

**Expected behavior**
MSAL returns a token for the specified account in the iAccount object

**Actual behavior**
MSAL returns the account of the wrong user

**Comment by bgavrilMS** [comment]
How can an MSA and an OrgId have the same email address? Maybe I don't understand what an OrgId is ...

**Comment by trwalke** [comment]
@bgavrilMS  There is an email thread going where we can ask Benoit more questions about this. Im assuming orgID refers to an AAD account. There was a time where there were less restrictions on MSA email addresses so I think it is possible for an old MSA account to have the same email as an AAD account.

**Comment by bgavrilMS** [comment]
If we cannot have a repro on this, I suggest we close this.

**Comment by trwalke** [comment]
Could not reproduce
