### ISSUE TITLE
[Documentation] Update Intune docs and sample code with MSAL details

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1903]
@trwalke and @bgavrilMS to help with code and scenarios. Please provide a list of docs we should look at.

**Comment by aiwangmicrosoft** [comment]
Couple of articles/samples to update:

Article 1: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin#prerequisites
PR 1: https://github.com/MicrosoftDocs/memdocs-pr/pull/1581

Sample - we should propose changes, README and config.
https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps

**Comment by trwalke** [comment]
Some good links:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/How-to-migrate-from-using-Android-Broker-on-ADAL.NET-to-MSAL.NET
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/How-to-migrate-from-using-iOS-Broker-on-ADAL.NET-to-MSAL.NET
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Leveraging-the-broker-on-iOS-and-Android
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal
https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/azure-ad-endpoint-comparison

**Comment by henrik-me** [comment]
planning: @aiwangmicrosoft @jmprieur to synergize on this and update the sample

**Comment by bgavrilMS** [comment]
@henrik-me @jmprieur - propose to remove this from our backlog. We do not have bandwidth to take care of other team's samples?

**Comment by henrik-me** [comment]
@bgavrilMS, not updating these docs hurts adoption of MSAL and makes customers continue to run into problems adopting Xamarin having to go through hoops of ADAL and when they reach out to us we tell them to move to MSAL. 
CC: @jmprieur

**Comment by jmprieur** [comment]
@henrik-me : working on it.
