### ISSUE TITLE
[Bug] GetDeviceId sometimes takes 1.5s 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1912]
**Which Version of MSAL are you using ?**
4.15

**Platform**
.net classic 

**Repro**

**Expected behavior**
AcquireTokenSilent normally takes ~300ms

**Actual behavior**
AcquireTokenSilent sometimes takes ~2s, whith a lot of time spent in GetDeviceId

**Possible Solution**
GetDeviceId on .net classic tries to enumerate the system NICs and use a network address as id. This can take a very long time when a VPN is configured on the system.

We should not call "get device id" because it is used in conjuction with MATS Telemetry. We do not use MATS telemetry at the moment.

**Comment by neha-bhargava** [comment]
Fixed in [MSAL 4.17.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.17.0)
