### ISSUE TITLE
[Bug] Java.Lang exception from the broker

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1914]
**Which Version of MSAL are you using ?**
4.14

**Platform**
android + broker 

**Repro**

Sometimes, when calling the broker, the following exception is thrown: 

Java.Lang.Exception: Exception of type 'Java.Lang.Exception' was thrown.

JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms)
**IAccountManagerFutureInvoker.GetResult (System.Int64 timeout, Java.Util.Concurrent.TimeUnit unit)**
IAccountManagerFutureExtensions+<>c__DisplayClass0_0.<GetResultAsync>b__0 ()
Task`1[TResult].InnerInvoke ()
Task.Execute ()
AndroidBrokerHelper.GetBrokerAuthTokenSilentlyAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload, Android.App.Activity callerActivity)
AndroidBroker.AcquireTokenInternalAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload)
AndroidBroker.AcquireTokenUsingBrokerAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] brokerPayload)
android.accounts.OperationCanceledException
android.accounts.AccountManager$AmsTask.internalGetResult AccountManager.java:2328
android.accounts.AccountManager$AmsTask.getResult AccountManager.java:2340
android.accounts.AccountManager$AmsTask.getResult AccountManager.java:2252

Remark: this is probably a Xamarin bug.

**Comment by bgavrilMS** [comment]
Related Xamarin issue: https://github.com/xamarin/xamarin-android/issues/4898

**Comment by bgavrilMS** [comment]
CC @trwalke

**Comment by henrik-me** [comment]
planning: Travis to follow up with the more-info

**Comment by trwalke** [comment]
What needs to be done here is the handling of the potential exceptions thrown when using GetAccountsAsync()

ForExample:
```CSharp
try {
    var r = result.GetAccountsAsync(…);
}
catch (Android.Accounts.OperationCanceledException e) {
    // …
}
```
see this for more details
https://github.com/xamarin/xamarin-android/issues/4898#issuecomment-680147755

What is happening here is that some of the exception types are not being used by the linker and when an exception is thrown, MSAL throws a strange error that is not very useful for diagnosing further.

**Comment by bgavrilMS** [comment]
As per AccountManager specs, an OperationCancelledException is thrown when: 

`OperationCanceledException if the operation was canceled for any reason, including the user canceling the creation process or adding accounts (of this type) has been disabled by policy`

I bet that in 99% of the reported case, the actual issue comes from "disabled by policy".
