### ISSUE TITLE
[Bug] AcquireTokenForClient Causes Application To Terminate With Code 0 Without Any Explanation

### ISSUE THREAD

**Issue by Sn3akyP3t3** [AzureAD/microsoft-authentication-library-for-dotnet#1917]
**Which Version of MSAL are you using ?**
MSAL 4.16.0

**Platform**
.NET Core 3.1 Console Application.  Same behavior observed in a netstandard class application when tested through a netframework integration test.

**What authentication flow has the issue?**
Daemon - I believe its client credentials flow.
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow

**Is this a new or existing app?**
New, but this code was being refactored from using only Graph API to using the Managed EWS API since we could not use Graph at this time due to an incompatibility discovered due to using Hybrid Exchange.  Before this refactoring it was tested against an Office 365 enabled account that was not associated with Exchange and tokens were acquired without fail.  Even with the Hybrid Exchange issue this step to acquire a token did not fail.

**Repro**
I'm not exactly sure what triggers this other than it seems to be related to use of a certificate, but that's not proven.  I don't manage the Exchange server so I'm not able to experiment with settings.  There is very little documentation with code samples showing use of a certificate so perhaps I'm not using it correctly, but at least it should be throwing an error if that were the case.  Most of the examples are client username/password or client secret which I'm trying to avoid for this application.

C# Code provided as a gist to keep the bug report from being crowded.  The certificate will have to be created on your own.  I don't yet have the details on how that was created, but it was an encrypted pfx file that was installed in the certificate manager decrypted.
https://gist.github.com/Sn3akyP3t3/e84d451e63845d0e566b2127f7e1e45f

**Expected behavior**
Acquisition of token or if failed then a response or if encountered error then throws exception.

**Actual behavior**
The application exits with error code 0 at the moment AcquireTokenForClient is executed.  When monitoring traffic from Fiddler it seems that https://login.microsoftonline.com is hit exactly one time with error code 200 shown, but the icon next to it is a red circle with a line drawn through it.  Upon lookup of what that symbol means it says that the session was aborted by either client or server.  Which of those is the cause is unknown to me.  https://docs.telerik.com/fiddler/knowledgebase/uiguide

**Possible Solution**

**Additional context/ Logs / Screenshots**
I plan to attempt in identifying which of the two client or server caused the termination by dabbling around with Wire Shark or something else, but I'm no expert at those tools so that will take some time to explore.  If I can determine which of the two is the cause I will return and update this bug report.

Update:
I believe this is indeed related to a certificate, but exactly what is going wrong is a mystery.  I'll try to add MSAL logging as suggested in my next round of troubleshooting.  The results of the Wire Shark packet capture reveal this is likely the server issuing a disconnect on encryption failure.  Here's a screenshot of the packet capture:
![image](https://user-images.githubusercontent.com/1790256/86955854-de89b300-c11d-11ea-921a-ce4ede053690.png)
The documentation around the Alert Message: Encrypted Alert is a little grey to me, but this is what I found:
https://www.openssl.org/docs/manmaster/man3/SSL_shutdown.html
https://tools.ietf.org/html/rfc5246#page-29

**Comment by bgavrilMS** [comment]
It might be easier to fetch some logs from MSAL ... https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

MSAL doesn't handle well all certificates, that could be a problem, but we need more details to investigate.

**Comment by Sn3akyP3t3** [comment]
I didn't see this question answered anywhere in documentation.  Does Certificate Based Authentication need to be enabled on local Exchange servers for authentication routed to Office 365 Azure hosted AD?  This was the only documentation I could find: https://docs.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/configure-certificate-based-auth?view=exchserver-2019

**Comment by Sn3akyP3t3** [comment]
I omitted Client and Tenant ID from the logs.  Hope that's alright.  Logging level was set to verbose.

```
Info (False) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] MSAL MSAL.NetCore with assembly version '4.16.0.0'. CorrelationId(762f8732-e216-4335-ba0e-a8e208d4204a)
Info (False) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

Info (True) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a]
=== Request Data ===
Authority Provided? - True
Client Id - ClientIdRemovedFromPosting
Scopes - https://outlook.office.com/.default
Redirect Uri - https://replyUrlNotSet
Extra Query Params Keys (space separated) -
ClaimsAndClientCapabilities -
Authority - https://login.microsoftonline.com/TenantIdRemovedFromPosting/
ApiId - AcquireTokenForClient
SuggestedCacheKey -
IsConfidentialClient - True
SendX5C - False
LoginHint -
IsBrokerConfigured - False

Info (True) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] === Token Acquisition (ClientCredentialRequest) started:
        Authority: https://login.microsoftonline.com/TenantIdRemovedFromPosting/
        Scope: https://outlook.office.com/.default
        ClientId: ClientIdRemovedFromPosting

Info (False) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] Looking up access token in the cache.
Info (False) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] Filtering by tenant id item count before 0 after 0
Info (False) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] Filtering by token type item count before 0 after 0
Info (False) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] No matching entry found for user or assertion
Verbose (False) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False
Info (True) MSAL 4.16.0.0 MSAL.NetCore Microsoft Windows 10.0.19041 [07/08/2020 18:50:12 - 762f8732-e216-4335-ba0e-a8e208d4204a] Fetching instance discovery from the network from host login.microsoftonline.com. Endpoint https://login.microsoftonline.com/common/discovery/instance

C:\Users\User\Desktop\TestingGetEwsToken\TestingGetEwsToken\bin\Debug\netcoreapp3.1\TestingGetEwsToken.exe (process 5000) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by Sn3akyP3t3** [comment]
Just a quick note.  Were going to recreate the certificate following this procedure: https://developermessaging.azurewebsites.net/2018/09/11/authenticating-against-exchange-web-services-using-certificate-based-oauth2-tokens/  Prior to this we were using a certificate generated by the company's CA which succeeded in getting a token when testing with the Graph API, but failed with Outlook with the only difference that I can tell being the Scope changed.

**Comment by bgavrilMS** [comment]
From the logs I do not see any issue in MSAL. The logs cut off immediately before MSAL tries to make an HTTP call to the `https://login.microsoftonline.com/common/discovery/instance` endpoint. The call doesn't fail, MSAL can handle failures and would throw an appropriate exception (or in this case just continue), the process just stops. 

Maybe there is an aggressive firewall / antivirus on the box which kills the process when it tries to connect to the Internet?

**Comment by Sn3akyP3t3** [comment]
I don't know what is incorrect with the code I provided as it was pieced together from an existing functional project and only slightly modified with the scope for EWS token acquisition, but it seems to terminate before it completes.  If I follow the example of code found linked from Azure AD quick start for .NET
![image](https://user-images.githubusercontent.com/1790256/87116329-1f2b1e80-c23b-11ea-9d3d-afa13c53c5d7.png)
 I'm able to get the token which was the initial goal, but I'm extremely puzzled by this failure.  I can at least say that there is no Antivirus or Firewall involved in this failure since the same behavior is observed on two different machines on to different networks with different applications installed.

Note that the functional project mentioned above is based heavily on the example provided by the folder base-console-app-cert from this repo: https://github.com/microsoftgraph/dotnetcore-console-sample, but the token is not accessible in this design which is fine if using Graph only, but I have a need to leverage EWS for the time being which demands the token up front to create the service object.

**Comment by Sn3akyP3t3** [comment]
It seems like changing the line in Program.cs to this resolves the failure to acquire the token:
AttemptToGetToken().GetAwaiter().GetResult();
I guess that's not equivalent to 
_ = AttemptToGetToken();
my mistake!

**Comment by Sn3akyP3t3** [comment]
This problem has everything to do with missing the warning given by Visual Studio that the call will not be awaited.  I must not have seen it due to the line being set with breakpoints which makes it extremely red and blocked out the wavy line that indicated the warning
![image](https://user-images.githubusercontent.com/1790256/87119882-d2e4dc00-c244-11ea-8510-b9e102ed3951.png)
.  When I created the test program I also incorrectly applied the necessary await thus recreating the problem in the original code, but in another way.

**Comment by Sn3akyP3t3** [comment]
This problem has everything to do with missing the warning given by Visual Studio that the call will not be awaited.  I must not have seen it due to the line being set with breakpoints which makes it extremely red and blocked out the wavy line that indicated the warning
![image](https://user-images.githubusercontent.com/1790256/87119882-d2e4dc00-c244-11ea-8510-b9e102ed3951.png)
.  When I created the test program I also incorrectly applied the necessary await thus recreating the problem in the original code, but in another way.
