### ISSUE TITLE
[Bug] Refresh tokens seem to expire early after they are refreshed silently in the cache

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#1921]
**Which Version of MSAL are you using ?**
4.14+

**Platform**
xamarin android, >NET Desktop

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL

**Repro**
1.	Set the RT expiration at 3h and keep AT expiration at the default 1h 
2.	Login interactively  
3.	After 1.5 hours, login silently 
4.	After another 1.5 hours and a few minutes, login silently
 Expected: silent login should work
 Actual: silent login fails with server error "RT has expired" 

**Expected behavior**
MSAL should refresh the access token with the cached refresh token. The token that was acquired from the first silent refresh should still be active at this point
**Actual behavior**
AAD returns an error stating that the token is expired.
**Possible Solution**

**Comment by trwalke** [comment]
Had about 2 customers run into the same issue so far

**Comment by bgavrilMS** [comment]
We also have an ICM open for smth similar.

**Comment by bgavrilMS** [comment]
-	The “sign-in frequency” policy is behaving correctly. If this policy is set to X hours, the user MUST re-enter their credentials after X hours, irrespective of how often they go through refresh_token grant and thus irrespective of the rolling expiration RT window
-	Currently there are no policies allowing to control the RT rolling expiration window (these [ones ](https://docs.microsoft.com/en-gb/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime) are deprecated and no longer usable on new tenants). It’s 90 days.
-	MSAL behaves correctly as it throws the MsalUiRequiredException when an RT expires, for either reason.
