### ISSUE TITLE
[Feature Request] [Internal] Embed commit ID into the nuget package or into the DLL to prevent releasing outdated DLL.

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1924]
https://stackoverflow.com/questions/15141338/embed-git-commit-hash-in-a-net-dll

**Comment by henrik-me** [comment]
@bgavrilMS : we should consider getting this done for the next release.

**Comment by bgavrilMS** [comment]
This has not been a problem in MSAL. Won't fix.
