### ISSUE TITLE
[Feature Request] Android WithUseEmbeddedWebView - Remove Sign in header bar with black background

### ISSUE THREAD

**Issue by manikandantk88** [AzureAD/microsoft-authentication-library-for-dotnet#1927]
**Is your feature request related to a problem? Please describe.**
When we use interactive authentication flow WithUseEmbeddedWebView, There is a header bar with black background titled "Sign in". Azure AD B2C Sign-in page is customized based on brand theme and UX guidelines. This Sign-in header looks really unpleasant. 
<img width="214" alt="MSAL_SIGN_IN_HEADER" src="https://user-images.githubusercontent.com/34866824/87274157-af49bc00-c4f8-11ea-8391-ab9f8df60217.PNG">

**Describe the solution you'd like**
Header can be removed. It is not required. Azure AD B2C Sign-in page has required information to inform the user to sign-in. It is unnecessary.

**Describe alternatives you've considered**
I couldn't find any alternatives. Please advise if anyone has faced it.

**Additional context**

**Comment by bgavrilMS** [comment]
It's just a string that could be configurable, but I'm curious what other MSALs do and how we would expose such an API. @rpdome - do you guys expose this as a configuration? 

CC @aiwangmicrosoft to follow up

**Comment by manikandantk88** [comment]
Any update on this?

**Comment by bgavrilMS** [comment]
No update on this @manikandantk88, I am not sure when we can visit this or what is the right thing to do (@aiwangmicrosoft  is on point for the scenario)

If you are blocked, MSAL does offer a mechanism of providing your own WebView - WithCustomWebUi. You could just copy our implementation of the embedded web ui but customize it. Let me know if you want me to give you a few code pointers.

**Comment by aiwangmicrosoft** [comment]
@manikandantk88 Like Bogdan mentioned, you can provide your own WebView or tweak ours today, so I'm not sure what you would like the customization flow to look like?

**Comment by Tarunshrma** [comment]
Hi @bgavrilMS ,

I have similar requirement as mentioned by @manikandantk88.   I did not find any sample code or good pointers to implement WithCustomWebUi. Can you please suggest some good pointers, I am using Xamarin forms.

Thanks
Tarun Sharma

**Comment by bgavrilMS** [comment]
What sort of customizations would you require there? 

- the color of the top bar 
- the title (I think webviews should use the title of the HTLM login pages as they come in from AAD, but not sure how to achive this in Android)

ICustomWebUi docs are [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.extensibility.icustomwebui?view=azure-dotnet) and our current implementation of EmbeddedWebView on Android is [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/3e53fbfab91b277e7d1920c9bd344ad705318a31/src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/EmbeddedWebUI.cs#L14) - see all files in that directory.

**Comment by manikandantk88** [comment]
> No update on this @manikandantk88, I am not sure when we can visit this or what is the right thing to do (@aiwangmicrosoft is on point for the scenario)
> 
> If you are blocked, MSAL does offer a mechanism of providing your own WebView - WithCustomWebUi. You could just copy our implementation of the embedded web ui but customize it. Let me know if you want me to give you a few code pointers.

Thanks

**Comment by jvillaro** [comment]
Hi guys, do we have any more updates?
 
There are new options for embedded webviews but they don't work for net standard. Documentation is kind of lacking for this scenario. And there are no real examples for doing what the OP is asking for.
Is it posible to add something like IsVisible, Text, TextColor, BackgroundColor and HorizontalTextAlignment? That way at least it's posible to integrate to our apps UI.

Thanks in advance for any information

**Comment by Luiz-Franco** [comment]
The ability to customize at least the title and background color would be really helpful.

In our case, using android emulator, the title shown is the app package set in AndroidManifest.xml file:

![image](https://user-images.githubusercontent.com/31076889/117361478-749e7f00-ae90-11eb-80d2-5569369b3191.png)
![image](https://user-images.githubusercontent.com/31076889/117361547-8c760300-ae90-11eb-8e4b-8d218be09b11.png)

It feels really odd for the customer to see the app package name as the title of a signin page.

**Comment by jennyf19** [comment]
@jvillaro @Luiz-Franco @manikandantk88 Which version of MSAL.NET are you using? This was fixed in 4.18. See this related [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2014) and this is what the embedded webview should look [like](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2014#issuecomment-682276629) , and you should be able to customize further in the manifest. I added this in the manifest:

`<application android:theme = "@android:style/Theme.NoTitleBar">` 

but now you should be able to display your app name or something else in the title bar area, by applying a [theme](https://stackoverflow.com/a/3752646). Or if you want nothing, do what I did above.

If this is not what you are looking for, please let us know.

cc: @SameerK-MSFT

**Comment by jennyf19** [comment]
@Luiz-Franco Awesome! Thanks for the quick response. I'll close this issue.
