### ISSUE TITLE
[Question] Returned correlation id does not match the sent correlation id

### ISSUE THREAD

**Issue by negberts** [AzureAD/microsoft-authentication-library-for-dotnet#1928]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 4.16.1

**Platform**
Xamarin.iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Actually more a question than a bug, but I have trouble finding the solution for this. What is actually going wrong if we receive the error "Returned correlation id does not match the sent correlation id". What have we done wrong in the registration?

**Comment by bgavrilMS** [comment]
ROPC flow is not enabled on mobile. What `AcquireToken*` method do you actually use? Do you use a broker?

**Comment by negberts** [comment]
AcquireTokenInteractive with scopes to access the underlaying API. Maybe that is the problem, that the scopes should only be supplied with AcquireTokenSilent to get the access token and not while getting the ID token. WithBroker is set to true, although our tenant doesn't use brokers like Authenticator app, but other tenants which use the app do.

**Comment by bgavrilMS** [comment]
We should not be changing the correlation ID but in any case, this is a major issue from a functional perspective. We use correlation IDs only for logging purposes, so that you can track the correlation between various auth SDKs and services. It looks like the broker might be overriding the correlation ID that you pass in. 

It is just a warning, it has no runtime effect. Are you seeing an exception?

related bug: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1805

**Comment by negberts** [comment]
Well, after that the access token that is generated does not give acccess to the API. This is happening both in MSAL as in ADAL. But because it happened in ADAL I tried migrating to MSAL exactly because of the related bug you mentioned. 

I've tried another version with broker support disabled and I get the same error. 

I will try to investigate some options further...

**Comment by bgavrilMS** [comment]
MSAL only fetches tokens, so as long as you received a token MSAL's job is done. You can inspect the token at https://jwt.ms/ 
The token should be identical whether you use the broker or not.

**Comment by negberts** [comment]
@bgavrilMS thank you for your quick responses. In the end it appeared the resource/scope is case sensitive. So https://pimota.onmicrosoft.com/PimApi is a different resource than https://pimota.onmicrosoft.com/pimapi which I find a bit surprising, but okay. I did a tolower() on both sides and now it is working.

**Comment by bgavrilMS** [comment]
Yeah, I also find it a bit surprising when a system is treating Uri in case sensitive way by default :(. Seems to happen a lot.
