### ISSUE TITLE
B2C token validation by MSAL library

### ISSUE THREAD

**Issue by rajesh-naik-by** [AzureAD/microsoft-authentication-library-for-dotnet#1934]
**Is your feature request related to a problem? Please describe.**
I have a generic question about token validation from msal library for dotnet, does msal library takes care of validating below attributes from the token? or is it a responsibility of consumer to validate the token?

- Signature
- exp
- nbf
- iss
- aud

**Describe the solution you'd like**
I would like to have token is being validated by msal library itself.

**Describe alternatives you've considered**
I have asked our application team to validate the tokens at their end using RSA/jwt decoding libraries.

**Comment by neha-bhargava** [comment]
@rajesh-naik-by  MSAL does not validate or decode the access token and neither should the application team decode the access token. There is middleware library to validate the token. @jmprieur, @GeoK Any suggestions?

**Comment by jmprieur** [comment]
@neha-bhargava is right. MSAL.NET is a token acquisition library (which can acquire tokens which are not even JWT, BTW)
Only the Web API for which the token was acquire should validate tokens,  you need to use https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki

Note that this library is used by ASP.NET and ASP.NET Core
For more information, see https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview and the following articles
