### ISSUE TITLE
[Bug] [UWP] Sign in with Apple has stopped working in Xamarin UWP

### ISSUE THREAD

**Issue by kevcrooks** [AzureAD/microsoft-authentication-library-for-dotnet#1939]
We have recently noticed that our sign-in with Apple policy (following the instructions here: https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-apple) has stopped working. 

When we click on the policy to open the sign in page, there's a brief spinner and then a blank screen, with just the "Connecting to a service" box at the top.
![image](https://user-images.githubusercontent.com/10667683/87560230-262ab480-c6b3-11ea-9d16-84672c424c55.png)

- We use the same logic for other authentication providers (Microsoft, Google and Local), which are all working as before, and the popups is working fine for these.

- Our other platforms use the same sign in logic (Xamarin Android, iOS and Mac), and these are continuing to work fine using the Apple Sign-in, so it's just UWP that it's not working for.

- We haven't changed this logic for a while, so we're not sure what may have changed to break this, and have tried reverting the packages to earlier versions as well, but we have the same problem. We are currently on the latest version of `Microsoft.Identity.Client` 4.16.1 (we also use `Microsoft.Identity.Client.Extensions.Msal` 2.12.0)

**Comment by jennyf19** [comment]
@kevcrooks thanks for notifying us. MSAL .NET does not control the UI, maybe something changed on the B2C side or w/Apple. @adamstoffel do you have any thoughts on this? thanks.

**Comment by bgavrilMS** [comment]
This was fixed by the B2C team.

**Comment by kevcrooks** [comment]
Great, thank you very much @bgavrilMS for the update - I've checked and confirm this is now working for us
