### ISSUE TITLE
Implement POP (SHR) for confidential client

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1946]
What MSAL implements today: 

- [WithProofOfPossession](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/67325c7cabb9e4dbccc32c6764c865f088b8f3ad/src/client/Microsoft.Identity.Client/ApiConfig/AbstractPublicClientAcquireTokenParameterBuilder.cs#L43) API
- this is available on .NET desktop for public client only
- there exists an internal interface `IPoPCryptoProvider` for key management
- key management is done by storing key on disk in a container (similar to DPAPI protection)

Tasks to complete: 

### First deliverable

1. Add an implementation of `IPoPCryptoProvider` that stores key in memory statically. Keys must be recycled every 8h. This should be the default implementation.
2. Expose public API on .net core and on confidentuil client

**Comment by bgavrilMS** [comment]
CC @henrik-me - a spec for the PoP work

**Comment by trwalke** [comment]
Continuing in Part 2 (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2013)

**Comment by trwalke** [comment]
fixed in [Release 4.18.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.18.0)
