### ISSUE TITLE
ID token related information is lost in the second call of AcquireTokenOnBehalfOf 

### ISSUE THREAD

**Issue by lnhzd** [AzureAD/microsoft-authentication-library-for-dotnet#1950]
To reproduce the issue, make 2 consecutive OBO calls with the same scope and same user assertion:

var result1 = Await this.confidentialApp.AcquireTokenOnBehalfOf(scopes, userAssertion).ExecuteAsync().ConfigureAwait(false);
var result2 = Await this.confidentialApp.AcquireTokenOnBehalfOf(scopes, userAssertion).ExecuteAsync().ConfigureAwait(false);

result1 has ID token, tenantId, uniqueId, accountName, etc populated
result2 has none of them populated.

2nd call seems to be getting token from cache, but ID token related information not populated on autehtnicationResult.
Is this by intention?

Thanks.

**Comment by bgavrilMS** [comment]
No, this is a bug, will get it fixed asap. 

OBO call actually looks in the token cache because it tries to find access tokens associated with the same assertion. It seems that when looking into the cache, we find the access token but we don't look for the idtoken.

**Comment by jmprieur** [comment]
@bgavrilMS is there enough information in the ID token to get the home tenant id ?

**Comment by bgavrilMS** [comment]
The IDToken contains `oid` and `tid`, but I am not sure if the `tid` is the "home tenant id" ... it probably is though.

Why do you ask?

**Comment by jmprieur** [comment]
to understand if we could surface the IAccount.

**Comment by bgavrilMS** [comment]
I am afraid there isn't enough information for this. Imagine you do `AcquireTokenOBO(scope, assertion)` ... MSAL has to first read the cache and try to find an access token and ID token. But we don't have enough information to figure out `home_tenant_id` at this point

**Comment by jmprieur** [comment]
@lnhzd why do you need the ID token? for a service to service call? do you mind explaining your scenario (out of curiosity)

**Comment by lnhzd** [comment]
> @lnhzd why do you need the ID token? for a service to service call? do you mind explaining your scenario (out of curiosity)

not exactly our scenario but to simplify it: for logging purpose - so logging is associated with the user context.
I am aware that the information we need (e.g.: preferred_username claim, oid) can be extracted from the access token as well - but the way we USED to do it is to get an access token for calling SQL Azure (down stream service) whenever we need the display name - a bit lazy but the theory is we need to get access token for the downstream service anyway, it's easy just to get them from the typed object rather than going through raw claims.

not needed anymore (and probably not the right way to do it in the first place) - we now extract that information from the incoming access token and then stick it on an asynlocal provider.

**Comment by jmprieur** [comment]
cc: @bgavrilMS @jennyf19 @pmaytak

**Comment by jmprieur** [comment]
@lnhzd this released in MSAL.NET 4.17.1 yesterday
