### ISSUE TITLE
PublicClientApplication.AcquireTokenSilent.ExecuteAsync() throws System.ArgumentException after Token expiration if Token does not contain an upn Attribute (Shibboleth)

### ISSUE THREAD

**Issue by klemensurban** [AzureAD/microsoft-authentication-library-for-dotnet#1954]
**Which Version of MSAL are you using ?**
MSAL 4.16.1.0

net45

Desktop / Mobile
    * [x] Interactive with ADFS2019 + federated SAML Claims Provider

c. This is a new app resp. previous App with ADAL 
-->

**Repro**

```csharp
            IEnumerable<IAccount> accounts = await publicClientApplication.GetAccountsAsync();
            IAccount account = accounts.FirstOrDefault();

            {
                authenticationResult = await publicClientApplication
                    .AcquireTokenSilent(adfsScopes, account)
                    .ExecuteAsync();
            }
```

**Expected behavior**

.AcquireTokenSilent(adfsScopes, account).ExecuteAsync() 
should return authenticationResult with a new valid Access- and ID-Token based on the refresh token after Expiration of the AccessToken

**Actual behavior**
.AcquireTokenSilent(adfsScopes, account).ExecuteAsync() 
throws System.ArgumentException (HResult = 0x80070057); Message; userPrincipalName does not contain @ character

**Additional context  !!!!
In the actual case, ADFS2019 is used as IDP, whereby the user does not authenticate directly to the ADFS but to a Shibboleth IDP integrated via ClaimProvider Trust. In the SAML token a persistentID is provided which is used as anchor claim, but no User Principal Name (UPN) is available. 
Since no UPN is available, the object account contains after calling
IAccount account = accounts.FirstOrDefault(); 
  the string "Missing from the token response" in the field "Username"
As long as the access token has not expired, AcquireTokenSilent returns the expected authenticationResult with valid access and ID tokens; If the access token has expired, the exception documented above occurs.

As a workaround, I used a custom IAccount implementation that encapsulates the original object when calling AcquireTokenSilent and always returns null for the Username field if the original string does not match the UPN pattern  (string@string). With this workaround, AcquireTokenSilent returns the expected authenticationResult with a new access and ID token

**Possible Solution**
Microsoft.Identity.Client.Account.Username should return null if no upn is available and not/never a string like "Missing from the token response" which is actually an error message and also contradicts the Sytax of a UPN

**Comment by bgavrilMS** [comment]
The "Possbile Solution" is correct, but a breaking change. Closing as workaround exists.
