### ISSUE TITLE
Support for regional ESTS.

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1956]
To increase the reliability, availability and perf of Azure, regionalization aims to keep all trafic inside a geographical area. For example, if an app needs to fetch data from Key Vault in WestUs2, all the traffic this entails - including MSAL generated traffic - should stay in WestUs2.

Proposal
The following proposal is an algorithm composed of several steps. Step 1 introduces new public API and has a discussion point.

Step 1
MSALs must provide the ability to configure regional
- cca.AcquireTokenForClient().WithAzureRegion(false).Execute()

Step 2
MSAL discovers the region
- by reading ENV variable REGION_NAME (works for Azure Functions)
- by making a call to the [local IMDS endpoint](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#instance-api)  (works for Azure VMs)
- otherwise fail with a meaningful exception

Step 3
MSAL computes the regional authority based on original authority.
- For the public cloud, the env is region + login.microsoft.com. Sovereign clouds are not yet supported, and MSAL should just throw.
- Regional authority: https://westus2.login.microsoft.com/12345-6789

Step 4
MSAL performs an instance discovery call to https://westus2.login.microsoft.com/common/discovery/instance 
- If the call succeeds, then proceed with using the preferred_network, preffered_cache and aliases.
- If the call fails, then proceed with using https://westus2.login.microsoft.com/12345-6789/  as a known authority, i.e. as if the instance metadata is:
`  "metadata": [
    {
      
      "preferred_network": "westus2.login.microsoft.com",
      "preferred_cache": "westus2.login.microsoft.com", 
      "aliases": [ " westus2.login.microsoft.com" ]
    },`

Additional details can be found here: [AAD SDK Proposal to Pin Auth to region.md](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=%2FPinAuthToRegion%2FAAD%20SDK%20Proposal%20to%20Pin%20Auth%20to%20region.md&_a=preview&version=GBdev)

**Comment by trwalke** [comment]
fixed in [Release 4.18.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.18.0)
