### ISSUE TITLE
OBO question.

### ISSUE THREAD

**Issue by cbrianball** [AzureAD/microsoft-authentication-library-for-dotnet#1964]
### Documentation Related To Component:
Exceptions

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
All documentation on how to handle `MsalUiRequiredException` appear to assume the `PublicClientApplication` type is used and not the `ConfidentialClientApplication`, which does not have the `AcquireTokenInteractive` method.

I assume since I'm trying to obtain a token to act on behalf of a user, I should call `AcquireTokenOnBehalfOf`, but that requries a `UserAssertion`, and I don't believe I have access to the token; what's the proper way of constructing a `UserAssertion` in this scenario?

**Comment by bgavrilMS** [comment]
Hi @cbrianball - I think the question here is - what are you trying to do ? 

With regards to the UIRequiredException, this can be thrown by `AcquireTokenSilent` when MSAL and AAD detect that interaction is required (e.g. security policies have changed, you ask for more scopes and user needs to consent etc. etc.). If you use a public client (win forms, wpf, console app) then you'd call `AcquireTokenInteractive`. Websites use a slightly different flow, where the website middleware gets an auth code (no need for MSAL) and MSAL can intervene and exchange it for an access token. 

I'd recommend you start looking at the scenarios and samples: https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code

For asp.net core, we have a library that does most of the heavy lifting https://github.com/AzureAD/microsoft-identity-web

**Comment by jmprieur** [comment]
If you're using ASP.NET Core, you might also be interested in this article: https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access
and this sample: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

**Comment by cbrianball** [comment]
Thanks for the info!
