### ISSUE TITLE
[Enhancement] AcquireTokenSilent should not return token acquired by OBO

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#1966]
**Which Version of MSAL are you using ?**
4.17.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ x ] OBO

**Expected behavior**
`AcquireTokenOnBehalfOf` does a cache lookup with a filter on the token hash of the token incoming to the Web API, and therefore it's not needed to call `AcquireTokenSilent`.
If `AcquireTokenSilent` is called, it should not return the OBO tokens. 

**Possible solution**

Make `AcquireTokenSilent` not return OBO access tokens (these have an assertion hash associated).
See @bgavrilMS's suggestion here : https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1349#issuecomment-647425964

**Comment by jmprieur** [comment]
cc: @bgavrilMS @jennyf19

**Comment by bgavrilMS** [comment]
I can make `AcquireTokenSilent` not return existing ATs that have associated assertion hash. But I can't make `AcquireTokenSilent` refresh the RT :(, so `AcquireTokenSilent` will still succeed. Unless AcquireTokenSilent is also configured with an assertion hash which would probably solve some of the OBO issues :).

Not sure this can be implemented, but M.I.W can do the right thing.

**Comment by jmprieur** [comment]
@bgavrilMS but OBO would refresh the token ? if ATS is not used?

**Comment by bgavrilMS** [comment]
No, OBO would make a token request on the user assertion. ESTS will response with the typical (AT, RT, IdT)

**Comment by bgavrilMS** [comment]
I think that with OBO, we should never use the RT... Maybe that's an alternative fix, OBO should not save the refresh token from EVo....

**Comment by henrik-me** [comment]
We should be absolutely sure we are not breaking anything when making this change. 
@jmprieur : would be good to have the scenario you are trying to solve fixed. I don't from this description understand why we would not want to return the obo token.

**Comment by jmprieur** [comment]
@bgavrilMS, now that we'll have OBO refresh the tokens, don't we want to do something here?

**Comment by bgavrilMS** [comment]
I think might be a breaking change @jmprieur, especially for people using a flat token cache. Maybe we move it to MSAL 5?

**Comment by bgavrilMS** [comment]
This was done.
