### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by OblivionSY** [AzureAD/microsoft-authentication-library-for-dotnet#1974]
### Documentation Related To Component:
MSAL / IMAP

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
I would like to see an example of a console app requesting a token which it can save for use later (next time it runs) so that it can re-authenticate without user interaction (offline_access?). Since the credentials grant flow is not supported when accessing IMAP (https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth). I would like to see the example where a user authenticates interactively, and then the response is stored, such that when the app next runs (5 minutes later, 5 hours later) it can use the tokens previously obtained to request a current authorised token). If there is such a sample, can it be linked to the IMAP page I referenced

**Comment by bgavrilMS** [comment]
Please have a look at MSAL sample page - https://docs.microsoft.com/en-gb/azure/active-directory/develop/sample-v2-code 
Most of our samples show you how to configure MSAL to persist the token cache. You can start with the Desktop (WPF) sample to see the calling patterns

**Comment by OblivionSY** [comment]
Thank you! I didn't check the WPF ones, but actually was the most helpful. Really appreciate the prompt response.

**Comment by bgavrilMS** [comment]
No prob. If yo are interested in .net core / Linux and Mac support, we have a published a token cache for public clients here: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet . Just for Windows it's easier to use the one in the sample.
