### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by JavaSergo** [AzureAD/microsoft-authentication-library-for-dotnet#1975]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Comment by jennyf19** [comment]
@JavaSergo Which documentation are you referring to? This issue is incomplete at the moment. Thanks.

**Comment by jennyf19** [comment]
closing, but please reopen with the necessary information to investigate or act. thank you.
