### ISSUE TITLE
[Feature Request] NEL integration with MSAL

### ISSUE THREAD

**Issue by KatherineHe15** [AzureAD/microsoft-authentication-library-for-dotnet#1983]
### Customer Value ###
MSAL customers need to be able to access the Identity network, and any outages in the network can have a profound impact on said customers. Outages can be caused by issues that can't be detected server-side, so without a client-side monitoring mechanism, the response to the outage is delayed. To decrease the effects of this, and to elevate our customers' experience, we need a fast and accurate solution. While there are already mechanisms in place, some have proven to be very costly. This is where NEL comes in.

### What is NEL? ###
Network Error Logging (NEL) is a W3C standard that can provide Microsoft with real-time application availability data from our end users. Some errors, like failed DNS lookup and a connection timeout, cannot be detected purely server-side, but with NEL, the errors can be detected and reported back to Microsoft through internal reporting services. More information on NEL can be found [here](https://w3c.github.io/network-error-logging/).

### Why should this be integrated? ###
As stated above, NEL provides Microsoft real-time client-side availability data. With this data, Identity teams can diagnose a variety of network health issues, including:
- Was there a DNS hijack?
- With the new DNS rollout, were there any reachability issues?
- Has Identity been blocked in a certain region?

Answers to questions like those above allow Microsoft to better service all customers with little to no cost.

### How should this be integrated? ###
This project, built in C# on .NET Core 3.1, can use MSAL's HTTP extensibility for integration. The beginning of the code is as follows:
```
public class Client : DelegatingHandler
{
   private static readonly HttpMessageHandler Handler = new SocketsHttpHandler
    {
        // first 3 values are from MSAL github. using SocketsHttpHandler because that's what MSAL NetCoreHttpClientFactory has
        // https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreHttpClientFactory.cs
        PooledConnectionLifetime = TimeSpan.FromMinutes(1),
        PooledConnectionIdleTimeout = TimeSpan.FromMinutes(1),
        MaxConnectionsPerServer = 30,
        ConnectTimeout = TimeSpan.FromMilliseconds(3000),
    };

    private static readonly HttpClient Httpclient = new HttpClient(Handler);

    ...
}
```
The project code currently sits in an [internal Microsoft repo](https://msazure.visualstudio.com/One/_git/ad-FUN-idsr?version=GBtkah%2Fmsalnelintegration&path=%2Fsrc%2Ftools%2Fprototype%2Fnelclient) that is owned by the Identity Platform Network SRE Team.

### Performance Impact ###
If the client is set to off, there will be no performance impact, as the client will simply return to the application immediately. Initially, the client is automatically set to off, so there will be no performance impact upon cold start. With normal functionality, the client makes a minimum of 4 extra HTTP calls: two to download the two headers needed to have all of the relevant NEL information, one to mimic the original call, and one to upload reports. In most cases, there should be no performance impact, as the client runs very quickly; for example, with preliminary testing, receiving a application.ok report took 11 ms, and receiving a dns.name_not_resolved report took 33 ms. If there is an error like a tcp.timeout, the application will be slowed down, as it'll take the client a while to recognize this error. Having a large report queue and policy cache could also create performance issues. However, I don't foresee either happening frequently, or happening at all, as there are already mechanisms in place to counteract such situations.

### Future of this project ###
First and foremost, after further preparation, we'd love to see the project piloted on a live MSAL application. Down the line, we'd also like to add more to the client for the purpose of getting more information about the network and its health.

**Comment by bgavrilMS** [comment]
1. Since NEL is sever-side driven, the first requirement is to have the STS integrate with it
2. MSAL allows developers to [use their own HttpClient ](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-provide-httpclient). Apps willing to try this out can simply plug in the NEL client integration code by injecting a custom HttpClinetHandler. There are no changes needed on MSAL.

@KatherineHe15  - could you please point us at the repo for your work, even if it is private?

**Comment by bgavrilMS** [comment]
Also, @KatherineHe15 - could you provide an estimate performance impact on an app willing to use NEL:

- cold start, i.e. application just starts and needs to download policies etc.
- normal functionality, i.e. how many extra HTTP calls are performed by the app

**Comment by KatherineHe15** [comment]
Hi @bgavrilMS , I've updated the issue to address your comments!

**Comment by bgavrilMS** [comment]
There is no work on MSAL side, as we already expose HttpClient.
