### ISSUE TITLE
[Bug] WsTrust federation error isn't being returned

### ISSUE THREAD

**Issue by jabbera** [AzureAD/microsoft-authentication-library-for-dotnet#1985]
**Which Version of MSAL are you using ?**
4.17.1

**Platform**
Windows

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [X] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL, but started seeing this issue

**Repro**

I don't know how to repro the issue but we are getting the following exceptions thrown:
One or more errors   occurred.>>Federated service at https://autologon.microsoftazuread-sso.com/<SNIP>/winauth/trust/2005/windowstransport?client-request-id=<SNIP>   returned error:

Notice the "returned error:" doesn't include any additional information. I'm assuming this is because:     https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dbab65dc2000275afa4b72045d7a775fa08b9909/src/client/Microsoft.Identity.Client/WsTrust/WsTrustResponse.cs#L23 has some sort of bug but without the body it's really hard to tell what's going on.

**Expected behavior**
Error information should ALWAYS be returned and if it cannot be determined the whole body should be returned.

**Actual behavior**
Error information fails to parse and the error is lost

**Possible Solution**
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1984

**Comment by trwalke** [comment]
Fixed in 4.18.0
