### ISSUE TITLE
[Feature Request] netstandard 2.0 or 2.1  support

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1991]
**Is your feature request related to a problem? Please describe.**
Customers are asking for a more capable .net standard version of MSAL, which allows for interactive flow. Some scenarios are: 

- MSAL usage in plugin scenarios - e.g. if I want to write a roslyn analyzer, it will be consumed by .net classic or by .net core but this is not known until my analyzer is deployed into VS or run via command line. In this case, we can only rely on MSAL .netstandard

- Similar to the above scenario, PowerShell also has pretty complex logic to switch between .net classic and .net core. 

- With Unity, only the netstandard version can be consumed (by unzipping the nuget package and selecting the DLL). We can improve the experience by offering a more capable netstandard

- For Blazor applications

**Describe the solution you'd like**
.net standard version of MSAL.

**Comment by jmprieur** [comment]
@bgavrilMS : would that issue be related as well to the suppression of the reference library?

**Comment by bgavrilMS** [comment]
Not so much...
