### ISSUE TITLE
[Feature Request] Improve logging

### ISSUE THREAD

**Issue by jonpayne** [AzureAD/microsoft-authentication-library-for-dotnet#1993]
Logging at `LogLevel.Info` is too verbose and the logs are unstructured. A simple request to get a token using a client secret logs 18 events. In a service that requests many tokens, writing 18 events per token request adds a lot of noise to the service logs.

Logs are sent to the `LogCallback` delegate as an unstructured string. In a service that has structured logs, passing the date, time, OS version and library version as a single string on each request adds a lot of duplication and makes the logs hard to integrate with other service logging.

**Describe the solution you'd like**
- Change `LogLevel.Info` to log just a summary of a token request, for example one event when the request is started containing the request details and a second event when the request succeeds / fails containing the response details and the caching behavior
- Move the logs for each step of the token acquisition process to `LogLevel.Verbose`
- Pass the log details to `LogCallback` as a structure rather than a string, separating out the various parts into fields
- Give event names or event IDs to the various events to allow services to filter events

**Describe alternatives you've considered**
- Parsing the log string with a regular expression to extract the useful data
- Only writing logs at `LogLevel.Warning` and `LogLevel.Error` to service logs and logging requests by injecting a handler into the HTTP pipeline

**Comment by bgavrilMS** [comment]
We would probably need to introduce another LogCallback delegate to be able to do this, but I am in favour of doing it. Needs some spec.

**Comment by pschaeflein** [comment]
The rest of the Azure SDK for .Net uses an EventSource for logging instead of a callback. 
https://docs.microsoft.com/en-us/dotnet/azure/logging
I would prefer a consistent approach.

**Comment by bgavrilMS** [comment]
MSAL is not part of the Azure SDK, but Azure SDK uses MSAL for most of its identity flow. 
That said, you are free to define whatever logging mechanism you wish, including EventSource, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

`enableDefaultPlatformLogging: true` uses EventSource on .NET (FWK and Core) 

Will this work?

**Comment by pschaeflein** [comment]
Sorry I wasn't clear - I would prefer not to write code that listens on an AzureEventSource **and** a logging callback from MSAL. 

The location of AAD/MSAL/Azure in the greater Microsoft organization is not relevant to most consumers of the SDK. I just want to add value to my customers by consuming the services. Increasing the amount of code that I need to write and maintain is not a goal of any SDK. 

If you are making changes to the logging capabilities of this library, I **strongly** urge you to consider adopting an approach that simplifies the task of the consumers

**Comment by bgavrilMS** [comment]
I agree that from an organizational point of view, it does not matter if MSAL is part of Azure SDK or not. But from a package dependency point of view, it does. MSAL will not take a dependency on `AzureEventSource` or any other Azure building blocks. Whenever we add a new dependency to MSAL, we break people due to diamond dependency issues. MSAL is at a lower level than Azure SDK. The idnentity part of Azure SDK is consistent, but MSAL as a building block is not.

Do you have a suggestion of how to bridge the two?

**Comment by pschaeflein** [comment]
Ah yes, I understand the dependency bit. A purist would argue that Logging is a building block as well, but I am a pragmatist.

If MSAL could move closer to a similar approach, that would help consumers. Maybe an event source or yours. I would just prefer to not have multiple classes in my app that are just capturing diagnostics. 

Thanks for the discussion.

**Comment by bgavrilMS** [comment]
We've added a new logging mechanism - `WithLogging(IIdentityLogger)`. This allows you to dynamically set the event level. It also exposes correlation ID separately. 

Please set the level at Warning and change it to Verbose if you run into issues.
