### ISSUE TITLE
[Bug][Internal][S] SSH integration test failing 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2004]
Test: Interactive_SSHCert_Async

Failure message: 

 Test method Microsoft.Identity.Test.Integration.SeleniumTests.InteractiveFlowTests.Interactive_SSHCert_Async threw exception: 
    Microsoft.Identity.Client.MsalServiceException: AADSTS29007: The permission (scope) list Agreement.Read.All Agreement.ReadWrite.All AgreementAcceptance.Read AgreementAcceptance.Read.All AllSites.FullControl AllSites.Manage AllSites.Read AllSites.Write AppCatalog.ReadWrite.All AuditLog.Read.All Bookings.Manage.All Bookings.Read.All Bookings.ReadWrite.All BookingsAppointment.ReadWrite.All Calendars.Read Calendars.Read.All Calendars.Read.Shared Calendars.ReadWrite Calendars.ReadWrite.All Calendars.ReadWrite.Shared Contacts.Read Contacts.Read.All Contacts.Read.Shared Contacts.ReadWrite Contacts.ReadWrite.All Contacts.ReadWrite.Shared Device.Command Device.Read DeviceManagementApps.Read.All DeviceManagementApps.ReadWrite.All DeviceManagementConfiguration.Read.All DeviceManagementConfiguration.ReadWrite.All DeviceManagementManagedDevices.PrivilegedOperations.All DeviceManagementManagedDevices.Read.All DeviceManagementManagedDevices.ReadWrite.All DeviceManagementRBAC.Read.All DeviceManagementRBAC.ReadWrite.All DeviceManagementServiceConfig.Read.All DeviceManagementServiceConfig.ReadWrite.All Directory.AccessAsUser.All Directory.Read.All Directory.ReadWrite.All EAS.AccessAsUser.All EduAdministration.Read EduAdministration.ReadWrite EduAssignments.Read EduAssignments.ReadBasic EduAssignments.ReadWrite EduAssignments.ReadWriteBasic EduRoster.Read EduRoster.ReadBasic EduRoster.ReadWrite email EWS.AccessAsUser.All Exchange.Manage Files.Read Files.Read.All Files.Read.Selected Files.ReadWrite Files.ReadWrite.All Files.ReadWrite.AppFolder Files.ReadWrite.Selected Financials.ReadWrite.All Group.Read.All Group.ReadWrite.All IdentityProvider.Read.All IdentityProvider.ReadWrite.All IdentityRiskEvent.Read.All Mail.Read Mail.Read.All Mail.Read.Shared Mail.ReadWrite Mail.ReadWrite.All Mail.ReadWrite.Shared Mail.Send Mail.Send.All Mail.Send.Shared MailboxSettings.Read MailboxSettings.ReadWrite Member.Read.Hidden MyFiles.Read MyFiles.Write Notes.Create Notes.Read Notes.Read.All Notes.ReadWrite Notes.ReadWrite.All Notes.ReadWrite.CreatedByApp offline_access openid People.Read People.Read.All People.ReadWrite PrivilegedAccess.ReadWrite.AzureAD PrivilegedAccess.ReadWrite.AzureResources profile Reports.Read.All SecurityEvents.Read.All SecurityEvents.ReadWrite.All Sites.FullControl.All Sites.Manage.All Sites.Read.All Sites.ReadWrite.All Sites.Search.All Subscription.Read.All Tasks.Read Tasks.Read.Shared Tasks.ReadWrite Tasks.ReadWrite.Shared TermStore.Read.All TermStore.ReadWrite.All User.Export.All User.Invite.All User.Read User.Read.All User.ReadBasic.All User.ReadWrite User.ReadWrite.All UserActivity.ReadWrite.CreatedByApp UserTimelineActivity.Write.CreatedByApp is missing user_impersonation
    Trace ID: ba06f002-d344-4f03-be8a-11479b183f00
    Correlation ID: f2aae3a3-1c38-4e6c-969d-28c5dedc9527
    Timestamp: 2020-08-19 15:02:59Z

at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/a3d3f99f61601e6ce5636bca7698cb7ae1862a6f/tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/SSHCertificateTests.cs#L45

**Comment by neha-bhargava** [comment]
This is a server error. Created an icm for ests: https://portal.microsofticm.com/imp/v3/incidents/details/209099217/home

**Comment by jmprieur** [comment]
@neha-bhargava : the icm says: "not an incident". Is it something that has changed in our tests? or in our code? why did the test start failing?

**Comment by neha-bhargava** [comment]
@jmprieur They have pointed me to a person in their team whom I am asking the details. Even I have this question. From the conversation it seems that we are not passing correct resource identifier.

@bgavrilMS was this test passing before?

**Comment by bgavrilMS** [comment]
This test was passing before.

**Comment by neha-bhargava** [comment]
Then maybe this is something to confirm with the lab team. If something is changed with this app or user permissions for this app

**Comment by neha-bhargava** [comment]
Created a task for the lab team: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1184052

**Comment by bgavrilMS** [comment]
@rayluo  investigated this problem: 

`
FYI: I got the SSH-cert unit test case working again. The trick is to use this scope: https://pas.windows.net/CheckMyAccess/Linux/user_impersonation
`

**Comment by trwalke** [comment]
Adding the above scope did not resolve the issue, I am reaching out to Ray to get his input.

**Comment by rayluo** [comment]
Later I realized that there are more requirements than the scope value. You would also [need a specific client_id](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.12.0/tests/test_e2e.py#L216-L217). BTW, the [entire e2e test setup is in line 197 to line 236](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.12.0/tests/test_e2e.py#L197-L236). Some inline comments talked about some of those requirements.

**Comment by trwalke** [comment]
Thanks @rayluo, Ill try this out
