### ISSUE TITLE
Microsoft.Identity.Client and getting rid of System.Windows.Forms reference

### ISSUE THREAD

**Issue by swidz** [AzureAD/microsoft-authentication-library-for-dotnet#2009]
I am working on an integration library that references Microsoft.Identity.Client (I have also tried to use older implementation Microsoft.IdentityModel.Clients.ActiveDirectory)

My library type is .Net Standard 2.0

If my library is referenced in .Net Core Class Library project then the build references Microsoft.Identity.Client which does not include reference to System.Windows.Forms

If my library is referenced in .Net Framework 4.6.1 Class Library project then the build references Microsoft.Identity.Client which does include reference to System.Windows.Forms

The customer has asked to prepare .Net Framework 4.6.1 library that can be linked in their ERP software which includes a webserver. It seems that the webserver application during startup runs some sort of validation before loading external libraries and checks if non of them is referencing System.Windows.Forms. In my case the webserver rejects the libraries.

I cannot build the libraries as .Net Core as it will not be compatible with the web application. I must use .Net Framework 4.6.1

Is there a solution to this problem?

**Comment by henrik-me** [comment]
@swidz  We are not planning on removing the reference to winforms for the net desktop target. however we are planning on supporting embedded webviews on netcore via custom ui. Closing, if you need more information please reopen and let us know

**Comment by pedrolupin** [comment]
Microsoft.Identity.Client 4.49.1 did not have a dependency on System.Windows.Forms, but when updating to newer Azure.Identity 1.10.4 -> Microsoft.Identity.Client 4.56.0 the dependency to Windows.Forms appeared, this is a problem
