### ISSUE TITLE
[Feature Request] Implement POP (SHR) for confidential client bringing your own keys (#2)

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2013]
What MSAL implements today: 

- [WithProofOfPossession](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/67325c7cabb9e4dbccc32c6764c865f088b8f3ad/src/client/Microsoft.Identity.Client/ApiConfig/AbstractPublicClientAcquireTokenParameterBuilder.cs#L43) API
- this is available on .NET desktop for public client only
- there exists an internal interface `IPoPCryptoProvider` for key management
- key management is done by storing key on disk in a container (similar to DPAPI protection)

Tasks to complete: 

### First deliverable
1. Refactor WithProofOfPossession public API to be more like MSAL Android's implementation ([api](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/PoPAuthenticationScheme.java) and [example](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/testapps/testapp/src/main/java/com/microsoft/identity/client/testapp/MsalWrapper.java#L122-L125)) and take into consideration the fact that **Method** and **Url** are optional.

### Second deliverable

2. [Needs discussion] Refactor `IPoPCryptoProvider` interface to provide a higher level abstraction. The current `CannonicalPublicKeyJwk` is pretty low level. Or maybe it's ok as Wilson can plugin here. 
3. Make IPoPCryptoProvider class public and expose a new overload of `WithProofOfPossession` that takes in a `IPoPCryptoProvider` so that customers can define their own key management.

**Comment by trwalke** [comment]
Continuation of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1946

**Comment by jmprieur** [comment]
@trwalke do we need to do more ?

**Comment by bgavrilMS** [comment]
@jmprieur - the second deliverable is around exposing an interface that enables users to bring their own POP keys. 
I'd say that a 3rd deliverable is to align our public API to the Android API, which has been approved in Api Reviews.

**Comment by bgavrilMS** [comment]
Blocked on spec.
