### ISSUE TITLE
Unable to hide tool bar - Cancel & Done button for IOS and Sign In Title bar for Android

### ISSUE THREAD

**Issue by Coder-RKV** [AzureAD/microsoft-authentication-library-for-dotnet#2014]
Using .WithEmbeddedWebView does not allow to customize to hide the tool bar options - Cancel and Done button for IOS and Title Bar in Android.

**Comment by jennyf19** [comment]
@iambmelt how do you guys handle this in native Android?

**Comment by iambmelt** [comment]
@Coder-RKV @jennyf19 If you'd like to hide the title bar on Android, you can apply a `theme` in your application's `AndroidManifest.xml` to the relevant `Activity` -- an example of how to apply a theme can be found [here](https://stackoverflow.com/a/3752646). Note you will need to apply a theme that does not display the title bar.

**Comment by Coder-RKV** [comment]
@iambmelt Thank you for your comment.
Applied a theme that doesn't display the title bar

[Activity(MainLauncher = false, Theme = "@style/MyTheme")]
    [IntentFilter(new[] { Intent.ActionView },
        Categories = new[] { Intent.CategoryBrowsable, Intent.CategoryDefault },
        DataHost = "auth",
        DataScheme = "msal[ClientId]")]
    public class MsalActivity : BrowserTabActivity
    {
    }

Doesn't help. The Sign In still shows up.

<img width="358" alt="Screen Shot 2020-08-27 at 7 06 23 PM" src="https://user-images.githubusercontent.com/1075905/91503450-7e4efc00-e898-11ea-9db9-b46617d698f7.png">

**Comment by iambmelt** [comment]
@Coder-RKV I suggest following up with @jennyf19 -- using the Android library, this is working for me

![image](https://user-images.githubusercontent.com/990063/91505148-c31c6800-e883-11ea-92ba-43a76593cd45.png)

**Comment by jennyf19** [comment]
thanks @iambmelt - we hard code the "sign-in" value. will look into this.

@Coder-RKV can you share a screen shot of the issue for iOS?

**Comment by Coder-RKV** [comment]
Thank you @iambmelt 
This is the sample I am referring to - https://github.com/Azure-Samples/active-directory-b2c-xamarin-native.

@jennyf19 Here's the IOS Screenshot
<img width="327" alt="Screen Shot 2020-08-27 at 8 05 04 PM" src="https://user-images.githubusercontent.com/1075905/91506666-a8a4b780-e8a0-11ea-8464-0ef3b4d109c1.png">

Are there any work arounds with any examples that I can explore? Looks like this would be an enhancement.

**Comment by jennyf19** [comment]
@Coder-RKV i'll have to ask our iOS team...btw...embedded webview is not recommended for B2C, as Google auth is not allowed w/embedded webview, you'd have to use the system browser. We recommend system browser for B2C for this reason. With system browser and B2C, you can customize all the elements of the sign-in screen. Is that what you're looking for?

**Comment by Coder-RKV** [comment]
@jennyf19 The requirement is to give a native app experience to the user since B2C is as of now just utilized for in-house account maintenance for the App. Hence utilized the embedded web view. If using the system browser, we can customize the screen to look like a native screen (I think it pops out in IOS) - like hiding the address bar e.t.c., please guide me to an example of that, I can check that out too.

**Comment by jennyf19** [comment]
@Coder-RKV I see. thanks for the additional information. Here's a [doc](https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview) from B2C on UI customization, if you need more help, let us know and we can put you in touch with someone from B2C.  
Is this what you're looking for on Android?
![image](https://user-images.githubusercontent.com/19942418/91508724-26f75e80-e88d-11ea-986e-ef01c54b018b.png)

**Comment by Coder-RKV** [comment]
@jennyf19 Thank you. We're already using Custom HTML. So that's covered, thanks.

Its great to not see the Sign In text in the above screenshot, we'd want that but without the black bar as well. Basically, the title bar itself to be hidden.

**Comment by jennyf19** [comment]
@Coder-RKV 
![image](https://user-images.githubusercontent.com/19942418/91511484-a0df1600-e894-11ea-9158-9fdbdd8e71a7.png)
I put this in the manifest:
` <application android:theme = "@android:style/Theme.NoTitleBar">`

**Comment by jennyf19** [comment]
@Coder-RKV Here's a link to b2c samples w/the UI customization: https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview#examples

**Comment by Coder-RKV** [comment]
@jennyf19 Thanks a tonne. So this'll be available in the next build or I'd have to try tweaking the manifest for my application (I doubt that's possible as it's already set to a particular style). Per the above comment, I've already tried that with the MSALActivity and that didn't work either.

**Comment by jennyf19** [comment]
@Coder-RKV i don't think it will work w/the "sign-in" label hard coded, but w/that removed, you should be able to tweak things. will be in the next release, as the current release that's being tested (4.18) is already in testing mode, so missed that one. how urgent is this for you?

**Comment by Coder-RKV** [comment]
@jennyf19 Actually it was a little urgent as this is a part of the sprint and the sprint release is slated for 1st September. Thats why I was trying all that I could to achieve this.

**Comment by jennyf19** [comment]
ok. I'll talk w/the team and see what we can do. otherwise, they are on a two week cadence for releases. should know more tomorrow (Friday). @Coder-RKV

**Comment by Coder-RKV** [comment]
Thank you so much @jennyf19

**Comment by Coder-RKV** [comment]
@jennyf19 Could you also please let know about the IOS side? For the Cancel button?

**Comment by jennyf19** [comment]
@Coder-RKV you might be able to use a customer renderer to hide those elements. we don't have a sample showing it though. you'd have to search. if i find anything, i'll let you know.

**Comment by Coder-RKV** [comment]
@jennyf19 Sure thanks, will check.

**Comment by Coder-RKV** [comment]
@jennyf19 Please let me know if we have any update on the timeline?

**Comment by jennyf19** [comment]
@Coder-RKV looks like the team will try to get this out next week. @trwalke will start that process once 4.18 is out the door.

**Comment by Coder-RKV** [comment]
@jennyf19 Thank you, please also keep me posted on the dates by which we can check out the nugget / branch. So that I can also communicate accordingly.
Thank you again.

**Comment by jennyf19** [comment]
sounds like a plan @Coder-RKV

**Comment by Coder-RKV** [comment]
@jennyf19 Any update please.

**Comment by jennyf19** [comment]
@Coder-RKV this will be in the 4.18 release, which should be out sept 2 or 3.

**Comment by jennyf19** [comment]
@Coder-RKV this has been fixed and in release 4.18.

**Comment by trwalke** [comment]
Thanks @jennyf19

**Comment by Coder-RKV** [comment]
> @Coder-RKV this has been fixed and in release 4.18.

Thank you. Implemented and working as expected!
