### ISSUE TITLE
Add telemetry for the region detected.

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#2018]
**Is your feature request related to a problem? Please describe.**
Add telemetry to log the detected region when .WithAzureRegion is set to true.

**Additional context**
As a follow up to [Support for regional ests](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1956), log the region detected or not detected to telemetry.

**Comment by trwalke** [comment]
Resolved in 4.19.0 https://www.nuget.org/packages/Microsoft.Identity.Client/
