### ISSUE TITLE
Need Help In Customising In App Browser Using ICustomWebUi Interface 

### ISSUE THREAD

**Issue by taruns-hexaware** [AzureAD/microsoft-authentication-library-for-dotnet#2023]
### Documentation Related To Component:
ICustomWebUi: Customising  In App Browser For AD B2C Flow
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

I am using AD B2C for my Xamarin form application. I am able to customize the top navigation bar by embedding my own browser however I did not find any way how to return to the application once operation succeed e.g. Sigup/Forgot password. I saw some example that were made for uwp app and they are using url query to decide (code= or error=) the AuthenticationResult. However I am never getting code="" in my url. The final url I am getting like "....../SelfAsserted/confirmed?csrf_token=....". Now sure how can I get the AuthenticationResult from my custom browser. I am using Xamarin form and iOS/Android implementation.

Thanks
Tarun Sharma

**Comment by jmprieur** [comment]
@taruns-hexaware : thanks for raising this issue
I don't think that we have the full coverage of the B2C scenarios when one customizes the Web view.
Adding an enhancement label

**Comment by bgavrilMS** [comment]
Typically when the URI from the browser starts with the redirect URI (which you control / configure), this is when you know that the navigation is complete. It's up to the browser to handle all the redirects etc. 

I know @jennyf19 made some changes to remove the "Sing In" from the title. What other customization do you need?

**Comment by taruns-hexaware** [comment]
Thanks @bgavrilMS 

Does that "Sign-in" thing is released... can we externalise the string like some parameter ? 

Regards
Tarun Sharma

**Comment by bgavrilMS** [comment]
I think we just removed it completely, so there is no title at all.

**Comment by bgavrilMS** [comment]
Commit is https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/4cef956ada53eabe4b633a4ac3e9183de973ad73 - should have already been released.

**Comment by jennyf19** [comment]
@taruns-hexaware @bgavrilMS @jmprieur yes, that has been released. But you can put whatever you want there by editing the [manifest](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/4cef956ada53eabe4b633a4ac3e9183de973ad73#diff-75259b16b33feead706840e7acf66b64R6)

**Comment by jmprieur** [comment]
Also this documentation might help? https://docs.microsoft.com/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet#withcustomwebui
