### ISSUE TITLE
[Internal] Improve the Azure AD build system speed and reliability

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2028]
**Is your feature request related to a problem? Please describe.**
The current build system can be somewhat unstable and can to take up to 40 mins for all tests to run. Tests are run at the end of the build so if they fail, it takes a significant amount of time to rerun the tests to debug issues.

**Describe the solution you'd like**

> Identify sources that are causing instability in the build system and apply mitigations where needed. 

> Divide the test tasks into sub tasks that can run simultaneously to reduce the overall time of the build.

> Ensure that the build system is using all of the latest features/apis to keep the build system up to date.

**Comment by bgavrilMS** [comment]
I've upgraded the tests to run on .net core 3
I've upgraded the test runner to vstest, which results in ~10 min improvement with some tests running in paralel.
I've upgraded the integration tests and ADO will automatically re-run failed tests.
