### ISSUE TITLE
[Feature Request] MSAL Logging should include machine info

### ISSUE THREAD

**Issue by bachoang** [AzureAD/microsoft-authentication-library-for-dotnet#2029]
**Is your feature request related to a problem? Please describe.**
Per discussion with Jenny Ferries and Jean-Marc, customers often run into intermittent issue with AcquireTokenSilent pulling up no account info even though they have already authenticated.  This might be due to the customers not using distributed MSAL Token cache when running the web site in a web farm.  They often will use in memory cache which is instantiated on one machine and not the other so if multiple requests do not get send to the same VM instance then this will be a problem.  MSAL logging having machine info can help root cause these cases.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmprieur** [comment]
@jennyf19 @bgavrilMS @trwalke @neha-bhargava @henrik-me : I think that we should do this (under PII probably) to help the support team?

**Comment by bgavrilMS** [comment]
@jmprieur - not sure what APIs we can use to get the machine info, but otherwise should not be a problem.
