### ISSUE TITLE
[Bug] Editing and saving profile clears cached accounts

### ISSUE THREAD

**Issue by RhomGit** [AzureAD/microsoft-authentication-library-for-dotnet#2031]
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.18.0

**Platform**
.NET Standard 2.0, .NET Framework 4.6.1, WPF

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive B2C 

**Is this a new or existing app?**
The app is in production but updated MSAL version and changed areas of code and are now re-testing.

**Repro**

```csharp
var ar = await pca.AcquireTokenInteractive(this.scopes)
    .WithAccount(account)
    .WithB2CAuthority(AuthB2C.AuthorityEditProfile)
    .WithParentActivityOrWindow(parentActivity)
    .WithPrompt(Prompt.NoPrompt)
    .ExecuteAsync();
```

**Expected behavior**
Saving a profile, closing my app and then restarting will remember the cached user and allow AcquireTokenSilent to succeed.

**Actual behavior**
```csharp
var accounts = await pca.GetAccountsAsync();
```
Saving a profile, close my app. Restart and try and get the accounts via the call above but they are empty.
Requires the user to reauth via AcquireTokenInteractive.

**Comment by jmprieur** [comment]
which token cache serialization did you use, @RhomGit ?
What's the code to create the public client application?

**Comment by RhomGit** [comment]
Hi Jean-Marc,

```csharp
this.scopes = AuthB2C.GetScopes(clientId);

string RedirectUri = $@"msal{this.clientId}://auth";

this.pca = PublicClientApplicationBuilder.Create(this.clientId)
    .WithB2CAuthority(AuthB2C.Authority)
    .WithIosKeychainSecurityGroup("com.microsoft.msalrocks")
    .WithRedirectUri(RedirectUri)
    .Build();

// ITokenCache (SerializeMsalV3) ref: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization
TokenCacheHelper.CacheFilePath = userDir + "msalcache.bin3";
TokenCacheHelper.EnableSerialization(this.pca.UserTokenCache);
```

**Comment by jennyf19** [comment]
@RhomGit are you using your own keychain group or "com.microsoft.adalcache"? If this is on iOS, the tokens will go to the keychain. If you're not on iOS, you don't need this line ` .WithIosKeychainSecurityGroup("com.microsoft.msalrocks")`...which platform are you having the issue on?

**Comment by RhomGit** [comment]
Hi Jenny,

this particular issue is on Windows desktop (I haven't tested other platforms). The iOS bit is in there because I share the MSAL portion of my code across many projects (including a Xamarin Forms mobile app) ... and yes, I need to update the keychain group to my own ;)

**Comment by jennyf19** [comment]
@RhomGit You said this was working previously? which version was working? do you have a repro you can share?

**Comment by RhomGit** [comment]
I honestly couldn't tell you as it has been such a long time (more than a year at the very least). Its a feature that you add in and then never test again until a user reports an issue (or a developer misclicks "Sign Out" and then recognises an issue hehe).

**Comment by jennyf19** [comment]
@RhomGit that's true. lol.

if you can send us a zip file, or point us to a repo, that would help, as in recent testing w/MSAL, I haven't seen this issue.

**Comment by jennyf19** [comment]
@RhomGit i think what I wrote in #2030 will resolve this one as well, but i'm not sure. If you disagree, just provide the repro steps, like you did in the other issue and i'll try it out. looks like the same issue though w/an authority mismatch. MSAL is defaulting to su_si, but you're trying to use an account from edit_profile, but su_si is a separate authorization server from the edit_profile one, so it doesn't know the su_si exists. :/
keep me posted!
