### ISSUE TITLE
[Feature Request / Question] Save, query, remove multiple IAccounts using a custom identifier

### ISSUE THREAD

**Issue by tipa** [AzureAD/microsoft-authentication-library-for-dotnet#2032]
**Describe the solution you'd like**
In my app, I want my users to be able to connect to multiple Microsoft Graph services. More specifically, my users are already able to connect to the MS Graph and grant the app permission to access their OneDrive. Now I also want them to be able to connect to their Outlook calendar so that the app can display their appointments. The user should be able to use either the same account that they already used for connecting to OneDrive, or a completely different account.

In order to distinguish the two I would like to save them separately, Currently, I am just using `(await clientApplication.GetAccountsAsync()).FirstOrDefault()` to retrieve the account being used for the OneDrive integration, but when adding the calendar integration, I couldn't be sure that the account that I receive is the one that the user wants to use for OneDrive or the one for the calendar (in case the user used 2 different accounts for both integrations).
Because the user can also disconnect (or log off) from either the OneDrive or calendar integration, it should also be possible to remove the credentials being used for one integration (OneDrive), while keeping the credentials that are used for the other (calendar). 

To sum it up, I would like to have multiple accounts (`IAccount`s) that can be saved, queried, removed by MSAL based on a (string) identifier that I can specify myself - in my case those identifiers would be "OneDrive" and "Calendars".

**Describe alternatives you've considered**
- I looked at `IClientApplicationBase.GetAccountAsync(string identifier)` but it seems like I cannot specify a custom `identifier` when saving the account but the `identifier` is always the `HomeAccountId.Identifier`
- register an additional client app in Azure
- keep track of what account the user wants to use for which feature in my app. This would increase the complexity of the logic I'd have to implement. Also, I wouldn't be able to just remove the account from the MSAL cache when the user "logs off" from e.g. the OneDrive integration as the account might still be needed by another integration.

**Additional context**
Microsoft.Identity.Client 4.18.0 (UWP + Xamarin)

**Comment by jennyf19** [comment]
> keep track of what account the user wants to use for which feature in my app. This would increase the complexity of the logic I'd have to implement. Also, I wouldn't be able to just remove the account from the MSAL cache when the user "logs off" from e.g. the OneDrive integration as the account might still be needed by another integration.

Yes, this is our current recommendation. We will keep the issue open and see if developers +1 👍 it, so we can gauge the priority & then determine next steps. Thanks for bringing it to our attention.

**Comment by tipa** [comment]
Thanks for your response. Too bad there's no easy solution for this. I might create a new client app in Azure then as this seems to by far the easiest solution...

**Comment by tipa** [comment]
Is this feature request closed because it has been rejected?

**Comment by bgavrilMS** [comment]
I'll let our PM @jmprieur  give a definitive answer, but with MSAL we ask developers to do their own user management, such as remembering which is the "Default" user etc.

**Comment by bgavrilMS** [comment]
No plans to address this as most apps are single account apps. Multiple accounts apps are expected to perform account management themselves.
