### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by joshtransient** [AzureAD/microsoft-authentication-library-for-dotnet#2033]
### Documentation Related To Component:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication
Intgegrated Windows Authentication flow

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
The link https://aka.ms/msal-net-interactive is broken

**Comment by jmprieur** [comment]
#assign jmprieur

**Comment by jmprieur** [comment]
Thanks for the heads-up @joshtransient 
I just fixed it.

#please-close

**Comment by joshtransient** [comment]
That was fast :) Thanks @jmprieur
