### ISSUE TITLE
[Bug] Creating the HttpClient is not thread safe

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#2034]
**Which Version of MSAL are you using ?**
4.18.0

**Platform**
Desktop (verified on net desktop, same issue applies to netcore, and possibly other targets)

**What authentication flow has the issue?**
All flows as this is about the HttpClient

**Is this a new or existing app?**
Existing in prod.

**Repro**
Verified by code inspection: 
src/client/Microsoft.Identity.Client/Platforms/netdesktop/Http/NetDesktopHttpClientFactory.cs
src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreHttpClientFactory.cs
Where the static is created, Should follow the model for Singleton in .net.

**Expected behavior**
It's expected that the code is thread safe

**Actual behavior**
The code is not thread safe

**Possible Solution**
Add a lock for the creation of the static http client

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by trwalke** [comment]
Resolved in 4.19.0 https://www.nuget.org/packages/Microsoft.Identity.Client/
