### ISSUE TITLE
[Feature Request] Ability to append headers on requests to the IDP for code and RT redemption

### ISSUE THREAD

**Issue by hpsin** [AzureAD/microsoft-authentication-library-for-dotnet#2037]
**Is your feature request related to a problem? Please describe.**
In order for our next generation Tenant Restrictions feature to work  securely, web applications must forward the headers they receive with the code to AAD to ensure that code injection attacks do not succeed. To do so, they need to be able to add a header to an auth code redemption request and an RT redemption request. 

**Describe the solution you'd like**
AcquireTokenByAuthorizationCode(code).WithHeaders({"headerA", "headerValue"})

**Describe alternatives you've considered**
We could take our header-based approach and rebuild it to operate on values in the body, but this moves the feature out of the appropriate layer and more into protocol.  This opens up new threat vectors, e.g. CSRF attacks where this is passed on the wire rather than as a header.

**Comment by hpsin** [comment]
Thanks Henrik - that's a good start.  This makes per-request injection rather difficult still, and can induce race conditions easily (e.g. the usual pattern of a static shared HttpClient being called to update the header dynamically is sure to fail).

**Comment by jmprieur** [comment]
@hpsin: if we surfaced this in Microsoft.Identity.Web would that be sufficient?
cc: @jennyf19 @henrik-me @pmaytak

**Comment by hpsin** [comment]
Is that used to redeem an auth code? An RT? That's where the headers need to be used.

**Comment by bgavrilMS** [comment]
@hpsin - it is used everywhere except to communicate with the /authroize endpoint, as the browsers deal with that. We should start a thread with all the MSAL owners to make this a proper API like you propose @hpsin , the HttpClient stuff is very rough.

**Comment by hpsin** [comment]
Perfect - as long as this is used for the /token request this should be sufficient then, thank you.

**Comment by bgavrilMS** [comment]
Exposed as `WithExtraHttpHeaders`
