### ISSUE TITLE
[Bug] Cannot get Access token from AcquireTokenInteractive

### ISSUE THREAD

**Issue by ntvuong1709it** [AzureAD/microsoft-authentication-library-for-dotnet#2039]
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client: 4.18.0

**Platform**
.Net 4.7.2

**What authentication flow has the issue?**
* Desktop / Mobile
    - [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
This is a testing app before applying to my existing app

```csharp
var pcaOptions = new PublicClientApplicationOptions
            {
                ClientId = "my client id",
                TenantId = "my tenant id",
                RedirectUri = "http://localhost:49468/",
            };

            string[] scopes = new string[] { "SMTP.Send" };

            var app = PublicClientApplicationBuilder.CreateWithApplicationOptions(pcaOptions)
                .WithLogging(Log, LogLevel.Verbose, true)
                .Build();

            var accounts = await app.GetAccountsAsync();
            AuthenticationResult result;

            try
            {
                result = await app.AcquireTokenSilent(scopes, accounts.FirstOrDefault())
                            .ExecuteAsync();
            }
            catch (MsalUiRequiredException)
            {
                try
                {
                    result = await app.AcquireTokenInteractive(scopes)
                            .ExecuteAsync();
                }
                catch (Exception ex)
                {
                }

            }
```

**Expected behavior**
Getting the result with access token

**Actual behavior**
**Exception**: A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

**Possible Solution**
I did some research, people said that I need to set the application as a public client. But no luck

![image](https://user-images.githubusercontent.com/30897181/92907604-aa997980-f44f-11ea-88f1-8023e5d7ae22.png)

**Comment by jennyf19** [comment]
@ntvuong1709it is the redirect uri correctly registered?

**Comment by ntvuong1709it** [comment]
> @ntvuong1709it is the redirect uri correctly registered?

Yes, it does. If the redirect uir is incorrect, there will be different error.

**Comment by jennyf19** [comment]
@ntvuong1709it Can you provide your manifest from the portal and a link to your code? you can send via email if you prefer : jeferrie@microsoft.com

**Comment by ntvuong1709it** [comment]
> @ntvuong1709it Can you provide your manifest from the portal and a link to your code? you can send via email if you prefer : [jeferrie@microsoft.com](mailto:jeferrie@microsoft.com)

Sorry for the late response, I have sent you the email with the manifest file. Please have a look

**Comment by jennyf19** [comment]
@ntvuong1709it so you need to use `.WithDefaultRedirectUri()`, because the one you are using is for web applications, which are confidential clients, and because of the redirect uri you are using, so Azure AD thinks you are a confidential client, noted by `"Web"` in the manifest:
```json
"replyUrlsWithType": [
		{
			"url": "http://localhost:49468/",
			"type": "Web"
		}
	],
```
so AAD continues to ask for a client secret/certificate when you try to sign-in. 

Try to edit the manifest to the following (line 51)
```json
"replyUrlsWithType": [
		{
			"url": "http://localhost:49468/",
			"type": "InstalledClient"
		}
	],
```

**Comment by ntvuong1709it** [comment]
@jennyf19 ,
Thanks for the reponse.
I edited the manifest according to your suggestion as below:

```csharp
"replyUrlsWithType": [
		{
			"url": "http://localhost:49468/",
			"type": "Web"
		},
		{
			"url": "https://login.microsoftonline.com/common/oauth2/nativeclient",
			"type": "InstalledClient"
		}
	]
```
For the console app, it's working now.

I still keep reply url for Web because I have a web app config as below. 

```csharp
var pcaOptions = new PublicClientApplicationOptions
            {
                ClientId = "clientId",
                TenantId = "tenantId",
                //RedirectUri = "http://localhost:49468/",
            };

            string[] scopes = new string[] { "smtp.send" };

            var app = PublicClientApplicationBuilder.CreateWithApplicationOptions(pcaOptions).WithDefaultRedirectUri()
                .Build();

            var accounts = await app.GetAccountsAsync();
            AuthenticationResult result;

            try
            {
                result = await app.AcquireTokenSilent(scopes, accounts.FirstOrDefault())
                            .ExecuteAsync();
            }
            catch (MsalUiRequiredException)
            {
                try
                {
                    result = await app.AcquireTokenInteractive(scopes)
                            .WithUseEmbeddedWebView(true)
                            .ExecuteAsync();
                }
                catch (Exception ex)
                {
                }
            }
```
If I use `.WithDefaultRedirectUri()`, I can get access token. However, if I specify the `RedirectUri = "http://localhost:49468/"` in the `pcaOptions` and remove `.WithDefaultRedirectUri()`, I get the error. 
Could you explain to me why ?

**Comment by jmprieur** [comment]
@ntvuong1709it 

As @jennyf19 suggested, if you want to use `RedirectUri = "http://localhost:49468/"` in the `pcaOptions` and remove `.WithDefaultRedirectUri()`, then you need to make  `http://localhost:49468/` an installedClient (that is native client/or public client app) URL, not a Web URL:

```Json
"replyUrlsWithType": [
		{
			"url": "http://localhost:49468/",
			"type": "InstalledClient"
		}
	]

``

**Comment by ntvuong1709it** [comment]
@jmattheus ,
Thanks for the response, it was a bit confuse because it is a web app and I expect that the type of Redirect Uri should be **web**. But if that is how it works, i guess it's fine.

**Comment by jennyf19** [comment]
@ntvuong1709it it is confusing.

**Comment by ntvuong1709it** [comment]
Anyway, thanks for the quick support @jennyf19 , @jmprieur . I appreciate that

**Comment by jmprieur** [comment]
Thanks for the update, @ntvuong1709it 
Closing this issue.
