### ISSUE TITLE
[Bug] The AcquireTokenSilent method never work

### ISSUE THREAD

**Issue by MrRyeS** [AzureAD/microsoft-authentication-library-for-dotnet#2040]
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.18.0

**Platform**
netcore 3.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [#] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**

            string[] scopes = new string[] { Audience + "/user_impersonation" };
            var app = PublicClientApplicationBuilder.Create(ClientId).WithRedirectUri("http://localhost").WithAuthority(Authority).Build();
            var accounts = await app.GetAccountsAsync();
            AuthenticationResult result;
            try
            {
                result = await app.AcquireTokenSilent(scopes, accounts.FirstOrDefault())
                            .ExecuteAsync();
            }
            catch (MsalUiRequiredException)
            {
                result = await app.AcquireTokenInteractive(scopes)
                            .ExecuteAsync();
            }
            return result.AccessToken;

**Expected behavior**
The first time I interactively login and get the token. Afterwards the cache should do the job.

**Actual behavior**
Every time I will have to interactively login. The AcquireTokenSilent method never work.

**Comment by jmprieur** [comment]
@MrRyeS : this is expected as you recreate the Public client application each time without serializing the token cache.

See:
-  https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/tree/master/2-TokenCache to learn how to use a cross platform cache that we release with MSAL.NET
- or https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/63b46c35f205691d26ed18919bd4698498babce6/active-directory-wpf-msgraph-v2/App.xaml.cs#L19 and https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/msal3x/active-directory-wpf-msgraph-v2/TokenCacheHelper.cs for a simpler cache.

**Comment by MrRyeS** [comment]
@jmprieur Thanks a lot for the quick response! My usage scenario is quite simple, so I tried to use the same pca every time and it works fine now. The links are really helpful! Thanks again.

**Comment by jmprieur** [comment]
Closing this issue @MrRyeS as it seems you agree that it's answered.
Feel free to reopen if you disagree.
