### ISSUE TITLE
Fallback for local imds call failure due to using an unsupported version

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#2055]
**Is your feature request related to a problem? Please describe.**
The call to local imds requires version as a query param. The request will fail in case the version is not supported. 

**Describe the solution you'd like**
Add a fallback in case the local imds call fails to check the current version and query updated link. https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#versioning

**Describe alternatives you've considered**

**Additional context**

**Comment by jmprieur** [comment]
@neha-bhargava : I don't understand this issue, what's the customer pain? how do we know that this is fixed?
we might want to take that offline.
