### ISSUE TITLE
[Bug] B2C interactive prompt does not render well in UWP

### ISSUE THREAD

**Issue by cindycluck** [AzureAD/microsoft-authentication-library-for-dotnet#2060]
**Which Version of MSAL are you using ?**4.19.0
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

**Platform**
   UWP

**What authentication flow has the issue?**   ALL Interactive in UWP mbedded Webviews.
* Desktop / Mobile
    * [x] Interactive 
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
     The app is in production, and I have upgraded to a new version of MSAL 

The AZURE B2C begin to recommend its new user flow, let anyone change to use the new version userflow.

**Repro**
https://stackoverflow.com/questions/64101050/azure-ad-b2c-the-browser-page-is-mis-rendered-in-embedded-webviews-with-msal-net

 The browser page is mis-rendered in Embedded Webviews with MSAL.net web( AAD B2C new versio userflow)
And I can run the user flow and right render with my system chrome web browser . 

```csharp
var your = (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes  

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by bgavrilMS** [comment]
@aiwangmicrosoft may want to contact the Windows folks for a resolution. MSAL does not own the Windows control that displays this.

**Comment by henrik-me** [comment]
@cindycluck : We don't own this Windows control and can't help fix this. Closing. The scenario is not well supported in UWP.
