### ISSUE TITLE
Unable to add custom claims with .withClientClaims

### ISSUE THREAD

**Issue by TimPenfare** [AzureAD/microsoft-authentication-library-for-dotnet#2061]
I am unable to add custom claims
app = ConfidentialClientApplicationBuilder.Create(_credentials.clientId)
                    .WithClientClaims(cert, new Dictionary<string, string> { { "client_ip", ipAddress }, { "email", email } })
                    .WithAuthority(new Uri(_oauth.Authority))
                    .Build();

**Comment by jmprieur** [comment]
@TimPenfare 
Even if MSAL.NET sends the claims, in the end Azure AD decides if the claims are included in the token. 
Did you read this article ?
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims ?

What do you observe? Do you expect the claim to be in the ID Token (for the client)? or the access token (for the resource)

**Comment by TimPenfare** [comment]
Hi, I am trying to add email claim to a access token I am generating using client credentials and cert.

Cheers

**Comment by TimPenfare** [comment]
Hi, All I want to do is to add an additional claim in the payload of the access token I thought the .withClientClaims performed that function

**Comment by TimPenfare** [comment]
The only claims I am seeing are 
"aud": "api://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
  "iss": "https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/",
  "iat": 1601387205,
  "nbf": 1601387205,
  "exp": 1601391105,
  "aio": "E2RgYGixvf9YYMmM+Du27hP1z9rtBwA=",
  "appid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
  "appidacr": "2",
  "idp": "https://sts.windows.net/d03f5aab-5d5f-4af1-9674-e5baa59cf00f/",
  "oid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
  "rh": "0.AAAAq1o_0F9d8UqWdOW6pZzwD8g5suiXrMdLiHv7-toWiRIxAAA.",
  "sub": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx2",
  "tid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
  "uti": "nfB81vm7AEyZXP8jkj4aAA",
  "ver": "1.0"


How do I add "email": "email@gmail.com"

**Comment by bgavrilMS** [comment]
Client credentials grant is also know as "service to service" authentication, i.e. you are requesting a token on behalf of a service, not on behalf of a user. So I don't think there is an email grant to be had. 

You can try to also request for the "profile" or "email" scopes and see what happens.
