### ISSUE TITLE
[Bug] RemoveAccount can fail silently in cache sharing apps

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2063]
**Which Version of MSAL are you using ?**
4.19

**Platform**
all with custom cache

**What authentication flow has the issue?**
refresh_token

**Is this a new or existing app?**
VS and family

**Repro**

App1 and App2 share the cache (via FOCI or by using the same client_id)

1) App 1 calls `AcquireTokenSilent` for account A which results in a refresh_grant flow occuring
2) App 2 removes account A, while App1 is still waiting for the flow to finish
3) App 1 flow finishes, and new tokens for account A are fetched

**Actual**: App1 will write Account A back to the cache
**Expected**: App 1 should not re-login account A
 
User impact: even though the user will have logged out of the family of apps, they are still logged in.

**Suggested solution:** 

When the refresh_token grant finishes and a response containing tokens is received, MSAL should check that the request account is still in the cache. If it is not, then MSAL should throw an MSALUiRequiredException instead of returning the tokens, thus forcing an interactive login.

**Comment by henrik-me** [comment]
@bgavrilMS to update with discussed solution

**Comment by jmprieur** [comment]
@bgavrilMS : is any discussion happening?

**Comment by bgavrilMS** [comment]
This is a theoretical race condition...

**Comment by jmprieur** [comment]
Changing to an enhancement as this is theoretical, and wee don't seem to address it urgently
