### ISSUE TITLE
Update documentation to let users know not to use simulator.

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#2071]
Update documentation to let users know not to use simulator.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Android-iOS-Emulator-with-MSAL
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-Docs
