### ISSUE TITLE
[Bug] iOS KeyChain error points to wrong docs location

### ISSUE THREAD

**Issue by dansiegel** [AzureAD/microsoft-authentication-library-for-dotnet#2077]
**Which Version of MSAL are you using ?**

4.18.0

**Platform**

xamarin.ios

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**

new

**Description**

When you have an issue with the publisher keychain, a MsalException is thrown with the following message:

```
The application cannot access the iOS keychain for the application publisher (the TeamId is null). This is 
needed to enable Single Sign On between applications of the same publisher. This is an iOS configuration 
issue. See https://aka.ms/msal-net-enable-keychain-access for more details on enabling keychain access.
```

**Expected behavior**

The aka.ms link should point to wherever the docs for this have actually migrated.

**Actual behavior**

The aka.ms link points to: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-iOS-specifics#enable-keychain-access

**Comment by bgavrilMS** [comment]
Hi @dansiegel - some parts of our wiki were indeed moved to docs.ms, but it seems to me that the paragraph around Enabling KeyChain Access describes what do ... https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations#enable-keychain-access

**Comment by dansiegel** [comment]
@bgavrilMS yeah I figured that's where the docs moved... was more filing that specific issue because the link went to the wrong place and should be updated to help folks out. 

I will add my actual code was:

```cs
var builder = PublicClientApplicationBuilder
     .Create(ClientId)
     .WithIosKeychainSecurityGroup(Xamarin.Essentials.AppInfo.PackageName)
     .Build();
```

and my Entitlements were:

```xml
<dict>
  <key>keychain-access-groups</key>
  <array>
    <string>$(AppIdentifierPrefix)com.{my app name}</string>
  </array>
</dict>
```

just like the docs say, and I was getting this error on the Simulator, but not the device.

**Comment by jennyf19** [comment]
@dansiegel should be fixed now, if you want to double check.

**Comment by dansiegel** [comment]
@jennyf19 looks like it's pointing at the right place now... 

I might suggest checking the rest of the links in the error messages... it looks like there's about 40 in total. The chances are there are several more that need to be updated due to the change in where the docs are... it would really suck if someone had to open an issue for each one 😉  

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/MsalErrorMessage.cs

**Comment by jennyf19** [comment]
@dansiegel yes, I agree. I'll open a new issue for that. 
Should this one be closed or did you figure out the keychain issue? thanks again for letting us know.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2083

**Comment by dansiegel** [comment]
Well I was never actually able to figure out what the issue was that was causing my issue sadly. If anyone has any ideas i'm all ears... but I'm going to close the issue since technically the issue was about the wrong docs location 😄

**Comment by jennyf19** [comment]
@dansiegel do you have a repro you can share? which version of iOS are you using? feel free to open another issue if you want.

**Comment by dansiegel** [comment]
I'll open a new issue for it. I need to generate a simpler reproduction

**Comment by adambarath** [comment]
> @bgavrilMS yeah I figured that's where the docs moved... was more filing that specific issue because the link went to the wrong place and should be updated to help folks out.
> 
> I will add my actual code was:
> 
> ```cs
> var builder = PublicClientApplicationBuilder
>      .Create(ClientId)
>      .WithIosKeychainSecurityGroup(Xamarin.Essentials.AppInfo.PackageName)
>      .Build();
> ```
> 
> and my Entitlements were:
> 
> ```
> <dict>
>   <key>keychain-access-groups</key>
>   <array>
>     <string>$(AppIdentifierPrefix)com.{my app name}</string>
>   </array>
> </dict>
> ```
> 
> just like the docs say, and I was getting this error on the Simulator, but not the device.


I had the same issue, but I figured it out how to run my app on simulator. I was wondering CodesignEntitlements tag is only defined under iPhone build configurations. I declared

This is the original CSPROJ generated by Visual Studio. You can see CodesignEntitlements tags are missing by default:
```xml
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TemplateGuid>{440aa056-593a-4519-8708-27081dee632f}</TemplateGuid>
    ....
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
    ...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhoneSimulator' ">
    ...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">
    ...
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    ...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
    ...
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    ...
  </PropertyGroup>
  ...
  ...
```

I modified a bit to:
```xml
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TemplateGuid>{440aa056-593a-4519-8708-27081dee632f}</TemplateGuid>
    ....
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
    ...
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    ...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhoneSimulator' ">
    ...
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    ...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">
    ...
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    ...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
    ...
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    ...
  </PropertyGroup>
  ...
  ...
```

Or just simplier:
```xml
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TemplateGuid>{440aa056-593a-4519-8708-27081dee632f}</TemplateGuid>
    ....
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
  </PropertyGroup>
  ...
```
