### ISSUE TITLE
[Bug][Regression] Get NoTokensFoundError when migrating ADAL v3 token for user who has multi tenants

### ISSUE THREAD

**Issue by erich-wang** [AzureAD/microsoft-authentication-library-for-dotnet#2090]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 4.19.0, the issue doesn't exist in MSAL 4.10.0

**Platform**
netcore/.Net 4.5

**What authentication flow has the issue?**
* Desktop / Mobile
For users associated with multi tenants, there're multiple RT in ADAL token cache because there is one corresponding RT for each tenant. When migrating ADAL v3 token, [the change](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/bafa2f06a9d4459dbb224052237520ba767e765b#diff-673aecdcc2a1fcef67de94c00ac55600R320) results in NoTokensFoundError

**Repro**

```csharp
            var builder = PublicClientApplicationBuilder.Create("1950a258-227b-4e31-a9cf-717495945fc2");
            var clientApplication = builder.Build();
            clientApplication.UserTokenCache.SetBeforeAccess((TokenCacheNotificationArgs args) =>
            {
                  args.TokenCache.DeserializeAdalV3(AdalToken)
            }
            var accounts = clientApplication.GetAccountsAsync().ConfigureAwait(false).GetAwaiter().GetResult();
            foreach (var account in accounts)
            {
                 var token = clientApplication.AcquireTokenSilent(new []{"https://management.core.windows.net/.default"}, account).ExecuteAsync().ConfigureAwait(false).GetAwaiter().GetResult();
                //Get NoTokensFoundError
           }

```

**Expected behavior**
Token should be returned successfully

**Actual behavior**
Get NoTokensFoundError

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by jmprieur** [comment]
@bgavrilMS : did it go in 4.20 ?
