### ISSUE TITLE
[Bug] Version 4.20.0 with dotnet sdk 5.0.100-rc.2.20479.15 results in NETSDK1130 error

### ISSUE THREAD

**Issue by fuocor** [AzureAD/microsoft-authentication-library-for-dotnet#2095]
**Which Version of MSAL are you using ?**
4.20.0

**Platform**
dotnet sdk 5.0.100-rc.2.20479.15

Other? - please describe;
using rc2 sdk and version 4.20.0 of MSAL results in:
`error NETSDK1130: Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.`

**Is this a new or existing app?**
existing

**Expected behavior**
no build error

**Actual behavior**
crashes build

**Possible Solution**
revert to 4.0.19

**Comment by jmprieur** [comment]
@fuocor 
This is now fixed in 4.20.1 released today
cc: @bgavrilMS
