### ISSUE TITLE
[Bug] NGen cannot process MSAL

### ISSUE THREAD

**Issue by wjvii** [AzureAD/microsoft-authentication-library-for-dotnet#2099]
**Which Version of MSAL are you using?**
4.19.0

**Platform**
Windows 10, .NET 4.8

**Existing app?**
Yes, the app is in production, and I have upgraded to a new version of MSAL

**Repro**

```
C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen.exe install .\Microsoft.Data.SqlClient.dll
```

**Expected behavior**
I expected it to install without error. I have tried to setup various binding redirects but they all fail.

**Actual behavior**
Failed to load dependency Microsoft.Identity.Client of assembly Microsoft.Data.SqlClient, Version=2.0.20168.4, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5 because of the following error : The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Possible Solution**
I am guessing this requires a binding redirect but I have not found one that works.

**Additional context/ Logs / Screenshots**
This is with Microsoft.Data.SqlClient 2.0.1. I am putting this issue in the MSAL repo because I have this same error with other packages such as Failed to load dependency Microsoft.Identity.Client of assembly Microsoft.Identity.Client.Extensions.Msal, Version=2.15.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae because of the following error : The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).

I have checked and rechecked the versions in the folder and they are the latest non-preview version of each Microsoft.Data.SqlClient, Microsoft.Identity.Client.Extensions.Msal, and Microsoft.Identity.Client.

Maybe ngen not complaining does not matter because the application does run, in which case I am curious as to why it is OK for it not to install properly because we run ngen as sort of a double check to make sure we have the proper versions and redirects.

Thank you in advance.

**Comment by bgavrilMS** [comment]
Hi @wjvii 

MSAL nuget package contains both lib and ref assemblies. This is allowed in modern version of NuGet. Ref assemblies are what you see in Visual Studio / developer programs against. Lib assemblies are runtime. We use a "bait and switch" technique, i.e. we hide some runtime APIs from the reference assembly to provide a better developer experience. 

I can only imagine that the ngen tool is too old to know about ref assemblies in the nuget package?
