### ISSUE TITLE
[Feature Request] Simplify the API by getting rid of Migration Aid

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2101]
MigrationAid was there to help customers move from MSAL v3 to MSAL v4 
It should be easy to detect how many apps are still running on MSAL v3, but I would imagine that not that many, since the last major update to MSAL v3 was on 30 Apr 2019. 

For people using MSAL v3, we could recommend the following pattern: 

- update to MSAL 4.20.1 first and benefit from the Migration Aid helpers
- migrate
- update to latest version of MSAL

**Comment by henrik-me** [comment]
Looking at the data from Kusto. I think this is not a viable option at the moment.
