### ISSUE TITLE
[Investigate] B2C Xamarin Sample getAccounts does not return an account after first sign-in

### ISSUE THREAD

**Issue by tal-athena** [AzureAD/microsoft-authentication-library-for-dotnet#2106]
## My Code

```js
        public async Task<UserContext> SingInWithoutInteractively()
        {
            UserContext newContext;
            try
            {
                // acquire token silent
                newContext = await AcquireToken();

            } catch
            {
                newContext = null;
            }

            return newContext;
        }

        public async Task<UserContext> SignInAsync()
        {
            UserContext newContext;
            try
            {
                // acquire token silent
                newContext = await AcquireToken();
            }
            catch (MsalUiRequiredException)
            {
                // acquire token interactive
                newContext = await SignInInteractively();
            }
            return newContext;
        }

        private async Task<UserContext> AcquireToken()
        {
            IEnumerable<IAccount> accounts = await _pca.GetAccountsAsync();
            AuthenticationResult authResult = await _pca.AcquireTokenSilent(B2CConstants.Scopes, GetAccountByPolicy(accounts, B2CConstants.PolicySignUpSignIn))
               .WithB2CAuthority(B2CConstants.AuthoritySignInSignUp)
               .ExecuteAsync();
            
            var newContext = UpdateUserInfo(authResult);
            return newContext;
        }
        private async Task<UserContext> SignInInteractively()
        {
            IEnumerable<IAccount> accounts = await _pca.GetAccountsAsync();

            AuthenticationResult authResult = await _pca.AcquireTokenInteractive(B2CConstants.Scopes)
                .WithPrompt(Prompt.SelectAccount)
                .WithAccount(GetAccountByPolicy(accounts, B2CConstants.PolicySignUpSignIn))
                .ExecuteAsync();
            
            var newContext = UpdateUserInfo(authResult);            
            return newContext;
        }
        private IAccount GetAccountByPolicy(IEnumerable<IAccount> accounts, string policy)
        {
            foreach (var account in accounts)
            {
                string userIdentifier = account.HomeAccountId.ObjectId.Split('.')[0];
                if (userIdentifier.EndsWith(policy.ToLower())) return account;
            }

            return null;
        }
```

## Expected behavior
After first login, I think _pca.GetAccountsAsync() should return accounts list and be able to refresh token

## Actual behavior
always _pca.GetAccountsAsync() returns empty array so, can't refresh token
So it ask to login every time app launches.

**Comment by jmprieur** [comment]
@tal-athena 
Did you add a token cache serialization.?
See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization#token-cache-for-a-public-client
and also https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Cross-platform-Token-Cache

**Comment by jennyf19** [comment]
@tal-athena can you provide a repro or a link? Are you using the [Xamarin B2C sample](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native)? If so, which platform are you using?

**Comment by tal-athena** [comment]
Yes, I am using that sample, my platform is Xamarin Forms. and tested on Android

**Comment by tal-athena** [comment]
@jmprieur , Is the account saved by default when login success? should I add cache serialization to save account data?

**Comment by jennyf19** [comment]
thanks @tal-athena we will take a look. Did you change anything in the sample or run it as-is?

**Comment by tal-athena** [comment]
@jennyf19 , almost didn't changed, but the authentication code is the code provided

**Comment by jennyf19** [comment]
@tal-athena I'm not able to repro this. I do have an account in the cache:
![image](https://user-images.githubusercontent.com/19942418/96188330-61779200-0ef3-11eb-82e8-06550b2ba925.png)
My repro steps are:
- on a Pixel 2 device
- sign-in interactively on first app start
- close the app
- run app again, and on AT silent, i have an account in the cache.

**Comment by jennyf19** [comment]
@tal-athena i just did a git clone of master. the sample works as-is without any configuration changes. Are you using a device or simulator?

**Comment by tal-athena** [comment]
@jennyf19 , I am using simulator- google pixel-2 Pie 9.0

**Comment by jennyf19** [comment]
@tal-athena okay. thanks for the additional info. any chance you can try on a device? there are some slight performance differences between the simulator and device, as noted in our native android team's [wiki](https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/Android-Emulator-with-MSAL). I'll try it out w/the simulator.

**Comment by tal-athena** [comment]
@jennyf19 , I also tested it on device (Samsung galaxy) but also not cached. I tested with sample repo,
does it need any additional configuration in azure?

**Comment by jennyf19** [comment]
@tal-athena no, you don't need to do anything, as the end-user. the sample should work as-is, with a git clone.
@trwalke @neha-bhargava could you try out the above sample as well? I'm not able to repro this issue atm. thank you.

**Comment by bgavrilMS** [comment]
@tal-athena - please work with Microsoft support to get your further, we cannot repro the issue

**Comment by tal-athena** [comment]
thanks for your attention
I resolved this error after adding openid scope to my app.
Thanks

**Comment by bgavrilMS** [comment]
Thanks for getting back to us @tal-athena !
