### ISSUE TITLE
[Feature Request] Supporting target resource's ARM id as an optional claim

### ISSUE THREAD

**Issue by archanak-msft** [AzureAD/microsoft-authentication-library-for-dotnet#2115]
I am part of the Azure Arc team; we manage customer's vm and Kubernetes clusters which are deployed on non-Azure infra. For our scenarios, the token validation entities reside on the user's infra.

There can be scenarios where the tokens issued for a given K8s cluster can be replayed for a different K8s cluster if the first K8s cluster is compromised and the same client app has permissions on both the clusters. If AAD can provide optional claim support which can have value as target resource ARM Id then this attack surface can be reduced.

Update: One of my teammates informed me that this support is available for first-party apps, so our ask here is to provide this support for third party apps as well.

**Comment by bgavrilMS** [comment]
CC @jmprieur @henrik-me  - can MSAL really do anything here?

**Comment by jmprieur** [comment]
No, @bgavrilMS @archanak-msft this is a question for the STS.
@archanak-msft : do you build a 1P app? do you want to take this offline with us?

**Comment by archanak-msft** [comment]
Sure @jmprieur , let's take this offline.

**Comment by bgavrilMS** [comment]
Closing. Please reopen if required.
