### ISSUE TITLE
Documentation Discrepency

### ISSUE THREAD

**Issue by mattallscripts** [AzureAD/microsoft-authentication-library-for-dotnet#2117]
Regarding this statement:

> Some scenarios, involving conditional access related to a device being enrolled require a broker (Microsoft Company portal or Microsoft Authenticator) to be installed on a device. MSAL.NET is not yet capable of interacting with these brokers, but this is on the backlog

Source: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/scenarios#controlling-the-location-of-the-dialog-with-the-parent-parameters-uiparent

Is this out-of-date? I see it was updated in July 2019 and since then Microsoft has released "shared device mode" which works by MSAL talking to Microsoft Authenticator:

> Build applications that support Firstline Workers
You can support Firstline Workers in your applications by using the Microsoft Authentication Library (MSAL) and Microsoft Authenticator app to enable a device state called shared device mode. When a device is in shared device mode, Microsoft provides your application with information to allow it to modify its behavior based on the state of the user on the device, protecting user data.

Source: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-shared-devices

Can someone please either correct the documentation and/or clarify?

**Comment by bgavrilMS** [comment]
Hi @mattallscripts - MSAL.NET supports brokered authentication on its Xamarin targets Android and iOS, i.e. you can configure MSAL to use the brokers. See this sample for details: https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/2-With-broker ... I updated the wiki.

However, MSAL.NET does not support First Line Worker scenarios. As far as I know it is not sufficient to be able to talk to a broker to support these scenarios, there is work to be done in the libraries. The native MSAL libraries (MSAL for Android, written in Java, and MSAL for iOS, written in ObjC) support this scenario.

@jmprieur can help prioritize, but right now we do not have this scenario on the MSAL.NET roadmap. We are thinking about having managed wrappers over the native libraries instead.

**Comment by mattallscripts** [comment]
Ok great thank you @bgavrilMS . I think I was conflating MSAL on Desktop with MSAL on Xamarin, so this helps clarify.

Supported? | MSAL on Desktop | MSAL on Xamarin
------------ | ------------ | -------------
**First Line Worker Scenario** | No | Yes
**Brokered Authentication (i.e. with "Authenticator")** | Yes | Yes

If the above is accurate and given my team is working on MSAL on Xamarin at this point, so seems like we have what we need.

**Comment by jmprieur** [comment]
@mattallscripts : First line worker is not available on MSAL.NET for Xamarin (it's available in MSAL Android/iOS native libraries)

**Comment by mattallscripts** [comment]
Ok I've corrected the table in my previous reply.

**Comment by bgavrilMS** [comment]
@mattallscripts - MSAL on desktop and MSAL.Xamarin share most of the code, but some features that are available on one may not be on the other. For example, some authentication flows such as AcquireTokenByIntegratedWindowsAuthentication are not available on Xamarin. Broker support also differs. Your table is like this: 

Supported? | MSAL on Desktop | MSAL.NET for Xamarin | MSAL Android/iOS native libraries
------------ | ------------ | ------------- | -------------
**First Line Worker Scenario** | No | No | Yes
**Brokered Authentication (i.e. with "Authenticator", "WAM")** | Not yet* | Yes | Yes

WAM (Windows Authentication Manager, i.e. the broker on Windows) is actively worked on.
