### ISSUE TITLE
[Feature Request] Enable WAM on .net classic for console apps, WinForms, WPF etc.

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2124]

**Comment by bgavrilMS** [comment]
@mjcheetham - I tested WAM + Fido and at present Work And School accounts can use a Fido Key while Microsoft accounts cannot (work needs to be done on WAM side). 

So I think your best bet for FIDO support remains WebView2

**Comment by bgavrilMS** [comment]
This was done, with some known issues described here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam (there are also tracking items)

**Comment by j5aenz** [comment]
i'm working with .net 5 right now and I have now way of accessing the .Broker() function or any of the features related to WAM. I am currently using the 4.23.0 version specified. is WAM currently available on .Net 5 for WPF or only other platforms? perhaps i have a fundamental misunderstanding of how the various libraries are colliding. thx.

**Comment by bgavrilMS** [comment]
@j5aenz - apologies for the confusion. We plan to enable WAM on NET5 in the 4.25 release (probably early next year, but if you have an urgent need I could try to speed it up). 

Let's use this work item to track NET5 work: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2274
