### ISSUE TITLE
[Bug] Authentication cancelled from some Android phones

### ISSUE THREAD

**Issue by shristikatiyar** [AzureAD/microsoft-authentication-library-for-dotnet#2128]
**Which Version of MSAL are you using ?**
4.20

**Platform**
Mobile Android

**What authentication flow has the issue?**
  Mobile (Interactive)

Is this a new or existing app?
The app is existing one we migrated from ADAL to MSAL.

The app is in production, and we have migrated from  ADAL to MSAL

**Expected behavior**
Authentication_canceled  exception should come only when user cancels the authentication. 
after user_null exception in silent token on interactive login user should be able to login 

**Actual behavior**
Some users are complaing to us about not able to login and from the logs they share  the error they are getting is user_null  in silent Authentication which is a expected error and after interactive login they get authentication_canceled  and repeatedly they are facing this error(Atatched Logs)

**Possible Solution**
User should  be able to login if  he is not cacelleing the authentication.

**Additional context/ Logs / Screenshots**
112a79e3-9009-41ff-b18c-7e3bfff06c76 correlation Id 
[O365MobileAppLog (98).txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/5414290/O365MobileAppLog.98.txt)

**Comment by jmprieur** [comment]
@shristikatiyar what pattern do you use?
- do you use try {AcquireTokenSilent}  / catch (MsalUiRequiredException) {AcquireTokenInteractive } ?  
  - if yes, do you pass-in the Claims member?
  - do the user have a browser installed that respects the constraints expected by the STS/MSA: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-system-browser-android-considerations?

**Comment by bgavrilMS** [comment]
Hi @shristikatiyar - the fact that you get a "user_null" is normal, there is no account info stored by MSAL yet so you have to perform interactive login. 

The issue here is the interactive login failing with "user cancelled" exception. This can happen if the user manually closes the browser that pops up or if the browser does not have tabs capabilities. The error message has a link with more details https://aka.ms/msal-net-system-browsers but essentially the mitigation is to ask the user to install a better browser.

**Comment by bgavrilMS** [comment]
Note that MSAL is unable to offer a better error message in this case, as the OS is only offering this level of information.

**Comment by shristikatiyar** [comment]
> @shristikatiyar what pattern do you use?
> 
> * do you use try {AcquireTokenSilent}  / catch (MsalUiRequiredException) {AcquireTokenInteractive } ?
>   
>   * if yes, do you pass-in the Claims member?
>   * do the user have a browser installed that respects the constraints expected by the STS/MSA: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-system-browser-android-considerations?

yes we  do try try {AcquireTokenSilent}  / catch (MsalUiRequiredException) {AcquireTokenInteractive } ? but we are not passing any claims

**Comment by bgavrilMS** [comment]
You can pass in claims as Jean-Marc explains to cover some other advanced scenarios, but the issue here is that `AcquireTokenInteractive` fails because there isn't a good browser on the phone. 

CC @jennyf19 who worked on this a while back, in case I forget any details

**Comment by shristikatiyar** [comment]
> Hi @shristikatiyar - the fact that you get a "user_null" is normal, there is no account info stored by MSAL yet so you have to perform interactive login.
> 
> The issue here is the interactive login failing with "user cancelled" exception. This can happen if the user manually closes the browser that pops up or if the browser does not have tabs capabilities. The error message has a link with more details https://aka.ms/msal-net-system-browsers but essentially the mitigation is to ask the user to install a better browser.

Yes  I agree user_null is the expected error and in this scenario we are doing a interactive call 
for system web browser the logic we are using is !pc.IsSystemWebViewAvailable which if return false we fall back to embedded web view ., so  does this flag return false  if any good system web browser is not available or only if no browser is available.

**Comment by bgavrilMS** [comment]
The logic around `IsSystemWebViewAvailable`  needs to be investigated.

@shristikatiyar - are you sure the users didn't simply navigate away from the browser?

**Comment by shristikatiyar** [comment]
> The logic around `IsSystemWebViewAvailable` needs to be investigated.
> 
> @shristikatiyar - are you sure the users didn't simply navigate away from the browser?
Users are complainig that they are not able to login it this scenario so i think they will not be doing it 
and also I have got similar issues from other users also

**Comment by bgavrilMS** [comment]
Can you tell us what model and make device affected users have?

**Comment by shristikatiyar** [comment]
> Can you tell us what model and make device affected users have?

Hi @bgavrilMS  we have reach out to customers ,once they share device details I will share details here meanwhile can you share the logic around IsSystemWebViewAvailable  as we use this to fall back on emebedded web view.

**Comment by bgavrilMS** [comment]
Sure, the logic is here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5000f4a5624c1acd4cf1c07b25c6abb5eedf746c/src/client/Microsoft.Identity.Client/Platforms/Android/AndroidPlatformProxy.cs#L180
