### ISSUE TITLE
[Bug] Interactive Authentication broken with v4.21.1

### ISSUE THREAD

**Issue by cheenamalhotra** [AzureAD/microsoft-authentication-library-for-dotnet#2129]
**Which Version of MSAL are you using ?**
**v4.21.1**
No issues till _v4.21.0_

**Platform**
.NET Framework (all versions)

**What authentication flow has the issue?**
Desktop > Interactive

**Is this a new or existing app?**
Tested with SqlClient.
Driver implementation for Token Acquisition: [AcquireTokenInteractive](https://github.com/dotnet/SqlClient/blob/4107f242b61703bb2b05817acdec85acd52d1e35/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs#L275-L278)

**Repro**
[TestInteractive.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/5418965/TestInteractive.zip)

**Expected behavior**
Should be able to connect as till v4.21.0

**Comment by jennyf19** [comment]
@cheenamalhotra thanks for opening the issue. Are you getting an error back or is there a stack trace/logs you can share?

**Comment by cheenamalhotra** [comment]
I get this error when I sign in:

![image](https://user-images.githubusercontent.com/13396919/96814471-a3ac4200-13d1-11eb-885b-3c50f40bf053.png)

**Comment by bgavrilMS** [comment]
So with MSAL 4.21.0 the interactive authentication was working and with 4.21.1 is is not because of a redirect URI mismatch? 

There was a minor single [product change ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/2dddc6b857f0b3833169f2e5890dc2058eabcbed)introduced and not in an area of code that handles redirect uri. 

What is the redirect URI configured in MSAL and what about the one registered in Azure portal? 
Does the **interactive** authentication really work in 4.21.0 ?

**Comment by bgavrilMS** [comment]
Thanks for the extra details, I had a look at the traces and found that in the successful case you configure: 

`https://login.microsoftonline.com/oauth2/nativeclient`

and in the failing case you configure

`https://login.microsoftonline.com/common/oauth2/nativeclient` (this one is **not** registered in app config so failure is expected)

I can see in your app that you mostly configure the second one, which is also MSAL's recommended one (but for legacy reasons it is not the default one, the default is `urn:ief:...` which you also have configured in app reg). 

https://github.com/dotnet/SqlClient/blob/4107f242b61703bb2b05817acdec85acd52d1e35/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs#L111 

I am not sure of what code path is used to configure the first redirect uri, and I haven't found in MSAL at all. I don't remember seeing any MSAL defects related to this either, maybe you have 2 versions of your product or a code path that I don't see here?

**Comment by jennyf19** [comment]
@cheenamalhotra see @bgavrilMS comment above.

**Comment by cheenamalhotra** [comment]
@bgavrilMS 

Thanks for investigating and providing details.

No, we don't have any other code path that could set redirect URI to `https://login.microsoftonline.com/oauth2/nativeclient`,
we have always only set `https://login.microsoftonline.com/common/oauth2/nativeclient` 🤔

**Comment by bgavrilMS** [comment]
@cheenamalhotra - please register `https://login.microsoftonline.com/common/oauth2/nativeclient` as a redirect URI. It currently isn't registered. Let us know if this doesn't fix the issue.
