### ISSUE TITLE
[Bug] WAM ATI flow for a logged-in account shows account picker

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2134]
**Which Version of MSAL are you using ?**
4.22.0

**Platform**
UWP

**What authentication flow has the issue?**
WAM ATI

**Is this a new or existing app?**
[WAM UWP test app](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/master/tests/devapps/WAM/UWPWam)

**Repro**
1. In `ATI_ClickAsync`, replace `.WithAccount(acc)` with `.WithLoginHint(upnPrefix)`.
2. Run the app.
3. Click `ATI` and login with an account. Account picker will be shown.
4. Click `Get Accounts` to verify the account is logged in.
5. Type the UPN of this logged in account into the UPN prefix textbox.
6. Click `ATI` again. Account picker will be shown, when it shouldn't be.

**Expected behavior**
As per spec, ATI flow should not show an account picker for an already logged-in/cached account. Instead, it should retrieve the cached token.

**Actual behavior**
ATI flow for an already logged-in/cached account shows an account picker.

**Additional context**
Run the repro steps with `.WithAccount(acc)`. Step 6 will correctly not show an account picker.

**Comment by bgavrilMS** [comment]
Won't be fixing this as it would require too much change. Preferred mechanism is to use WithAccount.
