### ISSUE TITLE
MSAL does not throw UiRequiredException when it should (Android Broker scenarios)

### ISSUE THREAD

**Issue by shristikatiyar** [AzureAD/microsoft-authentication-library-for-dotnet#2140]
**Which Version of MSAL are you using ?**
4.20

**Platform**
Xamrin.Android

**What authentication flow has the issue?**
Mobile

Other? - please describe;

**Is this a new or existing app?**
The app is in production and we have migrated from  ADAL to MSAL

**Repro**

                authResult = await pc.AcquireTokenSilent(scopes, account).ExecuteAsync();

                DataInsightsProvider.Instance.TrackEvent(DataInsightsEvents.FetchTokenSilentlySuccess);
            }
            catch (MsalUiRequiredException e)
            {
                // This exception is expected if there is no token in the cache.
                this.logger.Log($"{_logTagAuth}: Encountered error during silent authentication." +
                                                $" Error code = {e.ErrorCode}. Exception: {e}");
            }

**Expected behavior**
If a silent token acquisitaion call fails due to reason such as (no account found or broken resfresh toke is invalid) insted of MSAL  Service Exception we should get MSAL UI Required Exception so that we a interactive signin is performed.

**Actual behavior**
For some user in their session when a silent token acquistion is taking place MSAL Service Exception is thrown from broker
with error codes no_account_found or broker refresh token is invalid

**Possible Solution**
These error should throw a MSAL UI Required Exception

**Additional context/ Logs / Screenshots**
{\"Error Message\":\"Non-Graph Authentication Error:\",\"Exception Message\":\"Broker response returned error: Account does not exist in the broker, cannot proceed with silent request\"}
"Message\":\"nt.Internal.Requests.SilentBrokerAuthStrategy.SendTokenRequestToBrokerAsync () 

From the logs from telemetry error is returned from this function (while broker is trying to silently acquire token)

**Comment by bgavrilMS** [comment]
@shristikatiyar - what exactly are the error codes (verbatim)? You mentioned `no_account_found` and smth related to refresh token.

**Comment by bgavrilMS** [comment]
P1 since user impact is that they can't login or app crashes.

**Comment by bgavrilMS** [comment]
We need to find out the exact error codes which need to be translated to `MsalUiRequiredException` from Android broker.

**Comment by shristikatiyar** [comment]
> We need to find out the exact error codes which need to be translated to `MsalUiRequiredException` from Android broker.

Hi Bogdan , these are the two error codes we are getting. attaching the screenshot

Broker refresh token is invalid
no_account_found

![Screenshot (137)](https://user-images.githubusercontent.com/72396948/97418717-2469c180-192f-11eb-8db9-e6a923442844.png)
