### ISSUE TITLE
[Documentation] Acquire Token on Desktop - Force MFA

### ISSUE THREAD

**Issue by Pyrobolser** [AzureAD/microsoft-authentication-library-for-dotnet#2142]
### Documentation Related To Component:

`AcquireTokenInteractive(...)` of `PublicClientApplication(...)`

### Please check those that apply

- [ ] typo
- [X] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

I would like to preface this by saying that this might be me misunderstanding how this work but I cannot find any information about MFA in the documentation itself. I was able to force people to login and stop Windows using the cached credentials by using `.WithPrompt(Prompt.ForceLogin)`.

[https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet#withprompt](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet#withprompt)
  
But we also have multi-factor authentication enabled in our portal, for example I use my MFA code when connecting to our VPN application, and the login screen doesn't ask for my MFA code when used with this WinForms app.
Is there a way to force the login prompt to use MFA? I can't seem to find any configuration in Azure or actual code to use in the library to do that properly?

Thank you for the details you can provide.

**Comment by bgavrilMS** [comment]
MFA and Conditional Access in general is fully implemented on the service side and you control it via configuration. There is no SDK change. 

Have a look at these CA policies that might be used to achieve what you aim: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes ?

**Comment by Pyrobolser** [comment]
Thanks you for your answer, I will look more into that.
