### ISSUE TITLE
[Feature Request] High-Level perf assement scenario

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2146]
**Goal**: Be able to asses the performance impact of a M.I.W. (and later MSAL) PRs

### Approach

I propose a simple, not fully automated approach at first. 

1. Instrument M.I.W. so that we can read the following perf counters: 
- time spent in HTTP communication (by injecting your own HttpClient client that measures time spend on the network, for example [this one](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5000f4a5624c1acd4cf1c07b25c6abb5eedf746c/tests/Microsoft.Identity.Test.Common/Core/Helpers/HttpSnifferClientFactory.cs#L11))
- time spent in TokenCaching 
- time spent calling `AcquireTokenSilent` and `OBO` (just one of them is a good start though)

- In the end we care about a single metric:  total time of `ATS` / `OBO` **except** time spent in HTTP and in token cache ops 

2. Create a test project that uses the perf runner, or have a test project read the output of the perf runner
3. **1st deliverable** a test run that measures the Perf Metric and output it as a message

4. Source a VM that will be used exclusively for perf tests (we should talk to the lab guys about this)
5. **2nd deliverable** Introduce a fixed baseline in the test and run the tests only on this VM

Next steps: 

- Create a test runner that targets MSAL directly OR use chained builds to trigger a perf run on MSAL changes
- Profiling MSAL.

**Comment by bgavrilMS** [comment]
@pmaytak - some thoughts on where to take the perf story, let me know what you think.

**Comment by pmaytak** [comment]
Initial thoughts:
> In the end we care about a single metric: total time of ATS / OBO except time spent in HTTP and in token cache ops

For this case, would directly calling MSAL be better then? Similar to what the perf client project does - instantiate CCA/PCA, call methods, and have stopwatch around the method call.

> time spent in HTTP communication (by injecting your own HttpClient client that measures time spend on the network, for example this one)

Would it be possible to completely stub/fake the outbound HTTP call, so that we take the network variable out of these tests?

> Goal: Be able to asses the performance impact of a M.I.W. (and later MSAL) PRs

I think it would help to separate testing for MIW pipeline vs MSAL. So maybe just have a test runner that calls MSAL directly (as in the 1st point above).

**Comment by bgavrilMS** [comment]
Both strategies (targeting MSAL or targeting M.I.W) would work, I have a slight bias of going with M.I.W. because: 

- you've already written the test runner that drives M.I.W
- M.I.W scenarios are more perf sensitive than general MSAL scenarios

Instrumenting M.I.W is smth we need anyway. Eventually instrumenting MSAL directly is fairly important as well. Really up to you to decide on the order, the ultimate goal is to start doing some profiling work and start fixing MSAL. I don't mind if we manually have to patch M.I.W. and run a test to be able to say "this perf improving initiative led to 10% perf improv of MSAL". 

On the HTTP stack - yes, we can fully mock the stack. We already do this in our unit tests and have a ton of "helpers" to .. help with this :). Are you worried about EVO throttling the perf test?
