### ISSUE TITLE
[Bug] Broker on iOS does not pre-populate the username

### ISSUE THREAD

**Issue by shristikatiyar** [AzureAD/microsoft-authentication-library-for-dotnet#2147]
**Which Version of MSAL are you using ?**
4.20

**Platform**
Xamrin.iOS

**What authentication flow has the issue?**
Desktop  Interactive

**Is this a new or existing app?**
For iOS the app is not in Production with MSAL , we are planning to migrate from ADAl to MSAL in iOS

**Repro**

   authResult = await pc.AcquireTokenSilent(scopes, account).ExecuteAsync();

            DataInsightsProvider.Instance.TrackEvent(DataInsightsEvents.FetchTokenSilentlySuccess);
        }
        catch (MsalUiRequiredException e)
        {
            // This exception is expected if there is no token in the cache.
            this.logger.Log($"{_logTagAuth}: Encountered error during silent authentication." +
                                            $" Error code = {e.ErrorCode}. Exception: {e}");
        }

**Expected behavior**
We should get a correct link on clicking "Get the App" which redirects us to the app store for installing the right App.
Also when the app is redirected to Broker userame should be prepopulated. As of now user has to enter name again in Authenticator which is not a good user experience.

**Actual behavior**
1)When there is a CA Policy apllied "Required approved Client App" we are redirected to a message, where we are asked to install Autheticator   but below essage there is abutton "Get the app". on clicking it we are ot redirected to App store(For eg. with Policy "Required Device to be marked as Compliant" on clicking on Enrool now we are redirected to Company Portal).

2)User has to enter name again when the flow is redirected to Authenticator

**Possible Solution**
( Redirection link should be correct)

**Comment by bgavrilMS** [comment]
Not sure I understand the problem... Let me try to rephrase repro steps: 

1. MSAL is configured to use the broker
2. You perform `AcquireTokenInteractive` on a device without broker 
3. A browser pops up 
4. User enters email
5. Browser asks user to `Enrol their device` and provides a link to app store
6. User enrolls device and gets Authenticator app
7. User returns to the app
8. User hits login
9. Authenticator is opened and shows no account?

**Comment by jennyf19** [comment]
@shristikatiyar Can you please confirm the repro steps above from @bgavrilMS ?

also, if the user does not have a [CA policy requiring the broker](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions#device-platforms), they will not get the link to install the broker, as it's not required, and have the regular sign in experience.

**Comment by shristikatiyar** [comment]
> @shristikatiyar Can you please confirm the repro steps above from @bgavrilMS ?
> 
> also, if the user does not have a [CA policy requiring the broker](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions#device-platforms), they will not get the link to install the broker, as it's not required, and have the regular sign in experience.

![Screenshot_20201105-223629](https://user-images.githubusercontent.com/72396948/98279684-44992080-1fc0-11eb-962e-d8df56037e7c.png)

Hi @jennyf19  and  @bgavrilMS  I have attached the screenshot which comes when  we  apply the CA Policy Required Aproved client App but on clicking the button Get the app it does not redidrect to the app store to install broker (though in tthe message it is mentioned to install  company Portal) . 
![Screenshot_20201105-234123](https://user-images.githubusercontent.com/72396948/98280300-33044880-1fc1-11eb-9884-81472dd744a1.png)

Atteaching the second screenshot for what happens when after clicking buttton  "Get the app".

Ideally it should redirect to App store

**Comment by bgavrilMS** [comment]
Hi @shristikatiyar - can you confirm that the issue only occurs on iOS and not on Android? Can you see what the URL points to? 

How do you repro this - using a real device or an emulator? iOS emulators do not have App Store.

**Comment by shristikatiyar** [comment]
> How do you repro this - using a real device or an emulator? iOS emulators do not have App Store. Can you try with an real device?
I am trying this on real Device so the  issue exist in both  ios and Android , in iOS it shoud redirect to Play store and in IOs to App stor both is not happening

**Comment by bgavrilMS** [comment]
@jennyf19 - have you seen this sort of behaviour before? Since we don't control the contents of the browser, I think this just be transferred to the Intune or ESTS folks.

**Comment by bgavrilMS** [comment]
Please transfer to ESTS or Intune via ICM. Not an MSAL issue.
