### ISSUE TITLE
[Feature Request] Prevent multiple interactive auth requests on Android / iOS 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2148]
**Is your feature request related to a problem? Please describe.**

On Android and iOS, we start a browser or the broker and then give back control to the app (via async)
Many apps do not freeze the UI while waiting for the browser / broker to come back and so the user can click "Login" multiple times. 

This causes problems, especially on Android Broker, as the broker actively cancels the "in progress" login attempt before trying a new one, which results in an `MsalClientException` - error code `authentication_cancelled`

In some cases `AcquireTokenInteractive` also fails because of a state mismatch param. This can happen if you start 2 interactive requests (A and B) and request A finishes first, as MSAL would be waiting for state B. 

**Describe the solution you'd like**
MSAL should only allow 1 interactive request at a time, at least for Android and iOS brokers (I would not do this for desktop system browser). In case a 2nd request comes in, it should be ignored and made to wait for the first request.

**Comment by bgavrilMS** [comment]
Potential bug related to this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2153

**Comment by henrik-me** [comment]
I think this should not be limited to iOS and Android. Probably a good one for all interactive flows, unless provide some kind of handle back to an ongoing authentication session that we keep track of e.g. in the state parameter send to aad. 
@bgavrilMS ?

**Comment by bgavrilMS** [comment]
Yes, this needs a bit of thought. For example System Browser on Windows does not have this problem - each Interactive request is associated with a different port. It does not matter the order in which the responses come back. Embedded webview and WAM are modal dialogs, so you can't even get back to the app.

For ios and android, we do not have an mechanism to keep track of requests and of cancellations. We could keep track of requests using a map of <state, request>. When the response comes, it will have a state associated, so we could track down the originating request. Cancellation means removal of request from the map + AuthenticationCancelled exception.

 I'll ping Android folks to see how they handle this issue.

**Comment by bgavrilMS** [comment]
We will not fix this.
