### ISSUE TITLE
[Feature Request] [L] Implement content provider for communication with the Android broker.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2150]
**Is your feature request related to a problem? Please describe.**
The current communication method that MSAL uses (Account Manager) with the broker is one of the broker's fallback mechanisms that uses IBinder  for IPC communication. One limitation here is that the Android OS allocates a maximum of 1MB buffer on RAM per process for IBinder transactions. This buffer size includes all the transactions within the app process like intents between activities, fragments and broadcast receivers etc. Given this, Android recommends to limit the transaction size to absolute minimum while using bound service. If the buffer size goes beyond 1MB either on the app process or on the Broker's background process, the OS throws a TransactionTooLargeException  or a DeadObjectException  by killing the remote process (broker's :auth process). 

The content provider implementation is a very recent update in broker applications so MSAL will need a way to fall back to the old implementation incase the user is on an older version of the broker.

**Describe the solution you'd like**
Implement the content provider in MSAL.NET so that MSAL can communicate with the broker without running into IBinder errors. 

Deliverables: 

- Implement Content provider in MSAL for broker communication.

- Enable MSAL to fallback on the account manager communication strategy if the content provider fails.

**Additional context**
[Xamarin Content Provider Documentation](https://docs.microsoft.com/en-us/xamarin/android/platform/content-providers/)
[Broker Content Provider Spec](https://identitydivision.visualstudio.com/DefaultCollection/DevEx/_git/AuthLibrariesApiReview/pullrequest/1554?_a=files&path=%2FBrokerContract%2FContentProviderAndroidBroker.md&discussionId=15009)

**Comment by bgavrilMS** [comment]
Another support incident related to AddAccount API being banned in enterprises via Android 4 Work.

**Comment by bgavrilMS** [comment]
@trwalke - are we implementing this ? Should we schedule it for 4.26?

**Comment by jmprieur** [comment]
Outstanding work:
- [ ] address PR review
- [ ] re-test in the test app
- [ ] update the manual test
- [ ] test with the Xamarin sample (with and without broker)

**Comment by trwalke** [comment]
Released in MSAL 4.27.0
https://www.nuget.org/packages/Microsoft.Identity.Client/
