### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by pavinan** [AzureAD/microsoft-authentication-library-for-dotnet#2155]
### Documentation Related To Component:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/ADFS-support

### Please check those that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
Typed  "PCKE" instead of  "PKCE".

![image](https://user-images.githubusercontent.com/8724933/97779214-a6adec00-1ba2-11eb-8b85-095ca265b388.png)

**Comment by jmprieur** [comment]
Thanks @pavinan 
This is fixed
