### ISSUE TITLE
Target Principal Name Incorrect Error - More details

### ISSUE THREAD

**Issue by pseabury** [AzureAD/microsoft-authentication-library-for-dotnet#2157]
I have a detailed question [over here at StackOverflow](https://stackoverflow.com/questions/64615805/msal-error-target-principal-name-incorrect-with-federated-iwa) trying to determine why I'm getting this error.  

Why does the response fail to parse in this case?

![image](https://user-images.githubusercontent.com/1918526/97882978-e3d0c600-1ce9-11eb-8477-25ae0820a1ee.png)

**Comment by bgavrilMS** [comment]
Hi @pseabury - do you mind using the template for opening bugs on MSAL? It will avoid us asking basic questions like - what version of MSAL do you use, on what platform etc.

**Comment by bgavrilMS** [comment]
Also please give us the actual stack trace.

**Comment by pseabury** [comment]
> Hi @pseabury - do you mind using the template for opening bugs on MSAL? It will avoid us asking basic questions like - what version of MSAL do you use, on what platform etc.

Yeah sorry about that... I wrestled with using a template or not because I'm not sure it's a bug, I'm just looking for any additional information I can get to track down a way out of the MSAL mess.  I'll create a new one from the template.... thanks.

**Comment by bgavrilMS** [comment]
Closing as we're discussing on https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2159
