### ISSUE TITLE
[Bug] [Mac] Sign in with Apple isn't auto-filling the Apple ID on Xamarin.Mac

### ISSUE THREAD

**Issue by kevcrooks** [AzureAD/microsoft-authentication-library-for-dotnet#2161]
**Which Version of MSAL are you using ?**
Version 4.22.0 of Microsoft.Identity.Client and also Microsoft.Identity.Client.Extensions.Msal 2.16.5

**Platform**
Xamarin.Mac

**What authentication flow has the issue?**
Desktop (Xamarin.Mac), when using a sign-in with Apple user policy defined in Azure B2C, e.g.
https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-apple

I've tried using both `WithUseEmbeddedWebView(true)` and `WithUseEmbeddedWebView(false)` in the `PublicClientApplication`

**Is this a new or existing app?**
Existing app

The sign-in flow works correctly. However when signing in with Apple, even if logged in to Apple and iCloud on the Mac, the user still needs to enter their Apple ID when logging in. We would like the Apple ID to be automatically filled in this case when signing in.

I don't know if it is expected for the ID to be auto-filled by the OS, however Apple have recently rejected our app on the basis that:
**"The app asks for Apple ID when the user selects to sign in with Apple and iCloud account is set up."**

I'm wondering if Apple are wrong here to expect that the Apple ID will be auto-populated in the app when using "Sign-in with Apple"?

Can you let me know if this is a bug, or if there is something we need to do differently on our end to allow sign-in with Apple to work automatically from the app (when the user is signed in to a Mac/iCloud already with their Apple ID)?

**Comment by jmprieur** [comment]
@jennyf19 @trwalke @neha-bhargava @bgavrilMS what are your thoughts. (I believe this is external)

**Comment by bgavrilMS** [comment]
I would also think this is external. While the repro is with xamarin.mac, I think we should be able to repro this issue with a simple .NET classic console app. 

@neha-bhargava - didn't you also encounter a similar bug recently?

**Comment by jennyf19** [comment]
@adamstoffel can you look at this for us? Thank you.

**Comment by jennyf19** [comment]
@kevcrooks sorry for the delay. we are working on getting some help from the people working on Apple sign-in.

**Comment by bgavrilMS** [comment]
Please open a case on the Azure portal, as this is a service issue. The SDK does not control the content of the browser.
