### ISSUE TITLE
[Bug] ios http stack causing cancellation exceptions

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2164]
This is related to an ICM..

I think the issue might be related to https://github.com/xamarin/xamarin-macios/issues/9370 
 
Our SSO extension makes background requests as a result of which the requests got cancelled. 
I tried the workaround by using : 
`
var handler = new NSUrlSessionHandler() {
  BypassBackgroundSessionCheck = false, // readd the hack
};
var httpClient = new HttpClient (handler);
`

and that seemed to not cancel the request and I was able to SSO fine.

**Comment by jmprieur** [comment]
@bgavrilMS let's take it for 4.23.0

**Comment by henrik-me** [comment]
Should we allow a way for customers to opt. out of us setting this flag (besides from providing own handler)?

**Comment by bgavrilMS** [comment]
I think this degree of control is too granular / complex and customers are not interested in obscure http stack bugs.
