### ISSUE TITLE
[Feature Request] Provide a strongly typed way of expressing the claims to request

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#2170]
**Is your feature request related to a problem? Please describe.**
Part of the zero trust app readiness, apps will be able to request some specific claims (for instance for certain resources). Today the .WithClaims method makes it possible to express claims to request, but this is not an easy experience. This was ok when just passing the claims from the MsaUiRequiredException, but now that the scenarios will be more complex, we could do better, 

**Describe the solution you'd like**
Have a strongly typed experience to express the claims to request. See with Caleb for some of the needs

**Comment by bgavrilMS** [comment]
No customer ask for this. Claim challenges come pre-formatted from either STS or from resource.
