### ISSUE TITLE
[Feature Request] Optimize and harden IMDS endpoint calling logic

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#2177]
1. Instead of getting the json response from the imds endpoint for the compute node, there is an option to just get the region as text. Update the imds call to get the region as text.
2. Imds call does not need to retry if it fails. Update the HttpManager to add a method for imds calls.

**Comment by jmprieur** [comment]
@neha-bhargava :I believe you've been working on this ?

**Comment by neha-bhargava** [comment]
> @neha-bhargava :I believe you've been working on this ?

@jmprieur Just saw this comment. Yes I investigated this and will work on this.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
