### ISSUE TITLE
[Bug] WAM for console apps

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2196]
**Which Version of MSAL are you using ?**
4.23

**Platform**
.NET fwk, .NET Core

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

**Repro**

WAM does not work with console apps. When performing `AcquireTokenInteractive` without an IAccount, the account selector fails to display and an error similar to E_ACCESS_DENIED is thrown.

This is blocked on Windows team providing a solution.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
