### ISSUE TITLE
[Perf] Access tokens are listed too many times in AcquireTokenSilent / AcquireTokenForClient

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2204]
This issue impacts scenarios of large token cache, which is common for client credential flows (300k+ tokens). MSAL copies access tokens from memory into a list several times, which is a perf impact (TBD - numbers)

Technical details:

`InMemoryTokenCacheAccessor.GetAllAccessTokens()` iterates through the whole AT collection and returns a `List`. When `TokenCacheNotificationArgs.HasTokens` property is set, it calls `TokenCache.ITokenCacheInternal.HasTokensNoLocks()` which eventually calls `InMemoryTokenCacheAccessor.GetAllAccessTokens()`. `CacheSessionManager.RefreshCacheForReadOperationsAsync` sets that property twice.

So the AT dictionary ends up being iterated 3 times for a read, 2 times for a save. This can have a perf hit when cache has a large number of tokens.

Possible enhancement: Update `GetAllAccessTokens()` to not create a list or reduce the number of calls to `GetAllAccessTokens()`.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/24cb4663d91db1933b37253c8c1df2c16525818e/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryTokenCacheAccessor.cs#L155-L165
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/24cb4663d91db1933b37253c8c1df2c16525818e/src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs#L818-L822
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/24cb4663d91db1933b37253c8c1df2c16525818e/src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs#L106-L129

**Comment by neha-bhargava** [comment]
Fixed in [Msal release 4.24.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.24.0)
