### ISSUE TITLE
[Internal] Device Auth tests are not running.

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2207]
See https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=666112&view=ms.vss-test-web.build-test-results-tab - not tests found

**Comment by jennyf19** [comment]
@bgavrilMS the device auth tests seem to be passing now...maybe it was the build fix from earlier? idk. 
![image](https://user-images.githubusercontent.com/19942418/99588519-8dc57900-299f-11eb-844b-f30fc7c52810.png)
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=666395&view=results

**Comment by bgavrilMS** [comment]
They are passing because no tests are found.Test run takes 1s

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bgavrilMS** [comment]
![image](https://user-images.githubusercontent.com/12273384/99592357-04866480-29e8-11eb-8c83-c5efd770cc78.png)

**Comment by jennyf19** [comment]
oh i see.

**Comment by trwalke** [comment]
ill take a look

**Comment by jennyf19** [comment]
@trwalke i think i've got them working .i'll probably push up a PR tomorrow. have one more small issue to sort out w/publishing.

**Comment by jennyf19** [comment]
@trwalke I'll leave these Todo's for you to follow up on, as you set up the VM w/the lab and are more familiar w/the feature. Thanks.
TODO:
- [ ] Check which version of VS is on the windows 8 VM
- [ ] Try running the test on the VM, as it's not running correctly currently, as noted in the build logs, but it runs locally. Maybe the VM is missing something.
It's failing before even starting the test:
![image](https://user-images.githubusercontent.com/19942418/100037009-256b0300-2db6-11eb-9c4f-8c7c365eb41a.png)
Thank you!

**Comment by trwalke** [comment]
Made some progress on this. I am now able to get the test running on the agent by reconfiguring some of the parameters on the test task in YAML. There is an error to fix which I am investigating now but at least the test is actually being executed by ADO.

https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=707385&view=ms.vss-test-web.build-test-results-tab&runId=1422704&resultId=100001&paneView=debug

**Comment by trwalke** [comment]
Tests are now passing. a little bit of clean up and ill submit pr very soon
