### ISSUE TITLE
[Bug] When using "common", "organizations" or "consumers", client credential flow always misses the cache

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2212]
**Which Version of MSAL are you using ?**
all

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [x] Service to Service calls

The title says it all. I propose we ban "common" and "organizations" from client_crendential flow ASAP, without taking a breaking change as it is not a supported server feature. Not taking a breaking change will result in forcing more developers to do the right thing, thus reducing the load on EVO.

For "consumers" we will need some special handling, i.e. translate 'consumers' to the MSA tenant.

**Comment by bgavrilMS** [comment]
CC @henrik-me

**Comment by henrik-me** [comment]
Let's get telemetry on how much this is actually used.

**Comment by bgavrilMS** [comment]
Apollogies, after more careful inspection it looks like we simply store "realm: common"  in the token cache, as MSAL has no way of knowing the actual tenant ID, EVO does not tell us:

![image](https://user-images.githubusercontent.com/12273384/99650818-c6bc2700-2a4d-11eb-88cc-bc66d7c605cc.png)
