### ISSUE TITLE
[Bug] Sign-in is stuck for indefinite period for M365 admin mobile app customers using broker auth

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2218]
**Which Version of MSAL are you using ?**
4.22.0

**Platform**
xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue

Many of admin mobile app customers are complaining that they are not able to log into our app no matter how long they wait. We are able to successfully reproduce this on one of our test devices. I have attached the logcat log Chakra_IndefiniteSignIn_Nexus.txt here. PDJFJGNV is the company portal incident id pertaining to this log.

Our investigation reveals that flow is stuck while making GetAccounts call which never completes and below account manager crash is observed in the logs at the same time. No exception is thrown when this crash happens leaving our app waiting.

Also, I have attached another log Chakra_SuccessfulSignin5min_Nexus.txt where similar crash is observed while fetching token for a resource named O365 Portal. I have pasted relevant prints below so that you can correlate the timestamps in the broker logs.

 

Crash from Chakra_IndefiniteSignIn_Nexus.txt :

10-23 09:53:22.787 14033 14684 I mono-stdout: [2020-10-23 09:53:22.787] [Perf] Get Accounts Started for O365Portal -> (This call never ended)

10-23 09:53:22.825  2063  3154 E AccountManagerService: Account Manager Crash

10-23 09:53:22.825  2063  3154 E AccountManagerService: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: debug_table.action_type (code 1299)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at com.android.server.accounts.AccountManagerService.logRecord(AccountManagerService.java:4621)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at com.android.server.accounts.AccountManagerService.logRecordWithUid(AccountManagerService.java:4598)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at com.android.server.accounts.AccountManagerService.addAccount(AccountManagerService.java:2683)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:440)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:513)
10-23 09:53:22.825  2063  3154 E AccountManagerService: 	at android.os.Binder.execTransact(Binder.java:565)

Crash From Chakra_SuccessfulSignin5min_Nexus.txt :

10-23 10:20:18.812 21629 21830 I mono-stdout: [2020-10-23 10:20:18.812] [Perf] Fetching token silently for O365Portal started -> Silent token call started

10-23 10:20:18.861  2063  4317 E AccountManagerService: Account Manager Crash
10-23 10:20:18.861  2063  4317 E AccountManagerService: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: debug_table.action_type (code 1299)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at com.android.server.accounts.AccountManagerService.logRecord(AccountManagerService.java:4621)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at com.android.server.accounts.AccountManagerService.logRecordWithUid(AccountManagerService.java:4598)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at com.android.server.accounts.AccountManagerService.addAccount(AccountManagerService.java:2683)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:440)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:513)
10-23 10:20:18.861  2063  4317 E AccountManagerService: 	at android.os.Binder.execTransact(Binder.java:565)
 

10-23 10:25:19.078 21629 22200 I mono-stdout: [2020-10-23 10:25:19.077] [Perf]Exception while acquiring token for O365Portal. Error code: broker_application_required. -> MSAL threw exception after waiting for 5 min
10-23 10:25:19.078 21629 22200 I mono-stdout: Exception: MSAL.Xamarin.Android.4.20.1.0.MsalClientException: 
10-23 10:25:19.078 21629 22200 I mono-stdout: 	ErrorCode: broker_application_required
10-23 10:25:19.078 21629 22200 I mono-stdout: Microsoft.Identity.Client.MsalClientException: The current version of the broker may not support MSAL.Xamarin or power optimization is turned on. In order to perform brokered authentication on android you need to ensure that you have installed either Intune Company Portal (5.0.4689.0 or greater) or Microsoft Authenticator (6.2001.0140 or greater). see https://aka.ms/Brokered-Authentication-for-Android ---> System.ArgumentNullException: Value cannot be null

**Expected behavior**
MSAL should sign in with a reasonable amount of time.

**Actual behavior**
MSAL freezes for about 40-50 seconds during sign in.

**Possible Solution**
Implement content provider in MSAL

**Comment by trwalke** [comment]
Currently an ongoing investigation

**Comment by henrik-me** [comment]
Supporting Content Provider is a feature: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2150

**Comment by bgavrilMS** [comment]
Please follow the 2 underlying issues: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2144
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2150
