### ISSUE TITLE
[Fundamentals] Rename master branch to main

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#2220]
**Main branch**
_An inclusive new default_
New repos created within Microsoft orgs now have the default branch name of 'main'.

Teams are encouraged to rename their default branches if they are still using the 'master' branch name. This is an important, but not urgent, change.

**See more:**
https://repos.opensource.microsoft.com/

**Comment by jmprieur** [comment]
If we decide to do it, we also need to make sure we do a pass on the wiki, the Readme.md (all the .md files, actually, contribution.md etc ...), and docs.ms ....

Requires spec ....

**Comment by MichelZ** [comment]
I guess that one is complete @jmprieur @bgavrilMS

**Comment by jmprieur** [comment]
Thanks @MichelZ
