### ISSUE TITLE
AcquireTokenOnBehalfOfParameterBuilder does not support WithForceRefresh 

### ISSUE THREAD

**Issue by PetrPospisil** [AzureAD/microsoft-authentication-library-for-dotnet#2232]
**Is your feature request related to a problem? Please describe.**
We are using Microsoft.Identity.Web library. They internally use AcquireTokenOnBehalfOfParameterBuilder in order to get token. But this way the API lacks the WithForceRefresh functionality. Our application needs to refresh the OBO token in some cases, but we are unable to do so. 

I read the docs [https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of#how-to-call-obo](url) to use AcquireTokenOnSilent to be able to refresh the token. When I try to modify the code to call AcquireTokenOnSilent, it seems that the cache for AcquireTokenOnSilent gets a new own entry identified by user home account id... so AcquireTokenOnBehalfOf returns old token (from old cache entry identified by some token hash) and the AcquireTokenOnSilent returns new token (from new cache entry identified by user home account id)... 

I even tried to clear the cache manually, but I am unable to get the correct hash for the cache entry made by the AcquireTokenOnBehalfOf call.

**How can I refresh the cached token made by a AcquireTokenOnBehalfOf call?**

Please, help. Thx. :)

**Comment by bgavrilMS** [comment]
Yes, we should allow for `ForceRefresh` on all APIs that make use of the cache by themselves.

**Comment by bgavrilMS** [comment]
I think the only workaround at the moment is to to do `RemoveAccount` which will remove all accounts associated with that user, no matter what the original assertion cache is.

**Comment by PetrPospisil** [comment]
Hi, it seems that the workaround does not work.
The code looks similar to this.
`var authenticationResult = await tokenAcquisition.GetAuthenticationResultForUserAsync(TokenAcquisitionConstants.Scopes);
var type = tokenAcquisition.GetType();
var info = type.GetMethod("GetOrBuildConfidentialClientApplicationAsync", BindingFlags.Instance | BindingFlags.NonPublic);
var app = ((Task<IConfidentialClientApplication>)info.Invoke(tokenAcquisition, null)).GetAwaiter().GetResult();
app.RemoveAsync(authenticationResult.Account);`

**Comment by bgavrilMS** [comment]
Ok, we will make sure this gets prioritized in the next release, 4.24

**Comment by bgavrilMS** [comment]
I think you can still avoid loading the "Bad" tokens from the cache by completely avoiding the cache, but that may be complicated, for example by creating a new instance of ConfidentialClientApplication and by setting the cache serialization to NOT read the cache, but only write to it.

**Comment by PetrPospisil** [comment]
I could reset the instance of ConfidentialClientApplication using the reflection. Better then nothing. Thx for the tip.

**Comment by PetrPospisil** [comment]
I did what you suggested. I modified original cache implementation to remember and be able to remove all its entries and I reset ConfidentialClientApplication instance inside TokenAcquisition using reflection to be able to get the fresh token. It is really ugly hack, but at least it works with original Microsoft.Identity.Web nuget... Thx.

**Comment by bgavrilMS** [comment]
CC @jmprieur and @jennyf19  as this affects M.I.W
We will add .WithForceRefresh in MSAL 4.24, not sure if you need to make any changes on your side?

**Comment by jmprieur** [comment]
Sure we'll also update Microsoft.Identity.Web (as we'll need to call it).

**Comment by jennyf19** [comment]
@PetrPospisil this has been fixed in MSAL.NET, working on adding it to identity web. we need MSAL .NET to release first before we can have it in id web (fyi).

**Comment by neha-bhargava** [comment]
Fixed in [Msal release 4.24.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.24.0)
