### ISSUE TITLE
[Bug] WAM - AcquireTokenInteractive with picker does not need to force user to enter credentials

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2233]
**Which Version of MSAL are you using ?**
4.22

**Platform**
.net + uwp

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

**Repro**

1. Call AcquireTokenInteractive and login with account A
2. Call AcquireTokenInteractive with picker and again select account A

**Expected behavior**
Password (or FIDO or Hello) should not be collected again

**Actual behavior**
Creds are collected again

**Comment by neha-bhargava** [comment]
Fixed in [Msal release 4.24.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.24.0)
