### ISSUE TITLE
[Documentation] Nuget description error

### ISSUE THREAD

**Issue by kkrzysiek** [AzureAD/microsoft-authentication-library-for-dotnet#2240]
https://www.nuget.org/packages/Microsoft.Identity.Client/

there is a typo in the sentence: "(...)  These tokens again access to Mic(...)" -> should be "gain", not "again".

**Comment by jennyf19** [comment]
thanks for bringing this to our attention @kkrzysiek , will be in the next release.

**Comment by neha-bhargava** [comment]
Fixed in [Msal release 4.24.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.24.0)
