### ISSUE TITLE
[Bug] Sitting behind a gateway

### ISSUE THREAD

**Issue by IeuanWalker** [AzureAD/microsoft-authentication-library-for-dotnet#2245]
I've created a web app that is sitting behind an azure application gateway.

The web app isn't accessible directly and is only able to be accessed via the gateway endpoint, and using a multipath rule it forwards the requests to the azure web app address.

The Azure web service has an IP restriction on it, which only allows the WAF to communicate with it.

The identity package is redirecting users using the web apps app URL, rather than the gateways URL, causing the users to have an error as they cannot access the web app directly.

How do I override the host URL that MS authentication package is using to the gateway URL?

**Which Version of MSAL are you using ?**
Microsoft.Identity.Client - 4.19.0

**Platform**
netcore3.1

**What authentication flow has the issue?**
* Web App 
    * [x] Authorization code

**Is this a new or existing app?**
New in test at the moment hopefully live soon.

**Expected behavior**
Users to be redirected using the application gateway endpoint not the web app endpoint

**Actual behavior**
Users are being redirected using the web app endpoint causing an access issue

**Comment by jmprieur** [comment]
@IeuanWalker : would this help you? https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers ?

**Comment by IeuanWalker** [comment]
@jmprieur I don't think so.

For example, the external address is https://external.com/HWRCBookingAdmin/ sends the request down to https://interal.com/HWRCBookingAdmin/. But when MS auth library redirects the user it's using the internal address.

So for example if the user doesn't have access, it redirecting the user to https://interal.com/AzureAD/Account/AccessDenied?ReturnUrl=%2FHWRCBookingAdmin%2F instead of https://external.com/HWRCBookingAdmin/AzureAD/Account/AccessDenied?ReturnUrl=%2FHWRCBookingAdmin%2F

I've managed to override the login redirect URL by doing this in the startup, just set the environment variable called GatewayUrl on the app service to the external address i.e. https://external.com/ - 
```csharp
options.Events = new OpenIdConnectEvents
{
    OnRedirectToIdentityProvider = context =>
    {
        string replyUrl = Environment.GetEnvironmentVariable("GatewayUrl");
        if (!string.IsNullOrWhiteSpace(replyUrl))
        {
            context.ProtocolMessage.RedirectUri = replyUrl + "/signin-oidc";
        }
        return Task.FromResult(0);
    }
}
```

But not sure how to do the same sort of thing for access denied, also not sure there are other scenarios that it would redirect the user.

**Comment by jmprieur** [comment]
@IeuanWalker. I'd suggest you ask the question in the [aspnet core repo](https://github.com/dotnet/aspnetcore)
I would think that https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer would have solved your issue. 

BTW, given that you are using ASP.NET Core we strongly recommend that you use [Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web/wiki/1.0.0): think of it as MSAL.NET++ for ASP.NET Core web apps/APIs

**Comment by IeuanWalker** [comment]
@jmprieur thanks I'll take a look

**Comment by henrik-me** [comment]
@IeuanWalker : closing, however feel free to re-open if you have additional information or questions.
