### ISSUE TITLE
[Bug] WAM - AcquireTokenInteractive.WithAccount(DefaultOSAccount) should not show the account picker

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2246]
**Which Version of MSAL are you using ?**
4.23

**Repro**

ATS with default account, but get UIRequiredException (e.g. because of consent)
ATI using the same default account (as per sample app)

Actual: the account picker pops up
Expected: the account picker should not be used

**Comment by bgavrilMS** [comment]
I tried to use 

`RequestTokenForWindowAsync(IntPtr _parentHandle, WebTokenRequest webTokenRequest)` instead of 
` RequestTokenForWindowAsync(IntPtr _parentHandle, WebTokenRequest webTokenRequest, WebAccount wamAccount)`

Now the account picker isn't shown, but the WAM interactive window. On my machine I have 2 AAD accounts, so the window shows them both. I wonder if this is the expected behavior?

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
