### ISSUE TITLE
WAM - Update desktop sample

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2249]
We have an initial sample for UWP that integrates with WAM: https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/2-With-broker

We need to update our .NET sample as well: https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2 either in a separate directory (with-broker) or directly 

Intgrating with WAM is fairly straight-forward and I'm looking forward to feedback on the experience. Please see https://aka.ms/msal-net-wam for details

Questions for @jmprieur 

- deprecate or review the call WAM directly sample? https://github.com/azure-samples/active-directory-dotnet-native-uwp-wam
- do we want a separate directory "2-with-broker" for the the .NET sample or just use WAM as default?
- wouldn't we want a .NET Core sample as well?

**Comment by jmprieur** [comment]
@bgavrilMS : we have a multi-target (.NET Framework and .NET Core) desktop tutorial, which would be ideal to change: https://github.com/azure-samples/ms-identity-dotnet-desktop-tutorial

When we update it, indeed, we could archive https://github.com/azure-samples/active-directory-dotnet-native-uwp-wam

What happens if we run .WithBroker on a Windows 8 machine?

**Comment by bgavrilMS** [comment]
If you run on Win8, Mac or Linux, it reverts to using a browser

**Comment by bgavrilMS** [comment]
This is very cool, I think the wording can be improved a bit:

- most people don't know what WAM is, maybe we should just call it the windows broker
- WAM also allows sign in with any account, not just the ones known to Windows

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jmprieur** [comment]
Thanks @bgavrilMS. People don't know what a broker is either :)
For any account, yes, but the experience is a bit complex (the checkbox to have Windows not remember your account). I don't know if we want to keep it

**Comment by jmprieur** [comment]
@bgavrilMS : closing this issue as:
- https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2
- @Shama-K will work on the incremental tutorial (GitHub issue Azure-Samples/ms-identity-dotnet-desktop-tutorial#14)
