### ISSUE TITLE
[Bug] PlatformNotSupportedException in macOS App

### ISSUE THREAD

**Issue by tipa** [AzureAD/microsoft-authentication-library-for-dotnet#2251]
**Which Version of MSAL are you using ?**
MSAL 4.23.0
MSAL Extensions 2.16.5

**Platform**
Xamarin.macOS

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL

**Repro**

```csharp
var storageProperties = new StorageCreationPropertiesBuilder("msal_cache.dat", Environment.GetFolderPath(Environment.SpecialFolder.Personal), ClientId)
    .WithMacKeyChain(Foundation.NSBundle.MainBundle.BundleIdentifier, "msal_account")
    .Build();
var cacheHelper = await MsalCacheHelper.CreateAsync(storageProperties).ConfigureAwait(false);
cacheHelper.RegisterCache(pca.UserTokenCache);
```

**Expected behavior**
After updating MSAL to 4.2.30 I get a PlatformNotSupportedException when trying to add a token cache which is being thrown here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/79b57039a076391fe350a736fe9c951322fdd422/src/client/Microsoft.Identity.Client/TokenCache.Notifications.cs#L156-L164

**Actual behavior**
No exception when adding custom token cache

**Additional context/ Logs / Screenshots**
![Screenshot 2020-11-26 at 08 26 27](https://user-images.githubusercontent.com/2863198/100320192-21f79780-2fc1-11eb-9bb6-5651e3f745a3.png)

**Comment by bgavrilMS** [comment]
Keeping it open until we ship 4.24

**Comment by ghelyar** [comment]
For reference, we're also using this on Xamarin.Mac in order to use the macOS keychain as the token cache.

Without this, [iOS uses the keychain](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Platforms/iOS/iOSPlatformProxy.cs#L119), but [macOS does not](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Platforms/Mac/MacPlatformProxy.cs#L134).

**Comment by bgavrilMS** [comment]
Ack, please stay on MSAL 4.22 for now. Will get this shipped in 1-2 weeks.

**Comment by neha-bhargava** [comment]
Fixed in [Msal release 4.24.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.24.0)

**Comment by amirvenus** [comment]
Now that this issue is resolved, it would be great to add the macOS target to the existing Xamarin.Forms project as well.

**Comment by jmprieur** [comment]
@amirvenus : which existing Xamarin.Forms project? do you mean the test app in this repo? or a sample? (AAD? B2C?)

**Comment by amirvenus** [comment]
> @amirvenus : which existing Xamarin.Forms project? do you mean the test app in this repo? or a sample? (AAD? B2C?)

I meant this repo:
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native
