### ISSUE TITLE
Resilient of any downtime of AAD

### ISSUE THREAD

**Issue by rahul24** [AzureAD/microsoft-authentication-library-for-dotnet#2253]
### Documentation Related To Component: MSAL

https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult.isextendedlifetimetoken?view=azure-dotnet

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

I'm looking for a way to make my application more resilient to avoid any downtime from AAD. I found a way in the documentation below:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult.isextendedlifetimetoken?view=azure-dotnet

Can anyone pls help with the same - sample code of MSAL would certainly help?

**Comment by jmprieur** [comment]
@rahul24 : this is a legacy feature which is going to be deprecated in our next major version (and this is driven service side).
Let us come back to you with advice for resiliency.

**Comment by rahul24** [comment]
Thank you @jmprieur. I will be waiting for your reply on the resiliency part.

**Comment by bgavrilMS** [comment]
Hi @rahul24 - there are a few ideas around resilience here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability

There are a few initiatives that are being tried out internally, please email us for more details.

**Comment by rahul24** [comment]
@jmprieur - Can you confirm - this legacy feature is getting deprecated from server side code ("this is driven service side") or client side as well (MSAL.js)?

**Comment by jmprieur** [comment]
See also https://aka.ms/AzureADresilience
