### ISSUE TITLE
[Feature Request] Add optional api to provide region for regional auth scenarios

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#2259]
Add an optional api to provide region by the service. 

``` cs
.WithAzureRegion(true, UseRegion: <region>)
```

Refer to [this](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/2363?path=%2FPinAuthToRegion%2FAAD%20SDK%20Proposal%20to%20Pin%20Auth%20to%20region.md&_a=files&anchor=add-api-to-provide-an-option-to-specify-the-region-when-opting-for-regional-auth.) document for details.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
