### ISSUE TITLE
[Bug] AcquireTokenOnBehalfOfAsync is still visible in the Intellisene

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#2263]
**Which Version of MSAL are you using ?**
MSAL.NET 4.23.0

**Platform**
netcore

**Repro**
![image](https://user-images.githubusercontent.com/13203188/100887367-2fc38600-34b5-11eb-99d1-bf7450e0ac46.png)

**Possible Solution**
Apply the EditorBrowsable(false) attribute

**Comment by neha-bhargava** [comment]
Fixed in [Msal release 4.24.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.24.0)
