### ISSUE TITLE
[Feature] Enable WAM on net5.0-windows10.0.17763.0

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2274]
WAM to be enabled on net5.0-windows10.0.17763.0, the lowest net5-windows framework available. See https://blogs.windows.com/windowsdeveloper/2020/11/10/announcing-c-winrt-version-1-0-with-the-net-5-ga-release/ for more details about net5.0-windows

**Comment by j5aenz** [comment]
Thank you for setting up separate tracking on this. I think it's going to be the best bet for .Net 5 WPF with MVVM.

**Comment by bgavrilMS** [comment]
Keeping this open until we release 4.25

**Comment by j5aenz** [comment]
Can we expect a 4.25 release soon? i have 2 branches running .net framework and .net5 because i cannot get through the acquiretokeninteractive process. its a business need to keep it moving. not to pressure but any guidance would be helpful.

**Comment by bgavrilMS** [comment]
ETA is end of week, but this is not a commitment.

**Comment by j5aenz** [comment]
Thank you sir. I appreciate the info.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).

cc: @j5aenz
