### ISSUE TITLE
[Feature Request] Include `.WithTenantId()` in `AbstractAcquireTokenParameterBuilder`

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2280]
In MS Identity Web, we include the tenant if it's provided by the customer when doing the acquire token calls, but it would be better to use `.WithTenantId()`, like we can on the cca builder. This would enable us to remove the string parsing & concatenation we currently have to do to include the tenant w/the authority. 

cc: @jmprieur 

---

In fact, `WithTenantId()` should be the only option allowed, as we do not allow changes of environment. So we should obsolete (via warning) `WithAuthority` at request level and ask ppl to use `WithTenantId`

**Comment by jennyf19** [comment]
not a P1 issue.

**Comment by rymeskar** [comment]
+1. Introducing such configuration method would be in sync with what is on [AbstractApplicationBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractapplicationbuilder-1.withtenantid?view=azure-dotnet#Microsoft_Identity_Client_AbstractApplicationBuilder_1_WithTenantId_System_String_). Also, this way customers are no longer asked to worry about the authority base url when they already filled that out when configuring the CCA itself.

**Comment by rymeskar** [comment]
Is there any target date for this feature?
