### ISSUE TITLE
[Feature Request] Sample for ADAL and ADFS (2016)

### ISSUE THREAD

**Issue by devlanfear** [AzureAD/microsoft-authentication-library-for-dotnet#2282]
Are there any samples available for .NET for ADAL and ADFS 2016?

**Describe the solution you'd like**
Sample for .NET for ADAL and ADFS 2016 integration.
Xamarin as platform preferrable.

**Additional context**
Unfortunately, we can't use MSAL, because it requires ADFS2019

**Comment by jennyf19** [comment]
@kalyankrishna1 can you help with this one?

**Comment by devlanfear** [comment]
Hi @jennyf19  @kalyankrishna1 
Do you have any updates?
Thank you

**Comment by jmprieur** [comment]
@devlanfear 
the ADFS samples we have are here: https://github.com/Azure-Samples?q=adfs&type=&language=

This one seems to be using ADAL: https://github.com/Azure-Samples/active-directory-lab-hybrid-adfs

**Comment by jmprieur** [comment]
(Removed the labels as this would not be related to an MSAL improvement anyway.)

**Comment by devlanfear** [comment]
Thank you!
@jmprieur But looks like this one https://github.com/Azure-Samples/active-directory-lab-hybrid-adfs doesn't have ADAL

**Comment by jmprieur** [comment]
@kalyankrishna1 : do we have something?

**Comment by bgavrilMS** [comment]
ADFS 2016 is no longer supported.
