### ISSUE TITLE
Add logic to fallback to global endpoint if region detection through environment variable and imds fails.

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#2287]
In case MSAL fails to detect the region, fallback to global endpoint.

Please refer to the [design doc](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/2363?path=%2FPinAuthToRegion%2FAAD%20SDK%20Proposal%20to%20Pin%20Auth%20to%20region.md&discussionId=22632&_a=files&anchor=proposed-changes-to-add-resiliency-to-auto-region-detection) for details.

Currently we will only fallback to global when region detection fails and not when regional ests fail. For regional ests failures we are waiting on the ests-r team to provide us with the allow list of errors for which we need to fallback to global.

* Add an api FallbackToGlobal in the confidential client WithAzureRegion(AutoDetectRegion: true, FallbackToGlobal: true)
* Fallback logic in case we fail to detect the region -- first request decides this and then cache
* Add to telemetry if we are falling back to global for the request

**Comment by bgavrilMS** [comment]
@neha-bhargava @trwalke  - isn't this done?

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
