### ISSUE TITLE
Android TokenCachePlugin needs to use KeyStore

### ISSUE THREAD

**Issue by PilotC150** [AzureAD/microsoft-authentication-library-for-dotnet#229]
The iOS implementation of the TokenCachePlugin is already setup to use the iOS KeyChain and the Android version should go a similar route.  Storing the auth token in the SharedPreferences is not a secure solution.

Tagging @anujb

**Comment by kpanwar** [comment]
Keystore van

**Comment by PilotC150** [comment]
A security audit of our application, which currently uses the pre-release version of this that is in GitHub, came back complaining about where the auth token is stored.  The claim was that if somebody gains physical access to the mobile device they will be able to use the ADB utility to pull out some of the information in the Shared Preferences, which would give them the auth token.

I saw that the iOS implementation of the TokenCachePlugin uses the KeyChain so I was thinking the Android version should do a similar method.

If Shared Preferences are the best practice solution for this, is there any other way to make it more secure?

**Comment by kpanwar** [comment]
For that your phone must be rooted or the "attacker" must have the ability to execute adb root in some fashion. This would be no different than handing over your unlocked iOS or Android device to someone. If the phone is jailbroken or rooted, all bets are off. Storing tokens in keystore will not protect against any malware that could be installed to pull your credentials in transit which are higher order security bit than the token themselves.
