### ISSUE TITLE
How to implement custom token cache in Redis?

### ISSUE THREAD

**Issue by Mek7** [AzureAD/microsoft-authentication-library-for-dotnet#2297]
Hi,
I'm trying to implement a custom token cache so that tokens would be stored in Redis cache instead of in memory.
I have started with this [sample application](https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect). Unfortunately, it's using ADAL so I had to rework it to use MSAL. I know that sample has been archived and there is a newer version, but that one is in .NET Core, but my application where I have to incorporate MSAL into, still uses classic .NET Framework.
Now the "sign up", "sign out" and "sign in" flows work correctly in the example application from UI perspective, however I don't understand what happens with the cached tokens.
This is the code how I initialize the confidential application:
```
        public static Lazy<IConfidentialClientApplication> ClientApplication = new Lazy<IConfidentialClientApplication>(() =>
        {
            // initialize credentials
            var app = ConfidentialClientApplicationBuilder
                .Create(Startup.ClientId)
                .WithClientSecret(Startup.AppKey)
                .WithTenantId(Startup.TenantId)
                .WithRedirectUri("https://localhost:44302/Onboarding/ProcessCode")
                .Build();

            app.UserTokenCache.SetBeforeAccess(args =>
            {
                    // read data from cache
                    var data = CacheProvider.Value.GetObject<byte[]>(args.SuggestedCacheKey);
                    args.TokenCache.DeserializeMsalV3(data);
            });

            app.UserTokenCache.SetAfterAccess(args =>
            {
                // write data to cache
                var data = args.TokenCache.SerializeMsalV3();
                if (data == null)
                {
                    CacheProvider.Value.Invalidate(args.SuggestedCacheKey);
                }
                else
                {
                    CacheProvider.Value.AddOrUpdate(args.SuggestedCacheKey, data, a => data, expirationMode: ExpirationMode.Absolute, expireAfter: TimeSpan.FromHours(1));
                }
            });

            return app;
        });
```
In the sample application, there is User table in database, Tenant table in database, and Redis cache for token caching.
Assume I start with empty cache and empty tables in DB. First, I have to Sign up, otherwise I could not sign in. This goes well, and as a result, one record is inserted in Tenant table, one record in User table, and one record in Redis cache, which looks like this (I edited some data to not reveal real data)
```
{
  "AccessToken": {
    "someguid.someguid-login.windows.net-accesstoken-someguiduser.read user.read.all profile openid email": {
      "home_account_id": "someguid.someguid",
      "environment": "login.windows.net",
      "client_info": "longstring",
      "client_id": "someguid",
      "secret": "verylongstring",
      "credential_type": "AccessToken",
      "realm": "someguid",
      "target": "User.Read User.Read.All profile openid email",
      "cached_at": "1607678851",
      "expires_on": "1607682450",
      "extended_expires_on": "1607682450",
      "ext_expires_on": "1607682450"
    }
  },
  "RefreshToken": {
    "someguid.someguid-login.windows.net-refreshtoken-someguid--": {
      "home_account_id": "someguid.someguid",
      "environment": "login.windows.net",
      "client_info": "somestring",
      "client_id": "someguid",
      "secret": "verylongstring",
      "credential_type": "RefreshToken"
    }
  },
  "IdToken": {
    "someguid.someguid-login.windows.net-idtoken-someguid-": {
      "home_account_id": "someguid.someguid",
      "environment": "login.windows.net",
      "client_info": "somestring",
      "client_id": "someguid",
      "secret": "verylongstring",
      "credential_type": "IdToken",
      "realm": "someguid"
    }
  },
  "Account": {
    "someguid.someguid-login.windows.net-someguid": {
      "home_account_id": "someguid.someguid",
      "environment": "login.windows.net",
      "client_info": "somestring",
      "username": "some@user.com",
      "name": "My real name",
      "local_account_id": "someguid",
      "authority_type": "MSSTS",
      "realm": "someguid"
    }
  },
  "AppMetadata": {
    "appmetadata-login.windows.net-someguid": {
      "environment": "login.windows.net",
      "client_id": "someguid"
    }
  }
}
```
Up to now, all looks correct. Now I click Sign in. I am signed in without asking for credentials, and data in DB and cache are not changed.
The problem happens when I now click Sign out. I am signed out correctly, records in both DB tables are still the same, but in Redis cache the record now is much shorter and doesn't contain tokens:
```{"AccessToken":{},"RefreshToken":{},"IdToken":{},"Account":{},"AppMetadata":{"appmetadata-login.windows.net-someguid":{"environment":"login.windows.net","client_id":"someguid"}}}```
I would expect the record to be deleted from cache, not updated.
The code executed when Sign out is clicked, includes the following:
```
            string signedInUserID = ClaimsPrincipal.Current.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            string tenantID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid")?.Value;
            string objectID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier")?.Value;

            if (!string.IsNullOrWhiteSpace(signedInUserID) && !string.IsNullOrWhiteSpace(tenantID))
            {
                var account = Task.Run(() => Statics.ClientApplication.Value.GetAccountAsync(objectID + "." + tenantID)).GetAwaiter().GetResult();

                Task.Run(() => Statics.ClientApplication.Value.RemoveAsync(account)).GetAwaiter().GetResult(); // breakpoint here shows that account is not null so it was found and is passed to RemoveAsync method
            }
```

I have put breakpoints on the RemoveAsyncCall (above) and also in the cache handlers - SetBeforeAccess and SetAfterAccess. I can see that when I call RemoveAsync, the shorter data (without tokens) are passed to the handler to update the cache, not delete.
From this point, it all breaks.
Now I sign in again, and the cache record is not updated, but from UI perspective I am signed in correctly.
Now when I sign out again, cache record is not updated and also not deleted, and that's because when calling RemoveAsync method, account variable is null.
Now I clear the cache manually and Sign in again. This time, no record is inserted to cache at all.
I don't understand. Is this a bug or should I implement Redis cache for the tokens differently?

**Comment by jmprieur** [comment]
@Mek7 
We'd recommend you look at this sample which is both for .NET Core and .NET. 
https://github.com/Azure-Samples/active-directory-dotnet-v1-to-v2/tree/master/ConfidentialClientTokenCache

Microsoft.Identity.Web provides a token cache adapter for distributed token cache, and .NET proposes a redis implementation
https://github.com/Azure-Samples/active-directory-dotnet-v1-to-v2/blob/8040d7895fdef263900e69910b2549b773696f0b/ConfidentialClientTokenCache/Program.cs#L109-L118

**Comment by Mek7** [comment]
Thank you for your reply. I used the HasTokens property and now the cache entry is deleted instead of left pretty empty.
That, however, does not explain why, upon second login, no cache entry appears at all.
Anyway, I tried the example you suggested. Unfortunately, Microsoft.Identity.Web doesn't support .NET Framework 4.6.1 that I'm stuck with and upgrading to 4.7.2 is currently not possible.
```
Error	NU1202	Package Microsoft.Identity.Web 1.4.0 is not compatible with net461 (.NETFramework,Version=v4.6.1) / win-x86. Package Microsoft.Identity.Web 1.4.0 supports:
  - net472 (.NETFramework,Version=v4.7.2)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1)
```
Any suggestions?

**Comment by jmprieur** [comment]
@Mek7 : On the second login, do you get an account? there are several claims depending on the endpoint (Azure AD v2.0 / v1.0), and what the web API requests

you might want to have a look at this: https://github.com/AzureAD/microsoft-identity-web/blob/c5c714729e8aed1b2045105c732e8e51eea140d0/src/Microsoft.Identity.Web/ClaimsPrincipalExtensions.cs#L19

as well as this ASP.NET sample: https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect

**Comment by Mek7** [comment]
OK, I got it. I was missing a call to AcquireTokenByAuthorizationCode in AuthorizationCodeReceived callback of
OpenIdConnectAuthenticationNotifications
 ```
                        AuthorizationCodeReceived = async context =>
                        {
                            var code = context.Code;

                            // The following operation fetches a token and caches it in the token cache
                            await Statics.ClientApplicationForSignIn.Value.AcquireTokenByAuthorizationCode(new string[] { "User.Read" }, code).ExecuteAsync();
                        },
```
I had to create a second IConfidentialClientApplication because there is a different callback url for sign in than for sign up.
Now values are inserted and updated in the cache everytime I would expect 👍 
One more question though. The Redis cache allows to set expiration time of the records. Of course, it can be also set so that the records never expire. I have seen some properties of the cached value:
![image](https://user-images.githubusercontent.com/12199478/101914174-3a240500-3bc4-11eb-8cc4-b8cb5479b30a.png)
expiration = 3, timeout = 3600000
But it's not a good idea to parse the value in the SetAfterAccess to look at the timeout, because the structure of the value is subject to change. Is there a different way to find out the expiration time of the value that we can set before it is persisted to Redis cache? If not, would storing it without expiration be acceptable?
What would happen if the cache record disappeared? We want to use MSAL only for login, no other operations will be performed under the user account. I think it would just forget the user and require to log in again when he visits the website again (I didn't see a 'remember me' option in the MS login form, but that doesn't mean there isn't one...)

**Comment by jmprieur** [comment]
@Thanks for the update @Mek7.
Yes, if the record disappeared, the user will need to be re-signed-in (Challenged in ASP.NET terms)
For your last question about values, let's follow-up in https://github.com/AzureAD/microsoft-identity-web/issues/786 if you don't mind.

**Comment by Mek7** [comment]
Ok, this problem was solved so I am closing the issue.
