### ISSUE TITLE
[Documentation] Add “SECURITY: some security fix” and “RESILIENCY: some resiliency fix” to existing release notes

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#2298]
Update all past release notes to point out security and resilience improvements and fixes.

“SECURITY: some security fix” 
“RESILIENCY: some resiliency fix”

**Comment by gladjohn** [comment]
@pmaytak do you have any background on this? is this still applicable?

**Comment by pmaytak** [comment]
Yea, still applicable. We've been adding those tags to the changelog in few recent updates, but I don't think we went through historical releases, unless @bgavrilMS did? I would also maybe define what items fall under those two categories.

**Comment by bgavrilMS** [comment]
See examples in more recent releases :)
