### ISSUE TITLE
[Bug] Remove WAM support from .NET FwK as it's causing issues for asp.net

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#2299]
Remove WAM support for .net fwk. 

See details of the challenges: 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2247

Will add support for WAM for .net fwk in a separate package.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
