### ISSUE TITLE
[Feature] Add WAM Support to a separate package for netfwk and netcore

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#2300]
Issues with dependencies are/were causing trouble updating to the latest MSAL for ASP.NET to address this we will be adding WAM support to a separate package.

Final design TBD

**Related Issues:**
Removal from Core package: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2299
Challenge: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2247

**Comment by charlesroddie** [comment]
How are you going to make this discoverable? I assume that WAM is necessary to make authentication work correctly on Windows. Then how are consumers of this library informed that they will need to install it and integrate it on order to get their windows App working properly?

**Comment by jmprieur** [comment]
We are still thinking of what the best experience could be

@charlesroddie: If you are using .NET 5, there is a distinction between the the desktop platform and the web platform, and therefore, .WithBroker(true) would be available.

For .NET 4.6.1, 4.5, we could have .WithBroker throwing a meaningful exception telling you to add the separate NuGet package

Any feedback or idea is welcome.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
