### ISSUE TITLE
[Feature Request] Review sending PKAuth on unsupported platforms

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2302]
Today, on pretty much all platforms, MSAL advertises that it is PKAuth capable, and when ESTS challenges the app, MSAL simply states "oh, I can't actually do PKAuth". This seems very wasteful for ESTS (extra network call). Behaviour was copied from ADAL but no actual confirmation from ESTS that it is the right thing to do. 

Affected platforms: 

- .NET (FWK and Core) on Win10
- UWP
- mobile

**Comment by bgavrilMS** [comment]
Related to: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1849

**Comment by trwalke** [comment]
Issue has been identified on the UAP target. MSAL.UAP should be replaying the challenge with the bypass response but is instead throwing an exception by mistake. Will be resolved by next release

**Comment by bgavrilMS** [comment]
I still think we should not send the PKAuth capability to ESTS unless OS = win10 and tfm = .net fwk or .net core

**Comment by jmprieur** [comment]
@bgavrilMS do you mean OS = win10? or != win10 ?

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2026

**Comment by bgavrilMS** [comment]
Let's continue to track the work on #1849

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
