### ISSUE TITLE
[Feature Request] Investigate using MSAL on WinUI

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2307]
Windows UI Library (WinUI) 3 is a native user experience (UX) framework for both Windows Desktop and UWP apps. It aims to unify Windows Desktop with UWP.

We need to investigate how a WinUI app would integrate with MSAL: 

- WAM integration (likely to "just work")
- system browser (unlikely to work on UWP)
- embedded browser (should work since embedded browsers are available on both platfomrms)
- WebView2 (WinUI docs seem to suggest that this is supported on UWP)

**Comment by bgavrilMS** [comment]
probably nothing to do

**Comment by rslavey** [comment]
@bgavrilMS Please see https://github.com/microsoft/microsoft-ui-xaml/issues/5143

**Comment by bgavrilMS** [comment]
Yes, tracking external issue - https://github.com/microsoft/microsoft-ui-xaml/issues/5143
