### ISSUE TITLE
Enable embedded view support for .NET Core/.NET 5.0 Windows Forms projects

### ISSUE THREAD

**Issue by luisabreu** [AzureAD/microsoft-authentication-library-for-dotnet#2310]
Currently, embedded view support (for the login window) is disabled for all .NET Core/.NET 5.0 projects. Since .NET Core/.NET 5.0 now support Windows Forms, it would be a good idea to allow the use of embedded views for the login page for those type of projects.

**Comment by bgavrilMS** [comment]
Thx for opening. We've actually just implemented this for .NET5 and will be in the next release 4.25.0 (due to holiday season, likely to be in Jan).

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2281

**Comment by SundayRX** [comment]
Does the latest 4.25.0 version support .NET 5 WPF Porject?

**Comment by bgavrilMS** [comment]
@SundayRX yes. We should be able to release sometimes next week

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).

cc: @luisabreu @SundayRX
