### ISSUE TITLE
[Investigation] call to regional then global results in 2 access tokens

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2314]
### Repro:
- run `AcquireTokenToRegionalEndpointThenGlobalEndpoint_UseTokenFromCacheAsync()`
- put a break point on line 43 of ClientCredentialRequest & line 311 of TokenCache.ITokenCacheInternal -> in FindAccessTokenAsync() -> `tokenCacheItems = await FilterByEnvironmentAsync(requestParams, tokenCacheItems).ConfigureAwait(false);` & line 127 of InstanceDiscoveryManager -> `if (autoDetectRegion)`

First time through, the Regional endpoint is hit & a token is cached.
Second time through, w/Global endpoint...

MSAL looks in the cache first, and finds one item (note the Environment value)
![image](https://user-images.githubusercontent.com/19942418/102549385-db9dd180-4070-11eb-9a11-d2bef6dad4e3.png)

Then, MSAL filters by environment, using the authority, which is `https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/` and does not find a matching environment, so it returns no cache items.

MSAL then goes to the global endpoint and gets a token in the cache.

There are now two tokens in the cache, one for global and one for regional environment.
![image](https://user-images.githubusercontent.com/19942418/102549856-b2ca0c00-4071-11eb-8cc1-4513d36c6918.png)

**Token 1: (Regional)**
![image](https://user-images.githubusercontent.com/19942418/102550070-0d636800-4072-11eb-8824-b86c06976db2.png)

**Token 2: (Global)**
![image](https://user-images.githubusercontent.com/19942418/102550212-4dc2e600-4072-11eb-86cb-a13fc46ab8cf.png)

=====
### Global first, and then Regional
If you go Global endpoint first, and then Regional next, there is only one token in the cache, because the Regional authority has not been changed to the Regional authority/environment, so it can reuse the Global token in the cache.

![image](https://user-images.githubusercontent.com/19942418/102551289-16553900-4074-11eb-931f-a70c31676118.png)

**Tokens can be used across regional boundaries.**
 
## **To Investigate:**
- Is our current implementation "good enough"?
- Is this behavior optimal. Can we identify the region earlier and/or map to login.windows.net?
- Something else?

**Comment by bgavrilMS** [comment]
This has been fixed, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/836272468a92153e7d79e43440729704f139cd4b/tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithRegionTests.cs

Tokens obtained from the regional authority will be stored in the cache with the non-regional authority value. This ensures that switching from regional to global works.
