### ISSUE TITLE
[Bug] Sign in with Apple is sometimes failing with error code AADB2C90289

### ISSUE THREAD

**Issue by charlesroddie** [AzureAD/microsoft-authentication-library-for-dotnet#2318]
Reports from App center across all iOS, Android, UWP, Mac

The logging error message is
```
(False) MSAL 4.13.0.0 MSAL.Xamarin.iOS 14.0.1 [12/28/2020 22:29:06 - 4cddcefb-309a-46a
```

This was given from
```
PublicClientApplicationBuilder.Create(appId) .WithLogging(LogCallback(...),...)
```

We need to diagnose this immediately but the error is not helpful.

**Comment by charlesroddie** [comment]
Also got a separate report; could be a B2C issue?

```
Microsoft.Identity.Client.MsalServiceException: AADB2C90289: We encountered an error connecting to the identity provider. Please try again later. Correlation ID: 1ea67eda-e621-45ca-ad67-2fca95506f47 Timestamp: 2020-12-23 05:37:16Z
```

**Comment by jmprieur** [comment]
@charlesroddie : yes this is on the service side. Maybe a configuration error of the identity provider?
Definitively not an MSAL.NET issue.

**Comment by charlesroddie** [comment]
Is MSAL responsible for error messages? As mentioned above, we are using WithLogging which internally gives us a `string` message. This `string` is a human-readable thing which may contain helpful things like "ErrorCode: " with a subsequent `string` matching one of the MsalError `string`s, or a sentence "Authorization result was not successful. See error message for more details."

Does the error message `"(False) MSAL 4.13.0.0 MSAL.Xamarin.iOS 14.0.1 [12/28/2020 22:29:06 - 4cddcefb-309a-46a"` contain any useful information?

**Comment by jmprieur** [comment]
@charlesroddie it's a MsalServiceException, which means this is provided by the service (Azure AD as this is a AADB2C90289 error). MSAL cannot display more information than it receives from the service. It might be that the "Authorization result was not successful. See error message for more details." comes from the IdP managed by B2C, and that B2C does not transfer the full error message?

Did you try to run the policy from the B2C portal?

**Comment by charlesroddie** [comment]
Thanks for the info. The truncation was an app center issue. Most of these errors were not as critical as thought and may not have resulted in anything that users would notice.

**Comment by charlesroddie** [comment]
@kevcrooks found more info on this

> @kevcrooks
> 
> We have set up a "Sign in with Apple" user flow in B2C, and are using this from our client app with msal.
> 
> We do the same for multiple other sign-in methods, all of which are working fine. Furthermore "Sign in with Apple" is working fine for us, both in Debug mode and in TestFlight, but our app has been rejected multiple times during Apple review, with an error signing in.
> 
> We have a log of the error, but don't understand why this is failing only some of the time. I understand from related posts (e.g. [azure-ad-b2c/samples#104 (comment)](https://github.com/azure-ad-b2c/samples/issues/104#issuecomment-678608721)) that this error might be caused if the client _secret_ was incorrect, but this should cause the sign-in to always fail.
> 
> I've also refreshed the client secret, and this hasn't changed anything - the sign in still works for us, and is rejected by Apple.
> 
> **Error and stack trace
> `Microsoft.Identity.Client.MsalServiceException: AADB2C90289: We encountered an error connecting to the identity provider. Please try again later. Correlation ID: 708958a3-ab9e-43a5-aa5e-ccf0f7535cee Timestamp: 2021-01-06 19:42:20Z`
> 
> ```
> Microsoft.Identity.Client.Internal
> AuthCodeRequestComponent.VerifyAuthorizationResult (Microsoft.Identity.Client.UI.AuthorizationResult authorizationResult, System.String originalState)
> Microsoft.Identity.Client.Internal
> AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync (Microsoft.Identity.Client.UI.IWebUI webUi, System.Threading.CancellationToken cancellationToken)
> Microsoft.Identity.Client.Internal
> AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync (System.Threading.CancellationToken cancellationToken)
> Microsoft.Identity.Client.Internal.Requests
> InteractiveRequest.GetTokenResponseAsync (System.Threading.CancellationToken cancellationToken)
> Microsoft.Identity.Client.Internal.Requests
> InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
> Microsoft.Identity.Client.Internal.Requests
> RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken)
> Microsoft.Identity.Client.ApiConfig.Executors
> PublicClientExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenInteractiveParameters interactiveParameters, System.Threading.CancellationToken cancellationToken)
> FSharp.Control.Tasks
> TaskBuilder+bindTask@121[b,a].Invoke (Microsoft.FSharp.Core.Unit unitVar0)
> FSharp.Control.Tasks
> TaskBuilder.tryWith[a] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] step, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] catch)
> ```
> 
> This is an existing app that has previously been approved by Apple, but because we're not able to reproduce the failure locally, we don't have any ideas of how to diagnose or fix. Is there anything that could cause this exception only on some devices or some sign-ins - or any suggestions to diagnose/fix? Because of the error, it's not clear to us if we should look at the user flow, our use of msal to call the user flow, or the configuration in our Apple account?

**Comment by charlesroddie** [comment]
@jmprieur The last post from @kevcrooks gives a correlation ID and stacktrace. Does this still indicate it is unrelated to MSAL?

**Comment by jennyf19** [comment]
@charlesroddie if this is a sign-in with apple issue, we also need the b2c tenant name and policy name.

As @jmprieur pointed out, this is a server side issue.

**Comment by kevcrooks** [comment]
Thank you @jennyf19, we were able to ask Apple to try the sign-in using a web-only version of our policy, which also failed with an error. So this means it's not related to msal or our app, as @jmprieur mentioned, so we'll raise this with Azure or Apple separately and this issue can be closed @charlesroddie
