### ISSUE TITLE
[Investigate] Ensure that all builds/Tests run on PR do not run on forked Repos.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2323]
We need to be sure that all builds/Tests that are run on PR branches do not run on forked Repos. There is a potential for there to be a security issue and we need to be sure it is not a problem before turning on certain build tasks. 

For more details, See [important security considerations](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#important-security-considerations)

**Comment by jennyf19** [comment]
@pmaytak mentioned, @trwalke had done this, just confirmed, so closing.
![image](https://user-images.githubusercontent.com/19942418/114069371-c6cd8f80-9853-11eb-8bef-233f59c17b2a.png)
