### ISSUE TITLE
Cache key for Access Tokens differs between user type Member and user type Guest in single tenant application 

### ISSUE THREAD

**Issue by bmukes** [AzureAD/microsoft-authentication-library-for-dotnet#2327]
This goes along with
[Sample for ms-identity-aspnet-webapp-openidconnect-master throws exception on AcquireTokenSilent](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2324)

**Which Version of MSAL are you using ?**
4.24.0

**Platform**
ASP.NET 4.72

**What authentication flow has the issue?**
* Web App 
    * [x] Authorization code
**Is this a new or existing app?**
 This is a new app or experiment
**Repro**

- I am using an unverified AAD tenant that will be referred to as Tenant A.
- Create an application for OIDC Authorization flow with Supported account type of Single tenant.
- Add a user of user type _Member_ from Tenant A.
- Invite a guest user from a verified AAD tenant that will be referred to as Tenant B
- Add both users to the application.
- Create a client secret for the application
- Copy the client id, client secret, tenant id to the web.config app settings
- Set the redirect uri of the application to https://localhost:44388/signin-oidc

See the code in
[GitHub of ASP.NET project using MSAL](https://github.com/bmukes/TestMSAL.git)
Set a breakpoint in OnAuthorizationCodeReceivedAsync in Startup.Auth.cs right after the call to
```
			AuthenticationResult result = await clientApp.AcquireTokenByAuthorizationCode(new[] { "openid", "profile", "offline_access" }, notification.Code)
				.ExecuteAsync();
```
Run the code logging in as both users and observe the results

Add the variable result in your watch window, expand Account and look at the HomeAccountId

**Expected behavior**
That the value used for the cache key (HomeAccountId) would be the objectid and tenant id from Tenant A for both users.

**Actual behavior**
the value used for the cache key (HomeAccountId) for the guest user is the objectid and tenant from the AAD Tenant B.

This means that a call to 
`IAccount account = await app.GetAccountAsync(ClaimsPrincipal.Current.GetAccountId());`
will always return null for the guest user because the claims used by the GetAccountId extension will always contain values from Tenant A while the cached access token is using values from Tenant B.

**Additional context/ Logs / Screenshots**

Screen Shot user type Member
![image](https://user-images.githubusercontent.com/2730181/103931169-18437280-50dd-11eb-878a-d0ff28443a57.png)

Screen Shot User type Guest

![image](https://user-images.githubusercontent.com/2730181/103931405-7cfecd00-50dd-11eb-8485-b5d1247eb30f.png)

Notice that the TenantId shows that both users are from Tenant A and that the Account is using values from Tenant B.

**Comment by bmukes** [comment]
OK I figured out a hack for this issue but I still think this is a bug.  Note this is referencing the code in the Github link above.

1. Create a singleton to hold the IConfidentialClientApplication instance.

```
    public sealed class ConfidentialClientSingleton
    {
        private static readonly IConfidentialClientApplication instance = AsyncHelper.RunSync<IConfidentialClientApplication>(() => MsalAppBuilder.BuildConfidentialClientApplication());
        // Explicit static constructor to tell C# compiler  
        // not to mark type as beforefieldinit  
        static ConfidentialClientSingleton()
        {
        }
        private ConfidentialClientSingleton()
        {
        }
        public static IConfidentialClientApplication Instance
        {
            get
            {
                return instance;
            }
        }
    }
```

2.  add the following notification code in Startup.Auth.cs

```
        private async Task OnSecurityTokenValidatedNotification(SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> notification)
        {
            AuthenticationResult result =  notification.OwinContext.Environment["OnAuthorizationCodeReceivedAsync-AuthenticationResult"] as AuthenticationResult;
            if (result != null)
            {
                notification.AuthenticationTicket.Identity.AddClaim(new System.Security.Claims.Claim(ClaimConstants.UniqueObjectIdentifier, result.Account.HomeAccountId.ObjectId));
                notification.AuthenticationTicket.Identity.AddClaim(new System.Security.Claims.Claim(ClaimConstants.UniqueTenantIdentifier, result.Account.HomeAccountId.TenantId));
            }
            await Task.CompletedTask;
        }
        async Task OnAuthorizationCodeReceivedAsync(AuthorizationCodeReceivedNotification notification)
        {
 
            //IConfidentialClientApplication clientApp = await MsalAppBuilder.BuildConfidentialClientApplication();
            IConfidentialClientApplication clientApp = ConfidentialClientSingleton.Instance;
            
            AuthenticationResult result = await clientApp.AcquireTokenByAuthorizationCode(new[] { "openid", "profile", "offline_access" }, notification.Code)
				.ExecuteAsync();
	    notification.HandleCodeRedemption(result.AccessToken, result.IdToken);
            notification.TokenEndpointResponse.Scope = String.Join(" ", result.Scopes);
            notification.OwinContext.Environment.Add("OnAuthorizationCodeReceivedAsync-AuthenticationResult", result);
	}
```
3.  Anyplace you need an access token use the following code

```
            IConfidentialClientApplication app = ConfidentialClientSingleton.Instance;

            IAccount account = AsyncHelper.RunSync<IAccount>(()=> app.GetAccountAsync(ClaimsPrincipal.Current.GetMsalAccountId()));
            if (account != null)
            {
               AuthenticationResult result = AsyncHelper.RunSync<AuthenticationResult>(() => app.AcquireTokenSilent(new[] { "openid", "profile", "offline_access" }, account).ExecuteAsync());
            }
```

Any comments would be greatly appreciated as I really need to put this issue to bed for now.

**Comment by bmukes** [comment]
Hopefully, this will be my last post on this issue.  I am trying to use MSAL to cache the access token returned from the OIDC Authorization Code Flow.  Right now the ASP.NET application where I intend to use MSAL does not call any back end REST services.  But hopefully that will change in the future.   I would like to use the cached access token against future back end REST services.

**Comment by jmprieur** [comment]
@bmukes, we need to be better at supporting ASP.NET. I think that in your case we are missing the UserInfo.

**Comment by bmukes** [comment]
So based on your reply I guess I should be using the Microsoft.IdentityModel.Clients.ActiveDirectory library instead of MSAL?

**Comment by jmprieur** [comment]
No. We don't recommend you use ADAL. It's on the deprecation path: 
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

I just need to provide you with a sample that handles the guest accounts (call the user info endpoint, and get the right claims)

**Comment by Fresa** [comment]
@bmukes `OnSecurityTokenValidatedNotification` is called before `OnAuthorizationCodeReceivedAsync`: https://github.com/c4net/katanaproject/blob/df66bf44ffc4b5de0ec9a837f4a470614a9c68bf/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L337

It seems however that the same instance of the `AuthenticationTicket` is used in both handlers, so the claims can be added in the `OnAuthorizationCodeReceivedAsync` handler instead.

It also solves the problem that uid and uidt is completely missing for some reason among the claims parsed (which is used by [ClaimsPrincipalExtensions.GetMsalAccountId](https://github.com/AzureAD/microsoft-identity-web/blob/4ec973fb26ba3c489fa1408a27ddb374b36b1e84/src/Microsoft.Identity.Web/ClaimsPrincipalExtensions.cs#L19).

**Comment by llx9** [comment]
@jmprieur We recently got the same issue on looking up token cache for guest user accont. the token cache key is userId and tenantId from original tenant while when looking up cache it uses the host tenant's userId and tenantId.

**Comment by jmprieur** [comment]
@bgavrilMS @pmaytak

**Comment by bgavrilMS** [comment]
@jmprieur - what did you have to do to get this working in ASP.NET Core?

**Comment by jmprieur** [comment]
MSAL.NET uses the notion HomeAccountId, which is the concatenation of the home tenant Id and the home object ID of the user.
In a single tenant application, there can be guest users.
Guest users are users who are invited to the tenant, and therefore, their home account id is the account id in their original (home) temant. It's not the account id in this tenant.

To compute the home account ID, in the case of single tenant applications, you need to request the [ClientInfo](https://github.com/AzureAD/microsoft-identity-web/blob/4feafe34aea127dc688e33c156b9f5a1ee59557a/src/Microsoft.Identity.Web/ClientInfo.cs), which is done by updating the request to the identity provider (see [here](https://github.com/AzureAD/microsoft-identity-web/blob/0e8a08d8c55edf3aec695a809d189d2ac4b770d9/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L371), and when the ID token come back to extract this information, which is done [there](https://github.com/AzureAD/microsoft-identity-web/blob/ce9d7322072b0ffd08cd8abd9027c958d1a52e1b/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs#L153-L164)

```CSharp
                           string? clientInfo = context!.ProtocolMessage?.GetParameter(ClaimConstants.ClientInfo);


                           if (!string.IsNullOrEmpty(clientInfo))
                           {
                               ClientInfo? clientInfoFromServer = ClientInfo.CreateFromJson(clientInfo);


                               if (clientInfoFromServer != null && clientInfoFromServer.UniqueTenantIdentifier != null && clientInfoFromServer.UniqueObjectIdentifier != null)
                               {
                                   context!.Principal!.Identities.FirstOrDefault()?.AddClaim(new Claim(ClaimConstants.UniqueTenantIdentifier, clientInfoFromServer.UniqueTenantIdentifier));
                                   context!.Principal!.Identities.FirstOrDefault()?.AddClaim(new Claim(ClaimConstants.UniqueObjectIdentifier, clientInfoFromServer.UniqueObjectIdentifier));
                               }
                           }
```

Indeed, the homeAccountId is retrieved by ClaimsPrincipal.GetMsalAccountId() defined [here](https://github.com/AzureAD/microsoft-identity-web/blob/b31140ff2d7478c86ef668edca3164aa7fd6846c/src/Microsoft.Identity.Web.TokenCache/ClaimsPrincipalExtensions.cs#L80-L98)

**Comment by jmprieur** [comment]
@kalyankrishna1 can we please update the ASP.NET sample?

**Comment by jmprieur** [comment]
See also https://stackoverflow.microsoft.com/questions/277321/277505#277505
