### ISSUE TITLE
[Question] Guidance on multithreading for ConfidentialClientApplication

### ISSUE THREAD

**Issue by DOMZE** [AzureAD/microsoft-authentication-library-for-dotnet#2329]
I've been looking to use a ConfidentialClientApplication in my application, but under a multi-threading approach. Looking at the code, I see that ClientCredentialRequest checks (called through the ConfidentialClientExecutor) if the token is in the cache, and if not, requests a new one. TokenCache is responsible to store the acquired token and to remove any overlapping token, keep the last good one.

The problem I see (and I'm looking for a correction if that's the behavior) is that if the cache is empty and multiple threads, say N thread, access MSAL.NET to acquire a token (using AcquireTokenForClient method), those N threads will generate requests to AAD to grab a token, resulting in many outgoing requests which can be costly.

What is your guidance in regards to that, that is so that only 1 thread actually makes the requests, and the others "wait" and then look into the cache before redoing a request if it's a cache miss. I'm thinking here in terms of double locking or something along those lines.

**Comment by pmaytak** [comment]
You are correct in your observation. MSAL doesn't do much locking. So it's possible for multiple threads to get a different view of what's in the internal token cache. The internal token cache is tied to the Confidential Client App object instance. So you could create a separate CCA instance (with its own cache) for each thread. Each thread then only gets tokens for the specific set of resources (and then doesn't need to use the cache of other threads). Another strategy is to recreate CCA instance for something like each web request or session or user. This does mean that once CCA object is disposed off, the internal cache is lost; so you would have to set up an external serialization cache (like Redis). This way when CCA object is recreated, the internal cache can be repopulated with specific related tokens. See [Token cache serialization](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Token-cache-serialization) for more info on that. Also [High Availability](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability) wiki has some related info on this topic as well.

What is your scenario? Is it a web app, service? Do you expect a high number of calls, and are they constant or with spikes at certain times? Doing a top level locking, or having one thread get tokens, or staggering the times when threads need a token could be possible options. I think the best approach can depend on the exact scenario.

Also [Microsoft Identity Web](https://github.com/AzureAD/microsoft-identity-web) might be applicable. It's a library on top of MSAL that helps building web apps and APIs.

**Comment by DOMZE** [comment]
Thank you @pmaytak this enlightens me a lot more. My scenario is that I was looking to possibly reduce the number of HTTP calls to AAD to get a token for the same clientId/tenantId combination. The idea is that I'm doing automation and trying to consume different services in a headless/automated way and using multi-threading to split my processing

**Comment by jmprieur** [comment]
@DOMZE : MSAL.NET will maintain the cache for you and reduce the number of HTTP as much as possible. Just acquire a token and have enabled token cache serialization.
