### ISSUE TITLE
[Bug] MSAL 4.22 introduced UWP breaking change by supporting only UWP 10.0.15063 and higher

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2330]
MSAL 4.21 and lower support all UWP versions, i.e. U

![image](https://user-images.githubusercontent.com/12273384/104305556-b9a73b80-54c4-11eb-9710-c8545ed27727.png)

MSAL 4.22 + supports: 

![image](https://user-images.githubusercontent.com/12273384/104304615-80220080-54c3-11eb-98cf-59bbe89be924.png)

This breaks app using framework version 10.0.10240.0, of which there are many.

**Comment by bgavrilMS** [comment]
My suspicion is that this is caused by .net sdk or msbuild extras.

**Comment by bgavrilMS** [comment]
Not a P1 since versions older than 17096 are out of support. But fix is trivial so we will fix it.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
