### ISSUE TITLE
 Back button functionality is not working in password page.

### ISSUE THREAD

**Issue by shristikatiyar** [AzureAD/microsoft-authentication-library-for-dotnet#2331]
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Which Version of MSAL are you using ?**
4.24

**Platform**
 xamarin android

**What authentication flow has the issue?**
  Mobile Interactive
 

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue

**Expected behavior**
 Back button functionality is not working in password page.

**Actual behavior**
Back button functionality should be working in password page.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. 

https://user-images.githubusercontent.com/72396948/104376811-8cea3700-554b-11eb-822d-db1b6ab7d529.mp4

**Comment by bgavrilMS** [comment]
MSAL does not control the contents of the login browser page. Please follow up with ESTS
