### ISSUE TITLE
[L] Update KeyChain access APIs on extension cache to try to solve Mac access issues.

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2340]
There are problems with the token cache extension on both Windows and Mac, when used via PowerShell / Az CLI
For Mac, we can try to upgrade our access layer to KeyChain to use non-deprecated APIs. 

Luckily our friends in GCM have already done the hard work of exposing those APIs (via pinvoke) - see https://github.com/microsoft/Git-Credential-Manager-Core/tree/master/src/shared/Microsoft.Git.CredentialManager/Interop/MacOS

**Comment by bgavrilMS** [comment]
Not sure this is needed anymore, seems like the issue is fixed for some people, but maybe not all? https://github.com/Azure/azure-powershell/issues/13714

**Comment by jmprieur** [comment]
Affected: PowerShell.
- [ ] replace read/write methods from obsolete APIs to new apple APIs. The Git Credential manager people have provided the high level APIs. But it's not a 1:1 mapping.
- [ ] we need to make sure that using the new API doesn't break the existing cached information.

Big learning curve if someone doesn't know the extension
