### ISSUE TITLE
Add RSA Crypto Provider maps to NetCore and NetStandard Crypto Managers

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2342]
Same issue as in #2189 but the fix (#2276) need to be applied to .NET Core and NetStandard crypto managers.

Apply the fix in the crypto managers classes involved in confidential client apps or consolidate the common part of the code in a different file, somewhere in PlatformsCommon, for example.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/e917c1206b48d63fdc46cd8fe81ee20a9654ac4d/src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreCryptographyManager.cs#L76 (you can also copy the test for this one)

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/e917c1206b48d63fdc46cd8fe81ee20a9654ac4d/src/client/Microsoft.Identity.Client/Platforms/netstandard13/NetStandard13CryptographyManager.cs#L66

**Comment by trwalke** [comment]
fixed in [4.26.0 Release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.26.0)
