### ISSUE TITLE
[Documentation] Update Signed assertion documentation to describe how to implement SN+I authentication

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2350]
### Documentation Related To Component:
[Signed client assertions](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fwiki%2FClient-Assertions%23option-2---creating-a-signed-assertion-manually&data=04%7C01%7CTravis.Walker%40microsoft.com%7C3fcc35d4366e4c036b2608d8b9ae8914%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637463506562539423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LQQrTL%2BBktYo4fWfaUbYpTx5qB446jTr8p9t1UAcqHw%3D&reserved=0)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
This document is missing details on how a customer can implement SN+I when using a signed client assertion. 
This will allow customers to unblock themselves when they want to use both SN+I and signed client assertions.

**Comment by jmprieur** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Assertions#subject-name-issuer-authentication
