### ISSUE TITLE
[Bug] Key not valid for use in specified state.

### ISSUE THREAD

**Issue by RhomGit** [AzureAD/microsoft-authentication-library-for-dotnet#2352]
**Which Version of MSAL are you using ?**
MSAL 4.18.0

**Platform**
WPF
.NET Framework 4.6.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x ] Interactive

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue

**Repro**
I can not replicate this locally.
A repro of the code I use to connect is here: https://github.com/RhomGit/MSALDesktopRepro/blob/0d18219c59011d842f9c0cf8d7650093162a3760/Auth.cs#L86

**Behavior**
I have one of my production users experiencing the above issue and is unable to authenticate using the Public Client Application.
I have no idea what this error message means nor how to begin troubleshooting it.
I read this https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1201 issue however I don't use WithCertificate so doubt that it is the same issue.

If you could please provide some advice to point me in the right direction? Please bear in mind this is a high-valued, remote client in a stressful production setting so I am unable to actively troubleshoot with them.

**Comment by bgavrilMS** [comment]
Hi @RhomGit  - that exception message seems to suggest a problem with a certificate, however you are not using a certificate based auth flow. Could you provide the full stack trace please? 

It may also be helpul to collect logs https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by RhomGit** [comment]
Ok thanks for that @bgavrilMS  
I will add the logging as you suggest and arrange a new production release. 
Once this is rolled out and I have received the log file back from the client I will update this thread. Thanks

**Comment by henrik-me** [comment]
Could this be related to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1872 ? Can you pls. try 4.22 or wait for our 4.25 release coming out later this week?

**Comment by RhomGit** [comment]
I have moved to 4.24 for now. If there is a specific reason for me to hold off until 4.25 please let me know.

**Comment by henrik-me** [comment]
If you have moved to 4.24 you are good. 4.25 will remove one of the dependencies we have introduced, and place it in another package. Did you see a difference using 4.24?

**Comment by RhomGit** [comment]
We did see a difference with 4.24 ... he no longer gets this error and is in!
I have his logs but no need to do anything with them. I am closing this now as whatever was wrong in 4.18 seems to be resolved.

Thanks guys

**Comment by henrik-me** [comment]
Thanks for confirming. We recommend moving to 4.25 if possible.
