### ISSUE TITLE
[Bug] .NET 5.0 WPF The embedded WBE browser still doesn't seem to start!

### ISSUE THREAD

**Issue by SundayRX** [AzureAD/microsoft-authentication-library-for-dotnet#2355]
The Package Version Is 4.25.0
**Platform**
.NET 5.0 WPF Windows10
**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Integrated Windows Auth
Other? - please describe;
An embedded webview is not available on this platform. Please use WithUseEmbeddedWebView(false) or leave the default. See https://aka.ms/msal-net-os-browser for details about the system webview."}

I used the following code to try to obtain authorization through an embedded browser.
This code can pop up the embedded browser dialog box normally on .net framwork 4.X, but it still opens the os browser page on .NET 5.0.
AuthResult = await AccessClient.AcquireTokenInteractive(ApplicationAuthority)
                                                .WithParentActivityOrWindow(new WindowInteropHelper(Parent).Handle)
                                                .WithPrompt(Prompt.SelectAccount)
                                                .WithUseEmbeddedWebView(true)
                                                .ExecuteAsync();
Is there something wrong with my code? Or is there a bug? If there is something wrong with my code, please kindly advise

**Comment by bgavrilMS** [comment]
I think you're ending up targeting the .NET Core 2 version of MSAL.

**Comment by bgavrilMS** [comment]
Ok, I see the problem. By default, a .NET WPF app is using the target `net5-windows` but MSAL is build against `net5-windows10.0.17763.0` ... So the simplest thing to do here is to change your app to use this version 

![image](https://user-images.githubusercontent.com/12273384/105340309-9f144700-5bd5-11eb-9f5b-ca51864e5ac7.png)

This should not have any implications if you are not using any WinRT APIs (i.e. Windows SDK) in your project. Even if you do, I think it should be fine, as Visual Studio will suggest some fixes. 

I'm going to have a conversation with the .NET gurus to see how we can improve the experience here.

**Comment by bgavrilMS** [comment]
Having read more about this, I think Visual Studio editor experience is bad here. It only offers .NET5-windows project framework, but NET5-Windows does not pull in WinRT APIs. MSAL calls some WinRT APIs, so we have to specify a windows SDK version (the minimum possible is 10.0.17763.0).

![image](https://user-images.githubusercontent.com/12273384/105350878-b0645000-5be3-11eb-85bd-92321bcfe811.png)

**Comment by bgavrilMS** [comment]
Word on the street is that Visual Studio will provide a better UI experience in a subsequent update. The fix is to update the csproj file manually.

**Comment by bgavrilMS** [comment]
From MSAL's point of view, we should update the exception message to make it more clear.

**Comment by SundayRX** [comment]
First of all, thank you for your patience！！！！
I tried the method you suggested.It does work!!
I noticed that my output file was a little bit bigger after using WinRT.There are a few more files."WinRT.Host.Shim.dll" "WinRT.Runtime.dll" "Microsoft.Windows.SDK.NET.dll" This brings up a small new problem.
I used the ".NET Reactor" to package and encrypt the application.
Packages can no longer be encrypted as assemblies, although they can be normally packaged as Bundled.
So I have two questions：
1 Will the Visual Studio IDE fix the framework selection issue in the future？
2 Is the inability to encrypt assemblies caused by using WinRT?Of course I will try to discuss this with Eziriz!
Thanks again for your help!!!

**Comment by bgavrilMS** [comment]
Well, VS will make it easier to select win10-windows10.x.y.z platform. But it's just a cosmetic change for changing the csproj file.

I'm afraid I can't help with the sizes of those assemblies or the dependencies, consider opening issues on the .NET team. 

As a (pretty complex) workaround, you could target .NET Core 3.1 and implement your own embedded browser using this extensibility method: https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.extensibility.icustomwebui?view=azure-dotnet

**Comment by bgavrilMS** [comment]
Improved the error message
