### ISSUE TITLE
[Feature Request] Add to telemetry the field for cache_refresh status

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#2356]
As a resiliency request, we need to add a value to telemetry to indicate what caused cache refresh. For this we need to add a field cache_refresh to telemetry which can have following values:
0 - if token request goes to ESTS because no cached AT exists
1 - if token request goes to ESTS becasue cached AT expired 
2 - if token request goes to ESTS because refresh_in was used and the existing token needs to be refreshed
3 - if token request goes to ESTS because force_refresh was set to true
*blank* - if no cache is used

This change will have the schema version for telemetry changed to 3. The current telemetry header will look like 
``` schema_version | api_id, force_refresh, cache_refresh | platform_fields ``` after the modification.

Reference: https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/2506?_a=files&anchor=current-request

**Comment by trwalke** [comment]
fixed in [4.26.0 Release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.26.0)
