### ISSUE TITLE
[Bug] PKAuth does not work when using WithExtraQueryParams

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2359]
**Which Version of MSAL are you using ?**
4.25

**Platform**
net45

It looks like PKauth fails when .WithExtraQueryParams are used. The `SubmitUrl` parameter of PKAuth should be the token endpoint url without any query params.

This impacts Visual Studio as they are sending a bunch of extra query params. 

Fix is trivial - use only token endpoint URL for PKAuth - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/14b03ca8c7534021ac0184e4ca2687ce0ba6665a/src/client/Microsoft.Identity.Client/OAuth2/TokenClient.cs#L174

We should update our integration test with this quirk, now that we have one!

**Comment by bgavrilMS** [comment]
[Microsoft.Identity.Client.4.25.1-internal2.nupkg.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/5858278/Microsoft.Identity.Client.4.25.1-internal2.nupkg.zip)

**Comment by trwalke** [comment]
fixed in [4.26.0 Release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.26.0)
