### ISSUE TITLE
[Bug] [L]  PKeyAuth advertised but not performed on .NET Core and .NET Standard

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2363]
**Which Version of MSAL are you using ?**
4.25

**Platform**
- [ ] netcore
- [ ] net5
- [ ] netstandard (if possible)

**Flow**
all pca

**Impact**
ESTS will generate a challenge to Win7, Win8 etc. systems. Affected apps will always reply "I don't know how to resolve this challenge" even though they should be able to certify that the machine is managed.

**Comment by bgavrilMS** [comment]
If possible to extract the key - do it. If not, stop advertising PKAuth.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.30.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.30.0).
