### ISSUE TITLE
User not able to sign in 

### ISSUE THREAD

**Issue by shristikatiyar** [AzureAD/microsoft-authentication-library-for-dotnet#2369]
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Which Version of MSAL are you using ?**
4.24

**Platform**
Xamrin.Android

**What authentication flow has the issue?**
     Mobile
    * [ ] Interactive
 
Other? - please describe;

**Is this a new or existing app?**
 The app is in production, and I have upgraded to a new version of MSAL

-->

**Expected behavior**
We are getting this error 
Error: AzureAD graph Authentication error: Object reference not set to an instance of an object. Exception : System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.ValidateResponseFromBroker
whereas a more clear error with error code should be returned or it can ba a bug which leading yo this error

**Actual behavior**
Exception Thrown user not able to sign in.

**Possible Solution**
A better error with error code should be thrown or the error should not come.

**Additional context/ Logs / Screenshots**
[O365MobileAppLog - 2021-01-27T165608.211.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/5884952/O365MobileAppLog.-.2021-01-27T165608.211.txt)

**Comment by bgavrilMS** [comment]
Null Reference exception => P1 bug

**Comment by jennyf19** [comment]
@shristikatiyar can you please provide any more of the stack trace, it seems to possibly be something from the app. Are you using a .NET MAM or InTune plug in? 

we need more info in order to investigate.

**Comment by trwalke** [comment]
@shristikatiyar  can you please provide the broker logs?

**Comment by jennyf19** [comment]
@shristikatiyar can you please verify with the customer if the Company Portal is installed on the device? If so, can this be reproduced without it on the device?

**Comment by jennyf19** [comment]
@shristikatiyar any update on this? thank you.

**Comment by bgavrilMS** [comment]
Please reopen with logs if still an issue.
