### ISSUE TITLE
[Bug] PublicClientApplication does not support ROPC for AzureAdB2C because of the requirement to include ClientId as ResourceId in the list of scopes.

### ISSUE THREAD

**Issue by benjaminjnr** [AzureAD/microsoft-authentication-library-for-dotnet#2372]
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Which Version of MSAL are you using ?**
MSAL 4.25.0

**Platform**
netcore

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
This is a new app in development

**Repro**

```csharp
        private async Task<string> GetBearerTokenViaClientApplication(string userName, string userSecret)
        {
            var log = this.Logger;

            var azureAd = this.AppFactory.Services.GetService<IOptions<PublicClientApplicationOptions>>().Value;

			var configuration = this.AppFactory.Services.GetService<IConfiguration>();
			var b2cAuthority = $"{azureAd.Instance}/{azureAd.TenantId}/{configuration.GetValue<string>("AzureAdB2C:SignUpSignInPolicyId")}/";

			log.LogDebug("b2cAuthority - " + b2cAuthority);

			var client =
				PublicClientApplicationBuilder.CreateWithApplicationOptions(azureAd)
                    .WithB2CAuthority(b2cAuthority)
				    .Build();

            var scopes = new[] 
            { 
                "openid", 
                azureAd.ClientId, 
                "offline_access" 
            };
            var request = client.AcquireTokenByUsernamePassword(scopes, userName, userSecret.ConvertToSecureString());

            var result = await request.ExecuteAsync();

			log.LogDebug("Granted scopes - " + result.Scopes.StringConcat(" "));

            log.LogDebug("Access Token - " + result.AccessToken);

            return result.AccessToken;
        }
```

**Expected behavior**
My intention was to use the ROPC flow to obtain an access token from AzureAD B2C to one of my APIs.

**Actual behavior**
The code above throws an exception of: **System.ArgumentException : API does not accept client id as a user-provided scope**.

I traced the issue to the **_ValidateScopeInput_** method in the **_Microsoft.Identity.Client.Internal.Requests.RequestBase_**:
```csharp
        private void ValidateScopeInput(HashSet<string> scopesToValidate)
        {
            if (scopesToValidate.Contains(AuthenticationRequestParameters.ClientId))
            {
                throw new ArgumentException("API does not accept client id as a user-provided scope");
            }
        }
```

**Possible Solution**
The ROPC flow of AzureAD B2C requires the specification of a resource as part of the scope in this instance the ClientId.

I will suggest having a test to see if the request is hitting an AzureAD B2C endpoint or not before this exclusion test is applied

```csharp
        private void ValidateScopeInput(HashSet<string> scopesToValidate)
        {
            if (!<<expression that indicates AzureAD B2C>> &&  scopesToValidate.Contains(AuthenticationRequestParameters.ClientId))
            {
                throw new ArgumentException("API does not accept client id as a user-provided scope");
            }
        }
```

**Additional context/ Logs / Screenshots**
The block of code below works and is included to show the result we are trying to achieve:

```csharp
        private async Task<string> GetBearerTokenViaRest(string userName, string userSecret)
        {
            var azureAd = this.AppFactory.Services.GetService<IOptions<MicrosoftIdentityOptions>>().Value;

            var configuration = this.AppFactory.Services.GetService<IConfiguration>();
            var b2cAuthority = $"{azureAd.Instance}/{azureAd.TenantId}/{configuration.GetValue<string>("AzureAdB2C:SignUpSignInPolicyId")}";

            var log = this.Logger;

            var form = new MultipartFormDataContent
            {
                { new StringContent(azureAd.ClientId), "client_id" },
                { new StringContent("password"), "grant_type" },
                { new StringContent(userName), "username" },
                { new StringContent(userSecret), "password" },
                { new StringContent($"openid {azureAd.ClientId} offline_access"), "scope" },
	            //{ new StringContent(clientSecret), "client_secret" },
            };

            var tokenEndpoint = "v2.0/token";

            //log.LogInformation("form - " + form);

            using (var authClient = new HttpClient())
            {
                var tokenResult = await authClient.PostAsync($"{b2cAuthority}/oauth2/{tokenEndpoint}", form);

                log.LogInformation("Auth token fetch status - " + tokenResult.StatusCode);

                var tokenResultString = await tokenResult.Content.ReadAsStringAsync();

                //log.LogInformation(tokenResultString);

                var accessToken = JObject.Parse(tokenResultString);

                log.LogInformation(accessToken["access_token"].ConvertToString());

                return accessToken["access_token"].ConvertToString();
            }
        }
```

**Comment by jennyf19** [comment]
@benjaminjnr The ClientId should be the ClientId for the web API, or protected resource, not the client. You're trying to get a token with the client as the audience, but you need a token with the web API as the audience. A scope defined as a ClientId will not work anyway it has to be defined by the web API. More information [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview) on protecting a web API.

The [b2c documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-ropc-policy?tabs=app-reg-ga&pivots=b2c-user-flow) is at the protocol level, but MSAL handles a lot of this for you. See our documentation on [ROPC](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#configure-the-ropc-flow-in-azuread-b2c).

Here's an example from one of our tests for [ROPC with B2C](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/b2562d606fcdbb9bdd04d4201992d64b38c0d342/tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/B2CUsernamePasswordIntegrationTests.cs#L20). 

Also, MSAL appends the required scopes (`open_id` `offline_access`) by default, so you just need to include the web API scope.

**Comment by jennyf19** [comment]
You might find this [sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C) helpful.

**Comment by benjaminjnr** [comment]
Thanks @jennyf19. I guess ultimately it came down to my application setup. It seems scopes I define for the application in AzureAD B2C must be part of the permissions granted by Admin to the app in order to be used.

That is what first of all got me running around in circles. I am back where I started as per your advice and it seems to be working fine.

This is just an aside: I do notice something weird. The tokens I generate are accepted by the Microsoft.Identity infrastructure and all is fine. They are decoded properly on jwt.ms and jwt.io but jwt.io complains about Invalid Signature (I wonder why).
