### ISSUE TITLE
[Internal] Improve MSAL PR and CI build pipelines

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2378]
Both MSAL PR and CI build pipelines use template-ci-and-pr.yaml to build and test. Currently all steps in that template are sequential. Improve by separating the tasks into parallel jobs. Investigate if the tasks themselves can be made to run in parallel (like the unit/integration tests, build task). MSAL UI automation build pipeline can be used as an example.

**Comment by gladjohn** [comment]
@pmaytak Is there anything pending on this item? can this be closed?

**Comment by pmaytak** [comment]
Nothing pending, I don't think. Travis did the work some time ago.
