### ISSUE TITLE
[Internal] Improve App Center iOS mobile tests

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2379]
Currently the iOS test step in the MSAL UI Automation build pipeline takes ~18 minutes. Investigate why it takes so long and if there is a way to speed it up. One strategy is, perhaps, to use device sets and/or run in parallel. Similarly investigate Android tests.

**Comment by gladjohn** [comment]
Android test is at 3 mins now. But the last time IOS tests ran was in Sep

![image](https://user-images.githubusercontent.com/90415114/205156874-ffa8b916-05ee-48a2-8c64-96556566b554.png)

@pmaytak  @trwalke  @bgavrilMS @neha-bhargava   @SameerK-MSFT FYI : Do we know why the IOS test is turned off?

**Comment by pmaytak** [comment]
iOS tests were disabled when NET 6 was added [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3605/files#diff-079281cae4bba8321b08ba4c9fd4707530a978b7c0f8ec66ab6072171ce428a7). The XamariniOS tasks uses mono which couldn't build the MSAL project with Net6 in it.
Possble work around may be to add a flag to exclude net6 targets in MSAL, which will only be set by this build task.

**Comment by bgavrilMS** [comment]
Xamarin is on its way out and Maui does not have test support. Generally the mobile E2E tests are pretty low quality - mostly they do not catch bugs.
