### ISSUE TITLE
AcquireTokenAsync changed.  Where do I put the policy?

### ISSUE THREAD

**Issue by PilotC150** [AzureAD/microsoft-authentication-library-for-dotnet#238]
In the old version of this library there were overloads for AcquireTokenAsync that accepted the policy name as a parameter.  Those aren't there anymore.  

Is the policy just supposed to be passed in as an "extraQueryParameter" in the format of "p=<policy name>"?

**Comment by frankchen76** [comment]
It seems like ConfidentialClientApplication.AcquireTokenForClient(string[] scopes, string policy) accepts policy as the second parameter for one of overload methods. Have you checked out that?

**Comment by kpanwar** [comment]
It goes in authority, like https://login.microsoftonline.com/tfp/<tenant>/<policy>

**Comment by kpanwar** [comment]
It does not exist in dev branch. We removed it everywhere. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev/src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs

**Comment by PilotC150** [comment]
I changed the format of the authority to what the library now requires (as you pointed out), but it is still not executing the correct policy.  If I put `p=<policy>` in the `extraQueryParameters` parameter then it works.

Also, and maybe this should be a separate issue/discussion, when I log in (using an external system as defined in my policy), the Chrome browser window tries to redirect to `urn:ietf:wg:oath:2.0:oob?state=<big long token>`.  I'm assuming this is the Auth Token, but I'm not sure.  This is on Android.

**Comment by PilotC150** [comment]
As a follow up, is the redirect issue that I'm seeing at all related to issue #225?

**Comment by kpanwar** [comment]
You cannot use urn:ietf:wg:oath:2.0:oob as a redirect uri. You need to configure custom redirect uri for your application which is not yet supported in the portal, so you are pretty much blocked.

**Comment by thomfromnorth** [comment]
Maybe I misunderstood your comment, kpanwar, but I can configure custom redirect uri (without http or https) in azure portal (new portal, not the classic one),
like com.onmicrosoft.contoso.myapp://oauth/redirect

**Comment by kpanwar** [comment]
can you share your updated authority URL with the proposed format?

**Comment by kpanwar** [comment]
most of the issues discussed here are addressed in various PRs. Closing this one. Please file new issues if needed.

**Comment by danroth27** [comment]
@kpanwar I'm also seeing the behavior described, where the policy is not showing up in the authorize request. 

With MSAL 1.0.304142221-alpha (public on nuget.org) I see this when calling `PublicClientApplication.AcquireTokenAsync` with `authority=https://login.microsoftonline.com/fabrikamb2c.onmicrosoft.com` and `policy=b2c_1_sign_in` (notice the p parameter in the authorize request):

```
GET /fabrikamb2c.onmicrosoft.com/oauth2/v2.0/authorize?
scope=openid+offline_access&
client_id=90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6&
response_type=code&
p=b2c_1_sign_in&
redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&
client-request-id=be5a2e22-937a-4bb3-b1b7-bf9df5e5c509&
x-client-SKU=MSAL.Desktop&
x-client-Ver=1.0.0.0&
x-client-CPU=x64&
x-client-OS=Microsoft+Windows+NT+6.2.9200.0&
prompt=login
```

With MSAL 1.1.0-alpha0250 (on MyGet) I see this when calling `PublicClientApplication.AcquireTokenAsync` with `authority=https://login.microsoftonline.com/tfp/fabrikamb2c.onmicrosoft.com/b2c_1_sign_in` (notice there is no p parameter in the authorize request):
```
GET /fabrikamb2c.onmicrosoft.com/oauth2/v2.0/authorize?
scope=offline_access+openid+profile&
response_type=code&
client_id=90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6&
redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&
client-request-id=12e236a1-c907-4598-9ac5-9644bea4cafc&
x-client-SKU=MSAL.Desktop&
x-client-Ver=1.1.0.0&
x-client-CPU=x64&
x-client-OS=Microsoft+Windows+NT+6.2.9200.0&
prompt=login&
code_challenge=owLzirwTZNQscAPWituOUIimlK5EM5eGJCEdNfAy-Ko&
code_challenge_method=S256&
state=2f14861a-fd1c-4a69-8c61-3f7b9321c11c&
slice=testslice&
uid=true
```

@javiercn @vibronet

**Comment by jhondev** [comment]
Hi, How can I get this work in the version 1.1.0-preview?
