### ISSUE TITLE
[Feature Request] Specify tenant id for application token cache key

### ISSUE THREAD

**Issue by yohanb** [AzureAD/microsoft-authentication-library-for-dotnet#2381]
Looking at the current implementation of the token cache, I noticed when caching app tokens, the key is _clientId_AppTokenCache_.  In a multi-tenant application, this cache key will continuously get overridden for each tenant the token is requested.  Why not specify the tenant ID in the token cache key like so _clientId_tenantId_AppTokenCache_?
Thanks.

**Comment by bgavrilMS** [comment]
On it

**Comment by yohanb** [comment]
@bgavrilMS wasn't expecting that! 😂
let me know how I can help.

**Comment by yohanb** [comment]
took the initiative to create a PR for the requested enhancement.

**Comment by trwalke** [comment]
fixed in [4.26.0 Release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.26.0)
