### ISSUE TITLE
[Bug] Android - System Browser (Chrome) Opens instead of Chrome Tab on 4.24.0 and up

### ISSUE THREAD

**Issue by Strifex** [AzureAD/microsoft-authentication-library-for-dotnet#2382]
**Logs and Network traces**
N/A - just run this library on Android Emulator will duplicate this issue every time - no chrome tab is used and instead the browser itself is opened which doesn't appear to be correct and is a change in behavior since 4.23.0.

**Which Version of MSAL are you using ?**
4.23.0 - Works Correctly - Login flow appears as chrome tab
4.24.0 - Incorrect - Opens new Chrome Browser
4.25.0 - Incorrect - Opens new Chrome Browser

**Platform**
Xamarin.Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

**Is this a new or existing app?**
This is a new app I've tested with - but I've also replicated the behavior in the sample apps by upgrading/downgrading the version of the library used.

**Expected behavior**
The expectation is that when you utilize MSAL to login to AzureAD - that a chrome "tab" appears to display the web UI for the login flow.  This is denoated by an android toolbar with an X button in the top-left corner, etc. etc.

**Actual behavior**
On the latest versions of the library - the chrome "tab" doesn't appear - instead the entire chrome browser opens the login flow UI in a new tab inside the chrome application instead of the calling application.  Its cosmetically jarring and also will leave the login page open in the chrome browser in the backstack after completing the flow.

**Comment by juanmalm** [comment]
Having same issue. After updating to version >= 4.24.0 the entire chrome browser opens. This breaks the UI flow if you press the Android back button after signing with MSAL. Also it lets open a tab on chrome browser for each time you call the AcquireTokenInteractive.

**Comment by bgavrilMS** [comment]
Won't fix.
