### ISSUE TITLE
[Feature Request] Implement android broker handshake caching to improve performance.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2390]
**Is your feature request related to a problem? Please describe.**
Some users experience a long delay during broker operations due to the handshake operation taking .5 secs at times. This handshake is performed on every request made to the broker.

**Describe the solution you'd like**
Implement Handshake caching for the android broker to improve performance

**Additional context**
Example: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1108

**Comment by bgavrilMS** [comment]
Not a goal right now.

**Comment by bgavrilMS** [comment]
Rejected. Any new work on Android broker will build on a native building block that abstracts this.
