### ISSUE TITLE
[Bug] MSAL token can't be recognized in Azure DevOps

### ISSUE THREAD

**Issue by Wuhao1627003** [AzureAD/microsoft-authentication-library-for-dotnet#2394]
**Which Version of MSAL are you using ?**
MSAL.NET 4.25.0

**Platform**
net5.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;
IConfidentialClientApplication (Azure App)

**Is this a new or existing app?**
new experiment app

**Repro**

```csharp
string azureDevOpsResourceId = "499b84ac-1321-427f-aa17-267ca6975798/.default";
IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(appId).WithClientSecret(appSecret).WithAuthority(authorityUrl).Build();
                    var token = app.AcquireTokenForClient(new string[] { $"{azureDevOpsResourceId}/.default" });
                    Microsoft.Identity.Client.AuthenticationResult res = await token.ExecuteAsync();

                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", res.AccessToken);
```

**Expected behavior**
HttpResponseMessage returns success status code

**Actual behavior**
{"$id":"1","innerException":null,"message":"TF400813: The user '' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}

**Additional context/ Logs / Screenshots**
App has the permission to access Azure DevOps:
![image](https://user-images.githubusercontent.com/25204397/107138501-bb431280-694f-11eb-9f3a-d7bd7b86a0d1.png)

Note: My purpose is to use non-interactive (+no device code), non-PAT auth to access Azure DevOps, and it seemed to me that MSAL is the only solution here. Any other recommendations are welcome.

**Comment by jmprieur** [comment]
@Wuhao1627003 : you need to use the scope that was registered: `https://app.vssps.visualstudio.com/user_impersonation`, not `499b84ac-1321-427f-aa17-267ca6975798/.default`

BTW, in your code, you have .default twice (as `azureDevOpsResourceId` already contains `./default` (it shouldn't), and you also add it in `AcquireTokenForClient`

**Comment by Wuhao1627003** [comment]
Thanks, I changed to 
```csharp
var token = app.AcquireTokenForClient(new string[] { "https://app.vssps.visualstudio.com/user_impersonation" });
```

MSAL.NetCore.4.25.0.0.MsalServiceException:
        ErrorCode: invalid_scope
Microsoft.Identity.Client.MsalServiceException: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://app.vssps.visualstudio.com/user_impersonation is not valid.

**Comment by jmprieur** [comment]
Interesting, @Wuhao1627003 !
The doc is inacurate then. Could you please try: "https://app.vssps.visualstudio.com/.default"

**Comment by Wuhao1627003** [comment]
That gives back my previous error {"$id":"1","innerException":null,"message":"TF400813: The user '' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}

**Comment by jmprieur** [comment]
We've taken this offline
The tenant admins have disables the possibility for users to consent (this is a 3P app). I've provided @Wuhao1627003 with the procedure to have the app pre-authorized.
