### ISSUE TITLE
[Query] How to use AcquireTokenForClient for kusto database

### ISSUE THREAD

**Issue by sanjaydebnath** [AzureAD/microsoft-authentication-library-for-dotnet#2395]
Hi guys, we are using IConfidentialClientApplication to generate token against our AAD app. We use the Cert Issuer + Subject Name as the authentication mode. E.g. to generate token for graph calls, below is the code.

```csharp
// aadOptions variable contains details about tenant, app id etc.
// cert has the pfx
var confidentialClient = ConfidentialClientApplicationBuilder.Create(aadOptions.ClientId)
                .WithAuthority(new Uri(new Uri(aadOptions.Instance), $"{aadOptions.TenantId}/v2.0"))
                .WithCertificate(cert)
                .Build();
var result = await confidentialClient.AcquireTokenForClient(new[] { 
"https://graph.microsoft.com/.default" }).WithSendX5C(true).ExecuteAsync().ConfigureAwait(false);
```
This works fine. But Now we want to use the same mechanism while connecting to kusto clusters. The app id is already added with proper roles in the corresponding kusto database. But not able to figure out what should be the **scope** while generating the token for the cluster 'https://xyz.westus2.kusto.windows.net' which has a DB called 'abc'. 

```csharp
// aadOptions variable contains details about tenant, app id etc.
// cert has the pfx
var confidentialClient = ConfidentialClientApplicationBuilder.Create(aadOptions.ClientId)
                .WithAuthority(new Uri(new Uri(aadOptions.Instance), $"{aadOptions.TenantId}/v2.0"))
                .WithCertificate(cert)
                .Build();
var result = await confidentialClient.AcquireTokenForClient(new[] { 
"<<what should go here??>>" }).WithSendX5C(true).ExecuteAsync().ConfigureAwait(false);

var kustoClientBuilder = new KustoConnectionStringBuilder("https://xyz.westus2.kusto.windows.net")
            {
                FederatedSecurity = true,
                ApplicationToken = result.AccessToken,
                Authority = this.aadOptions.ClientId,
            };

```

Any help appreciated.

**Comment by sanjaydebnath** [comment]
Figured it out, the kusto builder itself provides option in easier way (section "Using X.509 certificate" in below link). Thanks, closing this.

https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto#aad-based-authentication-examples

**Comment by bgavrilMS** [comment]
Thanks for following up with the solution!
