### ISSUE TITLE
[Feature Request] Add ability to set window title of embedded auth prompt

### ISSUE THREAD

**Issue by mjcheetham** [AzureAD/microsoft-authentication-library-for-dotnet#2397]
**Is your feature request related to a problem? Please describe.**
Currently authentication prompts using the embedded webview have no context associated with them. You can have several prompts at the same time from different MSAL-using apps and not know which is which.

**Describe the solution you'd like**
Add a new method the ATI builder that allows you to set the window title of the WinForms embedded webview, for example:

```csharp
IPublicClientApplication app = appBuilder.Build();
await app.AcquireTokenInteractive(scopes)
  .WithUseEmbeddedWebView(true)
  .WithWindowTitle("Authenticating for Widgets: https://example.com")
  .ExecuteAsync();
```

**Describe alternatives you've considered**
Include this as an overload on an existing method?

```csharp
IPublicClientApplication app = appBuilder.Build();
await app.AcquireTokenInteractive(scopes)
  .WithUseEmbeddedWebView(true, "Authenticating for Widgets: https://example.com")
  .ExecuteAsync();
```

**Additional context**
You can already do `.WithParentActivityOrWindow()` and pass a pointer/window handle for GUI apps, but what about background app services/apps with no foreground window, or console apps?

**Comment by bgavrilMS** [comment]
@jmprieur for API surface. We have smth similar for system webview
