### ISSUE TITLE
[Bug] [S] Android - Method not found: System.Threading.Tasks.Task Microsoft.Identity.Client.SystemWebViewOptions.OpenWithEdgeBrowserAsync(System.Uri)

### ISSUE THREAD

**Issue by SergioZgz** [AzureAD/microsoft-authentication-library-for-dotnet#2399]
**Logs and Network traces**
Logs... I cannot log anything from MSAL just:
MSAL Info False (False) MSAL 4.25.0.0 MSAL.Xamarin.Android 29 [02/09/2021 14:56:33] Found 0 cache accounts and 0 broker accounts

Because when try to call the method that contais next code... all method fails 
```
authResult = await PCA.AcquireTokenInteractive(new string[] { BrandSettings.MSAL_SCOPE })
                                .WithSystemWebViewOptions(new SystemWebViewOptions { OpenBrowserAsync = SystemWebViewOptions.OpenWithEdgeBrowserAsync })
                                .ExecuteAsync();
```
            

**Which Version of MSAL are you using ?**
MSAL 4.25.0.0 (latest version available for Android / iOS)

**Platform**
My app is Xamarin Classic (NOT Forms) with MvvmCross.
App fail on iOS and Android (on iOS the error is related to JIT on AOT) and on Android the error is this: "Method not found: System.Threading.Tasks.Task Microsoft.Identity.Client.SystemWebViewOptions.OpenWithEdgeBrowserAsync(System.Uri)"

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

**Is this a new or existing app?**
b. The app is in production, I tried with our previous version of MSAL 4.22 and with latest 4.25 everything works fine but some customers need use EDGE for security policies with Intune.

**Repro**
This works fine (with embedded webview or external):
```
authResult = await PCA.AcquireTokenInteractive(new string[] { BrandSettings.MSAL_SCOPE })
                                .WithUseEmbeddedWebView(useEmbeddedWebView)
                                .WithParentActivityOrWindow(parent)
                                .ExecuteAsync();
```
But if we try to force EDGE, on simulator or real device, with or without EDGE installed doesnt work (This is the code that fails):
```
authResult = await PCA.AcquireTokenInteractive(new string[] { BrandSettings.MSAL_SCOPE })
                                .WithSystemWebViewOptions(new SystemWebViewOptions { OpenBrowserAsync = SystemWebViewOptions.OpenWithEdgeBrowserAsync })
                                .ExecuteAsync();
```
            
I also tried to change OpethWithEdgeBrowserAsync by OpenWithChromeEdgeBrowserAsync and fails too.

**Expected behavior**
OpenWithChromeEdgeBrowserAsync should open EDGE browser to authentication

**Actual behavior**
The method which contains the option OpenWithChromeEdgeBrowserAsync or OpenWithEdgeBrowserAsync fails when call with error "Method not found: System.Threading.Tasks.Task Microsoft.Identity.Client.SystemWebViewOptions.OpenWithEdgeBrowserAsync(System.Uri)"

Thanks for your time :)

**Comment by bgavrilMS** [comment]
Thanks for the bug @SergioZgz . We don't support any kind of system browser customization on mobile. Those options are only for desktop apps (.NET classic or .NET core). 

We need to remove this API from the Xamarin surface and throw a good exception if API is called from Xamarin via NetStandard.

Did you need any customization of the webview? We recommend you use a broker (e.g. Authenticator) anyway :)

**Comment by SergioZgz** [comment]
Ok Thank you so much

We will talk with our customers about the authenticator, I think that is better option too :)
