### ISSUE TITLE
[Bug] Region is prepended to an already regionalized authority when using regional

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2400]
**Which Version of MSAL are you using?**
4.25.0

**Platform**
NET Core 3.1

**What authentication flow has the issue?**
CCA.AcquireTokenForClient (but probably all)

**Repro / Actual behavior**
- Use [regional test app](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/tests/devapps/RegionalTestApp/Program.cs).
- Make sure verbose logging is enabled on line 98 `.WithLogging(Log, LogLevel.Verbose, true)`.
- Make sure both `AcquireTokenAsync` calls use regional.
![image](https://user-images.githubusercontent.com/34331512/107436841-f1fd6200-6ae2-11eb-9126-35133f68ab5f.png)
- In the logs for both calls (after auto-detection fails), you'll see that region is appended twice to the host in some instances.
![image](https://user-images.githubusercontent.com/34331512/107449347-43fcb280-6af8-11eb-8be5-a879da0ac56f.png)
![image](https://user-images.githubusercontent.com/34331512/107449468-74445100-6af8-11eb-8d21-d542bfca1f02.png)

**Expected behavior**
Any regionalized URL should only have one region in it.
![image](https://user-images.githubusercontent.com/34331512/107437930-97fd9c00-6ae4-11eb-901c-77f9453a7a32.png)
![image](https://user-images.githubusercontent.com/34331512/107437844-72709280-6ae4-11eb-88ce-8d35f2cacd4b.png)

**Additional context / Logs / Screenshots**
In `BuildAuthorityWithRegionAsync` method there's [code at the end that transforms the passed-in URL by adding a region](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/018c34ef0efbd7902aa71a1370609998911c345d/src/client/Microsoft.Identity.Client/Region/RegionDiscoveryProvider.cs#L263). During the first call, the known authority is correctly transformed into a regionalized authority. However, during the second call, a region is prepended to an already regionalized authority. Result - this adds an extra item into the instance discovery cache; this always ends up calling the `TryGetMetadataAsync` an extra time; and the token cache uses regionalized host instead of a known host in the token cache item key.
![image](https://user-images.githubusercontent.com/34331512/107114140-8bddba00-6818-11eb-89e0-868534b76dc3.png)
![image](https://user-images.githubusercontent.com/34331512/107114142-8f714100-6818-11eb-9fe8-1597608067ec.png)

**Comment by trwalke** [comment]
fixed in [4.26.0 Release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.26.0)
