### ISSUE TITLE
Instance metadata cache miss for every acquire token call when using regional

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2401]
**Which Version of MSAL are you using ?**
4.25.0

**Platform**
NET Core 3.1

**What authentication flow has the issue?**
CCA.AcquireTokenForClient (but probably all)

**Repro / Actual behavior**
- Use [regional test app](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/tests/devapps/RegionalTestApp/Program.cs).
- Make sure verbose logging is enabled on line 98 `.WithLogging(Log, LogLevel.Verbose, true)`.
- Make sure both `AcquireTokenAsync` calls use regional.
![image](https://user-images.githubusercontent.com/34331512/107436841-f1fd6200-6ae2-11eb-9126-35133f68ab5f.png)
- In the logs for each call (in the beginning of the call), you'll see that we always try to get network cache provider for a known authority (login.microsoftonline.com), even though we enabled regionalization.
![image](https://user-images.githubusercontent.com/34331512/107451312-deaac080-6afb-11eb-835c-5b6d9733e94e.png)

**Expected behavior**
If regionalization is enabled for a call, we should check the metadata cache only for regionalized authority.

**Possible Solution**
Perhaps the check for enabled regionalization needs to be done earlier in the code flow, before we check the cache for known metadata providers. So if regionalization is enabled, we regionalize the authority and check the cache with that URL. If it's disabled, we check the cache for known authority.

**Additional context / Logs / Screenshots**
[When an `InstanceDiscoveryMetadataEntry` is created](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/018c34ef0efbd7902aa71a1370609998911c345d/src/client/Microsoft.Identity.Client/Region/RegionDiscoveryProvider.cs#L195), the original known authority host entry is not cached. Result - Every time there's a request for a token, a known authority is passed in, checked against the cache, not found, goes through regionalization code, then the regionalized authority is correctly checked against the cache.

**Comment by henrik-me** [comment]
@pmaytak : Would be great to understand the perf impact this has. I would like to see some numbers. Given for regional we construct the metadata if I recall correctly then perhaps the cost is not an outbound call? Otherwise this is a network call which seems to be very expensive. Putting on the board to complete this investigation and clarification asap.

**Comment by pmaytak** [comment]
@henrik-me Yea, as far as I see, there are no extra network calls. Extra call is to the metadata cache.

**Comment by henrik-me** [comment]
Please help confirm to ensure we are able to correctly prioritize this work. thanks.
