### ISSUE TITLE
[S] MSAL random error in Microsoft.Identity.Client.Platforms.net45.Http.DnsSensitiveClientHandler

### ISSUE THREAD

**Issue by Zoe-ms** [AzureAD/microsoft-authentication-library-for-dotnet#2402]
MSAL version: 4.21.1
.Net version: net 45
How often:  latest data: 32 occurrences in 8900k 
call stack: 
An error occurred while sending the request.,   stacktrace:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Platforms.net45.Http.DnsSensitiveClientHandler.<SendAsync>d__2.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Http.HttpManager.<ExecuteAsync>d__10.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Http.HttpManager.<ExecuteWithRetryAsync>d__8.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Http.HttpManager.<SendGetAsync>d__5.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__11`1.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.OAuth2.OAuth2Client.<DiscoverAadInstanceAsync>d__9.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.<SendInstanceDiscoveryRequestAsync>d__8.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.<FetchAllDiscoveryMetadataAsync>d__7.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.<GetMetadataAsync>d__5.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.<FetchNetworkMetadataOrFallbackAsync>d__11.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.<GetMetadataEntryAsync>d__10.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.TokenCache.<Microsoft-Identity-Client-ITokenCacheInternal-SaveTokenResponseAsync>d__58.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Cache.CacheSessionManager.<SaveTokenResponseAsync>d__7.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Internal.Requests.RequestBase.<CacheTokenResponseAndCreateAuthenticationResultAsync>d__17.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<FetchNewAccessTokenAsync>d__3.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<ExecuteAsync>d__2.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__14.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at   Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.<ExecuteAsync>d__3.MoveNext()   --- End of stack trace from previous location where   exception was thrown ---      at   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()      at   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task)      at Microsoft.DataTransfer.MsiServiceClient.AadUtil.<AcquireTokenWithMASLAsync>d__1.MoveNext()
--

**Comment by bgavrilMS** [comment]
Thanks Zoe, do you have the error message as well? You only pasted the stack trace.

**Comment by Zoe-ms** [comment]
Hi @bgavrilMS, unfortunately that is all I got. The error message may be just "An error occurred while sending the request."

**Comment by bgavrilMS** [comment]
Looks like our custom HttpClient factory for .NET classic is having some problems on .net45, we should investigate if we can improve this.

**Comment by bgavrilMS** [comment]
Workaround: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-provide-httpclient

**Comment by Zoe-ms** [comment]
Thanks, Bogdan. 
1, Will this further be improved in MSAL? Or we can only rely on workaround?
2. About workaround, how we should customize the HttpClient? Just new a default instance like below? Thanks. 
    public class ClientFactory : IMsalHttpClientFactory
    {
        public HttpClient GetHttpClient()
        {
            return new HttpClient();
        }
    }

**Comment by bgavrilMS** [comment]
As per Microsoft guidelines:

`HttpClient is intended to be instantiated once and re-used throughout the life of an application. Especially in server applications, creating a new HttpClient instance for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors.`

So you could use a static HttpClient or you can recycle the HttpClient every 60 min or so, to avoid any issues with DNS, see https://github.com/dotnet/runtime/issues/18348#issuecomment-347361456

**Comment by bgavrilMS** [comment]
MSAL should provide a solution like https://github.com/dotnet/runtime/issues/18348#issuecomment-347361456 in the box.

**Comment by Zoe-ms** [comment]
Thanks, will take a look. So MSAL will fix this in 4.32 as well? Is there an ETA for 4.32?

**Comment by bgavrilMS** [comment]
I'm not sure we can take this for 4.32 .. I propose you fix it in your codebase first, and if it's all good we will take the fix in MSAL as well.

**Comment by bgavrilMS** [comment]
NET 45 goes out of support in a few months, and given our backlog, and the fact that there is a workaround, it's unlikely that we can find time to fix this. 

If you have another implementation of HttpClient that works better, please share it us and we could consume it.

**Comment by Zoe-ms** [comment]
Thanks for the update. Given that we will move to net 472 shortly, unlikely we will implement the workaround as well. Thanks.
