### ISSUE TITLE
Support for dynamic client registration?

### ISSUE THREAD

**Issue by bmildh** [AzureAD/microsoft-authentication-library-for-dotnet#2404]
Hello!

In all examples and documentation that I'm reading about MSAL, they all require you to statically register a client id. That is, in Azure AD, you need to pre-configure (out-of-band) your application. This is all fine for many scenarios. But is it not possible to to dynamic (oauth) client registration with MSAL (Azure AD, Graph)?

(I'm just starting to learn about OAuth and MSAL so I might just have missed something obvious. )

(edit: how do you apply labels to posts? like "question" label)

**Comment by jmprieur** [comment]
@bmildh:
you can use the Microsoft Graph API to do an app registration
See for instance https://github.com/jmprieur/app-provisonning-tool, and in particular 
https://github.com/jmprieur/app-provisonning-tool/blob/main/src/DotnetTool/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs

What is your scenario? is it a devops context?

To apply labels, you can use the Labels category on the side of the issue
![image](https://user-images.githubusercontent.com/13203188/107500277-46154e80-6b96-11eb-90bf-3140f06c8f4b.png)

**Comment by bmildh** [comment]
@jmprieur I was just thinking in general terms, no specific scenario. After a brief reading about OAuth, I was under the impression that OAuth2 gave us a means of delegating authorization in such a way that we do not need to pre-configure a clientid/secret on the authrorization server for each client instance. It seems a more flexible way of doing things instead of statically pre-configure a clientid/secret and copying that to the client. On the other hand, It might be more secure, locked-down, by doing statically pre-configure. 

Anyhoo. I'm just dipping my toes in the MSAL/OAuth world for the first time and will need to study more. 

I will check out your links, thank you.

**Comment by jmprieur** [comment]
@bmildh : indeed, the client (and its client credentials for the confidential client applications = web apps, web apis, daemon apps) needs to be known from the identity provider (establishing the trust relationship).
See https://www.youtube.com/watch?v=HEpq_YSmuWw
