### ISSUE TITLE
[Documentation] Token Caching and resiliency

### ISSUE THREAD

**Issue by poyadav2001** [AzureAD/microsoft-authentication-library-for-dotnet#2405]
### Documentation Related To Component:

Token Caching and resiliency
### Please check those that apply

- [ ] typo
- [* ] documentation doesn't exist
- [* ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

When using the MSAL library for Aad auth, it is clear the library has it own caching. But it is unclear when is the token refreshed by MSAL. Is it refreshed shortly before it is about to expire or more frequently?
It is a recommended practice that if the token will expire in 24 hours, force refresh the token every 12 hours so that in case of an Aad outage, we are guaranteed a downtime of 12 hours.
Is this something that the callers of the library have to handle or is this scenario already implemented in MSAL?
Looking at the codebase, we see properties RefreshOn and ExtendedExpiresOn, besides ExpiresOn, but these are properties of the token returned from Aad and documentation is not provided. A token is refreshed when the RefreshOn time is reached, but what is this timestamp?
I have found conflicting documentation at different places and I feel that the documentation under the wiki section does not clarify the issue
Token resiliency is an important factor and I feel this part needs clear and more elaborate documentation

**Comment by bgavrilMS** [comment]
@neha-bhargava - could you take this one please? I assume the question is mainly focused on service 2 service scenarios, although MSAL treats the user scenarios fairly similar.

**Comment by poyadav2001** [comment]
Any updates

**Comment by bgavrilMS** [comment]
Hi @poyadav2001 , apologies it must have fallen on @neha-bhargava 's radar.

I updated our "High Availability" wiki page with details about `refresh_in`, please have a look and let me know any follow-up questions.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability#pro-active-token-renewal

**Comment by poyadav2001** [comment]
Thank you for answering my doubts and updating the documentation
