### ISSUE TITLE
[L][Feature Request] Update cache_refresh telemetry field to log additional values

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#2406]
**Currently**, we are logging the following for the cache_refresh telemetry field:
0 if token request goes to ESTS because no cached AT exists, 
1 if token request goes to ESTS becasue cached AT expired, 
2 if token request goes to ESTS because refresh_in was used and the existing token needs to be refreshed, 
3 if token request goes to ESTS because force_refresh was set to true, 
blank if the cache is not hit to make the request

There is ask from ESTS team who is going to consume this field to not log blank and instead have a value since *blank* can be thought of as logged due to an error. Also, they get this value from non msals too and blank there means either they don't have telemetry or did not implement refresh_in

**To do:**
- Combine `force_refresh` and `cache_refresh` fields into `cache_info`.
- Update `cache_info` with the values:
  - 0 if cache is not hit to make the request (interactive call, username password call, device code flow, etc.)
  - 1 if token request goes to ESTS because force_refresh was set to true
  - 2 if token request goes to ESTS because no cached AT exists
  - 3 if token request goes to ESTS becasue cached AT expired
  - 4 if token request goes to ESTS because refresh_in was used and the existing token needs to be refreshed
  - 5 is reserved for Non MSAL customers by ESTS as they receive this telemetry from non MSAL producers too and this indicates no caching is done (No op for MSAL)

**Comment by bgavrilMS** [comment]
@neha-bhargava - if this is something doable in 2 days, consider focusing on it. The analyzer task seems larger.

**Comment by neha-bhargava** [comment]
@bgavrilMS There is another change proposed by Ray in the PR: https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/2805
He is suggesting to remove the force_refresh flag altogether. We should get that clarified before making that change.
