### ISSUE TITLE
[Feature Request] Investigate if SaveToken can be optimized

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2410]
Saving tokens is a very expensive operation - see numbers: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2309
This is causing services who cache all tokens in memory to slow down due to high CPU usage.

**Comment by henrik-me** [comment]
Related:
https://github.com/AzureAD/microsoft-identity-web/issues/961
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1770

**Comment by bgavrilMS** [comment]
This has been addressed by partitioned caches.
