### ISSUE TITLE
Refreshing token using client application ID URI

### ISSUE THREAD

**Issue by usdruscia** [AzureAD/microsoft-authentication-library-for-dotnet#2411]
**Which Version of MSAL are you using ?**
MSAL.NET 4.25.0

**Platform**
.NET Framework 4.5

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

**Is this a new or existing app?**
This is a new app or experiment

**Repro**

```csharp
// PublicClientApplication instantiation
var builder = PublicClientApplicationBuilder
                .Create("https://my.app") // I would like to use the URI instead of the ID
                .WithAuthority(AzureCloudInstance.AzurePublic, tenantId)
                .WithDefaultRedirectUri();

m_PublicClientApplication = builder.Build();

// Token acquisition
var accounts = await m_PublicClientApplication.GetAccountsAsync();
var result = await m_PublicClientApplication.AcquireTokenSilent("https://my.api/user_impersonation", accounts.FirstOrDefault()).ExecuteAsync();
```

**Expected behavior**
Get a refreshed access_token when it expires (which works if I use the `app ID` instead of the `app ID URI`)

**Actual behavior**
MsalUiRequiredException - AADSTS70000: Provided grant is invalid or malformed

**Comment by bgavrilMS** [comment]
Apologies, I accidentally disabled the nice exception that you normally get when you try to use a client_id that is not a GUID. It says: 

```xml
 <para>What happens?</para>You've specified a client ID that is not a <see cref="Guid"/>
 <para>Mitigation</para>Use the application ID (a GUID) from the application portal as client ID in this SDK
```

Will get this validation back in with the next MSAL release. 
You can use the non-guid form of the tenant ID by the way, e.g. `contoso.onmicrosoft.com`

**Comment by usdruscia** [comment]
Will the URI form will work at some point for the client ID?

**Comment by bgavrilMS** [comment]
Not that I'm aware of. May I ask what you are trying to do that you need the URI instead of the GUID?

**Comment by jmprieur** [comment]
@usdruscia. This is not going to happen and here is why:
1. App ID URIs are only needed for protected web APIs. They form the base of the scopes. See https://docs.microsoft.com/azure/active-directory/develop/scenario-protected-web-api-app-registration#application-id-uri-and-scopes. Applications in general, unless they are web APIs (or Azure functions, gRPC services which are like web APIs) do not expose an App ID URI.
2. MSAL.NET, on the other hand is used by client applications which want to acquire a token to call protected web APIs. This means it can be used for web APIs that call downstream web APIs, but it can also be used by all the other type of applications that call protected web APIs (Mobile apps, desktop apps, web apps, ...). And those applications in general don't have an app ID URI.
3. What all applications have, however, is a ClientID from the moment they are registered with Azure AD / Azure AD B2C.
4. And therefore, MSAL.NET uses the ClientID to identify the application that acquires the token (the client application)

**Comment by jmprieur** [comment]
@bgavrilMS : I see your point for the supportability labels given the re-enabled error message. But I suggest we raise a different issue for that one (as the initial issue is just a question, or a by design)

**Comment by usdruscia** [comment]
@bgavrilMS I'm working on a single-tenant solution where customers will deploy/install an API and other backend services in their own Azure subscription. This process will also take care of the AAD app registrations w/ URIs. The API will be consumed by different clients, including a windows desktop app, which needs to acquire a token to call the protected endpoints.

To ease the configuration of the desktop app, I would have liked to provide as many MSAL default values as possible, which means to rely on known URIs instead of "auto-generated" IDs for both the client ID and the scopes.
