### ISSUE TITLE
[Bug] MSAL.Desktop.4.25.0.0.MsalClientException: ErrorCode: authentication_canceled even though it was not canceled

### ISSUE THREAD

**Issue by seanLCS** [AzureAD/microsoft-authentication-library-for-dotnet#2413]
When I call:  authResult = await app.AcquireTokenInteractive(scopes)
                        .WithAccount(accounts.FirstOrDefault())
                        .WithPrompt(Prompt.SelectAccount)
                        .ExecuteAsync();
I get a user canceled error. I see the login window popup for a split second and then close immediately. This was all working prior to the latest automatic windows update. I'm not sure but it looks like update KB4601315 caused the issue. I tried updating Windows 10 to version 20H2 and the problem still exists. This is occurring on multiple computers, with different versions but all of them have the KB4601315 update. I tried turning off popup blocker and tried using a different browser. This is being called from a WPF .NET 4.7.2 desktop application.

**Logs and Network traces**
"   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.VerifyAuthorizationResult(AuthorizationResult authorizationResult, String originalState)\r\n   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceInternalAsync>d__6.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceVerifierAsync>d__4.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__8.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__13.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Structural3D.Structural4DUI.<Authorized>d__70.MoveNext() in C:\\[location]\\Structural4DUI.xaml.cs:line 481"

**Which Version of MSAL are you using ?**
Microsoft.Identity.Client v4.25.0

**Platform**
net4.7.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
This is a new app

**Repro**

```csharp
var authResult = await app.AcquireTokenInteractive(scopes)
                        .WithAccount(accounts.FirstOrDefault())
                        .WithPrompt(Prompt.SelectAccount)
                        .ExecuteAsync();
```

**Expected behavior**
Prior to the update, a login window appeared asking the user to select the correct account, or if done so already, a silent token was acquired.

**Actual behavior**
The error above is called

**Possible Solution**
This post.

**Additional context/ Logs / Screenshots**

**Comment by bgavrilMS** [comment]
I can't seem to reproduce this issue. I tried to install that update but Windows refuses to. 

One thing you can try is to use the system browser instead, i.e. the app will force Chrome or Edge or whatever browser you have by default to perform the log-in. 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/System-Browser-on-.Net-Core#system-browser-experience

**Comment by seanLCS** [comment]
Thanks for the reply. I tried what it says to do in the link you provided. The behavior is very strange. I added ".WithRedirectUri("http://localhost")" to the client application builder. When I ran the program the login window opened like normal and allowed me to select an account. I selected the account but of course I hadn't added that redirect uri to Azure AD yet so there was an error. I went to AD and added the redirect uri. When I ran the program again the exact same issue occurred; the login pops up for a second and then goes away and I get a user canceled error. I had read in another forum that it is better to use secure servers, so I tried changing it to "https" and that didn't change anything. Now no matter what I do, the original error is still there. If I delete the redirect or include it. Seems like it was a one shot thing but I can't understand why.

**Comment by bgavrilMS** [comment]
This is strange behaviour. First, let me say "http://localhost" is in no way dangerous for a WPF app (i.e. public client app). The mechanism for the browser to talk back to MSAL are sockets, i.e. MSAL will start listening to "http://localhost:1234" and your browser should eventually be redirected to "http://localhost:1234?code=auth_code". 

The fact that both embedded web browser (which is a very old version of IE) and system browser result in the same behavior suggest there is something wrong in the HTTP communication between the browser and AAD, maybe a proxy shuts down the connection or smth. 

Would it be possible to get some verbose logs please? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging . If you think they contain too much personal info, feel free to email them to bogavril (at microsoft.com)

It may also help to capture a network trace using Fiddler to investigate what's happening.

**Comment by seanLCS** [comment]
I can get you some verbose logs if you want, but I just found some more interesting behavior. When I tried it just now, it worked the first time again, but not subsequent tries. So I actually disabled the automatic login that occurs when the program runs (which is called from a window loaded event function). When I do this and allow the program to start, then manually login, the login works without issue, over and over. So it is seeming more and more like it is an issue with my program however I know this was not an issue before the Windows update. I then tried putting the thread to sleep for 1 second before automatically calling the login function, that did not work. When I changed it to 10 seconds, that did work. So It seems like I need to delay the call until the application is fully loaded. I did this in the past, I just need to look up the code to do it. I don't quite understand how an update can cause this behavior though, however that update did make changes to logon behavior.

**Comment by seanLCS** [comment]
Never mind, putting the thread to sleep only worked the first time also. It's not working now. I'll work on getting you the verbose logs.

**Comment by bgavrilMS** [comment]
You can always try that `await AcquireTokenInteractive` call in a console app... or in a vanilla WPF app.;

**Comment by bgavrilMS** [comment]
Can't repro. Please try WAM https:\\aka.ms\msal-net-wam
