### ISSUE TITLE
[Bug] MSAL calls into login.microsoftonline.com even when Authority Url is set to a different url

### ISSUE THREAD

**Issue by anhtuan1412** [AzureAD/microsoft-authentication-library-for-dotnet#2421]
In Power BI Destkop app, we use .NET MSAL to authenticate with AAD. We're running into an issue in an air-gapped environment. Power BI Desktop get access token in the following way

 var clientApp = PublicClientApplicationBuilder
	.Create(clusterInfo.Cloud.AppConfiguration.AppId)
	.WithAuthority(authorityUrl)
	.WithRedirectUri(clusterInfo.Cloud.AppConfiguration.RedirectUri)
	.WithLogging(MsalLoggerCallback.Log, MinimumMsalLogLevel, enablePiiLogging: false)
	.Build();
var result = await clientApp.AcquireTokenInteractive(scopes)
	.WithLoginHint(userEmail)
	.WithClaims(claims)
	.WithExtraQueryParameters(adalOrganizationAccountFlag)
	.ExecuteAsync();

In the air-gapped environment, Power BI Desktop sets the **authorityUrl** to a custom allowed URL. However, in the traces logged by MSAL we see the following line

DataMashup.Trace Information: 24579 : {"Start":"2021-02-18T00:42:24.5821899Z","Action":"PBI.MsalLog","Message":"Info: (False) MSAL 4.18.0.0 MSAL.Desktop Microsoft Windows NT 10.0.19042.0 [02/18/2021 00:42:24 - 21c05947-4389-496d-9af0-886b52988497] **Fetching instance discovery from the network from host login.microsoftonline.com"**,"ProductVersion":"2.88.1682.0 (20.12)","ActivityId":"00000000-0000-0000-0000-000000000000","Process":"PBIDesktop","Pid":21524,"Tid":1,"Duration":"00:00:00.0000181"}

I've tested the same code in other environments (with different authorityUrl) but I've never seen this trace. I'm wondering why this trace and why MSAL calls into login.microsoftonline.com when a different authorityUrl is set?

**Comment by bgavrilMS** [comment]
This is expected. Unless you call a well-known public cloud, MSAL will attempt to contact `login.microsoftonlie.com` to try to find out:
- if that authority has any aliases 
- optionally to validate the authority 

If the environment is air-gapped and the call fails, I expect MSAL to be able to continue. MSAL will no make that call again unless the process is restarted. 

Is this causing any problems for you? Please contact me directly to discuss in more detail, my alias is bogavril
