### ISSUE TITLE
Get bearer token with MSAL.NET to access App Service with EasyAuth

### ISSUE THREAD

**Issue by aelghoneimy** [AzureAD/microsoft-authentication-library-for-dotnet#2425]
I have an Azure App Service which is authenticated using Azure AD EasyAuth.
[![Configured AppService with AD][1]][1]

I am trying to send a request from another App Service using C# and MSAL.NET (Microsoft.Identity.Client).

The authentication code looks like this

```csharp
var app = ConfidentialClientApplicationBuilder
    .Create(config.ClientId) // The Client ID in the App Registration connected to the App Service
    .WithClientSecret(config.ClientSecret)
    .WithAuthority(new Uri(config.Authority)) // https://login.microsoftonline.com/tenant.onmicrosoft.com/v2.0
    .WithTenantId(config.TenantId) // Tenant Id Guid
    .Build();

// Used Scopes: ["https://graph.microsoft.com/.default"]
var credentials = await app.AcquireTokenForClient(config.Scopes)
    .ExecuteAsync(cancellationToken);
```

I get a bearer token successfully, but when I try to call the App Service with the token injected to the headers I get a 401 and `You do not have permission to view this directory or page.` 

Can you help please as I am trying to migrate from ADAL to MSAL. Before with ADAL I used to get the correct token with the Authentication Context and ResourceId.

  [1]: https://i.stack.imgur.com/rYDZe.png

**Comment by jmprieur** [comment]
@aelghoneimy 
If you are using ASP.NET Core, please look at Microsoft.Identity.Web.

If you use EasyAuth, you probably get a token for the user. Here you want to get a token on behalf of your app. Did you pre-authorize your app to call Microsoft.Graph

**Comment by aelghoneimy** [comment]
Thanks @jmprieur for replying back.

I have the current permissions applied

![image](https://user-images.githubusercontent.com/4632474/108880887-a2e32100-75fa-11eb-93df-ea5a6f1d4866.png)

I am authenticating using a backend ui-less service. I used to grab a token from AD using ADAL and then send a request with the Authorization header applied.

**Comment by aelghoneimy** [comment]
I solved the issue by updating two things:

1. The requested scopes when calling `AcquireTokenForClient` should include `{Application ID Uri}/.default`
2. In EasyAuth configuration, the `Allowed Token Audiences` needs to be set to the `Application ID Uri` as well

![image](https://user-images.githubusercontent.com/4632474/109246401-2018bc80-77da-11eb-810e-0324abb56d5f.png)

**Comment by jmprieur** [comment]
Thanks for the update @aelghoneimy
