### ISSUE TITLE
AADSTS50013: Assertion failed signature validation [Bug] 

### ISSUE THREAD

**Issue by SirElTomato** [AzureAD/microsoft-authentication-library-for-dotnet#2426]
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.25.0

**Platform**
React native and .Net Framework 4.7.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [x] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
This is when adding msal to an existing app. Msal is not in production on the app currently. 

**Repro**

```csharp
        public async Task<AuthenticationResult> AquireTokenOnBehalfOf(IEnumerable<string> scopes, string jwt)
        {
            var userAssertion = new UserAssertion(jwt);

            var res = await ConfidentialClientApplication.AcquireTokenOnBehalfOf(scopes, userAssertion).ExecuteAsync();

            return res;
        }
```

**Expected behavior**
I am using [this package](https://github.com/stashenergy/react-native-msal) to authenticate the user from the react native mobile app. After acquiring the token I am sending it to my .net WebAPI which tries to call ConfidentialClientApplication.AcquireTokenOnBehalfOf. 
Both the react native mobile app and the webapi are using the same client id from the azure app registration and scopes. 

I expect AuthenticationResult will be returned by the ConfidentialClientApplication.AcquireTokenOnBehalfOf method.

**Actual behavior**
Microsoft.Identity.Client.MsalUiRequiredException: 'AADSTS50013: Assertion failed signature validation. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: '9CEA37643ACE0D710AD63296857B251D1FCA5C48', Found key 'Start=12/21/2020 20:50:17, End=12/20/2025 20:50:17']
Trace ID: a03a5cf8-8d05-4bd2-a47a-ce3a1ce70e00
Correlation ID: 8b42b1c2-21bc-4d63-9b90-bafb81f83d32
Timestamp: 2021-02-23 14:13:26Z'

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots.

**Comment by jmprieur** [comment]
@SirElTomato : is the certificate used to create the app the same as the one registered in Azure AD for the app?

**Comment by SirElTomato** [comment]
@jmprieur I'm not using a certificate but a client secret. The react native package creates a PublicClientApplication and so doesn't allow you to specify the client secret. The secret used to create the confidential app on the api is the same as the one in Azure AD.

**Comment by SirElTomato** [comment]
I have Azure AD app setup as per [this](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/3.-Web-api-call-Microsoft-graph-for-personal-accounts). I am not using the JWT bearer middleware though, but just receiving the access token from the client and using it create a UserAssertion and call ConfidentialClientApplication.AcquireTokenOnBehalfOf

**Comment by SirElTomato** [comment]
I got this working by carefully following the example [here](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/3.-Web-api-call-Microsoft-graph-for-personal-accounts). I hadn't configured what was required in the "Expose an API" blade of the app registration.
