### ISSUE TITLE
[Bug] MSAL returns warning "org.freedesktop.DBus.Error.ServiceUnknown" when dbus-user-session package is installed 

### ISSUE THREAD

**Issue by erich-wang** [AzureAD/microsoft-authentication-library-for-dotnet#2431]
Copy the issue from: https://github.com/Azure/azure-powershell/issues/14207

**Description**

After installing `dbus-user-session` package on Ubuntu 18.04 ,  `Import-Module Az.Accounts` has returned `** Message: 17:43:58.624: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files` which has broken our CI due to writing to the stderr.
This issue doesn't reproduce on Ubuntu 20.04 where the `dbus-user-session` package is pre-installed by default or using sudo.

**Which Version of MSAL are you using ?**

**Platform**

Ubuntu 20.04

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**

**Repro**

```csharp
$ pwsh -command "Import-Module Az.Accounts"
** Message: 17:43:58.624: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
** Message: 17:43:58.630: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
** Message: 17:43:58.633: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files 

```

**Comment by bgavrilMS** [comment]
I don't think this is an extension problem, and will continue to provide help on the original issue.
