### ISSUE TITLE
[Bug] System.InvalidOperationException - Sequence contains more than one element when doing GetAccountAsync

### ISSUE THREAD

**Issue by bemartin** [AzureAD/microsoft-authentication-library-for-dotnet#2434]
**Logs and Network traces**
Authenticator Logs: 7QH2DKBB

**Which Version of MSAL are you using ?**
MSAL 4.26.0 and MSAL 4.27.0

**Platform**
xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Repro**

```csharp
return await ClientApplication
    .GetAccountAsync(accountIdentifier)
    .ConfigureAwait(false);
```

**Expected behavior**
It should return an account matching the identifier

**Actual behavior**
Throws System.InvalidOperationException - Sequence contains more than one element

StackTrace
```
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0007b] in <60a2fa4733f64e27a9f0ca9c8a951bd0>:0 
  at Microsoft.Identity.Client.ClientApplicationBase.GetAccountAsync (System.String accountId) [0x0007e] in 
```

**Possible Solution**
If it is possible for multiple accounts to be found for a single account identifier, then it should not be doing SingleOrDefault.
If it should not be possible, then there is some bug in Authenticator and a more specific exception should be thrown from MSAL to explain why the account could not be retrieved

**Comment by jmprieur** [comment]
@trwalke could you please have a look at this issue?
Thanks!

**Comment by trwalke** [comment]
There are some cases where I have seen more than one account return in the broker response itself. It may be what is happening here.
