### ISSUE TITLE
Xamarin.Forms Microsoft Identity AAD login not showing UPN hint with WithLoginHint in iOS[Bug] 

### ISSUE THREAD

**Issue by helishah-baliosoft** [AzureAD/microsoft-authentication-library-for-dotnet#2436]
I am working in Xamarin.Forms app and we have implemented Microsoft Identity AAD login in Xamarin.Forms.

Now we are using WithLoginHint to show the UPN login hint in login page as defined below.

```acquireTokenInteractiveParameterBuilder = acquireTokenInteractiveParameterBuilder.WithParentActivityOrWindow(parentUIWindow).WithLoginHint(UPN);```

Above is working fine in Android. It is showing UPN hint while sign in but in iOS it is not showing UPN hint which I am passing to WithLoginHint.

Showing in Android.
![image](https://user-images.githubusercontent.com/79844467/109492113-7a529f80-7ab0-11eb-8de9-ac4ad9bf4806.png)

Not showing in iOS (iPhone 12 iOS 14.4).
![image](https://user-images.githubusercontent.com/79844467/109492195-96eed780-7ab0-11eb-9358-5619783000d1.png)

Can you please check?
Thanks.

**Comment by jmprieur** [comment]
@trwalke @jennyf19 @bgavrilMS : do you have any idea?

**Comment by jennyf19** [comment]
@helishah-baliosoft What value are you using for `Prompt`? According to our iOS team, `Prompt.SelectAccount` will only work with `login_hint` if there is a matching session cookie. Can you try not including any prompt or doing `Prompt.None` + `.WithLoginHint(string hint)` and see if that resolves it?

**Comment by helishah-baliosoft** [comment]
@jennyf19 I am not using any Prompt. Below is my code snippet
```
AuthenticationResult authResult = null;
try
            {
                var accounts = await PCA.GetAccountsAsync();

                authResult = await PCA
                    .AcquireTokenSilent(scopes, accounts.FirstOrDefault())
                    .ExecuteAsync();

            }
            catch (MsalUiRequiredException)
            {
                // This exception is thrown when an interactive sign-in is required.                                
                // Prompt the user to sign-in
                var interactiveRequest = PCA.AcquireTokenInteractive(scopes);

                if (AuthUIParent != null)
                {
                    if (!string.IsNullOrEmpty(UPN))
                    {
                        interactiveRequest = interactiveRequest
                            .WithParentActivityOrWindow(AuthUIParent)                            
                            .WithLoginHint(UPN);
                    }
                    else
                    {
                        interactiveRequest = interactiveRequest
                            .WithParentActivityOrWindow(AuthUIParent);
                    }
                }

                authResult = await interactiveRequest.ExecuteAsync();
            }
            catch (Exception ex)
            {      throw ex;                
            }
            ```
            
            How to do Prompt.None here?

**Comment by jennyf19** [comment]
@helishah-baliosoft 

```csharp
interactiveRequest = interactiveRequest
                            .WithParentActivityOrWindow(AuthUIParent)  
                            .WithPrompt(Prompt.NoPrompt)                          
                            .WithLoginHint(UPN);
```

**Comment by helishah-baliosoft** [comment]
@jennyf19 I tried this but still it is showing me same as above screenshot in iPhone. Thanks.

**Comment by bgavrilMS** [comment]
Won't fix.
