### ISSUE TITLE
[Bug] MSAL / Xamarin / Android AADSTS700038

### ISSUE THREAD

**Issue by negberts** [AzureAD/microsoft-authentication-library-for-dotnet#2450]
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

MSAL 4.25.0.0 MSAL.Xamarin.Android 29 [02/23/2021 19:01:09] error: unauthorized_client errorDescription AADSTS700038: 00000000-0000-0000-0000-000000000000 is not a valid application identifier. Trace ID: 6cb7c3e0-2836-49ca-a9d0-50115cb20800 Correlation ID: 2be6254e-463f-4582-a050-ac02c040e572 Timestamp: 2021-02-23 19:01:09Z

Microsoft.Identity.Client.MsalServiceException , ErrorCode: unauthorized_client HTTP StatusCode 0 CorrelationId 71eba2fa-a991-4e40-8ffa-2b3d00016cb3 at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.ValidateResponseFromBroker (Microsoft.Identity.Client.OAuth2.MsalTokenResponse msalTokenResponse) [0x0008d] in <785f60953c63468c8b9683b727fb495f>:0 at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.FetchTokensAsync (System.Threading.CancellationToken cancellationToken) [0x000ef] in <785f60953c63468c8b9683b727fb495f>:0 at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.FetchTokensFromBrokerAsync (System.String brokerInstallUrl, System.Threading.CancellationToken cancellationToken) [0x000c0] in <785f60953c63468c8b9683b727fb495f>:0 at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync (System.Threading.CancellationToken cancellationToken) [0x000b7] in <785f60953c63468c8b9683b727fb495f>:0 at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x000fa] in <785f60953c63468c8b9683b727fb495f>:0 at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x000fb] in <785f60953c63468c8b9683b727fb495f>:0

**Which Version of MSAL are you using ?**
MSAL 4.25

**Platform**
Xamarin Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL

**Repro**
User is trying to login on Android device. Instead of getting to Microsoft Authenticator the error is thrown

**Expected behavior**
Microsoft authenticator should be opened.

**Actual behavior**
The exception is thrown above. Microsoft Authenticator is not shown. 

I cannot find anything on error AADSTS700038 on Google.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots.

**Comment by jmprieur** [comment]
@negberts:
- are you sure your client ID is not set to 00000000-0000-0000-0000-000000000000  ? this is what the logs are saying.
- are you using the broker (`.WithBroker(true)`) ?

**Comment by negberts** [comment]
@jmprieur I really love my customers who claim they have used it before, but instead never configured Azure AD at all.. Thank you!
