### ISSUE TITLE
OBO flow not working for Personal Microsoft accounts [Bug] 

### ISSUE THREAD

**Issue by SirElTomato** [AzureAD/microsoft-authentication-library-for-dotnet#2451]
Logs and Network traces
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

Which Version of MSAL are you using ?
Microsoft.Identity.Client 4.25.0

Platform
.Net Framework 4.7.2

What authentication flow has the issue?

Desktop / Mobile
Interactive
Integrated Windows Auth
Username Password
Device code flow (browserless)
Web App
Authorization code
OBO
Daemon App
Service to Service calls
Other? - please describe;

This is when adding msal to an existing app. Msal is not in production on the app currently.

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
An authentication result is returned when calling ConfidentialClientApplication.AcquireTokenOnBehalfOf(scopes, userAssertion).ExecuteAsync() with a JWT from a personal Microsoft Account

**Actual behavior**
When calling ConfidentialClientApplication.AcquireTokenOnBehalfOf(scopes, userAssertion).ExecuteAsync(), I get the below error:

```
Microsoft.Identity.Client.MsalUiRequiredException: 'AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
```

Exactly the same code and flow is working when logging in with an organisation account. 

Flow is as follows:
User signs in on mobile app and gives permissions
Mobile app sends jwt to webapi 
webapi calls ConfidentialClientApplication.AcquireTokenOnBehalfOf to cache the tokens using CosmosCache 

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots.

**Comment by jmprieur** [comment]
@SirElTomato 
- what authority do you use? I imagine "common" ?
- what scope did you request from your web API? Would that be a graph scope that is available only for AAD accounts, and not for MSA accounts? 

And also:
- are you on ASP.NET Core ? or .NET FW? Is it an option for you to use Microsoft.Identity.Web ?, which solves a lot of issue for you.

**Comment by SirElTomato** [comment]
- what authority do you use? I imagine "common" ?
  - yes, common
- what scope did you request from your web API? Would that be a graph scope that is available only for AAD accounts, and not for MSA accounts?
  - Mail.Read, offline_access, openid and User.Read. Are any of these not supported by MSA accounts? 
  
And also:

- are you on ASP.NET Core ? or .NET FW? Is it an option for you to use Microsoft.Identity.Web ?, which solves a lot of issue for you.
  - on .Net Framework 4.7.2 unfortunately. Am I able to use Microsoft.Identity.Web with this instead?

**Comment by jmprieur** [comment]
@SirElTomato : 
- Is the MSA user presented a consent screen allowing for the web API to access their email?
- Did you see this tutorial: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph
- and in particular this chapter: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/3.-Web-api-call-Microsoft-graph-for-personal-accounts

**Comment by SirElTomato** [comment]
@jmprieur 
I have this working now. I think there was a scope mismatch where I wasn't setting user.read scope on the extra scopes to consent from the app. I just removed user.read scope from my api and it works.

I think it was working for AAD accounts due to the consent already having been granted for user.read.

Thanks.
