### ISSUE TITLE
[Feature Request] Add private security nupkg analyzer to build pipeline

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2452]
- [x] Discuss solutions with 1es team
- [ ] Consume package from build and fail build if rule is broken
- [ ] Investigate a way to not break non-MSFT contributors from building MSAL.

Continuation of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2419

**Comment by bgavrilMS** [comment]
Decided to wait for team to make analyzer public
