### ISSUE TITLE
[Bug] Claims Challenges in WAM integration

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2454]
When MSAL receives an error from WAM, it does not extract the claims and MSAL cannot throw a meaningful exception with claims back to the user.

**Comment by jmprieur** [comment]
@bgavrilMS : do we agree this is a bug?

**Comment by bgavrilMS** [comment]
Yes, but is it really P1?

**Comment by bgavrilMS** [comment]
Confirmed that claims from ESTS are only for OBO flow.
