### ISSUE TITLE
[Bug] Release version crash on Surface Pro X (ARM64) (4.23.0.0)

### ISSUE THREAD

**Issue by nowheremanmail** [AzureAD/microsoft-authentication-library-for-dotnet#2456]
**Logs and Network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Which Version of MSAL are you using ?**

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

Other? - please describe;
Just try 
https://github.com/microsoftgraph/msgraph-training-uwp/tree/main/demo/GraphTutorial on a ARM64 device Release version

**Repro**
Just click on Signin, application crash.

**Expected behavior**
Open a popup asking to authenticate

**Actual behavior**
Just make application crash

**Comment by jmprieur** [comment]
@bgavrilMS : would it be a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2187 ?

**Comment by nowheremanmail** [comment]
It's true it's same problem ...
Sorry I didn't see

**Comment by jmprieur** [comment]
No worriesn @nowheremanmail. It's hard to see with so many issues :) 
Thanks for the update!
