### ISSUE TITLE
[Bug] After upgrade to dotnet472, our end to end test got **System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.472**

### ISSUE THREAD

**Issue by zihzhan-msft** [AzureAD/microsoft-authentication-library-for-dotnet#2457]
without other dependencies changes.
**Logs and Network traces**
https://microsoft-my.sharepoint-df.com/:t:/p/zihzhan/EWksabzwQrpDg8xJ2c6lDcgBB4NTnSzNAGSodsv7VCmv_A?e=svdIU6

**Which Version of MSAL are you using ?**
    <PackageReference Include="Microsoft.CodeCoverage" Version="15.9.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="5.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.2" />
    <PackageReference Include="Microsoft.ServiceFabric" Version="6.3.187" />
    <PackageReference Include="Microsoft.Skype.Bots.Media.Library" Version="1.18.0.5" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.4.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.4.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
    <PackageReference Include="System.Management.Automation" Version="10.0.10586.122" />

**Platform**
net472

**What authentication flow has the issue?**
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
Test pass

**Actual behavior**
Auth provider issue

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots.

**Comment by jmprieur** [comment]
@bgavrilMS : do you have an idea?

**Comment by bgavrilMS** [comment]
You are using a very old version of MSAL (4.0.0). Please try with latest version. It uses more modern crypto available in .NET

**Comment by pmaytak** [comment]
Closing this; please re-open if the issue still persists with the newer MSAL versions.
