### ISSUE TITLE
[M] CCA cache - Log error when cache is not serialized

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2461]
For confidential client apps, log error when cache is not serialized.

**Comment by jmprieur** [comment]
@pmaytak, , 
- we should log an error (but not throw)
- the error message should be: `The default token cache provided by MSAL is not designed to be performant when used in confidential client applications. Please use token cache serialization. See https://aka.ms/msal-net-cca-token-cache-serialization.`

**Comment by BobBonser** [comment]
I am getting this error in my log even though I do have AddInMemoryCaches in my startup

            var initialScopes = Configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');

            services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAd")
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                    .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                    .AddInMemoryTokenCaches();

**Comment by pmaytak** [comment]
Thanks @BobBonser, Is this the same issue as https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2990?

**Comment by jmprieur** [comment]
Which version of Id.Web do you use. @BobBonser ?

**Comment by BobBonser** [comment]
It does appear to be the same issue.

**Comment by BobBonser** [comment]
Not sure what I'd.Web means.

**Comment by bgavrilMS** [comment]
@BobBonser - Microsoft.Identity.Web ... But let's continue the conversation of #2990, as this issue is closed.
