### ISSUE TITLE
[Feature Request] [L] MSAL.NET supports Prompt.Create so that customers can implement self-service sign-up

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#2463]
**Is your feature request related to a problem? Please describe.**
When developers want to implement self-service sign up for their apps, they can use a `prompt=create`, triggered by a "Sign-up" link in their app. The end user can then enter the 'create account' experience.

**Describe the solution you'd like**
MSAL.NET should propose a new property named `Create` in the `Prompt` class. When using this property, MSAL.NET would send 'prompt=create' to the authorize endpoint, which will trigger the sign-up experience.

**Additional context**

Example URL:
https://login.microsoftonline.com/d014fd44-d398-4813-a3a9-8cd725f7f356/oauth2/authorize?
client_id=da53de5a-636b-425f-ad57-0f62d6f974c7
&response_type=id_token
&resource=da53de5a-636b-425f-ad57-0f62d6f974c7
&scope=openid
&nonce=default_nonce
&redirect_uri=https://jwt.ms
&prompt=create

![image](https://user-images.githubusercontent.com/13203188/110445289-3f5af800-80be-11eb-9a77-4afe34e834b5.png) 

The draft OIDC spec for this is here: https://openid.net/specs/openid-connect-prompt-create-1_0.html

**Work to do**
- [x] Expose a new Create property in `Prompt`.
- [x] Wire-up the prompt so that 'prompt=create' is sent to the authorize endpoint when this prompt is used.
- [x] Update the [wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withprompt), or better redirect it to the docs.ms page, which would, however need to be synced
 Update after release
- [ ] Update the docs.ms [AcquireToken desktop scenario page](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet#withprompt).
[MS Docs PR](https://github.com/MicrosoftDocs/azure-docs/pull/72667) Merge after release
- [x] Update Microsoft.Identity.Web documentation to explain how to trigger a sign-up experience
 Updated: [Web Apps / Enabling sign-up experience](https://github.com/AzureAD/microsoft-identity-web/wiki/Web-Apps#enabling-sign-up-experience)

Out of scope for this work item:
- Update the [desktop sample](https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2) to showcase this new prompt.
- Update the [Xamarin sample](https://github.com/azure-samples/active-directory-xamarin-native-v2) to showcase this new prompt 
- Update the [desktop tutorial](https://github.com/azure-samples/ms-identity-dotnet-desktop-tutorial) to showcase this new prompt

**Comment by jmprieur** [comment]
@bgavrilMS this is something we [committed to](https://dev.azure.com/IdentityDivision/Engineering/_workitems/edit/1233369) for Q3. I'd suggest we take it for next sprint / the release after next

cc: @henrik-me

**Comment by bgavrilMS** [comment]
Not applicable to WAM

**Comment by bgavrilMS** [comment]
@jmprieur - this prompt works for the application you provided in the example, but not for others. This will be confusing to people. Is there a config in the app registration that must be performed?

**Comment by jmprieur** [comment]
@bgavrilMS 
yes there is an app registration that needs to be performed, @bgavrilMS: this is for external identities:https://docs.microsoft.com/en-us/azure/active-directory/external-identities/self-service-sign-up-user-flow

**Comment by jmprieur** [comment]
We probably don't want to update the samples ...?

**Comment by pmaytak** [comment]
@jmprieur 
For Identity Web, I updated [Web Apps / Enabling sign-up experience](https://github.com/AzureAD/microsoft-identity-web/wiki/Web-Apps#enabling-sign-up-experience) wiki. Would it be useful to add that `SignUp` action to Identity.Web.UI AccountController?

**Comment by jmprieur** [comment]
@pmaytak : I don't think so ... this is only for external identities ...
