### ISSUE TITLE
Enable MSAL.NET to not request default scopes (was "We do not want AcquireTokenByAuthorizationCode() to return an idToken")

### ISSUE THREAD

**Issue by phwang0** [AzureAD/microsoft-authentication-library-for-dotnet#2465]
**Is your feature request related to a problem? Please describe.**
When using the confidentialClientApp's AcquireTokenByAuthorizationCode method, we do not want to generate an idToken.  We want to override the default scopes passed in, where we only pass in scope "offline_access".  The result should not contain an idToken.

Reason for this is because idToken requires additional permissions that customers need to grant us.  Since we do not consume idToken, it is not necessary for customers to give us permissions to retrieve idTokens on their behalf.

We want to specify the scopes we pass in in the AcquireTokenByAuthorizationCode method.  We only pass in offline_access scope, but upon inspecting headers in request sent by MSAL library, it contains openid scope.  We do not want MSAL library to send openid scope.

OAuth2 token request: { %%pii_removed%%}; client_id=b52893c8-bc2e-47fc-918b-77022b299bbc&client_info=1&client_assertion_type=urn%3aietf%3aparams%3aoauth%3aclient-assertion-type%3ajwt-bearer&client_assertion=xxxxxx&scope=offline_access+**openid**+profile&grant_type=authorization_code&code=xxxxxx&redirect_uri=https%3a%2f%2fpreview.powerbi.com%2fviews%2foauthredirect.html&api-version=2.0&cxh_inclusive=False&x-client-Ver=4.18.0.0&x-client-SKU=MSAL.Desktop&x-client-OS=Microsoft+Windows+NT+6.2.9200.0

 

Our code:

 

            this.app = ConfidentialClientApplicationBuilder

                .Create(clientId)

                .WithAuthority(authorityUrl)

                .WithCertificate(cert)

                .WithRedirectUri(redirectUrl)

                .WithHttpClientFactory(httpClientFactory)

                .Build();

 

                        var result = await this.app.AcquireTokenByAuthorizationCode(new string[] { "offline_access" }, authorizationCode)

                            .WithSendX5C(true)

                            .ExecuteAsync();

Error customer receives
Failed to update data source credentials: AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance. Trace ID: b516cac1-ce56-46a5-9bb9-8ecf2e0e5500 Correlation ID: 3f65a203-1783-45e2-a6d6-22651e94bdfd Timestamp: 2020-12-03 22:55:09ZHide detailsActivity ID:dc81ffa4-0abd-47ac-b7fa-2531c6fc62bfRequest ID:8972a115-189a-94a8-0edd-cec9d3d0336aStatus code:400Time:Thu Dec 03 2020 16:55:09 GMT-0600 (Central Standard Time)Service version:13.0.14788.65Client version:2011.3.03863-trainCluster URI:https://wabi-us-north-central-redirect.analysis.windows.net/

**Describe the solution you'd like**
We want to be able to pass in "offline_access" scope only in AcquireTokenByAuthorizationCode method.  MSAL library should then not send openid scope to the service, and service should not return idToken.

**Describe alternatives you've considered**
An alternative would to make our "data refresh app" a standalone app, so customers can choose it in app picker and give that app permissions to retrieve idToken.  But "data refresh app" is hidden within our larger "powerbi app", and customers should not have visibility on that.

**Additional context**

**Comment by phwang0** [comment]
it is ASP.NET.  We do not use the MSAL cache, but we cache the access and refresh tokens  on our side.  We reuse these tokens.  For example if our cache still contains access token, we use it.  If it expires, we use refresh token to get another access token.  If refresh token has expired, then we ask user to reauthenticate.

**Comment by jmprieur** [comment]
Then you probably don't need MSAL at all? ASP.NET can give you one token and a refresh token. If you do all the rest yourself?
not however, that MSAL brings added value that you'd have to add to your solution. Any reason when you don't use MSAL for everything (cc: @henrik-me )

**Comment by jmprieur** [comment]
@henrik-me, I agree.
For the public API, I would suggest, on the application builder, and the Abstract token acquisition builder:

```CSharp
// Allows you to specify the default scopes sent by MSAL.NET. By default MSAL sends, 
// when relevant for the flow, the following scopes: openid profile offline_access.
// Unless you have good reasons to do this, we recommend you don't remove default scopes
// as this will lead to reduce of functionality of MSAL.NET. For instance:
// - if you remove offline_access, the access token you will acquire won't be refreshable when
//   it expires
// - if you remove openid, the access token you will acquire won't be cached in most flows
//   (except AcquireTokenOnBehalfOf and AcquireTokenForClient)
.WithOverrideDefaultScopes(params string[] defaultScopes)
```

We need indeed to investigate what is the impact of missing default scopes, and make sure that MSAL still works in a degraded mode when they are not passed-in, possibly loging a warning for full awareness.

Seems an XXL work item to me.

**Comment by bgavrilMS** [comment]
My investigation so far into this. I am not able to not request "open_id"...

# No OpenId

![image](https://user-images.githubusercontent.com/12273384/113194553-2bd42480-9259-11eb-9b23-5819c070ad48.png)

# No Profile

Id Token missing all profile info, including UPN and client_info

	- GetAccounts return the account with Username set to "Missing from the token response"
	- To save stuff in the cache, we need the HomeAccountId, but we are missing the OID! We can use SUB instead of OID (this is what we do on ADFS. Is this ok?). 
	- The trick above needs to be made to be able to perform ATS
	
If you request profile afterwards, you'll have 2 account objects for the same account, one with OID and UPN and one with SUB and no UPN. But it works.

# No offline_access

GetAccounts() returns nothing, because we only care about, basically no way to get to the cache.
client_creds and OBO should still work from cache.

**Comment by bgavrilMS** [comment]
Since the main scenario of "no openid" cannot be performed, and the experience of "no offline_access" is very poor, I propose No Fix.

**Comment by bgavrilMS** [comment]
See branch bogavril/2465 for prototype.

**Comment by jmprieur** [comment]
Thanks @bgavrilMS 
I was wondering:
- If we would only add this feature to confidential client applications as this is where they were required (or alternatively net45, netcore if there is a need for desktop app). In other words, not apply this to mobile, where the experience would probably not make sense.
- if we wouldn't want to check that the scopes passed WithOverrideDefaultScopes are only among idtoken, profile, offline_access, and that profile is not specified without idtoken?

**Comment by bgavrilMS** [comment]
- Use an "advanced" namespace and an obsolete attribute
- Consider not even storing tokens in the cache in this circumstance, except for OBO.

**Comment by rayluo** [comment]
Out of curiosity, can we know for sure which scope caused that "AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance" error? Was it caused by the `openid` scope, or by the `offline_access` scope instead, (or by some other scope, for that matter)? Or is it equally possible that, depends on the Conditional Access policy, any scope could trigger such an error? I'm trying to understand how flexible MSAL would need to be. (The other case I encountered, the customer is aiming to remove `offline_access`, but `openid` is fine to them.)

Also, from a different perspective, some MSALs also perform an OIDC Discovery with AAD. Such behavior already implies the AAD is an OpenID provider, which it is. Then, it feels weird to send a request without `openid` scope to an OpenID provider, because [`openid` scope is required per OIDC specs](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest):

> scope
>    REQUIRED. OpenID Connect requests MUST contain the openid scope value. If the openid scope value is not present, the behavior is entirely unspecified.
