### ISSUE TITLE
[Bug] WAM - if authority ends in /organizations, logging in interactively with a login hint fails

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2476]
MSAL 4.27

**Repro Steps**

1.	Set the authority to https://login.microsoftonline.com/organizations
2.	Sign-In Interactively with an AAD user that has an account in the OS (for example, via login hint). The sign in must be interactive (i.e. force auth or the user has sign-in frequency CA, or consent is required etc.)

**Actual**: 

![image](https://user-images.githubusercontent.com/12273384/111176208-0977b100-85a1-11eb-81e4-ce2814f805ce.png)

Note: using /common works

**Logs**

--> ORG (FAILS)

 === WebTokenRequest ===
PromptType: ForceAuthentication
webTokenRequest.Property: authority: https://login.microsoftonline.com/organizations/
WebAccountProvider: 
=== WebAccountProvider ===
Authority organizations
DisplayName Work or school account
Id https://login.microsoft.com

UserName subzero@bogavrilltd.onmicrosoft.com
webAccount.Property: UPN: subzero@bogavrilltd.onmicrosoft.com
webAccount.Property: TenantId: 49f548d0-12b7-4169-a390-bb5304d24462
webAccount.Property: UserName: subzero@bogavrilltd.onmicrosoft.com
WebAccountProvider: 
=== WebAccountProvider ===
Authority organizations
DisplayName Work or school account
Id https://login.microsoft.com

--> COMMON (WORKS)

=== WebTokenRequest ===
PromptType: ForceAuthentication
webTokenRequest.Property: authority: https://login.microsoftonline.com/common/
WebAccountProvider: 

=== WebAccountProvider ===
Authority common
DisplayName Work or school account
Id https://login.microsoft.com

== WAM ACCOUNT == 
webAccount.Property: UPN: subzero@bogavrilltd.onmicrosoft.com
webAccount.Property: Authority: https://login.microsoftonline.com/common
WebAccountProvider: === WebAccountProvider ===
Authority organizations
DisplayName Work or school account
Id https://login.microsoft.com

Impact: 

|                     | Works ?|
| ------------- |:-------------:|
| AAD User + normal app    | no |
| MSA User + normal app  | yes |
| AAD User + MSA-PT app    | no |
| MSA User + MSA-PT app  | yes |

**Comment by bgavrilMS** [comment]
Possible solution:

```csharp
       if (string.Equals(wamAccount?.WebAccountProvider?.Authority, "organizations") && 
            string.Equals(authenticationRequestParameters.Authority.TenantId, "organizations"))
            {
                       webTokenRequest.Properties.Add("authority", "https://login.microsoftonline.com/common");
            }
            else
            {
                      webTokenRequest.Properties.Add("authority", "https://login.microsoftonline.com/organizations");
            }
```

This works for: 

|                     | Works ?|
| ------------- |:-------------:|
| AAD User + normal app    | yes |
| MSA User + normal app  | yes |
| AAD User + MSA-PT app    | yes |
| MSA User + MSA-PT app  | no |

**Comment by jmprieur** [comment]
@bgavrilMS 
Added a Workaround label to express that this is a work around only and this should be backed out when a proper fix exists on the WAM side.

**Comment by bgavrilMS** [comment]
This will be fixed in WAM and shipped with a future version of Windows.

**Comment by bgavrilMS** [comment]
Closing as won't fix. Will reopen if problem still persists in new WAM implementation.
