### ISSUE TITLE
AuthorizationCodeProvider missing part

### ISSUE THREAD

**Issue by hannespreishuber** [AzureAD/microsoft-authentication-library-for-dotnet#2484]
reading over and over 
where is the magic behind the tokens? sample code from docu doenst work  Code: authenticationChallengeRequired

`     var scopes = new string[] { "https://graph.microsoft.com/.default" };

            var cca = ConfidentialClientApplicationBuilder
                .Create(System.Configuration.ConfigurationManager.AppSettings["ClientId"])
                 .WithRedirectUri(System.Configuration.ConfigurationManager.AppSettings["redirectUri"])
                .WithClientSecret(System.Configuration.ConfigurationManager.AppSettings["ClientSecret"])
                .WithAuthority(System.Configuration.ConfigurationManager.AppSettings["Authority"])
                 .Build();
            var authenticationProvider = new AuthorizationCodeProvider(cca,scopes);
            GraphServiceClient graphClient = new GraphServiceClient(authenticationProvider);
            var user2 = await graphClient.Me
               .Request()
               .GetAsync();
`

**Comment by jennyf19** [comment]
@hannespreishuber this is not MSAL.NET, but the Graph SDK. @darrelmiller to answer.

If you're using ASP.NET Core, you should use [Microsoft identity web](https://github.com/AzureAD/microsoft-identity-web). Here's a sample [from our dev app](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/WebAppCallsMicrosoftGraph) and [here](https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsMicrosoftGraph/Pages/Index.cshtml.cs#L32)

**Comment by hannespreishuber** [comment]
1) this ist classic .net (Appsettings->web.config)
2) yes i use a sample from Graph SDK, but the problem seems to be the kind of authentication, where the source comes from the Azure App template (AzureAD)

still no solution (working on that for month)

**Comment by jmprieur** [comment]
@hannespreishuber what is the Azure App template? what is the scenario? what are your repro steps?
this issue seems to vague to me so that we can help you for the moment?

**Comment by hannespreishuber** [comment]
Azure - Portal AppModelv2-WebApp-OpenIDConnect-DotNet-master from https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Quickstart

Soruce Code 
https://github.com/hannespreishuber/AppModelv2-WebApp-OpenIDConnect-DotNet-master
