### ISSUE TITLE
[Feature Request]  change ITokenCacheSerializer.DeserializeMsalV3() to return cache object instead of void.

### ISSUE THREAD

**Issue by dhmahidawork** [AzureAD/microsoft-authentication-library-for-dotnet#2487]
**Is your feature request related to a problem? Please describe.**
I would like to store ITokenCacheSerializer.SerializeMsalV3 data in independent cache (redis, cosmos) and return is in case of 
 AAD down. Issue is  as ITokenCacheSerializer.DeserializeMsalV3() does return data type so its not possible.

**Describe the solution you'd like**
ITokenCacheSerializer.DeserializeMsalV3() return data, it will allow user to return cache data from independent cache and return it even if aad is down.

**Comment by jmprieur** [comment]
I'm confused @dhmahidawork : which kind of data would you want to return?
Do you have an architectural diagram of what you want to achieve. Did you see this article [Token cache serialization](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization)

Also there are other initiatives in progress to enable resilience.

**Comment by bgavrilMS** [comment]
Plaese use higher level caching constructs.
