### ISSUE TITLE
[Feature Request] [L] Fallback to WebView1 (WebBrowser) if WebView2 is not available

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2495]
Current strategy on .NET Core and .NET 5 is to fail if WV2 is not available. However, switching from embedded to system browser is a painful dev experience - you need to register a new redirect uri etc. 

Given that WV2 will be deployed in the box on most Win10 devices, we could fallback to WebView1 instead. 

Work to be done: 

- [x] See `MsalDesktopWebUiFactory`. It should always fallback to "legacy web browser" (`InteractiveWebUI`).
- [x] Include `WinFormsLegacyWebUi` feature on Net5 target and in `Msal.Desktop`.
- [x] Modify the web ui factories on .net5 to be the same as the one on MsalDesktop (and no code duplication pls)
- [x] Deprecate with obsolete=true the ability to specify your own runtine of WV2, as we want to just fallback on WV1 - see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/d2a8f929cdb52102773f0ae6100313a08241cfee/src/client/Microsoft.Identity.Client/ApiConfig/EmbeddedWebViewOptions.cs#L46
- [x] Update error messages about `MSAL.Desktop` from https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/d2a8f929cdb52102773f0ae6100313a08241cfee/src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreWebUIFactory.cs#L28 to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/d2a8f929cdb52102773f0ae6100313a08241cfee/src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs#L160
- [x] Update [WebView2 wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WebView2) after release

**Comment by pmaytak** [comment]
This is included in [MSAL 4.30.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.30.0).
