### ISSUE TITLE
[Feature Request] Add tracing to MSAL

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2496]
Our main method for getting logs is to register a logging callback with MSAL. This is not fit for purpose because: 

- many products that use MSAL do not enable logging
- getting logs require product changes

The standard way of getting logs is tracing, similar to how CacheExtension use it. Apps can extract logs by adding a config or using a tool like PerfView. No code changes are needed.

MSAL should fire traces as well as log messages.

**Comment by SameerK-MSFT** [comment]
This will be helpful in enhancing the observability. Developers will be able to consume the logs and act on them.

**Comment by bgavrilMS** [comment]
Path forward is `IIdentityLogger`
