### ISSUE TITLE
[Bug] WAM can't be used when requesting token for self AADSTS90009: Application '63b8670b-4b03-4c76-8e4f-0e2fb4be6a63'(63b8670b-4b03-4c76-8e4f-0e2fb4be6a63) is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier.

### ISSUE THREAD

**Issue by najadojo** [AzureAD/microsoft-authentication-library-for-dotnet#2498]
**Logs and Network traces**
[msal-verbose.log](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6191752/msal-verbose.log)

**Which Version of MSAL are you using ?**
MSAL 4.28.0

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [X] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**

```csharp
            PublicClientApp = PublicClientApplicationBuilder.Create("63b8670b-abcd-4c76-8e4f-0e2fb4be6a63")
                .WithAuthority(AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount)
                .WithExperimentalFeatures()
                .WithBroker()
                 .WithLogging((level, message, containsPii) =>
                 {
                     Debug.WriteLine($"MSAL: {level} {message} ");
                 }, LogLevel.Verbose, enablePiiLogging: true, enableDefaultPlatformLogging: true)
                .Build();
            IEnumerable<IAccount> accounts = await PublicClientApp.GetAccountsAsync().ConfigureAwait(false);
            IAccount firstAccount = accounts.FirstOrDefault();
               var authResult = await PublicClientApp.AcquireTokenSilent(new string[] { "api://63b8670b-abcd-4c76-8e4f-0e2fb4be6a63/.default" }, firstAccount)
                                                  .ExecuteAsync();
```

**Expected behavior**
Running the above could should return a successful auth result if the customer has a cached identity with appropriate consent.

**Actual behavior**
The above code gives an error result: AADSTS90009: Application '63b8670b-4b03-4c76-8e4f-0e2fb4be6a63'(63b8670b-4b03-4c76-8e4f-0e2fb4be6a63) is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier.

**Possible Solution**
The error message is fairly clear a `resource` property should have been added to the `WebTokenRequest`.

**Additional context/ Logs / Screenshots**

**Comment by jmprieur** [comment]
@najadojo 
Do you mean that the app registration for  63b8670b-abcd-4c76-8e4f-0e2fb4be6a63 is both a public client application and a web API exposing scopes?

**Comment by najadojo** [comment]
Yes that's correct.

**Comment by jmprieur** [comment]
@najadojo : did you try passing the AppIdUri of your web API (which might not be api://GUID)

**Comment by najadojo** [comment]
Not sure what you are suggesting... I'm passing the scope as listed in the app registration in the Azure Portal.

**Comment by bgavrilMS** [comment]
Possible duplicate from MSAL.Go library: https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/219

**Comment by bgavrilMS** [comment]
@jmprieur - should we ask for Hirsh's opinion this?

**Comment by jmprieur** [comment]
Sure @bgavrilMS 
cc: @hpsin

**Comment by hpsin** [comment]
Token to self has a lot of buggy behavior, which is why we strongly recommend against it.  We need to improve the documentation and story here, without breaking existing users of token to self. Shiung and I are tracking this, but don't have good line of sight to completion of it.
