### ISSUE TITLE
[Feature Request]  Microsoft.Identity.Web support for .Net framework 4.6.2.

### ISSUE THREAD

**Issue by dhmahidawork** [AzureAD/microsoft-authentication-library-for-dotnet#2499]
current version of Microsoft.Identity.Web support  .Net framework 4.7.2 or later. is it possible for you guys to provide support for  .Net framework 4.6.2 ?

**Comment by bgavrilMS** [comment]
@dhmahidawork - would you mind reopening this issue in https://github.com/AzureAD/microsoft-identity-web where Microsoft.Identity.Web belongs? 

Moving issues between repos is not a great experience and it might get lost.

**Comment by bgavrilMS** [comment]
CC @jmprieur
