### ISSUE TITLE
[Documentation] Is WAM Web Account Manager or Windows Authentication Manager?

### ISSUE THREAD

**Issue by sabuncu** [AzureAD/microsoft-authentication-library-for-dotnet#2504]
### Documentation Related To Component:
microsoft-authentication-library-for-dotnet

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
This page: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam
Under the heading WAM, it says: "MSAL is now able to call **Windows Authentication Manager**, a Win10 component that ships with the OS. This mechanism is in public preview."

Is this correct?  If so, what is Web Account Manager?

Thanks.

**Comment by bgavrilMS** [comment]
It's ` Web Account Manager`, sorry, too many acronyms :). I updated the wiki.

**Comment by sabuncu** [comment]
Whew, thank you!  When you're new to the topic like me, it's confusing.
