### ISSUE TITLE
[Feature Request] Regional authority validation

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2514]
Regional authorities cannot be validated, however the we could validate the non-regional authority. 

For example, if the input env is `hacked.com` and the regionalized env is `westus.hacked.com` 

- we cannot validate `westus.hacked.com`
- but we can validate `hacked.com` and assume `westus.hacked.com` belongs to the same threat domain

**Comment by bgavrilMS** [comment]
CC @jmprieur

**Comment by pmaytak** [comment]
This is included in [MSAL 4.30.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.30.0).
