### ISSUE TITLE
[Bug] MSAL not sending correct OS version string on .NET classic

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2517]
msal 4.29

MSAL sends x-client-os header with version string. THis is used by the server for device auth.
On .NET classic, this functionality is broken, as we mostly just send "6.2.5900" due to a bug in .NET fwk (see https://stackoverflow.com/questions/33328739/system-environment-osversion-returns-wrong-version)

This fixes the issue by send the correct OS description, e.g. "Windows 10", "Windows Server 2016" etc.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.30.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.30.0).
