### ISSUE TITLE
[Bug] Xamarin Android app Stuck after user name and password authentication is done. Does not navigate back to the app.

### ISSUE THREAD

**Issue by kgbuddhima** [AzureAD/microsoft-authentication-library-for-dotnet#2522]
<img width="429" alt="Screenshot 2021-04-01 at 19 29 49" src="https://user-images.githubusercontent.com/14989528/113305837-10345100-9321-11eb-82fb-7de047823709.png">

**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.29.0
.Net Standard 2.0.3
Xamarin.forms 4.8.0.1560

**Platform**
xamarin android

**What authentication flow has the issue?**
* Mobile

Other?
I didn't do any code changes to the sample app given by microsoft. the only change I did is adding redirect urls and client Id from my Azure AD app.

**Is this a new or existing app?**
The app downloaded from Samples

**Repo**
https://github.com/Azure-Samples/active-directory-xamarin-native-v2

`try
                    {
                        IAccount firstAccount = accounts.FirstOrDefault();
                        authResult = await App.PCA.AcquireTokenSilent(App.Scopes, firstAccount)
                                              .ExecuteAsync();
                    }
                    catch (MsalUiRequiredException ex)
                    {
                        try
                        {
                            authResult = await App.PCA.AcquireTokenInteractive(App.Scopes)
                                                      .WithParentActivityOrWindow(App.ParentWindow)
                                                      .ExecuteAsync();
                        }
                        catch(Exception ex2)
                        {
                            await DisplayAlert("Acquire token interactive failed. See exception message for details: ", ex2.Message, "Dismiss");
                        }
                    }

                    if (authResult != null)
                    {
                        var content = await GetHttpContentWithTokenAsync(authResult.AccessToken);
                        UpdateUserContent(content);
                        Device.BeginInvokeOnMainThread(() => { btnSignInSignOut.Text = "Sign out"; });
                    }`

**Expected behavior**
When the username and password are correct, the app should come to debug point => if (authResult != null)

**Actual behavior**
When calling App.PCA.AcquireTokenSilent , the login window appears. but the browser window stuck on Android emulator after user name and password entered and authentication is successful.

**Additional context/ Logs / Screenshots**
No exceptions happen

**Comment by jmprieur** [comment]
@kgbuddhima:
-  are you sure you recorded the right redirect URI?
- are you using the brokered and the non-brokered sub folder of the sample?

**Comment by bgavrilMS** [comment]
Closing. Please reopen if you have more details.
