### ISSUE TITLE
[Feature Request] Need samples or documentation to mimic Microsoft Teams SSO

### ISSUE THREAD

**Issue by geoffreygeslin** [AzureAD/microsoft-authentication-library-for-dotnet#2523]
I would like to implement an SSO experience like Microsoft Teams for Windows does in latest versions.
I don't know how Teams implements SSO. I wonder if MSAL is involved at some point...

**Describe the solution you'd like**
I want my Desktop app to be able to save token or credentials for further launch : If user did not disconnects explicitly, user remains authenticated on next run, without any prompt.
When the user disconnects, I would like my app to list all available accounts on his own authentication form (no click required on a "Authentication with Microsoft" button).

**Describe alternatives you've considered**
None. just know about MSAL persistent token cache and wonder if it can help.
Maybe I have to look for Windows Credential Center ?

**Additional context**
Solution should works for a .Net Desktop App

**Comment by jmprieur** [comment]
@geoffreygeslin 
Please read https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization
It will explain why this is not done out of the box (several strategies are possible), and will give you advice to use the cross platform cache serialization

You might also want to use WAM. See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam which will bring, on Windows, an even better SSO experience.

**Comment by bgavrilMS** [comment]
Teams use WAM, WAM is able to provide the best SSO experience possible on desktop.

**Comment by geoffreygeslin** [comment]
@jmprieur  @bgavrilMS I appreciate your answers and will check both WAM and token cache docs.

Do you know which component is used by Office desktop suite for SSO ?
I.E when I log in desktop Word, I will be directly authenticated in Excel, PowerPoint...

We build several desktop applications and SSO _between_ applications would also be appreciated for users.

**Comment by jmprieur** [comment]
I understand that you'd want to have SSO with applications.
I think you could get it with WAM or the system browser.
For the component used by the Office main apps, it's MSAL C++, which is not yet available to customers, but could be in the future.

**Comment by geoffreygeslin** [comment]
I do reed the docs and here is a quick sum up on choosing the right token cache library :
 * Use "Microsoft.Identity.Client.Extensions.Msal" with Msal.Net for public client applications (wich can use file system to store tokens)
 * Use serializers from "Microsoft.Identity.Web" for confidential Web App or Web APIs ("backends" wich may be replicated and use some distributed database or cache system to store tokens)

I still had to try WAM for better SSO ...but do not know when (priority changed on my project).

Anyway, thank you for your answers.

**Comment by jmprieur** [comment]
Thanks for the summary @geoffreygeslin 
I've copied and adapted it in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Token-cache-serialization#quick-summary
