### ISSUE TITLE
.NET Core WPF app uses browser instead of popup

### ISSUE THREAD

**Issue by leskodan** [AzureAD/microsoft-authentication-library-for-dotnet#2527]
**Which Version of MSAL are you using ?**

Microsoft.Identity.Client 4.29.0

**Platform**

.NET Core 3.1 WPF

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**

This is a new application.

**Repro**

```csharp
Window window = new Window();

authResult = await app.AcquireTokenInteractive(App.ApiScopes)
        .WithParentActivityOrWindow(new WindowInteropHelper(window).Handle)
        .ExecuteAsync();
```

**Expected behavior**
I have been following [this](https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop) example (which is a .NET Framework based sample) as a guide for integrating msal into my .NET Core 3.1 based WPF application. In this sample, ``AquireTokenInteractive()`` instantiates a browser popup which closes and returns to the app following authentication. This is the behavior I am attempting to replicate.

**Actual behavior**
The first issue that I ran into was related to B2C's support of netcore 3.1 in terms of redirects. Based on #1213, I was able to see that simply using ``http:localhost`` as the redirect uri makes the flow work, however, instead of a browser popup, the process opens the system browser and does not return to the application automatically after authentication.

How do I use the popup in this context?

**Related Question**
Is the ``http://localhost`` workaround suitable for production? Based on [this documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url) (see "Localhost Exceptions"), I am inclined to believe that it is.

Thanks!

**Comment by jmprieur** [comment]
http://localhost is fine.
you can use the WebView2 to have an embedded web view. For details see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WebView2

@bgavrilMS, is this article surfaced in the documentation TOC? (I could not find it)

**Comment by bgavrilMS** [comment]
in MSAL 4.30 (due in a 1-2 weeks), we will have better support for embedded webview and we should review our docs.
