### ISSUE TITLE
[Internal] Update code signing build task as per email

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2530]
See `ESRP Submission Failures ... ` email for details

If any changes need to be made, please apply them to all our projects: 

- [ ] MSAL
- [ ] ADAL
- [ ] M.I.W
- [ ] MSAL cache extension

**Comment by trwalke** [comment]
I can confirm that we are using the correct signing configuration for our SDKs.
