### ISSUE TITLE
[Bug] remove ? from filename in wiki

### ISSUE THREAD

**Issue by jongio** [AzureAD/microsoft-authentication-library-for-dotnet#2539]
Wiki file Is-MSAL.NET-right-for-me?.md - has a `?` in the title, which isn't allowed in Windows.  Please remove the ? from the filename.

**Comment by jmprieur** [comment]
Let's duplicate that page. There are links from several docs that we want to change

**Comment by jongio** [comment]
If we want to allow people to edit on windows then we can't keep the file with the ? in the title.  If you dupe and keep it then the file won't be fetched by windows and will look like it was deleted to git.

**Comment by jennyf19** [comment]
@jongio what are people editing exactly? I don't believe outside contributors can edit the wiki anyway. Usually, from customers or even internal partners, they give us an MD file w/updates and we copy/paste. Just trying to understand the issue better. thanks.

**Comment by jongio** [comment]
when you git clone on Windows
```
git clone https://github.com/AzureAD/microsoft-authentication-library-for-dotnet.wiki.git
Cloning into 'microsoft-authentication-library-for-dotnet.wiki'...
error: invalid path 'Is-MSAL.NET-right-for-me?.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```


There is a way for people to edit wiki.  I tried to today for #2540

**Comment by jennyf19** [comment]
@jongio thanks. we've had issues w/customers not being able to edit directly. are you going to push your changes for the iOT spelling?

**Comment by jongio** [comment]
No, too much of a pain to setup wiki to do a PR :)

I figured you'd be able to make the change in 2 mins versus me in many mins.

**Comment by jennyf19** [comment]
yes, but thought i'd ask just in case ;) 
thanks for bringing these issues to our attention.

**Comment by bgavrilMS** [comment]
workaround: Don't clone the wiki repo on Windows :)
