### ISSUE TITLE
[Bug] AcquireTokenForClient should use a partitioned token cache by default and not log errors

### ISSUE THREAD

**Issue by rabenshm** [AzureAD/microsoft-authentication-library-for-dotnet#2544]
**Which Version of MSAL are you using ?**
MSAL 4.29

**Platform**
net472

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [x] Service to Service calls

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Repro**

Use the following approach for token caching: 

- maintain a dictionary of [client_id] -> [ConfidentialClientApp]
- not a multi-tenant app, there is always 1 tenant 
- do not serialize the cache in any way
- for each request, try to reuse an existing CCA. If it does not exit, create one.

**Expected behavior**
Token and no error log messages

**Actual behavior**
Token. But we get the following **error** log message:

2021-04-12 15:34:11Z KD.MSAL    (False) MSAL 4.29.0.0 MSAL.Desktop Microsoft Windows NT 10.0.19042.0 [04/12/2021 15:34:11 - ] The default token cache provided by MSAL is not designed to be performant when used in confidential client applications. Please use token cache serialization. See https://aka.ms/msal-net-cca-token-cache-serialization.

**Impact**
Kusto offer this as part of their SDK, and pipe the MSAL errors into their logging pipeline, which customers monitor. These errors will create noise for customers monitoring the logs.

**Comment by bgavrilMS** [comment]
CC @jmprieur

**Comment by jmprieur** [comment]
@bgavrilMS 
I'm happy to remove the log error, but only if we provide an in-memory partitionned cache by default (which we could register with the normal pattern). Maybe something like the following? (and we could move / copy MsalAbstractTokenCacheProvider to MSAL.NET)

```CSharp
   /// <summary>
    /// Msal token cache serialize based on a concurrent dictionary.
    /// </summary>
    public class MsalDictionaryBasedTokenCacheSerializer : MsalAbstractTokenCacheProvider
    {
        private ConcurrentDictionary<string, byte[]> partitionnedCache = new ConcurrentDictionary<string, byte[]>();

        /// <inheritdoc/>
        protected override Task<byte[]> ReadCacheBytesAsync(string cacheKey)
        {
            byte[] value;
            partitionnedCache.TryGetValue(cacheKey, out value);
            return Task.FromResult(value);
        }

        /// <inheritdoc/>
        protected override Task WriteCacheBytesAsync(string cacheKey, byte[] bytes)
        {
            partitionnedCache.AddOrUpdate(cacheKey, bytes, (c, b) => b);
            return Task.CompletedTask;
        }

        /// <inheritdoc/>
        protected override Task RemoveKeyAsync(string cacheKey)
        {
            partitionnedCache.TryRemove(cacheKey, out _);
            return Task.CompletedTask;
        }
    }
```

**Comment by pmaytak** [comment]
This is included in [MSAL 4.30.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.30.0).

cc: @rabenshm

**Comment by sea1jxr** [comment]
@pmaytak It appears your change didn't remove the original error message that was the reason for this issue.  Should it be removed?

_2021-04-12 15:34:11Z KD.MSAL (False) MSAL 4.29.0.0 MSAL.Desktop Microsoft Windows NT 10.0.19042.0 [04/12/2021 15:34:11 - ] The default token cache provided by MSAL is not designed to be performant when used in confidential client applications. Please use token cache serialization. See https://aka.ms/msal-net-cca-token-cache-serialization._

**Comment by pmaytak** [comment]
@sea1jxr can you verify which MSAL version you used? In the log above it shows MSAL 4.29 and this change was in 4.30.

**Comment by sea1jxr** [comment]
@pmaytak I was using 4.34.0  Also you can look at the change and see that the error message still exists.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2550/files#L80

**Comment by pmaytak** [comment]
Yep, the message is still there, but since there's a default token serialization cache in the confidential client app now, the message won't be shown.

**Comment by pmaytak** [comment]
To-do: error message reported to be shown in 4.34. Need to investigate/repro.

**Comment by sea1jxr** [comment]
I just checked our logs, and we are using 4.34.0 and default serialization and we are getting the message when calling AcquireTokenOnBehalfOf not AcquireTokenForClient.   Does this make more sense, and should I be getting the message in that case?

**Comment by bgavrilMS** [comment]
@sea1jxr - yes, the default user (i.e. not app / S2S) MSAL cache is pretty horrible, as it will hold all tokens in memory. This simply does not scale for a web app or for a web api, where there is 1 token (well, 1 access token, 1 refresh token and 1 ID token) for **each user**. Unfortunately, MSAL cannot offer a better default implementation, as we cannot introduce breaking changes.

If you are not ready to use a distributed cache like Redis, you should at least configure a token cache that uses a dictionary for example. 

Have a look at: https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization

**Comment by jennyf19** [comment]
@sea1jxr Actually you can use Microsoft Identity Web to help with the caching. See [documentation here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet).

You can just use the `app.AddInMemoryTokenCaches();` or 
```csharp
app.AddDistributedTokenCaches(services =>
{
       services.AddDistributedMemoryCache();
 });
```
and you will benefit from correct partitioning and a much more performant cache, without having to set up redis or another distributed cache. 
See differences between [InMemory and DistributedMemory caches](https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization#inmemory-vs-distributedmemory-cache-options).

cc: @bgavrilMS
