### ISSUE TITLE
[Bug] Remove Xamarin iOS workaround for background thread

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2556]
Patch for [4.27.1](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/compare/4.27.0...jennyf/hotfix4.27.1?expand=1) will also be in 4.30.

**Comment by jennyf19** [comment]
cc: @bemartin

**Comment by jennyf19** [comment]
reminder to the team that we need to have @bemartin re-test w/the 4.30 release just to make sure there are no issues.

**Comment by jennyf19** [comment]
[4.27.1 patch](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.27.1) release

**Comment by pmaytak** [comment]
This is included in [MSAL 4.30.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.30.0).

cc: @bemartin @parkhk10
