### ISSUE TITLE
[Feature Request] [M] Add telemetry data to WAM 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2562]
When talking to WAM, we want to be able to tell if an app uses an MSAL library or if they use WAM directly. The solution is to send our existing `x-client*` data to WAM, using the `Properties` bag on requests. For example: 

```
x-client-SKU       MSAL.xplat.Win32
x-client-Ver        1.0.0+local
x-client-OS          10.0.19041.928
x-client-src-SKU MSAL.xplat.Win32
```

This is similar to how we add `wam_compat=2.0` property

**Comment by pmaytak** [comment]
This is included in [MSAL 4.31.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.31.0).
