### ISSUE TITLE
[Bug] [WAM-VS] [L] Wrong parenting of account picker 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2566]
4.30

1. Start a WinForms or WPF app (VS)
2. From this app, start a new process (IdentityService)
3. From this process, call WAM interactive with account picker, making sure to pass along the WindowHandle of the original process (VS). Note that Window Handles are a OS-wide, and can be sent around as simple integers (long). 

**Actual**: the account picker is not parented correctly

**Comment by pmaytak** [comment]
This is included in [MSAL 4.31.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.31.0).
