### ISSUE TITLE
[Feature Request] [2L] Expose tenant profiles in IAccount and ID token claims in the AuthenticationResult

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#2583]
**Is your feature request related to a problem? Please describe.**
Several customers want to get the ID token claims in the authentication result. See for instance #2580.

**Describe the solution you'd like**
- The AuthenticationResult could expose a new method `.GetIdTokenClaims()` returning a `ClaimsPrincipal` as this is the data structure which is commonly used in .NET - see #2584 
- More generally, we'd want that `IAccount` exposes `TenantProfiles`
- Update API review with .NET and Java design

```CSharp
interface IAccount
{
 // current members

 /// <summary>
 /// Get the information about the account in each tenant, keyed by tenant Id
 /// </summary>
 IDictionnary<string, ITenantProfile> TenantProfiles { get; }
}

interface ITenantProfile
{
  /// <summary>
  /// Get object if of the account in this tenant
  /// </summary>
  public string Oid {get;}

  /// <summary>
  /// Get the tenant ID
  /// </summary>
  public string TenantId {get;}

  /// <summary>
  /// Get the claims of the ID token for the account in this tenant
  /// </summary>
  public ClaimsPrincipal Claims {get;}

  /// <summary>
  /// Is the tenant the home tenant of the user?
  /// </summary>
  public bool IsHomeTenant {get;}
}
```

**Additional context**
- Tenant profile is a consistency item ... See the API review spec / design for Android: [Account & Tenant Profiles
](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=%2FAccountDomainModel%2FOverview.md&_a=preview&version=GBdev&anchor=account-%26-tenant-profiles)
- This is mostly for public client applications, or applications that don't use ASP.NET / ASP.NET Core as these framework already populate the .User.

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2571

**Comment by bgavrilMS** [comment]
Not sure this can be done for Confidential Client due to not checking signatures, continuing discussions offline.

**Comment by neha-bhargava** [comment]
FYI: PR for Java's implementation of tenant profiles in api review: https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/3515?path=%2FAccountDomainModel%2FOverview.md

**Comment by bgavrilMS** [comment]
@neha-bhargava  @jmprieur's there is subtle difference between this proposal and the one in Java lib. The Java proposal suggest to hide the extra API behind an interface that is not exposed to developers:


```java
AuthenticationResult result = pca.acquireToken(...otherTenantId);

IAccount account = result.getAccount();
String accountId = account.getId();
String objectId = account.getClaims.get("oid");

IMultiTenantAccount multiTenantAccount = (IMultiTenantAccount)account;

String tenantSpecificObjectId = multiTenantAccount.getProfiles().get(otherTenantId).getClaims().get("oid");
```

Is the purpose of this interface solely to hide the API?

**Comment by neha-bhargava** [comment]
> @neha-bhargava @jmprieur's there is subtle difference between this proposal and the one in Java lib. The Java proposal suggest to hide the extra API behind an interface that is not exposed to developers:
> 
> ```java
> AuthenticationResult result = pca.acquireToken(...otherTenantId);
> 
> IAccount account = result.getAccount();
> String accountId = account.getId();
> String objectId = account.getClaims.get("oid");
> 
> IMultiTenantAccount multiTenantAccount = (IMultiTenantAccount)account;
> 
> String tenantSpecificObjectId = multiTenantAccount.getProfiles().get(otherTenantId).getClaims().get("oid");
> ```
> 
> Is the purpose of this interface solely to hide the API?

@jmprieur to confirm but seems like it to me too. We don't expose the api directly.

**Comment by jmprieur** [comment]
@neha-bhargava @bgavrilMS 
What would be the point for us of having a hidden APIs. Our customers want to get the claims.

I would think that, in Java, this is related to the fact that they support front line workers, and have explicitly multi-tenant accounts. In MSAL.NET I'd say, we expose the API directly, and if there is only one tenant, there is only one tenant?

Is there code that I can try out? I see only this branch (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/nebharg/AddTokenIdClaims), but this is pretty old?

**Comment by neha-bhargava** [comment]
@jmprieur That is the old branch I created when trying to add claims to Auth result. Kept this for reference. Still working on it. Will update when the branch is ready.

**Comment by bgavrilMS** [comment]
Agreed that we should expose tenant profiles by default.
