### ISSUE TITLE
[Bug] Unity Windows Standalone il2cpp: NotSupportedException: System.Reflection.Emit.DynamicMethod::.ctor

### ISSUE THREAD

**Issue by najadojo** [AzureAD/microsoft-authentication-library-for-dotnet#2586]
**Which Version of MSAL are you using ?**
MSAL 4.30

**Platform**
net45 compiled with Unity Standalone il2cpp configuration

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**
Create a Unity project and add MSAL authentication code similar to the below in a Unity component.
Target Standalone and use the IL2CPP scripting backend.

```csharp
private void BeforeAccessNotification(TokenCacheNotificationArgs args)
{
    lock (FileLock)
    {
        args.TokenCache.DeserializeMsalV3(File.Exists(CacheFilePath)
            ? ProtectedData.Unprotect(File.ReadAllBytes(CacheFilePath), null, DataProtectionScope.CurrentUser)
            : null);
    }
}

private void AfterAccessNotification(TokenCacheNotificationArgs args)
{
    // if the access operation resulted in a cache update
    if (args.HasStateChanged)
    {
        lock (FileLock)
        {
            // reflect changes in the persistent store
            File.WriteAllBytes(
                CacheFilePath,
                ProtectedData.Protect(
                    args.TokenCache.SerializeMsalV3(),
                    null,
                    DataProtectionScope.CurrentUser));
        }
    }
}

PublicClientApplicationBuilder builder = PublicClientApplicationBuilder.Create(clientId);
builder = builder.WithRedirectUri("http://localhost");
builder = builder.WithAuthority(AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount);
builder = builder.WithLogging(MsalLog, LogLevel.Error, true);
var PublicClientApp = builder.Build();
PublicClientApp.UserTokenCache.SetBeforeAccess(BeforeAccessNotification);
PublicClientApp.UserTokenCache.SetAfterAccess(AfterAccessNotification);

var authResult = await PublicClientApp.AcquireTokenSilent(scopes, Account).ExecuteAsync();
```

**Expected behavior**
No dynamic code generation.

**Actual behavior**
NotSupportedException: System.Reflection.Emit.DynamicMethod::.ctor

**Possible Solution**
Building locally and removing the HAVE_CAS define seems to resolve the issue.

**Additional context/ Logs / Screenshots**
[Player.log](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6388281/Player.log)

**Comment by jmprieur** [comment]
@pmaytak : do you have an idea?

**Comment by bgavrilMS** [comment]
So far we've been asking folks to go with DeviceCode for unity. But using system browser would be very cool. 

Note that for Hololens use, I believe you have to use UWP + WAM.

**Comment by najadojo** [comment]
Yes UWP isn't a problem it is using the uap10.0 assembly which doesn't have this issue. But this isn't a HoloLens issue its a Windows Desktop issue.

DeviceCode flow has this problem with the net45 assembly as well. I believe you are suggesting to fallback to netstandard1.3 which isn't the topic of this issue. 

Primarily I'm asking what is the HAVE_CAS flag for and should it be removed to support this scenario?

**Comment by bgavrilMS** [comment]
We have no idea @najadojo - we copied Newtonsoft json library inside MSAL. We used to reference it, however this causes lots of problems (diamond depdencies), so we copied the logic inside MSAL. Those flags are Newtonsoft related.

**Comment by pmaytak** [comment]
@najadojo So you're not able to use netstandard1.3 in your project?

@bgavrilMS The HAVE_CAS flag is only set for net45/net461. It sets the dynamic code generation flag here:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/cd788b521090d6d62cb5edd5a695330650ff5f6d/src/client/Microsoft.Identity.Client/json/Serialization/JsonTypeReflector.cs#L462-L478
Which if it's false, then the behavior looks to be the same as what we have in netstandard.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/cd788b521090d6d62cb5edd5a695330650ff5f6d/src/client/Microsoft.Identity.Client/json/Serialization/JsonTypeReflector.cs#L519-L531

**Comment by bgavrilMS** [comment]
@pmaytak - am thinking of the following 2 possibilities: 

1. If there is no perf impact on this (think confidential client level of impact, where p95% is ~30ms), then let's do it.
2. If there is a small perf impact, let's do it only for public client
3. If there is a big perf impact, let's add some sort of 

```csharp
.WithUnitySupport();
```

Thoughts?

**Comment by najadojo** [comment]
No, we'd like the built-in browser launching that netstandard1.3 doesn't supply.

**Comment by pmaytak** [comment]
@bgavrilMS Yea, I can do a perf test, similar to what I did for previous work (#2428).

**Comment by pmaytak** [comment]
@bgavrilMS 
|                                     Method |      Mean (with flag, current) |      Mean (without flag) |
|------------------------------------------- |----------:|----------:|
|           Serialize_MsalTokenResponse_Test |  4.256 μs |  7.438 μs |
|         Deserialize_MsalTokenResponse_Test |  8.685 μs | 13.194 μs |
|   Serialize_InstanceDiscoveryResponse_Test | 30.063 μs | 42.920 μs |
| Deserialize_InstanceDiscoveryResponse_Test | 47.900 μs | 78.104 μs |
|          Serialize_OAuth2ResponseBase_Test |  1.574 μs |  2.347 μs |
|        Deserialize_OAuth2ResponseBase_Test |  2.724 μs |  4.348 μs |

**Comment by bgavrilMS** [comment]
I also ran a test for serializing / deserializing the token cache (I added a row in the table above). All in all, it does not seem to be bad. I think we can: 

- implement this for both public client & confidential client (very simple change)
- implement this only for public client (a bit more work)

@henrik-me  - thoughts?
