### ISSUE TITLE
[Bug] Update Webview2 userData folder location with the appropriate default value

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2591]
Continuation of issue here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2502

We are currently using `%UserProfile%/.msal/webview2/data` as the default location for the userData folder for webview2 but customers have complained that this can cause issues.

"it's important for packaged apps to store their app data within the %LocalAppData%\Packages\xxxxxxxxxxxx folder. Makes it much easier for clean install/uninstall, and enforces app isolation. Unless there is some magic to direct %UserProfile% in packaged apps (which there could be, but it didn't seem so in my preliminary tests), it's not going to get stored in the appropriate place if an app uses APPX/MSIX packaging."

We are waiting on the Webview2 team to provide a better implementation that will allow us to rely upon a default location provided by the webview2 component itself. (https://github.com/MicrosoftEdge/WebView2Feedback/issues/297)

There are also suggestions provided:

- _(most preferred)_ Make the WebView2WebUi extendable without having to fork the entire repo, or have some extendable version of it that can be easily passed to `.WithCustomWebUi()`
- Make the user data folder customizable (i.e. a property of `EmbeddedWebViewOptions`)
- _(least preferred, but acceptable)_ Handle the special case of detecting if the app is running with packaged identity and use a subfolder of `%LocalAppData%\Packages\xxxxxxxxxxxx` instead of `%UserProfile%`

**Comment by bgavrilMS** [comment]
Blocked by partner

**Comment by pmaytak** [comment]
For tracking: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1410

**Comment by bgavrilMS** [comment]
For AAD, please use WAM - https://aka.ms/msal-net-wam
