### ISSUE TITLE
MSAL .aars & Xamarin Binding Library?

### ISSUE THREAD

**Issue by vinceweeks-69** [AzureAD/microsoft-authentication-library-for-dotnet#2592]
I want to use Azure AD and msal sso for Xamarin. Is there an .aar for this project? Specifically for the MSAL module? If so, couldn't that .aar be used in a Xamarin Binding Library? I'm specifically looking for MultipleAccountPublicAccountApplication interfaces and classes that don't exist in the .net library for Microsoft.Identity.Client. Is this even do-able?

**Comment by trwalke** [comment]
Hi @vinceweeks-69, we have the multiple account mode available by default for MSAL.NET. It is built into the api already. Here is a sample demonstrating how to use it with the MSAL api (https://github.com/azure-samples/active-directory-xamarin-native-v2)

We do not support single account mode however, that functionality will be coming in MSAL 5.0. We are planning on binding to the MSAL Android AAR to gain feature parity with the MSAL Android project.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2172
