### ISSUE TITLE
[Bug] MSAL webview with secure certificate on App UWP

### ISSUE THREAD

**Issue by vinhdp195** [AzureAD/microsoft-authentication-library-for-dotnet#2600]
Getting tokens through MSAL, I am having the following problem:
Can't login at site organization (requires certificate)
Detail error:
1 / I have a UWP app
2 / At the app, open the authentication window (Webview)
3 / Enter user organization
4 / Redirect to the organization's authentication page (example: adfs.xyzcompany.co.jp)
5 / Input userid and password
=> Error: Select the certificate to use for authentication. If you want to cancel the operation, close the browser and try again.

In Browser Chrome, IE does not have the above error
I added a certificate to Chrome, IE. I still login successfully using the browser

=> I think in step number (2), Webview has no right to find the added certificate in IE browser
Is there any information about the error above or not?
I also tried with ADAL but still got the same error

**Comment by bgavrilMS** [comment]
It would be better if you could follow the issue template. What version of MSAL do you use? How does your code look like? 

The webview login in UWP is on course to be deprecated. We strongly recommend that you use WAM, see https://aka.ms/msal-net-wam

**Comment by vinhdp195** [comment]
Sorry because the description is not detailed

MSAL version is in use: 4.29.0
Code is at my UWP app:

**Comment by vinhdp195** [comment]
@bgavrilMS 
I tried with WAM with the following code: 

```
var pca = PublicClientApplicationBuilder.Create("client_id")
          .WithExperimentalFeatures()
          .WithBroker()
          .Build();
```

However, at the account window, cannot find the account that is logged in Chrome or IE Browser
Since this is an organization account, I chose to continue to the orther account
Now the window switches to login using Webview as above and also cannot login (error without certificate)

**Comment by vinhdp195** [comment]
@bgavrilMS 
I think it is impossible to solve the problem with WAM
Because the Windows account also has to add an account by selecting "Add a work or school account".
=> But at "Add a work or school account",  using a webview to login => The certificate is also not visible here

**Comment by bgavrilMS** [comment]
@vinhdp195 - trying to understand this better, since identity SDK does not use any certificates in PublicClientApplication. We rely on the browser (webview) to do the right thing. 

You said that if you try this with Chrome or IE, it works. Could you do a print screen for when that cert selection apears? 

Finally, could you capture a correlation ID ? It should be in the browser under "more details". It might allow us to see the exact failure.

**Comment by vinhdp195** [comment]
@bgavrilMS 
Error when the WAM not apply:
![2021-05-06_104522](https://user-images.githubusercontent.com/38124542/117239448-f5da1f80-ae58-11eb-863b-1309fd77f5fe.png)

Error applying WAM
![2021-05-06_104746](https://user-images.githubusercontent.com/38124542/117239461-ff638780-ae58-11eb-841b-13591d58248a.png)

**Comment by vinhdp195** [comment]
@bgavrilMS 
In Edge and IE, after I add a valid certificate I can login normally
![2021-05-06_105939](https://user-images.githubusercontent.com/38124542/117240185-7e0cf480-ae5a-11eb-8d29-0a94c6206b77.png)
![2021-05-06_110016](https://user-images.githubusercontent.com/38124542/117240189-7fd6b800-ae5a-11eb-8563-cf4c303dfdae.png)

**Comment by bgavrilMS** [comment]
I don't know where to route this problem. @henrik-me @jmprieur - can you help?

**Comment by henrik-me** [comment]
@bgavrilMS not sure. UWP team?

**Comment by bgavrilMS** [comment]
+ @Andrew ***@***.***> - would you have any suggestion for us on how to follow up with this issue? It seems to happen with the WEB control as well as with WAM.

Bogdan

**Comment by bgavrilMS** [comment]
Hi @vinhdp195 , sorry for the long delay. MSAL library doesn't deal with this type of problems specifically, but here's what I found out: 

The browsers on UWP (web auth host and WAM's browser) are isolated / run in a sandboxed env and cannot access the main browser's cookies / certs etc.

I think the cert may need to be installed system wide (i.e. in the Personal cert store maybe?)

Alternatively, Windows Hello will work with WAM.
