### ISSUE TITLE
AADSTS50013: Assertion failed signature validation. [Reason - The key was not found., Thumbprint of key used by client: 'xxxx'[Bug] 

### ISSUE THREAD

**Issue by santoshpatro** [AzureAD/microsoft-authentication-library-for-dotnet#2604]
Hi Team,

Need help on the issue detailed at : https://stackoverflow.com/questions/67400354/aadsts50013-assertion-failed-signature-validation-reason-the-key-was-not-fo

Any help on this issue is much appreciated

Thanks,
Santosh

**Comment by jmprieur** [comment]
@santoshpatro : I'm not familiar with the SAML apps, but I suspect that the ASP.NET Core web API (that you name "Back" on your diagram) does not use the same certificate as the one registered in the app registration ?

Adding @hpsin who might know better, or know who knows.

**Comment by santoshpatro** [comment]
Thanks much @jmprieur  and @bgavrilMS  for your response.

**Comment by santoshpatro** [comment]
Any help on the this request is much appreciated

**Comment by jmprieur** [comment]
@santoshpatro : do you have repro steps? As it is we don't have enough information to help you

**Comment by santoshpatro** [comment]
@jmprieur  - I have updated the question with all the details

**Comment by santoshpatro** [comment]
@jmprieur and @bgavrilMS - Any help on this issue is much appreciated. In case there are any examples related to this scenario please share it with me.

**Comment by bgavrilMS** [comment]
@jmprieur - could we ask CXP to handle this complex scenario?

**Comment by bgavrilMS** [comment]
not enough info but external. please open a service bug.
