### ISSUE TITLE
[Feature Request] Interaction with Azure B2C without using a web browser

### ISSUE THREAD

**Issue by IgorSivirinov** [AzureAD/microsoft-authentication-library-for-dotnet#2606]
Using a Web browser to register, log in, edit a profile, reset the password in applications for smartphones and desktop, I think is not correct. This makes it difficult to get a beautiful UI and individual UI for each platform.

I suggest creating new methods for interacting with Azure B2C.

Examples of methods:
``` C#
var clientApp = PublicClientApplicationBuilder
                .Create(ClientId)
                .WithRedirectUri(RedirectUri)
                .WithB2CAuthoritySignUpSignIn(AuthoritySignUpSignIn)
                .WithB2CAuthorityEditProfile(AuthorityEditProfile)
                .WithB2CAuthorityResetPassword(AuthorityResetPassword)
                .Build();

var authResult = await clientApp.LoginAsync(email, password);

var result = await clientApp.RegistrationAsync(user, password);

var result = await clientApp.EditProfileAsync(user);

var result = await clientApp.ResetPasswordAsync(password);
 ```

**Comment by jmprieur** [comment]
@IgorSivirinov I don't understand your suggestion.

AzureAD B2C is (mostly) using modern auth where a private dialog happens between the user and the identity provider (Azure AD B2C). Using username/password makes it impossible to process conditional access (multiple factor authentication) etc ...

Are you saying that you'd like to have comfort methods to add the authorities and to process the user flows?

**Comment by IgorSivirinov** [comment]
@jmprieur I would like one that looks more like [Firebase Authentication] (https://firebase.google.com/docs/auth). This gives you more options for creating a beautiful user interface.

**Comment by IgorSivirinov** [comment]
@jmprieur I would like methods that allow not to use the Web browser to interact with AzureAD B2C. Similar functionality is well implemented in [Firebase Authentication](https://firebase.google.com/docs/auth).

**Comment by jmprieur** [comment]
@nickgmicrosoft @JasSuri I think this is a feedback for the service.

**Comment by bgavrilMS** [comment]
B2C does allow Username / Password auth - see https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-ropc-policy?tabs=app-reg-ga&pivots=b2c-user-flow but you should really use it for testing flows only.

However, as @jmprieur states, modern auth is based on user interacting with a browser. We expect the user interaction to happen:

- the fist time the user logs in to the app / web site
- each time the Identity Provider wants to challenge the user (e.g. you login from a different location, or a tenant admin configured MFA)
- if the app requests more scope

So broadly speaking, you can expect to login your users once interactively, and then login them silently forever after. This is the basis of modern auth.

**Comment by bgavrilMS** [comment]
Will be closing this as we don't have server support for it. Please open a request to the service via the Azure Portal.
