### ISSUE TITLE
[Bug] MsalClientException: The cache contains multiple tokens satisfying the requirements. Try to clear token cache. 

### ISSUE THREAD

**Issue by najadojo** [AzureAD/microsoft-authentication-library-for-dotnet#2610]
Our application gets a token for 'openid', 'offline_access', and 'profile' interactively and uses ITokenCache to cache the results. At this point we can request tokens non-interactively for the scopes we've consented to. If we attempt another token request for the scopes: 'openid', 'offline_access', and 'profile' we get an error:  `The cache contains multiple tokens satisfying the requirements.`

**Logs and Network traces**
[multiple_matching_tokens_detected.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6437975/multiple_matching_tokens_detected.txt)

**Which Version of MSAL are you using ?**
MSAL 4.30.0

**Platform**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL

**Repro**

```csharp
        private void BeforeAccessNotification(TokenCacheNotificationArgs args)
        {
            lock (FileLock)
            {
                args.TokenCache.DeserializeMsalV3(File.Exists(CacheFilePath)
                    ? ProtectedData.Unprotect(File.ReadAllBytes(CacheFilePath), null, DataProtectionScope.CurrentUser)
                    : null);
            }
        }

        private void AfterAccessNotification(TokenCacheNotificationArgs args)
        {
            // if the access operation resulted in a cache update
            if (args.HasStateChanged)
            {
                lock (FileLock)
                {
                    // reflect changes in the persistent store
                    File.WriteAllBytes(
                        CacheFilePath,
                        ProtectedData.Protect(
                            args.TokenCache.SerializeMsalV3(),
                            null,
                            DataProtectionScope.CurrentUser));
                }
            }
        }

            PublicClientApplicationBuilder builder = PublicClientApplicationBuilder.Create(clientId);
            builder = builder.WithRedirectUri("http://localhost");
            builder = builder.WithAuthority(AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount);
            builder = builder.WithLogging(MsalLog, LogLevel.Verbose, enablePiiLogging: false);
            var PublicClientApp = builder.Build();
            var tokenCache = PublicClientApp.UserTokenCache;
            tokenCache.SetBeforeAccess(BeforeAccessNotification);
            tokenCache.SetAfterAccess(AfterAccessNotification);

            var probingGraphScopes = new string[]{ "openid", "offline_access","profile" };

            AuthenticationResult authResult;
            try
            {
                authResult = await PublicClientApp.AcquireTokenSilent(probingGraphScopes, Account).ExecuteAsync();
            }
            catch (MsalUiRequiredException msalUiEx)
            {
                AcquireTokenInteractiveParameterBuilder intBuilder = PublicClientApp.AcquireTokenInteractive(probingGraphScopes);
                intBuilder = intBuilder.WithUseEmbeddedWebView(false);

                authResult = await intBuilder.ExecuteAsync();
                Account = authResult.Account;
            }

            authResult = await PublicClientApp.AcquireTokenSilent(new string[] { "api://98e6160b-4308-432a-b82d-ed6fce38dfbf/.default" }, Account).ExecuteAsync();

            authResult = await PublicClientApp.AcquireTokenSilent(probingGraphScopes, Account).ExecuteAsync();
```

**Expected behavior**
Attempting to request token with cached Account should succeed. 

**Actual behavior**
```
MsalClientException: The cache contains multiple tokens satisfying the requirements. Try to clear token cache. 
```

**Comment by jmprieur** [comment]
@najadojo : which version of MSAL.NET did you update from?

Your code look legit at a first glance, but we would not write it like that: 
- You don't need to pass-in "openid", "offline_access","profile" , as they are already automatically requested by MSAL.NET. In particular with AcquireTokenSilent, I'm even surprized that you even get an **access token** in the authentication result (you do get an ID Token)
- Is there a reason why you don't not ask for a token for the API in the first place?

**Comment by najadojo** [comment]
I'm doing my best to emulate what I can do with WAM. I want to pass different scopes when the customer is using AAD vs MSA. As such I ask for the openid scopes to determine which tenant was returned and then follow with additional scopes depending on the answer. Its only the later scope requests where I pay attention to the token values.

I don't think the version of MSAL.NET had precipitated this condition but we did recently change from 4.10 to 4.30.

**Comment by bgavrilMS** [comment]
Please use latest MSAL and see if problem still occurs. Closing as this is very old bug and we cannot repro.
