### ISSUE TITLE
Question - timing problem getting token back after incremental consent

### ISSUE THREAD

**Issue by dmcweeney** [AzureAD/microsoft-authentication-library-for-dotnet#2612]
Hi,

We have an existing Asp.Net Core Web App/Api wired for OIDC auth and utilizing MSAL.Net 4.29.
We have extended this backend by adding Jwt Bearer token auth to support the client SSO when running in Teams.

All works fine except one scenario that is causing a problem. 

There is a part of the app that requires incremental consent. 
The inc consent flow works fine for the OIDC side of the house.
However when performing the inc consent from within Teams there is a timing problem. 

The flow is:
1. the client app code  running in Teams invokes the Teams SSO auth flow.
2. the user consents to the additional required scopes
3. the flow goes back into the client app running in Teams
4. the client app calls a backend api to issue a call to the graph api
5. the backend code calls the MSAL.Net AcquireTokenOnBehalfOf with WithForceRefresh=true
6. as there is no token in the local cache with the required scopes a POST is made to https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token
7. this call returns 400 / BadRequest / invalid_grant 

However the user has just consented to the additional scopes

If we put in a SLEEP of 30 seconds after the user grants the additional consents and before the api call is made to the backend (between 3 and 4 above) then it works. ie AcquireTokenOnBehalfOf will make the call to https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token and get a valid token back for calling the graph api.

Question - how do we get around this timing problem without the use of a SLEEP?

Thanks, Donal

**Comment by jmprieur** [comment]
@dmcweeney: 
- why are you using force refresh? this is very bad for performance: you can be throttled by AAD, and that would explain the time out?
-  did you consider using MIcrosoft.Identity.Web for your web API: https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis ?

**Comment by dmcweeney** [comment]
@jmprieur 

> why are you using force refresh? this is very bad for performance: you can be throttled by AAD, and that would explain the time out?

Understood as regards performance - however forceRefresh is being used only in this post incremental consent flow to try and 
force AAD to return the most up-to-date token for the additional scopes that the user has just consented to. 
But that aint happening - BadRequest/invalid_grant is being returned with forceRefresh true or false.

Apologies about the use of the word timeout - I had to meant SLEEP - (post updated/I was obviously in a sleep). If we do a sleep of 30 seconds after the inc consent flow completes, then all works fine!

> did you consider using MIcrosoft.Identity.Web for your web API: https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis ?

I did but retro-fitting all the backend code with MIcrosoft.Identity.Web would have created too much work and retesting!
It is on my roadmap to do at some stage.

**Comment by jmprieur** [comment]
@dmcweeney : can we know a bit more about the MsalServiceException? could you please enable the logs? (See [Loggin](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging)

**Comment by dmcweeney** [comment]
Hi @jmprieur ,

> Also, the token that comes to your web API should have the new claims, and therefore force refresh is definitively not needed in the web API.

Understood will remove it... (it was an expermint really)

> Would you have used AcquireTokenSilent before calling AcquireTokenOnBehalfOf ? (you shouldn't as AcquireTokenOnBehalfOf handles the cache itself)

No definitely not

> logs as requested...

At this point the user hs consented to the additional scopes Sites.Read.All and Files.ReadWrite.All from the Teams client. 
Control has returned to our client side code which has issued an api call to our backend. 
Our backend code is checking for the necessary scopes by calling AcquireTokenOnBehalfOf.
The following is the log output from that call.
I have scrubbed client-id and tenant-id but other ids are intact.

Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] MSAL MSAL.NetCore with assembly version '4.29.0.0'. CorrelationId(210de617-bfed-48b8-a234-fd5233728a72)
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] === OnBehalfOfParameters ===
SendX5C: False
ForceRefresh: True

Information: (True) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] 
=== Request Data ===
Authority Provided? - True
Client Id - {my-client-id}
Scopes - Sites.Read.All Files.ReadWrite.All
Redirect Uri - https://localhost:44348/teams/auth-end
Extra Query Params Keys (space separated) - 
ClaimsAndClientCapabilities - 
Authority - https://login.microsoftonline.com/{my-tenant-id}/
ApiId - AcquireTokenOnBehalfOf
IsConfidentialClient - True
SendX5C - False
LoginHint - 
IsBrokerConfigured - False
HomeAccountId - 
CorrelationId - 210de617-bfed-48b8-a234-fd5233728a72

Information: (True) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] === Token Acquisition (OnBehalfOfRequest) started:
	Authority: https://login.microsoftonline.com/{my-tenant-id}/
	Scope: Sites.Read.All Files.ReadWrite.All
	ClientId: {my-client-id}
	
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] [Region discovery] WithRegion not configured.
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True. 
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] [Instance Discovery] The network provider found an entry for login.microsoftonline.com. 
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] Resolving authority endpoints... Already resolved? - TRUE
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] Skipped looking for an Access Token in the cache because ForceRefresh or Claims were set. 
Information: (True) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:52 - ] [HttpManager] Sending request. Method: POST. URI: https://login.microsoftonline.com/{my-tenant-id}/oauth2/v2.0/token. 
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:53 - ] [HttpManager] Received response. Status code: BadRequest. 
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:53 - ] Response status code does not indicate success: 400 (BadRequest). 
Warning: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:53 - ] Request retry failed.
Information: (False) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:53 - ] HttpStatusCode: 400: BadRequest
Error: (True) MSAL 4.29.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [05/07/2021 16:11:53 - ] MSAL.NetCore.4.29.0.0.MsalUiRequiredException: 
	ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS65001: The user or administrator has not consented to use the application with ID '{my-client-id}' named 'My Teams Client [localhost]'. Send an interactive authorization request for this user and resource.
Trace ID: 4638b849-929c-4acf-b472-fea2e9c32600
Correlation ID: 210de617-bfed-48b8-a234-fd5233728a72
Timestamp: 2021-05-07 16:11:52Z
	StatusCode: 400 
	ResponseBody: {"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID '{my-client-id}' named 'My Teams Client [localhost]'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 4638b849-929c-4acf-b472-fea2e9c32600\r\nCorrelation ID: 210de617-bfed-48b8-a234-fd5233728a72\r\nTimestamp: 2021-05-07 16:11:52Z","error_codes":[65001],"timestamp":"2021-05-07 16:11:52Z","trace_id":"4638b849-929c-4acf-b472-fea2e9c32600","correlation_id":"210de617-bfed-48b8-a234-fd5233728a72","suberror":"consent_required"} 
	Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 210de617-bfed-48b8-a234-fd5233728a72
x-ms-request-id: 4638b849-929c-4acf-b472-fea2e9c32600
x-ms-ests-server: 2.1.11654.25 - WEULR2 ProdSlices
x-ms-clitelem: 1,65001,0,,
Set-Cookie: fpc=AlHqbP-hanFHsvQUyzD5T97_lgHZBAAAAGNdJ9gOAAAA; expires=Sun, 06-Jun-2021 16:11:52 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Fri, 07 May 2021 16:11:52 GMT

**Comment by jmprieur** [comment]
The exception tells you that there was no admin consent for the web API to call the downstream API:

AADSTS65001: The user or administrator has not consented to use the application with ID '{my-client-id}' named 'My Teams Client [localhost]'. Send an interactive authorization request for this user and resource

Do you create client ids and app registration on the fly?

**Comment by dmcweeney** [comment]
@jmprieur 

> Do you create client ids and app registration on the fly?

No - definitely not. I've also double checked the correct client id and tenant id is being used and they are the same as those being used in the inc consent flow on the client.

Its back to the timing of this call - a short time later (30 secs) it works - all params are the same - client id, tenant id, scopes...

**Comment by jmprieur** [comment]
@hspin would you have an idea? It seems that @dmcweeney is experiencing a transient AADSTS65001 ?

**Comment by dmcweeney** [comment]
@jmprieur should I raise this in the ACP Advisors forums?

**Comment by jmprieur** [comment]
I guess I should know, @dmcweeney, but what is it?

**Comment by dmcweeney** [comment]
@jmprieur  The id dev advisors on yammer

**Comment by jmprieur** [comment]
@dmcweeney, yes. Go ahead. @hpsin will answer, but he's OOF

**Comment by jmprieur** [comment]
@hpsin nice reminder :)

**Comment by hpsin** [comment]
Thanks @jmprieur ! This is perhaps a better question for @psignoret , but I can predict the answer - yes, there's a propagation delay between the app getting the consent and the various layers of caching in between the token issuance service and the consent database.  This is a known, at this time unsolvable issue in Azure AD.

**Comment by dmcweeney** [comment]
@hpsin thanks for the confirmation. That is pretty much what I suspected... sleep it is!

**Comment by psignoret** [comment]
@dmcweeney A bit late to the conversation, but just confirming what @hpsin says: the replication delays here are not ideal, but currently expected. We're looking into what options we have to reduce the delay here, but we don't have anything concrete to share yet.

**Comment by dmcweeney** [comment]
@psignoret thanks for the confirmation.
