### ISSUE TITLE
[Bug] (ws2019 adfs) Unexpected character encountered while parsing value: <. Path '', line 1, position 1.  (hresult: -2146233088)

### ISSUE THREAD

**Issue by karezza** [AzureAD/microsoft-authentication-library-for-dotnet#2620]
**Which Version of MSAL are you using ?**
- ~nuget package Microsoft.Identity.Client.Extensions.Msal v2.18.4~
- nuget package Microsoft.Identity.Client v4.31.0
- .net core 5.0
- c# via visual studio 2019

**Platform**
Windows 10 Enterprise, ADFS on Windows Server 2019

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [X] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

**Is this a new or existing app?**
Implementing a new app and trying to use the latest technique this time w/ MSAL, rather than older technique.  It is known the ADFS setup and values that I'm passing in work as they work in other projects and via a mobile app connected via a VPN.  (The older projects use ```Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext``` and the mobile app uses ```flutter_appauth ^0.9.2+6```, which is a wrapper around Android AuthApp.  Both the IdentityModel & AuthApp are able to use the existing AD FS setup.  Note:  The mobile app required the additional 'resource' parameter which I've done here as well just in case it is needed.)

**Note**
The error occurs at (1).

**Repro**

```c#
    public class Authenticate
    {
        public static async Task<string> GetOpenIdToken()
        {
            string ADFSBaseAddress = "https://dc.internal.net/adfs";
            string ClientID = "1a2b1a2b-1a2b-1a2b-1a2b-1a2b1a2b1a2b";
            string RedirectUri = "xyz.domain.app://";

            string token = string.Empty;

            IPublicClientApplication app = PublicClientApplicationBuilder.Create(ClientID)
                    .WithAdfsAuthority(ADFSBaseAddress)
                    .WithRedirectUri(RedirectUri)
                    .WithExtraQueryParameters(new Dictionary<string, string> { { "resource", HttpUtility.UrlEncode(RedirectUri) } })
                    .Build();

            IEnumerable<IAccount> accounts = await app.GetAccountsAsync();

            string[] scopes = new string[] { "openid", "profile" };
            AuthenticationResult result = null;
            try
            {
                result = await app.AcquireTokenSilent(scopes, accounts.FirstOrDefault())
                            .ExecuteAsync();
            }
            catch (MsalUiRequiredException ex)
            {
                try
                {
                    result = await app.AcquireTokenByIntegratedWindowsAuth(scopes)
                                .ExecuteAsync();
                }
                catch (Exception e)
                {
                    Console.WriteLine("(1) msal: " + e.Message +", code: "+ e.HResult);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("(2) msal: " + e.Message +", code: "+ e.HResult);
            }

            if (result != null)
            {
                token = result.AccessToken;
            }
            
            return token;
        }
    }
```

**Expected behavior**
Expected to get an openid token.

**Actual behavior**
Exception: ```Unexpected character encountered while parsing value: <. Path '', line 1, position 1.```, HResult = -2146233088

**Possible Solution**
(1) I saw in a posting a couple years old a similar error and an explanation that this was expected behavior, flow not supported.  Not sure if this is the same issue, though the error message is the same.  The documentation seems to be telling me MSAL will work with a local windows domain and adfs ([MSAL connects directly to AD FS](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-adfs-support)).  No?  If this is expected behavior, what should I be doing instead?

(2)   I saw a posting online that says the error below in 'Troubleshooting 2' was fixed in his POST by changing something like "SAML" to be "Saml".  I've since be unable to find the link again.  Could this be it?

---
**Troubleshooting 1**
When I used adfs via my mobile app using these same clientid/adfsbaseaddress/redirecturi I had to add a 'resource' parameter to get it to work. As a troubleshooting step, in case "resource" is also needed here, I attempted to do so in the same way via ```.WithExtraQueryParameters(new Dictionary<string, string> { { "resource", HttpUtility.UrlEncode(RedirectUri) } })``` as well as with just a string (and not the dictionary). Still getting the same error message.

**Troubleshooting 2**
I can see the following error in the AD FS log whenever I try to get a token, Event ID: 364.  From what I've found googling this I can eliminate 1) there is no time sync issue, 2) the certificate should be fine, I can browse to https://dc.internal.net/adfs/oauth2/token and it shows the certificate as valid.
```c#
Exception details: 
Microsoft.IdentityServer.RequestFailedException: MSIS7065: There are no registered protocol handlers on path /adfs/oauth2/token to process the incoming request.
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)
```

**Troubleshooting 3**
Though it seems completely unrelated I enabled this as well since I'm running out of ideas.  No improvement, same error msg.
```powershell
PS C:\Windows\System32> Get-AdfsProperties | fl *idpinitiatedsignon*

RelayStateForIdpInitiatedSignOnEnabled : False
EnableIdpInitiatedSignonPage           : True
```

**Troubleshooting 4**
Tried adding ```.WithUsername(<user>@<domain>)```, still getting same error.

**Troubleshooting 5**
Confirmed able to get token using PowerShell w/ ADAL & .net45.  Would really prefer not to roll the whole project back to older .net version to use ADAL.

**Troubleshooting 6**
As a temporary work around tried using AcquireTokenByUsernamePassword, which works, and can use the token to access a webapi but the HttpContext.User.Identity.Name is not getting set on the webapi side, even if I change the Audience to "urn:microsoft:userinfo".

**Comment by karezza** [comment]
When I used this via my mobile app I had to add a 'resource' parameter to get it to work.  As a troubleshooting step, in case "resource" is also needed here, I attempted to do so in the same way via ```.WithExtraQueryParameters(new Dictionary<string, string> { { "resource", HttpUtility.UrlEncode(RedirectUri) } })```, as well as with just a string (and not the dictionary).  Still getting the same error message.

**Comment by karezza** [comment]
I can see the following error in the AD FS log whenever I try to get a token, Event ID: 364

```
Exception details: 
Microsoft.IdentityServer.RequestFailedException: MSIS7065: There are no registered protocol handlers on path /adfs/oauth2/token to process the incoming request.
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)
```

From what I've found googling this I can eliminate 1) there is no time sync issue, 2) the certificate should be fine, I can browse to https://dc.internal.net/adfs/oauth2/token and it shows the certificate as valid

**Comment by karezza** [comment]
Here are some EventIDs from an enabled tracing log:
![adfs_tracing](https://user-images.githubusercontent.com/17791101/118174738-6dc1c000-b3ec-11eb-9fbb-8f836e4903f2.png)

**Comment by karezza** [comment]
I've begun investigating alternative technologies such as keycloak but I would rather just keep using this microsoft solution.  I figure its probably just an additional setup step in the move to MSAL from ADAL.  Continuing to watch this ticket.

**Comment by karezza** [comment]
Any troubleshooting I can do for you to help out?

**Comment by jmprieur** [comment]
@trwalke can you please have a look at this one?
@maliksahil would you please be able to help?

**Comment by bgavrilMS** [comment]
Hi @karezza - thank you for the very detailed issue. We've also had a recent report of this issue internally. 

Sadly, IWA [is simply disabled](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/e7fd6b8abfdb63dcf2aaa460aeec3616b40ba3ea/src/client/Microsoft.Identity.Client/Internal/Requests/IntegratedWindowsAuthRequest.cs#L54) when the authority is pure ADFS. Back when we did the work to add ADFS 2019 support to MSAL, I think we were playing with preview ADFS bits and IWA support was not there.

We are going to review our implementation of IWA soon, I have a tracking issue: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2731

All of this aside, please note that browser based auth is the more stable method of authentication. As an alternative to logging in the "current windows user", you can also use the windows broker to achieve this, see https://aka.ms/msal-net-wam

**Comment by karezza** [comment]
Thank you, understood.

**Comment by trwalke** [comment]
Issue tracking here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2771

**Comment by bgavrilMS** [comment]
We have improved the error message and will continue to track the feature request of supporting IWA in ADFS via #2771. 
Closing this.

**Comment by bgavrilMS** [comment]
As an alternative, please try to use WAM - see https://aka.ms/msal-net-wam
