### ISSUE TITLE
[Feature Request] [2L 5S] OBO to perform refresh_token flow

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2623]
Change OBO as per https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?version=GBdev&path=%2FConfidentialClient%2FOBO.md

- [x] add user_assertion_hash to RT as well as AT [S]
- [ ] change OBO logic to perform refresh_token flow [L]
- [ ] in refresh_token flow, only use RT associated with user_assertion_hash [S]
- [x] E2E Test: OBO with expired AT and valid RT in cache [L]
- [x] E2E Test: OBO with expired AT and missing RT in cache [S]
- [x] E2E Test: OBO with expired AT and RT not associated with user_assertion_hash in cache [S]
- [ ] Test that this is not a breaking change, i.e. GetAccounts / AcquireTokenSilent behave as expected [S]

See also: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2558 for the scenario

**Comment by bgavrilMS** [comment]
Will resolve issues #2447 #2558

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/microsoft-identity-web/issues/441
