### ISSUE TITLE
[Feature Request] MSAL Service Exception should expose error codes

### ISSUE THREAD

**Issue by michaelrm97** [AzureAD/microsoft-authentication-library-for-dotnet#2627]
**Is your feature request related to a problem? Please describe.**
ADAL exposes AAD error codes which our service uses to determine the reason for failures. Migrating from ADAL to MSAL requires us to manually parse the response body

**Describe the solution you'd like**
Expose the error codes like in ADAL and as it is done internally.

```CSharp
class MsalServiceException
{
 // ... other members

 /// <summary>
 /// Exposes the error codes collection
 /// </summary>
 IEnumerable<string> ErrorCodes {get;}
}
```

**Describe alternatives you've considered**
Manually parsing response body

**Additional context**

**Comment by bgavrilMS** [comment]
The AAD service was historically against this because they cannot guarantee that these error codes do not change. I.e. error codes would become part of the "public API" / service interface.

**Comment by jmprieur** [comment]
@hpsin do you agree that we shouldn't expose ErrorCodes in the MsalServiceException?

**Comment by hpsin** [comment]
The errors contain a code field, so it's OK to expose that (ie no parsing required, just return what's already parsed out in the JSON response). However, we should make it clear that this is for telemetry purposes only. Can you confirm that the error type (ie integration_required) is already made available? That's the thing people need to code against.

**Comment by bgavrilMS** [comment]
Yes, error code is made available via `MsalException` https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/01b6180a40bb2704a587a958633b4cf5b8aab690/src/client/Microsoft.Identity.Client/MsalException.cs#L96

**Comment by bgavrilMS** [comment]
@michaelrm97 - what error codes (suberrors) do you handle ?
