### ISSUE TITLE
[Documentation] [L] MSAL Documentation Refresh

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2632]
We need to update the documentation for MSAL before the next MS Build conference.
The documentation will be divided up amongst team members to ensure everything is up to date with the latest MSAL feature set. 
Please add any missing information that you are aware of and remove the documentation that references MSAL 2. Everything should be focused on MSAL 4 and the migration from ADAL to MSAL 4.

Bogdan
- [x] Complete
![image](https://user-images.githubusercontent.com/30090357/118425233-9b716800-b67d-11eb-8d34-ca2e7603eb82.png)

Jenny
- [x] Complete
![image](https://user-images.githubusercontent.com/30090357/118425297-c0fe7180-b67d-11eb-97ec-255167a580cd.png)

Neha
- [x] Complete
![image](https://user-images.githubusercontent.com/30090357/118425492-25b9cc00-b67e-11eb-8c2e-4a0eff3969c1.png)

Sameer
- [x] Complete
![image](https://user-images.githubusercontent.com/30090357/118425605-5e59a580-b67e-11eb-81e5-fef78d355b06.png)

Peter
- [ ] Complete
![image](https://user-images.githubusercontent.com/30090357/118425676-877a3600-b67e-11eb-962d-b68605e438b8.png)

Travis
- [x] Complete
![image](https://user-images.githubusercontent.com/30090357/118425761-aed10300-b67e-11eb-90eb-8f75614d5845.png)

**Comment by jennyf19** [comment]
I think these are the pages that need to be updated:

remove reference to 2x/3x in these pages: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication 


https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-Tokens#iaccount-msal-2x
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-Tokens#iuser-msal-1x
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#adalnet-v2x-migration-to-msalnet-v3x

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/clearing-token-cache

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#iaccount-not-iuser

 https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#using-the-builders-to-instantiate-an-app (lots of stuff here w/3x reference)

 remove part on msal.net 2.0-preview here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#you-can-also-enable-embedded-webviews-in-xamarinios-and-xamarinandroid-apps

 remove 3x references: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Testing-an-app-using-MSAL#unit-testing

remove 1.x reference: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Token-cache-serialization#custom-token-cache-serializers-for-msalnet

Update table, xamarin supports device code:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-Tokens#summary-for-public-client-applications

do we need this page? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/hololens2

Remove? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Telemetry

**Comment by jmprieur** [comment]
- In https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token, I've updated the text, as in CCA, AcquireTokenSilent should not be called before the AcquireTokenForClient, AcquireTokenByAuthorizationCode, AcquireTokenOnBehalfOf. For ASP.NET Core customers should really use Microsoft.Identity.Web

**Comment by jmprieur** [comment]
- [ ] In https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/known%20issues#systemsecuritycryptographycryptographicexception-a-device-attached-to-the-system-is-not-functioning, do we still need the known issue for crypto?

**Comment by bgavrilMS** [comment]
No, it was fixed. I deleted the entry.

**Comment by jennyf19** [comment]
all items are done. closing.
