### ISSUE TITLE
[Bug] Get token for client with ADFS throws null ref due to TokenType

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2636]
Throws a null ref  in `GetKey()` on the TokenType being null when trying to save the access token.

not sure if related:
Also, the tenantId when using ADFS is null, so the cache key is missing the tenantId, and looks like the following: 
`567794c8-a349-4ye3-672a-9947accbde95__AppTokenCache`

and this is the authority: `https://127.0.0.1/adfs/` 

See this [line](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0d53f3e80e29f9c6d172e069c10e02d71e24f65e/src/client/Microsoft.Identity.Client/Cache/SuggestedWebCacheKeyFactory.cs#L68).

**Comment by mancyc** [comment]
[msal_Vervose_logs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6496909/msal_Vervose_logs.txt)

I saw this issue with latest Msal 4.30.1 as well as 4.28.1.
Attached verbose logging output

**Comment by bgavrilMS** [comment]
For the null ref, it is probably an old version of ADFS. We have integration tests with ADFS 2019 and token_type is present in the response. Can someone confirm the version of ADFS used?

For the cache key observation - ADFS was designed to be single-tenant, you can't have more than 1 tenant per ADFS server, so tenant_id is indeed null and the cache key looks ok.

**Comment by jennyf19** [comment]
not a P1, ADFS set up issue, but still a bug in MSAL.

**Comment by mancyc** [comment]
@bgavrilMS We are using WS2019, so ADFS version is 2019. I will check with ADFS team to check the setup on why it is returning empty fields in the token request
