### ISSUE TITLE
[Feature Request] Expose AuthenticationResult.TokenType with MSAL.NET

### ISSUE THREAD

**Issue by hkuadithya** [AzureAD/microsoft-authentication-library-for-dotnet#2637]
We are migrating some legacy code in our projects from ADAL to MSAL.

Both ADAL and MSAL return an object of type `AuthenticationResult` after acquiring an access token.

* ADAL: [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationresult?view=azure-dotnet)
* MSAL: [Microsoft.Identity.Client.AuthenticationResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult?view=azure-dotnet)

In our older code path, we rely on the type of ADAL access token i.e. `AuthenticationResult.AccessTokenType` to set the scheme in [AuthenticationHeaderValue](https://docs.microsoft.com/en-us/previous-versions/visualstudio/hh193878(v=vs.118)) for making another request.

```
new AuthenticationHeaderValue(
    scheme: firstPartyAuthResult.AccessTokenType,
    parameter: firstPartyAuthResult.AccessToken);
```

MSAL's [AutenticationResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult?view=azure-dotnet&viewFallbackFrom=azure-dotnet) does have `AccessToken` but it **doesn't** seem to have `AccessTokenType` (correct me If I'm wrong). 

How do I determine the `AccessTokenType` for a MSAL auth result? Please don't suggest hardcoding the scheme to `Bearer`. Thanks in advance.

SO thread mirroring this issue: https://stackoverflow.microsoft.com/questions/258737

**Comment by hkuadithya** [comment]
@bgavrilMS could you provide a timeline for the release of MSAL.NET `4.32`? Is there a link I can refer to for checking the release timelines?

**Comment by jennyf19** [comment]
@hkuadithya should be in 1-2 weeks.
