### ISSUE TITLE
[Bug] .NET Framework and Angular 10 Flow

### ISSUE THREAD

**Issue by alexandruIonutZ** [AzureAD/microsoft-authentication-library-for-dotnet#2644]
Client App : Angular 10
Backend : .Net Framework 4.7.2

The flow I need is as follows. The user authenticates in the Web application (Angular), the response token is sent to the API, the API saves it in the database and based on it, it has access to the User's Calendar Events. Each time the user returns to the application, the API returns the calendar data based on this "refresh token" and user don't need to reauthenticate. What flow should I use? I don't found any similar model.

**Comment by bgavrilMS** [comment]
You use the authorization code flow. When the user needs to login, you redirect them to the IDP. 

What do you use on the backend? ASP.NET classic?

**Comment by alexandruIonutZ** [comment]
Thanks for the reply @bgavrilMS . I figured it out it's about an On-Behalf-Of flow.
I use MSAL Angular v2 with scopes: 'api://xxxx-xxxx-xxxx-xxxx/Calendars.ReadWrite','openid'  to receive an accessToken,
I send the access token to the API and i receive AADSTS70000 error.
![image](https://user-images.githubusercontent.com/84448936/119118586-05e62780-ba33-11eb-99c1-6c79ab8d62ef.png)

Scopes on SPA:
![image](https://user-images.githubusercontent.com/84448936/119118980-6a08eb80-ba33-11eb-86ad-40606b834c07.png)

Scopes on API:
![image](https://user-images.githubusercontent.com/84448936/119119240-b05e4a80-ba33-11eb-80e8-d0d89d143dfa.png)

Scopes defined by the API are exposed:
![image](https://user-images.githubusercontent.com/84448936/119119155-9cb2e400-ba33-11eb-95ea-edc7c5cb6423.png)

And known Client Applications are linked to SPA aplication.
![image](https://user-images.githubusercontent.com/84448936/119119468-e3a0d980-ba33-11eb-8cfe-5efdb1bed89c.png)

Where is the problem?

**Comment by alexandruIonutZ** [comment]
And if i replace scope of the SPA ''api://xxxx-xxxx-xxxx-xxxx/Calendars.ReadWrite'' with "api://xxxx-xxxx-xxxx-xxxx/.default" the request return this error:
![image](https://user-images.githubusercontent.com/84448936/119128062-cffa7080-ba3d-11eb-9e62-44d268aecabf.png)

**Comment by bgavrilMS** [comment]
@jmprieur @jennyf19 - do you have any guidance with this? a web API backend with Angular frontend is a pretty common setup.

I am not sure if this is the right approach (getting a token from the frontend as a SPA), but I'll let the others comment on this. For now, let me summarize what I think you've done: 

1. Front end - Angular SPA. Asks for a token for your backend service, scope <my_api>. This works.
2. Web API gets the token, and validates it. You have to have to validate with a library like 
3. You Web API now has to call a downstream web API (graph). The app registration steps required for this are detailed in this sample:
 
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph#register-the-service-app-todolistservicems-identity-dotnet-native-aspnetcore-v2

Note that in the sample we're using 2 different clientIDs, one for the app (in the sample it's a WPF desktop app, you have an SPA) and one for the "service".

**Comment by alexandruIonutZ** [comment]
Hi @bgavrilMS .
We solved the problem like this:
In the Angular application I make the request "https://login.microsoftonline.com/common/oauth2/v2.0/authorize" which returns a code to me and i send it to the WebAPI.

With this code I make in my "WebAPI" the request "/ token" which returns an access_token and a refresh_token.
Every time the user enters the application I check in the API if the access_token is valid, if is not valid, i take another one based on the refresh_token.

The question is whether the refresh_token is valid for 24 hours or for 90 days?

Here it is specified that the token is valid for 24 hours in the SPA: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

Here it is specified that the token is valid for 90 days: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes

**Comment by bgavrilMS** [comment]
Yes, this strategy would work, possibly better than OBO. It is similar to what a framework like ASP.NET (Core) does behind the covers. 

To answer your questions: 

- refresh token validity is 90 days by default
- You no longer use the SPA flow. SPA means that the front-end gets the token. You are now using the authorization flow. So 90 days will apply. 
- a tenant admin or AAD might revoke the refresh token before expiry (for example for security reasons, or if the tenant admin adds more stringent rules such as MFA). If this happens, when you try to get a new access token via the refresh_token flow, you'd get an error code of "interaction_required" or "invalid_grant". This means that the user needs to login again and your web app should redirect them to the login page.

 Please note that you can use MSAL to handle some of this complexity for you: 

1. You can have MSAL exchange the authorization code for a token for you using `AcquireTokenByAuthorizationCode`. This will also cache the access token / refresh token for you.
1. You can have MSAL smartly give you a token from its token cache, see `AcquireTokenSilent` . If a non-expired access token is not found, MSAL will perform the refresh_token flow for you.
1. You can have MSAL craft the authorization URL for you like [this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/fac5d52f802de1c523c734b349a8e39c7d65a9f3/tests/Microsoft.Identity.Test.Integration.NetFx/HeadlessTests/ConfidentialClientIntegrationTests.cs#L100) (you don't need the actual secret)

Irrespective of you using MSAL or not, you need to think about caching the tokens.  This should be done on a per-session basis, as your front end will know about a returning user. We can follow up when you get to this point.

**Comment by jmprieur** [comment]
@alexandruIonutZ @bgavrilMS did you look at this sample: https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/7-AdvancedScenarios/1-call-api-obo/README.md ?

**Comment by alexandruIonutZ** [comment]
Thanks for the answer, @bgavrilMS and @jmprieur  !

@jmprieur , this example led to the error detailed above: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2644#issuecomment-845834720

@bgavrilMS Refresh token expire 90 days after the aquisition or after the last refresh token flow?
Is there any way we can keep the token active for more than 90 days?

**Comment by bgavrilMS** [comment]
Every time you contact AAD for tokens, they will give you back a "fresh" RT. So as long as your user comes back to the app sometimes in the 90 days, the re-login experience will be silent. Or another way of saying this is that the RT has a 90 days **rolling** expiration windows.

**Comment by alexandruIonutZ** [comment]
@bgavrilMS , thank you for the quick response.
Ok, i understand. I use this function to refresh the access token and the response contains just the access_token and not the RT.
![image](https://user-images.githubusercontent.com/84448936/119344825-ce7cb280-bca0-11eb-9a19-074b9151b9b4.png)

I need to silent acquire a new RT or the existing RT has the expire period extended?

**Comment by bgavrilMS** [comment]
You need to add "offline_access" special OAuth2 scope for the response to contain an RT.

It's great that you are making process on this using a vanilla / make your own http requests approach, and since AAD is OAuth2 / OpenIdConnect certified, you can use any low level library or create your own requests. 

But please be mindful of security and complexity. MSAL may be a bit harder to use, but now you have to deeply understand things like refresh token flows etc. "guest" scenarios, where a user from one org can be a guest in other organizations will likely not work for you. Security wise, it is recommended that you use PKCE to protect against man in the middle attacks and move to use a certificate instead of a secret.

**Comment by alexandruIonutZ** [comment]
Thank's @bgavrilMS .
Working now.
