### ISSUE TITLE
Design and add monitoring flags for global stats

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2646]
- [x] tokens obtained by MSAL (for entire process)
- [x] tokens obtained by MSAL via cache (for entire process)
- [x] time spent in MSAL (per process) - includes HTTP and cache times
- [x] <s>Azure region detected (expose in auth result metadata)</s> Separate issue for this.

Should be exposed in AuthenticationResult.AuthenticationResultMetadata and via telemetry.
For the entire process = for the whole life of MSAL, i.e. use static counters. 

- [x] Create API Review doc

**Comment by bgavrilMS** [comment]
As a follow up from MyApps - CC @henrik-me @jennyf19

**Comment by pmaytak** [comment]
> * [ ]  time spent in MSAL (per process) - includes HTTP and cache times
This is the same as `DurationTotalInMs`? So just add it to telemetry?
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/963a2641edc71381e2b72c54a30ae629a2d3cf45/src/client/Microsoft.Identity.Client/AuthenticationResultMetadata.cs#L30

**Comment by bgavrilMS** [comment]
`DurationTotalInMs` is the time that the current request took. The one you're designing is a "total" time. Essentially a static counter where you add up each individual request duration.
