### ISSUE TITLE
Is there an ability to skip the attribute collection page after signing in with social login ?

### ISSUE THREAD

**Issue by kberawala** [AzureAD/microsoft-authentication-library-for-dotnet#2653]
I have enabled social login with facebook, google  and apple.

on submitting for review apple asked to remove the additional step that collects the additional attributes after sign-in with apple. In general, we are not collecting the additional attributes other than email/firstname and lastname which is already part of the token.

Is it possible to skip the attribute collection page, so user can simply sign in the app ? 

![image](https://user-images.githubusercontent.com/13636878/119285540-99169b80-bc85-11eb-99c1-5b819e09de67.png)

**Comment by bgavrilMS** [comment]
@kberawala - this SDK is only responsible for acquiring tokens. We do not control the flow of authentication, web content, claims etc. 

I don't know the answer to your question. I suggest you open an issue on the service directly, from the Azure Portal.
