### ISSUE TITLE
[Feature Request][L] MAUI/.NET 6.0 preview builds

### ISSUE THREAD

**Issue by rbanks54** [AzureAD/microsoft-authentication-library-for-dotnet#2655]
In attempting to build a .NET 6.0/MAUI app on Android, there are reports of being unable to use the BrowserTabActivity as it is only included in MonoAndroid builds.

This discussion covers it in a little more detail: https://github.com/dotnet/maui/discussions/1034

Are there plans to produce preview builds of the MSAL library for use with .NET 6/MAUI?
If not, can you produce one or suggest a short term workaround that doesn't involve forking the code 😄?

**Comment by jmprieur** [comment]
@rbanks54 : do you have recommendations on how you'd work around / fix this?

**Comment by rbanks54** [comment]
In terms of workarounds.... I'm a little out of ideas, which is why I'm asking 😄 

All I can come up with as options is:
* fork the code and try to do it myself (not a good long term option)
* find another OAuth client library and see if I can get it working with MAUI

**Comment by jmprieur** [comment]
Let's get back to you on this one.
BTW, we accept contributions :)

**Comment by trwalke** [comment]
Might be a good idea to ask the Xamarin Android team what their recommendation is on this.
@jmprieur

**Comment by pmaytak** [comment]
I was able to repro the issue and found a way that works. I think this is related to Visual Studio versions 2019 Preview vs 2022 Preview. I added MSAL NuGet reference to the [HelloMaui](https://github.com/dotnet/maui-samples/tree/main/HelloMaui) Android project. When I built the project with VS 2019, it pulled netcoreapp2.1 MSAL binary (which doesn't have the Android stuff). When I built with VS 2022, it pulled the correct monoandroid binary and built the project successfully. I wasn't able to find any existing VS or Maui bugs logged related to this, though.

Can you try with VS 2022 to see if it works for you?

I used VS 2019 (16.11.0 Preview 3.0) and VS 2022 (17.0.0 Preview 2.1) for this.

For reference [Net6.0 precedence rules](https://github.com/terrajobst/designs/blob/main/accepted/2021/net6.0-tfms/net6.0-tfms.md#compatibility-rules)

**Comment by rbanks-willow** [comment]
I wonder if this was a behaviour change between the preview 5 & 6 SDKs? Regardless, the code now compiles and BrowserTabActivity can be referenced, so let's call this issue closed 😊

Thanks!

**Comment by pmaytak** [comment]
Possibly. I did only test with .NET 6 Preview 6 SDK.
