### ISSUE TITLE
[Bug] AcquireToken* methods provide a token that includes scopes that were not requested.

### ISSUE THREAD

**Issue by Rick-Kirkham** [AzureAD/microsoft-authentication-library-for-dotnet#2661]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.30.0 

**Platform**
.NET 4.8

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [x ] Authorization code
    * [x ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

This is a new app or experiment.

**Repro**

```csharp
string[] graphScopes = { }; //{ "https://graph.microsoft.com/Files.Read.All" };

            // Get the access token for Microsoft Graph.
            AcquireTokenOnBehalfOfParameterBuilder parameterBuilder = null;
            AuthenticationResult authResult = null;
            try
            {
                parameterBuilder = cca.AcquireTokenOnBehalfOf(graphScopes, userAssertion);
                authResult = await parameterBuilder.ExecuteAsync();
            }
```

THE SAME SYMPTOMS HAPPEN WITH AcquireTokenByAuthorizationCode .

**Expected behavior**
The returned access token has only the MS Graph scope requested: Files.Read.All  (in addition to basic AAD scopes, like profile).

**Actual behavior**
In addition to the Graph scope that is requested, the token scopes include additional Graph scopes that were requested (and consented to by the admin) when the web application was registered in Azure AD portal. For example, Mail.Read was requested when the app was registered (and consented to by the admin) in the portal and it is included in the access token even though it is not requested in the graphScopes parameter of AcquireToken*. 

**Possible solution**
Is it expected that the access token will include all scopes that were requested when the web app was registered in AAD (and consented to by the admin)? If so, is it correct to say that the graphScopes parameter is only used to request additional scopes "on the fly"? 

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@Rick-Kirkham: yes, the access token accumulates the scopes (for a given resource). Passing-in scopes parameters ensures that the access token you'll get will have them, but it might be that in the cache a token already have them all.
AzureAD decides what scopes to return when requesting a token using a refresh token.

**Comment by bgavrilMS** [comment]
As @jmprieur states , it is an optimization that AAD does in order to minimize the number of HTTP calls made by an app to AAD.
