### ISSUE TITLE
[Bug] Inconsistency in whether a scope must be passed to AcquireToken* methods. 

### ISSUE THREAD

**Issue by Rick-Kirkham** [AzureAD/microsoft-authentication-library-for-dotnet#2662]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.30.0

**Platform**
.NET 4.8

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ x] Authorization code
    * [x] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

This is a new app or experiment.

**Repro**

```csharp
parameterBuilder = cca.AcquireTokenOnBehalfOf(graphScopes, userAssertion); //graphScopes cannot be empty array

ELSEWHERE IN THE CODE:

var authResultBuilder = clientApp.AcquireTokenByAuthorizationCode((graphScopes,  // graphScopes can be empty
				Request.Params["code"]  
			);
```

**Expected behavior**
For complicated reasons, the web app uses On Behalf Of in some scenarios, but uses Auth Code flow in certain other scenarios. I expect the same restrictions on the graphScopes parameter for both AcquireTokenOnBehalfOf and AcquireTokenByAuthorizationCode. 

**Actual behavior**
You can pass an empty array for the graphScopes parameter to AcquireTokenByAuthorizationCode without error (in which case the returned token includes only scopes that were previously consented to by the admin in the AAD portal), but if you pass an empty array to AcquireTokenOnBehalfOf, there is an error saying that you have to request at least one scope. 

**Possible solution**
Is this inconsistency intentional or is it a bug in AcquireTokenOnBehalfOf? 

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@Rick-Kirkham 
- When you use AcquireTokenByAuthorizationCode (part of the sign-in process), you really ask MSAL.NET to redeem the code, and add the resulting token to the token cache. It's ok not to ask for scopes as this is usually done in the Startup.cs or equivalent, that is at sign-in, and not in the controllers. That is the access token (and the refresh token) will be available in the MSAL.NET cache for use in various controllers and controller actions that will request a token for one or another API (and this token will be already in the cache or not, in which case the refresh token will be used to get a token for a different API / scopes).

- On the contrary, OBO is used on the controller action, that is you know which API to call, and you need to provide scopes for this API.

HTH.

BTW, if you are building an ASP.NET Core web app (mixed with web API obvisouly), we recommend you move to Microsoft.Identity.Web
