### ISSUE TITLE
[Feature Request] [L] Support for Windows WinUI 3 desktop apps

### ISSUE THREAD

**Issue by andrewleader** [AzureAD/microsoft-authentication-library-for-dotnet#2673]
The Microsoft.Identity.Client library doesn't support Windows WinUI 3 desktop Project Reunion apps today. I think the library is seeing the `net5.0-windows` TFM and thinking it's a WPF or WinForms app, and therefore doesn't work with a WinUI 3 app (which is neither of those).

**Describe the solution you'd like**
Microsoft.Identity.Client library works with WinUI 3 desktop apps.

**Additional context**
To reproduce...

1. First set up dev environment (install Reunion VSIX): https://docs.microsoft.com/en-us/windows/apps/project-reunion/set-up-your-development-environment
2. Then create a WinUI desktop app: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop
3. Then add the Microsoft.Identity.Client NuGet package to the app and attempt to build and run the app

**Comment by igalfsg** [comment]
Is this planned for 4.35.0?

**Comment by jmprieur** [comment]
It's going to be investigated first. We need to understand what needs to be done, @igalfsg 
If you know already, don't hesitate to provide hints.

**Comment by igalfsg** [comment]
@jmprieur I haven't looked into the library's code. However, version 4.27.1 still works with Win UI 3. That was before it was switched from the in app prompt to browser authentication so I would guess it has something to do with how that feature was implemented.

**Comment by trwalke** [comment]
The same issue seems to be open in the Microsoft.UI.XAML repo
https://github.com/microsoft/microsoft-ui-xaml/issues/5143

I also tried using VS 2022 to build but I run into the same error

**Comment by bgavrilMS** [comment]
This is most likely due to WinUI. MSAL has a tfm of `net5.0-windows10.0.17763.0` and WinUI app has `net5.0-windows10.0.19xxx`. MSAL calls into WinRT on its own.

**Comment by marb2000** [comment]
**I couldn't repro the bug**. I created a Blank C# WinUI 3 app using the Windows App SDK 0.8.1, added the MSAL.NET library, and the project was built. I got an error that does not block the build. WinUI 3 supports arm64 and I guess MASL.NET doesn't:

_There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm64'._

**Comment by trwalke** [comment]
Thanks @marb2000. Ill verify that I installed 0.8.1 and try again.

**Comment by jmiddour** [comment]
I can confirm that the behavior still remains.  I don't know if it's WinUI's issue to fix or the identity client.
I've messed with the tfms and runtime ids a _lot_, and haven't gotten a working combination with v4.35 yet running vs16.11 preview.  Though for me, the missing runtime pack is a build blocker.

**Comment by bgavrilMS** [comment]
This is unlikely to be a Microsoft.Identity.Client problem. The error comes from a targets file introduced by WinUI

`Microsoft.UI.Xaml.Markup.Compiler.interop.targets(465,9): Xaml Internal Error error WMC9999: **Operation is not supported on this platform.`

MSAL is a standard .NET library with a target on .net5-windows10.0.17763.0, which calls into WinRT APIs.

**Comment by jmiddour** [comment]
My opinion is that it is interaction issue, not an issue with one or the other inherently.

The operation being called that is not supported is System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(Guid clsid, Guid riid)
To me this suggests something in the identity client is asking for something that is not included by winui3 by default and winui3 (for some reason) is attempting to use an unsupported call to find it.  I could be misunderstanding the trace for sure.

I do not know how to determine what exactly what winui3 is missing that identity client wants.  As far as I can tell, my winui3 app targeting net5.0-windows10.0.19041.0 with a minimum version of 10.0.17763.0 is the only significant difference between the two targeting scenarios.  I have removed the win-arm64 runtime ids as I don't need to target arm64 anyway.  

I've not been able to narrow down what's going on further on my own, so any insight would be most appreciated.

**Comment by bgavrilMS** [comment]
We are discussing with the WinUI team and they are investigating. Will post updates here. We found a similar issue here: microsoft/microsoft-ui-xaml#5143

net5.0-windows10.0.19041.0 means that you want to use NET5, with general purpose Windows Features (such as WinForms), and with access to the Windows SDK version 19401
You app consumes MSAL, which is built against net5.0-windows10.0.17763.0, which means NET5 + Win SDK 177630. As far as I know (and I'm pretty sure of this) - the Windows SDKs are backwards compatible and you can see that your app correctly consumes MSAL.

**Comment by jmiddour** [comment]
I opened that issue 😄.   I'm glad both teams are working on it.  In the meantime, I'm using 4.27.1 as a workaround.  I'm not thrilled to be using an unsupported version, but that's what works at the moment.

**Comment by PaulSorauer-IPG** [comment]
So I'm using WinUI in .NET 6.0-pre (`net6.0-windows10.0.19041`) as part of the standard project template that shipped with MAUI Preview 7. It's using ProjectReunion 0.8.1.

I get a hard crash in my Startup.ConfigureServices routine when trying to build a `IPublicClientApplication` using Microsoft.Identity.Client.

Having read through this post I have tried various versions of the Microsoft.Identity.Client library:

- 4.34.1
- 4.27.1
- 4.16.1 (just for luck)
- 4.10.1 (just for luck)

None workaround the issue.

Because it's a hard crash I've been unable to catch the exception using a TRY/CATCH block.

I know most of the conversation here has revolved around compatibility with .NET 5.0 but I'm wondering if anyone has any ideas for a workaround for .NET 6.0 / MAUI Preview 7, please?

Cheers.

**Comment by jmiddour** [comment]
@PaulSorauer-IPG -- I think I might have run into the same problem you did on the hard crash.  I reported it [here](https://github.com/microsoft/microsoft-ui-xaml/issues/5673).  If this is the same, and you find a work around of any sort, please let me know!

**Comment by PaulSorauer-IPG** [comment]
> @PaulSorauer-IPG -- I think I might have run into the same problem you did on the hard crash. I reported it [here](https://github.com/microsoft/microsoft-ui-xaml/issues/5673). If this is the same, and you find a work around of any sort, please let me know!

Hi @jmiddour - I did previously come across that thread but it didn't immediately appear to be directly related. In my case, because of the hard crash, I can't get any stack trace / exception details - there's a quirk in VS2022 at the moment that doesn't allow debugging of WinUI apps, so you have to deploy and run from the desktop and then attach the debugger, which doesn't help if your app is crashing during startup. 😥

I just know it's the call to create the `IPublicClientApplication` in the service configuration because when I take it out of my app constructor there's no crash.

**Comment by hachadwick** [comment]
I am not sure if this has been stated before but, I am able to use Microsoft.Identity.Client version 4.27.1 without issue in my WINUI 3 app. If I use a version later than that, I get an build error. It appears the issue was introduced in version 4.28.0, possibly.

**Comment by hachadwick** [comment]
Will this issue/ticket be closed when the SDK is updated?

**Comment by trwalke** [comment]
Need to do basic smoke testing to ensure new preview works

**Comment by emorell96** [comment]
This has come back now with MAUI in RC1: https://github.com/dotnet/maui/issues/6052
The build fails with two errors when MSAL is added to a MAUI library. Any idea how to avoid building for arm? I have no need to support arm on windows.
```
2>C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'.
2>C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm-aot'.
```

**Comment by bgavrilMS** [comment]
This works today, there is nothing to do.

**Comment by diemperdiem** [comment]
> So I'm using WinUI in .NET 6.0-pre (`net6.0-windows10.0.19041`) as part of the standard project template that shipped with MAUI Preview 7. It's using ProjectReunion 0.8.1.
> 
> I get a hard crash in my Startup.ConfigureServices routine when trying to build a `IPublicClientApplication` using Microsoft.Identity.Client.
> 
> Having read through this post I have tried various versions of the Microsoft.Identity.Client library:
> 
> * 4.34.1
> * 4.27.1
> * 4.16.1 (just for luck)
> * 4.10.1 (just for luck)
> 
> None workaround the issue.
> 
> Because it's a hard crash I've been unable to catch the exception using a TRY/CATCH block.
> 
> I know most of the conversation here has revolved around compatibility with .NET 5.0 but I'm wondering if anyone has any ideas for a workaround for .NET 6.0 / MAUI Preview 7, please?
> 
> Cheers.

@PaulSorauer-IPG  Any luck?

**Comment by bgavrilMS** [comment]
@diemperdiem - we expect this to work. Please open a new bug if it isn't.

**Comment by bgavrilMS** [comment]
@rossirpaulo - please open a bug for this

**Comment by baskren** [comment]
For anyone coming here hoping to find a fix to the most recent (Fall 2022) incarnation of this issue:
https://github.com/microsoft/microsoft-ui-xaml/issues/5689#issuecomment-982128778

**Comment by baskren** [comment]
Here is the bug : https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3941 
Why it's closed is a mystery to me.
