### ISSUE TITLE
[Feature Request] Easier token caching

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2683]
**Is your feature request related to a problem? Please describe.**
Token caching is hard, because it involves writing a lot of boiler plate code and because of bad initial design, where a notification mechanism was used instead of an object / interface.

Microsoft.Identity.Web simplifies things this by introducing `MsalAbstractTokenCacheProvider` which deals with the complex `Before` / `After` [notifications](https://github.com/AzureAD/microsoft-identity-web/blob/8ca113676ccf8ecb465a55acfe2857ca5610ed99/src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs#L50) and focuses on `Read` / `Write` [operations](https://github.com/AzureAD/microsoft-identity-web/blob/8ca113676ccf8ecb465a55acfe2857ca5610ed99/src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs#L106):

```csharp
WriteCacheBytesAsync(string cacheKey, byte[] bytes);
Task<byte[]> ReadCacheBytesAsync(string cacheKey);
```

## Solution 1

Introduce `MsalAbstractTokenCacheProvider` in MSAL.

```csharp
IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder
    .Create("id")
    .WithClientSecret("secret")
    .Build();

// L1TokenCache can live in MSAL
MsalAbstractTokenCacheProvider adapter = new L1TokenCache(MaxSize = "2Gb");
adapter.Init(cca.AppTokenCache);

// OR RedisTokenCacheAdapter lives in Microsoft.Identity.Web
MsalAbstractTokenCacheProvider adapter = new RedisTokenCacheAdapter();
adapter.Init(cca.AppTokenCache);

```

In addition MSAL can provide several implementations out of the box: 

- a partitioned in memory cache for CCA 
- an L1  cache for CCA with eviction options (this already exists in M.I.W based on MemoryCache, but an Msal implementation is possible if using Wilson's cache with event based evictions)
- MSAL ex cache for public clients (which could move entirely in MSAL by the way)

M.I.W. can also rely on this infrastructure to make it easier to consume their token caches.

## Solution 2

```csharp

interface ITokenCacheSerialization
{ 
    void Write(string cacheKey, byte[] payload, CacheHints hints));
    byte[] Read(string cacheKey);
    void Delete(string cacheKey);
}

// then MSAL would use it as 
 IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder
    .Create(s_clientIdForConfidentialApp) // <-- can even be seen as a mandatory param for apps
    .WithTokenCacheSerialization(ITokenCacheSerialization)
    .WithClientSecret(s_confidentialClientSecret)
    .Build();
```

In MSAL 4, we keep the 2 ways of serialization. In MSAL 5, we rely exclusively on the new way - deprecate `BeforeAccess` / `AfterAccess` etc. and provide an adapter: 

```csharp

// MSAL 5 migration help
ITokenCacheSerialization seri = new CallbackAdapter() { BeforeAccess = ((notificatation) => { /* old logic */} AfterAccess= ((notificatation) => { /* old logic */} };
```

**Comment by bgavrilMS** [comment]
@jmprieur - as discussed, here's an idea of the token caching issue. Let's discuss when you have time.

**Comment by jmprieur** [comment]
Thanks @bgavrilMS.
Yes. Let's discuss.

I like solution 2. It's just that, as we discussed we'd provide 2 ways of doing the same thing for a while. But I think that's ok. This is essentially doing what Ms.Id.Web does.
- I think that the interface should be named `ITokenCacheSerializer`, not `ITokenCacheSerialization`. I even question the "Token" part. It seems to be a standard byte[] serializer if we except the CacheHints, (but are these token related, or can they be expressed more abstractly? I think we'd want to spend a bit more time on the `CacheHints` content.
- it's methods should also be async. Most cache implementation require I/Os, which therefore tend to be asynchronous. We could provide both the Async and sync methods, though (not sure)

If we chose solution 1 (which is not that different from today), wouldn't it make sense that the first part of the solution 1 be there by default (without adding a serializer)
The second part of solution 1 is a bit oversimplified for the Redis cache:
- It should really use the standard existing cache implementation of [`IDistributedCache`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.caching.distributed.idistributedcache), hence an adapter.
- It needs an L1/L2 mechanism and a retry mechanism.

**Comment by RhomGit** [comment]
There is recently a new issue with clearing the cache and multiple accounts re-appearing in the cache. Perhaps introduced in latest Windows 10 update.
Due to the timing and relevance of this thread I presume you are aware of it? Also https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2696 might be related.

If not I can open a new issue and spend some time investigating further (very busy, don't want to do this)...

**Comment by jmprieur** [comment]
@RhomGit : for which type of application ? confidential client application? or public client application? are you using WAM? do you have repro steps?

**Comment by RhomGit** [comment]
PCA. I'll open a new issue, I was hoping you knew about it.

**Comment by jmprieur** [comment]
@bgavrilMS might.

**Comment by bgavrilMS** [comment]
Sorry, haven't see this. Let's continue the discussion on the relevant thread.

**Comment by jmprieur** [comment]
@bgavrilMS : do you think we still need it, now that we have the following:https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnetcore
