### ISSUE TITLE
[Bug] [Internal] Fix the release build Guardian false positives. This is a mandatory step injected by policies to check that the DLLs are signed. It now scans 100s of DLLs in the staging directory. Ensure the product DLLs are scanned!

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2694]
Solution: configure this step to scan only MSAL DLLs

**Comment by pmaytak** [comment]
Side note: this might have already been fixed by #2693 but maybe need to verify.

**Comment by trwalke** [comment]
Waiting for reply from support on the best way to resolve this issue
https://msazure.visualstudio.com/One/_workitems/edit/10208323

**Comment by trwalke** [comment]
The solution we have today works fine and is the right thing to do. Get conformation from ADO support
