### ISSUE TITLE
MSAL.NET Token Silent Refresh Initiates Interactive Sign-in & Redirect URI

### ISSUE THREAD

**Issue by marktsn** [AzureAD/microsoft-authentication-library-for-dotnet#2695]
Using the code https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/tree/main/Demos/03-add-msgraph

**Expected behavior**
Each time the calendar page is loaded, this sample code should retrieve an access token by using the AcquireTokenSilent method.  When the received token is expired after 1 hour, the token refresh should be silent and non interactive without redirecting the user:

From GraphHelper.cs 

```
                var result = await idClient.AcquireTokenSilent(graphScopes, accounts.FirstOrDefault())
                            .ExecuteAsync();
```

```
                        requestMessage.Headers.Authorization =
                            new AuthenticationHeaderValue("Bearer", result.AccessToken);
                    }));
```

**Actual behavior**
When the calendar menu item is clicked to refresh the data after 1 hour, the user is redirected to microsoft online sign in briefly, which automatically signs the user back in and then returns the session back to the page via the redirect URI.  

**To my knowledge this experience should be transparent to the user without any redirect occurring**.  At the end of this process we have a new token generated which lasts for another hour, but not without impacting the user.

**Additional context / logs / screenshots**
The session has been set to over 1 hour in the web.config and verified that the session is not timed out, therefore suspect an issue with the MSAL .NET library method for handling token silent refresh

**Comment by bgavrilMS** [comment]
How did you setup your token caching?
