### ISSUE TITLE
RemoveAsync(Account) doesn't remove account from cache

### ISSUE THREAD

**Issue by chaitanya-chawla** [AzureAD/microsoft-authentication-library-for-dotnet#2696]
I am using WAM with msal.net cache
The authority is https://login.windows.net

The GetAccountsAsync call returns the single operating system account. After that no matter how many times, the removeAsync(account) method is called, I am unable to remove OS account from cache.

**Comment by jmprieur** [comment]
@chaitanya-chawla : did you try with https://login.microsoftonline.com ?

**Comment by bgavrilMS** [comment]
Apps cannot remove OS accounts. Only users can do that. 

You can choose not to list OS accounts via a flag - see [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam#advanced-options)

Here's what `RemoveAsync(account)` does: 

1. Removes "app only" accounts. An "app only" account is one where the user does not allow their account to be "captured" by the OS. Only "Work and School" accounts allow this option, when the user adds a new account: 

![image](https://user-images.githubusercontent.com/12273384/121862348-a2c67880-ccf2-11eb-9854-80059083ea86.png)

2. Removes all account information from MSAL's token cache (this includes MSA - i.e. personal accounts - account info and other account information copied by MSAL in its cache)

**Comment by pmaytak** [comment]
Discussed offline, everything works as expected after removing setting `ListWindowsWorkAndSchoolAccounts` to true. Will update the wiki to clarify the behavior.

**Comment by josephtobiah01** [comment]
How do i disable PublicClientApplicationBuilder from using broker?

**Comment by Meysam551** [comment]
I Use sp and call with dapper :) :(

**Comment by pmaytak** [comment]
@josephtobiah01 Broker is opt-in right now (by calling `WithBroker(options)`). So if you don't enable it explicitly, browser will be used. Why do you not want to use it? Do you experience issues with it? If so, create a new issue and we can take a look.
