### ISSUE TITLE
[Feature Request] Add a public method to get auto-detected region

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2698]
**Describe the solution you'd like**
- Create a public method that returns the cached region that was auto-detected by MSAL or does a first time detection.
- Rename auto-discovery to auto-detection for consistency (variable names, comments, etc.).

```csharp
IConfidentialClientApplication.TryDetectAzureRegion() : string
```

**Comment by bgavrilMS** [comment]
#3173 covers this.
