### ISSUE TITLE
[Feature Request]  Specify WithCertificate while fetching the token to deal with certificate rotation

### ISSUE THREAD

**Issue by yantang-msft** [AzureAD/microsoft-authentication-library-for-dotnet#2705]
**Is your feature request related to a problem? Please describe.**
I would like to use pattern 1 in this [doc](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Multi-tenant-client_credential-use#pattern-1---let-msal-do-it) since I don't need to manage the token.
However, the problem is we rotate our certificate periodically, and I can only specify the certificate while building the `ConfidentiClientApplication`. If the certificate expired, the token acquisition will fail which means I have to create another `ConfidentiClientApplication` instance with new certificate, but then the token cache are lost.

**Describe the solution you'd like**
I hope I can specify the certificate on the fly, something like
``` csharp
var result = await s_cca .AcquireTokenForClient("scope_for_downstream_api")
                      .WithCertificate(certificate)  // Add new API here
                      .WithAuthority("https://login.microsoft.com/<tenant_id>")
                      .WithSendX5C(true)
```

**Describe alternatives you've considered**
Alternative could be accepting a callback to get certificate in the builder.

**Comment by jmprieur** [comment]
@yantang-msft : is it for the ADAL.NET to MSAL.NET migration?

My recommendation. 
Provide an override with .WithCertificate that accepts a delegate as we've done for .WithClientAssertion():
https://docs.microsoft.com/azure/active-directory/develop/msal-net-client-assertions#signed-assertions

Work arounds
- Use the override of .WithClientAssertion() with the delegate ... this is documented in the article I liked ... but it's work. It would be better to expose the override of .WithCertificate
- Do like Microsoft.Identity.Web does to rotate the certificate (but this requires using a token cache serializer)

**Comment by yantang-msft** [comment]
@jmprieur This is for ADAL to MSAL migration. And yes, it there is override for .WithCertificate that takes a delegate then it would be great.

I plan to use [pattern 2](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Multi-tenant-client_credential-use#pattern-2---take-control-of-the-cache), I guess that's what you meant by follow Microsoft.Identity.Web using a token cache serializer.
The drawback is I have to create a new ConfidentialClientApplication instance every time fetching the token, as opposed to pattern 1 to have one static instance.

**Comment by bgavrilMS** [comment]
@yantang-msft  - there is no drawback really, creating those objects is very fast and it eliminates some bottlenecks associated with having 1 app + multiple requests, which internally uses some locks. Microsoft.Identity.Web also does this - it creates a new app for each request, and points the app to the common cache. This is recommended pattern that works for all flows.

**Comment by yantang-msft** [comment]
@bgavrilMS Thanks for the confirmation!
