### ISSUE TITLE
Bad WAM exception on unssuported OSes (Win 7, 8.1, server 2012)

### ISSUE THREAD

**Issue by nthurner** [AzureAD/microsoft-authentication-library-for-dotnet#2706]
**Documentation related to component**

Requirements

**Please check those that apply**

- [ ] documentation needs clarification

**Description of the issue**

Windows Server 2012 is not supported due System.NotImplementedException
  HResult=0x80004001
  Message=The method or operation is not implemented.
  Source=Microsoft.Identity.Client
  StackTrace:
   at Microsoft.Identity.Client.Internal.Broker.NullBroker.Microsoft.Identity.Client.Internal.Broker.IBroker.GetAccountsAsync

Windows 2012 is not Win10OrServerEquivalentInternal. See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/2e6c97336b03cbcc08555f693633429205d439cc/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/DesktopOsHelper.cs#L150

private static bool IsWin10OrServerEquivalentInternal()
        {
            if (IsWindows())
            {
                string winVersion = GetWindowsVersionString();

                if (winVersion.Contains("Windows 10", StringComparison.OrdinalIgnoreCase) ||
                    winVersion.Contains("Windows Server 2016", StringComparison.OrdinalIgnoreCase) ||
                    winVersion.Contains("Windows Server 2019", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }

            return false;

**Comment by jmprieur** [comment]
@bgavrilMS : would we want to have a better meaningfull exception?

**Comment by nthurner** [comment]
Hi
README.md says:

"Requirements
Operating system: Windows 7 or greater"

MSAL client do not work in Windows server 2012 r2. I think that the requirements are not correct.
Very Thank

**Comment by bgavrilMS** [comment]
I'd expect browser based auth to work. 
WAM is not present on WIn server 2012 so it won't work, but this is a bad exception.

**Comment by bgavrilMS** [comment]
P3 as this is not a supported OS

**Comment by maliksahil** [comment]
Ideally an error like this should return the PlatformNotSupportedException.
The error message should clearly mention which platforms are supported.

**Comment by bgavrilMS** [comment]
Windows 2012 is not a supported OS.

**Comment by bgavrilMS** [comment]
Looks like this is supported until 2023, we should fix this.

**Comment by pmaytak** [comment]
Included in [MSAL.NET 4.36.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.36.0).

cc: @nthurner

**Comment by bgavrilMS** [comment]
Yes it is supported ! Can you please try out our new WAM implementation as per https://aka.ms/msal-net-wam

**Comment by data-handler** [comment]
Thank you @bgavrilMS I have tried this before but was unable to get provide a handle running inside VS Code. Is that still possible?

**Comment by data-handler** [comment]
@bgavrilMS This works when after I publish the app and run it. Thanks again.

**Comment by bgavrilMS** [comment]
If you can't get a window handle for the app, you can use the Windows API `GetForegroundWindow` instead - https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getforegroundwindow and WAM will be parented to whatever app is in the foreground. It works well most of the time, expect when it doesn't :) (e.g. if the user switches between apps quickly).
