### ISSUE TITLE
[Feature Request] ECR: MSAL support for dynamic certificates

### ISSUE THREAD

**Issue by hkuadithya** [AzureAD/microsoft-authentication-library-for-dotnet#2708]
Usually, this is how an MSAL application is built using a certificate or a Client Assertion.

```
var application = ConfidentialClientApplicationBuilder
                    .Create(clientId: applicationId)
                    .WithCertificate(certificate)             // OR use  .WithClientAssertion(clientAssertionDelegate)
                    .WithAuthority(firstPartyAuthority)
                    .Build();
```

Now, this works great when we're dealing with **static certificates**. 

However, most Microsoft Services are now using ECR (Emergency Certificate Rotation) wherein, the certificates are renewed dynamically and the running applications are expected to reload their certificate stores and certificate caches at runtime. This removes the need for new application deployments just for updating certificates.

However, if the certificates can keep changing dynamically, we must retrieve the latest cert every single time and rebuild the Confidential application before making a request. To ameliorate this, we're using **custom caching strategies** where we cache the tokens till the expiration period.

## Potential Solution

Expose a delegate whose responsibility is to return the latest certificate. **MSAL application would store the Cert expiration time internally. If the Cert is about to expire, MSAL will seamlessly invoke the delegate to fetch the latest Cert again**. 

```
.WithCertificate(Func<X509Certficate2> certDelegate)
```

It will be the consumer's responsibility to implement the delegate and return the latest Certificate from either Certificate store or certificate cache. This code will be a "hot path". The consumer has to implement this in the least expensive manner. Else, it will be a bottleneck.

```
Func<X509Certificate2> certDelegate = () => 
{
      var certificate = // retrieve the latest certificate. Consumer must ensure good perf.
      return certificate;
};
```

****NOTE:** I also tested with `.WithClientAssertion(clientAssertionDelegate)` which uses a delegate. But, it looks like MSAL doesn't invoke this delegate again to fetch the latest client assertion once the cert expires. Can an engineer from MSAL confirm the exact behavior?**

## Token Cache

The token cache will be valid until the Cert is valid. Once the cert expires, use the delegate to fetch the latest cert and invalidate the stale cache. Eg: `NotAfter` property of the certificate. 

![image](https://user-images.githubusercontent.com/20955088/122274972-050cae00-ce98-11eb-90f0-cf55a1f21b2d.png)

**Comment by hkuadithya** [comment]
@bgavrilMS @jmprieur Could you guys please take a look at this? Basically, we would like the MSAL client to support certificate rotation scenarios. Ideally, we don't want to create a new MSAL confidential application every time the cert gets rotated due to ECR. Please acknowledge and review this.

**Comment by jennyf19** [comment]
@hkuadithya if you are on [net framework 462 or 472](https://github.com/AzureAD/microsoft-identity-web/wiki/asp-net) or [ASP.NET Core](https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates), you can use Microsoft identity web, which does certificate rotation for you.

**Comment by jmprieur** [comment]
@hkuadithya : apart from AcquireTokenForClient, we do recommend that you create a IConfidentialClientApplication for each request, and enable to token cache serializer. This is quick to create and has a small footprint. What's your concern about instantiating a new confidential client application?

**Comment by hkuadithya** [comment]
@jmprieur So, if you use a global/singleton Token cache serializer, will the same token cache will be used multiple `IConfidentialClientApplication`? My only argument for using a global MSAL confidential application was to reduce computation footprint and have a global shared token cache used in the running service.

And how does this token cache serializer solve the issues with Automated Certificate rotation? I found some docs as suggested by Jenny above: https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates

Do you have any code samples which can be used for our scenarios? Requirements-
1. Common token cache used across the service to reduce the request load on AAD 
2. Seamlessly fetch and use the latest certificate when the cert expires (`NotAfter` DateTime)

**Comment by jmprieur** [comment]
@hkuadithya 
Think of Microsoft.Identity.Web as MSAL for Web.
MSAL.NET itself cannot take a dependency on KeyVault, the Azure SDK etc (the Azure SDK depends on MSAL.NET, and also there are scenarios were customers and partners want the library to be lightweight)

See https://github.com/AzureAD/microsoft-identity-web/wiki/asp-net#some-of-the-samples-illustrating-token-cache-serialization-or-certificates-in-net-framework-apps for samples

**Comment by hkuadithya** [comment]
@jmprieur I'll be closing this issue now. Please highlight Certificate Rotation scenarios in the Identity Client docs as well (link to Identity Web APIs and Samples). Else, you'll keep receiving several issues like these.

**Comment by jmprieur** [comment]
@hkuadithya : can you share links where you'd want to see this info from?
