### ISSUE TITLE
[Feature Request] Add additional duration metrics

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#2711]
**Describe the solution you'd like**
Add metrics to the `AuthenticationResultMetadata`.
- `DurationInInternalCache` - either just how long `ITokenCacheInternal.FindAccessTokenAsync` takes or an aggregate of all cache access (FindAccessToken + FindRefreshToken + etc.) during an AcquireTokenX call.
- `DurationInMsalOnlyInMs` - for an AcquireTokenX call, duration of internal MSAL code minus the external calls (like HTTP calls, waiting for user input, serializing cache, etc.).

**Comment by bgavrilMS** [comment]
`DurationInInternalCache` - is this with or without loading / saving the data to Redis etc? 
`DurationInMsalOnlyInMs` - don't we already have that, as TimeSpentInTotal - TimeSpentInHttp - TimeSpentInCache ? I guess what you are saying is that we should also substract time spent in authorization (in the browser) for `publicClientApp.AcquireTokenInteractive` calls?

**Comment by pmaytak** [comment]
- `DurationInInternalCache` - without the serialization, since `DurationInCacheInMs` measures that.
- Yes, we can calculate it. Would be good to verify for all the flows, like interactive.

**Comment by bgavrilMS** [comment]
Sounds good. Can you think of any other time spent outside MSAL except the ones below? 

- http
- cache
- waiting for browser to come back to MSAL for AcquireTokenInteractive?

**Comment by jmprieur** [comment]
for http, the Otel extension for ASP.NET Core does a lot

**Comment by neha-bhargava** [comment]
> for http, the Otel extension for ASP.NET Core does a lot

Otel does capture the network latency and other details with otel logging or auto instrumentation. This will be good to have in MSAL logs for troubleshooting but not for capturing metrics.
