### ISSUE TITLE
Follow up on WebView2 related work items. Investigate, create bugs in [WebView2 repo](https://github.com/MicrosoftEdge/WebView2Feedback) if needed.

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2720]
#2482, #2591, #2685

We should also consider removing WV2 support from MSAL if state is not good enough. On .NET Classic this can be done without breaking change.

**Comment by pmaytak** [comment]
Status updates are in the issues themselves.
