### ISSUE TITLE
[Internal] Test .WithClaims on AcquireTokenForClient

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#2726]
**Is your feature request related to a problem? Please describe.**
AcquireTokenForClient now needs to support .WithClaims(claimsChallenge) (for CAE with Service principals)

**Describe the solution you'd like**

```CSharp
AcquireTokenForClient(scopes)
  .WithClaims(claimsChallenge)
  .ExecuteAsync();
```

**Comment by jmprieur** [comment]
This is a partner request (Oren/Jay)

**Comment by jmprieur** [comment]
This might exist already. When the service supports it we'd want to test.

**Comment by bgavrilMS** [comment]
Yes, the `WithClaims` API exists everywhere.
