### ISSUE TITLE
[Documentation] WAM overview has incorrect target framework moniker

### ISSUE THREAD

**Issue by kyle-rader** [AzureAD/microsoft-authentication-library-for-dotnet#2727]
**Documentation related to component**

**Please check those that apply**

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

The target framework require for WAM on Windows 10 is listed as `net5.0-windows10.0.17763.0` in the [this section](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam#availability) but the actual moniker required is `net5-windows10.0.17763.0` (without the `.0`).

**Comment by pmaytak** [comment]
Hi @kyle-rader Can you clarify why `net5*`? What is the behavior when you use `net5.0-windows10.0.17763.0`?

[.NET 5+ OS-specific TFMs](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#net-5-os-specific-tfms), specifies `net5.0*`. (Although both `net5*` and `net5.0` do to work.)

**Comment by bgavrilMS** [comment]
I confirm what Peter said, both work for me. 

In my setup (I'm running a net5 WinForms app), Visual Studio can't seem to figure out if my project changes and doesn't rebuild. I have to manually rebuild the project, otherwise it'll run an old version. Maybe this is the issue?

**Comment by kyle-rader** [comment]
Ah I figured it out. I had `net5.0-...` in my csproj for a console app, but a script was passing `-f net5.0` elsewhere overriding it, which was causing this runtime error:
```
If you have a Windows application which targets net5 or net5-windows, please change the target to net5-windows10.0.17763.0.
Your app can still run on earlier versions of Windows such as Win7 if you add <SupportedOSPlatformVersion>7</SupportedOSPlatformVersion> in the csproj.
 The broker (WAM) is available only on Win10 and this library will fallback to a browser on older systems.

If you have a NET5 cross-platform (Windows, Mac, Linux) application, please dual target net5 and net5-windows10.0.17763.0. Your installer should deploy the net5 version on Mac and Linux and the net5-window10.0.17763.0 on Windows.

If you have a .NET Core 3.1 application, please install the nuget package named Microsoft.Identity.Client.Desktop and call the extension method .WithWindowsBroker() first.
For details see https://aka.ms/msal-net-wam and https://github.com/dotnet/designs/blob/main/accepted/2020/platform-checks/platform-checks.md
```

Thanks for confirming both work!
