### ISSUE TITLE
[Bug] Better error messages for IWA

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2731]
Msal 4.33

- [x] IWA on pure ADFS (see customer bug https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2620)
- [x] review IWA implementation, MSAL C++ seem to be doing things a bit differently - increase robustness in parsing mex document
- [x] improve error messages when Mex document cannot be parsed and when UserRealm endpoint cannot be reached 

It's simply disabled https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/e7fd6b8abfdb63dcf2aaa460aeec3616b40ba3ea/src/client/Microsoft.Identity.Client/Internal/Requests/IntegratedWindowsAuthRequest.cs#L54

But even removing that line does not seem to work, as the first leg of request (the userrealm query) results in a 404 NotFound. 

We need to find the spec for IWA.

**Comment by jmprieur** [comment]
we discussed:
- direct to ADFS was never supported. We'd want to support it
- need better exceptions (more actionable).
More.
@maliksahil : would you be interested in helping specing what needs to be done:

**Comment by maliksahil** [comment]
Yep, happy to help. Will discuss and come up with a spec.

**Comment by trwalke** [comment]
Issue for supporting IWA in ADFS https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2771
