### ISSUE TITLE
Include x64 Builds in Nuget Package

### ISSUE THREAD

**Issue by crazydef** [AzureAD/microsoft-authentication-library-for-dotnet#2734]
Hi, I just started looking at integrating MSAL into our application stack and the first hurdle that jumps right out at me is that the Nuget Package doesn't contain any 64-bit binaries.

It would save me (and others) a ton of work if the Nuget package contained 64-bit builds.

As it stands, it looks like I currently have to spend (read: waste) time turning my wrappers (all our code is C++) into a COM module to marshal calls between the application and MSAL.

**Comment by jmprieur** [comment]
What do you mean @crazydef ? it's "any CPU". Would you like us to use .NET native to pre-generate for all platforms?

**Comment by crazydef** [comment]
Sorry, ignore me.  It was a long day of many things not quite working that suddenly started working for no obvious reason after a clean build.
