### ISSUE TITLE
MSAL 4.33 throws on mismatch authority

### ISSUE THREAD

**Issue by rabenshm** [AzureAD/microsoft-authentication-library-for-dotnet#2736]
Hello

After upgrading to MSAL 4.33.0 we are getting exception  Microsoft.Identity.Client.MsalClientException:
 The application is configured for cloud login.microsoftonline.com and the request for a different cloud - login.windows.net. This is not supported - the app and the request must target the same cloud.
See https://aka.ms/msal-net-authority-override for details.

We are using KeyVaultClient which is using callback which is probably sending the login.windows.net. We do not have control over that.

We initialize the application with login.microsoftonline.com

Thanks

**Comment by bgavrilMS** [comment]
This is blocking Kusto from upgrading. The environments "login.microsoftonline.com" and "login.windows.net" are the same, MSAL should do instance discovery before throwing.
