### ISSUE TITLE
Question - Validate token using MSAL

### ISSUE THREAD

**Issue by earora97** [AzureAD/microsoft-authentication-library-for-dotnet#2740]
Hi,

I was going through the code and I am trying to understand if MSAL has the support of validating tokens too? If yes can you please point me to the code snippet? If not, can you please help me understand how can I validate my token generated using MSAL library? Thanks!

**Comment by jmprieur** [comment]
@earora97
No msal.Net doesn't validate tokens. 
And a client app shouldn't validate a token and sometimes can't even as it can be encrypted. Only the protected web API for which the token was acquired should validate it. See which sdk you want to use to do that in https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview
