### ISSUE TITLE
[Bug] Remove the null check for .WithAzureRegion()

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#2747]
When a null value is passed in the .WithAzureRegion() api, we point skip region discovery and use the global endpoint and null is a valid value for this api.

Remove the null check made here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/ee3cd9c2fe59c0c34ff3a65142bc16f017fd7b27/src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs#L206

**Comment by jmprieur** [comment]
@henrik-me I think you didn't want to take this one.
Can we please get to a closure?
cc: @bgavrilMS @jennyf19 @trwalke @pmaytak

**Comment by bgavrilMS** [comment]
It's one of those API rules where we haven't been very consistent: 

`WithAccount(null)` `WithLoginHint(null)` - ignores setting
`WithRedirectUri(null)` and most others - throw

IMO, we should standardize on the second option, i.e. throwing, to make the APIs more intentional.
