### ISSUE TITLE
[Bug] CCS routing hint sends "missing from token response" as UPN in case of B2C

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2748]
![image](https://user-images.githubusercontent.com/19942418/124679190-dd967900-de78-11eb-85fb-45894378312e.png)
repro:
Sign-in w/a b2c account. Close the app. Sign-in again using `.WithLoginHint()`, and you'll see "Missing from the token response" in the UI, then in the routing hint, it is sent. Probably should not send it in this case? Or not send for B2C.

**Comment by trwalke** [comment]
Yes, probably should not send. Thanks for finding @jennyf19
