### ISSUE TITLE
Enable deterministic builds for CI MSAL builds.

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#2754]
Open the nuget package with NugetPackageExplorer
Under Health it can be observed that deterministic (dll/exe) is flagged for an error.

The solution is that the ContinuousIntegrationBuild MSBuild property has to be set to true when built on CI. In practice that means something like this in your directory props/targets file.

```
  <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
```
[Reference](https://www.mitchelsellers.com/blog/article/net-5-deterministic-builds-source-linking)

Should be done for: 

- [ ] MSAL
- [ ] MSAL.Desktop
- [ ]  MSAL cache extension 
- [ ] MIW

**Comment by bgavrilMS** [comment]
This has to be done for: MSAL, MSAL.Desktop, MSAL cache extension and MIW
