### ISSUE TITLE
[Bug] Do not throw if no ccs routing hint provided

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2755]
@trwalke i don't think MSAL should throw if no ccs routing hint is provided, because maybe there isn't a user present, so MSAL should not apply the header if the value is string.Empty or null. What do you think?
`throw new ArgumentException(MsalErrorMessage.CcsRoutingHintMissing, nameof(userObjectIdentifier));`

this way, the app will continue to work. doesn't seem like an issue that should prevent the app from working.

cc; @jmprieur thoughts?

**Comment by trwalke** [comment]
I took a look at some of the other apis that are not critical to authentication and they do not check for null values so I think you are right. 

These two apis do not check for null for example:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/517598c185e1010b4a161d54a9fb53a3fde49b3a/src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs#L144

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/517598c185e1010b4a161d54a9fb53a3fde49b3a/src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs#L157

Can remove in the next hotfix after the Kusto bug is done.

**Comment by jennyf19** [comment]
makes sense, thanks @trwalke
