### ISSUE TITLE
How to refresh a token?

### ISSUE THREAD

**Issue by crazydef** [AzureAD/microsoft-authentication-library-for-dotnet#2769]
Hi,

I'm using MSAL for .Net (wrapped in two DLLs - why is there no c++ version?) to manage authentication for this application.

I've set up a token cache, and I can retrieve a token with:

```
authResult = await clientApp.AcquireTokenSilent(scopes, firstAccount).ExecuteAsync();
return authResult.AccessToken;
```

However the token I receive has expired.  It was my understanding that tokens would be automatically refreshed, or, if they have totally expired, the above function would throw an exception so that I could guide the user through the reauthentication process.

This does not appear to be the case.

So, how do I ensure the retrieved token is up-to-date?  Or how can I check whether the token has expired and manually force the user to reauthenticate?

PS, I tried adding `WithForceRefresh(true)` to the above and that made no difference.

**Comment by jmprieur** [comment]
@crazydef : this should just work.
- do you have repro steps?
- How do you know that the token has expired? 
  - is it the web API that you use it for that tells you this?
  - or is it the expiry on the token itself?
- which flow did you use to acquire the token i the first place?

**Comment by crazydef** [comment]
@jmprieur

Apparently it is working.  There was a stupid bug in my code that was confusing the issue.  :)

**Comment by jmprieur** [comment]
Thanks for the update, @crazydef
