### ISSUE TITLE
MSAL drops the port when canonicalizing the authority URI

### ISSUE THREAD

**Issue by danroth27** [AzureAD/microsoft-authentication-library-for-dotnet#277]
When canonicalizing the authority URI MSAL [drops the port](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev/src/Microsoft.Identity.Client/Internal/Instance/B2CAuthority.cs#L45). This makes it impossible to use MSAL with an authority using a different port than the default.

**Comment by kpanwar** [comment]
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/272
