### ISSUE TITLE
[Feature Request] Enable MSAL to perform IWA in pure ADFS environments

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2771]
**Is your feature request related to a problem? Please describe.**
At the moment. MSAL is unable to perform IWA when connected to an ADFS `WithAdfsAuthority()` which results in an exception being thrown. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2731

**Describe the solution you'd like**
There is an authentication flow available for MSAL to use to handle this scenario. There is a variation of the auth code flow for MSAL that allows IWA to take place at the /authorize endpoint to retrieve a code. This code can then be exchanged at the token endpoint for a code.  By providing "amr_values=wia" as an extra query parameter to the authorize endpoint, we can configure the endpoint to prompt the httpClient to perform Windows authentication for the currently signed in user.  Errors returned from the endpoint can be made non interactive by adding "prompt=none" which will allow the client to receive it.

**Additional context**
To test this, a machine can be provisioned from the lab and domain joined to the ADFS2019 lab. The machine must also be added to the ADFS intranet via internet options.

Tasks:
- [ ] Enable the IntegratedWindowsAuthRequest class to send requests to the /authorize endpoint and provide  "amr_values=wia" and "prompt=none" as query parameters when the authority is ADFS
- [ ] Enable the IntegratedWindowsAuthRequest to exchange an auth code with the token endpoint
- [ ] Configure E2E environment for continuous testing
- [ ] Add E2E and other appropriate tests

**Comment by bgavrilMS** [comment]
Do we have a test environment? I'd like to try to see why WAM can't achieve this.

**Comment by bgavrilMS** [comment]
We don't have time to work on this issue at present. The scenario should be possible via WAM, see https://aka.msa/msal-net-wam

**Comment by bachoang** [comment]
Tried out WAM with ADFS but this does not work.  See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2836

**Comment by bgavrilMS** [comment]
Won't fix.
