### ISSUE TITLE
[Bug] System.UriFormatException: Invalid URI -  when creating ConfidentialClientApplicationBuilder with auto region discovery

### ISSUE THREAD

**Issue by Avivskie** [AzureAD/microsoft-authentication-library-for-dotnet#2772]
Opening bug after discussing it with Jenny Ferries from the MSAL team.
Getting the below exception when the code is deployed into Geneva synthetic runners, but when running locally the exact same code it works fine.

**Logs and network traces**

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.21] ConfidentialClientApplication 22779505 created'

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.47 - 27773b9b-3b35-4839-9388-bc3a6fb95095] MSAL MSAL.Desktop with assembly version '4.34.0.0'. CorrelationId(27773b9b-3b35-4839-9388-bc3a6fb95095)'

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.47 - 27773b9b-3b35-4839-9388-bc3a6fb95095] === AcquireTokenForClientParameters ===
SendX5C: True
ForceRefresh: False

TraceMessage: 'MSAL: True MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.49 - 27773b9b-3b35-4839-9388-bc3a6fb95095] 
=== Request Data ===
Authority Provided? - True
Client Id - 3eca24fd-ea16-411c-b865-27d750704e99
Scopes - https://management.azure.com/.default
Redirect Uri - https://replyUrlNotSet
Extra Query Params Keys (space separated) - 
ClaimsAndClientCapabilities - 
Authority - https://login.microsoftonline.com/33e01921-4d64-4f8c-a055-5bdaffd5e33d/
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - True
LoginHint - 
IsBrokerConfigured - False
HomeAccountId - 
CorrelationId - 27773b9b-3b35-4839-9388-bc3a6fb95095

TraceMessage: 'MSAL: True MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.49 - 27773b9b-3b35-4839-9388-bc3a6fb95095] === Token Acquisition (ClientCredentialRequest) started:
	Authority: https://login.microsoftonline.com/33e01921-4d64-4f8c-a055-5bdaffd5e33d/
	Scope: https://management.azure.com/.default
	ClientId: 3eca24fd-ea16-411c-b865-27d750704e99

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.52 - 27773b9b-3b35-4839-9388-bc3a6fb95095] [Cache Session Manager] Waiting for cache semaphore'

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.52 - 27773b9b-3b35-4839-9388-bc3a6fb95095] [Cache Session Manager] Entered cache semaphore'

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.52] [InMemoryPartitionedTokenCache] ReadCacheBytes did not find cacheKey 3eca24fd-ea16-411c-b865-27d750704e99_33e01921-4d64-4f8c-a055-5bdaffd5e33d_AppTokenCache'

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.52 - 27773b9b-3b35-4839-9388-bc3a6fb95095] [Cache Session Manager] Released cache semaphore'

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.52 - 27773b9b-3b35-4839-9388-bc3a6fb95095] No access tokens found in the cache. Skipping filtering. '

TraceMessage: 'MSAL: False MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.55 - 27773b9b-3b35-4839-9388-bc3a6fb95095] [Region discovery] Region found in environment variable: East US.'

TraceMessage: 'MSAL: True MSAL 4.34.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Datacenter [07/15 20:04:04.60 - 27773b9b-3b35-4839-9388-bc3a6fb95095] System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.UriBuilder.get_Uri()
   at Microsoft.Identity.Client.Instance.Authority.CreateAuthorityWithEnvironment(AuthorityInfo authorityInfo, String environment)
   at Microsoft.Identity.Client.Instance.AuthorityManager.<RunInstanceDiscoveryAndValidationAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<FetchNewAccessTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()'

**Which version of MSAL.NET are you using?**
MSAL.NET 4.34.0

**Platform**
.NET 472

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

            return await this.ConfidentialClientApplication.AcquireTokenForClient(
                    new[] { $"{this.Resource}/.default" })
                .WithSendX5C(true)
                .ExecuteAsync()
                .ConfigureAwait(false);

**Expected behavior**
Getting the above exception when calling "AcquireTokenForClient". this happens when deployed into Geneva Synthetics, but when running it locally same code with same configuration works good.

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes.  

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by Avivskie** [comment]
It seems that the bug is related to the auto discovery with WithAzureRegion(), when removing that part it works fine.

**Code that didnt work:**

```
ConfidentialClientApplicationBuilder.Create(this.jobConfigurations.ArmServicePrincipleId)
                    .WithCertificate(this.certificate)
                    .WithAuthority(uri.AbsoluteUri)
                    .WithAzureRegion()
                    .Build();
```

**Code that worked:**

```
ConfidentialClientApplicationBuilder.Create(this.jobConfigurations.ArmServicePrincipleId)
                    .WithCertificate(this.certificate)
                    .WithAuthority(uri.AbsoluteUri)
                    .Build();
```

**Comment by jmprieur** [comment]
@Avivskie:

> "Region found in environment variable: East US.'"

The `$Region` environment variable is set to  "East US" which contains a space, and therefore cannot be a part of the URI for the regional Azure AD. You need to provide the region **short name**. See https://identitydocs.azurewebsites.net/static/v2/msal-net-regional-adoption.html#how-to-provide-region-value

I guess 'eastus' ?


cc: @jennyf19  and @bgavrilMS

**Comment by Avivskie** [comment]
@jmprieur 
I didnt provide anything, the "East US" is the result of the MSAL auto region discovery,
Note that this Environment Variable is on a machine I do not necessarily control nor have access to (cloud service/azure function etc.). 

I think you need to have validation for the auto discovery, and if the auto discovery is the full name then convert it to short region name.

**Comment by bgavrilMS** [comment]
What the Azure system that you deploy to ? I was under the impression that the environment variable is supposed to be set to the region short name. If there is a variation, the owners of the system should fix it to ensure consistency. 

The only validation we can do is to make sure there is no space in the name. The list of region keeps expanding, we can't hardcode it.

**Comment by Avivskie** [comment]
@bgavrilMS 
We provide the above MSAL code as part of a client library/nuget we publish to multiple consumers in Azure, we do not know where they will deploy it. we can ask them to pass us a string with the region, but then we will need to validate our self if it is a valid region, this is why we prefer the auto discovery feature over passing the string of the region.

I understand the list of regions is growing and you cannot verify each and every one, but even just space validation here will be helpful (which in most cases means the full name is was in the environment variable instead of the short name).

btw, just curious, is it a requirement for every windows system to have the environment variable REGION_NAME set to the short region name? perhaps this assumption is not correct and I am just the first one encountering such system, and a different maybe more robust solution is needed :)

**Comment by bgavrilMS** [comment]
Ack. What I'm trying to say is that we should try to track down the azure system where the application was deployed to and work with them to fix the issue. 

The algorithm for region auto-detection is: 


1. Try to read env variable REGION_NAME. 
2. If not present, try to make an HTTP call to the IMDS endpoint `http://169.254.169.254/metadata/instance/compute/location?api-version=2020-06-01` - this might also have the region. 
3. If not present, auto-detection fails and MSAL will use the non-regional (i.e. global) authority that was configured.


We tested this on several systems, such as VMs and compute. Some systems do advertise the region, some do not. Hence we ask the developers to give us the region if they know it.

**Comment by Avivskie** [comment]
Okay, I will contact the team that owns those machines and try to set a meeting between all parties, meanwhile I think we will remove the auto discovery altogether from our code.

**Comment by Avivskie** [comment]
@bgavrilMS I've checked and that problematic run was built on Azure Function, so you might want to check with them regarding that env variable on their machines.

**Comment by wangyuan8421** [comment]
I have another input. I'm using nuget Microsoft.Identity.Client 4.34.0.

Same error(Invalid URI). Same solution(Disable WithAzureRegion fist).

Two things a different.
1. I'm using MSAL in AzureFunction. As the comment in source code: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0d53f3e80e29f9c6d172e069c10e02d71e24f65e/src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs#L195 "**Auto-detection works on a limited number of Azure artifacts (VMs, Azure functions).**" So I did not input region string.
2. The same code works fine in local environment. Once I deploy AzureFunction to Azure, it will throw this exception.

Hope this can provide some more context about this issue.
