### ISSUE TITLE
[Bug] Inconsistent results using OBO flow

### ISSUE THREAD

**Issue by SirElTomato** [AzureAD/microsoft-authentication-library-for-dotnet#2773]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.34.0
Microsoft.Identity.Web 1.14.0

**Platform**
.Net Framework 4.7.2

**What authentication flow has the issue?**
* Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [x] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
- Sign in with mobile app
- Call private API which creates confidential client application and calls AquireTokenOnBehalfOf
- Call downstream graph API (outlook)

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.

**Repro**

```csharp
    public class MicrosoftService : IMicrosoftService
    {
        public IConfidentialClientApplication ConfidentialClientApplication { get; set; }
        private readonly ICompanyUserRepo _userRepo;
        private readonly IAuthenticationSettings _authenticationSettings;
        private readonly IDatabaseSettings _databaseSettings;

        public MicrosoftService(
            ICompanyUserRepo userRepo,
            IAuthenticationSettings configuration,
            IDatabaseSettings databaseSettings)
        {
            _userRepo = userRepo;
            _authenticationSettings = configuration;
            _databaseSettings = databaseSettings;

            ConfidentialClientApplication = BuildApp();
        }

        public async Task GetAccessTokenAndUpdateUser(string userId, IEnumerable<string> scopes, string jwt)
        {
            await AquireTokenOnBehalfOf(scopes, jwt);

            var user = _userRepo.GetByIdAndPartitionKeyOrDefault(userId, userId);
            user.MicrosoftIdentity = jwt;

            _userRepo.Update(user);
        }

        public async Task<AuthenticationResult> GetToken(string userId, IEnumerable<string> scopes)
        {
            var user = _userRepo.GetByIdAndPartitionKeyOrDefault(userId, userId);
            var jwt = user.MicrosoftIdentity;

            return await AquireTokenOnBehalfOf(scopes, jwt);
        }

        public async Task RevokeToken(string userId, IEnumerable<string> scopes)
        {
            var user = _userRepo.GetByIdAndPartitionKeyOrDefault(userId, userId);
            var authResult = await AquireTokenOnBehalfOf(scopes, user.MicrosoftIdentity);

            await ConfidentialClientApplication.RemoveAsync(authResult.Account);
            user.MicrosoftIdentity = null;

            _userRepo.Update(user);
        }

        private async Task<AuthenticationResult> AquireTokenOnBehalfOf(IEnumerable<string> scopes, string jwt)
        {
            var userAssertion = new UserAssertion(jwt);
            var res = await ConfidentialClientApplication.AcquireTokenOnBehalfOf(scopes, userAssertion).ExecuteAsync();

            return res;
        }

        private IConfidentialClientApplication BuildApp()
        {
            // The application which retreives the auth token must also use the same client id and redirect url when requesting the token. The auth token from the response is then passed to the AquireTokenByAuthorisationCode method below. 

            IConfidentialClientApplication app = ConfidentialClientApplicationBuilder
                .Create(_authenticationSettings.MicrosoftRevokeAppId)
                .WithRedirectUri(_authenticationSettings.EmailScanWebAppBaseUrl + _authenticationSettings.MicrosoftRedirectAction)
                .WithClientSecret(_authenticationSettings.MicrosoftRevokeAppSecret)
                .WithTenantId(_authenticationSettings.MicrosoftTenantId)
                .Build();

            IMsalTokenCacheProvider cosmosTokenCacheProvider = CreateCosmosTokenCacheSerialiser();
            cosmosTokenCacheProvider.Initialize(app.UserTokenCache);

            return app;
        }

        private IMsalTokenCacheProvider CreateCosmosTokenCacheSerialiser()
        {
            IServiceCollection services = new ServiceCollection().AddLogging();
            var cosmosConnectionString = string.Format("AccountEndpoint={0};AccountKey={1};", _databaseSettings.RevokeGlobalDatabaseUri, _databaseSettings.RevokeGlobalDatabaseKey);

            services.AddDistributedTokenCaches();
            services.AddCosmosCache((CosmosCacheOptions cacheOptions) =>
            {
                cacheOptions.DatabaseName = _databaseSettings.RevokeGlobalDatabase;
                cacheOptions.ContainerName = _authenticationSettings.CosmosMsalContainer;
                cacheOptions.CreateIfNotExists = true;
                cacheOptions.ClientBuilder = new CosmosClientBuilder(cosmosConnectionString);
            });

            IServiceProvider serviceProvider = services.BuildServiceProvider();
            IMsalTokenCacheProvider msalTokenCacheProvider = serviceProvider.GetRequiredService<IMsalTokenCacheProvider>();

            return msalTokenCacheProvider;
        }
    }
}

```

**Expected behavior**
A token is retrieved which can be used to call the downstream api

**Actual behavior**
Sometimes the token is retrieved, sometimes it returns this error instead: 
```
AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.\r\nTrace ID: 19a4f1a4-09cd-4729-8ccb-b1299cc37600\r\nCorrelation ID: 34dc13fe-7c6e-49af-acdc-e85b62088927\r\nTimestamp: 2021-07-15 13:37:24Z
```

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@SirElTomato
- do you see this happening recently? or also with previous versions of MSAL?
- what scopes are you requesting?
- do you have MSAL logs? https://aka.ms/msal-net-logging

**Comment by SirElTomato** [comment]
@jmprieur I've just found out that this error is happening with personal microsoft accounts only, it works fine with organisational accounts.

I have had this issues previously but fixed it by adding the extra scopes to the acquire token interactively method from the mobile app. I believe it is because the scopes required are already consented to for the whole of the organisation for the organisational account I am using. 

currently from the app I am using the api://xxxxx as the scope and "mail.read" as the extra scope, are there any more scopes I need to consent to from the initial interactive sign in? 

Thanks

**Comment by SirElTomato** [comment]
When I get the consent screen popup I get asked for consent for "Maintain access to data you have given Revoke access to" and "View your basic profile" but nothing about email read access

**Comment by jmprieur** [comment]
@SirElTomato.
user.read is "view your basic profile".

In If your web API calls downstream web APIs, you can also roll-up consent of these APIs.
For details, see https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-overview
and https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph in particular https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph#configure-known-client-applications-for-service-todolistservicems-identity-dotnet-native-aspnetcore-v2. In that case the scope you'd use would be `api://xxxxx/.default`

**Comment by SirElTomato** [comment]
what about mail.read, thats what i need to call the outlook api?

**Comment by jmprieur** [comment]
I would think you need the api://xxx part.
Did you try without user.read?

**Comment by SirElTomato** [comment]
I have api://xxx set as a scope on the initial consent from mobile app. 
I don't have user.read set as a scope anywhere in my code

**Comment by SirElTomato** [comment]
Mobile app code:

```
    private readonly kScopes = [
        'api://6480c91c-8732-4289-91f2-76c7635bb240/ScanEmails'
    ];

    private readonly kExtraScopes = [
        "mail.read"
    ];
    private readonly kClientId = '6480c91c-8732-4289-91f2-76c7635bb240';

    private _msalClient: PublicClientApplication;

    constructor() {
        this._msalClient = new PublicClientApplication({ auth: { clientId: this.kClientId } });
    }

    login() {
        return new Promise<boolean>(async (resolve) => {

            const acquireTokenParams: MSALInteractiveParams = {
                scopes: this.kScopes,
                promptType: MSALPromptType.CONSENT,
                extraScopesToConsent: this.kExtraScopes
            };

            try {
                const result: MSALResult = await this._msalClient.acquireToken(acquireTokenParams);
                const resultString = JSON.stringify(result);
                if (result && result.accessToken) {
                    console.log(result.accessToken);
                    const response = await myApi.GenerateMicrosoftApiTokens({ jwt: result.accessToken, scopes: this.kScopes })
                    resolve(response.success);
                }
                else {
                    resolve(false);
                }
                console.log(resultString);

            } catch (error) {
                const jsonError = JSON.stringify(error);
                console.log(jsonError);
                resolve(false);
            }
        })
    }

```

**Comment by SirElTomato** [comment]
My api service to call downstream api (outlook)

```
public class OutlookService : IOutlookService
    {
        private readonly List<string> _scopes = new List<string> { "offline_access", "mail.read", "openid" };
        private readonly IMicrosoftService _revokeMicrosoftService;
        private readonly GraphServiceClient _graphClient;

        public OutlookService(IMicrosoftService microsoftService)
        {
            _microsoftService = microsoftService;

            var authProvider = new OnBehalfOfProvider(_microsoftService.ConfidentialClientApplication, _scopes);
            _graphClient = new GraphServiceClient(authProvider);
        }

        public async Task<RevokeEmailPagingContent> GetSenders(string userId, string pagingLink, int numberOfEmailsToGetPerPage, string folderToScanDisplayName)
        {
            var token = await _revokeMicrosoftService.GetToken(userId, _scopes);

            var mailFolders = await _graphClient.Me.MailFolders.Request().GetAsync();
            MailFolder mailFolder = mailFolders.ToList().Find(x => x.DisplayName == folderToScanDisplayName);

            if (mailFolder == null)
            {
                throw new ArgumentException("Folder to scan display name does not exist.");
            }

            var queryOptions = new List<QueryOption>();

            if (!string.IsNullOrEmpty(pagingLink))
            {
                new List<QueryOption> {
                    (new QueryOption("$skiptoken", pagingLink)),
                };
            }

            var messages = await _graphClient.Me.MailFolders[mailFolder.Id].Messages.Request(queryOptions)
                .Top(numberOfEmailsToGetPerPage)
                .OrderBy("receivedDateTime desc")
                .GetAsync();

            var emailContent = messages.Select(x => new RevokeEmailContent { Id = x.Id, Sender = x.Sender.EmailAddress.Address }).ToList();
            pagingLink = messages.NextPageRequest?
                .QueryOptions?
                .FirstOrDefault(x => string.Equals("$skiptoken", x.Name, StringComparison.InvariantCultureIgnoreCase))?
                .Value;

            return new RevokeEmailPagingContent()
            {
                EmailContent = emailContent,
                PagingLink = pagingLink,
            };
        }
    }
```

**Comment by jmprieur** [comment]
@SirElTomato, is your issue solved? or do you need more from us?

**Comment by SirElTomato** [comment]
@jmprieur nope still having the issue

**Comment by SirElTomato** [comment]
Can you review the scopes used in the code samples above and let me know if they are correct

**Comment by JoshB82** [comment]
Hello,

My name is Josh and I work with @SirElTomato on a project using this code.

@jmprieur When you're available please can you take a look at the scopes in @SirElTomato's code above. We need to know if this is a problem on our end or not and we cannot ship a feature without this working.

Feel free to message me if you have any more questions.

Many thanks for your time.

**Comment by jmprieur** [comment]
@SirElTomato @JoshB82 the scopes look good.
In fact MSAL.NET always requests "openid profile offline_access" so that the cache works correctly, so you could use only "mail.read" if you wish.

**Comment by JoshB82** [comment]
Authenticating with an @outlook.com email address results in `AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.` This occurs for both `"mail.read"` and  `"offline_access", "mail.read", "openid"` scopes set in the code.

Do you think there is a problem with using a personal @outlook.com email address?

**Comment by SirElTomato** [comment]
@jmprieur no consent is requested for the mail.read scope for personal accounts. Is there something we are doing wrong?

When I get the consent screen popup I get asked for consent for "Maintain access to data you have given Revoke access to" and "View your basic profile" but nothing about email read access

**Comment by SirElTomato** [comment]
I will collect some logs now following [this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging), do you want me to send you logs with pii direct to your email?

**Comment by bgavrilMS** [comment]
There may be a different way consent and actual tokens are handled for Mail.Read between AAD (work and school) and MSA (personal) accounts. I'll try to repro.

**Comment by bgavrilMS** [comment]
In the app registration portal in Azure, if you go to the Manifest, can you confirm that both apps have:

```json
"signInAudience": "AzureADandPersonalMicrosoftAccount",
```


`

**Comment by SirElTomato** [comment]
Yes I confirm that this is in the Manifest: 
```
"signInAudience": "AzureADandPersonalMicrosoftAccount",
```

**Comment by SirElTomato** [comment]
Although there is only one app registration which handles both the mobile app and the private api as per [this](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/3.-Web-api-call-Microsoft-graph-for-personal-accounts)

**Comment by bgavrilMS** [comment]
I think I can repro this even with User.Read, the consent seems to be handled differently. Still investigating...

**Comment by bgavrilMS** [comment]
@jennyf19  - I do not fully understand how Microsoft.Identity.Web constructs the WWWAuthenticate challenge. It seems ok, but consent is still needed. If you login with the tenant administrator, you get a different experience. Can we take a look at this toghter.

@SirElTomato - is it possible to pre-consent on behalf of the tenant there?

**Comment by jennyf19** [comment]
@bgavrilMS ID web doesn't construct the WWW-Authenticate header.

**Comment by SirElTomato** [comment]
@bgavrilMS It's not possible to pre-consent on behalf because the issue is for personal accounts. i think the reason it is working for organisational accounts is because I have granted consent on behalf of the tenant.

**Comment by bgavrilMS** [comment]
@jennyf19 - MIW does create a WWWAuthenticate header and I think there is a bug there. The code is [here](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/20b616af1cc159fc5ed5b754b1570309568d9c24/2. Web API now calls Microsoft Graph/TodoListService/Controllers/TodoListController.cs#L77) - `ITokenAcquisition.ReplyForbiddenWithWwwAuthenticateHeader`

In my testing, the [client app receives the 401](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/20b616af1cc159fc5ed5b754b1570309568d9c24/2. Web API now calls Microsoft Graph/TodoListClient/MainWindow.xaml.cs#L298) but no WWWAuthenticate header for some reason. So it just prints "Forbidden". Interestingly, I managed to get into this situation with an AAD user not MSA.

@SirElTomato @JoshB82  - could I confirm with you that this is what's happening ? In my testing, with an AAD user this [line](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/20b616af1cc159fc5ed5b754b1570309568d9c24/2. Web API now calls Microsoft Graph/TodoListClient/MainWindow.xaml.cs#L298) is hit. But when things go wrong, the else clause is hit because the response.Headers.WwwAuthenticate.Any() is false

**Comment by bgavrilMS** [comment]
@SirElTomato  @JoshB82 - as a workaround, try the following: 

- in the sample, instead of `await DisplayErrorMessage(response)` (e.g. line 304 for AddItem), you can get consent like this: 

```csharp

var accountThatNeedsConsent = accounts.FirstOrDefault(); 

await _app.AcquireTokenInteractive(new[] { "User.Read" })
                        .WithPrompt(Prompt.Consent)
                        .WithAccount(accountThatNeedsConsent)
                        .ExecuteAsync();
```

This will force the consent screen. Let me know if this works and we see about doing an actual fix.

**Comment by SirElTomato** [comment]
@bgavrilMS I can't try the workaround you suggested because the initial aquisitioin of the token is done on the mobile app side using [this code as previously commented](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2773#issuecomment-881455315). 

The mobile app is react native and uses [this package](https://github.com/stashenergy/react-native-msal)

The private API uses AquireTokenOnBehalfOf as shown in [this code as previously commented](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2773#issuecomment-881456313)

**Comment by bgavrilMS** [comment]
Does the mobile app not open the browser and prompt the user to consent to both scopes? You can check if the MSA user has indeed consented by reviewing consent for apps here: https://account.live.com/consent/Manage

**Comment by SirElTomato** [comment]
No consent is requested for the mail.read scope for personal accounts. 

When I get the consent screen popup I get asked for consent for "Maintain access to data you have given Revoke access to" and "View your basic profile" but nothing about email read access. 

When I check the consent though the link you provided, it only shows consent for the two listed above, nothing for the mail.read scope.

**Comment by bgavrilMS** [comment]
Ok, I think I get your point now.

This is what happens when I try the following call in a client desktop app using MSAL.NET:

```csharp
 var result = await _app.AcquireTokenInteractive(new[] {"api://GUID/access_as_user"}) // this is the OBO scope
                        .WithAccount(acc)
                        .WithExtraScopesToConsent(new[] { "User.Read", "Mail.Read" } )
                        .WithPrompt(Prompt.SelectAccount)
                        .ExecuteAsync()
                        .ConfigureAwait(false);

```

1. MSAL opens a browser which makes a call to the /authorize endpoint. It asks for scopes "api://GUID/access_as_user", "user.read" and "mail.read". The consent screen that comes up is asking for these 3 scopes.

2. After user consent , MSAL makes a call to the /token endpoint with the authorization_code it just obtained. But it requests a token only for "api://GUID/access_as_user"

This is the logic of "extra scopes to consent to" - we need to ask for all scopes at the /authorize endpoint to get consent, but at the /token endpoint just get a token for the OBO scope, since the client app doesn't actually need a token for "User.Read" and "Mail.Read"


Now back to you issue - I wonder if this is a problem with the client code that you are using? Is this MSAL.JS ? You should see a consent screen popping asking for "Mail.Read" consent. Maybe you can try to capture the network traffic or the authorization URI to confirm ?

**Comment by SirElTomato** [comment]
@bgavrilMS 
The mobile app is react native and uses [this package](https://github.com/stashenergy/react-native-msal)
I am using [this code as previously commented](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2773#issuecomment-881455315).

**Comment by bgavrilMS** [comment]
Sadly AzureAD is not the author of https://github.com/stashenergy/react-native-msal . I think this may be a bug on their side. I believe they are wrapping MSAL.JS. 

It might be possible to workaround this bug by using `.WithExtraQueryParameters("scope=OBOscope,Mail.Read")` but I would check with them or with MSAL.js

**Comment by SirElTomato** [comment]
@bgavrilMS We've raised a bug on msal for android repo (which is what this third party package is wrapping) but not getting any response from anyone, maybe you could assist? 

https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1520 

We tried using your work around but it didn't seem to do anything. Can you give more details on how .WithExtraQueryParameters works or point at me at some documentation please?

**Comment by bgavrilMS** [comment]
Yes. The scenario is "Client app needs a token for a web api and web api needs a token for Graph. Consent must only be asked once."

The protocol is pretty simple. Assume that the web api scope is `API_SCOPE` and graph api scope is `Mail.Read`

In MSAL: 

`AcquireTokenInteractive("API_SCOPE").WithExtraScopesToConsentTo("Mail.Read");`

At protocol level:

1. When MSAL makes the call to the /authorize endpoint, it asks for both `API_SCOPE` and `Mail.Read`. This will ensure that consent is asked for **both** resources.
1. MSAL uses the auth_code to get a token for `API_SCOPE` only. 
1. The client app accesses the web api with this token. This works, as the token for API_SCOPE gives access to the web api 
1. The web api uses OBO to get a token for Graph. This works **silently**, because consent will already have been given.
