### ISSUE TITLE
[Documentation] WithRegionName documentation summary provide incorrect region name link

### ISSUE THREAD

**Issue by Avivskie** [AzureAD/microsoft-authentication-library-for-dotnet#2779]
**Documentation related to component**
Region Name

**Please check those that apply**

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [-] error(s) in example
- [ ] needs example

**Description of the issue**
![image](https://user-images.githubusercontent.com/10419623/126076414-048e58ee-f691-441e-9238-b9bb7b791203.png)

The link provided in the documntation gives the wrong region names - for example in the link its USEast, but actually the region short name is EastUS.
I couldnt find a link with the correct region names, and therefore I didnt fix it myself.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.region?view=azure-dotnet

**Comment by bgavrilMS** [comment]
There seems to be no public documentation of the short region names. This issue is blocked.
