### ISSUE TITLE
AcquireTokenInteractive hangs - never returning

### ISSUE THREAD

**Issue by stmoor** [AzureAD/microsoft-authentication-library-for-dotnet#2786]
**Logs and network traces**
[] False MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] === InteractiveParameters Data ===
[] LoginHint provided: False
[] User provided: False
[] UseEmbeddedWebView: Embedded
[] ExtraScopesToConsent: 
[] Prompt: select_account
[] HasCustomWebUi: False
MSAL Info False False MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: Embedded
ExtraScopesToConsent: 
Prompt: select_account
HasCustomWebUi: False
[] True MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] 
[] === Request Data ===
[] Authority Provided? - True
[] Client Id - **
[] Scopes - **
[] Redirect Uri -**
[] Extra Query Params Keys (space separated) - 
[] ClaimsAndClientCapabilities - 
[] Authority - **
[] ApiId - AcquireTokenInteractive
[] IsConfidentialClient - False
[] SendX5C - False
[] LoginHint - 
[] IsBrokerConfigured - False
[] HomeAccountId - 
[] CorrelationId - c7481e64-385e-4a62-bb0d-c3cbb4e509b8
MSAL Info True True MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] 
=== Request Data ===
Authority Provided? - True
Client Id - **
Scopes -**
Redirect Uri - **
Extra Query Params Keys (space separated) - 
ClaimsAndClientCapabilities - 
Authority - https://**
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint - 
IsBrokerConfigured - False
HomeAccountId - 
CorrelationId - c7481e64-385e-4a62-bb0d-c3cbb4e509b8
[] True MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] === Token Acquisition (InteractiveRequest) started:
[] 	Authority: **
[] 	Scope: **
[] 	ClientId: **
[] 	
MSAL Info True True MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] === Token Acquisition (InteractiveRequest) started:
	Authority: **
	Scope: **
	ClientId: **
	
[] False MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] [Instance Discovery] Skipping Instance discovery for non-AAD authority. 
MSAL Info False False MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] [Instance Discovery] Skipping Instance discovery for non-AAD authority. 
[] False MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] Resolving authority endpoints... Already resolved? - TRUE
MSAL Info False False MSAL 4.34.0.0 MSAL.Xamarin.Android Mono 6.12.0 (2020-02/b4a385816ed) 28 [07/20 19:59:59.77 - c7481e64-385e-4a62-bb0d-c3cbb4e509b8] Resolving authority endpoints... Already resolved? - TRUE

**Which version of MSAL.NET are you using?**
MSAL.NET 4.34.0

**Platform**
Xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ x] Interactive

**Is this a new or existing app?**
c. This is a new app or experiment.

**Repro**

```csharp
  private B2CAuthenticationService()
  {

      // default redirectURI; each platform specific project will have to override it with its own
      var builder = PublicClientApplicationBuilder.Create(Constants.B2CConstants.ClientId)
            .WithB2CAuthority(Constants.B2CConstants.AuthoritySignin)
            .WithIosKeychainSecurityGroup(Constants.B2CConstants.IosKeychainSecurityGroups)
            .WithRedirectUri($"msal{Constants.B2CConstants.ClientId}://auth")
            .WithLogging(MyLoggingMethod, LogLevel.Info,
               enablePiiLogging: true,
               enableDefaultPlatformLogging: true);
      
      // Android implementation is based on https://github.com/jamesmontemagno/CurrentActivityPlugin
      // iOS implementation would require to expose the current ViewControler - not currently implemented as it is not required
      // UWP does not require this
      var windowLocatorService = DependencyService.Get<IParentWindowLocatorService>();
      
      if (windowLocatorService != null)
      {
            builder = builder.WithParentActivityOrWindow(() => windowLocatorService?.GetCurrentParentWindow());
      }
      
      _pca = builder.Build();
}

private async Task<AuthenticationResult> SignInInteractively()
{
      AuthenticationResult authResult = await _pca.AcquireTokenInteractive(Constants.B2CConstants.Scopes)
          .WithPrompt(Prompt.SelectAccount)
          .WithUseEmbeddedWebView(true)
          .WithParentActivityOrWindow(App.UIParent)
          .ExecuteAsync();
      
      return authResult;
}

```

**Expected behavior**
When the user selects an account to log in, e.g. Microsoft, the AcquireTokenInteractive should return an AuthenticationResult. 

**Actual behavior**
It hangs, never returns. It never reaches the "return authResult;" line

**Comment by jennyf19** [comment]
@stmoor was this working for you previously?

**Comment by stmoor** [comment]
Yes, I did some changes to the project like moving the calls to the B2CAuthenticationService instead of being directly on the login page, but that is it. Other than that, the calls are identical, no change in the way I call the library.

**Comment by jennyf19** [comment]
@stmoor could you provide a link to your project?

**Comment by stmoor** [comment]
Here is the link - you should have access to https://github.com/stmoor/TestApp

**Comment by jennyf19** [comment]
Thanks...actually could you give access to @SameerK-MSFT ? I'll have him take a look. thank you @stmoor

**Comment by stmoor** [comment]
Done. Thanks!

**Comment by SameerK-MSFT** [comment]
I will try to repro. But it looks like a threading issue. Have you used ConfigureAwait(false)? It may address the issue.

**Comment by stmoor** [comment]
@SameerK-MSFT Yes I tried ConfigureAwait(false) and it did not fix it. Thanks for looking into it.

**Comment by bgavrilMS** [comment]
@stmoor 

Does the browser pop up? Does the user complete authentication but the browser never goes back to the app? 
Where there any changes to the redirect URIs or to the manifest? The browser needs to redirect via the URI back to the app.

In your app you should have some code like - can you see that this is hit and report back on the codes?

```csharp
 protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);
        }
```

**Comment by stmoor** [comment]
@bgavrilMS yes the browser pops up, and the user selects a Microsoft account and then it immediately redirects back to the app. No changes to the redirect urls or the manifest. 

I could not find this piece of code on my app. Where should it go? I can add it.

**Comment by bgavrilMS** [comment]
Something like this https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.Droid/MainActivity.cs#L35

**Comment by stmoor** [comment]
@bgavrilMS  Okay, interesting. I ran the app today and it worked fine. Not sure what changed other than me adding this piece of code above. The requestCode was 0 and the resultCode was Adroind.App.Result.Ok.

**Comment by bgavrilMS** [comment]
Ok, thanks for confirming. As far as I remember, this hook gets invoked everytime a browser goes back to your app. MSAL then uses the data to extract an auth code which can be exchanged for a token.
