### ISSUE TITLE
Remove reference to System.IdentityModel

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#279]
Remove reference to System.IdentityModel, as suggested by @brentschmaltz

**Comment by brentschmaltz** [comment]
Yes please do, otherwise our asp.net customers will have issues.

**Comment by jmprieur** [comment]
We should not reference System.IdentityModel. We should be using Microsoft.IdentityModels.Tokens for crypto support and Microsoft.IdentityModels.S2S.Tokens for https (proof of possession) and token biding.
Same for ADAL.

**Comment by jmprieur** [comment]
the dependency is no longer there.
