### ISSUE TITLE
[Bug] WithForceRefresh Not working with WAM broker

### ISSUE THREAD

**Issue by vinhdp195** [AzureAD/microsoft-authentication-library-for-dotnet#2794]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.34.0 

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [o] Interactive
    * [o] Integrated Windows Authentication

Other:
UPW App is using WAM
I also use WithForceReresh(true)
However, WithForceReresh is not working properly
WithForceReresh does not provide new tokens immediately
New tokens can be obtained every 5 minutes
Why is that?

```csharp
                // Refresh token
                var pcaOptions = new PublicClientApplicationOptions
                {
                    ClientId = clientId ,
                    TenantId = tenantId 
                };

                var pca = PublicClientApplicationBuilder
                    .CreateWithApplicationOptions(pcaOptions)
                    .WithBroker()
                    .Build();

                var acc = await pca.GetAccountsAsync();
                var authenticationResult = await pca
                    .AcquireTokenSilent(SCOPES, acc..FirstOrDefault()).WithForceRefresh(true).ExecuteAsync();
```

**Comment by bgavrilMS** [comment]
This is correct, we do not pass the "force_refresh" flag to WAM. I will reach out to see if this is supported. 

What is the issue that you are trying to solve?

**Comment by vinhdp195** [comment]
> This is correct, we do not pass the "force_refresh" flag to WAM. I will reach out to see if this is supported.
> 
> What is the problem that you are trying to solve?
@bgavrilMS 
I have a function, it forces a token refresh, whenever it's activated
So, I need .withForceRefresh()

**Comment by bgavrilMS** [comment]
@vinhdp195 - why does your function need to force a token refresh? MSAL / WAM will always give you a valid token with at least a few min of expiry left.

**Comment by vinhdp195** [comment]
> @vinhdp195 - why does your function need to force a token refresh? MSAL / WAM will always give you a valid token with at least a few min of expiry left. We will do the refresh part for you if needed.

I already know how msal works
However, due to specific work reasons, it is forced to refresh the token
I would consider not using ForceRefresh

**Comment by bgavrilMS** [comment]
Ok thanks. The reason I am asking is that I don't remember WAM APIs supporting this flag, so we might need to make a feature request and it helps to understand the developer scenario when making feature requests.

**Comment by bgavrilMS** [comment]
We will not be fixing this. It is not recommended to force refresh.
