### ISSUE TITLE
[Bug] Unable to work without consenting tracking

### ISSUE THREAD

**Issue by Mikozans** [AzureAD/microsoft-authentication-library-for-dotnet#2797]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.35.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive

The app is in production, I haven't upgraded MSAL, but started seeing this issue.

I'm facing a problem with my app's Apple store submission.

This is what they are claiming:

> We discovered one or more bugs in your app. Specifically, after we tapped in “Don’t Allow”, no action occurred, and we were unable to access to the app.

I've tried to skip this prompt using "Prompt.NoPrompt" and it worked in previous submissions (the latest working one was in May) but not anymore.

So we have three issues here:

- Why Microsoft started tracking this kind of data?
- Clicking on "Don't allow" is preventing the user from logging succesfully.
- iOSHidePrivacyPrompt and NoPrompt are not working

Is there any workaround to be able to login (pressing scape seems to work) or just not showing the prompt?

**Repro**

```csharp
        SystemWebViewOptions systemWebViewOptions = new SystemWebViewOptions()
        {
          iOSHidePrivacyPrompt = true,
        };
        authResult = await publicClientApp.AcquireTokenInteractive(new[] { "wl.basic", "wl.signin", "wl.offline_access", "wl.emails" }).WithPrompt(Prompt.NoPrompt).WithSystemWebViewOptions(systemWebViewOptions).ExecuteAsync();

```

**Additional context / logs / screenshots**
![loginMSAL](https://user-images.githubusercontent.com/16270716/127151829-31f0d3a7-b749-4181-9f43-9e90b02d9c6e.png)

**Comment by bgavrilMS** [comment]
I asked the Apple dev team about this, waiting for a reply. 

To login, MSAL kicks off the system browser and navigates to `https;//login.microsoftonline.com/oauth/v2.0/authorize?scopes=foo&client_id=bar`.

**Comment by SameerK-MSFT** [comment]
>> Why Microsoft started tracking this kind of data?
The behavior has not changed from Microsoft side. Apple started prompting this from iOS 13.x+
>> iOSHidePrivacyPrompt and NoPrompt are not working
I will look into it.

**Comment by SameerK-MSFT** [comment]
I ran the sample "https://github.com/Azure-Samples/active-directory-xamarin-native-v2". It seems to run fine. Did you add ".WithUseEmbeddedWebView(false);"?

**Comment by Mikozans** [comment]
> Did you add ".WithUseEmbeddedWebView(false);"?

Yes, and still the same, prompt is shown (even with no prompt) and if I click on "Don't allow" I can't login.

This is my public client in case it helps: 
```csharp
var publicClientApp = PublicClientApplicationBuilder.Create(Constants.AAD_CLIENT_ID)
                                                          .WithAuthority(AadAuthorityAudience.PersonalMicrosoftAccount)
                                                          .WithLogging((level, message2, containsPii) =>
                                                          {
                                                            Debug.WriteLine($"MSAL: {level} {message2} ");
                                                          }, Microsoft.Identity.Client.LogLevel.Warning, enablePiiLogging: false, enableDefaultPlatformLogging: true)
                                                          .WithRedirectUri(Constants.AAD_REDIRECT_URI)
                                                          .WithIosKeychainSecurityGroup("com.microsoft.adalcache")
                                                          .Build();
```

**Comment by bgavrilMS** [comment]
Might be an OS update that disabled this? Feature or bug ? :)

Just to add a little context - the cookies stored in the browser after login does make the login experience better, as the user will not be asked to re-enter their username / password etc. We can this browser SSO. This is why the cookies are useful.

**Comment by SameerK-MSFT** [comment]
@Mikozans Thanks for sharing the creation code. I could repro it in the sample code after adding ".WithAuthority(AadAuthorityAudience.PersonalMicrosoftAccount)". 

It **reproduces only with my corp account and not with my personal Microsoft account**. Did you try login with both personal and corp account?
I will investigate in the meantime.

**Comment by bgavrilMS** [comment]
AadAuthorityAudience.PersonalMicrosoftAccount translates to `https://login.microsoft.com/consumers/` which means allow auth with "any MSA account". You should not able to login with an AAD (i.e. work and school) account when hitting the /consumers endpoint.

**Comment by Mikozans** [comment]
> AadAuthorityAudience.PersonalMicrosoftAccount translates to `https://login.microsoft.com/consumers/` which means allow auth with "any MSA account". You should not able to login with an AAD (i.e. work and school) account when hitting the /consumers endpoint.

Yes, I know. I have 2 different login options for Microsoft's accounts:

-  Microsoft Professional Account (works flawless with no prompt) -> .WithAuthority(AadAuthorityAudience.AzureAdMultipleOrgs)

-  Microsoft Personal Account -> .WithAuthority(AadAuthorityAudience.PersonalMicrosoftAccount)

**Comment by Mikozans** [comment]
Just to add more info, this seems to be the same issue: [https://answers.microsoft.com/en-us/outlook_com/forum/oaccount-oother/unable-to-log-on-to-any-microsoft-site-on-safari/fadf795c-9148-4e0e-9c94-70b87cf57441](url)

**Comment by Mikozans** [comment]
> @Mikozans Thanks for sharing the creation code. I could repro it in the sample code after adding ".WithAuthority(AadAuthorityAudience.PersonalMicrosoftAccount)".
> 
> It **reproduces only with my corp account and not with my personal Microsoft account**. Did you try login with both personal and corp account?
> I will investigate in the meantime.

Yes, but it only happens to me with personal accounts. the only differences between them in my code are the AadAuthorityAudience and scopes (user.read and user_impersonation in corp ).

**Comment by SameerK-MSFT** [comment]
Here are the findings with more options:
**AzureAdMultipleOrgs**
Corp account - no prompt no problem
Personal account - not allowed prompt not applicable

**AzureAdAndPersonalMicrosoftAccount**
Corp account - no prompt no problem
Personal account - no prompt no problem

It appears that the issue happens only when there is mismatch in the account type and the authority.

**Comment by bgavrilMS** [comment]
So there is no issue? Can we close this?

**Comment by bgavrilMS** [comment]
@Mikozans - can you please update your authority to smth like "https://login.microsoftonline.com/common" if you want to accept both AAD and MSA accounts? And also get rid of Prompt.None?

**Comment by Mikozans** [comment]
If I change it to AzureAdAndPersonalMicrosoftAccount there's another issue. 

I use different scopes depending if it's a corp account ({AadBackendId/user_impersonation", "user.read"}) or not ({ "wl.basic", "wl.signin", "wl.offline_access", "wl.emails" }).

So using AzureAdAndPersonalMicrosoftAccount  + { "wl.basic", "wl.signin", "wl.offline_access", "wl.emails" } throws 

> Error: AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'offline_access openid profile wl.basic wl.emails wl.offline_access wl.signin' is not configured for this tenant.
