### ISSUE TITLE
[Bug] GetAccountAsync not finding Guest account?

### ISSUE THREAD

**Issue by dmcweeney** [AzureAD/microsoft-authentication-library-for-dotnet#2799]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.35.0

**Platform**
Asp.Net Core 3.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [x] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.

**Expected behavior**
ConfidentialClientApplication.GetAccountAsync not finding a guest account which has been added to the cache.

**Actual behavior**
I'm seeing some funnies with MSAL.Net (4.35 and 4.29) with regards to Guest accounts. I tried on 4.29 with no success so upgraded to 4.35 and have encountered the same problem.

Let me preface this by saying I could be making a mistake here also.

I have an asp.net core 3.1 multi-tenant web app configured to use OIDC with AAD as the IDP.

When I am logging into the app as a Guest in the context of the guest tenant I am hitting the
https://login.microsoftonline.com/{guest-tenant-id}/oauth2/v2.0/authorize endpoint with response_type=code id_token.

The OpenIdConnect events execute as normal, I get the authorization code and call the AcquireTokenByAuthorizationCode flow which in turn adds it to the token cache.
The cache key I am using here is a combination of the oid and tid from the first tenant profile.

```
	TenantProfile tenantProfile = args.Account?.GetTenantProfiles().FirstOrDefault();
	string accountId = ClaimsPrincipalExtensions.CreateMsalAccountId( tenantProfile.Oid, tenantProfile.TenantId );

```
The reason being that my HttpContext.User's claims only include the oid and tid of the guest user/tenant.

The cache is updated and later when I want to aquire an access token to call the graph api I call the ConfidentialClientApplication.GetAccountAsync using the account identifier of the HttpContext.User and no accounts are found.

I have treble checked the token cache keys and it is the same key value that is being used in the AuthorizationCode flow and the GetAccountAsync/AcquireTokenSilent flow.

The GetAccountAsync logs the following:

```
[Cache Session Manager] Released cache semaphore
GetAccounts found 1 RTs and 1 accounts in MSAL cache. 
[Region discovery] WithAzureRegion not configured. 
[Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
[Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True. 
GetAccounts found 1 RTs and 1 accounts in MSAL cache after environment filtering. 
[Region discovery] WithAzureRegion not configured. 
[Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
[Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True. 
**Filtered by home account id**. Remaining accounts 0 
Found 0 cache accounts and 0 broker accounts
Returning 0 accounts

```
The "**filtered by home account id**" made me do a bit of looking and I see the GetAccountAsync is filtering on the home account values

```
public async Task<IAccount> GetAccountAsync(string **accountId**, CancellationToken cancellationToken = default)
{
    var accounts = await GetAccountsInternalAsync(ApiIds.GetAccountById, **accountId**, cancellationToken).ConfigureAwait(false);
    return accounts.SingleOrDefault();
}
```

But the accountid I am searching for is of a guest account and the home account id will be different!

Am I right in thinking this is the source of the problem and I will have to use GetAccountsAsync and filter myself?

Thanks, Donal

**Comment by bgavrilMS** [comment]
Do you use Microsoft.Identity.Web? 

@jennyf19 as she has this oid / tid problem fresh in her mind

**Comment by dmcweeney** [comment]
@bgavrilMS  no we do not use Microsoft.Identity.Web - it is on our backlog to move to it but would require a sizable amount of testing.

**Comment by jennyf19** [comment]
@dmcweeney was this working in previous versions? before 4.29?

**Comment by dmcweeney** [comment]
Hi @jennyf19 

It did not work in 4.29 but for a different reason.

When we were adding support for Guest accounts I noticed that 
- args.Account.HomeAccountId.Identifier is set for the AcquireTokenByAuthorizationCode flow.
- args.Account is null for the AcquireTokenSilent flow

However args.Account.HomeAccountId.Identifier does not work for the Guest account as it points to the "HOME" account details
and the AcquireTokenSilent will never find a token for the Guest user in the AcquireTokenSilent flow as the ClaimsPrincipal 
for the user will have the guest tenant id and guest user id, and we will not be able to create the correct cache key.

The reason for moving to 4.35 was so we can access the TenantProfile in the AcquireTokenByAuthorizationCode flow.

Also note that in the AcquireTokenByAuthorizationCode flow the ClaimsPrincipal will not have been set for the HttpContext.User.

I am on vacation this week but when I come back we can do a Teams meeting and I can show you this happening.

Thanks, Donal

**Comment by bgavrilMS** [comment]
It will be easier for you to move to Microsoft.Identity.Web. What you are doing now is reverse-engineering what we had to to do in MIW to get all of this working. 

The args have a `SuggestedCacheKey` property - you can use it for caching. Yes, it is set to account.HomeAccountId which is, as the name suggest, the **same** for home and guest account for the same user. But MSAL will do the right thing, it will cache the 2 separate ID tokens.

**Comment by jennyf19** [comment]
@dmcweeney I agree with @bgavrilMS. If you provide details on your scenario, we can provide links, etc...to help w/the migration, if needed. let us know.

**Comment by dmcweeney** [comment]
@jennyf19 @bgavrilMS  will try the upgrade ans see how it goes. 
I may need some assistance with the step up consent changes.

**Comment by bgavrilMS** [comment]
@jennyf19 - I believe this is a Microsoft.Identity.Web potential bug

**Comment by dmcweeney** [comment]
@jennyf19 - just wondering why MIW does not use the IConfidentialClientApplication.GetAuthorizationRequestUrl and should we be following suit?

**Comment by jennyf19** [comment]
@dmcweeney there is something wrong with the URI above, as `scope` and `scopes` are both listed. Can you provide a link to a repro?

**Comment by dmcweeney** [comment]
@jennyf19 I just called the ReplyForbiddenWithWwwAuthenticateHeader to see what it would return passing in the scopes I was requesting and the MsalUiRequiredException thrown by GetAccessTokenForUserAsync

            string consentUrl = $"{application.Authority}/oauth2/v2.0/authorize?client_id={mergedOptions.ClientId}"
                + $"&response_type=code&redirect_uri={application.AppConfig.RedirectUri}"
                + $"&response_mode=query&scope=offline_access%20{string.Join("%20", scopes)}";

            IDictionary<string, string> parameters = new Dictionary<string, string>()
                {
                    { Constants.ConsentUrl, consentUrl },
                    { Constants.Claims, msalServiceException.Claims },
                    { Constants.Scopes, string.Join(",", scopes) },
                    { Constants.ProposedAction, proposedAction },
                };

            string parameterString = string.Join(", ", parameters.Select(p => $"{p.Key}=\"{p.Value}\""));


You can see in the code it is adding in scope and scopes and not formatting it correctly.

**Comment by jennyf19** [comment]
@dmcweeney are you using this from a web app or a web API? It's designed for a web API, but not web apps.

**Comment by dmcweeney** [comment]
@jennyf19  I was trying it out from a web app - just kicking the tyres

**Comment by dmcweeney** [comment]
@jennyf19  @bgavrilMS  Just an update on this - I have implemented MIW and for the most part it was fairly straightforward. 

I had to take care of the consent myself - mainly because of the way our client and backend talk. 

In the signout I had to inject some code in the RedirectToIdentityProviderForSignOut to target the correct tenant signout endpoint - not organizations. 

Another thing I noticed in the OIDC signout is - if I am signed into the app against my home tenant and also signed in in a different browser as a Guest in a different tenant - and then sign out of one of the apps - the tokens for all get cleared from the token cache... (because it is using Home Account Id in key. Not sure if there is anything that can be done about this.

One other piece of feedback - AddMicrosoftIdentityWebApi can be a bit confusing as regards the 2 sets of options it takes, the duplication between them and what should be set where. Then EnableTokenAcquisitionToCallDownstreamApi also has options with some further duplication. The merge options code does give decent errors though!

**Comment by jmprieur** [comment]
Thanks @dmcweeney for your feedback.
we have a few questions for you. In general are there things that MSAL.NET or Microsoft.Identity.Web can do differently or better to support your scenario? (would it be more a Microsoft.Identity.Web issue?)

> I had to take care of the consent myself - mainly because of the way our client and backend talk. 
Can you please elaborate? what did you have to do? didn't the override of the prompt work?

> In the signout I had to inject some code in the RedirectToIdentityProviderForSignOut to target the correct tenant signout endpoint - not organizations.
Would you think we should we do it by default in Microsoft.Identity.Web? 

for the OIDC signout, I think it's by design.

Thanks for the feedback about `AddMicrosoftIdentityWebApi` complexity. We are trying to simplify things in this area. We also have https://github.com/AzureAD/microsoft-identity-web/issues/895 to improve at some point.

**Comment by dmcweeney** [comment]
Hi @jmprieur some feedback as promised and apologies for the delay.

I would have assumed that the default behavior for `GetAccessTokenForUserAsync` would have been to get the access token for the tenant that the current web app user is authenticated against - ie the tenantId specified in the `http://schemas.microsoft.com/identity/claims/tenantid` claim. I only discovered this was not the case **when I was logged in as a Guest user** and my AD user searches were returning results from my Home tenant! I guess the simplest fix here is to provide some additional documentation on the tenantId param to say that if not specified it defaults to the home tenant id.

On a similar vein I would have expected the web app signout to redirect to the tenant specific signout endpoint of the current authenticated web app user - instead the signout hits the organizations signout endpoint and if you are **logged in as a guest user** you get signed out of your home account. It would be helpful if MIW added in this behaviour by default.

Another variation of this issue exists in the RedirectToIdentityProvider for the incremental consent process **when signed in as a Guest user**. Our app is a web app/web api hybrid - and the `GetAccessTokenForUserAsync` is used behind a number of api calls. If the `GetAccessTokenForUserAsync`  fails because the user has not consented to the required scopes we return an known status which enables the ui to allow the user to choose if they want to start the incremental consent flow or not. 
We could not use the `AuthorizeForScopesAttribute` as it was picking up the wrong redirectUrl and not targetting the correct tenant id of the current authenticated Guest user. What would be useful for us is if 
	- the `IncrementalConsentAndConditionalAccessHelper` class was made public. 
	- the `BuildAuthenticationProperties` method took a redirectUrl param. 
	- And the consent flow targeted the tenant of the current signed in user (my hack here was to store the tenantId in the `AuthenticationProperties.Items` and check for it in the RedirectTo... )
	- another useful alternative would be to convert the logic in the `AuthorizeForScopesAttribute.OnException` into a public helper method.

The following are some additions/tweaks that would make my life easier…
	- Public accessible constants for the likes of "login.microsoft.com". 
	- Public accessible helper methods for building urls to the various authorize/signout/token endpoints also allowing for tenant specific endpoints.
	- Allow the developer specify a callback for when Cancel is clicked in the Consent/Inc Consent dialogs. I have my handling code in the `MessageReceived` event handler, but it would be simplier to manage this with optional callbacks.
	- Some documentation around the Issuer validation - in `AddMicrosoftIdentityWebApi`, I had to do a bit of rooting through the source code to find the correct way to initialize `ValidateIssuer`, `ValidIssuers`, `IssuerValidator`.

One last request - has the MIW team ever considered providing "mock" `IAuthenticationHandler` and "mock" `ITokenAcquisition` implementations for use in `TestServer` / integration test development?

Overall this is a super addition for web server/web app developers who use AAD. 
I know I was slow to move but it was well worth it.

Thanks, Donal

**Comment by bgavrilMS** [comment]
We recommend using Microsoft.identity.Web - version 2 now has support for ASP.NET classic as well as ASP.NET Core. Getting things to work for website using vanilla MSAL is pretty complex otherwise.
