### ISSUE TITLE
[Bug]  support for REGION_NAME env variable should be more resilient to user friendly region names

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2803]
msal 4.35.1

REGION_NAME env variable does not seem reliable. Azure Functions sometimes populate it with the long region name (which is unusable).

The solution is: 
`string region = Environment.GetEnvironmentVariable("REGION_NAME")?.Replace(" ", string.Empty).?ToLower();`

**Comment by jmprieur** [comment]
@bgavrilMS @SameerK-MSFT @pmaytak 
After discussing with the Azure function PM, I learnt that this is a standard conversion, and most places in azure tools to compute the short name region by stripping out whitespace and lowercasing the string. For example, CLI, ARM template processing, etc do that

So, the data we need is there in the REGION_NAME variable. And Matthew would assert that MSAL can and should be resilient to users (reasonably) passing in the versions with whitespace.

Therefore proposing to:
- close this issue.
- Or repurpose it to make the detection by REGION_NAME more resilient: in RegionManager.cs l 163, something like the following?

  ```CSharp
  string region = Environment.GetEnvironmentVariable("REGION_NAME")?.Replace(" ", string.Empty).?ToLower();
  ```

cc: @trwalke, @jennyf19, @henrik-me

**Comment by jmprieur** [comment]
Unless anybody objects proposing to move it back to the triage column
Changing the title

**Comment by dannybtsai** [comment]
@jmprieur, do you have an example of the REGION_NAME?

**Comment by jmprieur** [comment]
@dannybtsai 

"RegionName": "East US 2",
"RegionShortName": "eastus2"
