### ISSUE TITLE
[Feature Request] Allow developers to set SendX5C once, rather than on every single request, as SNI creds don't work without it. 

### ISSUE THREAD

**Issue by hpsin** [AzureAD/microsoft-authentication-library-for-dotnet#2804]
**Is your feature request related to a problem? Please describe.**
When setting up SNI with Azure AD, every single STS request must come with an X5C claim, otherwise the credential cannot be used.  Currently, developers are forced to mark up every single token request with "SendX5C", and if they miss one, the request will fail. It would be easier to indicate, while setting the client credential, that it is an SNI scenario and therefore X5C must always be included. 

**Describe the solution you'd like**
Per-application setting of X5C, rather than per-request. A per-request override is provided, although marked obsolete. 

**Describe alternatives you've considered**
We are improving the SNI error messages server side as well to cut down on the number of incidents and questions we get about failure to setup SNI in MSAL. Making it easy to find the SNI option in MSAL, however, will also help.  Making this dynamic 
 (so no setup is required) is not possible at this time. 

**Additional context**
There was a comment in the codebase about how things like certs should be captured per-request, since there are some requests that "don't need them".  I am unaware of such patterns (particularly, I don't know that such patterns don't exist in ADFS), but if one existed it would make a per-application pattern less feasible.

**Comment by bgavrilMS** [comment]
The only reason why a request would not need a cert if is the request can serve a token from its cache.

**Comment by bgavrilMS** [comment]
I think this makes sense, we can simply add:

```csharp
            IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder
                .Create(s_clientIdForConfidentialApp)
                .WithCertificate(cert, sendX5C = true)                
                .Build();
```

However, the problem with configuration options at both APP level and at REQUEST level is that they can conflict. In this case, if you'd set sendX5C to false in a request, but the app has it set to true, we'd just throw.


@hpsin - what if MSAL were to send the X5C claim all the time? Is this where you are saying that it cannot be done?

**Comment by hpsin** [comment]
> I think this makes sense, we can simply add:
> 
> ```cs
>             IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder
>                 .Create(s_clientIdForConfidentialApp)
>                 .WithCertificate(cert, sendX5C = true)                
>                 .Build();
> ```
> 
> However, the problem with configuration options at both APP level and at REQUEST level is that they can conflict. In this case, if you'd set sendX5C to false in a request, but the app has it set to true, we'd just throw.

I'd expect per-request setting to override the per-app setting, not to throw. (The request may fail, but we're doing what the dev asked for). See below for why we'd maybe want that. 
 
> @hpsin - what if MSAL were to send the X5C claim all the time? Is this where you are saying that it cannot be done?

This would have a perf impact if MSAL sent the claim in 100% of requests across all apps, the x5c claim isn't unnoticeable in size. This is me paying due respect to [Chesterton's Fence](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence) - I don't understand _why_ it wasn't done this way to start when the other SDKs do follow the pattern of setting it at an app level. I saw some comments in the code about how not all requests support sending an x5c header.  Since MSAL supports ADFS/AD/WIA/other non-OAuthy protocols, I wasn't sure if I'd mess them up by making it per app. 

>The only reason why a request would not need a cert if is the request can serve a token from its cache.

If this is the only reason to make it per-request, then I think we can safely make it per-app. That request, as you call out, doesn't need the cert, but having the cert there won't break anything (unless the cache somehow pivots off the credential used, in which case we can file another bug).

**Comment by bgavrilMS** [comment]
- [ ] Needs a consistency item and design
- [ ] Need to inform Azure SDK as it will simplify their model

**Comment by hpsin** [comment]
Perfect, thanks @bgavrilMS!
This was mostly driven out of azure SDK not having a solution readily evident for confidential clients (only client creds flows). 
I have updated the PR per comments, but still waiting on @jmprieur for some final updates before we call it ready I think

**Comment by bgavrilMS** [comment]
We can pick up the reminder work @hpsin, it will be faster this way.

**Comment by bgavrilMS** [comment]
After discussing with ESTS server folks, it looks like sending both X5C and X5T will introduce a perf penalty for 3rd parties, because X5C will be attempted first (and will fail - 3p cannot use X5C auth), then fallback to X5T. 

As such, I recommend we move back to @hpsin original proposal: 

- add a mechanism to turn X5C on at the app level, i.e. `WithCertficate(x509cert cert, bool sendX5C)`
- configuration at request level overrides config at app level

**Comment by jmprieur** [comment]
I like that this is not disruptive for current users.
Let's plan to update the 1p doc

**Comment by jmprieur** [comment]
Agreed:

- `.WithCertificate` will now takes a new `sendX5C` boolean with a default value of `false`
  > ```cs
  >             IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder
  >                 .Create(s_clientIdForConfidentialApp)
  >                 .WithCertificate(cert, sendX5C: true)                           
  >                 .Build();
  > ```

- `.WithClientClaims` will now takes a new `sendX5C` boolean with a default value of `false`
  > ```cs
  >             IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder
  >                 .Create(s_clientIdForConfidentialApp)
  >                 .WithClientClaims(cert, claimsDictionnary, sendX5C: true)                           
  >                 .Build();
  > ```
