### ISSUE TITLE
[Bug] Change OnActivityResult requestCode on Android from 0 (zero) to something else

### ISSUE THREAD

**Issue by mdobric** [AzureAD/microsoft-authentication-library-for-dotnet#2807]
**Logs and network traces**
MyMsalApp.MainActivity.OnActivityResult(int requestCode, Android.App.Result resultCode, Android.Content.Intent data)
Android.App.Activity.n_OnActivityResult_IILandroid_content_Intent_( Parameters)
Android.Runtime.DynamicMethodNameCounter.8( Parameters)

**Which version of MSAL.NET are you using?**
4.35.1

**Platform**
Xamarin Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ x ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
n/a

**Is this a new or existing app?**
Existing app

**Repro**

```csharp
        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);

            // requestCode is always 0
            AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(
                requestCode, resultCode, data);
        }
```

**Expected behavior**
I would like to provide the request code that is passed to the OnActivityResult() method on Android. My app handles various activity results and I use the request code to determine the action to perform. 

**Actual behavior**
The request code passed to OnActivityResult() is always zero.

**Possible solution**
Provide a way to pass in the request code when performing interactive login. If that's not possible, then at least change the current default from zero to a library provided constant value that's less likely to collide with existing request codes.

**Additional context / logs / screenshots**
n/a

**Comment by bgavrilMS** [comment]
We will not implement this unless msal android agrees to implement this.
