### ISSUE TITLE
Microsoft.Identity.Client.MsalServiceException: 'AADB2C90086: The supplied grant_type [client_credentials] is not supported

### ISSUE THREAD

**Issue by logcorner** [AzureAD/microsoft-authentication-library-for-dotnet#2812]
Hi 
Following the docs here https://docs.microsoft.com/en-us/azure/active-directory-b2c/application-types,  I can read the following  :

Current limitations > Unsupported application types > Daemons/server-side applications
........
Although the OAuth 2.0 client credentials grant flow is not currently directly supported by the Azure AD B2C authentication service

So , what the recommendations for scenarios where I have a backgroundservice that calls a web api protected by azure AD B2C ?

The background service should be registered in the azure AD B2C tenant using the client credentials flow but I think it is not possible using Azure AD B2C according to the docs.

The following code throws the error : 'AADB2C90086: The supplied grant_type [client_credentials] is not supported

```
       string clientSecret = "rhHe-R4h0~iKm~HHGGYYSSJb4IZ5cj0Rx-";
            IConfidentialClientApplication application = ConfidentialClientApplicationBuilder.Create(ClientID)
            .WithB2CAuthority(Authority)
            .WithRedirectUri(_redirectUri)
            .WithClientSecret(clientSecret)
            .Build();
IEnumerable<string> scopes = new string[] { "https:// {{myb2ctenant}}.onmicrosoft.com/ed8e231f-c5f7-495e-b00f-df6c4a67d5c1/.default" };

            var authResult = await application.AcquireTokenForClient(scopes)
            .ExecuteAsync();

```

**Comment by jmprieur** [comment]
@logcorner 
indeed, Azure AD B2C supports neither client credentials, nor on-behalf-of.

**Comment by logcorner** [comment]
> @logcorner
> indeed, Azure AD B2C supports neither client credentials, nor on-behalf-of.

Hi @jmprieur , thank you I read that is the documentation.
So how to authenticate a background service  that call an API protected by azure AD B2C ?
I think that the Azure AD B2C team should add such feature 
Regards

**Comment by jmprieur** [comment]
@logcorner 
yes we all agree. It's on their backlog.

**Comment by bgavrilMS** [comment]
Closing this, as there is nothing the SDK can do to help.
