### ISSUE TITLE
[Feature Request] [SPIKE] OBO for SP does not work when refreshing the RT

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#2817]
The spike should focus on reusing the existing APIs and the UserTokenCache. 

- [x] Do the existing OBO APIs make sense for SP?
- [ ] What does it take to refresh the RT?
- [ ] Should the API use the AppTokenCache?
- [ ] How will token caching be done? (e.g. cache keys)

**Comment by sean-yao** [comment]
Any ETA for supporting this?

**Comment by trwalke** [comment]
Seems like the PPE app we use to test this scenario suddenly starting working for the refresh flow scenario too. need to recreate apps in 1st/3rd party portal to test

**Comment by pmaytak** [comment]
Released in [4.43.2](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.43.2).
