### ISSUE TITLE
[Bug] AcquireTokenInteractive never returning

### ISSUE THREAD

**Issue by stmoor** [AzureAD/microsoft-authentication-library-for-dotnet#2827]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.35.0

**Platform**
Xamarin Forms

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
c. This is a new app or experiment.

**Repro**

```csharp
// Sign in method that gets called by  B2CAuthenticationService.Instance.SignInAsync();
  private async Task<AuthenticationResult> SignInInteractively()
  {
      AuthenticationResult authResult = await _pca.AcquireTokenInteractive(B2CConstants.Scopes)
          .WithPrompt(Prompt.SelectAccount)
          .WithParentActivityOrWindow(App.UIParent)
          .ExecuteAsync(); 

      return authResult;
  }

// Method where sign in is called. 
  async void OnLoginButtonClicked(object sender, EventArgs e)
  {
      AuthenticationResult result;
      try
      {
          var userContext = await B2CAuthenticationService.Instance.SignInAsync();
          await Navigation.PushAsync(new LogoutPage(userContext));
      }
      catch (MsalException ex)
      {
          if (ex.Message != null && ex.Message.Contains("AADB2C90118"))
          {
              result = await B2CAuthenticationService.Instance.ResetPasswordAsync();
              await Navigation.PushAsync(new LogoutPage(result));
          }
          else if (ex.ErrorCode != "authentication_canceled")
          {
              await DisplayAlert("An error has occurred", "Exception message: " + ex.Message, "Dismiss");
          }
      }
  }
```

**Expected behavior**
Expected that once the user signs, it will return to app. 

**Actual behavior**
It just hangs. It never hits the OnActivityResult method of the MainActivity in the android project. The screen just stays blank. 

**Additional context / logs / screenshots**
![image](https://user-images.githubusercontent.com/77985069/129447176-2b397ca9-a3e3-487c-a92a-bfab51148882.png)

**Comment by bgavrilMS** [comment]
This is ussually a configuration problem. Have a look at the sample https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-xamarin-native/integrate-azure-ad-b2c-xamarin-forms/
