### ISSUE TITLE
[Bug] AADSTS50196: The server terminated an operation because it encountered a loop while processing a request

### ISSUE THREAD

**Issue by ashinzekene** [AzureAD/microsoft-authentication-library-for-dotnet#2831]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.35.1

**Platform**
 .NET 4.5.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
    * [ ] Username Password
    
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
Trying to upgrade to MSAL from ADAL

**Repro**

```csharp
var securePassword = new SecureString();
foreach (char ch in passWord)
{
    securePassword.AppendChar(ch);
}
authResult = app.AcquireTokenByUsernamePassword(scopes, username, securePassword).ExecuteAsync().Result;
```
Also, trying to do this does not work because it seems the caching does not work
```csharp
var accounts = app.GetAccountsAsync().Result;
var scopes = new string[] { "user.read "};

AuthenticationResult authResult;
try
{
    authResult = app.AcquireTokenSilent(scopes, accounts.FirstOrDefault()).ExecuteAsync().Result;
}
catch (AggregateException ae)
{
    if (!(ae.InnerException is MsalUiRequiredException))
    {
        throw;
    }
    var securePassword = new SecureString();
    foreach (char ch in passWord)
    {
        securePassword.AppendChar(ch);
    }
    authResult = app.AcquireTokenByUsernamePassword(scopes, username, securePassword).ExecuteAsync().Result;
}
return authResult.AccessToken;
```

**Expected behavior**
`app.GetAccountsAsync().Result;` should return the previously logged in account

**Actual behavior**
`app.GetAccountsAsync().Result;` returns an empty list

**Comment by bgavrilMS** [comment]
By default, caching happens in memory. So if you restart your app, the cache will be destroyed. 

You can persist the token cache in an encrypted file. Here's a solution that works on Windows, Mac and Linux - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization#token-cache-for-a-public-client-application

**Comment by ashinzekene** [comment]
The app was not restarted

**Comment by bgavrilMS** [comment]
If you call `app.GetAccountsAsync().Result;` immediately after `AcquireTokenByUsernamePassword` returns a result, does it not return 1 account?

**Comment by ashinzekene** [comment]
The function was called multiple times and `app.GetAccountsAsync().Result;` kept returning an empty result even after successfully logging in

**Comment by bgavrilMS** [comment]
Do you re-create your PublicClientApplication object (app)? Unlike ADAL, the cache is not static, it is attached to the app object. If you create a new one, the cache will go away.

**Comment by ashinzekene** [comment]
Yeah, I think this is the issue
