### ISSUE TITLE
[Bug] Federated service at https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized. 

### ISSUE THREAD

**Issue by ashinzekene** [AzureAD/microsoft-authentication-library-for-dotnet#2833]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.35.1

**Platform**
 .NET 4.5.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
    * [x] Username Password
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
Trying to upgrade to MSAL from ADAL

**Repro**

```csharp
app.AcquireTokenByUsernamePassword(scopes, username, securePassword).ExecuteAsync().Result;
```

**Expected behavior**
Return successfully

**Actual behavior**
throws error

**Additional context / logs / screenshots**
```
There was an error parsing WS-Trust response from the endpoint. This may occur if there is an issue with your ADFS configuration. See https://aka.ms/msal-net-iwa-troubleshooting for more details. Error Message: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized. 
```
```

**Comment by bgavrilMS** [comment]
Are you internal @ashinzekene ? Can you post on the migration channel?

**Comment by ashinzekene** [comment]
What's the migration channel?

**Comment by bgavrilMS** [comment]
https://teams.microsoft.com/l/channel/19%3a3f112ecb27024f2682379a7af3667869%40thread.tacv2/ADAL.NET%2520to%2520MSAL.NET%2520Migration?groupId=7e394638-cacd-40c7-9e80-c4434c4c90df&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47
