### ISSUE TITLE
[Feature Request] Client Side higher level API POP support

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2844]
Currently, MSAL knows how to do access token POP using the low level API  `.WithProofOfPossession(popConfig)`, recommended only for `AcquireTokenForClient`. Higher Level constructs are needed on the client side: 

- [ ] Parsing `WWWAuthenticate` header for POP scheme details
- [ ] Parsing `AuthenticateInfo` header for 200 OK details
- [ ] A `DownstreamAPI` abstraction that selects between Bearer and POP and in case of POP injects the optional nonce from the `WWWAuthenticate` and `AuthenticateInfo` headers

The format of the headers is not well understood.

**Comment by rymeskar** [comment]
It would be great if the downstream API & related infra could also solve the mockability requirements [[1](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2449), [2](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1702)].

What I've also seen in the wild is customers struggling with the lifetimes of I..Clients. Whether they are intended per request or as singletons and how to hook up caches with them.  Encapsulations of these intricacies would be just great.

**Comment by bgavrilMS** [comment]
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3237 which is better spec'ed
