### ISSUE TITLE
[Feature Request] [SPIKE] Add support for multi-layered caching

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-authentication-library-for-dotnet#2845]
**Is your feature request related to a problem? Please describe.**
Add out-of-the-box extensibility for multi-layered caching. If necessary, this can result in a re-design of the caching API.

**Describe the solution you'd like**
Based on discussion with @bgavrilMS, the necessary features and considerations are:
* encryption in the distributed cache (with support of outage-free encryption key rollover)
* no binary/string serialization in local cache (the instances are kept in memory..).
* proper handling of private keys of `cnf`.
* [granular partitioning for all scenarios](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2826).
* [avoid concurrent instances](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2796) racing to refresh the cache value.
* [attempt pre-emptive refresh](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2795) when relevant.
* the solution should be re-usable with the 1P SAL solution.
* avoid unnecessary byte allocations (use object pools when relevant -- serialization, encryption, etc.) cc: @geeknoid.
* expose caching statistics/telemetry.

**Alternatives**
Identity.Web package provides [support of distributed cache](https://github.com/AzureAD/microsoft-identity-web/tree/master/src/Microsoft.Identity.Web/TokenCacheProviders).
There are the following shortcomings:
* does not serve all MSAL customers (has not the same targets)
* the package is [heavy-weight](https://github.com/AzureAD/microsoft-identity-web/issues/1336), bringing unnecessary ASP.NET Core dependencies
* some requirements/considerations cannot be implemented directly in Identity.Web and need to come from MSAL
* according to current design, would not serve 1P SAL

**Comment by rymeskar** [comment]
Is this feature still relevant?

**Comment by bgavrilMS** [comment]
THis has been completed, agreed.
