### ISSUE TITLE
[Feature Request] Disable cache syncronization for confidential client apps

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2848]
WithEnableCacheSynchronization is set to true by default, but can be set to false for a perf improvement on S2S / AppTokenCache.

**Comment by bgavrilMS** [comment]
I don't think so. The locking would only affect the AppTokenCache.

**Comment by jmprieur** [comment]
@bgavrilMS I realize i wasn't clear. I meant.
- app is deployed on several deployment slots.
- each deployed code has the same client ID and goes to the same distributed redis app token cache

**Comment by bgavrilMS** [comment]
This is a great question. If machine A and machine B compete for tokens, there is no way for MSAL to reconcile these anyway. The locking mechanism is in process and per application object only. The logic of AcquireToken* calls is: 

```
Lock
Read cache from Redis in memory
Unlock

If no token is found in the cache, get one from AAD

Lock
Read cache from Redis in memory
Merge new token
Write cache from memory to Redis
Unlock
```

By removing the locks, we can no longer guarantee the order of operations. I think this is fine for AcquireTokenForClient.

For the other scenarios, the problem I see is: 

- a Remove(Account) could potentially be missed
- a more powerful RT (with MFA) can be overwritten by a less powerful RT

Then again, these sort of problems are best left to eventual consistency. Any ideas on how we could experiment disabling syncronization for user token cache?

**Comment by maliksahil** [comment]
You can do distributed locks with Redis. Basically it is built around establishing a lock with an auto-release (see redlock algorithm) https://redis.io/topics/distlock
