### ISSUE TITLE
[Feature Request] Add an indication that the token cache is not used

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2850]
We can detect that the token cache is not used, for example by using the throttling idea: 

- take a hash of each successful request (hash most the request params, e.g. not the correlation ID)
- keep a static cache of [hash] -> [num_requests, last_request_date] (or use WilsonLRU dictionary which has eviction policies)
- if a certain threshold is met, start logging errors and emit telemetry

Note: we can limit this to AcquireTokenForClient for starters.

Alternative: discuss with ESTS to see if they have a Kusto query to achieve the same.

**Comment by maliksahil** [comment]
Why wouldn't AuthenticationResultMetadata.TokenSource be enough?

**Comment by jmprieur** [comment]
@maliksahil this would leave the burden to the app developer to check this property
what Bogdan has been proposing is that MSAL proactively detects that the cache is never used.

**Comment by maliksahil** [comment]
And if we detect cache is not being used, what do we do? Warning/error/something else?
Also - should this be a workbook in AAD instead of a feature in MSAL?

**Comment by jmprieur** [comment]
the proposal was to throw. As this would be a development mistake.
@bgavrilMS to keep me honest on this.
what does it take to have a workbook in AAD? do you have docs on it, @maliksahil ?

**Comment by maliksahil** [comment]
Yup here - https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-use-azure-monitor-workbooks

The workbook leverages a query, and shows information to the admin - so it won't cause an exception, but it will alert an admin of poorly written apps. We use workbooks for apps using ADAL for instance. As long as we can use a query to identify token cache not being used, we can easily author a workbook.

**Comment by jmprieur** [comment]
Thanks @maliksahil. For Azure AD premium SKUs.

**Comment by bgavrilMS** [comment]
Dropping in favour of higher level APIs
