### ISSUE TITLE
[Bug] AcquireTokenForClient throws Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0 in .Net Framework

### ISSUE THREAD

**Issue by ashinzekene** [AzureAD/microsoft-authentication-library-for-dotnet#2858]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.35.1.0

**Platform**
.NET 4.7

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [x] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
Migrating from ADAL to MSAL

**Repro**

```csharp
var scopes = new string[] { resource + "/.default" };
var cert = GetCertificateFromStore();
var app = ConfidentialClientApplicationBuilder.Create(appId)
    .WithLegacyCacheCompatibility(false)
    .WithCertificate(cert).Build();

var result = await app.AcquireTokenForClient(scopes).WithAuthority(authority).ExecuteAsync();

```

**Expected behavior**
Return token

**Actual behavior**
```
Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.. Exception Stack trace:    
  at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientCredentialWrapper credential, Boolean sendX5C)
   at Microsoft.Identity.Client.Internal.ClientCredentialWrapper.AddConfidentialClientParameters(OAuth2Client oAuth2Client, ICoreLogger logger, ICryptographyManager cryptographyManager, String clientId, Authority authority, Boolean sendX5C)
   at Microsoft.Identity.Client.OAuth2.TokenClient.AddBodyParamsAndHeaders(IDictionary`2 additionalBodyParameters, String scopes)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
```

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by ashinzekene** [comment]
Probably the same as this https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1258

**Comment by smartstoremx** [comment]
Dear All,

We are trying to get the  access token to use to request my own api. I am using Microsoft. Identity.Client nuget. version: 4.36.0

a) In Net core  MVC web application, unit test, console , Library projects works.
b) In Net framework 4.7.2 in unit test, console, library projects  works.

c) In MVC web application with net framework 4.7.2 do not work.  When you execute **await app.AcquireTokenForClient(scopes)** . It stay forever not response.

We did the following. you can replicate the problem.

1. Open visual studio 2019.
2. Create a new project using MVC web application net framework 4.7.2
3. Inside the home controller add the following code:

       public async Task<string> TokenGetAsync()
        {
            IConfidentialClientApplication app;

            app = ConfidentialClientApplicationBuilder.Create(" your AD client ID ")  
                   .WithClientSecret(" Secret ID ")  
                   .WithAuthority(new Uri("https://login.microsoftonline.com/ {domain name} .onmicrosoft.com"))
                   .Build();
            string[] scopes = new string[] { "https://{domain name}.onmicrosoft.com/xxxxxx/.default" };

            AuthenticationResult result = null;
            try
            {
                // **************Here stay for ever never return the token in MVC net framework 4.7.2******************
                result = await app.AcquireTokenForClient(scopes)
                    .ExecuteAsync();    
            }
            catch (MsalServiceException ex) when (ex.Message.Contains("AADSTS70011"))
            {
                   Console.WriteLine("Scope provided is not supported");
                   return "";
            }
            return result.AccessToken;
        }


        public ActionResult Index()
        {
            ViewBag.Token = TokenGetAsync().GetAwaiter().GetResult(); 
            return View();
        }

We need your help please.

**Comment by bgavrilMS** [comment]
@ashinzekene - .net 45 is going to be deprecated in a few months, so we are declining to fix this. 
The workaround is to sign your own assertion - see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Assertions#option-1---using-microsoftidentitymodeljsonwebtokens-library-recommended

**Comment by ashinzekene** [comment]
Sorry, It's .NET 4.7 not 4.5

@bgavrilMS

**Comment by bgavrilMS** [comment]
@ashinzekene - can you try to see if `certificate.PublicKey.Key.KeySize` works on your cert?

**Comment by ashinzekene** [comment]
Already upgraded .net version
