### ISSUE TITLE
WAM + B2C

### ISSUE THREAD

**Issue by charlesroddie** [AzureAD/microsoft-authentication-library-for-dotnet#2860]
Currently with B2C set up, a user choosing choosing a Microsoft login flow will get a web browser which doesn't remember usernames and passwords.

Attempting to use WAM runs into the limitation:

> https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam#wam-limitations
> B2C authorities are not supported

Is this limitation intrinsic to WAM or B2C, or is it something that MSAL can address?

**Comment by bgavrilMS** [comment]
This is a WAM limitation indeed.

**Comment by bgavrilMS** [comment]
Closing as there are no short / medium term plans for WAM to support B2C
