### ISSUE TITLE
[Feature Request] Help service owners by producing metrics to watch and warn them if they don’t respect the guidance

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#2869]
**Is your feature request related to a problem? Please describe.**
Partners and customers who don't follow the guidance on how to use the token cache or MSAL confidential client application lifecycle might run into problem such as:
- they will be throttled by AzureAd if they keep asking for the same token (if the cache is not used)
- they will run in perf issues if only the user token default cache is used (for the moment).

**Describe the solution you'd like**
Provide metrics and alerts, and guidance on what to watch, so that services know when they don't respect the guidance.
See details in [Alerting service owners when they implement bad practices.docx](https://microsoft.sharepoint.com/teams/aad/devex/Shared%20Documents/DotNetDocs/Alerting%20service%20owners%20when%20they%20implement%20bad%20practices%20draft.docx)

Metrics to observe can be placed in AuthenticationResult.AuthenticationResultMetadata so that the developer is able to monitor these during testing/production. Rule violations specifically can go into AuthenticationResult.AuthenticationResultMetadata.RuleViolations.
We will also log these metrics.

Rule Violations to monitor:
 - [ ] Token Cache is not being used and the same request is replayed continuously which will eventually lead to throttling
 - [ ] /common or /organizations is used for client credential flows
 - [ ] Token cache serialization is not used in web app / web api scenarios involving users

Other metrics to monitor:
 - [ ] An indication of when refresh in has been triggered
 - [ ] An indication of whether or not refresh in has failed as it runs on a background thread and only logs errors

**Comment by jmprieur** [comment]
See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2850 which could be part of the solution

**Comment by maliksahil** [comment]
Would it be possible to detect where someone should use a distributed cache, but isn't - and given an appropriate error message? For instance, a developer develops something on their machine (works on my machine), and pushes it to a load balanced farm (doesn't work there) -- can we give an obvious suitable error message?

**Comment by bgavrilMS** [comment]
We can only detect if cache serialization is used or not from MSAL. We don't know where bytes are stored. For web site and web app scenarios, we already issue a log.error if cache serialization is not used.

**Comment by bgavrilMS** [comment]
Other guidance ideas: 

- client_credentials over `common` or `organizations`
- use of WithAuthority at the request level, without setting WithAuthority at the app level (they will get into problems when they use a different cloud). 
- internal cache size hitting some upper limit?

**Comment by jmprieur** [comment]
- for WithAuthority at the request level, we would avoid the issue by having .WithTenant()

**Comment by trwalke** [comment]
One additional proposal is the use of telemetry to allow us to understand how MSAL is used. Perhaps we can gather usage data that will help us identify customers who are violating our guidance with some sort of Kusto query or even a dashboard. It also may be beneficial to add S360 items that will notify customers of bad practices. While it is certainly going to take some time to identify the best strategy for acting on this data, perhaps we can still start the initial steps of providing the data that indicates what customers are doing.

**Comment by jmprieur** [comment]
> Would it be possible to detect where someone should use a distributed cache, but isn't - and given an appropriate error message? For instance, a developer develops something on their machine (works on my machine), and pushes it to a load balanced farm (doesn't work there) -- can we give an obvious suitable error message?

> We can only detect if cache serialization is used or not from MSAL. We don't know where bytes are stored. For web site and web app scenarios, we already issue a log.error if cache serialization is not used.

@bgavrilMS : we cannot at detect where things are serialized at runtime. but we could detect by code analysis.

**Comment by maliksahil** [comment]
You could also detect situations such as "I am asking for a token when I shouldn't be - even if I am using the cache" or "I am running into deserialization issues" -- and create a support/troubleshooting guide, where one possible reason for this could be, you are using in-memory cache when you really should be using distributed cache.

**Comment by jmprieur** [comment]
What would be situations where i'm asking for a token when i shouldn't be, @maliksahil ?

**Comment by maliksahil** [comment]
> What would be situations where i'm asking for a token when i shouldn't be, @maliksahil ?

You should be renewing a token once every hour or so. If you find that you are frequently asking for a new access token sometimes every hour, but randomly much sooner (few minutes), is a sign that you are using in memory cache, when you should be using distributed cache.

**Comment by jmprieur** [comment]
I still don't understand why this is the sign you are using an in memory cache? do you mean if your app is restarted?

**Comment by maliksahil** [comment]
Think containerized apps, or load balanced apps - the individual instances are not sharing the in memory cache.

**Comment by bgavrilMS** [comment]
Done via telemetry
