### ISSUE TITLE
Pointless page 

### ISSUE THREAD

**Issue by jsquire** [AzureAD/microsoft-authentication-library-for-dotnet#2872]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET, [#23805](https://github.com/Azure/azure-sdk-for-net/issues/23805).

## Details

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0a1d89-3377-deef-faf6-8d73cba667e7
* Version Independent ID: 0d322b99-0aeb-8dcd-41be-0cadbd07d96b
* Content: [ClientApplicationBase.UserTokenCache Property (Microsoft.Identity.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.clientapplicationbase.usertokencache?view=azure-dotnet#Microsoft_Identity_Client_ClientApplicationBase_UserTokenCache)
* Content Source: [xml/Microsoft.Identity.Client/ClientApplicationBase.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/ClientApplicationBase.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bgavrilMS** [comment]
Hi @secatur @jsquire - can you please provide a repro ? This issue is not actionable.

**Comment by jmprieur** [comment]
@bgavrilMS : there is no XML comment, it does not tell how to use it ...

**Comment by bgavrilMS** [comment]
Got it, looks like "Summary' is bad casing, "summary" should be ok.
