### ISSUE TITLE
[Feature Request] Provide ability to turn off the default retry-once policy and recommend retry policy

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-authentication-library-for-dotnet#2877]
By default, MSAL retries http calls once on 5xx with [a delay of 1 second](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/ef3b2f61d9f0d441a1d2232ca2062a8d60e13437/src/client/Microsoft.Identity.Client/Http/HttpManager.cs#L162). 

**Scenario**
In expert and high traffic scenarios, customers might want to provide own retry strategies, retry periods and resilient http client strategies (circuit breaker).
The behavior within MSAL then intercepts with the logic that the clients might want to inject through [the WithHttpClientFactory](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractapplicationbuilder-1.withhttpclientfactory?view=azure-dotnet) configuration.

**Proposal**
Provide a knob to turn off the retry-once behavior of MSAL.

Note: see larger issue tracking this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3561

**Design**

While we could add a complex extensiblity point such as the one described [here](https://gist.github.com/mjcheetham/44880df497c147b1f90a73fe86f8a3b7), we recognize that retry libraries like Poly work perfectly fine at HttpClient level and Msal already exposes this layer. So the proposal is to add an overload to `WithHttpClientFactory`:

```WithHttpClientFactory(IMsalHttpClientFactory factory, bool disableDefaultRetryPolicy)```

We should provide docs on how to add retry policy for HTTP.

**Comment by bgavrilMS** [comment]
CC @trwalke

**Comment by bgavrilMS** [comment]
We will remove the default retry policy completely, as there are concenrns about retry storms. Apps should deal with retries.

**Comment by gladjohn** [comment]
MSAL 4.47.0 has been released, This issue is now fixed.
