### ISSUE TITLE
Add AndroidManifest.xml to sdk

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#288]
Add AndroidManifest.xml

**Comment by jmprieur** [comment]
Adding a manifest would allow to provide default capabilities that SDK needs to provide. If the SDK has its own manifest, developers would not have to check Internet (and other capabilities) in their own application manifest (as they would be merged)
Also in MSAL we use system.webview. Today the application developer needs to provide the redirect URL of the application. We might manage to have it in the SDK.
Native Android automatically compte the redirect URL for us. Look how it does it.

**Comment by henrik-me** [comment]
Closing this issue. Will track as user story on the backlog.
