### ISSUE TITLE
[Feature Request] Add support for Auth transfer to native AAD using transfer token

### ISSUE THREAD

**Issue by maliksahil** [AzureAD/microsoft-authentication-library-for-dotnet#2883]
**Is your feature request related to a problem? Please describe.**

Customers that need to support WAM with MSAPT are faced with the difficult task of either modifying an existing app registration, or creating a new app registration and go through preauthorization. Modifying the existing app registration is not always possible (https://docs.microsoft.com/en-us/azure/active-directory/develop/supported-accounts-validation) and even when possible is a manual process.

**Describe the solution you'd like**

Supporting  Auth transfer to native AAD using transfer token in MSAL.NET would allow 1P customers to create a new app registration and link it to their existing app registration and achieve MSAPT through WAM.

**Describe alternatives you've considered**

There are 3 alternatives,
a) Modify an existing app reg
b) Create a new client id
c) Auth transfer to native AAD using transfer token

**Additional context**

[Document](https://microsoft.sharepoint.com/:w:/t/Identity-DevEx/EatIUauX3c9Ctw1l7AQ6iM8B5CeBZxc58eoQCE0IuZ0VFw?e=nAdjfk&isSPOFile=1&wdLOR=c700F1A64-4873-3849-9AC4-C9D58B11D401)

**Comment by bgavrilMS** [comment]
In terms of public API, I suggest we add `MsaPassthroughTransferClientId ` to the existing `WindowsBrokerOptions`

```csharp

 var pca = PublicClientApplicationBuilder
                .Create(app_client_id)
                .WithBroker(true)
                .WithWindowsBrokerOptions(new WindowsBrokerOptions() {
                    ListWindowsWorkAndSchoolAccounts = true, // defaults to false
                    MsaPassthrough = true, // defaults to false
                    MsaPassthroughTransferClientId = "49FA1..." // new option defaults to null
                })

                .Build();
```

If `MsaPassthrough` is set to true and `MsaPassthroughTransferClientId` is not set, then we use the `app_client_id` to perform the transfer logic (this is alternative a) or b), where MSA-PT still needs to be used).

**Comment by maliksahil** [comment]
How much API pollution do we have around stuff that 3P developers will  never use? And is it a reasonable ask to put that in a separate nuget package intended for 1P devs? 

Or do we want to keep something like `.WithMsaPassthroughTransferClientId(..)` .. to perhaps one day facilitate such separation? Will PassthroughTransferClientId ever apply to non broker scenarios?

**Comment by bgavrilMS** [comment]
`How much API pollution do we have to have around?` It's a fair question. Today, we have at least 3 features which I believe we only offer to 1p: 

- regional auth (planned to go to 3p as well, not sure when)
- cert rotation support via SN/I (sendX5C) - no plans for 3p
- MSA passthrough options in WAM - no plans for 3p

Extracting the entire logic (API + implementation) in a separate packge would be pretty difficult, but doable. Extracting just the public APIs (i.e. implementation remains in MSAL) is not so difficult, but would require a breaking change.

**Comment by maliksahil** [comment]
Ok I will create an issue for this so we can discuss this and collectively decide if we want to further pollute the API surface/stop where we are/or undo the pollution. I don't know how big of a concern this is, but I cannot argue against keeping the API clean.

**Comment by bgavrilMS** [comment]
Won't fix, will reopen if a customer asks for this.
