### ISSUE TITLE
[Bug] Friendly error message when using regional with 3rd party app

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2884]
Is your feature request related to a problem? Please describe.
Partners try to run their services locally, and get the following exception:

AADSTS100007: Regional Cache Auth Service token requests for audience App that is not MSI are forbidden
and they are confused as this is not actionable.

Describe the solution you'd like

work with EVO to improve the error message and have it more actionable (with an aka.ms link) | my preferred option. @hpsin can we do that?
Describe alternatives you've considered
MSAL.NET could catch this particular error code and throw a more meaningful exception with an aka.ms link ... but that's not ideal

Additional context
Partners are also confused by the following message when debugging:

False MSAL 4.33.0.0 MSAL.Desktop Windows 10 Enterprise [07/01 18:26:29.13 - 2a8dbdf4-426d-41ee-b387-be0a650d1a00] [Region discovery] Auto-discovery failed.

we need to document that this is this a normal behavior.

- [ ] Regional is not currently supported by 3p. We need a good error message. 
- [ ] Contact other MSAL library owners and ask them to do the same
- [ ] Make sure the API review doc around regional is updated with this change.

**Comment by trwalke** [comment]
Waiting for service to update message

**Comment by henrik-me** [comment]
have no idea why my machine closed this one... re-opening

**Comment by bgavrilMS** [comment]
Server side error message has been updated to "AAD Regional ONLY supports auth either for MSIs OR for requests from MSAL using SN+I for 1P apps or 3P apps in Microsoft infrastructure tenants"
