### ISSUE TITLE
[Documentation] Fix Logging documentation about PII handling 

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-authentication-library-for-dotnet#2889]
**Documentation related to component**

The [MSAL logging documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-dotnet#configure-logging-in-msalnet) describes the PII handling behavior wrong.

"LogCallback is set to a delegate that does the logging. If PiiLoggingEnabled is true, this method will receive the messages twice: once with the containsPii parameter equals false and the message without personal data, and a second time with the containsPii parameter equals to true and the message might contain personal data. In some cases (when the message does not contain personal data), the message will be the same.
"
 is not true. The callback does not get fired twice, only [once](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/bd5609dbb504e4755079a010a2b2544f3a72ba6b/src/client/Microsoft.Identity.Client/Internal/Logger/MsalLogger.cs#L207) with either PII or no PII.

**Comment by jmprieur** [comment]
@trwalke please add to the observability spec.

**Comment by bgavrilMS** [comment]
I believe this is just a doc update - https://github.com/MicrosoftDocs/azure-docs/pull/81586

**Comment by bgavrilMS** [comment]
Fixed.
