### ISSUE TITLE
[Feature Request] Perf improvement around handling strings in logger

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-authentication-library-for-dotnet#2890]
[Logging APIs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/bd5609dbb504e4755079a010a2b2544f3a72ba6b/src/client/Microsoft.Identity.Client/Internal/Logger/MsalLogger.cs#L85) accept and create a tuple of a scrubbed message and a message that contains PII. This is wasteful as in the end only one string message is logged and the other string is just created and never used.

The proposal is to defer the creation of scrubbed/non-scrubbed message to a later stage of the logging pipeline so that only one string manipulation occurs. In the implementation, there might be overlaps with the feature request that proposes to have [granularized obfuscation mechanism](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2871).

**Comment by bgavrilMS** [comment]
All verbose log messages now use a lambda to create strings.
