### ISSUE TITLE
[Feature Request] [IOS] Xamarin Implement Conditional Access Grant Control “require app protection policy”

### ISSUE THREAD

**Issue by mafrank1** [AzureAD/microsoft-authentication-library-for-dotnet#2894]
**Is your feature request related to a problem? Please describe.**
We are using MSAL and Intune Xamarin library in our app. Both integrations are working in most cases, but we want to use the Conditional Access Grant Control “require app protection policy”. Based on the feedback of the Intune team the MSAL library does not provide this feature yet.

**Describe the solution you'd like**
Please integrate the Conditional Access Grant Control “require app protection policy” feature in the MSAL library and provide an release timeline.

- [ ] Create App for testing
- [x] Create IntunePolicyRequiredException
- [x] Trap Broker exception in Android
- [ ] Documentation of Android
- [ ] Ensure Keychain value is used for iOS
- [ ] Customize AcquireTokenSilent flow per platform
- [ ] Documentation of iOS

Estimate time to code complete: 10 days.

**Comment by tomzeni** [comment]
I have the same issue, please advise

**Comment by HannesVo** [comment]
I have the same issue, please advise us !

**Comment by mafrank1** [comment]
Any updates on this request?

**Comment by bgavrilMS** [comment]
We are exploring options for the future of Xamarin, as we are falling behind the MSAL Android and MSAL iOS teams. We are aware of this gap.

@henrik-me in case he knows more

**Comment by mafrank1** [comment]
@bgavrilMS Thanks for the update!
@henrik-me Are you have any timeline for the implementation? Is there any workaround for Xamarin based apps available?

**Comment by henrik-me** [comment]
@mafrank1 we do not have any timeline at the moment. we are re-evaluating previous approaches. We are going to spend the next 3 months to validate our newest approach leveraging a native implementation. The previous attempts for wrapping native implementations did prove to be to hard to build and maintain, We are cautiously optimistic that this new approach will be  successful.

@maliksahil @SameerK-MSFT

**Comment by Nicwalle** [comment]
Same issue here on iOS

**Comment by tomzeni** [comment]
any updates on this ?

@maliksahil @SameerK-MSFT @henrik-me

**Comment by mafrank1** [comment]
@henrik-me Just one question regarding your comment.

> For others reading, also want to remind that this is for App CA only, we support MDM via brokered auth today.

Do you mean that the current Xamarin implementation for iOS is supporting the Conditional Access compliance state check? If yes, is there any code example or documentation available?

**Comment by tomzeni** [comment]
@bgavrilMS @henrik-me 
are there any news, achievements, release dates or an new outlook?
can you please give an update on the current status in this regard. 
thanks a lot

**Comment by bgavrilMS** [comment]
Hi @tomzeni - we have started working on this. @SameerK-MSFT  will update the thread as needed. It's too early to give an estimate, and a lot of people are going on holiday etc. Probably early next year.

**Comment by SameerK-MSFT** [comment]
Tasks
- [ ] Create App for testing
- [ ] Create IntunePolicyRequiredException
- [ ] Trap Broker exception in Android
- [ ] Ensure Keychain value is used for iOS
- [ ] Customize AcquireTokenSilent flow per platform

**Comment by tomzeni** [comment]
@bgavrilMS @henrik-me 
can you please provide an brief update about the current status?  
Thanks a lot!

**Comment by tomzeni** [comment]
Hey @bgavrilMS thanks for offering me to test Android, but currently we have only an iOS App in development.

Looking forward to the iOS Version.

**Comment by robbo-aj** [comment]
Is there a timeline on when the iOS changes will be ready? We are about to write a LOB app for iOS and were hoping to support both MDM and MAM. Thanks

**Comment by SameerK-MSFT** [comment]
Created separate issue for Android - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3185

**Comment by bgavrilMS** [comment]
I'll let @SameerK-MSFT update the thread with details, especially around app provisioning.

TrueMAM support for iOS has been merged we'll release it with MSAL 4.42, possibly today or early next week, depending on testing.

**Comment by bgavrilMS** [comment]
ios support released in 4.42

**Comment by SameerK-MSFT** [comment]
@tomzeni  As @bgavrilMS mentioned, this functionality now has been provided in release 4.42. Please take a look. Regarding how to use it, here is unofficial blog that explains it. https://sameer.blog/2022/02/25/secure-resources-using-xamarin-and-intune-mam-sdk-on-ios/ and a dev app demonstrating it can be found here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/master/tests/devapps/Intune-xamarin-ios

**Comment by tomzeni** [comment]
Hey @SameerK-MSFT @bgavrilMS and Team, my first tests with 4.42 were all successful.
It just works! I'm happy AF. thank you so much for your effort fixing that issue. also for the great and well commented demo app. love u guys!
