### ISSUE TITLE
[Bug]  Broker Authentication in 4.36.1 is broken?

### ISSUE THREAD

**Issue by tomzeni** [AzureAD/microsoft-authentication-library-for-dotnet#2897]
**Logs and network traces**
"MSAL.Xamarin.iOS.4.36.1.0.MsalClientException: ErrorCode: uiviewcontroller_required_for_ios_broker" Microsoft.Identity.Client.MsalClientException: UIViewController is null, so MSAL.NET cannot invoke the iOS broker."

**Which version of MSAL.NET are you using?**
MSAL.NET 4.36.1

**Platform**
Xamarin iOS

**What authentication flow has the issue?**
Mobile, Interactive and with BrokerApp (MS Authenticator)

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL.

**Repro**
The Line of Code which raises the exeption is: 
IEnumerable<IAccount> accounts = await App.PCA.GetAccountsAsync();

**Expected behavior**
fill the IEnumerable<IAccount> accounts with list of Accounts

**Actual behavior**
"MSAL.Xamarin.iOS.4.36.1.0.MsalClientException"

**Additional context / logs / screenshots**
After updating from 4.35 to 4.36.1 we got an "MSAL.Xamarin.iOS.4.36.1.0.MsalClientException: ErrorCode: uiviewcontroller_required_for_ios_broker" Microsoft.Identity.Client.MsalClientException: UIViewController is null, so MSAL.NET cannot invoke the iOS broker."

The Line of Code which raises the exeption is: IEnumerable<IAccount> accounts = await App.PCA.GetAccountsAsync();
If downgrade to 4.35 everything works again... in both cases the uiviewcontroller is present....

Even the Demo App "2-With-broker" from https://github.com/Azure-Samples/active-directory-xamarin-native-v2 shows a similar issue after updating to Microsoft.Identity.Client version 4.36.1

Does 4.36.1 support Broker Auth? Please advise or fix this.

**Comment by jennyf19** [comment]
The sample you mention was tested  and updated in the 4.36 release, and 4.36.1 did not have anything impacting iOS or broker.  @SameerK-MSFT will take a look. Thanks for letting us know.

**Comment by tomzeni** [comment]
Thanks @jennyf19 for your help and investigation

the sample at https://github.com/Azure-Samples/active-directory-xamarin-native-v2 
consists of two demo projects "1-Basic" and "2-With-broker":
- "1-Basic" project > that one got updated to 4.36 release
- "2-With-broker" project > is still on 4.32 release (wondering if there is a reason for)

I've tested the "2-With-broker" project with different releases up to 4.36.1.
the 4.35.1 release is the last one "working" with broker. 4.36 and 4.36.1 did not work

**Comment by bgavrilMS** [comment]
Fixed in 4.36.2 which was just released.

**Comment by SameerK-MSFT** [comment]
@tomzeni please verify the fix. Thanks.
