### ISSUE TITLE
[Documentation] Update documentation to inform customers on how to monitor MSAL for potential issues

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#2915]
**Documentation related to component**
Observability

**Please check those that apply**

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**
It is critical for us to ensure all relevant documentation is updated to reflect the current and new observability options to ensure customers know what to look for in the logs/telemetry/metrics for the warnings/errors we produce. We need to be clear that logging should be enabled whenever possible as it is critical in the diagnosis of customer issues when they encounter one. If we can provide enough actionable information in the logs we can begin to reduce the number of customers asking for support. We also need to be sure to update ADAL to MSAL migration documentation so that customers are made aware of the new observability options when migrating. 

It must be clear:

- That enabling observability, whether it be logs/telemetry/metrics/etc, is critical to ensure MSAL is working correctly 
- What customers need to do to enable these observability options for monitoring
- Customers should strive to monitor these options whenever possible

Things to update:
MSAL Migration pages for first party
MSAL Migration pages for third party
Samples
Quick starts?

[Important Metrics](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability#add-monitoring-around-msal-operations)

[Logging](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging)

[Upcoming observability options](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/MSAL%20Observability/MsalObservability.md&version=GBtrwalke/MsalObservability&_a=preview)

**Comment by trwalke** [comment]
@jmprieur please modify as needed

**Comment by localden** [comment]
Closing as this is now here: https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/exceptions/msal-logging

If there are any specific requirements for monitoring/logging, a separate issue can be opened.
