### ISSUE TITLE
Microsoft.Identity.Client MSAL implementation to .Net Framework needs to cache the access token

### ISSUE THREAD

**Issue by kanagaraj2503** [AzureAD/microsoft-authentication-library-for-dotnet#2916]
We have migrated the ADAL to MSAL changes, where we are using public client app builder and confidential builder for two different purpose, where we need to cache the token for consequent request, could you please share how to cache the token in .Net Framework web application (not dotnet core)?

Found some article for desktop application token cache using file approach but feel that the file approach does not useful in our case, may need kind of memory cache approach.

Note : As I check the articles the Memory cache supported for all the .net core application but not .net framework (our framework version 4.6.1)

**Comment by bgavrilMS** [comment]
Hi @kanagaraj2503 

Yes, please have a look here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet

**Comment by bgavrilMS** [comment]
Can you please describe your scenario? How can a public client and a confidential client share the cache? What flows are involved and what did you do in ADAL?

**Comment by kanagaraj2503** [comment]
Hi @bgavrilMS -

I already gone thru the above given link [Token Cache](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet) but this needs Microsoft.Identity.Web whereas my current .net framework 4.6.1 does not support (it supports only .net core FX). 

my scenario is, create the public client token and cache for consequent call not required to share with confidential client.

Thanks.

**Comment by jmprieur** [comment]
@kanagaraj2503  did you try the new Microsoft.Identity.Web.TokenCache NuGet package? I has less dependencies. This should work for you: we added target frameworks  (.NET Standard 2.0)

For public clients, see https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=desktop

**Comment by bgavrilMS** [comment]
For now, use the solution @jmprieur suggests. 
In MSAL 4.37 (out in a few days), there will be an option to use a static in-memory cache in MSAL box.
