### ISSUE TITLE
[Bug] [Internal] Several unit tests related to background refresh fails sporadically

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2918]
ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async

Assert.IsTrue failed.

at Microsoft.Identity.Test.Unit.PublicApiTests.RefreshInTests.ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async() in \tests\Microsoft.Identity.Test.Unit\PublicApiTests\RefreshInTests.cs:line 148

This failed twice on 9/30 and I disabled it.

**Comment by pmaytak** [comment]
I think I fixed it in commit https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2893/commits/c934eee9c1322e21dcbb869449933ff1d6d37343. Had to do with refresh in jitter timing.

**Comment by MichelZ** [comment]
These tests are still disabled, right? If they don't get fixed, should they be deleted?

**Comment by pmaytak** [comment]
Yea, still disabled. They should get fixed. We weren't able to repro locally, only seem to happen on the build pipeline and not always.
