### ISSUE TITLE
[Bug] Fix potentially breaking changes in 4.37

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2927]
Most of the changes for 4.37 are now in, so I have produced a preview package. While inspecting for breaking changes via ApiReview tool, it looks like we have 1 breaking change and 1 API exposed which should not be exposed: 
 
 
Breaking change: we cannot ADD anything to interfaces as it will break existing implementation 
 Unintended API exposed: As per "framework design guidelines, <protected> is really the same as <public> in terms of visibility"
 

![image](https://user-images.githubusercontent.com/12273384/135646374-7a965125-667f-4b4e-915c-d54e99fa22aa.png)

**Comment by pmaytak** [comment]
@bgavrilMS `Validate` methods here follow the existing pattern. `AcquireTokenInteractiveParameterBuilder` already has protected `Validate` method.
`public abstract class AbstractAcquireTokenParameterBuilder` has `protected virtual void Validate()`, so `Validate` in child builder classes are protected override also. However, the child builder classes are public sealed with internal constructor.

However, `public abstract class AbstractApplicationBuilder` has `internal protected Validate`...
