### ISSUE TITLE
SetAuthenticationAgentContinuationEventArgs  NULL pointer exception.  MSAL Android Xamarin Forms

### ISSUE THREAD

**Issue by joelxxx** [AzureAD/microsoft-authentication-library-for-dotnet#2933]
Target: Android 11
Xamarin Forms   5.0.0.2125
Microsoft.Identity.Client 4.36.2
.NET Standard 2.1

We have a Xamarin forms app running on Android.
We can see in Azure Portal  -> Sign-in logs    
that the app came in and successfully signed in for this user in our tenant.

Calling this
AuthenticationAgentContinuationHelper.SetAuthenticationAgentContinuationEventArgs(requestCode, resultCode, data);

Throws an exception
{System.NullReferenceException: Object reference not set to an instance of an object.
  at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationAgentContinuationHelper.SetAuthenticationAgentContinuationEventArgs
(System.Int32 requestCode, Android.App.Result resultCode, Android.Content.Intent data) [0x0001c] in <660f095f2b6c44bfb44126a8f88e3177>:0 
  at SHACX.Droid.MainActivity.OnActivityResult (System.Int32 requestCode, Android.App.Result resultCode, Android.Content.Intent data) [0x00017] in C:\Users\safep\source\repos\SHACX\SHACX\SHACX.Android\MainActivity.cs:70 }

The call is being made as expected from an intent back from MSAL login in this function in the MainActivity, but crashed with a null reference somewhere in the library.

        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            try
            {
                AuthenticationAgentContinuationHelper.SetAuthenticationAgentContinuationEventArgs(requestCode, resultCode, data);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }
        }

**Comment by bgavrilMS** [comment]
Does this always happen?

**Comment by joelxxx** [comment]
Yes,  always happens.

**Comment by joelxxx** [comment]
Our login sequence runs on a separate runnable like this
        async void Java.Lang.IRunnable.Run()
        { 
        }

Invoked from MainActivity::OnCreate() like this
            Handler handler = new Handler();
            handler.PostDelayed(this, 1000);

**Comment by bgavrilMS** [comment]
Could you take a look at the sample first - it should work - https://github.com/Azure-Samples/active-directory-xamarin-native-v2
Try with embedded browser and system browser first. Then with broker if you want to enable that.

**Comment by joelxxx** [comment]
If I add the needed intent to   AndroidManifest.XML     and change these lines of code

                                // builder.WithSystemWebViewOptions(systemWebViewOptions);
                                builder.WithUseEmbeddedWebView(true);

Then the dialog "are you trying to sign into MYAPPNAME?" with a "cancel" and "continue"  works when I press "continue" and the login process is completing with a valid authresult and display of user's info.

Thank you for your help.

1.  Is my changing of the redirectURI correct and as you expected I would need to for single tenant Android ?
2.  Is changing the 2 options above in order to make the buttons on the "are you trying to sign into MYAPPNAME"? dialog have an effect an expected result , or is this a bug.  (the fact that the dialog buttons do nothing  if you don't change the above code).

**Comment by joelxxx** [comment]
Great help,  I will try the system browser.
...... This mostly works until I get to the "are you trying to sign into YOUR_APP"  with a cancel or continue.
Neither button does anything and you are stuck.

I think this is a bug and will open it in another issue.


Thank you for your help, my original problem is solved for this issue.



Note, in 
Azure Portal -> Active Directory -> app registrations -> your_app -> redirect URI's
choose "add a platform"
Choose "mobile and desktop applications"
Then pick the option for the redirect starting with msalxxxxxxxxxxxxx
