### ISSUE TITLE
[Bug] What means the error `AADSTS700026: Client application has no configured keys`?

### ISSUE THREAD

**Issue by eddynaka** [AzureAD/microsoft-authentication-library-for-dotnet#2938]
**Logs and network traces**
```
A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS700026: Client application has no configured keys.
Trace ID: a32ca39b-d3b3-4e22-bfb3-3ba256599400
Correlation ID: 1102ca62-1657-430d-8c46-b31b976750b7
Timestamp: 2021-10-08 13:49:52Z
```

**Which version of MSAL.NET are you using?**
4.29.0

**Platform**
ConsoleApplication using net472 or netcoreapp3.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
This is a new app or experiment.

**Repro**

```csharp
AuthenticationResult result = await app.AcquireTokenForClient(new[] { scope }).ExecuteAsync()
```

**Expected behavior**
Returning a well key or a specific error where the error is documented.

**Actual behavior**
Returning an error with an unspecified code, which isn't documented (at least, I didn't find anywhere).

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by bgavrilMS** [comment]
Hi @eddynaka - it's better to start from a sample as it will explain how to setup everything. What type of application are you building? A service that needs to call another service (i.e. no user involved) is documented under "daemon or service apps" - see https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#service--daemon 

Desktop app samples are here: https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#desktop
