### ISSUE TITLE
Delegate permission or let client application request scope for AAD B2C application

### ISSUE THREAD

**Issue by hegao15** [AzureAD/microsoft-authentication-library-for-dotnet#2943]
**Is your feature request related to a problem? Please describe.**
The Web API is the server application which registered from B2C tenant, while the user would create their own Client app to invoke with the Web API. However, the user could only register their Client app from default directory which must be different tenant with B2C. In this case, to delegate Web API to Client app seems impossible as they are from different tenant/directory.

**Describe the solution you'd like**
Expected to have a solution to delegate permission from AAD B2C application to Client app OR
The client could request a specified scope for the AAD B2C application and authenticate successfully by OAuth standard flow.

**Comment by bgavrilMS** [comment]
B2C now supports this flow - https://learn.microsoft.com/en-us/azure/active-directory-b2c/client-credentials-grant-flow?pivots=b2c-user-flow
