### ISSUE TITLE
[Bug] WAM does not work on Windows 2016

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2946]
MSAL 4.36.2

1. Use a domain joined Win Server 2016 machine
2. Call AcquireTokenInteractive
3. Choose an AAD account

Actual: the WAM window pops up but it is blank. After 10-20s the UserCancelled exception is reported (by WAM and surfaced by MSAL). 

**Actual**: after about a 20 second wait, the ResponseStatus is "UserCancel"
**Expected**: MSAL should fallback to a browser, like on Win8, because WAM does not work well on Win 2016

**Comment by bgavrilMS** [comment]
WAM does not work on Win 2016 because the AAD plugin does not return an Id Token. We need to disable it on WIn 2016 and fallback to a browser, similar to how we do on Win 8.

**Comment by sparkspriya** [comment]
Hi,
Any ETA for this issue fix?

**Comment by bgavrilMS** [comment]
Hi @sparkspriya - we are aiming to fix this with MSAL 4.39, in a few weeks time. Do note that we found that WAM won't work via MSAL on Win Server 2016, so our fix will essentially be for MSAL to fallback to a browser.

**Comment by rayluo** [comment]
> we found that WAM won't work via MSAL on Win Server 2016, so our fix will essentially be for MSAL to fallback to a browser

So, how will MSAL detect whether it is running on a Win Server 2016 machine? I'm asking this because MSAL Python would probably have to pick up the same logic, too. (CC @MSamWils : Will Mid-tier also not work on Win Server 2016, either?)

**Comment by bgavrilMS** [comment]
Hi @rayluo - the broker concept in MSAL should have some sort of "IsAvailable" property, because WAM is not available on Win7, Win8 etc. And Mac / Linux brokers are optional installs. If the broker is not available, the convention that we use in MSAL is to fallback to a browser. 

The reason why WAM is not available on Win Server 2016 is that the AAD plugin does not return an ID token. MSAL libraries don't really work with it. And WAM is not included on Win7, Win8 at all. 

Logic to detect Windows version is here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/DesktopOsHelper.cs
