### ISSUE TITLE
[Bug] Xamarin Forms , dialog "are you trying to sign in to appname"   cannot be dismissed with  system browser

### ISSUE THREAD

**Issue by joelxxx** [AzureAD/microsoft-authentication-library-for-dotnet#2949]
Target: Android 11
Xamarin Forms 5.0.0.2125
Microsoft.Identity.Client 4.36.2
.NET Standard 2.1

using the sample app here
https://github.com/Azure-Samples/active-directory-xamarin-native-v2
The basic-1 app.

Change the app to use a single tenant only.
   In app.cs provide an Authority
            PCA = PublicClientApplicationBuilder.Create(ClientID)
                .WithRedirectUri(specialRedirectUri?? $"msal{ClientID}://auth")
                .WithIosKeychainSecurityGroup("com.microsoft.adalcache")
                .WithAuthority(Authority)
                .Build();

  In AndroidManifest.xml add the needed intent for return url
      android:host="msauth://com.companyname.yourCompany/your_app_signature_key" />
  in azure portal for your tenant register the new app and the redirect URL as a "mobile and desktop applications" platform
     put the new client id from azure portal into the sample app

Stay with the "system browser" option

The login scenario works as expected until you get a dialog that says
"Are you trying to sign into your_app"
only continue if you downloaded the app from a store or website that you trust
"cancel"  "continue"

Pressing either button does nothing,  the page appears to reload to the same page.
the dialog cannot be dismissed and you are stuck.

If you change from "system web view"  to "embedded web view"
the same dialog comes up with the button working correctly and you can complete the login sequence
                                    //builder.WithSystemWebViewOptions(systemWebViewOptions);
                                    builder.WithUseEmbeddedWebView(true);

**Comment by SameerK-MSFT** [comment]
This can be threading issue in the app. Also for single tenant App, please specify TenantID in the builder.

**Comment by bgavrilMS** [comment]
I don't think this is a threading issue @SameerK-MSFT . The system webview is a bit tricky to configure. Please make sure you follow all the steps https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-android-considerations



The sample https://github.com/azure-samples/active-directory-xamarin-native-v2 is also useful, as it uses system browser by default. Please have a look at the manifest https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/main/1-Basic/UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml and the attributes on the activity https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/main/1-Basic/UserDetailsClient/UserDetailsClient.Droid/MsalActivity.cs

Does the sample also not work for you?
