### ISSUE TITLE
[Feature Request] Deprecate WithTemeletry and simplify MSAL internal operations

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2955]
MSAL 4.36.2

WithTelemetry is not used and it is unlikely that we will ever revive it. As such, we should deprecate it and simplify MSAL to eliminate some string operations etc. which make MSAL slow.

**Comment by pmaytak** [comment]
Was this fixed by [#3043?](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3043)
