### ISSUE TITLE
WithAzureRegion API has public documentation that points to URL requiring authentication.

### ISSUE THREAD

**Issue by jimmyca15** [AzureAD/microsoft-authentication-library-for-dotnet#2958]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/2a095c5a83a7abcf9ea7208cd2a0de085a18dc99/src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs#L256

This link included in the `WithAzureRegion` public API summary points to a URL that requires authentication. Seems unintended.

**Comment by jmprieur** [comment]
@jimmyca15 
For the moment, this API requires special app registration (not available yet to non-Microsoft services). This is expected at this point.
