### ISSUE TITLE
[Feature Request] Expose the region or error used by MSAL

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2975]
Part of AuthenticationResultMetadta, expose a `string RegionOrDiscoveryError` which is populated only if `WithAzureRegion` is used.

If region auto-detection failed, this metric should describe the reason (over and over again!)

{
 AuthenticationMetadata.RegionDiscoveryOutcome -> [RegionOutcome, Exception, RegionUsed]
}

**Comment by jennyf19** [comment]
@bgavrilMS can this be prioritized for upcoming release?

**Comment by bgavrilMS** [comment]
We were thinking to wrap up msal 4.38 and not start new work. Note that MSAL exposes `AuthentcationResultMetadata.TokenEndpoint`, which will include the region. Is this not enough?

**Comment by jennyf19** [comment]
I think having the entire token endpoint is not straightforward for people who don't know what they are looking for. If this is not needed, close the issue. Can you also remove the 4.38 milestone, if it won't be in that release? Thanks.

**Comment by pmaytak** [comment]
@bgavrilMS The amount of work should be minimal, but the clarity to users should be beneficial. I propose we take this in the next release (maybe even do a quick small one).

**Comment by bgavrilMS** [comment]
Ok
