### ISSUE TITLE
[Feature Request] Allow disabling TokenCache for Confidential clients

### ISSUE THREAD

**Issue by johnthcall** [AzureAD/microsoft-authentication-library-for-dotnet#2976]
**Is your feature request related to a problem? Please describe.**
My team uses confidential clients across millions of tenants and is currently creating a new confidential client application each request. We have been asked to start using a static confidential client application but have some reservations about the token cache implementation. It appears that the confidential client token cache has no eviction which will cause memory pressure in our service over time. We can obviously build the cache from the output of AcquireTokenForClient or via serialization events from ITokenCache but it appears in either case that the underlying token cache would still be populated.

**Describe the solution you'd like**
Add the ability for requests to configure that the entry should not be written to the built-in token cache or to configure the same on ConfidentialClientApplicationBuilder.

**Describe alternatives you've considered**
Continue using a unique confidential client application for each request and take the hit of regional discovery in each request when using "WithAzureRegion"

**Comment by bgavrilMS** [comment]
@johnthcall - if you want to maintain your own cache, for perf reasons, we understand. Ideally we would get MSAL into a place where it is more performant, but this will take time. 

If the token caches here https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet are not good enough, you can always implement your own token caching mechanism outside MSAL. 

There is no need to disable MSAL's token cache. Just don't configure any L2 token caching and let the `ConfidentialClientApplicationObjects` go out of scope.
