### ISSUE TITLE
ClinicalService.AcquireTokenInternalAsync throwing MsalClientException but not consistently

### ISSUE THREAD

**Issue by munkii** [AzureAD/microsoft-authentication-library-for-dotnet#2978]
**Logs and network traces**
```
Microsoft.Identity.Client.Internal
AuthCodeRequestComponent.VerifyAuthorizationResult (Microsoft.Identity.Client.UI.AuthorizationResult authorizationResult, System.String originalState)
Microsoft.Identity.Client.Internal
AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync (Microsoft.Identity.Client.UI.IWebUI webUi, System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal
AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
InteractiveRequest.GetTokenResponseAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.ApiConfig.Executors
PublicClientExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenInteractiveParameters interactiveParameters, System.Threading.CancellationToken cancellationToken)
```

```
ClinicalService.AcquireTokenInternalAsync (System.String[] scopes)
Microsoft.Identity.Client.MsalClientException: User canceled authentication. On an Android device, this could be due to the lack of capabilities, such as custom tabs, for the system browser. See https://aka.ms/msal-net-system-browsers for more information.

```

**Which version of MSAL.NET are you using?**
MSAL.NET 4.36.1

**Platform**
Xamarin Forms 5.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
This is an exisitng app
**Repro**

```csharp
        public async Task<IAuthenticationResult> AcquireTokenAsync(string[] scopes)
        {
            if (scopes is null)
            {
                throw new ArgumentNullException(nameof(scopes));
            }

            return await this.AcquireTokenInternalAsync(scopes);
        }

        private async Task<IAuthenticationResult> AcquireTokenInternalAsync(string[] scopes)
        {
            try
            {
                var account = await this.GetCurrentAccount();
                AuthenticationResult result = await this.pca.AcquireTokenSilent(scopes, account).ExecuteAsync();
                return new AuthenticationResultWrapper(result);
            }
            catch (MsalUiRequiredException)
            {
                // Acquire token interactively
                var parameterBuilder = this.pca.AcquireTokenInteractive(scopes);
                parameterBuilder.WithParentActivityOrWindow(this.uiParent);

                AuthenticationResult authResult = await parameterBuilder.ExecuteAsync();

                return new AuthenticationResultWrapper(authResult);
            }
            catch (Exception e)
            {
                this.logger.LogException(e, "ClinicalService - AcquireTokenAsync");
                throw;
            }
        }
```

**Expected behavior**
I would expect the pca.AcquireTokenSilent to fail and the parameterBuilder.ExecuteAsync() to succeed, after the browser pops up to get the user to enter credentials

**Actual behavior**
On a specific Android device HUAWEI P smart 2019 we are seeing the Exception being thrown but not consistently. We have **never** seen it happen with the debugger attached but when we deploy a prebuilt release package we do see it sometimes but not always.

I realise the text in the exception is trying to be helpful with "User canceled authentication. On an Android device, this could be due to the lack of capabilities, such as custom tabs, for the system browser. See https://aka.ms/msal-net-system-browsers for more information." but the problem does not happen every time on the same device so I am going to have to assume it is not a browser configuration issue

**Possible solution**

**Additional context / logs / screenshots**
The android device is running 9.0.1.188
The browser configurd on the device is Chrome

**Comment by bgavrilMS** [comment]
It's possible that Huawei phones do not have capable browser installed by default as per https://aka.ms/msal-net-system-browsers  - please ask the user to install a capable browser in this case.

Closing as known issue.
