### ISSUE TITLE
[Bug] Could not load file or assembly 'Microsoft.Windows.SDK.NET

### ISSUE THREAD

**Issue by pgarbo** [AzureAD/microsoft-authentication-library-for-dotnet#2982]
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Windows.SDK.NET, Version=10.0.17763.18, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Windows.SDK.NET, Version=10.0.17763.18, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker..ctor
at Microsoft.Identity.Client.Platforms.net5win.Net5WinPlatformProxy.CreateBroker(ApplicationConfiguration appConfig, CoreUIParent uiParent)
at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.FetchTokensFromBrokerAsync(String brokerInstallUrl, CancellationToken cancellationToken)
at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)

```

**Which version of MSAL.NET are you using?**
MSAL.NET 4.37.0

**Platform**
.NET 5

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
c. This is a new app or experiment.

**Repro**
as per https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-wam , TargetNetwork  is "net5.0-windows10.0.17763.0":
```csharp
var app = PublicClientApplicationBuilder
                .Create(clientId)
                .WithAuthority(authority)
                .WithRedirectUri(redirectUri)
                .WithBroker() 
                .Build();
 var accounts = await _app.GetAccountsAsync();
 var result = await _app.AcquireTokenInteractive(_scopes)
                .WithAccount(accounts.FirstOrDefault())
                .WithParentActivityOrWindow(new IntPtr(hwnd))
                .ExecuteAsync(); //this throws exception

```

**Expected behavior**
WAM (C:\Windows\SystemApps\Microsoft.AccountsControl_cw5n1h2txyewy\AccountsControlHost.exe) dialog shown, no exception thrown

**Actual behavior**
on some machines "Could not load file or assembly 'Microsoft.Windows.SDK.NET, Version=10.0.17763.18, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified." exception is thrown and WAM dialog is not shown.

**Possible solution**
a workaround is to not use .WithBroker() - then another authentication dialog is shown (C:\Program Files (x86)\Microsoft\EdgeWebView\Application\95.0.1020.30\msedgewebview2.exe)

**Additional context / logs / screenshots**
only on some machines. I understand if it cannot be replicated, but maybe someone has a clue why it happens and if not using .WithBroker makes sense?

**Comment by bgavrilMS** [comment]
Unable to reproduce.
