### ISSUE TITLE
querystring is too long error in uwp b2c app

### ISSUE THREAD

**Issue by bitquality** [AzureAD/microsoft-authentication-library-for-dotnet#2984]
Hi

We are using Microsoft.Identity.Client nuget library version 4.x and we are able to authenticate social identity providers like facebook and also some third-party ones using azure b2c userflows. While authenticating with our Azure AD SSO we get an error in the app which says "Requested query string too long". But on web we have NO such issue. 

with some research and support help forums from MS, we identified we need to modify the code from the app side and send a POST Request instead of GET so that SAML request will not error out.

Any idea if Microsoft.Identity.Client nuget library allows us to do that ?

We normally use code like below to initialize the and call acquire token methods.

```
`PublicClientApp = PublicClientApplicationBuilder.Create(AuthServiceConfiguration.ClientId)
                .WithB2CAuthority(AuthServiceConfiguration.Authority)
                .Build();

 AuthenticationResult authResult = await PublicClientApp.AcquireTokenInteractive(AuthServiceConfiguration.ApiScopes)
                    .WithAccount(GetAccountByPolicy(accounts, AuthServiceConfiguration.PolicySignUpSignIn))
                    .WithPrompt(Prompt.SelectAccount)
                    .ExecuteAsync()
```

**Comment by pmaytak** [comment]
@bitquality Which MSAL.NET version exactly do you use? We recommend to upgrade to the latest one (4.37.0).
I faintly remember we fixed a similar error before, but if you're on the latest version, this might be something else.
