### ISSUE TITLE
[Bug] Authentication restrictions with Azure AD on mobile app when using extended scopes

### ISSUE THREAD

**Issue by sowmini** [AzureAD/microsoft-authentication-library-for-dotnet#2989]
**Description of Issue**
We have a Xamarin Forms mobile application that authenticates the users against the Enterprise AD and uses MSAL to accomplish this. This mobile application also needs to access an internally developed Azure function, which is protected by AD (all the AD registrations lie within the same subscription).

**Enterprise Level CAPs enforced:** 
Baseline Mobile Policy includes:
- Managed device
- Requires Approved Client app

Below is the behavior that we observe when trying to login to the _mobile app using a Managed device_:

**1. MSAL with Scope "User.Read"**
Mobile app authenticates the user successfully. No baseline CAPs are applied when Scope = User.Read and user successfully logs in the app. 

**2. MSAL with Scope = "User.Read" and protected AD function scope (user_impersonation)**
Mobile app authenticates the user but fails authorizing them with the error - "You can't get there from here." with the below message that the app does not meet CAP. 
AADSTS530021: Application does not meet the conditional access approved app requirements
The CAP is treating the same app differently when we add the scope of our own functions. "Requires Approved Client App" condition gets triggered only when function scopes are added. 

**Which version of MSAL.NET are you using?**
Nugets: 
Microsoft.Identity.Client: 4.35.1
Microsoft.Graph: 4.1.0

**Platform**
Xamarin Forms 5.0.0.2012

**What authentication flow has the issue?**
*  Mobile
    * [ ] Interactive
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
New app

**Repro**
1. Use a SampleGraphTutorial Xamarin Forms App.
2. Edit the Scopes of the app to use User.Read + Scope of Custom API
3. Ensure that the scope of the AD registration of the Custom API is exposed so that the AD registration of the mobile app can access it. _[configuration done in Azure portal]_
4. Run the application and login using AD credentials

**Expected behavior**
Must successfully log in the user.

**Actual behavior**
Fails to login with the message: You can't get there from here. 

**Notes**
We want to understand the inconsistency in behavior with the same managed device, same application when run with different scopes.

**Additional context / logs / screenshots**
Errors: 
AADSTS530021: Application does not meet the conditional access approved app requirements

**Comment by bgavrilMS** [comment]
1. I believe that you have to use the broker on mobile to certify that the device is managed. See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-use-brokers-with-xamarin-apps
2. AAD cannot issue a token for 2 separate resources, in this case Graph and your custom api. Do you need both? if you do, you'll have to interactively get a token for resource 1 (e.g. Graph) and silently get a token for resource 2 (you web api). See `.WithExtraScopesToConsentTo`

**Comment by sowmini** [comment]
@bgavrilMS Thank you for your response. 

We were able to pinpoint the issue and it lies with the Conditional Access Policy that was enforced in our AD at the enterprise level. The "Require approved client app" does not authorize any custom app (in spite of wrapping with Intune and brokering auth through Intune Company Portal).
