### ISSUE TITLE
[Bug] Logs error about cache serialization even though one is provided?

### ISSUE THREAD

**Issue by Abrissirba** [AzureAD/microsoft-authentication-library-for-dotnet#2990]
**Logs and network traces**
12:58 [Error] [] : False MSAL 4.37.0.0 MSAL.NetCore .NET 5.0.11 Microsoft Windows 10.0.19043 [11-04 11:58:00.33 - 9c02650f-5821-42a0-97c6-a8a7f269e513] The default token cache provided by MSAL is not designed to be performant when used in confidential client applications. Please use token cache serialization. See https://aka.ms/msal-net-cca-token-cache-serialization.

**Which version of MSAL.NET are you using?**
MSAL 4.37.0.0 MSAL.NetCore .NET 5.0.11 Microsoft Windows 10.0.19043

**Platform**
.NET Core 5

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
We are using MSAL-angular to sign in to azure ad and the token is sent from the client to a web api endpoint that is protected by that. We are using msal for some endpoints and cookies for the rest.

**Is this a new or existing app?**
c. This is a new app or experiment.

**Repro**

```csharp
 var authBuilder = services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme);

            authBuilder.AddMicrosoftIdentityWebApi(Configuration)
                    .EnableTokenAcquisitionToCallDownstreamApi()
                        .AddMicrosoftGraph(Configuration.GetSection("DownstreamAPI"))
                        .AddInMemoryTokenCaches();

            authBuilder.AddCookie("Samla", options =>
            {
                options.Cookie.Name = "auth_cookie";
                options.Cookie.HttpOnly = true;
                options.Cookie.SameSite = SameSiteMode.None;
                options.SlidingExpiration = true;
                options.ExpireTimeSpan = TimeSpan.FromDays(14);
                options.Events = new CookieAuthenticationEvents
                {
                    OnRedirectToLogin = redirectContext =>
                    {
                        redirectContext.HttpContext.Response.StatusCode = 401;
                        return Task.CompletedTask;
                    },

                };
            });
```

**Expected behavior**
No errors is expected in the log if we add .AddInMemoryTokenCaches()

**Actual behavior**
Getting errors in the log saying that a cache serialization has not been provided

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by pmaytak** [comment]
Thanks, @Abrissirba, what Microsoft Identity Web version do you use?

@jmprieur Should we remove this warning altogether now, since default user and app caches are partitioned and in-memory caches from Identity Web offer eviction options?

**Comment by bgavrilMS** [comment]
@pmaytak - I think we should continue to log an error if app developers are using web app or web api. But stop logging this error for client_credentials.

**Comment by xxAtrain223** [comment]
I'm seeing this bug in Microsoft.Identity.Web 1.20.0 with a similar Startup:
```csharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraph(Configuration.GetSection("GraphAPI"))
    .AddInMemoryTokenCaches();
```

**Comment by jmprieur** [comment]
@bgavrilMS @pmaytak maybe this error should not appear in ASP.NET Core developer mode

**Comment by bgavrilMS** [comment]
@jmprieur - do you mean by reading ASPNETCORE_ENVIRONMENT  env variable?

**Comment by Abrissirba** [comment]
I would prefer to be aware of all potentiall errors in development and not being suprised by it when I go to production. 

I am using 1.20.0 of Microsoft Identity Web

**Comment by jmprieur** [comment]
> @jmprieur - do you mean by reading ASPNETCORE_ENVIRONMENT env variable?

Yes, for instance.

**Comment by bgavrilMS** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs#L358


Having looked at this in more detail, it looks like we are logging this error in the correct place: 

- confidential client flows except `client_credentials`
- if cache serialization is not enabled.

But the error message is not good: 

- "The default token cache provided by MSAL is not designed to be performant when used in confidential client applications. Please use token cache serialization. See https://aka.ms/msal-net-cca-token-cache-serialization."

It should say: 

- "Only in-memory caching is used. The cache is not persisted and will be lost if the machine is restarted. It also does not scale for a web app or web api, where the number of users can grow large. Production apps should use distributed caching. See https://aka.ms/msal-net-cca-token-cache-serialization".

**Comment by ptrotter1** [comment]
Should this be a warning or info instead of an error? The docs say `AddInMemoryTokenCaches` is fast and fine in production if you don't mind losing the cache on server restart. My use case is an Intranet application with less than 50 users.

**Comment by xxAtrain223** [comment]
My use is similar, Intranet application with about 5 users. This also seems like it would be better suited as a compile time warning instead of a runtime error/warning. Is there an existing analyzer that this could be added to?

**Comment by BobBonser** [comment]
I agree, this should be a warning not an error.

**Comment by bgavrilMS** [comment]
Ack, we can log a warning instead.
