### ISSUE TITLE
[Bug] sub_code not being extracted for errors passed on RedirectURI

### ISSUE THREAD

**Issue by crmann1** [AzureAD/microsoft-authentication-library-for-dotnet#2991]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
4.37.0.0

**Platform**
.NET

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
Visual studio

**Repro**

Start a sign in flow. Click the back button on the first page. 

**Expected behavior**
sub_code should be extracted and provided as part of MSALServiceException OR 
the operation should be treated as a user cancel.

**Actual behavior**
An access_denied error is returned but cannot differentiate between a real access denied and a cancel.

**Possible solution**
Redirect URI after pressing back
https://login.microsoftonline.com/common/oauth2/nativeclient?error=access_denied&error_subcode=cancel

Extract the subcode and attach to the AuthenticationResult and thereby the MSALServiceException
error_subcode=cancel

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
Side note. For other cases (When UI required), the sub_code is supposed to be exposed via the `UiRequiredExceptionClassification`. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MsalUiRequiredException-classification#msaluirequiredexception-classification

Thanks @crmann1 for this heads-up
The cancel was something processed entirely by the UI (server side), not MSAL, and didn't return anything that MSAL could use. Thanks for noticing that the redirectURI has a fragment with the information (not sure if this is new, or if we didn't think earlier we could use it).

In term of design. Which exception would you see used?
MsalServiceException? 
Or a new MsalUserCancelledException?

**Comment by crmann1** [comment]
Don't think it matters, we just need it so that we can classify our telemetry properly and not show the user an error when it really is a cancel.

Ideally sub_codes would exist on any exceptions thrown where they are sent from the server.
In this case since we know the user cancelled the cancel exception would be good.

**Comment by SameerK-MSFT** [comment]
IMO, it is better to have new "MsalUserCancelledException", as this is not really a service exception; but an operation canceled by the user. It will bring clarity. Thinking broadly, can we call is MsalUserDidNotApprove exception? It will serve in two cases user cancellation and timeout. We can have a subside specifying the case. That will avoid too many exceptions and server two scenarios.

**Comment by crmann1** [comment]
I think MsalUserCancelledException is enough, it tells the intent. I think the more broadly named one is a bit verbose.  But in the spirit of that maybe MsalRejectedByClientException?

**Comment by henrik-me** [comment]
inheriting from the MSALClientException?

**Comment by jmprieur** [comment]
Yes, to be compatible with the current behavior?

**Comment by SameerK-MSFT** [comment]
1. Ran NetFxConsoleApp
2. Made sure that the broker is not used (option b)
3. In the interactive login (Option 4), Closed the login window.

It throws MSALClientException with code "authentication_cancelled." We have the functionality; but not as a specialized exception. 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/exceptions

Do we still need specialized exception?

**Comment by SameerK-MSFT** [comment]
@crmann1 can you please validate, if you are using the same scenario/API and if so, is the above OK for you?

**Comment by bgavrilMS** [comment]
I think the more detailed repro steps are as follows: 

1. Use a .NET classic desktop app
2. Configure the *system browser*:

- redirect uri "http://localhost"
- `.WithUseEmbeddedWebview(false)`

3. AcquireTokenInteractive
4. When the *system* browser pops up, click back

**Actual**: MSALServiceException 
**Expected**: MsalClientException with error_code "user_cancelled" (to be consistent to the sceanario of embedded browser + user hits close button)

**Comment by bgavrilMS** [comment]
I think @crmann1 is referring to the "back button" on the login page: 

![image](https://user-images.githubusercontent.com/12273384/140718992-fb966729-9039-4678-8432-0c6e43b571bb.png)

It's easier to see what's happening with Fidler or by using the system webview - the browser redirects to `http://localhost:54752/?error=access_denied&error_subcode=cancel&state=ae17a813` if the user clicks "Back"

In my opinion, the Back button should not be displayed on this page, because this is the first page. If the user hits "Back", they do not necessarily mean to cancel authentication.

@crmann1 - I suggest you ICM ESTS > ESTS (it's better if you do it, not us) so that they can remove this button from the first page / account selector page. If it is not technically possible, we see about fixing it in MSAL by translating this error to the "user_cancelled" MsalClientException. I do not think we'd need another exception type for this.

**Comment by jmprieur** [comment]
@bgavrilMS : can't we take Chris's suggestion? Now that ESTS sends a fragment in the redirect URI (`?error=access_denied&error_subcode=cancel`). Providing a meaningful exception is something when the authentication is cancelled one way or another, is something we had many requests about

**Comment by jmprieur** [comment]
no or course, no, only when the subcode is cancel

**Comment by bgavrilMS** [comment]
So it looks like AAD will fix this issue on their end, as @SameerK-MSFT, who is on the insider ring, cannot repro. Not sure when the changes will make it to prod.

We can still fix this, by just throwing the same MsalClientException with the error code "user_cancelled" as before. Not sure it's worth coming up with a new exception type.
