### ISSUE TITLE
[Feature Request] Provide a way to debug dump the sanitized cache

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2996]
The MSAL team sometimes need to look in the token cache to understand bugs reported by app developers. This is not always possible because of compliance issues. To workaround it, MSAL should have a mechanism to sanitize the cache and dump it. 

To achieve this: 

- [ ] On SaveTokenResponseAsync, if verbose logging is enabled and if token cache serialization is enabled, dump the first 10 **keys** of MsalAccessTokenCacheItem. Also dump the total number of AT, RT, IdTs and Accounts.
- [ ] If PII is enabled, do not log the home_account_id part of the key

**Comment by jmprieur** [comment]
I also wonder if having just the number of elements in each collection could help in some cases?

**Comment by bgavrilMS** [comment]
That we could log as info every time. And if there are many items, we can log as warning.

**Comment by bgavrilMS** [comment]
This was done. We are displaying the first 10 access tokens and refresh tokens that are found in the cache when logging is set to verbose mode.
