### ISSUE TITLE
support Resiliency for outages

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#3]
Add support for resiliency/client heuristics for outages

**Comment by kpanwar** [comment]
case ERROR_HTTP_STATUS_SERVER_ERROR:    //500
   case ERROR_HTTP_STATUS_BAD_GATEWAY:     //502
   case ERROR_HTTP_STATUS_SERVICE_UNAVAIL: //503
   case ERROR_HTTP_STATUS_GATEWAY_TIMEOUT: //504

**Comment by jmprieur** [comment]
In Adal we support from 500 to 599 inclusive and network timeout. 
Msal has a network timeout retry built-in
Also Adal supports the lifetimeextended => that's resiliency.

**Comment by jmprieur** [comment]
In progress: PR is https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1331

**Comment by jennyf19** [comment]
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).
