### ISSUE TITLE
[Bug] Setting ListWindowsWorkAndSchoolAccounts to false does not prevent the account picker from showing those accounts

### ISSUE THREAD

**Issue by exchange321** [AzureAD/microsoft-authentication-library-for-dotnet#3001]
**Logs and network traces**
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.08 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] MSAL MSAL.Desktop with assembly version '4.37.0.0'. CorrelationId(eca8fc49-7be5-4ac3-860a-4cd57384c89e)
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.13 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent: 
Prompt: select_account
HasCustomWebUi: False

Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.17 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] 
=== Request Data ===
Authority Provided? - True
Scopes - User.Read openid email profile offline_access
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - True
HomeAccountId - False
CorrelationId - eca8fc49-7be5-4ac3-860a-4cd57384c89e

Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.20 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] === Token Acquisition (InteractiveRequest) started:
	 Scopes: User.Read openid email profile offline_access
	Authority Host: login.microsoftonline.com
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.23 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] [Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.26 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] Fetching instance discovery from the network from host login.microsoftonline.com. 
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.90 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] Authority validation enabled? False. 
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.93 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] Authority validation - is known env? True. 
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:35.97 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] Broker is configured. Starting broker flow without knowing the broker installation app link. 
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:36.06] [WAM Broker] Using desktop as a parent window.
Info => False MSAL 4.37.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/11 03:00:36.10 - eca8fc49-7be5-4ac3-860a-4cd57384c89e] Can invoke broker. Will attempt to acquire token with broker. 

**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.37.0
Microsoft.Identity.Client.Desktop 4.37.0

**Platform**
WPF .NET 4.8

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
This is a new app under development.

**Repro**

```csharp
using Microsoft.Identity.Client;
using Microsoft.Identity.Client.Desktop;

IPublicClientApplication Client = PublicClientApplicationBuilder.Create(AzureActiveDirectoryClientId)
	.WithWindowsBroker()
	.WithWindowsBrokerOptions(new WindowsBrokerOptions { ListWindowsWorkAndSchoolAccounts = false, MsaPassthrough = false })
	.Build();

AuthenticationResult result = await Client.AcquireTokenInteractive(AzureActiveDirectoryScopeRequested)
	.WithPrompt(Prompt.SelectAccount)
	.ExecuteAsync();
```

**Expected behavior**
As `ListWindowsWorkAndSchoolAccounts` is set to `false`, the account picker should not list and use any work or school account.

**Actual behavior**
Work or school accounts are listed and an option to use work or school account is shown.

**Additional context / logs / screenshots / links to code**
The account picker shown:
![image](https://user-images.githubusercontent.com/8732662/141230545-28dc2df8-4218-4ac1-9a65-544f09640207.png)

**Comment by bgavrilMS** [comment]
Yes @exchange321 , this is by design. We don't have too much control over the Account Picker UI, but it behaves similarly to how the browser behaves. 

If you set `ListWindowsWorkAndSchoolAccounts` to true (by default it's false), the `GetAccounts()` will return you the list of Work And School accounts that are configured in Windows. You can try to silently log in with those.

**Comment by bgavrilMS** [comment]
If you want your app to work only with personal accounts, please set your authority to `https://login.microsoftonline.com/consumers`

**Comment by exchange321** [comment]
👍 it works! Thanks @bgavrilMS!
