### ISSUE TITLE
[Bug] Pop token does not rotate properly for CCA

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3003]
When using a CCA and enabling POP, MSAL will not rotate the key for the default POP provider after 7 hours if the CCA has not been recreated.

**Which version of MSAL.NET are you using?**
Latest

**Platform**
.NET FWK/.NET Core

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Repro**

Create a CCA and enable POP.
Acquire a POP token
acquire another POP token after 8 hours and notice the token is retrieved from the cache

**Expected behavior**
MSAL should rotate the key when default crypto provider is used.

**Actual behavior**
The same key is used for the lifetime of the app

**Comment by bgavrilMS** [comment]
was fixed

**Comment by SameerK-MSFT** [comment]
Fixed in [MSAL 4.40.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.40.0)
