### ISSUE TITLE
Hybrid SPA Sample and DOC updates

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3006]
Feature is described here: https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/3922?_a=files&iteration=17&base=16

Feature has already been implemented in MSAL.Net. This is a tracking item for, 

- Add New Samples for the e2e scenario
- Update existing samples, if any
- Update Documentation 

This is a tracking item for samples and docs for the Hybrid SPA feature

MSAL ,Net PR : https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2981

**Comment by jmprieur** [comment]
@bgavrilMS @gladjohn : do we think that the doc is done? (not sure if that should be in the fixed column yet)
