### ISSUE TITLE
[Feature Request] Provide a correlation id as part of cache callback

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-authentication-library-for-dotnet#3008]
The cache callback parameters today do not include correlation guids. It is worthwhile to also pass the correlation id for tracing purpose as part of the [TokenCacheNotificationArgs ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.tokencachenotificationargs?view=azure-dotnet).

**Comment by jmprieur** [comment]
@trwalke : I think it's worth adding this one to the observability spec as well

**Comment by bgavrilMS** [comment]
We should probably expose the LogCallback as well. This will allow token cache implementations to use MSAL's logging infra. Tracked in this discussion: #3010
