### ISSUE TITLE
[Feature Request] Separate refresh token cache from access token cache

### ISSUE THREAD

**Issue by jesperkristensen** [AzureAD/microsoft-authentication-library-for-dotnet#3011]
**Is your feature request related to a problem? Please describe.**
I have implemented https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview which calls `AcquireTokenByAuthorizationCode` when the user logs in and calls `AcquireTokenSilent` when calling an external API.

I have reached the step where I need to select a token cache. I am given two options, both are not optimal:
* In memory caching: The user's login is lost when the web app is restarted or the user reaches a different backend from when the user logged in.
* Distributed caching: The cache is much easier to access by attackers compared to if it was stored in memory or in the user's authentication cookie.

(there is a third option of session caching, but sessions are implemented using one of the two methods above anyway).

Ideally I would like to store the user's token in an encrypted cookie, but the token cache is too large to fit in a cookie.
Only the refresh tokens are essential in the cache. If the refresh token is lost, the user is logged our. If an access token is lost, the app can get a new one the next time it calls `AcquireTokenSilent`.

**Describe the solution you'd like**
Allow refresh tokens to be stored encrypted in the user's authentication cookie (which is not lost when reacing another server instance), an access token stored in a memory cache (which can hold more data than a cookie).

**Describe alternatives you've considered**
We will use SQL server caching for now https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet#sql-server even though we are not confident in the security properties of this solution.

**Additional context**
We are implementing the token caching manually based on `cca.UserTokenCache.SetAfterAccess/SetBeforeAccess` because `Microsoft.Identity.Web.TokenCache` depends on a number of system libraries in version `>= 5.0.0` but we have other dependencies that require the same system libraries in verion `>= 4.4.2 && < 5.0.0`

**Comment by bgavrilMS** [comment]
I'd recommend you encrypt your cache before storing it in Redis or any other distributed cache.

**Comment by bgavrilMS** [comment]
Consider using the L1/L2 cache from Microsoft.Identity.Web.TokenCache package, which has an option to encrypt at L2 level. 

https://github.com/AzureAD/microsoft-identity-web/wiki/L1-Cache-in-Distributed-(L2)-Token-Cache#encrypt-or-not
