### ISSUE TITLE
[Feature Request] MSAL internal cache eviction 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3020]
# Goal

MSAL should support cache eviction options (ideal: max memory size; less than ideal: max number of items)

## North star

1. MSAL should support some eviction options (ideal: max memory size; less than ideal: max number of items)
2. L1 must be really fast
3. MSAL should allow app developers to provide their own caching mechanism (e.g. MemoryCache)
4. L1 / L2 observability (availability & hit ratios)

## Status Quo 

Today, MSAL does not have an L1 layer. Its cache operations are: 

```
1. Find
[optional] Fetch data from L2 into memory
Apply filtering logic and find token

2. Save
Get response from ESTS
Merge response with tokens in memory
[optional] Save data to L2
```

## Ideas

- We could satisfy item 1 with a tactical fix. If L2 is not defined, MSAL will use it accessors to accumulate tokens. We can gain inspiration from MemoryCache implementation on how to compute size. When size is reached, evict the entire cache. 
- Accessors cannot be implemented with MemoryCache because MemoryCache does not support "GetAllItems" operation.

- If we completely re-implement the Find 

```
1. Find
Fetch data from L1. If not hit, fetch data from L2 into accessors.
L1 is just a generic map[string] -> object, where string = cache key and object = accessor
```

- `SetCacheOptions(L1Options)` where `L1Options` defines: `Enabled`, `Static`, `MaxItems`, `MaxSize` (?), and in the future a `IL1CacheInterface`
- L2 cache continues to be defined as today
- With a proper L1, there is no need for partitioned accessors, although these can stay.

**Comment by pmaytak** [comment]
@bgavrilMS
> Today, MSAL does not have an L1 layer. Its cache operations are:

To clarify - L1 is the dictionary/accessor, L2 is serialization cache (ex. Redis)?

> MSAL should allow app developers to provide their own caching mechanism (e.g. MemoryCache)

To replace L1/accessors? So that user can provide their own L1, L2 caches?

**Comment by bgavrilMS** [comment]
Today, we have the accessor and the cache serialization callbacks. 
If the callbacks are not used, the accessor becomes an L1 cache, especially when it's set to be static. 
If the callbacks are used, the we agreesively pull everything from the external store into the accessor, so the accessor is no longer an L1.

Most Id.Web.TokenCache caches are actually a combination of MemoryCache (L1) + IDistributedCache (L2)

My suggestion on this would be to leave the accessor alone for now and focus on what it'd take for MSAL to have an L1 cache where we'd store OBJECTS and not JSON, for speed. 

In terms of L1 cache, I'd start from an existing implementation rather than extensibility: 

- MemoryCache is a good start for prototyping, although it's unlikely we can take a dependency on it (but maybe we can rediscuss this)
- Have a look at https://github.com/AzureAD/microsoft-identity-web/tree/master/src/Microsoft.Identity.Web.TokenCache - I recommend that you setup a simple Redis (use your private az sub or ping me for my personal Redis instance) and try to get an S2S app going and play with all the cache options. It's important to understand how the existing L1 / L2 works. This is what we're trying to replace (but don't get hang up into "legacy" details. We can expose a new mechanism and softly deprecate the exsting one).
- There are 2 internal caches which we could use instead of MemoryCache: the one from Wilson and the one from SPO. A good default is critical
- Nobody asked for L1 extensibility, it's not critical at the moment. But we should design with extensiblity in mind. Especially when it comes to eviction options.

**Comment by bgavrilMS** [comment]
MSAL internal cache eviction is not planned, too complex to build and we have a solution based on MemoryCache.
