### ISSUE TITLE
[Bug] An error occurred while sending the request Microsoft.Identity.Client.Platforms.net45.Http.DnsSensitiveClientHandler

### ISSUE THREAD

**Issue by techyrajeev** [AzureAD/microsoft-authentication-library-for-dotnet#3021]
Getting this error while login -
"ErrorMessage": "An error occurred while sending the request.",

**Logs and network traces**

"ErrorMessage": "An error occurred while sending the request.",
    "ErrorLocation": "   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.Platforms.net45.Http.DnsSensitiveClientHandler.<SendAsync>d__2.MoveNext()\r\n--- End of batch trace from the previous location where the exception was thrown---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.Http.HttpManager.<ExecuteAsync>d__14.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.Http.HttpManager.<ExecuteWithRetryAsync>d__12.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.Http.HttpManager.<SendGetAsync>d__9.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__11`1.MoveNext()\r\n--
    
**Which version of MSAL.NET are you using?**
MSAL.NET 4.36

**Platform**
.NET Framework 4.7
WPF
Windows Application Packaging wrapper (Centennial App)

**What authentication flow has the issue?**
* Desktop
    * [-] Interactive
    * [-] Integrated Windows Authentication
    * [-] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.

**Expected behavior**
User should be able login into the app
**Actual behavior**
User is not able to login into account via WAM

**Comment by bgavrilMS** [comment]
This does not look like WAM. This is an HTTP error which shows that MSAL is making either a discovery or a token request. Either way, we need error and logs to investigate.

**Comment by bgavrilMS** [comment]
Closing as not enough info. Please reopen if you can get logs.
