### ISSUE TITLE
CreateFromWwwAuthenticateHeaderValue does not work with full www-authenticate header

### ISSUE THREAD

**Issue by Trimack** [AzureAD/microsoft-authentication-library-for-dotnet#3027]
The method signature suggests the value of the www-authenticate header should be used for input. From investigating the internal implementations, it seems that it does not expect the leading "Bearer " or similar string to be part that header value.

With current implementation, response from e.g. CDS (Dataverse) looking like
`www-authenticate: Bearer authorization_uri=https://login.microsoftonline.com/12345678-268e-46c2-8d30-1ad8ad2cd49d/oauth2/authorize, resource_id=https://testingorg0127.crm10.dynamics.com/` fails to parse due to the leading segment not matching the `authorization_uri` as expected.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/c2605eb6d57cb4efd259887300b3e17c693ff781/src/client/Microsoft.Identity.Client/WwwAuthenticateParameters.cs#L129

**Comment by bgavrilMS** [comment]
Is this different from https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3026 ?

**Comment by Trimack** [comment]
I believe so due to my last comment in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3026#issuecomment-972749141.

**Comment by bgavrilMS** [comment]
I'm going to close this one in favour of #3026

**Comment by Trimack** [comment]
I believe this to be a different issue due to the `public` access modifier of this method. #3026 on the other hand stems from the WwwAuthenticate property. I reckon a xmldoc fix for this one at least would be appreciated.
