### ISSUE TITLE
Using WAM with custom OAuth2 / OpenID Connect providers

### ISSUE THREAD

**Issue by pjaros1** [AzureAD/microsoft-authentication-library-for-dotnet#3038]
**Is your feature request related to a problem? Please describe.**
Is it possible to use WAM in MSAL for authentication with own custom provider who supports OAuth2 / OIDC authentication (or any other flow) or is WAM works just with Azure AD?

**Comment by bgavrilMS** [comment]
MSAL itself only talks to AAD / ADFS for now, although there are plans to make it talk to any identity provider. 

WAM has 2 plugins as far as I know - one for corporate accounts and one for personal accounts. Both Microsoft identity providers.

There does seem to be some extensibility in the account selector control for other account providers - have a look at https://docs.microsoft.com/en-us/windows/uwp/security/web-account-manager#add-providers-that-dont-support-webaccountmanager
