### ISSUE TITLE
Confidential Client & ID Tokens Using OpenIdConnect

### ISSUE THREAD

**Issue by SpencerK369** [AzureAD/microsoft-authentication-library-for-dotnet#3039]
I am migrating an ASP.NET MVC 5 application from using the old ADAL.NET to use MSAL.NET. I am struggling to get any ID tokens in any class outside of our custom Azure authentication builder class. 
`public static class AzureAdAuthenticationBuilderExtensions
    {        
        public static AuthenticationBuilder AddAzureAd(this AuthenticationBuilder builder, IConfiguration config)
            => builder.AddAzureAd(_ => { }, config);

        public static AuthenticationBuilder AddAzureAd(this AuthenticationBuilder builder, Action<AzureAdOptions> configureOptions, IConfiguration config)
        {
            builder.Services.Configure(configureOptions);
            builder.Services.AddSingleton<IConfigureOptions<OpenIdConnectOptions>, ConfigureAzureOptions>();
            builder.AddOpenIdConnect(options =>
            {
                var azureadoptions = new AzureAdOptions(); config.Bind("AzureAd", azureadoptions);
                options.ClientId = $"{azureadoptions.ClientId}";
                options.Authority = $"{azureadoptions.Instance}{azureadoptions.TenantId}";
                options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                {
                    ValidAudience = $"{azureadoptions.ClientId}",
                    //ValidAudiences = new List<string> { $"{azureadoptions.ClientId}", $"api://{azureadoptions.ClientId}", $"https://myapp.azurewebsites.net/" },
                    //ValidIssuer = $"https://sts.windows.net/{azureadoptions.ClientId}/" // for "signInAudience": "AzureADMyOrg" or "AzureADMultipleOrgs"
                    //ValidIssuer = $"{azureadoptions.Instance}{azureadoptions.TenantId}" // for "signInAudience": "AzureADandPersonalMicrosoftAccount"
                    ValidIssuers = new List<string> { $"https://sts.windows.net/{azureadoptions.TenantId}/", $"{azureadoptions.Instance}{azureadoptions.TenantId}/v2.0" }
                };
                //Log.LogInformation($"the AddJwtBearer options have been configured for ClientId = {azureadoptions.ClientId}");
            });

            return builder;
        }

        private class ConfigureAzureOptions: IConfigureNamedOptions<OpenIdConnectOptions>
        {
            private readonly AzureAdOptions _azureOptions;

            public ConfigureAzureOptions(IOptions<AzureAdOptions> azureOptions)
            {
                _azureOptions = azureOptions.Value;
            }

            public void Configure(string name, OpenIdConnectOptions options)
            {
                options.ClientId = _azureOptions.ClientId;
                options.Authority = _azureOptions.Authority;
                options.UseTokenLifetime = true;
                options.CallbackPath = _azureOptions.CallbackPath;
                options.RequireHttpsMetadata = false;
				options.ClientSecret = _azureOptions.ClientSecret;
				options.Resource = "https://graph.windows.net"; 

				options.ResponseType = OpenIdConnectResponseType.CodeIdToken;

				// Subscribing to the OIDC events
				options.Events.OnAuthorizationCodeReceived = OnAuthorizationCodeReceived;
				options.Events.OnAuthenticationFailed = OnAuthenticationFailed;
			}

			public void Configure(OpenIdConnectOptions options)
            {
                Configure(Options.DefaultName, options);
            }

			/// <summary>
			/// Redeems the authorization code by calling AcquireTokenByAuthorizationCodeAsync in order to ensure
			/// that the cache has a token for the signed-in user, which will then enable the controllers (like the
			/// TodoController, to call AcquireTokenSilentAsync successfully.
			/// </summary>
			private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)
			{
				string[] scopes = new string[] { "https://(url/appid)/user_impersonation" };
				var code = context.ProtocolMessage.Code;

				string signedInUserID = context.Principal.FindFirst(ClaimTypes.NameIdentifier).Value;
				IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder.Create(_azureOptions.ClientId)
					.WithTenantId(_azureOptions.TenantId)
					.WithAuthority(new Uri(_azureOptions.Authority))
					.WithClientSecret(_azureOptions.ClientSecret)
					.WithRedirectUri("https://localhost:44362/signin-oidc")
					.Build();

				AuthenticationResult result = await cca.AcquireTokenByAuthorizationCode(scopes, code)
					.ExecuteAsync();

				context.HandleCodeRedemption(result.AccessToken, result.IdToken);
			}

			/// <summary>
			/// this method is invoked if exceptions are thrown during request processing
			/// </summary>
			private Task OnAuthenticationFailed(AuthenticationFailedContext context)
			{
				context.HandleResponse();
				context.Response.Redirect("/Home/Error?message=" + context.Exception.Message);
				return Task.FromResult(0);
			}
		}
	}`

I did not initially develop this application and was not the one who put this in place. In the function OnAuthorizationCodeReceived I modified it to use IConfidentialClientApplication instead of what we were using with ADAL.NET. This code works just fine and we get back an access token and id token just fine. The problem comes from when we try to get the id token again using a custom BaseHTTPService which has a function that returns the access token as seen in the method GetAccountServiceToken.
`public class BaseHttpService : IBaseHttpService
    {
        protected readonly HttpClient _client;
        private static AzureAdOptions _azureOptions;

        public BaseHttpService(HttpClient client, IConfiguration configuration)
        {
            _client = client;
            _azureOptions = new AzureAdOptions
            {
                ClientId = configuration.GetValue<string>("AzureAd:ClientId"),
                ClientSecret = configuration.GetValue<string>("AzureAd:ClientSecret"),
                TenantId = configuration.GetValue<string>("AzureAd:TenantId"),
                SignInUrl = "https://localhost:44362/Account/SignIn",
                Domain = configuration.GetValue<string>("AzureAd:AppIDURL")
            };
        }

        public static async Task<string> GetAccountServiceToken(string audienceId, HttpContext context)
        {
            // Because we signed-in already in the WebApp, the userObjectId is know
            string userObjectID = (context?.User.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier"))?.Value;

            string[] scopes = new string[] { _azureOptions.Domain + "/.default" };
            IConfidentialClientApplication cca = ConfidentialClientApplicationBuilder.Create(_azureOptions.ClientId)
               .WithTenantId(_azureOptions.TenantId)
               .WithAuthority(new Uri("https://login.microsoftonline.com/" + _azureOptions.TenantId))
               .WithClientSecret(_azureOptions.ClientSecret)
               .WithRedirectUri("https://localhost:44362/signin-oidc")
               .Build();

            AuthenticationResult result = null;
            try
            {
                var accesstoken = await cca.AcquireTokenForClient(scopes).ExecuteAsync();
                var assert = new UserAssertion(accesstoken.AccessToken, "urn:ietf:params:oauth:grant-type:jwt-bearer");
                result = await cca.AcquireTokenOnBehalfOf(scopes, assert).ExecuteAsync();
            }
            catch (MsalUiRequiredException ex) when (ex.ErrorCode == MsalError.InvalidGrantError)
            {
                result = await cca.AcquireTokenForClient(new string[] { _azureOptions.Domain + "/.default" }).ExecuteAsync();
            }

            if (result != null)
            {
                return "Bearer " + result.AccessToken;
            }

            return string.Empty;
        }

        public async Task<T> PostInfo<T>(string url, T objectToPost) where T : class
        {
            if (objectToPost != null)
            {
                ByteArrayContent postContent = GetInfoToPost(objectToPost);

                HttpResponseMessage response = await _client.PostAsync(url, postContent);

                if (response.IsSuccessStatusCode)
                {
                    return objectToPost;
                }
                else
                {
                    throw new System.Exception(response.StatusCode + ": " + response.RequestMessage);
                }
            }

            return objectToPost;
        }

        protected static ByteArrayContent GetInfoToPost(object objectToPost)
        {
            var objectJson = JsonSerializer.Serialize(objectToPost);
            var buffer = System.Text.Encoding.UTF8.GetBytes(objectJson);
            var byteContent = new ByteArrayContent(buffer);

            byteContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

            return byteContent;
        }
    }`
The method GetAccountServiceToken returns an access token just fine but always from the result within the catch block where we get it from AcquireTokenForClient. What I need to do is get the id token, but this will never be returned from AcquireTokenForClient and thus I need to either get it from AcquireTokenOnBehalfOf or another method such as AcquireTokenSilent. But no matter how much I have tried I cannot get either of those to work. Also if it is not worthy I have tried seeing that if there are ever any accounts in this IConfidentialClientApplication using 
`var accounts = await cca.GetAccountsAsync();`
but again no matter what I do there are never any accounts. I have been trying to piece together code from multiple examples and trials and errors but I can never achieve what I want.

My end goal is to just get and return the id token from the method GetAccountServiceToken, that is all I want. Any help would be greatly appreciated! Thanks and sorry for the sloppy code, I have been going back and forth on this task for a while now.

**Comment by jmprieur** [comment]
@SpencerK369 : just use Microsoft.Identity.Web instead, it will do all the work for you.
You'll be able to inject a ITokenAcquisition instance in your controller to get tokens.

See https://github.com/AzureAD/microsoft-identity-web/wiki/1.0.0, 
and https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps

**Comment by SpencerK369** [comment]
Thank you very much this seemed to be exactly what I needed. I am no longer using the Confidential Client route.
