### ISSUE TITLE
[Bug] Support Windows 2022 for WAM

### ISSUE THREAD

**Issue by MichelZ** [AzureAD/microsoft-authentication-library-for-dotnet#3040]
**Is your feature request related to a problem? Please describe.**
WAM Broker probably fails to detect Windows 2022 as a supported OS.

**Describe the solution you'd like**
Support Windows Server 2022

**Additional context**
New OS versions were released that need to be added to DesktopOsHelper.
ProductName from Registry:   "Windows Server 2022 Datacenter"

**Comment by bgavrilMS** [comment]
Yes, let's take this as a bug though.

**Comment by bgavrilMS** [comment]
See #2946 as well

**Comment by gladjohn** [comment]
This has been fixed in [MSAL 4.41.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.41.0)
