### ISSUE TITLE
[Feature Request] Remove MATS telemetry

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#3043]
Remove MATS telemetry (previous telemetry infrastructure which is not used).
To-do:
- Remove references to MATS and refactor/clean up HTTP telemetry.
- Run performance tests for before and after

Related to #3024.

**Comment by SameerK-MSFT** [comment]
Fixed in [MSAL 4.40.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.40.0)
