### ISSUE TITLE
[Bug] WAM Account Picker did not return an account. 

### ISSUE THREAD

**Issue by techyrajeev** [AzureAD/microsoft-authentication-library-for-dotnet#3044]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.37.0

**Platform**
.NET 4.7

**What authentication flow has the issue?**
* Desktop
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.

**Exception**
Microsoft.Identity.Client.MsalClientException 

**Expected behavior**
User should be able login without any issue
**Actual behavior**
User is not able to login due WAM error

Important note: user is not running as elevated.

**Comment by bgavrilMS** [comment]
We would need more info from the Account Picker control to see what's happening. 

[AcctCtrl.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/7634178/AcctCtrl.zip)

1.	Start_asptrace.cmd
2.	<repro>
3.	Stop_asptrace.cmd
4.	Share the resulting ETL (via email, as it might contain personal info)
