### ISSUE TITLE
[Bug] Broker response returned error: User canceled authentication.  

### ISSUE THREAD

**Issue by techyrajeev** [AzureAD/microsoft-authentication-library-for-dotnet#3046]
Which version of MSAL.NET are you using?
MSAL.NET 4.37.0

Platform
.NET 4.7, WPF

**What authentication flow has the issue?**
* Desktop
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
    
Is this a new or existing app?
a. The app is in production, and I have upgraded to a new version of MSAL.

Exception
Microsoft.Identity.Client.MsalServiceException 

Expected behavior
User should be able login without any issue
Actual behavior
User is not able to login due WAM error, even though user hasn't canceled the authentication we are getting this error.

**Comment by bgavrilMS** [comment]
This is an expected error if the user cancelles auth. 
If they do not and you still get this error, we'd need more info from WAM itself. See https://aka.ms/wamhot for how to collect logs.
