### ISSUE TITLE
[Bug] Improve WAM exceptions 

### ISSUE THREAD

**Issue by techyrajeev** [AzureAD/microsoft-authentication-library-for-dotnet#3047]
Which version of MSAL.NET are you using?
MSAL.NET 4.37.0

Platform
.NET 4.7, WPF

**What authentication flow has the issue?**
* Desktop
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
    
Is this a new or existing app?
a. The app is in production, and I have upgraded to a new version of MSAL.

Exception
Broker response returned error: WAM Error  Microsoft.Identity.Client.Platforms.Features.WamBroker.AadPlugin  
 Error Code: WAM_aad_provider_error_2148008704  
 Error Message:   
 Possible causes:  
 - Invalid redirect uri - ensure you have configured the following url in the AAD portal App Registration: ms-appx-web://microsoft.aad.brokerplugin/{ClientID}  
- No Internet connection  
Please see https://aka.ms/msal-net-wam for details about Windows Broker integration 

Actual behavior
User is not able to login due WAM error

## Expected behavior:

There are 2 basic scenarios:

1. When application is making user-initiated action, for example saving file in cloud. In this case, this is the application responsibility to display error to the user in non-intrusive way and have a control element, which allow user to repeat the action again.

2. When application doing some background operations, like syncing emails. For such operation it is important to do back off retry logic.

MSAL should expose if an error is retry-able

Work to be done: 

- [x] Update WAM AAD plugin error handling logic to determine if error is retry-able (see comment for logic to determine retry-able errors)
- [x] Expose IsRetryiable property on MsalException
- [x] For service errors, mark HTTP 5xx and HTTP 429 errors retry-able
- [x] Better error message for BT_SPURIOUS_ACTIVATION
- [x] Update WAM doc https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam with error guidance (the 2 basic scenarios) 
- [ ] Update error doc https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-error-handling-dotnet

**Comment by bgavrilMS** [comment]
This is a message from the WAM team regarding this error: 


```
Expected. This is a catch all error, which basically means that either WAM plugin process didn’t start, or WAM plugin process didn’t finished in expected protocol, this may mean many things:
1.	3rd party protection software blocks our application – admin needs to add exclusion.
2.	Token request was made when the system has exhausted resources, the device is in boot crunch or in sleep/low power mode.
3.	System is about to shut down, and no further activity allowed.
4.	For UWP application: they not allowed to do extensive activity at the moment of call.
5.	Very rare it can mean that WAM plugin crashed, usually in internal windows builds (if we have some bugs). .
This error must be retriable according to this document.
```

MSAL can 2 things to improve here: 

a. Retry the request once
b. Produce a better error with potential causes.

**Comment by bgavrilMS** [comment]
The snippet below is from the WAM guidance doc. They mark some errors are retry-able. We don't have this concept in MSAL, but we can introduce it by adding 

`bool IsRetryable` on `MsalClientException`





```csharp


bool IsRetriable(DWORD errorCode)

{

switch (facility(errorCode))

{

// network issues

case FACILITY_ADAL_HTTP:

case FACILITY_ADAL_INTERNET:

case FACILITY_ADAL_URLMON:

// background infrastructure canceled, due not enough resources at this moment.

case FACILITY_ADAL_BACKGROUND_INFRASTRUCTURE:

return true;

default:

return (errorCode == BT_E_SPURIOUS_ACTIVATION // background infrastructure canceled, due not enough resources at this moment.

|| errorCode == WAIT_TIMEOUT // overall request timed out.

|| errorCode == HRESULT_FROM_WIN32(WAIT_TIMEOUT) // overall request timed out.

|| errorCode == HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND) // bug in WAM core in some version of Windows, the issues is retriable Bug 15107486.

|| errorCode == ERROR_ADAL_SERVER_ERROR_TEMPORARILY_UNAVAILABLE // server temporary unavailable.

|| errorCode == ERROR_ADAL_SERVER_ERROR_RECEIVED // internal server error.

);
```

**Comment by bgavrilMS** [comment]
See https://microsoft.sharepoint.com/:w:/t/AADThreshold/EdfYP7lDeXhOumtOUvdLaTMB13WUvVjFNpYPR6lLs0aFYw?e=2AADEh&CID=18aa89ab-c070-8521-a63d-8814242c2aef for full guidance on errors.

**Comment by bgavrilMS** [comment]
@neha-bhargava  - I updated the work item with a more general purpose mechanism for retry-able errors.
