### ISSUE TITLE
Access to MS Graph blocked by Conditional Access policy

### ISSUE THREAD

**Issue by UserPU** [AzureAD/microsoft-authentication-library-for-dotnet#3050]
To read information via the Graph API from our Azure environment I used on a Desktop app  Microsoft.Identity.Client library (version 4.18) to authenticate users with integrated Windows Authentication. 
 Net framework 4.8 in the background. This works perfect for some time but now a Conditional Access policy was enabled and the following call ends in an exception.

_authResult = Await PublicApp.AcquireTokenByIntegratedWindowsAuth(m_scopes).ExecuteAsync(CancellationToken.None).ConfigureAwait(False)_

**Exception: AADSTS53001: Device is not in required device state: domain_joined. Conditional Access policy requires a domain joined device, and the device is not domain joined.**

dsregcmd /status

+----------------------------------------------------------------------+ | Device State | +----------------------------------------------------------------------+

         AzureAdJoined : YES
      EnterpriseJoined : NO
          DomainJoined : YES

From my point of view my device is domain joined and there is no reason to block this access. Same pc as before. Can be tested in parallel. App used with a user without conditional access works. App used with a user who has an conditional access policy assigned fails.

Is this a bug or what have I to change to run my call also with Conditional Access enabled?

**Comment by bgavrilMS** [comment]
Conditional Access can only be satisfied by a browser or by the broker. If I am not mistaken, `AcquireTokenByIntegratedWindowsAuth` will in this case throw an `MsalUiRequiredException`, which means that you have to call `AcquireTokenInteractive` to show UI. This will be one time only - after an interactive login, the silent login will work. 

Alternatively, you can use the broker (WAM) on Windows, which is able to satisfy device management CA without UI. See https://aka.ms/msal-net-wam. WAM is the preferred auth mechanism on Windows.
