### ISSUE TITLE
Unit Test project crashes on method AcquireTokenInteractive for instance IPublicClientApplication

### ISSUE THREAD

**Issue by chigivigi** [AzureAD/microsoft-authentication-library-for-dotnet#3053]
Which version of MSAL.NET are you using?
Microsoft.Identity.Client 4.39.0

Platform
Net6,0 Unit Test

What authentication flow has the issue?
* Desktop / Mobile
    * [ ] Interactive

Other?
I am migrating a unit test project from netcore3.0 to net6.0. When debugging in Visual Studio, I ran into a problem when calling the method AcquireTokenInteractive for instance of IPublicClientApplication.

The method starts executing, the login page opens in browser, I login and receive this message in browser:

Authentication complete. You can return to the application. Feel free to close this browser tab.

After the message is displayed in browser, Visual Studio does not return to the method AcquireTokenInteractive, Visual Studio stops debugging, there are no error messages in error list. In the output I found two exceptions.

The first one is: Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll

The second error is: Exception thrown: 'Microsoft.Identity.Client.MsalServiceException' in System.Private.CoreLib.dll

Is this a new or existing app?
I am migrating the app to use net6.0. It has been used with netcore3.0 framework before for local testing before publishing the function that uses the same actions.

Repro

```csharp
IPublicClientApplication PublicClientApp = PublicClientApplicationBuilder.Create(azureADAppSettings.ApplicationID)
            .WithTenantId(azureADAppSettings.TenantID)
            .WithAuthority(AzureCloudInstance.AzurePublic, tenantName)
            .WithRedirectUri(redirectUri)
            .Build();

result = await PublicClientApp.AcquireTokenInteractive(scopes).ExecuteAsync();
```

Expected behavior
The login returns the token response where I would extract the access token.

Actual behavior
The method starts executing, the login page opens in browser, I login and receive this message in browser:

Authentication complete. You can return to the application. Feel free to close this browser tab.

After the message is displayed in browser, Visual Studio does not return to the method AcquireTokenInteractive, Visual Studio stops debugging, there are no error messages in error list. In the output I found two exceptions.

The first one is: Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll

The second error is: Exception thrown: 'Microsoft.Identity.Client.MsalServiceException' in System.Private.CoreLib.dll

Additional context / logs / screenshots / links to code
I have made some changes to my app registration in portal azure based on the second error message. I add the missing redirect uri to app registration and set the application as public client type.

The second error remained after the changes I made in the app registration on portal azure.

**Comment by chigivigi** [comment]
The issue was that the redirectUri was not added as a native url instead it was added as web url.

**Comment by chigivigi** [comment]
The issue was that the redirectUri was not added as a native url instead it was added as web url.

**Comment by bgavrilMS** [comment]
Thanks for following up.
