### ISSUE TITLE
[Feature Request] Allow POP token envelope to be created externally

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3059]
Today, MSAL creates the SignedHttpRequest (SHR) on its own and supports a few possible params (m, u, p, q). For more flexibility, MSAL should allow app developers to cerate their SHR separately, for example using Wilson: 

`Microsoft.IdentityModel.Protocols.SignedHttpRequest`

**Comment by SameerK-MSFT** [comment]
Fixed in [MSAL 4.40.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.40.0)
