### ISSUE TITLE
[Bug] Extreme memory usage for cache

### ISSUE THREAD

**Issue by austvik** [AzureAD/microsoft-authentication-library-for-dotnet#3063]
**Logs and network traces**
None. But if someone from Microsoft approaches jaustvi@microsoft.com they can see some more source code.

**Which version of MSAL.NET are you using?**
MSAL.NET 4.37.0

**Platform**
.NET Core 5

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [x] Service to Service calls

Other?

**Is this a new or existing app?**
a. The app is in production, and we have upgraded to MSAL.

**Repro**
No, got rid of it, not taking down production service again.

**Expected behavior**
Use little memory. Dont cache unneeded information. Make it possible to set limits to the cache size.

**Actual behavior**
Using a gigabyte of memory. Took down our service. People had to work weekend to fix it.

**Possible solution**

        /// <summary>
        /// Invokes private method TokenCreator.CreateHttpAuthenticatorPrivate using reflection.
        /// This is needed because TokenCreator.CreateMSAuth10AtPopHeaderAsync that we ideally
        /// would use retrieved OIDC information from all tenants and caches them carelessly
        /// without any means of limiting cache size. Dumps from prod front-ends running XXXX
        /// have shown more than 100k cache entries, each containing 26 lists of strings,
        /// where the lists themselves (without their contents) amounted to over 100MB of memory,
        /// and we had over 2GB of strings allocated (unknown how large fraction of these were
        /// from the OIDC cache).
        /// </summary>
        /// <remarks>Since TokenCreator.CreateHttpAuthenticatorPrivate does not make any remote
        /// calls, this method can be run by tests to ensure that the library we are referencing
        /// still declares this method with the right signature and functionality.</remarks>
        /// <param name="appToken">An tenant-level actor token to wrap.</param>
        /// <param name="payloadToken">The S2S token to wrap.</param>
        /// <param name="payloadTokenType">The type of the payload token.</param>
        /// <param name="uri">The URI that's going to be requested.</param>
        /// <param name="httpMethod">The HTTP method that will be used to request the <paramref name="uri"/>.</param>
        /// <param name="signingCredentials">Credentials to sign the token with.</param>
        /// <param name="additionalPayloadClaims">Additional claims to include in the token.</param>
        /// <returns>A POP token that can be placed in a MSAuth1.0 type authorization header.</returns>
        internal string CreateHttpAuthenticator(string appToken, string payloadToken, string payloadTokenType, Uri uri, string httpMethod, SigningCredentials signingCredentials, IDictionary<string, object> additionalPayloadClaims)
        {
            /*
             * private static string CreateHttpAuthenticatorPrivate(
             *     string appToken,
             *     string payloadToken,
             *     string payloadTokenType,
             *     Uri uri,
             *     string httpMethod,
             *     SigningCredentials signingCredentials,
             *     IDictionary<string, object> additionalPayloadClaims)
             */
            return (string)createHttpAuthenticatorPrivate.Invoke(null, new object[] {appToken, payloadToken, payloadTokenType, uri, httpMethod, signingCredentials, additionalPayloadClaims});
        }

**Additional context / logs / screenshots / links to code**

Production service makes calls for many tenants. The OICD Cache filled up and took down our service when it ran out of memory.

**Comment by bgavrilMS** [comment]
MSAL will cache all tokens as they come. An S2S token for 1 tenant is about 2KB in size. If you need tokens for a very large number of tenants, then the memory will grow and grow. 

The solution for now is to configure in-memory caching and add an eviction policy. See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet#in-memory-token-cache-1. Note that overall latency to get a token is a bit worse when using this mechanism (in the order of ~10-30ms).

We are working on providing a cache eviction policy directly from MSAL, but I do not have an ETA yet. Please use the above solution for now. Tracking item https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3020

CC @pmaytak who's working on all cache related items.

**Comment by bgavrilMS** [comment]
Looking more in detail at this, it looks like you are using SAL, not MSAL. SAL is an internal library. I'll reach out.

**Comment by bgavrilMS** [comment]
@austvik - are you using SAL (TokenCreator) or MSAL? SAL is an internal library.

**Comment by bgavrilMS** [comment]
SAL issue
