### ISSUE TITLE
[Inquiry] .NET Framework ADAL to MSAL 2.0 migration

### ISSUE THREAD

**Issue by argelj289** [AzureAD/microsoft-authentication-library-for-dotnet#3076]
I was given a required action to migrate the application that we support to use MSAL 2.0

our applications are running in .NET 4.8 Framework platform

I would like to inquire for an accurate documentation on implementing MSAL to our application

What files that should I be looking and placing the codes

What libraries I should be installing from Nuget package manager

**Comment by bgavrilMS** [comment]
Please see https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration
Note that it's not MSAL 2.0, it's the latest version of MSAL (currently 4.39.0).

For Microsoft internal teams we have a channel dedicated to this, but please read the docs first https://teams.microsoft.com/l/channel/19%3ae19672c8c1bb4237a5a3356cda5880fd%40thread.tacv2/General?groupId=7e394638-cacd-40c7-9e80-c4434c4c90df&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by argelj289** [comment]
> Please see https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration Note that it's not MSAL 2.0, it's the latest version of MSAL (currently 4.39.0).
> 
> For Microsoft internal teams we have a channel dedicated to this, but please read the docs first https://teams.microsoft.com/l/channel/19%3ae19672c8c1bb4237a5a3356cda5880fd%40thread.tacv2/General?groupId=7e394638-cacd-40c7-9e80-c4434c4c90df&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

it looks like your sample works on my problem. I just learned that MsalAccountId is the combination of oid and tid with "." in between..

its just weird that ClaimsPrincipal.Current.GetMsalAccountId() returns null

but thanks so much for the help :)

**Comment by bgavrilMS** [comment]
`ClaimsPrincipal.Current.GetMsalAccountId()` return null? I assume you're in an ASP.NET Classic (not core?). ASP.NET calls the /authrorize endpoint on its own, this is not MSAL. And by default, ASP.NET does not retrieve the MsalAccountId. You need to intervene in the OWIN request and add "client_info=1" to the request and then it'll work. Let me know if this the case and we can continue the discussion. IF you're on ASP.NET Core, please use Microsoft.Identity.Web and this does it all for you.

Token validation is done by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki. For 1st party apps we have some internal token types and a different library is used. Please ask on the channel.

**Comment by argelj289** [comment]
> `ClaimsPrincipal.Current.GetMsalAccountId()` return null? I assume you're in an ASP.NET Classic (not core?). ASP.NET calls the /authrorize endpoint on its own, this is not MSAL. And by default, ASP.NET does not retrieve the MsalAccountId. You need to intervene in the OWIN request and add "client_info=1" to the request and then it'll work. Let me know if this the case and we can continue the discussion. IF you're on ASP.NET Core, please use Microsoft.Identity.Web and this does it all for you.
> 
> Token validation is done by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki. For 1st party apps we have some internal token types and a different library is used. Please ask on the channel.

Yes, we are using not ASP.NET Core. where in the code I can intervene the OWIN request and add "client_info=1"?

I couldn't find sample of how I can set it in the code

for the token validation, will try the link you provided and will reach out to the channel for further help

Thank you

**Comment by bgavrilMS** [comment]
@kalyankrishna1 - do we have a sample for ASP.NET Classic?

**Comment by jmprieur** [comment]
@bgavrilMS : we have this one: https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect
@argelj289. when you wrote MSAL 2.0, did you mean MSAL.js 2.0?

**Comment by argelj289** [comment]
> @bgavrilMS : we have this one: https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect @argelj289. when you wrote MSAL 2.0, did you mean MSAL.js 2.0?

@jmprieur no, I meant the one installed using nuget package manager

**Comment by argelj289** [comment]
Hi guys, looking forward for your answer. Thank you

**Comment by bgavrilMS** [comment]
@argelj289 - can you please go over the ASP.NET sample above in detail? It explains everything, including the multi-tenancy question. Let us know if you have any other questions.
