### ISSUE TITLE
Unable to find acquireTokenByUsernamePassword in IConfidentialClientApplication

### ISSUE THREAD

**Issue by KamranShahid** [AzureAD/microsoft-authentication-library-for-dotnet#3081]
I have a backend application where i need to verify client credentials of a user. I am trying IConfidentialClientApplication with my app clientid, app secret,tenant id create ConfidentialClientApplication. then i was thinking that i will able to verify user credentials via acquireTokenByUsernamePassword but unable to find this method. 
Please let me know what i am  missing.
My simple requirement is to verify username/password of a user of my Azure AD

**Comment by bgavrilMS** [comment]
We do not support `AcquireTokenByUsernamePassword`  on confidential client. The flow exists indeed, but generally `AcquireTokenByUsernamePassword` is discouraged due to security holes. In fact, the new standard OAuth 2.1 drops it altoghter.

That said, you can use PublicClientApplication + `AcquireTokenByUsernamePassword`

**Comment by KamranShahid** [comment]
Ok let me try.

**Comment by KamranShahid** [comment]
I am getting following exception when using PublicClientApplication

A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal.
 See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: **************************************
Correlation ID: ******************************88
Timestamp: 2021-12-21 09:06:25Z

Anyway i can initialize client_secret (i think which i use with my application) with PublicClientApplication ?

**Comment by bgavrilMS** [comment]
No, PublicClient means there is no secret between the app and AAD. It is meant mainly for desktop and mobile apps. But you can think that the password for the user is the secret that ensures confidentiality. 

You need to go to the application portal and enable "Allow public client flows" setting on the Authentication page.

**Comment by KamranShahid** [comment]
Thanks @bgavrilMS . Will try out this
My basic requirement is to authenticate my some backend application with username/password of an Azure Ad user. 
I even needed to do health checking of user which i did via help of graph api and adding an Application in my Azure AD and given relevant User.Read and User.ReadAll permission on my app. 
If there is any further guidance then it could also help

**Comment by bgavrilMS** [comment]
Can you use a Service Principal instead? A backend service can be authorized to get a token with an app-level scope (Application Permissions) 

![image](https://user-images.githubusercontent.com/12273384/146907585-c88f453b-dc4b-4fbf-9e0b-09412b6e0284.png)

`User.Read.All` in particular is an application scope, not a user scope, i.e. only a service principal can read the details about the ALL the users in the tenant. 

![image](https://user-images.githubusercontent.com/12273384/146907804-3ff2fe27-4452-42a4-bdac-7a8c92514ec0.png)

In MSAL you'd call AcquireTokenForClient("https://graph.microsoft.com/.default")

**Comment by KamranShahid** [comment]
My App needed to verify username/passwords of a user is correct or not. some sort of authentication app it is. Let me google about Service Principal and any code related to it

**Comment by bgavrilMS** [comment]
@RootFengshun - for testing you can use the PublicClientApplication route. The fact that you know / can deploy the username and password ensures the confidentiality. We just don't recommended it for normal, non-test users.
