### ISSUE TITLE
[Bug] Allow res:// error pages to be displayed in embedded webview

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3083]
msal 4.39

ICM follow up 
res:// scheme is an IE internal scheme for displaying errors. It should be allowed to improve supporatibility.

**Comment by SameerK-MSFT** [comment]
Fixed in [MSAL 4.40.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.40.0)
