### ISSUE TITLE
You did not mentioned where to get  MSATenantId = "9188040d-6c67-4c5b-b112-36a304b66dad";

### ISSUE THREAD

**Issue by devamirsaleem** [AzureAD/microsoft-authentication-library-for-dotnet#3085]
I dont know what is MSA TenantID. I am relactant to use it because I don't know what it is?  who is responsible to generate it and what is the purpose.  I am creating a single sign on application using MVC.asp.net for my corporate. 

The below code is prsent in the startup.auth.cs
const string MSATenantId = "9188040d-6c67-4c5b-b112-36a304b66dad";

     private Task OnSecurityTokenValidatedAsync(SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> notification)
        {
            // Make sure that the user didn't sign in with a personal Microsoft account
            **if (notification.AuthenticationTicket.Identity.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value == MSATenantId)**
            {
                notification.HandleResponse();
                notification.Response.Redirect("/Account/UserMismatch");
            }

            return Task.FromResult(0);
        }

**Comment by bgavrilMS** [comment]
Who is the token for? For your own web api or do you use it to access Graph or some other external resource? If you are not the indented audience for the token, you MUST NOT decode the token. Token validation is pretty complex and MSAL is not the library that does it. 

In any case, when you create your application in the app registration portal on Azure, you can specify the types of users that are allowed to log in "Work & School", "Personal" or both. 

On the token acquisition side, if you are a single tenant application, configure the authority as "https://login.microsoftonline.com/<your_tenant_id>". If you are a multi-tenant app (e.g. you want to allow ppl from other companies to log in), then it's "https://login.microsoftonline.com/organizations"

Aside: All personal accounts live in a special tenant (918...dad).

**Comment by devamirsaleem** [comment]
I have done the registration on Azure AD, set the permission to access users using Microsoft Graph, I am all good, I am able to get the data but when the code get to the method mentioned above it throws the error because I had set the MSIlTenant= my tenant id and clearly it would throw error.  So I am not sure how MSATenant code was generated and how I can use it for my app.

if (notification.AuthenticationTicket.Identity.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value == MSATenantId)  // <--this MSATenantId

**Comment by bgavrilMS** [comment]
Not sure I understand what you are trying to do. If the token is for Graph, then you have no business decoding the token. At most you can inspect the ID token.

In your app registration, you control who can login: 

![image](https://user-images.githubusercontent.com/12273384/147086503-1cfb0b47-e75d-4ec1-8447-99e482b5bbe4.png)

For an existing app, follow the instructions on the "Authentication" tab. 

Did you go through the samples ? https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#web-applications

**Comment by devamirsaleem** [comment]
Sorry, maybe I am unable to expalin well.  I am not trying to do anything. I downloaded the code  ms-identity-aspnet-daemon-webapp and found that code there so I am asking the purpose of it.  ReadMe pointed me to this forum to ask for the issues.

**Comment by bgavrilMS** [comment]
No worries. Please try to go through the samples. For ASP.NET classic (not core), have a look at https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect

"daemon" apps are for service 2 service communication, i.e. service principals, not users. 
web apps are for logging in users in web apps such as asp.net 
web APIs are for accessing protected APIs

**Comment by devamirsaleem** [comment]
Thanks for guidance, and I will read the document to gain knowlege, but it was useful for me based on your last reply, I am able to make the decision.
Actually, I am creating an Web app and it requires users data , if I go with the code Authorization flow then admin would need to concent each time regular user access the app, to avoid user consent on the application level, I am using the client credentail flow.  I thought it would be a better approach but as you mentioend daemon apps are for service 2 service communication. So I may look for something, which a WebApi-Users to Access MSGraph that would access the MSGraph api and a client app would communicate with WebApi-Users to get users data.

**Comment by devamirsaleem** [comment]
Thanks
