### ISSUE TITLE
Unresponsive login view / Microsoft AuthHost is not responding

### ISSUE THREAD

**Issue by georgii11** [AzureAD/microsoft-authentication-library-for-dotnet#3086]
**Which version of MSAL.NET are you using?**
MSAL.NET 2.7.1

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
Multiple existing apps which were previously working, started displaying the issue without any change.
I've also registered a new test app to check and it happened for it too.

**Repro**

Basically the issue happens at this part of code:

```csharp
string[] m_scopes = { "user.read" };
AuthenticationResult authResult = await m_identityClientApp.AcquireTokenAsync(m_scopes);
//m_identityClientApp is of type PublicClientApplication
```

**Expected behavior**
Auth view should close after the last continue/ok.

**Actual behavior**
The view becomes unresponsive.
![unresponsive-loginView](https://user-images.githubusercontent.com/41159244/147151723-5860ab6c-9493-4925-b20f-337f2fba19b6.png)

**Additional context / logs / screenshots / links to code**
Multiple apps have started to display this behavior without any code changes. They were working fine until around 1.5-2 weeks ago.
The apps were using an even older ver of MSAL and started showing the issue, I tried updating to 2.7.1 and it still happens.
The app itself does not get stuck though; if I force close the Microsoft AuthHost, I can go on in my app, even be able to obtain further details such as access token, user id.

I know the version I use is a bit old, but for now it's the highest I can go without having dependencies issues. 
I have a mixed project: Entry point is C++ and the part where I actually use MSAL is a C# runtime component project in which I have to manually reference the MSAL dlls plus dependencies or it crashes because it fails to load them. I can't just add them using NuGet packages.
I don't know the exact reason why, but it's related to the fact that the main project is C++, I tested the same C# runtime component project in a C# one and it worked normally there.
So it's quite tricky trying to update and resolve dependencies like that. It's also a bummer because it used to work and it just broke one day.

**Comment by SameerK-MSFT** [comment]
We do not support that old version. Please try to upgrade. Just a trip. This looks like threading issue. Please use ConfigureAwait(false). But again the version is too old to support at this time.

**Comment by georgii11** [comment]
Hi! 
Thanks for the response @SameerK-MSFT ! Sadly ConfigureAwait(false) did not help.
Do you have an idea in which min version this might be fixed? If not, what's the min supported one? As I mentioned, sadly it's tricky to update; besides the different project types combo we also still have to support older stuff (i.e. windows sdk) and I can't update to the latest for now.

**Comment by bgavrilMS** [comment]
I think a Windows update is the root cause for this. Others have reported it as well :(

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3109

**Comment by bgavrilMS** [comment]
What version of Windows do you see this happening? And does this always happen, and for all users?

**Comment by bgavrilMS** [comment]
@georgii11 - let's continue the conversation on #3109

**Comment by bgavrilMS** [comment]
Closed as duplicate
