### ISSUE TITLE
[Bug] WAM seems to not pass the device information when a CAP for sign-in frequency is enabled 

### ISSUE THREAD

**Issue by sncorreia** [AzureAD/microsoft-authentication-library-for-dotnet#3087]
**Logs and network traces**
This is just the last part of the MSAL logs - Full logs can be provided as well as a .etl trace

```
Verbose False MSAL 4.35.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/08 15:36:50.99] Finished WAM:RequestTokenForWindowAsync: in 118148 ms

Info False MSAL 4.35.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/08 15:36:55.43 - c81c6cc3-5d7e-4433-a417-c21a69d1d109] Checking MsalTokenResponse returned from broker. 

Info False MSAL 4.35.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/08 15:37:16.81 - c81c6cc3-5d7e-4433-a417-c21a69d1d109] Error authentication_canceled returned in broker response. 

Error True MSAL 4.35.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [11/08 15:37:31.47 - c81c6cc3-5d7e-4433-a417-c21a69d1d109] MSAL.Desktop.4.35.1.0.MsalServiceException: 

ErrorCode: authentication_canceled
```

**Which version of MSAL.NET are you using?**
MSAL.NET 4.35.1.0

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
Desktop WPF application using WAM 

**Is this a new or existing app?**
This is an existing app.

**Repro**

```csharp
string authority = https://login.microsoftonline.com/ + applicationConfig.TenantID + "/v2.0";
Application.PublicClient = PublicClientApplicationBuilder.Create(applicationConfig.ClientID)
    .WithAuthority(authority)
    .WithDefaultRedirectUri()
    .WithWindowsBroker()
    .WithLogging(logMethod, LogLevel.Verbose, true, false)
    .Build();

IAccount osAccount = PublicClientApplication.OperatingSystemAccount;

try
{
    try
    {
        var mfaResult = await Application.PublicClient.AcquireTokenSilent(new string[1] { "api://eos-mfa.bvb/MFA" }, osAccount).ExecuteAsync();
    }
    catch (MsalUiRequiredException)
    {
        Application.AuthenticationResult
            = await Application.PublicClient.AcquireTokenInteractive(new string[1] { "api://eos-mfa.bvb/MFA" })
                                            .WithAccount(osAccount)
                                            .ExecuteAsync();
    }
}
finally
{
    File.WriteAllLines(@"c:\temp\msalloggingwithbroker.txt", _tempLogging);
}
```

**Expected behavior**
The device information should be passed to Azure AD to comply with the conditional access policy.

**Actual behavior**
This application was working correctly before.
However, after enforcing a Conditional Access Policy for sign-in frequency, seems like the information regarding the device is not being passed and the users are getting blocked by conditional access.
The first authentication occurs smoothly and the users are able to log in into the app.  However, after 1 hour, instead of successfully signing in again after performing MFA, they get blocked by conditional access, stating that the device **is not compliant.**

**Possible solution**

**Additional context / logs / screenshots / links to code**
I am opening this on behalf of a customer and as advised by @bgavrilMS. Will also share this with them, so they can provide or add more info directly if needed.

Nevertheless, for troubleshooting purposes, the WithWindowsBroker() method was removed from the code above, when relying in the browser, everything worked correctly, so this seems to point to an issue with the broker usage.

As below:
```
string authority = https://login.microsoftonline.com/ + applicationConfig.TenantID + "/v2.0";
Application.PublicClient = PublicClientApplicationBuilder.Create(applicationConfig.ClientID)
    .WithAuthority(authority)
    .WithDefaultRedirectUri()
    //.WithWindowsBroker()
    .WithLogging(logMethod, LogLevel.Verbose, true, false)
    .Build();

IAccount osAccount = PublicClientApplication.OperatingSystemAccount;

try
{
    try
    {
        var mfaResult = await Application.PublicClient.AcquireTokenSilent(new string[1] { "api://eos-mfa.bvb/MFA" }, osAccount).ExecuteAsync();
    }
    catch (MsalUiRequiredException)
    {
        Application.AuthenticationResult
            = await Application.PublicClient.AcquireTokenInteractive(new string[1] { "api://eos-mfa.bvb/MFA" })
                        .WithAccount(osAccount)
                        .ExecuteAsync();
    }
}
finally
{
    File.WriteAllLines(@"c:\temp\msalloggingwithoutbroker.txt", _tempLogging);
}
```

**Comment by bgavrilMS** [comment]
@sncorreia - for now I see 1 problem with your code - the authority should not end in "v2.0", it's just

string authority = https://login.microsoftonline.com/ + applicationConfig.TenantID

MSAL or WAM will append v2.0 when it computes the token endpoints. In particular WAM actually uses the v1 endpoint. Can you try with this change and let us know if it works? 

If it still does not work, can you collect : 

1. Fiddler trace 
2. Ideally the full WAM logs 

Please see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#wam-logging

Please email these directly as they have a lot of PII. bogavril at microsoft.com

**Comment by bgavrilMS** [comment]
Closing, as we do not have enough info to proceed here. This issue needs to be raised with either WAM team or with Conditional Access team.

**Comment by bgavrilMS** [comment]
Recommendation is to try the latest WAM integration, see https://aka.ms/msal-net-wam (the preview one), as it is based on the code that all Microsoft apps use.
