### ISSUE TITLE
[Feature Request] WCF Azure Ad and Azure web app integration

### ISSUE THREAD

**Issue by penetratorGithub** [AzureAD/microsoft-authentication-library-for-dotnet#3092]
**Is your feature request related to a problem?  
We are migrating a on-premises wcf  project to azure and we would like to use this library to integrate authentication.  currently we have a in-home authentication with a sql DB which is a headache maintaining users, so we would like to integrate with our azure AD.
 
Thanks

**Comment by bgavrilMS** [comment]
Please have a look at the samples https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#web-applications first.

- "daemon" deals with app to app authentication, i.e. there are no users involved, just service principals
- "web app" focused on technologies such as ASP.NET and ASP.NET Core (which can be hosted in Azure web app afaik)
- "web api" focuses on scenarios where you have a more standard web api which is accessed from a variety of of clients, such as mobile / desktop apps, not just browsers. 

Also note that we have a higher level library called "Microsoft.Identity.Web" specially designed for ASP.NET Core. It has integration with "App Service Authentication" which is very lightweight way of getting tokens from App Service. Please see https://github.com/AzureAD/microsoft-identity-web/wiki/deploying-to-app-services and https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=azure-resource-explorer%2Cprogramming-language-csharp#configure-app-service-to-return-a-usable-access-token
