### ISSUE TITLE
[Bug] Fix build warning in Test App

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3096]
**Logs and network traces**
NA

--- Component: --- 
com.fasterxml.jackson.core jackson-annotations 2.12.1 - Maven 

--- Found at: --- 
/s/tests/CacheCompat/CommonCache.Test.MsalJava/pom.xml

**Comment by bgavrilMS** [comment]
I assume it's a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3098
