### ISSUE TITLE
[Bug] AcquireTokenByAuthorizationCode has a wrong request format when the "code" parameter is relatively long.

### ISSUE THREAD

**Issue by 97589713** [AzureAD/microsoft-authentication-library-for-dotnet#3097]
MSAL.NET 4.44.0
.NET 6.0
Web app  Authorization code
```csharp
var app = ConfidentialClientApplicationBuilder.Create(config.ClientId)
    .WithCertificate(ReadCertificate(config.CertificateName))
    .WithAuthority(new Uri(config.Authority))
    .WithRedirectUri("http://localhost")
    .Build();
var scopes = new string[] { "user.read" };

// This short code parameter is no problem
var code = "M.R3_BL2.fc488bde-c208-f7fe-7435-a25677456d99";

// This long code parameter will cause problem
//var code = "0.AXEAF09iccdX-Uus7E7OVAL17LP7C4Dd7jlEldzrwvs_ZM4zAAA.AQABAAIAAAD--DLA3VO7QrddgJg7Wevr4zAIwaPccHzOU2jdnXLbkaSq6wEjCMwQAjKxP3vqpCW0ddzCvO1fUF9-I3NjuBvlyAB-Cr9GFku_TGReCBLUkN3SyyV6ToHJ1pdz9ya7c23QtHXEo5bQkA7g34rUv4i-96OKTfyEnPljgMhF6pa2Yg8-rAj_2acoFe0RrhYVWB5RNe0MzpqLLrhqViXiWUEZU19ptVcePF5OhF-IOPeAGm95s74qcd03Er3-W13lYFHa9UPOmvv931d6BZDs4N2TzalvRF_TRjipat48b55AVoWln4FDm9RJAwlrHBSCCokI9vvZrk8aKYRKWIX_BxjBjeVwh71at_Zg4Jh6aQmCDMWB9TVO9Hkk2b4qiktv7zFYV93FkBF3qqS4EcbuuYREw0tustUBS0CLzMOA2Wcl0AsvCVtDZdji8TTkP1tqx95kyV-4ZSraDRb9Hz-b01uiGbe0y-aHF_b7w1p0imi6HzkSg6Y4ymmIvhWgKatxyu9RmyKAKhCePZByZ5wl7Ec3rS_bdc36N_wgJRrshu17KBh_lyl3XviPriJBA7X5UbTrVaTyxkRp4RGQ29f_TQxF70T_ZYWaelZwD4kPjvATZ5RDV9q3tdT_6b2SUxgQfEdCA8vCHZ4MgSXwYCyC0NOlIAA&session_state=d72a90a8-566e-4d4e-9572-006cea09a647#";

result = await app.AcquireTokenByAuthorizationCode(scopes, code).ExecuteAsync();
```

**Fiddler capture**
The short "code" request is correct, and the correct response is returned, the request body snippet capture is as follows
```
code=M.R3_BL2.fc488bde-c208-f7fe-7435-a25677456d99&redirect_uri=http%3A%2F%2Flocalhost
```
The long "code" request seems that there are extra strings such as **“sessionstate”**
```
code=0.AXEAF09iccdX......SXwYCyC0NOlIAA%26session_state%3Dd72a90a8-566e-4d4e-9572-006cea09a647%23&redirect_uri=http%3A%2F%2Flocalhost
```
"code" request parampeter has these extra strings : **%26session_state%3Dd72a90a8-566e-4d4e-9572-006cea09a647%23**

**Comment by bgavrilMS** [comment]
What is the scenario where you encounter this? Are you using ASP.NET or ASP.NET Core? 


That redirect URI looks like a desktop app redirect uri ...

**Comment by 97589713** [comment]
.Net 6.0 Console app running under windows11, just a test.

**Comment by bgavrilMS** [comment]
What is the exact error that you get back? 

It looks like you are using a public client flow to obtain the auth code, which typically involves extra security params like PKCE. But you redeem the code like a confidential client app instead, which by default is more lax.

**Comment by 97589713** [comment]
I am simulating such a scene:

1. Client: Desktop App such as WPF, hosting the WebView2 browser, get the "code" after logging in;
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id={ClientId}&scope={Scopes}&response_type=code&redirect_uri={RedirectUri}
```
2. Server: .Net 6.0 Web Api, use the "code" passed by the client to obtain the "refresh_token" and return it to the client;

**Comment by bgavrilMS** [comment]
The component making the "authorize" request should also make the "token" request. It's better to solve this problem differently: 

- if you are just hosting a browser and your client app does not need a token for anything else, then you can use a web site scenario https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#web-applications

- if your client app (WPF) needs a token for itself (e.g. to call Graph), then I suggest you make your backend into a web api and use AcquireTokenOnBehalfOf - see this sample which uses a console app + web api
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

**Comment by 97589713** [comment]
The session_state string was passed in by me. When I got the code parameter, obtained an extra session_state string. I used this regular expression to fix, and now it works, thank you!
```
 @"code=(?<code>.+?)(&|$)"
```
