### ISSUE TITLE
Authorization Code Grant

### ISSUE THREAD

**Issue by jkim-js** [AzureAD/microsoft-authentication-library-for-dotnet#3099]
Looking at https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#authorization-code, it looks like the client-side (.NET desktop) cannot create an auth code.

That is, only the JavaScript version of MSAL seems to be able to create an auth code; but any chance this is in the plans for MSAL.NET?  Or is this restricted by design?

**Comment by trwalke** [comment]
Auth code grant is supported by MSAL.NET. Also, the MSAL is not creating the auth code, it is acquired from the STS. MSAL simply makes the request for the code form the authorize endpoint. The code will be made available from the STS once the user signs into the login screen.

For auth code flow on public clients, see: [AcquireTokenInteractive](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively)

For auth code flow on confidential clients, see: [Acquiring tokens with authorization codes on web apps](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-with-authorization-codes-on-web-apps#getting-tokens-by-authorization-code-web-sites)

**Comment by jkim-js** [comment]
Thanks @trwalke 

The exact workflow I have is:  Desktop App (token 1) -> Custom Web API (token 1 -> exchanged with token 2) -> Azure/MS Api (token 2)
- Desktop App:  Public client
- Custom Web API: Confidential client

As far as I can tell, the [On-behalf-of ](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#on-behalf-of) flow is the recommended approach for this setup.

My question:  Is there a way to enforce the Desktop App's token to be single-session or one-time use, just like with the Auth Code flow?

Ideally (magic-wand) I could get the Auth Code on the public client, and the auth code could be exchanged for a token on the confidential-client web api; but this doesn't seem to be possible.

**Comment by trwalke** [comment]
All access tokens have a default lifetime of 60 mins and I do not believe there is a way to acquire a token that is one time use like the auth code. 

There are options to configure token lifetime and sign in frequency which may help reduce the timeframe in which the tokens are active

[Sign In Frequency](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime)

[Token Life Time](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#access-token-lifetime)

**Comment by jkim-js** [comment]
Thanks @trwalke for confirming.
