### ISSUE TITLE
[Problem] AcquireTokenSilent with the Account after AcquireTokenOnBehalfOf  don't work

### ISSUE THREAD

**Issue by zhonghua-wu** [AzureAD/microsoft-authentication-library-for-dotnet#3100]
I  encounter  a problem.
After call AcquireTokenOnBehalfOf with userAssertion , I got a accessToken.
Then I call AcquireTokenSilent with the Account, I got a error " no fresh token".
When I look into the logs, it seems " find 0 access token in partition".

Is this by design or not?

**Comment by bgavrilMS** [comment]
Yes, this is by design. 

`AcquireTokenOnBehalfOf` will look in the cache on itself, so there is no need to call `AcquireTokenSilent`
The reason why we did this is that OBO tokens are session bound. So if you no longer have the original assertion, you should not be able to use OBO tokens. 

I cleanup up our wiki entry about OBO, please have a look: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of

**Comment by zhonghua-wu** [comment]
Here is my scenario :
A user in Microsoft team application ( actually web app), want to export their data to onedrive.
So he start the export from the interface, call the api using user Assert.
But the export process running in backend and the server may reboot when deploy new version.

Do you know if any way can support backend get a usable token and recover after reboot?
Thanks a lot.

Regards.
Howar


发件人: Bogdan Gavril ***@***.***>
发送时间: 2022年1月11日 19:51
收件人: AzureAD/microsoft-authentication-library-for-dotnet ***@***.***>
抄送: Howar Wu ***@***.***>; Author ***@***.***>
主题: Re: [AzureAD/microsoft-authentication-library-for-dotnet] [Problem] AcquireTokenSilent with the Account after AcquireTokenOnBehalfOf don't work (Issue #3100)


Yes, this is by design.

AcquireTokenOnBehalfOf will look in the cache on itself, so there is no need to call AcquireTokenSilent
The reason why we did this is that OBO tokens are session bound. So if you no longer have the original assertion, you should not be able to use OBO tokens.

I cleanup up our wiki entry about OBO, please have a look:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fwiki%2Fon-behalf-of&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570907316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wTmSwnQ9SQz%2FNIxHoZ8ucOlJFx3JJgv49tmYu26UEjk%3D&reserved=0>

―
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fissues%2F3100%23issuecomment-1009888117&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570907316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=31PwkvIW84zZI68B%2BfQnd%2FbTtJCi6OnsaL3fIef3%2By0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPVHW7PL2HLUVNPOAS2IVHLUVQKRRANCNFSM5LVNHGVA&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570907316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zJWRAeNm6ybaBKrz3%2F4GT9G5q%2Fg1ZU41C5rDshZrb3A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570907316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IvKAWEOFivGUs6ebONARJCMmMLK8g3ouwMWkDrrsPUM%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570957314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TBOBZOw9bA4D%2BLxkR3JHyIIQMtaZPFtv5%2FCB%2FM1I2g4%3D&reserved=0>.

**Comment by zhonghua-wu** [comment]
In the wiki , I saw the ILongRunningWebApi.


Could I get a token after reboot with distribute token cache and the session key?
I will test this solution tomorrow.
Thank you for that documentation.

Regards.


发件人: Bogdan Gavril ***@***.***>
发送时间: 2022年1月11日 19:51
收件人: AzureAD/microsoft-authentication-library-for-dotnet ***@***.***>
抄送: Howar Wu ***@***.***>; Author ***@***.***>
主题: Re: [AzureAD/microsoft-authentication-library-for-dotnet] [Problem] AcquireTokenSilent with the Account after AcquireTokenOnBehalfOf don't work (Issue #3100)


Yes, this is by design.

AcquireTokenOnBehalfOf will look in the cache on itself, so there is no need to call AcquireTokenSilent
The reason why we did this is that OBO tokens are session bound. So if you no longer have the original assertion, you should not be able to use OBO tokens.

I cleanup up our wiki entry about OBO, please have a look:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fwiki%2Fon-behalf-of&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570907316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wTmSwnQ9SQz%2FNIxHoZ8ucOlJFx3JJgv49tmYu26UEjk%3D&reserved=0>

―
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fissues%2F3100%23issuecomment-1009888117&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570907316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=31PwkvIW84zZI68B%2BfQnd%2FbTtJCi6OnsaL3fIef3%2By0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPVHW7PL2HLUVNPOAS2IVHLUVQKRRANCNFSM5LVNHGVA&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570907316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zJWRAeNm6ybaBKrz3%2F4GT9G5q%2Fg1ZU41C5rDshZrb3A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570907316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IvKAWEOFivGUs6ebONARJCMmMLK8g3ouwMWkDrrsPUM%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Czhongw%40microsoft.com%7Ca1f8f734edf047b3080b08d9d4f89cac%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637774986570957314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TBOBZOw9bA4D%2BLxkR3JHyIIQMtaZPFtv5%2FCB%2FM1I2g4%3D&reserved=0>.

**Comment by trwalke** [comment]
`Could I get a token after reboot with distribute token cache and the session key?`
Yes you can, distributed caches are intended to be persistant storage so long as the cache is stored somewhere that is persistant.
@zhonghua-wu

**Comment by fuocor** [comment]
I noticed that the first time the token is read from the cache it does not assign the user to the `TokenCacheNotificationArgs` in the `OnAfterAccessAsync` method. Only after token is accessed with `AcquireTokenInLongRunningProcess` then it is set.

**Comment by bgavrilMS** [comment]
@fuocor - let's continue the discussion about that on your issue https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3100
