### ISSUE TITLE
Using `ILongRunningWebApi` does not assign a value to 'TokenCacheNotificationArgs.Account

### ISSUE THREAD

**Issue by fuocor** [AzureAD/microsoft-authentication-library-for-dotnet#3108]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes.  

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by bgavrilMS** [comment]
I'd expect there to be an Account object on CACHE WRITE. When reading the cache, MSAL only has the OBO key. 

MSAL cannot look into the initial assertion for OBO (e.g. it could be encrypted, or it could be in a non-jwt format!) to figure out the account. But your web api can do that, since the assertion is for the web api.
