### ISSUE TITLE
Turn on Encrypt in tokencache, but can't decode the token in another process

### ISSUE THREAD

**Issue by zhonghua-wu** [AzureAD/microsoft-authentication-library-for-dotnet#3110]
I have enabled token cache in my webapi and backend service  with same clientid.
            services.Configure<MsalDistributedTokenCacheAdapterOptions>(
              options =>
           {
               options.DisableL1Cache = false;
               options.Encrypt = true;
               options.SlidingExpiration = TimeSpan.FromHours(24);
           });

when I try to get token in backend with sessionKey. 
I got this error message: "msal v3 deserialization failed to parse the cache contents. is this possibly an earlier format needed for deserializemsalv2? (see https://aka.ms/msal-net-3x-cache-breaking-change)."
if I turn off the Encrypt, it works properly.

it seems that backend can't decode data correctly. 
what configuration should I check for those encyrpt setting?

thanks a lot.

**Comment by trwalke** [comment]
Thoughts on this one @bgavrilMS , @pmaytak ?

**Comment by jmprieur** [comment]
@trwalke @zhonghua-wu 
Wouldn't it be because the encryption keys need to be shared between the machines?
See https://github.com/AzureAD/microsoft-identity-web/wiki/L1-Cache-in-Distributed-(L2)-Token-Cache#data-encryption

**Comment by zhonghua-wu** [comment]
I add this code in both side. with same blob url and same cert string
    services.AddDataProtection()
            .PersistKeysToAzureBlobStorage()
            .ProtectKeysWithCertificate(new X509Certificate2(Convert.FromBase64String());

still get the same error.

**Comment by bgavrilMS** [comment]
Hi @zhonghua-wu - can you check if you can use the ASP.NET Core API to encrypt and decrypt some other data on the 2 machines? 

Microsoft.Identity.TokenCache just use the ASP.NET Core infrastructure for this:

Something like: 

```csharp
// 1. configure the data protection like above

// 2. get the data protector
 IDataProtectionProvider? dataProtectionProvider = serviceProvider.GetService(typeof(IDataProtectionProvider)) as IDataProtectionProvider;
var protector = dataProtectionProvider?.CreateProtector(DefaultPurpose);

// 3. use protector to encrypt and decrypt data
protector.Protect(message); // on machine 1
protector.Unprotect(message); // on machine 2
```

**Comment by zhonghua-wu** [comment]
// 3. use protector to encrypt and decrypt data

protector.Protect(message); // on machine 1

protector.Unprotect(message); // on machine 2

when I run this on machine 1 and 2,  machine 2 will throw a execute time exception.

Regards.

发件人: Bogdan Gavril ***@***.***>
发送时间: 2022年1月13日 18:59
收件人: AzureAD/microsoft-authentication-library-for-dotnet ***@***.***>
抄送: Howar Wu ***@***.***>; Mention ***@***.***>
主题: Re: [AzureAD/microsoft-authentication-library-for-dotnet] Turn on Encrypt in tokencache, but can't decode the token in another process (Issue #3110)


Hi @zhonghua-wu<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzhonghua-wu&data=04%7C01%7Czhongw%40microsoft.com%7Cbbc2f35e27b347d686c708d9d683a964%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776683296267945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=J0NgBphqgEvciL4Y9IzIXsSR9fSF05SjLTH52lFl3Bo%3D&reserved=0> - can you check if you can use the ASP.NET Core API to encrypt and decrypt some other data on the 2 machines?

Microsoft.Identity.TokenCache just use the ASP.NET Core infrastructure for this:

Something like:

// 1. configure the data protection like above



// 2. get the data protector

 IDataProtectionProvider? dataProtectionProvider = serviceProvider.GetService(typeof(IDataProtectionProvider)) as IDataProtectionProvider;

var protector = dataProtectionProvider?.CreateProtector(DefaultPurpose);



// 3. use protector to encrypt and decrypt data

protector.Protect(message); // on machine 1

protector.Unprotect(message); // on machine 2

―
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fissues%2F3110%23issuecomment-1012026280&data=04%7C01%7Czhongw%40microsoft.com%7Cbbc2f35e27b347d686c708d9d683a964%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776683296317936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mqtw9kqlJtBJSJPEnLfjI5XH5vggbdyVfcE7%2Fnn42Og%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPVHW7M7SGLR4EL6VDMV273UV2V6DANCNFSM5L24RLFQ&data=04%7C01%7Czhongw%40microsoft.com%7Cbbc2f35e27b347d686c708d9d683a964%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776683296317936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0BlGm3wldF5skJ9m8Fojn35aakIOoA3lQ1lBAqY0RhQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Czhongw%40microsoft.com%7Cbbc2f35e27b347d686c708d9d683a964%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776683296317936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7SGEOd62UuVZImcBLHPWVf09SXwuSoE0EfOn90ec%2Bpo%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Czhongw%40microsoft.com%7Cbbc2f35e27b347d686c708d9d683a964%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776683296317936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=B60Ew1e37a7QVTvVrGNaH7wQ5XQztl%2FZAnP9BjnX0eY%3D&reserved=0>.

**Comment by bgavrilMS** [comment]
Ok, so it looks like it's a configuration problem with the data protector API, not a bug in the token caching package. This is all described here: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0

Could you try to remove the protection at rest temporarily (`.ProtectKeysWithCertificate(new X509Certificate2(Convert.FromBase64String());`) to debug? Maybe add logging to the package as well ?

**Comment by zhonghua-wu** [comment]
After set application name in protection configuration part.
It works.

Thanks you all !

发件人: Bogdan Gavril ***@***.***>
发送时间: 2022年1月13日 23:21
收件人: AzureAD/microsoft-authentication-library-for-dotnet ***@***.***>
抄送: Howar Wu ***@***.***>; Mention ***@***.***>
主题: Re: [AzureAD/microsoft-authentication-library-for-dotnet] Turn on Encrypt in tokencache, but can't decode the token in another process (Issue #3110)


Ok, so it looks like it's a configuration problem with the data protector API, not a bug in the token caching package. This is all described here: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Faspnet%2Fcore%2Fsecurity%2Fdata-protection%2Fconfiguration%2Foverview%3Fview%3Daspnetcore-6.0&data=04%7C01%7Czhongw%40microsoft.com%7C595ce0444b3647872a4708d9d6a85400%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776840763318848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dBHteUVhPY4VTnoJoDK0KNbJ%2F%2FRvUifo4a86mYkxHH4%3D&reserved=0>

Could you try to remove the protection at rest temporarily (.ProtectKeysWithCertificate(new X509Certificate2(Convert.FromBase64String());) to debug? Maybe add logging to the package as well ?

―
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fissues%2F3110%23issuecomment-1012235719&data=04%7C01%7Czhongw%40microsoft.com%7C595ce0444b3647872a4708d9d6a85400%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776840763368850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hufogIqa%2B8BAoewS8%2BQHCJzZS2N3kytUYDMkgkXYTwI%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPVHW7KMH3YZ5QBA2D3573DUV3UWLANCNFSM5L24RLFQ&data=04%7C01%7Czhongw%40microsoft.com%7C595ce0444b3647872a4708d9d6a85400%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776840763368850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jWvc9gGBB11TU9T%2BJ5veNaiI6oUM7zSpAAOyYt%2BtwIY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Czhongw%40microsoft.com%7C595ce0444b3647872a4708d9d6a85400%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776840763368850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7umHO0OJUuNLZRjzfKveno1XEu8%2BjTTE4SWidbjPseg%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Czhongw%40microsoft.com%7C595ce0444b3647872a4708d9d6a85400%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637776840763368850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wFA9xRiPl1YKrBKVgWyHb5bK1ib61HdOTItxTcqq4A4%3D&reserved=0>.

**Comment by bgavrilMS** [comment]
Great, thanks for lettings us know what the problem was @zhonghua-wu !
