### ISSUE TITLE
[Feature Request] Add "skip token caching" option to IConfidentialClientApplication

### ISSUE THREAD

**Issue by ekaleksa** [AzureAD/microsoft-authentication-library-for-dotnet#3113]
**Scenario**
For applications which have a custom layer of in-memory caching built on top of the IConfidentialClientApplication, it will be more memory efficient to have the ability to not store tokens issued through Msal in the built-in library in-memory cache.

**Proposal**
Provide a flag which when set to true will skip caching of an acquired token to the in-memory Msal cache.

**Comment by jmprieur** [comment]
@ekaleksa  the issue I see with this, is unless these applications are using a sold SDK on top of MSAL there would no longer be a guaranty for MSAL to provide resilience and security any longer.

**Comment by bgavrilMS** [comment]
As per @jmprieur 's comment, we will not fix this. Please reach out to us to improve token caching in MSAL.
