### ISSUE TITLE
Expose the ability to add a custom string to auth dialogs such as WAM

### ISSUE THREAD

**Issue by rub8n** [AzureAD/microsoft-authentication-library-for-dotnet#3125]
**Is your feature request related to a problem? Please describe.**
We currently don't have a contextual way (e.g., on the actual authentication dialog) to tell VS users about why they are being prompted for credentials.

**Describe the solution you'd like**
We want to have the ability to send a custom string to authentication dialogs such as the one below:

![image](https://user-images.githubusercontent.com/11544832/151049554-04dd06de-3716-46d0-b9d1-3983a31e4c95.png)

The string should be surfaced across all screens that can benefit from the context (e.g., screens that leverage login hints)

**Describe alternatives you've considered**
We are considering adding additional context in other parts of the products.

**Comment by kyle-rader** [comment]
Following

**Comment by bgavrilMS** [comment]
Added a tag that will speed up things @kyle-rader

**Comment by gladjohn** [comment]
This has been fixed in [MSAL 4.41.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.41.0)
