### ISSUE TITLE
[Documentation] Clarify requirements / steps to get UseCorporateNetwork working in UWP apps

### ISSUE THREAD

**Issue by RobertVS-MS** [AzureAD/microsoft-authentication-library-for-dotnet#3131]
**Documentation related to component**

PublicClientApplicationBuilder

**Please check those that apply**

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**

Current documentation doesn't really detail well the SSO / MS-APP redirect uri requirement in UWP apps to get UseCorporateNetwork to work properly

**Comment by bgavrilMS** [comment]
Won't fix. Please use WinUI.
