### ISSUE TITLE
[Feature Request] Enable Azure.Identity to benefit from MSAL.NET token cache when used for Managed identity

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#3137]
**Is your feature request related to a problem? Please describe.**
Azure.Identity (Azure SDK) is using MSAL.NET for some flows, and in that case it benefits from MSAL.NET cache. But in other cases, it goes directly to the MSI endpoint, and does not cache the token.
The ask is to have a way for the Azure SDK to benefit from MSAL.NET cache

**Describe the solution you'd like**
The spec is [here](https://microsoft.sharepoint.com/:w:/t/activedirectory/acmi/EUyj9w-qLt5IqsqtXydnFdAB0nIbjbBQKbjTLl-RuWSpCw?e=QftciK)

**Describe alternatives you've considered**
See the spec

**Additional context**
This will be a consistency item,

**Comment by jmprieur** [comment]
See also the previous spike: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/ffb0592e10dc5938980b02486d228406c9587370

**Comment by bgavrilMS** [comment]
@trwalke - please sync with @schaabs on this first and also read the spec.
