### ISSUE TITLE
[Bug] MacPlatformProxy.StartDefaultOsBrowserAsync crashes

### ISSUE THREAD

**Issue by sady4850** [AzureAD/microsoft-authentication-library-for-dotnet#3143]
In Xamarin.Forms for Mac

```Process.Start("open", url)``` always fails with

```
System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x000f6] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/System/System.Diagnostics/Process.cs:616 
  at System.Diagnostics.Process.Start () [0x00032] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin
```

Versions:
Visual Studio Community 2019 for Mac
Version 8.10.17 (build 2)
Installation UUID: ed6d2ea0-5b98-4d0a-a2d9-57b59223c033
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

Mono Framework MDK
Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

Roslyn (Language Service)
3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

NuGet
Version: 5.9.0.7134

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.201
	3.1.200
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.1
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.3
	3.1.2
	2.1.23
	2.1.22
	2.1.17

Xamarin.Profiler
Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.2.1 (19586)
Build 13C100

Xamarin.Mac
Version: 8.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

Xamarin.iOS
Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

Xamarin Designer
Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

Xamarin.Android
Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/dmitrybarakhov/Library/Android/sdk
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 31.0.0

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

Android Device Manager
Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

Build Information
Release ID: 810170002
Git revision: 58f7763d4d64fcf005a474d25a5d9fd5ce46d7f5
Build date: 2022-01-05 12:51:28-05
Build branch: release-8.10

Operating System
Mac OS X 11.6.2
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Nov 10 22:23:07 PST 2021
    root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64

**Comment by bgavrilMS** [comment]
Not sure what the problem is. What is the code that you are running?

**Comment by sady4850** [comment]
I'm using this library in Xamarin.Forms for Mac project. During authentication it crashes in ```MacPlatformProxy.StartDefaultOsBrowserAsync``` due to  ```Process.Start("open", url)``` will always fail (see call stack above). As for your default implementation for starting a browser doesn't work in this case could you provide a service to implement which will be called for launching a browser ?

**Comment by bgavrilMS** [comment]
We don't really support running from Mono. Can you run either under .NET Core or under Xamarin.Mac ?

**Comment by bgavrilMS** [comment]
Ah yes, luckily we already have that. Have a look at `OpenBrowserAsync` from the options of `.WithSystemWebViewOptions(options)`  - this allows you to define your own logic for opening the browser and navigating the an URL.

**Comment by bgavrilMS** [comment]
@sady4850 - I can try to help fix this issue. The method that fails is very simple, it just opens a browser and navigates to a URL: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/12178a78ea187b4e385a6e0a849bfc88f904f738/src/client/Microsoft.Identity.Client/Platforms/netdesktop/NetDesktopPlatformProxy.cs#L217

Can you get this code to work in your setup?
