### ISSUE TITLE
[Bug] XML documentation for suggestion cache key is not well formed

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#3147]
**Repro**
See https://docs.microsoft.com/en-us/dotnet/api/azure.identity.tokencacherefreshargs.suggestedcachekey?view=azure-dotnet#azure-identity-tokencacherefreshargs-suggestedcachekey

![image](https://user-images.githubusercontent.com/13203188/153060632-604744e6-1a4d-4fd4-a6c7-3fd4c5447cc3.png)

**Expected behavior**
We should see the items. 

**Actual behavior**
We only see the bullet points

**Possible solution**
Fix the XML comment

**Comment by pmaytak** [comment]
Fixed in Azure SDK repo also.
