### ISSUE TITLE
[Bug] Fallback to browser auth in W10 Broker scenario - 4.41.0

### ISSUE THREAD

**Issue by MarcJenningsUK** [AzureAD/microsoft-authentication-library-for-dotnet#3148]
**Which version of MSAL.NET are you using?**
MSAL.Net 4.41.0

**Platform**
.Net 4.7.2 WPF

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL.

**Expected behavior**
Windows 10 shows broker login, Server 2016 falls back to browser

**Actual behavior**
Updated to 4.41 to allow running on server 2016.  App now falls back from Broker to browser auth on both Windows 10 and 2016

**Additional context / logs / screenshots / links to code**
Both Windows 10 and Server 2016 in the app return Microsoft Windows NT 6.2.9200.0 from Environment.OSVersion.VersionString

**Comment by MarcJenningsUK** [comment]
Sorry, my bad.  I was expecting 2016 to fall back to the browser and W10 to use the broker.  Both fall back to browser now.  No code changes other than package upgrade

**Comment by bgavrilMS** [comment]
@MarcJenningsUK  - I just tried with a WinForms app on NET 4.7.2 and I see WAM popping up. In MSAL 4.41 we stopped using `Environment.OSVersion.VersionString` completely to detect win version and started calling into some Windows APIs - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/ed901db2a22bd860db1050a5bfbda667468247d4/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/Win32VersionApi.cs#L155

1. Are you using `Environment.OSVersion.VersionString` in your code to enable / disable WAM? 
2. How does your code look like? In particular, how do you create your public client application and how do you enable WAM?

![image](https://user-images.githubusercontent.com/12273384/153211445-521550c7-0edb-4263-a304-93d9491694c1.png)

**Comment by MarcJenningsUK** [comment]
The only use of OSVersion is in App Isights logging.  I just noticed they were the same.  We do not use that check to drige any logic.

Code to generate the PCA is


`var clientId = ConfigurationManager.AppSettings["ClientId"];`
`var tenantID = ConfigurationManager.AppSettings["TenantId"];`
`var scopeVar = ConfigurationManager.AppSettings["ScopeVar"];`
`scope = new [] { scopeVar };`
`PublicClientApplicationOptions applicationOptions = new PublicClientApplicationOptions()`
`{`
`    AzureCloudInstance = AzureCloudInstance.AzurePublic,`
`    ClientId = clientId,`
`    TenantId = tenantID,`
`    RedirectUri = redirectURL`
`};`
`this.publicClientApp = PublicClientApplicationBuilder.CreateWithApplicationOptions(applicationOptions)`
`    .WithWindowsBroker()`
`    .Build();`

**Comment by MarcJenningsUK** [comment]
@bgavrilMS also worth reiterating that this is a WPF 4.7.2 app, not WinForms.

**Comment by bgavrilMS** [comment]
What version of Windows 10 do you have?

**Comment by MarcJenningsUK** [comment]
@bgavrilMS Microsoft Windows [Version 10.0.18363.2037]

Revalidated with a sample app.  With identical code 4.40 shows the broker.  4.41 shows the browser based auth.

Sample app is the one downloaded from the AAD app registration Get started page, modified to suit our own environment and setup.

**Comment by bgavrilMS** [comment]
Is that Windows Pro, Home or Enterprise?

We probably have a bug in our Windows detection logic, which has changed in 4.41

**Comment by MarcJenningsUK** [comment]
@bgavrilMS  W10 Enterprise

**Comment by gladjohn** [comment]
@MarcJenningsUK can you please run this sample app and paste the output. This is an extract of the new logic to determine the OS Version Information using RtlGetVersion https://github.com/gladjohn/RTLVersionInfo.git

**Comment by MarcJenningsUK** [comment]
@gladjohn  `Product Type 1. Major Version 10. Build Number 18363.`

That is the same response for the framework 4.8 exe as supplied as for 4.7.2 when I replaced the framework version in the project file

**Comment by MarcJenningsUK** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/25245008/153248363-0be30cae-c9f8-47c6-9b3c-68b00f8f1d1c.png">

**Comment by MarcJenningsUK** [comment]
@gladjohn I also copied IsWamSupportedOs from the repo into the project and it returns True, so whether there's a defect elsewhere than OS detection I don't know.

**Comment by gladjohn** [comment]
Thanks @MarcJenningsUK for getting back on this with the detailed information. Looking at other changes we did for WAM for 4.41.0

**Comment by gladjohn** [comment]
@MarcJenningsUK we fall back to browser when the [authority is ADFS 2019](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2836). What is the authority in your case?

**Comment by bgavrilMS** [comment]
@gladjohn  - I think Marc sets `AzureCloudInstance = AzureCloudInstance.AzurePublic` (see code above) which is AAD only.

**Comment by MarcJenningsUK** [comment]
Yes, AAD.

**Comment by gladjohn** [comment]
Hi @MarcJenningsUK , if you have MSAL logging enabled. can you please share the extended logging information?

**Comment by MarcJenningsUK** [comment]
@gladjohn We don't but we can pop it in for test purposes.

**Comment by gladjohn** [comment]
@MarcJenningsUK  also please paste a screenshot of the account picker you are seeing, maybe it is the AAD plugin account picker that is showing up? this was fixed as part of [bug 2289](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2289). You can also verify the difference in the account picker from the screenshots posted on that bug

**Comment by MarcJenningsUK** [comment]
@gladjohn
[AuthLog.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/8040043/AuthLog.txt)
 
Sorry, I am unable to post a screenshot of the auth window, but our RPA and UI test scenarios are expecting to see the Windows account picker as shown [above](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3148#issuecomment-1033765868) but we see the Account picker of the AAD plugin as per the linked bug screenshots

**Comment by bgavrilMS** [comment]
Ok, so, I think this is as expected... You are still using WAM, but the UI experience has changed because of #2289 as @gladjohn  mentioned. 

When you specify the authority as "/organizations" or "/tenantId" as you do, then you configure the application to use only work and school accounts. /organizations means "any work and school accounts" and /tenantId means only the work and school accounts in your organization.

Because we know you deal only with AAD accounts, there is no need for the account picker UI. This is a Windows component we're having problems with and getting logs for it is hard etc. See for example bugs #3044 and #2560. The account picker you see is still part of WAM, but somewhat more stable. The Windows Account Picker is necessary only when dealing with personal accounts (i.e. you set the tenant to "common" or "consumers")

WAM's internal account picker
![image](https://user-images.githubusercontent.com/12273384/153389554-b8a94f1c-ace8-4c48-86d1-848e8eff82f5.png)

Windows account picker
![image](https://user-images.githubusercontent.com/12273384/153389686-29054953-51bc-46da-9b7f-3d7fa9c7aedd.png)

**Comment by gladjohn** [comment]
@MarcJenningsUK thanks for the confirmation that it is the AAD plugin account picker and not the browser. Here is the [PR for the fix to show AAD plugin account picker](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3101) if the authority is AAD, @bgavrilMS FYI

**Comment by MarcJenningsUK** [comment]
Thanks for the confirmation.  It is disappointing, however, since we now have additional effort to refactor our RPA and UI Test processes to account for the somewhat undocumented behavioral changes.

**Comment by bgavrilMS** [comment]
Thanks for the feedback @MarcJenningsUK , that is good learning that changing UX experiences breaks test plans for app owners and we need to minimize it. If you find any gaps or you find that the experience is degraded, please let us know. We could allow apps to revert back to the old behavior via a setting if needed. 

And many thanks for the very prompt replies to the many questions and asks from us!

**Comment by MarcJenningsUK** [comment]
I have just asked our RPA team to confirm whether they can interact with the new UI at all - I know that was a concern when we started our migration to the cloud efforts.  Thanks for your attention, but could you confirm how we could request fallback behavior if it turns out to be required?

**Comment by bgavrilMS** [comment]
Just open a feature request here on GitHub, or reopen this issue.
