### ISSUE TITLE
[Bug] Privacy and TOU links not visible in embedded picker UI for smaller screen

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3153]
**Logs and network traces**
NA

**Which version of MSAL.NET are you using?**
Not specified

**Platform**
Windows

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
Existing Whiteboard app 

**Repro**

**Expected behavior**
ToU link is visible

**Actual behavior**
TOU Link not visible 

**Possible solution**

**Additional context / logs / screenshots / links to code**
In the https://intentional.visualstudio.com/intent/_workitems/edit/68876

**Comment by ShubhiamRepo** [comment]
Could you please share an ETA for this if possible.

**Comment by ShubhamMsoft** [comment]
@bgavrilMS Could you please provide an update the ETA here if possible.

**Comment by bgavrilMS** [comment]
I assume this occurs with embedded webview only and not with WAM. We recommend using WAM everywhere. We are exploring a more complex fix for this kind of issues in a major upgrade to MSAL.

**Comment by ShubhamMsoft** [comment]
@bgavrilMS Could you please provide an update the ETA here if possible. Thanks.

**Comment by bgavrilMS** [comment]
Hi @ShubhamMsoft, we will not be fixing this. Recommendation is to use WAM. See https://aka.ms/msal-net.wam
