### ISSUE TITLE
[Documentation] Update WAM docs for the AAD plugin introduced in MSAL 4.41.0

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3155]
**Documentation related to component**
WAM AAD Plugin 

**Please check those that apply**

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation may need clarification or updated screenshots of the UI to differentiate between Windows account picker
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**
documentation may need clarification or updated screenshots of the UI to differentiate between Windows account picker

**Comment by bgavrilMS** [comment]
What do you need to update here @gladjohn ?

**Comment by gladjohn** [comment]
this was more for tracking the windows/aad account picker UI. Need to find if there is a screenshot update for any docs

**Comment by bgavrilMS** [comment]
I propose that we don't update the docs with this. Too much documentation is as bad as too little doc. This behavior can easily be observed while testing, and the GH issues around it are also easy to find.
