### ISSUE TITLE
Getting OS or first account when signed in with an MSA fails

### ISSUE THREAD

**Issue by crmann1** [AzureAD/microsoft-authentication-library-for-dotnet#3157]
When the user is signed into windows with an MSA account, and we try and get a token for the signed in user we get two different kinds of error messages but no token is retrieved. 

1) Ask for the OS account
   var appBuilder = PublicClientApplicationBuilder.Create(NewClientId)
                .WithAuthority(AadAuthorityAudience.AzureAdMultipleOrgs)
                .WithExperimentalFeatures()
                .WithWindowsBrokerOptions(new WindowsBrokerOptions
                 {
                     ListWindowsWorkAndSchoolAccounts = true,
                     MsaPassthrough = true,
                 })
                .WithWindowsBroker();

            var pca = appBuilder.Build();

            try
            {
                var resultSignedIn = await pca.AcquireTokenSilent(new string[] { "https://graph.microsoft.com/User.Read" }, PublicClientApplication.OperatingSystemAccount).ExecuteAsync();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
   
![image](https://user-images.githubusercontent.com/12025013/153682497-be71ee7f-c526-4bc0-b197-0941b0023561.png)

2)  Instead of using the operating system account we just use the first account (which is the MSA)
       var accounts = await pca.GetAccountsAsync();
       var resultFirst = await pca.AcquireTokenSilent(new string[] { "https://graph.microsoft.com/User.Read" }, accounts.First()).ExecuteAsync();
![image](https://user-images.githubusercontent.com/12025013/153682563-83813457-fbdb-42b0-b650-f7e7ef5693c0.png)

**Comment by gladjohn** [comment]
Hi @crmann1 you can find the WAM calling pattern documented [WAM Calling Patter](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WAM) 

you can also take a look at this [WPF sample that uses WAM](https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2) for more guidance.

**Comment by crmann1** [comment]
Thanks for the pointers, however that document does not discuss the issue seen here.  The issue here is about asking for the OS default account not working when the windows user is an MSA, and the second part is related to it but trying to use the account listed in the accounts collection not working either when it is the signed in windows user and is an MSA.

**Comment by gladjohn** [comment]
@crmann1 what version of MSAL are you using? can you please add some logs to the issue. I am able to sign-in successfully and acquire a token.

**Comment by bgavrilMS** [comment]
We may need to reach out to WAM folks to understand why this occurs. We'll need very exact logs. Let's sync on this @gladjohn

**Comment by bgavrilMS** [comment]
I had a discussion with WAM folks and they confirmed the following: 

1. You will not be able to silently login with Default OS Account if this account is MSA :( This is a limitation of WAM + MSA-PT.
2. You should however be able to perform account discovery, list all accounts (AAD and MSA) and request tokens silently for all of them. The fact that you cannot is a bug in MSAL C#, which I think we have already logged - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3121 (ignore the part of the "workaround exists")
