### ISSUE TITLE
[Documentation] Document troubleshooting steps for Accounts Settings Pane failures for win32 and UWP apps

### ISSUE THREAD

**Issue by maliksahil** [AzureAD/microsoft-authentication-library-for-dotnet#3158]
**Documentation related to component**
Win32/UWP apps using the account settings pane

**Please check those that apply**

- [ ] typo
- [x ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**
Identity SDKs now use Accounts Settings Pane for integration with WAM. This sometimes fails, for example the control blinks and returns no data. 

Please publish details about how to get detailed information about the failure, so that we can come back to you for a meaningful root cause session. We should have instructions for both win32 and UWP apps. 

https://microsoft.visualstudio.com/OS/_workitems/edit/38159669

**Comment by bgavrilMS** [comment]
Done, https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam#troubleshooting
