### ISSUE TITLE
Why is the token endpoint hardcoded instead of obtained by the well known endpoint

### ISSUE THREAD

**Issue by sleepwalkerffs** [AzureAD/microsoft-authentication-library-for-dotnet#3165]
I was implementing a ClientCredentialsFlow and therefore I was utilizing the `services.AddAccessTokenManagement(...)` extension method in order to register a `.ConfigureBackchannelHttpClient()` to obtain the access token automaticically. So as I did before with other Identity servers I went to the well known endpoint in my case `https://login.windows.net/{tenantId}/.well-known/openid-configuration`  which gave me the following JSON (shorted for brevity):  
```jsonc
{
  "token_endpoint": "https://login.windows.net/{tenantId}/oauth2/token",
  //more stuff here  
}
```  
so I configured the `ClientCredentialsTokenRequest` to have the `oauth2/token` as the token endpoint. 
The results where that I did get an access token but no role claims came with it. I tried to implement it then according to the microsoft documentation [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-app-configuration?tabs=dotnet#instantiate-the-confidential-client-application-with-a-client-secret) and [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-acquire-token?tabs=dotnet#acquiretokenforclient-api). Long story short, with this implementation I did get role claims with the access token. I debugged into the code to see how the http request is setup (because I thought I missed some settings or stuff) and found this piece of code [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/b32458fde68d27929cc35f8af2eeda1b8257de22/src/client/Microsoft.Identity.Client/Instance/AadAuthority.cs#L16) and was surprised that the token endpoint is hardcoded instead of obtained from the well known endpoint. It would be nice to know the reasoning behind that and the decision why not to implement it as the standard way. 😄   

Thank you in advance

**Comment by bgavrilMS** [comment]
This was done for perf reasons to avoid an HTTP call. For token acquisition, MSAL only needs to know the token endpoint. We don't need any keys or anything else from the `.well-known` OIDC endpoint. And the token endpoint for AAD is `"{authority}/oauth2/v2.0/token"`

Note that MSAL only works with AAD authorities (well, and ADFS and B2C, but the story is similar). When we'll support "any authority", we'll have to use the well-known endpoint.

**Comment by sleepwalkerffs** [comment]
Ok, I totally understand that from you Point of View but the question for me still remains: "Why is the token endpoint, stated by the well known endpoint, incorrect". But I guess I have to ask someone else, someone from the AAD team. 😄

**Comment by bgavrilMS** [comment]
Ah, I understand your question better now. This is because AAD has been around for a very long time, before OAuth2. Once OAuth2 was added, AAD wanted to become standards compliant, but it cannot simply turn off the old service. So it versioned it. 

Old v1 endpoint: https://login.microsoftonline.com/common/.well-known/openid-configuration
New v2 endpoint: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

MSAL library only talks to v2 endpoint.
