### ISSUE TITLE
[Feature Request] Allow changing region at request level

### ISSUE THREAD

**Issue by mezaugusto** [AzureAD/microsoft-authentication-library-for-dotnet#3171]
**Is your feature request related to a problem? Please describe.**
In case the regional endpoint is unavailable we need to retry the request with the global endpoint.

However, this configuration(`WithAzureRegion`) is limited to the client builder. We currently reuse clients between requests to cache tokens so we would like to be able to change the region at the request level.

**Describe the solution you'd like**
Being able to change region from the `AcquireTokenForClientParameterBuilder` or being able to reset a request to the global endpoint.

**Describe alternatives you've considered**
- The alternative we have is to create two clients, one with the regional endpoint and one with the global endpoint.
We can't create a client every time and use shared cache as we need the token serialization.

- Using `WithAuthority` with the global endpoint has no impact as the regional endpoint is still used

**Additional context**
It seems this capability was present but was removed in #2509.

**Comment by jmprieur** [comment]
That would work @mezaugusto
