### ISSUE TITLE
[Bug] Clear IOS Keychain values stored by MSAL in Xamarin Forms (IOS)

### ISSUE THREAD

**Issue by sandeep1503** [AzureAD/microsoft-authentication-library-for-dotnet#3172]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.31.0(Microsoft.identity.client)

**Platform**
Xamarin Forms 5.0.0.2196

**What authentication flow has the issue?**
* Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
This is related to logout and clean.  Values are stored in xamarin IOS keychain. 

**Is this a new or existing app?**
This is a new app

**Repro**

```csharp
request creation-- 
---------------------
this.app = PublicClientApplicationBuilder.Create(ClientId)
                .WithIosKeychainSecurityGroup("com.myorgname.appname")
                .WithAuthority(AuthEndpoint)
                .WithLegacyCacheCompatibility(false)
                .WithRedirectUri(this.RedirectUri)
                .Build();

login--
-------------------
   authResult = await this.app.AcquireTokenInteractive(this.scopes)
                                                .WithParentActivityOrWindow(ParentWindow)
                                                .WithExtraScopesToConsent(this.extraScopes)
                                                .ExecuteAsync().ConfigureAwait(true);

Logout -- 
---------------------

var accounts = await this.app.GetAccountsAsync().ConfigureAwait(true);
            while (accounts.Any())
            {
                await this.app.RemoveAsync(accounts.FirstOrDefault()).ConfigureAwait(true);
                accounts = await this.app.GetAccountsAsync().ConfigureAwait(true);
               
            }
            SecureStorage.RemoveAll();
            ClearCache?.Invoke();

 ```

**Expected behavior**
MSAL should have proper way to logout and clear all values stored by library from IOS Keychain.

**Actual behavior**
Keys and secrets are still available in IOS Keychain even after logout. 

**Possible solution**
Is there any possible solution to clear these values from IOS Keychain programatically. 

**Additional context / logs / screenshots / links to code**
<img width="580" alt="Screenshot 2022-02-18 at 11 17 05 AM" src="https://user-images.githubusercontent.com/24807994/154625722-dd545087-a398-4918-b31c-3e86ac4d6def.png">

**Comment by bgavrilMS** [comment]
When you sing out a user via the `RemoveAsync(account)` API, the values will be deleted.

**Comment by sandeep1503** [comment]
@bgavrilMS Our Pentest team has done testing from their side and able to find the key values in their testing as shown in the screenshot. They have recommended to encrypt or prevent the storage of sensitive information on keychain and to always specify an accessibility level explicitly when storing sensitive data into the Keychain. 

Please help what needs to be done here.

**Comment by bgavrilMS** [comment]
App access to the keychain is considered secure from Microsoft perspective and these libraries undergo security reviews regularly.

 All our code for accessing the keychain is open source here, so you can inspect it - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Platforms/iOS/iOSTokenCacheAccessor.cs. KeyChain is secure and the MSAL libraries assume the device is not jailbroken. 

The libraries do not provide develop access to the cache on mobile platforms. We are working on enabling proof of possession tokens, which would add a level of encryption, but this is some way away.
