### ISSUE TITLE
Would like to know kind of account the default OS account is

### ISSUE THREAD

**Issue by crmann1** [AzureAD/microsoft-authentication-library-for-dotnet#3174]
We would like you to expose on the Public client application what kind of account the default OS signed in account it. 

In MSAL currently there is code to do
bool IsDefaultAccountMsaAsync()  = consumers 

What would be great is if you could have a method called  GetDefaultAccountProviderAuthority
 so we can compare the strings ourselves incase they every add something else or change. If no provider could be found then maybe just null is fine.

**Comment by bgavrilMS** [comment]
This can be done through Windows APIs or by getting a token for the logged in user and checking the home account id.
