### ISSUE TITLE
[Bug] Error in creating UWP package for Microsoft Store Upload

### ISSUE THREAD

**Issue by vinodshinde** [AzureAD/microsoft-authentication-library-for-dotnet#3184]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.41.0

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    *  Interactive

**Is this a new or existing app?**
The app is in production and currently using legacy Live SDK, 
I am trying to upgraded MSAL, but started seeing this issue.

**Expected behavior**
It should create a UWP app package to upload to store.

**Actual behavior**
App package creation fails with following error
C:\Users\User\\.nuget\packages\microsoft.net.native.compiler\2.2.11-rel-30601-02\tools\Microsoft.NetNative.targets(805,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'ntdll.dll!RtlGetVersion' for method 'System.Int32 Microsoft.Identity.Client.PlatformsCommon.Shared.Win32VersionApi.RtlGetVersion(Microsoft.Identity.Client.PlatformsCommon.Shared.Win32VersionApi.OSVERSIONINFOEXW)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

C:\Users\User\\.nuget\packages\microsoft.net.native.compiler\2.2.11-rel-30601-02\tools\Microsoft.NetNative.targets(805,5): error : Internal compiler error: Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by bgavrilMS** [comment]
@vinodshinde - how do you create the package?
@gladjohn - I think we may need to find another solutuion for the versioning `RtlGetVersion` as it might not work in UWP.

**Comment by vinodshinde** [comment]
I use this menu
![image](https://user-images.githubusercontent.com/1417468/155549557-ee0cb939-09b1-47b1-ba91-f4e87cd5f6d1.png)

**Comment by bgavrilMS** [comment]
Ack, please use MSAL 4.40 until we sort this out.

**Comment by vinodshinde** [comment]
I am actually using Microsoft.Graph which pulls the latest MSAL by default. so not sure how to force Microsoft.Graph to use 4.40 version

**Comment by bgavrilMS** [comment]
@vinodshinde - you can take a direct dependency on MSAL 4.40 and that will override Microsoft.Graph's dependency.

**Comment by bgavrilMS** [comment]
@gladjohn  - can we get rid of those warnings by setting this `DllImport(ExactSpelling=true)` ? Do we even call this logic in UWP?

**Comment by gladjohn** [comment]
Yes the plan is to fix the warnings for the next release by adding `DllImport(ExactSpelling=true)`. We do not call into the DesktopOSHelpers for UWP we just enable broker by default.

**Comment by vinodshinde** [comment]
@bgavrilMS @gladjohn I added direct dependency on MSAL 4.40 but the AppPackage creation still failed. Also tried by deleting all bin and obj folders.
Finally ended up removing Microsoft.Graph nuget package completely from project.

Used WebAutheticationBroker for OAuth flow and using direct REST API calls using HttpClient on Microsoft Calendar and OneDrive. I only need List, Upload, Download from OneDrive. On Calendar i needed CRUD on Calendar and CRUD on calendar events. So it was not that bad.
Thank you for looking into it.

**Comment by DRAirey1** [comment]
Ran into this issue trying to publish to the store. I had everything working just great on my local machine and I decided just to make sure I had the latest version of everything before I published my UWP package to the store. Pulled down Microsoft.Identity.Client 4.42.1 and published. Spent the next hour trying to figure out why my package was rejected with:

```
Error Found: The supported APIs test detected the following errors:
API RtlGetVersion in ntdll.dll is not supported for this application type. ThetaRex.OpenBook.Desktop.dll calls this API.

```
Finally, as the only think I really changed before publishing was the new version of Microsoft.Identity.Client. So I dropped back to 4.42.0 and everything passed the validation and published.

**Comment by bgavrilMS** [comment]
Ack, thanks for the details @DRAirey1 - so it looks like the errors occur at the time you upload the package to the store. 

@gladjohn - can we just consider WAM to be available all the time on UWP ? I doubt ppl install UWP apps on Win Server 2016 and if they do, we'll just have to escalate to Windows team for guidance. But until then, I recommend we just ignore the Window versioning stuff on UWP.

**Comment by DRAirey1** [comment]
> so it looks like the errors occur at the time you upload the package to the store.

Correct. I hadn't used the local app validation cycle in a while, but after getting this error I ran it again and it showed the same error.

**Comment by DRAirey1** [comment]
> @DRAirey1 - how do you run this app validation cycle on local app?

Sorry, should have been more clear. In Solution Explorer, select the UWP project and then:
Publish -> Create App Package -> Microsoft Store as <package name> by <company> -> Create -> Launch Windows App Certification Key
