### ISSUE TITLE
[Feature Request] Libset encryption on Ubuntu - use 600 mode on Unix for Token Cache

### ISSUE THREAD

**Issue by maliksahil** [AzureAD/microsoft-authentication-library-for-dotnet#3186]
Please see this issue for details, 
https://github.com/AzureAD/microsoft-authentication-extensions-for-python/issues/106

ADO tracking item https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1760106

We store plaintext on Win, Mac and Linux - same protection is required everywhere.

**Comment by neha-bhargava** [comment]
Investigated how to implement this in C# for all the platforms. Found the following options:
1. For Linux simply write a method to execute the `$"chmod 600 {filePath}"`. Ref: https://stackoverflow.com/questions/45132081/file-permissions-on-linux-unix-with-net-core. This can be used for linux and maybe also for mac but not for windows
2. For NetFramework there is an option to do this in C# by using File.SetAccessControl: https://docs.microsoft.com/en-us/dotnet/api/system.io.file.setaccesscontrol?view=netframework-4.8. This is only available for NetFramework and Xamarin.iOS, Xamarin.Mac. 
3. There is also an option to create an IsolatedStorage and create file with that: https://docs.microsoft.com/en-us/dotnet/api/system.io.isolatedstorage.isolatedstoragefile?view=net-6.0#examples.
