### ISSUE TITLE
[Bug]When trying to authenticate against mooncake with WAM get an error from ESTS

### ISSUE THREAD

**Issue by crmann1** [AzureAD/microsoft-authentication-library-for-dotnet#3187]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
4.41

**Platform**
Windows

**What authentication flow has the issue?**
WAM

**Is this a new or existing app?**
Visual studio

**Repro**

1. Use Windows OS where you have an Work and School account connected to Public Cloud
2. AcquireTokenIntreactive with a sovereign account 
3. When prompted to add the account to the OS, do not choose "App only"

Actual:  

Message: AADSTS90002: Tenant 'xxxxxxxx' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant. 

Talked to bogdan internally, asked to open this bug 

Workaround: user should choose "App Only" option. Failure seems to be related to PRT protocol.

**Comment by bgavrilMS** [comment]
I was able to get a token using these app coordinates with WAM:

![image](https://user-images.githubusercontent.com/12273384/156196934-3ccc46e1-8992-4dee-827e-6ca5b38f01e4.png)

**Comment by bgavrilMS** [comment]
Fixed in 4.42.1
