### ISSUE TITLE
[Bug] Missing default OpenID permission in DeviceCodeRequest.cs?

### ISSUE THREAD

**Issue by tobias-graf-p** [AzureAD/microsoft-authentication-library-for-dotnet#3196]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.41.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [x] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Not sure if other flows are impacted as well.

**Repro**
Initiate a device code flow as per the examples like this:

```csharp
var scopes = new[] { "https://[...].onmicrosoft.com/[...]/user_impersonation" };

var app = PublicClientApplicationBuilder.Create(clientId)
    .WithTenantId(tenantId)
    .Build();

var result = await app.AcquireTokenWithDeviceCode(scopes, deviceCodeResultCallback)
    .ExecuteAsync()
    .ConfigureAwait(false);
```

**Expected behavior**
The [documentation ](https://docs.microsoft.com/en-us/graph/permissions-reference#openid-permissions) states, that _the Microsoft Authentication Library (MSAL) currently specifies offline_access, openid, profile, and email by default in authorization and token requests._ See [here](https://docs.microsoft.com/en-us/graph/permissions-reference#:~:text=The%20Microsoft%20Authentication%20Library%20(MSAL)%20currently%20specifies%20offline_access%2C%20openid%2C%20profile%2C%20and%20email%20by%20default%20in%20authorization%20and%20token%20requests.). So based on this documentation I expect that all four default OpenID permissions would be added to my request (in addition to the one I defined myself in my above code sample).

**Actual behavior**
At least for the device code flow, the library does not add the _email_ permission. See [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Internal/Requests/DeviceCodeRequest.cs#L34). Not sure if it also applies to other flows.

Also not sure if the _email_ permission should actually be added by default or not. But at least the implementation does not match the documentation ...

**Possible solution**
Either fix the documentation or the implementation.

**Comment by bgavrilMS** [comment]
No, `email` is not added. Only the others. I'll fix the docs.

**Comment by tobias-graf-p** [comment]
Just for curiosity: What is the reason that openid, profile and offline_access are added by default (and email not)? I think with openid and profile I can anyway already access the users profile, not? Wouldn't it be more intuitive that the library adds all four default OpenId permissions to the request? Or - on the other hand - that it does not add any default permissions at all?

**Comment by bgavrilMS** [comment]
@tobias-graf-p 

- `openid` is needed so that AAD returns an IdToken. This is very important, because MSAL cannot crack open the Access Tokens (e.g. it would be a security issue, because if you crack open an access token, you must also validate its signature etc. also, the app using MSAL is most likely not the intended destination for the token). But MSAL can crack open the Id Token and figure out a few details from it, such as the `tid` claim, which is important for token caching
- `profile` - don't remember exactly, but I think this adds the `preffered_username` claim to Id Token. This is the recommended "display value" for the user.
- `offline_access` is needed so that AAD also returns a refresh token. Without a refresh token, you'd have to interactively re-auth every few hours. 

We don't need `email` because we only use `preffered_username` to populate Account.Username field. 

In your case, ask for no scopes first, see if the Id Token returned is good enough. Then add `email` if needed.

**Comment by jmprieur** [comment]
@tobias-graf-p: you don't need MSAL to request the email claim.
you can configure the app in the app registration to request it. See **https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims**

**Comment by tobias-graf-p** [comment]
Hi @bgavrilMS, hi @jmprieur 

Thank you very much for your responses. 

I understand (more or less) the purpose of the different claims. But my actual question is why MSAL is adding exactly these three default claims (like `openid`, `profile` and `offline_access`) by default (i.e. why not only `openid` on the one hand or also `email` on the other hand)?

I understand that the `openid` claim is required for AAD to return a token at all. But in my scenario (I think) I would not need the `profile` nor the `offline_access` claim. In my scenario the user authenticates in a cmd application in order to get a token to do **one single** call to one of our api endpoints. The cmd application does not store anything locally, so if the user would want to execute the process again (what he usually doesn't has to do), he would has to re-authenticate again. So I don't need the `offline_access` claim. And neither would I need the `profile` claim, I think. But since MSAL adds these claims to the request by default, the user is also asked for his consent for the `profile` and `offline_access` claims, what in my case (I think) would not be neccessary (and what I would like to avoid). But I don't have an option to **not** pass these claims in my request using the MSAL lib, do I?

**Comment by bgavrilMS** [comment]
MSAL needs these 3 scopes to be able to cache and refresh your tokens.
