### ISSUE TITLE
[Bug] WAM may be invoked on UWP apps on non WAM supported Windows OSs

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3208]
**Logs and network traces**
none

**Which version of MSAL.NET are you using?**
MSAL.NET 4.40.0

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
we may have a bug in MSAL,where on UWP and NET5-windows10... we do not check if the OS is supported. So UWP would try to invoke WAM on Win Server 2016 for example.

We only make this check in .net fx and .net core.

**Comment by bgavrilMS** [comment]
Thanks for raising this @gladjohn - I think it's as simple as adding an extra check here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/a4c11726e3c545cdf2c73ed23f3a16332d2dbb0b/src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs#L818

**Comment by pmaytak** [comment]
@gladjohn Was this fixed by https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3239?

**Comment by gladjohn** [comment]
It is not, we may still invoke WAM on Windows Server 2016 if UWP was sideloaded. But we agreed to close this as won't fix for now

**Comment by bgavrilMS** [comment]
It's unlikely that anyone uses UWP apps on WIn Server 2016. In any case, there doesn't seem to be any reliable information for an SDK (not an app!) to tell the exact OS on UWP.

Closing as won't fix.
