### ISSUE TITLE
[Bug] After returning a token from AcquireTokenInteractive() and giving back control to the caller, the MSAL UI "sticks" and will not go away

### ISSUE THREAD

**Issue by nunotrancoso** [AzureAD/microsoft-authentication-library-for-dotnet#3212]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.4.0+ all have same issue, building with 4.42.0 at the moment.

**Platform**
Xamarin.iOS (XCode 13.2.1, Microsoft Visual Studio Enterprise 2019 Version 16.11.10 )

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ X] Interactive

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.
We have to upgrade to 4.4.0+ because of (non optional) broker use by one client. Everything works great with the old MSAL, except for broker (when changing passwords) so we need to upgrade to a newer version that (as far as docs state...) actually works properly with broker.

```csharp
app = PublicClientApplicationBuilder.Create(_clientid)
				.WithClientId(_clientid)
				.WithTenantId(_tenant)
				.WithIosKeychainSecurityGroup("com.microsoft.adalcache")
				.WithParentActivityOrWindow(SGGlobals._MSALRootViewController)
				.WithRedirectUri(RedirectURI)
				.WithLogging(Log, LogLevel.Info, true)
				.Build();
				
authresult = await app.AcquireTokenInteractive(_scope)
						.WithAccount(firstAccount)
						.WithPrompt(Prompt.SelectAccount)
						.WithParentActivityOrWindow(SGGlobals._MSALRootViewController)
						.ExecuteAsync();
```

**Expected behavior**
If the token has been returned to the caller, the MSAL UI should remove itself.

**Actual behavior**
The token is returned to the caller but the MSAL UI **WILL NOT** go away, rendering the app unusable even though control has been returned to the normal app flow.

**Additional context / logs / screenshots / links to code**
We also get Keychain errors in the MSAL log:

2022-03-07 09:56:40.290 SG[3638:1352696] Warning True MSAL 4.42.0.0 MSAL.Xamarin.iOS Mono 6.12.0 (2020-02/4150e65c9e3) 15.0 [2022-03-07 09:56:40Z] Failed to remove adal cache record: MissingEntitlement
2022-03-07 09:56:40.291 SG[3638:1352696] Warning True MSAL 4.42.0.0 MSAL.Xamarin.iOS Mono 6.12.0 (2020-02/4150e65c9e3) 15.0 [2022-03-07 09:56:40Z] Failed to save adal cache record: MissingEntitlement

but the code in https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations to check Keychain access works fine

**Comment by bgavrilMS** [comment]
Could you try the sample with your app coordinates? We do a manual check for this scenario on every release - https://github.com/azure-samples/active-directory-xamarin-native-v2

**Comment by nunotrancoso** [comment]
Can try, but will have to figure out how Forms works, as the sample app crashes (and never works again...) if i put in our tenant and custom scope in. Btw, we use Native not Forms. and just from looking at it, the UI is quite different... Even added some bits from the sample app to ours, but made no difference, UI still not the same as in Forms. 

`
// on Android and iOS, prefer to use the system browser, which does not exist on UWP
SystemWebViewOptions systemWebViewOptions = new SystemWebViewOptions()
{                            
 iOSHidePrivacyPrompt = true,
};
builder.WithSystemWebViewOptions(systemWebViewOptions);
 builder.WithUseEmbeddedWebView(false);
authResult = await builder.ExecuteAsync().ConfigureAwait(false);
`

**Comment by nunotrancoso** [comment]
Small update. Seems that while the issue happens when MSAL is used, MSAL is not the culprit. While i could not get the Forms sample app to properly behave, ie could not debug it at all, i just created a blank native app and "copy/pasted" the core sample code to the new blank app. All worked as expected, and the "requester" was the "regular" MSAL dialog. Used the sample code from the blank app in our app and... still same problem, still same different dialog.

And the the lightbulb went on. Intune. We are (trying) to integrate the new version of Intune because of broker issues and... yeah, it's the "Intune style" MSAL dialog, even though it's **NOT** an Intune call, we are **NOT** using broker (yet) and we are just trying to do a "regular" MSAL call to an AAD registration endpoint...

Not sure what in MSAL (or even why)  is being messed with, but guess i'll have to move this question to the Intune Xamarin people.

**Comment by nunotrancoso** [comment]
Another small update: Had to reconfigure a development server because of changes we are making, and when using that scenario/server we must pull the app configuration from an API not Intune. And... MSAL works fine. So went and did some more testing.

Long story short:

If app/user **has not** been enrolled in Intune, MSAL works as expected, completes the request and disposes of the dialog.
If app/user **has** been enrolled in Intune, MSAL exhibits this weird behavior of not disposing of the dialog even tough the request has completed and control has been handed back to the app.

**Comment by bgavrilMS** [comment]
@SameerK-MSFT , in case you've seen similar issue.

**Comment by bgavrilMS** [comment]
@nunotrancoso - please not that MSAL doesn't yet support App Protection Policy, just user protection. @SameerK-MSFT is working on the app protection now.

**Comment by bgavrilMS** [comment]
Closing, as we are not able to repro this. Please try with MAUI.
