### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by ModernRonin** [AzureAD/microsoft-authentication-library-for-dotnet#3226]
**Documentation related to component**
I mean [this section](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows#scopes-to-request).

**Please check those that apply**

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**
It would be helpful if you clarified that with "resource Id" you mean only the "api://<appId>" part, without anything like "access_as_user". This just cost me 1-2 hours, so a bit of clarification might help others save that time :-)

Maybe just explain it like this:

> If the scope you'd use with `PublicClientApplicationBuilder` is `api://<someId>/access_as_user`, then for `ConfidentialClientApplicationBuilder` you need to pass `api://<someId>/.default`.

**Comment by jmprieur** [comment]
@ModernRonin : in which document do we need to clarify things/

the scope can be a lot of things. It depends on how the APP ID URI of the web API that you can to call was registered. api://clientIdOfWebApi/scope is the default in newly created web APIs In tenants without a verified domain.
In tenants with verified domains this would be something else (that includes the domain name.)

**Comment by ModernRonin** [comment]
@jmprieur I linked the document and the specific section in the document

**Comment by localden** [comment]
Closing as this is no longer applicable. Full document here: https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/web-apps-apis/client-credential-flows
