### ISSUE TITLE
[Bug] : WAM exception when requesting scope for web api

### ISSUE THREAD

**Issue by vedeevi** [AzureAD/microsoft-authentication-library-for-dotnet#3230]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.Net **4.42.1 (latest version)**

**Platform**
.Net 5 & .Net 6 Console application.

1. Configure WAM 
2. Have a 3p web api exposing resource R
3. Use a single tenant public client application 
4. AcquireTokenInteractive with WAM, requesting a token for scope `R/user_impresonation` or `R/.default`

Actual: 
 **Exception**
"_AADST90008: The user or administrator has not consented to use the application with ID "<our resource id to which we requested token for>".  This happened because application is misconfigured it must request to Microsoft Graph by specifying at least "Sign in and read user profile._"..... 

Expected: token

Important: if not using WAM, we get a token

For our AAD App Id , admin consent was already granted to Microsoft Graph "User.Read", etc. permissions and not sure why we are getting this above said error when trying to get the token using "user_impersonation" OR ".default" scope.

**Additional context / logs / screenshots / links to code**

**Comment by vedeevi** [comment]
Hi Team,

Please let us know is this bug got prioritized for fixing and when can we expect the release of this bug fix in the new version of libraries...

Thanks,
vedeevj.

**Comment by bgavrilMS** [comment]
The workaround to this issue is to use the GUID format of the API ID:

![image](https://user-images.githubusercontent.com/12273384/161546990-4d8702b7-0251-4a24-a4fa-17d0e0995694.png)

If you are using the normal format today, try to use the format: 

`api://<client_id>`

**Comment by bgavrilMS** [comment]
Tracking AAD issue: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1800497

**Comment by AndreErb** [comment]
@bgavrilMS 
Unfortunately, the [workaround](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3230#issuecomment-1087514172) you suggested above doesn't work for all scenarios. 

It doesn't work specifically if one needs to aquire a token with a scope for one and the same app registration.
It only works if you have 2 app registrations, 1 Client App and 1 API App registration.
I think that's what you were trying to say [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3264#issuecomment-1091608569):
> Yes, these are both known issues for WAM
> 
> 1. Requesting a web api scope from the same client id: [[Bug] : WAM exception when requesting scope for web api #3230](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3230)
> 
> Possible workaround: use the GUID format of the scope and use separate client IDs for the public client and the web api.
> 

However, if you have only 1 client app registration and aquire a token for that, the same error is returned.

You pointed out, that it's not a MSAL issue but an Azure AD issue.
Unfortunately, we cannot track the issue, as the URL [seems to be private](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3230#issuecomment-1087523362).

**Comment by bgavrilMS** [comment]
Yes, thanks for the clarification @AndreErb - 1 client id (client app calling itself) does not currently work. Consider updating your setup to use 2 client ids. 

I do not have an ETA for the service work, but I will keep this issue open until the private one is fixed.

**Comment by SameerK-MSFT** [comment]
This has been fixed by Azure AD. Verified with the previous app. Cannot repro.
