### ISSUE TITLE
[Feature Request] Devicecode flow does not return a full URI

### ISSUE THREAD

**Issue by camptatopenmars** [AzureAD/microsoft-authentication-library-for-dotnet#3231]
The OAuth spec for device code flow includes a provision for a full URI to be returned.  The purpose of this URI is to enable the device to do things like display a QR code such that the user just needs to authenticate and authorize the device - avoiding the need to also type in the user code as well.  This can in many situations enable mobile device scenarios without any additional steps other than authorizing the device.  Our product team would very much like to enable this, but at the moment we are not able to see a way to achieve this with MSAL without resorting to hacks.

**Comment by bgavrilMS** [comment]
Pls request this to the service. It is not an SDK problem.
