### ISSUE TITLE
[Bug] : Microsoft Graph endpoint doesn't work with MailKit (While Outlook Endpoint works)

### ISSUE THREAD

**Issue by Just1n** [AzureAD/microsoft-authentication-library-for-dotnet#3234]
**Logs and network traces**
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54] MSAL MSAL.Desktop with assembly version '4.42.1.0'. CorrelationId(8058cc59-66db-443a-9673-5c14979a2b54)
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent:
Prompt: not_specified
HasCustomWebUi: False

MSAL Info True True MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54]
=== Request Data ===
Authority Provided? - True
Client Id - 73e31e62-5fee-4eb5-8a07-d726ab53a62f
Scopes - email offline_access IMAP.AccessAsUser.All
Redirect Uri - https://login.microsoftonline.com/common/oauth2/nativeclient
Extra Query Params Keys (space separated) -
ClaimsAndClientCapabilities -
Authority - https://login.microsoftonline.com/common/
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint -
IsBrokerConfigured - False
HomeAccountId -
CorrelationId - 8058cc59-66db-443a-9673-5c14979a2b54
UserAssertion set: False
LongRunningOboCacheKey set: False

MSAL Info True True MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54] === Token Acquisition (InteractiveRequest) started:
        Authority: https://login.microsoftonline.com/common/
        Scope: email offline_access IMAP.AccessAsUser.All
        ClientId: 73e31e62-5fee-4eb5-8a07-d726ab53a62f

MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54] [Region discovery] Not using a regional authority.
MSAL Info True True MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54] Fetching instance discovery from the network from host login.microsoftonline.com. Endpoint https://login.microsoftonline.com/common/discovery/instance.
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54] Authority validation enabled? True.
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54] Authority validation - is known env? True.
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:19Z - 8058cc59-66db-443a-9673-5c14979a2b54] Using legacy embedded browser.
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] [Legacy WebView] Redirect URI was reached. Stopping WebView navigation...
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] An authorization code was retrieved from the /authorize endpoint.
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Exchanging the auth code for tokens.
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent:
Prompt: not_specified
HasCustomWebUi: False

MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Checking client info returned from the server..
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Saving token response to cache..
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] [Region discovery] Not using a regional authority.
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Saving AT in cache and removing overlapping ATs...
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Looking for scopes for the authority in the cache which intersect with email offline_access IMAP.AccessAsUser.All
MSAL Always False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z] [GetAllAccessTokens] Total number of cache partitions found while getting access tokens: 0
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Intersecting scope entries count - 0
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Matching entries after filtering by user - 0
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Saving Id Token and Account in cache ...
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Saving RT in cache...
MSAL Info False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54]
        === Token Acquisition finished successfully:
MSAL Info True True MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54]  AT expiration time: 2022/3/17 15:13:50 +00:00, scopes: IMAP.AccessAsUser.All openid POP.AccessAsUser.All profile SMTP.Send User.Read email. source: IdentityProvider
MSAL Info True True MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] Fetched access token from host login.microsoftonline.com. Endpoint: https://login.microsoftonline.com/common/.
MSAL Always False False MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54]
[LogMetricsFromAuthResult] Cache Refresh Reason: NotApplicable
[LogMetricsFromAuthResult] DurationInCacheInMs: 0
[LogMetricsFromAuthResult] DurationTotalInMs: 9915
[LogMetricsFromAuthResult] DurationInHttpInMs: 1015

MSAL Always True True MSAL 4.42.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-03-17 13:44:28Z - 8058cc59-66db-443a-9673-5c14979a2b54] [LogMetricsFromAuthResult] TokenEndpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token

Unhandled Exception: MailKit.Security.AuthenticationException: Authentication failed.
   at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__101.MoveNext() in D:\src\MailKit\MailKit\Net\Imap\ImapClient.cs:line 1064

**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.42.1

**Platform**
.NET 4.8

**What authentication flow has the issue?**
* Desktop / Mobile
    * Interactive

**Other?**
1. According to the [comparision](https://docs.microsoft.com/en-us/outlook/rest/compare-graph) of Microsoft Graph and Outlook REST API endpoints, the Outlook REST endpoints will be fully decommissioned in Nov. 2022.
2. This MailKit's [official example](https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md) of using Microsoft.Identity.Client seems using scopes with prefix 'https://outlook.office.com/api' which I think it shoule be Outlook REST API endpoints.
3. The sample works fine, But if I remove the prefix of the scopes, I would get  `Authentication failed` error.
4. There're also some threads talking about this: [Link1](https://github.com/jstedfast/MailKit/issues/1126), [Link2](https://answers.microsoft.com/en-us/msoffice/forum/all/graph-url-scopes-not-supported-for-smtp-and-imap/4bb49947-f9af-4044-949b-0ab35b285069?auth=1)

**Is this a new or existing app?**

**Repro**

```csharp
                      var publicClientApplication = PublicClientApplicationBuilder.Create("73e31e62-5fee-4eb5-8a07-d726ab53a62f")
				.WithLogging(MyLoggingMethod, LogLevel.Info, enablePiiLogging: true, enableDefaultPlatformLogging: false)
				.WithAuthority("https://login.microsoftonline.com/common") // SuppressCodeSmell Reason = No need translation
				.WithDefaultRedirectUri().Build();

			var scopes = new[] {
				"email",
				"offline_access",
				//"https://outlook.office.com/IMAP.AccessAsUser.All",
				"IMAP.AccessAsUser.All",
			};

			var authToken = publicClientApplication.AcquireTokenInteractive(scopes).ExecuteAsync().Result;

			var oauth2 = new SaslMechanismOAuth2(authToken.Account.Username, authToken.AccessToken);

			using (var client = new ImapClient())
			{
				client.Connect("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
				client.Authenticate(oauth2);
				Console.WriteLine("Authenticated");
				client.Disconnect(true);
			}
```

**Expected behavior**
No Errors

**Actual behavior**
`Authentication failed` exception

**Possible solution**

**Additional context / logs / screenshots / links to code**
https://answers.microsoft.com/en-us/msoffice/forum/all/graph-url-scopes-not-supported-for-smtp-and-imap/4bb49947-f9af-4044-949b-0ab35b285069?auth=1
https://github.com/jstedfast/MailKit/issues/1126
https://stackoverflow.com/questions/43473858/connect-to-outlook-office-365-imap-using-oauth2/60773366#60773366

**Comment by Just1n** [comment]
What is the difference between scopes `https://outlook.office.com/IMAP.AccessAsUser.All` and `IMAP.AccessAsUser.All`?

**Comment by SameerK-MSFT** [comment]
That is how the scope is defined by the backend. The app will have to request scope with the same exact string. Hope this helps.

**Comment by Just1n** [comment]
So why it works by using `https://outlook.office.com/IMAP.AccessAsUser.All` but doesn't work with `IMAP.AccessAsUser.All` ?
