### ISSUE TITLE
[Feature Request] MsalRuntime + C# interop package

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3240]
# Goal

1. MsalRuntime release build should create a package
2. MsalRuntime release definition should upload package to nuget

## Status Quo

Currently we have a prototype project which can be build to produce a nuget package. Instructions here: https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/2758/files#diff-a0ec2664f83946ee18864d33661b05bf89154963766e37181f0f35cd522de701

## Next steps - P1

- [x] Build Interop Layer using cmake under the current C++ build pipeline
- [x] Pack the NuGet using Axure DevOPS build steps (using a .nuspec file)
- [x] Add package metadata like copyright etc. (may need to sync with Medhir on this) 
- [x] Pull the versioning information into the NuGet package. The version of msalruntime is defined in a file version.txt 
- [x] Add the .snk file to the interop proj during cmake build
- [x] Add package validation under Azure DevOPS build
- [x] Output Microsoft.Identity.Client.NativeInterop.dll and Microsoft.Identity.Client.NativeInterop.nupkg must be signed. 
- [x] Upload package to ADO package feed (just like MSAL) and be ready to upload to nuget.org (we should not do it yet, before we finalize naming and versioning strategy) 

## Next steps - P2

- [x] #3335
- [x] Revisit the local build strategy and see if it can be improved after figuring out all the rest.

**Comment by localden** [comment]
The runtime now ships as its own package.
