### ISSUE TITLE
Consistency track: please provide consistent APIs to disable authority validation and instance discovery

### ISSUE THREAD

**Issue by xiangyan99** [AzureAD/microsoft-authentication-library-for-dotnet#3242]
Now we have different API/behaviors for customers to disable authority validation and instance discovery.

Please sync across languages to provide consistent ones.

This is important because JEDI scenarios are blocked by current behavior.

**Comment by bgavrilMS** [comment]
We do provide a mechanism called WithInstanceDiscoveryMetadata, allowing apps to bypass instance discovery and provide a JSON formatted url with the authorities. But this is not consistent between MSALs.

**Comment by logangeorge01** [comment]
I believe this issue can be closed with new method [WithInstanceDiscovery(Boolean) ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractapplicationbuilder-1.withinstancediscovery?view=msal-dotnet-latest#microsoft-identity-client-abstractapplicationbuilder-1-withinstancediscovery(system-boolean))
