### ISSUE TITLE
[Bug] MacOS Desktop App: In interactive Authentication Window, it is no longer possible to paste username or password

### ISSUE THREAD

**Issue by oholthau** [AzureAD/microsoft-authentication-library-for-dotnet#3244]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.41.0

**Platform**
Xamarin.Mac Modern, Version 8.6.0.3 from 2022-01-16

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.

**Repro**

Try interactively to login to Azure AD.
You are not able to paste, neither via right-click nor via Command-V

**Expected behavior**
Paste is possible

**Actual behavior**
If you press Command-V, nothing is pasted
If you right-lick, the context menu dios not contain "Paste"

See Microsoft TrackingID#2202250050001244

**Comment by bgavrilMS** [comment]
We are looking at adding MacCatalyst support, which will reuse the iOS infrastructure. This should fix it.
