### ISSUE TITLE
[Feature Request] Add new logger interface that is in alignment with SAL/Wilson/MISE

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3245]
**Is your feature request related to a problem? Please describe.**
We need to add a new interface that customers will be able to use with MSAL.NET where the customer will be able to reuse the same logger implementation with SAL/Wilson/MISE without having to reimplement anything. 

**Describe the solution you'd like**
Add a new api where MSAL will accept an implementation of a logger interface (IIdentityLogger) that MSAL will use for all of its logging operations.

Expose this logger implementation to the external cache api (TokenCacheNotificationArgs) so that the customer can log messages during caching operations if needed.

**Additional context**
The current logging api:

    public T WithLogging(
                LogCallback loggingCallback,
                LogLevel? logLevel = null,
                bool? enablePiiLogging = null,
                bool? enableDefaultPlatformLogging = null)
        
will be made obsolete by the new logging interface api. An adapter can be added in MSAL to adapt this api to use the new logger implementation to maintain backwards compatibility so that we don't break current customer functionality.

Should Msal.net extensions should probably be updated to use the same logging strategy?

**Comment by bgavrilMS** [comment]
Fixed in MSAL 4.44
