### ISSUE TITLE
[Bug] Exception during RemoveAsync - Invalid JSON String

### ISSUE THREAD

**Issue by riyabans** [AzureAD/microsoft-authentication-library-for-dotnet#3248]
**Logs and network traces**
https://microsoftapc-my.sharepoint.com/:x:/g/personal/riyabansal_microsoft_com/EaWZbnfBc4xNpq_VwrAkeIsBXId-gq4s5QvJY4L7Lwg_QQ?e=4TgX9I

**Which version of MSAL.NET are you using?**
MSAL.NET 4.42.0.0 

**Platform**
.NET 4.7, WPF

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)

Other?
We are getting this exception when we try to remove the user account using the MSAL function:PublicClientApp.RemoveAsync(Account). 

We have added a null check for the account. 

"ErrorMessage": "Invalid JSON string. (Exception from HRESULT: 0x83750007)",
"ErrorLocation": " at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker.<RemoveAccountAsync>d__32.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Identity.Client.ClientApplicationBase.<RemoveAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Identity.Client.ClientApplicationBase.<RemoveAsync>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at MicrosoftWhiteboard.Auth.MsalClient.<Logout>d__11.MoveNext()"

**Is this a new or existing app?**

The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**
Not able to repro at our end. One of the customers reported it to us.

**Expected behavior**
No Exception should occur. Customer should be able to logout

**Actual behavior**
Customer is not able to logout due to this exception.

**Comment by bgavrilMS** [comment]
I think this happens because `RemoveAccount` has a bug where it does not correctly infer if the account belongs to AAD or to MSA.

**Comment by riyabans** [comment]
Thanks @bgavrilMS for closing this issue. Can you share some visibility on when would be able to update our MSAL libraries to 4.43.0 version?

Thanks,
Riya Bansal

**Comment by bgavrilMS** [comment]
Hi @riyabans - we aim to ship MSAL 4.43 this week, should be out there by Wednesday (but hopefully by end of day Monday)

**Comment by NakulSabharwal** [comment]
@bgavrilMS After updating to v43, we are still seeing this issue.

**Comment by NakulSabharwal** [comment]
@bgavrilMS Is there any workaround for this bug to logout successfully that we can use until this issue is fixed ?

**Comment by bgavrilMS** [comment]
Should work now with MSAL 4.44 with new broker implementation - see https://aka.ms/msal-net-wam

**Comment by bgavrilMS** [comment]
It looks like the error is coming from WAM and Nakul will follow up with WAM via ICM. 
The error is not critical.

**Comment by bgavrilMS** [comment]
Can't repro. Suggestion is to try with new WAM implementation - https://aka.ms/msal-net-wam
