### ISSUE TITLE
[Bug] IsSystemWebViewAvailable doesn't work correctly in WSL2

### ISSUE THREAD

**Issue by wayneyaoo** [AzureAD/microsoft-authentication-library-for-dotnet#3251]
**Logs and network traces**
Not applicable

**Which version of MSAL.NET are you using?**
MSAL.NET 4.39.0

**Platform**
.NET 6, WSL2 Debian

**What authentication flow has the issue?**
Not applicable. The auth flow works correctly but they cannot be invoked correctly.

* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

The app is in production, I haven't upgraded MSAL, but started seeing this issue.
The flow works correctly before but somehow doesn't work anymore but I'm not sure when.

**Repro**

```csharp
            try
            {
                // The IsSystemWebViewAvailable doesn't seem to work correctly on WSL
                if (!azureApp.IsSystemWebViewAvailable()) // azureApp is a PublicClientApplicationBuilder.Build() object.
                {
                    // Device code flow to get openid only, if client has no web view.
                    result = azureApp.AcquireTokenWithDeviceCode(
                            new[] { "openid" },
                            codeResult =>
                            {
                                console.Output.WriteLine(codeResult.Message);
                                return Task.CompletedTask;
                            })
                        .ExecuteAsync(cancellationToken).GetAwaiter().GetResult();
                }
                else
                {
                    // Common authorization code flow within browser.
                    result = azureApp
                        .AcquireTokenInteractive(new[] { "openid" })
                        .WithPrompt(Prompt.SelectAccount)
                        .ExecuteAsync(cancellationToken).GetAwaiter().GetResult();
                }
            }
            catch (MsalException ex)
            {
                throw new CommandException($"Unable to authenticate to Azure AD: {ex.Message}");
            }

```

**Expected behavior**

The expected behavior is that if a user is in an environment where UI/web browser is available, it should go to interactive login page otherwise device code login should be use.

**Actual behavior**

The actual behavior is that the `IsSystemWebViewAvailable` always returns true and it tries to open a browser in WSL shell which never succeeded. I attempted `IsUserInteractive` and that doesn't work either.

One thing to notice is that it works on a real Linux server without UI (it did jump to device code flow).

**Possible solution**
No idea how this works under the hood. I can imagine platform-dependent code.

**Comment by bgavrilMS** [comment]
The root cause is most likely `IsUserInteractive` - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreWebUIFactory.cs

**Comment by bgavrilMS** [comment]
And `IsUserInteractive` is implemented here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/DesktopOsHelper.cs#L204

**Comment by bgavrilMS** [comment]
I think the WSL folks have made some changes, including adding support for UI components. For example on my recently installed WSL2 Ubuntu, I can actually execute `xdg-open https://www.google.com` (after installing the xdg tools)

**Comment by bgavrilMS** [comment]
Question is - what error do you get here? How is `AcquireTokenInteractive` failing?

**Comment by wayneyaoo** [comment]
@bgavrilMS Ha thanks for the investigation! That explains why `IsUserInteractive` doesn't work. I do see a env variable `DISPLAY` is set on my WSL2 Debian to ":0" so MSAL probably thinks a UI is available. Does `IsSystemWebViewAvailable` use similar mechanism under the hood to make decision? 

I don't have `xdg-open` stuff installed so acquire token interactively gives this expected error:

`
Unable to open a web page using xdg-open, gnome-open, or kfmclient tools. See inner exception for details. Possible causes for this error are: tools are not installed or they cannot open a URL. Make sure you can open a web page by invoking from a terminal: xdg-open https://www.bing.com
`

The problem here is `IsSystemWebViewAvailable `/`IsUserInteractive` made the wrong decision leading to this error. I agree that WSL2 folks could make changes as it worked before but not now.

**Comment by bgavrilMS** [comment]
Hi @wayneyaoo - do you have `wslview` installed? Can you try to type `wslview https://example.com` ?

As far as I know, WSL team have actually done a lot of work to make this type of scenario possible, i.e. your headless Linux will open a browser window on Windows. Git Credential Manager, which behaves very similarly to MSAL, have tested this.

**Comment by wayneyaoo** [comment]
Hi @bgavrilMS, thanks for the information. Glad to see that the integration of the WSL and host Windows is getting stronger and more natural!

I dont have any desktop-related component installed since I treat it as a minimal Linux. I don't object it if WSL2 comes with some view component like `wslview` by default in the future or I need to install those component to make it work here. I probably should ask this somewhere else but my question is, should I treat WSL2 now as "an environment with GUI"? If yes, then MSAL is working correctly. It's just my machine that lacks something that should've been there by default and I'll happily install whatever necessary to resolve the issue and believe anyone running my code on WSL would do the same. If no, then probably MSAL is not working correctly I guess, as the `IsSystemViewAvailble`/`IsUserInteractive` should return false in WSL2.

Which case do you think MSAL should currently assume?
