### ISSUE TITLE
[Feature Request] Public cloud regionalization - use <region>.login.microsoft.com

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3252]
Once the feature below is complete (end of April), we should switch to use `<region>.login.microsoft.com`

[Feature 759642: DNS:: Active / Active - Microsoft.com Resiliency - Boards (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fidentitydivision.visualstudio.com%2FEngineering%2F_workitems%2Fedit%2F759642&data=04%7C01%7CBogdan.Gavril%40microsoft.com%7Ce29fa06deccf4d01bf7608da0ced8346%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637836511523321689%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UbKwTNUxEX7e5WAM5YqmOWQDFlvguXnmdU3J7IM5s5k%3D&reserved=0)

**Comment by neha-bhargava** [comment]
The timelime was updated to 5/31, and then 6/17

**Comment by pmaytak** [comment]
Update: moved to 8/15.

**Comment by neha-bhargava** [comment]
Update: moved to 9/29

**Comment by tomkerkhove** [comment]
We have recently upgraded from 4.48.1 to 4.91.1 and this feature broke our service given customers with custom VNETs have to allow the new formats. Is there a way where we can configure to use the old `<region>.r.login.microsoftonline.com` notation?

**Comment by tomkerkhove** [comment]
One idea would be to introduce this overload: `builder.WithAzureRegion(region, regionalHostSuffix: "r.login.microsoftonline.com")`
