### ISSUE TITLE
[Feature Request] On Windows, IntegratedWindowsAuth should fallback to Broker.Silent(CurrentUser)

### ISSUE THREAD

**Issue by johnterickson** [AzureAD/microsoft-authentication-library-for-dotnet#3257]
**Is your feature request related to a problem? Please describe.**
There are many tools in the ecosystem that authenticate using IntegratedWindowsAuth.  As companies move towards Zero Trust and thus turn off VPN, this stops working.  Either we have to ask all tools to write some fallback between IWA and silent broker auth (I'm not sure which order is ideal), or we can fix it centrally in MSAL and then just have the tools upgrade the version they are using.

**Describe the solution you'd like**
If IWA fails (e.g. because VPN is not connected), then MSAL will automatically fallback to attempting a silent auth via broker. 

**Describe alternatives you've considered**
A way to phrase my ask more generically would be "give me one API that attempts to silently authenticate as the current user".  Right now each tool needs to conditionally compile for different OS and try multiple fallback options. E.g. https://github.com/johnterickson/msalsample

**Additional context**
@bgavrilMS and I chatted about some of this in Teams.

**Comment by johnterickson** [comment]
> "give me one API that attempts to silently authenticate as the current user"

@kyle-rader Perhaps this is the abstraction level you are already looking at implementing?

**Comment by kyle-rader** [comment]
That is effectively the design goal of https://github.com/AzureAD/microsoft-authentication-cli - in CLI format. We do want to upstream the higher level abstraction into MSAL directly though. For all the reasons you called out above.

**Comment by bgavrilMS** [comment]
At MSAL level, this is not feasiable, because the redirect URIs are not compatible.
