### ISSUE TITLE
[Bug]  IConfidentialClientApplication.RemoveAsync doesn't remove redis key for long session token.

### ISSUE THREAD

**Issue by zhonghua-wu** [AzureAD/microsoft-authentication-library-for-dotnet#3259]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**

4.42.0
**Platform**

.net core

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [X] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

This app is in production, I am adding new feature to it.

**Repro**
1. iniialize redis token cache 
2. call AcquireTokenInLongRunningProcess api , token is created in redis
3. call IConfidentialClientApplication.RemoveAsync to remove this user
4. call  IConfidentialClientApplication.GetAccountsAsync, the account is deleted
5. the token is redis is not deleted.
```csharp
var externalResourceToken = await longRunningWebApi.InitiateLongRunningProcessInWebApi(scopes, token, ref sessionKey)
                        .WithAuthority(authority)
                        .WithSendX5C(true)
                        .ExecuteAsync()
                        .ConfigureAwait(false);
await this.confidentialClientApplication.RemoveAsync(externalResourceToken.Account);
```
all code run successfully.
after this call, the redis key still exist.

**Expected behavior**
the redis key should be removed.
**Actual behavior**
the redis kye still exist.
**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by bgavrilMS** [comment]
Yes, this is a known limitation - we made OBO session based, not user based, to eliminate misuse of the security model, i.e. if you consider OBO user-based, it's very easy to misuse it and expose security flaws. So in OBO, caching happens by `hash(incomming_assertion)`. `GetAccounts()` is not allowed in a Confidential Client app, it is not defined. `RemoveAccount` does  not have enough information to find all OBO cache nodes associated with the account. 


The workaround - if you are concerned about cache size, we recommend that you evict old entries, e.g. entries that we not accessed in the past X days. 

CC @maliksahil - I think we should re-discuss OBO, as the current solution has some limitations.

**Comment by jmprieur** [comment]
@bgavrilMS @maliksahil please involve me and @jennyf19 as well
