### ISSUE TITLE
Embedded WebView - add options to hide zoom control (Android) hide cancel top left corner (iOS)

### ISSUE THREAD

**Issue by t3slaughter** [AzureAD/microsoft-authentication-library-for-dotnet#3260]
I am currently using Xamarin Forms. It works good but there are some options I would like to have to give user a better experience. For Android the zoom control gets in the way on signupsignin. This should either be hide by default or give developer an option to hide it. Also for iOS there is an additional navigation cancel link in top left corner. There is already a cancel and this one from iOS should be either hidden by default or another option to hide.

In https://github.com/AzureAD/microsoft-authentication-library-for-android 02/12/2020 they added option to configure zoom controls. Can we get this option?

**Comment by localden** [comment]
Closing this issue as we [no longer support Xamarin](https://devblogs.microsoft.com/identity/uwp-xamarin-msal-net-deprecation/).
