### ISSUE TITLE
[Bug] Integrated Windows Auth with Conditional Access

### ISSUE THREAD

**Issue by jasase** [AzureAD/microsoft-authentication-library-for-dotnet#3264]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.42.1

**Platform**
.Net 6.0 

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
The app is in production, Conditional Access was activated for some users.

**Repro**

```csharp
 public class Program
 {
     private const string CLIENT_ID = "xxx";
     private const string AUTHORITY_ID = "https://login.microsoftonline.com/xxx/v2.0";
     private const string API_ID = "api://xxx/api";

     public static void Main(string[] args)
     {
         var apiScope = new string[] { API_ID };
         var userScope = new string[] { "User.read " };

         var clientApp = PublicClientApplicationBuilder.Create(CLIENT_ID)
                                                       .WithAuthority(AUTHORITY_ID)
                                                       .Build();

         var result = clientApp.AcquireTokenByIntegratedWindowsAuth(userScope)
             .ExecuteAsync()
             .Result;

         var token = result.AccessToken;

         Console.WriteLine(token);
         Console.Read();
     }
 }
```

**Expected behavior**
The code should get an access token to access the Api and print it

**Actual behavior**
AcquireTokenByIntegratedWindowsAuth generate an exception:

AADSTS53001: Device is not in required device state: domain_joined. Conditional Access policy requires a domain joined device, and the device is not domain joined.
Trace ID: 0cc22c11-a2c2-44db-bdae-00b80b8b6400
Correlation ID: 37c4997f-0a0c-4a8b-beb4-ae1071407e6f
Timestamp: 2022-04-05 04:28:08Z

**Additional context / logs / screenshots / links to code**
Application is executed on a domain joined Windows 10 Client and `clientApp.AcquireTokenByIntegratedWindowsAuth(userScope)` works until Conditional Access Policy was activated. 
Normally we use a custom scope but also common scopes like `User.read` are not working

**Comment by bgavrilMS** [comment]
What happens if you use `AcquireTokenInteractive` instead? You might need to add `http://localhost` as a redirect URI to try this out, or try it from a .NET classic app, as it has an embedded browser built in. Are you sure that you are really domain joined?

I was under the impression that Integrated Windows Auth (IWA) would satisfy this CA policy, but maybe it does not do it in all cases. In any case, I recommend you move off IWA and use WAM instead - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication#use-wam-instead as it provides a better experience and is more secure.

**Comment by jasase** [comment]
We switch our Authentication request to WAM. Now the Conditional Access policy for domain_joined device seems to be fulfilled, but now the application has some problems with our custom scope. We call `clientApp.AcquireTokenInteractive(new string[] {  "api://xxx/smp.api"})` only with our custom scope. This lead to the following error:

```
 Error Code: WAM_aad_provider_error_3399614466 
 Error Message:  
 WAM Error Message: AADSTS90008: The user or administrator has not consented to use the application with ID 'xxx'(xxx). This happened because application is misconfigured: it must require access to Microsoft Graph by specifying at least 'Sign in and read user profile' permission.
Trace ID: dead07e7-46ee-489c-afb0-765949708600
Correlation ID: 717db566-f9ec-4095-b7a1-fcb07e77ef93
Timestamp: 2022-04-07 08:37:10Z 
 Internal Error Code: 3399614466 
 Is Retryable: False 
 Possible causes: 
 - Invalid redirect uri - ensure you have configured the following url in the AAD portal App Registration: ms-appx-web://microsoft.aad.brokerplugin/5346a47b-a3b6-4484-852c-ceea56ba3614 
- No Internet connection 
Please see https://aka.ms/msal-net-wam for details about Windows Broker integration)'
```

If we call with scope `user.read` everything except the call to our custom API is working

**Comment by jasase** [comment]
Also requesting two scopes like described here does not work:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-user-gets-consent-for-multiple-resources

**Comment by bgavrilMS** [comment]
Yes, these are both known issues for WAM

1. Requesting a web api scope from the same client id: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3230

Possible workaround: use the GUID format of the scope and use separate client IDs for the public client and the web api.

2. WithExtraScopesToConsentTo does not currently work with WAM.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3120

**Comment by bgavrilMS** [comment]
We do not have a silent solution for your scenario @jasase at this point. You'll have to rely on `AcquireTokenInteractive` to pop up the browser, which will certify the "device is managed" CA policy.

**Comment by bgavrilMS** [comment]
I am going to close this as you can follow the other issues for WAM or use Interactive to get unblocked.
