### ISSUE TITLE
[Feature Request] no instance discovery metadata for PPE endpoint.

### ISSUE THREAD

**Issue by Qi-Zhang-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3265]
**Is your feature request related to a problem? Please describe.**
There is no instance discovery metadata for PPE endpoint.

**Describe the solution you'd like**
There is no instance discovery metadata for login.windows-ppe.net, which is the PPE endpoint.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Instance/Discovery/KnownMetadataProvider.cs#L40

Also, I see that when we set the authority to login.windows-ppe.net, the instance discovery called made by MSAL looks like:

https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https:%2F%2Flogin.windows-ppe.net%2F0d035206-f7e3-4ad9-b326-1cd88c6c24d6%2Foauth2%2Fv2.0%2Fauthorize

which is weird given login.microsoftonline.com is the prod endpoint, and the response does not contain login.windows-ppe.net.

**Describe alternatives you've considered**

**Additional context**

**Comment by bgavrilMS** [comment]
ESTS-R team are getting a lot of support cases because of this.

**Comment by SlyryD** [comment]
I can't sign in with an MSA PPE account. Should https://login.live-int.com/oauth20_authorize.srf be added as well?

**Comment by bgavrilMS** [comment]
Can you login with an MSA PPE account by using AAD's PPE authority ? https://login.windows-ppe.net/common ?

**Comment by SlyryD** [comment]
It might be a WAM integration issue, but it doesn't seem like it. This is an MSA PPE account I can use to sign into word.officeppe.com.
![image](https://user-images.githubusercontent.com/4186968/191084444-dc90ad71-5368-4574-a8cf-2b8cc3920cc2.png)

**Comment by bgavrilMS** [comment]
@SlyryD - can you please send an email to me (bogavril) and I will forward it to some people who can help.
