### ISSUE TITLE
Add MiseCache to MSAL in Mise.

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3271]
**Problem statement**
Token acquisition component in Mise which uses Msal by default has an in-memory cache without eviction, size limits.
**Goal**
By default, if not specified by users, use MiseCache as serialization cache in Msal.

**Comment by pmaytak** [comment]
After investigation Msal cannot use MiseCache since it's operations require MiseContext which is not available in Msal. Prototype has been done using an in-memory cache similar to the one in Identity Web. Work is pending waiting for a better caching solution.
