### ISSUE TITLE
[Feature Request] Add more information to error logs

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#3278]
**Problem statement**
Currently users use either Error or Warning log level. When exception happens and is logged, the information can be a bit generic and not enough to debug (ex. some HTTP timeout exception happened). Sometimes the error is difficult to repro or the users can't change log level to Verbose, for some reason.

**Possible solution**
Make sure when we log errors (and perhaps warnings), we don't just log the exception but also any related request information that can help in debugging. Look at what we log in Info logs and maybe move that information to Error logs. Also verify all the important places in MSAL where we log errors (ex. where we send token requests) and see if more information is needed to be added there.

**Comment by bgavrilMS** [comment]
I think we should do this for any HTTP errors, AAD errors and unexpected errors from MSAL. `log.Error` and `log.Warning` are used to also give user information about suboptimal config (e.g. using "https://lmo/common" is S2S flow will trigger a log error).

**Comment by bgavrilMS** [comment]
@neha-bhargava  - you can also pick this one.

**Comment by neha-bhargava** [comment]
> I think we should do this for any HTTP errors, AAD errors and unexpected errors from MSAL. `log.Error` and `log.Warning` are used to also give user information about suboptimal config (e.g. using "https://lmo/common" is S2S flow will trigger a log error).

Do you mean to log information related to which endpoint is used in case of HTTP errors? Or the flow used for AAD errors?

**Comment by bgavrilMS** [comment]
@neha-bhargava - please reach to @pmaytak who can explain the context of this request in more detail. The point is that if some error occurs, we should dump at least the full details of the request to the Error log. We now only log at INFO level the details about each request (see the logic in RequestBase).

**Comment by pmaytak** [comment]
Updated work item description.
