### ISSUE TITLE
[Feature Request] Support PoP over AcquireTokenByUsernamePassword

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-authentication-library-for-dotnet#3287]
**Is your feature request related to a problem? Please describe.**
Previously, PoP was supported for over PCA AcquireTokenByUsernamePassword. We were relying on this method for integration testing of our server API code over C#. We would like to continue doing this.

**Describe the solution you'd like**
Expose ability to mint PoP with PCA.AcquireTokenByUsernamePassword

**Additional context**
This ability was previously supported in MSAL.

**Comment by bgavrilMS** [comment]
This is an important scenarios for testing. If RPOC + POP is configued, we could just throw away the RT. 

CC: @trwalke

**Comment by rymeskar** [comment]
@jmprieur / @bgavrilMS any update on this feature?

**Comment by bgavrilMS** [comment]
Yes @rymeskar, we will enable this in the 4.46 release. It will only work on Windows (Win 10+) when using the broker. Is this ok?

**Comment by rymeskar** [comment]
Win10+ would still work on .NET fx and .NET (Core) runtimes, right?

Is there any reason for not including Linux server?

**Comment by bgavrilMS** [comment]
@rymeskar - on Windows, with the broker, the RT is also bound. That's the safest way to do POP - both AT and RT being bound. Only the broker can handle RT biding. 

We may enable the flow everywhere even without the RT properties, haven't decided on that yet.
