### ISSUE TITLE
[Bug] MSAL granting me consent to scope that isn't defined in the app registration

### ISSUE THREAD

**Issue by Camios** [AzureAD/microsoft-authentication-library-for-dotnet#3296]
**Logs and network traces**
[20220429 MSAL logs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/8587748/20220429.MSAL.logs.txt)

**Which version of MSAL.NET are you using?**
MSAL.NET 4.43.1

**Platform**
.NET 6

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
This is a new app/experiment based on https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad and https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2.

**Repro**
I have three Azure App Registrations for testing purposes.
1. One which has the standard "user.read" scope for Microsoft Graph used in MS examples. Client id: 591{snip}
2. Second one which represents a backend API and exposes a custom API scope "api://d8d{snip}/Con{snip}.Read". Client id: d8d{snip}
3. Lastly one to represent the frontend desktop client application which has an API permissions consisting of the "user.read" scope for Microsoft Graph as well as the backend API scope "api://d8d{snip}/Con{snip}.Read. Client id: 23b{snip}

I have a desktop app - I modified https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2 to:
1. use .NET6, 
2. force Azure Ad, 
3. don't use token cache (although i did previously test with it enabled at some point)
4. let me pick from a list of client ids and authorities (eg a tenant id vs "organizations") and
5. calls my protected API rather than the Microsoft Graph API.
6. Lastly, added logging for lodging this issue.

I wanted to do a negative test where I use the first client app registration (Client id starting with 591) which only has the Microsoft Graph permission 
![image](https://user-images.githubusercontent.com/2810835/165878491-83649e99-ed1a-4323-a0ff-b5f80f60e6e7.png)
but request the backend API scope and I expected an error but instead MSAL/AzureAD granted me an access token with the requested backend API scope! 
[20220429 JWT claims.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/8587753/20220429.JWT.claims.txt)
I'm still fairly inexperienced with this, but isn't it a fundamental thing? What have I missed?

Solution (missing PII):
[WpfMsalAuthExpiryDotNet6.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/8587896/WpfMsalAuthExpiryDotNet6.zip)

**Expected behavior**
When requesting a token for a scope that isn't permitted on the associated client app registration, a token shouldn't be generated granting permission for that scope. Instead an error should occur.

**Actual behavior**
A token is returned with scope granted for an API that the app has no permission to use.

**Possible solution**
.

**Additional context / logs / screenshots / links to code**
.

**Comment by jmprieur** [comment]
@Camios
- Is your web API behind APIM? (you referenced an APIM doc?)
- Did you (the user) consent for the web API? Wouldn't you have added the web API initially to your app registration, tried and consented, and then removed the web API from your app registration?
- If you think that can have been the case (I think so), please delete the service principal associated with your first application, to reset the consents, and retry.

PS: MSAL does not grant consent. It starts a private repo 

cc: @psignoret in case you have an idea.

**Comment by Camios** [comment]
@jmprieur 

* The app registration for the backend API is an APIM API policy that returns a static response (it doesn’t actually make a backend call). But does it actually matter because the problem occurs with the access token before I make a call to the protected API. 
* The first App Registration was created by someone else many months ago. I created the second and third App Registrations just this week and to my knowledge, no one has modified the first App registration to grant the backend API permissions.   Is there a way to verify or reset on the client side? One odd thing is when using interactive acquisition the browser window says the first app registration says it is asking for permission to the backend API - is that browser showing the info from the client App registration or the requested scope or mixture?

**Comment by bgavrilMS** [comment]
So, you're using a desktop application to fetch a token for your web api. You seem to request scope `api://d8d{snip}/Con{snip}.Read` and you get a token for that scope. 

Please read more about consent here: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#incremental-and-dynamic-user-consent

By default, users are allowed to consent by themselves to most scopes. Some "admin" scopes are blocked, because they are too "powerful", e.g. scopes that would allow a user to access other user's data. 

You can control this behavior as far as I know - see https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-user-consent?tabs=azure-portal

**Comment by Camios** [comment]
So yeah it's an Azure App Registration "feature". API Permissions are the minimum scope - that's counter to all other zero trust permission settings. It wasn't clear to me that "incremental and dynamic user consent" which allows any app to elevate its permissions above what was defined in API Permissions for any scope that was allows User consent. Still doesn't make a lot of sense the way that's been designed/implemented/explained. 
I ended up steering clear of API permissions and going with Authorized app instead.

This issue can be closed.
