### ISSUE TITLE
[Bug] WAM broker does not honor LoginHint 

### ISSUE THREAD

**Issue by JPWilli** [AzureAD/microsoft-authentication-library-for-dotnet#3301]
MSAL 4.46

1. Use WAM preview
2. Declare that the app is MSA-PT, i.e. only AAD plugin should handle auth
3. AcquireTokenInteractive using a login_hint

**Actual**: the full account picker pops up every time

![image](https://user-images.githubusercontent.com/12273384/186440761-4601928b-8711-4632-886b-6576d1848ae0.png)

**Expected** - a better interactive login experience, at the very least the Account Picker should not be invoked and instead the AAD plugin's browser should accelerate the authentication, e.g. Note that if account is part of the OS, the AAD plugin seems to be able to give back token silently.

![image](https://user-images.githubusercontent.com/12273384/186441272-0ab6d3b0-7873-4764-a672-42e1916d2f0a.png)

Tracking ADO issue: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2040431

Note: when implementing a fix, please see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3520 as well for internal API details

**Comment by bgavrilMS** [comment]
This is a known issue, and something that should be discussed with WAM team. If you know in advance that the user if AAD or MSA, there may be an enhancement that can be done.

**Comment by JPWilli** [comment]
At least in our use case, we could provide IsMSA or IsAAD metadata with the login hint if needed.

**Comment by bgavrilMS** [comment]
Closing this. For new requests to WAM, please contact them directly.

**Comment by bgavrilMS** [comment]
CC @crmann1 - I updated this bug to track the re-auth issue.

**Comment by bgavrilMS** [comment]
Blocked on functionality from msal runtime.

**Comment by bgavrilMS** [comment]
This has been unblocked.

**Comment by bgavrilMS** [comment]
Copying the design from email:


Even with login_hint specified, MsalRuntime always shows the account picker.
 
Here is the logic that I proposed for fixing this bug:

    if (account id)
    {
        Call GetAccountByIdAsync;
        if (hasAccount)
        {
            Call AcquireToken* API with the account;
            return;
        }
    }
    
    Call AddAdditionalParameter with this key and value to suppress the account control:
    // {key: value} where key = "msal_identity_provider" and value is either "msa" or "aad"
    Call SignIn with the login_hint;
    // Any unexpected conditions (listed below) will result as showing the account control AND ignore the login_hint like what we have currently.
    // 1. the login_hint is missing
    // 2. the value is not msa nor aad
 
Note that this logic only trigger when MSALRuntime cannot disambiguate the identity provider based on the condition below:
•	/common authority with login_hint
•	/organizations or /<tenant id> authority with MSA-PT enabled and with login_hint
 
Once we sign off this design, I will check in this design to the msalruntime spec and start coding.

**Comment by bgavrilMS** [comment]
So I think from MSAL.NET perspective we can have the following logic: 

1. If the app developer knows if the account is MSA or AAD, they can pass in this extra QP on their own (you don't need to do anything here except to test and document) 
AND
2. If the app developer uses `WithAccount` rather than `WithLoginHint` in ATI, then we look at the AccountId.HomeTenantId - if this is `98...dad` (MSA) then we add the "msa" extra QP on our own. Otherwise , we add the "aad" extra QP on our won. 


AFAIK, MSA-PT applications never display the account picker anyway, but it's worth testing.

**Comment by gladjohn** [comment]
moving to in-progress to track the doc updates needed for this. i.e. users can pass the QP
