### ISSUE TITLE
[Feature Request] WAM runtime support for AcquireTokenByUsernamePassword

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3308]
This is tracking work item for SigninSilently() with additional parameters `MSALRuntime_Username` and `MSALRuntime_Password

More info on the API Review doc linked [here](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/%5BXplat%5D%20MSALRuntime/Windows%20MSALRuntime/IntegrationWithMsalRuntime.md&version=GBdev&line=136&lineEnd=136&lineStartColumn=73&lineEndColumn=166&lineStyle=plain&_a=contents)

- [ ] Get it working for Bearer tokens
- [ ] Integration test for Bearer
- [ ] Also enable "WithProofOfPosession" API with this flow.
- [ ] Integration test for POP

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
