### ISSUE TITLE
[Feature Request] Use MSAL for other identity providers

### ISSUE THREAD

**Issue by ameyasubhedar** [AzureAD/microsoft-authentication-library-for-dotnet#3309]
**Is your feature request related to a problem? Please describe.**
MSAL seems to be quite generic in its design and makes its easy for UX and CLI apps to authenticate, but its not clear from documentation that it can be used with other Identity Providers.

**Describe the solution you'd like**
Use MSAL to authenticate and authorize with other identify providers, e.g. OAuth and OIDC complaint IdPs.

If this is possible, please provide the documentation and examples on how to achieve this.

**Comment by bgavrilMS** [comment]
Hi @ameyasubhedar, MSAL does not work with other IDPs except AAD, ADFS and AAD B2C. Tracking issue for support of other IdPs is here: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1538

Closing as duplicate.
