### ISSUE TITLE
[Bug] PCA Builder throws exception with IsBrokerAvailable in iOS

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3320]
**Logs and network traces**
NA

**Which version of MSAL.NET are you using?**
MSAL 4.43.0

**Platform**
iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
No

**Repro**

```csharp
var pcaBuilder = PublicClientApplicationBuilder.Create(clientId);
if (pcaBuilder.IsBrokerAvailable())
{
}
```

**Expected behavior**
IsBrokerAvailable returns result

**Actual behavior**
Throws an exception on iOS

**Possible solution**
Pass optional parent to IsBrokerAvailable.

**Additional context / logs / screenshots / links to code**
None

**Comment by pmaytak** [comment]
Related to #3303 (which is more of a long-term fix).

**Comment by bgavrilMS** [comment]
Maybe there should be an ios-specific  and android-specific helper for this?

**Comment by bgavrilMS** [comment]
I recommend deprecation of this method.

**Comment by bgavrilMS** [comment]
Please deprecate this property @SameerK-MSFT , it is not useful.
