### ISSUE TITLE
[Bug] MSAL cache can get confused when WAM has two accounts that match an Identifier

### ISSUE THREAD

**Issue by JPWilli** [AzureAD/microsoft-authentication-library-for-dotnet#3323]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).
Due to PII concerns, I've given @bgavrilMS and @pmaytak logs directly.

**Which version of MSAL.NET are you using?**
4.42.1

**Platform**
.Net 5

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
Visual Studio is seeing this when enabling WAM for a subset of users.

**Repro**
This one is hard to nail down, the best I can say if we ask MSAL  to GetTokenSilent for ARM, on a non-home tenant, and given [not-sure-what] circumstance, that can cause WAM to get/maintain a 2nd account for the same identifier.

Then, subsequent calls to GetTokenSilent can use the wrong WAM account to back the MSAL account, and return something with the non-home-tenant as the Home Tenant.

Again, logs provided separately through email due to PII.

**Expected behavior**
Home Tenant should be constant for a given MSAL account, regardless of what tokens are requested.

**Comment by bgavrilMS** [comment]
WAM does have some logic to match an IAccount and WebAccount based on ID with a fallback to UPN.

**Comment by pmaytak** [comment]
After some investigation, not sure if I was able to repro this exactly. Provided info/updates via email. At the moment pending more specific repro steps/debugging session.

Some notes on the scenarios tested (using a home and a guest account):
1. GetAccounts (ListOSAccounts=true, 0 accounts in MSAL cache, 2 accounts in WAM)
	- Returns 1 account, 1 saved into MSAL cache (whichever account was the last to be processed from WAM)
2. ATI with Guest account  (ListOSAccounts=true)
	- Returns 1 account, 1 saved into MSAL cache (whichever account was the last to be processed from WAM)
	- Then GetAccounts
		- Same as above.
3. ATI with Guest account  (ListOSAccounts=false)
	- Returns 1 guest account
	- Then GetAccounts
		- Same as above
4. ATI with Home account (ListOSAccounts=true)
	- Returns 1 account, 1 saved into MSAL cache (whichever account was the last to be processed from WAM)
	- Then GetAccounts
		- Same as above
5. ATI with Home account, then ATS for Guest authority but the Home account (ListOSAccounts=false)
	- Result is Home and Guest accounts in MSAL cache, ATS returns Guest token, returns home account with both tenant profiles.
	- With (ListOSAccounts=true)
		- Same as above

**Comment by bgavrilMS** [comment]
Can't repro, suggestion is to try with the new WAM implemenatation.
