### ISSUE TITLE
[Bug] WAM Interop dlls fail to load in Net Classic 

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3328]
Investigate issue with WAM Interop dlls failing to load in Net Classic

**Comment by bgavrilMS** [comment]
When you start, the original ETA = revised ETA. I updated the parent ADO to be the one for token biding. 

Please provide repro steps for this, in particular: 

- the type of app (win forms, wpf, winui or console)
- the bitness of the application

**Comment by bgavrilMS** [comment]
This is for a test project. Seems like MSTest problem. Closing as external.
