### ISSUE TITLE
[Bug] Improve performance in Serialize and Deserialize methods in AdalCacheOperations

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#3329]
**Which version of MSAL.NET are you using?**
Latest

**Problem**
[`Serialize`](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/a2e46b12008f5244e4c4d5e21ff303292757ac24/src/client/Microsoft.Identity.Client/Cache/AdalCacheOperations.cs#L18) and [`Deserialize`](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/a2e46b12008f5244e4c4d5e21ff303292757ac24/src/client/Microsoft.Identity.Client/Cache/AdalCacheOperations.cs#L41) methods in `AdalCacheOperations` create a lot of LOH allocations.

**Context**
`AdalCacheOperations` are used to serialize refresh tokens and enable reuse between ADAL and MSAL, which is not needed if only MSAL is used.

**Workaround**
- Call `WithLegacyCacheCompatibility(false)` to disable those ADAL related calls. It's a migration feature, which is not needed when using only MSAL.

**Possible soliton**
Set the legacy cache compatibility to false by default in MSAL.

**Possible solution**
Change `Serialize` to
```csharp
        public static Stream Serialize(IDictionary<AdalTokenCacheKey, AdalResultWrapper> tokenCacheDictionary)
        {
            Stream stream = new SegmentedMemoryStream();

            BinaryWriter writer = new BinaryWriter(stream);
            writer.Write(SchemaVersion);

            writer.Write(tokenCacheDictionary.Count);

            StringBuilder reusedBuilder = new StringBuilder();

            foreach (KeyValuePair<AdalTokenCacheKey, AdalResultWrapper> kvp in tokenCacheDictionary)
            {
                writer.Write(string.Format(
                    CultureInfo.InvariantCulture,
                    "{1}{0}{2}{0}{3}{0}{4}",
                    Delimiter,
                    kvp.Key.Authority,
                    kvp.Key.Resource,
                    kvp.Key.ClientId,
                    (int)kvp.Key.TokenSubjectType));

                reusedBuilder.Clear();
                writer.Write(kvp.Value.Serialize(reusedBuilder));
            }

            stream.Position = 0;

            return stream;
        }

```
Change `Deserialize` to
```csharp
            using (Stream stream = new MemoryStream(state))
            {
                BinaryReader reader = new BinaryReader(stream);
                int blobSchemaVersion = reader.ReadInt32();

                int count = reader.ReadInt32();
                for (int n = 0; n < count; n++)
                {
                    string keyString = reader.ReadString();

                    string[] kvpElements = keyString.Split(new[] { Delimiter }, StringSplitOptions.None);
                    AdalResultWrapper resultEx = AdalResultWrapper.Deserialize(reader.ReadString());
                    AdalTokenCacheKey key = new AdalTokenCacheKey(
                        kvpElements[0],
                        kvpElements[1],
                        kvpElements[2],
                        (TokenSubjectType)int.Parse(kvpElements[3], CultureInfo.CurrentCulture),
                        resultEx.Result.UserInfo);

                    dictionary.Add(key, resultEx);
                }
            }
```

**Comment by bgavrilMS** [comment]
I would rather deprecate ADAL cache compat completely. We can do it from CCA asap, probably from pca as well because pca can get SSO via WAM. @jmprieur thoughts?

**Comment by jmprieur** [comment]
I agree. When we take a major version, let's deprecate it

**Comment by henrik-me** [comment]
Any reason we are not marking it as deprecated now with a warning recommending to turn it off? Could save CPU and memory resources.

**Comment by bgavrilMS** [comment]
@henrik-me - this logic gets executed every time, unless we can figure out that the user has not enabled ADAL migration or that it can't be done, i.e.: 

1. client_credentials flow (RT) or OBO (since tokens are tied to original assertion)
2. custom serialization is not used

We have discussed in the past to also disable it if a request does not use "SerializeADAL" APIs, but decided that it was too complex.

**Comment by bgavrilMS** [comment]
Looks like this is blocking some folks, so implement the suggestion.

**Comment by pmaytak** [comment]
> Looks like this is blocking some folks, so implement the suggestion.

@bgavrilMS Which suggestion [Dynamically disable this in code](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3329#issuecomment-1190220663) or [Improve the Adal Serialize/Deserialize perf](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3329#issue-1238986031)

> Any reason we are not marking it as deprecated now with a warning recommending to turn it off? Could save CPU and memory resources.
There's no public API to obsolete, since this ADAL stuff is done internally by default? We could log a warning specifying to disable this or if they want it enabled, then explicitly call `WithLegacyCacheCompatibility(true)` which will remove the log warning too.

**Comment by bgavrilMS** [comment]
Improving the perf as suggested seems like a quick win.

**Comment by bgavrilMS** [comment]
You'll need to find the original email to fix this. The SegmentedMemoryStream is not part of .NET

**Comment by neha-bhargava** [comment]
Tried to apply the performance optimization suggestions and they are causing cache compat test failures. Closing as won't fix.
