### ISSUE TITLE
[Bug]  Microsoft.Identity.Client.MsalUiRequiredException - thrown in Xamarin forms after app update with wrong Grant credentials time

### ISSUE THREAD

**Issue by edgiardina** [AzureAD/microsoft-authentication-library-for-dotnet#3333]
Using Azure Active Directory B2C + Xamarin Forms iOS and Android

We are seeing issues where our iOS (and possibly android) users are being logged out despite having long-lived refresh tokens (90 days, with no bounded expiry)

![image](https://user-images.githubusercontent.com/3627193/169167814-b5468a73-32f2-4012-bc04-94692d8a2848.png)

**Logs and network traces**
OAuth2Client.ThrowServerException (Microsoft.Identity.Client.Http.HttpResponse response, Microsoft.Identity.Client.Internal.RequestContext requestContext)
Microsoft.Identity.Client.MsalUiRequiredException: AADB2C90080: The provided grant has expired. Please re-authenticate and try again. Current time: 1652302335, Grant issued time: 1649246515, Grant expiration time: 1650456115 Correlation ID: 8540fdff-e495-4a33-b7b0-764542b8b145 Timestamp: 2022-05-11 20:52:15Z 
 
*********NOTE*******

**the above timestamps are the SAME for every request, regardless when it comes in. The timestamps above show an April 6th Refresh Token to April 20th, and the current time says May 11th, but this error came in May 17th! All our users can't possibly have the same refresh token timestamps so there has to be some issue. Also the 'Current Time' is the same for all these errors, and does not track the actual error time as reported by AppCenter (May 11th tracks with the date we deployed the new version to the app store)**

Microsoft.Identity.Client.OAuth2
OAuth2Client.ThrowServerException (Microsoft.Identity.Client.Http.HttpResponse response, Microsoft.Identity.Client.Internal.RequestContext requestContext)
Microsoft.Identity.Client.OAuth2
OAuth2Client.CreateResponse[T] (Microsoft.Identity.Client.Http.HttpResponse response, Microsoft.Identity.Client.Internal.RequestContext requestContext)
Microsoft.Identity.Client.OAuth2
OAuth2Client.ExecuteRequestAsync[T] (System.Uri endPoint, System.Net.Http.HttpMethod method, Microsoft.Identity.Client.Internal.RequestContext requestContext, System.Boolean expectErrorsOn200OK, System.Boolean addCommonHeaders)
Microsoft.Identity.Client.OAuth2
OAuth2Client.GetTokenAsync (System.Uri endPoint, Microsoft.Identity.Client.Internal.RequestContext requestContext, System.Boolean addCommonHeaders)
Microsoft.Identity.Client.OAuth2
TokenClient.SendHttpAndClearTelemetryAsync (System.String tokenEndpoint, Microsoft.Identity.Client.Core.ICoreLogger logger)
Microsoft.Identity.Client.OAuth2
TokenClient.SendHttpAndClearTelemetryAsync (System.String tokenEndpoint, Microsoft.Identity.Client.Core.ICoreLogger logger)
Microsoft.Identity.Client.OAuth2
TokenClient.SendTokenRequestAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] additionalBodyParameters, System.String scopeOverride, System.String tokenEndpointOverride, System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal
SilentRequestHelper.RefreshAccessTokenAsync (Microsoft.Identity.Client.Cache.Items.MsalRefreshTokenCacheItem msalRefreshTokenItem, Microsoft.Identity.Client.Internal.Requests.RequestBase request, Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters authenticationRequestParameters, System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests.Silent
CacheSilentStrategy.RefreshRtOrFailAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests.Silent
CacheSilentStrategy.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests.Silent
CacheSilentStrategy.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests.Silent
SilentRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests.Silent
SilentRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.Internal.Requests
RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken)
Microsoft.Identity.Client.ApiConfig.Executors
ClientApplicationBaseExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenSilentParameters silentParameters, System.Threading.CancellationToken cancellationToken)
aG.Locker.Forms.Services.Authentication
AzureB2CAuthenticationService.RefreshExistingAccounts ()

**Which version of MSAL.NET are you using?**
4.40.0

**Platform**
Xamarin Forms (iOS and Android)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ X ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
 The app is in production, and I believe this issue has been happening since we launched it January 2022.

**Repro**
we don't 100% have a local reproduction, but we started receiving user reports that they would be logged out after we deployed an update to the app via the App Store.

We call the below RefreshExistingAccounts in 4 places in our Xamarin Forms app

1. `OnResume` so that if the app was resumed after sleep or the OS killed it in the background, we get a new token if our existing one is invalid
2. `OnAppLinkRequestReceived` same as 1, really, but in case we are waking the app from following a deep link
3. Once on our 'loading' page which we go to when the app starts before we load any other shell pages
4. All our pages that are behind authentication inherit from a BasePage, who has a BaseViewmodel, who calls RefreshExistingAccounts to make sure our token didn't expire since the last navigation event. 

We are not 100% sure which of the above is triggering the issue.

```csharp
//app.xaml.cs
        protected override async void OnResume()
        {
            base.OnResume();
            Log.Information("App Resumed");
            SetThemeBasedOnDeviceTheme();

            //On resume from sleep, make sure our API token is still valid
            var authService = ServiceProvider.GetService<IAuthenticationService>(); //singleton from D.I.
            if (!authService.IsAuthenticated())
            {
                await MainThread.InvokeOnMainThreadAsync(authService.RefreshExistingAccounts);
            }
        }

Middleware / Auth Service code
public async Task RefreshExistingAccounts()
        {
            try
            {
                Accounts = await SignUpInAuthenticationClient.GetAccountsAsync();

                if (Accounts.Count() > 0)
                {
                    AuthResult = await SignUpInAuthenticationClient
                    .AcquireTokenSilent(new List<string> { azureB2CConfiguration.Scopes }, Accounts.FirstOrDefault())
                    .ExecuteAsync();

                    if (IsAuthenticated())
                    {
                        await ConfigureLoggedInUser();
                    }
                }

            }
            catch (ApiException ex) when (ex.ErrorCode == 482)
            {
                //rethrow here so that LoadingViewModel can redirect to user name creation page.
                throw ex;
            }
            catch (Exception err)
            {
                //general exception trap for network stability issues or acquire token interruption failures
                logger.LogError(err, "Unable to find existing accounts");
            }
        }
```

**Expected behavior**
Users refresh tokens should be valid even after app version update from App Store

**Actual behavior**
User is essentially being logged out by this exception after an update from the app store.

**Comment by bgavrilMS** [comment]
Hi @edgiardina - I don't know how we can help with this. Refresh Token management is done by the service. The SDK knows nothing about refresh token expiration. Is it possible that setting the sliding window to bounded will ensure a better experience? 

The way it works is: 

- the identity provider (B2C) issues an RT that is valid for 90 days and an AT that is valid for 1h
- when you call AcquireTokenSilent, if the AT is expired, MSAL will fetch a new one using the RT
- if this works, the identity provider gives us back a fresh AT and a fresh RT (hence the "rolling window" term).
- if it doesn't work, the identity provider returns an error which MSAL translates as a UiRequiredException.

I suggest you open an issue via the Azure Portal, so that the customer support team / B2C product group can help.

**Comment by edgiardina** [comment]
I guess my concern is that the token is cached by the SDK and somehow the values gotten out of the cache must be wrong after update from the App Store.

**Comment by bgavrilMS** [comment]
On iOS we write the cache to keyChain and on Android to Shared Preferences. I am not aware of app updates changing the ability of the app to access these locations. Accounts object you have in your code is only returned if at least READ access to the token cache occurs. Account is really a projection of the IdToken plus the existence of a refresh token.

**Comment by edgiardina** [comment]
OK. On further research, there is a bug in the UI for AppCenter which caused the provided timestamps to look the same in their web interface. However, if I download the actual report instance as a file, I can see the timestamps are different for each reported instance of the error. So I think MSAL is in the clear here, apologies. I still don't know why users are getting this exception so often after we ship an update, but the grant times are correct in the errors.

**Comment by brentvvosselen** [comment]
Hi @edgiardina, we're facing a similar issue in our application and cannot pinpoint exactly where it goes wrong.
It has been a while that you have raised the issue, but did you find a solution to this?

Many thanks!
