### ISSUE TITLE
Publish Interop PDBs

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3335]
Figure out how to publish symbols (pdb). Currently the .snupkg file does not contain the msalruntime.pdb.

**Comment by bgavrilMS** [comment]
The MSAL C++ team have asked not to publish the pdb file until they open source MSAL C++.

**Comment by gladjohn** [comment]
> The MSAL C++ team have asked not to publish the pdb file until they open source MSAL C++, so I guess this is blocked until then?

moving to blocked for now

**Comment by bgavrilMS** [comment]
Closing as won't fix for now.
