### ISSUE TITLE
Update desktop samples with new WAM implementation.

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3350]
Update the WAM samples to include the new WAM implementation. 

- [ ] [desktop-msgraph-v2](https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2)

**Comment by bgavrilMS** [comment]
Let's wait for a release to update this. Our existing WAM impl has GA-ed.

**Comment by pmaytak** [comment]
@gladjohn Closing as this was moved to Fixed and seems to be completed.
