### ISSUE TITLE
[Feature Request] Samples not building because of windows-2016 brownout

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3351]
**Is your feature request related to a problem? Please describe.**
Windows-2016 environment removal from Azure DevOps will cause some samples not to build. We need to move over to using the Windows 2022.  The windows-2016 environment is deprecated and will be removed from Azure DevOPS on June 30, 2022. For more details, [see](https://github.com/actions/virtual-environments/issues/5403)

- [x] [desktop-msgraph-v2](https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2) - Updated to use Hosted VS2019 Agent

there could be others that needs to be updated. Will have this as a tracking item. 

**Describe the solution you'd like**
We need to move over to Windows 2022

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by bgavrilMS** [comment]
I propose we tackle this as part of a release, i.e. we don't make proactive changes now, but when we upgrade MSAL the CI will fail and we update then.
