### ISSUE TITLE
[Documentation] Broken link in the wiki

### ISSUE THREAD

**Issue by adriancuadrado** [AzureAD/microsoft-authentication-library-for-dotnet#3357]
**Documentation related to component**

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Scenarios#mobile-application-calling-a-web-api-in-the-name-of-the-user-whos-signed-in-interactively

**Please check those that apply**

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**

There is a broken link in the word `location` that points to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Scenarios#controlling-the-location-of-the-dialog-with-the-parent-parameters-uiparent

**Comment by localden** [comment]
Superseded by this document: https://learn.microsoft.com/en-us/entra/msal/dotnet/getting-started/scenarios

The issue is no longer applicable since the URL is no longer included.
