### ISSUE TITLE
[Documentation] Typo in wiki

### ISSUE THREAD

**Issue by adriancuadrado** [AzureAD/microsoft-authentication-library-for-dotnet#3358]
**Documentation related to component**

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#instantiating-a-confidential-client-application-from-code

**Please check those that apply**

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**
There are 2 code snippets that are as follow:

```
string redirectUri = "https://myapp.azurewebsites.net";
IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(clientId)
    .WithClientSecret(clientSecret) // only for web apps, not web APIs nor daemon
    .WithRedirectUri(redirectUri )
    .Build();
```

```
IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(clientId)
    .WithCertificate(certificate)
    .WithRedirectUri(redirectUri )  // only for web apps, not web APIs nor daemon
    .Build();
```

Note how the commet `// only for web apps, not web APIs nor daemon` is in different lines in each code snippet. Is this intended? Is `.WithClientSecret(clientSecret)` meant to be used _only for web apps, not web APIs nor daemon_?

Also, there is a space between `redirectUri` and the closing parenthesis that is going to drive me mad.

**Comment by adriancuadrado** [comment]
I just noticed that in the section [Instantiating a public client application from configuration options](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#instantiating-a-public-client-application-from-configuration-options) there is a broken link for this text: [Sample code: Instantiation of a public client application with configuration Options](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#sample-code-instanciation-of-a-public-client-application-with-configuration-options)

**Comment by bgavrilMS** [comment]
Thanks, I updated the wiki to state that this page has been moved to the docs:

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-applications

Please let us know if you are having issues with the code.
