### ISSUE TITLE
[Documentation] What is the correct MsalServiceException.StatusCode value on retry events?

### ISSUE THREAD

**Issue by DavoudEshtehari** [AzureAD/microsoft-authentication-library-for-dotnet#3369]
**Documentation related to component**
Microsoft.Identity.Client.MsalServiceException

**Please check those that apply**

- [x] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

**Description of the issue**
Looking for the correct answer I found the following docs, but I've confused what is the correct answer!

**Wiki**: [Simple retry for errors with HTTP error codes 500-600](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/retry-after#simple-retry-for-errors-with-http-error-codes-500-600)
- There isn't direct reference to `StatusCode` and the sample code uses `ErrorCode`, while it talks about "Http error 429". Is this the correct value for the `StatusCode` on retry events?

**Doc**: [NavigateError Event Status Codes](https://docs.microsoft.com/en-us/previous-versions//bb268233(v=vs.85)?redirectedfrom=MSDN) (out of support) and [HTTP Status Codes](https://docs.microsoft.com/en-us/windows/win32/wininet/http-status-codes?redirectedfrom=MSDN)
- You can't find "429" in the list, and the 449 seems the most possible answer.

**Also, the [NavigateErrorStatusCode](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0d53f3e80e29f9c6d172e069c10e02d71e24f65e/src/client/Microsoft.Identity.Client/Platforms/Features/WinFormsLegacyWebUi/NavigateErrorStatus.cs#L26) shows the correct value is 449.**

**Comment by bgavrilMS** [comment]
No, it's 429, please see the HTTP spec: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by bgavrilMS** [comment]
[HttpStatusCode](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=net-6.0) does NOT have 429 listed on all platforms - you can see it's there on NET6. But the code is just an int, so you can rely on `(int)response.HttpStatusCode`
