### ISSUE TITLE
[Bug] Region failures not well logged

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3372]
msal 4.44

1. Create CCA with region set to auto-detection. Set logger to Info.
2. AcquireTokenForClient in an env not on Azure (e.g. personal dev machine)
3. AcquireTokenForClient again. 

Actual: in the log I see

## first call
`[Region discovery] Auto-discovery successful but found null or empty region.` **info** (this is misleading)
`[Region discovery] Region from REGION_NAME env variable not detected. 6/7/2022 6:10:03 PM` (verbose)
HTTP expection for calling IMDS (verbose)

## subsequent calls
[Region discovery] Not using a regional authority.

Expected: 

## first call
status of discovery from env variable and IMDS

## first and subsequent calls
reason for auto-discovery failure (at WARN level)

**Comment by pmaytak** [comment]
Partially fixed by #3523

**Comment by bgavrilMS** [comment]
#3523 fix should be sufficient.
