### ISSUE TITLE
[Bug] Requesting a SpaAuthCode for a B2C client results in a null SpaAuthCode response from the token endpoint

### ISSUE THREAD

**Issue by david-shinn** [AzureAD/microsoft-authentication-library-for-dotnet#3380]
**Logs and network traces**
![Screenshot 2022-06-09 145613](https://user-images.githubusercontent.com/85179801/172935687-a560f6b0-591d-4c1b-a97a-f70104d3ea1b.png)
)

**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.42.1

**Platform**
.NET Framework 4.8

**What authentication flow has the issue?**
* Web app 
    * [x ] Authorization code
    
Other?
Requesting a Spa Authorization Code for a B2C client results in a null Spa code response from the token endpoint

**Is this a new or existing app?**
New

**Repro**

```csharp
ConfidentialClientApplicationBuilder.Create(_clientId)
                      .WithClientSecret(_clientSecret)
                      .WithRedirectUri(_redirectUri)
                      .WithB2CAuthority($"{_authority}/{policy}")
                      .Build()

confidentialClientApplication.AcquireTokenByAuthorizationCode(scopes, authorizationCode)
                .WithSpaAuthorizationCode(withSpaAuthorizationCode)
                .ExecuteAsync()
```

**Expected behavior**
The AuthenticationResult response contains a non-null SpaAuthCode property

**Actual behavior**
SpaAuthCode property is null

**Possible solution**
Is it even possible with a B2C authority?

**Additional context / logs / screenshots / links to code**
The normal authorization code requests works fine for the BE, but the SpaAuthCode for the FE is always null.

**Comment by jmprieur** [comment]
I don't think that this protocol is supported by B2C.

**Comment by david-shinn** [comment]
Thanks for the confirmation. Do you have a recommended alternative for a hybrid ASP.NET sites loading React apps that need auth tokens on some pages?

**Comment by bgavrilMS** [comment]
Not tracking this any longer
