### ISSUE TITLE
ASP.NET Webforms Sample 

### ISSUE THREAD

**Issue by hannespreishuber** [AzureAD/microsoft-authentication-library-for-dotnet#3382]
After days of trying nearly everything and reading - still no sucess 

ASP.NET Webforms, MSGraph 
login startup

`
app.UseOpenIdConnectAuthentication(New OpenIdConnectAuthenticationOptions() With {
.ClientId = clientId,
.Authority = authority,
.PostLogoutRedirectUri = postLogoutRedirectUri,
 .RedirectUri = "https://localhost:44399",
  .Notifications = New OpenIdConnectAuthenticationNotifications() With {
             .SecurityTokenValidated = Function(context)
                                           Dim name As String = context.AuthenticationTicket.Identity.FindFirst("preferred_username").Value
                                           context.AuthenticationTicket.Identity.AddClaim(New Claim(ClaimTypes.Name, name, String.Empty))
                                           Return Task.FromResult(0)
                                       End Function,
              .AuthenticationFailed = Function(context)
                                          Return Task.FromResult(0)
                                      End Function
              }
        })
`

seems to be success. (user.identity.name)

account is null /nothing
ClaimsPrincipal.Current. have user content
in aspx page 

`
 
        Dim app = ConfidentialClientApplicationBuilder.Create(ClientID) _
            .WithTenantId(tenantId) _
            .WithClientSecret(ClientSecret) _
               .WithAuthority(New Uri(authorityUri)) _
               .WithLegacyCacheCompatibility(False) _
        .WithRedirectUri(redirectUri).Build()
       app.AddInMemoryTokenCache()
        Dim result As AuthenticationResult
        '' Dim accounts = Await app.GetAccountsAsync() old???
        Dim Account = Await app.GetAccountAsync(ClaimsPrincipal.Current.GetMsalAccountId())

        Try

            result = Await app.AcquireTokenSilent(scopes, Account).ExecuteAsync().ConfigureAwait(False)
`

I am sure I miss some understanding

**Comment by jmprieur** [comment]
@hannespreishuber : did you look at this sample: https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect ?

**Comment by hannespreishuber** [comment]
works with core and others. 
Azure AD - 
as I have written: account is null /nothing
