### ISSUE TITLE
[Question] Single-tenant app token cache

### ISSUE THREAD

**Issue by zsybupt** [AzureAD/microsoft-authentication-library-for-dotnet#3385]
Hi Team,
We are now using a single-tenant application and AcquireTokenForClient(scopes), and there are around 15k resources here. Now the memory keeps growing up, and we want to enable distributed cache. If we use for example a redis for distribute cache, the key is the same (tenantId), so the value will be the set of all resource's tokens, right?  Then we will run to another issue of big redis value.

Is there a solution for our problems, Thanks !

**Comment by bgavrilMS** [comment]
How come you have 15k resources? That's quite a lot. 1 tenant and 15k resources will not scale well based on our existing cache partitioning, because, as you say, we only partition by tenant id. 

You'd have to write your own cache - see https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom#custom-token-cache-for-a-web-app-or-web-api-confidential-client-application

And instead of using MSAL's [suggested cache key](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.cs#L87) you'd use `suggestedCacheKey + resource`.

**Comment by bgavrilMS** [comment]
CC @jmprieur

**Comment by zsybupt** [comment]
@bgavrilMS  Thanks for reply, I have two questions here:
> 
> You'd have to write your own cache - see https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom#custom-token-cache-for-a-web-app-or-web-api-confidential-client-application
> 
> And instead of using MSAL's [suggested cache key](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.cs#L87) you'd use `suggestedCacheKey + resource`.

1.If we implement our own cache, when the OnBeforeAccess method get called. Is there a way for us to correlate this call with the  resource. I see there is a correlationid in TokenCacheNotificationArgs, so can we create a correlationId, use WithCorrelationId and store the resource by correlationId before call AcquireTokenForClient, and then we can get the resource by it in OnBeforeAccess.
2. We now have single-tenant+multi-tenant, apptoken+usertoken, is there a way to just implement our own cache for single-tenant app token scenario, we dont want to change other scenarios' behavior.

**Comment by zsybupt** [comment]
For 2, maybe we can use properties to check with it is single tenant+app token, then will add resouce in the cache key, otherwise we can keep the default behavior.

**Comment by bgavrilMS** [comment]
For 1 - I think MSAL needs to expose the resource (scope) in `TokenCacheNotificationArgs` - please open a featuer request for this, should be pretty simple. 

For 2 - you can just have 2 ConfidentialClientApplication objects - one with app token + custom cache, one with user tokens + normal cache.

**Comment by zsybupt** [comment]
Great, I will open a feature request

**Comment by bgavrilMS** [comment]
@zsybupt - it is not needed to change the serialization primitives. The way it works is

```csharp
AcquireTokenForClient for tenant T and resource R

1. Do a cache read. Suggested cache key is T. You will change that and make it T+R
2. Cache is read. Assume cache miss.
3. MSAL will go to ESTS and fetch a token. 
4. Do a cache write. Suggested cache key is T. You will change that and make it T+R. Token for resource R and tenant T is cached in Redis under key T+R.

If you call AcquireTokenForClient for tenant T and resource R again, the cache read on step 1 will succeed.
```

**Comment by zsybupt** [comment]
For now, we are using a singleton ConfidentialClientApplication, so I think the Accessor are shared for each request, when do a cache write, all access tokens of the partition (tenantid) will be writen to redis.

So we have to create a ConfidentialClientApplication for each request in single-tenant scenario, right ?

**Comment by bgavrilMS** [comment]
No, you don't have to create a new CCA object everytime. Each `AcquireToken*` call manages its own cache.

**Comment by zsybupt** [comment]
Yes, singleton's issue is the memory of accessor will grow larger, and will not be disposed. If we have a cache enabled, we don't need a singleton now, cache will handle request across different ConfidentialClientApplicaiton.

Thanks for your reply.

**Comment by bgavrilMS** [comment]
Accessor is flushed on every request. Each request clears the existing internal MSAL cache (the accessor) and then loads the tokens from the location the app developer specifies (e.g. Redis). So accessor growing large will definitely not happen. 

But 2 parallel requests can theoretically mess up the shared state (the accessor) which can lead to MSAL not fetching a token from the accessor (like a cache miss) but going to ESTS. Originally we were using locks to prevent this from happening, but this caused problems (contention / high latency) in high tput sceanrios and we dropped it. Worse case scenario is that MSAL will make a few extra ESTS calls when it doen't need to, which is acceptable. In practice, nobody complained and we are serving some pretty large internal customers. You can monitor the cache hit ratio by looking at `AuthenticationResult.AuthenticationResultMetadata.TokenSource`.

So yes - 1 CCA per request will avoid all this complication but singleton CCA will also work. I recommend 1 CCA per request.

**Comment by zsybupt** [comment]
seems there are other works to do before the release.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/milestone/100

**Comment by pmaytak** [comment]
@zsybupt 4.45.0 was released. Closing as seems like the question is answered, but if not, please reopen.
