### ISSUE TITLE
[Feature Request] Expose resource (scopes) in TokenCacheNotificationArgs

### ISSUE THREAD

**Issue by zsybupt** [AzureAD/microsoft-authentication-library-for-dotnet#3389]
**Is your feature request related to a problem? Please describe.**
#3385 As described here, now the app token is partitioned by tenantid, when using it with single-tenant, it will become a memory issue with large resource amount.  And if we want to enable distributed cache, the value's size is a concern, because the suggestedkey is {clientId}_{tenantId}_AppTokenCache, so all the access tokens will be serialized into a byte array, this will cause a LOH allocation and a large redis vaule (if we use redis as distributed cache).

**Describe the solution you'd like**
1. Expose the resource (scope) in TokenCacheNotificationArgs.
~2. Change the serializer behavior to support single access token serializations.~

**Comment by bgavrilMS** [comment]
I'd like to take this for 4.45, it is a trivial change.

**Comment by zsybupt** [comment]
Thanks for your quick reply, how long does it take to release a new 4.45 version, is there an ETA? If it takes too long, may be we have to find a workaround

**Comment by bgavrilMS** [comment]
I have a PR out of this, we're aiming for a release by ~mid next week (end of week if things go well).

**Comment by zsybupt** [comment]
Great, Thanks
