### ISSUE TITLE
[Documentation] Small grammar issue in MSAL doc

### ISSUE THREAD

**Issue by richardsondev** [AzureAD/microsoft-authentication-library-for-dotnet#3390]
**Documentation related to component**

**Please check those that apply**

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**

In the following section header, "migrating" should be used instead of "migration"

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-or-Microsoft.Identity.Web#im-adding-auth-to-an-existing-app-or-im-migration-from-adal  "I'm adding auth to an existing app or I'm migration from ADAL"

**Comment by bgavrilMS** [comment]
Thanks, fixed.
