### ISSUE TITLE
[Feature Request] Determine OS using MSALRuntime for WAM

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3394]
**Is your feature request related to a problem? Please describe.**
Currently we use our own logic to determine the current OS. MSAL Runtime provides it's own implementation to determine if Broker is available. 

**Describe the solution you'd like**
Switch to MSAL Runtime provided version of OS check

**Describe alternatives you've considered**
none applicable

**Additional context**
This can be fully implemented when we move completely to the new broker. But for the new broker this can be used.

**Comment by bgavrilMS** [comment]
Our logic seems to work fine, proposing won't fix.
