### ISSUE TITLE
[Feature Request] Update microsoft sdl analyzer package

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3397]
We need to update the Microsoft.CodeAnalysis.NetAnalyzers package

error: 10>C:\Users\nebharg.REDMOND\.nuget\packages\microsoft.codeanalysis.netanalyzers\5.0.3\build\Microsoft.CodeAnalysis.NetAnalyzers.targets(632,5): warning : The .NET SDK has newer analyzers with version '6.0.0' than what version '5.0.3' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference.
10>CommonCache.Test.MsalNode -> C:\git\msal-1006\tests\CacheCompat\CommonCache.Test.MsalNode\bin\Debug\net461\CommonCache.Test.MsalNode.exe

**Describe the solution you'd like**

- Navigate to https://www.1eswiki.com/wiki/Microsoft.Internal.Analyzers.Rulesets to get the new ruleset file
- update Microsoft.CodeAnalysis.NetAnalyzers
- Use the tool in the latest Microsoft.CodeAnalysis.NetAnalyzers to convert the ruleset file to an editor config
- update editor config in msal directory

**Comment by bgavrilMS** [comment]
I trust that OneBrach takes care of this?

CC

**Comment by bgavrilMS** [comment]
it's on version 8 today.
