### ISSUE TITLE
[Bug] Remove XAMARINMAC20 filter form identity logging

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3402]
MSAL sems to fail to build when the XAMARINMAC20 target tries to use the new "Microsoft.IdentityModel.Abstractions". Therefore, the new logging api is hidden form XamarinMac with

#If !XAMARINMAC20
...
#endif

We need to find a way to make Xamarin Mac work with the new package wo we can stop hiding the logger code form that platform and simplify the implementation

**Which version of MSAL.NET are you using?**
4.45.0

**Platform**
Xamarin Mac

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes.  

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by bgavrilMS** [comment]
We dropped support for xamarin mac.
