### ISSUE TITLE
[Bug] Upgrade Newtonsoft to the latest version

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3413]
**Logs and network traces**
NA

**Which version of MSAL.NET are you using?**
4.44

**Platform**
Applicable to all

**issue?**
GitHub has warning to upgrade Newtonsoft. Ref: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/security/dependabot

**Possible solution**
- [x] Upgrade Newtonsoft references (PRs [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies+newtonsoft.json))
- [x] Upgrade Newtonsoft direct source code ref

**Comment by bgavrilMS** [comment]
We also need to upgrade Newtonsoft version in MSAL.

**Comment by bgavrilMS** [comment]
This was alraedy done for Wilson if you need inspiration.

**Comment by bgavrilMS** [comment]
@trwalke - please coordinate with @pmaytak on this one or pick something else.
