### ISSUE TITLE
[Bug] Microsoft.Identity.Client doesnot return a Refresh token along with Access Token

### ISSUE THREAD

**Issue by Hexagon-INH** [AzureAD/microsoft-authentication-library-for-dotnet#3418]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive   

Other?

**Is this a new or existing app?**

**Repro**

```csharp
var your = (code) => private static async Task<AuthenticationResult> SignInUserAndGetTokenUsingMSAL(string[] scopes)
        {
            // Initialize the MSAL library by building a public client application
            application = PublicClientApplicationBuilder.Create(clientId)
                                       .WithAuthority(authority)
                                       .WithDefaultRedirectUri()
                                       .Build();

            AuthenticationResult result;

            
            try
            {
                var accounts = await application.GetAccountAsync("e9..0.1..a");
                string LoginHint = "jy.tala@h.com";
                result = await application.AcquireTokenSilent(scopes, LoginHint)
                    .WithForceRefresh(true)
                        .ExecuteAsync();
            }
            catch (MsalUiRequiredException ex)
            {
                // If the token has expired, prompt the user with a login prompt
                result = await application.AcquireTokenInteractive(scopes)
                        .WithClaims(ex.Claims)
                        .ExecuteAsync();
                
                
            }
            return result;
        };
```

**Expected behavior**
I have an Desktop .Net app that will connect to Azure DevOps. Im using Microsoft.Identity.Client to fetch access token . As this is valid for only an hour, i would like to save the Refresh token(as its validity is 90 days and can be used to fetch access token silently) too. When user closes and restarts the app even after few hours/days, using Refresh token i would try to acquire token silently without asking user to select an account. 

For this i would need to save the refresh token. 

Token cache is inmemory and is lost whenever the app is closed. We do not have persisted token cache available for the app.
We have registered the app in Azure cloud with scopes : user_impersonation, offline_access, User,Read

Please suggest how to acheive this. Or how to fetch refresh token.

**Actual behavior**
Does NOT return Refresh token.  

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by bgavrilMS** [comment]
MSAL libraries are slightly higher level than OAuth protocol, so we do not expose RT concept, but we do use it internally. MSAL library will never give you an AT that is expired. 

Please have a look at the sample https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/tree/master/2-TokenCache which shows you how to configure token caching. You will also need to remove `WithForceRefresh`. 

AcquireTokenSilent will take care of RT handling for you. It will: 

- give back an AT from cache if one is available
- if an AT does not exist or is expired, but an RT exists, MSAL will use the RT to give to fetch a new AT
- if all else fails (e.g. no RT, or the idenity provder needs to enforce MFA), MSAL will throw an MsalUIRequiredException

**Comment by Hexagon-INH** [comment]
Hi i checked the sample you gave its working. 

But when i use the same code in my code , the msal.contoso.cache file is not getting generated. 

i have installed all the packages that are specified in the sample but to latest versions and for target framework 4.6.1.

I donot understand what package or dll is misssing that even on debug the breakpoint on Registercache does not hit .

Could you pls suggest how to proceed

**Comment by Hexagon-INH** [comment]
packages i have installed:

<packages>
  <package id="Azure.Core" version="1.24.0" targetFramework="net461" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration" version="6.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.FileExtensions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Json" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Physical" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileSystemGlobbing" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Primitives" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Graph" version="4.32.0" targetFramework="net461" />
  <package id="Microsoft.Graph.Core" version="2.0.9" targetFramework="net461" />
  <package id="Microsoft.Identity.Client" version="4.45.0" targetFramework="net461" />
  <package id="Microsoft.Identity.Client.Extensions.Msal" version="2.22.0" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Abstractions" version="6.19.0" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="6.19.0" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Logging" version="6.19.0" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Protocols" version="6.19.0" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="6.19.0" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Tokens" version="6.19.0" targetFramework="net461" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.7.1" targetFramework="net461" />
  <package id="System.IdentityModel.Tokens.Jwt" version="6.19.0" targetFramework="net461" />
  <package id="System.Memory" version="4.5.4" targetFramework="net461" />
  <package id="System.Memory.Data" version="1.0.2" targetFramework="net461" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net461" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="6.0.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Claims" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.ProtectedData" version="6.0.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encodings.Web" version="6.0.0" targetFramework="net461" />
  <package id="System.Text.Json" version="6.0.4" targetFramework="net461" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net461" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net461" />
</packages>

**Comment by bgavrilMS** [comment]
You have to manually configure the cache and set it like here: https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/blob/master/2-TokenCache/Console-TokenCache/Program.cs#L41 (see block of code L41 - L56)
