### ISSUE TITLE
[Bug] TestSerializeAccountWithWamId Test fails due to difference in line ending

### ISSUE THREAD

**Issue by azchohfi** [AzureAD/microsoft-authentication-library-for-dotnet#3425]
I tried cloning the repo and running the Microsoft.Identity.Test.Unit tests, in netcoreapp3.1, and a single test failed to run:
`TestSerializeAccountWithWamId`

Investigating this further, I found out that the reason for this is that this file is the only test that uses multi-line string literals.
This means that it uses the current file's CRLF definition, which is not specified by this project, neither on .gitattributes, nor or .editorconfig file. Running:
`git ls-files --eol tests\Microsoft.Identity.Test.Unit\CacheTests\CacheSerializationTests.cs`
Returns:
`i/lf    w/lf    attr/                   tests/Microsoft.Identity.Test.Unit/CacheTests/CacheSerializationTests.cs`

Which means that the repository is storing this file as LF, and the cloned version is also LF. If I open the file in Visual Studio and change the line endings to CRLF, then the test passes.

**Repro**
Clone the repo with only LF at your global git configs, run the tests.

**Expected behavior**
C# files use consistent line endings so this issue doesn't happen.

**Actual behavior**
The build will work, but one test will fail.

**Possible solution**
Configure .gitattributes and .editoconfig files so line endings are consistent.

**Comment by azchohfi** [comment]
Looks like it will work, yup!

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
