### ISSUE TITLE
[Feature Request] Public API to extract TenantId out of Authority URL

### ISSUE THREAD

**Issue by rabenshm** [AzureAD/microsoft-authentication-library-for-dotnet#3429]
**Is your feature request related to a problem? Please describe.**
As we have been requested to use only .WithTenantId on the request level instead of .WithAuthority we would like to have public API common code to get the TenantId out of the Authority Url

**Describe the solution you'd like**
As described

**Describe alternatives you've considered**

**Additional context**

**Comment by bgavrilMS** [comment]
Probably a static stand-alone method. `ClientApplicationBase.GetTenantId(Uri authority)` or an extension method on string / Uri.

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
