### ISSUE TITLE
[Bug] Call AcquireTokenInteractively instead of SignInInteractively

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3437]
Tracking item to investigate and test all scenarios before doing the switch from SignInInteractively -> AcquireTokenInteractively 

If you knew the account is in WAM and am able to rehydrate the account, please do call AcquireTokenInteractively instead of SignInInteractively. We don’t want to show any unnecessary prompt to the user. 

**Background :** 

When the account is not the default OS Account or when no login_hint is passed then we call the [SIgnInInteractivelyAsync API](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fblob%2Fmain%2Fsrc%2Fclient%2FMicrosoft.Identity.Client.Broker%2FRuntimeBroker.cs%23L83&data=05%7C01%7CGladwin.Johnson%40microsoft.com%7Ca54e71ad965146040edc08da5ab6933a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637922037460050967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S%2BZCdFBUdOP%2FVUQdouL%2FYwCjmdRAAp84OzSWzvKdTwU%3D&reserved=0), Now you get prompted to let windows remember the account for further sign-ins. Choosing to remember.  WAM goes through this registration process.

**Expected :** With that message “Windows will remember the account”, I’d expect the UI is not shown when I pass the login_hint for subsequent calls. But instead the UI is always thrown requesting to enter password. 

**Suggested Fix :** Call AcquireTokenInteractively instead of SignInInteractively

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
