### ISSUE TITLE
[Feature Request] Deprecate Old WAM

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3447]
**Is your feature request related to a problem? Please describe.**
Explore options on how to deprecate the old WAM broker

**Describe the solution you'd like**
need to explore possible solutions

**Describe alternatives you've considered**
none

**Additional context**
This will make the new broker the only option in MSAL .Net for WAM

**Comment by bgavrilMS** [comment]
@jmprieur - I was thinking we do this as part of 4.x ? Here's how I see this done: 

1. Figure out how to inject functionality from MIcrosot.Identity.Client.Broker in MSAL. Currently this is done via "WithBrokerPreview". We can leave this as is and I was thinking of removing "WithBroker" from net4*, netstandard and netcore and replacing it iwth  MIcrosot.Identity.Client.Broker.WithBroker. Suggestions welcome.

1. Deprecate Microsoft.Identity.Client.Desktop package via nuget message which recommends use of MIcrosot.Identity.Client.Broker package instead.

It's true that ` Microsoft.Identity.Client.Desktop` also has WebView2 support for B2C. I suggest we drop this for now and update our desktop sample instead (the CustomWebUI version)

**Comment by jmprieur** [comment]
@bgavrilMS : I guess I would need to see the before / after in term of API / DevEx to fully understand

**Comment by gladjohn** [comment]
@bgavrilMS 

do we have a final plan on the deprecation of the old broker? are we doing the alternative approach? 

"Deprecate MIcrosot.Identity.Client.Broker and move all functionality to Microsoft.Identity.Client.Desktop. Should be a drop-in replacement, but we cannot gurantee that the exact scenarios will work."

**Comment by gladjohn** [comment]
@SameerK-MSFT assiging this to you since you are working on finalizing the design

**Comment by gladjohn** [comment]
Adding this to in-progress to track the deprecation of the old broker and for naming the new APIs
