### ISSUE TITLE
[Bug] Net Standard Platform Proxy Updates

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3451]
- NetStandard13PlatformProxy.cs is incorrectly named, it should be updated to reflect net standard 2.0.

- Update NetStandard13PlatformProxy.cs to use logic from the netcoreapp2.1 target as these platform proxies should ideally be the same after the net standard 2.1 update.

- Investigate if the netcoreapp2.1 target should be deleted.

**Comment by bgavrilMS** [comment]
Closing as duplicate of #1991

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
