### ISSUE TITLE
[Bug] Microsoft.Identity.Client: unable to obtain token for partner azure region (Ex. China)

### ISSUE THREAD

**Issue by RajneeshVerma** [AzureAD/microsoft-authentication-library-for-dotnet#3455]
Error details ![image](https://user-images.githubusercontent.com/5612153/177644946-cc0441dd-5c86-416c-85b2-389e225453e8.png)

**Which version of MSAL.NET are you using?**
[Microsoft.Identity.Client -Version 4.36.1](https://www.nuget.org/packages/Microsoft.Identity.Client/4.36.1)

**Platform**

**What authentication flow has the issue?**
* Web app 
    * [x] Authorization code

**Is this a new or existing app?**

The app is in production, and I have upgraded to a new version of MSAL. 

We were using [Microsoft.Identity.Client -Version 4.11.0](https://www.nuget.org/packages/Microsoft.Identity.Client/4.11.0) to get access token from AAD App residing in partner regions (China) which internally calls public cloud discovery url: https://login.microsoftonline.com/*_TenantId_*/v2.0/.well-known/openid-configuration to get token endpoint.

It started failing when we updated to [Microsoft.Identity.Client -Version 4.36.1](https://www.nuget.org/packages/Microsoft.Identity.Client/4.36.1), we have tested the same in latest version [Microsoft.Identity.Client -Version 4.45.0](https://www.nuget.org/packages/Microsoft.Identity.Client/4.45.0) and its still not working.

**Expected behavior**
We should be able to get access token from partner azure regions after upgrading to the latest version of MSAL.NET

**Actual behavior**
Error occured while generating token, error details are added above, it can be easily reproduced with any AAD App from a partner region.

**Possible solution**
Is this a known issue ? do we have any other option to make it working !!

**Comment by bgavrilMS** [comment]
We have integration tests running in other clouds, so I do expect this to work. The error message suggests that the tenant_id is incorrect. 

How do you specify the authority? You should use "https://login.partner.microsoftonline.cn/{tenant_id}"

**Comment by jmprieur** [comment]
@RajneeshVerma : what do you mean "recent versions". Please be more specific (in which version of MSAL was this working? I understand it's not working in 4.36.1.

Also:
- do you mean China as an Azure region ? or an Azure cloud?
- What is your app? is it a web app? a web API? a daemon app? where is it hosted? App services? Azure functions etc ...?

**Comment by RajneeshVerma** [comment]
@jmprieur Working version is mention in my initial message
**Working version**: [Microsoft.Identity.Client -Version 4.11.0](https://www.nuget.org/packages/Microsoft.Identity.Client/4.11.0)
**do you mean China as an Azure region ? or an Azure cloud?**: China Azure Cloud
**What is your app?**: Web API hosted in a VM calling other Web API (Protected with AAD) with Client Credentials flow.

*Issue can be easily reproduced by using an AAD App available in China Azure Cloud*

**Comment by RajneeshVerma** [comment]
@bgavrilMS This was working solution and is in production with 4.11.0 version but it broke after upgrading to 4.36.0 or latest.
Can you please share more details in which version the discovery was removed so that we can plan accordingly.

**Comment by bgavrilMS** [comment]
I'd like to better understand the scenario. How can you know the tenant_id upfront but not the cloud which it belongs to?

**Comment by RajneeshVerma** [comment]
I know the TenantId as well as cloud region but as MSAL.NET is using with discovery we haven't saved/provided authority.

As this is broken in latest version, we will work to use authority to generate token.

**Comment by bgavrilMS** [comment]
Thanks for the update @RajneeshVerma. We'd like to keep MSAL as is, i.e. no call to OIDC endpoint, as it improves perf quite a bit. Since you have a solution, I'm goning to close this as won't fix.
