### ISSUE TITLE
[Bug] UWP Samples Fail to compile in the MAUI - Preview

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3460]
**Which version of MSAL.NET are you using?**
4.46-preview2

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
Compilation fails in the sample

**Is this a new or existing app?**
Existing

**Expected behavior**
Xamarin Samples compile for UWP

**Actual behavior**
Xamarin samples fail to compile for UWP

**Possible solution**
Temporarily unload the projects. Not supported anyway.

**Comment by bgavrilMS** [comment]
Does not repro
