### ISSUE TITLE
[Bug] MSAL not communicating with  swift application. Not able signing in automatically if logout from other app

### ISSUE THREAD

**Issue by snehal1611** [AzureAD/microsoft-authentication-library-for-dotnet#3467]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.43.1

**Platform**
 Xamarin iOS & Swift

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Username Password

Other?

**Is this a new or existing app?**
This is a new app or experiment.

**Repro**
var accounts = await _pca.GetAccountsAsync();
                var firstAccount = accounts.FirstOrDefault();
                
                var authResult = await _pca.AcquireTokenSilent(Scopes, firstAccount).ExecuteAsync();

                // Store the access token securely for later use.
                await SecureStorage.SetAsync("AccessToken", authResult?.AccessToken);
                await SecureStorage.SetAsync("ExpiresOn", authResult?.ExpiresOn.ToString());

**Expected behavior**
When we log in from xamarin based app then swift based app both apps logs in successfully and when we logout from swift based  app it should logout from both app

**Actual behavior**
When we log in from xamarin based app then swift based app is logging in successfully and when we logout from swift based  app it is logs out from both app but issue is when trying to login again from xamarin based app it is not logging in swift based app

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by trwalke** [comment]
Are you using the broker to sign in with these apps?

**Comment by bgavrilMS** [comment]
not enough info.
