### ISSUE TITLE
[Feature Request] Provide a way of clearing the in-memory token cache for a ConfidentialClientApplication

### ISSUE THREAD

**Issue by akamud** [AzureAD/microsoft-authentication-library-for-dotnet#3474]
Sometimes an application might be updated on Azure to have more permissions added to it, when this happens, if a token is already cached by my `ConfidentialClientApplication`, there is no way (that I know of) to remove a token that is already cached, to force a "refresh". So all the subsequent requests to my resource will return 403 until the token expires from cache and a new one is obtained.

I tried using the `GetAccountsAsync` method documented [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-clear-token-cache), but, even though it doesn't explicitly say anything regarding this, it only [handles user tokens](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/ClientApplicationBase.cs#L244).

There should be a way to force clearing the token cache. The way I see this getting implemented in my application is having a retry policy that tries to obtain a new token whenever a call to my resource returns 403, to make sure my token is refreshed.

I see a few ways this could be possible:
* Getting something like the "AppAccounts" so I can manually remove them.
* Clearing the cache explicitly
* Having a way to force a bypass from cache when requesting a new token (`AcquireTokenForClient`).

**Comment by jmprieur** [comment]
Did you try the `.WithForceRefresh(true)` call on the builder retruned by app.AcquireTokenXXX() methods?\

```CSharp
app.AcquireTokenForClient(scopes)
 .WithForceRefresh(true)
 .ExecuteAsync();
```

**Comment by akamud** [comment]
> Did you try the `.WithForceRefresh(true)` call on the builder retruned by app.AcquireTokenXXX() methods?\
> 
> ```cs
> app.AcquireTokenForClient(scopes)
>  .WithForceRefresh(true)
>  .ExecuteAsync();
> ```

Never knew this existed, sorry about that.
Is this documented somewhere other than the API Browser that I missed?

**Comment by jmprieur** [comment]
You are right, @akamud it's not well documented (apart from https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-2.x-to-MSAL.NET-3.x), and it shouldn't be used in other scenarios than the one you mentioned.
We need to document it better.

BTW, mind you, don't use it systematically otherwise Azure AD will throttle you.

**Comment by akamud** [comment]
Thanks for your responses, you've been very helpful!

If you allow me to suggest, when I was trying to figure this out, I though [this page](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-clear-token-cache) would have this info.

We are being very careful in our retry policy to try it only once skipping cache, to avoid the throttling.

**Comment by bgavrilMS** [comment]
Thanks @akamud - I created a docs PR for this https://github.com/MicrosoftDocs/azure-docs/pull/95763
