### ISSUE TITLE
[Bug] Perf - MSAL stores authorities as strings and doing too many string operations. Try to use Uri instead.

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3487]
Refactor AuthorityInfo and related code. We should not be doing so much string operations.

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
