### ISSUE TITLE
[Bug] MSAL.NET does not pass intune_mam_resource to the broker

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3490]
**Logs and network traces**
NA

**Which version of MSAL.NET are you using?**
4.45.0

**Platform**
iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
NA

**Is this a new or existing app?**
New

**Expected behavior**
intune_mam_resource  should be passed to the broker. Empty if there is not entry.

**Actual behavior**
intune_mam_resource  should be passed to the broker. Empty if there is not entry.

**Possible solution**
Add the entry to parameters

**Additional context / logs / screenshots / links to code**
NA

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
