### ISSUE TITLE
[Bug] MSAL misses `/dstsv2` vdir in "userrealm" API Authority for dSTS

### ISSUE THREAD

**Issue by saitharun-msft** [AzureAD/microsoft-authentication-library-for-dotnet#3492]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.44.0

**Platform**
.NET 4.6

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
 This is to onboard MSAL support for dSTS 

**Repro**
Try using Integrated Windows Authentication to Test instance 3 dSTS and user realm should fail with 404

**Expected behavior**
`/dstsv2/` should be prefixed for dSTS userrealm API request URI
`GET /dstsv2/common/userrealm/sthodupunuru@microsoft.com?api-version=1.0 HTTP/1.1`

**Actual behavior**
MSAL is hitting endpoint for userrealm API which is resulting in 404. `/dstsv2/` in the authority is missing
 `GET /common/userrealm/sthodupunuru@microsoft.com?api-version=1.0 HTTP/1.1`.  

**Possible solution**
Fix the authority for the `userrealm` api for dSTS

**Network Traces for the MSAL userrealm API for dSTS**
**Request:**
```
GET https://test-instance3-passive-dsts.dsts.core.azure-test.net/common/userrealm/sthodupunuru@microsoft.com?api-version=1.0 HTTP/1.1
x-client-SKU: MSAL.Desktop
x-client-Ver: 4.44.0.0
x-client-CPU: x64
x-client-OS: Windows 10 Enterprise
Accept: application/json
Host: test-instance3-passive-dsts.dsts.core.azure-test.net
Connection: Keep-Alive
```
**Response:**
```
HTTP/1.1 404 Not Found
Cache-Control: private
Content-Type: text/html; charset=utf-8
request-id: a59c424d-ddc0-4755-b48e-63a778481270
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Tue, 19 Jul 2022 07:03:10 GMT
Content-Length: 1928

<!DOCTYPE html>
<html>
    <head>
        <title>The resource cannot be found.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>The resource cannot be found.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the following URL and make sure that it is spelled correctly.
            <br><br>

            <b> Requested URL: </b>/common/userrealm/sthodupunuru@microsoft.com<br><br>

    </body>
</html>
```

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
