### ISSUE TITLE
[Bug] Increased latency in AcquireTokenOnBehalfOf

### ISSUE THREAD

**Issue by mezaugusto** [AzureAD/microsoft-authentication-library-for-dotnet#3493]
**Logs and network traces**
After updating to MSAL `4.44.0` from `4.42.0` we have seen an increase in latency, we have set up a 5s timeout and we are seeing several request reaching this threshold with this new version of the library, only in `AcquireTokenOnBehalfOf` calls, we also perform `AcquireTokenForClient` but that call is not impacted. Is there anything in the new library that might cause this issue?

Sample call:
```
MSAL 4.44.0.0 MSAL.Desktop 4.7.2 Windows Server 2019 Datacenter [2022-07-18 23:20:47Z - cb11a15f-f946-42f0-9167-4d0770207ff7]
System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

**Which version of MSAL.NET are you using?**
MSAL.NET 4.44.0.0

**Platform**
.NET Framework 4.6.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [x] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
We are also ruling out other potential root causes

**Is this a new or existing app?**

**Repro**
The app is in production, started seeing issues after upgrading part of production, only servers with new version experience latency increase, and only a small number of requests.

This is how we use MSAL:

```csharp
var applicationOptions = new ConfidentialClientApplicationOptions
{
    ClientId = clientid,
    ClientName = clientName,
    LegacyCacheCompatibilityEnabled = false,
    EnableCacheSynchronization = false,
};

var client = ConfidentialClientApplicationBuilder
                .CreateWithApplicationOptions(applicationOptions)
                .WithAuthority(authority)
                .WithLogging(MsalClientLogger, logLevel: LogLevel.Warning, enablePiiLogging: true)
                .WithCertificate(certificate, sendX5C: true)
                .WithAzureRegion(azureRegion)
                .Build();

client.AddInMemoryTokenCache(services =>
{
    services.Configure<MemoryCacheOptions>(options =>
    {
        options.SizeLimit = cacheSizeLimitInMb * 1024 * 1024;
    });
});

client
    .AcquireTokenOnBehalfOf(scopes)
    .WithCorrelationId(correlationId)
    .WithTenantId(tenantId).ExecuteAsync(cancellationToken)
```

**Expected behavior**
Call finishes within normal 1-2s threshold

**Actual behavior**
Call stalls for 5s or more

**Additional Context**
We are in the process of testing the current payload without the MSAL upgrade to rule out other possible issues.

**Comment by jmprieur** [comment]
@pmaytak @bgavrilMS : could that be a threading issue?

**Comment by bgavrilMS** [comment]
@mezaugusto - is it possible to fetch some verbose logs for when the call takes ~5s? Please email the logs if needed (bogavril at microsoft.com)

What sort of load are you looking at and how many users call the API before the slowdown takes place?

**Comment by pmaytak** [comment]
+1 logs will help and knowing if it's only in 4.44 can help narrow it down.

Meanwhile: between 4.42. and 4.44, I don't see any changes that would directly contribute to requests hanging up, but maybe regression in some related ones:
- #3313
- #3295

**Comment by pmaytak** [comment]
Closing this issue as there's no direct work on MSAL side.
Linking issues for further related improvements:
- Replace HTTP client implementation for .NET Framework targets with the .NET Core implementation.
  - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2867
- Update logging guidance to showcase best practices and how to dynamically change log level.
  - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3557
- Verify exception handling documentation is clear and contains necessary information. 
  - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3562
- Ensure that timeout and HTTP exceptions are captured by telemetry.
  - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3547
- Review all reliability recommendations and publish them to docs.ms (currently on our public wiki). 
   - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3563
- Enhance default retry policy and update guidance.
  - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3561
- Block MSAL release if performance test results indicate a regression.
  - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3564
- Implement a telemetry-based feedback loop that detects suboptimal use of MSAL.
  - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3565
