### ISSUE TITLE
[Feature Request] MSALRuntime now exposes loginHint for SignInAsync API

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3520]
**Is your feature request related to a problem? Please describe.**
MSALRuntime now exposes loginHint for SignInAsync API. 

**Describe the solution you'd like**
See if this will benefit MSAL broker implementation. Currently we use SignInAsync only for the default OS account. 

**Describe alternatives you've considered**
n/a

**Additional context**
Add accountHint in SignIn interface [#2983](https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/2983/files)

**Comment by bgavrilMS** [comment]
Let's do this work as part of the bigger "login hint" fix .
