### ISSUE TITLE
[Feature Request] Set specific versioning for Native Interop

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3524]
**Is your feature request related to a problem? Please describe.**
Set specific versioning for Native Interop on the broker project

**Describe the solution you'd like**
<PackageReference Include="Microsoft.Identity.Client.NativeInterop" Version="[0.10.1]" />

as defined [here](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges)

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by bgavrilMS** [comment]
What do you mean by strict versioning?

**Comment by gladjohn** [comment]
> What do you mean by strict versioning?

updated to specific version, so we can set an exact interop version until we finalize on the MSALRuntime WAM

**Comment by bgavrilMS** [comment]
Isn't this what is happening now? Microsoft.idenitity.Client.Broker depends on 
![image](https://user-images.githubusercontent.com/12273384/181540202-7d970ccc-31ea-4db2-98bc-66c39c2cfa61.png)

This is an exact version. 

And on: 

![image](https://user-images.githubusercontent.com/12273384/181542314-d1dfcc93-8557-444b-b24c-f80fab212f26.png)


msbuild / nuget will take care to transfor the project reference into a package reference with exact version semantic, when you the CI executes the "pack" command.

**Comment by gladjohn** [comment]
Currently the package reference is listed as >= Native Interop Version

![image](https://user-images.githubusercontent.com/90415114/181581466-20394610-6503-4dc8-a3da-e19030e1f3e6.png)

We want to it to be = A specific Native Interop Version 

![image](https://user-images.githubusercontent.com/90415114/181582001-4c51b552-1fc4-4fab-88d0-892466b1b2f5.png)

by specifying 

![image](https://user-images.githubusercontent.com/90415114/181581759-331dfc09-3a4b-4968-a207-dc4e68c708ed.png)

**Comment by gladjohn** [comment]
Hopefully the newer versions of interop does not but VS integrated with 0.8.0 and if with a private release they did see some issues. We can close this for now and revisit if needed.
