### ISSUE TITLE
[Bug] Error "The refresh token has expired due to inactivity" even after calling AcquireTokenInteractive

### ISSUE THREAD

**Issue by dimustriz** [AzureAD/microsoft-authentication-library-for-dotnet#3525]
**Logs and network traces**
Microsoft.Identity.Client.MsalUiRequiredException AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-08-23T18:32:11.4208496Z and was inactive for 90.00:00:00. Trace ID: 206f7d66-e3ff-4627-bd6e-03abca4bec00 Correlation ID: 72d6d58f-92df-4eb2-8ad0-a73c65d71d5c Timestamp: 2022-04-27 18:54:21Z at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException (Microsoft.Identity.Client.Http.HttpResponse response, Microsoft.Identity.Client.Internal.RequestContext requestContext) <0x102990570 + 0x00308> in <b1b1858c130d4f3884734339a9eb3ae8#73df98c5f57e8ef5e1969027a5439288>:0 at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T] (Microsoft.Identity.Client.Http.HttpResponse response, Microsoft.Identity.Client.Internal.RequestContext requestContext) <0x1029904f0 + 0x00037> in <b1b1858c130d4f3884734339a9eb3ae8#73df98c5f57e8ef5e1969027a5439288>:0 at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T] (System.Uri endPoint, Sys Code: -2146233088

**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.28.1

**Platform**
Xamarin Android, Xamarin iOS

**What authentication flow has the issue?**
* Mobile
    * [ ] Interactive

**Is this a new or existing app?**
The app is in production.

**Repro**

Preconditions:
- A mobile app has an App registration at Azure.
- The mobile app uses Azure AD to login.

Steps to reproduce:
1. Login to the Azure AD with some credentials.
2. Don't use the app for a long time (more than 90 days). 
3. Try to login.

**Expected behavior**
The app should login.

**Actual behavior**
The app gets following error:
-----
AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-08-23T18:41:19.5131275Z and was inactive for 90.00:00:00. 
-----
Any king of logout or explicit (instead of silent one) login doesn't help.

**Possible solution**
The Azure AD has to allow user to login using UI interaction.

**Comment by gladjohn** [comment]
MSAL cannot silently authenticate and user interaction is required. The error message tells you why the interaction is required. 

Your app is supposed to catch the MsalUiRequiredException exception and call AcquireTokenInteractive.

**Comment by dimustriz** [comment]
Yes, the message is clear. But AcquireTokenInteractive does'n help and leads to the same error.

**Comment by bgavrilMS** [comment]
This is very strange, AcquireTokenInteractiev gets a new pair of (access token, refresh token), it does not use the refresh token at all. 

Do you see the browser at all?

**Comment by dimustriz** [comment]
Yes, the user can see UI interaction, he enters his creds, and then the exception occurs again.

Please find the code snippet below. AuthService here is a wrapper which calls corresponded API methods. 
![image](https://user-images.githubusercontent.com/15669814/181443434-268a32a8-a159-40b1-95ea-db2fd0d131af.png)

I tried to clear token cache (https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-clear-token-cache) but it doesn't help.

**Comment by bgavrilMS** [comment]
I cannot find the server logs because the exception is too old. Do you have a newer one? (see the correlation id and timestamp), <30 days?

Is it possible to get the MSAL verbose logs https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging ?

**Comment by dimustriz** [comment]
I modified the app to add the PII to logs as requested, and as a part of this modification our middleware (which covers the MSAL) was upgraded. The app was provided to end user and he just reported that he was able to successfully log in. 

I am not sure what the issue cause was exactly and where it was fixed but anyway we can say that we unable to reproduce it now.

Thank you for your support.

**Comment by bgavrilMS** [comment]
Thanks for following up @dimustriz
