### ISSUE TITLE
[Engineering Task] Enable OneBranch to Build MAUI

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3526]

**Comment by SameerK-MSFT** [comment]
MAUI requires VS2022. It is not available on OneBranch pipeline. Installing the required software takes lot of time with trial and error. Maui will be released as preview from the old pipeline till OneBranch supports VS2022.

**Comment by gladjohn** [comment]
work completed
