### ISSUE TITLE
[Feature Request] WAM Authentication Library Should Support .NET 4.5 for Back Compatibility

### ISSUE THREAD

**Issue by lacomc** [AzureAD/microsoft-authentication-library-for-dotnet#3539]
**Is your feature request related to a problem? Please describe.**
Previous versions of the library supported older versions of .NET Framework, but newer ones that target NET Standard 2.0 do not. On the other hand, previous versions are not compatible with programs running as elevated processes (see [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2560)). While the newer library has fixed this issue, there is a gap where there is no way for those stuck on older versions of .NET Framework to successfully use WAM in apps that need to run as elevated processes.

**Describe the solution you'd like**
A version of the WAM library that supports running as an elevated process from a .NET Framework 4.5 application.

**Describe alternatives you've considered**
- Upgrading our application to a newer version of .NET - We've discussed this, but leadership is very hesitant to break back compatibility, meaning this is not a viable short-term option for us.
- Creating separate executables, one which targets .NET 4.5 (required for back compat) and one that targets a newer .NET version that is compatible with the newer WAM libraries. This is cumbersome and hacky, so not an ideal solution.
- Cloning the WAM library and re-targeting it ourselves to allow us to use it in our NET 4.5 app. This would likely create more work for both us and the windows auth library team because we would need to maintain code that we don't fully understand and would likely end up needing support from the auth library team.

**Additional context**
We started the conversation around this already with @bgavrilMS and @gladjohn, who said they believe this is doable.

**Comment by gladjohn** [comment]
Hi @lacomc please test the private drop @bgavrilMS provided and let us know if that works for you.
