### ISSUE TITLE
[Bug]  Login window in the background 

### ISSUE THREAD

**Issue by yonatanbk** [AzureAD/microsoft-authentication-library-for-dotnet#3542]
**Which version of MSAL.NET are you using?**

**Platform**
.NET Framework 4.7.2
**What authentication flow has the issue?**
* Desktop / Mobile
    * [V ] Interactive

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**
A windows background service that call a console app which call `AcquireTokenInteractive(scopes .WithPrompt(Prompt.SelectAccount)`
The triggering to acquiring the token is done by some async event 

**Expected behavior**
The login window should be opened in a new window with icon the task bar as the top mostwindow . 

**Actual behavior**
1. If not using `.WithParentActivityOrWindow(GetForegroundWindow())` then the login window is opened in the background and there is  icon on the task bar (because it's opened in the background the user misses that he should log in):
![image](https://user-images.githubusercontent.com/73930834/182019040-a6c447da-7839-466e-a88d-5be5128f37c6.png)

2. If we add `.WithParentActivityOrWindow(GetForegroundWindow())` to the code then the login window is opened in the top most window but there is no icon in the task bar and the user may lose track where he should login

**Possible solution**
Create a new icon in the task bar for the login window if using WithParentActivityOrWindow(...)

**Comment by yonatanbk** [comment]
Hi, is there any update?

**Comment by bgavrilMS** [comment]
@jmprieur - any suggestion on how to proceed with this public client request? The scenario is legitimate - it is about making the embedded browser show a dialog. AFAIK, WAM does not support this.

**Comment by bgavrilMS** [comment]
We are going full in on using WAM on Windows. As such, we will not be making changes to webview scenarios.
