### ISSUE TITLE
[Bug] Provide better HttpClient factory on .NET fwk (use the factory from .NET Core)

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3546]
Looks like the .NET fwk factory is throwing a lot of timeout errors: 

![image](https://user-images.githubusercontent.com/12273384/182413201-3eaab18f-a3af-42c7-8f30-cdea832f88a2.png)

Suggested fix: use .NET Core's factory on .net

**Comment by jmprieur** [comment]
amazing!
Do we know if the .NET Core would throw less?

**Comment by bgavrilMS** [comment]
Btw, I updated the query to also print out occurrences of this error in IdWeb. And there aren't any. Well done @jennyf19 and @jmprieur

**Comment by pmaytak** [comment]
More details sent via email, but in general: there seems to be 2.2x fewer errors with the updated Http client on Msal.Desktop.
