### ISSUE TITLE
[Feature Request] Request to support Signup/MSAL New Account Creation via Prompt.Create option

### ISSUE THREAD

**Issue by ssanghami** [AzureAD/microsoft-authentication-library-for-dotnet#3552]
**Is your feature request related to a problem? Please describe.**
Ours is Microsoft Defender Consumer Security Windows Store App using WPF/UWP. we are using the MSAL login window for allowing users to log in using Microsoft Account.
As part of the new feature request, we want users to be able to directly create a new account from our app flow. Currently, users can create a new account after clicking the create new account option shown in the MSAL dialog, but we want to be able to bring users directly to this Create new account MSAL page.
which is not working when I tried the below code statement, it always shows the signin window instead of signup.

await s_clientApp.AcquireTokenInteractive(MicrosoftSecurityScope)
                        .WithParentActivityOrWindow(parentWindow)
                        .WithPrompt**(Prompt.Create)**
                        .ExecuteAsync();
 

**Describe the solution you'd like**
Please provide support for (Prompt.Create) or signup flow from our app directly in MSAL.

**Describe alternatives you've considered**
We have to de-prioritize our feature ask as its not available still.
**Additional context**
we want to reach to this page directly,
![image](https://user-images.githubusercontent.com/12921059/182462396-22ee1a95-69a3-494c-9546-11340d03db4b.png)

**Comment by pmaytak** [comment]
@ssanghami  This feature ([Prompt.Create](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-interactive?tabs=dotnet#withprompt)) is only for [External Identities](https://docs.microsoft.com/en-us/azure/active-directory/external-identities/external-identities-overview). Was this enabled in your tenant as described [here](https://aka.ms/msal-net-prompt-create)?

**Comment by ssanghami** [comment]
Ours is a first party app, as I read from the existing documentation the
signup feature is only supported for B2C mode apps.

Regards
Sam

**Comment by bgavrilMS** [comment]
@ssanghami "first party app" meaning 1st party portal? This means that you target AAD authority, i.e. Work and School accounts and Microsoft personal accounts (outlook.com, live.com, hotmail.com). 

B2C is a different authority.

**Comment by ssanghami** [comment]
Yes, its a first party app using microsoft internal 1st party app portal,
enabled for MSA authentication.

I did not see where to configure the flow we are looking for as mentioned
in the signup documentation.

I see the issue is being closed as answered,  but I got no conclusion from
it.

Regards
Sanghamitra

**Comment by pmaytak** [comment]
@ssanghami My understanding is External Identities is a feature only in AAD, not in B2C, but it is created to specifically work like B2C. I suggest to contact First Party team to clarify if it's available for First Party Apps and how to configure it.
