### ISSUE TITLE
[Bug] Microsoft.Identity.Client.desktop - Dependency loop detected

### ISSUE THREAD

**Issue by MikeJungerKB** [AzureAD/microsoft-authentication-library-for-dotnet#3554]
Hello,

I use powershell to install this package on a WIndows Server 2019
Install-Package Microsoft.Identity.Client.desktop -ProviderName NuGet

But I get the error
Install-Package : Dependency loop detected for package 'Microsoft.Identity.Client.Desktop'.
At line:1 char:1
+ Install-Package Microsoft.Identity.Client.desktop -ProviderName NuGet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Deadlock detected: (Microsoft.Identity.Client.Desktop:String) [Install-Package], Excepti
   on
    + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

If you need any logging, please tell me how to get them.

Many Thanks

**Comment by bgavrilMS** [comment]
Not sure how to help here, we don't offer explicit PowerShell support, we only rely on the fact that the .NET and packages should work on PowerShell. 

In any case, I recommend not using `Microsoft.Identity.Client.Desktop` for now, but instead using the newer WAM experience from here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam#new-wam-preview-in-msal-444

This is a different package, so hopefully the error will go away.
