### ISSUE TITLE
[Feature Request] Update logging guidance

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3557]
**Is your feature request related to a problem? Please describe.**
We recently added support for the IIdentityLogger and explained how one can use an environment variable in their code to change the log level without recompiling. This works for public clients, but confidential clients will have an issue since you need to restart the machine to get the updated env variables and these clients typically run in data centers and restarting the machine can be tricky or remove the reproduction of the issue all together.

**Describe the solution you'd like**
Integrate Microsoft.Extensions.Logging and  Microsoft.Extensions.Configuration into our documentation to show how developers may be able to use a configuration file to change the log level on while the service is still running. 

**Additional context**
https://www.nuget.org/packages/Microsoft.Extensions.Logging/7.0.0-preview.6.22324.4
https://www.nuget.org/packages/Microsoft.Extensions.Configuration/7.0.0-preview.6.22324.4

**Comment by pmaytak** [comment]
The MS Docs for logging is here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-dotnet?tabs=dotnet
I also think the aka.ms/msal-net-logging needs to be changed to point to the MS docs and not our wiki.
