### ISSUE TITLE
[Feature Request] Add MAUI support to 4.46

### ISSUE THREAD

**Issue by williamchenicon** [AzureAD/microsoft-authentication-library-for-dotnet#3559]
MAUI works with 4.46 preview version, but not work with 4.46. 

Please add it back.  
Thanks,

**Comment by Gurgen** [comment]
Is it working in preview version? I tried from nuget 4.46.0-preview2, getting `Xamarin.Shared.Sdk.targets(1197, 3): clang++ exited with code 1` error

**Comment by williamchenicon** [comment]
It is working for MAUI.

**Comment by bgavrilMS** [comment]
Let's continue to track MAUI support on the main issue here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3127

Only preview versions will have MAUI support until we are able to stabilize it. Please see status in the main post.
