### ISSUE TITLE
Review reliability recommendations and publish to docs.ms

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3563]
Existing doc: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability

**Comment by pmaytak** [comment]
Also relevant docs that need review:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Exceptions
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-error-handling-dotnet

**Comment by localden** [comment]
Closing as this is covered in [High Availability](https://learn.microsoft.com/entra/msal/dotnet/advanced/high-availability). We can make incremental improvements to the doc there now.
