### ISSUE TITLE
Can MSAL.NET exception messages contain sensitive data?

### ISSUE THREAD

**Issue by nickmqb** [AzureAD/microsoft-authentication-library-for-dotnet#3576]
We are using MSAL.NET in a web app. The web app logs all (unhandled) exceptions. This potentially includes exceptions from MSAL.

We'd like to avoid logging any sensitive data such as access/refresh tokens.

Is it safe to assume that any exceptions thrown by MSAL will never contain such information?

**Comment by jmprieur** [comment]
@nickmqb : yes, there are options to show PII, that are disabled by default. 
See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#personal-identifiable-information-pii--organizational-identifiable-information-oii

**Comment by jmprieur** [comment]
Closing as answered

**Comment by nickmqb** [comment]
I'm still a bit confused. The linked paragraph refers to logging, not exceptions ("By default, MSAL.NET **logging** does not capture or log any PII or OII".)

We are not using MSAL's logging features, nor are we setting any logging options.

Instead we are capturing exception messages (with our own logger) which may include any exception messages originating from within MSAL.

So I was wondering about those exception messages specifically, whether they may contain sensitive data?

**Comment by bgavrilMS** [comment]
@nickmqb - today none of our exception messages contain PII, but to be on the safe side I'd say that you should treat MsalException messages as potentially containing PII. Our logger is implemented like that. Sadly, supportability suffers, it's difficult for us to diagnose issues without exception message.

Do you treat general .NET exceptions as having PII? If an exception occurs in say the HTTP Client...

We recommend that you do add a logger and that you log at least Warning level messages and provide dynamic way to change verbosity and PII bool.

**Comment by nickmqb** [comment]
That's a good point about general .NET exceptions. Generally, in our case we're OK with logging certain types of PII (e.g. a user ID). However, we want to be careful about more sensitive subtypes of PII (e.g. access/refresh tokens) and avoid logging those, hence the reason for "zooming in" on MSAL a bit more. Would MSAL be able to provide a weaker guarantee here, i.e. exception messages not containing OAuth access/refresh tokens? I'm wondering about any exceptions originating from within MSAL, so potentially not just MsalServiceException/MsalClientException instances.

**Comment by bgavrilMS** [comment]
@nickmqb - MSAL will not log tokens, not even when PII is enabled. That's a big no-no for all MSAL libraries.

**Comment by nickmqb** [comment]
OK, thanks for your help.
