### ISSUE TITLE
Getting MSAL to work with Microsoft.Data.SqlClient to create an azure database on sql server

### ISSUE THREAD

**Issue by dgxhubbard** [AzureAD/microsoft-authentication-library-for-dotnet#3577]
We have a desktop app our customers purchase, and some customers want to access azure while running azure ad. We use a DbConnectionInterceptor to determine if azure is used and get the access token. This code is put together from the [WPF app example](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-windows-desktop).  What should the Authentication setting be, for Microsoft.Data.SqlClient connection string, is my first question. Next why does this have an error with the connection string:

`Data Source=tcp:foo.database.windows.net,1433;Pooling=True;Authentication=ActiveDirectoryIntegrated`

We are not setting a password.

![image](https://user-images.githubusercontent.com/5032382/183533926-f2b554c5-512c-4155-a8d8-cd67e1c23d15.png)

![image](https://user-images.githubusercontent.com/5032382/183533990-114d3787-e437-4eec-8c43-a85298fe4343.png)

Our code not event make it to our DbConnectionInterceptor.

`    public class AzureAdDbConnectorInterceptor : DbConnectionInterceptor
    {
        private static string ClientId = "c32c25e9-2f19-4171-ad22-83e969f65e57";

        private static string Tenant = "common";

        private static IPublicClientApplication _clientApp;

        public static IPublicClientApplication PublicClientApp { get { return _clientApp; } }

        static AzureAdDbConnectorInterceptor ()
        {
            _clientApp = PublicClientApplicationBuilder.Create ( ClientId )
                        .WithAuthority ( AzureCloudInstance.AzurePublic, Tenant )
                        .WithDefaultRedirectUri ()
                        .Build ();
        }

        public override InterceptionResult ConnectionOpening (
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result )
        {
            
            var sqlConnection = ( SqlConnection ) connection;
            if ( DoesConnectionNeedAccessToken ( sqlConnection ) )
            {
                sqlConnection.AccessToken = GetAuthenticationToken ();
            }

            return base.ConnectionOpening ( connection, eventData, result );
        }

        public override async ValueTask<InterceptionResult> ConnectionOpeningAsync (
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result,
            CancellationToken cancellationToken = default )
        {
            var sqlConnection = ( SqlConnection ) connection;
            if ( DoesConnectionNeedAccessToken ( sqlConnection ) )
            {

                sqlConnection.AccessToken = GetAuthenticationToken ();
            }

            return await base.ConnectionOpeningAsync ( connection, eventData, result, cancellationToken );
        }

        private static bool DoesConnectionNeedAccessToken ( SqlConnection connection )
        {
            var connectionStringBuilder = new SqlConnectionStringBuilder ( connection.ConnectionString );

            var dataSource = connectionStringBuilder.DataSource;

            var contains = false;

            if ( dataSource.Contains ( MsSqlConstants.AzureUrl, StringComparison.OrdinalIgnoreCase ) )
                contains = true;

            return contains;
                
                //&& string.IsNullOrEmpty ( connectionStringBuilder.UserID );
        }

        public string ResultText
        { get; set; }

        private string GetAuthenticationToken ()
        {
            AuthenticationResult authResult = null;

            var scopes = new List<string> () { "user.read", "user.write" };

            var accountResult = _clientApp.GetAccountsAsync ();
            accountResult.Wait ();

            var firstAccount = accountResult.Result.FirstOrDefault ();

            try
            {
                Task<AuthenticationResult> result = _clientApp.AcquireTokenSilent ( scopes, firstAccount ).ExecuteAsync ();

                result.Wait ();

                authResult = result.Result;

            }
            catch ( MsalUiRequiredException ex )
            {
                // A MsalUiRequiredException happened on AcquireTokenSilent.
                // This indicates you need to call AcquireTokenInteractive to acquire a token
                System.Diagnostics.Debug.WriteLine ( $"MsalUiRequiredException: {ex.Message}" );

                try
                {
                    Task<AuthenticationResult> result = 
                        _clientApp.AcquireTokenInteractive ( scopes ).
                            WithUseEmbeddedWebView ( true ).
                            ExecuteAsync ();

                    result.Wait ();

                    authResult = result.Result;

                }
                catch ( MsalException msalex )
                {
                    ResultText = $"Error Acquiring Token:{System.Environment.NewLine}{msalex}";
                }
            }
            catch ( Exception ex )
            {
                ResultText = $"Error Acquiring Token Silently:{System.Environment.NewLine}{ex}";

            }

            if ( authResult != null )
                return authResult.AccessToken;
            else
                return null;

        }
    }
`

**Comment by jmprieur** [comment]
@dgxhubbard the resource you asked tokens for is Microsoft Graph (user.read / user.write is to read/write the user profile).

I'm confused about what you are trying to do:
- Which resource do you want to get access to? is it Azure SQL?
- Do you have any pointer on the doc you used for DbConnectionInterceptors?
- Did you see this doc?
  https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#example-connection-interception-for-sql-azure-authentication-using-aad

  It seems the scopes to use would rather be "https://database.windows.net//.default" ?

- Did you try to use an AzureDatabaseProvider?

**Comment by MichelZ** [comment]
Try removing `Authentication=ActiveDirectoryIntegrated` from your connection string when you use an access token.

**Comment by bgavrilMS** [comment]
Please reach out to SQL Client folks first. We can help with specific auth issues / auth errors, but not with SQL Client issues.

**Comment by dgxhubbard** [comment]
@jmprieur  the db interceptor comes from [here](https://devblogs.microsoft.com/azure-sdk/azure-identity-with-sql-graph-ef/), but it is using Azure.Identity, which I cannot get working. I tried MSAL, because Azure.Identity was trying to get credentials from vs 2022, which I did not [request](https://github.com/Azure/azure-sdk-for-net/issues/30397). Then I tried to get azure working using MSAL. I will try the scope and see what that does. I have not found any good examples to create an azure database with credentials. Even the authentication setting in the connection string is a [guess](https://github.com/dotnet/SqlClient/issues/1697).

**Comment by dgxhubbard** [comment]
@MichelZ I will try try removing the connection string authentication setting, and see what that does. I thought from Microsoft.Data.SqlClient that the setting was needed for azure.

**Comment by dgxhubbard** [comment]
@jmprieur  setting the scope and @MichelZ  removing the Authentication setting go me into the db interceptor. In the db interceptor, I try and get a token, in GetAuthenticationToken, but using 

`
 var accountResult = _clientApp.GetAccountsAsync ();
 accountResult.Wait ();

  var firstAccount = accountResult.Result.FirstOrDefault ();
`

returns null. How do I get the logged in users azure ad information to get the access token?
