### ISSUE TITLE
[Bug]  WithProofOfPossessionKeyId(tokenAcquisitionOptions.PopPublicKey) needs to be available on all flows

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#3598]
WithProofOfPossessionKeyId(tokenAcquisitionOptions.PopPublicKey) is only available on the client credentials flow, but needs to be enabled on OBO and AT silent as well. This is a pre-requisite for support in Id Web of PoP tokens without the signed HTTP request.

**Comment by bgavrilMS** [comment]
MSAuth1.0ATPOP was not defined outside client_credentials flow. SAL only supports a flavour of OBO, it is not being used conjunction with POP.

**Comment by bgavrilMS** [comment]
We'll hold any release until this gets fixed @jennyf19, I'll update you on this asap.

**Comment by jmprieur** [comment]
@bgavrilMS : the point is SAL needs to get a token with a kid. That's all. It will then mint tokens with this as payload depending on the protocols.

If we request such a payload token from Auth Code flow, Acquire token silent (it web apps), or OBO won't it work?
