### ISSUE TITLE
[Bug] Script error “Object doesn’t support property or method ‘isInteger’” appears when trying to sign in.

### ISSUE THREAD

**Issue by liulinakateryna** [AzureAD/microsoft-authentication-library-for-dotnet#3603]
**Description**
We are using the *Microsoft.Identity.Client* nuget package for user authentication in our WPF desktop client. The actual problem is that the script error *"Object doesn’t support property or method ‘isInteger’"* appears during sign-in.

**Which version of MSAL.NET are you using?**
Tried both versions 4.36.1 and 4.46.0.

**Platform**
.NET Framework 4.6.1

**Steps to reproduce**
1.	Open “Sign in to your account” window and enter your password.
2.	Click “Sign in” button (user is navigated to the “Help us protect your account” page).
<img width="424" alt="1" src="https://user-images.githubusercontent.com/34003994/184616019-a70335ad-e757-4b7a-a288-bd173bfb42b9.png">

3.	Click “Next” button on “Help us protect your account” page.
<img width="422" alt="2" src="https://user-images.githubusercontent.com/34003994/184615889-5129ead2-3552-4b8a-a338-c024c2bac81c.png">

**Expected behavior**
The user should be asked to install Microsoft Authenticator and be able to setup MFA.

**Actual behavior**
The script error *“Object doesn’t support property or method ‘isInteger’”* appears (see the screenshot below). The error is thrown in [main.486a7dba.js](https://mysignins.microsoft.com/bundle/main.486a7dba.js).
<img width="424" alt="3" src="https://user-images.githubusercontent.com/34003994/184615715-c0536653-a878-48d4-abab-4d8425dedea6.png">

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL (current version 4.36.1), but started seeing this issue.

**Repro**

```csharp
IPublicClientApplication publicClientApplication = PublicClientApplicationBuilder
	.Create(someClientId)
	.WithRedirectUri("msal{ClientId}://auth")
	.Build(); 
	
AcquireTokenInteractiveParameterBuilder builder = publicClientApplication
	.AcquireTokenInteractive(new string[] { "user.read" })
	.WithPrompt(Prompt.ForceLogin)
	.WithLoginHint(someEmail);

AuthenticationResult authenticationResult = await builder.ExecuteAsync();
```

**Comment by bgavrilMS** [comment]
The behavior of the browser is driven by AAD (the service), not by the SDK. It looks like they have introduced a regression :(. I recommend that you open a ticket via the Azure Portal. Having a Fiddler trace, which should the correlation ID + timestamp would be very helpful.

**Comment by lukeskinner** [comment]
I'm also having the same issues with this, I've spent a lot of time trying to see if I can override the web browser to be WebView2 but have not had much success so far. After finding this item I have raised a ticket in the Azure Portal (with fiddler trace + IDs + timestamp).

I found a "SetIWin32WindowFunc" method on the SqlAuthenticationProvider class in this library but I was unable to get it to play ball with lots of errors about cross-threads. I'll update on here what comes from the Azure ticket.

**Comment by bgavrilMS** [comment]
The solution here is to use WAM: https://aka.ms/msal-net-wam for AAD accounts. 
For B2C accounts, Microsoft.Identity.Client.Desktop has WebView2 support.

**Comment by lukeskinner** [comment]
Thanks for the heads up about WAM, I'm using Microsoft.Data.SqlClient which uses this library as a dependency so I don't have easy access to the classes such as 'PublicClientApplicationBuilder'. I appreciate that's not what this github repo is but the scenario is exactly the same on the initial reported issue to mine except mine is via SqlConnection (azure ad auth).
I'll do some more research around WAM just in case

**Comment by bgavrilMS** [comment]
Another way of handling this is to force the embedded browser to user newer version of IE. There is a registry property and enable IE11 emulation on the internal browser: 

This is for ssms.exe, but you can replace with your app:

`
New-ItemProperty -path 'HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION' -name 'Ssms.exe' -value '11000' -PropertyType 'DWord'
`
 You might have to do it for Powershell.exe / Powershell_ISE.exe were added as well.

**Comment by bgavrilMS** [comment]
Cl,osing as external.
