### ISSUE TITLE
MAUI iOS crashes when the app reaches Apple app store[Bug] 

### ISSUE THREAD

**Issue by JawadJaber** [AzureAD/microsoft-authentication-library-for-dotnet#3617]
**Logs and network traces**
https://1drv.ms/u/s!AsZPe-3ZmkfLgZZ2yN-7et3pKNQzGA?e=z0n7LA
EOF

**Which version of MSAL.NET are you using?**
Ex: MSAL.NET 4.46.0-preview2 

**Platform**
MAUI iOS

**What authentication flow has the issue?**
* Mobile
    * [x] Interactive
    * [x] Username Password

Other?
I am using MSAL properly on my ios devices and ios simulators whenever I build the project directly from visual studio 2022. However, when the app is published to the app store (TestFlight internal users or external users). then the app crashes and the above report is available in my Xcode.

**Is this a new or existing app?**
new app

**Comment by bgavrilMS** [comment]
@SameerK-MSFT - this looks serious, can you please take a look?

**Comment by bgavrilMS** [comment]
I can't see anything related to MSAL in there, is auth started automatically /

**Comment by JawadJaber** [comment]
I now can confirm this is not Msal issue, but it is MAUI bug for sure.

**Comment by bgavrilMS** [comment]
Thanks @JawadJaber for confirmation.
