### ISSUE TITLE
[Bug] AuthenticationContinuationHelper class not found in AppDelegate.cs after updating to 4.46.1 in MAUI

### ISSUE THREAD

**Issue by NiladriPadhy** [AzureAD/microsoft-authentication-library-for-dotnet#3620]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).
AuthenticationContinuationHelper class not found in AppDelegate.cs after updating to 4.46.1

**Which version of MSAL.NET are you using?**

4.46.1
**Platform**

Xamarin ios
**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
a. The app is in dev, and I have upgraded to a new version of MSAL.
c. This is a new experiment in MAUI

**Comment by bgavrilMS** [comment]
We did not make MAUI public yet, so MSAL 4.46.1 does not have support for it. You app falls back to MSAL netstandard, which does not have this api. Please stay on the preview version.

**Comment by NiladriPadhy** [comment]
> We did not make MAUI public yet, so MSAL 4.46.1 does not have support for it. You app falls back to MSAL netstandard, which does not have this api. Please stay on the preview version.

@bgavrilMS Sure, Thanks a lot.
