### ISSUE TITLE
[Question] UserTokenCache and multiple ConfidentialClientApp instances

### ISSUE THREAD

**Issue by nickmqb** [AzureAD/microsoft-authentication-library-for-dotnet#3625]
Hi,

This is a question regarding MSAL's default in memory UserTokenCache, when there are multiple ConfidentialClientApp instances.

By default, does each app object have its own separate set of cached tokens? And can we rely on this always being the case in the future?

It seems like this is the case, but I couldn't find a doc that explicitly states this.

We are relying on tokens being strictly confined to a specific app instance for security purposes, so was hoping confirm our assumption.

Thanks!

**Comment by jmprieur** [comment]
@nickmqb 
you can have the token cache shared between instances. See
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet#token-cache-without-serialization

**Comment by nickmqb** [comment]
Thanks. So just to be 100% sure: if we don't specify .WithCacheOptions(), we get the non-shared behavior, and we can rely on this being the case in the future?

**Comment by jmprieur** [comment]
yes, @nickmqb

**Comment by nickmqb** [comment]
That's good to know. Thank you for your help.
