### ISSUE TITLE
 Getting MSAL to work to create an azure database on sql server [Bug] 

### ISSUE THREAD

**Issue by dgxhubbard** [AzureAD/microsoft-authentication-library-for-dotnet#3628]
Runnnin on windows 11 using version 4.46.1 of microsoft.identity.client, we are trying to create a database on an azure sql server using ef core 6 migrations. Using this [article](https://blogs.aaddevsup.xyz/2021/06/how-to-use-an-access-token-to-connect-to-an-azure-sql-database/) as our starting point we have not been able to create the database. We request a token, with a azure ad user who is an admin for the sql server, and we get the token, however when we call Migrate we get an error:

![image](https://user-images.githubusercontent.com/5032382/186728506-89b8071b-9879-4d9f-b616-b768950dbb4c.png)

We have tried to resolve the [issue](https://github.com/dotnet/SqlClient/issues/1697) with Microsoft.Data.SqlClient, but they feel this is an issue with MSAL. 

I am including this code sample that reproduces the issue. Our customers want to be able to use our software to create their database on azure, so our application must be a multi tenant app, any help you can provide would be appreciated.
[CoreWpf.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/9426925/CoreWpf.zip)

**Comment by bgavrilMS** [comment]
Hi @dgxhubbard - I see that the other issue is very long, can you please add a summary for it? Note that we don't know much  about SQL, so let's focus on authentication only. 

I looked at the code in the other issue, and functionally it is ok. You might want to serialize your token cache, otherwise when you restart the app `GetAccounts` will return 0 accounts. https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom 

So it looks like you are actually able to get a token no? Is this the wrong token or what is the problem?

**Comment by dgxhubbard** [comment]
I get a token, and then when I use it to create the database, there are a bunch of SqlExceptions and I get the message login failed for principal:

![image](https://user-images.githubusercontent.com/5032382/186949615-7f71ebb8-8416-4849-bfb1-8feb8b608b5d.png)

How can I get a token yet have the login fail? Unless the error message is useless, I am not sure what the problem is. I request the token for the azure sql server, and get the token back then set that in the SqlClient. I request the token using scope  "https://database.windows.net//.default".

**Comment by dgxhubbard** [comment]
@bgavrilMS Has there been anything on this issue. I have provided a sample app, so I don't know what else is needed to move this along

**Comment by bgavrilMS** [comment]
Not enough info to troubleshoot this issue. Please follow the bug template. 

If you get a token but the protected API refuses it, please open an issue on the team owning the protected API.
