### ISSUE TITLE
[Bug] PlatformNotSupported exception when running MAUI app in iOS Simulator using Azure B2C

### ISSUE THREAD

**Issue by madmapper** [AzureAD/microsoft-authentication-library-for-dotnet#3632]
**Logs and network traces**
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/5810614/186968219-46eb7242-7831-4309-80d6-5488b2d0cd6d.png">

**Which version of MSAL.NET are you using?**
4.46.1

**Platform**
.net MAUI

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
This is a new app or experiment.

**Repro**

```csharp
//PCA object created:
PCA = PublicClientApplicationBuilder
                .Create("ClientID")
                .WithIosKeychainSecurityGroup("com.microsoft.adalcache")
                .WithAuthority("https://login.microsoftonline.com/common")
                .WithRedirectUri("http://localhost")
                .WithExperimentalFeatures(true)
                .Build();

//interactive auth flow triggered
AuthenticationResult result = await App.PCA.AcquireTokenInteractive(Constants.Scopes)
                                .WithUseEmbeddedWebView(false)
                                .WithPrompt(Prompt.ForceLogin)
                                .ExecuteAsync()
                                .ConfigureAwait(false);
```

**Expected behavior**
Device opens web view for interactive auth session

**Actual behavior**
exception thrown

**Additional context / logs / screenshots / links to code**
Same flow is working with XF5 version of app.

**Comment by bgavrilMS** [comment]
Hi @madmapper - we don't have MAUI support in 4.46.1 yet. We are having some problems with our release pipeline, so we can only publish previews. 

Can you please use https://www.nuget.org/packages/Microsoft.Identity.Client/4.46.0-preview2 instead?

CC @SameerK-MSFT
