### ISSUE TITLE
[Bug] WithAuthority with AcquireTokenInteractive not working

### ISSUE THREAD

**Issue by shivam1305** [AzureAD/microsoft-authentication-library-for-dotnet#3634]
**Description**
When creating publicClientApp like this:
```
this.publicClientApp = PublicClientApplicationBuilder.Create(ClientId)
                .WithExperimentalFeatures()
                .WithRedirectUri(ClientRedirectUri)
                .WithBroker()
                .Build();
```
by default, set authority as common which we want. But later on, based on different scenarios we need to change the authority to consumer and show prompt to select personal account only.

We thought following code should work:

```
result = await publicClientApp.AcquireTokenInteractive(scopes)
                        .WithAuthority(AadAuthorityAudience.PersonalMicrosoftAccount)
                                .ExecuteAsync();
```

But, it is not working. It is not able to change the authority. So, it is not able to change the prompt to show only personal account.

**Which version of MSAL.NET are you using?**
MSAL.NET 4.24.0/4.46.0/4.47.0

**Platform**
UWP

**Expected behavior**
By default, we want this prompt:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/42907325/187042760-a1032949-855c-45bb-a702-5a58bd794ba7.png">
For some scenario, we want this prompt:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/42907325/187042828-074abae4-35fa-470b-a17a-6fbf216773fb.png">

**Actual behavior**
Can't change the prompt to:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/42907325/187042934-38ebf772-4a08-4952-b60a-1c141f08bdd7.png">

via following code:
```
result = await publicClientApp.AcquireTokenInteractive(scopes)
                        .WithAuthority(AadAuthorityAudience.PersonalMicrosoftAccount)
                                .ExecuteAsync();
```

**Possible solution**

**Additional context / logs / screenshots / links to code**

We are able to get prompt for personal account by setting authority while creating publicClientApp as follows:
```
this.publicClientApp = PublicClientApplicationBuilder.Create(ClientId)
                .WithExperimentalFeatures()
                .WithRedirectUri(ClientRedirectUri)
                .WithAuthority(AadAuthorityAudience.PersonalMicrosoftAccount)
                .WithBroker()
                .Build();
```

But, we need to change authority dynamically. Sometimes we need to show prompt for "common" and sometimes we need to show prompt for "consumer".

**Comment by bgavrilMS** [comment]
This is not a supported scenario. You can only switch from `common` or `organizations` to an actual tenant ID, e.g. `72f...`

Please use a new PublicClientApplication object for consumer-only auth.

Also, you can choose to create your `PublicClientApplication` on the fly every time, if it's simpler for you. That should work fine.
