### ISSUE TITLE
Using MSAL with AAD B2C client credentials endpoint

### ISSUE THREAD

**Issue by sven5** [AzureAD/microsoft-authentication-library-for-dotnet#3639]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.46

**Platform**
.NET Core (Blazor)

**What authentication flow has the issue?**
Client Credentials

**Is this a new or existing app?**
This is a new app or experiment.

**Expected behavior**
When using the client credentials flow endpoint for B2C we have to use the following endpoint:
https://myb2ctenant.b2clogin.com/myb2ctenant.onmicrosoft.com/<policy-name>/oauth2/v2.0/token

But this endpoint actually does not return `roles` claim - only `scp` (Scopes) are returned. Though, the MSAL does not correctly recognize application permissions. That means currently, MSAL cannot be used for this scenario. 
Is anyone aware of this limitation? What can we do around this?

**Actual behavior**
The OAuth token only returns `scp` and not `roles`. MSAL doesn't recognize these permissions.

**Possible solution**
MSAL should be adjusted to work with `scp` claims in B2C scenario.

**Comment by bgavrilMS** [comment]
Hi @sven5 - the claims included in the OAuth token are not controlled by MSAL. Are you saying that if you make the call with Postman you get a different token?

**Comment by sven5** [comment]
Hi @bgavrilMS 
you are right. MSAL is working correctly. One should be aware that für B2C you have to use `WithB2CAuthority()` extension.
But the token is returned correctly. 

It seems to be a peculiarity with B2C that it return `scp` instead of `roles`
