### ISSUE TITLE
[Bug] Keychain (IF YOU REMOVE Entitlements.plist from iOS Bundle Signing)

### ISSUE THREAD

**Issue by brdacon1** [AzureAD/microsoft-authentication-library-for-dotnet#3646]
The application cannot access the iOS keychain for the application publisher (the TeamId is null). This is needed to enable Single Sign On between applications of the same publisher. This is an iOS configuration issue. See https://aka.ms/msal-net-enable-keychain-access for more details on enabling keychain access. 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/62226456/187824836-77b776d3-39ec-471e-8b54-5773e0f3a148.png"<img width="573" alt="image" src="https://user-images.githubusercontent.com/62226456/187824957-aee87304-2bee-465a-80f5-1da93787367d.png">

**Comment by bgavrilMS** [comment]
Does this help? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3636

@sameerkapps - can we improve the user experience or the docs ?

**Comment by brdacon1** [comment]
If you select Entitlements.plist in iOS Bundle Signing you recived error for build. Follow: error : The specified iOS provisioning profile 'VS: WildCard Development' could not be found.
