### ISSUE TITLE
Error when trying to clone Azure Repo (Git) to local PC.

### ISSUE THREAD

**Issue by jossgc** [AzureAD/microsoft-authentication-library-for-dotnet#3652]
*Submitting this on behalf of my affected customer. Previous consent granted to share logs and information collected.*

I have a customer that is having issues when cloning his Azure Repo to his local PC, behavior persists when trying to clone the repo either from Git bash or Visual Studio with same behavior.
 
**Actual behavior**
Whenever affected user tries to clone any of his repositories the Credential Manager window pop-ups to login, it shows only the user account that he uses to login to his local computer (which is not the correct one), so he manually type in the correct account to login but still shows a permission error (see below) and lists the local account for his computer, which is not the account that is part of the Azure DevOps organization.

Same scenario experienced when trying to clone the Repo from Visual Studio, affected user is able to connect to the project, but at the moment he tries to clone the repo, he experience the same behavior.

The flow customer is experiencing:

1. Run git clone command
2. Identity picker shows up, it *only* shows customer's local PC account, which is not the account that he needs to use to perform operations over the repository.
3. Customer manually type in the correct account.
4. Shows error and pointing to wrong account (customer's local PC account).

**Error shown:**
$ git clone https://Qurate@dev.azure.com/Qurate/QRG-EDW/_git/EDW_Admins_DeltaLake
Cloning into 'EDW_Admins_DeltaLake'...
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
fatal: Failed to create PAT: TF401444: Please sign-in at least once as AAD Tenant ID\wrong local account in a web browser to enable access to the service.
fatal: Authentication failed for 'https://dev.azure.com/Qurate/QRG-EDW/_git/EDW_Admins_DeltaLake/

**Debugging done**
Log out from all visual studio sessions opened.
Close all visual Studio instances.
Go to the following locationS and clear up the content:
%localappdata%\microsoft\VisualStudio (for this, there can be multiple numbers, such as 12.0, 13.0, and so on. Please go for each one and delete the folder called: ComponentModelCache)
%localappdata%\microsoft\VSCommon
%localappdata%.identityservice (This will clean up the entire cache including AAD, session and account data)
%localappdata%/Microsoft/VisualStudio
%localappdata%/Microsoft/VisualStudio Services
After this please restart Visual Studio and try again.
**Result: issue persists**

we ran under the git bash command git --version to confirm we are on latest version, which we are (2.37.1)
-we checked user's permissions within DevOps (organization's permission, project's permission, repo's permission and Project Administrator's permissions), all in place and good.
-cleaned .IdentityService folder again: C:\Users<username>\AppData\Local.IdentityService
-Went back to git bash and try again to clone the repo: issue persists.
-we confirmed VS version: VS 2019 16.11.17
-we look up for the following path: [file:///C:/Program%20Files/Git/mingw64/share/doc/git-doc/git-credential.html](https://onesupport.crm.dynamics.com/_imgs/loading.gif#) with this will be skip clone process and we will go straight to credential part.
-On git bash we ran the following, issue persists:
git credential fill
protocol=https
host=dev.azure.com
path=

-tried again but adding extra property username and trying with capital letters as per UPN (to disregard if it is an issue with case sensitive), issue persists:
git credential fill
protocol=https
host=dev.azure.com
path=
Username=

-affected user confirmed he is using a VPN but another user has the same error and there is another user that don't. Access to Azure DevOps Portal works perfectly, and from VS he is able to connect to Projects, issue begins when he tried to clone the repo.
-we tried to add the required account directly to the credential manager and try to clone again from git bash: issue persists.
-restarted git bash: issue persists.
-deleted manual entry of the account on Credential Manager.

Another thing we noticed is that if we go to Control Panel > Credential Manager > Windows Credential > There isn't any credential stored there, nor for Git or Visual Studio.

We recently worked with GCM over [this issue](https://github.com/GitCredentialManager/git-credential-manager/issues/850) team trying to troubleshoot, they were able to identify that there is a specific portion of [this call](https://github.com/GitCredentialManager/git-credential-manager/blob/2a077a874b32d987cd4849b17adca96b413ad57a/src/shared/Core/Authentication/MicrosoftAuthentication.cs#L178-L186) that it is affecting login process and they redirected us to you guys.

**Ask**
Can you please take a look on this issue and help us troubleshoot/resolve it? Any help or insight will be highly appreciated.
Latest git traces collected: 
[git_output-updatedwithoutpii.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/9490746/git_output-updatedwithoutpii.txt)

**Comment by bgavrilMS** [comment]
Hi @jossgc - I am transferring this to GCM. This is not an actionable issue for MSAL.

**Comment by bgavrilMS** [comment]
I'll post some comments in the GCM thread.
