### ISSUE TITLE
[Bug] Exception AADSTS53000 using AcquireTokenByIntegratedWindowsAuth on .NET Framework but not with .NET Core

### ISSUE THREAD

**Issue by xboixed** [AzureAD/microsoft-authentication-library-for-dotnet#3653]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.46.2 

**Platform**
.NET 4.8, .NET Core 6.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [x] Username Password
    * [x] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
The app is in production and after the basic authentication deprecation for EWS it needs to migrate to to a modern authentication.

**Repro**

```csharp
var ewsScopes = new string[] { "EWS.AccessAsUser.All" };
// same behavior on both lines
var authResult = await pca.AcquireTokenByUsernamePassword(ewsScopes, "account", "*****").ExecuteAsync();
or
var authResult = await pca.AcquireTokenByIntegratedWindowsAuth(ewsScopes).ExecuteAsync(CancellationToken.None);
```

**Actual behavior**
The code is working successfully on a .NET Core (from 3.0 to 6.0) console application but the exact same code on a .NET Framework 4.8 console app is throwing the exception : 
<HTML>
<head>

<body>

| Name | Value | Type
| -- | -- | --
| $exception | {"AADSTS53000: Device is not in required device state: compliant. Conditional Access policy requires a compliant device, and the device is not compliant. The user must enroll their device with an approved MDM provider like Intune.\r\nTrace ID: bb23ea0d-7f5e-4277-b1aa-8fe61cfb0800\r\nCorrelation ID: 87a736dd-7388-4aea-8a20-e45b87d2bba3\r\nTimestamp: 2022-09-05 17:08:46Z"} | Microsoft.Identity.Client.MsalUiRequiredException

</body>
</HTML>
The access policy is attached to the scope EWS.AccessAsUser.All.

The running device is enrolled.

To mention that there is no problem on the same machine with both frameworks using AcquireTokenInteractive

**Possible solution**
Migrate to .NET Core but the effort would be huge as we are using the .NET Framework windows service infrastructure with complex configurations.

**Comment by bgavrilMS** [comment]
This is by design. Apps need to use interactive auth to be able to prove that the device is managed. 

`AcquireTokenByUsernamePassword` should not even be used except for tests on in some lab-only scenarios, and the CA policy can be disabled for the handful of test users.

Please have a look at using WAM, which allows you to get a token for the currently logged in user in Windows. https://aka.ms/msal-net-wam

**Comment by xboixed** [comment]
@bgavrilMS Thank you for your reply. What is by design? the behavior difference between .NET Core and the standard .NET Fwk? Why it is only working with .NET Core? EWS is rarely used on interactive applications but mainly from services (Meeting rooms mgmt, background msg processing, etc.) so EWS often needs background/silent sign-ins with delegated permissions. 

Investigating further we can see that .NET Core MSAL is not providing the operating system but works successfully :

![MicrosoftTeams-image](https://user-images.githubusercontent.com/112887068/188850455-a76a5bf3-3f31-4485-a5b3-8c6a195ae4c0.png)

And then the policy is ignored and doesn't apply :

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/112887068/188851219-09aae2d1-eed7-4ce0-81ea-36a9ade24b76.png)

On the other hand, the standard .NET Fwk is failing but with the difference it is providing some more information about the device :

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/112887068/188851916-ea209ebc-8d31-4105-9a08-649689e19fde.png)

With the following policy check result : 
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/112887068/188852273-90a626b2-f051-410a-9499-5a55eba4eb90.png)

The conditional policies set at the Exchange level are :

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/112887068/188852623-27c82efd-6b0a-4127-afc2-918157f1e93c.png)

With the server device enrollment defined as below, joined as an **Hybrid Azure AD** and which conditional policy allows to be authenticated : 
![2022-09-07_12-14-35](https://user-images.githubusercontent.com/112887068/188870349-e291a887-4586-41a8-a893-d819b426b514.png)

Again, the issue happens on both type of connections : UsernamePassword and IntegratedWindowsAuth which are properly documented with their potential restrictions/limitations but there's no mention of a lab character of these methods and I cannot understand why an Integrated Windows Auth would be a problem as it doesn't require to manipulate an app-only secretId (let's say a password) with a far larger scope than an delegated authentication.

So, again the question I'd like you to answer is why the .NET Core authentication is successful with the code I copied from your website and not the one with the standard .NET 4.6?

Thank you!

**Comment by bgavrilMS** [comment]
I don't know, I think you'd need to provide us with verbose logs https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging to have a look. 

`IntegratedWindowsAuth` as far as I know does not certify that the device is managed or not. 

My recommendation would be: 

1. [Best] use WAM, see https://aka.ms/msal-net-wam. This allows you to get a token **silently** for the default Windows account. Internally this tries several protocols, including IntegratedWindowsAuth. Just use `P
ublicClientApplication.OperatingSystemAccount` as account.

2. [Ok] Username/Password flow + WAM. I believe this will prove that the device is managed. 

3. [Not ideal, but will work] Configure your CA policy to not apply to the users on these machines.
