### ISSUE TITLE
[Bug] AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com)

### ISSUE THREAD

**Issue by NakulSabharwal95** [AzureAD/microsoft-authentication-library-for-dotnet#3655]
"AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).\r\nTrace ID: {Unknown Guid}\r\nCorrelation ID: {Unknown Guid}\r\nTimestamp: 2022-09-07 15:58:58Z",

**Which version of MSAL.NET are you using?**
MSAL.NET 4.44.0

**Platform**
NET 4.5

**What authentication flow has the issue?**
* Desktop
Interactive Embedded browser

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**
Acquire token silently using this configuration in non-public env.
```csharp

            return PublicClientApplicationBuilder.Create(clientId)
                   .WithRedirectUri(REDIRECT_URI)
                   .WithAuthority(authority, tenant)
                   .WithWindowsBroker(false)
                   .WithMultiCloudSupport(true)
                   .WithMsalLogging();
```

**Expected behavior**
Login to non-public account and correctly get access tokens.

**Actual behavior**
The above error :  A silent sign-in request was sent but no user is signed in.

**Comment by jmprieur** [comment]
@NakulSabharwal95 : did you get a new GPO pushed to your machine? or an update of your operating system?

**Comment by bgavrilMS** [comment]
This seems like a configuration problem...

**Comment by pmaytak** [comment]
@NakulSabharwal95 Where you able to verify if this was due to IE policies?
