### ISSUE TITLE
[Bug] Need guidance on handling AADSTS50076 error

### ISSUE THREAD

**Issue by nebhagat** [AzureAD/microsoft-authentication-library-for-dotnet#3665]
**Logs and network traces**

An exception occurred while getting user token from AAD. TenantId:XX Audience:XX, exception message:AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'XX'.
Trace ID: fa9d1369-853f-423f-b624-b78cd3da0e00
Correlation ID: 70fee1b3-4ec2-4bcd-8637-471686d69b2e
Timestamp: 2022-09-10 16:43:36Z

**Which version of MSAL.NET are you using?**

Microsoft.Identity.Client 4.39.0

**Platform**
netstandard2.0

**What authentication flow has the issue?**

* Daemon app 
    * [] Service to Service calls

Looking for guidance to handle AADSTS50076 error. We got the error for confidentialClientApplication to obtain on behalf of token. As we are backend service not sure what's the guideline on handling MFA.

AuthenticationResult authenticationResult = await this.confidentialClientApplication
                    .AcquireTokenOnBehalfOf(scopes, new UserAssertion(userToken))
                    .WithAuthority(this.authServiceOptions.AuthorityPrefix + tenantId, validateAuthority: true)
                    .WithSendX5C(this.sendX5c)
                    .ExecuteAsync()
                    .ConfigureAwait(false);

**Comment by jmprieur** [comment]
@nebhagat from your web API, you need to cache the UiRequiredException and send back a WWW-Authenticate header with the claims that the client should ask the user to provide.
You might want to look at this sample, where it's explained: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph
