### ISSUE TITLE
[Bug] Close button of sign in dialog is not reachable with keyboard

### ISSUE THREAD

**Issue by Bboyaji** [AzureAD/microsoft-authentication-library-for-dotnet#3671]
**Logs and network traces**
N/A

**Which version of MSAL.NET are you using?**
MSAL with Visual Studio, Dev 16 and Dev 17

**Platform**
NET472

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
Existing App

**Repro**
1. Launch VS and sign in
2. Iterate through the elements of the Sign in Dialog page with keyboard
3. Check if the close button in the upper right corner will be selected by the focus

**Expected behavior**
The close button in the upper right corner will be selected by the focus

**Actual behavior**
The close button in the upper right corner will not be selected by the focus

**Possible solution**
N/A

**Additional context / logs / screenshots / links to code**
![accountPicker](https://user-images.githubusercontent.com/95256270/190209128-78cc5f8f-7c2d-4c06-b907-c2922bf16825.png)

**Comment by pmaytak** [comment]
@bboyajiantest MSAL doesn't control how that popup works. You can post Visual Studio feedback here: https://developercommunity.visualstudio.com/home

@gladjohn @bgavrilMS I guess we could ping the WAM team about this.

**Comment by bgavrilMS** [comment]
I have a feeling @bboyajiantest is performing accessibility testing for VS? This looks like our embedded browser no?

@crmann1 - was this working before?

**Comment by crmann1** [comment]
No idea if it was or not. But it is an accessibility issue found in the current bits.

**Comment by bgavrilMS** [comment]
This never worked though, and I'm not sure it is possible to make it work. I can't select the close button with TAB in any application (WinForms or WPF). Thoughts?

**Comment by bgavrilMS** [comment]
Won't fix, please use WAM.
