### ISSUE TITLE
[Bug] MSAL 4.37.- logs critical errors when they are not critical

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#3683]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**

**Platform**
ASP.NET Core 6.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ x] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

**Repro**
- Create an ASP.NET Core web app (using Visual Studio File new project ASP.NET core web app, and checking Microsoft identity platform for the authorization. Check 'use graph" in the wizard.
- Update MSAL.NET to 4.47.0
- Run it

**Expected behavior**
The logs shouldn't call out critical errors when they are not

**Actual behavior**
![image](https://user-images.githubusercontent.com/13203188/190942380-eaacd17e-fd45-445b-8dbf-fcefeb676315.png)

Does it means that MSAL logs as "always" things that should not be logged as "always"?

See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/search?q=logger.Always&type=code.
I don't think that any of these should be logged as "always (which will translate to critical in ASP.NET Core)

**Comment by bgavrilMS** [comment]
I would think https://github.com/AzureAD/microsoft-identity-web/pull/1891 is enough? 

`Always` log level concept is similar to Azure Identity log level, which should be translated to "asp.net core's info level"
