### ISSUE TITLE
Could some body please tell me why MSAL.NET status against WinUI3 is shown as n/a ?

### ISSUE THREAD

**Issue by dg2k** [AzureAD/microsoft-authentication-library-for-dotnet#3686]
I am trying to migrate a Xamarin code to .NET MAUI and I have used basic authentication to use OneDrive storage to backup user data (using Microsoft Graph API).

I was hoping to find MSAL authentication for WinUI and not clear to me if  **n/a** as indicated means not available at this time, or **not applicable** at all. Surely, there are many scenarios where apps demand authentication as for user OneDrive storage access.

Perhaps I am missing something here. Please let me know how to migrate MSAL authentication used in Xamarin to .NET MAUI and if different options exist.

**Comment by pmaytak** [comment]
@dg2k Where do you see the **n/a** comment? 
See [these samples](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/main/MAUI) on how to use MSAL.NET in MAUI.

**Comment by dg2k** [comment]
Hi @pmaytak - [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/MauiStatus.md)

**Comment by pmaytak** [comment]
@dg2k Thanks, yea seems outdated. [This one's](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/main/MauiApps.md) up to date.

@SameerK-MSFT I'll remove the MauiStatus.md from this repo, and update the release notes to point to the one in samples. Agree? 
This file does mention UWP and MacOS, which sample one doesn't. What's the status on those?

**Comment by pmaytak** [comment]
Updated MauiStatus.md

**Comment by bgavrilMS** [comment]
> Status of UWP is that it still works. Maui + MacCatalyst does not work.
