### ISSUE TITLE
[Internal] Create dashboard with run Kusto query to report on HTTP client errors

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#3687]
**Overview:** Before 4.46.2 there were different HTTP client factory implementations in .NET Fx and .NET Core. Based on data .NET Core was more resilient (threw less errors). In [4.46.2](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3626), .NET Fx started using the client implementation of .NET Core.

**Goal:** Create a query to find and compare the number of HTTP related errors pre- and post- 4.46.2 on .NET Core and Fx.

Related: #3546

**Comment by pmaytak** [comment]
Results are for data between 9/20-9/27. HasFix represents versions 4.46.2 and above. The error count includes: request_timeout, TaskCanceledException, OperationCanceledException. In the first table the error count includes HttpRequestException, in the second table, it's not included.

The rows for before fix, show what is expected - more errors on NetFx than NetCore. The after the fix comparison shows the error percentage is much closer now between frameworks, and NetFx actually has less. I am not sure why the number of errors is much higher for after the fix numbers. There was an error handling refactoring in 4.44. So it could be that the errors counted is more broad than needed. It could also be that maybe the error handling code is more accurate now; and we weren't catching all errors before.

| **Sku**      | **HasFix** | **ErrorCount** | **TotalRequests** | **% Error** |
|-------------:|-----------:|---------------:|------------------:|------------:|
| MSAL.NetCore | 1          | 6645           | 301392            | 2.204770%   |
| MSAL.NetCore | 0          | 9637           | 968025221         | 0.000996%   |
| MSAL.Desktop | 1          | 42             | 46316             | 0.090681%   |
| MSAL.Desktop | 0          | 105229         | 935277733         | 0.011251%   |


| **Sku**      | **HasFix** | **ErrorCount** | **TotalRequests** | **% Error** |
|-------------:|-----------:|---------------:|------------------:|------------:|
| MSAL.NetCore | 1          | 5312           | 301392            | 1.762489%   |
| MSAL.NetCore | 0          | 9656           | 968025221         | 0.000997%   |
| MSAL.Desktop | 1          | 7              | 46316             | 0.015114%   |
| MSAL.Desktop | 0          | 105221         | 935277733         | 0.011250%   |

**Comment by pmaytak** [comment]
Moved to Blocked status. Will wait some time, maybe a week, until more requests with new MSAL version come through to increase the sample size. The increase in errors maybe be due to small sample size.

**Comment by bgavrilMS** [comment]
We should discuss with data team about best practices here before having a dashboard. Maybe looking at past 1 week is enough?

**Comment by pmaytak** [comment]
Update: Created some error-related queries. Added details in #3546 and sent via email.
