### ISSUE TITLE
[Documentation] msal vs msauth redirect uri on android

### ISSUE THREAD

**Issue by J-Swift** [AzureAD/microsoft-authentication-library-for-dotnet#3688]
**Documentation related to component**

Android?

**Please check those that apply**

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

**Description of the issue**

I just went through setting up B2C in a MAUI app and it looks like theres a disconnect in how redirect URIs should be specified/configured between the Azure portal and the app settings. The samples all give `msal{ClientId}://auth` forms of the redirect, but all the Azure documentation seems to indicate I should be using `msauth://{bundle}/{signature}`? I didn't even realize I could generate the `msal` version on the portal until I looked closer at the options (see screenshot).

<img width="558" alt="Screen Shot 2022-09-21 at 12 18 09 PM" src="https://user-images.githubusercontent.com/734158/191558131-75cb1ed8-75cd-4585-9a7b-2e5b1abeaaff.png">

I ended up doing the `msauth` version because it seems like Azure wants me to, but this should really be explained and documented on the SDK side, and the SDK updated to use this version in the examples.

**Comment by J-Swift** [comment]
So do both auth flows support PKCE, etc? Or are there tradeoffs between them? I'm pretty lost about the differences between them, so it would definitely be helpful to have a clear explanation of which to use and when. It sounds like the broker integration is the only consideration?

**Comment by bgavrilMS** [comment]
Yes, we use PKCE everywhere as it improves security stance. 

`msal4a1aa1d5-c567-49d0-ad0b-cd957a47f842://auth` is simpler to manage and will work with both embedded webview / system webview, which B2C supports. 

https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-android-considerations
