### ISSUE TITLE
[Bug] Pass Default CancellationToken while calling into SignOutSilentlyAsync

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3705]
Pass Default CancellationToken while calling into SignOutSilentlyAsync

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs#L388

public Task<SignOutResult> SignOutSilentlyAsync(string clientId, string correlationId, Account account, CancellationToken cancellationToken = default(CancellationToken))

**Comment by bgavrilMS** [comment]
@gladjohn - please try to phrase bugs in a way that outlines the user impact. Is there any?

I'd argue that: 

1. All runtime operations use the default cancellation token unless a real token is passed in
2. Why not propagate the actual cancellation token from the app developer to the runtime? It involves changing the IBroker interface a bit, but that's an internal interface so not a big deal. Just no-op on ios and android. 
3. 
4. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/ClientApplicationBase.cs#L196

**Comment by bgavrilMS** [comment]
We discussed about this offline, it is not required.
