### ISSUE TITLE
[Bug] AADSTS700016 error for Service Principal

### ISSUE THREAD

**Issue by vidai-msft** [AzureAD/microsoft-authentication-library-for-dotnet#3706]
**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client.dll 4.39.0

We got a requirement using Azure PowerShell to create a new service principal and then assign Owner RBAC role to this service principal at the subscription level. After that, we use the new service principal to log into Azure to perform some actions.
However, even after successfully logging in, we still would randomly see the following exception.

The general process is:
`New-AzADServicePrincipal`
`New-AzRoleAssignment`
`Connect-AzAccount` - This command is easy to fail so we have retry mechanism to mitigate. This is understandable.
(After successfully logging in, we can confirm the app appeared on the Azure portal)
`Get-AzAccessToken` - We assume at this moment, the app should be ready. But still it would fail with the below exception. Retry after a few seconds will often work.
`Get-AzResourceGroup` - Sometimes, even the previous command succeeded, this command could also fail saying the app was not found. This is confusing. Retry after a few seconds will often work.

Exception thrown:
```
Microsoft.Identity.Client.MsalServiceException (0x80131500): AADSTS700016: Application with identifier 'b40a59c0-92ae-4ce0-b231-6d9d70f7b2b9' was not found in the directory 'Microsoft'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: eb3740e8-0839-4476-aaa2-aa9521182a00
Correlation ID: f59ae33b-1fe0-436c-bc54-a6f547ccf8d7
Timestamp: 2022-09-27 07:16:26Z
```
Providing one more Correlation ID for investigation.
```
Microsoft.Identity.Client.MsalServiceException (0x80131500): AADSTS700016: Application with identifier '515c4ffe-1d47-4994-8a94-0a09c1cbedb5' was not found in the directory 'Microsoft'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: eb3740e8-0839-4476-aaa2-aa9588982a00
Correlation ID: 564171d4-1726-444e-9e6e-11a7916c0bfe
Timestamp: 2022-09-27 07:54:14Z
```

Please help clarify:
1. Is this error expected?
2. If this is expected, can you please elaborate on why this happens easily even after successfully logging in? Is there any recommended workaround to mitigate this kind of issue?
3. If this is not expected, any other information needed for investigation?

Thanks!

**Comment by bgavrilMS** [comment]
Hi @vidai-msft, this is not an SDK issue. Since you are internal, best way to escalate this is to open ICM to `ESTS > Incident Triage`
