### ISSUE TITLE
[Bug] Suppress account control when login_hint is present

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3709]
Related Bug [Bug 2040431](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fidentitydivision.visualstudio.com%2FEngineering%2F_workitems%2Fedit%2F2040431&data=05%7C01%7CGladwin.Johnson%40microsoft.com%7C796125e803074fac150408da9c0085f8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637993823307760708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FEy1h61LDdI79gw8Z%2Fme0MQR2LuUksgAw%2FNdAzR%2F8Cg%3D&reserved=0): Even with login_hint specified, MsalRuntime always shows the account picker

The related bug is tracking a fix on MSALruntime, this issue is to adopt to the fix when msalruntime fixes the related issue.

**Comment by bgavrilMS** [comment]
Let's track this with https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3301
