### ISSUE TITLE
[Feature Request] Common cache for .NET identity libraries

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#3712]
Tracking work items [here](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1979842).
Related to #3532, #3020

**Comment by pmaytak** [comment]
No specific work as of now. Postponed, in discussions to use R9 caching implementation.

**Comment by bgavrilMS** [comment]
Marking this as blocked until we have a design.

**Comment by pmaytak** [comment]
Use #4257 instead.
