### ISSUE TITLE
[Bug] Deprecate xamarin.mac target, as nobody uses it

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3722]
0 requests made in the past 10 days and it's causing issues with logging.

**Comment by bgavrilMS** [comment]
CC @trwalke

**Comment by pmaytak** [comment]
> 0 requests made in the past 10 days and it's causing issues with logging.

@bgavrilMS Would be good to have a dashboard for this - app count per MSAL target and request count per MSAL target, unless we already do.
