### ISSUE TITLE
Intermittent Issue when authenticating to Microsoft using service principal 

### ISSUE THREAD

**Issue by btharunkumar** [AzureAD/microsoft-authentication-library-for-dotnet#3723]
I have created an Azure function which will authenticate to Power BI and export Power BI reports
In this function, I am authenticating to Microsoft to get the access token details. 

Function is failing some times and the logs are showing the below Exception:
Exception: AggregateExceptions
Exception Message: One or more errors occurred. (An error occurred while sending the request.)

Adding stack trace for more understanding:

{"startDateTime":"2022-09-26T15:23:53.5535062Z","logType":"Error","reportsUploaded":"0","emailStatus":"0","reportsExported":"0","endDateTime":"2022-09-26T15:24:13.5709713Z","totalReports":"0","account":"****","response":"Failed","utilityName":"Scheduler","action":"Authorize","scheduleId":"41","stackTrace":"at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at PBIUtilities.AadService.GetAccessToken() in C:\\Users\\MAQ-USER\\Desktop\\New folder\\GIT\\Juniper\\JSI-PowerBI-Utility\\PBIUtilityFunctions\\PBIUtilities\\Helper\\AadService.cs:line 45\r\n   at PBIUtilities.PbiService.GetPowerBIClient() in C:\\Users\\MAQ-USER\\Desktop\\New folder\\GIT\\Juniper\\JSI-PowerBI-Utility\\PBIUtilityFunctions\\PBIUtilities\\Helper\\PbiService.cs:line 41\r\n   at PBIUtilities.FunSendNotification.Run(String myQueueItem, ILogger log) in C:\\Users\\MAQ-USER\\Desktop\\New folder\\GIT\\Juniper\\JSI-PowerBI-Utility\\PBIUtilityFunctions\\PBIUtilities\\FunSendNotification.cs:line 67","exceptionType":"System.AggregateException","exceptionMessage":"One or more errors occurred. (An error occurred while sending the request.)"}

Adding method definition for GetAccessToken() 

![image](https://user-images.githubusercontent.com/100213908/193278957-a38e8f3a-dade-451f-9b31-b4db28fc7050.png)

**Comment by bgavrilMS** [comment]
There is no info in the stack trace, because you use `.Result`. Either use `async` in your code, or use `GetAwaiter().GetResult()`

Can you try to extract the actual exception and post here please?
