### ISSUE TITLE
[Bug] Failed Authenticate by using cached refresh token 

### ISSUE THREAD

**Issue by hienguye** [AzureAD/microsoft-authentication-library-for-dotnet#3725]
**Which version of MSAL.NET are you using?**
"Microsoft.Identity.Client" Version="4.46.0"
"Microsoft.Identity.Client.Broker" Version="4.46.0-preview"

**Platform**
net6.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
Using cached refresh token

**Is this a new or existing app?**
Existing live MSA app

**Repro**
So I have 2 separate applications.

The first one with the code as below:
```csharp
            var pca = PublicClientApplicationBuilder
                .Create(clientId)
                .WithBrokerPreview(true)
                .WithAuthority(https://login.microsoftonline.com/consumers)
                .WithParentActivityOrWindow(GetConsoleOrTerminalWindow)
              .Build();

            pca.UserTokenCache.SetAfterAccessAsync(MakeCacheUpdateCallback(environmentConfig));
```

This is working fine with login by MSA account. And I can also obtain the refresh token and save it to a file in the function MakeCacheUpdateCallback

On the other hand, I have a separate code:
```csharp
            var this.pubClientApp = PublicClientApplicationBuilder
                .Create(clientId)
                .WithBrokerPreview(true)
                .WithAuthority(https://login.microsoftonline.com/consumers)
             .Build();

            this.pubClientApp.UserTokenCache.SetBeforeAccessAsync(BeforeAccessNotification);
            var accounts = await this.pubClientApp.GetAccountsAsync();
```

As SetBeforeAccessAsync, it will get access to the saved refresh token from the first code and set it to TokenCache. The secret is always got successfully and TokenCache is also DeserializeMsalV3 without exception:
```csharp
            private async Task BeforeAccessNotification(TokenCacheNotificationArgs args)
            {
                try
                {
                    string secret = await this.kvClient.GetKeyVaultSecret();

                    byte[]? token = null;

                    if (secret != null)
                    {
                        token = Convert.FromBase64String(secret);
                    }

                    if (token != null)
                    {
                        args.TokenCache.DeserializeMsalV3(token);
                    }
                }
                catch (Exception e)
                {
                    // do nothing if secret doesn't yet exist.
                }
            }
```

**Actual behavior**
With getting the refresh token successfully, the call this.pubClientApp.GetAccountsAsync(); always return 0 account.

**Expected behavior**
 I think GetAccountsAsync should return the valid account from the token cache.

**Comment by bgavrilMS** [comment]
I'm a little confused about what you are trying to here. I see that you are trying to write your own cache, which is quite tricky to do. This is why we recommend folks to just use a cache we provide in a separate library - see https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=desktop

If you do need to write your own cache, then you need to implement both `OnBeforeAccess` and `OnAfterAccess` - see https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom#simple-token-cache-serialization-msal-only

**Comment by hienguye** [comment]
I'm writing my own cache. The issue is that I want to acquire token for MSA account in a test VM. As far as I know, you can only do it interactively with MSA account. So the goal I want to achieve is that I can authenticate in one machine and save the cache token to some server. Then on the second machine, get the cache token and acquire the access token silently.

I did implement both OnBeforeAccess and OnAfterAccess. As on after access, it will get the token, serialize it then save it. This step is success. Then on before access, it will deserialize the cache and authenticate. The token is deserialized, saved and serialized successfully. The problem is that the GetAccountsAsync() always return 0 account.

**Comment by bgavrilMS** [comment]
Can you try to follow the guidance cache first and just use a file (even plaintext) ?

**Comment by hienguye** [comment]
I tried the MsalCacheHelper but it doesn't work. I tried to use Microsoft.Identity.Client.Extensions.Msal version 2.24 but my project is net6 and it doesn't built successfully. So I'm using version 4.5.1-preview. The syntax is different with instruction
            var storageProperties = new StorageCreationPropertiesBuilder("cache.plaintext", "./", ClientAppId).Build();

            var cacheHelperTask = MsalCacheHelper.CreateAsync(storageProperties);

I'm running the code in the first machine, the cache file cache.plaintext is created, then I copied it over to the second and run the same code. But the GetAccountASync() still return 0

**Comment by bgavrilMS** [comment]
Copying the cache file from one machine to another is not supported. Cache file is encrypted with DPAPI - it cannot be decrypted on another machine. 

Can you help me understand your scenario better? How are 2 machines involved here?

**Comment by hienguye** [comment]
This is for automated testing in Azure pipeline for MSA account. So I have the service which is required access token to call the API. I want to do automated integration test in Azure pipeline. And since Azure pipeline doesn't have UI, so I have no way to do interactive authenticate to get the access token.

So another team is suggesting the workaround is to implement the cache, deserialize the refresh token, save it in the key vault. Then on the Azure pipeline, the test can get the refresh token from key vault, serialize it and save to its cache. Then it can acquire the access token silently. As I know, there is a team who already successfully done this.

This is the reason why I have to implement the BeforeAccessNotification and AfterAccessNotification by using custom cache.

**Comment by bgavrilMS** [comment]
Got it, thanks for explaining. 

The only way this is going to work is to not use the broker, because the broker does not give back the refresh token to the apps / MSAL. So you'd need: 


1. Configure and get a plaintext cache on a dev machine, for the test account. You can inspect the cache file - it should have an access token, a refresh token, id token and account metadata.
2. Upload this to KV
3. The CI machine downloads the file, creates a PCA object which points to this file and calls `GetAccountsAsync()` on it. 

The broker must not be involved in any of the operations!
You can use the code [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom#simple-token-cache-serialization-msal-only) to deserialize the cache, just remove the encryption APIs (DPAPI)
