### ISSUE TITLE
[Bug] New Broker Scopes required message needs to be improved

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3727]
![image](https://user-images.githubusercontent.com/90415114/193678943-b28c61da-9106-4fe2-8bc7-3b33e030bbd8.png)

message needs to be improved saying "application scopes needs to be passed" or something better. Because user could be passing just the OIDC scopes

for now I have updated the [troubleshooting section ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WAM#msalclientexception-errcode-5376-at-least-one-scope-needs-to-be-requested-for-this-authentication-flow-error-message)

**Comment by bgavrilMS** [comment]
Propose "won't fix" as it's a very corner case scenario. If the user passes in "profile" or "openid", MSAL should throw an exception.
