### ISSUE TITLE
[Bug] Incorrect HomeAccount details populated in AuthenticationResult of AcquireTokenByRefreshToken

### ISSUE THREAD

**Issue by palakkapoor** [AzureAD/microsoft-authentication-library-for-dotnet#3736]
Obtain Refresh token invoking oauth2 endpoint directly and using AcquireTokenByRefreshToken

1. Obtain ID token, access token, refresh token for the user using [https://login.microsoftonline.com/organizations/oauth2/v2.0/token endpoint using a Public Client App.

2. Use the above refresh token to call AcquireTokenByRefresh token method to obtain a new refresh token using MSAL. 
AcquireTokenByRefreshTokenParameterBuilder acquireTokenByRefreshTokenParameterBuilder = (app as IByRefreshToken).AcquireTokenByRefreshToken(
                scopes,
               refreshTokenHttp);
            AuthenticationResult authenticationResult = await acquireTokenByRefreshTokenParameterBuilder.ExecuteAsync(CancellationToken.None)
                .ConfigureAwait(false);

 Note that HomeAccountId details (Identifier, TenantId, ObjectId) in AuthenticationResult is completely incorrect.

Discussed this issue with @bgavrilMS @trwalke and they confirmed that the cause of the issue is that they don't send "client_info" = 1 with this request, so MSAL isn't able to cache the user properly.

**Comment by gladjohn** [comment]
@palakkapoor this is fixed in MSAL 4.48.0
