### ISSUE TITLE
[Feature Request] Capture cacheLatency in MSAL

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#3738]
We have a parameter that logs DurationInCache, which is captured for distributed cache scenarios. We can capture this for MSAL InMemoryCache access by adding a stopwatch in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/01ecd12464007fc1988b6a127aa0b1b980bca1ed/src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs.

Also, add another enum in CacheUsed to indicate it is Msal's internal cache.

**Comment by bgavrilMS** [comment]
I am closing this until we can wrap up the discussions

**Comment by pmaytak** [comment]
> I am closing this until we can wrap up the discussions

@bgavrilMS What is specifically left to discuss related to this?

**Comment by bgavrilMS** [comment]
There is an email thread with requests for datapoints from E&D.
