### ISSUE TITLE
Desktop plug-in based app with multiple token requests for different scopes - A default account was not found

### ISSUE THREAD

**Issue by Camios** [AzureAD/microsoft-authentication-library-for-dotnet#3742]
Multiple scope requests but doesn't remember the account selected from the first request. 

We have a desktop app which is a hub for multiple plugins. Different plugins request tokens with different scope(s). Plugins are initialised concurrently and I'm trying to prevent multiple interactive prompts (depending on the scenario there seems to be multiple behaviours from MSAL).
All plugins should be using the same user account for requesting the tokens.
I saw for the android sdk there was single account client, but didn't see one for desktop apps. What design should I use instead?

I'm using `PublicClientApplicationBuilder` and `WithBroker()` together with an on-disk TokenCacheHelper to auth users against Azure AD. 

We only support single org for auth against Azure AD. While most users are login to windows with the same account as azure, we have some users who use a different account (different domain) to login to windows than the required Azure AD domain.

The code initially tries to acquire a token silently.
Silent acquisition works for most users thanks to WAM broker.
If I don't enable WAM broker then silent auth fails and users will also be shown an interactive prompt (we use `WithParentActivityOrWindow`).  If two plugins simultaneously request scopes, then the MSAL library will attempt to show multiple interactive prompts at the same time over the top of one another and one seems to block the other from interaction.
To work around that, I made the interactive acquisition block mutually exclusive code and once entered, there's a second attempt to acquire the token silently before performing the interactive prompt acquisition. The reason for the second silent acquisition attempt is in case another plugin acquired the token interactively while this plugin was blocked - this prevents a second interactive prompt.
This solves the problem for windows users on the right domain when WAM broker is disabled.

For users that who login to windows from a different domain, silent auth fails, then the user is shown interactive prompt to acquire the token. If multiple plugins do it simultaneously IIRC the prompts are sequential. This happens before and after my mutual exclusion block for the interactive prompt. Each plugin's attempt is getting the same error "A default account was not found".

If I'm using the WAM broker, then the account we use is the `OperationSystemAccount`. Otherwise we call `GetAccountsAsync` and use the first account or null.

It seems GetAccountsAsync is always returning `null` for users on the incompatible domain. I assumed that after the first token acquisition that `GetAccountsAsync` would remember the account. 

How can I get users on the incompatible domain to only have one interactive prompt?

Further, I had a user on a home PC (workgroup based) attempt this and they were presented with a Windows OS kind of dialog asking them something like if they want to remember this just one time / for all time and about downloading/applying the organisation's (security?) profile on to their machine - it is a very confusing dialog (ramifications of different options aren't clear). I think they accepted it forever (the default) but now they don't get interactively prompted to select their account, but how do they "undo" this acceptance so we can test this again with a clean slate? I don't know if this was especially for workgroup-based PCs or if the incompatible domain user might have also seen the dialog.

` MsalUiRequiredException while Acquiring token silently MSAL.NetCore.4.45.0.0.MsalUiRequiredException: 
	ErrorCode: interaction_required
Microsoft.Identity.Client.MsalUiRequiredException: A default account was not found
   at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker.AcquireTokenSilentDefaultUserAsync(AuthenticationRequestParameters authenticationRequestParameters, AcquireTokenSilentParameters acquireTokenSilentParameters)
   at Microsoft.Identity.Client.Internal.Requests.BrokerSilentStrategy.SendTokenRequestToBrokerAsync()
   at Microsoft.Identity.Client.Internal.Requests.BrokerSilentStrategy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
   at Frostbite.Authentication.Microsoft.AzureAuth.GetAuthTokenSilentlyAsync(String[] scopes) in E:\dev\dev-na-noraw\TnT\Code\Tools\Shared\Frostbite.Authentication\source\Authentication\Microsoft\AzureAuth.cs:line 147
	StatusCode: 0 
	ResponseBody:  
	Headers: `

**Comment by bgavrilMS** [comment]
1. For the UX experience when you "add a new account to Windows" with 3 options, I will provide the feedback to the Windows team. The SDK cannot do anything about this.
2. For multiple consent prompts, please tell me if pre-consenting is not an option? The tenant admin can pre-consent on behalf of all the users for your app. If you need to access 2 separate APIs (e.g. some Graph APIs and some of your own APIs) you need to make 2 separate calls indeed, because access tokens are scoped to 1 resource only. 
3. The `OperationSystemAccount` login is only available when the broker is enabled. If it not enabled, MSAL will throw a UiRequiredException, because we don't know what user to choose.
4. For the different domain, I'd like to get more details. Can you provide some isolated repro steps: 

a. You create a PublicClientApplication with authority set to X and without broker
b. You login interactively (with a browser, not with the broker)
c. You call "GetAccounts" and get null?

Note that going from broker to browser experience is not great, the accounts logged in with the broker will not be found when the broker is disabled. Going from browser to broker should be better.

**Comment by Camios** [comment]
The other scenarios I was trying are: 

- **User is on a compatible domain but without the broker** - in this case I was getting two prompts simultaneously so I added a mutual exclusion around the interactive prompt. Without the broker, IIRC for the "hint" account we use the first account returned from `GetAccountsAsync` if any; otherwise `null`. In this scenario the first silent acquisition for "users" fails and the first interactive prompt for "users" works, then the second silent acquisition for "inventory" succeeds - this was too was causing confusion - but I now believe it is again due to the "hint" account.
- Workgroup user with broker (not sure how close this is to my primary scenario of an incompatible domain with broker) - I would be prompted with that Windows prompt (which you clarified is asking to add the Work account to windows). If i didn't add the work account to the PC then I got a hellish experience: multiple prompts for credentials and 2FA and I don't think any of it was remembered/cached so I kept having to say "no don't add account to windows", supply credentials (not sure about 2FA).  I eventually gave in and tried remember/adding the account (can't remember exactly) and now I'm never again prompted for credentials - "forever" token sounds like a problem/bug. Unless there is something else refreshing this - what is keeping this active forever? And how do i make it forget to be able to re-test a blank slate? 

I haven't tried testing the combination of "without the broker" AND "incompatible domain". If the workgroup scenario is the same, then I just need a way to forget the work account to start anew.

**Comment by Camios** [comment]
Spread my response over a few comments as it was getting quite large (or is that worse)

**Comment by Camios** [comment]
using System;
	using System.Linq;
	using System.Threading;
	using System.Threading.Tasks;
	using log4net;
	using Microsoft.Extensions.Options;
	using Microsoft.Identity.Client;
	using RestSharp;
	using RestSharp.Authenticators;

	namespace Foo;

	public class AzureAuth
	{
		private readonly IPublicClientApplication m_clientApp;
		private readonly AzureAuthOptions m_options;
		private readonly SemaphoreSlim m_interactiveAcquisitionSemaphore = new SemaphoreSlim(1, 1);
		private int m_interactiveTokenAcquisitionCount;

		public AzureAuth(IOptions<AzureAuthOptions> options)
		{
			m_options = options.Value;

			var builder = PublicClientApplicationBuilder.Create(m_options.ClientId)
				.WithAuthority(AzureCloudInstance.AzurePublic, m_options.Tenant)
				.WithDefaultRedirectUri();

			if (m_options.UseBroker)
			{
				// Adds Broker for Web Account Manager which enables Windows Single Sign-On(??).
				// Requires Azure App Registration to define a redirect URI matching: "ms-appx-web://microsoft.aad.brokerplugin/{client_id}"
				// Falls back to browser-based account selection.
				builder.WithBroker();
			}

			m_clientApp = builder.Build();

			// TokenCacheHelper impl based-on / copied-from an MSAL sample
			TokenCacheHelper.EnableSerialization(m_clientApp.UserTokenCache);
		}

		public async Task<string> GetAuthTokenAsync(string[] scopes, IntPtr windowHandle)
		{
			if (scopes == null)
				throw new ArgumentException($"{nameof(scopes)} was null.", nameof(scopes));

			int preWaitTokenCount = m_interactiveTokenAcquisitionCount;
			s_log.Debug($"Pre-first silent acquisition interactive count: {preWaitTokenCount}");

			string token = await GetAuthTokenSilentlyAsync(scopes)
				.ConfigureAwait(false);

			if (string.IsNullOrEmpty(token))
			{
				// Use a semaphore to prevent simultaneous requests for interactive token acquisition.
				s_log.Debug($"Waiting for interactive acquisition semaphore");
				await m_interactiveAcquisitionSemaphore.WaitAsync()
					.ConfigureAwait(false);
				try
				{
					s_log.Debug($"Acquired interactive acquisition semaphore");

					// On acquisition of the semaphore, check whether a new token was acquired while waiting for that semaphore.
					// This is to avoid unnecessarily attempting another silent acquisition if the number of tokens hasn't changed. e.g. first time
					s_log.Debug($"Post wait. Token count check. NewCount: {m_interactiveTokenAcquisitionCount} > OldCount: {preWaitTokenCount}");
					if (m_interactiveTokenAcquisitionCount > preWaitTokenCount)
					{
						// a new token was acquired while waiting for the semaphore, silently check if it's a match
						token = await GetAuthTokenSilentlyAsync(scopes)
							.ConfigureAwait(false);
					}

					if (string.IsNullOrEmpty(token))
					{
						// Calling AcquireTokenInteractive to acquire a token with user interaction
						token = await AcquireTokenInteractiveAsync(scopes, windowHandle)
							.ConfigureAwait(false);
					}
				}
				finally
				{
					if (!string.IsNullOrEmpty(token))
					{
						m_interactiveTokenAcquisitionCount++;
						s_log.Debug($"Pre-semaphore release. Silent acquisition interactive count incremented to: {m_interactiveTokenAcquisitionCount}");
					}
					m_interactiveAcquisitionSemaphore.Release();
					s_log.Debug($"Released interactive acquisition semaphore");
				}
			}
			return token;
		}

		public async Task<string> GetAuthTokenSilentlyAsync(string[] scopes)
		{
			if (scopes == null)
				throw new ArgumentException($"{nameof(scopes)} was null.", nameof(scopes));

			AuthenticationResult authResult = null;
			var firstAccount = await GetAccountAsync()
				.ConfigureAwait(false);
			try
			{
				s_log.Debug($"Attempting silent acquisition of token for account: {firstAccount}.");
				authResult = await m_clientApp.AcquireTokenSilent(scopes, firstAccount)
					.ExecuteAsync()
					.ConfigureAwait(false);
				s_log.Debug($"Acquired token for account: {firstAccount}.");
			}
			catch (MsalUiRequiredException e)
			{
				//A MsalUiRequiredException happened on AcquireTokenSilent.
				//Token returned will be null value
				s_log.Debug($"MsalUiRequiredException while Acquiring token silently {e}");
			}
			return authResult?.AccessToken;
		}

		private async Task<string> AcquireTokenInteractiveAsync(string[] scopes, IntPtr windowHandle)
		{
			AuthenticationResult authResult = null;
			try
			{
				var firstAccount = await GetAccountAsync()
					.ConfigureAwait(false);

				s_log.Info($"Attempting to acquire token interactively, because silent acquisition failed for account {firstAccount}.");

				var builder = m_clientApp.AcquireTokenInteractive(scopes)
					.WithAccount(firstAccount)
					.WithPrompt(Prompt.SelectAccount);

				if (windowHandle != IntPtr.Zero)
				{
					builder.WithParentActivityOrWindow(windowHandle);
				}
				else
				{
					s_log.Warn("Parent window wasn't set for showing interactive account selection window - it may be hidden behind other window(s).");
				}
				authResult = await builder.ExecuteAsync()
					.ConfigureAwait(false);
			}
			catch (MsalClientException e)
			{
				s_log.Error("Exception while acquiring token interactively.", e);
			}

			return authResult?.AccessToken;
		}

		private async Task<IAccount> GetAccountAsync()
		{
			IAccount firstAccount = null;

			if (m_options.UseBroker)
			{
				firstAccount = PublicClientApplication.OperatingSystemAccount;
			}
			else
			{
				var accounts = await m_clientApp.GetAccountsAsync()
					.ConfigureAwait(false);
				firstAccount = accounts.FirstOrDefault();
			}

			return firstAccount;
		}
	}

**Comment by bgavrilMS** [comment]
Please have a look at this sample I wrote, it shows the "recommeded' way to integrate with broker, i.e.

https://github.com/bgavrilMS/MSAL-SingleAccount-SSO

1. When app opens the first time, login the user with default OS account
2. If user is not happy with this, they can change the account

If your users have several AAD accounts on their machine, maybe it's better to not use the "DefaultOsAccount" option? Also, please disable the broker and try to see how the experience is with the browser.

**Comment by Camios** [comment]
On the Workgroup PC, I found the AAD account's removal is in a different spot in Windows 11 - it is under Settings -> Account -> Work and school accounts. Whereas on windows 10 it is under "Email & accounts". 
Disconnecting the work account clears something and forces the user to pick their account to re-auth.
Can you tell me where I can read about this - specifically what is keeping the work account authorised on the workgroup PC? And also how to find out about the validity period (what is the length, can it be controlled)?

**Comment by Camios** [comment]
Also, thanks for the sample and the tips. I'll try out the variations on the various PCs.

**Comment by bgavrilMS** [comment]
I couldn't find any good in-depth documentation about account integration with Windows, but our friends from GitHub wrote this nice article explaining some of the design choices, at least from an end-user perspective. 

https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/windows-broker.md

A few things to note: 

- When a Work and School account logs in for the first time, Windows will ask the user if they want to domain join the device. User can choose not to do this (app only account). 
- When a Personal (i.e. outlook.com) account logs in, Windows does not ask the user. They are automatically added to the Accounts menu.
- If an account is added to Windows, some other apps can use it to sign in the user to that account. This as follows: 
1. Microsoft apps can "discover" both Work and School and Personal accounts
2. 3rd party apps can "discover" only Work and School accounts
3. Personal accounts can be configured to disalow this

![image](https://user-images.githubusercontent.com/12273384/195851027-46017ed3-f2b1-4741-ab3f-c10a0f8254a2.png)


- Applications cannot remove accounts from Windows, even if they led to the account being added. Only users can remove themselves from Windows.
  
- If you don't like auth experience with Windows, you can always use a browser for auth. This will not add accounts to Windows etc. However, even the experience in the browser is a lot better if the user has the account in Windows.

**Comment by Camios** [comment]
@bgavrilMS thanks for the support, can you point me to documentation/explanation of the function which keeps the work account authenticated (doesn't need to acquire a new token) when the broker is enabled?

**Comment by Camios** [comment]
^ I think this dialog is causing it 

<img width="625" alt="image" src="https://user-images.githubusercontent.com/2810835/196115329-81d9e7ac-8100-4c8e-8bdc-b4e314397e31.png">

I could do with some help understanding what is providing this dialog and the effect the checkbox and the different "OK" and "No, ..." buttons have on auth.

**Comment by bgavrilMS** [comment]
Hi, please see https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/windows-broker.md#for-work-or-school-accounts-azure-ad-backed-identities

Applications can perform `AcquireTokenSilent(DefaultOsAccount)` to get tokens with the current Windows account.
Applications can also enable account discovery (we haven't fully implented this in MSAL.NET yet), and then `GetAccounts` will return the WIndows accounts.

**Comment by SameerK-MSFT** [comment]
No response for 7 days. Closing. Feel free to reopen.

**Comment by bgavrilMS** [comment]
We've been chatting daily @SameerK-MSFT, keeping this open for other questions.

**Comment by Camios** [comment]
Thanks for providing the info. The link for https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/windows-broker.md#for-work-or-school-accounts-azure-ad-backed-identities was very helpful.

It is the exact documentation I was expecting from MS but was disappointed. 
The current MS documentation is either high-level/conceptual or is just tutorials for configuring it. There seems to be a big documentation gap on areas of actual impact to the user's system and resulting behaviour for each of the different choices/flows. 

I'd request it but I'm not sure which team to contact. Any idea?

**Comment by bgavrilMS** [comment]
@balakr-msft-zz  @ploegert as FYI, example of advanced users being confused by all the WAM options / behavior of domain joining etc. There is also no documentation around this - some products wrote their own.

https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/windows-broker.md#for-work-or-school-accounts-azure-ad-backed-identities
