### ISSUE TITLE
[Bug] MsalClientException: authenticaiton_canceled in NET MAUI iOS 16 during startup up

### ISSUE THREAD

**Issue by AlexanderSCK** [AzureAD/microsoft-authentication-library-for-dotnet#3748]
**Logs and network traces**
[0:] MSAL.Xamarin.iOS.4.47.2.0.MsalClientException: 
	ErrorCode: authentication_canceled
Microsoft.Identity.Client.MsalClientException: User canceled authentication. 
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.VerifyAuthorizationResult(AuthorizationResult authorizationResult, String originalState)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at AppB2C.AuthService.SignInInteractively() in D:\iOS\FoodBookB2C\AuthService.cs:line 60
Loaded assembly: /private/var/containers/Bundle/Application/82E39548-F2D3-4A6D-9FA8-719606177968/AppB2C.app/System.Runtime.Intrinsics.dll [External]
Thread started: <Thread Pool> #14

**Which version of MSAL.NET are you using?**
MSAL.NET 4.47.2

**Platform**
.NET MAUI iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
iOS 16 

**Is this a new or existing app?**

**Repro**

```csharp
protected override async void OnStart()
    {

        var result = await authService.AcquireTokenSilent();
        if (result != null)
        {
            ProfileViewModel.GetResult(result);
            MainPageViewModel.IsLoggedIn = true;

        }
        else
        {
            try
        {
            var singResult = await authService.SignInInteractively().ConfigureAwait(false);
            ProfileViewModel.GetResult(singResult);
        }
        catch (Exception ex)
        {

            Debug.WriteLine(ex.ToString());
        }
        MainPageViewModel.IsLoggedIn = false;

        }
```
```csharp
 public async Task<AuthenticationResult> SignInInteractively()
        {
            AuthenticationResult result = null;
            try
            {
                var systemWebViewOptions = new SystemWebViewOptions()
                {
                    iOSHidePrivacyPrompt = true
                };
                result = await App.AuthenticationClient
                    .AcquireTokenInteractive(Constants.Scopes)
                    .WithSystemWebViewOptions(systemWebViewOptions)
                    .WithUseEmbeddedWebView(false)
                    .ExecuteAsync()
                    .ConfigureAwait(false);
                
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.ToString());
            }
            return result;
        }
```
**Expected behavior**
On Android the app works fine on startup it detects if the user is logged in and if not goes to the SignUpInteractive method in the App.xaml.cs OnStart() and initiates a browser with Azure B2C, however the same behavior on iOS 16 using Hot Reload on a Iphone 8 physical device produces the MSAL client exception user canceled authenticaiton, however if called after the application has loaded it functions properly, the signinteractive issues the browser and gets a result on the same iOS app, but  I have to call it also on startup if the user is not logged in and load the Azure B2C sign in page before he can navigate to the mainpage or the mainpage is displayed, it should behave as it does on Android. 

**Actual behavior**
The MSALClientException is thrown and the systembrowser windows doesnt show up. 

**Possible solution**

**Additional context / logs / screenshots / links to code**

```csharp
public partial class App : Application
{
    public static IPublicClientApplication AuthenticationClient { get; private set; }

    public static NavigationPage NavigationPage { get; private set; }

    private readonly IAuthService authService;
    public MainPageViewModel MainPageViewModel { get; private set; }
    public ProfileViewModel ProfileViewModel { get; private set; }

    public App(MainPageViewModel viewModel, IAuthService authService, MainPageViewModel mainPageViewModel, ProfileViewModel profileViewModel)
    {
        InitializeComponent();
        AuthenticationClient = PublicClientApplicationBuilder.Create(Constants.ClientId)
               .WithIosKeychainSecurityGroup(Constants.IosKeychainSecurityGroups)
               .WithB2CAuthority(Constants.AuthoritySignIn)
               .WithRedirectUri($"msal{Constants.ClientId}://auth")
               .Build();

        this.authService = authService;
        MainPageViewModel = mainPageViewModel;
        ProfileViewModel = profileViewModel;
    }

    protected override Window CreateWindow(IActivationState activationState)
    {
        MainPage = NavigationPage = new NavigationPage(new MainPage(MainPageViewModel));
        return base.CreateWindow(activationState);
    }
    protected override async void OnStart()
    {

        var result = await authService.AcquireTokenSilent();
        if (result != null)
        {
            ProfileViewModel.GetResult(result);
            MainPageViewModel.IsLoggedIn = true;

        }
        else
        {
            Device.BeginInvokeOnMainThread(SingUser);

        }
    }

    private async void SingUser()
    {
        try
        {
            var singResult = await authService.SignInInteractively().ConfigureAwait(false);
            ProfileViewModel.GetResult(singResult);
        }
        catch (Exception ex)
        {

            Debug.WriteLine(ex.ToString());
        }
        MainPageViewModel.IsLoggedIn = false;
    }
}
```

**Comment by AlexanderSCK** [comment]
Executing the Page OnApearing event on the MainPage also produces strange behaviors with the same set up. It gives me a null Exception: Object not set to an instance of an Object at SystemWebUI: SystemWebView, although the authentication services and Public applicationbuilder are all initliazed and working, on Android again it behaves correctly with OnAppearing. Just giving more context. I want to initiate the log in "Azure Page" on start up before the user can access the rest of the application every time the token is not obtain silently aka he is not loged in.

**Comment by bradyguyc** [comment]
I am getting the same error I would also like to share that on my AcquireTokenSilentAsync it does not throw an exception.   I have to check the results.InnerExceptions to verify if it really was successful on iOS.  This is not the case on Android.  

I am using .NET 7.0 preview

I then get to the same spot.   A cancel exception except that the browser window never showed.

`
 private static  async void OnSignIn()
    {
        Task<AuthenticationResult> result;
        try
        {
result = PCAWrapperB2C.Instance.AcquireTokenSilentAsync(B2CConstants.Scopes).WaitAsync(new TimeSpan(0,0,20));
            if (result.Exception.InnerExceptions.Count > 0)
            {
                AuthenticationResult sresult = await PCAWrapperB2C.Instance.AcquireTokenInteractiveAsync(B2CConstants.Scopes).ConfigureAwait(false);
                currentData.userInfo = currentData.UpdateUserInfo(sresult);
                // show the IdToken
            }
            currentData.userInfo = currentData.UpdateUserInfo(result.Result);
            // show the IdToken
            //await ShowMessage("AcquireTokenTokenSilent call IdToken", result.IdToken).ConfigureAwait(false);
        }
        
        catch (MsalUiRequiredException)
        {
            // This executes UI interaction to obtain token
            AuthenticationResult sresult = await 
             PCAWrapperB2C.Instance.AcquireTokenInteractiveAsync(B2CConstants.Scopes).ConfigureAwait(false);
            currentData.userInfo = currentData.UpdateUserInfo(sresult);
            // show the IdToken
            //await ShowMessage("AcquireTokenInteractive call IdToken", result.IdToken).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
 
            Crashes.TrackError(ex);
            await ShowMessage("Exception in AcquireTokenTokenSilent", ex.Message).ConfigureAwait(false);
        }
    }
`
