### ISSUE TITLE
Update MAUI sample to use caching on Windows

### ISSUE THREAD

**Issue by SophisticatedConsulting** [AzureAD/microsoft-authentication-library-for-dotnet#3753]
When running the MSAL library with a Windows App, credentials do not seem to be cached and _AcquireTokenSilentAsync_ always fails.
How can this be supported for a Windows App? Is there a sample app demonstrating cached credentials (the maui example provided does not support cached credentials)?
Currently this is a question as I am not sure if it is a bug, feature request or question about how to achieve it.

**Comment by SophisticatedConsulting** [comment]
Thanks for the sample code @bgavrilMS.

**Comment by bgavrilMS** [comment]
CC @SameerK-MSFT

**Comment by bgavrilMS** [comment]
This is in progress with @abatishchev

**Comment by bgavrilMS** [comment]
This has been fixed - I can see the cache being set on the Maui sample - https://github.com/Azure-Samples/ms-identity-dotnetcore-maui
