### ISSUE TITLE
Error Using Azure Certificate Based Authentication on Windows Application

### ISSUE THREAD

**Issue by igalfsg** [AzureAD/microsoft-authentication-library-for-dotnet#3757]
I am trying to use Azure Certificate Based Authentication to Authenticate with this Nuget Package using a windows machine, and I get the following exception: "AADSTS500176: Cannot find issuing certificate in trusted certificates list." However when I try on the browser it works. My best guess is that the wrong tenant ID is being sent on the request since Azure CBA requires the specific tenant and /common doesn't work. I looked for the trace ID and correlation ID in my tenant and could not find them but I haven't done a network trace to confirm this theory. 

   

> at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
>    at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
>    at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__11`1.MoveNext()
>    at Microsoft.Identity.Client.OAuth2.OAuth2Client.<GetTokenAsync>d__10.MoveNext()
>    at Microsoft.Identity.Client.OAuth2.TokenClient.<SendHttpAndClearTelemetryAsync>d__11.MoveNext()
>    at Microsoft.Identity.Client.OAuth2.TokenClient.<SendHttpAndClearTelemetryAsync>d__11.MoveNext()
>    at Microsoft.Identity.Client.OAuth2.TokenClient.<SendTokenRequestAsync>d__5.MoveNext()
>    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
>    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
>    at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
>    at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
>    at ezsshUIV3.Services.AuthenticationService.<GetTokenAsync>d__0.MoveNext()

**Comment by bgavrilMS** [comment]
How did you configure the certificate and the application?

**Comment by igalfsg** [comment]
This is using the newly released Azure certificate based authentication for smartcard based authentication https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-certificate-based-authentication the workflow start's the same but then it sends you to another sts endpoint (https://certauth.login.microsoftonline.com/<tenantID>/certauth)

**Comment by bgavrilMS** [comment]
Ah I see. What "browser" do you use here? The embedded browser, the system browser or the broker (WAM) ? I recommend trying the system browser.

**Comment by igalfsg** [comment]
I have tried both, and in the browser, it even breaks SSO, let's say I login into Azure using the certificate, then go to a site with MSAL, using SSO I get this error. Then I go back to Azure and I get a token error.

**Comment by bgavrilMS** [comment]
@jmprieur - do you know if anybody tested this feature with MSAL libraries? Is there a setup we can try?

**Comment by igalfsg** [comment]
Also I just checked with Azure CLI and same issue so it seems to be an issue with any app using MSAL.
az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
AADSTS500176: Cannot find issuing certificate in trusted certificates list.
Trace ID: b993c96d-0416-497f-9d80-07dc4c68d600
Correlation ID: cd4d4232-c0fe-490b-a4b5-de3f2684b721
Timestamp: 2022-11-07 21:41:42Z

@bgavrilMS  If @jmprieur  can't get you an environment to test I can guide you on how to do it in your test environment using your existing AME cert

**Comment by bgavrilMS** [comment]
I don't have an AME account, this might take some time. Feel free to start an email thread on this.

**Comment by igalfsg** [comment]
Just started the email thread

**Comment by bgavrilMS** [comment]
Hi again @igalfsg - I am suprised that this feature isn't working at least with WAM. I assume you have everything setup on your end for a test. Can you install VS 2022 **Preview** edition (it should say version 17.5.0 Preview 1) and test it that way? VS 2002 Preview has integration with all 3 auth webviews that MSAL supports: embedded, system and WAM. 

You can change them by going to account options

![image](https://user-images.githubusercontent.com/12273384/202702982-8ed52af3-4149-489a-84d1-e594c0f80e1a.png)
