### ISSUE TITLE
[Bug] - Microsoft.Identity.Client  causing failure due to out of memory exception

### ISSUE THREAD

**Issue by niketk** [AzureAD/microsoft-authentication-library-for-dotnet#3762]
**Logs and network traces**
Response Content: 500 {"Error":{"Code":"Unknown","Message":"The type initializer for 'Microsoft.Identity.Json.Utilities.ImmutableCollectionsUtils' threw an exception.","Target":null,"InnerError":{"Code":"System.TypeInitializationException","Message":"The type initializer for 'Microsoft.Identity.Json.Utilities.ImmutableCollectionsUtils' threw an exception.","Target":"TryBuildImmutableForDictionaryContract","InnerError":{"Code":"System.OutOfMemoryException","Message":"Exception of type 'System.OutOfMemoryException' was thrown.","Target":".cctor","InnerError":null}}}}

It looks like Microsoft.Identity.Client internally uses https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/ImmutableCollectionsUtils.cs which seems to be throwing this error. This service is handling low volume and there is reasonable memory available on the service fabric node.

**Which version of MSAL.NET are you using?**
4.45.0

**Platform**
.net core 3.1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [X ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
The app has been in production and the issue was noticed recently.

**Repro**

```csharp
 AuthenticationResult authenticationResult = await this.confidentialClientApplication
                .AcquireTokenOnBehalfOf(scopesForAuth, new UserAssertion(internalToken))
                .WithAuthority(authority)
                .ExecuteAsync()
                .ConfigureAwait(false);
```
**Expected behavior**
Request to our service doesnt fail with 500

**Actual behavior**
Request fails with error  Response Content: 500 {"Error":{"Code":"Unknown","Message":"The type initializer for 'Microsoft.Identity.Json.Utilities.ImmutableCollectionsUtils' threw an exception.","Target":null,"InnerError":{"Code":"System.TypeInitializationException","Message":"The type initializer for 'Microsoft.Identity.Json.Utilities.ImmutableCollectionsUtils' threw an exception.","Target":"TryBuildImmutableForDictionaryContract","InnerError":{"Code":"System.OutOfMemoryException","Message":"Exception of type 'System.OutOfMemoryException' was thrown.","Target":".cctor","InnerError":null}}}}

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by pmaytak** [comment]
@niketk Can you try upgrading to the latest MSAL? In 4.46.1 we updated to the latest Newtonsoft version, so maybe this was fixed.

How often do you see this error?
To fix it, do you restart the app/node, or does it go away by itself?

**Comment by niketk** [comment]
ok .. i am upgrading the package. The error is intermittent and only happening in 1 geo and it goes away by itself.

**Comment by niketk** [comment]
I deployed the change with version 4.46.1 and havent seen the error in last 24 hours.
