### ISSUE TITLE
[Bug] AcquireTokenSilent returns null token after delete of App Registration

### ISSUE THREAD

**Issue by wstaelens** [AzureAD/microsoft-authentication-library-for-dotnet#3764]
I've removed the default "bug" template because it is a "strange" behaviour that we have seen today and we lost HOURS. I hope somebody can report it to the correct team/section. I thought this was the best location...

(I apologize in advance if I use wrong 'azure' terms.)

We have a Blazor Server app registered in Azure (via App Registration) and it is using .azurewebsites.net and B2C, custom domain.
We are using MSAL.net

We have several app registrations. One of them was called for example "OurCompanyApp" and other "OurCompanyApp Test".
We removed one of the apps (i believe) "OurCompanyApp **Test**" (but we needed to restore it later on).

During the deleting of the registered app called *OurCompanyApp Test* in the App registration section a property/setting was removed **in another app registration** with a similar resource name (*OurCompanyApp*)!! *(don't know if it is also related due to the fact that our tenantname is also similar as the resource name)*

The setting "Access tokens (used for implicit flows)' was unchecked in "OurCompanyApp" when we removed "OurCompanyApp Test".

As a result each time when we opened Visual Studio 2022 to debug locally we received a null value for our token when using AcquireTokenSilent. We were not able to login anymore.

By checking the option "Access tokens (used for implicit flows)" again, all was fine again.

After a search we have found somebody who reported a similar issue who mentioned an internal translation of a domain which sounds very similar (*the internal resource name translation*) to what we have experienced:
https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad/azure-b2c-owin-redirect-uri-mismatch-when-using-custom-domain/m-p/103230

> UPDATE: **I determined that because the B2C directory was setup with a custom domain name of ourdomain.com), there must have been an internal translation of that domain to the resource name (appname.onmicrosoft.com).**  
>
> myapp.ourdomain.com --> myapp.appname.onmicrosoft.com.
>
> This was confirmed by sending that redirect URL in the request, but configuring the B2C application reply URL to myapp.appname.onmicrosoft.com.  There was no problem that the parameter didn't match up to the reply URL configured in B2C, but obviously I simply received a 404 since myapp.appname.onmicrosoft.com doesn't exist.
>
> By creating a brand new B2C tenant/directory, and using only the appname.onmicrosoft.com resource name (no custom domain on the directory), the original problem has been resolved.

Hope somebody picks this up, as this feels like a "bug" and you can really waste HOURS by this.

**Comment by bgavrilMS** [comment]
There's nothing the SDK can do about this, so I'm going to close it. Hopefully ppl running into this kind of problem will find the issue via search.
