### ISSUE TITLE
ROPC flow still doesn't work with MSAL .Net

### ISSUE THREAD

**Issue by cotepatrice** [AzureAD/microsoft-authentication-library-for-dotnet#3766]
I've followed [this tutorial](https://learn.microsoft.com/en-us/azure/active-directory-b2c/add-ropc-policy?tabs=applications-legacy&pivots=b2c-custom-policy) from Microsoft to create my ROPC flow. It works absolutely fine when I call it from Postman with the url like "https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/B2C_1A_ROPC_AUTH/oauth2/v2.0/token". In the body I pass the client ID, the scope, username, password and grant_type = "password".

It returne a nice token with everything I need in it (as defined in my B2C_1A_ROPC_AUTH custom policy).

But As soon as I try to call it with MSAL.Net, I always get a "404", like if the user doesn't exists.

Here's my code sample, [based on your own document](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#authority-for-a-b2c-tenant-and-policy) in this repo :

```csharp
public static Task<string> GetRPOCTokenAsync(string clientId, string userName, string pwd, List<string> scopes)
{
	IPublicClientApplication espaceClientApp;
	espaceClientApp = PublicClientApplicationBuilder
	.Create(clientId)
	.WithB2CAuthority("https://mytenant.b2clogin.com/ftp/mytenant.onmicrosoft.com/B2C_1A_ROPC_AUTH")
	.Build();

	AuthenticationResult authResult = null;
	var accounts = await espaceClientApp.GetAccountsAsync("B2C_1A_ROPC_AUTH");

	if (accounts.Any())
	{
		try
		{
			// Attempt to get a token from the cache (or refresh it silently if needed)
			authResult = await espaceClientApp.AcquireTokenSilent(scopes, accounts.FirstOrDefault())
				.ExecuteAsync();
		}
		catch (MsalUiRequiredException)
		{
			// No token in the cache for the account. Will proceed below
		}
	}

	// Cache empty or no token for account in the cache, attempt by username/password
	if (authResult == null)
	{
		var securePassword = new SecureString();
		foreach (char c in pwd)
		{
			securePassword.AppendChar(c);  // keystroke by keystroke
		}

		try
		{
			authResult = await espaceClientApp.AcquireTokenByUsernamePassword(scopes, userName, securePassword).ExecuteAsync();
		}
		catch (Exception ex)
		{
			throw new ApplicationException(ex.Message);
		}
		
	}

	if (authResult == null)
	{
		throw new ApplicationException("Unable to reach AAD B2C service for authentication.");
	}

	return authResult.AccessToken;
}
```

For some reason, the custom policy doesn't even seem to be called as I see no trace in DialogInsight but I see those linked to my previous calls in Postman (and yes, I've waited and waited and refreshed over and over again, there's no sign of it). So it looks that it might be linked to the Authorithy definition or something? Any idea?

P.S. I doubled checked my client id, username, password infos in debug . They are the absolute same as the ones I used in Postman.

**Comment by bgavrilMS** [comment]
I think you need to use "tfp" and not "ftp" in the authority URL

**Comment by cotepatrice** [comment]
@bgavrilMS Thanks! I was so focused on params that I totaly missed this typo.

Also I updated MSAL to latest version (2.24) and noticed that the call with SecureString is obsolete and we should now pass the password in clear.

**Comment by bgavrilMS** [comment]
Thanks for the update @cotepatrice . Latest MSAL version is 4.47.2 https://www.nuget.org/packages/Microsoft.Identity.Client 

We may un-obsolete that API because it's used so much. But SecureString really does not provide any security benefit, particularly on .net core
