### ISSUE TITLE
[Bug] ATS with MSA-PT on MSALRuntime Broker fails to get token

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3772]
- Acquire a MSA-PT token with ATI
- GetAccounts
- Use the MSA account to acquire token silently

Error : {Status: ApiContractViolation
Error: 0x80860001
Context: Error
Tag: 0x21420083} 

Actual : MSA-PT ATS with broker should work

**Dev App Repro :** 

![image](https://user-images.githubusercontent.com/90415114/198750228-6a33de54-ce28-4ddf-b487-d4e2b6d70a70.png)

**Comment by gladjohn** [comment]
In this scenario the authenticationRequestParameters.Authority is set to `{https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/}`, but changing to to `https://login.microsoftonline.com/organizations` works

[Current code is](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs#L163) ,

```cs
           var authParams = new NativeInterop.AuthParameters
                (authenticationRequestParameters.AppConfig.ClientId,
                authenticationRequestParameters.Authority.AuthorityInfo.CanonicalAuthority.ToString());
```

It should be, 
```cs
            var authority =
                isMsaPassthrough ?
                "https://login.microsoftonline.com/organizations" :
                authenticationRequestParameters.Authority.AuthorityInfo.CanonicalAuthority.ToString();

            var authParams = new NativeInterop.AuthParameters
                (authenticationRequestParameters.AppConfig.ClientId,
                authority);
```

**Comment by bgavrilMS** [comment]
This is a problem of the dev app, not for WAM.

**Comment by bgavrilMS** [comment]
I have not heard about this issue being reported by a customer? Has it been fixed?

**Comment by bgavrilMS** [comment]
Closing, please reopen if actual.
