### ISSUE TITLE
[Feature Request] Authority Validation enhacements

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3775]
This is a consistency item. 

Spec is here: https://microsoft.sharepoint.com/:w:/t/ADAL/ESzbQvzlMuBDjAsqfaHdjNUBsTmwIUR5g17IAY4rvOY_Hw?e=7dv5hZ 

Tasks 

- [x] Implement phase 2 `WithInstanceDiscoevryEndpoint("DISABLED")` which turns off all instance discovery 
- [ ] Ensure ESTS-R scenarios work in conjunction with this setting
- [ ] Testing

@rayluo to confirm that only phase 2 is required and if phase1 ("WithKnownAuthorityHosts") is optional / recommended etc.

**Comment by rayluo** [comment]
> @rayluo to confirm that only phase 2 is required and if phase1 ("WithKnownAuthorityHosts") is optional / recommended etc.

Yes. Also, [that internal specs](https://microsoft.sharepoint.com/:w:/t/ADAL/ESzbQvzlMuBDjAsqfaHdjNUBsTmwIUR5g17IAY4rvOY_Hw?e=7dv5hZ) grew along with the lengthy conversation. If you just want to focus on what ended up happening, [this implementation PR in MSAL Python](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/496) shipped only a boolean instance_discovery=True or False. You can for example take a look into its unit test cases.
