### ISSUE TITLE
[Bug] Xamarin Forms iOS broker authentication doesn't work in combination with Microsoft Authenticator

### ISSUE THREAD

**Issue by DaniRvd** [AzureAD/microsoft-authentication-library-for-dotnet#3782]
**Logs and network traces**
I added to files as attachment  to this item on of the contains all log registerd on iOS tablet, the second one contains only the errors

**Which version of MSAL.NET are you using?**
 MSAL.NET 4.47.0, 4.47.1, 4.47.2

**Platform**
Xamarin Forms iOS project

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
The issue is appearing on iOS tablet OS version 15.7 when using MSAL for acquiring token with broker and on device is installed Microsoft Authenticator.
 
When trying to get the token MS authenticator is opened, after selecting account the authenticator will be  close and the application will be restarted

**Is this a new or existing app?**
 The app is in production, and I have upgraded to a new version of MSAL.

**Repro**

```csharp
var your = (code) => var pca = PublicClientApplicationBuilder.Create(authenticationService.ClientApplicationId)
                    .WithIosKeychainSecurityGroup("com.microsoft.adalcache")
                    .WithBroker()
                    .WithRedirectUri("...")
                    .Build();
```

**Expected behavior**
After selecting the account in authenticator then application should use the account to generate a token and authenticate the user

**Actual behavior**
Application is restarted and you should take the login process from beginning, in this way you're in a infinite loop and the login process will never end  
If MS authenticator is not installed, then the authentication with Brocker is working without no issue 

**Possible solution**
-

**Additional context / logs / screenshots / links to code**

I attached here a screen recording with issue reproduction, device logfiles, test project source code

Device logs

[UserDetailsClientLogs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/9919871/UserDetailsClientLogs.txt)
[UserDetailsClientFaults.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/9919876/UserDetailsClientFaults.txt)

Reproduction Steps

https://user-images.githubusercontent.com/20532118/199480498-40a64f94-3cdf-4c77-8440-76dedc4ee1a3.mp4

Source Code
The source code can be found at bellow link or download the archive attached to this item
https://github.com/Azure-Samples/active-directory-xamarin-native-v2

[2-With-broker.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/9919939/2-With-broker.zip)

**Comment by bgavrilMS** [comment]
Just to understand, does this problem occur after upgrading MSAL library?

**Comment by DaniRvd** [comment]
No, I migrated from ADAL to MSAL because I need to support federated accounts. For this reason, migrated to MSAL with broker.
It seems to work fine is the Microsoft authenticator is not installed on the device. If the authenticator is installed, after selecting the account in authenticator the application is restarted (see above video).
MSAL versions which I completed in the description are the version with which I tested in the test project and in our application.

So in order to respond to your question is not happening after upgrading MSAL library.

**Comment by bgavrilMS** [comment]
@SameerK-MSFT - can you pls provide a suggestion on how to unblock the folks here? The logs show that AcquireTokenInteractive with broker is happening but then failing. Is this a regression?

default	12:47:37.356192+0200	UserDetailsClientiOS	True MSAL 4.47.0.0 MSAL.Xamarin.iOS Mono 6.12.0 (2020-02/dffa5ab9224) 15.7 [2022-11-02 10:47:37Z] Valid MSAL style redirect Uri detected.

default	12:47:37.356230+0200	UserDetailsClientiOS	True MSAL 4.47.0.0 MSAL.Xamarin.iOS Mono 6.12.0 (2020-02/dffa5ab9224) 15.7 [2022-11-02 10:47:37Z] Starting iOSBroker:AcquireTokenInteractiveAsync

default	12:47:37.363951+0200	UserDetailsClientiOS	True MSAL 4.47.0.0 MSAL.Xamarin.iOS Mono 6.12.0 (2020-02/dffa5ab9224) 15.7 [2022-11-02 10:47:37Z] GetOrCreateBrokerKey - found an existing key

default	12:47:37.369546+0200	UserDetailsClientiOS	True MSAL 4.47.0.0 MSAL.Xamarin.iOS Mono 6.12.0 (2020-02/dffa5ab9224) 15.7 [2022-11-02 10:47:37Z] The SecStatusCode from trying to get the broker application token is: SecStatusCode: ItemNotFound

default	12:47:37.370373+0200	UserDetailsClientiOS	True MSAL 4.47.0.0 MSAL.Xamarin.iOS Mono 6.12.0 (2020-02/dffa5ab9224) 15.7 [2022-11-02 10:47:37Z] Invoking the iOS broker

default	12:47:37.370560+0200	UserDetailsClientiOS	True MSAL 4.47.0.0 MSAL.Xamarin.iOS Mono 6.12.0 (2020-02/dffa5ab9224) 15.7 [2022-11-02 10:47:37Z] iOS Broker Payload: authority=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2F&scope=User.Read&client_id=4a1aa1d5-c567-49d0-ad0b-cd957a47f842&correlation_id=312242e4-e0df-4fa3-8d59-62a1bab71deb&client_version=4.47.0.0&intune_enrollment_ids=&intune_mam_resource=&redirect_uri=msauth.com.yourcompany.UserDetailsClient%3A%2F%2Fauth&username=&extra_oidc_scopes=openid+offline_access+profile&prompt=select_account&broker_key=KE67XU1bRjRONt5Agt_yrdIsVKl4WKkv_U7Fwz0pxvQ&msg_protocol_ver=3&broker_nonce=204d99e3-d1a7-405c-b2cb-94d2c12c6bdc

**Comment by SameerK-MSFT** [comment]
Sorry about the delayed response. It looks like there are two apps mentioned here:
1. In production
2. Sample
Does it happen in the sample app with no changes? 

In the other (i.e. production) app, are you setting ViewController as parent window?
Is the call from the UIThread?

**Comment by DaniRvd** [comment]
Hi @SameerK-MSFT !
Indeed, there are two apps, production and sample app, the issue is happening on both applications with no change when Microsoft Authenticator is installed on the device.
Yes, in the production app the parent window is set and like in the sample app authentication is working if only if Microsoft Authenticator is not installed on the device.

**Comment by DaniRvd** [comment]
Related to  UI thread , just tried to call AquireTokenInteractive from UI thread, but no difference, issue is still reproducible.
![image](https://user-images.githubusercontent.com/20532118/205270196-134c2816-1785-4f34-9954-3ec76f420c0f.png)

**Comment by bgavrilMS** [comment]
We will probably need some broker logs for this. @SameerK-MSFT @trwalke - can you help to put toghether troubleshooting steps for broker scenarios, i.e. how to get broker logs?

**Comment by SameerK-MSFT** [comment]
I ran the sample with the latest i.e. 4.49.1 and it runs fine. It was tested using iPhone 6s os ver 15.7. Does this happen only on "iOS tablet" or also on iPhone?

**Comment by DaniRvd** [comment]
Do you have Microsoft Authenticator installed on your iPhone?
If yes I'll try also with the latest version of MSAL, on the tablet, we only deliver our for the tablets

**Comment by SameerK-MSFT** [comment]
Yes. I do have Microsoft Authenticator installed and tested with it. The test was done only on the iPhone 6s. @z0mero did you face the issue on Tablet/iPhone/Both?

**Comment by z0mero** [comment]
I have this problem on iPad, i did not test it on iPhone, because my app is available only for iPad devices. But i tested it on multiple versions of iPad and the issue is reproducible on each of them.

**Comment by SameerK-MSFT** [comment]
I tested this with MSAL.NET 4.49.1 on iPad and it works fine with Microsoft Authenticator. Could not repro with no changes in the sample. One thing that I noticed in your code
![](https://user-images.githubusercontent.com/20532118/205270196-134c2816-1785-4f34-9954-3ec76f420c0f.png)
is that is is missing ConfigureAwait(false); Please add it after ExecuteAsync(). (Yes. It is missing from our sample also). And let me know how it goes. Thanks

**Comment by SameerK-MSFT** [comment]
Closing due to no response.
