### ISSUE TITLE
[Feature Request] Update/ add to data logged to ITelemetryClient

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#3784]
As discussed with E&D team following changed to be made to the telemetry client logging:
* Api id to identify the type of request for example OBO/ Client credential
* Type of confidential client for example if it is SNI based auth/ Certificate/ Assertion/ Managed Identity. 
* Log data for each resource in the scopes list.
* Error codes: STS error code or MsalException error code (for client errors) or Exception type in the ErrorCode field.
* Log token type as an enum instead of pop token.
* Log the endpoint
* Log the type of cache used. L1/ L2. This data can be stored in the TokenSource field. To make this change we need to expose a variable in [TokenCacheNotificationArgs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs) and pass this data back from Microsoft.Identity.Web.

* In case of L2 cache failure (not cache miss, but for example timeout etc.), we want this logged as well. Perhaps a special TokenSource? (consider tracking separately)

The details are listed in [this](https://microsoft-my.sharepoint-df.com/:w:/p/nebharg/EWrRAFHR6VdGvx5i_-uCZiUBROlxzCXZzLdRUJ8ePTKkgw?e=Pe1zcS) document.

**Comment by bgavrilMS** [comment]
2 small updates / clarifications: 

- we'd like to log separately - resource and scope (please only do string parsing if telemetry client is used)
- for errors, we'd like to log separately the error string and the error code

<img width="327" alt="image" src="https://user-images.githubusercontent.com/12273384/226400362-77d10823-042f-43ee-875c-e5688965a8b4.png">
