### ISSUE TITLE
MSAL fails on UWP when using certain claims.

### ISSUE THREAD

**Issue by franswah** [AzureAD/microsoft-authentication-library-for-dotnet#379]
Issue appears to be related to the number of claims, fails after a certain number of claims is added.

Claims added to Policy that caused the failure:

![image](https://cloud.githubusercontent.com/assets/10676451/25587469/150f13da-2e59-11e7-8bbb-5ab2bb411e93.png)

![image](https://cloud.githubusercontent.com/assets/10676451/25587574/82bae12a-2e59-11e7-8fac-c98f3c132ad9.png)

**Comment by kpanwar** [comment]
this is completely from the B2C service side. The

**Comment by kpanwar** [comment]
This is not related to the library. B2C service is working to reduce their auth code size.
