### ISSUE TITLE
[Bug] AcquireTokenInteractive - Interactive login window vanishes before user can login

### ISSUE THREAD

**Issue by JPhilC** [AzureAD/microsoft-authentication-library-for-dotnet#3790]
**Which version of MSAL.NET are you using?**
4.48.0.0

**Platform**
.NET Framework 4.7,1

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive Azure B2C

**Is this a new or existing app?**
The app is in production and has been working fine for a number of years. As of 5th November the login page flashes up and disappears preventing users from logging in.

User
**Repro**

```csharp

/// Creation of the PublicClientApplication
            var builder = PublicClientApplicationBuilder.Create(Constants.B2CClientID)
                  .WithB2CAuthority(Constants.B2CAuthoritySignIn)
                  .WithRedirectUri($"msal{Constants.B2CClientID}://auth")
                  .WithLogging(MyLoggingMethod, Microsoft.Identity.Client.LogLevel.Verbose,
                       enablePiiLogging: true,
                       enableDefaultPlatformLogging: false);
            return builder.Build();

/// Following MsalUiRequiredException the following method is called.
      private async Task<Models.LoginResult> SignInInteractively()
      {
         IEnumerable<IAccount> accounts = await _app.PublicClientApp.GetAccountsAsync();

         AuthenticationResult authResult = await _app.PublicClientApp.AcquireTokenInteractive(Constants.B2CScopes)
             .WithAccount(GetAccountByPolicy(accounts, Constants.B2CPolicySignIn))
             .ExecuteAsync();

         var newContext = new Models.LoginResult() { UserId = authResult.UniqueId, AccessToken = authResult.AccessToken };
         return newContext;
      }

```

**Expected behavior**
The usual microsoft login window should be displayed allowing the user to enter their login details. 

**Actual behavior**
The customer reported on 5th November than their users could no longer access the system. I can see from my system that the login window flashes up and vanishes. An MsalClientException " The browser based authentication dialog failed to complete. Reason: The server understood the request, but is refusing to fulfill it." is thrown.

The system has been working faultlessly for a number of years. I attach a verbose log from the point of the AcquireTokenInteractive() call.

Nothing has been changed in the application code or in the Azure configuration for a number of years.

**Additional context / logs / screenshots / links to code**
**Logs and network traces**
MSAL Info True True MSAL 4.48.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-11-06 18:04:23Z - ac4d2448-778f-4a6b-a9e8-463972878a34] MSAL MSAL.Desktop with assembly version '4.48.0.0'. CorrelationId(ac4d2448-778f-4a6b-a9e8-463972878a34)
MSAL Info True True MSAL 4.48.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-11-06 18:04:23Z - ac4d2448-778f-4a6b-a9e8-463972878a34] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent: 
Prompt: not_specified
HasCustomWebUi: False

MSAL Info True True MSAL 4.48.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-11-06 18:04:23Z - ac4d2448-778f-4a6b-a9e8-463972878a34] 
=== Request Data ===
Authority Provided? - True
Client Id - db889216-edca-4368-983a-37ece8c32ece
Scopes - https://smalegalb2c.onmicrosoft.com/cms/access
Redirect Uri - msaldb889216-edca-4368-983a-37ece8c32ece://auth
Extra Query Params Keys (space separated) - 
ClaimsAndClientCapabilities - 
Authority - https://login.microsoftonline.com/tfp/smalegalb2c.onmicrosoft.com/b2c_1_sign_in/
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint - 
IsBrokerConfigured - False
HomeAccountId - 
CorrelationId - ac4d2448-778f-4a6b-a9e8-463972878a34
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

MSAL Info True True MSAL 4.48.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-11-06 18:04:23Z - ac4d2448-778f-4a6b-a9e8-463972878a34] === Token Acquisition (InteractiveRequest) started:
	Authority: https://login.microsoftonline.com/tfp/smalegalb2c.onmicrosoft.com/b2c_1_sign_in/
	Scope: https://smalegalb2c.onmicrosoft.com/cms/access
	ClientId: db889216-edca-4368-983a-37ece8c32ece
	
MSAL Info True True MSAL 4.48.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-11-06 18:04:23Z - ac4d2448-778f-4a6b-a9e8-463972878a34] [Instance Discovery] Skipping Instance discovery for non-AAD authority. 
MSAL Info True True MSAL 4.48.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-11-06 18:04:23Z - ac4d2448-778f-4a6b-a9e8-463972878a34] Using legacy embedded browser.
MSAL Verbose True True MSAL 4.48.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-11-06 18:04:23Z - ac4d2448-778f-4a6b-a9e8-463972878a34] [Legacy WebView] Navigating to 'https://login.microsoftonline.com/tfp/smalegalb2c.onmicrosoft.com/b2c_1_sign_in/oauth2/v2.0/authorize?scope=https://smalegalb2c.onmicrosoft.com/cms/access openid profile offline_access&response_type=code&client_id=db889216-edca-4368-983a-37ece8c32ece&redirect_uri=msaldb889216-edca-4368-983a-37ece8c32ece://auth&client-request-id=ac4d2448-778f-4a6b-a9e8-463972878a34&x-client-sku=MSAL.Desktop&x-client-ver=4.48.0.0&x-client-cpu=x64&x-client-os=Windows 10 Enterprise&prompt=select_account&code_challenge=9iOBtXqqtNTaTJ6d9WNIp4N9IKnWjEAezb6RPVLJxwg&code_challenge_method=S256&state=683385de-1fd7-4dea-943f-743f9f2fa0ea488a653c-0123-4cc7-bbb0-6911c990751b&client_info=1&response_mode=form_post'.
MSAL Error True True MSAL 4.48.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-11-06 18:04:24Z - ac4d2448-778f-4a6b-a9e8-463972878a34] MSAL.Desktop.4.48.0.0.MsalClientException: 
	ErrorCode: authentication_ui_failed
Microsoft.Identity.Client.MsalClientException: The browser based authentication dialog failed to complete. Reason: The server understood the request, but is refusing to fulfill it.
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WindowsFormsWebAuthenticationDialog.ShowBrowser(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WindowsFormsWebAuthenticationDialog.OnAuthenticate(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WindowsFormsWebAuthenticationDialogBase.AuthenticateAAD(Uri requestUri, Uri callbackUri, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.InteractiveWebUI.OnAuthenticate(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WebUI.<>c__DisplayClass20_0.<AcquireAuthorizationAsync>b__0()
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WebUI.<AcquireAuthorizationAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceVerifierAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in mscorlib.dll
Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in mscorlib.dll
Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in mscorlib.dll
Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in mscorlib.dll
Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in mscorlib.dll
[Login] Error = The browser based authentication dialog failed to complete. Reason: The server understood the request, but is refusing to fulfill it.

**Comment by bgavrilMS** [comment]
That error code is indicative of the embedded browser encountering an error in the authorization flow. The error is telling the browser that a page is forbidden. This can happen if the server (B2C) or the Identity Provider (e.g. Google, Facebook etc.) have made changes to their auth flow and have made a mistake. Most common is to have some image with http url instead of https. 

Possible workarounds: 

1. Try to use a WebView2 based browser. We provide one, just reference Microsoft.Identity.Client.Desktop and add `WithDesktopFeatures` when creating the public client application object.
2. Try to use the system browser if possible, via `WithUseEmbeddedWebview(false)`

Ideally you should open a service issue via Azure Portal.

**Comment by JPhilC** [comment]
Thanks for the suggestions. For some reason the  Microsoft.Identity.Client.Desktop nuget package is not visible in Nuget manager and when I install it using Package Manager it causes the error:

CS1703 C# Multiple assemblies with equivalent identity have been imported: and. Remove one of the duplicate references.

Since I posted the original issue I realise that I have missed a notice posted on the Azure AD B2C blade stating that the login.microsoftonline.com endpoint for Azure AD B2C tenants is being retired. I do use this endpoint so that may be the problem.

**Comment by bgavrilMS** [comment]
Oh, ok, yes. Please the B2C specific authority and let us know if it fixes the issue.

**Comment by JPhilC** [comment]
That was the problem. I changed the Url used in the WithB2CAuthority method from "https://login.microsoftonline.com/tfp/[Tenant].onmicrosoft.com/b2c_1_sign_in/oauth2/v2.0/authorize" to "https://[Tenant].b2clogin.com/tfp/[Tenant].onmicrosoft.com/b2c_1_sign_in/oauth2/v2.0/authorize" and this fixed the immediate problem of the login page vanishing before users could log in.

I then had another problem in that access to the App Service was not being allowed. I needed to go into each of the App Service Authentication blades and update the Microsoft identity provider Issuer URL to replace the login.microsoft.com part with [Tenant].b2clogin.com.
