### ISSUE TITLE
[Bug] PublicClientApplication.GetAccountsAsync() crash - Key not valid for use in specified state

### ISSUE THREAD

**Issue by RhomGit** [AzureAD/microsoft-authentication-library-for-dotnet#3793]
**Logs and network traces**
```
Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at TokenCacheHelper.BeforeAccessNotification(TokenCacheNotificationArgs args)
   at Microsoft.Identity.Client.TokenCache.<Microsoft-Identity-Client-ITokenCacheInternal-OnBeforeAccessAsync>d__110.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Identity.Client.Cache.CacheSessionManager.<RefreshCacheForReadOperationsAsync>d__17.MoveNext()
```

**Which version of MSAL.NET are you using?**
4.46.0

**Platform**
.NET 4.8

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x ] Interactive

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**
https://github.com/RhomGit/MSALDesktopRepro
The specific line of crash is here: https://github.com/RhomGit/MSALDesktopRepro/blob/0d18219c59011d842f9c0cf8d7650093162a3760/Auth.cs#L93

**Additional context / logs / screenshots / links to code**
This is happening on a fresh laptop install for one of our remote clients. Have uninstalled/reinstalled etc. and I don't know why this is crashing. This code is working on hundreds of installs and I'm concerned that this might be something new. Any hints as to what this might be?

```
accounts = await pca.GetAccountsAsync();
```

**Comment by bgavrilMS** [comment]
Hi @RhomGit - this is coming from the token cache callbacks you defined, particularly from the DPAPI calls https://github.com/RhomGit/MSALDesktopRepro/blob/0d18219c59011d842f9c0cf8d7650093162a3760/TokenCacheHelper.cs#L27

Did you roam the data maybe? DPAPI only works on 1 machine afaik. Sadly, neither Windows, Mac nor Linux offer bulletproof encryption at rest APIs, there is always some case where it doesn't work. 

I suggest you use the token caching as described here: https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=desktop - the same error might occur, but it will be silently ignored. Caching will only work in memory for the duration of the app. You can choose to store tokens unencrypted if this is ok from a security point of view (e.g. ask the end-user to save the tokens on an encrypted drive or smth).

**Comment by RhomGit** [comment]
Hi @bgavrilMS - thanks for this. It was a roaming profile and I'll look to workaround.

**Comment by bgavrilMS** [comment]
Thanks for confirming @RhomGit. DPAPI can in theory be used to support roaming profiles (https://stackoverflow.com/questions/27789485/does-protecteddata-work-on-multiple-computers) but we've decided to use it as defailt (only for local computers)

Another way of enabling SSO in your scenario is to use WAM + default OS account, see https://github.com/bgavrilMS/MSAL-SingleAccount-SSO

**Comment by RhomGit** [comment]
No worries @bgavrilMS 

Just fyi I have now encountered a second client with this issue on our latest build (not roaming this time).
Have updated to Microsoft.Identity.Client 4.48.1 and it still persists.

I'll look into switching out to the new token caching method you described above.
