### ISSUE TITLE
EuropeWest does not work when using Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion 

### ISSUE THREAD

**Issue by jsquire** [AzureAD/microsoft-authentication-library-for-dotnet#3813]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#32566](https://github.com/Azure/azure-sdk-for-net/issues/32566).

## Details

Microsoft.Identity.Client.ConfidentialClientApplicationOptions points to this document page to instruct us to select AzureRegion but EuropeWest is not a valid region.
The correct input is WestEurope.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1e0fc3-2a82-bac4-fda7-69488e552963
* Version Independent ID: 0eb49f0b-04ff-bd8d-6247-8300eced728b
* Content: [Region Class (Microsoft.Azure.Management.ResourceManager.Fluent.Core) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.region?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.ResourceManager.Fluent.Core/Region.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ResourceManager.Fluent.Core/Region.xml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bgavrilMS** [comment]
@Protheon - are you letting the SDK auto-discover the region or do you set the region name?

**Comment by Protheon** [comment]
hi @bgavrilMS. let me confirm that on monday to be 100% sure of what i'm saying, not currently at my work laptop.

**Comment by Protheon** [comment]
hi @bgavrilMS. Here are the findings:
If I set Microsoft.Identity.Client.ConfidentialClientApplicationOptions.AzureRegion = "EuropeWest" (as visible in the aforementioned documentation) I get the error:
'No such host is known. (europewest.r.login.microsoftonline.com:443)'

If I set to "WestEurope" I get the error:
'AADSTS100007: AAD Regional ONLY supports auth either for MSIs OR for requests from MSAL using SN+I for 1P apps or 3P apps in Microsoft infrastructure tenants.'

If it do not set any AzureRegion, it works.

**Comment by bgavrilMS** [comment]
Thanks @Protheon - I can "decrypt" the error message for you: 

- "regional feature only works for 1P apps" -  this means applications registered by Microsoft team. The regional feature is not supported by 3P, i.e. 3rd party applications. 
 
I assume you are not internal to Microsoft? Regional auth is currently rolled out to Microsoft services only. There are plans to make regional auth available to all customers, both internal and external, but I do not have an ETA. It is possible that the feature will be enabled without developers opting in, for example it will be handled exclusively by Azure infrastructure (DNS server magic).

**Comment by Protheon** [comment]
Thanks for the info @bgavrilMS . I will keep it unset then. Still, I would recommend updating the documentation because "EuropeWest" doesnt seem to be a valid region either for 1P or 3P if i understand correctly.
You may close this issue at your discression.
Best regards!
