### ISSUE TITLE
Unable to get token using EWS OAuth for Outlook - var authResult = await pca.AcquireTokenInteractive(ewsScopes).ExecuteAsync();

### ISSUE THREAD

**Issue by Tayyab53** [AzureAD/microsoft-authentication-library-for-dotnet#3816]
public async System.Threading.Tasks.Task ProcessFiles()
        {
            var pcaOptions = new PublicClientApplicationOptions
            {
                ClientId = ConfigurationManager.AppSettings["appId"],
                TenantId = ConfigurationManager.AppSettings["tenantId"]
            };

            var pca = PublicClientApplicationBuilder
                .CreateWithApplicationOptions(pcaOptions).Build();

            // The permission scope required for EWS access
            var ewsScopes = new string[] { "https://outlook.office365.com/EWS.AccessAsUser.All" };
            
            try
            {
                // Make the interactive token request
                var authResult = await pca.AcquireTokenInteractive(ewsScopes).ExecuteAsync();

                // Configure the ExchangeService with the access token
                var ewsClient = new ExchangeService();
                ewsClient.Url = new Uri("https://outlook.office365.com/EWS/Exchange.asmx");
                ewsClient.Credentials = new OAuthCredentials(authResult.AccessToken);

**Comment by pmaytak** [comment]
@Tayyab53 What is the issue? Are you getting an error? What MSAL version do you use?

**Comment by Tayyab53** [comment]
@pmaytak: It's not giving any error during the debug of the application. The moment control goes past the below line of code, the debugging gets terminated:

var authResult = await pca.AcquireTokenInteractive(ewsScopes).ExecuteAsync();

Note: The client id and the tenant id to register the application have been provided by Active Directory team, so not sure any changes to the manifest file need to be done by the team?

Please suggest.

**Comment by pmaytak** [comment]
What type of app is this? Console? Win Forms?

If it's a Windows app, you have to call AcquireTokenInteractive on a UI thread to prevent any deadlocks with synchronization context. See wiki, which also has links to samples at the bottom: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withparentactivityorwindow

What exception type do you catch in that try block? You can make sure it's generic Exception, so the error is not bubbled up and crashes the app.

You can also enable Verbose MSAL logging: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Logging

**Comment by Tayyab53** [comment]
@pmaytak: It's a Console App, I have used generic Exception to catch all types of errors but still it terminates the debugging.

**Comment by pmaytak** [comment]
Try enabling the **verbose** logs to see what's the latest thing MSAL before the crash.

**Comment by Tayyab53** [comment]
@pmaytak: While trying to enable the verbose logs in console app, there are major code differences between https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth
AND
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Logging

Can you please send me the **EWS** OAuth Code to implement it in Console application since below code logic's doesn't seem to be working with Delegated Permissions:
https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth

**Comment by bgavrilMS** [comment]
Hi @Tayyab53 - your code is like

```csharp
var pca = PublicClientApplicationBuilder
    .CreateWithApplicationOptions(pcaOptions).Build();
```

Please change it to: 

```csharp
var pca = PublicClientApplicationBuilder
    .CreateWithApplicationOptions(pcaOptions)
    .WithLogging(new ConsoleLogger(), true)
    .Build();

public class ConsoleLogger : IIdentityLogger
        {
            public bool IsEnabled(EventLogLevel eventLogLevel)
            {
                return true;
            }

            public void Log(LogEntry entry)
            {
                Console.WriteLine($"{entry.EventLogLevel} - {entry.Message}");
            }
        }
```

**Comment by Tayyab53** [comment]
@bgavrilMS: Thanks for the code, I got the below in the console screen:

Informational - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:03:30Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] MSAL MSAL.Desktop with assembly version '4.48.1.0'. CorrelationId(1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08)

**Comment by Tayyab53** [comment]
Adding entire log:

**Note:** Removed Client Id and Tenant Id

Informational - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:03:30Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] MSAL MSAL.Desktop with assembly version '4.48.1.0'. CorrelationId(1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08)
Informational - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:05:57Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent:
Prompt: not_specified
HasCustomWebUi: False

Informational - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:05:59Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08]
=== Request Data ===
Authority Provided? - True
Client Id - 
Scopes - https://outlook.office365.com/EWS.AccessAsUser.All
Redirect Uri - 
Extra Query Params Keys (space separated) -
ClaimsAndClientCapabilities -
Authority - https://login.microsoftonline.com/
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint -
IsBrokerConfigured - False
HomeAccountId -
CorrelationId - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

Informational - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:06:27Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] === Token Acquisition (InteractiveRequest) started:
        Authority: https://login.microsoftonline.com/
        Scope: https://outlook.office365.com/EWS.AccessAsUser.All
        ClientId:

Informational - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:06:30Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] [Region discovery] Not using a regional authority.
Verbose - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:06:32Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False.
Informational - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:06:34Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] Fetching instance discovery from the network from host login.microsoftonline.com. Endpoint https://login.microsoftonline.com/common/discovery/instance.
Verbose - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:06:36Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] Starting [Oauth2Client] Sending GET request
Verbose - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:06:39Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] Starting [HttpManager] ExecuteAsync
Verbose - True MSAL 4.48.1.0 MSAL.Desktop 4.7.2 Windows 10 Enterprise [2022-11-23 14:06:42Z - 1e5575ea-30ad-49d2-ad69-0ab6d7ae6e08] [HttpManager] Sending request. Method: GET. URI: https://login.microsoftonline.com/common/discovery/instance.

**Comment by Tayyab53** [comment]
@bgavrilMS, @pmaytak: Can you please have a look at the above Verbose Logs. Please suggest is there any configuration missing.

**Comment by Tayyab53** [comment]
@bgavrilMS, @pmaytak, @bratsche, @RamonPage: Can someone look at the above Verbose Logs and suggest me further how to implement it

**Comment by pmaytak** [comment]
@Tayyab53 
- Are those all the logs the you get, then app crashes? Or does it hang? I don't see anything wrong so far. If does get stuck during the web request to instance discovery, it would at least end with a timeout exception. It's just strange that no exception is shown. Usually any exceptions would be printed to the console when app crashes. You can also check the Windows EventLog, maybe something's logged there.
- I assume when `AcquireTokenInteractive` is hit, you don't see any pop ups to login?
- Is your app supposed to be in the global cloud, or national ones?
- Can you attach a zipped project / repro? (make sure to remove secrets, app IDs)

**Comment by Tayyab53** [comment]
@pmaytak, @bgavrilMS: 

- These are the only logs that could generate before the app crashes.
- Yes the app crashes when "AcquireTokenInteractive" is hit without any message on the console or any pop-ups
- Not sure of the global cloud/national cloud
- **I have attached the app(zipped) format. Removed all Id's**
[EWS.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/10091042/EWS.zip)
**Also attaching the app permissions from Active Directory**
![image](https://user-images.githubusercontent.com/28978938/203958428-47909a8c-ed54-4eee-b7ff-17d953f716fe.png)

**Comment by bgavrilMS** [comment]
Please update Program.cs as: 

<img width="424" alt="image" src="https://user-images.githubusercontent.com/12273384/203977360-98697fba-3c35-45ee-a429-20461f2fa65a.png">


`ProcessFiles` is async, so you must wait for it to finish. .NET even gives you a warning about this

"warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call."

**Comment by Tayyab53** [comment]
@bgavrilMS, @pmaytak: When I use below code:
![image](https://user-images.githubusercontent.com/28978938/204001382-1d3dfbc3-d3ac-4308-936a-cfa488286fde.png)
it gives error: 
![image](https://user-images.githubusercontent.com/28978938/204001529-c27ffbf4-50f4-4941-aebf-fe42fdc9d614.png)

When I add Main method, it gives similar await warning and crashes at: "AcquireTokenInteractive"
![image](https://user-images.githubusercontent.com/28978938/204002418-4df2a583-4102-4486-ba10-a0b6e0d7ca1e.png)

**Comment by Tayyab53** [comment]
@bgavrilMS: When I run the app **without** debug mode, it is waiting for key to terminate the app, means it doesn't go beyond the line: "AcquireTokenInteractive"
![image](https://user-images.githubusercontent.com/28978938/204003154-88e5454e-d0f7-4fab-aa77-d37f2679e0c7.png)

**Comment by bgavrilMS** [comment]
You must use the async / await pattern, for which I recommend you read about. 

See https://stackoverflow.com/questions/9208921/cant-specify-the-async-modifier-on-the-main-method-of-a-console-app

**Comment by Tayyab53** [comment]
Thank you. I am able to connect to the email account. 

But the login screen is popped-up during each time app is executed(Delegated Permission). Since the console application wil be scheduled using task scheduler, how can we avoid login screen pop-ups for task scheduler.
