### ISSUE TITLE
Allow usage of a previously generated device code

### ISSUE THREAD

**Issue by mattmsft** [AzureAD/microsoft-authentication-library-for-dotnet#3817]
**Is your feature request related to a problem? Please describe.**

A new device code is always generated when calling `AcquireTokenWithDeviceCode`
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow#code-snippet

**Describe the solution you'd like**

Please allow usage of a previously generated device code in `AcquireTokenWithDeviceCode`

**Describe alternatives you've considered**

Right now, the application needs to poll for the device code that is generated whenever `AcquireTokenWithDeviceCode` is called. This requires the application be running, if it is terminated the polling stops and the device code cannot be used again, even if it's approved after the application is terminated.

ADAL supported this by allowing fetching of a device code before polling for the result of that device code
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Device-profile-for-devices-without-web-browsers

**Comment by jmprieur** [comment]
What is your scenario, @mattmsft ?

**Comment by mattmsft** [comment]
https://learn.microsoft.com/en-us/azure/search/search-howto-index-sharepoint-online

Specifically, the device code flow section. We are generating the device code error, generating an error, exiting the indexer app, then the customer resumes the indexer app after they approve the device code and checks the cached code if it was approved

**Comment by jmprieur** [comment]
@mattmsft I understand that the coding pattern is different, but why do you want to expose the user to an error, and have them restart the indexer?

**Comment by bgavrilMS** [comment]
We discussed offline that team should be using OBO.
