### ISSUE TITLE
[Bug] Android.Content.PM.PackageManager+NameNotFoundException: com.microsoft.windowsintune.companyportal

### ISSUE THREAD

**Issue by MihaMarkic** [AzureAD/microsoft-authentication-library-for-dotnet#3819]
**Which version of MSAL.NET are you using?**
4.48.1

**Platform**
Xamarin/Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
Android 12, 11

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL. I was running 4.38.1 before and targeted SDK 28, while now it targets SDK 33.

**Repro**
Try authentication with MS ~~broker~~ Authenticator.

**Expected behavior**
Authentication should succeed.

**Actual behavior**
On some devices in production where previous version worked, this exception occurs:
Android.Content.PM.PackageManager+NameNotFoundException: com.microsoft.windowsintune.companyportal
Which is odd, because (if I'm not mistaken) company portal is a widget, at least at my test device it appears so.
Also on those devices the companyportal widget is present.

**Possible solution**
Factory restore devices with default set of apps works.

**Note**
I know I didn't provide much info, which is hard, since it happens only to some random production devices, though why would it seek com.microsoft.windowsintune.companyportal in first place?

**Comment by SameerK-MSFT** [comment]
Are you integrating with Intune SDK?

**Comment by MihaMarkic** [comment]
@SameerK-MSFT Below is what I use (from Microsoft.Identity.Client library).

```csharp
string[] Scopes = { "User.Read" };
var pca = CreateApplication();
var accounts = await pca.GetAccountsAsync();
try
{
    AuthenticationResult authResult = null;
    try
    {
        IAccount firstAccount = accounts.FirstOrDefault();
        authResult = await pca.AcquireTokenSilent(Scopes, firstAccount).ExecuteAsync();
    }
    catch (MsalUiRequiredException)
    {
        try
        {
            authResult = await pca.AcquireTokenInteractive(Scopes)
                                      .WithParentActivityOrWindow(this)
                                      .WithUseEmbeddedWebView(true)
                                      .WithPrompt(Prompt.NoPrompt)
                                      .ExecuteAsync();
        }
        catch (Exception ex)
        {
            return ...
        }
    }
    if (authResult != null)
    {
        return ...
    }
    return ...
}
catch (Exception ex)
{
    return ...
}

IPublicClientApplication CreateApplication()
{
    var builder = PublicClientApplicationBuilder
        .Create(ClientID)
        .WithTenantId(TenantId)
        .WithRedirectUri(MSBrokerRedirectUri)
        .WithBroker();
    return builder.Build();
}
```

**Comment by bgavrilMS** [comment]
Probably a bug on our side. When broker is enabled (WithBroker) we do look for both Authenticator and Company Portal. both of them can act as brokers.

@trwalke - do we look for Authenticator first and then Company Portal?

**Comment by bgavrilMS** [comment]
@MihaMarkic - I was wondering how you create the PCA object. Do you use `WithBroker(true)` ?
Would be good to have a stack trace of that exception.

Possible root cause is here: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs#L353

**Comment by MihaMarkic** [comment]
@bgavrilMS 
Ah, well, the code is still the same. But yes, it's using `true` since it's default value for `enableBroker` argument.

Here is the stack trace, looks like that method is the culprit, indeed
```
    Java.Interop
    JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
    Java.Interop
    JniPeerMembers+JniInstanceMethods.InvokeAbstractObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
    Android.Content.PM
    PackageManagerInvoker.GetPackageInfo (System.String packageName, Android.Content.PM.PackageInfoFlags flags)
    Microsoft.Identity.Client.Platforms.Android.Broker
    AndroidBrokerHelper.ReadCertDataForBrokerApp (System.String brokerPackageName)
    Microsoft.Identity.Client.Platforms.Android.Broker
    AndroidBrokerHelper.VerifySignature (System.String brokerPackageName)
    Microsoft.Identity.Client.Platforms.Android.Broker
    AndroidBrokerHelper.GetInstalledAuthenticator ()
    Microsoft.Identity.Client.Platforms.Android.Broker
    AndroidBrokerHelper.CanSwitchToBroker ()
    Microsoft.Identity.Client.Platforms.Android.Broker
    AndroidBrokerHelper.IsBrokerInstalledAndInvokable (Microsoft.Identity.Client.AuthorityType authorityType)
    Microsoft.Identity.Client.Platforms.Android.Broker
    AndroidBrokerFactory.GetInstalledBrokerAsync (Microsoft.Identity.Client.UI.CoreUIParent uIParent, Microsoft.Identity.Client.Core.ILoggerAdapter logger)
    Microsoft.Identity.Client.Platforms.Android.Broker
    AndroidBrokerFactory+<>c__DisplayClass3_0.<CreateBroker>b__0 ()
    Microsoft.Identity.Client.Platforms.Android.Broker
    AndroidBrokerFactory.CreateBroker (Microsoft.Identity.Client.UI.CoreUIParent uIParent, Microsoft.Identity.Client.Core.ILoggerAdapter logger)
    Microsoft.Identity.Client.Platforms.Android
    AndroidPlatformProxy.CreateBroker (Microsoft.Identity.Client.ApplicationConfiguration appConfig, Microsoft.Identity.Client.UI.CoreUIParent uiParent)
    Microsoft.Identity.Client
    ClientApplicationBase.GetAccountsFromBrokerAsync (System.String homeAccountIdFilter, Microsoft.Identity.Client.Cache.ICacheSessionManager cacheSessionManager, System.Threading.CancellationToken cancellationToken)
    Microsoft.Identity.Client
    ClientApplicationBase.GetAccountsInternalAsync (Microsoft.Identity.Client.TelemetryCore.Internal.Events.ApiEvent+ApiIds apiId, System.String homeAccountIdFilter, System.Threading.CancellationToken cancellationToken)
    Microsoft.Identity.Client
    ClientApplicationBase.GetAccountsAsync (System.Threading.CancellationToken cancellationToken)
    Microsoft.Identity.Client
    ClientApplicationBase.GetAccountsAsync ()
    MYAPP.Droid.Core
    CoreActivity`1[T].VerifyIntuneCredentialsAsync ()
    MYAPP.Droid.Core
    IntegratedLoginCoreActivity.DoLoginAsync (System.Threading.CancellationToken ct)
    android.content.pm.PackageManager$NameNotFoundException: com.microsoft.windowsintune.companyportal
    android.app.ApplicationPackageManager.getPackageInfoAsUser ApplicationPackageManager.java:278
    android.app.ApplicationPackageManager.getPackageInfo ApplicationPackageManager.java:250
```

**Comment by bgavrilMS** [comment]
Ack, we will need to discuss this with MSAL Android experts to see what's going on. Looks like there is an incompatibility between `AccountManager` and `PackageManager.GetPackageInfo`

**Comment by SkJonko** [comment]
Hi,
We have any update with this bug in MSAL ?
I encounter the same problem in my application in some Android Devices.

**Comment by MihaMarkic** [comment]
I think the solution is to update queries node in AndroidManifest.xml to something like sample below. Previously I've had only com.azure.authenticator set.
```xml
<queries>
	<!-- required for authentication starting with Android 12 -->
	<package android:name="com.azure.authenticator" />
       <package android:name="com.microsoft.windowsintune.companyportal" />
</queries>
```
@SkJonko @bgavrilMS

**Comment by bgavrilMS** [comment]
That makes sense. MSAL will try to communicate with Authenticator first, and if that isn't installed, with Company Portal. I guess the `PackageManager.GetPackageInfo` behavior changed in an Android API and for packages not listed in queries, it throws that exception.

We should update our docs and samples for this.

**Comment by SameerK-MSFT** [comment]
In Xamarin, we reference Mono.Android 9.0 and 10.0 That does not support API 33 changes. However, MAUI supports API 33 and the issues does not occur in it.
We do not plan to support enhancements in Xamarin and recommend moving apps to MAUI.

**Comment by MihaMarkic** [comment]
Just FYI the same is happening on latest .NET Android. Unless I add `<package android:name="com.microsoft.windowsintune.companyportal" />` that is.
