### ISSUE TITLE
Xamarin Forms UWP freezes when using B2C + MSA

### ISSUE THREAD

**Issue by Surfrat** [AzureAD/microsoft-authentication-library-for-dotnet#3821]
**Which version of MSAL.NET are you using?**
Version: 4.48.1

**Platform**
Xamarin Forms UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Expected behavior**
Login dialog appears.

**Actual behavior**
Exception thrown.

Hi,

I have followed the sample app configuration and code from [here](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native), 

This app sample works for Local, MS and Google Accounts. Unfortunately most packages in this sample are very old. I have created a new sample project, that is attached, with the latest Nuget Packages. I am faced with the error: 

`Microsoft.Identity.Client.MsalClientException: Only loopback redirect uri is supported, but msale5737214-6372-472c-a85a-68e8fbe6cf3c://auth/ was found.`

Attached is the full verbose stack trace, logs and the sample app.
Can you please help me solve this problem?

To view my B2C configuration please look [here](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/186).  This issue contains images of my B2C setup.

[UWP Stack Trace.log](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/10076015/UWP.Stack.Trace.log)
[Msal.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/10076016/Msal.zip)

Thanks

Mark and Zac.

**Comment by bgavrilMS** [comment]
You are using a version of UWP which is no longer supported. Please bump it up to use at least SDK level 10.0.17763.0. All other SDKs are deprecated. Note that this doesn't mean you won't support lower runtimes, such as Win 10.0.0.0, but the SDK must be at least 10.0.17763.0

https://www.nuget.org/packages/Microsoft.Identity.Client#dependencies-body-tab

**Comment by bgavrilMS** [comment]
Better yet, don't use Xamarin, it's being deprecated by Microsoft. It is being replaced by Maui. UWP is also being retired and replaced by WinUI. With Maui, you get WinUI version by default. 

Here's the sample to follow: https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/main/MAUI/MauiAppB2C

**Comment by Surfrat** [comment]
As far as using .Net Maui - I wish I could. 

I am following the .Net Maui progress closely. My problem is that the third party vendors are not quite there yet with full support. My app is 80% complete and uses Prism and a lot of the Syncfusion components. I will re-asses this in a years time and make the switch then.

**Comment by bgavrilMS** [comment]
Ack. Unfortunately this may take a long time to fix. The SDK itself is not responsible for the content that gets displayed in the browser. The browser is a UWP control called WAB (win auth broker - this is not the same as WAM - win auth manager). 

WAB is very sensitive to HTML content it has to navigate to, and will bail on any sign of a problem (e.g. a picture is linked via HTTP instead of HTTPS). 

I will ping the b2c folks, but I suggest you open a ticket via Azure Portal yourself about this. 

Realistically, I cannot tell you if this is going to be fixed or not. UWP is on its way out and B2C is also being redesigned to become a part of normal AAD.

**Comment by Surfrat** [comment]
Thanks very much for your insights, as it makes design decisions easier. Is it possible to only use Local login for UWP only and Local, Google and MS for Android and iOS?

This way I can side step the problem for now or use Local login only for all three platforms.

I really appreciate your help, the joys of software engineering :)

**Comment by bgavrilMS** [comment]
Yeah, app models with strict constraints like UPW are hard to work with. I am not aware of any way to configure B2C to show some providers on mobile and other providers on UWP.

**Comment by bgavrilMS** [comment]
Won't fix UWP, please use WinUI or raise the issue via Azure Portal for B2C
