### ISSUE TITLE
[Bug] LongOBO. Issues with cache serialization after user session has been revoked

### ISSUE THREAD

**Issue by lukasz-zoglowek** [AzureAD/microsoft-authentication-library-for-dotnet#3825]
**Which version of MSAL.NET are you using?**
4.48.1

**Platform**
.NET 6.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [X] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**

```csharp


var app = ConfidentialClientApplicationBuilder.Create(clientId)
        .WithAuthority(authorityUri, true)
        .WithCertificate(certificate).Build() as ILongRunningWebApi;

string userTokenCache = string.Empty;

application.UserTokenCache.SetAfterAccess(args =>
{
    if (args.HasStateChanged)
    {
        userTokenCache = args.TokenCache.SerializeMsalV3().FromByteArray();
    }
});

var accessToken = ...
string sessionKey1 = string.Empty;

try
{
    var result = await app.InitiateLongRunningProcessInWebApi(scopes, accessToken, ref sessionKey1)
                                        .WithSendX5C(true)
                                        .ExecuteAsync(); //SUCCESS
    // sessionKey1 ==   "Q97ineyQVRJEjXsoxa24cFMXjOsrD8rg1zUFrINWNyo"                                    
                                        
    // !!!! At this point admin revokes user session
    result = await app.AcquireTokenInLongRunningProcess(scopes, sessionKey1)
                                    .WithForceRefresh(true) // to repro sooner
                                    .WithSendX5C(true)
                                    .ExecuteAsync(); // FAILS (Expected)

}
catch (MsalServiceException e) // AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed.
{
    // New valid access token
    var newAccessToken = ...

    // The below call doesn't work even though a new valid access token is provided
    //var result = await app.InitiateLongRunningProcessInWebApi(scopes, newAccessToken, ref sessionKey1)
    //                                     .WithSendX5C(true)
    //                                    .ExecuteAsync();   

    // The old session key cannot be used anymore
    var sessionKey2 = string.Empty;

    var result = await app.InitiateLongRunningProcessInWebApi(scopes, newAccessToken, ref sessionKey2)
                                        .WithSendX5C(true)
                                        .ExecuteAsync(); //SUCCESS

    //  sessionKey2 ==   "ChOUdSBf_WOM1Ascdkh6iloF4cIUMXrLUsJzS92CQjQ"
    // At this point UserTokenCache has 2 refresh tokens for both session keys
}

Console.WriteLine(userTokenCache);
// userTokenCache has only 1 RefreshToken with "user_assertion_hash": "Q97ineyQVRJEjXsoxa24cFMXjOsrD8rg1zUFrINWNyo" (invalid one)

```

**Expected behavior**
The serialized cache should contain 2 RefreshTokens or only the latest one

**Actual behavior**
The serialized cache contains only the first RefreshToken, which cannot be used because user session was revoked. 
There is no api available to remove the invalid refresh token.

**Possible solution**
Various solutions could be considered
- when calling ILongRunningWebApi calls and MSAL returns a critical MsalServiceException about session revocation, remove the refresh token from the cache. It is unusable for future calls
- when calling ILongRunningWebApi.InitiateLongRunningProcessInWebApi with a fresh AT and existing RT is invalid, generate a new RT and replace the existing RT with a new RT
- Make sure to serialize all refresh tokens
- Add an API to remove refresh tokens based on OBO session key

**Current workaround**
if MsalServiceException is thrown during InitiateLongRunningProcessInWebApi, make a new InitiateLongRunningProcessInWebApi call with a new token and an empty token cache. The old token cache cannot be used.

**Comment by bgavrilMS** [comment]
Thanks for the detailed repro steps. If you remove all token caching logic and add `MemoryCache` (as per https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet#in-memory-token-cache-1) - does this still occur?

**Comment by lukasz-zoglowek** [comment]
I am not using asp net core extensions, but I think memory cache just works fine. If I examine application.UserTokenCache I can see 2 RT

**Comment by bgavrilMS** [comment]
@lukasz-zoglowek - please confirm my understanding here.

1. The important bug fix here is to ensure `InitiateLongRunningProcessInWebApi` being called twice works
2. Secondary, we can add an API `RemoveOBOTokens(string sessionId)`, which can be called automatically when ESTS signals this. 

We will prioritize this for the next release, please let me know if it's urgent and we can take a look at it faster.

**Comment by lukasz-zoglowek** [comment]
Thanks @bgavrilMS 
I agree with your summary.

**Comment by bgavrilMS** [comment]
CC @pmaytak in case this is similar to the OBO bugs you recently looked at

**Comment by trwalke** [comment]
@bgavrilMS @pmaytak I ran through this flow and from what I see it looks like the calling of `InitiateLongRunningProcessInWebApi` twice is working. The first token is overwritten by the second token but the second token is not the same as the first. This is true for both the access token and the refresh token.

Ill keep looking to see what else I can find
