### ISSUE TITLE
[Bug] Microsoft.Identity.Client.MsalClientException: WAM Account Picker did not return an account.

### ISSUE THREAD

**Issue by jhaverkamp** [AzureAD/microsoft-authentication-library-for-dotnet#3826]
**Logs and network traces**
MSAL.Desktop.4.48.1.0.MsalClientException: 
	ErrorCode: authentication_canceled
Microsoft.Identity.Client.MsalClientException: WAM Account Picker did not return an account.
   bei Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker.<AcquireInteractiveWithPickerAsync>d__23.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker.<AcquireTokenInteractiveAsync>d__15.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.<FetchTokensAsync>d__9.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<FetchTokensFromBrokerAsync>d__10.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
**Which version of MSAL.NET are you using?**

4.48.1.0
**Platform**

.NET 4.8 (WinForms)
**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [X] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
WAM-Dialog is visible for a short time, then closes/crashes 

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue.

The error only appears on one Windows 10 machine. Works for all other users within that organization.

**Repro**

```csharp
 var builder = PublicClientApplicationBuilder.Create(clientAppId)
                                                        .WithWindowsBroker(true)
                                                        .WithDesktopFeatures()
                                                        .WithDefaultRedirectUri();
```

**Expected behavior**
WAM Dialog is displayed. User can pick his account to authenticate.

**Actual behavior**
WAM-Dialog crashes and returns MsalClientException.

**Possible solution**
Tried to repair the dialog by using the powershell script.
```
if (-not (Get-AppxPackage Microsoft.AccountsControl)) { Add-AppxPackage -Register "$env:windir\SystemApps\Microsoft.AccountsControl_cw5n1h2txyewy\AppxManifest.xml" -DisableDevelopmentMode -ForceApplicationShutdown } Get-AppxPackage Microsoft.AccountsControl
```

Had no effect.

**Comment by bgavrilMS** [comment]
This can happen if user starts. Consider upgrading to our newer WAM implementaion, which fixes some of these bugs, including run as admin: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam#new-wam-preview-in-msal-444 (it's a small app change)

**Comment by jhaverkamp** [comment]
We changed our code to 

```
var builder = PublicClientApplicationBuilder
                .Create(clientAppId)
                .WithAuthority(AadAuthorityAudience.AzureAdMultipleOrgs)
                .WithExperimentalFeatures(true)
                //.WithLogging(new MaslLogger(), enablePiiLogging: true)
                .WithParentActivityOrWindow(() => parent)
                .WithRedirectUri("ms-appx-web://microsoft.aad.brokerplugin/XXXXXXXX")
                .WithBrokerPreview(true);
            ;
```

We will deliver the changes in our next release.
But we aren't seeing the "fancy"-Windows dialog anymore.  Always web-ui on all our test environments.

Kind regards,

Jürgen

**Comment by bgavrilMS** [comment]
@jhaverkamp - yes, since MSAL knows you are only dealing with work and school accounts, we do not need the "fancy" windows control (it may be fancy, but there are quite a lot of problems with it as you've seen). The windows dialog (account picker) is only needed to differentiate between Work & School and Personal accounts. 

If you have time and want to improve the experience, I suggest you have a look at this sample https://github.com/bgavrilMS/MSAL-SingleAccount-SSO/blob/master/SSO/Program.cs - it shows how to login the default Windows user without prompting.
