### ISSUE TITLE
[Bug] Program execution terminates after the code: var authResult = await pca.AcquireTokenInteractive(ewsScopes).ExecuteAsync(); 

### ISSUE THREAD

**Issue by Tayyab53** [AzureAD/microsoft-authentication-library-for-dotnet#3827]
**When I use below code:**
![image](https://user-images.githubusercontent.com/28978938/204276292-4fbd07d1-d2ce-48f2-ae67-1b50941193a6.png)

**It gives the error:**
![image](https://user-images.githubusercontent.com/28978938/204276364-ad8d6c3c-784c-4b2a-b965-2b1d5f81b4fb.png)

**When I add Main method, it gives similar await warning and crashes at: "AcquireTokenInteractive"I have a program.cs as below:**
![image](https://user-images.githubusercontent.com/28978938/204276112-a69c4afe-01f9-4c08-87ce-6f715b9487aa.png)

**When I run the app without debug mode, it is waiting for key to terminate the app, means it doesn't go beyond the line:** "AcquireTokenInteractive"
![image](https://user-images.githubusercontent.com/28978938/204276522-f7e739a2-1f28-4666-9222-5b168d6520c1.png)

**Here attaching the code(.zipped)** - Already Removed the Id's
[EWS.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/10103661/EWS.zip)

**Comment by bgavrilMS** [comment]
What version of Visual Studio are you using?

**Comment by bgavrilMS** [comment]
I think you are using a version of Visual Studio that is too old. Can you please use a more recent one and you'll get async for the main method in console app. 

Alternatively, you can set the C# language version to something more modern, see https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version. I think you need at least 7.1 for the async stuff in console apps.

**Comment by Tayyab53** [comment]
@bgavrilMS @bratsche @RamonPage @vbatts: Thank you. I am able to connect to the email account.

But the login screen is popped-up during each time app is executed(Delegated Permission). Since the console application wil be scheduled using task scheduler, how can we avoid login screen pop-ups for task scheduler job.

**Comment by bgavrilMS** [comment]
Please have a look at the sample that shows how to use a token cache - https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/tree/master/2-TokenCache

You can also skip the first login prompt in most cases (but not all!) by using WAM on Windows - https://aka.ms/msal-net-wam - this will authenticate the current user to your app, provided that there is no consent need.

**Comment by Tayyab53** [comment]
@bgavrilMS: I have used sample piece of code from the below link: 
 https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/tree/master/2-TokenCache

But it is not caching the credentials, hence it prompts the login screen during each execution of the application. This app(Console) need to be deployed this week as a task scheduler job. So the login screen must not be prompted each time.

Please find attached the application(Zipped) - **Removed app and tenant Id's**

**Please have a look at it and help me with the code, need to deploy this week.**
[EWS.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/10166742/EWS.zip)

**Comment by Tayyab53** [comment]
@bgavrilMS: Please help me with the code. We need to deploy the application this week.

**Comment by bgavrilMS** [comment]
Hi @Tayyab53 - the MSAL team is not able to help with code, we are here to investigate issues and to point you to samples. Please have a look at the sample https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/tree/master/2-TokenCache and let us know if you have any questions.

**Comment by Tayyab53** [comment]
@bgavrilMS: My Console Application has been granted **Delegated Permission**. 

In order to use the console application as a **Task Scheduler Job** in Windows. Do I need to change the app permissions to **"App-Only Authentication"** or "Delegated Permission" is the right permission assigned so far in the Azure Portal
