### ISSUE TITLE
WebApp => WebApi demo code for Microsoft.Identity.Client (and maybe B2C)

### ISSUE THREAD

**Issue by NikolaosWakem** [AzureAD/microsoft-authentication-library-for-dotnet#384]
Hi,

Do you have some demo code that could be applied to 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/dev/dev%20apps/WebTestApp/WebApp 

to upgrade it to use this library to Microsoft.Identity.Client

Specifically the

Startup.cs / private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)

and

TodoController.cs public async Task<IActionResult> Index()

methods..

**Comment by kpanwar** [comment]
We don't have any sample code at the moment. You should refer to official samples, which will be published at https://github.com/azure-samples?query=active-directory

**Comment by NikolaosWakem** [comment]
thanks.. for anyone also looking - perhaps check out [https://github.com/danroth27/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore-b2c](url)
