### ISSUE TITLE
[Feature Request] Add test to check published Identity.Client packages version and validate against current publishing version

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3840]
**Is your feature request related to a problem? Please describe.**
In the past we have released internal MSAL versions that were higher than the published NuGet versions, to avoid doing this we need to add a test that will catch such scenarios

**Describe the solution you'd like**
test runs on the release pipeline and fails if the current version +2 versions higher than the NuGet version. This test should check all MSAL libraries. 

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by bgavrilMS** [comment]
I don't recall this happening, or at least not more than once. Not sure if it's worth investing here.
