### ISSUE TITLE
Need ability to have more than 3 path segments in B2C authority URI

### ISSUE THREAD

**Issue by mcmcelro** [AzureAD/microsoft-authentication-library-for-dotnet#3842]
The method [AbstractApplicationBuilder.WithB2CAuthority](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5d0b45f0a1e90957af9409866c78f6d4f6b92510/src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs#L872) passes into [AuthorityInfo.FromB2CAuthority](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5d0b45f0a1e90957af9409866c78f6d4f6b92510/src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs#L224), which [creates a new AuthorityInfo with an AuthorityType of AuthorityType.B2C](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5d0b45f0a1e90957af9409866c78f6d4f6b92510/src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs#L42).

As currently designed, this method parses out the segments of the authority URI, separated by a forward slash '/', then recombines them as follows:

`CanonicalAuthority = new Uri(string.Format(
                        CultureInfo.InvariantCulture,
                        "https://{0}/{1}/{2}/{3}/",
                        authorityUri.Authority,
                        pathSegments[0],
                        pathSegments[1],
                        pathSegments[2]));`

The problem here is simple: this limits the length of a B2C authority URI to a domain plus three segments.

I am currently developing a mobile app in Xamarin.Forms using the latest version of Microsoft.Identity.Client (v4.48.1), attempting to authenticate against an OAuth endpoint for B2C. As retrieved from the OpenID configuration discovery URL, our endpoint's URI is

`https://[tenant].b2clogin.com/[tenant].onmicrosoft.com/[policyID]/oauth2/v2.0/authorize`

As you can see, this is a domain plus 5 path segments. When I use a PublicClientApplicationBuilder to show the login flow for our application, the authority URI is automatically truncated to 

`https://[tenant].b2clogin.com/[tenant].onmicrosoft.com/[policyID]/oauth2/`

There is no way to avoid this, as the limit of 3 segments is hard-coded.

I understand needing a **minimum** of 3 path segments based on this code, but I have not been able to find any explanation for why the limit of 3 was imposed. It seems arbitrarily small and bound to cause headaches.

The login flow works flawlessly if I use an endpoint of

`https://[tenante].b2clogin.com/tfp/[tenant].onmicrosoft.com/`

but we would prefer to be able to load the endpoint from a proper OpenID configuration endpoint rather than hard-code this path.

**Comment by bgavrilMS** [comment]
How do you get to the OIDC endpoint? You'd go to the authority first ? There is no need to go to OIDC endpoint, MSAL knows how to form the url for the authorization and tenant endponints. 

MSAL starts from the authority string, which is `https://[tenante].b2clogin.com/tfp/[tenant].onmicrosoft.com/[policyid]`. 
`https://[tenant].b2clogin.com/[tenant].onmicrosoft.com/[policyID]/oauth2/v2.0/authorize` is the authorization endpoint.

**Comment by bgavrilMS** [comment]
Yes, MSAL is a slightly higher-level library, it hides some of the protocol details from you. You start with the authority string `https://[tenante].b2clogin.com/tfp/[tenant].onmicrosoft.com/[policyid]`.

MSAL will know how to construct the OIDC url or the authorization url as needed based on that.
