### ISSUE TITLE
MAUI WithBroker has no impact

### ISSUE THREAD

**Issue by manishtpatel** [AzureAD/microsoft-authentication-library-for-dotnet#3844]
Setup: MSAL with version 4.48.1, MAUI app targeting Windows, running on windows 10 1809 

Issue: WithBroker() has no effect. It always opens in broker mode

I have tried both our migrated app from xamarin.forms to maui and sample app from this repo, and both behave identically. Checked the log and documentation, not sure how to diagnose any further.

We have a kiosk application, shared by users so we need embedded non-broker sign-in.

**Comment by bgavrilMS** [comment]
Broker is disabled by default. Either ignore `WithBroker` or use `WithBroker(false)` and you should get the embedded webview.

**Comment by SameerK-MSFT** [comment]
> we need embedded non-broker sign-in.
Also, if you are need embedded, you would want to add WithEmbedded option. Is the authentication AAD or B2C?
