### ISSUE TITLE
[Bug] Review PII logs in MSAL.NET

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3846]
hostnames should only be logged for AAD authorities, because in B2C and ADFS they have identifiers.
tenant id should be logged as pii

**Comment by jmprieur** [comment]
I disagree. This makes things hard to support customers

**Comment by rymeskar** [comment]
+1 to @jmprieur . this type of data does not need to be obfuscated.

**Comment by bgavrilMS** [comment]
I have reviewed this with our privacy team and have confirmed that organizational data is not PII. MSAL.net conforms to this, as well as Java and Python. Only MSAL Js is more restrictive, and they will update their logging as needed.

For more details see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/PII
