### ISSUE TITLE
[Bug] Unsupported browser error if MFA is on

### ISSUE THREAD

**Issue by shacharrozin2** [AzureAD/microsoft-authentication-library-for-dotnet#3850]
Which version of MSAL.NET are you using?

Platform
.NET Framework 4.8

What authentication flow has the issue?

Desktop
 Interactive

Other?

Is this a new or existing app?

b. The app is in production, I haven't upgraded MSAL, but started seeing this issue.

Repro

                    return await _clientApp.AcquireTokenInteractive(scopes)
                                           .WithPrompt(Prompt.SelectAccount)
                                           .WithParentActivityOrWindow(GetForegroundWindow())
                                           .ExecuteAsync()
                                           .ConfigureAwait(false);

Expected behavior
Browser prompts for authentication, and provides support for MFA.

Actual behavior
Browser prompts as expected, but then prompts with more information required. This in itself is ok, easy enough to step through in normal circumstances and provide additional information.  If no additional info is required, then it proceeds normally. When clicking next, it thinks about it for a bit and then presents this screen and authentication is not able to be completed

![image](https://user-images.githubusercontent.com/120018428/206178746-7e070f02-3c72-45c2-93c8-ca3eef58f3e0.png)

**Similar bug exists bug Workaround doesn't work:** 
I saw this bug: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3820 
and tried to use the workaround, but it didn't work in my code since I'm not using embedded view. 

I locally tested it and changed the code to use embedded view + used the workaround (adding my app name in the registry with value 11000) - it worked. 
New-ItemProperty -path 'HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION' -name '<myAppName>.exe' -value '11000' -PropertyType 'DWord'

New code (calling WithUseEmbeddedWebView): 
                    return await _clientApp.AcquireTokenInteractive(scopes)
                                           .WithPrompt(Prompt.SelectAccount)
                                           .WithParentActivityOrWindow(GetForegroundWindow())
                                           .WithUseEmbeddedWebView(useEmbeddedWebView: true)
                                           .ExecuteAsync()
                                           .ConfigureAwait(false);

However, application is in production and I can't change the code to all of the users like I tested locally, therefore workaround doesn't work. 
Without the code changes I described, when only using the registry changes - workaround failed.

**Comment by bgavrilMS** [comment]
Please switch to use WAM, this will work https://aka.ms/msal-net-wam (use the preview bits for new apps)
