### ISSUE TITLE
Token from AcquireTokenSilent does not work with Exchange

### ISSUE THREAD

**Issue by Tayyab53** [AzureAD/microsoft-authentication-library-for-dotnet#3851]
Hi Team,

I have used below code to implement EWS Modern Authentication in a **Console Application** and deployed as **Task Scheduler Job** with **Delegated API Permissions**. 

![image](https://user-images.githubusercontent.com/28978938/206432376-17b78f65-f5e6-4460-b87a-35124ec3918d.png)

Since it is deployed as a **Task Scheduler Job** with delegated permissions. I wanted to bypass the credentials **dialog** for "User Name/Password" and request token by providing credentials in code itself,  Hence I have used **"AcquireTokenByUsernamePassword"** to get a token via username/password. 

I am able to connect to the Outlook account and do my work. But I would like to know couple of points from your end:

1. On every execution of the **Task Scheduler Job**, it is requesting token based on the credentials i.e **"AcquireTokenByUsernamePassword"**, instead it could have used the cached token using below method:
**AcquireTokenSilent**. While Debugging, it is clear - the control never gets to the **AcquireTokenSilent** method

2. Is it good practice to call **"AcquireTokenByUsernamePassword"** on every execution of task scheduler job(**Duration - every 15 mins**) and generate a new token as above code suggests

3. Will there be any issues going forward with the above approach, any **exceptions** or **production issues** to deal with above approach?

Any changes you would recommend? Please suggest.

**Comment by Tayyab53** [comment]
@bgavrilMS: **Referring to your below comments:**

MSAL caches tokens in memory in the PublicClientApplication app object. So if you re-create that object you blow the internal cache away.

Ways around this:

1. Don't recreate the PCA object OR  - We have change the console app(Task Scheduler) to run as a **Windows Service** now. **Is it feasible to generate a token once during the first execution and use it continuously(with Thread.Sleep(30seconds)). Will this approach work for years to come without any issues?**. Is there any over exhaust/timeout issue for a single token to be used during the years to come

2. Store the tokens in a static cache by adding .WithCacheOptions(CacheOptions.EnableSharedCacheOptions) - Is it feasible for a Windows Service

3. (Preffered) store the cache in a file encrypted on disk - just use this lib that does it all for you https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=desktop

Note that we do not recommend this flow in production, because it's easy to lose the password.

**Please suggest**

**Comment by bgavrilMS** [comment]
Please use option 3.

**Comment by Tayyab53** [comment]
@bgavrilMS: In Pursuit to use Option 3:

On first instance, we are connecting to the account using **AcquireTokenByUsernamePassword()**, later from next instances it should be using the cached token using **AcquireTokenSilent()**.

But while using **AcquireTokenSilent()**, it gives below error:

**Error: The request failed. The remote server returned an error: (401) Unauthorized**

Below is the code snippet for your reference:

**var accounts = await app.GetAccountsAsync()
var firstAccount = accounts.FirstOrDefault();
if (accounts.Any())
{
     result = await app.AcquireTokenSilent(Config.Scopes, firstAccount)
                                  .ExecuteAsync();
}
else
{
    result = await app.AcquireTokenByUsernamePassword(Config.Scopes,
                Config.Username,
                Config.Password).ExecuteAsync();
}
var ewsClient = new ExchangeService();
ewsClient.Url = new Uri("URL");
ewsClient.Credentials = new OAuthCredentials(result.AccessToken);**

Please suggest

**Comment by bgavrilMS** [comment]
Who returns the 401? The ewsClient ? 


Suggested code change:

```csharp

try 
{
ar accounts = await app.GetAccountsAsync()
var firstAccount = accounts.FirstOrDefault();
result = await app.AcquireTokenSilent(Config.Scopes, firstAccount)
.ExecuteAsync();
}
// no account in cache or refresh token failed
catch (MsalUiRequiredException e)
{
   result = await app.AcquireTokenByUsernamePassword(Config.Scopes, Config.Username,Config.Password).ExecuteAsync();
}

**Comment by Tayyab53** [comment]
@bgavrilMS: I have used your code, but **again** it fails at the **same** below line of code:

**Microsoft.Exchange.WebServices.Data.Folder FindFolder = Microsoft.Exchange.WebServices.Data.Folder.Bind(ewsClient, WellKnownFolderName.MsgFolderRoot);**

**Comment by bgavrilMS** [comment]
Can you look at the `result.AccessToken` in https://jwt.ms and see what is the difference between the one obtained from `AcquireTokenSilent` and `AcquireTokenUsernamePassword` ?

**Comment by Tayyab53** [comment]
Yes there are few differences:
"scp": "Name.AccessAsUser.All User.Read",  **(UserNameand Password)**
"scp": "Name.AccessAsUser.All User.Read profile openid email", **(Silent)**

"xms_st": {
    "sub": ".............ID........"    **Found in (Silent)**  **This is missing in (UserNameand Password)**
  },

"tenant_region_scope": "NA",    **Found in (Silent)**  **This is missing in (UserNameand Password)**

**Comment by Tayyab53** [comment]
@bgavrilMS: There is also a difference for the below attribute(aud) - **Comparison between AcquiteTokenBySilent() and AcquireTokenByUserNameandPassword()** 

**Claim Type:                                 Value:                                                                                          Method:
aud                                https://outlook.office.com                                               AcquireTokenByUserNameandPassword
aud                                00000003-0000-0000-c000-000000000000                                 AcquiteTokenBySilent**

**Comment by bgavrilMS** [comment]
What is the value of `Config.Scopes` ?

**Comment by Tayyab53** [comment]
@bgavrilMS: Thanks for the support:

I just figured out, was using: string[] Scopes = new[] { "user.read" };

Now changed to: new string[] { "https://outlook.office.com/EWS.AccessAsUser.All" }

**Comment by bgavrilMS** [comment]
Yes, "user.read" is a scope for the Microsoft Graph resource. It's shorthand for "https://graph.microsoft.com/User.Read". But you seem to require a scope on the Exchange resource,  "https://outlook.office.com/EWS.AccessAsUser.All"

Note that AAD supports asking for several scopes from 1 resource only. If you need scopes from different resources, you'll have to make 2 different AcquireToken* calls.
