### ISSUE TITLE
[Fundamentals] Test MSAL on .NET 7

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#3856]
.NET 7 had some regression related to threading and race conditions (https://github.com/dotnet/runtime/issues/79529). Need to test various scenarios, especially multi-threaded, high-throughput.

To-Do:
- [ ] Run tests (unit, integration, etc.) on .NET 7.
- [ ] Update perf project to .NET 7 and run tests.
- [ ] Test with bombardier and  WebAPI project.
- [x] Test with the [multi-threaded code](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/tests/devapps/NetCoreTestApp/Program.cs#L251) in NetCore Console dev app.
- [ ] Test multi-threaded ATS with [NetFx WAM app](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/a5e1abee8b01cb4532cdfe53a782969a4677650b/tests/devapps/WAM/NetFrameworkWam/Form1.cs#L466)
- [ ] Any other test cases not covered by the above.

**Comment by TaviTruman** [comment]
Do these tests include .NET WPF and MAUI apps?

**Comment by bgavrilMS** [comment]
Yes. But this is just an internal task. MSAL is fully supported on NET7 and we rely on .NET to release fully backwards compatible versions. Seems like this does not always happen :). 

Note - most of the team use VS 2022 Preview, so we do actively develop with preview version of net7.

**Comment by SameerK-MSFT** [comment]
The .NET 7 issue was specific to ASP.NET core. We did minimal testing to make sure that it is not broken on our side.
