### ISSUE TITLE
[Engineering Task] Improve publishing symbols to internal symbol server

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#3858]
Need to investigate and improve (if there's a way) to use better credentials instead of PAT when publishing symbols to symweb.

Wiki: https://www.1eswiki.com/wiki/Using_Azure_DevOps_Symbols#Publish_using_symbol.exe

Related issue #2497.

**Comment by gladjohn** [comment]
@trwalke assigning this to you since the work is done
