### ISSUE TITLE
EWS OAuth works on local machine, but fails on Dev and Prod Server

### ISSUE THREAD

**Issue by Tayyab53** [AzureAD/microsoft-authentication-library-for-dotnet#3866]
**EWS OAuth works on local machine, but fails on Dev and Prod Server**

**Issue 1:**
Error Details:
![image](https://user-images.githubusercontent.com/28978938/207794569-d0b0a02a-5265-4dba-9b2f-4f81a9cbe777.png)

**Even though we opened the Port 443 for the given IP, on next execution in the Dev and Prod Server the IP(Outlook) has changed, keeps changing on every execution**. But the same error doesn't occur in local machine.

Please suggest how to resolve it.

**Issue 2:**
Also on first instance, we are connecting to the account using **AcquireTokenByUsernamePassword()**, later from next instances it should be using the cached token using **AcquireTokenSilent()**.

But while using AcquireTokenSilent(), it gives below error:

**Error: The request failed. The remote server returned an error: (401) Unauthorized**

Below is the code snippet for your reference:

var accounts = await app.GetAccountsAsync()
var firstAccount = accounts.FirstOrDefault();
if (accounts.Any())
{
result = await app.AcquireTokenSilent(Config.Scopes, firstAccount)
.ExecuteAsync();
}
else
{
result = await app.AcquireTokenByUsernamePassword(Config.Scopes,
Config.Username,
Config.Password).ExecuteAsync();
}
var ewsClient = new ExchangeService();
ewsClient.Url = new Uri("URL");
ewsClient.Credentials = new OAuthCredentials(result.AccessToken);

**Please suggest**

**Comment by bgavrilMS** [comment]
You have to be able to make HTTP requests to AAD for tokens. This is an HTTP error indicating that there is no network connectivity. Use a tool like Fiddler to understand the various HTTP requests made by MSAL - they should all be to "https://login.microsoftonline.com"

If you have some exotic proxy, you can inject your own HttpClient - https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-provide-httpclient
