### ISSUE TITLE
[Bug] Perf issue in SaveAccessToken

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3878]
MSAL 4.49.1

See email thread "Suspicious ConcurrentDictionary allocation" for details

Found a suspicious ConcurrentDictionary allocation stack in Falcon data in CPR:

 
![image](https://user-images.githubusercontent.com/12273384/208923015-c39d3f98-df7b-4054-8564-81257027959f.png)

 

The biggest caller is SaveAccessToken. Why would a save method need a concurrent dictionary?

Here is overall allocation:
 
![image](https://user-images.githubusercontent.com/12273384/208923042-3df0d411-ab61-4ac2-9d23-6dd244d4762d.png)

 

 

SaveAccessToken is responsible for 1.54% allocations in Falcon.BingAtWork process, that is a lot.

 

Source code:

 

        internal readonly ConcurrentDictionary<string, ConcurrentDictionary<string, MsalAccessTokenCacheItem>> AccessTokenCacheDictionary;

        internal readonly ConcurrentDictionary<string, ConcurrentDictionary<string, MsalRefreshTokenCacheItem>> RefreshTokenCacheDictionary;

        internal readonly ConcurrentDictionary<string, ConcurrentDictionary<string, MsalIdTokenCacheItem>> IdTokenCacheDictionary;

        internal readonly ConcurrentDictionary<string, ConcurrentDictionary<string, MsalAccountCacheItem>> AccountCacheDictionary;

 

        public void SaveAccessToken(MsalAccessTokenCacheItem item)

        {

            string itemKey = item.CacheKey;

            string partitionKey = CacheKeyFactory.GetKeyFromCachedItem(item);

 

            AccessTokenCacheDictionary

                .GetOrAdd(partitionKey, new ConcurrentDictionary<string, MsalAccessTokenCacheItem>())[itemKey] = item; // if a conflict occurs, pick the latest value

        }

 

Using ConcurrentDictionary.GetOrAdd(key, value) is improper here because a new concurrent dictionary needs to be allocated every time and it’s not needed most of the time.

 

Here is proper implementation:

 

            AccessTokenCacheDictionary

                .GetOrAdd(partitionKey, (k) => new ConcurrentDictionary<string, MsalAccessTokenCacheItem>(4, 5))[itemKey] = item; // if a conflict occurs, pick the latest value

 

Now we’re calling ConcurrentDictionary.GetOrAdd(key, Func<key>). We’re also reducing the concurrency level and initial capacity of the second level concurrent dictionary to reduce memory usage.

 

Even using two level ConcurrentDictionary could be questionable. It’s better to use something like ConcurrentDictionary<ValueTuple<string, string>, MsalAccessTokenCacheItem>>.

 

Notice the items being added is always MsalAccessTokenCacheItem, so it’s even possible to use ConcurrentDictionary<MsalAccessTokenCacheItem, MsalAccessTokenCacheItem>. You just need to make sure having the proper equality comparer.

 

Notice key generation is also expensive:

 

 

MsalAccessTokenCacheKey.ToString is costing 2.62% allocations in total.

 

It’s best to avoid such expensive key generation.

**Comment by trwalke** [comment]
We have already did a bit of refactoring to saving/Cache key logic to reduce this inefficiency. Closing for now until more issues with this are identified.
