### ISSUE TITLE
[Feature Request] FunctionApp calls will be impossible if MSAL serialized cache token is enforced

### ISSUE THREAD

**Issue by WayneAASPLLC** [AzureAD/microsoft-authentication-library-for-dotnet#3884]
**Is your feature request related to a problem? Please describe.**
The following will always fail because you cannot create files or directories in a zip deployed app. The app is already secured due to zip deployment, so this new requirement isn't even needed?

```
if (app == null)
            {
                try
                {
                    log.Log(Microsoft.Extensions.Logging.LogLevel.Information, "Auto creating cache directory");
                    var directorypath = Environment.CurrentDirectory + "/token";
                    if (!Directory.Exists(directorypath))
                        Directory.CreateDirectory(directorypath);
                    log.Log(Microsoft.Extensions.Logging.LogLevel.Information, "Creating StroageCache");
                    var storageProperties =
                        new StorageCreationPropertiesBuilder("TokenCache", directorypath)
                        .Build();

                    log.Log(Microsoft.Extensions.Logging.LogLevel.Information, "Creating ConfidentalClient");
                    app = ConfidentialClientApplicationBuilder.Create(ClientId)
                        .WithClientSecret(secret)
                        .WithTenantId(tenantId)
                        .WithAuthority("https://login.microsoftonline.com/" + tenantId)
                        .WithLegacyCacheCompatibility(false)
                        .Build();

                    log.Log(Microsoft.Extensions.Logging.LogLevel.Information, "Registering Cache");
                    var cacheHelper = await MsalCacheHelper.CreateAsync(storageProperties);
                    cacheHelper.RegisterCache(app.UserTokenCache);
                }
                catch
                {
                    log.Log(Microsoft.Extensions.Logging.LogLevel.Information, "New method failed, reverting to legacy");
                    app = ConfidentialClientApplicationBuilder.Create(ClientId)
                        .WithClientSecret(secret)
                        .WithTenantId(tenantId)
                        .WithAuthority("https://login.microsoftonline.com/" + tenantId)
                        .WithLegacyCacheCompatibility(true)
                        .Build();
                }
            }
```

**Describe the solution you'd like**
Keep legacy cache available!

**Describe alternatives you've considered**
The alternative would be to make the function app not a zip deploy which is less secure. You may be increasing security for MSAL for people not doing this but for zip deploy this is a negative impact on security.

**Comment by pmaytak** [comment]
`MsalCacheHelper` from [Microsoft Identity token cache extensions library](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet) is intended for **public client** applications, such as desktop or mobile, which are usually single-user.
**Confidential client** apps like web apps and web APIs are usually multi-user, hosted in distributed environments, for which distributed caches like Redis, SQL Server are more appropriate. This scenario would also apply to Azure Functions. [This wiki](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnetcore) has more details how to set up the cache (we recommend using Microsoft Identity Web).

`WithLegacyCacheCompatibility` relates to an application sharing a single cache source between ADAL.NET (deprecated legacy library) and MSAL.NET (new one). When enabled it allows MSAL to use refresh tokens from ADAL. This feature is independent of the token cache serialization mentioned above.

Does this clarify the situation a bit? Is there documentation that you found confusing related to this?

**Comment by WayneAASPLLC** [comment]
It gives me a better understanding, but the main request is to make sure that legacy option stays open so function apps can do this and stay a zip deploy securely.

**Comment by pmaytak** [comment]
What caching method do you mean by "legacy option"?

> The following will always fail because you cannot create files or directories in a zip deployed app. The app is already secured due to zip deployment, so this new requirement isn't even needed?

The usage in code snippet is incorrect. You should use either [in-memory or distributed cache](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnetcore) in Azure Functions; not file based.

**Comment by WayneAASPLLC** [comment]
Regarding In-Memory:
It isn't a asp.net program, it is a desktop app so there is no option for in-memory.
Go into the Desktop Apps tab and you will see there is no way to do this:
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=desktop
It tells you to use a StorageCreationPropertiesBuilder which is indeed something that writes a file and fails on zip deployed function apps.
That could be another way though, allow in-memory for desktop apps due to function apps?

Regarding Legacy Options:
app = ConfidentialClientApplicationBuilder.Create(ClientId)
                        .WithClientSecret(secret)
                        .WithTenantId(tenantId)
                        .WithAuthority("https://login.microsoftonline.com/" + tenantId)
                        **.WithLegacyCacheCompatibility(true)**
                        .Build();

This line right here, as long as this stays an option it will work but it is using ADAL. That is the legacy cache compatibility which from what I can tell is 100% safe since this is a read only zip deploy anyway?

**Comment by WayneAASPLLC** [comment]
![image](https://user-images.githubusercontent.com/117128832/209966819-f4e5ddc8-15ce-4ae4-9226-afb6c9cf9364.png)

**Comment by pmaytak** [comment]
What kind of function trigger app is this? Do you just call AcquireTokenForClient?
It would be considered a confidential daemon app, so you can follow [these steps](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet#referencing-the-nuget-package) to use Microsoft.Identity.Web.TokenCache.

What is the lifecycle of this app? If it runs continously, you could use in-memory cache by either (1) not setting up the cache, so the default cache is used or (2) use memory cache from the Identity Web package which has size limits and eviction. If your app is opened and closed, then that you'd have to go with persisted distributed cache.

> This line right here, as long as this stays an option it will work but it is using ADAL.

Do you use ADAL then also? How do you set up custom caching for ADAL?
`WithLegacyCacheCompatibility` allows to only share refresh tokens, which are only in user authentication flows. So for AcquireTokenForClient flow, this feature doesn't do anything.

> Keep WithLegacyCacheCompatibility as an option and don't deprecate.

No plans to remove it as of now.

**Comment by WayneAASPLLC** [comment]
What kind of function trigger app is this? Do you just call AcquireTokenForClient?
I use different function apps for different triggers. Currently, I have 1 that is an HTTP trigger and 1 that is a Queue trigger from storage Queue. They all need to write to other API's and tasks like Dynamics 365 for example based on what comes in.

What is the lifecycle of this app?
It is 24/7 active API and that is what the withlegacycachecompability is used for. Currently it works by default, but I am being told by others MSAL cache will be enforced. I want to make sure that doesn't happen because this is a perfect example of where you don't need to do it and it will not work anyway due to Read Only Zip Deploys

No plans to remove it as of now.
That is good to hear, that is what I was hoping to hear.

I wrote the example like this so you can see that it attempts MSALs new caching first and then reverts back to legacy if it fails. Which it is failing every time due to the Read Only ZIp Deploy.

**Comment by bgavrilMS** [comment]
You should write your own token cache logic. We will not deprecate the cache extensibility mechanism
