### ISSUE TITLE
Can you please point me the rust MSAL project [Feature Request] 

### ISSUE THREAD

**Issue by B3K7** [AzureAD/microsoft-authentication-library-for-dotnet#3890]
**Is your feature request related to a problem? Please describe.**
Given that Mark Russinovich's twitter account is prioritizing RUST over C/C++, can you please point me to a x.509 based MSAL implementation written in RUST which use is able to use Microsoft Graph and supply its own identity (i.e. it's own client certificate )?  

**Describe the solution you'd like**
MSAL implementation written in RUST.

**Describe alternatives you've considered**
https://docs.rs/crate/msal_browser/0.2.6
https://github.com/Azure-Samples/ms-identity-python-daemon/tree/master/2-Call-MsGraph-WithCertificate

**Additional context**

As per Michele Mosca:
-  Don't
> -  Panic
> -  Procrastinate
 - Do
> - Plan 
> - Prepare 

https://www.linkedin.com/posts/dr-mosca_221212372pdf-activity-7016808281847336960-nv8C

In pseudo code:
IF  [rust template employs transitionary crypto or PQC ]  THEN [ Respect! ]

**Comment by bgavrilMS** [comment]
**AAD is fully OAuth2 + OIDC compliant, so any SDK which implements the protocol can be used.** 

MSAL is the SDK for AAD, so it implements the protocol, offers slightly higher level API and some features like token caching. 

We are evaluating creating an MSAL SDK, we understand the need, but we do not have the resources for one. One of the strategies we are evaluating is to go for is to create a Rust wrapper over the MSAL .NET SDK compiled with AOT.

**Comment by B3K7** [comment]
Noted.  Thank-you.
