### ISSUE TITLE
MSAL 4.99 package followup

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3891]
We have accidentally published MSAL 4.99 to some internal package managers. To fix this we have contacted affected teams and most have unlisted this package. 

Work left to do: 

1.  based on  this [doc](https://microsofteur-my.sharepoint.com/:x:/g/personal/ckyalo_microsoft_com/EYyVCxA0GOdDiJuHRD1F9K8BNpkSrRebNhu_fkOGuxO4yg?e=aCH1CP&CID=39508779-f304-08b4-346c-649f07031679)
 ensure teams listed in the XLS have deleted (not just delisted) the package

2. run the MSAL 4.99 kusto query again (cam be done independently of 1).

**Comment by gladjohn** [comment]
We have 2 more teams that needs to be followed up with, sending out emails

**Comment by bgavrilMS** [comment]
Closing this. It is being taken care of.
