### ISSUE TITLE
[Bug] AcquireTokenByIntegratedWindowsAuth stopped working

### ISSUE THREAD

**Issue by rupinderkang-teck** [AzureAD/microsoft-authentication-library-for-dotnet#3903]
**Logs and network traces**
[ERROR] Failed to process in one cycle: System.AggregateException: One or more errors occurred. ---> Microsoft.Identity.Client.MsalClientException: Integrated Windows Auth is not supported for managed users. See https://aka.ms/msal-net-iwa for details. 

**Which version of MSAL.NET are you using?**
MSAL.NET 4.36.2 

**Platform**
net461, C# Console Application

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Integrated Windows Authentication

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**

```csharp
 if (this.ExchangeClient != null)
                return;
            PublicClientApplicationOptions pcaOptions = new PublicClientApplicationOptions
            {
                ClientId = _clientId,
                TenantId = _tenantId,
                RedirectUri = _redirectUri
            };
            var pca = PublicClientApplicationBuilder.CreateWithApplicationOptions(pcaOptions).Build();
            var ewsScopes = new string[] { _EwsScope };
            Logger?.Info("Logging in mailbox as " + Environment.UserName);
#if DEBUG_AS_ME
            var authResult = await pca.AcquireTokenInteractive(ewsScopes).ExecuteAsync();
#else
            var authResult = await pca.AcquireTokenByIntegratedWindowsAuth(ewsScopes).ExecuteAsync();
#endif
            this.ExchangeClient = new ExchangeService()
            {
                Url = new Uri(_ExchangeUri),
                Credentials = new OAuthCredentials(authResult.AccessToken)
            };
            Logger?.Info("Logged in mailbox");
```

**Expected behavior**
Expecting the successful AuthenticationResult from AcquireTokenByIntegratedWindowsAuth method . 
Note: this code was already in production an working since a year. It stopped working 1 week before

**Actual behavior**
Throws MsalClientException: Integrated Windows Auth is not supported for managed users

**Possible solution**
Looking for suggestions on a fix for the bug. I cannot fix it. I worked with AAD team and cloud team to find out the reason. AAD shows user as managed user. I talked to AAD team and they haven't changed anything since 2018.

**Additional context / logs / screenshots / links to code**
Failed to process in one cycle: System.AggregateException: One or more errors occurred. ---> Microsoft.Identity.Client.MsalClientException: Integrated Windows Auth is not supported for managed users. See https://aka.ms/msal-net-iwa for details. 
   at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<FetchAssertionFromWsTrustAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailboxManager.<InitializeExchangeClient>d__15.MoveNext() in LoadingResultService\MailboxManager.cs:line 61
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LoadingResults.MailboxManager.GetUnreadItems(Int32 maxItem) in LoadingResults.MailProcessor.ProcessOnce() in LoadingResultService\MailProcessor.cs:line 101
   at .LoadingResults.TaskScheduler.RunOnce() in LoadingResultService\TaskScheduler.cs:line 75
   at .LoadingResults.TaskScheduler.Start() in .LoadingResultService\TaskScheduler.cs:line 50
---> (Inner Exception #0) MSAL.Desktop.4.36.2.0.MsalClientException: 
	ErrorCode: integrated_windows_auth_not_supported_managed_user
Microsoft.Identity.Client.MsalClientException: Integrated Windows Auth is not supported for managed users. See https://aka.ms/msal-net-iwa for details. 
   at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<FetchAssertionFromWsTrustAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Discovery call results:
![image](https://user-images.githubusercontent.com/107279356/212213183-7e9cbc9c-3d21-4a35-b9de-d01f0127ae92.png)

**Comment by bgavrilMS** [comment]
## On IWA

The IWA protocol states that we must first determine if the user is managed or federated. To do this, MSAL makes a call:

`https://login.microsoftonline.com/common/userrealm/bogavril@microsoft.com?api-version=1.0`

Notice how for my corporate account this appears as Federated and IWA can proceed. 

Does the "account_type" appear managed for all the users in your tenant? Or just for some? Is it possible that the tenant admin migrated the users from AD to AAD?

## IWA alternative

We're no longer suggesting ppl use IWA, as it's quite flaky (although I've never seen this issue before). Instead, we recommend folks use Windows Broker integration. The Windows Broker has the capability of logging in / getting tokens for the current Windows broker **silently**. Internally it uses several protocols which MSAL cannot implement. So it has better chance of success.

See https://aka.ms/msal-net-wam (try the preview version)

**Comment by rupinderkang-teck** [comment]
With WAM , I am getting error : No account or login hint was passed to the AcquireTokenSilent call. 

All my app settings on azure looks correct. Azure Enterprise Application , sigin logs show "Success" status under the Service principal sign-ins tab.

**Comment by bgavrilMS** [comment]
There is a setting somewhere where you can configure AAD to report those users as "federated" - this is done specially so that IWA continues to work. I don't know what this setting is :( to help further. Maybe someone turned it off?

For WAM, please have a look at this sample - https://github.com/bgavrilMS/MSAL-SingleAccount-SSO (it's preconfigured, just use it). In particular have a look at https://github.com/bgavrilMS/MSAL-SingleAccount-SSO/blob/master/SSO/Program.cs#L159 and at https://github.com/bgavrilMS/MSAL-SingleAccount-SSO/blob/master/SSO/Program.cs#L180 that shows how to get SSO with Windows account. Note that the SSO might not always work, so eventually we fallback to AcquireTokenInteractive.

**Comment by rupinderkang-teck** [comment]
WAM Sample code that you provided works on the window but not on the windows server.  On windows server I am getting error: Could not acquire a token silently from cache or broker... MSAL.Desktop.4.49.1.0.MsalUiRequiredException: 
ErrorCode: current_broker_account
Microsoft.Identity.Client.MsalUiRequiredException: Only some brokers (WAM) can log in the current OS account. 

My application is a backend process that reads emails from mailbox. I cannot use interactive authentication.

**Comment by bgavrilMS** [comment]
Go it. Indeed WAM does not work on Server 2016.

If it's a backend process, can you not use `AcquireTokenForClient`, i.e. get a token for an app (not for a user) based on a certificate?

**Comment by rupinderkang-teck** [comment]
To work  with AcquireTokenForClient,  what type of permissions should I configure on Azure to read mailbox, Delegated permissions or Application permissions?

![image](https://user-images.githubusercontent.com/107279356/213064658-b5df67de-b000-4d32-8e02-71d70a667ded.png)

I have Delegated permissions and I am getting error: The remote server returned an error: (403) Forbidden.

**Comment by bgavrilMS** [comment]
Application permissions are needed for AcquireTokenForClient.

And the scope string will be the name of the resource, e.g. `AcquireTokenForClient("https://graph.microsoft.com/.default")` - the token will have the correct "scopes" inside.

**Comment by rupinderkang-teck** [comment]
There were some changes by our AAD admin at organizational level.  Two things helped the same Integrated Windows Authentication on to work:
1. Excluding service account (under which service was running) from the MFA conditional access policy
2. Enabling desktop SSO
