### ISSUE TITLE
Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found, Getting this error when trying to log into MS account using WAM

### ISSUE THREAD

**Issue by JaninduJay** [AzureAD/microsoft-authentication-library-for-dotnet#3906]
I am trying to implement MSAL to a xamarin windows app. When im trying to use AcquireTokenInteractive it gives me this error.

 " {"Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port
 both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details"} "

CODE:
app = PublicClientApplicationBuilder.Create(ClientId)
                                                        .WithBroker()
                                                        .Build();
                                                        
System.Collections.Generic.IEnumerable<IAccount> accounts = await app.GetAccountsAsync();

AcquireTokenInteractiveParameterBuilder interactiveRequest = await app.AcquireTokenInteractive(GetScopes).WithAccount(accounts.FirstOrDefault()).ExecuteAsync();

AND in Azure AD i have added the below redirecr Uri;
"ms-appx-web://microsoft.aad.brokerplugin/{sid}"

**Comment by bgavrilMS** [comment]
What do you mean "xamarin windows app" ? Do you mean Universal Windows Application or Maui application? You should not use UWP for new apps, use Maui.

The redirect URI you have to register is described here: https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-wam#redirect-uri

**Comment by JaninduJay** [comment]
Hello Sorry for replying late, Do you have a resource regarding MSAL implementation using WAM to a Universal Windows Application (UWP) using latest Microsoft identity client library (4.49.1) .

**Comment by bgavrilMS** [comment]
https://aka.ms/msal-net-wam should explain this

**Comment by JasonYeMSFT** [comment]
Does anyone on this thread understand why the PublicClientApplicationBuilder is trying to use "urn:ietf:wg:oauth:2.0:oob" as the redirect uri? Like in what condition would it use this as the redirect uri? We are seeing a similar issue in our product but we had no idea why it's using it since we should have done the work to set it to something else.

**Comment by elim-mt** [comment]
I am having the same issue here....
```
  // Connection string for the Dataverse service client
 var connectionString = $@"
     AuthType=ClientSecret;
     Url={dataverseUrl};
     ClientId={clientId};
     ClientSecret={clientSecret};
     Authority=https://login.microsoftonline.com/{tenantId};
     RedirectUrl=http://localhost
 ";

 using (var serviceClient = new ServiceClient(connectionString))
 {
       : 
 }
```
and I am getting the error message:
```
Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseConnectionException
  HResult=0x80131500
  Message=Failed to connect to Dataverse
  Source=Microsoft.PowerPlatform.Dataverse.Client
  StackTrace:
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateServiceConnection(Object externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId, SecureString password, String domain, String Geo, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, String clientId, Uri redirectUri, PromptBehavior promptBehavior, OrganizationWebProxyClientAsync externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned, Boolean useDefaultCreds, Version incomingOrgVersion, ILogger externalLogger, String tokenCacheStorePath)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.ConnectToService(String connectionString, ILogger logger)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient..ctor(String dataverseConnectionString, ILogger logger)
   at TestDataverseSDK.Program.Main(String[] args) in C:\Users\elim\source\repos\TestDataverseSDK\TestDataverseSDK\Program.cs:line 46

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
MsalClientException: Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
```

**Comment by elim-mt** [comment]
> Does anyone on this thread understand why the PublicClientApplicationBuilder is trying to use "urn:ietf:wg:oauth:2.0:oob" as the redirect uri? Like in what condition would it use this as the redirect uri? We are seeing a similar issue in our product but we had no idea why it's using it since we should have done the work to set it to something else.

Looks like you might have to include the .WithDefaultRedirectUri() method call as part of your Build.

**Comment by elim-mt** [comment]
I have a slightly different problem, I am getting the error message:
`AADSTS900971: No reply address provided.`

```
Request Id: a7453e4f-f309-4ba4-98a8-7f4258090000
Correlation Id: d2a9296b-bfa3-477a-b4a0-966951a299db
Timestamp: 2024-11-01T01:29:29Z
Message: AADSTS900971: No reply address provided.
```
and here's what I am trying to do...
```
 // Connection string for the Dataverse service client
 var connectionString = $@"
     AuthType=ClientSecret;
     Url={dataverseUrl};
     ClientId={clientId};
     ClientSecret={clientSecret};
     Authority=https://login.microsoftonline.com/{tenantId};
     RedirectUri=http://localhost
 ";

 using (var serviceClient = new ServiceClient(connectionString))
 {
:
}
```

Can anyone help me please? Thank you.
