### ISSUE TITLE
[Question] AADSTS7000213: Invalid certificate chain

### ISSUE THREAD

**Issue by jsquire** [AzureAD/microsoft-authentication-library-for-dotnet#3909]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#33608](https://github.com/Azure/azure-sdk-for-net/issues/33608).

### Query/Question

I'm migrating from Microsoft.Azure.KeyVault 3.0 to Azure.Security.KeyVault.Certificates 4.4.0. After the migration one of the unit tests started to fail. The exception I get is this:
"Azure.Identity.AuthenticationFailedException: ClientCertificateCredential authentication failed: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000213: Invalid certificate chain.
Timestamp: 2023-01-20 06:53:09Z ---> Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000213: Invalid certificate chain.

I'd like to understand what AADSTS7000213 is and how to go about debugging the failure. The same unittest runs without an issue under the old Microsoft.Azure.KeyVault 3.0. What are the things I should be checking, and to look for?

### Environment

.NET 4.7 on Win 10 
Visual Studio 2019

**Comment by bgavrilMS** [comment]
@shanuwed - the error message is `AADSTS7000213: Invalid certificate chain.`

This means that you are using a certificate to get a token for KeyVault (as you should). To give you a token, AAD must verify the confidentiality between your server and AAD, i.e. it must validate a digital signature which Azure SDK / MSAL generates with the cert you provide. 

As part of validating a digital signature, AAD will also validate that the certificate itself is valid. This means it 's not expired, the thumbprint matches etc. etc. And that the certificate chain is valid. Looks like the certificate chain is not valid, which afaik means that one of the authorities in the certificate chain has been marked as untrusted or an intermediate certificate has expired etc. 

Please check the certificate used.

**Comment by VinayTalla20** [comment]
Hi, we have created cert in keyvault(PME), 
we have updated App Registrations(SP) manifest as below:

"trustedCertificateSubjects": [
        {
            "authorityId": "00000000-0000-0000-0000-000000000001",
            "subjectName": "fe7c10b4-bc92-4498-ae84-adf993d6cc1d.microsoft.com",
            "revokedCertificateIdentifiers": []
        },
        {
            "authorityId": "00000000-0000-0000-0000-000000000001",
            "subjectName": "prod-fe7c10b4-bc92-4498-ae84-adf993d6cc1d.microsoft.com",
            "revokedCertificateIdentifiers": []
        }
    ]
    
    
   when try to run python script
   
   we use below error:
   
   azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS7000213: Invalid certificate chain. Trace ID: 39f5306d-c654-4a94-9899-b1f5b7c02c00 Correlation ID: abaf9c74-d060-4b99-b4d3-e576ff51a086 Timestamp: 2024-05-22 05:19:51Z

**Comment by aileenlikexin** [comment]
Hi @VinayTalla20 , 
We met the same issue on AME. Have you resolved the issue?

**Comment by aileenlikexin** [comment]
Thanks @VinayTalla20 !

My top suspicion is that our azure key vault certificate was not configured correctly, but don't have much clue. I will briefly list all I have done. Our major goal is to get a token to Azure OpenAI resources ("https://cognitiveservices.azure.com/.default") via Certificate Credentials. We have:
1) Set up the key vault and created a certificate in it. The certificate is a "self-signed" one, but not "issued by an integrated/non-integrated CA". The content type is PKCS#12 but not PEM. Other attributes all followed default azure settings.
2) Registered an application for authentication. The above certificate was added as a trusted certificate subject to the manifest.
3) Added all required role assignment to all resources.

Do you have any suggestions for us, or what is the key point that resolved your issues? Thanks a lot!

**Comment by VinayTalla20** [comment]
Hi @aileenlikexin, 

We have Used below manifest for app regisration in our case we are using authentication from microsoft corp tenant to PME Tenant

 "trustedCertificateSubjects": [
        {
            "authorityId": "00000000-0000-0000-0000-000000000001",
            "subjectName": "msftpipelinesprod.microsoft.com",
            "revokedCertificateIdentifiers": []
        }
    ]

make sure the certificate operation is successful 

![image](https://github.com/user-attachments/assets/9b8681f4-2bae-4172-b405-8d5443f328cc)


Also Don't forget to add    **send_certificate_chain=True**

creds = CertificateCredential(_tenantId, _clientId, certificate_data=get_cert(keyvault_url, cert_name), send_certificate_chain=True)

**Comment by aileenlikexin** [comment]
Thanks @VinayTalla20 ! 

Our issue is now resolved mainly by changing the self-signed certificates to one "issued by an integrated CA", and it looks like your certificate has CA linked to it as well. Then we updated the manifest in app registration accordingly. Thank you so much for the insight!
