### ISSUE TITLE
[Bug] Msal Runtime throws user signed out error when calling acquire token silent.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3916]
**Logs and network traces**
When trying to execute WamUsernamePasswordRequestAsync_WithPiiAsync after the changes in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3859
The following error occurs

Test method Microsoft.Identity.Test.Integration.Broker.RuntimeBrokerTests.WamUsernamePasswordRequestAsync_WithPiiAsync threw exception:
Microsoft.Identity.Client.MsalUiRequiredException: WAM Error

Error Code: 0
Error Message: Account has previously been signed out of this application.
Internal Error Code: 540940121

I cant seem to find this error in our SDK so it looks like it is from WAM. However, it does not make sense. My changes are only affecting local MSAL cache so not sure how calling ATS on WAM can generate this error. There is also an identical test that does not use PII that works fine too.

Test: WamUsernamePasswordRequestAsync_WithPiiAsync - fails
Test: WamUsernamePasswordRequestAsync - passes

![image](https://user-images.githubusercontent.com/30090357/213997247-00f137e6-2f9b-4e08-bb86-18f5bf62208e.png)

Both tests are performing a username password auth to sign the user in and they happen one right after another so maybe there is some race condition?
 
Diff between the two tests

![image](https://user-images.githubusercontent.com/30090357/214511812-7ad46fd7-e51d-4bcb-9b2f-eb759421e15d.png)

**Which version of MSAL.NET are you using?**

latest
**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

**Repro**

execute the following tests one after another:WamUsernamePasswordRequestAsync, WamUsernamePasswordRequestAsync_WithPiiAsync.

**Comment by trwalke** [comment]
Currently on an email thread with Sam to acquire more info. This may be an external issue

**Comment by bgavrilMS** [comment]
Exception thrown is MsalUiRequiredException so this is unlikely to affect existing apps. Marking as P3.

**Comment by bgavrilMS** [comment]
Blocked on MSAL C++

**Comment by gladjohn** [comment]
@trwalke you can use Interop version 0.13.6 to verify this fix
