### ISSUE TITLE
[Bug] MSAL.NET on .NET6 Application not working

### ISSUE THREAD

**Issue by bpescarolli** [AzureAD/microsoft-authentication-library-for-dotnet#3931]
I run Windows Form Application on .NET 6 using Microsoft.Identity.Client and PublicClientAppBuilder, but when clicked to log on ... pops up that message ...

![image](https://user-images.githubusercontent.com/5093247/216307805-a0899855-8302-4fce-b109-4249010b8990.png)

If runs the same code on Windows Forms from .NET Framework 4.6.1 it works perfectly, but not on .NET 6.

The MSAL.NET not have support for .NET 6? or need make somes adaption to the code?

Solve that problem ... or finds alternatives solution ...

follow up that samples on my git repository

[https://github.com/bpescarolli/MSAL_dotnet6 (It not works)](https://github.com/bpescarolli/MSAL_dotnet6)

[github.com/bpescarolli/MSAL_dotnetFramework461 (Its works perfectly)](https://github.com/bpescarolli/MSAL_dotnetFramework461)

**Comment by pmaytak** [comment]
The behavior is different on .NET Framework and .NET 5+. On .NET 6, you need to specifically target `net6.0-windows10.0.17763.0` or later (the TFM must have the Windows SDK version).

We also recommend to use [WAM ](https://aka.ms/msal-net-wam)(Windows broker), it's safer and has more features than a browser. In this case you can still target net6.0 or net6.0-windows.

**Comment by bpescarolli** [comment]
Hello @pmaytak , thanks for the return , I tested now ... according to the guidelines .... and it works , I didn't know there was that WAM detail in the documentation anyway thanks for the heads up.

topic is closed!
