### ISSUE TITLE
Automation certificate "AzureADIdentityDivisionTestAgentCert" will be renewed on Feb 8th

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3939]
Automation certificate "AzureADIdentityDivisionTestAgentCert" in Azure Key Vault "BUILDAUTOMATION" will soon be renewed (Feb 8th) 

Azure Key Vault will renew your (Not configured) certificate on February 8, 2023 19:25 UTC. If applicable, please ensure your certificate registration is up-to-date. For more details, see the link below.

**Account information**
Subscription ID: c1686c51-b717-4fe0-9af3-24a20a41fb0c
Key Vault name: BUILDAUTOMATION
Certificate name: AzureADIdentityDivisionTestAgentCert
Certificate thumbprint: 4E87313FD450985A10BC0F14A292859F2DCD6CD3

This is used in [test automation](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4ad4790397c7099e34c6ff5de768a43475d16e22/tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs#L19)

**Comment by pmaytak** [comment]
We should spend some time to complete https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3293, so we don't worry about rotating certs each time.

**Comment by bgavrilMS** [comment]
Agreed, KV can generate a new cert. All we need is to load the cert "by name". Sort  of a poor man's SN/I

**Comment by gladjohn** [comment]
@SameerK-MSFT assigning this to you per today's discussion. 

**Option 1 :** Fix #3293 

**Option 2 :** If Option 1 is a stretch before the release then we just fix this current task

**Comment by SameerK-MSFT** [comment]
I would do in two steps:
1. Update the thumbprint
2. Do CN. If time runs out, stick with #1 for this release.

**Comment by SameerK-MSFT** [comment]
Closed as per https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3949
