### ISSUE TITLE
Can't login with Office365 account.

### ISSUE THREAD

**Issue by 23W** [AzureAD/microsoft-authentication-library-for-dotnet#394]
When user tries to login with Office365 credentials it see "needs permission window". But when it press Accept button nothing happens. Others buttons (Cancel and Show details links work fine).

MSAL version: 1.1.0.277 (alpha).

P.S.: When is MSAL 1.1 release planned?
P.P.S: Why is exception code "consent_required" absent? I thought it should be in MsalClientException class.

**Comment by kpanwar** [comment]
What platform are you targeting? Can you share the logs? You can provide a delegate in Logger class to collect logs. 
Consent_required is not a top level error code. Server classifies them as invalid_grant.

**Comment by kpanwar** [comment]
You should use the latest from myget feed.

**Comment by 23W** [comment]
Last version (alpha 335) works fine.
My platform: .Net45.
Alpha 277 threw "consent_required" exception when user with Office365 account answered "Cancel" on app access permissions.

**Comment by kpanwar** [comment]
Around //BUILD, which is next week.

**Comment by 23W** [comment]
It's a great news, thank you!
