### ISSUE TITLE
[Bug] Exception thrown on WAM while hitting the back button on the AAD plugin

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3965]
**Logs and network traces**
```
{Status: Unexpected
Error: 0xcaa20004
Context: AADSTS90123: The token can't be issued because the identity or claim issuance provider denied the request. Response code: access_denied.
Trace ID: 70012e01-5118-4111-9463-8e30368b9601
Correlation ID: 8c47e613-9d60-4e27-a884-c419fa4c3a38
Timestamp: 2023-02-02 16:38:14Z
Tag: 0x21420087}
```

**Which version of MSAL.NET are you using?**
MSAL 4.50.0

**Platform**
Net Core

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
new for msal 4.50.0

**Repro**

```
**Here are the settings to repro :** 

Authority : lmo/org

MSA-PT = True

Provide a Login Hint. 

Interop version : latest 

Once the AAD plugin pops up, hit the back button (left of the UPN)
```

**Expected behavior**
Back should take to the logon screen without exceptions

**Actual behavior**
AADSTS90123: The token can't be issued because the identity or claim issuance provider denied the request. 

**Additional context / logs / screenshots / links to code**
[Internal tracking bug ](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2375805)

**Comment by bgavrilMS** [comment]
@gladjohn - I marked this as "extenal", please correct me if I am wrong.

**Comment by MSamWils** [comment]
As mentioned from gladjohn, it's tracked by this internal bug:
[Internal tracking bug](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2375805), which is on the ESTS UX side.
