### ISSUE TITLE
Where has microsoft-authentication-library-for-cpp gone?

### ISSUE THREAD

**Issue by atesti** [AzureAD/microsoft-authentication-library-for-dotnet#3968]
I want to understand how WAM works under the hood and implement it myself.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam
indicates that
https://www.nuget.org/packages/Microsoft.Identity.Client.NativeInterop
needs to be installed, that [microsoft-authentication-library-for-dotnet](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) requires addtional native source code in order to use WAM.

However, the nuget package points to
https://github.com/AzureAD/microsoft-authentication-library-for-cpp
which has been deleted.

Can you restore that repository or provide the source code how WAM actually works?

What is the real internal API that WAM uses?

**Comment by bgavrilMS** [comment]
It's not deleted, it's just private. The CPP team have it on their roadmap to open source the repository. I do not have an ETA.

Note that WAM code is part of Windows and not open source.
