### ISSUE TITLE
[Bug] Need better error message when broker and embeddedview is set to false

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3972]
When Broker is set to false at the app level and .WithUseEmbeddedView is also set to false, we need to handle the exception 

![image](https://user-images.githubusercontent.com/90415114/220699532-942244dd-d4b2-459b-b446-4bc1eaef8c12.png)

**Comment by trwalke** [comment]
Not sure I understand this one @GladwinJohnson. 
Seems like the error provided is telling you what to do. When I tried using a loopback redirect Uri `http://localhost` in this scenario, the authentication worked.

Perhaps there is some context I am missing here?

**Comment by bgavrilMS** [comment]
Agreed, let's keep as is.
