### ISSUE TITLE
[Feature Request] Something like WAM but for Linux or other non-Windows OS

### ISSUE THREAD

**Issue by agoodwin** [AzureAD/microsoft-authentication-library-for-dotnet#3977]
(Apologies if this functionality is already covered, I have searched but I am sure I could have missed something obvious.)

We are developing more and more cross-platform tools. In particular, we have Python tools that are run on both Windows and Linux and these need to call our backend APIs secured with AzureAD/MSAL.

On Windows, we have been using the Integrated Windows Authentication (IWA) flow, and we are just starting to get into using this on AD-joined Linux machines with users signed in using their AD-accounts. Despite the name, Integrated "Windows" Authentication, [this page](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication) seems to clearly indicate that we're not doing anything crazy by expecting this to work on our Linux machines.

However, in the link I gave above, it also clearly recommends moving away from IWA to instead use something I hadn't heard of before, WAM. That's fine, but I see this is a Windows 10+ technology only, and it's specifically mentioned that it will fall back to a browser sign-in prompt on other operating systems.

For our tools generally, but especially Python tools that are run through a shell, it doesn't make sense to prompt the user in any way when they've already had to sign in using their domain account (either to Windows or their Linux shell). So we are very much in favour of the IWA approach, where users are silently authenticated without any interaction required. In some cases there is no UI session for the browser prompt to work in, which further makes it important that we don't hassle the user with needing a device code or something like that.

**Describe the solution you'd like**
So the functionality I'd like to ask for, if IWA is being discouraged, is some equivalent solution to WAM that is recommended for non-Windows machines, that will provide that same user experience of not prompting for an interactive sign-in when the user has already had to do this to get into the machine in the first place. Or, if this solution already exists, what is that recommended solution?

**Describe alternatives you've considered**
IWA is what we've considered and are using. As long as this is expected to be supported into the future, we will stick with this, as it appears to us after some brief initial testing that it works fine on our AD-joined Linux machines. It seems to meet all of our requirements, other than some flakiness we're trying to solve with certain machine/user combinations, and other than the concern raised by the documentation discouraging it in favour of WAM.

**Comment by gladjohn** [comment]
HI @agoodwin, 

looks like you already saw the WAM docs at [https://aka.ms/msal-net-wam](https://aka.ms/msal-net-wam) "WAM can login the current windows user silently." If you want to login the user that is logged on to the machine, you can use the `PublicClientApplication.OperatingSystemAccount` more info and [samples here](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-wam)

Also take a look at [IWA constraints](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication#constraints) and how WAM overcomes most of those. 

We will be adding support to other OSs in WAM in the near future.

**Comment by agoodwin** [comment]
Great, thanks @gladjohn. I think the key thing for us there is that WAM support for other OSs is coming soon, so that sounds promising.

Given that IWA seems to currently work for all of our needs, we'll probably stick with that in the immediate future rather than taking the time and effort to further research into WAM right now. But it sounds like WAM will be a promising change of technology for us to do in future, once the other OS support is there.
