### ISSUE TITLE
[Bug] VM Managed Identity (Experimental) throws wrong exception when wrong resource is passed

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3979]
**Logs and network traces**
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:08Z] ManagedIdentityApplication 32854180 created
Acquiring token with scope https://managements.azure.com/.default
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] MSAL MSAL.NetCore with assembly version '4.46.0.0'. CorrelationId(d2491c38-16f3-40be-9bf1-ac8eeecc4046)
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] === AcquireTokenForManagedIdentityParameters ===
ForceRefresh: False

True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046]
=== Request Data ===
Authority Provided? - True
Client Id - ManagedIdentityDefaultClientId
Scopes -
Redirect Uri - https://replyUrlNotSet
Extra Query Params Keys (space separated) -
ClaimsAndClientCapabilities -
Authority - https://login.microsoftonline.com/common/
ApiId - AcquireTokenForManagedIdentity
IsConfidentialClient - False
SendX5C - False
LoginHint -
IsBrokerConfigured - False
HomeAccountId -
CorrelationId - d2491c38-16f3-40be-9bf1-ac8eeecc4046
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] === Token Acquisition (ManagedIdentityAuthenticationRequest) started:
        Authority: https://login.microsoftonline.com/common/
        Scope:
        ClientId: ManagedIdentityDefaultClientId

True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Internal cache] Total number of cache partitions found while getting access tokens: 0
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [FindAccessTokenAsync] Discovered 0 access tokens in cache using partition key: ManagedIdentityDefaultClientId_common_AppTokenCache
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [FindAccessTokenAsync] No access tokens found in the cache. Skipping filtering.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Region discovery] Not using a regional authority.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Instance Discovery] Skipping Instance discovery because it is disabled.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Authority validation enabled? False.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Authority validation - is known env? True.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Starting ManagedIdentityClient:.ctor
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Managed Identity] Service Fabric managed identity unavailable.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Managed Identity] App service managed identity is unavailable.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Managed Identity] Cloud shell managed identity is unavailable.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Managed Identity] Azure Arc managed identity is unavailable.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Managed Identity] Unable to find AZURE_POD_IDENTITY_AUTHORITY_HOST environment variable for IMDS, using the default endpoint.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [Managed Identity] Creating IMDS managed identity source. Endpoint URI: http://169.254.169.254/metadata/identity/oauth2/token
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Finished ManagedIdentityClient:.ctor in 31 ms
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Starting [HttpManager] ExecuteAsync
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [HttpManager] Sending request. Method: GET. URI: http://169.254.169.254/metadata/identity/oauth2/token.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] [HttpManager] Received response. Status code: BadRequest.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Finished [HttpManager] ExecuteAsync in 602 ms
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Response status code does not indicate success: 400 (BadRequest).
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:09Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Request retry failed.
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:10Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] Error message: [Managed Identity] Authentication unavailable. The requested identity has not been assigned to this resource.
Status: BadRequest
Content:
{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://managements.azure.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: ab366fb9-c13f-4b41-b441-5833b3592401\r\nCorrelation ID: 9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4\r\nTimestamp: 2023-02-27 21:52:09Z","error_codes":[500011],"timestamp":"2023-02-27 21:52:09Z","trace_id":"ab366fb9-c13f-4b41-b441-5833b3592401","correlation_id":"9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4","error_uri":"https://westus2.login.microsoft.com/error?code=500011"}

Headers:
Server: IMDS/150.870.65.926
Date: Mon, 27 Feb 2023 21:52:09 GMT

[Managed Identity] Error Code: invalid_resource Error Message: AADSTS500011: The resource principal named https://managements.azure.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: ab366fb9-c13f-4b41-b441-5833b3592401
Correlation ID: 9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4
Timestamp: 2023-02-27 21:52:09Z Http status code: BadRequest
True MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.14 Microsoft Windows 10.0.14393 [2023-02-27 21:52:10Z - d2491c38-16f3-40be-9bf1-ac8eeecc4046] MSAL.NetCore.4.46.0.0.MsalServiceException:
        ErrorCode: managed_identity_request_failed
Microsoft.Identity.Client.MsalServiceException: [Managed Identity] Authentication unavailable. The requested identity has not been assigned to this resource.
Status: BadRequest
Content:
{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://managements.azure.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: ab366fb9-c13f-4b41-b441-5833b3592401\r\nCorrelation ID: 9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4\r\nTimestamp: 2023-02-27 21:52:09Z","error_codes":[500011],"timestamp":"2023-02-27 21:52:09Z","trace_id":"ab366fb9-c13f-4b41-b441-5833b3592401","correlation_id":"9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4","error_uri":"https://westus2.login.microsoft.com/error?code=500011"}

Headers:
Server: IMDS/150.870.65.926
Date: Mon, 27 Feb 2023 21:52:09 GMT

[Managed Identity] Error Code: invalid_resource Error Message: AADSTS500011: The resource principal named https://managements.azure.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: ab366fb9-c13f-4b41-b441-5833b3592401
Correlation ID: 9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4
Timestamp: 2023-02-27 21:52:09Z
   at Microsoft.Identity.Client.ManagedIdentity.ImdsManagedIdentitySource.HandleResponseAsync(AcquireTokenForManagedIdentityParameters parameters, HttpResponse response, CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\ManagedIdentity\ImdsManagedIdentitySource.cs:line 101
   at Microsoft.Identity.Client.ManagedIdentity.ManagedIdentitySource.AuthenticateAsync(AcquireTokenForManagedIdentityParameters parameters, CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\ManagedIdentity\ManagedIdentitySource.cs:line 81
   at Microsoft.Identity.Client.ManagedIdentity.ManagedIdentityClient.SendTokenRequestForManagedIdentityAsync(AcquireTokenForManagedIdentityParameters parameters, CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\ManagedIdentity\ManagedIdentityClient.cs:line 37
   at Microsoft.Identity.Client.Internal.Requests.ManagedIdentityAuthenticationRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\Internal\Requests\ManagedIdentityAuthenticationRequest.cs:line 91
   at Microsoft.Identity.Client.Internal.Requests.ManagedIdentityAuthenticationRequest.ExecuteAsync(CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\Internal\Requests\ManagedIdentityAuthenticationRequest.cs:line 81
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\Internal\Requests\RequestBase.cs:line 95
        StatusCode: 0
        ResponseBody:
        Headers:
managed_identity_request_failed
[Managed Identity] Authentication unavailable. The requested identity has not been assigned to this resource.
Status: BadRequest
Content:
{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://managements.azure.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: ab366fb9-c13f-4b41-b441-5833b3592401\r\nCorrelation ID: 9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4\r\nTimestamp: 2023-02-27 21:52:09Z","error_codes":[500011],"timestamp":"2023-02-27 21:52:09Z","trace_id":"ab366fb9-c13f-4b41-b441-5833b3592401","correlation_id":"9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4","error_uri":"https://westus2.login.microsoft.com/error?code=500011"}

Headers:
Server: IMDS/150.870.65.926
Date: Mon, 27 Feb 2023 21:52:09 GMT

[Managed Identity] Error Code: invalid_resource Error Message: AADSTS500011: The resource principal named https://managements.azure.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: ab366fb9-c13f-4b41-b441-5833b3592401
Correlation ID: 9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4
Timestamp: 2023-02-27 21:52:09Z
   at Microsoft.Identity.Client.ManagedIdentity.ImdsManagedIdentitySource.HandleResponseAsync(AcquireTokenForManagedIdentityParameters parameters, HttpResponse response, CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\ManagedIdentity\ImdsManagedIdentitySource.cs:line 101
   at Microsoft.Identity.Client.ManagedIdentity.ManagedIdentitySource.AuthenticateAsync(AcquireTokenForManagedIdentityParameters parameters, CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\ManagedIdentity\ManagedIdentitySource.cs:line 81
   at Microsoft.Identity.Client.ManagedIdentity.ManagedIdentityClient.SendTokenRequestForManagedIdentityAsync(AcquireTokenForManagedIdentityParameters parameters, CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\ManagedIdentity\ManagedIdentityClient.cs:line 37
   at Microsoft.Identity.Client.Internal.Requests.ManagedIdentityAuthenticationRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\Internal\Requests\ManagedIdentityAuthenticationRequest.cs:line 91
   at Microsoft.Identity.Client.Internal.Requests.ManagedIdentityAuthenticationRequest.ExecuteAsync(CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\Internal\Requests\ManagedIdentityAuthenticationRequest.cs:line 81
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\Internal\Requests\RequestBase.cs:line 95
   at Microsoft.Identity.Client.ApiConfig.Executors.ManagedIdentityExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForManagedIdentityParameters managedIdentityParameters, CancellationToken cancellationToken) in F:\MsiApiPrototype\src\client\Microsoft.Identity.Client\ApiConfig\Executors\ManagedIdentityExecutor.cs:line 48
   at Program.<Main>$(String[] args) in F:\MsiApiPrototype\tests\devapps\Managed Identity apps\ManagedIdentityAppVM\Program.cs:line 21

**Which version of MSAL.NET are you using?**

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [x] Service to Service calls - Managed Identity Experimental Feature testing

Other?

**Is this a new or existing app?**

**Repro**

```csharp
using Microsoft.Identity.Client;
using Microsoft.IdentityModel.Abstractions;

IIdentityLogger identityLogger = new IdentityLogger();

IManagedIdentityApplication mi = ManagedIdentityApplicationBuilder.Create()
                .WithLogging(identityLogger, true)
                .Build();

string? scope = "https://managements.azure.com/.default";

do
{
    Console.WriteLine($"Acquiring token with scope {scope}");

    try
    {
        var result = await mi.AcquireTokenForManagedIdentity(scope)
            .ExecuteAsync().ConfigureAwait(false);

        Console.WriteLine("Success");
        Console.ReadLine();
    }
    catch (MsalServiceException e)
    {
        Console.WriteLine(e.ErrorCode);
        Console.WriteLine(e.Message);
        Console.WriteLine(e.StackTrace);
        Console.ReadLine();
    }

    Console.WriteLine("Enter the scope to acquire token.");
    scope = Console.ReadLine();
} while (!string.IsNullOrEmpty(scope));
```

**Expected behavior**
[Managed Identity] Error Code: invalid_resource Error Message: AADSTS500011: The resource principal named https://managements.azure.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

**Actual behavior**
Microsoft.Identity.Client.MsalServiceException: [Managed Identity] Authentication unavailable. The requested identity has not been assigned to this resource.
Status: BadRequest
Content:
{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://managements.azure.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: ab366fb9-c13f-4b41-b441-5833b3592401\r\nCorrelation ID: 9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4\r\nTimestamp: 2023-02-27 21:52:09Z","error_codes":[500011],"timestamp":"2023-02-27 21:52:09Z","trace_id":"ab366fb9-c13f-4b41-b441-5833b3592401","correlation_id":"9fa23f6b-f55c-4e1c-bd5f-9c3c68122ca4","error_uri":"https://westus2.login.microsoft.com/error?code=500011"}

**Possible solution**
The requested identity has not been assigned to this resource could be misleading here, Since the System Identity has been assigned to the VM. This is not a Service Exception but user passed a wrong resource. 

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by gladjohn** [comment]
```cs
string? scope = "https://managements.azure.com/.default";
```

non-existent scope used, which is a user error in this case.

**Comment by neha-bhargava** [comment]
This is a service exception as we are not validating the resource in MSAL and the error comes from the service. We can maybe update the error message for this exception.

**Comment by bgavrilMS** [comment]
Propose to won't fix this.
