### ISSUE TITLE
[Bug] NETSDK1149	Microsoft.Identity.Client.Desktop.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.  

### ISSUE THREAD

**Issue by TaviTruman** [AzureAD/microsoft-authentication-library-for-dotnet#3982]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**

Microsoft.Identity.Client.Desktop 4.50.0
**Platform**

	<TargetFrameworks>net7.0-windows</TargetFrameworks>
**What authentication flow has the issue?**
* Desktop / Mobile
    * [x ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

Severity	Code	Description	Project	Line	File	Suppression State
Error	NETSDK1149	Microsoft.Identity.Client.Desktop.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.  An updated version of the component supporting .NET 5 is needed. For more information, see https://aka.ms/netsdk1149	RUB.IG.AdminUI	1033	C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	

**Is this a new or existing app?**

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
Be able to perform a build

**Actual behavior**
Severity	Code	Description	Project	Line	File	Suppression State
Error	NETSDK1149	Microsoft.Identity.Client.Desktop.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.  An updated version of the component supporting .NET 5 is needed. For more information, see https://aka.ms/netsdk1149	RUB.IG.AdminUI	1033	C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by pmaytak** [comment]
Your app needs to target a specific Windows SDK version, net7.0-windows10.0.17763.0 or above, and not reference Microsoft.Identity.Client.Desktop.

You can also target just net7.0 and reference Microsoft.Identity.Client.Broker for new WAM experience (this will be generally available in the next release).

**Comment by TaviTruman** [comment]
@pmaytak I wish you had not been so quick to close out this issue. I have a WPF application that targets .NET 7, and I use the [Community toolkit Graph-Controls](https://github.com/CommunityToolkit/Graph-Controls) in the project. The Graph-Controls library makes use of Microsoft.Identity.Client.Desktop package.

**Comment by pmaytak** [comment]
[This sample](https://github.com/CommunityToolkit/Graph-Controls/tree/main/Samples/WpfNetWindowsMsalProviderSample) works for me. Graph-Controls only references MSAL.Desktop on netcoreapp3.1 TFM. But it also has a target for net6.0-windows10.0.17763.0, which is correctly picked up if your app targets net7.0-windows10.0.17763.0.

**Comment by pmaytak** [comment]
Just to confirm, does your app work now?

**Comment by TaviTruman** [comment]
@bgavrilMS I don't; the code comes from the CommunityToolkit Graph-Controls Sample.

**Comment by TaviTruman** [comment]
@pmaytak Yes! My app now works!
