### ISSUE TITLE
[Feature Request] In Identity.Client project change “net6.0-windows10.0.17763.0” to just “net6.0-windows”

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#3986]
**Is your feature request related to a problem? Please describe.**
Yes. Removed dependency on Window platforms

**Describe the solution you'd like**
change “net6.0-windows10.0.17763.0” to just “net6.0-windows”

**Describe alternatives you've considered**
NA

**Comment by bgavrilMS** [comment]
Ack, thanks for the reference. There aren't actually any known issues with a legitimate app using embedded webview, only with malicious app using webview. But then again, a malicious app already installed can do much more damage, e.g. it can redirect your to a hacked authorization endpoint to steal username / password using the system browser. 

But I agree we could have handled the transition from net6-windowsXYZ to net6-windows better, possibly by taking a breaking change.
