### ISSUE TITLE
How to define/limit login type for Live or Office365 account?

### ISSUE THREAD

**Issue by 23W** [AzureAD/microsoft-authentication-library-for-dotnet#399]
How can I limit login type for users (Live\Personal only or Azure\Office365 only). For example, I want to allow only users with Microsoft Personal accounts (formerly Live) to login in my app. And only in Pro version app allows Office365 accounts to login (but with different command). 
So I want to separate login method for different endpoints. Can I do it in MSAL?

platform: .Net45
app: desktop application.

And second question: Is there a way of determining account type (e.g. Live\Personal only or Azure\Office365) associated with a particular email address before authetication/authorization?

**Comment by kpanwar** [comment]
I don't understand what you mean by "but with different command". Can you expand?
Yes, you can authenticate against different endpoints. to authenticate only MSA accounts use https://login.microsoftonline.com/consumers/ as the authority. For your "pro version" of the app,  you don't need to pass in any authority, as the API uses "https://login.microsoftonline.com/common/" by default. It will allow both MSA and AAD users to sign into your app.

**Comment by 23W** [comment]
@kpanwar , thank you.
About commands: I meant UI "commands" in my app. Sorry if it was understand. I want to use two UI commands in main app menu: "Login with Personal account" and "Login with Office365 account" (in pro version only).  Depends on which user select, app will provides different services.

Authorities: As I understand, I can change `authority` parameter in `PublicClientApplication` constructor for limit MSAL by account type that is required for me.
My "Login with Personal account" should use `https://login.microsoftonline.com/consumers/` for login with MSA(Personal) account only. It's understand.
Which `authority` should be used by "Login with Office365 account" for login with AAD only?

P.S.: Default authority is convenient as universal method of course. But I need in two separated login methods.

**Comment by kpanwar** [comment]
Yes, use organizations in that cAse.

**Comment by 23W** [comment]
thank you
