### ISSUE TITLE
[Bug] Use of WithProofOfPossession in PCA should not be listed as Experimental when WAM GAs

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3992]
**Logs and network traces**
none

**Which version of MSAL.NET are you using?**
MSAL 4.50.0

**Platform**
Net 5.0 Windows xxxx 

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive - WAM
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
Dev App

**Repro**

```csharp
catch (MsalUiRequiredException)
            {
                result = await pca
                    .AcquireTokenInteractive(s_scopes)
                    .WithParentActivityOrWindow(hWnd)
                    .WithProofOfPossession("nonce", System.Net.Http.HttpMethod.Get, s_downstreamApi)
                    .ExecuteAsync()
                    .ConfigureAwait(false);
            }
```

**Expected behavior**
Use of WithProofOfPossession in PCA should not be listed as Experimental when WAM GAs

**Actual behavior**
Use of WithProofOfPossession in PCA is currently listed as Experimental 

**Additional context / logs / screenshots / links to code**
![image](https://user-images.githubusercontent.com/90415114/223331788-3d1f9ae8-3fa6-4357-92ef-678117fc7505.png)

**Comment by bgavrilMS** [comment]
Agreed
