### ISSUE TITLE
[Feature Request] Support "spa_accountId" response parameter from STS

### ISSUE THREAD

**Issue by will-bartlett** [AzureAD/microsoft-authentication-library-for-dotnet#3994]
**Is your feature request related to a problem? Please describe.**
Azure Portal is working on a feature (called the WebNativeBridge) which enables it to use OS single sign-in state. This feature initializes MSAL.JS with a parameter "accountId" which is a handle into the native operation system instead of the normal OAuth authorization code parameter. When Azure Portal uses this feature in its "hybrid SPA" implementation, the server returns this parameter to the confidential client in the field "spa_accountId" instead of the existing parameter "spa_code". MSAL.JS needs to use this parameter to initialize itself.

**Describe the solution you'd like**
Like AuthResult.SPA_CODE, expose AuthResult.SPA_ACCOUNTID. 

**Describe alternatives you've considered**
Alternatively, expose AuthResult.AdditionalParameters, so we can access AuthResult.AdditionalParameters["spa_accountId"].

Another alternative considered - putting spa code and spa accountid in the same field - does not work. Both codes and accountids are opaque. MSAL.JS needs to know whether the opaque value used to initialize it is an authorization code or an accountId.

**Additional context**
Part of zod. 

** Algorithm **

<img width="539" alt="image" src="https://user-images.githubusercontent.com/12273384/224666092-06ba6253-ce6d-4ce9-b468-ba23e4c3d066.png">

Note ^^  that MSAL.NET does not make /authorization calls, it just formats the URL and using `WithExtraQueryParameters` is sufficient here.

**Comment by bgavrilMS** [comment]
CC @gladjohn and @jmprieur

**Comment by bgavrilMS** [comment]
JS changes associated with this: 

https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5759/files#diff-e7645604421092f76d09943662ec9f80a9c22dc2b3a0ff05189f985bb0e5c444
