### ISSUE TITLE
[Bug]  ConfidentialClientApplicationBuilder.WithAuthority expects base url to not have path 

### ISSUE THREAD

**Issue by ohadbitt** [AzureAD/microsoft-authentication-library-for-dotnet#3995]
**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.48.0
**Platform**
.net6  Win64

**What authentication flow has the issue?**
Confidential client app

**Is this a new or existing app?**
existing

**Repro**

```csharp
var cca = ConfidentialClientApplicationBuilder.Create(applicationClientId)
                                                              .WithAuthority("https://host.core.azure-test.net/dstsv2", "tid")


```

**Expected behavior**
cca.Authority should be `https://host.core.azure-test.net/dstsv2/tid`

**Actual behavior**
`https://host.core.azure-test.net/tid` 

Workaround: 

WithAuthority("https://host.core.azure-test.net/dstsv2/tid")

**Comment by bgavrilMS** [comment]
This is a bug with Dsts authority formation.

**Comment by trwalke** [comment]
I cant seem to reproduce this with the latest version of MSAL. 
![image](https://user-images.githubusercontent.com/30090357/234166089-c1872791-5871-4195-8649-fa5a8dc1a95b.png)
However, it does repro with the 4.48.0 version. Can you try the [latest version](https://www.nuget.org/packages/Microsoft.Identity.Client/4.53.0) of MSAL and confirm if it works for you as well? @ohadbitt

**Comment by bgavrilMS** [comment]
Closed as resolved. Please reopen if issue persists.
