### ISSUE TITLE
[Bug] Error in Android manifest

### ISSUE THREAD

**Issue by azharuddinsayed** [AzureAD/microsoft-authentication-library-for-dotnet#4002]
Severity	Code	Description	Project	File	Line	Suppression State
Error		..\obj\Release\130\lp\102\jl\AndroidManifest.xml Warning:
	Namespace 'com.google.android.gms.auth.api' used in: AndroidManifest.xml, AndroidManifest.xml.

	android:exported needs to be explicitly specified for element <activity#crc648316b0a9aa8cfd61.BrowserTabActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
Directory 'obj\Release\130\lp\102' is from 'Xamarin.GooglePlayServices.Auth.Api.Phone.dll'.	...\obj\Release\130\AndroidManifest.xml	49

**Comment by bgavrilMS** [comment]
Please try to give more information on how to repro this.

**Comment by azharuddinsayed** [comment]
@bgavrilMS what are the more information you need , please let me know

**Comment by bgavrilMS** [comment]
I see that you have commented on a similar issue that was closed ? Is that the root cause?

**Comment by azharuddinsayed** [comment]
@bgavrilMS i am using Xamarin.Forms [5.0.0.2515] Android Issue
Microsoft.Identity.Client 4.50.0
but still i am facing the issue

**Comment by bgavrilMS** [comment]
Did the workaround provided in the original issue not work?

**Comment by azharuddinsayed** [comment]
@bgavrilMS we do not have any plan to move to MAUI now it will take time.

**Comment by bgavrilMS** [comment]
I suggest that you try to find a fix in MSAL yourself. The team is busy with security work on desktop environments and we will not be fixing Xamarin bugs, but we do accept contributions.

**Comment by SameerK-MSFT** [comment]
Being a Xamarin bug, this will not be fixed.

**Comment by bgavrilMS** [comment]
@kennyoye88  - we don't know who you are or why you are getting emails? Did you click the "Watch" button on GitHub?

<img width="455" alt="image" src="https://user-images.githubusercontent.com/12273384/227334261-4d77aaf2-b3c4-46a0-bfb3-23ebe0caa485.png">
