### ISSUE TITLE
[Feature Request] ConfidentialClientApplicationBuilder support for managed identity and federated identity credentials

### ISSUE THREAD

**Issue by timmydo** [AzureAD/microsoft-authentication-library-for-dotnet#4004]
**Is your feature request related to a problem? Please describe.**
I have a service in azure using user-assigned managed identity. I want this service to be able to get credentials representing an AAD application (which is running under a different AAD tenant than the managed identity token). Then I want to get a token for the AAD application that I can send to other services (key vault, etc.).

**Describe the solution you'd like**

I'm trying to figure out how to use MSAL/ConfidentialClientApplicationBuilder to do this.

**Describe alternatives you've considered**
I was hoping this would be supported by MSAL.

**Additional context**

https://learn.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0

Maybe this is already supported but I can't find any docs on it?

**Comment by bgavrilMS** [comment]
MSAL 4.51 (scheduled to be released in a few days) will bring Managed Identity support as a preview API. Otherwise, you'll have to use Azure SDK to get that token. 

To use federated credentials, you can utilize the existing api `WithClientAssertion` on the `ConfidentialClientApplication` object. The assertion is the token you get from AAD.

**Comment by bgavrilMS** [comment]
CC @jmprieur

**Comment by timmydo** [comment]
Great. We are already using the Azure SDK to get the MI token. Is there any sample code that shows how to tie it together? Using the Azure SDK with .WithClientAssertion or a full end-to-end with MSAL 4.51?

**Comment by jonso4** [comment]
Hey @bgavrilMS, I just tried to use federated credentials to use AAD app X to request a token for a resource that grants access to AAD app Y. I ran into an error of "AAD-issued tokens may not be used for federated identity flows". Is there any plan to support this?

**Comment by bgavrilMS** [comment]
Hi @jonso4 and @timmydo - I'm going to close this as part of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3754

We have just shipped managed identity support APIs as public preview. We don't have docs and sample yet, these are being worked on, but our PM did come out with a blog post:

https://den.dev/blog/managed-identity-msal-net/
