### ISSUE TITLE
Update MSAL.NET ruleset/editorconfig with thew latest recommended rules from 1ES

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#4007]
**Is your feature request related to a problem? Please describe.**
Currently, the ruleset we use has fallen behind the most recent set of rules outlined by 1ES. 

**Describe the solution you'd like**
We need to update the .editorConfig files in MSAL to reflect these new updates. Ruleset can be found here: [1ES Ruleset](https://www.1eswiki.com/wiki/Microsoft.Internal.Analyzers.Rulesets#Consuming_Microsoft.Internal.Analyzers.Rulesets_in_your_source_tree)

**Describe alternatives you've considered**
Identify if it is possible to make the ruleset/.editorconfig update automatically with the latest from 1ES

**Additional context**
Ruleset files can be converted to .editorconfigs using the analyzer package provided by 1es `Microsoft.Internal.Analyzers`

**Comment by bgavrilMS** [comment]
@trwalke - how are we going to consume this ? The NuGet package is internal.
