### ISSUE TITLE
[Engineering Task] Develop an e2e test strategy for MSI and test Web App Scenarios

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4012]
Tracking item for a CI based e2e test scenario for MSI. 

- E2E test needs to run only only in our Release pipeline 
- During the Release builds, Deploy MSAL MSI sample web app (@neha-bhargava will be pushing this to the dev app) to Azure App Service ([App created](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/c1686c51-b717-4fe0-9af3-24a20a41fb0c/resourceGroups/MSAL_MSI/providers/Microsoft.Web/sites/msimsalintegration/appServices) for this purpose) (Owner : @trwalke)
- Fail build if deployment to Web App fails (Owner : @trwalke)
- Add a new Test Project and call it `Microsoft.Identity.Test.E2E`, add tests that will call into the above published Web App and get a token (Owner : @gladjohn)

**Comment by gladjohn** [comment]
here is the [one pager](https://microsoft.sharepoint-df.com/:w:/t/ID4S/EWL14HQvySRPg8X15_Y-r9YBI-kUTC2sv75qSQVxqC3F9w?e=5fDeWZ) for the security hackathon

**Comment by bgavrilMS** [comment]
Deprioritizing

**Comment by bgavrilMS** [comment]
Insufficient ROI for this. Let's revisit if a better strategy is brought up.
