### ISSUE TITLE
[Samples] Need to create MSI samples and link to docs

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4013]
Need to create MSI samples and link to docs

**Comment by localden** [comment]
@gladjohn flagging here for awareness, but we have this: https://github.com/Azure-Samples/msal-managed-identity

I will work on updating the `README` in that repository to make sure developers have a good "getting started" experience.

**Comment by gladjohn** [comment]
@localden can this be closed?
