### ISSUE TITLE
[Documentation] Update documentation for WAM

### ISSUE THREAD

**Issue by SameerK-MSFT** [AzureAD/microsoft-authentication-library-for-dotnet#4015]
**Documentation related to component**
WAM

**Please check those that apply**

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs Update

**Description of the issue**
WAM is being upgraded to the new broker. This has some breaking changes and needs examples.

**Comment by gladjohn** [comment]
updated the wiki because [https://aka.ms/msal-net-wam](https://aka.ms/msal-net-wam) is still pointing to the Wiki. I will work with Den to understand what needs to be done for the MS docs

**Comment by gladjohn** [comment]
PR by Bogdan : https://github.com/MicrosoftDocs/azure-docs/pull/107791#pullrequestreview-1376281899
