### ISSUE TITLE
[Bug] WAM fails with cannot execute an interactive request

### ISSUE THREAD

**Issue by crmann1** [AzureAD/microsoft-authentication-library-for-dotnet#4033]
**Logs and network traces**

"WAM Error  \n Error Code: 0 \n Error Message: ApiContractViolation \n WAM Error Message: Cannot execute an interactive request because one is already in progress \n Internal Error Code: 523883728 \n Is Retryable: false 

**Which version of MSAL.NET are you using?**
4.48.1

**Platform**
.NET

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X ] Interactive (WAM)

Other?

**Is this a new or existing app?**
VS

**Repro**
No, seen in telemetry

**Comment by gladjohn** [comment]
@crmann1 looks like we have a repro now in VS for this issue. As discussed, this something either MSALRuntime can handle or the apps can handle themselves. But please let us know if there is anyway we could help.

**Comment by gladjohn** [comment]
I created an [internal ADO](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2506452) and assigned this to @MSamWils
