### ISSUE TITLE
Distributed cache solution for managed identity

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#4042]
Since there is no client id in case of system assigned managed identity, the app token cache that we use to cache managed identity tokens can fail for a scenario where distributed cache is used for 2 different resources. Due to same cache key for both the resources, the tokens can be used interchangeably and this is a possible security concern.

**Comment by bgavrilMS** [comment]
Fixed by disabling cache extensibility./
