### ISSUE TITLE
[Feature Request] Revise the minimum number of tests that run

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4050]
Revise min number of tests that run (see the yaml tasks that run tests - look for `minimumExpectedTests: '1'`

**Comment by bgavrilMS** [comment]
The test running tasks have protection against this - we can fail the build if too few tests fail. E.g. NET FWK unit tests less than 1000 -> fail the build.

**Comment by bgavrilMS** [comment]
Generally if 1 test runs, all of them run and we have that protection already.
