### ISSUE TITLE
[Internal] Verify that unit and integration tests cover all platform code paths.

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#4052]
Need to verify that unit and integration tests cover all platform code paths.

Most of the code paths is common - it can be tested on one platform like NetStandard. There are some code paths that need to be tested on different platforms. 
For ex, the JSON handling code needs to be tested on net6+ and non-net6. NetFx and non-NetFx has some different code paths. Net6-win and non-net6-win have different logic for brokers.

**Comment by bgavrilMS** [comment]
.NET and .NET FWK is all we can and should test. unit test run on both. Integration tests should only run on .NET unless there is a specific reason to also run on .NET FWK
