### ISSUE TITLE
[Bug] Build failure. Invalid iOS version

### ISSUE THREAD

**Issue by VladislavAntonyuk** [AzureAD/microsoft-authentication-library-for-dotnet#4091]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**

4.53.0

**Platform**

net7.0-ios

**Repro**

https://github.com/VladislavAntonyuk/MauiSamples/tree/main/Auth/MauiAuth

**Expected behavior**
No build issue.

**Actual behavior**
Error	CS1705	Assembly 'Microsoft.Identity.Client' with identity 'Microsoft.Identity.Client, Version=4.53.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' uses 'Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=16.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

**Possible solution**
Downgrade to 4.52.0

**Additional context / logs / screenshots / links to code**
The latest available version of iOS Sdk is 16.2: https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md

**Comment by gladjohn** [comment]
HI @VladislavAntonyuk, I am not sure where about the `Microsoft.iOS, Version=16.4.0.0` error in `Microsoft.Identity.Client, Version=4.53.0.0` , [MSAL 4.53.0](https://www.nuget.org/packages/Microsoft.Identity.Client/#supportedframeworks-body-tab) uses `net6.0-ios15.4`

**Comment by VladislavAntonyuk** [comment]
My target framework is net7.0-ios.
I tried with net7.0-ios15.4 and got the same error.
The same issue is on CI.

**Comment by pmaytak** [comment]
So I think the app does have to target specific iOS version, like net7.0-ios16.2. Otherwise net7.0-ios will end up picking up net6.0 MSAL binaries. In 4.53.0 we haven't made any changes that would affect the TFMs. When rebuilding as net7.0-ios16.2, is environment clean, and all previous cached bin/obj folders erased? Maybe VS is picking up some old files.

**Comment by VladislavAntonyuk** [comment]
@pmaytak I uses net7.0-ios without specifying version.
The issue is reproducing on CI so I assume the env is clean. 
Could you reproduce the issue from the link I provided?

**Comment by gladjohn** [comment]
@VladislavAntonyuk we are able to repro the issue. We will update once we find the root cause or if we have a workaround or a fix

**Comment by VladislavAntonyuk** [comment]
@gladjohn is there a nightly generated package available, so I can check if the is fixed?

**Comment by VladislavAntonyuk** [comment]
@pmaytak seems like the issue is not fixed.

**Comment by pmaytak** [comment]
@VladislavAntonyuk 16.4 was released 2 days ago. https://www.nuget.org/packages/Microsoft.iOS.Sdk/#versions-body-tab
We verified that our nightly builds were using 16.2 until 2 days ago too.

Can you try updating the iOS MAUI workloads on your machine?

**Comment by VladislavAntonyuk** [comment]
if .net 8 is installed, VS or `dotnet workload install ios` installs version 16.2.462-net8-p3.
it works with .net 7.

**Comment by baskren** [comment]
@VladislavAntonyuk : Thank you for the tip (`dotnet workload install ios`).  Spent many hours until I found your recommendation.

**Comment by AnithaRaniT** [comment]
@VladislavAntonyuk, @pmaytak I'm also facing the same issue as,

**Comment by pmaytak** [comment]
The original issue was that MSAL included Microsoft.iOS 16.4 which was a preview version at the time. As of now Microsoft.iOS 16.4 is public [stable](https://www.nuget.org/packages/Microsoft.iOS.Sdk/16.4.7099). So this seems like a different issue.

Some things to try:
- Include an explicit reference to the latest Microsoft.iOS.SDK package.
- Target net7.0-ios15.4.
- Make sure you have the latest .NET 7 SDK installed, then run `dotnet workload install ios`.
- Install the latest .NET  SDK and install workloads again.
