### ISSUE TITLE
Microsoft.Identity.Client.MsalClientException: The browser based authentication dialog failed to complete. Reason: The protocol is not known and no pluggable protocols have been entered that match.

### ISSUE THREAD

**Issue by aarondglover** [AzureAD/microsoft-authentication-library-for-dotnet#4094]
I am using MSAL with my winforms application and utilising it to authenticate to Azure B2C using signup-signin user flow.

I am unable to sign in most times today with the following exception after trying to sign in interactivly

`Microsoft.Identity.Client.MsalClientException: The browser based authentication dialog failed to complete. Reason: The protocol is not known and no pluggable protocols have been entered that match.`

Is this likely an issue with AZURE B2C? Can anyone help me troubleshoot this further?

Thanks in Advance
Aaron

**Comment by pmaytak** [comment]
What MSAL version do you use and on which platform (net fx, net6?)

This may be related to too many claims in the response and thus long authorize URL: https://stackoverflow.com/questions/62813104/authentication-with-msal-net-fails-for-some-users

Can you try reducing the number of claims to see if it works?
Another thing to try is WebView2 embedded browser, which is newer and based on Edge. If your app is NetFx you can call WithDesktopFeatures from Microsoft.Identity.Client.Desktop package.

**Comment by aarondglover** [comment]
Unfortunately the claims length was not the issue (and shouldn't have been given that nothing had changed for 12months+). Some change has rolled out through Azure B2C that no one quite knows about. The update is continuing the propagate through azure as we speak as this problem has become progressively worse.

The solution for me was the update my project to use the 
- MSAL Microsoft.Identity.Client v4.5.3 (previously 2.x)
- Microsoft.Identity.Client.Desktop v4.5.3
- Update program throughout to use new Builder for Client and update calls to acquire tokens. some example below for those you might find this useful. There were about a dozen other examples, but this demonstrates the basic updating which occurred from MSAL 3.x I think.
```
'Old Call
Public Shared ReadOnly Property PublicClientApp As PublicClientApplication = New PublicClientApplication(
    ClientId, 
    Authority, 
    TokenCacheHelper.GetUserCache())

'New Call using Builder
Public Shared ReadOnly Property PublicClientApp As PublicClientApplication = PublicClientApplicationBuilder.
        CreateWithApplicationOptions(
                New PublicClientApplicationOptions() With {
                        .ClientId = ClientId}).
        WithB2CAuthority(Authority).
        Build


'Old Call
Return Await PublicClientApp.AcquireTokenSilentAsync(ApiScopes, GetUserByPolicy(accounts, PolicySignUpSignIn), Authority, False)

'New Call
Return Await PublicClientApp.AcquireTokenSilent(ApiScopes, GetUserByPolicy(accounts, PolicySignUpSignIn)).ExecuteAsync()
```


```
'Old Call
 authResult = Await PublicClientApp.AcquireTokenAsync(
         ApiScopes, GetUserByPolicy(accounts, PolicySignUpSignIn), 
         UIBehavior.SelectAccount, 
         String.Empty, 
         Nothing, 
         Authority)

'New Call         
 authResult = Await PublicClientApp.AcquireTokenInteractive(ApiScopes).
         WithAccount(GetUserByPolicy(accounts, PolicySignUpSignIn)).
         WithPrompt(Prompt.SelectAccount).
         WithB2CAuthority(Authority).
         ExecuteAsync
```
