### ISSUE TITLE
Is there a way to call a custom Azure AD B2C policy with MSAL in .net MAUI?

### ISSUE THREAD

**Issue by joebeernink** [AzureAD/microsoft-authentication-library-for-dotnet#4097]
**Documentation related to component**
Microsoft.Identity.Client

**Please check those that apply**

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**
I'm trying to allow the user to delete their account on a mobile app built in .NET MAUI while using AD-B2C and MSAL.

I have the custom flow built and working when called from my ReactJS website (using msalClient.acquireTokenPopup) but I can't get the MAUI app to call the custom IEF policy.

I added the correct policy as follows:

        private void InitializePublicClientApplicationDeleteBuilder()
        {
            PublicClientApplicationDeleteBuilder = PublicClientApplicationBuilder.Create(AzureADB2CConfig.ClientId)
                .WithExperimentalFeatures() // this is for upcoming logger
                .WithB2CAuthority($"{AzureADB2CConfig.Instance}/tfp/{AzureADB2CConfig.Domain}/{AzureADB2CConfig.DeleteProfilePolicyId}")
                .WithRedirectUri(AzureADB2CConfig.MsalRedirectUri)
                .WithLogging(new IdentityLogger(EventLogLevel.Warning), enablePiiLogging: false);    // This is the currently recommended way to log MSAL message. For more info refer to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging. Set Identity Logging level to Warning which is a middle ground;
        }
And then tried to call it with

        public void DeleteUser(IAccount user, string[] scopes)
        {
            InitializePublicClientApplicationDeleteBuilder();

            // Initialize the MSAL library by building a public client application
            PublicClientApplicationDelete = PublicClientApplicationDeleteBuilder
                .Build();

            PublicClientApplicationDelete.AcquireTokenInteractive(scopes);
        }
But the delete policy is never rendered. This is in a non-embedded browser in MAUI because Google doesn't allow embedded browsers. Not sure if that makes a difference. There is no AcquireTokenPopUp in the .net package, so Interactive seemed to be the best route.

Is there a different way to do this? Can that be added to the documentation?

**Comment by bgavrilMS** [comment]
Let's treat this as a bug @joebeernink 

1. Do other flows like SignInSingUp work?
2. Can you provide the app coordinates (client id, name of the policies etc.) for us to try? Feel free to email them to me (bogavril at microsoft com) if you do not wish to make them public.

**Comment by Blamoh** [comment]
Hi, same issue for me. Any news on this topic ?

**Comment by bgavrilMS** [comment]
@Blamoh @joebeernink - can you try switching to embedded browser / system browser on mobile? Use `WithEmbeddedWebview(true / false)` and see if it helps?

**Comment by joebeernink** [comment]
Unfortunately, embedded browser isn't an option in production because Google does not allow apps using sign in as Google to use embedded browsers (I spent a few weeks trying to figure that one out). I'll try reverting back to that to test the theory, but it's a non-starter for production at this point.

**Comment by joebeernink** [comment]
Tried it as 
PublicClientApplicationDelete.AcquireTokenInteractive(new List<string>()).WithUseEmbeddedWebView(true);

Didn't seem to make a difference.

**Comment by bgavrilMS** [comment]
> Unfortunately, embedded browser isn't an option in production because Google does not allow apps using sign in as Google to use embedded browsers (I spent a few weeks trying to figure that one out). I'll try reverting back to that to test the theory, but it's a non-starter for production at this point.

That is a fair point. 
But just to let you know that I did manage to get the delete profile to work with embedded browser. I am not sure why the system browser isn't working, still looking into it. 

Not a great experience, but can you ask users to delete their profile only via website?

**Comment by bgavrilMS** [comment]
Hmm, the flow just started working for me now, even with system browser `.WithUseEmbeddedWebView(false)` - did you make any changes?

**Comment by bgavrilMS** [comment]
Closing as no-repro.

**Comment by joebeernink** [comment]
Sorry, got really busy last week (launched both the Apple and Android apps on the stores and a bunch of other stuff). I was never able to get this to work on Android, but still need to go through all the troubleshooting steps you listed. I'm just not sure which of those steps would help if sign ins are working fine, but the delete flow is not. If only google allowed the MAUI embedded browser.
