### ISSUE TITLE
Good way to test a silent token refresh failure in MSAL for Blazor?

### ISSUE THREAD

**Issue by andrewrondeau-optirtc** [AzureAD/microsoft-authentication-library-for-dotnet#4098]
I'm currently using MSAL (https://www.nuget.org/packages/Microsoft.Authentication.WebAssembly.Msal) in a blazor project. Due to how our project is implemented, silent token refresh is failing. (As described at https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript2, "More often, failures are due to the refresh token's 24-hour lifetime expiring and [the browser blocking third party cookies](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas), which prevents the use of hidden iframes to continue authenticating the user.")

In this case, I get an AccessTokenNotAvailableException when I make an HTTP request. Handling this exception is documented at https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0#attach-tokens-to-outgoing-requests.

**How do I simulate a silent token refresh failure so I can test a silent token refresh _interactively_?**

So far I've put in a debugging hook to throw an AccessTokenNotAvailableException from a subclass of AuthorizationMessageHandler. Is there a better way to do this? We need to keep this as part of our regression suite; and our product is not ready to invest in significant test automation.

For example, is there a value we can tweak in local storage or session storage that would trigger MSAL to perform a silent token refresh?

**Comment by gladjohn** [comment]
@jmprieur can you please assist with this ask?

**Comment by jmprieur** [comment]
Blazorwasm uses MSAL.js
@peterzenz @sameerag @EmLauber can help here.

**Comment by gladjohn** [comment]
Thanks @jmprieur. 

@andrewrondeau-optirtc can you please file an issue at the [MSAL JS issue page](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues)

**Comment by andrewrondeau-optirtc** [comment]
Thanks, submitted at https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5913
