### ISSUE TITLE
Problems with non-default authorities.

### ISSUE THREAD

**Issue by 23W** [AzureAD/microsoft-authentication-library-for-dotnet#410]
Default authority in MSAL is defined as "https://login.microsoftonline.com/common/".
But according description of `PublicClientApplication` class you can change it to [others Azure AD v2.0  endpoints](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints):

**common**  - it's default  authority. "https://login.microsoftonline.com/common/"
> Allows users with both personal Microsoft accounts and work/school accounts from Azure Active Directory to sign into the application.

**consumers** - it's authority for personal accounts only. "https://login.microsoftonline.com/consumers/"
> Allows only users with personal Microsoft accounts (MSA) to sign into the application.

**organizations** - it's authority for works accounts.  "https://login.microsoftonline.com/organizations/"
> Allows only users with work/school accounts from Azure Active Directory to sign into the application

I've tried used **consumers** with purpose to allow only personal accounts to be logged in app.

    App = new PublicClientApplication(AppKey, authority: "https://login.microsoftonline.com/consumers/", userTokenCache: tokenCache);

But for some reason, MSAL asked me for **work or school** account?
![consumers](https://cloud.githubusercontent.com/assets/11534020/25805528/b599a4b4-3408-11e7-8bfb-797831662f06.png)

When I've inputted my personal account mail, I received error:
![consumers_pa](https://cloud.githubusercontent.com/assets/11534020/25805678/3728eac6-3409-11e7-8750-1463f00bc64f.png)

I tried work account and authorization finished with error:  
![consumers_wa](https://cloud.githubusercontent.com/assets/11534020/25805765/86f4fb44-3409-11e7-84c2-b7d262f07b7c.PNG)

The same behavior when I tried to use "https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/" endpoint. Where **9188040d-6c67-4c5b-b112-36a304b66dad** is [tenant GUID for  consumers](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-tokens#claims-in-id-tokens) with a Microsoft accounts (personal accounts). 

I moved my code to **organizations** endpoint:

    App = new PublicClientApplication(AppKey, authority: "https://login.microsoftonline.com/organizations/", userTokenCache: tokenCache);

I've expected that MSAL allows only work/school account with this endpoint. But, it allowed to input **personal** account too:
![organizations](https://cloud.githubusercontent.com/assets/11534020/25805913/20e54bf0-340a-11e7-9aa0-4226378108c3.png)

I've inputted some user's personal credentials and received error (this user hasn't any work accounts in any tenants):
![organizations_pa](https://cloud.githubusercontent.com/assets/11534020/25806239/3eba606a-340b-11e7-990f-3fc5ea521ebc.PNG)

Work account has been authenticated correctly.

Would anybody explain such behavior? Looks like only default **common** endpoint works properly. But it doesn't allow to limit logon by account type: personal or work only. 

Platform: .Net 45, desktop.
MSAL version: last.
P.S: This issue is connected with #399.

**Comment by kpanwar** [comment]
This is a known issue in the service. they are working to fix it.

**Comment by RedBlue1776** [comment]
Does this also prevent the client from using Azure Germany, or Azure Gov?  

I believe customizing this is a requirement for those environments.  Is this a library issue or something else?

**Comment by jmprieur** [comment]
this does not prevent sovereign clouds, which are known authorities: See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/62c5cdecd1d7fe21acf67d7419aefb9437ddfe27/src/Microsoft.Identity.Client/Internal/Instance/AadAuthority.cs#L41-L46
