### ISSUE TITLE
[Bug] Azure AD B2C authentication fails on UWP

### ISSUE THREAD

**Issue by kyurkchyan** [AzureAD/microsoft-authentication-library-for-dotnet#4102]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
4.53.0

**Platform**
UWP with Xamarin.Forms

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [x] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**
1. Clone the [sample project](https://github.com/kyurkchyan/uwp-b2c-login-issue)
2. Run and try to sign in

**Expected behavior**
A successful login

**Actual behavior**
First of all, we receive "We can't connect to the service you need right now. Check your network connection or try this again later" error in the opened browser window. When open the Windows event log I see the following error

```
AuthHost encountered a navigation error at URL: <https://msoisalesstaging.b2clogin.com/tfp/msoisalesstaging.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?scope=offline_access+openid+https%3A%2F%2Fmsoisalesstaging.onmicrosoft.com%2Fmsoisales%2Fmongodb-realm-sync+profile&response_type=code&client_id=a0789689-6dd6-4f8f-bacd-bef3bfbfcf4d&redirect_uri=ms-app%3A%2F%2Fs-1-15-2-1207448870-1919239748-1716570430-323877461-3067963371-1728433620-2282859050%2F&client-request-id=9de92785-4b16-4594-987b-caef9cb887aa&x-client-SKU=MSAL.UAP&x-client-Ver=4.49.1.0&x-client-CPU=x64&x-client-OS=Windows+10&x-client-DM=Blade+15+Advanced+Model+%28Early+2021%29+-+RZ09-036&prompt=select_account&code_challenge=3oVCkz54nCG7AOVClZOuAfrvNc-eegWjdgJlBSry9QY&code_challenge_method=S256&state=ca6fe89f-9c45-4879-828e-667e0700c9d67e5da2b1-f2d3-44e1-81f6-9f50c3337d11&client_info=1> with StatusCode: 0x800C000D.
```

**Additional context / logs / screenshots / links to code**

[azure_ad_b2c_uwp_logs.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/11285910/azure_ad_b2c_uwp_logs.zip)

I have search for all of the possible suggested solutions about this issue such as

1. [Adding enterprise network capabilities](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/28#issuecomment-462495404)
2. [Making sure the redirect URL is explicitly mentioned](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/28#issuecomment-338233458)
3. [Making sure that we use recommended user flow](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2188#issuecomment-743493637)

None of the above helped to solve the problem. The problem started happening in our production app without any changes, and currently, none of our users can log in, causing essentially global p1 for us. Also, the sample I shared is the official B2C sample for Xamarin.Forms and when I put our clientID and sign in process properties into the sample I see the same error.  Probably something has changed that we are not aware.

**Comment by bgavrilMS** [comment]
Ack. Sadly UWP's component that does auth (AuthHost or WAB) is very strict and any HTML / CSS / HTTP issue in the page (e.g. an image served over HTTP instead of HTTPS) causes it to drop the connection. 

The service folks do not test everything with UWP because UWP is pretty much dead.

Trying to repro so that I can contact the service folks. 

Long term, can you move to WinUI / Maui / WPF?

**Comment by kyurkchyan** [comment]
@bgavrilMS We are having P1 with all of our customers :( And we need to resolve this issue ASAP. 

Maui migration is on our Roadmap, but obviously, we need to resolve this issue to unblock our customers. 

Thanks for taking a look into it!

**Comment by bgavrilMS** [comment]
Yeah, I can repro with your app and with our test B2C coordinates, which we use in the samples ...

**Comment by kyurkchyan** [comment]
@bgavrilMS good to hear that you've been able to reproduce the issue. I really hope the resolution is something simple :)

**Comment by bgavrilMS** [comment]
Hmm, if I try with the FabrikamB2C tenant (the ones our samples point at) but with redirect URI set to `msal{ClientID}://auth` this seems to work. Did you try that?

**Comment by arvizio** [comment]
Kinda the same issue here, MSAL stopped working in our production UWP app since yesterday evening. Back then the issue was intermittent, now it's persistent.  AcquireTokenInteractive()  shows the sign-in page, but after hitting Sign In, the UI is removed and blank window with "Connecting to a service" caption stays indefinetly. The AcquireTokenInteractive() never returns.  Silence in the log.

**Comment by kyurkchyan** [comment]
@arvizio  I have a strong guess that the intermittency was because of the most recent change that potentially was released last week and was being gradually rolled out throughout the last 7 days. We observed a gradual increase in the relative frequency of this issue over the past week. And now, this new change is rollout out 100%, and that's the reason it's now 100% reproducible.

**Comment by bgavrilMS** [comment]
@kyurkchyan - what is (roughly) the timestamp for which you encountered the error?

`AuthHost encountered a navigation error at URL: <https://msoisalesstaging.b2clogin.com/tfp/msoisalesstaging.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?scope=offline_access+openid+https%3A%2F%2Fmsoisalesstaging.onmicrosoft.com%2Fmsoisales%2Fmongodb-realm-sync+profile&response_type=code&client_id=a0789689-6dd6-4f8f-bacd-bef3bfbfcf4d&redirect_uri=ms-app%3A%2F%2Fs-1-15-2-1207448870-1919239748-1716570430-323877461-3067963371-1728433620`

**Comment by bgavrilMS** [comment]
I have raised an issue on the internal incident tracker (id 383545237)

Please do reach out to Azure Support yourselfes (via the Azure Portal or directly if you have an account person). In my experience, customers reaching out directly are able to explain better the impact. 

@kyurkchyan - these errors are difficult to detect on service side. Hope we're lucky with this one, but with a similar issue with Perosnal accounts on AAD, it took more than 2 weeks :(

**Comment by kyurkchyan** [comment]
@bgavrilMS  regarding the exact timestamp, it's hard to tell. I've tried and retried the authentication over and over again today. So, there have been multiple attempts. And I am unsure which exact attempt corresponds to the one you mentioned. 

We've already sent a support request to Azure Support as well. The problem is that we buy azure from a service provider, which adds yet another layer of indirect communication and thus, delays. 

Thanks again for the effort, @bgavrilMS. I really appreciate your support. And thanks for being honest that this potentially can take days to resolve. Thus we will need to find something more immediate as a workaround (such as switching to another authentication provider).

**Comment by bgavrilMS** [comment]
@kyurkchyan - can you try with redirect uri $"msal{ClientID}://auth" ? I tried it on your app and it seems to work
@arvizio - what redirect URI do you use? Smth like `ms-appx-web://microsoft.aad.brokerplugin/{sid}` ? Can you switch to $"msal{ClientID}://auth" ?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/12273384/233440577-ff6bde0a-c5c7-433c-aba7-c29b13d2bbe4.png">


CC @localden and @jmprieur for awareness

**Comment by kyurkchyan** [comment]
@bgavrilMS msal{ClientID}://auth does work, it worked before. The thing is when we enter valid credentials and then sign in we see a screen like this

![image](https://user-images.githubusercontent.com/3243139/233442292-acfbb412-6cfe-46f3-b795-8a8f9bc235a9.png)


If you want to try (considering this is a test app I am ok sharing these credentials here) just try the following username and password

username: gagik@xamlab.com
password: Test123456

**Comment by arvizio** [comment]
@bgavrilMS  Switching to $"msal{ClientID}://auth" removes the hang, but now we have "Can't connect to the service you need right now.." AFTER submitting the correct credentials. To carify further: initial UI with username and password does show up. It also properly react on incorrect credentials.

**Comment by AndreasBreuninger** [comment]
Here the exact same behavior. Our Xamarin apps for UWP no longer work. There are no problems with Android. 
We use the interactive flow with user/password.
We have set up a completely new B2C environment for testing purposes. The policies from the startup pack were applied. 
https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/main/LocalAccounts

The Debuglog says somethin linke that:
`True MSAL 4.53.0.0 MSAL.UAP .NET Core 4.6.31331.01 Windows 10 [2023-04-21 07:58:54Z - a93b5f65-XXXX-XXXX-a00b-06d235de9cb7] System.IO.FileNotFoundException: **The specified protocol is unknown**. (Exception from HRESULT: 0x800C000D)`

There seems to be something broken with the returned redirect URI. In the audit log we see, that tokens are generated and the user is authenticted. When debuggung the authentication with fiddler as desxcribed here: https://learn.microsoft.com/en-us/windows/uwp/security/web-authentication-broker
there is a response with an 302 statuscode that says 

```
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="msalade589b9-9d9d-XXXX-XXXX-203c05c4652e://auth/?state=dc3a6a95-2f8b-XXXX-XXXX-f3f72036778093ac42cc-af55-4d1e-87a4-b6b1ac47fe0a&client_info=ey...n0&code=ey...AQ">here</a>.</h2>
</body></html>
```
The same URI is also within the Locaion header. 

Unfortunately, I can't tell if this is the normal behavior, since the login no longer works via any policy and I can't capture the request.

**Comment by charlesroddie** [comment]
We are experiencing this issue, very critical and have contacted Azure support.

> Long term, can you move to WinUI / Maui / WPF?

These platforms are not ready yet for us. None of these have AOT compilation so would be a downgrade in user experience and security, and MAUI is not production quality yet.

**Comment by bgavrilMS** [comment]
@AndreasBreuninger @charlesroddie @arvizio  - thank you for posting here. Can you please also tell me your tenant names ? Here or via email (bogavril at microsoft com) if you don't want this to be made public.

I will raise the awareness around this incident as it clearly affects many customers. I'm also trying to see the impact based on telemetry, as the service should see a drop in token requests from your tenants and in general from UWP apps. 

Current hypothesis is that this has to do with URL lengths. The UWP browser has a limitation on that and it looks like some of the authorization flow redirects break this.

**Comment by AndreasBreuninger** [comment]
Tenantname is egonschachtelmeierb2c
I've also thought about the 256 character limit for the redirect Uri..

**Comment by bachoang** [comment]
@bgavrilMS this is most likely due to this recent change in B2C:
https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad/azure-ad-b2c-authorization-code-and-refresh-token-size-increase/m-p/3770890

**Comment by AndreasBreuninger** [comment]
> This change should not affect device-installed apps, such as mobile and desktop apps. 

Can't find a solution for uwp Apps there. Just a comment that MS might do a rollback. Can someone confirm this?

**Comment by AndreasBreuninger** [comment]
> @bgavrilMS this is most likely due to this recent change in B2C: https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad/azure-ad-b2c-authorization-code-and-refresh-token-size-increase/m-p/3770890



> This change should not affect device-installed apps, such as mobile and desktop apps. 

Can't find a solution for uwp Apps there. Just a comment that MS might do a rollback. Can someone confirm this?

**Comment by bgavrilMS** [comment]
Update on this: currently, the rollback is happening on a tenant by tenant basis. 

@charlesroddie - your tenant is being reverted now, it'll take time to propagate to all regions.

**Comment by swright-kepro** [comment]
> Update on this: currently, the rollback is happening on a tenant by tenant basis.
> 
> @charlesroddie - your tenant is being reverted now, it'll take time to propagate to all regions.

Will all tenants be rolled back eventually?

**Comment by bgavrilMS** [comment]
> > Update on this: currently, the rollback is happening on a tenant by tenant basis.
> > @charlesroddie - your tenant is being reverted now, it'll take time to propagate to all regions.
> 
> Will all tenants be rolled back eventually?

I will have an update on this shortly.

**Comment by PatGet** [comment]
Would be great to know if this will be rolled back for all tenants as @AndreasBreuninger only gave you a test tenant. We also openend an azure Support ticket yesterday, I'm going to link this issue and your internal tracking number there.

**Comment by bgavrilMS** [comment]
Folks, there will be some official communication about this incident and the mitigation coming out soon, addressed directly to the affected subscription admins. There should not be anything that needs doing from anyone on this thread or anyone using UWP + B2C.

**Comment by kyurkchyan** [comment]
The issue has been resolved for me. I hope the next release of Azure AD will be a more successful one :) Thanks, @bgavrilMS for following up on the issue!
