### ISSUE TITLE
Cors error only using cypress after upgrading msal to 7.0.5

### ISSUE THREAD

**Issue by saad1200** [AzureAD/microsoft-authentication-library-for-dotnet#4104]
After upgrading from Webassembly.MSAl from version 6.0.1 to 7.0.5. Running cypress on the single sign on Blazor app start throwing CORS error. Downgrading that package gets the app to work again. this behaviour only happen when running Cypress 11 and 12. The app works just fine Out of Cypress.
Auth2 is setup with Azure AD.

**Comment by pmaytak** [comment]
I assume it's Microsoft.Authentication.WebAssembly.Msal? It uses MSAL JavaScript. Please [create an issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) in MSAL.JS repo.
