### ISSUE TITLE
Require Tag and internal error code for WAM errors when thrown as an Msal exception

### ISSUE THREAD

**Issue by crmann1** [AzureAD/microsoft-authentication-library-for-dotnet#4106]
Right now in 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4e8df7a04cdec8a21a5a8dc57439f23561ec23e1/src/client/Microsoft.Identity.Client/Platforms/uap/WamBroker/WamAdapters.cs

When an unknown broker error is encountered the error code is just "unknownbroker error".  Can you attach the internal error code and the tag to the msal exception, this information is critical to diagnose wam related errors.   The information is in the message, but we need it on the object in order to use it in remote telemetry.

For example the string says

	"Unknown Status: Unexpected Error: 0xffffffff80070520 Context: Unexpected exception while waiting for accounts control to finish: '(pii)' Tag: 0x1f7d734b (error code -2147023584) (internal error code 528315211)"

We need the error code, internal error code and tag.

**Comment by bgavrilMS** [comment]
@crmann1 - the code that you point to is older WAM implementation, which we now only use for UWP. This is the code that [transforms the WAM error into an MSAL exception ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/Platforms/Features/RuntimeBroker/WamAdapters.cs#L64)

Looks like the flow goes into the default case of the switch. We can improve the actual message I think.

Is the ask to have a new exception type, where Tag and Internal Error Code are available programmatically (the Error Code can be made available even now).
