### ISSUE TITLE
Latest MSAL version is not compatible with current maui SDK 

### ISSUE THREAD

**Issue by SophisticatedConsulting** [AzureAD/microsoft-authentication-library-for-dotnet#4120]
When using the current version of MSAL I get the following error when building:

CSC : error CS1705: Assembly 'Microsoft.Identity.Client' with identity 'Microsoft.Identity.Client, Version=4.53.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' uses 'Microsoft.iOS, Version=**16.4.0.0**, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=**16.2.0.0**, Culture=neutral, PublicKeyToken=84e04ff9cfb79065

This is true for both the current VS production version 17.5.5 and the pre-release version 17.6.0 preview 6

**Comment by pmaytak** [comment]
This is tracked in #4091. Fix is merged and will come in the next release; aiming for the end of the week.
