### ISSUE TITLE
[Bug] MSAL triggering SSO 3 times in rapid sequence in a Blazor WASM application

### ISSUE THREAD

**Issue by andrea-migliaccio** [AzureAD/microsoft-authentication-library-for-dotnet#4123]
Hi,

it's being a while that two different (while technically similar) application triggers the authentication redirect or popup three times in rapid sequence when the refresh token is expired. This is happening in our deployed application while not in the local development environment. The development environment and deployment environment share the same AAD App Registration Client-ID.

From the browser network we can see this sequence:

1. GET /token --> 400 bad request for refresh token expiration
2. First auth popup open
3. we receive the /login-callback
4. the first back end API call is executed successfully...
5. PROBLEM: while executing further API calls we can see further GET /token and other two authentication popup are opened and quickly closed

We can't see any meaning log from MSAL in the browser console.

What can we do to provide usefull traces to better address this weird behaviour?

Thanks!
Andrea

**Comment by pmaytak** [comment]
Blazor WASM uses MSAL JavaScript. Please [create an issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) in MSAL.JS repo.
