### ISSUE TITLE
[Feature Request] Update ID.Web.TokenCache to provide telemetry data during authentication.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#4137]
**Is your feature request related to a problem? Please describe.**
ID.Web needs to provide telemetry data outlined in `TelemetryData.cs`.

**Describe the solution you'd like**
today, the only data available in `TelemetryData.cs` is the cache level which represents whether or not the cache used is L1 or L2. `TelemetryData` is exposed in the TokenCacheNotificationArgs` provided during cache operations. ID.Web needs to provide this telemetry data if available.

**Additional context**
Telemetry PR with the TelemetryData data type: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3737

**Comment by jmprieur** [comment]
@trwalke should this be transferred in the Id.Web repo?

**Comment by jennyf19** [comment]
+1 to @jmprieur 's question. Also, can we see an example of the data from kusto? Is this part of the current telemetry being sent with msalCur/msalLast or something else? If part of current telemetry, do you have a link to the update in the ADO repo of the telemetry schema?

**Comment by bgavrilMS** [comment]
Agreed this should be moved to Id.Web repo for tracking. We can use a simple card (non-issue) to track progress on the MSAL.NET board. 

@jennyf19 - this is the client telemetry, not HTTP telemetry, although it would be interesting to see this in HTTP telemetry as well, but not sure how to log it. 

Epic is tracked with - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3784 and spec for client telemetry is [here](https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/authorize?client_id=00000003-0000-0ff1-ce00-000000000000&response_mode=form_post&response_type=code+id_token&resource=00000003-0000-0ff1-ce00-000000000000&scope=openid&nonce=0e09b4a0300400000246519b61130374-F41D6C1087D1CEEAAA5551A69FA9D30CE0E577EA7270E230F07EB86CBA149DDF&redirect_uri=https%3a%2f%2fmicrosoft-my.sharepoint-df.com%2f_forms%2fdefault.aspx&state=OD0w&login_hint=BOGAVRIL%40MICROSOFT.COM&claims=%7b%22id_token%22%3a%7b%22xms_cc%22%3a%7b%22values%22%3a%5b%22CP1%22%5d%7d%7d%7d&wsucxt=1&cobrandid=11bd8083-87e0-41b5-bb78-0bc43c8a8e8a&client-request-id=0e09b4a0-3004-0000-0246-519b61130374&sso_nonce=AwABAAEAAAACAOz_BQD0_8lhpAbIXj55DuaCs3cdpZ9bkYTCv_5K1HSKUSMd4Dwc0u4sAZH_krcyvbEtWgUzzwZvoZNI2-DI5JdpM0xs73YgAA&mscrid=0e09b4a0-3004-0000-0246-519b61130374)

**Comment by pmaytak** [comment]
There were issues already created:
https://github.com/AzureAD/microsoft-identity-web/issues/1900
https://github.com/AzureAD/microsoft-identity-web/issues/1901

**Comment by trwalke** [comment]
https://github.com/AzureAD/microsoft-identity-web/pull/2256
