### ISSUE TITLE
Blank screen on interactive aquire token in Outlook add-in.

### ISSUE THREAD

**Issue by LaughingJohn** [AzureAD/microsoft-authentication-library-for-dotnet#4139]
Hi,

This is a bit of a long shot given the complexity of my situation and the other software involved, but I wonder if anyone might be able to suggest some further debugging steps or suggestions.

Circumstances:
.Net Framework 4.7.2 (winforms)
MSAL.Net version 4.54.0.0
Outlook Add-in using Add-in express (Add-in Express for Office and .NET release 10.1.4703).

I have added a button on the Outlook toolbar which opens a windows form which allows the user to select a system. Once the user presses OK it calls MSAL.Net interactively to prompt for credentials. 

This works fine, some of the time. However I also have an add-in express form panel which displays on certain emails only. When I click on an email that displays the panel AND click away, the next time I try to change system/user MSAL hangs with a blank grey screen and never comes back. I also can't close the window using the close button, but I can close it via the task bar. After this has happened once it continues to happen. Only restarting Outlook 'resets' it. Just FYI the way it works is there is a single instance of the panel which I show/hide depending on the email that is selected.

![2023-05-18_09-44-16](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/305820/b6b79593-26ab-4162-bf2d-6617e069def7)

Strangely if I cut some of the code out of the panel it starts to work consistently, but that code is only creating the UI and I can't narrow it to a particular line, it seems to be more about the amount of code, as if there's some sort of weird timing issue, even though the form has long finished running code before I click on the ribbon button to change connection. At one point having commented out code and gradually re-introducing it I could consistently make it work/not work by adding/removing a line that just set a tooltip. Which is madness of course, but I then started adding other code back and it started happening again. I just don't see how it's a timing issue given the code has finished running. Very weird and hard to track down.

Authentication Code:

```
        private async Task<string> AquireTokenWithPromptInternal()
        {
            var publicClientApplication = await GetPublicClientApplication();
            var scopes = new List<string> { ResourceId };
            
            var authResult = await publicClientApplication.AcquireTokenInteractive(scopes).ExecuteAsync();
            return authResult.AccessToken;
        }
        private async Task<IPublicClientApplication> GetPublicClientApplication()
        {
            if (_publicClientApplication != null)
            {
                return _publicClientApplication;
            }

            _publicClientApplication = PublicClientApplicationBuilder.Create(ClientId)
                .WithLogging(new MyLogger())
                .WithRedirectUri(RedirectUrl)
                .WithAuthority(new Uri(AuthorityCommon))
                .Build();

            var storageProperties = new StorageCreationPropertiesBuilder(_tokenLocation.FileName, _tokenLocation.Path).Build();
            
            var cacheHelper = await MsalCacheHelper.CreateAsync(storageProperties);
            cacheHelper.RegisterCache(_publicClientApplication.UserTokenCache);

            return _publicClientApplication;
        }

```

I've got an MSAL trace out for both the working version and the failing one (I've changed my company name in the text). The failing version has less text in it as if something isn't being called. Failing version first:

**FAILING VERSION**

False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] MSAL MSAL.Desktop with assembly version '4.54.0.0'. CorrelationId(08036b41-027e-4396-9cd1-f2bd1edbecad)
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent: 
Prompt: not_specified
HasCustomWebUi: False

False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] 
=== Request Data ===
Authority Provided? - True
Scopes - https://www.MyCompany.net/webservices/user_impersonation
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 08036b41-027e-4396-9cd1-f2bd1edbecad
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] === Token Acquisition (InteractiveRequest) started:
	 Scopes: https://www.MyCompany.net/webservices/user_impersonation
	Authority Host: login.microsoftonline.com
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] [Instance Discovery] Instance discovery is enabled and will be performed
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] [Region discovery] Not using a regional authority. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] [Instance Discovery] The network provider found an entry for login.microsoftonline.com. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] Using legacy embedded browser.
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:40:08Z - 08036b41-027e-4396-9cd1-f2bd1edbecad] 

**WORKING VERSION**

False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] MSAL MSAL.Desktop with assembly version '4.54.0.0'. CorrelationId(36494100-ca6d-4ed5-aee6-0fc4f60e46e6)
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent: 
Prompt: not_specified
HasCustomWebUi: False

False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] 
=== Request Data ===
Authority Provided? - True
Scopes - https://www.MyCompany.net/webservices/user_impersonation
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] === Token Acquisition (InteractiveRequest) started:
	 Scopes: https://www.MyCompany.net/webservices/user_impersonation
	Authority Host: login.microsoftonline.com
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] [Instance Discovery] Instance discovery is enabled and will be performed
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] [Region discovery] Not using a regional authority. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Fetching instance discovery from the network from host login.microsoftonline.com. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Starting [Oauth2Client] Sending GET request 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Starting [HttpManager] ExecuteAsync
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] [HttpManager] Sending request. Method: GET. Host: https://login.microsoftonline.com. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] [HttpManager] Received response. Status code: OK. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Finished [HttpManager] ExecuteAsync in 104 ms
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Finished [Oauth2Client] Sending GET request  in 110 ms
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Starting [OAuth2Client] Deserializing response
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Finished [OAuth2Client] Deserializing response in 36 ms
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] [Instance Discovery] After hitting the discovery endpoint, the network provider found an entry for login.microsoftonline.com ? True. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Authority validation enabled? True. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Authority validation - is known env? True. 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] Using legacy embedded browser.
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:01Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] 
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:02Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] 
'OUTLOOK.EXE' (CLR v4.0.30319: C:\Source\MyCompany.Outlook.AddinAI\MyCompany.Outlook.AddinAI\bin\Debug\): Loaded 'C:\WINDOWS\assembly\GAC\Microsoft.mshtml\7.0.3300.0__b03f5f7f11d50a3a\Microsoft.mshtml.dll'. Module was built without symbols.
False MSAL 4.54.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-05-18 08:39:02Z - 36494100-ca6d-4ed5-aee6-0fc4f60e46e6] 
The thread 0x68a0 has exited with code 0 (0x0).
The thread 0x5c24 has exited with code 0 (0x0).

**Comment by bgavrilMS** [comment]
The logs don't really say much. Outlook may be doing some strange things with UI threads etc. which trips up the embedded browser, but I don't see much to go on and this issue hasn't been reported by other apps. 

Taking a step back, do Outlook addins really need to prompt the user for auth? They already logged in to Outlook, why do they need to login into your plugin ? Typically apps that offer extensibility provide a way to get the user identity and auth. I am not familiar with Outlook programming model, but they seem to offer a **silent** way to get tokens - https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/authentication#single-sign-on-access-token

If all this fails, I suggest moving away from that embedded browser and using WAM - https:\\aka.ms\msal-net-wam

**Comment by LaughingJohn** [comment]
Hi @bgavrilMS,

Thanks for the quick reply. Unfortunately this is a legacy COM add-in - it runs in process with Outlook. The link you sent was for "modern" outlook add-ins which use javascript and are hosted in the web so not applicable unfortunately. Additionally we support additional identity providers other than AD.

I suspect you are right that it is some sort of UI thread issue, although try as I might I can't figure it out. There's probably too many moving parts for you to be able to help, but I thought it was worth a try. Just driving me mad :)

Feel free to close this issue. 

Kind Regards,
LJ

**Comment by bgavrilMS** [comment]
See if WAM does trick. Or switch to using the system browser (via `WithEmbeddedWebview(false)`) - the system browser is a different process, so no more UI threads :)
