### ISSUE TITLE
[Feature Request] MSAL Logging Improvements V2

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4149]
Need to analyze logs on commonly used flows and see if we are able to get needed info in case of failures. 

**Ways to achieve :** 
repro common scenarios or run tests and analyze logs

**Additional context**
We have had few cases where we end up asking for Fiddler traces. Can we log safely in MSAL what we send to AAD and what we get back? so we do not have to depend on traces? just our own logs 

**Work needed to achieve this?** 
We need a spec for this work to sort out PII, ROPC flow, authorization code flow etc.

**Comment by trwalke** [comment]
I think we already log a part of the request and potentially the header values sent. We can definitely add more data here. However, Not sure there is a way to get the traffic from the browser which can sometimes be really useful.

**Comment by bgavrilMS** [comment]
We can't log HTTP requests and repsonses because they contain tokens.
