### ISSUE TITLE
Blank Login Screen when try to authenticate with Microsoft login using MSAL in >1K resolution

### ISSUE THREAD

**Issue by AnzarN** [AzureAD/microsoft-authentication-library-for-dotnet#4152]
We have WinUI3 app, in which we are using MSAL to authenticate Azure AD app, which works as expected in HD display resolution but the machines which are **Full HD** or **4K,** shows **blank Mircosoft Authentication** screen. In blank screen the cursor pointer is being changed ( ex. Arrow to Hand if there is any clickable area ) and upon clicking, it shows the password box as well but text is not visible. 
I have attached screenshots for your reference.

If login for first time then it displays blank Mircosoft login screen so user can not enter credentials. 

This problem replicates specifically on screens with resolution more than **1K**

I have tried with Sample App : https://github.com/Azure-Samples/ms-identity-netcore-winui also and facing same issue in sample app also.

![LoginDefect](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/assets/118263613/667e04d3-60f9-4a65-97ea-e7cbe2ab1919)

I have two different Tenants, In one Tenant my AzureAD App is registered, and in second Tenant I have given Admin consent for the same app. Microsoft Login Page works fine in a Tenant where AzureAD App is originally registered, but not working in second Tenant despite of giving all required access and permissions.

## Expected Behavior: 
Authentication screen should show normally irrespective of resolution.

## Current Behavior:
It shows blank on screen with resolution more than 1K.

**Comment by bgavrilMS** [comment]
We'll work on updating that sample as well.
