### ISSUE TITLE
[Feature Request] MI Add support for Object / Principal ID in UAMI

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4156]
**Is your feature request related to a problem? Please describe.**
[Azure Redis](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/pull/7/files) team seems to be using `PrincipalID`. Need to add support in MSAL 

**Describe the solution you'd like**
Add support for ObjectID in UAMI 

**Describe alternatives you've considered**
none

**Additional context**
Please also evaluate if we need to add object id 

**Work Involved:**

- [ ] Code update 
- [ ] Unit test updates
- [ ] Integration test updates 
- [ ] Sample updates
- [ ] Doc updates

**Comment by bgavrilMS** [comment]
Seems like it should be easy to add, let's prioritize it for the next release?

**Comment by bgavrilMS** [comment]
Why do they need principal ID instead of client id?

**Comment by gladjohn** [comment]
> Why do they need principal ID instead of client id?

looks like they don't. But both app service and IMDS sources support `object_id` and `principal_id` in the token request. Do we want to add support?

**Comment by rkammara12** [comment]
object_id is one of the supported parameters for calling IMDS Token endpoint, there are around 95k token requests with object_id parameter in production right now. So please add object_id as one of the acceptable parameters.

**Comment by gautamdsheth** [comment]
`object_id` would also be really great to have in MSAL.

The thing is, Azure Automation requires it as well.

The `principal_id` is an alias of `object_id`, but does not work on Azure Automation at the time of writing, while `object_id` works on both.

**Comment by bgavrilMS** [comment]
We should be able to take this in our next release. Is it a lot of work?

**Comment by gladjohn** [comment]
fix should be fairly simple, just need to find out if there is extra work for the integration tests with the helper service. I can take a fix for this in our next release

**Comment by gladjohn** [comment]
Released in MSAL 4.55.0
