### ISSUE TITLE
[Feature Request] Expose WAM telemetry data

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4159]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, we [log](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/Platforms/Features/RuntimeBroker/WamAdapters.cs#LL67C13-L67C92) MSAL Runtime telemetry. Ask from MSALRuntime team is, to expose it as a property 

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by trwalke** [comment]
What will we do with the property?
Will something consume the data? Telemetry pipeline?
