### ISSUE TITLE
[Bug] PublicClientApplicationBuilder truncates the authority URL provided through the .WithAuthority()

### ISSUE THREAD

**Issue by LymarV** [AzureAD/microsoft-authentication-library-for-dotnet#4163]
While I am trying to specify a third-party Authority (PingIdentity in my case) the authority URI gets truncated after the identity client build.

In the case of PingIdentiry, the authority URI has the following format:
https://auth.pingone.eu/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/as

Where `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` - is my "Environment ID".

The resulting identity client does not contain the last `/as` part of the URI path.

Going by the link (on an auth attempt) an error web page opens with the next content:
`{"message":"Missing Authentication Token"}`

Specifying the `.WithInstanceDiscoveryMetadata("https://auth.pingone.eu/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/as/.well-known/openid-configuration")` parameter didn't help.

I also have tried using another OIDC library [IdentityModel.OidcClient](https://github.com/IdentityModel/IdentityModel.OidcClient) with those credentials/authority, and it works properly (it doesn't truncate the authority URI and allows you to authenticate).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.54.1

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
This is a new app or experiment.

**Repro**

```csharp

var identityClient = PublicClientApplicationBuilder.Create(applicationId)
	.WithAuthority("https://auth.pingone.eu/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/as", false)
	.WithIosKeychainSecurityGroup("com.microsoft.adalcache")
	.WithRedirectUri($"msal{applicationId}://auth")
        .Build();

```

**Expected behavior**
The resulting authority URI of the identity client equals the provided value

**Actual behavior**
The resulting authority's URI path contains only the first segment.
On an authorization attempt, an error page opens with the `{"message":"Missing Authentication Token"}` content.

**Additional context / logs / screenshots / links to code**

<img width="1114" alt="Screenshot 2023-06-01 at 14 15 54" src="https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/6746572/7ab5a8dd-bf34-43fc-a641-5748e6f6f3b0">

**Comment by pmaytak** [comment]
`WithAuthority` is for AAD, ADFS, and AAD B2C identity providers only. We added `[WithGenericAuthority](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplicationbuilder.withgenericauthority?view=msal-dotnet-latest)` API but currently it's only for confidential client credentials flow.

#1538 is the overall tracking issue to bring non-Microsoft IdP support for other flows.
