### ISSUE TITLE
[Feature Request] WWWAuthenticate Resource property obsolete with warning instead of error

### ISSUE THREAD

**Issue by jovinson-ms** [AzureAD/microsoft-authentication-library-for-dotnet#4166]
**Is your feature request related to a problem? Please describe.**
In #3160 the `Resource` property in `WWWAuthenticateParameters` was marked as obsolete. There was a question on the PR as to whether the `ObsoleteAttribute.IsError` property should be set to `true`, and the decision was made to do it, with the rationale that callers should know the resource they are requesting.

The issue is that there are scenarios, such as [this security advisory from Azure Key Vault](https://devblogs.microsoft.com/azure-sdk/guidance-for-applications-using-the-key-vault-libraries/#additional-recommended-actions), where clients are supposed to inspect the `resource` parameter in the response to ensure it matches the set of well known domains.

Because the `ObsoleteAttribute` now throws a compiler error, it doesn't allow consumers to decide on how they want to address this issue - it can't be suppressed as a warning could be.

**Describe the solution you'd like**
I'd like the `IsError` property to be set to the default of `false`.

**Describe alternatives you've considered**
I've tried various ways of suppressing the error - other than conditional compilation I don't know of a way, and that certainly seems like overkill.

**Additional context**

**Comment by pmaytak** [comment]
@jovinson-ms I understood the article as:
- You need to validate the user-provided URIs (Key Vault in that case) **before** you make a request to the resource.
- If the resource host is valid, you can make a request, and get WwwAuthParams and you already know the resource, so you don't need to use AuthParams.Resouce.

Am I misunderstanding the scenario?

**Comment by bgavrilMS** [comment]
Clients that perform resource validation (e.g. by comparing the host part of the resource against a list of known good hosts), 
can still use the indexer to retrieve the raw value of the resource / scope. 
If a resource is used, add "/.default" to it to transform it into a scope, e.g. "https://graph.microsoft.com/.default" is the OAuth2 scope for "https://graph.microsoft.com" resource.

I added a PR that updates the API docs.

**Comment by bgavrilMS** [comment]
We could expose an API like `string[] GetScopes(string[] allowedResourceHosts)` where the app developer gives us a list of allowed resources (just the hostname of the full URI should suffice). 

E.g. `wwwAuthParams.GetScopes("https://graph.microsoft.com", "https://graph.microsoftonline.com")` -> `https://graph.microsoft.com\.default`

**Comment by jovinson-ms** [comment]
> @jovinson-ms I understood the article as:
> 
> * You need to validate the user-provided URIs (Key Vault in that case) **before** you make a request to the resource.
> * If the resource host is valid, you can make a request, and get WwwAuthParams and you already know the resource, so you don't need to use AuthParams.Resouce.
> 
> Am I misunderstanding the scenario?

@pmaytak the article does say to validate the URI as a first step, but also to perform a challenge and then validate the resource against the desired host: "Azure Key Vault libraries have been updated to make sure the resource in the challenge matches the given host domain". Here's the [Key Vault SDK implementation](https://github.com/Azure/azure-sdk-for-net/blob/fbe8b5cfd152353d544b9d3f710bbfe15ba2946e/sdk/keyvault/Azure.Security.KeyVault.Shared/src/ChallengeBasedAuthenticationPolicy.cs#L95).

**Comment by jmprieur** [comment]
@bgavrilMS would this `GetScopes()` method provide scopes for the intersection of the allowedResourceHosts and the resources in the WWW-Authenticate header?
