### ISSUE TITLE
[Feature Request] Remove unnecessary x-client info 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4167]
Currently MSAL sends the following: 

| Name             | Example Value              | Notes                                                              |
|------------------|----------------------------|--------------------------------------------------------------------|
| x-client-sku     | msal-netcore               | Identifies MSAL library (e.g. MSAL.NET on NET fwk, MSAL ObjC etc.) |
| x-client-version | 4.45.0                     |                                                                    |
| x-client-CPU     | x64                        |  |
| x-client-OS      | Win Server 2016 Datacenter | RuntimeInformation.OSDescription                                   |
| x-client-DM      | Apple Iphone 14            | Only on mobile and UWP                                             |

Understand if the service uses all this information. We should cut as much as possible irrelevant information. Even if it is low-impact from a privacy perspective, it is not 0-impact.

Proposal: cut the following

- x-client-CPU

**Comment by rayluo** [comment]
> Currently MSAL sends the following:
> 
> Name	Example Value	Notes
> ...
> 
> Proposal: cut the following
> 
> * x-client-CPU

This proposal is also applicable to other MSALs, isn't it?
