### ISSUE TITLE
[Bug] Power BI users Unable to login to my account in the Power BI Desktop

### ISSUE THREAD

**Issue by Sharlkaur** [AzureAD/microsoft-authentication-library-for-dotnet#4174]
Description - users can't get to login my power bi account in the desktop app.
The error says as follows
"power bi desktop unable to sign in
WAM Error
Error Code: 2156265475
Error Message: ApiContractViolation
WAM Error Message: (pii)
Internal Error Code: 557973634
Is Retryable: false Possible causes:
- Invalid redirect uri - ensure you have configured the following url in the AAD portal App Registration: ms-appx-
web://microsoft.aad.brokenplugin/7f6af8a-fedc-4b08-8b4e-37c4d127b6cf
- No Internet connection:
Please see https://aka.ms/msal-net-wam for details about Windows Broker Integration"

User tried the following:
* deleting the cache and temp files
* disabling antivirus and firewall
*using another internet connection
*Adding a registry value to enable Windows Broker.

 Workaround: 
1) On the login pop-up, chose the "Use a different account/Work or school account" option
2) Uncheck the "allow my org to manage my device" option in the authentication pop-up dialog and click on "sign in to this app only".

_Make sure that your question or issue is not already covered in [MSAL docs](https://learn.microsoft.com/en-us/entra/msal/dotnet/) or [samples](https://learn.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code?tabs=apptype)._

**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**

**Platform**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive (broker)
    * [ ] Interactive (embedded or system browser)
    * [ ] Integrated Windows Authentication
    * [ ] Username / Password
    * [ ] Device code (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Client credentials (service-to-service calls)

Other?

**Is this a new or existing app?**

**Repro**

```csharp
var your = (code) => here;
```

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes.  

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by MSamWils** [comment]
The error is ONL_E_INVALID_APPLICATION and it means that your application didn't register from the MSA server side.
What authority did you pass to MSAL? 
Is your application work for both personal and work/school account?

**Comment by msft-robertxu** [comment]
Hello, just to provide more info:
1) The authority used is `https://login.microsoftonline.com/common`
2) This is unknown, is there any limitations depending on the account?

**Comment by MSamWils** [comment]
Hi @msft-robertxu , that `<URI>/common` authority means you allow users to use their personal or work/school account to sign in your application. 
You need to check with your team from the design level on whether or not MSA can be used to sign-in in your app.
If yes, I will work with you on how to enable your application from retrieving MSA token.
If not, please use `<URI>/organizations` authority.

**Comment by msft-robertxu** [comment]
Hi @MSamWils - thanks for the info. We've never previously restricted users from using their personal or work/school accounts. Before we turned on WAM, users were able to select the 'Use a different account' option and sign in successfully.

Let me know how we can retrieve the MSA token correctly.

**Comment by msft-robertxu** [comment]
Hello, we do allow users to use work/school accounts, but not personal accounts.

Please let me know how we can get the MSA token correctly. We have also tried a private build pointing to the `/organizations` endpoint but it didn't work for everyone.

**Comment by bgavrilMS** [comment]
@msft-robertxu - did you fix this ? If not, can you enable verbose loggin + PII to get more details about the exception?

**Comment by msft-robertxu** [comment]
Hi @bgavrilMS - Yes, we can close this. I've confirmed that we only use work/school accounts, and pointing our authority url to `/organization` fixes this specific issue.
