### ISSUE TITLE
[Bug] Unexpected exception while waiting for accounts control to finish

### ISSUE THREAD

**Issue by msft-robertxu** [AzureAD/microsoft-authentication-library-for-dotnet#4179]
**Logs and network traces**

These were extracted from our own PowerBI Desktop logs - but hopefully they can still be used.
https://microsoft-my.sharepoint.com/:u:/p/robertxu/EYFLD0qC0fNBokXAu1lMbM8BrDujgyjXSXmifUwxjZvOiA?e=7u9LCe

**Which version of MSAL.NET are you using?**

MSAL.NET 4.51.0

**Platform**

.NET 6.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive (broker)
    * [ ] Interactive (embedded or system browser)
    * [ ] Integrated Windows Authentication
    * [ ] Username / Password
    * [ ] Device code (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Client credentials (service-to-service calls)

**Is this a new or existing app?**
**a. The app is in production, and I have upgraded to a new version of MSAL.**

**Additional context / logs / screenshots / links to code**
This is from an ICM. We have been unable to reproduce this locally with our own MSFT accounts, but according to the user:
**Customer use their DV account (etc. Domain\Test-DV) which is different from windows sign in account (Domain\Test)**
So it seems like an issue where their sign-in account does not match their Windows account.
Unsure if this is expected behavior or not?
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/136652061/a8fe7277-42cb-4320-aebb-7ee095e00180)

**Comment by gladjohn** [comment]
@MSamWils please find the logs. You can also ping Robert XU in teams directly

**Comment by MSamWils** [comment]
Sync'd with @msft-robertxu and @gladjohn offline, let's make sure is the application support native MSA or MSA passthrough scenario before we dive into this issue.

**Comment by localden** [comment]
@msft-robertxu - are you still experiencing the issue?

**Comment by msft-robertxu** [comment]
We have not gotten any user complaints for this issue anymore - so I will go ahead and close this.
