### ISSUE TITLE
is it possible to use the msalcache.bin3 cache file on different PCs, but using the same hard drive?

### ISSUE THREAD

**Issue by austincrft** [AzureAD/microsoft-authentication-library-for-dotnet#4180]
I noticed that copying the `msalcache.bin3` file to another PC does not work, which makes sense from a security perspective. I'd like to understand _how_ it is being limited to a single PC, like if it's based on MAC address or something specific to a drive.

For more background, at my company we have a desktop app that we offer "as a service" using Azure Virtual Desktop (AVD). The problem here is that when you open up an app in AVD you are not guaranteed to end up on the same VM, so our users are required to login more frequently than we would like. I wrote some code to store/retrieve the MSAL cache file using blob storage, but that is not working since the MSAL cache file does not work across PCs.

In AVD we have the option of using FSLogix to virtualize the hard drive in the AVD environment and share that across the various VMs. If the MSAL cache file is restricted only by hard drive, this would work for us, but if it's using something like a MAC address then it will not work.

Can you provide any info here?

**Comment by pmaytak** [comment]
We use [DPAPI](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Cross-platform-Token-Cache#windows) for encryption on Windows with the scope of [CurrentUser](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.dataprotectionscope?view=windowsdesktop-7.0). There's a less secure option to use [unencrypted file](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/main/src/Shared/StorageCreationPropertiesBuilder.cs#L205). You can also subscribe [your own caching implementation](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom#simple-token-cache-serialization-msal-only). Another option is to use [Windows broker](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom#simple-token-cache-serialization-msal-only) and pass [PublicClientApplication.OperatingSystemAccount](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.publicclientapplication.operatingsystemaccount?view=msal-dotnet-latest) which should silently login with the account that's already logged into the OS.

**Comment by pmaytak** [comment]
Hmm, so the public client apps are basically intended for single users (like a mobile device or a desktop app). If you share that cache file, it'll aggregate tokens for all users. (Plus there'll be issues with having multiple versions of the file and such.) Windows broker would probably be a better options here - the user would log into the VM, then log into the app silently with the OS account. You can also [add your own cache implementation](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom) to make MSAL read/write from a distributed cache, for example.

@jmprieur @localden Do you have any other ideas on this scenario?

**Comment by localden** [comment]
Yeah, sharing a cache for a public client app sounds a bit worrisome to me, not the least because that seems like a recipe for enabling an individual to log in as someone else by virtue of having access to the same shared cache. Would that not be a problem, @pmaytak?

**Comment by bgavrilMS** [comment]
DPAPI blob is not roamable.
