### ISSUE TITLE
[Engineering Task] Publish MSAL pdbs to internal symweb

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4189]
Requirement from VS

**Comment by pmaytak** [comment]
We should already have this implemented.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2497

**Comment by bgavrilMS** [comment]
Sorry, we cannot do this without detailed instructions with how to achieve it from vanilla ADO tasks. Not devdiv internal build. In the past we have tried to this several times and we never managed to do it due to limitations in the archive symbols tasks.  This is a devdiv requirement only.

**Comment by gladjohn** [comment]
@trwalke tested this with OneBranch and the next MSAL release will start pushing these
