### ISSUE TITLE
[Bug] Updating from 4.10 to 4.54 results in AADSTS50052: The password entered exceeds the maximum length.

### ISSUE THREAD

**Issue by AdamBlade** [AzureAD/microsoft-authentication-library-for-dotnet#4195]
**Which version of MSAL.NET are you using?**
Msal.Net 4.10 -> Msal.Net 4.54

**Platform**
Net 4.7.1, Net 6

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive (broker)
    * [ ] Interactive (embedded or system browser)
    * [ ] Integrated Windows Authentication
    * [ ] Username / Password
    * [ ] Device code (browserless)
* Web app 
    * [ ] Authorization code
    * [x] On-Behalf-Of
* Daemon app 
    * [ ] Client credentials (service-to-service calls)

Other?

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL.
This is a new app trying to migrate old application from Net 4.x to Net 6.

Hello,

I'm not sure if this the right place or format but I'm a bit stuck with an issue upgrading from an older version to the latest.

The error in question:
MsalServiceException: AADSTS50052: The password entered exceeds the maximum length. Please reach out to your admin to reset the password.

I'm using **Microsoft.AnalysisServices.AdomdClient.retail.amd64** which has a dependency on **Microsoft.Identity.Client**. 
The application calls power BI with a connection string that has Password={accessToken} which is my AAD access token.
On version 4.10, the connection works fine but If I upgrade the package to the latest version I now get the error that the password is too long. From what I've gathered the issue starts occurring after version 4.43. 

The same behaviour is also in net core equivalent package **Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64** which as far as I can tell should be pretty much exactly the same. This particular package must have Microsoft.Identity.Client (=> 4.43.0)

```csharp
        string ConnectionString = $"Provider=MSOLAP;Data Source={server};User ID=;Password={accessToken};Catalog={databaseName};Persist Security Info=True; Impersonation Level=Impersonate";

        using (AdomdConnection adomdConnection = new AdomdConnection())
        {
            adomdConnection.ConnectionString = ConnectionString;
            AdomdCommand adomdCommand = new AdomdCommand();
            adomdCommand.Connection = adomdConnection;                
            adomdCommand.CommandText = "SAMPLE QUERY";
            adomdConnection.Open(); // Fails AADSTS50052
            CellSet cellSet = adomdCommand.ExecuteCellSet();
            adomdConnection.Close();
        }
```
Am I missing something obvious here? 
Has anyone encountered something similar, any hint would help a lot.
For reference the access token is **2184 characters long**.
Thank you in advance.

**Actual behavior**
New versions throws error that Password is too long when passing an access token in the connection string.

**Expected behavior**
On older version passing password as access token resulted in a connection.

**Comment by bgavrilMS** [comment]
It looks like you are using the Username/Password flow instead of OBO and you set the password to be the incoming access token. The token is very long, and the error is ok.  

I would raise an issue to the SDK / application consuming MSAL. I don't see how MSAL could perform OBO flow in one version one ROPC flow in another version.
