### ISSUE TITLE
[Engineering Task] Use CloudMine to track GH items

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4203]
**What is CluodMine?** : https://eng.ms/docs/products/1es-cloudmine/ 
**Get Access:** https://eng.ms/docs/products/1es-cloudmine/access

**Comment by gladjohn** [comment]
we may not do this, as Sowmya seems to be working on this already

**Comment by gladjohn** [comment]
@bgavrilMS should we close this given that data team is already working on this?

**Comment by bgavrilMS** [comment]
@gladjohn - afair Sowmya is working on tracking PR speed. We should work on tracking GH issue health, as per KR1 in your list.

**Comment by gladjohn** [comment]
See [[Feature Request] Explore Microsoft github policy service#4239](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4239)
