### ISSUE TITLE
[Feature Request] Improve error message when the distributed token cache is encrypted with Data Protection and decryption fails

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4206]
See troubleshooting case for repro - https://github.com/AzureAD/microsoft-identity-web/wiki/Token-Cache-Troubleshooting#im-using-encryption-and-im-getting-deserialization-errors

We should catch / rethrow this exception with a better error message in the Id.Web.TokenCache project.

**Comment by jmprieur** [comment]
It's not token encryption, @bgavrilMS, it's encryption of the distributed cache.
