### ISSUE TITLE
[Engineering Task] Enable codeql in github using gh actions

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4211]
more info here : https://github.com/github/codeql-action/

**Comment by gladjohn** [comment]
As per the discussion I had with @bgavrilMS, we already enabled CodeQL in OneBranch and that will be the One compliant path moving forward

**Comment by trwalke** [comment]
ID web has this enabled
https://github.com/AzureAD/microsoft-identity-web/actions/runs/5193903612/jobs/9365004862?pr=2256
