### ISSUE TITLE
Does MASL work with .Net Core 2.0 Preview 1 without Azure AD/B2C?

### ISSUE THREAD

**Issue by Ponant** [AzureAD/microsoft-authentication-library-for-dotnet#422]
Hello,
I am testing out ASP.NET Identity in .Net Core 2.0 Preview 1 and it is stated here https://blogs.msdn.microsoft.com/webdev/2017/05/10/aspnet-2-preview-1/ that "Build secure web APIs using ASP.NET Core Identity. Acquire access tokens for accessing your web APIs using the Microsoft Authentication Library (MSAL)" , which makes me think that we should be able to create a local DB for identity and access the API or MVC with a client app using MASL without using Azure AD or Azure AD B2C. Is that correct, and if so do you have a working sample? thanks

**Comment by jmprieur** [comment]
Closing this issue as .NET Core 2.0 has GAed, and the B2C samples use MSAL.
