### ISSUE TITLE
[Engineering Task] OneBranch Release Pipeline Updates

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4221]
OneBranch release pipeline needs to, 
- [x] Build MSAL sln 
- [ ] Run all tests 
- [x] Run all compliance tasks (no exceptions / exclusions)
- [x] Publish Artifacts
- [x] With a switch Push to NuGet / IDDP 
- [x] Publish PDBs / Symbols (It's own pipeline)
- [x] Create a pipeline build with no artifacts

**Comment by trwalke** [comment]
Would be good to investigate the new OneBranch pipeline before turning back on the old one. I am looking into getting more details for it
