### ISSUE TITLE
[Engineering Task] CodeQL may not be running correctly in OneBranch builds

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4227]
Need to check if CodeQL is able to run on OneBranch 

https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1132633&view=logs&j=15dfcb1a-0989-5cf6-3160-3e181e44de87&t=4125dd50-01d1-5f57-f742-89ba994c2ecd

**Comment by trwalke** [comment]
might have something to do with the fact that the source files are in a sub directory named after the SDK
Also, maybe we need a config file?
https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/one-branch-codeql
