### ISSUE TITLE
Get “client info is null” with MSAL 1.1.0-preview

### ISSUE THREAD

**Issue by Rick-Kirkham** [AzureAD/microsoft-authentication-library-for-dotnet#424]
I have some code that was working on MSAL 1.1.0-alpha307, but on 1.1.0-preview it throws exception "client info is null", which is returned in the HTTP response. The app is registered in the AAD V2 endpoint and it gets MS Graph data. From the stack trace, it looks like its able to get the token for Graph but not able to cache it. 

The code and the stack trace are at: http://stackoverflow.com/questions/44032487/get-client-info-is-null-with-msal-1-1-0-preview

**Comment by kpanwar** [comment]
It could be that the alpha build was not asserting on missing client_info. We are looking at service side issue

**Comment by kpanwar** [comment]
This was fixed.
