### ISSUE TITLE
[Engineering Task] Use the Policheck tool to add complex exceptions

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#4263]
To add complex exceptions to policheck see https://eng.ms/docs/microsoft-security/security/azure-security/cloudai-security-fundamentals-engineering/security-integration/guardian-wiki/sdl-azdo-extension/policheck-build-task

This creates a policheck-rules-db.mdb file that can be added to the code.

We already have a "Policheck Exclusions" text file which can be used to exclude complete files from policheck scanning.

**Comment by gladjohn** [comment]
https://identitydivision.visualstudio.com/IDDP/_git/MSAL.NET-OneBranch/pullrequest/9512?_a=files

**Comment by neha-bhargava** [comment]
> @neha-bhargava for policheck exclusions we have added the following for OneBranch,
> 
> ![image](https://user-images.githubusercontent.com/90415114/261137063-0ffcb265-4040-43a9-af35-eed44819f473.png)
> 
> word wise exclusion is a little more complex, like creating a .mdb file and maintaining the list. Hopefully this works where we can exclude files. If not we can revisit this again. OneBranch PR [here](https://identitydivision.visualstudio.com/IDDP/_git/MSAL.NET-OneBranch/pullrequest/9512?_a=files), if you agree then I will close this task.

Agree that word wise exclusion is complex. This should be fine until we do not have a lot of files getting excluded.
