### ISSUE TITLE
[Bug] CacheSynchronizationEnabled flag default is inconsistent

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4268]
MSAL 4.54.1

## Expected 

CacheSynchronizationEnabled should be `true` by default. It should have negligible impact over when CCA is constructed on a request by request basis. But when CCA is singleton, cache correctness cannot be achieved without this flag set to true (i.e. without locking).

(It should also be hidden / soft deprecated API, as it is too low level)

## Actual

If using `ApplicationOptions` when constructing the CCA object, the `CacheSynchronizationEnabled`  is set to `false` if not explicitly declared.
If not using `ApplicationsOptions`, the `CacheSynchronizationEnabled` is set to `true`

**Comment by bgavrilMS** [comment]
CC @jennyf19 and @jmprieur as this affects Id.Web since afaik it constructs the CCA from options all the time.

**Comment by pmaytak** [comment]
> But when CCA is singleton, cache correctness cannot be achieved without this flag set to true (i.e. without locking).

Nit clarification here - CCA is singleton **and token cache serialization is enabled**. 

So the effects of changing default from false to true:
| # | Scenario                           | Effect                                       |
|---|------------------------------------|----------------------------------------------|
| 1 | CCA is per request                 | Negligible                                   |
| 2 | Singleton CCA, no serialized cache | Not recommended, should not be used in prod. |
| 3 | Singleton CCA w/ serialized cache  | Fixes cache inconsistency                    |

For 2, we don't have telemetry if CCA is singleton...

**Comment by pmaytak** [comment]
So the flag is consistent - it's false by default.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/80c848b5b7bfc033b11ee82107344bfc22efc0da/tests/Microsoft.Identity.Test.Unit/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs#L103-L109

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/80c848b5b7bfc033b11ee82107344bfc22efc0da/tests/Microsoft.Identity.Test.Unit/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs#L130-L131

Although it is set to true in app config; it's actually overridden in the CcaBuilder.Create:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/80c848b5b7bfc033b11ee82107344bfc22efc0da/src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs#L116

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/80c848b5b7bfc033b11ee82107344bfc22efc0da/src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs#L86
