### ISSUE TITLE
[Engineering Task] MSAL net only release fix Duplicate 'PackageReference' 

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4269]
Installed MSBuild.Sdk.Extras 3.0.44 from https://api.nuget.org/v3/index.json with content hash aFiJ4XQtdk5LsXLqzjGpboaA3u+hhAFyAhgeUkbDOsfYcv8+AZiYSzbAkxfse6VlANuuDKAcj8DKYgUOmEMecQ==.
Project "D:\a\1\s\src\client\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" on node 1 (Restore target(s)).
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
##[warning]src\client\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj(0,0): Warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.CSharp 4.5.0, Microsoft.CSharp 4.5.0; System.Runtime.Serialization.Primitives 4.3.0, System.Runtime.Serialization.Primitives 4.3.0; System.Runtime.Serialization.Formatters 4.3.0, System.Runtime.Serialization.Formatters 4.3.0; System.Security.SecureString 4.3.0, System.Security.SecureString 4.3.0, System.Security.SecureString 4.3.0, System.Security.SecureString 4.3.0; Xamarin.AndroidX.Browser 1.0.0, Xamarin.AndroidX.Browser 1.4.0.
Project "D:\a\1\s\src\client\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (1) is building "D:\a\1\s\src\client\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (1:3) on node 1 (_GenerateRestoreProjectPathWalk target(s)).
D:\a\1\s\src\client\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.CSharp 4.5.0, Microsoft.CSharp 4.5.0; System.Runtime.Serialization.Primitives 4.3.0, System.Runtime.Serialization.Primitives 4.3.0; System.Runtime.Serialization.Formatters 4.3.0, System.Runtime.Serialization.Formatters 4.3.0; System.Security.SecureString 4.3.0, System.Security.SecureString 4.3.0, System.Security.SecureString 4.3.0, System.Security.SecureString 4.3.0; Xamarin.AndroidX.Browser 1.0.0, Xamarin.AndroidX.Browser 1.4.0.
Done Building Project "D:\a\1\s\src\client\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (_GenerateRestoreProjectPathWalk target(s)).
Restore:
  Restoring packages for D:\a\1\s\src\client\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj...

**Comment by bgavrilMS** [comment]
I am not able to repro this, need better repro steps. Nobody else complained.
