### ISSUE TITLE
ConfidentialClientApplication only supports xxx.onmicrosoft.com and not yyy.xxx.zzz in B2C

### ISSUE THREAD

**Issue by NikolaosWakem** [AzureAD/microsoft-authentication-library-for-dotnet#427]
ConfidentialClientApplication and AcquireTokenSilentAsync only supports xxx.onmicrosoft.com for Authority and not custom domains defined in B2C

**Comment by kpanwar** [comment]
This is by design. You should pass b2c authority as documented and openid configuration will return vanity domains as expected and confidential client will use it .

**Comment by NikolaosWakem** [comment]
@parakhj by design apparently

Sadly this design not documented anywhere that I could find!

**Comment by parakhj** [comment]
yyy.xxx.zzz should work, as long as the openid configuration allows it. @kpanwar is right in that you should use what the openid configuration returns. This isn't an MSAL issue, so no fix necessary by MSAL

**Comment by NikolaosWakem** [comment]
So the authority MUST NOT be in non vanity name, however the scopes MUST be in 'vanity' name.. 

Seems obvious now - should have check the design i guess!
