### ISSUE TITLE
[Bug] .WithTenantId started to throw ArgumentException

### ISSUE THREAD

**Issue by rabenshm** [AzureAD/microsoft-authentication-library-for-dotnet#4280]
### Library version used

4.55.0

### .NET version

4.8

### MSAL client type

Confidential

### Application type

Web API

### Authentication flow type

Client credentials (service-to-service calls)

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

Well calling on the ConfidentialClientApplication builder .WithTenantId with invalid tenant, a new argument exception regarding authorityurl is being throw, although we do not explictly set authorityurl by ourselves, and this is not declared as a thrown exception.

Until now we handled MsalException for those scenario. As discussed offline with Bogdan suggest to change to MsalClientException not to break flows.

For now we have rolled back to previous MSAL version.

### Expected behavior

MsalClientException should be thrown , better on the Execute and not in the builder (even if MSAL itself will not go our for STS)

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.50

**Comment by bgavrilMS** [comment]
Today we throw an ArgumentException if authority URl is malformed (e.g. has spaces in it). We should throw an MsalClientException

**Comment by pmaytak** [comment]
Between 4.50 and 4.55, the exceptions in calling only `WithTenant` at app level didn't change. Exceptions for calling `WithTenant` and `WithAuthority` changed from `MsalClient` to `Argument` - which is what I assume this issue is about. We simply didn't allow calling both, `WithTenant` and `WithAuthority`, which I think was incorrect. I think now it's correct - `WithTenant` just modifies user-provided or default authority. There are more details in the PR: #4347.

**Comment by pmaytak** [comment]
@rabenshm Can you clarify which method you called and what the exception you were expecting, I wasn;t able to find the exact scenario.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/34331512/d711b2de-0c9d-4347-9e4f-e4e9df231f67)

**Comment by rabenshm** [comment]
We were calling .WithTenantId , but we were only getting exception when calling the AcquireToken and not in the Builder level.

After your change we are getting the exception on the builder level.


________________________________
