### ISSUE TITLE
ADAL Should Use [assembly: CLSCompliant(true)]

### ISSUE THREAD

**Issue by davihar** [AzureAD/microsoft-authentication-library-for-dotnet#429]
At a point in the past ADAL used [assembly: CLSCompliant(true)] but https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/commit/1f1d9aef83bb0698d130fac4b56257b5c9e77057 changed it to [assembly: CLSCompliant(false)] which is a breaking change for consuming developers.  Any developer which attempts an upgrade and their consuming code uses CLSCompliant(true)] will experience a build break.

Ideally this change should be reverted.  It would be better for consuming developers if you use [assembly: CLSCompliant(true)] and then annotate the specific parts of ADAL with [CLSCompliant(false)] that require it so that it is less likely consuming developers will run into this upgrade issue.

If a specific target requires CLSCompliant(false) for the whole assembly then that target should be compiled that way but the other targets should be compiled with CLSCompliant(true).

**Comment by kpanwar** [comment]
This is incorrect repo. File the issue in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
