### ISSUE TITLE
[Engineering Task] Some tests are not running in the build pipeline

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4292]
### Type of task?

Builds

### Description

Check the [latest CI builds](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1149548&view=ms.vss-test-web.build-test-results-tab), under the test results tab search for `ServicePrincipal_OBO_PPE_Async`. 

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/90415114/b50234b1-bbe2-48de-856e-27ed2f9aaf94)

there are about 150 tests that are not running. Some are marked to be Ignored, but majority of the ones that are not running fall under `RunOn` attribute

**Comment by trwalke** [comment]
Might be due to a missing YAML task or a build issue. Will need to scan through logs.  

Also, there was some refactoring for OBO SP tests done here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/febbdd3c2746814ba301e65e16c572720b338893

I dont even see "ServicePrincipal_OBO_PPE_Async" in the repo anymore so maybe some of these tests were refactored?

**Comment by trwalke** [comment]
Marking as p2 because if there are missing tests that can be a serious issue for code/scenario coverage. Maybe it can be a p3 though.

Thoughts @bgavrilMS

**Comment by bgavrilMS** [comment]
<img width="242" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/12273384/895c4616-784b-4bf1-a905-ebf10c7d69c3">

I also put a PR out to add back all Ignored integration tests. 

RunAs significantly optimizes test runtime. If you feel some tests need to run on more platforms, please propose PR.

[ignored] unit tests should be driven down.

**Comment by bgavrilMS** [comment]
Are you saying that we deleted the OBO SP test that you fixed @gladjohn ?

**Comment by gladjohn** [comment]
I am not able to find the `ServicePrincipal_OBO_PPE_Async` test in the repo anymore., think we can close this
