### ISSUE TITLE
error in dotnet core application

### ISSUE THREAD

**Issue by chenxizhang** [AzureAD/microsoft-authentication-library-for-dotnet#431]
![image](https://cloud.githubusercontent.com/assets/1996954/26659499/9e0edd20-46a3-11e7-8213-aaec13ff3565.png)

![image](https://cloud.githubusercontent.com/assets/1996954/26659508/b2f53220-46a3-11e7-9340-4b29a6a0e4ac.png)

**Comment by SomkaPe** [comment]
Please provide MSAL log

**Comment by kpanwar** [comment]
This is by design. Netcore API are uncapable of showing a UI in a platform agnostic way. We will remove the interactive API for netcore

**Comment by Thraka** [comment]
Is there a text UI replacement? If every .NET core supports `Console.WriteLine` and `Console.ReadLine` why can't we use that?

**Comment by jmprieur** [comment]
@Thraka : the HTML presented in the platforms providing a browser is sent by Azure AD. to display a UI, the platforms need to provide a browser, and .NET core does not yet.

**Comment by Thraka** [comment]
ahhh gotcha. Thanks!

**Comment by lanatmwan** [comment]
can we expect that the interactive api will be added back in .net core 3 since it sounds like it is going to have a browser? https://blogs.msdn.microsoft.com/dotnet/2018/10/04/update-on-net-core-3-0-and-net-framework-4-8/

**Comment by Thraka** [comment]
@lanatmwan I dont think there is a browser for .net core 3, not sure where you read on that on the linked page.

**Comment by lanatmwan** [comment]
@Thraka Sorry, guess I read that too quickly and had a bout of wishful thinking. I didn't notice that the new browser control was for .Net Framework. 

Similar to your previous comment about using console, I would like to see an official powershell core cmdlet that can perform the authentication but it sounds like "device flow" is the closest I am going to get.

**Comment by Thraka** [comment]
@jmprieur The azure cli works around this browser limitation. You really should too 😄
