### ISSUE TITLE
[Engineering Task] Remove support for netcoreapp 2.1

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#4313]
### Type of task?

Other(s)

### Description

Remove support for netcoreapp 2.1

**Comment by bgavrilMS** [comment]
Approved as a minor version bump.

**Comment by bgavrilMS** [comment]
As part of this, please make sure that our tests run on .NET 6 (not on lower .NET, otherwise they'll hit MSAL netstandard).
