### ISSUE TITLE
[Bug] WebAssembly MSAL Blazor Query Parameter Persistance 

### ISSUE THREAD

**Issue by Jeremy-Code-F** [AzureAD/microsoft-authentication-library-for-dotnet#4317]
### Library version used

7.0.2

### .NET version

net7.0

### MSAL client type

Managed identity

### Application type

Web app

### Authentication flow type

Managed Identity

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

Hi,

I'm am working with Blazor's query parameter system for a new feature.
Everything is working fine with that, but I am not sure how to deal with MSAL redirect's losing the query information

e.g. if I save a bookmark to a url of my app

https://localhost:7227/stuff?SomeStuff=0357e575-ff9a-4a82-828f-814e313f0e4c

and open that in a new tab without authenticating at the root of the app first, the query parameters get chopped off (my guess is left out of the redirect information when auth completes). So after auth is finished the user gets redirected to
https://localhost:7227/stuff

I can't seem to find any information on this behavior, is there a suggested way of dealing with this? 

Thanks!

### Relevant code snippets

```csharp
builder.Services.AddMsalAuthentication(options =>
{
    builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
    options.ProviderOptions.DefaultAccessTokenScopes.Add("api://my-app/API.Access");
    options.ProviderOptions.DefaultAccessTokenScopes.Add("User.Read");
    options.ProviderOptions.LoginMode = "Redirect";
    options.UserOptions.RoleClaim = "roles";
}).AddAccountClaimsPrincipalFactory<RemoteAuthenticationState, RemoteUserAccount, CustomAccountClaimsPrincipalFactory>();
```

### Expected behavior

I expect the redirect back to my application to keep all query parameters

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by trwalke** [comment]
@Jeremy-Code-F I am assuming you are using Identity.Web for this?

@jennyf19 @jmprieur have you seen this before?

**Comment by Jeremy-Code-F** [comment]
> @Jeremy-Code-F I am assuming you are using Identity.Web for this?
> 
> @jennyf19 @jmprieur have you seen this before?

These are all the Microsoft* packages I have installed

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/45114285/9811993f-9837-4393-aa57-5dedbf517933)


There are 73 'Implicitly' installed ones as well I can provide that list if it's useful

**Comment by pmaytak** [comment]
Microsoft.Authentication.WebAssembly.Msal uses MSAL JavaScript. Create an issue in [MSAL JS repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) or maybe [aspnetcore/Blazor repo](https://github.com/dotnet/aspnetcore/issues).
