### ISSUE TITLE
Getting "MsalException: ADFS is not a supported authority in sample application"

### ISSUE THREAD

**Issue by SuperJMN** [AzureAD/microsoft-authentication-library-for-dotnet#432]
Using the WPF sample: https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2

And this data:
![image](https://cloud.githubusercontent.com/assets/3109851/26669923/f109701a-46af-11e7-9f7b-878b9d3371cc.png)

What am I doing wrong? :(

**Comment by kpanwar** [comment]
You are attempting to use adfs as an authority. Library does not support adfs yet.

**Comment by punitganshani** [comment]
Any idea when ADFS will be supported in MSAL?

**Comment by jmprieur** [comment]
We are working on plans now, @punitganshani

**Comment by andresk09** [comment]
is ADFS already supported? @jmprieur

**Comment by jmprieur** [comment]
Not yet, @andresk09, but we are working on Windows Integrated Authentication at the moment
I'm assuming you are ok to use the login.onmicrosoftonline.com authority and let Azure AD redirect to ADFS? you are not looking for a direct route to ADFS?
