### ISSUE TITLE
[Engineering Task] NuGet package name and info are hardcoded in the sign binary yml

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4324]
### Type of task?

Builds

### Description

[Sign Binary Yaml ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/d25f45f7e356bd92986e412dd68b5d341343aa6a/build/template-sign-binary.yaml#L28)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/90415114/a7274d4e-ff04-4657-a662-ff79e15820dd)

**Comment by trwalke** [comment]
We can do a separate signing task for each binary and feed it a different config for each.

**Comment by gladjohn** [comment]
> We can do a separate signing task for each binary and feed it a different config for each.

Or we could just use the [assembly name](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/build/template-pack-and-sign-all-nugets.yaml#L31) that we are already passing

**Comment by bgavrilMS** [comment]
I don't see the user impact for this. It's just a description.
