### ISSUE TITLE
[Bug] WebView1 fallback leads to Unsupported Browser for "More Information Required" Dialog in AAD

### ISSUE THREAD

**Issue by akainz** [AzureAD/microsoft-authentication-library-for-dotnet#4326]
### Library version used

4.55.0

### .NET version

.Net 7

### MSAL client type

Public

### Application type

Desktop

### Authentication flow type

Interactive (with embedded or system browser)

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

It seems like MSAL is falling back to WebView1 when authenticating with AAD "Using WebView1 embedded browser because the authority is Aad. WebView2 does not provide SSO." 

However the account doesn't have 2-fa or an alternative email so there is an "More Information Required" dialog. AAD wants to ask for a secondary email.

However clicking on next they will get a message "Unsupported Browser" "Your browser is not supported or up-to-date. Try updating it, or else download and install the latest version of [Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge)."

Falling back to WebView1 seems to make it effectively unusable for AAD accounts with additional information required  as far as I can tell.

This is on 

Log Below

```
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:12Z - ] [Instance Discovery] Instance discovery is enabled and will be performed
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:12Z - ] [Region discovery] Not using a regional authority. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:12Z - ] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:12Z - ] Fetching instance discovery from the network from host login.microsoftonline.com. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:12Z - ] Starting [Oauth2Client] Sending GET request 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:12Z - ] Starting [HttpManager] ExecuteAsync
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:12Z - ] [HttpManager] Sending request. Method: GET. Host: https://login.microsoftonline.com. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] [HttpManager] Received response. Status code: OK. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] Finished [HttpManager] ExecuteAsync in 396 ms
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] Finished [Oauth2Client] Sending GET request  in 400 ms
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] Starting [OAuth2Client] Deserializing response
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] Finished [OAuth2Client] Deserializing response in 30 ms
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] [Instance Discovery] After hitting the discovery endpoint, the network provider found an entry for login.microsoftonline.com ? True. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] Authority validation enabled? True. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] Authority validation - is known env? True. 
False MSAL 4.55.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.19045 [2023-08-31 10:08:13Z - ] Using WebView1 embedded browser because the authority is Aad. WebView2 does not provide SSO.
```
![Screenshot from 2023-08-31 17-15-54](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/12965553/4ba5e16f-6c92-4468-94f4-b21c0a323da3)
![Screenshot from 2023-08-31 17-16-10](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/12965553/55a79e4d-1137-4be0-80fe-e7e25e0f5499)

### Relevant code snippets

```csharp
...
 config.Instance = "https://login.microsoftonline.com/common";
            config.RedirectUri = "msal02f9737c-ec35-4bee-aa08-3757436ee076://auth";
            // build the AAd authority Url
            string authority = string.Concat(config.Instance, config.TenantId);
            var myLogger = new MyIdentityLogger();
            // Initialize the MSAL library by building a public client application
            application = PublicClientApplicationBuilder.Create(config.ClientId)
                                                    .WithAuthority(authority)
                                                    .WithLogging(myLogger)
                                                    .WithParentActivityOrWindow(GetWindowHandle)
                                                    .WithRedirectUri(config.RedirectUri)
                                                    .Build();

            var storage = new StorageCreationPropertiesBuilder("lk_token.cac", Base.GetDataPath()).Build();
            // This hooks up the cross-platform cache into MSAL
            var cacheHelper = await MsalCacheHelper.CreateAsync(storage);
            cacheHelper.RegisterCache(application.UserTokenCache);
...
```

### Expected behavior

MFA works with AAD

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
The service controls the content in those pages, not the SDK, but the SDK does indeed use WebView1 as default browser.

I suggest the following: 

1. Try to upgrade WebView1 to use a newer engine. See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/troubleshooting. This doesn't require you to make changes to your app.

3. If this is your app, upgrade from WebView to WAM (this is a Windows component). See https://aka.ms/msal-net-wam 
4. [Alternative] If this is your app, you can configure to use the system browser instead of embedded browser. It will use whatever the user's browser is. I don't recommend this, WAM is better.


6. How is the "additional information" handled? Is this fully handled by AAD or by a 3rd party (AAD has extensibility for MFA, on-prem directories etc.)? If it's fully handled by AAD, then open an issue through the Azure Portal.

**Comment by akainz** [comment]
@bgavrilMS I had a look and both 1 and 2 solve the issue. In case you arrive here via search engine. Either set a registry key according to the first link to use Edge in Webview1 or use WithBroker(true) to use WAM
...
            application = PublicClientApplicationBuilder.Create(config.ClientId)
                                                    .WithAuthority(authority)
                                                    .WithLogging(myLogger)
                                                    .WithBroker(true)
                                                    .WithParentActivityOrWindow(GetWindowHandle)
                                                    .WithRedirectUri(config.RedirectUri)
                                                    .Build();
...

We decided to go with WAM because it seems the longer supported solution but it's nice to know one can use WebView1 with a new browser.

Thanks @bgavrilMS this closes our issue
