### ISSUE TITLE
[Bug] MSAL cache extensions package references deprecated System.IO.FileSystem.AccessControl 5.0.0

### ISSUE THREAD

**Issue by AnKiLa** [AzureAD/microsoft-authentication-library-for-dotnet#4335]
### Library version used

4.56.0

### .NET version

.NET 4.7.2

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

MSAL cache extensions package 4.56.0. shows a dependency to System.IO.FileSystem.AccessControl >= 5.0.0. which is marked as deprecated.
This brings up warnings in Visual Studio NuGet Package manager. Are there any plans to use non deprecated packages in near future?

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
So this dependency is deprecated because it is already included in .NET Framework and in .NET 6. But the project here is `netstandard2.0`. 

Let's see what .NET folks recommend here - https://github.com/dotnet/runtime/issues/91729

I think we have to add back support for .NET Fwk and .NET here to fix this (on these frameworks, we don't need that dependency)

**Comment by pmaytak** [comment]
> So this dependency is deprecated because it is already included in .NET Framework and in .NET 6. But the project here is `netstandard2.0`.
> 
> Let's see what .NET folks recommend here - [dotnet/runtime#91729](https://github.com/dotnet/runtime/issues/91729)
> 
> I think we have to add back support for .NET Fwk and .NET here to fix this (on these frameworks, we don't need that dependency)

Adding .Net FX would not have fixed it, since it'd still be an issue for .NET Standard?

Either way, they [un-deprecated](https://github.com/dotnet/runtime/issues/91729#issuecomment-1710532511) the 5.0.0. So this is not an issue now.

**Comment by bgavrilMS** [comment]
I am very pleasantly surprised by how fast this was sorted out.
