### ISSUE TITLE
Authenticating against Azure App Services

### ISSUE THREAD

**Issue by mjfara** [AzureAD/microsoft-authentication-library-for-dotnet#434]
Not sure if this goes here, can't find ANYONE with the same problem, or any documentation regarding this scenario. Been pulling my hair out with this one for the last week.
I have a simple requirement in my UWP app, and don't care what the process is to make it happen.

I want my user's to log in once, and be able to access the MS Graph on the back end (Azure Mobile App).
I've tried client-flow with MSAL, App Services does not accept the authentication token:

`PublicClientApplication myApp = new PublicClientApplication("My-AppID-From-App-Registration-Portal");
string[] scopes = new string[] { "User.Read" };
AuthenticationResult authenticationResult = await myApp.AcquireTokenAsync(scopes).ConfigureAwait(false);

JObject payload = new JObject();
payload["access_token"] = authenticationResult.AccessToken;
payload["id_token"] = authenticationResult.IdToken;

user = await MobileService.LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount, payload);`

This does not work, can anyone shed some light on why? And how I can get it to work?

**Comment by DiegoVil** [comment]
This works for me when I execute it in LocalMachine, when I try to run it in HoloLens simulator or Mobile simulator also crashes for me.

`  public static async Task<string> GetTokenForUserAsync()
        {
            AuthenticationResult authResult;
            try
            {
                
                authResult = await IdentityClientApp.AcquireTokenAsync(Scopes) ;
                ///Put and endpoint Here
                authResult = await IdentityClientApp.AcquireTokenSilentAsync(Scopes, null);
                TokenForUser = authResult.IdToken;
                // save user ID in local storage
                _settings.Values["userID"] = authResult.User.Identifier;
                _settings.Values["userEmail"] = authResult.User.DisplayableId;
                _settings.Values["userName"] = authResult.User.Name;
            }

            catch (Exception ex)
            {
                if (TokenForUser == null || Expiration <= DateTimeOffset.UtcNow.AddMinutes(5))
                {
                    authResult = await IdentityClientApp.AcquireTokenAsync(Scopes);

                    TokenForUser = authResult.IdToken;
                    Expiration = authResult.ExpiresOn;

                    // save user ID in local storage
                    _settings.Values["userID"] = authResult.User.Identifier;
                    _settings.Values["userEmail"] = authResult.User.DisplayableId;
                    _settings.Values["userName"] = authResult.User.Name;
                }
            }

            return TokenForUser;
        }`

**Comment by kpanwar** [comment]
What does not work exactly? Can you share the stacktrace?

**Comment by DiegoVil** [comment]
The program'[3192] AuthenticationHoloLens.exe' exited with code-1073741819 (0xc0000005) 'Access violation'.

I do not know if the problem comes from here or from the info in the next [post](https://forums.hololens.com/discussion/7285/sign-on-ui).

**Comment by kpanwar** [comment]
I need the stacktrace to be sure that this is the sdk problem.

**Comment by kpanwar** [comment]
You are sending a graph token to mobile services which is a completely different audience. It will not work by design. Btw, current limitation of the STS is that it cannot issue tokens for anything other than MS graph.
