### ISSUE TITLE
[Bug] Breaking change in ManagedIdentityApplicationBuilder.Create causing MissingMethodException

### ISSUE THREAD

**Issue by tompazourek** [AzureAD/microsoft-authentication-library-for-dotnet#4341]
### Library version used

4.56.0

### .NET version

netstandard2.0

### Scenario

ManagedIdentityClient - managed identity

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

- In PR #4107, there was a breaking change in the `ManagedIdentityApplicationBuilder.Create` method. This causes `MissingMethodException` for libraries that used this method. One such library that used it is Microsoft's own https://github.com/Azure/Microsoft.Azure.StackExchangeRedis

### Expected behavior

- Breaking changes shouldn't be present in minor version upgrades. Especially if they cause breaking of other Microsoft libraries.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by tompazourek** [comment]
Related: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/issues/18

**Comment by gladjohn** [comment]
@tompazourek Before upgrading to MSAL 4.56.0, were you using a preview version of MSAL for the managed identity feature? i.e. were you calling Managed Identity with the Experimental Features flag?

**Comment by gladjohn** [comment]
MI was released with [MSAL version 4.54.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.54.0). Also, the final API was [updated](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4114), when we GA'd the feature.

**Comment by tompazourek** [comment]
> @tompazourek Before upgrading to MSAL 4.56.0, were you using a preview version of MSAL for the managed identity feature? i.e. were you calling Managed Identity with the Experimental Features flag?

I'm using the latest Microsoft.Azure.StackExchangeRedis version 1.1.0 that depends on Microsoft.Identity.Client >= 4.53.0.

Due to a dependency upgrade, I moved to the latest Microsoft.Identity.Client 4.56.0 and that that broke Microsoft.Azure.StackExchangeRedis library on the aforementioned MissingMethodException. I wasn't using any feature flags whatsoever or preview versions of any packages.

What's surprising to me is that the 4.53.0 to 4.56.0 update is only a minor version bump. I didn't expect any breaking change in runtime.

> MI was released with [MSAL version 4.54.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.54.0). Also, the final API was https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4114, when we GA'd the feature.

It would be better if the API changes in #4107 weren't breaking especially when they're released in a minor version. What I mean by that is that it would be better to keep the original public method signatures working, maybe mark them with `[ObsoleteAttribute]`, and remove them in the next major version (5.0.0). The Microsoft.Identity.Client package is commonly referenced by many different libraries, and making breaking changes in minor versions can result in dependency hell as it might be impossible to satisfy the version constraints of the dependent packages and still keep it working during runtime.

When I look at the [release notes for 4.54.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.54.0), I see only a small mention of updated API. If there's a big change that will make other libraries stop working, I'd expect some bigger notice, maybe even "BREAKING CHANGES" section.

What my expectation is for a library like Microsoft.Identity.Client that's often used as a dependency:

- Try to avoid making breaking changes
- If a breaking API change is made, bump the major version (e.g. 5.0.0), and announce it very visibly with details

@gladjohn What's your opinion on this? Do you also feel the handling of breaking changes is important and could be better for Microsoft.Identity.Client?

**Comment by tompazourek** [comment]
@gladjohn I'm wondering about the preview version you mentioned. I realized that I don't really understand what you meant. Can you please explain a bit more?

From my point of view, there was a `public static ManagedIdentityApplicationBuilder Create(string userAssignedId)` method signature in 4.53.0, and then in 4.54.0, this method signature disappeared, and was replaced by `public static ManagedIdentityApplicationBuilder Create(ManagedIdentityId managedIdentityId)`.

Which part of this was the preview stuff? Was the method behind some feature flag? I only see normal public methods released in stable package versions.

I don't completely follow, so I might be missing something...

**Comment by gladjohn** [comment]
Looks like you have already been working with [StackExchangeRedis](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/issues/18), am I missing something here?

**Comment by tompazourek** [comment]
> Looks like you have already been working with [StackExchangeRedis](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/issues/18), am I missing something here?

That referenced issue was caused by this breaking change in Microsoft.Identity.Client. The Microsoft.Azure.StackExchangeRedis authors can fix it by updating the dependencies and releasing a new version.

This issue we're discussing right now (#4341) is about not having breaking changes in Microsoft.Identity.Client in the first place. This affects Microsoft.Azure.StackExchangeRedis, but doesn't necessarily only affect Microsoft.Azure.StackExchangeRedis. It's possible that more people encounter the breaking changes as they update to newer versions. And not just people that use Microsoft.Azure.StackExchangeRedis, it can be anyone who uses any of the methods that were removed.

- Ideally, this issue would be fixed by bringing back the removed methods. But I have a feeling that avoiding breaking changes is not a high priority for this project, so I don't feel it's going to happen.
- If nothing else happens with the existing breaking changes, it would be good to be more careful about making breaking changes in the future.

But it's possible I'm wrong about what's a breaking change here and what isn't since you mentioned some experimental flags and preview versions and I don't actually understand what you meant.

**Comment by gladjohn** [comment]
When MSAL does preview features like in this case for Managed Identity, App Developers need to use `.WithExperimentalFeatures()` flag, this enables them (in this case Redis) to test the preview. Since, we (MSAL) are still in private preview, the final APIs may change between preview versions or when we GA the feature. Like in this case when we GA'd managed identity, we changed the method to better suit the developer scenarios. Once we GA, MSAL will ensure not to cause a breaking change in minor versions. 

If you see the [PR from Redis](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/pull/7/files#diff-2e13eadf9b1b11531485ee9176d267a9930d2a69142e2d4c5b64445a52bc474a), you will notice they are moving from a MSAL Preview version to a feature GA'd version. 

Are you able to update to the latest Redis lib, that uses the GA'd version of MSAL?

**Comment by tompazourek** [comment]
> When MSAL does preview features like in this case for Managed Identity, App Developers need to use `.WithExperimentalFeatures()` flag, this enables them (in this case Redis) to test the preview. Since, we (MSAL) are still in private preview, the final APIs may change between preview versions or when we GA the feature. Like in this case when we GA'd managed identity, we changed the method to better suit the developer scenarios. Once we GA, MSAL will ensure not to cause a breaking change in minor versions.
> 
> If you see the [PR from Redis](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/pull/7/files#diff-2e13eadf9b1b11531485ee9176d267a9930d2a69142e2d4c5b64445a52bc474a), you will notice they are moving from a MSAL Preview version to a feature GA'd version.
> 
> Are you able to update to the latest Redis lib, that uses the GA'd version of MSAL?

I see it now, thank you for taking time to explain.

The latest version of Microsoft.Azure.StackExchangeRedis is 1.1.0 and that one still references the missing method. There's no version of Microsoft.Azure.StackExchangeRedis released that would work with current Microsoft.Identity.Client.

**Comment by bgavrilMS** [comment]
Preview APIs are not meant to be used in production. We need to revise our mechanism for this. At the very least we must ask other sdk to not depend on them.

But for the short term, @gladjohn can you pls reach out to the Redis folks to get this updated ASAP? The longer this lives, the more diamond dependencies issues folks will face.

**Comment by gladjohn** [comment]
>  @gladjohn can you pls reach out to the Redis folks to get this updated ASAP?

Requested Redis team to update their SDK as soon as they can.

**Comment by tompazourek** [comment]
A month has passed, and still nothing has changed. Can you please try to urge this?

The Redis repository doesn't seem to be active or maintained, the owners don't respond to issues.

This is now a more serious issue as there's a CVE in Azure.Identity (https://github.com/advisories/GHSA-5mfx-4wcx-rv27) which also relates to these package versions...

**Comment by bgavrilMS** [comment]
We will reach out again, apologies about this.

**Comment by tompazourek** [comment]
Resolved now, the Microsoft.Azure.StackExchangeRedis package was released with version 2.0.0.

Thank you all.
