### ISSUE TITLE
How do I configure an already existing Blazor Server application to use Azure AD authentication?

### ISSUE THREAD

**Issue by BharatForDotNet** [AzureAD/microsoft-authentication-library-for-dotnet#4344]
**Please check those that apply**

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**
How do I configure an already existing Blazor Server application to use Azure AD authentication?

**Comment by pmaytak** [comment]
See [Blazor samples](https://learn.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code?tabs=framework#blazor). These use Microsoft.Identity.Web - a wrapper library over MSAL.NET, the recommended way.
