### ISSUE TITLE
[Engineering Task] Fix CodeQL issues

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4352]
### Type of task?

Other(s)

### Description

Fix [CodeQL issues](https://identitydivision.visualstudio.com/Engineering/_queries/query/?_a=query&wiql=%0ASELECT%20ID%2CSeverity%2CState%2C%5BAssigned%20To%5D%2CTitle%20FROM%20WorkItem%20WHERE%20Tags%20Contains%27TSA-MSAL%20.NET%20AUTH%20SDK-CodeQL-Official%27%0A) 

### Solution

Fix the issue

**Comment by gladjohn** [comment]
setting as P2 since the issues are in test code.

**Comment by bgavrilMS** [comment]
I'm suprised this is in test code only. Product does the same. We need an exception though, because AAD doesn't support other padding scheme.
