### ISSUE TITLE
What's the plan to support Entra ID using WebView2 with MSAL.NET

### ISSUE THREAD

**Issue by AvishekChakrabortyTR** [AzureAD/microsoft-authentication-library-for-dotnet#4357]
Hello,
Hoping this is the correct place to raise this query. Please let me know if I should raise it some where else. 
I see notice on the learn portal here https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/webview2 that WebView2 is not supported for Microsoft Entra ID (formerly known as Azure Active Directory) authorities due to stability issues. This is a problem for us as this forces to launch IE browser which isn't supported anymore. Can you let us know what's the plan to support Entra ID here?

**Comment by bgavrilMS** [comment]
Hi @AvishekChakrabortyTR 

For AAD authority (work and school & personal accounts), the North Star is WAM - see https://aka.ms/msal-net-wam 
For other authorities, including ADFS, B2C, CIAM etc., you can use webview2 today in your app, by referencing MIcrosoft.identity.Client.Desktop package and calling `WithDesktopFeatures`
