### ISSUE TITLE
Replacing Microsoft.IdentityModel.Clients.ActiveDirectory with Microsoft.Identity.Client

### ISSUE THREAD

**Issue by VigneashSelvaraj** [AzureAD/microsoft-authentication-library-for-dotnet#4362]
Hi - 
Package Microsoft.IdentityModel.Clients.ActiveDirectory seems to deprecated and my company is suggesting to migrate to use Microsoft.Identity.Client. I need to retrieve an access token from my AZURE KEY VAULT. May I know the replacement code by using Microsoft.Identity.Client. BACKGROUND: This is a .Net Framework 4.6.2 project

```
private async Task<string> GetTokenAsync(string authority, string resource, string scope)
{
    try
    {
        var authContext = new AuthenticationContext(authority);
        AuthenticationResult result = await authContext.AcquireTokenAsync(resource,
                                            new ClientCredential(ClientId, ClientSecret));
        if (result == null)
        {
            throw new InvalidOperationException("Bearer token acquisition needed to call KeyVault service failed");
        }
        else
        {
            return result.AccessToken;
        }
    }
    catch (Exception exp)
    {
        var ex = new Exception(string.Format("Authentication failed for {0}", ClientId), exp);
        throw ex;
    }
}
```

**Comment by pmaytak** [comment]
See the migration docs: https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/msal-net-migration.
For client credentials, you'd want this: https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/migrate-confidential-client?tabs=daemon#update-the-code-of-daemon-scenarios
