### ISSUE TITLE
Values of PublicClientApplication.Users is not retained in Xamarin.Forms iOS app

### ISSUE THREAD

**Issue by jamesyip** [AzureAD/microsoft-authentication-library-for-dotnet#437]
Every time the app is restored, PublicClientApplication.Users is empty and there are no way we can save the user token to prevent the prompt for login page again.

**Comment by kpanwar** [comment]
Can you provide MSAL logs? If it does not repro on a real device then it is apple specific issue.

**Comment by kpanwar** [comment]
See https://forums.xamarin.com/discussion/81026/could-not-save-account-to-keychain-34018

**Comment by jamesyip** [comment]
May I know how to generate the MSAL log?

Thanks,

James

**Comment by jennyf19** [comment]
You will need to implement the log callback. You can see a sample of implementing it here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev/tests/dev%20apps/WebTestApp/WebApp/Controllers/HomeController.cs#L57

**Comment by jamesyip** [comment]
This is done at my iOS app or web API app?

________________________________

**Comment by jmprieur** [comment]
@jamesyip : I'm not sure I understand the question. this is .NET code; at the Xamarin.Forms app. you also have a web app ?

**Comment by jamesyip** [comment]
We are working on a Xamarin.Forms app which connects to WebAPI for data. The WebAPI is protected by Azure B2C. So the MSAL is on Xamarin.Forms app.

Thanks,

James

**Comment by kpanwar** [comment]
@jamesyip - you need to implement the callback in ios app

**Comment by Francessco121** [comment]
We see this issue on iOS 11.  It works as expected on iOS versions prior to 11.  We are implementing the callback in the AppDelegate...

```csharp
public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
{
    AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(url);
    return true;
}
```

**Comment by kpanwar** [comment]
That callback is for invoking the app back. This issue only exists in simulators. Are you seeing in a real device?

**Comment by Francessco121** [comment]
Thanks for the quick reply! Unfortunately we do not have access to a real iOS 11 device. So if this is just a simulator issue then I guess we're actually all set.

**Comment by jmprieur** [comment]
Closing as the problem looks like solved
