### ISSUE TITLE
[Bug] Cache Hit Ratio in Header Telemetry is Not Thread Safe

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-authentication-library-for-dotnet#4370]
### Library version used

latest

### .NET version

Any

### Scenario

ConfidentialClient - web api (AcquireTokenOnBehalfOf), Other - please specify

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

The cache hit ratio is [not thread safe](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fblob%2F80c848b5b7bfc033b11ee82107344bfc22efc0da%2Fsrc%2Fclient%2FMicrosoft.Identity.Client%2FTelemetryCore%2FHttp%2FHttpTelemetryManager.cs%23L21C1-L22C1&data=05%7C01%7Ckarymes%40microsoft.com%7Cbf6bd565fcee412ac48e08dbb54064c9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638303060445819304%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OsnUoBtf55DhmdrKHgfqSqTWnJwnWoC0nqhF2v1U4oA%3D&reserved=0) and thus the numbers might be skewed.

### Expected behavior

Thread-safety of the code.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
We were actually thinking of dropping this data altogether. It's more reliable to use the "cache refresh reason" / "cache info" field - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/80c848b5b7bfc033b11ee82107344bfc22efc0da/src/client/Microsoft.Identity.Client/TelemetryCore/Http/HttpTelemetryManager.cs#L95

**Comment by rymeskar** [comment]
Meaning that there won't be collectible cache hit ratio on eSTS header telemetry?

**Comment by bgavrilMS** [comment]
Proposal is to stop emitting this data. MSAL doesn't have a reliable way of collecting this and we've never seen it as actionable.

**Comment by rymeskar** [comment]
Thank you :) I am fine with such approach.

**Comment by rymeskar** [comment]
Since OpenTelemetry support was released, I am fine closing this item.
