### ISSUE TITLE
Is there a way to use a WebView instead of Chrome browser for Android sign-in to avoid storing cookies / cache?

### ISSUE THREAD

**Issue by ammarMheir** [AzureAD/microsoft-authentication-library-for-dotnet#438]
Recently, it seems that Chrome browser is used for logging in, however this started posing an issue where the chrome browser is storing cookies / cache on user login info and hens when initially logging a user out, then logging back in again, the Chrome browser will appear for a quick second then simply direct the user back to the home page. I'm assuming the credentials are stored and thus not displaying the login page again once the user initially logs out and tries to log back in again. 

I understand that the Library does not clear the cache mentioned here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/92

So is there a way to fall back to using a WebView instead? Or is there a workaround to clearing the cookies / cache?

**Comment by kpanwar** [comment]
There is no fallback or plans to provide one. Can you provide a video repro and MSAL logs to show UI flash. Reason I ask for this is because It should never happen as the library sends prompt=select_account and that ensures that the user sees a selection page and not a flash.

**Comment by Blin4ik91** [comment]
Same issue here, how to fix it ?

**Comment by Blin4ik91** [comment]
> There is no fallback or plans to provide one. Can you provide a video repro and MSAL logs to show UI flash. Reason I ask for this is because It should never happen as the library sends prompt=select_account and that ensures that the user sees a selection page and not a flash.

still not working correct, same issue here.... 
don't know how to fix it

**Comment by jmprieur** [comment]
@Blin4ik91 
this is now fixed. Did you read this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-Android-specifics ? and this https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Android-system-browser ?

**Comment by Blin4ik91** [comment]
@jmprieur 
yes, Xamarin Android specifics are set, even Chrome is not working.
I tested it on a Nokia and a Samsung device.

**Comment by jennyf19** [comment]
@Blin4ik91 Do you have the android:scheme identified in the manifest:

`<data android:scheme="msal{client_id}" android:host="auth" />`

And the following values in the manifest:

```CSharp
<activity android:name="microsoft.identity.client.BrowserTabActivity">
	<intent-filter>
		<action android:name="android.intent.action.VIEW" />
		<category android:name="android.intent.category.DEFAULT" />
		<category android:name="android.intent.category.BROWSABLE" />
		<data android:scheme="msale3b9ad76-9763-4827-b088-80c7a7888f79" android:host="auth" />
         </intent-filter>
</activity>

**Comment by Blin4ik91** [comment]
> @Blin4ik91 Do you have the android:scheme identified in the manifest:
> 
> `<data android:scheme="msal{client_id}" android:host="auth" />`
> 
> And the following values in the manifest:
> 
> ```cs
> <activity android:name="microsoft.identity.client.BrowserTabActivity">
> 	<intent-filter>
> 		<action android:name="android.intent.action.VIEW" />
> 		<category android:name="android.intent.category.DEFAULT" />
> 		<category android:name="android.intent.category.BROWSABLE" />
> 		<data android:scheme="msale3b9ad76-9763-4827-b088-80c7a7888f79" android:host="auth" />
>          </intent-filter>
> </activity>
> ```

Yes, it is all definied.
The Login-View appers only if there was no login before (eg. reinstallation)
after that I can't Logout myself because it logs me automatically in again.
(WebView appears for a few milliseconds)

**Comment by jennyf19** [comment]
@Blin4ik91 Can you share the code for the AcquireToken calls (interactive and silent)?

**Comment by Blin4ik91** [comment]
@jennyf19 
// Logout
`_currentAuthenticationResult = null;
if (!(await _adClientApp.GetAccountsAsync()).Any())
  return;

(await _adClientApp.GetAccountsAsync()).ToList()
.ForEach(u =>
{
 _adClientApp.RemoveAsync(u);
});`

// Login
`user = null;
_currentAuthenticationResult = await _adClientApp.AcquireTokenAsync(Settings.Scopes, user,
UIBehavior.NoPrompt, null, new string[0], Settings.Authority, _uiParent);`

**Comment by jennyf19** [comment]
@Blin4ik91 I think you are seeing the UI flash because of `UIBehavior.NoPrompt`. You should be using `UIBehavior.SelectAccount`, as it's recommended to only use NoPrompt with B2C scenarios where you already have the user logged in but don't want to show them another prompt or UI dialog. Then you should be able to log out as well. Can you try and see if this fixes the issue for you?

**Comment by Blin4ik91** [comment]
@jennyf19 
great this works fine, I thought you have to log in with your credentials with this setting every time
but it's not true.

**Comment by jennyf19** [comment]
thanks for the update, @Blin4ik91
