### ISSUE TITLE
how to set Topmost=true when using withuseembededwebview

### ISSUE THREAD

**Issue by QQstone** [AzureAD/microsoft-authentication-library-for-dotnet#4382]
Users complain that sometimes login prompts are displayed in the background, making them unaware of it.
Is there a way to set it to always be at the top, like setting the Topmost parameter for a WPF window?

**Comment by pmaytak** [comment]
You can use [WithParentActivityOrWindow](https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/desktop-mobile/wam#parent-window-handles) to parent the web view to the calling window.

**Comment by QQstone** [comment]
@pmaytak  as I understand it, this method cannot prevent other program's windows from covering our login popups

**Comment by bgavrilMS** [comment]
The suggestion provided by @pmaytak is the best path forward. See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/Platforms/Features/WinFormsLegacyWebUi/WindowsFormsWebAuthenticationDialogBase.cs#L329

We won't be fixing any issues with the legacy web browse. We encourage all apps to migrate to WAM - see https://aka.ms/wam
