### ISSUE TITLE
[Bug] WAM SSO with Windows not working for guest account

### ISSUE THREAD

**Issue by AndrewMitev** [AzureAD/microsoft-authentication-library-for-dotnet#4383]
### Library version used

4.56.0

### .NET version

.NET 7

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I have configured the proper redirect URL in the Mobile and desktop applications redirect URIs

WAM Error  
 Error Code: 3399614466 
 Error Message: IncorrectConfiguration 
 WAM Error Message: (pii) 
 Internal Error Code: 557973643 
 Possible causes: 
- Invalid redirect uri - ensure you have configured the following url in the application registration in Azure Portal: ms-appx-web://microsoft.aad.brokerplugin/86bd0e8c-bff0-4596-bfa5-5fa9df1b380e 

### Relevant code snippets

result = await app.AcquireTokenSilent(scopes, PublicClientApplication.OperatingSystemAccount)
            .ExecuteAsync();

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by AndrewMitev** [comment]
This is the result:

True MSAL 4.56.0.0 MSAL.NetCore .NET 7.0.12 Microsoft Windows 10.0.19045 [2023-10-19 08:32:38Z] [MSAL:0002]	ERROR  	ErrorInternalImpl:134	Created an error: 8xg43, StatusInternal::InteractionRequired, InternalEvent::None, Error Code 0, Context 'Could not find an account. Both local account ID and legacy MacOS user ID are not present'

I am trying to acquire token from my windows ad account which is from tenant A, I created tenant B with that account and my app registration is in tenant B.

**Comment by bgavrilMS** [comment]
Is the user a guest in tenant B? Have you pre-consented to the application? Generally when MsalUiRequiredException occurs, you have to call `AcquireTokenInteractive`

**Comment by AndrewMitev** [comment]
UserType: member, Identities: External Azure AD. What do you mean by pre-consting to the app? Can you explain?

**Comment by AndrewMitev** [comment]
Also got this:

Application '86bd0e8c-bff0-4596-bfa5-5fa9df1b380e'(api://86bd0e8c-bff0-4596-bfa5-5fa9df1b380e) is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier.

**Comment by bgavrilMS** [comment]
> UserType: member, Identities: External Azure AD. What do you mean by pre-consting to the app? Can you explain?

Well when you request a token from a user for the first time, consent it needed. This is when AAD asks "Do you (i.e. the user) agree to allow the app XYZ to access user profile information on your behalf?". The consent screen can only be displayed in a browser, so AcquireTokenSilent will fail with a UiRequiredException. 

For app ID URI, can you try a different name ? I believe WAM has some limitations for accessing your own web api.
