### ISSUE TITLE
[Bug] Using assigned token lifetime policy of app registration.

### ISSUE THREAD

**Issue by trebiax** [AzureAD/microsoft-authentication-library-for-dotnet#4386]
### Library version used

4.57.0

### .NET version

**.NET 7** WPF application

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

Hello,

Trying to apply token lifetime policy to newly created application in app registration of Microsoft Entra ID.

As a source used this article:

https://learn.microsoft.com/en-us/azure/active-directory/develop/configure-token-lifetimes

Everything succeeded, policy created, policy assigned to app.

But when I'm using MSAL (for .net desktop app) to acquire token interactively

`PublicClientApp.AcquireTokenInteractive(scopes)`

I am not getting token with the specified lifetime. Apparently, policy isn't used by application. Always the default token is used (60-90 minutes)

IMP! The issue is, when I create policy with flag: `IsOrganizationDefault = $false` that case it's ignored.

If I create same policy with` IsOrganizationDefault = $true`, then policy works (apparently considered by app) and acquired token lifetime is the one I had specified.

What's wrong with `IsOrganizationDefault = $false` or what am I doing wrong ?

I also tried to use old AzureADPreview approach (instead of microsoft graph), command:

```
 $policyDefinition = @('{
 "TokenLifetimePolicy": {
 "Version": 1,
 "AccessTokenLifetime": "04:00:00", 
 "IdTokenLifetime": "04:00:00", # Tried without that as well
 "RefreshTokenLifetime": "04:00:00" # Tried without that as well
   } 
 }')

$policy = New-AzureADPolicy -Definition $policyDefinition -DisplayName "CustomTokenLifetimePolicy" -IsOrganizationDefault $false -Type "TokenLifetimePolicy"
Add-AzureADApplicationPolicy -Id "SomeApplicationObjectId" -RefObjectId $policy.Id 
```

Also tried to use Microsoft Graph SDK Client (for .net). Succeeded to fetch assigned policies, via:

`await graphClient.Policies.TokenLifetimePolicies["tokenId"].AppliesTo.GetAsync();`

in result of this command there is listed my application, so looks like policy is assigned in all 3 approaches (Graph powershell, Graph .net client, AzureADPreview).

So most likely token acquisition process ignores consideration of that policy, for some reason. The question is why ? Prioritization described in one of articles ([https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes](https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes)) looks like being taken into consideration (there is no default organization policies, neither others. Just one created policy, the custom one)

Thanks for any help !

### Expected behavior

Expecting token lifetime policy to be impacting on token acquisition process

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Solution and workarounds

Workaround is to use 

`IsOrganizationDefault = $false` when creating token lifetime policy

**Comment by bgavrilMS** [comment]
Hi @trebiax - the SDK does not control the CA policies or other settings from the application config, it's fully controlled by the service.

 Please reach out via the Azure Portal support options for help with this.
