### ISSUE TITLE
[Feature Request] Add support for CIAM custom authority

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4387]
### MSAL client type

Public, Confidential

### Problem Statement

CIAM will support custom authorities, which will require MSAL to perform OIDC discovery of the endpoints. 

Blocked until we have a test environment.

### Proposed solution

Recommendation is for MSAL to add support to `WithGenericAuthority` for user flows (consider renaming to `WithOidcAuthority`). 

Since this is a general-purpose mechanism, we should also try to use a non-Microsoft authority, such as Facebook or Google. MSAL can still add "client_info" and parse `tid` claim from id tokens by default, to provide an "AAD-like" experience. If "client_info" isn't there, account id will be `sub` claim. If `tid` isn't there, it's just ignored.

**Comment by bgavrilMS** [comment]
CC @rayluo @localden  as we do not have a test enviroment.

**Comment by rayluo** [comment]
> CC @rayluo @localden as we do not have a test enviroment.

FYI: Still waiting for [this internal PR](https://msazure.visualstudio.com/One/_git/ESTS-Main/pullrequest/8841090?path=%2Fsrc%2FProduct%2FESTSFE%2FConfiguration%2Fsettings.ini) to be approved and deployed. I have pinged stakeholders via email and teams.

**Comment by bgavrilMS** [comment]
Done
