### ISSUE TITLE
Remove AcquireTokenAsync API from public clients in netcore

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#439]
Remove AcquireTokenAsync API from public clients in netcore As the API has no way to show UI in a platform agnostic way.

**Comment by jmprieur** [comment]
Note that, even developpers cannot use it today (they get a not implemented exception), this is a breaking change in the public API, so we might need to way for the next major release

**Comment by jmprieur** [comment]
Until .NET core has UI we need to remove it from the public API (as MSAL is a preview libraries)

**Comment by jmprieur** [comment]
Done.
See https://aka.ms/msal-net-2-released
