### ISSUE TITLE
Flyout Page SetCollapseStyle doesn't have any change

### ISSUE THREAD

**Issue by AnithaRaniT** [AzureAD/microsoft-authentication-library-for-dotnet#4390]
### Library version used

.Net MAUI 

### .NET version

.Net7

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I'm trying to create a New MAUI app in windows wth Flyout Navigation. 

And in Windows I want the Flyout should be open partially always and when I click on the Hamburger it should open fully.

Like as Below:

Actual:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/45478510/e04b71cc-8c8d-45bf-805d-758d4241e672)

Expected:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/45478510/b9e72a91-9f27-4434-8520-be96355aa552)

In my Xamarin project I'm able to achieve this with a small code snippet of 
`On<Windows>().SetCollapseStyle(CollapseStyle.Partial);`

But the same is not working in MAUI

### Relevant code snippets

```csharp
`On<Windows>().SetCollapseStyle(CollapseStyle.Partial);`
```

### Expected behavior

Expected:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/45478510/b9e72a91-9f27-4434-8520-be96355aa552)

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Hi @AnithaRaniT - I think you have the wrong repo. This is the repo of MSAL, an authentication SDK. You are looking for MAUI https://github.com/dotnet/maui
