### ISSUE TITLE
[Bug] B2C signin not working with Android 14

### ISSUE THREAD

**Issue by DevDachi** [AzureAD/microsoft-authentication-library-for-dotnet#4393]
### Library version used

4.57.0

### .NET version

.NET 8 RC2

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue.

### Issue description and reproduction steps

We have working .Net Maui 8.0 based app for Android, iOS and Windows with B2C authentication. With Android 14 (Tested on Pixel device), the authentication is initiated, and intent filter scheme get called on the app, but it displays an empty activity and no further progress. 

The same app is working fine for Windows (all version), iOS (all version) and Android (< 14).

### Relevant code snippets

```csharp
_publicClientApplication = PublicClientApplicationBuilder.Create(Constants.ClientId)
#if ANDROID
	   .WithParentActivityOrWindow(() => Platform.CurrentActivity)
#elif IOS
            .WithIosKeychainSecurityGroup(Constants.IosKeychainSecurityGroups)
#endif
            .WithB2CAuthority(Constants.AuthoritySignIn)
            .WithRedirectUri($"msal{Constants.ClientId}://auth")
            .Build();

            authenticationResult = await _publicClientApplication
                .AcquireTokenInteractive(Constants.Scopes)
                .ExecuteAsync(cancellationToken);

```

We Noticed that on Android 14 device, following override is not getting hit, when browser calls back:

```csharp
    protected override void OnActivityResult(int requestCode, Result resultCode, Intent? data)
    {
        base.OnActivityResult(requestCode, resultCode, data);
        AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);
    }
```

### Expected behavior

Should be able authenticate with Android 14.

### Identity provider

Azure B2C Basic Policy

### Solution and workarounds

By using .WithUseEmbeddedWebView(true), it works fine for Microsoft Identity provider, but not for Google (Google doesn't allow sign with WebView). Also, with embedded WebView, we lose SSO capability.

**Comment by pmaytak** [comment]
@DevDachi Is this issue related to this https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4377#issuecomment-1765474934 (blank activity screen on Android 14).

**Comment by DevDachi** [comment]
Thanks @pmaytak for looking into this issue and connecting to a potential similar cause. Our situation seems different from related issue (No custom splash activity for us), but we are able to pinpoint what is breaking.

On the Android MainActivity class, we had launch mode set as single instance and this was causing the main activity on separate task from all other activities. After changing this to Single Task or removing this (default is standard), it works as expected. 

```csharp
...
//LaunchMode = LaunchMode.SingleInstance)]
LaunchMode = LaunchMode.SingeTask)]
public class MainActivity : MauiAppCompatActivity
...
```

We do not remember adding this manually and perhaps was added by visual studio maui.net project template in the past. 

We have confirmed that when a new project created with Visual Studio 2022 Version 17.7.2, the LaunchMode for the MainActivity is no longer set. This change aligns with our desired solution.
