### ISSUE TITLE
UWP Extra Query String Params Not Appended

### ISSUE THREAD

**Issue by devildog** [AzureAD/microsoft-authentication-library-for-dotnet#440]
Using a UWP app and trying to acquire a token with a custom domain. Two issues:
1. Have to set ValidateAuthority = false;  No where could I find this in any documentation but without this the request always fails due to invalid / not found authority

2. Assuming I set ValidateAuthority=False and then call:
result = await App.AuthenticationClient.AcquireTokenAsync(new string[] { "" },loginHint: null, behavior: UIBehavior.ForceLogin, extraQueryParameters: "B2C_1A_signup_signin_common-v2", parent: null);

I see this attempt:
GET https://host/tenant/v2.0/.well-known/openid-configuration

I expect this:
GET https://host/tenant/v2.0/.well-known/openid-configuration?p=B2C_1A_signup_signin_common-v2

Is there an alternative way to add the extra query string parameters so they are passed?

**Comment by kpanwar** [comment]
API input is incorrect. please look at sample https://github.com/Azure-Samples/active-directory-b2c-dotnet-uwp/. Line of interest is https://github.com/Azure-Samples/active-directory-b2c-dotnet-uwp/blob/master/active-directory-b2c-dotnet-uwp/App.xaml.cs#L110
