### ISSUE TITLE
[Bug] Gov Clouds(Fairfax and Mooncake) Failures: MsalClientException ErrorCode: authority_override_regional

### ISSUE THREAD

**Issue by sdk-jain** [AzureAD/microsoft-authentication-library-for-dotnet#4405]
### Library version used

4.45.0

### .NET version

4.7.2

### Scenario

ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

We are seeing MSAL exceptions after Microsoft.Identity.Client package upgrade and **only in Gov clouds.**

MSAL.Desktop.4.45.0.0.MsalClientException:   ErrorCode: authority_override_regional Microsoft.Identity.Client.MsalClientException: You configured WithAuthority at the request level, and also WithAzureRegion. This is not supported when the environment changes from application to request. Use WithTenantId at the request level instead.

Tried below fix as per some posts but that also didnt work:

newAuthenticationTask = newAuthenticationContext.AcquireTokenForClient(scopes).WithAuthority(newAuthorityId, false).WithSendX5C(isManagedCert).ExecuteAsync();

As we looked and discussed there was a breaking change done in recent release which is causing this:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/85684016/5e558d1d-5add-4a08-b942-4f1e6e23b01d)

@MSAL team: Please look and fix this issue.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.45.0

**Comment by bgavrilMS** [comment]
Let's deprecate `WithAuthority` at the request level with an `[Obsolete]` attribute.

**Comment by rayluo** [comment]
> `@MSAL` team: Please look and fix this issue.

Side note to @sdk-jain , that `@MSAL` github account is not owned by MSAL team.
