### ISSUE TITLE
[Bug] Error messages for using non-RSA certificates for certificate based auth could be better

### ISSUE THREAD

**Issue by christothes** [AzureAD/microsoft-authentication-library-for-dotnet#4407]
Currently, if a non-RSA certificate is used for certificate auth, the resulting error is a null reference exception (see below). Ideally, [SignWithCertificate](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4b0b6cdc73e079cc6a73c20f3ab01058da29e2b0/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs#L62-L63) would check whether the PublicKey.Oid is RSA and fail with a more descriptive exception.

```
NullReferenceException: Object reference not set to an instance of an object.

This exception was originally thrown at this call stack:
    Microsoft.Identity.Client.PlatformsCommon.Shared.CommonCryptographyManager.SignWithCertificate(string, System.Security.Cryptography.X509Certificates.X509Certificate2)
    Microsoft.Identity.Client.Internal.JsonWebToken.Sign(System.Security.Cryptography.X509Certificates.X509Certificate2, string, bool)
    Microsoft.Identity.Client.Internal.ClientCredential.CertificateAndClaimsClientCredential.AddConfidentialClientParametersAsync(Microsoft.Identity.Client.OAuth2.OAuth2Client, Microsoft.Identity.Client.Core.ILoggerAdapter, Microsoft.Identity.Client.PlatformsCommon.Interfaces.ICryptographyManager, string, string, bool, System.Threading.CancellationToken)
    Microsoft.Identity.Client.OAuth2.TokenClient.AddBodyParamsAndHeadersAsync(System.Collections.Generic.IDictionary<string, string>, string, System.Threading.CancellationToken)
    Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(System.Collections.Generic.IDictionary<string, string>, string, string, System.Threading.CancellationToken)
    Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(System.Collections.Generic.IDictionary<string, string>, System.Threading.CancellationToken)
    Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(System.Threading.CancellationToken, Microsoft.Identity.Client.Core.ILoggerAdapter)
    Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(System.Threading.CancellationToken)
    Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(System.Threading.CancellationToken)
    Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenForClientParameters, System.Threading.CancellationToken)
```

related to https://github.com/Azure/azure-sdk-for-net/issues/39711

**Comment by pmaytak** [comment]
+to-do: We also need to update this message and any relevant ones: "Could not use the certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps build against .NET Desktop 4.6 or lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a different certificate type (non-CNG) or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion.  and Inner Exception System.Security.Cryptography.CryptographicException: Keyset does not exist"
- Update to use 4.6.2
- Add a space after aka link before the period, otherwise it's broken

**Comment by bgavrilMS** [comment]
Although null-ref is pretty unpleasant, this is not a P1 as it's not a mainline scenario.
