### ISSUE TITLE
[Bug] Investigate absence of AAD error code in logs

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/microsoft-authentication-library-for-dotnet#4408]
### Library version used

4.56.0.0

### .NET version

.NET 6

### Scenario

ConfidentialClient - web api (AcquireTokenOnBehalfOf)

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

While working with an internal partner, we noticed that while the server was responding with an error code, AADSTS700027 in this case, it was not in the logs. The only relevant information in the logs was as followed:

ErrorCode: invalid_client
HTTP StatusCode 401

This is using Microsoft.Identity.Web.TokenAcquisition.

The root cause of the actual issue was that the client need to include the sendX5C option.

### Expected behavior

The error code from AAD is included in the logs.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by trwalke** [comment]
Looked into this and it seems like this is by design, we do not provide the full exception details because it is Pii.

**Comment by neha-bhargava** [comment]
Fixed in [MSAL.Net 4.60.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.60.0)
