### ISSUE TITLE
Investigate MTLS handshake + HttpClient extensiblity

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4432]
Few options : 

Currently, we use a default HttpClient without any customizations. For MTLS we may have to, 

- [x] Use existing HTTP Client and create an HttpClientHandler and set client certificate (consider clients passing their own httpclients)
- [x] Create new HTTP Client with an override for HttpClientHandler 
- [x] Add an optional httpclienthandler 
- [x] Or, WithHttpClient((X509Certificate2 mstlsCert) => HttpClient)
- [x] Expose an API for clients to get the certificate and then pass the httpclient with the certificate 
- [ ] uni testing

Add exceptions accordingly by validating the cert when POP tokens are requested

**Comment by bgavrilMS** [comment]
I think the investigation is done.
