### ISSUE TITLE
Broker could not satisfy the silent request

### ISSUE THREAD

**Issue by AmeerMansourGWsp** [AzureAD/microsoft-authentication-library-for-dotnet#4438]
### Library version used

4.57

### .NET version

4.8

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

1-I have created wpf app. and connected to AD B2C 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/151910954/8ac538b4-367f-4c4d-9062-a90e5bee8a45)
this is how i created PublicClientApplication
2-user login first time successfully 
3-when opening app again, it through this error when trying to Acquire Authentication Result Silent
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/151910954/909c309e-abbc-4bd9-aef1-51d37fd775d3)

### Expected behavior

AcquireAuthenticationResultSilent get AuthenticationResult without having to ask user to sign again each time he open my application

### Identity provider

Azure B2C Basic Policy

**Comment by AmeerMansourGWsp** [comment]
note: i used same code with older version (v4.0.30319) and it was working 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/151910954/95265723-58c1-47bb-ac53-4f1703b679fd)
this how i was getting auth result silently 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/151910954/b49a3371-7346-4659-8335-2272512ceee1)

**Comment by bgavrilMS** [comment]
Hi, what is the authority that you use here? Is it B2C ? The broker only works with AAD authority - https:\\login.microsoftonline.com\common (so work and school + personal Microsoft accounts, i.e. outlook.com etc.). 

That said, I expect we ignore the broker completely on B2C.

**Comment by AmeerMansourGWsp** [comment]
yes it is b2c.
so you mean if i am using b2c, i shouldn't be using withdesktopfeature ?

**Comment by AmeerMansourGWsp** [comment]
nice !
it works now !
i used [Microsoft.Identity.Client](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client?view=msal-dotnet-latest) only and it worked.

thanks !

**Comment by AmeerMansourGWsp** [comment]
@bgavrilMS 
it didn't work completely . it shows me this error when user sign up
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/151910954/2cbd10c5-a8af-4fe5-a54f-fd5fac57a3e3)

i still need broker and it works only  with older version (v4.0.30319)

**Comment by AmeerMansourGWsp** [comment]
still not working 
this is my code 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/151910954/408929d1-d318-4642-b65c-88ab2f02a6b1)
and this is nuget packages that i used
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/151910954/eb9b59e1-5b16-47cc-81ec-769f27b2cc08)

**Comment by AmeerMansourGWsp** [comment]
yes !
thanks for clarifying. if possible can you update the documentation in the wpf demo.
