### ISSUE TITLE
MSAL not supporting older version (before v2.0)

### ISSUE THREAD

**Issue by imvigo** [AzureAD/microsoft-authentication-library-for-dotnet#444]
I am using MSAL for in Xamarin mobile application. I want to use the older authorization endpoint and not v2.0, i.e. 
I want to use **https://login.microsoftonline.com/{tenant}/oauth2/authorize** and not **https://login.microsoftonline.com/common/oauth2/v2.0/authorize**.

Even after explicitly using the 1st url, at runtime, the second url seems to be called. With a little investigationg and looking at this [file](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0c635b72a9dfb4ed49abec890d18fcb3691a8775/src/Microsoft.Identity.Client/Internal/Instance/AadAuthority.cs),
it seems that the authority is changed explicitly to use v2.0 and that might be causing me a problem.

Is this issue to be resolved in near future, and is there any workaround in MSAL ?

**Comment by jmprieur** [comment]
Hello @imvigo 
If you want to use the AAD V1 endpoint, you should not use MSAL.Net (which is only about the V2 endpoint)
You need to use [ADAL.Net](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet) which is for the V1 endpoint.
