### ISSUE TITLE
[Bug] MSAL logging enabled results in high latencies.

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#4441]
### Library version used

4.58.0

### .NET version

Net 6

### Scenario

ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

When logging is disabled in the below snapshot, the totalDuration is ~0 ms when the token is acquired from in memory cache. When the logging is disabled, the totalDuration is ~3 ms when the token is acquired from in memory cache. 

```
var builder = ConfidentialClientApplicationBuilder.Create(s_appSettings.ClientId)
    .WithAuthority(s_appSettings.Authority, false)
    .WithLogging(s_logger)
    .WithCertificate(s_appSettings.GetCertificate());

var cca = builder.Build();

AuthenticationResult result;


for (int i = 0; i < 100; i++)
{

    Stopwatch stopWatch = Stopwatch.StartNew();

    result = await cca.AcquireTokenForClient(scopes)
        .ExecuteAsync()
        .ConfigureAwait(false);

    Console.WriteLine($"Elapsed time: {stopWatch.ElapsedMilliseconds} ms");
}
```

### Relevant code snippets
Implementation of logger used:

```
class MyIdentityLogger : IIdentityLogger
{
    public EventLogLevel MinLogLevel { get; }

    public MyIdentityLogger()
    {
        //Retrieve the log level from an environment variable
        var msalEnvLogLevel = Environment.GetEnvironmentVariable("MSAL_LOG_LEVEL");

        if (Enum.TryParse(msalEnvLogLevel, out EventLogLevel msalLogLevel))
        {
            MinLogLevel = msalLogLevel;
        }
        else
        {
            //Recommended default log level
            MinLogLevel = EventLogLevel.Warning;
        }
    }

    public bool IsEnabled(EventLogLevel eventLogLevel)
    {
        return true;
    }

    public void Log(Microsoft.IdentityModel.Abstractions.LogEntry entry)
    {
        Console.WriteLine($"{entry.EventLogLevel} {entry.Message}");
        Console.ResetColor();
    }
}
```

### Expected behavior

The latencies should not vary a lot when MSAL logging is enabled.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Great bug, thanks @neha-bhargava. CC @pmaytak and @trwalke

**Comment by bgavrilMS** [comment]
It's possible that console logging is the issue here.

**Comment by trwalke** [comment]
Can confirm this is a result of the Console logging, I modefied the logger to log to a string builder for the first 50 iterations and then switch to console.log after and the latency appears after the first 50 runs.

@bgavrilMS @neha-bhargava 

![Image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/30090357/ebc342dc-55ee-4487-b20d-60d86cd5b4ea)
