### ISSUE TITLE
[Engineering Task] Have a singleton stopwatch in MSAL to improve performance

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#4442]
### Type of task?

Performance

### Description

Instead of creating a new stop watch everytime a request starts, create a singleton instance.

See [Implementation in MISE](https://identitydivision.visualstudio.com/DevEx/_git/MISE?version=GBgeok/telemetry-exporter&path=/src/Caching/Utility.cs)

**Comment by pmaytak** [comment]
Reopening #4639 should be merged also.
