### ISSUE TITLE
[Bug] AcquireTokenSilent call is failing on Mac because of missing OperatingSystem information 

### ISSUE THREAD

**Issue by grabalon** [AzureAD/microsoft-authentication-library-for-dotnet#4444]
### Library version used

4.54.0.0

### .NET version

.NET Core

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

More information available in this ICM, but essentially the user having this issue is seeing Conditional Access policies block him from calls to AcquireTokenSilent because the Operating System (Mac) is not being sent by MSAL when making the network calls.

https://portal.microsofticm.com/imp/v3/incidents/incident/434595820/summary

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
This is a system browser scenario. I checked some server logs and it seems MSAL doesn't send x-client-os on the second leg of the auth_code flow, i.e. on the token client call. Also, it is sending x-ms-pkeyauth=1 which it really should not on MacOS, as this is Win Only feature.

**Comment by bgavrilMS** [comment]
Issue occurs on public client, but can occur on confidential client too
