### ISSUE TITLE
[Bug] JWT Token improperly signed when running in Linux container

### ISSUE THREAD

**Issue by abhumbla413** [AzureAD/microsoft-authentication-library-for-dotnet#4446]
### Library version used

4.58.0

### .NET version

.NET 7.0

### Scenario

ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I have a simple Web App I am running in a Linux container. When I attempt to acquire a token with my confidentialclientapplication using either a certificate or a secret, I get a JWT token successfully back, but the signature is incredibly short and truncated with three ellipsis. This causes the calls I make using this JWT token to be rejected with a 401. My app is running in a Linux container spun up on my Windows machine through Visual Studio.

What's odd is when I run the exact same code, copied and pasted, with the exact same package and .NET version on my Windows machine or on a Windows container, the issue doesn't happen. I get a proper JWT token that I'm able to use to make successful calls to my service. I have tried playing around with different package versions and I can't seem to solve this. Below I've included a screenshot of my code and the truncated token
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/97633677/0e6f8de6-219e-423f-8c44-0c6d1720d111)

### Relevant code snippets

```csharp
var authorityUrlBase = "https://login.microsoft.com";
var ev2ResourceUrl = "api://5375f9aa-e781-4cee-a49a-b8409f0428e4";
var tenantId = "72f988bf-86f1-41af-91ab-2d7cd011db47";
var app = ConfidentialClientApplicationBuilder
                .Create("<appid>")
                .WithClientSecret("<secret>")
                .WithAuthority($"{authorityUrlBase}/{tenantId}")
                .Build();
string[] scopes = new string[] { $"{ev2ResourceUrl}/.default" };
var tokenBuilder = app.AcquireTokenForClient(scopes).WithSendX5C(true);
var result = await tokenBuilder.ExecuteAsync();
```

### Expected behavior

I expect the jwt token to be signed properly when running on a Linux container

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Solution and workarounds

If another library is known to work on Linux I'd appreciate being redirected

**Comment by bgavrilMS** [comment]
I think that's just the text visualizer in Visual Studio @abhumbla413 . If you do a Console.Writeline or even add a watch and right click on the value and do a "copy value" you will see the entire token. 

We are supporting 100s of services using Linux container
