### ISSUE TITLE
[Bug] Dependency on System.Diagnostics.DiagnosticSource (>= 7.0.2)  in version 4.58.0 missing in .NET 6 Azure Functions

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#4456]
### Discussed in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/discussions/4455

<div type='discussions-op-text'>

<sup>Originally posted by **Ozindar** December  6, 2023</sup>
We've got a .NET 6.0 Azure Function using the Identity.Client. This worked fine with 4.57. With a recently deploy we've upgraded to 4.58 but in Azure this triggers a File not found when it's searching for the DiagnosticsSource version 7 assembly.  
"dotnet publish" does not seem put that dll in the output folder. For the moment I've pinned the Identity.Client to 4.58.  
Is there a viable solution to keep using the latest Identity.Client in combination with a .NET6 Azure Function and what would be the best approach?</div>

**Comment by pmaytak** [comment]
@Ozindar Does this repro if you try .NET 7 or 8 Azure Function? Can DiagnosticSource package be used in Azure Functions in general? For ex, in your app can you target MSAL 4.57 and just add a reference to DiagnosticSource v6.0.0, will that work?

**Comment by pmaytak** [comment]
@Ozindar I wasn't able to repro. I created and published a .NET 6 HTTP Trigger Function with MSAL 4.58.1. Tried with framework-dependent and self-contained deployment modes, portable and win-x86 runtimes, integrated and classic pipelines. App compiled and ran fine. Please provide and repro and more details on any related deployment settings that can help repro.

**Comment by Dolphinsimon** [comment]
We have met the same errors in Azure Functions.
`Inner exception System.IO.FileNotFoundException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:
   at Microsoft.Identity.Client.Platforms.Features.OpenTelemetry.OtelInstrumentation.Microsoft.Identity.Client.TelemetryCore.OpenTelemetry.IOtelInstrumentation.LogFailedMetrics (Microsoft.Identity.Client, Version=4.58.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase+<RunAsync>d__12.MoveNext (Microsoft.Identity.Client, Version=4.58.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor+<ExecuteAsync>d__3.MoveNext (Microsoft.Identity.Client, Version=4.58.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)`

**Comment by bgavrilMS** [comment]
We will investigate. For now stick to MSAL 4.57, as it does not have this dependency.

**Comment by jmprieur** [comment]
It's because Azure functions don't run the application with the references that you build. We have the same issue with IdentityModel
They (Azure functions) need to upgrade to a new version of MSAL.NET

**Comment by Dolphinsimon** [comment]
@pmaytak Yes, Azure Function will clean the output libraries before publishing to the cloud. If the library was already in the function runtime, then the library will be deleted. For this issue, the System.Diagnostics.DiagnosticSource is in the function .NET runtime, but the version is not 7.0.2, the .NET v4 runtime is only support .NET6.0 libraries, the version is 6.x. 
To fix this issue, you can set the library dependency library version to 6.x or Add <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> to a <PropertyGroup> in the function app’s .csproj file.

**Comment by bgavrilMS** [comment]
@GeoK @neha-bhargava - do you know if System.Diagnostics.DiagnosticSource version 6.x would work instead of version 7.x?

**Comment by bgavrilMS** [comment]
Seems to be a known issue with Azure Functions. Looking for workarounds....

**Comment by pmaytak** [comment]
Created two possible fixes for this #4486 (preferred) and #4487. 

To aggregate info about this behavior including some links.

Issue description and workarounds (`_FunctionsSkipCleanOutput` and `FunctionsPreservedDependencies`):
- [_FunctionsSkipCleanOutput and FunctionsPreservedDependencies | Knoxbits Blog (bryanknox.github.io)](https://bryanknox.github.io/2022/07/15/functionsskipcleanoutput-and-functionspreserveddependencies.html)
- [Remove _FunctionsSkipCleanOutput after it is no longer needed · Issue #27 · bryanknox/AzureFunctionsOpenIDConnectAuthSample (github.com)](https://github.com/bryanknox/AzureFunctionsOpenIDConnectAuthSample/issues/27#issuecomment-882117441)
- [Latest version of OpenTelemetry (1.4) is unusable due to dependency on System.Diagnostics.DiagnosticSource 7.0 · Issue #8938 · Azure/azure-functions-host (github.com)](https://github.com/Azure/azure-functions-host/issues/8938#issuecomment-1350189798)
- [Could not load file or assembly System.IdentityModel.Tokens.Jwt, Version=5.6.0.0 · Issue #397 · Azure/azure-functions-vs-build-sdk (github.com)](https://github.com/Azure/azure-functions-vs-build-sdk/issues/397#issuecomment-648809799)
- [Concerns of FunctionsPreservedDependencies · Issue #9161 · Azure/azure-functions-host (github.com)](https://github.com/Azure/azure-functions-host/issues/9161#issuecomment-1476537462)

A list of assemblies that the Azure Functions runtime uses:
[azure-functions-host/tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/ExistingRuntimeAssemblies.txt at dev · Azure/azure-functions-host (github.com)](https://github.com/Azure/azure-functions-host/blob/dev/tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/ExistingRuntimeAssemblies.txt)

.NET 8 Isolated worker model is recommended.
- [.NET on Azure Functions – August 2023 roadmap update - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-august-2023-roadmap-update/ba-p/3910098)
- [GA: Azure Functions supports .NET 8 in the isolated worker model | Azure updates | Microsoft Azure](https://azure.microsoft.com/en-us/updates/ga-azure-functions-supports-net-8-in-the-isolated-worker-model/)
- [Migrate .NET function apps from the in-process model to the isolated worker model | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=net8)

**Comment by pmaytak** [comment]
@ozindar @Dolphinsimon MSAL 4.59.0 was released that references DiagnosticSource 6.0.1.
