### ISSUE TITLE
msafed support in MSAL

### ISSUE THREAD

**Issue by dmcweeney** [AzureAD/microsoft-authentication-library-for-dotnet#447]
Hi,

ADAL supports setting the QS msafed=0 to limit logins to Work or School accounts.
What is the equilivent in MSAL?

Thanks

Donal

**Comment by jmprieur** [comment]
did you try passing this in the additionalParameters parameter of the acquireTokenXX methods?

**Comment by dmcweeney** [comment]
Hi @jmprieur at the moment for ADAL I'm setting it in the RedirectToIdentityProvider... as it is oidc that is controlling the login. If my understanding is correct the acquireTokenXX are too late in the login process.

**Comment by kpanwar** [comment]
There is no such property in Adal. Are you sure you are calling Adal? For MSAL you could pass authority as https://login.microsoftonline..com/organizations

**Comment by kpanwar** [comment]
Then my solution should work. Use organizations instead of common

**Comment by dmcweeney** [comment]
Ok thanks - wont be able to test it until Monday - will let you know then.
Thanks..

**Comment by kpanwar** [comment]
I am closing the issue for now, let me know if it does not work for you.

**Comment by dmcweeney** [comment]
Thank you @kpanwar that worked...
