### ISSUE TITLE
[Bug] Update Managed Identity Exceptions to MSALServiceExceptions

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4483]
### Type of task?

Development

### Description

The ManagedIdentityException didn't play well with our hierarchy of exceptions, since it only derviced from ServiceException. But not from UIRequiredException. The only reason we added this exception was to be able to add extra bit of data about what source leads to this exception.

It also prevents code reuse, since any shared logic between MSI and STS now has to deal with the problem of throwing the correct exception (or catching MsalServiceEx and rethrowing MSIException, which is also complex).

**Comment by bgavrilMS** [comment]
This is not an engineering task.
