### ISSUE TITLE
Unable to use Windows Integrated Auth

### ISSUE THREAD

**Issue by OrionSoftwareSupport** [AzureAD/microsoft-authentication-library-for-dotnet#4484]
### Library version used

4.58.1

### .NET version

.Net 7.0.14

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I've created an Azure App Registration, and turned on the "Allow public client flows" setting, but can't use Windows Integrated Auth. I get this message:

> Error authenticating (UI Required): AADSTS65001: The user or administrator has not consented to use the application with ID '<Client ID>' named 'APPNAME Client - Dev'. Send an interactive authorization request for this user and resource. Trace ID: ba0d9901-db09-4829-a3c2-6b8ad3df8b00 Correlation ID: 74e8ee72-4382-4748-af45-ef3a484335dc Timestamp: 2024-01-02 19:21:46Z

I've already consented for myself in another client, and I had an admin grant consent for the whole tenant. This makes it seem like at least the error message is inaccurate. I've attached a small sample console app project to demonstrate this, but I also get the same behavior with the **active-directory-dotnet-iwa-v2** sample project, I just need to insert `.WithUsername("myemail@mydomain.com")` at PublicAppUsingIntegratedWindowsAuthentication.cs:77. My sample code strips that same approach down to its bare essentials.

[AuthTest.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/13813727/AuthTest.zip)

### Relevant code snippets

```csharp
// NuGet references:

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.58.1" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="8.0.0" />
  </ItemGroup>

// Where it's going wrong (in attached Program.cs):

var scopes = new[] { "access_as_user" };
var user = UserPrincipal.Current;
var result = await app
    .AcquireTokenByIntegratedWindowsAuth(scopes)
    .WithUsername(user.EmailAddress)
    .ExecuteAsync(CancellationToken.None);
```

### Expected behavior

Authentication succeeds and I get an access token back

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by OrionSoftwareSupport** [comment]
I figured it out! I was giving "my_scope_name" as the scope, but I saw when I clicked on the API name in Azure Portal, that the name needs to be in the form "api://<service app ID>/my_scope_name".

**Comment by bgavrilMS** [comment]
Thanks for following up with the solution @OrionSoftwareSupport
