### ISSUE TITLE
[Bug] (maybe) missing roles

### ISSUE THREAD

**Issue by AnthonyGiretti** [AzureAD/microsoft-authentication-library-for-dotnet#4489]
### Library version used

8.0.0

### .NET version

.NET 8

### Scenario

WebSite

### Is this a new or an existing app?

None

### Issue description and reproduction steps

Roles are missing in the JWT. I upraded form the version 3.2.1 and that version brought automatically roles in the JWT. I tried to add myself roles with the code snippet below without success. How to get roles in the version 8.0.0 ?

### Relevant code snippets

```csharp
options.ProviderOptions.DefaultAccessTokenScopes.Add("roles"); // Not working
options.ProviderOptions.AdditionalScopesToConsent.Add("roles"); // Not working
```

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by jmprieur** [comment]
@AnthonyGiretti : the roles claim is directed by the service (Microsoft Entra), not by the app.
See https://learn.microsoft.com/entra/identity-platform/enterprise-app-role-management

**Comment by AnthonyGiretti** [comment]
Thanks.

Can you clarify ? Not sure to understand this. I already setup roles in
Entra Id. With the Msal version 3.2.1 they show up in the JWT, they don’t
anymore in the version 8.0.0.
In Oauth , you are supposed to request the roles by adding « openid roles »
in the GET call for auth.


Anthony Giretti
Blogger, Speaker MVP, MCSD
mobile: +1 514 557 1380
website: https://anthonygiretti.com
email: ***@***.***

**Comment by AnthonyGiretti** [comment]
For now, I have to keep version 3.2.1 which is deprecated to keep roles in the JWT.

**Comment by bgavrilMS** [comment]
Not an SDK issue.
