### ISSUE TITLE
[Engineering Task] Test and update QuicksStarts

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4519]
We need to test and fix our quick starts. Quick Starts are based on samples. 

For .NET these are: 

1. ASP NET Web
2. ASP NET Core Web App
3. Dot Net Core Daemon

... yes these are all powered by ID.Web - even # 3 - but the MSAL team needs to be better understand them

Tracking document [here](https://microsoft.sharepoint.com/:x:/t/appregportal/EZZQEVnkGhJLlLvMHoTol3cBY3k13IReYVet5VtYUJyJlQ?e=kNCAj9&nav=MTVfe0FDQkFBOThELTA3MjgtNDIwNS1COEI5LUY0N0E4Qjg4RTI5MH0&isSPOFile=1&clickparams=eyAiWC1BcHBOYW1lIiA6ICJNaWNyb3NvZnQgT3V0bG9vayIsICJYLUFwcFZlcnNpb24iIDogIjE2LjAuMTY3MTguMjAwMDIiLCAiT1MiIDogIldpbmRvd3MiIH0%3D&CID=E2C32AAD-FB47-407F-BAA7-AA1C3FEDD5FE&web=1&wdLOR=cE3C72A42-5D64-4F4D-88F9-D37A572A9365)

Please note that testing needs to be done in PPE and you'll need an account for it. Reach out to Trishala Pugazhendhi for details.

**Comment by bgavrilMS** [comment]
CC @jmprieur @jennyf19

**Comment by trwalke** [comment]
Moving to next quarter
