### ISSUE TITLE
In Android after Login into the Azure AD account the User.mname is comming "unknown" alway

### ISSUE THREAD

**Issue by NavalKishor** [AzureAD/microsoft-authentication-library-for-dotnet#452]
Our team has recently moved to Azure AD and in android we using MSAL Library to Login and access the other api,

We are able to login to azure login page in android after entering the credential and we are getting the result in the AuthenticationResult object on successful login but com.microsoft.identity.client.User.mName is always coming as "unknown".
why variable  mName of class User  is coming like this.How we can fix this issue.

While debugging i checked the access_token on the jwt.io and there in json structure i found these details
{
...
 "given_name": "Naval",
  "family_name": "Jha",
  "name": "unknown",
  "emails": [
    "Naval.jha@gmail.com"
  ]
...
}
Is there Anyway to access this above json variable like given_name with help of MSAL library

**Comment by kpanwar** [comment]
library does not look into access tokens because they are not meant for the client. it does however look into id token. you should be able to access information about the user by access AuthenticationResult.User

**Comment by NavalKishor** [comment]
@kpanwar thanks for your quick reply. As i said i am able to access the User object and getting data also But the variable mName is having data  as "unknown" always.Even after successfully login. I am getting id_token and access_token here and other data as well as expected except this nName in User instance.

**Comment by kpanwar** [comment]
It is because your id token came back with that information. this is not a library issue from what I gather because library simply parses what it got back. you should update the name of the user in your azure ad directory
