### ISSUE TITLE
Error occured when making a request with the page iterator

### ISSUE THREAD

**Issue by mewanZCW** [AzureAD/microsoft-authentication-library-for-dotnet#4521]
### Library version used

5.38.0

### .NET version

.Net 8.0

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I get this error in my console app when try to get all the file and folders count from a sharepoint list. 
**unauthenticated : Invalid audience Uri '00000003-0000-0000-c000-000000000000'**
This was working fine before without any issues and there wasn't any code or library changes. Then I tried upgrading the libraries, But no change.  I'm using "microsoft.com/devicelogin" to authenticate. I tried to generate the token with Graph explorer and got the same error. Still I can upload document and get sharepoint lists in the site from my code. In reading sharepoint lists method also has the same code with the PageIterator and it works fine.  

In "GetLibraryItemsCount" still I get the first 200 items in the first resqust and get the error in the next request. 
Also I already included those scopes.

MsGraphScope = new string[] { "User.Read", "Sites.Read.All", "Sites.Manage.All", "Sites.ReadWrite.All" };

### Relevant code snippets

```csharp
public async Task<int> GetLibraryItemsCount(string driveId)
{
    List<DriveItem> items = new List<DriveItem>();
    var allItems = await _graphClient.Drives[driveId].Items.GetAsync((requestConfiguration) =>
    {
        requestConfiguration.QueryParameters.Filter = "folder ne null or file ne null";
    });

    var pageIterator = PageIterator<DriveItem, DriveItemCollectionResponse>
            .CreatePageIterator(_graphClient, allItems,
            (i) =>
            {
                items.Add(i);
                return true;
            });

    await pageIterator.IterateAsync();

    return items.Count;
}
```

### Expected behavior

"GetLibraryItemsCount" should return all item count within the list.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

2.32.0

**Comment by trwalke** [comment]
Im guessing you are using MSAL somewhere in your console app, can you provide a snippet?
So you updated from which version of MSAL.NET to which?
Version 2.32.0 refers to Microsoft.Identity.Client.Extensions.Msal right? Have you tried using the latest version of Microsoft.Identity.Client and Microsoft.Identity.Client.Extensions.Msal?

**Comment by mewanZCW** [comment]
> Hi @mewanZCW Im guessing you are using MSAL somewhere in your console app, can you provide a snippet? SYou updated from which version of MSAL.NET to which? Version 2.32.0 refers to Microsoft.Identity.Client.Extensions.Msal right? Have you tried using the latest version of Microsoft.Identity.Client and Microsoft.Identity.Client.Extensions.Msal?

Hi @trwalke 
I raised a another issue in msGraph sdk https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2291 and they confirm that this is a API issue that the allItems.OdataNextLink is not returning the correct url as the host is changed in the url. So I'll close this issue from here. Thanks for getting back.
