### ISSUE TITLE
StrongNamer is abandoned and relies on an obsolete sdk

### ISSUE THREAD

**Issue by SimonCropp** [AzureAD/microsoft-authentication-library-for-dotnet#4527]
building without .NET Core SDK v2.1 installed gives
```
StrongNamer requires at least the .NET Core SDK v2.1 to run with 'dotnet build'
```

**Comment by bgavrilMS** [comment]
The fact that the SDK is obsolete is not impactful. The logic will run with a modern runtime. The SDK is just an interface.

**Comment by SimonCropp** [comment]
well it is a pretty big blocker for anyone wanting to contribute. ie forcing them to install a deprecated sdk

**Comment by bgavrilMS** [comment]
I am able to build MSAL using just: 
<img width="436" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/12273384/0e190964-d4fc-4d94-aaae-65d3a12bd627">

You don't need to build StrongNamer, it is just a dependency. 

I agree we should get rid of it, and MSAL does publish the full strong name key as per Open Source Foundation recommendations - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/build/MSAL.snk, to allow contributors to do work. However, our integration tests rely on `Selenium.WebDriver` which is not signed. 

When I try to run an integration tests without StrongNamer I get: 

Error: System.IO.FileLoadException: Could not load file or assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Do you know a way around it?
