### ISSUE TITLE
PublicClientApplication constructor throws StackOverflow Exception on UWP ARM devices

### ISSUE THREAD

**Issue by duckwaffle** [AzureAD/microsoft-authentication-library-for-dotnet#453]
I'm using the latest Preview nuget version of Microsoft.Identity.Client in a Xamarin.Forms project.

When calling the constructor of PublicClientApplication("client-id") on a Windows 10 phone device I'm encountering what is occasionally seen as a StackOverflowException. However VS does not always break on that exception, and more often than not the app will exit with a "Failed to activate" error in the output.

When I can break on the exception, I'm getting the following call stack:

` Microsoft.Identity.Client.dll!Microsoft.Identity.Client.PlatformInformation.NativeMethods.GetProcessorArchitecture(Microsoft.Identity.Client.Internal.RequestContext requestContext)
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.PlatformInformation.GetProcessorArchitecture()
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.Internal.MsalIdHelper.GetMsalIdParameters()
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.Logger.LogMessage(string logMessage, Microsoft.Identity.Client.Logger.LogLevel logLevel, bool containsPii)
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.PlatformInformation.NativeMethods.GetProcessorArchitecture(Microsoft.Identity.Client.Internal.RequestContext requestContext)
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.PlatformInformation.GetProcessorArchitecture()	
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.Internal.MsalIdHelper.GetMsalIdParameters()	
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.Logger.LogMessage(string logMessage, Microsoft.Identity.Client.Logger.LogLevel logLevel, bool containsPii)
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.ClientApplicationBase.ClientApplicationBase(string clientId, string authority, string redirectUri, bool validateAuthority)
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.PublicClientApplication.PublicClientApplication(string clientId, string authority)
Microsoft.Identity.Client.dll!Microsoft.Identity.Client.PublicClientApplication.PublicClientApplication(string clientId)`

**Comment by jennyf19** [comment]
@duckwaffle - Can you try with the latest version of [MSAL 1.1.4-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/1.1.4-preview)? Let us know if you still see the issue.

**Comment by duckwaffle** [comment]
@jennyf19 oh wow haha. I probably won't do that, I don't really care about UWP ARM devices any more now that the platform is officially dead ;)

**Comment by jennyf19** [comment]
@duckwaffle ha!
