### ISSUE TITLE
New sample for Asp.Net Core 2

### ISSUE THREAD

**Issue by dmcweeney** [AzureAD/microsoft-authentication-library-for-dotnet#457]
Hi,

Can we get some updated samples please that show msal/azure ad/azure ad b2c authentication working on Asp.Net Core 2.0?

Thanks

Donal

**Comment by jmprieur** [comment]
Hello @dmcweeney. 
We are currently updating our .NET Core samples to .NET Core 2.0
For instance, I've updated https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/tree/aspnet_core_2_0 yesterday 

**Note** that for the moment the 2.0 implementation is in a separate branch (as most customers have not necessarily updated their tooling yet)

There are also pull requests for the dotnetcore-daemon-certificate-credential sample (https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential/pull/3#issuecomment-323186192) and a B2C sample: https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi/pull/6#issuecomment-323186147
