### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by aisakk** [AzureAD/microsoft-authentication-library-for-dotnet#4576]
_Make sure that your question or issue is not already covered in [MSAL docs](https://learn.microsoft.com/en-us/entra/msal/dotnet/) or [samples](https://learn.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code?tabs=apptype)._

**Documentation related to component** 

**Please check those that apply**

- [ ] typo - [x ] documentation doesn't exist - [ x] documentation needs clarification - [ ] error(s) in example - [ x] needs example

**Description of the issue** 

Good, I'm looking at Microsoft documentation about jwt and I only noticed that there is explanation about dotnet users-jwt but about JwtSecurityToken they don't explain it in detail with examples of how to use it, do you know where I can get a detailed explanation about JwtSecurityToken?

**Comment by bgavrilMS** [comment]
What are you trying to do @aisakk ? Are you building an app that needs to access a protected API that Microsoft hosts (like MIcrosoft Graph, Azure KeyVault etc.)? And what kind of app is this - web app / web api / desktop / mobile ?

Or are you trying to create your own Web API?

**Comment by aisakk** [comment]
Good morning @bgavrilMS I am trying to create a minimals web API with .net and I want to implement JWT, I am guided by the microsoft documentation but I get dotnet users-jwt is only for testing and I would like to implement JwtSecurity from the package System.IdentityModel.Tokens.Jwt or Microsoft.IdentityModel.Tokens.Jwt but when I go to the documentation there is no example of how to implement it, I would like to know if they are on it? or if there is an example of how to do it?

**Comment by kylemar** [comment]
I would suggest using https://learn.microsoft.com/en-us/entra/msal/dotnet/microsoft-identity-web/ which will handle the JWT for you instead of doing the lower level JWT handling yourself.

**Comment by aisakk** [comment]
I could see the links you attached but it does not tell me about how to apply JWT but another type of authentication, I would like to implement JWT the only reference I see is this https://learn.microsoft.com/es-es/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-8.0&tabs=linux but I would like to know if there is another reference on how to create the jwt with the [System.IdentityModel.Tokens.Jwt](https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/) package or if there is a way to explain and cover everything related to the jwt topic.

**Comment by kylemar** [comment]
What is your scenario? MSAL acquires tokens from Entra ID. It does not generally create tokens on its only (except for Confidential Clients using certificate credentials). An app that uses MSAL would not need to create JWT tokens. On the API side, APIs consume and validate tokens, they do not create them.

**Comment by aisakk** [comment]
@kylemar what I need is to create a token from scratch, I know that the api only consumes, but I need to create the token with the documentation that I pass but the documentation does not specify in detail a clear example of how to use System.IdentityModels.Tokens on JWT of how to generate it only gives you the CLI "dotnet users-jwt" and that in production does not work because you must create the token in a login to give the user to navigate within the specified paths.

**Comment by aisakk** [comment]
Thank God I was able to create a JWT token thanks to a documentation I got on google, "It would be nice if you could put an example in the Microsfoft documentation of how to create a jwt token without dotnet users-jwt", @kylemar  @bgavrilMS

**Comment by bgavrilMS** [comment]
> @kylemar what I need is to create a token from scratch, I know that the api only consumes, but I need to create the token with the documentation that I pass but the documentation does not specify in detail a clear example of how to use System.IdentityModels.Tokens on JWT of how to generate it only gives you the CLI "dotnet users-jwt" and that in production does not work because you must create the token in a login to give the user to navigate within the specified paths.

Apps / SDK don't create tokens, Identity Providers (AAD, Okta, ADFS etc.) create tokens based on user entering their credentials, passing MFA etc. An SDK like System.IdentityModel.* can parse and validate a token issued by an Identity Provider. An SDK like Microsoft.Identity.Client can help with token acquisition by making HTTP calls to the Identity Provider.

If you need help with token acquisition, please let us knop the type of app you are trying to build. Is it a desktop app (e.g. WinForms, Command Line app) or a web app?
