### ISSUE TITLE
Only include dependencies not provided by the framework

### ISSUE THREAD

**Issue by thompson-tomo** [AzureAD/microsoft-authentication-library-for-dotnet#4605]
### Summary
The nuget packages should only have dependencies on libraries which are not provided by the framework

### Proposal
The System.Io.FileSystem.AccessControl is conditionally added based on target framework so that it is not included for the newer frameworks

**Comment by bgavrilMS** [comment]
Would you like to propose a fix for this @thompson-tomo ? Is there an impact for this? (e.g. build warnings?)

**Comment by thompson-tomo** [comment]
PR submitted as #4613

**Comment by neha-bhargava** [comment]
Fixed in [MSAL.Net 4.60.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.60.0)
