### ISSUE TITLE
[Feature Request] Provide the source code for Microsoft.Identity.Client.NativeInterop or a guide on how to implement Sign In Silently in native code

### ISSUE THREAD

**Issue by mcgeeky** [AzureAD/microsoft-authentication-library-for-dotnet#4607]
### MSAL client type

Public

### Problem Statement

Whilst the Microsoft.Identity.Client and Microsoft.Identity.Client.NativeInterop libraries provide for a broad range of authentication scenarios, in my case, I require only a very specific scenario for silent single sign in with Entra ID (Core.SignInSilentlyAsync). For this one method, if using Microsoft's preferred approach, I should include Microsoft.Identity.Client and Microsoft.Identity.Client.NativeInterop in my app, amounting to several MBs of compiled code and introducing numerous dependencies I don't want nor need in my app.

A problem I face with the NativeInterop library is that if there is any bug within the NativeInterop code, I, as a developer, have no means to debug that issue and must rely on Microsoft to triage and identify a fix - Microsoft's timescales may not align with my app and my customers.

If I can implement my own SignInSilentlyAsync then I alone am responsible for fixing any issues rather than currently dealing with a "black box" that makes me wary of using this library for my customers.

### Proposed solution

Microsoft to release either the source code for Microsoft.Identity.Client.NativeInterop, or a developer guide, on how to implement our own Core.SignInSilentlyAsync.

**Comment by bgavrilMS** [comment]
We do not have capacity to document or to help with this. Microsoft.Identity.Client.NativeInterop has a 0.x version precisely to discourage direct use, as per SemVer. We do not guarantee backwards compatibility at this level. 

Recommendation is to use MSAL. Not sure what dependencies are preventing you, we keep MSAL dependencies at a minimum.

Otherwise, you can always put a few breakpoints in RuntimeBroker.cs to figure out how MSAL uses `Microsoft.Identity.Client.NativeInterop`.

**Comment by mcgeeky** [comment]
It would be useful to know what the NativeInterop library is doing in SignInSilently. I can view the source of the other MSAL libraries but not the NativeInterop.

For example, I have had some customers report an error: "The requested security package does not exist". This is since integrating NativeInterop in to my app. This error never occurred in my app before. The error is thrown by System.Net.SSPIWrapper.AcquireCredentialsHandle from .Net for package "Microsoft Unified Security Protocol Provider" when sending a web request to SharePoint Online immediately after acquiring a token from NativeInterop.

Could NativeInterop be holding on to a handle that it has not released, causing this package error? Its difficult to diagnose without the source for NativeInterop.

**Comment by mcgeeky** [comment]
> Not sure what dependencies are preventing you, we keep MSAL dependencies at a minimum.

There are no dependencies preventing me; but I want to keep dependencies and footprint to a minimum. With the microsoft.identity.client, microsoft.identity.client.broker, microsoft.identity.client.nativeinterop, microsoft.identitymodel.abstractions and system.diagnostics.diagnosticsource that's about 4MB of compiled code when my only interest is in SignInSilently.

> Otherwise, you can always put a few breakpoints in RuntimeBroker.cs to figure out how MSAL uses `Microsoft.Identity.Client.NativeInterop`.

Thanks, I will look in to it.

**Comment by mlovisek** [comment]
I've similar problem to mcgeeky. Would like to see how the authentication request is being constructed within "SignInSilently".
Trying to acquire token by using MSAL for my customs cope "api://{myclient ID}/my-custom-scope". Interactive way works well. However with using WAM (Broker) I am getting error (below) which does not make sense to me as interactive sign-in works w/o issue for the same client ID and scope.
In MSAL everything looks good but I am lost when it hits NativeInterop (SignInSilentlyAsync).

"AADSTS90009: Application '{myclient ID}' is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier"

Thanks for any advice.

**Comment by liszto** [comment]
@bgavrilMS is it possible to provide at least the release note for each new revision of this `Microsoft.Identity.Client.NativeInterop` package to let developers know what changed inside ?
