### ISSUE TITLE
PublicClientApplication ctor on UWP mobile

### ISSUE THREAD

**Issue by escape-llc** [AzureAD/microsoft-authentication-library-for-dotnet#461]
I have my application running "perfectly" on UWP on Windows 10 desktop.  I'm using this package with MS Graph package.

When i take same application and run it on any Windows 10 mobile emulator (10.0.14393.0), it goes into the constructor of PublicClientApplication, and never returns, and the app eventually abnormally terminates with Access Violation error, or hangs indefinitely.  I tried moving where i call this ctor, to no avail, same Access Violation hard termination.

I do not get a stack trace nor can i get the debugger to break on the error.

I'm using latest packages and latest VS2017.  All the projects in the solution are all built as Universal Windows.  Not using Xamarin just straight XAML.  I have mobile extensions for the UWP in references list.  Is anything else required to get it to run on mobile?

Follow-up:  I attached logger handler, and nothing came out on mobile emulator, but lots came out on desktop (because normal operation).

**Comment by escape-llc** [comment]
Some follow-up information:  build in Release mode, and everything works on mobile emulator!

Can anyone provide any information why it would fail in Debug and work in Release?  I know there is some native compilation involved in Release, but why would it be like that?

**Comment by escape-llc** [comment]
More follow-up information i installed newer emulator 15063 and everything works in debug mode.  Is there a minimum platform requirement in this package?

**Comment by jmprieur** [comment]
Normally, not, but there might have been issues with tooling (the emulator)
Closing this one now, since that worked for you
