### ISSUE TITLE
[Bug] Improve browser login page

### ISSUE THREAD

**Issue by NextIshwar** [AzureAD/microsoft-authentication-library-for-dotnet#4618]
### Library version used

4.59.0

### .NET version

8.0.101

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

While using the library, I noticed a minor inconvenience in the login flow. Specifically, during the email entry stage, the keyboard presents a 'Go' button, which effectively redirects the user to the password entry page. However, upon reaching the password entry page, the 'Next' button on the keyboard seems to lack any associated action, leading to confusion.

### Relevant code snippets

```csharp
await IdentityClient.AcquireTokenInteractive(_configService.Scopes)
                                            .WithPrompt(Prompt.ForceLogin)
                                            .WithParentActivityOrWindow(ParentWindow)
                                            .WithUseEmbeddedWebView(false)
                                            .ExecuteAsync();
```

### Expected behavior

It is suggested that the 'Next' button on the password entry page should perform the sign-in action, providing a more intuitive and seamless user experience. This adjustment would enhance the overall usability of the MSAL library and contribute to a smoother authentication process for users.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.59.0

**Comment by pmaytak** [comment]
MSAL doesn't control what the login window shows; it just pops up the browser window to show whatever the Microsoft Entra ID /  service sends back. You can post the feedback in [Azure forums](https://feedback.azure.com/d365community/forum/22920db1-ad25-ec11-b6e6-000d3a4f0789).
