### ISSUE TITLE
System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

### ISSUE THREAD

**Issue by hig-dev** [AzureAD/microsoft-authentication-library-for-dotnet#462]
Using this in version 1.1.0-preview on Xamarin.Android with Xamarin.Android.Support.CustomTabs 25.4.0.2 gives the following exception when trying to log in:

System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

This is the same issue: https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/11

**Comment by kpanwar** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/443

**Comment by msarun006** [comment]
i have  also the  same problem
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method **'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.**
