### ISSUE TITLE
[Bug] Using NET8-based Blazor WASM SPA with MSAL returns access_token with incorrect `aud` claim (MS Graph instead of API client_id)

### ISSUE THREAD

**Issue by mdddev** [AzureAD/microsoft-authentication-library-for-dotnet#4625]
### Library version used

8.0.1

### .NET version

```xml
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="8.0.1" />
  </ItemGroup>

</Project>

```

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

The below repo is based off this guidance

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-accounts?view=aspnetcore-8.0

* clone [Repro repo here](https://github.com/mdddev/blazor-wasm-entra-ext-id)
* add and configure app registrations
* run blazor app
* open /user page

The `aud` claim is expected to be the client_id of the web API project I registered in the customer tenant of Entra External Identities.
Instead the id for MS Graph is shown. Even when - in User.razor - I explicitly request an access_token via

```chsarp
        var opt = new AccessTokenRequestOptions() { Scopes = ["api://<CLIENT_ID_WEB_API>/access_as_user"] };
        var accessTokenResult = await AuthorizationService.RequestAccessToken(opt);
```

This is ignored.

### Expected behavior

The client_id of the web api projeect is shown in the `aud` claim of the acces_token.

### Identity provider

Microsoft Entra External ID

**Comment by pmaytak** [comment]
@mdddev Microsoft.Authentication.WebAssembly.Msal uses MSAL JavaScript. Create an issue in [MSAL JS repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) or maybe [aspnetcore/Blazor repo](https://github.com/dotnet/aspnetcore/issues).
