### ISSUE TITLE
Add CAE integration tests

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#4626]
Need to add end-to-end integration tests for Continuous Access Evaluation. Ideally these would be automated with lab but at first, manual would be okay.

Tasks:
- [ ] Register a new test app for testing CAE in the lab tenant (separate one so that disabling it doesn't affect other tests).
- [ ] Create a new test user for testing CAE in the lab tenant (separate one so that revoking the session doesn't affect other tests).
- [ ] Create a lab API endpoint to revoke a user session.
- [ ] Create a lab API endpoint to disable/enable the app's service principal. 
- [ ] Update the Lab code with new APIs 
- [ ] Release updated package to NuGet, since that's how Id Web consumes it.
- [x] Write a test for user flow.
- [x] Write a test for an app flow.

**Comment by bgavrilMS** [comment]
I think the CAE integration tests are best placed in ID.Web, not in MSAL, because Id.Web actually handles the challenges.
