### ISSUE TITLE
[Bug] Stop using PKCS1 padding in POP+SHR in-memory crypto provider

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4633]
### Library version used

4.59

### .NET version

All

### Scenario

ConfidentialClient - web site (AcquireTokenByAuthCode), ConfidentialClient - web api (AcquireTokenOnBehalfOf), ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

None

### Issue description and reproduction steps

Compliance bug - CodeQL has flagged the usage of a deprecated padding scheme. See https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2827295?src=WorkItemMention&src-action=artifact_link for details

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by neha-bhargava** [comment]
Fixed in [MSAL.Net 4.60.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.60.0)
