### ISSUE TITLE
[Bug] On Android - Shared Device Mode using broker getAccounts call returns: "cannot perform getAccounts on a shared device."

### ISSUE THREAD

**Issue by zacutti-basf** [AzureAD/microsoft-authentication-library-for-dotnet#4635]
### Library version used

4.59.0

### .NET version

MAUI 6 / 8

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

When using broker (intune company portal) the GetAccountsAsync methods returns 0 accounts.
After debugging it, I can see that the broker app returns:
broker_result_v2:
```
{
  "cached_at": 0,
  "broker_error_code": "invalid_request",
  "broker_error_message": "cannot perform getAccounts on a shared device.",
  "expires_on": 0,
  "ext_expires_on": 0,
  "http_response_code": 0,
  "serviced_from_cache": false,
  "success": false
}
```
Steps:
1 - Set a device to Shared Device Mode.
2 - Enable broker .WithBroker(true)
3 - Call the PublicClientApplication.GetAccountsAsync() method

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Indeed, Shared Device Mode / Front Line Worker scenario does not work with MSAL .NET 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2910

**Comment by zacutti-basf** [comment]
wow .. not even MS is using MAUI, definitively doesn't seems to be a serious option.
thanks a lot @bgavrilMS
