### ISSUE TITLE
Xamarin: Have Option to Hide Url

### ISSUE THREAD

**Issue by cvanbeek13** [AzureAD/microsoft-authentication-library-for-dotnet#465]
It would be nice to have the option on iOS and Android to not show the URLs in the sign-in and token acquisition Webview.  Ideally, there would just be an activity indicator so users could see that it was working but wouldn't see all the individual redirects. 

Just a suggestion for an improvement.

**Comment by kpanwar** [comment]
there is no way to hide system webview address bar. this is by OS design
