### ISSUE TITLE
MSAL implementation of cache is broken

### ISSUE THREAD

**Issue by dgxhubbard** [AzureAD/microsoft-authentication-library-for-dotnet#4651]
### Library version used

4.59.0

### .NET version

.net 7

### Scenario

ConfidentialClient - web api (AcquireTokenOnBehalfOf)

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

Below is our copy AzureTokenCacheHelper. We have a production app where we send a test email using microsoft graph. On one system we have seen the application lockup (the app becomes non-repsonsive) and does nothing when we try send the test email, on every other system send test email is working.

Our copy of AzureTokenCacheHelper creates the file ".msalcache.bin3" where the tokens are cached in the user local app data. On this system in explorer if you enter "%localappdata" this resolves to the root directory of c drive, and on every other system this goes to users local appdata. The users system that locks up does not have the file ".msalcache.bin3" anywhere on the drive and as stated they do not have a local directory in Users. We are stuck trying to figure why %localappdata% does not work in explorer or if this has anything to do with the issue. On other systems the cache file ".msalcache.bin3" is not created. We have also found that if ".msalcache.bin3" is deleted on systems that send test email is working the send still works and a new login is not required. Is the cache stored anywhere else is the system or does azure cache the token.  I would think if our cache file ".msalcache.bin3" is deleted a new login would be forced. How do we resolve this issue?

Our application is registered as public on azure.

```
using System;

using System.IO;
using System.Security.Cryptography;



using Microsoft.Identity.Client;


namespace MyApp
{
    public static class AzureTokenCacheHelper
    {
        static AzureTokenCacheHelper ()
        {
            try
            {
                string folder = Environment.GetFolderPath ( Environment.SpecialFolder.ApplicationData );

                // Combine the base folder with your specific folder....
                string localFolder = Path.Combine ( folder, "Local" );

                // CreateDirectory will check if every folder in path exists and, if not, create them.
                // If all folders exist then CreateDirectory will do nothing.
                Directory.CreateDirectory ( localFolder );

                var localAppData = Environment.GetFolderPath ( Environment.SpecialFolder.LocalApplicationData );

                // For packaged desktop apps (MSIX packages, also called desktop bridge) the executing assembly folder is read-only. 
                // In that case we need to use Windows.Storage.ApplicationData.Current.LocalCacheFolder.Path + "\msalcache.bin" 
                // which is a per-app read/write folder for packaged apps.
                // See https://docs.microsoft.com/windows/msix/desktop/desktop-to-uwp-behind-the-scenes


                CacheFilePath = Path.Combine ( localAppData, ".msalcache.bin3" );
            }
            catch ( System.InvalidOperationException )
            {
                // Fall back for an unpackaged desktop app
                CacheFilePath = System.Reflection.Assembly.GetExecutingAssembly ().Location + ".msalcache.bin3";
            }
        }

        /// <summary>
        /// Path to the token cache
        /// </summary>
        public static string CacheFilePath { get; private set; }

        private static readonly object FileLock = new object ();

        public static void BeforeAccessNotification ( TokenCacheNotificationArgs args )
        {
            lock ( FileLock )
            {
                args.TokenCache.DeserializeMsalV3 ( File.Exists ( CacheFilePath )
                        ? ProtectedData.Unprotect ( File.ReadAllBytes ( CacheFilePath ),
                                                 null,
                                                 DataProtectionScope.CurrentUser )
                        : null );
            }
        }

        public static void AfterAccessNotification ( TokenCacheNotificationArgs args )
        {
            // if the access operation resulted in a cache update
            if ( args.HasStateChanged )
            {
                lock ( FileLock )
                {
                    // reflect changes in the persistent store
                    File.WriteAllBytes ( CacheFilePath,
                                       ProtectedData.Protect ( args.TokenCache.SerializeMsalV3 (),
                                                             null,
                                                             DataProtectionScope.CurrentUser )
                                      );
                }
            }
        }

        public static void EnableSerialization ( ITokenCache tokenCache )
        {
            tokenCache.SetBeforeAccess ( BeforeAccessNotification );
            tokenCache.SetAfterAccess ( AfterAccessNotification );
        }
    }
}

```

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.59.0

**Comment by dgxhubbard** [comment]
I forgot to add the code to acquire the access token

```
                // Set up the authentication context and acquire a token
                ConfidentialClientApp = ConfidentialClientApplicationBuilder.Create ( AzureAdConstants.ClientId )
                    .WithAuthority ( AzureAdConstants.AppAuthority )
                    .WithClientSecret ( AzureAdConstants.ClientSecret )
                    .Build ();

                if ( ConfidentialClientApp == null )
                    throw new NullReferenceException ( "FAILED to create client app builder" );

                AzureTokenCacheHelper.EnableSerialization ( ConfidentialClientApp.UserTokenCache );


                AuthenticationResult =
                    await ConfidentialClientApp
                    .AcquireTokenForClient ( Scopes )
                    .ExecuteAsync ();

            if ( AuthenticationResult != null )
            {
                AccessToken = AuthenticationResult.AccessToken;

            }

```

**Comment by bgavrilMS** [comment]
We have a caching solution for desktop apps, which uses files and there we use `AppLocalData`

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client.Extensions.Msal/Shared/SharedUtilities.cs#L124

**Comment by bgavrilMS** [comment]
There is no "login" i.e. user interaction here, this is app to app communication - `AcquireTokenForClient` - you are getting a token for the app (client) not for the user.

But please note that you should NOT deploy such an app to end user computers. Desktop and mobile apps cannot safely store secrets.  As an attacker I can scan the memory of your app and I'll steal your secret. 

https://learn.microsoft.com/en-us/entra/identity-platform/msal-client-applications

**Comment by dgxhubbard** [comment]
@bgavrilMS We are using ConfidentialClientApplicationBuilder, which I thought is recommended, not PublicClientApplicationBuilder. Are you talking about decompiling and stealing the client secret or something else.

**Comment by dgxhubbard** [comment]
@bgavrilMS when we delete the cache bin3 shouldnt that remove token? I misspoke about login we use PublicClientApplicationBuilder to connect to azure dbs that is the login part.

**Comment by dgxhubbard** [comment]
@bgavrilMS I am not sure what line 124 of SharedUtilities does other than get user local app data, which can be gotten by Environment. Is there a cache in the code or was your point the directory.

**Comment by dgxhubbard** [comment]
@bgavrilMS As for caching in memory the app is started and stopped by users constantly so not sure how in memory would help. In the examples I have seen the token cache helper is used in most. Is there another cache that msal sets up besides the one we are using.

**Comment by dgxhubbard** [comment]
@bgavrilMS the examples I have seen that send email use the ClientConfidentialApplicationBuilder mostly. Should we not be using it?

**Comment by nbevans** [comment]
If your app is deployed to end user machines then almost without further question it should not be using the confidential client. It should use public client.

Confidential client is for when you deploy a server side component in your own managed and secure infrastructure. The "ClientSecret" key (which confidential client requires) should never leave your infrastructure. If it ends up baked into your app which is then installed onto end users devuces then the entire security of the App Registration is compromised and you'd need to revoke that ClientSecret.

**Comment by bgavrilMS** [comment]
> @bgavrilMS the examples I have seen that send email use the ClientConfidentialApplicationBuilder mostly. Should we not be using it?

With regards to the location of the cache, if %appdata% is problematic, you can choose anything else you'd like. Afaik the cache is not roamable (DPAPI doesn't decrypt on other machines by default). You can set it the same dir as your executable.

As @nbevans pointed out, apps sitting on user's machines / devices generally can't be secured. An attacker can get a hold of you app, run a memory scan on it and retrieve the secret. 

The security posture is a bit better with certificates. In an organization, the admin can deploy a certificate and secure it. MSAL will have access to the "Sign" operation of the certificate but not to the actual private key. 

Have a look at: https://learn.microsoft.com/en-us/entra/identity/authentication/concept-certificate-based-authentication - note how this is "getting a token for a user" (delegated scopes) and not for an app (this is what you do). App tokens are too powerful.
