### ISSUE TITLE
[Bug] MSAL does not properly overwrite access tokens in cache when OBO is performed for the same assertion but with 2 different keys

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#4673]
### Library version used

4.59.0

### .NET version

8.0

### Scenario

ConfidentialClient - web api (AcquireTokenOnBehalfOf)

### Is this a new or an existing app?

None

### Issue description and reproduction steps

When initializing a Long running OBO app for the second time using the same user assertion but with a different OBO cache key, MSAL will not export the second AT from the cache when using `SerializeMSALV3()`. This results in the later call to `AcquireTokenInLongRunningObo()` to fail with an error indicating that no tokens are available in the cache for the second key. 

This is because when MSAL Exports the serialized cache, the OBO cache key is not present in the `MsalAccessTokenCacheKey`
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/add5f1cd97682a5b3d5f5122c0e3d52217b248e6/src/client/Microsoft.Identity.Client/Cache/TokenCacheJsonSerializer.cs#L30

Thus, only the first AT/RT on the top of the cache list will be serialized.

This can happen as a result of a customer loosing the initial cache key used to initialize the user and is trying to reintitialize the user with a new OBO key. This will cause them to be in a state where they can no longer initialize that user as long as the initial token with the lost key is present in the cache.

### Relevant code snippets

```csharp
reproduction using the test LongRunningAndNormalObo_WithDifferentKeys_TestAsync


public async Task LongRunningAndNormalObo_WithDifferentKeys_TestAsync()
        {
            string userTokenCache = string.Empty;

            var user1 = (await LabUserHelper.GetSpecificUserAsync("idlab1@msidlab4.onmicrosoft.com").ConfigureAwait(false)).User;
            var pca = PublicClientApplicationBuilder
                .Create(PublicClientID)
                .WithAuthority(AadAuthorityAudience.AzureAdMultipleOrgs)
                .Build();

            var userAuthResult = await pca
                .AcquireTokenByUsernamePassword(s_oboServiceScope, user1.Upn, user1.GetOrFetchPassword())
                .ExecuteAsync(CancellationToken.None)
                .ConfigureAwait(false);

            var cca = BuildCCA(userAuthResult.TenantId);

            cca.UserTokenCache.SetAfterAccess(args =>
            {
                if (args.HasStateChanged)
                {
                    userTokenCache = System.Text.Encoding.Default.GetString(args.TokenCache.SerializeMsalV3());
                }
            });

            string oboCacheKey = "obo-cache-key";
            string oboCacheKey2 = "obo-cache-key2";
            UserAssertion userAssertion = new UserAssertion(userAuthResult.AccessToken);

            cca.UserTokenCache.SetBeforeAccess(args =>
            {
                args.TokenCache.DeserializeMsalV3(System.Text.Encoding.Default.GetBytes(userTokenCache), true);
            });

            var result = await cca.InitiateLongRunningProcessInWebApi(s_scopes, userAuthResult.AccessToken, ref oboCacheKey)
                .ExecuteAsync().ConfigureAwait(false);

            Console.WriteLine(userTokenCache);

            var result2 = await cca.InitiateLongRunningProcessInWebApi(s_scopes, userAuthResult.AccessToken, ref oboCacheKey2)
                .ExecuteAsync().ConfigureAwait(false);

            Console.WriteLine(userTokenCache);

            result = await cca.AcquireTokenInLongRunningProcess(s_scopes, oboCacheKey2).ExecuteAsync().ConfigureAwait(false);

            Console.WriteLine(userTokenCache);
        }
```

### Expected behavior

MSAL should overwrite the original token with the new token. Or at least export them both so they are both available.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Solution and workarounds
At the moment, customers are able to drop the cache during cache serialization to get out of this state. 

Suggestion to avoid issue: Microsoft.Identity.Web.TokenCache or serialize cache as dictionary with `SuggestedCacheKey`

**Comment by bgavrilMS** [comment]
Does the partner have a workaround for this @trwalke ?

**Comment by bgavrilMS** [comment]
Also, can you post what the user impact is? It's not clear (too technical)

**Comment by trwalke** [comment]
> Does the partner have a workaround for this @trwalke ?

Yes, they need to drop the cache to get out of this state when MSAL calls token cache callbacks

**Comment by pmaytak** [comment]
This happens with a flat cache serialization as shown in the repro. The cache serializer does flatten the internal cache based on the item cache key. If you replace the `userTokenCache` in the repro with a dictionary and use `args.SuggestedCacheKey`, the code will work.

Normal OBO runs into the same behavior. (Update the repro - set cache keys to null, get a second user token and use it in the second call to Initiate.

The intention is that the OBO cache key replaces the user assertion when used as a cache key. So two different cache keys - meaning two different sessions (expecting different assertions).

So a suggested way when serializing yourself is to use a dictionary for serializing the cache or Microsoft.Identity.Web.TokenCache.

**Comment by bgavrilMS** [comment]
@pmaytak - could you please detail the suggestion? How can the user fix this / migrate the cache?

**Comment by pmaytak** [comment]
The easiest mitigation is probably to just replace the cache implementation with a partitioned one (clearing the old one). Otherwise, the MSAL's cache event handlers could be updated to first read from the new partitioned cache, then in the old flat cache; the writes would be only to the partitioned cache.

**Comment by bgavrilMS** [comment]
I agree. @trwalke, can we close on this?
