### ISSUE TITLE
[Bug] MsalCacheHelper.RegisterCache not working as expected after version upgrade

### ISSUE THREAD

**Issue by PavanKumarCoder** [AzureAD/microsoft-authentication-library-for-dotnet#4681]
### Library version used

4.58.1

### .NET version

.Net Framework 4.8

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

IPublicClientApplication.AcquireTokenInteractive is not creating the cache file specified using the MsalCacheHelper.RegisterCache.

This issue started appearing ever since we upgraded the Microsoft.Identity.Client.Extensions.Msal library from 2.31.0 to 4.58.1.
Microsoft.Identity.Client was also upgraded from 4.54.1 to 4.58.1.

Prior the upgrades, the cache file was getting created and everything was fine. However, after upgrade the cache file is not getting created and we are getting continuous login popups.

IPublicClientApplication.AcquireTokenSilent is continuously failing because there is no cache file.

### Expected behavior

IPublicClientApplication.AcquireTokenSilent shouldn't fail after initial authentication when we specify the cache file and cache directory.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.54.1

**Comment by bgavrilMS** [comment]
I cannot repro this @PavanKumarCoder - I tried on Windows with

`var cache = await MsalCacheHelper.CreateAsync(new StorageCreationPropertiesBuilder("cache.bin", MsalCacheHelper.UserRootDirectory).Build())`

Where do you put the cache file?

**Comment by PavanKumarCoder** [comment]
In this directory:

C:\Users\****\AppData\Local\***\

**Comment by localden** [comment]
@PavanKumarCoder can you please share your code snippet where you are configuring the cache?

**Comment by localden** [comment]
Closing as there is no input from author. @PavanKumarCoder - feel free to ping us if the issue persists with the latest version of the library.

**Comment by TovTyvold** [comment]
@localden I am experiencing the same as what is mentioned in this issue. Should I create a new issue?

**Comment by localden** [comment]
@TovTyvold - likely, but I am no longer on this team, and it seems like the recommended path has changed. See [the blog post](https://devblogs.microsoft.com/blog/securing-developer-tools-with-authentication-brokers#feedback-and-support) for latest recommendation.
