### ISSUE TITLE
AcquireTokenInteractive only offers Password Sign-in

### ISSUE THREAD

**Issue by psychosys** [AzureAD/microsoft-authentication-library-for-dotnet#4687]
Hi Guys

Microsoft.Identity.Client to create a program to sign-in to Microsoft Account, 
I am using **AcquireTokenInteractive** the login dialog only gives me Password Sign-in , I have Yubikey and other factor set in my account to login with but AcquireTokenInteractive only offers Password , basically I want to make it passwordless, I want to login Once and rest of time it will be passwordless

I am using WebView2 but it still doesn't give me YubiKey signin option

Regular Browser Gives me this option but I was unable to get such thing with **Microsoft.Identity.Client**
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/58204209/f0504ae8-a70b-4092-a2d0-b45a3b454530)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/58204209/1a88bc8c-369d-416c-be38-3596e5265411)

Thanks

**Comment by bgavrilMS** [comment]
I'm not sure that's WebView2. We disabled WebView2 support with Entra ID auth, as there were SSO problems with it and we don't want to invest in browser based auth. 

Can you please try to use WAM instead? https://aka.ms/msal-net-wam

System browser will also work.

**Comment by psychosys** [comment]
> I'm not sure that's WebView2. We disabled WebView2 support with Entra ID auth, as there were SSO problems with it and we don't want to invest in browser based auth.
> 
> Can you please try to use WAM instead? https://aka.ms/msal-net-wam
> 
> System browser will also work.

Thank you very much, I was able to fix it 

I have a question and nobody was able to answer me

I would like to login with FIDO and also receive **Push with Microsoft Authentication**, Push only works with Password sign-in not FIDO, do you know How can I enforce MFA through Push ?

**Comment by bgavrilMS** [comment]
@psychosys - I do not know, these aspects are not handled by the SDK. 

My uninformed opinion - FIDO is a form of MFA, so AAD doesn't require another form of MFA (Authenticator). https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-howitworks#available-verification-methods

I do not know if there is an option to force 2 MFA methods (e.g. FIDO and Authenticator).

**Comment by localden** [comment]
Closing this issue as the MSAL part is resolved.
