### ISSUE TITLE
[Bug] can't use WithEmbeddedWebViewOptions on net8 android

### ISSUE THREAD

**Issue by softlion** [AzureAD/microsoft-authentication-library-for-dotnet#4691]
### Library version used

4.60.0

### .NET version

net8-android

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

When adding the line `WithEmbeddedWebViewOptions` that triggers the throw line 60 of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/ApiConfig/EmbeddedWebViewOptions.cs

If I remove the line `WithEmbeddedWebViewOptions()`, it is working as expected.

```
        var query = adClient.AcquireTokenInteractive(scopes)
            .WithUseEmbeddedWebView(true)
            .WithEmbeddedWebViewOptions(new () { Title = "Title" }) //crash
            .WithPrompt(Prompt.ForceLogin);
```

I updated a xamarin app to maui. Now when the embedded login view is displayed, it has a title. On xamarin it did not have a title. So I tried to change the default title, and hit the crash.

It looks like the #if condition in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/ApiConfig/EmbeddedWebViewOptions.cs is incorrect.

Instead of checking for Net6, it checks if the app is running on Windows.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Solution and workarounds

None

**Comment by bgavrilMS** [comment]
This option doesn't work on mobile. But I think MSAL should not throw exception, just log a warning. 

In any case, can you please set this option conditionally only on windows app (if needed).

**Comment by softlion** [comment]
Well, so why `.WithUseEmbeddedWebView(true)` does work.

You mean on mobile you can't set the title ?

Is there a way to hide that title on the embedded view ?

**Comment by bgavrilMS** [comment]
On mobile nobody asked to set the title before so we haven't looked into it.

**Comment by softlion** [comment]
> On mobile nobody asked to set the title before so we haven't looked into it.

That's because there used to have no title.  
When upgrading from xamarin to maui, the title appeared in the embedded web view. Why ? dunno.

**Comment by localden** [comment]
Assigning this to myself to test and validate. @softlion - can you please post a screenshot here of the behavior that you are seeing?

**Comment by softlion** [comment]
Thank you for completing this.

The scenario is for keeping a nice UI,  as there is no way to remove that title bar. Or maybe there is an option I missed for that ?

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/190756/4d92413d-3cb1-4456-a0e5-e6ea2756001e)

**Comment by rajagopalannairr** [comment]
@softlion I am also facing the same issue. In our app, we are getting a title bar that was not there previously with Xamarin. Our customer is not happy with the title bar because we are using a custom login design, and the page with the title bar does not look good at all. Is there any fix for this?

@bgavrilMS I believe this a bug.

**Comment by rajagopalannairr** [comment]
@softlion 

`<item name="windowNoTitle">true</item>` try setting this in your theme file.

**Comment by soorajramakrishnan** [comment]
@softlion Are you find any work around. We are facing same issue when we migrate from Xamarin forms. project to MAUI

**Comment by soorajramakrishnan** [comment]
@bgavrilMS We are facing the same issue when we migrate from Xamarin project to MAUI. In Xamarin forms, its working fine.

**Comment by softlion** [comment]
No I did not found any workaround. I tried setting the theme on the BrowserTabActivity, and I tried forcing it on the maui theme. No luck.


@bgavrilMS that still crashes in v4.61.3

Could you also add an option to completely remove that caption ?

Code:
```
        var query = adClient.AcquireTokenInteractive(scopes)
            .WithUseEmbeddedWebView(true)
            .WithEmbeddedWebViewOptions(new () { Title = "My Title" })
            .WithPrompt(Prompt.ForceLogin);
```

Something like:

```
            .WithEmbeddedWebViewOptions(new () { Title = "My Title", IsVisible=false })
```

**Comment by localden** [comment]
@softlion @soorajramakrishnan isn't the title the name of your application in the screenshot above?

**Comment by softlion** [comment]
> @softlion @soorajramakrishnan isn't the title the name of your application in the screenshot above?

It is the name of the app, the one appearing below the icon on the phones's dashboard. I don't want any text here, like it used to be with the xamarin version .

**Comment by rajagopalannairr** [comment]
@softlion @soorajramakrishnan @localden @bgavrilMS @jennyf19 

[Unable to hide tool bar - Cancel & Done button for IOS and Sign In Title bar for Android](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2014)
[[Feature Request] Android WithUseEmbeddedWebView - Remove Sign in header bar with black background](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1927)

The same issue was there previously with Xamarin also, later They fixed it using 
`<item name="windowNoTitle">true</item>
`
I tried these workarounds and nothing is working for MAUI. Our customer is not happy with the way things are going with MAUI sadly :(

**Comment by localden** [comment]
Sounds like [this](https://stackoverflow.com/a/77363153) is what's required.

**Comment by kramer-e** [comment]
Setting the theme in the manifest worked for me:

``<application android:theme="@style/MyTheme">``

And in your styles.xml "MyTheme" style add ``<item name="windowNoTitle">true</item>``

If you want full screen, you can add ``<item name="android:windowFullscreen">true</item>``

<img  width="200" height="444" alt="Image" src="https://github.com/user-attachments/assets/fe6300f9-dae1-4eee-9b45-3a135af00482" />
