### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by olivermue** [AzureAD/microsoft-authentication-library-for-dotnet#4705]
### MSAL client type

Public

### Problem statement

I used the version 4.56 to acquire a graph token for my registered multi-tenant application within a desktop application via the interactive login. So far it works, but the code is more complicated than it should be IMHO:

```csharp
var app = PublicClientApplicationBuilder.Create("{some client id}")
    .WithAuthority(AzureCloudInstance.AzurePublic, "common")
    .WithRedirectUri("http://localhost")
    // 👇🏻 Needed due to usage of OnBeforeTokenRequest()
    .WithExperimentalFeatures()
    .Build();

var result = await app
    .AcquireTokenInteractive(new[] { "https://graph.microsoft.com/.default" })
    // 👇🏻 Needed to avoid error AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.
    .OnBeforeTokenRequest(request =>
    {
        request.Headers.Add("Origin", "http://localhost");
        return Task.CompletedTask;
    })
    .ExecuteAsync(cancellation);
```

### Proposed solution

Is there any better way to add the origin header? Maybe I missed something in the code or documentation. If not, the call of `.WithRedirectUri()` could potentially get an additional parameter, cause the origin header normally matches the redirect uri. Maybe something like this:

```csharp
var app = PublicClientApplicationBuilder.Create("{some client id}")
    .WithAuthority(AzureCloudInstance.AzurePublic, "common")
    .WithRedirectUri("http://localhost", OriginHeader.SameHostAndPort)
    .Build();

var result = await app
    .AcquireTokenInteractive(new[] { "https://graph.microsoft.com/.default" })
    .ExecuteAsync(cancellation);
```

The mentioned new parameter would be an enum that reflects the possibilities according to the [documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin).
```csharp
public enum OriginHeader
{
    NotSet, // Same behaviour as current implementation
    Null,  // Add the explicit header value "null"
    SameHost, // Extracts the scheme and hostname from the given uri
    SameHostAndPort // Extracts the scheme, hostname and port (if available) from the given uri
}
```

**Comment by bgavrilMS** [comment]
I think you misconfigured your app. The "http://localhost" must apear as under desktop apps

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/12273384/6f72b4a9-e44b-4834-afed-5842f941c9e5)

Or in the app manifest: 

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/12273384/4b6f8ed6-eb48-4c9e-8c1b-011dc56aa5c2)

**Comment by olivermue** [comment]
The app is also used for other login flows and has already the SPA platform with the localhost uri and additionally the following desktop app settings:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/17193431/e6c81efe-951a-49b2-9ae9-2ad8868aaf53)

Adding here the localhost doesn't fix the problem, it makes it worse. If we try after adding the localhost to the desktop app to retrieve the token including the origin header value we retrieve the following error message:
> AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'http://localhost'.

If we try without the origin header value we get back this error message, which means no way works anymore.
> A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

So far it seems that the different possibilities and configuration options don't work in every combination. I understand that our app seems to be a _special case_ due to the existing multi-usage. Due to this fact I'm glad that my given workaround gives me a valid token and that for the _default cases_ a correct configured app leads to easier code and my _special case_ doesn't need to be considered for a library change.
