### ISSUE TITLE
Is it expected to support a "Sign Out" feature?

### ISSUE THREAD

**Issue by ajtruckle** [AzureAD/microsoft-authentication-library-for-dotnet#471]
My application has a small popup window to display a list of calendars. This calls a console application behind the scenes to get the details.

To initially see the calendar list I have a button "Sign In". This show the logon / credentials screen and then thereafter use the Token Cache. So the next time you show this window it will automatically list the calendars.

Question: Must I have a "Sign Out" button too which does this (according to the samples I have read):

```
public void SignOut()
{
	strResultsText = "";
	if (Program.PublicClientApp.Users.Any())
	{
		try
		{
			Program.PublicClientApp.Remove(Program.PublicClientApp.Users.FirstOrDefault());
			Console.WriteLine("User has signed-out");
		}
		catch (MsalException ex)
		{
			strResultsText = $"Error signing-out user: {ex.Message}";
		}
	}
}
```

From my perspective the user will always want the connection present. But are there reasons or standards that govern I should include a "Sign Out" button with the above code?

**Comment by jmprieur** [comment]
@ajtruckle, if your users always use the same identity you don't need a signout button.
BTW, for questions, please use https://stackoverflow.com/questions/tagged/msal. You will have quicker answers from members of the community
