### ISSUE TITLE
[Feature Request] Remove UWP targets

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-authentication-library-for-dotnet#4717]
### MSAL client type

Public

### Problem statement

See [Announcing the Upcoming Deprecation of MSAL.NET for Xamarin and UWP](https://devblogs.microsoft.com/identity/uwp-xamarin-msal-net-deprecation/) for details and links.

### Proposed solution

Remove UWP targets, dev apps, and anything else related.

**Comment by nbevans** [comment]
Does this mean critical security updates for UWP will no longer be forthcoming?

**Comment by bgavrilMS** [comment]
> Does this mean critical security updates for UWP will no longer be forthcoming?

We will analyze on a case by case basis - we may patch 4.61 (or whatever) in case of serious problems. UWP relies on several Windows components which are in maintenance mode - a similar bar applies.
