### ISSUE TITLE
TokenCache is not working for xamarin.iOS

### ISSUE THREAD

**Issue by rajamaheshwarsingh** [AzureAD/microsoft-authentication-library-for-dotnet#472]
Hi,

I used this library to authenticate users for xamarin forms project sample. 
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native.

User is authenticated when the app is relaunched in android project.
But in iOS app, User is redirected to login page when the app is relaunched after first 
successful login. 

Please help as it is turning out to be very critical for my project.
Following is the error message i am getting
![image](https://user-images.githubusercontent.com/17141206/30381884-49837314-98bb-11e7-8c1f-0f12aa44320e.png)

**Comment by kpanwar** [comment]
Does this repro on the device? If not, then you should be unblocked. This is a known issue with simulator

**Comment by kpanwar** [comment]
I am closing this issue due to lack of response.
