### ISSUE TITLE
[Bug] Force Login Prompt doesn't work with Custom B2C Policy

### ISSUE THREAD

**Issue by Arslan007** [AzureAD/microsoft-authentication-library-for-dotnet#4724]
### Library version used

4.60.3

### .NET version

.NET 8 MAUI Blazor

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

Switched from Standard B2C Userflow to Custom B2C Policy and now client doesnot honor the force login prompt provided to `PublicClient`

**With Standard Userflow**

https://B2CTenant.b2clogin.com/tfp/B2CTenant.onmicrosoft.com/B2C_1_Insight-SignIn/oauth2/v2.0/authorize?scope=SCOPE-VALUE/access_as_user+openid+profile+offline_access&response_type=code&client_id=CLIENTID&redirect_uri=msal54913353-0009-4271-831e-19751137cc05://auth&client-request-id=abd9d0ee-6eaf-45a2-a72b-f8a6cfedac53&x-client-SKU=MSAL.NetCore&x-client-Ver=4.59.0.0&x-client-OS=Microsoft+Windows+10.0.19045&prompt=login&code_challenge=Gva8MICaqlz8pkLI6J6zYpDGzeRrHgcI_IufWSUkpMc&code_challenge_method=S256&state=4f36d05d-4d49-48be-a058-99099f82bc6f2d747927-1c4d-4be3-a5eb-8022a7ed65c7&client_info=1

**With Custom UserPolicy**

https://B2CTenant.b2clogin.com/tfp/B2CTenant.onmicrosoft.com/B2C_1A_SIGNIN_IRISNDT/oauth2/v2.0/authorize?scope=SCOPE-VALUE/access_as_user+openid+profile+offline_access&response_type=code&client_id=CLIENTID&redirect_uri=msal54913353-0009-4271-831e-19751137cc05://auth&client-request-id=ddcd8c5f-0baf-4231-8f9c-67aa011c1ad7&x-client-SKU=MSAL.NetCore&x-client-Ver=4.60.3.0&x-client-OS=Microsoft+Windows+10.0.19045&prompt=login&code_challenge=wD8sIURk_ZnjDJP2h9xERNe1lwcIS_pPj8G3PAlCSfI&code_challenge_method=S256&state=cbc727f4-675b-49a5-be8a-a7709f8f4d67b2bea6f1-37ff-4565-aa85-9a70b20e812a&client_info=1

I can see prompt is passed as per logs of MSAL library but MSAL client still picks old user

### Relevant code snippets

```csharp
await PublicClientApplication.AcquireTokenInteractive(scopes)
   .WithParentActivityOrWindow(PlatformConfig.Instance.ParentWindow)
   .WithPrompt(Prompt.ForceLogin)
   .ExecuteAsync()
   .ConfigureAwait(false);
```

### Expected behavior

When Force Login Prompt is provided the MSAL client should honor that and ask user to provide the credentials in interactive flow.

### Identity provider

Azure B2C Custom Policy

### Solution and workarounds

No workaround

**Comment by XRMech** [comment]
My UWP hololens2  application that connects to OneDrive has also stopped getting past entering the email and seems to also stop at the same call
var authResult = await identityClientApp.AcquireTokenInteractive(grantScopes).ExecuteAsync();
I have tried updating to the latest Microsoft.Graph, and can't seem to get past a long list of incompatible libraries for UWP, so ensuring the original ones still authenticate seems important.

**Comment by Arslan007** [comment]
My issue was my custom policy was not having support of prompts so once I added there everything start working
