### ISSUE TITLE
[Bug] PublicClientApplicationBuilder does not work with redirecturi other than localhost

### ISSUE THREAD

**Issue by tanakamawere** [AzureAD/microsoft-authentication-library-for-dotnet#4725]
### Library version used

4.60.3

### .NET version

8

### Scenario

ConfidentialClient - web site (AcquireTokenByAuthCode)

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

When testing the application locally, the login button works. It's code is the following 
```
private async void OnLoginClicked()
{
    try
    {
        // Attempt silent login, and obtain access token.
        var result = await _pcaWrapper.AcquireTokenSilentAsync(_pcaWrapper.Scopes).ConfigureAwait(false);

        // Set access token.
        GlobalValues.AccessToken = result?.AccessToken;
        snackbar = Snackbar.Add("You are now signed in!", Severity.Success);
        navManager.NavigateTo(navManager.Uri, true);
    } 
    // A MsalUiRequiredException will be thrown, if this is the first attempt to login, or after logging out.
    catch (MsalUiRequiredException)
    {
        try
        {
            // Perform interactive login, and obtain access token.
            var result = await _pcaWrapper.AcquireTokenInteractiveAsync(_pcaWrapper?.Scopes).ConfigureAwait(false);

            // Set access token.
            GlobalValues.AccessToken = result?.AccessToken;
            snackbar = Snackbar.Add("You are now signed in!", Severity.Success);
            navManager.NavigateTo(navManager.Uri, true);
        }
        catch (Exception ex)
        {
            // Ignore.
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
        snackbar = Snackbar.Add("An error occurred while signing in. Please try again.", Severity.Error);
    }
    finally
    {
        isBusy = false;
    }
}
```

The _pcaWrapper is being injected into the Blazor page and its implementation is the following

```
    public PCAWrapper(IConfiguration configuration)
    {
        _configuration = configuration;
        _settings = _configuration.GetRequiredSection("Settings").Get<Settings>();

        if (_settings?.Scopes == null)
            return;

        Scopes = _settings.Scopes.ToStringArray();
        // Create PCA once. Make sure that all the config parameters below are passed
        PCA = PublicClientApplicationBuilder
                                    .Create(_settings?.ClientId)
                                    .WithB2CAuthority(_settings?.Authority)
#if !ANDROID
                                     .WithRedirectUri($"https://medbase.co.zw")
                                     //.WithRedirectUri("http://localhost")
#endif
                                    .Build();
    }
```

When I use the localhost redirect uri, the users are logged in successfully (that's when debugging on my local machine.) When I set the redirect URI to my production URI, the button doesn't do anything (I suppose because the PCAWrapper isn't being built on start up). This occurs on my production server and even locally if I just set the redirect URI to `medbase.co.zw` just to test

### Expected behavior

The redirect URI should just allow the login button to work with any URI, correct or incorrect. 

### Identity provider

Azure B2C Basic Policy

### Solution and workarounds

None found

**Comment by bgavrilMS** [comment]
System browser requires `http://localhost` redirect URI. MSAL communicates with the system browser via a local socket. 

For web sites and web apis, you want https redirect URI. For public client, `http://localhost` is acceptable. Visual Studio uses it as well, you can intercept the traffic with a tool like Fiddler to check...

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/12273384/a29624c2-9a56-4de6-80f2-129a151ee8a2)

**Comment by tanakamawere** [comment]
Wait, I'm talking about in production. I obviously don't use localhost as the redirect UI 
I should use my own callback URL but that isn't working 
I'm using Https://medbase.co.zw/signin-oidc but that's not working

**Comment by rayluo** [comment]
> Title: [Bug] PublicClientApplicationBuilder does not work with redirecturi other than localhost

> Scenario
ConfidentialClient - web site (AcquireTokenByAuthCode)

@tanakamawere , you were perhaps confused with the two types. PublicClientApplication only uses `http://localhost:...` and that is by design. ConfidentialClientApplication is for websites and they allow any redirect uri. Even if you are testing your website locally, you shall not use PublicClientApplication for that test.

**Comment by tanakamawere** [comment]
I see. I have learnt something. 
So I am converting my PublicClientApplication Builder to use the Confidential Client Application. 

Could you help me convert the following method since InteractiveAsync doesn't exist in the Confidential Client Application... 

```
public async Task<AuthenticationResult> AcquireTokenInteractiveAsync(string[] scopes)
{
    if (CCA == null)
        return null;

    var accounts = await CCA.GetAccountsAsync(_settings?.PolicySignUpSignIn).ConfigureAwait(false); ;
    var account = accounts.FirstOrDefault();

    return await CCA.AcquireTokenInteractive(scopes)
                            .WithB2CAuthority(_settings?.Authority)
                            .WithAccount(account)
                            .WithParentActivityOrWindow(PlatformConfig.Instance.ParentWindow)
                            .WithUseEmbeddedWebView(false)
                            .ExecuteAsync()
                            .ConfigureAwait(false);


}
```

**Comment by pmaytak** [comment]
See [Public client and confidential client applications](https://learn.microsoft.com/en-us/entra/identity-platform/msal-client-applications) for differences between two types and [Application configuration options
](https://learn.microsoft.com/en-us/entra/identity-platform/msal-client-application-configuration) on MSAL config options.

There's a Blazor WASM sample [here](https://learn.microsoft.com/en-us/entra/identity-platform/sample-v2-code?tabs=apptype#single-page-applications) that uses MSAL JavaScript and a Blazor Server sample [here](https://learn.microsoft.com/en-us/entra/identity-platform/sample-v2-code?tabs=apptype#web-applications) which [actually uses Microsoft.Identity.Web](https://github.com/Azure-Samples/ms-identity-blazor-server/blob/732d7e3109e03127034edc284841e73701816245/WebApp-OIDC/B2C/blazorserver-B2C/Startup.cs#L34) - an simplified abstraction over MSAL.NET (recommended).

**Comment by tanakamawere** [comment]
Thank you all
