### ISSUE TITLE
[Bug] "Back" button appears in MSAL.net (which was not appearing in ADAL.net)

### ISSUE THREAD

**Issue by smohanty05** [AzureAD/microsoft-authentication-library-for-dotnet#4738]
### Library version used

Microsoft.Identity.Client 4.60.3

### .NET version

.net framework 4.8

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

I am migrating from ADAL.net to MSAL.net
From desktop app username is sent to the method which acquires token.
`
publicClient = PublicClientApplicationBuilder.Create(clientId)
                                      .WithAuthority(authority)
                                      .WithRedirectUri(redirectUri.ToString())
                                      .Build();
FileCache.EnableSerialization(publicClient.UserTokenCache);
var accounts = await publicClient.GetAccountsAsync();
AuthenticationResult result = null;
try
{
    result = await publicClient.AcquireTokenSilent(scopes, accounts.FirstOrDefault())
              .ExecuteAsync();
    if (!string.IsNullOrEmpty(userName) && !result.Account.Username.Equals(userName + "@" + tenant, StringComparison.InvariantCultureIgnoreCase))
        throw new MsalUiRequiredException(MsalError.MultipleTokensMatchedError, "Multiple tokens matched");
}
catch (MsalUiRequiredException ex)
{
    if (ex.ErrorCode == MsalError.MultipleTokensMatchedError)
    {
        // clear the cache
        ClearCache();
    }
    if (string.IsNullOrEmpty(userName))
        result = await publicClient.AcquireTokenInteractive(scopes)
                    .WithPrompt(Prompt.ForceLogin)
                    .ExecuteAsync();
    else
        result = await publicClient.AcquireTokenInteractive(scopes)
                    .WithPrompt(Prompt.ForceLogin)
                    .WithLoginHint(userName + "@" + tenant)
                    .ExecuteAsync();
`
AcquireTokenInteractive  showing the dialog box with "Back" button when username provided to the method is an invalid user. But there is no use of Back button here. Clicking on it causes User Authentication Cancelled exception.

------------------------------
In ADAL.net, the old code was as below:
`
authContext = new AuthenticationContext(authority, new FileCache());
AuthenticationResult result = null;
try
{
    result = await authContext.AcquireTokenSilentAsync(resourceId, clientId);
    if (!string.IsNullOrEmpty(userName) && !result.UserInfo.DisplayableId.Equals(userName + "@" + tenant, StringComparison.InvariantCultureIgnoreCase))
    {
        throw new AdalException(AdalError.MultipleTokensMatched);
    }
}
catch (AdalException ex)
{
    if (ex.ErrorCode == AdalError.UserInteractionRequired || ex.ErrorCode == AdalError.FailedToAcquireTokenSilently || ex.ErrorCode == AdalError.MultipleTokensMatched)
    {
        if(ex.ErrorCode == AdalError.MultipleTokensMatched)
        {
            if (authContext != null)
                authContext.TokenCache.Clear();
        }
        if (string.IsNullOrEmpty(userName))
        {
            result = await authContext.AcquireTokenAsync(resourceId, clientId, redirectUri, new PlatformParameters(PromptBehavior.Always));
        }
        else
        {
            result = await authContext.AcquireTokenAsync(resourceId, clientId, redirectUri, new PlatformParameters(PromptBehavior.Always), new UserIdentifier(userName + "@" + tenant, UserIdentifierType.RequiredDisplayableId));
        }
    }
}`
----------------------
I have attached screenshots from both MSAL.net and ADAL.net below.

MSAL.net=>
![MSAL net](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/65710408/abf488dd-a236-4258-9ada-fb0a7312acb9)

ADAL.net=>
![ADAL net](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/65710408/818a2d18-bd40-44a7-a90f-10e070fe9989)

Users will consider this as regression after migration from ADAL.net to MSAL.net.

Is there a way to remove/hide the Back button?

### Expected behavior

Back button should not be shown in this case as there is no use of it (in the scenario described).

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
This is a service problem, SDK does not control UI

**Comment by localden** [comment]
@bgavrilMS it does seem odd, however, that the behavior would be different between ADAL and MSAL in UI rendering (even if it's not the library that controls the UI). Let me reach out to service folks and see if we can get some clarity here.

**Comment by rayluo** [comment]
> @bgavrilMS it does seem odd, however, that the behavior would be different between ADAL and MSAL in UI rendering (even if it's not the library that controls the UI). Let me reach out to service folks and see if we can get some clarity here.

ADAL talks to v1 endpoint and MSAL talks to v2. It could be the different out-of-the-box behaviors of the two endpoints. Just a hypothesis, though. I did not try it myself. :-)

**Comment by smohanty05** [comment]
@localden , please find the Fiddler result for ADAL and MSAL.
[MSAL_ADAL.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/15318655/MSAL_ADAL.zip)

**Comment by localden** [comment]
@smohanty05 I only see the `CONNECT` handshakes in there, but not the actual requests. Can you please enable HTTPS decryption and then re-capture the requests?

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/53200638/70ee9a15-6e79-4935-b996-2cdd1579a10e)

Same as last time - please don't enter any creds 😀

**Comment by smohanty05** [comment]
@localden , please find the request and response in the attached document.
[ADAL.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/15349243/ADAL.txt)
[MSAL.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/15349245/MSAL.txt)

**Comment by localden** [comment]
@smohanty05 appreciate the context, we are investigating.

**Comment by fengga** [comment]
@smohanty05 , can you apply the same change as in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4836 and see if it can resolve the issue?

**Comment by smohanty05** [comment]
@fengga , the issue is resolved with WithExtraQueryParameters("haschrome=1").

Thanks a lot!

So, should we use this in our code as wherever we use WithLoginHint or this fix would be part of MSAL.net goods?

**Comment by fengga** [comment]
> @fengga , the issue is resolved with _WithExtraQueryParameters("haschrome=1")_.
> 
> Thanks a lot!
> 
> So, should we use this in our code wherever we use _WithPrompt_ or this fix would be part of MSAL.net goods?

That PR was merged. Before the next release I think you can just use _WithExtraQueryParameters("haschrome=1") on your side.

**Comment by smohanty05** [comment]
Thank you @fengga!

**Comment by smohanty05** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4836
This looks like old bug which was marked as 'Won't fix'?
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/89
