### ISSUE TITLE
[Engineering task] Support logical URLs

### ISSUE THREAD

**Issue by starosta33** [AzureAD/microsoft-authentication-library-for-dotnet#4754]
### Task type

Design

### Description

For multiple reasons, we'd like ask MSAL to support the functionality currently supported in SEAL internal library, i.e. for the logical URL claim provided by a caller to be embedded in the resulting SHR under a dedicated `client_claims` property.

Example:
```
"client_claims" : {"lu":"https://calling.teams.microsoft.com"}
```

We can share more details and the current implementation internally

**Comment by bgavrilMS** [comment]
Hi @starosta33 - please contact us directly. My alias is bogavril
