### ISSUE TITLE
Calling custom web api from .net web app

### ISSUE THREAD

**Issue by SanjayAswale** [AzureAD/microsoft-authentication-library-for-dotnet#478]
The code sample mentioned below does not work with preview version of MSAL library. 
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-devquickstarts-webapp-webapi-dotnet

Can you update this sample to work with preview version?

Can we pass custom scope of web api in openidconnect? I was trying this by following this article:
https://blogs.msdn.microsoft.com/tsmatsuz/2017/06/22/web-api-and-custom-scope-with-azure-ad-v2-endpoint/
but it failed when in add openid/offline_access scope with custom scope.

Appreciate your help !
Sanjay A.

**Comment by jmprieur** [comment]
We cannot yet call a 3rd party web api on the AAD v2 endpoint (that is with MSAL). This is something we'll work on in the near future.
