### ISSUE TITLE
[Bug] MeasureDurationResult incorrect when running in linux

### ISSUE THREAD

**Issue by SingleCopy** [AzureAD/microsoft-authentication-library-for-dotnet#4784]
### Library version used

4.60.3

### .NET version

C# .net 8.0

### Scenario

ManagedIdentityClient - managed identity

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

When our unit tests are run using a linux distro, the AuthenticationResult->AuthenticationResultMetadata->DurationTotalInMs is returning a incorrect time. This is due to the Stopwatch.Frequency being 10000000 on windows and 1000000000 on linux, this is not taken into account when performing the calculation.

[](url)

### Relevant code snippets

```csharp
public MeasureDurationResult(long ticks)
{
    Milliseconds = ticks / TimeSpan.TicksPerMillisecond;
    Microseconds = ticks / (TimeSpan.TicksPerMillisecond / 1000);
    Ticks = ticks;
}
```

### Expected behavior

Regardless of O/S, the DurationTotalInMs should be the same, however, on linux, the DurationTotalInMs is incorrect

Windows:
ElapsedTicks: 8423086
DurationTotalInMs: 842

Linux
ElapsedTicks: 8423086
DurationTotalInMs: 84230

### Identity provider

Other

**Comment by localden** [comment]
Sounds like we need to update the converstion factor (`1000.0 / Stopwatch.Frequency`).

**Comment by SingleCopy** [comment]
@localden Correct, this is for Managed Identity, I have updated my description.
