### ISSUE TITLE
custom URI for xamarin.forms mobile app

### ISSUE THREAD

**Issue by rajamaheshwarsingh** [AzureAD/microsoft-authentication-library-for-dotnet#479]
How to specify custom URI for xamarin.forms mobile app when the user clicks on Register link on Azure B2C directory in sign-in page provided by Azure B2C directory.

In Azure portal, created custom link with URI "MyApplicatin://register". The link is visible in Azure login page in mobile application, but clicking on that link nothing is happening in the mobile app.

**Comment by jmprieur** [comment]
@parakhj : can you please have a look.

**Comment by parakhj** [comment]
@rajamaheshwarsingh are you still facing an issue?

**Comment by jmprieur** [comment]
closing as there was no answer.
