### ISSUE TITLE
[Bug] "Work and school account" Option Doesn't Show on WAM Pop-up Window

### ISSUE THREAD

**Issue by msJinLei** [AzureAD/microsoft-authentication-library-for-dotnet#4797]
### Library version used

4.63.0

### .NET version

.netstandard 2.0

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

Acquire token interactively with WAM broker

### Expected behavior

WAM pop windows should contains "work and school account" options
But actually not

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/54836179/e910d6c0-a628-4918-be99-9b9857ad77d2)

I cannot reproduce the issue. May need the original reporter to provide the detailed debug logs.

See https://github.com/Azure/azure-powershell/issues/24964

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
The issue here is that the account picker does not have a "Use a different account" + "Work and School account" option. Only the option "Use a different account" + "MSA" exists.

Possibly a problem with the account picker?

**Comment by bgavrilMS** [comment]
Workaround exists as PS users have option to disable WAM.

**Comment by bgavrilMS** [comment]
@iulico-1 @ashok672 - apart from the issue itself, it would be good to start adding more troubleshooting to the public docs. I know WAM has been through a lot, so maybe it's just a matter of making more TSG guides available ? 

There's a small troubleshooting section at https://aka.ms/msal-net-wam

**Comment by iulico-1** [comment]
@msJinLei , what's the authority passed for the interactive request that only show MSA sign-in with new account UX ?

**Comment by msJinLei** [comment]
> @msJinLei , what's the authority passed for the interactive request that only show MSA sign-in with new account UX ?

The same as nonWAM flow
"https://login.microsoftonline.com" for public cloud

**Comment by localden** [comment]
@msJinLei - naive question, but have you tried scrolling in that view? We've seen some issues in the past where work and school accounts were hidden behind a scrollable section.

**Comment by localden** [comment]
@msJinLei - can you please confirm whether you can scroll in the account picker, and that the item is not hidden behind a scrollable area?

**Comment by msJinLei** [comment]
@localden Let's wait for the issue reporter's feedback

**Comment by xinyuxu1026** [comment]
Hi @msJinLei , the user confirmed that scroll down resolved the issue.
