### ISSUE TITLE
[Bug] I'm getting "Only loopback redirect uri is supported"

### ISSUE THREAD

**Issue by malsabi** [AzureAD/microsoft-authentication-library-for-dotnet#4805]
### Library version used

4.61.3

### .NET version

.NET 8 Core, Version 8.0.204

### Scenario

PublicClient - desktop app, PublicClient - mobile app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

Hello I'm using .NET MAUI and the latest version of MSAL Library 4.61.3 however I'm getting the following exception:

``` 
Only loopback redirect uri is supported, but msal4204552g-24f0-4682-a237-1250c3234191://auth/ was found. Configure http://localhost/ or http://localhost:port both during app registration and when you create the PublicClientApplication object.
```

Packages Installed:
1. Microsoft.Identity.Client 4.61.3
2. Microsoft.Identity.Client.Extensions.Msal 4.61.3 

Note: This used to work completely fine on **4.59.1**

### Relevant code snippets

```csharp
Here is my code that is used to handle authentication in different platforms, however the issue happened in Windows, I didn't test for Android / iOS. Can you please tell me what is required here to make it work ? 


	public AuthenticationService(IOptions<AuthenticationSettings> authenticationSettings)
	{
		this.authenticationSettings = authenticationSettings.Value;

		authenticationClient = PublicClientApplicationBuilder.Create(this.authenticationSettings.ClientId)
#if IOS
			.WithIosKeychainSecurityGroup("com.microsoft.adalcache")
#endif
			.WithRedirectUri($"msal{this.authenticationSettings.ClientId}://auth")
#if ANDROID
			.WithParentActivityOrWindow(() => Platform.CurrentActivity)
#endif
			.Build();
	}

	public async Task<AuthenticationResult?> LoginAsync(CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();
		try
		{
#if WINDOWS
			await AttachTokenCache();
#endif
			return await authenticationClient
				.AcquireTokenInteractive(authenticationSettings.Scopes)
#if WINDOWS
				.WithUseEmbeddedWebView(authenticationClient.IsEmbeddedWebViewAvailable())
#endif
				.ExecuteAsync(cancellationToken);
		}
		catch (MsalClientException)
		{
			return null;
		}
	}
```

### Expected behavior

The expected behavior Is to open the authentication window and write the email / password.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.59.1

**Comment by bgavrilMS** [comment]
Is this error happening on Android and iOS only?

I think I can repro this, for some reason my MAUI Android app references MSAL net6 instead of referencing MSAL net6-android; Not sure what the root cause is.

**Comment by pmaytak** [comment]
> Is this error happening on Android and iOS only?
> 
> I think I can repro this, for some reason my MAUI Android app references MSAL net6 instead of referencing MSAL net6-android; Not sure what the root cause is.

Hmm, is the app referencing lower unsupported Android API version? Then it'll drop to net6.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4e51d0afea8aab1871e3a5fef7193b87ad43226d/src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj#L20

**Comment by charlesroddie** [comment]
We are getting this after a package update in UWP.

**Comment by gh615** [comment]
This issue is also occurring in the msgraph-sample-maui. https://github.com/microsoftgraph/msgraph-sample-maui
After updating the Microsoft.Identity.Client and Microsoft.Identity.Client.Extensions.Msal packages to the latest version.(from 4.57.0 to 4.61.3)
But I have only confirmed this on Windows (I have not tested it on other platforms).

**Comment by mkionet** [comment]
This has just started happing to our maui app, only on windows, android works, not tested ios.

Microsoft.Identity.Client 4.61.3
Microsoft.Identity.Client.Extensions.Msal 4.61.3

I tried reverting to older versions but was still no good.

**Comment by malsabi** [comment]
Any Updates?

**Comment by bgavrilMS** [comment]
For folks who have UWP apps, MSAL dropped support for UWP. See https://devblogs.microsoft.com/identity/uwp-xamarin-msal-net-deprecation/. The last version of MSAL that supports UWP and is not affected by a CVE is https://www.nuget.org/packages/Microsoft.Identity.Client/4.47.2

For folks having the problem on MAUI Windows, we dropped support for net6-windows10.xyz and moved it to a different package. Happy to help anybody having problems here. The sample The sample https://github.com/Azure-Samples/ms-identity-dotnetcore-maui  is up to date
## For getting embedded browser support 

- Add a reference to `Microsoft.Identity.Client.Desktop` like [this](https://github.com/Azure-Samples/ms-identity-dotnetcore-maui/blob/main/MauiAppBasic/MauiAppBasic.csproj#L83) and add this to where you construct the PublicClientApplication:

```csharp
#if WINDOWS
                .WithWindowsEmbeddedBrowserSupport()
#endif
```
## For apps using the broker on Windows

Easiest to is to follow the PR - https://github.com/Azure-Samples/ms-identity-dotnetcore-maui/commit/aadf6b62bb5e2f6aabafa6814573abece64032ff#diff-45125fbd9dbdb0351f4478b0b30c5d9e578741766f92b7e8c8b18ecc5bb4e4f1

**Comment by malsabi** [comment]
I can confirm adding the following worked in Windows! thanks for the workaround but it looks like a solution no? cause if it's a workaround will there be any changes that I need to be alerted for?

```
#if WINDOWS
                .WithWindowsEmbeddedBrowserSupport()
#endif
```

**Comment by bgavrilMS** [comment]
Later update - we will release a newer version of MSAL with the hotfix with UWP support, most likely version 4.60.4 ... It will appear as vulnerable at first, until we can update the CVE.

By the way, the CVE is related to a confidential client flow. None of the apps mentioned in this thread execute that code.

**Comment by bgavrilMS** [comment]
> I can confirm adding the following worked in Windows! thanks for the workaround but it looks like a solution no? cause if it's a workaround will there be any changes that I need to be alerted for?
> 
> ```
> #if WINDOWS
>                 .WithWindowsEmbeddedBrowserSupport()
> #endif
> ```

Yes, this is the pattern going forward.

**Comment by ashok672** [comment]
Solution provided to the problem

**Comment by LapinskasL** [comment]
@bgavrilMS, thanks for the solution. However, you're referencing .NET 7 in your code. How do I make this work with a .NET 8 MAUI app? I'm using Blazor Hybrid, if it makes any difference.
