### ISSUE TITLE
[Bug] 4.60.3 has a known moderate severity vulnerability

### ISSUE THREAD

**Issue by mfeingol** [AzureAD/microsoft-authentication-library-for-dotnet#4806]
### Library version used

4.60.3

### .NET version

UWP

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

MSAL 4.60.3 is vulnerable to this issue: https://github.com/advisories/GHSA-m5vv-6r4h-3vj9

MSAL 4.60.3 is also the latest version of MSAL that supports UWP. We cannot upgrade to new versions. And yet Nuget is signaling that this package is vulnerable and needs an update.

Please provide a version of MSAL 4.60.x that addresses the vulnerability.

### Expected behavior

UWP should continue to be supported with security fixes.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
@localden updated the CVE to more accurately reflect the affected version. 4.47.2 is not affected and supports UWP

https://www.nuget.org/packages/Microsoft.Identity.Client/4.47.2

**Comment by mfeingol** [comment]
Thanks, @bgavrilMS. I think "acceptable" depends on the impact of regressing back to such an old version of MSAL. In an ideal world we'd continue to provide at least security fixes for the most recent possible version of MSAL that supports UWP until UWP is officially deprecated.

(And yes, I'm aware of WinUI and have worked on a port... there are significant functional regressions in WinUI that make that impossible for now.)

**Comment by localden** [comment]
@mfeingol unfortunately, that is currently the only path forward for UWP. The Windows team [has been recommending](https://learn.microsoft.com/en-us/windows/apps/get-started/?tabs=uwp%2Cnet-maui#other-native-platform-options) WinUI for some time now, and we're snapping to their support model for frameworks and toolkits. 4.47.2 does not have known security vulnerabilities and may be used if you are still supporting UWP applications.

**Comment by mfeingol** [comment]
@localden: I understand where you're coming from, but this decision doesn't seem aligned with the guidance you linked to. 

> UWP is supported and will continue to receive bug, reliability, and security fixes

If you're telling me that 4.47.x will be updated further as new MSAL vulnerabilities appear, then that would be unfortunate (regressing any of us in this situation 13 minor versions) but would at least be consistent with the guidance.

**Comment by localden** [comment]
@mfeingol I am working with the engineering team to see if we can do a point release for MSAL.NET for the 4.60.3 branch that mitigates the CVE, but beyond that UWP and Xamarin will not be included in other versions of MSAL. Will follow-up on this thread once I get a definitive point of view on the possibility of a new release.

**Comment by mfeingol** [comment]
Thanks for that. I should note that it's worth considering Xamarin and UWP in two separate categories. Xamarin's deprecation date was announced and has been reached; no further support is expected there. UWP, on the other hand, is still solidly supported... at least on paper.

**Comment by localden** [comment]
> Thanks for that. I should note that it's worth considering Xamarin and UWP in two separate categories. Xamarin's deprecation date was announced and has been reached; no further support is expected there. UWP, on the other hand, is still solidly supported... at least on paper.

From our team's vantage point, it's in maintenance mode, and most customers are moving to WinUI and other Windows App SDK toolchains. There are _very_ few UWP applications using MSAL, just for a reference.

On the earlier point, though - we are working on getting a point release and seeing what it would take to build it properly. It will _likely_ be 4.60.4 that will contain the security fix and will still have the UWP and Xamarin TFMs.

**Comment by nbevans** [comment]
It was previously noted here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4717#issuecomment-2061657818 that UWP security fixes would be forthcoming on a case-by-case basis. This seems like such a case where there is indeed a basis for doing so.

**Comment by localden** [comment]
> It was previously noted here [#4717 (comment)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4717#issuecomment-2061657818) that UWP security fixes would be forthcoming on a case-by-case basis. This seems like such a case where there is indeed a basis for doing so.
> 
> Whilst UWP is indeed in maintenance mode, it is not obsolete. And whilst there may not be many applications using MSAL with UWP. That does not necessarily account for all of the hidden line-of-business applications that were built with UWP over the years it was fashionable. I really think MSAL should commit to providing security fixes for as long as UWP is still in maintenance support. It feels like the right thing to do.

As @bgavrilMS mentioned, we will do this on a case-by-case basis, depending on both severity and impact. We're working a point release for the _current_ CVE notice.

**Comment by nbevans** [comment]
@localden Thanks for the update. It is appreciated.

**Comment by localden** [comment]
4.60.4 was released and we're working with GitHub to adjust the security alert for this specific build (it mitigates the vulnerability but still caught in the current version range).

**Comment by localden** [comment]
Closing this - 4.60.4 should be the version with the fix for the legacy branch, and is no longer lighting up with the warning. 
![Screenshot of NuGet showing Microsoft.Identity.Client versions](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/53200638/899faa4a-f279-40cb-98d2-154edd4d2c36)

**Comment by mfeingol** [comment]
Thank you, MSAL team.

**Comment by charlesroddie** [comment]
@localden @trwalke , does 4.60.4 correspond to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4814 ?
I can't find a tag for 4.60.4 or any merged code.
We need this for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5144 .
