### ISSUE TITLE
[Documentation] - ICustomWebUi.AcquireAuthorizationCodeAsync mistake

### ISSUE THREAD

**Issue by NETSphereSoft** [AzureAD/microsoft-authentication-library-for-dotnet#4809]
_Make sure that your question or issue is not already covered in [MSAL docs](https://learn.microsoft.com/en-us/entra/msal/dotnet/) or [samples](https://learn.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code?tabs=apptype)._

**Documentation related to component**
Microsoft.Identity.Client

**Please check those that apply**

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**
There is a small mistake in the XML `remarks` of `Microsoft.Identity.Client.Extensibility.ICustomWebUi.AcquireAuthorizationCodeAsync` at [line 34](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4e51d0afea8aab1871e3a5fef7193b87ad43226d/src/client/Microsoft.Identity.Client/Extensibility/ICustomWebUI.cs#L34). There is an additional `"\>` after the `paramref`

**Comment by bgavrilMS** [comment]
Fixed via https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4812
