### ISSUE TITLE
[Feature Request] Remove unused telemetry features

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4815]
### MSAL client type

Confidential, Managed identity

### Problem statement

- drop x-client-last-telemetry
- remove the WithTelemetryClient APIs if any

**Comment by rayluo** [comment]
> * drop x-last-request header

Does that mean `x-client-last-telemetry` header or are they two different things? @bgavrilMS

**Comment by bgavrilMS** [comment]
> > * drop x-last-request header
> 
> Does that mean `x-client-last-telemetry` header or are they two different things? @bgavrilMS

Yes, x-client-last-telemetry
