### ISSUE TITLE
[Bug] Getting type or namespace not found error while using BrowserTabActivity

### ISSUE THREAD

**Issue by rohitnahatam** [AzureAD/microsoft-authentication-library-for-dotnet#4819]
### Library version used

4.61.3

### .NET version

netstandard2.0

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

I am currently using 4.60.3 and trying to upgrade to 4.61.3. After upgrade , I am getting this error for BrowserTabActivity.
I was looking at the documentation but couldn't find any change related to this.
Error - The type or namespace name 'BrowserTabActivity' could not be found (are you missing a using directive or an assembly reference?)	
 
Co-pilot was suggesting to use Activity instead of BrowserTabActivity, but couldn't find any supporting sample code for the same to validate if it is okay to use.

### Relevant code snippets

```csharp
using Android.App;
using Android.Content;
using Microsoft.Identity.Client;

namespace Droid.Login
{
    [Activity(Exported = false)]
    [IntentFilter(new[] { Intent.ActionView },
            Categories = new[] { Intent.CategoryBrowsable, Intent.CategoryDefault },
            DataHost = "auth",
            DataScheme = "msalxxxxxxxxxxxxxxxxxxxxxxxxxxxx")]
    public class MsalActivity : BrowserTabActivity
    {
    }
}
```

### Expected behavior

The code should be built successfully.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Are you still using Xamarin? Or is this a MAUI app?

Possible duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4817

**Comment by rohitnahatam** [comment]
yes, we are still using Xamarin.

**Comment by rohitnahatam** [comment]
@bgavrilMS Just wanted to check if there is a timeline till when you will be fixing the security vulnerabilities in 4.60? Asking this as we are still using Xamarin and there isn't plan to migrate to MAUI yet.
