### ISSUE TITLE
[Feature Request] Privacy Page open by Iexplore.exe

### ISSUE THREAD

**Issue by LKMMKL** [AzureAD/microsoft-authentication-library-for-dotnet#4823]
### Library version used

4.61.3

### .NET version

.Net Framework 4.7.2
OS 22631.3737

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

1. Fill in username and password。Click Next.
2. Click privacy link in permission confirmation page.
3.  The web page open in Iexplore.exe

![2H_F_2@$XN4CMDVH8C)~GPR](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/31981596/16463523-aecc-48db-9a4d-42c04cd9ae1d)
![BJKB)O1K2IB4}@7}IA@I61W](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/31981596/35647dab-38a1-41d9-81c0-7c3b3b7cd9fa)

### Expected behavior

The IE browser has expired, I would like to replace it with Edge. Can it be implemented at the API level? I haven't seen any relevant documentation.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
This is a service error, MSAL dosn't control the auth content. 

Suggestion is to use WAM https://aka.ms/msal-net-wam

**Comment by LKMMKL** [comment]
Sorry, I don't understand the meaning of the service error. Does it mean that this operation was not performed by this library？
