### ISSUE TITLE
[Engineering task] The IMsalMtlsHttpClientFactory should be publicly accessible to allow developers to create HttpClient instances configured for MTLS.

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4841]
### Task type

Other

### Description

The `IMsalMtlsHttpClientFactory` interface in the MSAL library is currently marked as internal, making it inaccessible for developers who need to customize their HttpClient with an MTLS certificate. This limitation prevents the effective utilization of the new feature designed for secure communication with Azure AD.

**Steps to Reproduce:**
- Attempt to implement `IMsalMtlsHttpClientFactory` in a project.
- Observe the error: CS0122 `IMsalMtlsHttpClientFactory` is inaccessible due to its protection level.

**Expected Behavior:**
The `IMsalMtlsHttpClientFactory` should be publicly accessible to allow developers to create HttpClient instances configured for MTLS.

**Actual Behavior:**
The `IMsalMtlsHttpClientFactory` is marked as internal, leading to a protection level error when trying to implement it in an external project.

### Solution

Change the access modifier of the `IMsalMtlsHttpClientFactory` interface from internal to public.

**Comment by bgavrilMS** [comment]
No description of the scenario this unlocks. And no dev ex proposal for ID.Web / MISE.
