### ISSUE TITLE
[Bug] Unable to acquire token using Microsoft.Identity.Client Version=4.61.3.0 in Dynamics CRM custom workflow activity

### ISSUE THREAD

**Issue by Sandeep891-dev** [AzureAD/microsoft-authentication-library-for-dotnet#4843]
### Library version used

4.61.3.0

### .NET version

4.6.2

### Scenario

ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

We are using 'Microsoft.IdentityModel.Clients.ActiveDirectory library in our Dynamics CRM custom workflow activity code for getting authentication token from Microsoft Entra ID.

This has suddenly stopped working and we started receiving an error 'Could not load file or assembly Microsoft.IdentityModel.Clients.ActiveDirectory, Version=5.3.0.0 or one of its dependencies. The system cannot find the file specified.'

As per the suggestion mentioned in https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/ we replaced the assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory' of version 5.3.0.0 with 'Microsoft.Identity.Client' of version 4.61.3.0 and updated the code to get the token in our Dynamics CRM custom workflow activity.

Also, we have written code as suggested in https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/migrate-confidential-client?tabs=daemon and registered our custom workflow activity code with Dynamics CRM.

However, we are receiving the error 'Could not load file or assembly Microsoft.Identity.Client, Version=4.61.3.0, Culture=neutral or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

### Expected behavior

**AcquireTokenForClient** returns an access token successfully without any errors.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Assembly loading issue are outside the scope of this project. MSAL is a normal, standard nuget package that can be referenced from nuget.org or from any other package manager. We cannot help with issues related to dynamic assembly loading or custom build systems.
