### ISSUE TITLE
[Bug] Landscape and portrait not working as expected in some of the devices 

### ISSUE THREAD

**Issue by kiranbasvaraj** [AzureAD/microsoft-authentication-library-for-dotnet#4850]
### Library version used

4.36.1

### .NET version

netstandard2.0

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

existing

### Issue description and reproduction steps

Issue:1
1. Install any Xamarin application which supports only portrait
2. try to rotate the application on the login page
3. The application will still rotate to landscape even if the app is not developed to support landscape

Issue:2
1. Install the Xamarin forms application which supports landscape
2. rotate the application on the login page
3. the app will not rotate to landscape(Lenovo and some of the Samsung devices)

Issue:3
Scroll is not working in Android devices

### Expected behavior

Landscape and portrait should work

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Solution and workarounds

no

**Comment by xinyuxu1026** [comment]
Hi @kiranbasvaraj , Xamarin is no longer supported, please refer to this doc https://devblogs.microsoft.com/identity/uwp-xamarin-msal-net-deprecation/.
It's MAUI that replaced Xamarin, I tried in our MAUI test app using Galaxy Nexus (Samsung device), all the rotate and scroll work fine in both embedded browser and system browser. Could you please update to MAUI and see if this issue will resolve? Thanks.
