### ISSUE TITLE
AbstractAcquireTokenParameterBuilder<T>.WithAdfsAuthority throws with a null TenantId when the authority host Uri ends in `/adfs`

### ISSUE THREAD

**Issue by christothes** [AzureAD/microsoft-authentication-library-for-dotnet#4860]
Azure.Identity recently changed from calling the deprecated:

```c#
AbstractAcquireTokenParameterBuilder<T>.WithAuthority(AuthorityHost.AbsoluteUri, tenantId);
```
to this: 
```c#
UriBuilder uriBuilder = new UriBuilder(AuthorityHost)
{
    Path = tenantId
};
builder.WithTenantIdFromAuthority(uriBuilder.Uri);
```

When `adfs` is passed as the tenantId, `WithTenantIdFromAuthority` throws because tenantId is null.

I looked at the MSAL code and this is the reason we end up with a null TenantId
 
[This](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4110b05894ef5ab39740ac4733c03f697530cf71/src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs#L311-L313) creates an AdfsAuthority which [hard codes null as the TenantId](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4110b05894ef5ab39740ac4733c03f697530cf71/src/client/Microsoft.Identity.Client/Instance/AdfsAuthority.cs#L63)
 
Ideally `WithTenantIdFromAuthority` should handle the ADFS case and do the same thing as `WithAuthority(AuthorityHost.AbsoluteUri, tenantId)` does.

**Comment by bgavrilMS** [comment]
What is the actual value of the uri in `WithTenantIdFromAuthority(uri)` ?

**Comment by christothes** [comment]
> 1. What is the actual value of the uri in `WithTenantIdFromAuthority(uri)` ? Someting like `https://somehost.com/adfs/`

yes, something like that.

> 2. How do you create the application object? Do you set WithAuthority(adfsAuthority) ? Or do you leave it as is?

We leave it as is, until we apply the tenantId, which is normally required. [Here is the specific example](https://github.com/Azure/azure-sdk-for-net/blob/203f6cdfd9e7dc991a24e0014bf89e693d7a2f7d/sdk/identity/Azure.Identity/src/MsalPublicClient.cs#L360-L366)

> If you leave it as is, the default is the AAD authority `https://login.microsoftonline.com/common`. Request can alter the tenant only, but not the host. If you set the authority in the CCA/PCA object as `https://somehost.com/adfs/` and then the same on the request, then I agree this is a bug and we can fix it.

Yes, that is effectively what we are doing in the code linked above.

**Comment by bgavrilMS** [comment]
Ok, so you do create the app with the correct authority ? 

 https://github.com/Azure/azure-sdk-for-net/blob/203f6cdfd9e7dc991a24e0014bf89e693d7a2f7d/sdk/identity/Azure.Identity/src/MsalPublicClient.cs#L45

Here ^^ the authority is set to `https://somehost.com/adfs/` ?

**Comment by christothes** [comment]
> Ok, so you do create the app with the correct authority ?
> 
> https://github.com/Azure/azure-sdk-for-net/blob/203f6cdfd9e7dc991a24e0014bf89e693d7a2f7d/sdk/identity/Azure.Identity/src/MsalPublicClient.cs#L45
> 
> Here ^^ the authority is set to `https://somehost.com/adfs/` ?

No - there it would be set only to `https://somehost.com/`. It is when the token is requested that we build up the tenantId using `WithTenantIdFromAuthority`

https://github.com/Azure/azure-sdk-for-net/blob/203f6cdfd9e7dc991a24e0014bf89e693d7a2f7d/sdk/identity/Azure.Identity/src/MsalPublicClient.cs#L360-L366

**Comment by johnypony3** [comment]
hi team, is there an update on this?

**Comment by bgavrilMS** [comment]
I think we fixed it in the lastest version of MSAL.NET ... Could you try?

**Comment by johnypony3** [comment]
I took over this project, I arrived here because the specific nuget package: `Azure.Identiy` was being flagged as a vulnerability.

Would this package be updated or should the project be using msal.net?

**Comment by bgavrilMS** [comment]
Just use the latest Azure.Identity and directly refernce Microsoft.Identity.Client version 4.65

**Comment by johnypony3** [comment]
My apologies, I missed your reply to this.

I attempted your suggestion, and it failed the same way.

I Completely forgot about this issue and opened a separate one with code here: https://github.com/Azure/azure-sdk-for-net/issues/47584

**Comment by johnypony3** [comment]
@bgavrilMS @christothes and I worked on an issue I opened under Azure.Identity and we found that the issue is reproduceable and it is still an issue with MSAL. Below is all of the info to reproduce the issue. Thanks everyone for their time.

I would also like to reiterate that I have followed the suggestion of adding the msal nuget package 4.65 and later. 

### Library name and version

Azure.Identity 1.13.1

### Describe the bug

Starting at 1.11.0 the code below does not work. If I downgrade to one version lower, 1.10.4 this code works without issue.

```csharp
using Azure.Core.Diagnostics;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Compute;
using Azure.ResourceManager.Network;
using Azure.ResourceManager.Resources;
using Azure.ResourceManager.Storage;

const string AZ_CLIENT_ID = "";
const string AZ_LOGIN_TENANT = "adfs";
const string AZ_PASS = "";
const string AZ_USER = "";
const string DEFAULT_TCP_RESOURCE_GROUP = "";
const string NAME = "";
const string SERIAL = "";

string LOGIN_ENDPOINT = $"https://login.{SERIAL}.microsoftdatabox.com";
string MANAGEMENT_ENDPOINT = $"https://management.{SERIAL}.microsoftdatabox.com";

using var listener = AzureEventSourceListener.CreateConsoleLogger();

var tokenOptions = new UsernamePasswordCredentialOptions
{
    AuthorityHost = new Uri(LOGIN_ENDPOINT),
    Diagnostics =
                {
                    IsLoggingContentEnabled = true,
                    LoggedHeaderNames = { "x-ms-request-id", "Authorization" },
                    LoggedQueryParameters = { "api-version" },
                }
};

var ArmClientOptions = new ArmClientOptions
{
    Environment = new ArmEnvironment(new Uri(MANAGEMENT_ENDPOINT), MANAGEMENT_ENDPOINT)
};

ArmClientOptions.SetApiVersion(ResourceGroupResource.ResourceType, "2019-10-01");
ArmClientOptions.SetApiVersion(VirtualMachineResource.ResourceType, "2020-06-01");
ArmClientOptions.SetApiVersion(DiskImageResource.ResourceType, "2020-06-01");
ArmClientOptions.SetApiVersion(VirtualNetworkResource.ResourceType, "2018-11-01");
ArmClientOptions.SetApiVersion(NetworkInterfaceResource.ResourceType, "2018-11-01");
ArmClientOptions.SetApiVersion(StorageAccountResource.ResourceType, "2019-06-01");
ArmClientOptions.SetApiVersion(BlobContainerResource.ResourceType, "2019-06-01");

var creds = new UsernamePasswordCredential(AZ_USER, AZ_PASS, AZ_LOGIN_TENANT, AZ_CLIENT_ID, tokenOptions);

ArmClient armClient = new(creds, "", ArmClientOptions);

var rgClient = armClient
    .GetDefaultSubscription()
    .GetResourceGroup(DEFAULT_TCP_RESOURCE_GROUP);
```

### Expected behavior

No erros

### Actual behavior

Errors with this:

```csharp
[Informational] Azure-Identity: UsernamePasswordCredential.GetToken invoked. Scopes: [ https://management.redacted.microsoftdatabox.com/.default ] ParentRequestId: 606ed31c-a999-48e3-bb8d-4b3d08c8da5b
[Informational] Azure-Identity: UsernamePasswordCredential.Authenticate invoked. Scopes: [ https://management.redacted.microsoftdatabox.com/.default ] ParentRequestId: 606ed31c-a999-48e3-bb8d-4b3d08c8da5b
[Informational] Azure-Identity: UsernamePasswordCredential.Authenticate was unable to retrieve an access token. Scopes: [ https://management.redacted.microsoftdatabox.com/.default ] ParentRequestId: 606ed31c-a999-48e3-bb8d-4b3d08c8da5b Exception: Azure.Identity.AuthenticationFailedException (0x80131500): UsernamePasswordCredential authentication failed: Value cannot be null. (Parameter 'tenantId')
See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/usernamepasswordcredential/troubleshoot
---> System.ArgumentNullException (0x80004003): Value cannot be null. (Parameter 'tenantId')
[Informational] Azure-Identity: UsernamePasswordCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.redacted.microsoftdatabox.com/.default ] ParentRequestId: 606ed31c-a999-48e3-bb8d-4b3d08c8da5b Exception: Azure.Identity.AuthenticationFailedException (0x80131500): UsernamePasswordCredential authentication failed: Value cannot be null. (Parameter 'tenantId')
See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/usernamepasswordcredential/troubleshoot
---> System.ArgumentNullException (0x80004003): Value cannot be null. (Parameter 'tenantId')
```

### Reproduction Steps

Change to version 1.11.0 or later to fail
Change to version 1.10.4 or earlier to work

### Environment

Windows, VS2022, .net 6 or 8

**ASE is disconnected**

**Comment by christothes** [comment]
The simplified repro is to call 

`AcquireTokenByUsernamePasswordParameterBuilder.WithTenantIdFromAuthority("https://login.1234.microsoftdatabox.com/adfs")`

which is what Azure.Identity does with an authority host value and tenantId value described above.

**Comment by johnypony3** [comment]
Thank you for the work @bgavrilMS! I see the code in main however the pipeline is failing. I have created an issue for [this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5043). We are still blocked.

**Comment by johnypony3** [comment]
Thank you, this indeed fixes the issue.
