### ISSUE TITLE
[Bug] AcquireTokenInteractive with WithUseEmbeddedWebView stopped working after upgrading library from version 4.58.1 to 4.62.0

### ISSUE THREAD

**Issue by jignesh-fandco** [AzureAD/microsoft-authentication-library-for-dotnet#4861]
### Library version used

4.62.0

### .NET version

C# UWP 
  <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.18362.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

Hi,

[Urgent]

One of my live Microsoft Store App (Written in UWP) is using Microsoft.Identity.Client nuget library. Following code was working perfectly well until i upgraded library from version 4.58.1 to 4.62.0

`PublicClientApplicationBuilder.Create(ClientId)
   .WithAuthority(AzureCloudInstance.AzurePublic, Tenant)
   .WithRedirectUri(redirectUri)
   .Build();

authResult = await app.AcquireTokenInteractive(scopes)
         .WithAccount(accounts.FirstOrDefault())
         .WithPrompt(Prompt.SelectAccount)
         .WithUseEmbeddedWebView(true)
         .ExecuteAsync();`

**After library version upgrade it starts throwing error**

Error Acquiring Token Silently: To enable the embedded webview on Windows, reference
Microsoft.Identity.Client.Desktop and call the extension method 
.WithWindowsEmbeddedBrowserSupport().

**But when i try to add Microsoft.Identity.Client.Desktop in my UWP app, it says library is not compatible with project.**

NU1202: Package Microsoft.Identity.Client.Desktop 4.62.0 is not compatible with
uap10.0.17763 (UAP,Version=v10.0.17763) / win10-x86-aot.

I don't understand what to do,
kindly advise.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by symbiogenesis** [comment]
Isn't UWP losing support? 

It said it isn't compatible with win10-x86-aot

I think only WinUI would support AOT. You probably need to downgrade until you port to WinUI.

**Comment by localden** [comment]
Please note that we [dropped support for UWP](https://devblogs.microsoft.com/identity/uwp-xamarin-msal-net-deprecation/). [4.60.4](https://www.nuget.org/packages/Microsoft.Identity.Client/4.60.4) is the last supported version that includes UWP binaries.
