### ISSUE TITLE
[Bug] SHA2 changes break custom claims

### ISSUE THREAD

**Issue by localden** [AzureAD/microsoft-authentication-library-for-dotnet#4868]
### Library version used

4.62.0

### .NET version

Cross-framework.

### Scenario

ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

In this PR ([Use SHA2 and PSS for client assertion (#4616)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/d2f015ad1daa38af744f66adda3cc6abec1cdc8b?diff=split&w=0)), MSAL totally revamps how it processes client claims and encodes them into the request token. For the Network Security Perimeter feature team, they use a client claim called "custom_claims" that can look like this:

```json
 “customClaims”: { 
     “xms_az_nwperimid”: ["GUID", "GUID2", "GUID3"]} 
```

The new code explicitly removes handling the client claim values as JSON and instead treats them as strings, putting double quotes around whatever is passed. 

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Hi @trwalke - any updates on this?

**Comment by trwalke** [comment]
Taking a look @localden
