### ISSUE TITLE
SFAuthenticationSession needs to be used on iOS 11 for SSO

### ISSUE THREAD

**Issue by onovotny** [AzureAD/microsoft-authentication-library-for-dotnet#489]
As is described here, https://www.pingidentity.com/en/company/blog/2017/08/08/single_sign-on_and_ios_11.html, on iOS 11 `SFAuthenticationSession` needs to be used for cross-app SSO to work.

**Comment by jennyf19** [comment]
SFAuthenticationSession and ASWebAuthenticationSession updates in [MSAL v2.2.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.2.0)  
@onovotny
