### ISSUE TITLE
[Bug] B2C Token not cached in PublicClientApplication (MAUI, MSAL.NET)

### ISSUE THREAD

**Issue by FREE2WIN2** [AzureAD/microsoft-authentication-library-for-dotnet#4896]
### Library version used

4.61.3

### .NET version

.net8-android

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

The token retrieved by AcquireTokenInteractive() is not cached. The call to GetAccountsAsync() always returns an empty collection.
This is very strange as all relevant details are present (tid, preferred_username) and all fields in the account within the result are set and valid. But the account and token are still not cached, making silent authentication impossible.

It is only a B2C issue as using a normal authority works fine.
And the specified ranges are the custom scope (<app-id-uri>/<scope>) + offline_access + openid
The B2C authority has the scheme https://{b2cname}.b2clogin.com/tfp/{b2cname}.onmicrosoft.com/{policy}/

### Relevant code snippets

```csharp
// Creation of the PublicClientApplication: (only once for my singleton service.)
var builder = PublicClientApplicationBuilder
   .Create(Constants.ApplicationId)
   .WithB2CAuthority(Constants.B2CAuthority)
   .WithRedirectUri($"msal{Constants.ApplicationId}://auth")
   .WithParentActivityOrWindow(() => Platform.CurrentActivity);

// AuthFlow (copied from the documentation):
var accounts = await this.IdentityClient.GetAccountsAsync().ConfigureAwait(false);
AuthenticationResult? result = null;
bool tryInteractiveLogin = false;
try
  {
    result = await this.IdentityClient
          .AcquireTokenSilent(Constants.Scopes, accounts.FirstOrDefault())
          .ExecuteAsync()
          .ConfigureAwait(false);
    }
    catch (MsalUiRequiredException)
    {
      tryInteractiveLogin = true;
    }
    catch (Exception ex)
    {
      Console.WriteLine($"MSAL Silent Error: {ex.Message}");
    }
    if (tryInteractiveLogin)
    {
      try
      {
        result = await this.IdentityClient
          .AcquireTokenInteractive(Constants.Scopes)
          .WithUseEmbeddedWebView(true)
          .WithParentActivityOrWindow(Platform.CurrentActivity)
          .ExecuteAsync()
          .ConfigureAwait(false);
      }
      catch (Exception ex)
      {
        Console.WriteLine($"MSAL Interactive Error: {ex.Message}");
      }
    }
     var accountAfter = (await this.IdentityClient.GetAccountsAsync().ConfigureAwait(false)).FirstOrDefault();
// -> accountAfter is null!
```

### Expected behavior

The accountAfter should be the same account given in the authentication result. But it is null.
Additionally the token should be cached but it is not.

### Identity provider

Azure B2C Custom Policy

**Comment by bgavrilMS** [comment]
What's your `Constants.B2CAuthority` ?

**Comment by FREE2WIN2** [comment]
its this scheme: https://{name}.b2clogin.com/tfp/{name}.onmicrosoft.com/{policy}/

**Comment by FREE2WIN2** [comment]
I have resolved the issue. The root cause was a **missing refresh token** due to the lack of administrator approval for the offline_access grant in the app registration.

**Comment by rayluo** [comment]
> > ### Issue description and reproduction steps
> > The token retrieved by AcquireTokenInteractive() is not cached. The call to GetAccountsAsync() always returns an empty collection. ... making silent authentication impossible.
>
> I have resolved the issue. The root cause was a **missing refresh token** due to the lack of administrator approval for the offline_access grant in the app registration.

But, even if a refresh token (RT) is missing, app shall still be able to do AcquireTokenSilent() to get the access token (AT).

I believe the symptom is caused by MSAL .Net's `GetAccountsAsync()` historically also uses RT existence as a search criteria. We may want to reconsider whether we can drop that criteria. @bgavrilMS
