### ISSUE TITLE
[Bug] AcquireTokenInteractive with WithPrompt(Prompt.ForceLogin) is overridden via existing PRT

### ISSUE THREAD

**Issue by halbyr** [AzureAD/microsoft-authentication-library-for-dotnet#4902]
### Library version used

Microsoft.Identity.Client.Desktop 4.60.3

### .NET version

net48

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

When calling AcquireTokenInteractive on PublicClientApplication with WithPrompt(Prompt.ForceLogin) the user is not allowed to enter password and the login credentials are overridden with the existing PRT.

### Relevant code snippets

```csharp
_app = PublicClientApplicationBuilder.Create(settings.ClientId)
            .WithLogging((level, message, _) =>
                    _logger.Log(GetLoggerLogLevel(level), message), LogLevel.Verbose, false)
            .WithTenantId(settings.ApplicationId)
            .WithDefaultRedirectUri()
            .WithParentActivityOrWindow(GetWindowHandle)
            .WithAuthority($"https://login.microsoftonline.com/{settings.ApplicationId}/")
            .WithWindowsDesktopFeatures(brokerOptions)
            .WithBroker(brokerOptions)
            .WithCacheOptions(CacheOptions.EnableSharedCacheOptions)
            .Build();

                    result = await _app.AcquireTokenInteractive(scopes)
                            .WithUseEmbeddedWebView(true)
                            .WithParentActivityOrWindow(GetWindowHandle())
                            .WithPrompt(Prompt.ForceLogin)
                            .ExecuteAsync()
                            .ConfigureAwait(false);
```

### Expected behavior

The user is asked to enter username and password and these entered credentials are used to request an OAuth2 token from the specified AAD authority. The credentials are not overridden by the existing PRT.

### Identity provider

Azure Active Directory Federation Services (ADFS)

### Solution and workarounds

Clearing the token cache doesn't work.

**Comment by bgavrilMS** [comment]
What are you trying to achieve with ForceLogin? 

Controlling the auth behavior is better controlled by the tenant admin via CA. For example https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-session-lifetime

**Comment by iulico-1** [comment]
@halbyr, please share more details on your e2e scenario. Logic that requires that client to control force prompt behavior usually indicates to a problematic calling pattern within your app.

**Comment by bgavrilMS** [comment]
Have a look at `WithExtraScopesToConsentTo` for combined consent for multiple resources. However, note that it might not work with WAM.

https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/desktop-mobile/acquiring-tokens-interactively#withextrascopestoconsent

**Comment by iulico-1** [comment]
Closing due to no recent action on this issue. Please reopen if required information is available.
