### ISSUE TITLE
[Bug] Incompatibility between wam_compat=2.0 and the resource params

### ISSUE THREAD

**Issue by exchange321** [AzureAD/microsoft-authentication-library-for-dotnet#4918]
### Library version used

4.61.3

### .NET version

.NET Framework 4.8

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

We've received an IcM ticket from a tenant stating that all their users are seeing the following error in the auth popup window starting 7th Aug 2024 when the app is requesting an OCPS token:
> Sorry, there was a problem signing in.
> Message: AADSTS901002: The ' resource' request parameter is not supported.

After reaching out to the eSTS team with the request and correlation IDs, the eSTS team provided the following original request params:
```
response_type=code
&client_id=xxxxxx
&redirect_uri=ms-appx-web://Microsoft.AAD.BrokerPlugin/xxxxxx
&resource=https://clients.config.office.net
&scope=offline_access openid profile
&prompt=login
&login_hint=xxxxxx
&response_mode=form_post
&wam_compat=2.0
&x-client-SKU=MSAL.xplat.Win32
&hsu=1
&x-client-Ver=1.1.0+local
&x-client-OS=10.0.22621.3672
&x-client-src-SKU=MSAL.xplat.Win32.runtime
&windows_api_version=2.0.1
&cxh_host=TB
&cxh_platform_version=10.0.22621
&tb-aad-env-id=10.0.22621.3672
&tb-aad-device-family=3
&is_remote_login_allowed=False
&webauthn=False
&x-ms-SsoFlags=False
```
and stated that when `wam_compat=2.0` is specified, the `resource` param is not allowed.

There is only one tenant reported ^ so far, and we are not able to reproduce the issue locally, likely because `wam_compat=2.0` is set conditionally.

As a result, we are reaching out to understand:
1. under what circumstances `wam_compat=2.0` is set
2. how our app knows when `wam_compat=2.0` is set
3. what the workaround of providing the `resource` param is when `wam_compat=2.0` is set

### Relevant code snippets

```csharp
AcquireTokenInteractiveParameterBuilder tokenBuilder = client.AcquireTokenInteractive(Array.Empty<string>())
    .WithParentActivityOrWindow(Window.Handle)
    .WithExtraQueryParameters(new Dictionary<string, string>
    {
        { "resource", "https://clients.config.office.net" },
    });

if (account != null)
{
    tokenBuilder.WithAccount(account);
}
else if (loginHint != null)
{
    tokenBuilder.WithLoginHint(loginHint);
}

return tokenBuilder.ExecuteAsync();
```

### Expected behavior

The following error should not occur and MSAL.NET should return the token successfully
> Message: AADSTS901002: The ' resource' request parameter is not supported.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by exchange321** [comment]
> Why are you adding "resource" via extra query parameters?

@bgavrilMS Hmm.... otherwise, how else can we specify requesting a OCPS (`https://clients.config.office.net`) token?

**Comment by rayluo** [comment]
> > Why are you adding "resource" via extra query parameters?
> 
> @bgavrilMS Hmm.... otherwise, how else can we specify requesting a OCPS (`https://clients.config.office.net`) token?

Entra ID (thus MSAL) uses "scope". Does that OCPS provide any docs describing what equivalent scope(s) that it supports? You may try the [".default" suffix](https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc#the-default-scope).

**Comment by exchange321** [comment]
I can confirm that `<token type URL>/.default` works as an alternative to the `resource` param for all the token types we need, although it's kinda bizarre that the `resource` param has been working for months without issues and only not working for 1 tenant recently. Closing this ticket. Thanks a lot for your help @bgavrilMS and @rayluo 👍
