### ISSUE TITLE
[Bug] Library tries to find VS install, fails, even though I have three VS installs

### ISSUE THREAD

**Issue by ryanmolden** [AzureAD/microsoft-authentication-library-for-dotnet#4925]
### Library version used

4.61.3

### .NET version

net462

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

This is in perfview.

I was debugging another couple of bugs I filed, and noticed this exeption indicating the library had attempted to, but failed to, find VS installs to try and use VS' authentication token (presumably).

![image](https://github.com/user-attachments/assets/5f428d59-b977-4310-833e-1e69886fab77)

Not sure what logic you are using but it appears broken as this machine has 3 VS installs.

I work at MS on VS (you can contact me internally at rmolden), so I can probably get you in contact with people that could show you how to do this location correctly.

### Expected behavior

If you are going to try to locate VS to try and use its authentication token, that location logic should probably work.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by crmann1** [comment]
This issue is not with MSAL, it is with https://github.com/Azure/azure-sdk-for-net

**Comment by bgavrilMS** [comment]
@ryanmolden - please reopen bug on Az.SDK. I'm not going to transfer this as they have a different bug template.
