### ISSUE TITLE
[Bug] Integrated Windows Authentication

### ISSUE THREAD

**Issue by william-msft** [AzureAD/microsoft-authentication-library-for-dotnet#4938]
### Library version used

msal-net

### .NET version

I'm trying to access prod db, from SAW using AME account, using [Connect to Production SQL Server | Container Apps TSG (eng.ms)](https://eng.ms/docs/cloud-ai-platform/devdiv/serverless-paas-balam/serverless-paas-vikr/azure-container-apps/container-apps-on-call-process-tsg/troubleshooting/sop/sop-111) and get these errors:
 
```
TITLE: Connect to Server
------------------------------
 
Cannot connect to capps-sql-japaneast.database.windows.net.
 
------------------------------
ADDITIONAL INFORMATION:
 
Failed to authenticate the user NT Authority\Anonymous Logon in Active Directory (Authentication=ActiveDirectoryIntegrated).
Error code 0xparsing_wstrust_response_failed
There was an error parsing the WS-Trust response from the endpoint. 
This may occur if there are issues with your ADFS configuration. See https://aka.ms/msal-net-iwa-troubleshooting for more details.
Enable logging to see more details. See https://aka.ms/msal-net-logging. (Microsoft SQL Server, Error: 0)
 
For help, click: https://docs.microsoft.com/sql/relational-databases/errors-events/mssqlserver-0-database-engine-error
 
------------------------------
BUTTONS:
 
OK
------------------------------
```
![image](https://github.com/user-attachments/assets/a623aade-a25d-465f-8055-a834c518fc91)
 
I can't find what Error 0 corresponds to.

### Scenario

Other - please specify

### Is this a new or an existing app?

None

### Issue description and reproduction steps

1. Open SQL Management Server using AME account with SAW
2. Connect to database, as show in screenshot. This produces error.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Please reach out to SQL team first. Let's not discuss this on GitHub.
