### ISSUE TITLE
[Bug] AcquireTokenInteractive fails with unknown_broker_error 

### ISSUE THREAD

**Issue by LKMMKL** [AzureAD/microsoft-authentication-library-for-dotnet#4953]
### Library version used

4.64.1

### .NET version

WPF APP
.NET Framework 4.8.1
Microsoft.Identity.Client, Version="4.64.1"
Microsoft.Identity.Client.Broker, Version="4.64.1"

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

1. Double click to run the [app demo](https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2.git)
2. Select an Account in auth window.
3. Click Next,  the window  disappear and  throw error.

Strangely, when you use a new app demo to  execute login process, the first time is ok, but using the same app afterwards has always been an error. I think some information saved locally may have caused the error, but I couldn't find it.

The Error Information:
![スクリーンショット (1)](https://github.com/user-attachments/assets/4f42903e-9d13-4ce0-bd4a-677071978c9e)

### Expected behavior

I hope it login success.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.64.1

**Comment by fengga** [comment]
@LKMMKL , I tried your app, signin always succeeds on my machine. It looks like the error was coming from WAM, can you remove the WAM account and try again? You can go to windows -> settings -> accounts, remove the account there, and try again in your app. You can also try to sign in another account in your app.

**Comment by fengga** [comment]
I noticed in your app it shows using .net 4.55.0, please consider update to the newest version first.
Also, error 0x80070525 is "The specified account does not exist", tag 0x2082320c is ERROR_NO_SUCH_USER. This error is coming from WAM, please remove the account from WAM (use the steps I mentioned above) and try again.

**Comment by fengga** [comment]
Can you respond to my last reply?

**Comment by fengga** [comment]
0x2082320c means you are trying to use a default account in WAM but the default account does not exist. Please check your WAM account page and set the accounts there. We are considering close this issue.
