### ISSUE TITLE
[Bug] iOS broker does not launch on IOS 18.0.1

### ISSUE THREAD

**Issue by stevencreaney** [AzureAD/microsoft-authentication-library-for-dotnet#4958]
### Library version used

4.65.0

### .NET version

8.0.403

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

This is a .Net MAUI app written for Windows/IOS.  We are leveraging the sample code provided in the MSAL MAUI sample.

This code previously worked just fine, but until IOS18.0.1 and XCode 16, plus any of the relevant updates from the dotnet workloads and nuget packages, this is now consistent.

When executing AcquireTokenInteractiveAsync on PublicClientApplication, the Task never returns and the application hangs.

```
return await PublicClientApplication.AcquireTokenInteractive(scopes)
.WithLoginHint(existingAccount?.Username ?? string.Empty)
.WithSystemWebViewOptions(systemWebViewOptions)
.WithParentActivityOrWindow(PlatformConfiguration.Instance.ParentWindow)
.ExecuteAsync()
.ConfigureAwait(false);
```

The last line of logging is:

> False MSAL 4.65.0.0 MSAL.Xamarin.iOS .NET 8.0.10 18.0.1 [2024-10-18 16:06:54Z] Invoking the iOS broker
> False MSAL 4.65.0.0 MSAL.Xamarin.iOS .NET 8.0.10 18.0.1 [2024-10-18 16:06:54Z] iOS Broker Payload Count: 16
> False MSAL 4.65.0.0 MSAL.Xamarin.iOS .NET 8.0.10 18.0.1 [2024-10-18 16:06:54Z] Starting waiting for broker response

We do see this in the device output:
> BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).

We noticed this appears to happen right here:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/97c51de3dcb87f4843b5767b5d73a6b5d82f4225/src/client/Microsoft.Identity.Client/Platforms/iOS/Broker/iOSBroker.cs#L210

### Relevant code snippets

```csharp
return await PublicClientApplication.AcquireTokenInteractive(scopes) .WithLoginHint(existingAccount?.Username ?? string.Empty).WithSystemWebViewOptions(systemWebViewOptions).WithParentActivityOrWindow(PlatformConfiguration.Instance.ParentWindow).ExecuteAsync().ConfigureAwait(false);
```

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Solution and workarounds

Implement the suggested code updates for UIApplication.open() vs UIApplication.openURL().

**Comment by bernardoif** [comment]
Hi, 

I'm facing the same problem here, is there any fix or workaround ? I've been trying multiple approaches without success.

This happens to me on iOS 18.0 and iOS 18.0.1

**Comment by noka03** [comment]
Im having the same issue.
In my case the issue presented itself only after calling RemoveAsync ie:
`await PublicClientApplication.RemoveAsync(user).ConfigureAwait(false);`
After calling this I was no longer able to communicate with the Microsoft Authenticator (Broker)

**Comment by noka03** [comment]
This is holding up my project.
Thanks for the fix.
When is the next scheduled release?

**Comment by bgavrilMS** [comment]
I am starting the release process, we will release in 1-2 days.
