### ISSUE TITLE
Token caching doesn't work with common tenant and on-behalf-of token acquisition

### ISSUE THREAD

**Issue by htuomola** [AzureAD/microsoft-authentication-library-for-dotnet#496]
**Repro steps:**
 1. Create instance of `ConfidentialClientApplication` using the constructor that doesn't take Authority as parameter - defaulting to common tenant
 2. Call `ConfidentialClientApplication.AcquireTokenOnBehalfOfAsync(IEnumerable<string> scopes, UserAssertion userAssertion)` twice with same parameters

**Expected**: Same token is returned for both calls (on second call, cached token is returned)
**Actual**: Two different tokens are returned, caching is not utilized

Tested first with `tags/1.1.0-preview` but also latest in `dev` (a8fe076a2768c72d3695ef89eb50c1eac0e39dcc). 

**Preliminary analysis** 
Looking at the  1.1.0-preview version, it seems that the matching cache entry gets filtered out in here:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/77891b760cf194991f1ab9939c5e3282de226055/src/Microsoft.Identity.Client/TokenCache.cs#L321

wherein `item.Authority` has value `https://login.microsoftonline.com/<tenantID>/`
but `requestParams.Authority.CanonicalAuthority` equals `https://login.microsoftonline.com/common/`. Not quite sure which way this should work but the Authority is always saved with explicit tenant ID value, here:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/77891b760cf194991f1ab9939c5e3282de226055/src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs#L195

Using the client constructor which takes authority parameter and passing `https://login.microsoftonline.com/<tenantID>/` bypasses the problem and acts as a workaround.

**Comment by htuomola** [comment]
Just noticed that there's an overload of `AcquireTokenOnBehalfOfAsync` which takes the authority as parameter as well. Tried it and with that the caching works as expected - which is a bit better workaround as the authority can be passed per-call and not at constructor time.

**Comment by jmprieur** [comment]
Thanks @htuomola. yes, this is the expected way.
