### ISSUE TITLE
[Bug] WithUseEmbeddedWebView(true) trigger OnSleep and OnResume on Android but not IOS 

### ISSUE THREAD

**Issue by JoacimWall** [AzureAD/microsoft-authentication-library-for-dotnet#4973]
### Library version used

4.66.1

### .NET version

Net 8.0.403 

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

The OnSleep and OnResume events should only be triggered when you leve the app. When we use a EmbeddedWebView(true) we should never leve the app. I just want to know is this expected behaviour or bug?   

### Identity provider

Azure B2C Custom Policy

**Comment by iulico-1** [comment]
@JoacimWall , can you please provide more context ? What did you mean by "we should never leve the app" ? I assume this is  about your application being suspended by the underlying OS and the behavior you are seeing across the two platforms is unexpected, but I need more details to make progress.

**Comment by JoacimWall** [comment]
> @JoacimWall , can you please provide more context ? What did you mean by "we should never leve the app" ? I assume this is about your application being suspended by the underlying OS and the behavior you are seeing across the two platforms is unexpected, but I need more details to make progress.

Hi we are using a WithUseEmbededWebView(true) then we are in the Mobile app and then the OS events OnSleep and OnResume should not be triggered. This events is triggered when you leave an app and when you reopen the app.  This Error is related to MAUI and is appearing on Android but not on iOS.

//Joacim

**Comment by iulico-1** [comment]
@JoacimWall, MSAL library doesn't control when the underlying OS decides to suspend your application.   WithUseEmbededWebView option doesn't change that behavior.
