### ISSUE TITLE
[Bug] UWP application fails WACK with latest version of Microsoft.Identity.Client

### ISSUE THREAD

**Issue by YakubMordon** [AzureAD/microsoft-authentication-library-for-dotnet#4978]
### Library version used

4.66.1

### .NET version

Microsoft.NETCore.UniversalWindowsPlatform 6.2.14

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

I have trouble with passing WACK using Microsoft.Identity.Client 4.66.1

To reproduce bug you need to:
1. Create UWP Application
2. Download Microsoft.Identity.Client 4.66.1 from NuGet
3. Publish application in Release mode
4. Perform WACK testing on application

End result should show such error:
![image](https://github.com/user-attachments/assets/3938f4c5-6398-412e-abb0-adc7217da34c)

### Expected behavior

WACK testing should pass Supported API test

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.29.0

### Solution and workarounds

Only workaround I found is to downgrade version of Microsoft.Identity.Client to version 4.29.0.
Maybe there's higher stable version of MSAL, but I hadn't looked at this

**Comment by bgavrilMS** [comment]
UWP is not longer supported. Please see: https://devblogs.microsoft.com/identity/uwp-xamarin-msal-net-deprecation/
