### ISSUE TITLE
Can not use MSAL in .net core console application

### ISSUE THREAD

**Issue by chenxizhang** [AzureAD/microsoft-authentication-library-for-dotnet#499]
`using System;
using Microsoft.Graph;
using Microsoft.Identity.Client;
using System.Linq;
using System.IO;

namespace consoleapp
{
    class Program
    {
        static void Main(string[] args)
        {
            IUser user = null;
            string CacheFilePath = System.Reflection.Assembly.GetExecutingAssembly().Location + ".msalcache.txt";
            object FileLock = new object();

            var tokenCache = new TokenCache();
            tokenCache.SetBeforeAccess((_args) => {
                //反序列化
                lock (FileLock)
                {
                    
                    _args.TokenCache.Deserialize(System.IO.File.Exists(CacheFilePath)
                        ? System.IO.File.ReadAllBytes(CacheFilePath)
                        : null);
                }

            });
            tokenCache.SetAfterAccess((_args) =>
            {
                //序列化
                if (_args.TokenCache.HasStateChanged)
                {
                    lock (FileLock)
                    {
                        System.IO.File.WriteAllBytes(CacheFilePath, _args.TokenCache.Serialize());
                        _args.TokenCache.HasStateChanged = false;
                    }
                }
            });

            var client = new PublicClientApplication("a1d42c27-29c4-4e8b-b08c-1ee417f2aa40", "https://login.microsoftonline.com/common/oauth2/authorize", tokenCache);
            if (client.Users != null && client.Users.Count() > 0)
                user = client.Users.First();

            var graph = new GraphServiceClient(new DelegateAuthenticationProvider(async(request)=> {

                var scope = new string[] { "user.read","mail.read","mail.send" };//动态权限，在注册时可以什么都不填
                AuthenticationResult token = null;
                try
                {
                    token = await client.AcquireTokenSilentAsync(scope, user);//这个方法会尝试用之前用户信息获取token，如果scope加大了，会重新要求授权，如果token过期了，或者在5分钟内将要过期，也会尝试用refreshtoken去换取新的token，如果出错，则会重新请求token
                }
                catch (Exception)
                {
                    token = await client.AcquireTokenAsync(scope);//弹出窗口要求用户授权
                    user = token.User;

                }

                request.Headers.Add("Authorization", $"Bearer {token.AccessToken}");
            }));

            var me = graph.Me.Request().GetAsync().Result;
            Console.WriteLine(me.DisplayName);
            var messages = graph.Me.Messages.Request().GetAsync().Result;
            Console.WriteLine(string.Join(Environment.NewLine, messages.Select(x => x.Subject)));

            Console.Read();
        }
    }
}
`

The error is 
![image](https://user-images.githubusercontent.com/1996954/32782857-b9b9aaa0-c984-11e7-9120-26d93385f85f.png)

**Comment by jmprieur** [comment]
@chenxizhang : .NET core does not provide any UI (in particular a Web view, which is needed for OAuth 2.0 / OIDC), so indeed, you cannot use AcquireTokenAsync() in .Net Core. 
you would have to use other flows like:
- for services/daemon applications, the client credentials grants (with an application secret, or a certificate). this is explained in https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential for ADAL.Net (but you can transpose to MSAL)
- the device profile grant where AzureAD provides you with a code which you then enter on a web page on another device which has a Web browser
See https://github.com/Azure-Samples/active-directory-dotnet-deviceprofile, which is for ADAL.Net, but which you can easily adapt as well.
HTH

**Comment by chenxizhang** [comment]
OK , I see . thank you @jmprieur
