### ISSUE TITLE
Msal.net does not build with recent versions of Visual Studio 2017

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#501]
**Repro steps**
- Install Visual Studio 2017.4.3. (all options to be sure that I'm not missing any frameworks)
- clone the msal repository
- open the MSAL.sln solution in Visual Studio.

**Expected:**
I can build the solution (possibly after updating the NuGet packages)

**Actual**
- after opening the solution for the first time, I get "Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Identity.Client could not be loaded"
- the Microsoft.Identity.client project's Dependencies node shows icons warnings (as the NuGet packages were not restored)
- The solution does not build

**Comment by kpanwar** [comment]
Visual Studio is terrible. You need to restore the packages from the command line using  "msbuild MSAL.sln /t:restore /p:configuration=release" and the use VS to build and develop.

**Comment by jmprieur** [comment]
Verified.
