### ISSUE TITLE
[Bug] If client_info is invalid, throw exception

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#5013]
### Library version used

4.63.1

### .NET version

9

### Scenario

ConfidentialClient - web site (AcquireTokenByAuthCode)

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

1. Use an IdP which returns a client_info, but instead of the expected format (base64url encoded version of {"uid": <guid>, "utid": <guid>"} it returns a bad value like "foo".

**Actual**: MSAL incorrectly ignores the bad format and returns a result with a bad AccountID
![image](https://github.com/user-attachments/assets/be9b0cf1-c819-4f9f-90ab-d3ca56449b80)

Expected: an exception stating that the Identity Provider sends incorrect values.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by rayluo** [comment]
> 1. Use an IdP which returns a client_info, but instead of the expected format (base64url encoded version of {"uid": , "utid": "} it returns a bad value like "foo".
> 
> **Actual**: MSAL incorrectly ignores the bad format and returns a result with a bad AccountID ![image](https://private-user-images.githubusercontent.com/12273384/392841191-be9b0cf1-c819-4f9f-90ab-d3ca56449b80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Mjc2MTEsIm5iZiI6MTczMzUyNzMxMSwicGF0aCI6Ii8xMjI3MzM4NC8zOTI4NDExOTEtYmU5YjBjZjEtYzgxOS00ZjlmLTkwYWItZDNjYTU2NDQ5YjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDIzMjE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNmQyYzRmMzZhMjlkOGIxM2Q2NmIzYzkxNDg1ZDRmZGI2Y2Y5MGIxMGI0OTE3NzJjMzUzNDYxMTA3YzliZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QvCuG1CSTJ0mHIaCxnnIJ8u_MiTlBopf-ukG2NGbzJw)
> 
> Expected: an exception stating that the Identity Provider sends incorrect values.

Good to know. The current behavior was probably caused by an overly aggressive exception handling, thus should be an easy fix for MSAL .Net.

But how do we want the fix to be? Does the new "exception stating that the Identity Provider sends incorrect values" have to be a specific one such as WrongClientInfo (which might then imply other MSALs would need to follow suit)? The status quo in other MSALs is presumably just throwing a default exception such as json decode error. I suppose that is fine, because it is rare.

**Comment by bgavrilMS** [comment]
Won't fix
