### ISSUE TITLE
Errors with Xamarin.Forms 2.5

### ISSUE THREAD

**Issue by cvanbeek13** [AzureAD/microsoft-authentication-library-for-dotnet#504]
I'm getting these build warnings when using this package in a Xamarin.Forms project with the Xamarin.Froms version 2.5.0.91635:

`2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Boolean.abc_action_bar_embed_tabs_pre_jb. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Boolean.abc_action_bar_expanded_action_views_exclusive. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Boolean.abc_config_allowActionMenuItemTextWithIcon. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Color.hint_foreground_material_dark. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Color.hint_foreground_material_light. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Dimension.abc_dialog_list_padding_vertical_material. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Dimension.abc_search_view_text_min_width. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_btn_rating_star_off_mtrl_alpha. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_btn_rating_star_on_mtrl_alpha. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_dialog_material_background_dark. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_dialog_material_background_light. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_ic_ab_back_mtrl_am_alpha. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_ic_clear_mtrl_alpha. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_ic_go_search_api_mtrl_alpha. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_ic_menu_moreoverflow_mtrl_alpha. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_ic_search_api_mtrl_alpha. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_ic_voice_search_api_mtrl_alpha. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Drawable.abc_ratingbar_full_material. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Integer.abc_max_action_buttons. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1344,2): warning XA0106: Skipping TestApp.Droid.Resource.Layout.notification_template_lines. Please check that your Nuget Package versions are compatible.`

This issue can be reproduced by creating a new Xamarin.Forms PCL project, updating the Xamarin.Forms NuGet to the newest version.  Then if you rebuild you should get no build warnings, but these warnings will show up after adding this NuGet package and rebuilding again. 

I'm currently using Microsoft.Identity.Client version 1.1.0-preview

**Comment by kpanwar** [comment]
Please try Microsoft.Identity.Client.1.1.1-alpha0412.nupkg from our MyGet feed at https://www.myget.org/F/aad-clients-nightly/api/v2

**Comment by cvanbeek13** [comment]
How do I add that package from Visual Studio?  Sorry, I've never used anything but NuGet

**Comment by kpanwar** [comment]
You need to add myget as a package source. Internet search will yield results for this

**Comment by jmprieur** [comment]
@cvanbeek13 : look at http://www.forevolve.com/en/articles/2017/08/06/how-to-use-a-custom-nuget-feed-in-visual-studio-2017/
- for the name you can use aad-clients-nightly,
- for the source you must use https://www.myget.org/F/aad-clients-nightly/api/v2

**Comment by jmprieur** [comment]
Verified. See also #507
