### ISSUE TITLE
Profile edit policy asks users to sign in again although they are already logged in

### ISSUE THREAD

**Issue by BtrJay** [AzureAD/microsoft-authentication-library-for-dotnet#505]
Hi all,

The issue was originally reported in https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/35

I've found this issue when I create a edit profile policy in Azure B2C and replicate the snippets from the sample.

The snippet below is from the Xamarin forms sample

https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient/MainPage.xaml.cs

// KNOWN ISSUE:
// User will get prompted
// to pick an IdP again.
AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, GetUserByPolicy(App.PCA.Users, App.PolicyEditProfile), UIBehavior.SelectAccount, string.Empty, null, App.AuthorityEditProfile, App.UiParent);

Are there any updates on this? Or any workarounds to handle profile editing without sign-in again?

Kind Regards,

Jay

**Comment by jmprieur** [comment]
@BtrJay : this is on the backlog to fix a certain number of issues with B2C, this one including.
There is no workaround, but did you try UIBehavior.Consent (that's a horrible hack, with no guaranty to work in the future but worked for me on .NET Desktop)

**Comment by jennyf19** [comment]
@BtrJay @dgonzalezp Fixed in [MSAL 2.5.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.5.0)
