### ISSUE TITLE
Support for IdentityServer / generic OIDC

### ISSUE THREAD

**Issue by hajekj** [AzureAD/microsoft-authentication-library-for-dotnet#506]
I believe it would be great if this library also supported [IdentityServer](https://github.com/IdentityServer/) as well (or generally any OIDC) since it makes it much easier to work with tokens, caching, refreshing etc.

The current options (using OIDC middleware) are [very poor](https://github.com/aspnet/Security/blob/5d802a798847f61c8c32368f5690a48caefbca97/samples/OpenIdConnectSample/Startup.cs#L164) and if this library supported the standard OIDC instances, it would be much better.

**Comment by jmprieur** [comment]
@hajekj : Thanks for your feedback
This is a goal for MSAL.NET to be OIDC compliant, but MSAL also offers (as you mentioned) other services which are tuned for AzureAD, enterprises features etc ....

**Comment by hajekj** [comment]
@jmprieur: As per the source code - the current instance discovery - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/1f49f5dbe17344e064d4d200559e36284aade1d5/src/Microsoft.Identity.Client/Internal/Instance/Authority.cs#L123 seems to allow only AAD and B2C instances unless I am wrong.

**Comment by jmprieur** [comment]
@hajekj, I see your point
you can always set validate authority to false.
