### ISSUE TITLE
MissingMethodException when calling _identityClient.AcquireTokenAsync() from later version of Xamarin Forms (Android)

### ISSUE THREAD

**Issue by cbarkerms** [AzureAD/microsoft-authentication-library-for-dotnet#507]
MissingMethodException is thrown if using a later version of Xamarin Forms.  I had to roll back to the following versions (which will not always be possible in the real-world):

  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.224" targetFramework="monoandroid71" />

Also, I had to call the following overload:

await _identityClient.AcquireTokenAsync(DelegatedPermissionScopes, uiParent);

Also not optimal as my code is in a .NET Standard library and sometimes I will instead need to call:

await _identityClient.AcquireTokenAsync(DelegatedPermissionScopes);

Depending on if uiParent is set.

Once I had implemented the above workarounds, I could proceed with the pre-release package rather than alpha:

  <package id="Microsoft.Identity.Client" version="1.1.0-preview" targetFramework="monoandroid71" />

I would like to:

a) Not have to implement any of those workarounds as they are not always possible in the real-world;
b) Be able to use the latest release/pre-release Nuget rather than an Alpha, which I cannot ship with.

**Comment by RhomGit** [comment]
Just to provide a little more info on this issue (its a real show stopper for my team):

`12-04 15:09:08.681 I/MonoDroid( 7872): UNHANDLED EXCEPTION:`
`12-04 15:09:08.716 I/MonoDroid( 7872): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.`
`12-04 15:09:08.716 I/MonoDroid( 7872):   at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e975227ac8644a30bb0866117325de0d>:0 `
`12-04 15:09:08.716 I/MonoDroid( 7872):   at (wrapper dynamic-method) System.Object:531367e7-3c77-4d76-add4-698e079c95b5 (intptr,intptr)`

**Comment by RhomGit** [comment]
Also, I have tried "1.1.1-alpha0414" from "aad-clients-nightly" and that stopped the app even running.

`12-04 15:19:50.695 I/MonoDroid( 8498): System.TypeInitializationException: The type initializer for 'Attribute' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field 'Microsoft.Identity.Client.Resource/Attribute.alpha' not found.`

**Comment by RhomGit** [comment]
For the thread on "MissingMethodException", refer: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/490

**Comment by cbarkerms** [comment]
I don't want to make the assumption that this is the same as issue #490.  There are definitely similar issues in there, but I also want to be clear that a requirement I have here is to be able to call a given overload for AcquireTokenAsync and ideally not have to do an ifdef per platform.

**Comment by jmprieur** [comment]
this should be fixed by #450

**Comment by cbarkerms** [comment]
@jmprieur - which nugget package version did this make it into?

**Comment by jmprieur** [comment]
If you want to try a pre-release, please check-out on MyGet
https://www.myget.org/F/aad-clients-nightly/api/v2
the latest nightly is prerealease 1.1.1-alpha0414

**Comment by cbarkerms** [comment]
thanks - when will this make it out of Alpha? We can't ship with Alpha.

**Comment by jmprieur** [comment]
We should release a non-alpha preview this week.
Without releasing, did you try out the alpha0414 to check that this solves your problem?

**Comment by cbarkerms** [comment]
Yes.  The Alpha resolves the main part of the problem, but IIRC it still means I need to call the appropriate override:

For Android:
await _identityClient.AcquireTokenAsync(DelegatedPermissionScopes, uiParent);

For UWP:
await _identityClient.AcquireTokenAsync(DelegatedPermissionScopes);

Not a big deal, but it would be nice if this was taken care of for me to prevent forking code.

**Comment by jmprieur** [comment]
for the uiParent, I think it would be better to raise another issue (this one was for the exception). Or it it related? Did you tryin in UWP to use an empty UIParent instance? or just pass null?

**Comment by cbarkerms** [comment]
passing null is actually what i am doing right now, but i wasn't sure whether that would have adverse effects. thanks!

**Comment by jmprieur** [comment]
This won't, the override you call for UWP actually calls the an implementation method passing null. The same implementation method is called by the override you use for Android.
Closing this issue for now.
