### ISSUE TITLE
Wants to Use "Azure.com" to Sign In - iOS 11

### ISSUE THREAD

**Issue by robintschroeder** [AzureAD/microsoft-authentication-library-for-dotnet#512]
Using the Getting this message for release builds on iOS 11 (Xamarin.Forms, Xamarin.iOS). 
Is there anyway to modify the message or prevent it from appearing?

![azure _permissions](https://user-images.githubusercontent.com/29012597/33736712-3d3deaf4-db59-11e7-9336-552df2fc092d.png)

Thanks in advance

**Comment by jmprieur** [comment]
We cannot change it. This is an operating system level call.

**Comment by bukkabalakrishna** [comment]
@jmprieur  I am facing something similar and thought of posting my question here. Please let me know if I need to create a new ticket. 

                   In my ios app i am seeing a similar dialogue asking for permission as below and I understand why that is happening. Is there any way I can show the full tenant url (something like https://<tenantName>.b2clogin.com> instead of just "b2clogin.com"? in the dialogue box. 

![image](https://user-images.githubusercontent.com/15980608/50649032-c2b2b900-0f4a-11e9-9842-08a336998f73.png)

**Comment by jennyf19** [comment]
@bukkabalakrishna This pops up anytime the app uses SFAuthenticationSession or ASWebAuthenticationSession, we cannot change what is displayed there, as that is the point of the pop up. From Apple's developer site: " users are prompted by a dialog to give explicit consent, allowing the application to access the website’s data in Safari. When the webpage is presented, it runs in a separate process, so the user and web service are guaranteed that the app has no way to gain access to the user’s credentials. "

**Comment by NextSteps79** [comment]
feature request property management Readme.md.
rss sindicalice raw master github/NextSteps79
