### ISSUE TITLE
ConfidentialClientApplication.AcquireTokenForClientAsync Rejects Most Scopes?

### ISSUE THREAD

**Issue by MattHoneycutt** [AzureAD/microsoft-authentication-library-for-dotnet#516]
I've followed along with the dotnet-tutorial project, and using that, I was able to get the tutorial app to talk to my Office 365 account just fine.  Everything worked as intended.  But that sample actually uses MSAL for authenticate via OWIN.  That's not what I need.

In my application, authentication is handled separately and does not use OWIN.

Instead, what I'm trying to do is use ```ConfidentialClientApplication.AcquireTokenForClientAsync``` to get a token so that I can access the user's calendar, etc.  

The problem is that calling ```ConfidentialClientApplication.AcquireTokenForClientAsync``` with anything other than this single, default scope ("https://graph.microsoft.com/.default") returns an error like the following: ```AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/.default https://graph.microsoft.com/User.Read is not valid.```  I've tried using just "User.Read", too, and just about every other possible thing I could think of passing. :)

It's quite possible I'm going about this the wrong way and not using the correct method(s) or classes.  Is there something else I should be looking at instead?  Are there examples of a lighter-weight integration that doesn't require hooking in everything and having to use OWIN combined with MSAL for authentication? 

Thanks!

**Comment by jmprieur** [comment]
@MattHoneycutt : which kind of application is it? is it an ASP.NET web application?

**Comment by MattHoneycutt** [comment]
@jmprieur It's really an Angular SPA with Web API on the backend.

**Comment by Socrathustra** [comment]
Did you resolve this issue? I am having the same problem. I'm probably just going to use the HttpContext to put the request together manually at this point. I can't figure out what's wrong.

**Comment by MattHoneycutt** [comment]
Not to my satisfaction, no.  I ended up just letting OWIN handle it, but the solution never felt right.  I think the API turned out to be more of a hindrance than a help in my case.

**Comment by jmprieur** [comment]
@MattHoneycutt  I guess you should rather use MSAL.js (not MSAL.NET) ?

**Comment by jmprieur** [comment]
Closing as this is rather an ADAL.js issue.
BTW ADAL.js now has wrappers for Angular.js and Angular 2+

**Comment by omerlh** [comment]
I'm experiencing a similar issue - trying to use `AcquireTokenForClientAsync` to request a token for a specific AD application, using another AD application. I take the scope from Azure AD portal (the preview, the one that shows the scopes) and tried to use it to acquire a token, but the request failed with the same issue. Can you please help?

**Comment by jmprieur** [comment]
@omerlh 
for a given resource, `AcquireTokenForClientAsnc` takes only one possible scope which is "{resource}/.default". For instance if the resource is Microsoft Graph, this would be "https://graph.microsoft.com/.default". 

Did you read MSAL.NET's conceptual documentation: https://aka.ms/msal-net-client-credentials, and in particular https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows#scopes-to-request

**Comment by omerlh** [comment]
Sorry, no - my mistake. I saw the comment - but I assumed that if this scope was valid, it will be displayed in the portal. Thanks!
