### ISSUE TITLE
Client Info is null

### ISSUE THREAD

**Issue by rfcdejong** [AzureAD/microsoft-authentication-library-for-dotnet#517]
Is it possible to make client_info optional? As of this week the microsoft oauth2 NativeFlow does not accept a client_info anymore "AADSTS50179: client_info is not supported for this flow". Perhaps we can work around it by adding a custom dummy claim to the tokendata, but the client_info is just containing a dummy value..

**Comment by shiungyong** [comment]
Raymond, can you reach out to me over email at shiungy at microsoft.com? I'd like to get more details on the issue you're running into here.

**Comment by rfcdejong** [comment]
The change has been reverted by microsoft to make it compatible again with the native flow by a priority ticket. I asked a co-worker of my to contact you about the issue and ticket. It would still be nice if the client_info can be made optional since it is of no use anyway.

**Comment by shiungyong** [comment]
Thanks Raymond, I'll wait for the additional information.

You are correct that client_info is of no use to the application but it plays a critical role in how the underlying framework behaves, so the failure is unexpected and we would like to debug this further.
