### ISSUE TITLE
Link in Step 3 of readme is not working

### ISSUE THREAD

**Issue by melwil** [AzureAD/microsoft-authentication-library-for-dotnet#521]
The link in question goes here:

https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/master/active-directory-wpf-nodejs-webapi-v2/MainWindow.xaml.cs#L84

**Comment by jmprieur** [comment]
thanks for the heads-up.
Fixed by commit #bbc2d92
