### ISSUE TITLE
Calling Graph API using B2C and MSAL

### ISSUE THREAD

**Issue by MrCharli3** [AzureAD/microsoft-authentication-library-for-dotnet#526]
There are no publicly documented samples where we use Azure B2C and MSAL authentication to call the Graph API. Only [samples ](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet)of using B2C to call Graph API uses ADAL. And the MS [samples ](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-web-dotnet-susi) for B2C uses MSAL. Has me really confused of what I'm supposed to use.

Is there no way I can use B2C and MSAL to call the Graph API? Then how can I suggest to my customers to use MSAL?

**Comment by jmprieur** [comment]
I think that the 7 following B2C samples all use MSAL.Net
https://github.com/Azure-Samples?utf8=%E2%9C%93&q=b2C++dotnet&type=&language=

I think that if you use a Graph scope (for instance "User.Read") instead of a scope for the Web API, this should work.

**Comment by jmprieur** [comment]
The Graph API cannot be called by B2C at the moment.
Adding @parakhj for elaborating.

**Comment by parakhj** [comment]
The graph API does not accept B2C tokens (B2C tokens are different than AAD tokens since they are two different services).

**Comment by valuesoft-dk** [comment]
Then how to get more information about the B2C-signed in user, clientside ? For instance what groups the user is member of ? Or any of the other things you can do with https://graph.microsoft.com and https://graph.windows.net ?

**Comment by jmprieur** [comment]
@valuesoft-dk 
@parakhj or @SaeedAkhter-MSFT will confirm, but my impression is that with B2C you use social identities, whereas the notion of groups is something that's in Azure AD (not social identities), therefore I'd think that if you want to use your you'd want to use Azure AD directly?

**Comment by NikolaosWakem** [comment]
Having put a B2C product into production - would I touch it again? Never.. it’s a complete white elephant with almost no support and zero resource being put into it by Microsoft.. my advice would be to avoid like the plague

**Comment by valnav** [comment]
@NikolaosWakem We are investing resources towards Azure AD B2C and would love to understand the issues you faced. If possible, we can setup a phone conversation to discuss this.

@valuesoft-dk - You are correct **Azure AD B2C is for local accounts as well**. I wanted to clarify your statement.
> At first its sounds nice, but reading further then:
Important: To use the Graph API with your B2C tenant, you need to register an application using the App Registrations service in the Azure portal, NOT Azure AD B2C's Applications menu. The following instructions lead you to the appropriate menu. You can't reuse existing B2C applications that you registered in the Azure AD B2C's Applications menu.
... so wrong path.

The example: [Azure AD B2C: Use the Azure AD Graph API](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet) you mentioned will get the user info and claims for your scenario. Even though you are registering the application under the App Registrations in the Azure Portal - it is still in the context of the B2C Tenant. We are working towards combining the two app registrations into one, which would remove the confusion. Please let me know if you are still facing issues.

**Comment by valuesoft-dk** [comment]
Can you point me to a working sample that demonstrates just that ? It's Angular (not AngularJS), so TypeScript or JavaScript its fine.

**Comment by valnav** [comment]
@valuesoft-dk  You can take a look at this sample [b2c-webapp-webapi](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/). it gives you an idea on how to do this.

**Comment by Journeyman42** [comment]
@valnav 

I have exactly the same issue as @valuesoft-dk although I am implementing a Xamarin forms app using MSAL. The appeal of doing this was so I could allow users to sign up via email and then use the resulting token to call a secured API in the active directory

It's utterly bizarre to me that you allow a user to be created and a token returned which is of absolutely no use to the software if you wish to utilise claims, which almost everyone will want to do, without registering a second app and - in my case - embedding a client secret within the app itself. This used to be part of ADAL but was deprecated for what I think was obvious reason!

Is there an example please of the flow for a native app wishing to access an API but also make use of claims for the users who sign up as in my case?

**Comment by GNMurthy1982** [comment]
Hi All, 
I have created two applications  one is for ASP.Net WEB API and WEB APP under Azure AD B2C applications (Home  -> Azure AD B2C - Applications)
I gave read wright access for Web API and I am able to call API from WEB APP using azure B2C OpenIdConnectAuthentication. Now I would like to  call AAD Graph API from WEB API to read and modify user data. Please provide a samples for this scenario.

**Comment by jmprieur** [comment]
@GNMurthy1982 which social identity are you using?

**Comment by GNMurthy1982** [comment]
We are using local account.

**Comment by jmprieur** [comment]
cc: @valnav

**Comment by stephlocke** [comment]
Is there now a sample for SPA + MSAL + Graph for retrieving properties of B2C users?  I can see folks have managed to get it working inside this Vue extension https://github.com/mvertopoulos/vue-msal/blob/master/lib/src/main.ts#L156 but I could do with a non-typescript standalone js code sample to crib from.

**Comment by savcic-milorad** [comment]
Any updates on this issue?

**Comment by mk48** [comment]
anyone got solution?

**Comment by bgavrilMS** [comment]
@mk48 - do you mean how to use https://learn.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-operations ? Where did you get stuck?

**Comment by mk48** [comment]
i wanted to get userinfo in AD-B2C, thanks for sharing that link, i will watch and update.

**Comment by KalanaDananjaya** [comment]
This article https://learn.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-operations shows that you can in fact call MS Graph using AD-B2C app registration(But without any samples). When I try to call Graph API with AD-B2C token it gives back a 401 response with the following error. 

API Call : 
```
curl 'https://graph.microsoft.com/v1.0/me' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3000' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'authorization: Bearer ***' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed 
```

Response: 
```
{
  "error":{
    "code":"InvalidAuthenticationToken",
    "message":"Access token validation failure. Invalid audience.",
    "innerError":{
      "date":"2023-01-09T01:58:21",
      "request-id":"***",
      "client-request-id":"***"
    }
  }
}
```

Following is my token payload.

```
{
  "exp": 1673233100,
  "nbf": 1673229500,
  "ver": "1.0",
  "iss": "https://sunbeamorg.b2clogin.com/65b41437-4de2-48bf-8708-f6bb84a65d44/v2.0/",
  "sub": "d5d12e23-a506-49ac-93dd-d59125bfcd06",
  "aud": "663cd27b-26cf-4d90-b101-90bc370395a1",
  "nonce": "ff88c979-5856-42b2-b888-f34f1c854b0b",
  "iat": 1673229500,
  "auth_time": 1673229497,
  "city": "Kurunegala",
  "given_name": "Kalana",
  "family_name": "Wijethunga",
  "extension_testRole": "adminKal",
  "tfp": "B2C_1_signup"
}
```



In forums it says AD-B2C tokens does not support MS Graph API calls, but azure documentation explains like it can. I am not sure which one is right.

**Comment by jmprieur** [comment]
@KalanaDananjaya 
You can call graph to administer a b2c tenants (manage apps, users etc ...). in that case you are using the B2c application as an aad application.

You cannot call Microsoft graph on behalf of a user in a b2c tenant
