### ISSUE TITLE
System.NullReferenceException at Microsoft.Identity.Client.WebUI.SetAuthorizationResult(AuthorizationResult authorizationResultInput)

### ISSUE THREAD

**Issue by ruchiverma6** [AzureAD/microsoft-authentication-library-for-dotnet#529]
We are using xamarin forms for mobile app development.

we are getting following crash System.NullReferenceException at Microsoft.Identity.Client.WebUI.SetAuthorizationResult

Please find full crash logs:

Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
Microsoft.Identity.Client.WebUI.SetAuthorizationResult(AuthorizationResult authorizationResultInput):
Microsoft.Identity.Client.AuthenticationAgentContinuationHelper.SetAuthenticationAgentContinuationEventArgs(int requestCode, Result resultCode, Intent data):
LoginHelper.SetAuthenticationAgentContinuationEventArgs(int requestCode, Result resultCode, Intent data):
OnActivityResult(int requestCode, Result resultCode, Intent data):
Android.App.Activity.n_OnActivityResult_IILandroid_content_Intent_(IntPtr jnienv, IntPtr native__this, int requestCode, int native_resultCode, IntPtr native_data):
at (wrapper dynamic-method) System.Object:5f5859b2-a48e-4a91-86dd-f7939b3d5e43 (intptr,intptr,int,int,intptr)

**Comment by jmprieur** [comment]
which version of MSAL.Net are you using? 1.1.1-preview0040 ?
which version of Xamarin forms are you referencing?

**Comment by ruchiverma6** [comment]
MSAL Microsoft.identity.client version 1.0.304142221-alpha

Xamarin.Forms version 2.3.4.270

**Comment by jmprieur** [comment]
Can you please try with MSAL preview 1.1.2 ? 
you might want to read the following [wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Troubleshooting-Xamarin.Android-issues-with-MSAL)
cc:  @jennyf19

**Comment by henrik-me** [comment]
@ruchiverma6 did you try out the latest MSAL preview release?

**Comment by ruchiverma6** [comment]
I was using  MSAL Microsoft.identity.client version 1.0.304142221-alpha.

I tried updating Microsoft.Identity.Client.1.1.2-preview0008  for xamarin project.
After updating to Microsoft.Identity.Client.1.1.2-preview0008 successfully.
I am using xamarin.form to Xamarin.Forms.2.5.0.280555.
I am using android.support library having versions 25.4.0.2.

After updating, my existing code it is giving build errors related to:
**The type or namespace name 'IPlatformParameters' could not be found (are you missing a using directive or an assembly reference**

Unable to solve these errors
Also I got on link specifying 
https://libraries.io/nuget/Microsoft.Identity.Client

**Comment by jennyf19** [comment]
@ruchiverma6 - Sorry you're having issues with this. MSAL does not use `PlatformParameters`, that is used in ADAL (our older authentication library). Can you make sure there are no references to ADAL in the nuget package manager?
Also, can you please send me the exact Acquire Token method you are using?
Here is the official [Nuget site](https://www.nuget.org/packages/Microsoft.Identity.Client/1.1.2-preview0008), not sure why are you are getting redirected to the one you listed above.
Once I hear back from you, we will continue working on this.

**Comment by jmprieur** [comment]
Closing this one as we did not hear from you @ruchiverma6 
Please re-open if you still experience the issue
