### ISSUE TITLE
MsalServiceException: returned user identifier does not match the sent user identifier SaveTokenResponseToCache 

### ISSUE THREAD

**Issue by markti** [AzureAD/microsoft-authentication-library-for-dotnet#533]
I keep getting this after I login and am redirected back to my Xamarin application using the msal[application id]://auth return url...and i'm not sure why...

**Comment by SomkaPe** [comment]
This happens If  you send a login hint or User into the acquireToken call,  and sign in with a different account

**Comment by markti** [comment]
so should I always pass a null user object to the AcquireTokenAsync method? I'm using the standard GetUserByPolicy(...) method that is provided in the sample code...

**Comment by markti** [comment]
```
            try
            {
                var usr = GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn);
                AuthenticationResult ar = await App.PCA.AcquireTokenSilentAsync(App.Scopes, usr, App.Authority, false);
                UpdateUserInfo(ar);
                UpdateSignInState(true);
            }
            catch (Exception ex)
            {
                // Uncomment for debugging purposes
                //await DisplayAlert($"Exception:", ex.ToString(), "Dismiss");

                // Doesn't matter, we go in interactive mode
                UpdateSignInState(false);
            }
```

**Comment by SomkaPe** [comment]
which sample are you using ?

**Comment by markti** [comment]
active-directory-b2c-Xamarin-native

**Comment by markti** [comment]
but i've re-created it in a clean project....

**Comment by markti** [comment]
i have gotten it to work...in my clean environment...but it seems to be stuck now... i kept deleting the account after I register and get it all working on register, then this issue pops up.

**Comment by markti** [comment]
there is only one user in the PCA.Users collection...maybe the old user object is cached and it isn't getting cleared out...

**Comment by markti** [comment]
I've restarted the android emulator...but the issue still seems to persist.

**Comment by markti** [comment]
it was cached....had to uninstall the app from the emulator...only way to clear the cache...!!

**Comment by jmprieur** [comment]
Thanks for the heads-up, @markti 

In MSAL.NET, users are represented by the ``IUser`` interface. These are available as a collection of users ``Users`` in the application.

![image](https://user-images.githubusercontent.com/13203188/36192204-da04d5d6-1160-11e8-8b1e-4e3ce356d11b.png)

It is possible, from the application to remove a given user, which removes it from the cache.
To clear the cache:
```CSharp
foreach(IUser user in application.Users.ToArray())
{
 application.Remove(user);
}
```
> the ToArray() is here to avoid getting an exception because the collection would be changed while being iterated

**Comment by upskydownshoes** [comment]
Had same problem. Putting @jmprieur suggestion in the sign in buttons code fixed it thanks! So with the recent switch from IUser to IAccount it looks as so:

    async void OnSignInSignOut(object sender, EventArgs e)
            {                            
                IEnumerable<IAccount> accounts = await App.PCA.GetAccountsAsync();
                try
                {
                    if (btnSignInSignOut.Text == "Sign in")
                    {
                        
          //jmpriers suggestion start
         foreach (IAccount user in await App.PCA.GetAccountsAsync())
                            {
                            await App.PCA.RemoveAsync(user);
                            }
         //jmpriers suggestion end

                             AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, 
    GetAccountByPolicy(accounts, App.PolicySignUpSignIn), App.UiParent);
                        UpdateUserInfo(ar);
                        UpdateSignInState(true);
                    }
                    else
                {
                        while (accounts.Any())
                        {
                            await App.PCA.RemoveAsync(accounts.FirstOrDefault());
                            accounts = await App.PCA.GetAccountsAsync();
                        }
                        UpdateSignInState(false);
                    }
                }
                catch (Exception ex)
                {
                
                    if (ex.Message.Contains("AADB2C90118"))
                        OnPasswordReset();
                    // Alert if any exception excludig user cancelling sign-in dialog
                    else if (((ex as MsalException)?.ErrorCode != "authentication_canceled"))
                        await DisplayAlert($"Exception:", ex.ToString(), "Dismiss");
                }
            }
