### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#535]
![image](https://user-images.githubusercontent.com/13203188/37057063-1076865a-217e-11e8-862b-e2211642175d.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/37057928-dbf8f4dc-2180-11e8-808b-75deb15b3b70.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/37058781-7a0914e8-2183-11e8-92cd-41d1ca94390c.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/37063988-40e52368-2193-11e8-887e-e86b97c54d19.png)

![image](https://user-images.githubusercontent.com/13203188/37064286-39d466e6-2194-11e8-9df9-b5f9ab36567e.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/37081843-a3bf7886-21e2-11e8-8899-2b81f0bb48e3.png)

![image](https://user-images.githubusercontent.com/13203188/37081859-b8589822-21e2-11e8-9e1b-d68768a128ff.png)

![image](https://user-images.githubusercontent.com/13203188/37081919-ed8ca2b8-21e2-11e8-935f-9c56b9172e5f.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/37082180-afc4b708-21e3-11e8-8af8-a6dcbd2dfba8.png)

![image](https://user-images.githubusercontent.com/13203188/37082196-bc727314-21e3-11e8-8f0f-2ac81c9b955c.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/37082327-3716113e-21e4-11e8-921a-31f052ccdd84.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/37082863-968a8892-21e5-11e8-981a-2b1000f45da4.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/37083057-3dc4a566-21e6-11e8-86a4-34de333fe820.png)

![image](https://user-images.githubusercontent.com/13203188/37083135-7fbd06c0-21e6-11e8-9935-c878b5c12ddc.png)

**Comment by jennyf19** [comment]
![systembrowsermsal](https://user-images.githubusercontent.com/19942418/40319616-a563346c-5cdd-11e8-82d3-2328bef9c172.PNG)

**Comment by jennyf19** [comment]
![systembrowsermsalandroid](https://user-images.githubusercontent.com/19942418/40319632-add78210-5cdd-11e8-9b09-71735d5792df.PNG)

**Comment by jennyf19** [comment]
![embeddedmsalandroid](https://user-images.githubusercontent.com/19942418/40319714-f5df7a36-5cdd-11e8-9efc-9f1b6661f4be.PNG)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/44098875-9b7d9e64-9fe1-11e8-82a0-d70029e6cbb6.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/44657759-4f2df780-a9fe-11e8-97d1-1abbffade340.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/44658598-b26d5900-aa01-11e8-9c91-e40972c27e30.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/44658761-2ad41a00-aa02-11e8-9f6e-d8e8d5f0baaf.png)

![image](https://user-images.githubusercontent.com/13203188/44658812-5eaf3f80-aa02-11e8-9f4a-0f815d4af947.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/44722040-19574480-aacc-11e8-8d88-96e20eb89919.png)

![image](https://user-images.githubusercontent.com/13203188/44722109-4efc2d80-aacc-11e8-8597-5aac8088ffb5.png)

![image](https://user-images.githubusercontent.com/13203188/44722143-73f0a080-aacc-11e8-9ea7-3a5afd622dca.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/44722725-3ab93000-aace-11e8-8f14-ef350bc975b9.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/44849863-4e6caf80-ac10-11e8-8e4b-c59452d14ccf.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/44856370-166e6800-ac22-11e8-90f9-65d31e86ae92.png)

![image](https://user-images.githubusercontent.com/13203188/44856646-c93ec600-ac22-11e8-85d0-12eaa505b123.png)

![image](https://user-images.githubusercontent.com/13203188/44856653-cd6ae380-ac22-11e8-95d7-52527361ff89.png)

![image](https://user-images.githubusercontent.com/13203188/44856666-d3f95b00-ac22-11e8-83ca-c299e89916c5.png)

![image](https://user-images.githubusercontent.com/13203188/44856673-d78ce200-ac22-11e8-80ab-92b901619f42.png)

![image](https://user-images.githubusercontent.com/13203188/44856679-db206900-ac22-11e8-877a-9a1e6a6d0c75.png)

![image](https://user-images.githubusercontent.com/13203188/44856682-df4c8680-ac22-11e8-9fb0-d51d8673b04a.png)

![image](https://user-images.githubusercontent.com/13203188/44856748-060abd00-ac23-11e8-8b69-cbe928bec23c.png)

![image](https://user-images.githubusercontent.com/13203188/44856754-0c993480-ac23-11e8-82ef-e0eaa586b9c8.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/45366759-6dfec300-b594-11e8-914f-2e24de669e09.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/46328474-4364c080-c5bc-11e8-8865-582d1933eb2d.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/48255596-801ea580-e40d-11e8-8c26-cf167388d5c4.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/49435190-4f385300-f7b6-11e8-8a83-7e468e5fd124.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/51684356-28471200-1fec-11e9-937a-009f02268aae.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/53400353-f5f35080-39ad-11e9-8270-7e12e34a4ac4.png)

**Comment by jmprieur** [comment]
Confidential client apps

![image](https://user-images.githubusercontent.com/13203188/53402109-60f25680-39b1-11e9-868a-0dcad865cb31.png) ![image](https://user-images.githubusercontent.com/13203188/53402132-6ea7dc00-39b1-11e9-8c59-79d39e38f6bd.png) ![image](https://user-images.githubusercontent.com/13203188/53402143-74052680-39b1-11e9-9c8e-57cdca0a9c1d.png)

**Comment by jmprieur** [comment]
Public client applications
  ![image](https://user-images.githubusercontent.com/13203188/53402429-05749880-39b2-11e9-809e-d29f38a77bff.png)  ![image](https://user-images.githubusercontent.com/13203188/53402444-0a394c80-39b2-11e9-9b0c-2a71eb2ac819.png)
![image](https://user-images.githubusercontent.com/13203188/53403025-1f62ab00-39b3-11e9-9597-af6fd420a61f.png)

**Comment by jmprieur** [comment]
Interfaces on apps
![image](https://user-images.githubusercontent.com/13203188/53404448-04456a80-39b6-11e9-967b-51399ecdfbdb.png)

Builders
![image](https://user-images.githubusercontent.com/13203188/53405198-98fc9800-39b7-11e9-80fb-802361fc1707.png)

**Comment by jmprieur** [comment]
Application options

![image](https://user-images.githubusercontent.com/13203188/53407720-1971c780-39bd-11e9-97cb-4f82cd3610de.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/53432175-51dfc880-39f2-11e9-958a-f513a62b394c.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/55964057-4976e080-5c74-11e9-8880-b8f631e38da0.png)

![image](https://user-images.githubusercontent.com/13203188/55964069-4e3b9480-5c74-11e9-8d8c-cbd9ec08603b.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/56017514-cac78500-5cff-11e9-93a3-00e78d6f5240.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/56017770-94d6d080-5d00-11e9-89f3-f3a7a1d6f2e8.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/56027172-d58d1480-5d15-11e9-8ada-c0292f1800b3.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/56698870-3c141a00-66a8-11e9-89bb-7a635395d9e5.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/60799285-2d031b00-a173-11e9-9d28-ac07a7ae894a.png)

![image](https://user-images.githubusercontent.com/13203188/60799366-4c01ad00-a173-11e9-934f-f02e26c9429e.png)

![image](https://user-images.githubusercontent.com/13203188/60799411-60de4080-a173-11e9-9dcc-d39a45826d42.png)

![image](https://user-images.githubusercontent.com/13203188/60799477-7eaba580-a173-11e9-9f8b-431f5b09344e.png)

![image](https://user-images.githubusercontent.com/13203188/60799538-9e42ce00-a173-11e9-860a-015a1840fd19.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/61164749-fb6cb580-a4cc-11e9-9b1d-2823cda3eebe.png)

**Comment by bgavrilMS** [comment]
![image](https://user-images.githubusercontent.com/12273384/61951596-6330ff00-afa9-11e9-9203-e4b93d78a8b8.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/110454488-9618ff80-80c7-11eb-86a1-48ccd8ddaea4.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/110701232-c3d47600-81a5-11eb-829b-74a324d09f43.png)

**Comment by pmaytak** [comment]
![prompt](https://user-images.githubusercontent.com/34331512/112267137-3f1c3a00-8c32-11eb-97fb-33604311329a.png)

**Comment by pmaytak** [comment]
![Installs-Unity-Hub](https://user-images.githubusercontent.com/34331512/113494681-72b35b80-949f-11eb-8d48-4f247f8c8624.png)
![Projects-Unity-Hub](https://user-images.githubusercontent.com/34331512/113494723-f8cfa200-949f-11eb-8312-af0f1a3d59a8.png)
![Scenes-Unity-Editor](https://user-images.githubusercontent.com/34331512/113494754-421ff180-94a0-11eb-9337-15288832174b.png)
![Play-Unity-Editor](https://user-images.githubusercontent.com/34331512/113494772-6d0a4580-94a0-11eb-8cc1-f6ced5a5dfea.png)
![Components-Unity-Editor](https://user-images.githubusercontent.com/34331512/113494792-95923f80-94a0-11eb-9eaf-50ee5824061e.png)
![Inspector-Unity-Editor](https://user-images.githubusercontent.com/34331512/113494817-e7d36080-94a0-11eb-9157-d6a4774e38c9.png)
![Build-Settings](https://user-images.githubusercontent.com/34331512/113494838-2ec15600-94a1-11eb-9a39-283c310fb1f0.png)
![VS](https://user-images.githubusercontent.com/34331512/113494891-a3949000-94a1-11eb-8708-c8dd98989647.png)
![UnityTestApp](https://user-images.githubusercontent.com/34331512/113494910-caeb5d00-94a1-11eb-9722-0ae8963bd566.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/118163279-a6ef3580-b3d6-11eb-92be-528e6326daba.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/124992678-245ead00-dff8-11eb-816c-aaf3edc70aa3.png)
