### ISSUE TITLE
Ref docs/code comments incorrectly say parameter is optional 

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-dotnet#542]
For example: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dc3f0656b7f8b8d6f474a8ed19c671dd51626459/src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs#L63. Also occurs in a few other overloads. 

There is no default value and thus the developer must pass null. While it's not required for the call to succeed, it's still not a completely optional parameter. 

There doesn't seem to be a reason not make this parameter optional with null as the default.

**Comment by danieldobalian** [comment]
@jmprieur fyi

**Comment by jmprieur** [comment]
Thanks @danieldobalian 
cc: @henrik-me @jennyf19

**Comment by bgavrilMS** [comment]
@jmprieur - would we want to add null as default values for the 2 token cache params or just update the docs?

**Comment by jmprieur** [comment]
@bgavrilMS : please just remove OPTIONAL for the moment. We need to think a bit more of the token cache (user and apps)

**Comment by jmprieur** [comment]
Fixed
