### ISSUE TITLE
MSAL in C++ App hangs on AcquireTokenAsync

### ISSUE THREAD

**Issue by adamtoth** [AzureAD/microsoft-authentication-library-for-dotnet#545]
From within a C++ app using /clr managed code interop, I am trying to use the MSAL library to authenticate the user, however when calling AcquireTokenAsync, the login window does not appear and the app hangs.

The C++ app is compiled using /clr, and is referencing a C# dll. In the C# dll, I am using the PublicClientApplication class and the AcquireTokenAsync method to try and authenticate the user. 

From the C# dll, I am able to set breakpoints and step through, and even show a message box using System.Windows.Forms.MessageBox.Show(), so I know I can affect the main UI thread. However when calling AcquireTokenAsync, no browser window is ever popped open for the user, and the call sits awaiting the result of that dialog close. Is there any way to control how that dialog is created and on what thread, and make sure that it pops up?

**Comment by henrik-me** [comment]
@adamtoth are you using the latest version of ADAL? Assuming this is a desktop app? We haven't tested managed C++ thus not sure what is happening (though it should work). Have you tried the same in a sample C# app? The OS will sync the call to the UI thread and if anything else is holding on to the same thread then it will be in a deadlock. Are you opening the messagebox from the same location in the code as the call to open the webview?

**Comment by jmprieur** [comment]
Closing. Feel free to reopen if you are still interested in this issue
