### ISSUE TITLE
When the hell are you going to release this?

### ISSUE THREAD

**Issue by Dark-Bond** [AzureAD/microsoft-authentication-library-for-dotnet#548]
It's been a year in Preview, people.

**Comment by jmprieur** [comment]
Hello Dark-Bond
We are currently working on a common cache between ADAL and MSAL, which will allow you to migrate your end users more easily without them needing to re-sign in. We are also adding the embedded web browser (which was in ADAL.NET already) to MSAL.Net as there are a number of Android phones which don't support Chrome custom tabs, or for which those are disabled. 
Then we'll be working on the missing public client application flows (See the "not supported yet" flows in the comparison table of [Supported Grant](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#supported-grants) ... and this should GA.
