### ISSUE TITLE
Explicit definition of proxy

### ISSUE THREAD

**Issue by yanoska** [AzureAD/microsoft-authentication-library-for-dotnet#552]
Hi,
when the library is used behind the proxy, there is no way (except setting Microsoft.Identity.Client.Internal.Http.HttpClientFactory._client by reflection) to set the values of proxy. It would be nice to be able to set custom HttpClientHandler throught HttpMessageHandlerFactory.

**Comment by jmprieur** [comment]
@yanoska : did you try to configure the proxy at the system level. `HttpClient` used by MSAL should be able to use it. For instance I'd think setting [WebRequest.DefaultWebProxy](https://www.bing.com/search?q=webrequest.defaultwebproxy&form=EDGNTT&qs=PF&cvid=e57027460fb44894b68148a597cd18ac&refig=ae758c3aafae44cc965e42ddf9426b53&cc=FR&setlang=en-US&elv=AY3%21uAY7tbNNZGZ2yiGNjfNTg8W4Rv8MPoPW8nmNYrxjOlsDkt8VumMVq9GCycf5LgMj9dHmqnscQa2xhmIlkYxOu7ZpqD9p*L5skizNdC3m)

**Comment by yanoska** [comment]
@jmprieur: No, I didn't. It is working. For some reason I assumed something like constructor of GraphServiceClient which accepts instance of HttpClientHandler. Thanks.

**Comment by jmprieur** [comment]
thanks for the update, @yanoska 
I've updated the conceptual documentation adding an article to use proxies : [using MSAL.NET with a proxy](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/proxy)

**Comment by dimitertodorov** [comment]
Is WebRequest.DefaultWebProxy supported on dotnet core.

D
