### ISSUE TITLE
Nuget compatibility problem with recent Xamarin.Android.Support.Compat 

### ISSUE THREAD

**Issue by pdeliot** [AzureAD/microsoft-authentication-library-for-dotnet#553]
NU1107: Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 MyApp.Android -> Xamarin.Android.Support.v7.MediaRouter 27.0.2 -> Xamarin.Android.Support.v7.Palette 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2) 
 MyApp.Android -> Microsoft.Identity.Client 1.1.2-preview0008 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).

**Comment by jmprieur** [comment]
@pdeliot : did  you read [Troubleshooting Xamarin.Android issues with MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Troubleshooting-Xamarin.Android-issues-with-MSAL)

**Comment by pdeliot** [comment]
The issue is occuring during Nuget Package restore.
If the package is referenced by manual proj. editing or referenced before upgrading target to 27.0.1, I have an error but the build is possible and all looks functionnal.

The issue is during package installation validation.

**Comment by jennyf19** [comment]
Yes...we've had issues with the Nuget Package restore in the past...a typical problem with Xamarin dependencies. Based on your experiences, looks like we need to update the documentation to include higher versions as well. Does that make sense?

**Comment by pdeliot** [comment]
Probably updateing depedency requirement in the nuget package description would solve the issue.

**Comment by konrad11901** [comment]
This issue still occurs:

```
Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 App1 -> Xamarin.Android.Support.Design 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2) 
 App1 -> Microsoft.Identity.Client 1.1.2-preview0008 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).	
```

When can we expect a fix?

**Comment by jennyf19** [comment]
Thanks @konrad11901 We'll look into this.

**Comment by jennyf19** [comment]
@konrad11901 @pdeliot 
Plus update to the latest version of MSAL [1.1.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/1.1.3-preview). We have the fixes in there for 27.0.2 and MonoAndroid8.1

**Comment by konrad11901** [comment]
I can also confirm that this issue doesn't occur with the latest version. Thanks for the fix!

**Comment by jennyf19** [comment]
@pdeliot @konrad11901 Thanks for the follow-up...much appreciated!
