### ISSUE TITLE
An error occurred trying to restore packages : unable to find version 1.1.3-alpha0009 of package Microsoft.Identity.Client

### ISSUE THREAD

**Issue by syedwalihasan** [AzureAD/microsoft-authentication-library-for-dotnet#561]
![error](https://user-images.githubusercontent.com/18749369/40460487-f675c69e-5f17-11e8-8890-208e8e3e6cfc.png)

It was Microsoft Team Sample presented at Build Conference

**Comment by jennyf19** [comment]
@syedwalihasan - This is the latest version of the library [v1.1.2-preview](https://www.nuget.org/packages/Microsoft.Identity.Client/1.1.2-preview0008). The Team Sample must be using their own version. You could try uninstalling and then reinstalling, or give us a link to the sample, and we can take a look. thanks

**Comment by syedwalihasan** [comment]
Below the project link, i tried uninstalling, that didn't work either :(
https://github.com/Azure-Samples/xamarin-azure-businessreview

**Comment by jennyf19** [comment]
@syedwalihasan Closing this, as it is not an issue with MSAL, but let us know if you need further assistance with this.
