### ISSUE TITLE
Issue with nuget package

### ISSUE THREAD

**Issue by sameerkattel** [AzureAD/microsoft-authentication-library-for-dotnet#565]
I get below error once nuget package https://www.nuget.org/packages/Microsoft.Identity.Client/1.1.3-preview0012 is installed

> Package does not contain a manifest.

using visual studio 2015 community edition.

**Comment by henrik-me** [comment]
@sameerkattel thanks for the heads up. we are investigating.

**Comment by henrik-me** [comment]
@sameerkattel : Which project type are you using? It works for me with Win8.1.

**Comment by sameerkattel** [comment]
@henrik-me The solution has console app,class libraries and windows application. I am running on windows 10. .net framework 4.5.2

**Comment by henrik-me** [comment]
@sameerkattel:  I just created a new console app targeting Microsoft.Identity.Client 1.1.4-preview0002 using VS 2015 enterprise. I would not assume differences to using the community edition. Can you try the latest?

**Comment by jmprieur** [comment]
Closing as no-repro
