### ISSUE TITLE
Running on dotnet core does not respect WebRequest.DefaultWebProxy

### ISSUE THREAD

**Issue by dimitertodorov** [AzureAD/microsoft-authentication-library-for-dotnet#566]
Please see here for previous issue on this.
#552 

Unfortunately, dotnet core does not support DefaultWebProxy
This means when running in a Firewalled environment, there is no way to complete the Authentication.

Overriding the _client within HttpClientFactory works using Reflection, but is not ideal.
Possible Fixes
- Allow for passing in a custom HttpClientHandler in Client constructors. (Similar to what Autorest clients allow)
- Expose HttpClientFactory or allow specifying custom client factory.

Here is a utility class I created to work around this for now.
```
using System;
using System.Net.Http;
using System.Reflection;
using Microsoft.Identity.Client;

namespace GoCloud.Client.Core
{
    public static class IdentityClientManager
    {
        // This is needed to allow overriding the HttpClient handler that MSAL uses for Authentication.
        // dotnet core does not use WebRequest.DefaultProxy, so this dirty hack is needed.
        // TODO: Remove once MSAL client allows for Proxy/Handler Config
        public static void SetHttpHandler(HttpClientHandler handler)
        {
            Type t = typeof(ConfidentialClientApplication)
                .Assembly.GetType("Microsoft.Identity.Client.Internal.Http.HttpClientFactory");
            var idmClient = t
                .GetField("_client", BindingFlags.Static | BindingFlags.NonPublic);
            var newClient = new HttpClient(handler);
            if (idmClient != null) idmClient.SetValue(null, newClient);
        }
    }
}
```

**Comment by henrik-me** [comment]
thanks @dimitertodorov for pointing out the issue. @rayluo for awareness as he is currently looking at the http handling. @jmprieur seems worth documenting until we have something more user friendly.

**Comment by jmprieur** [comment]
Done: See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/proxy
