### ISSUE TITLE
ADAL to MSAL Port for application where cloud servers are given access tokens by mobile.

### ISSUE THREAD

**Issue by mbalsam** [AzureAD/microsoft-authentication-library-for-dotnet#578]
We have an ADAL application that we want to port to MSAL to support DOTNET core. 

It appears that most of the workflows that are documented, present a model where the client generates its access token and keeps the token active using the client device.. 

Our current model works and uses a client and a server approach with ADAL.   This is our workflow.

1. Mobile application acquires an access token
2. Mobile sends the access token to a server application
3. The server does work on behalf of the mobile.  
4. This includes having the server refreshing the access token without asking mobile for hourly revalidations. 

We are trying to accomplish this same process with MSAL, but can't find information that documents how this workflow would be implemented.    

Can you point us in the right direction?

**Comment by jmprieur** [comment]
@mbalsam : coming back to this, is it an option for you to have the same ClientId for your mobile application and your Web API? this is possible in MSAL / Microsoft identity platform v2.0 (AAD v2.0). This way your mobile could get a token for a resource (with the consent etc ...), and pass it to your application, which would access the resource. Or the mobile app could get a token for itself and the Web API do OBO.
See https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#use-of-a-single-application

**Comment by jmprieur** [comment]
proposing to close as I believe this is answered.
but feel free to reopen if this does not work for you
