### ISSUE TITLE
Web UI not visible when running in Windows VR headsets

### ISSUE THREAD

**Issue by joaocpaiva** [AzureAD/microsoft-authentication-library-for-dotnet#579]
PublicClientApplication.AcquireTokenAsync never returns because the Web UI is not visible.

Repro:
1) Download [project](https://drive.google.com/open?id=15oeAs5L1q0ymVGcJZUEgi4QpAzbTya7x)
2) Open Visual Studio solution and build for x86.
3) Open "Mixed Reality Portal" with simulation enabled.
4) Run project in Local Machine.

Observe that AcquireTokenAsync is invoked but it never returns (the Web UI is not visible).

**Comment by jmprieur** [comment]
Hello @joaocpaiva 
Is there a Web browser in a Windows VR headset? 

If that's not the case, you should use the device code flow (which enables you to sign-in in the app running in the VR headset from your phone for instance), or another device. But [Device code flow](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Device-profile-for-devices-without-web-browsers) is not yet implemented in MSAL.Net (this is coming)

**Comment by joaocpaiva** [comment]
@jmprieur yes Microsoft Edge is available.

**Comment by bgavrilMS** [comment]
This request is very old and likely the issue has been fixed. If .net framework is available on Windows VR, this should work, as we are using the WebBrowser control. 

Another approach that is available with MSAL 3.x is to inject your own browser implementation. This is needed for example on .net core. You can for example invoke the system browser. Have a look at this sample to see how this is done (we're still working on a proper sample). 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/dev3x/tests/devapps/NetCoreTestApp/Experimental
