### ISSUE TITLE
Enable ETW logging

### ISSUE THREAD

**Issue by samneirinck** [AzureAD/microsoft-authentication-library-for-dotnet#580]
I'm trying to diagnose some issues we're having where the `AcquireTokenForClientAsync` call takes too long on some environments, and would like to look into the logs. 

It seems like setting `Logger.DefaultLoggingEnabled` is no longer the correct way [due to this PR](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/415/files). Is the only supported scenario to set the `Logger.LogCallback` property? And are there any plans to enable the scenario again to use ETW? It would be easier to enable/disable on the fly.

**Comment by jmprieur** [comment]
@samneirinck did you have a look at the conceptual documentation [Logging](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging). It explains why things changed, and how to use the logger.
Thanks for your feedback about the ETW events. that's something we could introduce in MSAL (they were in ADAL) if this is important for you. can you please tell me more about your scenario?How did you enable/disable them on the fly (I suppose with ADAL as I don't think MSAL ever supported them) ?

**Comment by samneirinck** [comment]
I didn't, thank you. It looks like I implemented it as described on the wiki. 

About ETW: I thought the `DefaultLoggingEnabled` property in previous versions enabled logging to ETW? I didn't confirm, but this was just by reading through the source code that it eventually drops down to ETW.
The benefit I see is that I can quickly enable/disable the logging, without needing either a configuration change or a new deployment. I regularly use tools like [PerfView](https://github.com/Microsoft/perfview) to temporarily enable logging, and look into the results. It does't require a restart of the process or a configuration change, so if a problem is occurring, it's easier and safer to toggle it on.

**Comment by henrik-me** [comment]
@jmprieur : did you consider this further? I suggest closing or prioritizing

**Comment by MarkZuber** [comment]
This only works on Windows.  The developer can use the callback to fire off ETW events if that's desired but I don't see a need to implement it in the core library.
