### ISSUE TITLE
How to request token from appTokenCache?

### ISSUE THREAD

**Issue by sameerkattel** [AzureAD/microsoft-authentication-library-for-dotnet#581]
[AcquireTokenSilentAsync using cached token](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token) seems to only work for userCacheToken. What about appTokenCache?

**Comment by jmprieur** [comment]
@
what is your experience? is it a question ? or a bug? if that's a bug do you have repro steps? some with which we can repo?

**Comment by sameerkattel** [comment]
@jm
 It's a question. How to request a cached token for client app credential? AcquireTokenSilentAsync only considers user token cache.
Here is the current code where everytime i am requesting a token which i want to avoid.
  ```
                      var daemonClient =
                            new ConfidentialClientApplication(oauthApplicationIdentity.Id,
                                string.Format(authorityFormat, tenantId), oauthApplicationIdentity.CallbackUri,
                                new ClientCredential(oauthApplicationIdentity.Secret),
                                null, new TokenCache());
                         var authResult =
                            await daemonClient.AcquireTokenForClientAsync(new[] { oauthApplicationIdentity.Scope });
```

**Comment by jmprieur** [comment]
@
the userTokenCache contains access/refresh tokens for users. It's used in all the overrides involving users (that is public client application flow, and the on behalf of flow and code flow in the case of confidential client applications) . The app Token cache is used in the flows where the app request a token in the name of no user (in its own name), that is only for the confidential client flow, which is your case. you can use the same custom serialization for the application token cache : `AcquireTokenForClientAsync` will use the app cache, not the user cache.

**Comment by sameerkattel** [comment]
@Jm
 But when I try to call AcquireTokenForClientAsync  daemonClient.Users value is always null and it always throw exception
```
            var daemonClient =
                new ConfidentialClientApplication(oauthApplicationIdentity.Id,
                    string.Format(authorityFormat, tenantId), oauthApplicationIdentity.CallbackUri,
                    new ClientCredential(oauthApplicationIdentity.Secret),
                    null, new TokenCache());

            var graphClient = new GraphServiceClient(
                new DelegateAuthenticationProvider(
                    async requestMessage =>
                    {
                        AuthenticationResult authResult;
                        try
                        {
                            authResult = await daemonClient.AcquireTokenSilentAsync(new [] { oauthApplicationIdentity.Scope},daemonClient.Users.FirstOrDefault());
                        }
                        catch (MsalUiRequiredException)
                        {
                            // A MsalUiRequiredException happened on AcquireTokenSilentAsync. 
                            // This indicates you need to call AcquireTokenAsync to acquire a token
                            authResult = await daemonClient.AcquireTokenForClientAsync(new[] { oauthApplicationIdentity.Scope });
                        }

                        // Append the access token to the request.
                        requestMessage.Headers.Authorization =
                            new AuthenticationHeaderValue("bearer", authResult.AccessToken);
                    }));
```

**Comment by jmprieur** [comment]
@sameerkattel 
I understand your concern now, and sorry if the doc is not perfect. 
With the  [confidential client flow](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows) your daemon application is requesting tokens in its own name, so there is no user, so there is no user.

Also  `AcquireTokenForClientAsync` pre-checks the cache, so no need to call AcquireTokenSilentAsync in that case.


The following sample explains how to use AcquireTokenForClientAsync: https://github.com/Azure-Samples/active-directory-dotnet-daemon-v2

**Comment by sameerkattel** [comment]
@jmprieur  Thanks! Now i know where i was doing wrong. I was instantiating the client inside delegationhandler everytime  :)
