### ISSUE TITLE
System.MissingMethodException with Xamarin Forms on Android

### ISSUE THREAD

**Issue by josephkandi** [AzureAD/microsoft-authentication-library-for-dotnet#582]
I have installed the `1.1.4-preview0002` nuget with Xamarin.Forms 3.1.0.5839.44 and i get the exception `System.MissingMethodException`
```
System.Threading.Tasks.Task`1<Microsoft.Identity.Client.AuthenticationResult> Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable`1<string>)```

The same project works fine on iOS

**Comment by jmprieur** [comment]
@bgavrilMS : assigning to you part of the work you've been doing on the .NET Standard platform

**Comment by jmprieur** [comment]
This is now solved in [MSAL.NET 2.6.0](https://aka.ms/msal-net-2-6)
