### ISSUE TITLE
ClientApplicationBase.Users is always empty on iOS

### ISSUE THREAD

**Issue by DaRosenberg** [AzureAD/microsoft-authentication-library-for-dotnet#585]
This reproduces reliably both in our app, and in the sample app here: https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

It seems that, at least on iOS (I have not tested on other platforms), tokens are never added to the cache. Inspecting the `ClientApplicationBase.Users` property always yields an empty enumerable, and calling the `ClientApplicationBase.GetUser(string identifier)` method always returns `null`.

I have checked this on a few different occasions in the authentication lifecycle, including immediately after a successful `AcquireTokenAsync()` and also after app restart.

To see this, just run the sample app linked to above (the iOS version) in the iPhone Simulator, do a successful authentication, and then terminate and relaunch the app. You'll see that the sign-in state is now back to signed out.

**Comment by DaRosenberg** [comment]
BTW, also tried this against tip of dev, from our own app. Same result.

**Comment by jmprieur** [comment]
@DaRosenberg : do you sign-in with an Azure AD account? or a Microsoft personal account? do you see the issue in both?

**Comment by DaRosenberg** [comment]
@jmprieur For all my testing so far I have been signing in using a Azure AD B2C tenant, using Microsoft Account as the configured identity provider.

**Comment by DaRosenberg** [comment]
@jmprieur I tested this with the newest version of MSAL in the ADAL repo (tip of the dev branch) and the issue is the same.

However I think I have managed to isolate this down to where it fails:

![image](https://user-images.githubusercontent.com/3889090/42055857-b295892e-7b18-11e8-95e9-ca0f871f4c0b.png)

This is in `Microsoft.Identity.Core/Platforms/iOS/TokenCacheAccessor.cs`. As you can see, the `SecKeyChain.Add()` call does not return `SecStatusCode.Success` as would be expected. Instead it returns `SecStatusCode.Param`.

We are completely blocked on this issue, so any assistance would be very welcome.

**Comment by henrik-me** [comment]
@SomkaPe : can you pls. take a look at this one?

**Comment by jmprieur** [comment]
@DaRosenberg : we are going to look at it.
I'm a bit confused by the fact that you are completely blocked: the tip has not released yet? you mean previous versions of MSAL also exhibited this issue?

**Comment by DaRosenberg** [comment]
@jmprieur Yes, all versions of MSAL I have tried exhibit the same issue for us - also 1.1.4-preview0002.

**Comment by jmprieur** [comment]
@DaRosenberg : did you look at this sample? (I recommend reading the readme in detail): [xamarin-native-v2](https://github.com/azure-samples/active-directory-xamarin-native-v2)

**Comment by DaRosenberg** [comment]
@jmprieur Since we use AAD B2C we looked at this sample:
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

As I mentioned in my initial comment, the issue **also reproduces with that sample**.

I did read the readme of the sample very thoroughly, and carried out all the steps. I also looked at the readme of the sample you linked to now, and it does not seem to differ much, I can confirm that I have carried out all the steps outlined there.

**Comment by DaRosenberg** [comment]
@jmprieur @henrik-me @SomkaPe I found the solution.

1. Keychain access needs to be enabled in `Entitlements.plist`.
2. If using Xamarin, the `Entitlements.plist` also needs to be added to "custom entitlements" for the `iPhoneSimulator` platform configurations; this is not done automatically for a new Xamarin project, but is required for Keychain access to work on the simulator.

I strongly suggest you add this information to your readme files in the samples, and also in your wiki. It's not currently mentioned anywhere, and unless you get very deep into the MSAL source, you will never realize that it requires Keychain access on iOS.

Also I suggest you update your samples to fix this by adding the entitlements:

- https://github.com/Azure-Samples/active-directory-b2c-xamarin-native
- https://github.com/azure-samples/active-directory-xamarin-native-v2

**Comment by jennyf19** [comment]
Thanks @DaRosenberg - We have information on this in our wiki in [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Token-cache-serialization#on-ios-you-need-to-enable-keychain-groups), but I will add it to the MSAL wiki. 

@jmprieur I'll take a look at updating the samples.

**Comment by jennyf19** [comment]
@DaRosenberg - Started to document this in our [wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-ios-specificities#enable-keychain-groups) in MSAL.

[Issue for b2c](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/55)

[Issue for Xamarin v2](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/33)

Can we close this issue?

cc: @jmprieur

**Comment by DaRosenberg** [comment]
@jennyf19 Yep.
