### ISSUE TITLE
Allow client app to control SFSafariViewController tint colors on iOS

### ISSUE THREAD

**Issue by DaRosenberg** [AzureAD/microsoft-authentication-library-for-dotnet#586]
Currently, on iOS, the interactive request web browser always renders with a (rather unattractive) light blue tint on the navigation bar and command bar.

We need to be able to control this from our app, because the current resulting user experience is simply not acceptable for us when the authentication UI uses such an out-of-place color scheme that does not fit at all within the context of our app.

Specifically, we need to be able to control the values of the following `SFSafariViewController` properties:

- preferredBarTintColor: UIColor?
The color to tint the background of the navigation bar and the toolbar.
- preferredControlTintColor: UIColor?
The color to tint the the control buttons on the navigation bar and the toolbar.

I suggest the following approach for minimum impact:

1. Make the `WebUI` class public (instead of internal)
2. Add two public static properties of type `UIColor?` to the iOS version of this class. This will allow the client iOS app layer to independently set these properties (e.g on app launch) even if the rest of the authentication logic is implemented in a platform-neutral assembly.
3. In the `WebUI.Authenticate()` method, configure the `SFSafariViewController` instance with the values of those two new static properties, if they have been set.

It would be even nicer to take this further and not rely on statics, by instead allowing the client app to provide an `IWebUI` implementation, but that would be a bigger change.

**Comment by jmprieur** [comment]
Thanks for your feedback, @DaRosenberg. cc @jennyf19 
The current version uses the system web browser, so I guess this is what you are seeing. I'm not sure if the application can control its colors. Note that we are soon going to release a version of MSAL which enables an embedded web browser. Would that inherit the colors of the application? 

otherwise, I suppose that we'd need to surface platform specific UI properties like what is done in ADAL.NET: [Properties of PlatformParameter specific to iOS to fine grain control the UX](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows#properties-of-platformparameter-specific-to-ios-to-fine-grain-control-the-ux)

**Comment by DaRosenberg** [comment]
@jmprieur The current version (in *this* repo) uses `SFSafariViewController`, and yes the application can control it's colors, that's what I tried to describe above with the two properties. I made these improvements in my fork, and it works great. I'm happy to provide a PR for your review?

I should check out your upcoming MSAL which uses an embedded web browser, to try and understand if that would solve the issue. Where is the source of that one? In fact, can you clarify for us which version of MSAL is actually under development? I see one in this repo and another one in the ADAL repo, and that one has newer commits than this one. Which one is the "real" MSAL?

**Comment by bgavrilMS** [comment]
@DaRosenberg - we're moving the development of MSAL here: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet - follow the instructions for building the dev branch https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL-.NET-Build-&-Run

The next version of MSAL is probably going to be a 2.x.x-preview, since MSAL will be split into 2 assemblies, although there shouldn't be many backwards compatibility issues. 

We do publish early bits on MyGet: https://www.myget.org/feed/aad-clients-nightly/package/nuget/Microsoft.Identity.Client

**Comment by DaRosenberg** [comment]
@bgavrilMS Thanks for that clarification. Would you say MSAL is the preferred choice for a cross-platform mobile app targeting AAD B2C or should we be considering ADAL?

**Comment by bgavrilMS** [comment]
Yes, MSAL is the lib of choice. @jmprieur created a very nice graphic explaining this (rather complex) - have a look https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Register-your-application-with-Azure-Active-Directory

**Comment by jmprieur** [comment]
@DaRosenberg : as @bgavrilMS explained the source code for the next version of MSALNET in indeed in the `dev` branch but of the `ADAL.NET` repo (we know, this is weird!). What happens is that we have been working on a common core DLL between ADAL.NET and MSAL.NET, and found it easier for the moment to have the code for both libraries in one repo (and unfortunately it went to ADAL.NET whereas the future is definitively MSAL.NET).
When we release, we'd probably re-import the code of both librarie into this repo and update the other to say that the code is in this other one (but we still want to use ADAL.NET and MSAL.NET repos for documentation and issues anyway)

That explained, if you want to try the embedded web browser, you can:

-  Add to Visual Studio a package feed: https://www.myget.org/F/aad-clients-nightly/api/v3/index.json
- Open in VS the https://github.com/Azure-Samples/active-directory-xamarin-native-v2 sample and upgrade the four projects to Microsoft.Identity.Client v2.0.0-internalwkWebViewUpdate17325
- in the UserDetailsClient.iOS project, in `AppDelegate.cs` file line 28, insert:
  ```CSharp
  App.UiParent = new UIParent(useEmbeddedWebview: true);
  ```

**Comment by DaRosenberg** [comment]
@jmprieur Thanks, I'll give that one a try and see how I fare - will report back on this issue.

**Comment by jmprieur** [comment]
@DaRosenberg : we are still testing the embedded web view, BTW, so not 100% sure everything works yet
you might want to try the following branch of the sample (or do the step above yourself): https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/jmprieur/testEmbeddedWebView

**Comment by jmprieur** [comment]
@parakhj : do you want to have a look at this one (for the experience with teh B2C landing landing page). I don't think that this is MSAL.NET related.

**Comment by parakhj** [comment]
I'm not exactly sure where the blue is coming from... likely the blue in our template? @DaRosenberg do you have another UI template by any chance that you can use to customize the UI? Here is a custom one if you need it - https://fabrikamb2c.blob.core.windows.net/b2cpartnerconference/unified.html

**Comment by DaRosenberg** [comment]
@parakhj We have already created a custom template for this page, with completely custom styling from scratch, and it does not have this issue, so for our project we are good. But this would be a problem for anyone who would prefer not to go through the work of custom styling - B2C would be a lot better if all the standard templates looked good out-of-box. Currently the default pages are so poorly built and styled that we felt forced to do custom ones just to get a acceptable user experience, and this is just one example. If they had reasonably good UX, we would probably have been happy to use the built-in pages and only rely on the branding.

A while ago I saw some new (and potentially more well-built) templates exposed in the preview B2C portal experience, where we could even select among different themes, but those seem to have been removed again from the portal. Are those coming back? In fact, anything you can share on what your plans are for the markup and styling of the upcoming B2C flows would be helpful.

**Comment by DaRosenberg** [comment]
@parakhj And regarding this particular issue, it seems to be some kind of blue border rendered at the top edge of the screen, that gets positioned behind the translucent bar. Any content outside of the bar should not affect the rendering of the bar.

**Comment by parakhj** [comment]
@DaRosenberg Great feedback - we do have better templates coming (as you noticed)! We are working to bring them out of preview very soon, so stay tuned there. 

+ @Sammak
