### ISSUE TITLE
No way to avoid IDP selection prompt when invoking "edit profile" policy in B2C?

### ISSUE THREAD

**Issue by DaRosenberg** [AzureAD/microsoft-authentication-library-for-dotnet#588]
My app is a Xamarin.iOS app targeting an AAD B2C tenant.

To invoke the AAD B2C "edit profile" policy, it seems we need to specify an explicit authority in the call to `AcquireTokenAsync()`, using one of the overloads that accept an `authority` parameter.

However, all 4 overloads that accept an `authority` parameter, also require the `behavior` parameter, and because the `UIBehavior` type is a `struct` it cannot be supplied as `null`. Nor does it have any static fields to initialize an empty/zero behavior.

As a result, we have to specify either `SelectAccount`, `ForceLogin` or `Consent`, and in my testing, all of them results in the IDP selection UI being displayed before the actual profile edit UI.

How can we avoid showing an IDP selection UI in AAD B2C and instead directly present the user with the actual profile edit UI?

**Comment by jmprieur** [comment]
+ @parakhj 
I believe that this is on the backlog to try and fix this. @negoe : can you please confirm?

**Comment by jmprieur** [comment]
@henrik-me another good one;

**Comment by henrik-me** [comment]
@jmprieur : makes sense to investigate options.

**Comment by jmprieur** [comment]
Proposal is to add a new constant named `NoPrompt` to the `UIBehavior` structure.
When the uIBehavior parameter is be set to `NoPrompt` in overrides of AcquireTokenAsync on public client application, MSAL.NET won't send a prompt=xxx clause any longer.

cc: @henrik-me

**Comment by jmprieur** [comment]
This is now available in ADAL.NET 2.6.0 preview
