### ISSUE TITLE
PublicClientApplication doesn't work on WP8.1 (System.NullReferenceException crash)

### ISSUE THREAD

**Issue by georgii11** [AzureAD/microsoft-authentication-library-for-dotnet#591]
Hello,
I am trying to follow the sample for UWP (https://github.com/microsoftgraph/uwp-csharp-connect-sample) and implement a simple way to connect to a microsoft account on windows 8.1 and windows phone 8.1 too (in c#).
It's all working fine on UWP and W8.1, but on WP8.1, the constructor for PublicClientApplication doesn't work and my app crashes with System.NullReferenceException. I couldn't find any clear documentation saying if it's supported or not, but since I was able to get the Microsoft.Identity.Client package for a wp8.1 project and the class is present in it, I assumed it should work.
I tried new PublicClientApplication with a valid client id, with and without a string for authority, tried using different versions of the Microsoft.Identity.Client package, nothing worked.
Any ideas?

**Comment by bgavrilMS** [comment]
The sample is using a pretty old preview version of Microsoft.Identity.Client - could you update it to the latest version (currently 1.1.4-preview) and try again?

**Comment by georgii11** [comment]
I tried with the latest too and it's the same thing.

**Comment by bgavrilMS** [comment]
Hi @georgii11 - we are actually planning to stop supporting Win Phone and Win 8.1 apps for MSAL. ADAL would continue to support these platforms. 

So we wouldn't have a ship vehicle even if we found a fix for this issue.

@jmprieur can confirm this.

**Comment by jmprieur** [comment]
@georgii11 : can you please explain what your scenario is requiring MSAL.NET for windows phone 8.1 applications? do you use B2C? or do you want to sign-in both work & school and personal accounts? can you explain a bit more?

**Comment by jmprieur** [comment]
So indeed, if you are using the Live SDK, you need Microsoft personal accounts (= MSA = Live accounts). so the options are:
- MSAL supports Windows Phone 8.1
- or you don't migrate from the Live SDK (as ADAL does not support Microsoft personal accounts)

+ @henrik-me @bgavrilMS FYI

**Comment by georgii11** [comment]
Well since the Live SDK will become deprecated not migrating to anything will mean to drop the feature. 

Is there any chance MSAL will support Windows Phone 8.1 at least to allow a migration like this, with minimum functionalities ?
