### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by SergeBerwert** [AzureAD/microsoft-authentication-library-for-dotnet#595]
I have a question is this project dead, or is Microsoft just ignoring de basic needs of customers here also? If I look at the Insights it looks like an abandoned Product.
We plan to develop a new product and I would not like to ride a dead horse.
But maybe I don’t get it and there is a newer library available?

**Comment by bgavrilMS** [comment]
@SergeBerwert This project is not dead and the commitment to support it stands. We are actively working on it. We are trying to consolidate this project (MSAL) with the older ADAL library https://github.com/AzureAD/azure-activedirectory-library-for-dotnet and will be releasing both libraries from the ADAL GitHub repo. We are on course of releasing the "unified" libraries from the ADAL repo as soon as possible. 

Each of the libraries targets different scenarios and different AD flavours, please have a look at the picture in this wiki page for details:
 
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Pre-requisite-Register-your-application-with-Azure-Active-Directory

Once we release, we will likely "archive" this repo. Until then, please use the MSAL preview version available on nuget and feel free to post issues either to this repo or to the MSAL repo. If you'd like to try out the MSAL v2 you can check out our nightly build on myget: https://www.myget.org/feed/aad-clients-nightly/package/nuget/Microsoft.Identity.Client/2.0.0-internal20001dev (there may be a newer version).

**Comment by SergeBerwert** [comment]
@bgavrilMS thanks for your response. As I understand you work in a different repo. But the Microsoft.Identity.Client is still not as release version available for more than two years. I hope you understand why I finally got a little frustrated about.

**Comment by bgavrilMS** [comment]
Sure. Let us know if you are missing any feature from MSAL. @jmprieur will help triage and prioritize.
