### ISSUE TITLE
Disable logging of access token on Xamarin.Android

### ISSUE THREAD

**Issue by marilag** [AzureAD/microsoft-authentication-library-for-dotnet#602]
Our app just got PEN tested and one of the issues was that the access token appears on the log in Android devices after a successful log-in. We tried to set the logging level to warning or error but we can still see the token using logcat. Is there a way to disable this completely?

**Comment by bgavrilMS** [comment]
Hi @marilag, thank you for reporting, what version of the library are you using? Also, how does the log line look like - I am going to search for it?

**Comment by marilag** [comment]
We are using v 1.1.2. Here's how the log look like. 
![msallog](https://user-images.githubusercontent.com/9032945/44535463-58ffe400-a6fa-11e8-9d33-90a642dcff49.png)

**Comment by bgavrilMS** [comment]
Got it. The team have audited all logging for GDPR and have introduced a mechanism for ensuring that the auth library does not log personal identifiable information. Please have a look at this wiki page that describes it: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

You'll need to upgrade the latest version of the library (1.1.4-preview - no breaking changes; or 2.*-preview soon).

I'm going to close this, please feel free to reopen if you meet other issues.

**Comment by jennyf19** [comment]
@marilag - Can you update to 1.1.4-preview, set up the MSAL logging as noted in the link above, and send us the complete log for an acquire token call? Can also be sent via email if you prefer. Thanks.
