### ISSUE TITLE
MSAL 2.0.0-preview breaking change - TokenCacheExtention.Deserialize(null) throws 

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#603]
Try the following code in MSAL.NET 1.1.4-preview
```CSharp
TokenCache tokenCache = new TokenCache();
tokenCache.Deserialize(null);
```
this works

now upgrade to MSAL.NET 2.0.0-preview
this throws a NullReferenceException: 

  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at Microsoft.Identity.Core.MsalIdHelper.GetMsalIdParameters()\r\n   at Microsoft.Identity.Client.Internal.MsalLogger.Log(LogLevel msalLogLevel, String logMessage, Boolean containsPii)\r\n   at Microsoft.Identity.Client.Internal.MsalLogger.Info(String message)\r\n   at Microsoft.Identity.Core.Cache.TokenCacheSerializeHelper.DeserializeUnifiedCache(TokenCacheAccessor tokenCacheAccessor, Byte[] unifiedState, RequestContext requestContext)\r\n   at Microsoft.Identity.Client.TokenCacheExtensions.Deserialize(TokenCache tokenCache, Byte[] unifiedState)\r\n   at adal4_msal2.Program.<Main2>d__1.MoveNext() in C:\\Users\\jmprieur\\source\\repos\\local\\adal4-msal2\\Program.cs:line 21" | string

**Comment by jmprieur** [comment]
@jennyf19, @trwalke, @rayluo : FYI, this breaks a number of Web App samples.
I think we should fix it.

**Comment by jmprieur** [comment]
Verified

**Comment by henrik-me** [comment]
This is not the right fix. Have shared info via email.

**Comment by henrik-me** [comment]
This is not the right fix. pls. revert

**Comment by jmprieur** [comment]
@henrik-me : @jennyf19 reverted it. Thanks for catching it.
