### ISSUE TITLE
TokenCache doesn't work with B2C authorities after migrating to MSAL 2.0.0-preview

### ISSUE THREAD

**Issue by Daniel-NP** [AzureAD/microsoft-authentication-library-for-dotnet#604]
I made to following steps for migration from v1.1.4 to 2.0.0:

- Enable embedded WebView:  `            App.Services.UiParent = new UIParent(this, true);`
- Switch from `IUser` to `IAccount`
- Changed the AcquireTokenSilentAsync from
`AuthenticationResult = await PCA.AcquireTokenSilentAsync(
                    Scopes, GetUserByPolicy(PCA.Users, PolicySignUpSignIn), Authority, false);`
 to 
`                var accounts = await PCA.GetAccountsAsync();`
 `  AuthenticationResult = await PCA.AcquireTokenSilentAsync(scopes, accounts.FirstOrDefault());`
- Changed the AcquireTokenAsync method from
 `                AuthenticationResult = await PCA.AcquireTokenAsync(
                    Scopes, GetUserByPolicy(PCA.Users, PolicySignUpSignIn), App.Services.UiParent);`
 to
 `AuthenticationResult = await PCA.AcquireTokenAsync(scopes,  App.Services.UiParent);`

The TokenCache is not given in my PCA constructor:
`            PCA = new PublicClientApplication(ClientId, Authority)
            {
                RedirectUri = $"msal{ClientId}://auth"
            };`

Used Plattform and libraries:
- Xamarin.Forms v3.1.0.697729
- Android Support Libraries: 27.0.2.1

I tried Android (6.0) and UWP, both need an explicit login action to get an `AuthenticationResult`.
`PCA.GetAccountAsync()` always returns an empty list, so in my view it seems to be an error with the TokenCache.

Do I need to delete the old v1.x-Cache in some way? Can you reproduce the error?

**Comment by bgavrilMS** [comment]
As far as I know, the migration path is from ADAL 3.* to MSAL 2 or from ADAL 4.* to MSAL 2, not from MSAL 1.* to MSAL 2. @jmprieur to confirm

**Comment by jmprieur** [comment]
Yes, the MSAL 1.x cache is not compatible (this was not a promise: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet#important-note-about-the-msal-preview). 

The ADAL 3.x and ADAL.4x caches are compatible with MSAL .2.x with a bit of work (See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released#you-can-enable-sso-between-adalnet-3x-applications-adalnet-4x-applications-and-msal-on-the-same-platform)

But here @Daniel-NP do I understand correctly that even after you signed-in users, the cache is empty ?

**Comment by jmprieur** [comment]
Also @Daniel-NP : do you have a sample where we could repro the issue?

**Comment by Daniel-NP** [comment]
@jmprieur: how can i see that the cache is empty?
When I call this
`             AuthenticationResult = await PCA.AcquireTokenAsync(scopes,  App.Services.UiParent);
                var accounts = await PCA.GetAccountsAsync();` the accounts are empty.

I'm using the Azure B2C service and MSAL on my client. So I don't think I use ADAL at all.
[Here](https://gist.github.com/Daniel-NP/8b0b0d55b822579eb20f44a2110e5eac) is my AuthenticationService.

**Comment by jmprieur** [comment]
@Daniel-NP : I realize you are using MSAL and not ADAL (was giving you the information about the cache migration, but indeed, for B2C, this is not relevant)
Does AcquireTokenAsync works (is there a IAccount in the authentication result)?

Since; from what I understand, you can customize which claims need to appear in the B2C token, I suspect that the token received by B2C is missing claims that the token cache is looking for. Adding @henrik-me @SomkaPe @jennyf19 who might know a bit more.
Also adding @parakhj as a heads-up

**Comment by Daniel-NP** [comment]
I'm currently preparing a sample application. Is it possible for you to use your own azure b2c credentials or do I need to share my credentials with you?

**Comment by henrik-me** [comment]
@jmprieur @Daniel-NP : You will likely benefit from looking at the log. There are 2 claims required to be able to cache, those are unfortunately not part of the default B2C setup. @parakhj was on point to help ensure this happened. The log will tell you which two claims needs to be there.

**Comment by jmprieur** [comment]
@Daniel-NP : I was able to repro it. (in other B2C tenants as well)
What I observe is that:
- I can get a token interactively (both an access token and an idToken), but the `Account` member of the `AuthenticationResult` has the following characteristics (different from what we have for the AAD tokens): 
  - the Username is null
  - the AccountId's ObjectID contains the policy : ObjectId = "<guid>-b2c_1_susi"
Then indeed, as you observed, this account is not added to the token cache.

Also the claims included in the idToken are different than the claims included in the AAD idToken, and I believe some of them are needed for indexing the cache

We are working on a solution, **meanwhile, I'll advise that you to keep using MSAL 1.1.4 -preview.**. We'll update you with this GitHub issue.

Thanks again for reporting and sharing your repros. 
I'm renaming the issue to have B2C in the title

**Comment by henrik-me** [comment]
@Daniel-NP : we are working with the B2C team to get this addressed. the workaround for now is to setup the claim mapping. @trwalke will keep this thread updated on our progress.

**Comment by jmprieur** [comment]
Added it to the MSALNET 2.0.0-preview [known issues](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released#known-issues). The explanation and the work around are available in https://aka.ms/msal-net-token-cache-index-keys

This was also raised as a sample issue in [active-directory-xamarin-native-v2 issue #38](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/38)

**Comment by trwalke** [comment]
We have implemented a fix for this issue and we are planning to release within the next week or so

**Comment by TuroczyX** [comment]
@trwalke That would be perfect! Could you please update the sample code-s as well. It would help a lot.

**Comment by trwalke** [comment]
@TuroczyX Will do. in the meantime, we have released a hotfix for this https://www.nuget.org/packages/Microsoft.Identity.Client/2.0.1-preview
