### ISSUE TITLE
B2C Authentication not working post Microsoft.Identity.Client Upgrade >2.0.0-preview

### ISSUE THREAD

**Issue by sumodmadhavan** [AzureAD/microsoft-authentication-library-for-dotnet#615]
### Problem Statement

We upgraded from .NET Core 2.0 to .NET Core 2.1. In the process we upgraded the assemblies Microsoft.Identity.Client. Post upgrade B2C authentication is not working. Upgrade has caused breaking changes.

## .NET Version : .NET Core 2.1

Microsoft.AspNetCore.Authentication | 2.1.2
Microsoft.AspNetCore.Identity | 2.1.3
Microsoft.Identity.Client | 2.0.0-preview

## .NET Version : .NET Core 2.0

Microsoft.AspNetCore.Authentication | 2.0.2
Microsoft.AspNetCore.Identity | 2.0.2
Microsoft.Identity.Client | 1.1.4-preview0002

### ASP NET Core Logs
**X.Prana.Order.Web> System.Threading.LockRecursionException: Recursive read lock acquisitions not allowed in this mode.**
X.Prana.Order.Web>    at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
X.Prana.Order.Web>    at X.Prana.Framework.Authentication.Cache.MsalSessionCache.Load()
X.Prana.Order.Web>    at X.Prana.Framework.Authentication.Extensions.OpenIdConnectOptionsSetup.OnAuthorizationCodeReceivedAsync(AuthorizationCodeReceivedContext context)
X.Prana.Order.Web>    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RunAuthorizationCodeReceivedEventAsync(OpenIdConnectMessage authorizationResponse, ClaimsPrincipal user, AuthenticationProperties properties, JwtSecurityToken jwt)
X.Prana.Order.Web>    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
X.Prana.Order.Web> info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[4]
X.Prana.Order.Web>       Error from RemoteAuthentication: Recursive read lock acquisitions not allowed in this mode..

### Attached : Fiddler Traces and ASP CORE Server Logs

Observation : Fiddler multiple 302.
[Fiddler](http://prntscr.com/kx55ej)

[B2C.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/2406298/B2C.zip)

**Comment by henrik-me** [comment]
@sumodmadhavan : Did you try with the latest version of MSAL.NET? v. 2.0.1-preview? Se e.g. https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-V2.0.1

**Comment by henrik-me** [comment]
@jennyf19 @bgavrilMS @MarkZuber

**Comment by sumodmadhavan** [comment]
@henrik-me . Issue is resolved with  v. 2.0.1-preview. We can close this issue.

**Comment by henrik-me** [comment]
@sumodmadhavan : thanks for confirming.

**Comment by skorpionet100** [comment]
I receive AADSTS50049: Unknown or invalid instance at AcquireTokenByAuthorizationCodeAsync  method using the 2.0.0-preview to 2.3.1-preview versions on this sample: https://github.com/chrispadgettlivecom/WebApp-OpenIDConnect-DotNetCore21 that with 1.1.4 works.... what's changed?

**Comment by jennyf19** [comment]
@skorpionet100 - I'm getting a redirect_uri invalid issue on that sample. Can you send the logs or stack trace? Are you using the authority in the sample or {tenant}.b2clogin.com?
