### ISSUE TITLE
Crash on UWP after migration from 1.1.2 to 2.0.0

### ISSUE THREAD

**Issue by TKNos** [AzureAD/microsoft-authentication-library-for-dotnet#619]
**Which Version of MSAL are you using ?**
MSAL 2.0.0-preview

**Which platform has the issue?**
UWP

**What authentication flow has the issue?**
* Desktop 

**Repro**
Upgraded a working application from 1.1.2 to 2.0.0. After creating a new package and distributing it via sideloading, users installing the new version can no longer start the app. After a short period of time the application simply crashes.

Further investigations have shown that it is somehow related to the `settings.dat`-file created in the `AppData`-folder. As soon as I delete this file, the app can be started again leading to a recreation of this file. In addition, if a user makes a clean installation with the new version, the application can be started as well, as there exists no `settings.dat` after a clean installation.

From my point of view it looks like the data stored by MSAL within this file is not compatible between v1.* and v2.*.

**Expected behavior**
Application starts without crashing. 

**Actual behavior**
Application crashes

**Possible Solution**
See description above.

**Comment by henrik-me** [comment]
@TKNos : This is not a file that the library does anything with. Do you store the cache in that file? If so, pls. take a look at the changes we made to the cache between v1 and v2 [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released). See specifically the section on the cache.

Aside: We have identified [an issue with the http stack on UWP](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1273) and out next update will include this change. However it doesn't seem like what you are facing here is at all related to that.

**Comment by henrik-me** [comment]
@bgavrilMS : is this related to the issue you found regarding long scopes on UWP?
@TKNos : no longer sure about the file. We will be looking closer at this and provide an update.

**Comment by bgavrilMS** [comment]
@TKNos - on UWP, we don't allow you to provide a TokenCache because we provide one that uses the ApplicationDataContainer

I see that this is a Xamarin application. How is it structrured? 

- do you use a netstandard shared project?
- where does the auth code live - on the netstandard project or on the UWP project?

**Comment by TKNos** [comment]
@bgavrilMS Thanks for your respose.

- It is a .NET standard 1.4 project (`<TargetFramework>netstandard1.4</TargetFramework`)
- The auth code lives in the shared project

**Comment by bgavrilMS** [comment]
@TKNos - I'll look into this, but authentication is platform specific, i.e. some parts, especially the UIBehaviour need to instantiated on the non-shared assemblies. As a workaround, you could try to move auth code to each platform, this should work. 


@jmprieur - we really need to prioritize getting a sample for Xamarin forms to understand how this needs to be implemented.

**Comment by jmprieur** [comment]
Closing as this was documented in
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-2.6.0-released
