### ISSUE TITLE
Google Identity Provider: Redirect to Custom Attribute Page Not Working

### ISSUE THREAD

**Issue by markolbert** [AzureAD/microsoft-authentication-library-for-dotnet#621]
I'm trying to implement Azure AD B2C authentication for an AspNet Core 2.1 website using the Microsoft Account and Google identity providers. My code is based on [this example](https://github.com/chrispadgettlivecom/WebApp-OpenIDConnect-DotNetCore21).

The Microsoft Account flow works the way I expect it to: authenticate, and then get sent to a page where you are requested to fill in custom attributes defined in the Azure AD B2C portal. After you click submit the OnAuthorizationCodeReceived event is raised in the site's codebase.

The Google flow doesn't. After authentication, you don't get sent to a custom attribute page. Instead, the OnAuthorizationCodeReceived event is raised immediately.

I looked over the redirect urls in both cases. The Microsoft Acccount one looks like this:

> https://login.live.com/oauth20_authorize.srf?client_id=704398a8-908a-4512-9cc0-4453014b4714&redirect_uri=https%3a%2f%2fridemonitor.b2clogin.com%2fridemonitor.onmicrosoft.com%2foauth2%2fauthresp&response_type=code&scope=openid+profile+email&response_mode=form_post&nonce=TQsICDEyv245x1E4pkQynQ%3d%3d&state=StateProperties%3deyJTSUQiOiJ4LW1zLWNwaW0tcmM6ZjBlYmQ4OTUtNmVjYS00NzBhLWE4ZDYtY2U4NTgyYzFmZmNjIiwiVElEIjoiNzIwZDg5NDEtNmM2Zi00YzIzLWI5MWEtZDMyZjJjODA5Yjk4In0

Buried in there is a redirect_uri parameter which I believe takes you to that custom attribute page.

The Google redirect is different:

> https://accounts.google.com/signin/oauth?client_id=769952297467-qhqd9brt7pl4sra1hnjhnnqchce2h6f1.apps.googleusercontent.com&as=c-8m6tr-h2tUDpRHqIApkQ&destination=https://ridemonitor.b2clogin.com&approval_state=!ChR4aFltdld5TGNwWUEyUlA1R0R6TRIfczBDdExlN01TRElYa013TWpqbVNUV1h5alREUVloWQ%E2%88%99ANKMe1QAAAAAW7K6uQbexonsHodkbBOebSymUYB1yufO&oauthgdpr=1&xsrfsig=AHgIfE8msp705-PG2II5uHWqjoODqYSLPg

There is no redirect_uri parameter, although of course Google could be expecting something similar under a different name.

FYI, I am using 1.1.4-preview0002 of the Microsoft.Identity.Client package. I tried using the latest preview (2.1?), and ran into the same difference in authentication flow, but also ran into an exception in the OnAuthorizationCodeReceived handler, so I reverted to the earlier version.

**Comment by markolbert** [comment]
Forgot to mention: I'm using the new b2clogin.com domain throughout. The example I'm working off of uses the older microsoftonline.com domain. That probably doesn't matter, but...

**Comment by jmprieur** [comment]
Adding @parakhj as I think that's an issue with b2C? (not MSAL.NET ?)

**Comment by markolbert** [comment]
You could be right; it's unclear to me.

I forgot to mention that an earlier version of my app -- which didn't follow that example source code I cited, and did use the deprecated microsoftonline.com domain -- worked the way I expected it to (i.e., after authentication by either Google or Microsoft, the custom attribute page appeared).

I thought MSAL might be involved because it's part of the approach in that example, and in my code.

**Comment by parakhj** [comment]
@markolbert gonna ask a few clarifying questions:
1. Are you using a built-in or custom policy? I assume custom policy?
2. The custom attribute page usually comes up during sign up only - did you use a custom policy to insert an attribute page during sign in as well?
3. If you capture a network trace, is Google returning a code/token back to B2C?

**Comment by markolbert** [comment]
1. I'm using built-in policies, edited via the Azure AD B2C portal to include certain specific, pre-defined attributes.
2. I'm not using custom policies.
3. Google is returning a token, which is being handled by the OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context) event handler.

**Comment by jmprieur** [comment]
@parakhj : I think this is not related to the library. Can you please confirm, based @markolbert's answers. Also how do we want to track that on your tracking items? do we want us to create a bug or User story in your VSTS team project?

**Comment by parakhj** [comment]
Sorry - i missed the reply from Mark. This is not related to the library. @markolbert it's been a while so i'm curious if you figured it out. The only potential explanation is that the user already exists, and that is why the custom attributes page didn't show up (since it only shows up on sign up). I will test this in my tenant to confirm. If i can repro it, i will let you know. 

@jmprieur we don't have a formal way for tracking Github issues (yet), but I can start a separate thread on that.

**Comment by jmprieur** [comment]
Proposing to close this issue as external (to MSAL.NET).
Parakh will follow-up with you @markolbert 
Feel free to reopen if you disagree.

**Comment by markolbert** [comment]
@parakhj, I run into the problem (failure to redirect to the custom attributes page) even after I delete the authentication from within Chrome. Which I presume is enough to delete the user? If not, I'm happy to try deleting the user, if someone can explain to me where I go to do so.

**Comment by parakhj** [comment]
Go to the settings for Azure AD B2C in your Azure AD B2C directory. Click on users. And then find and delete the user there.

________________________________
