### ISSUE TITLE
AcquireTokenAsync: Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by RhomGit** [AzureAD/microsoft-authentication-library-for-dotnet#628]
Microsoft.Identy.Client 1.1.4-preview0002
Xamarin.Forms.3.2.0.871581
netstandard2.0
iPhone 8 Plus iOS 12.0 Simulator

- I am using Xamarin, have the MSAL flow working in Android and am now trying to get it doing the same for iOS.
- I call "AcquireTokenAsync"
- The login.microsoftonline.com dialog opens correctly.
- I enter the user destails correctly and sign in.
- pca opens the error dialog "Safari cannot open the page because the address is invalid."

I have configured the following steps:
a) the pca RedirectUri has been set to  "msal" + AppID + @"://auth"; (the same as Android)
b) AppDelegate.cs has the OpenUrl override added (a breakpoint here never gets hit btw)
c) Entitlements.plist has had "keychain-access-groups" group added with my bundle identifier.
d) iOS Bundle Signing, Manual Provisioning, Custom Entitlements have been set to Entitlements.plist
e) The .csproj in a text editor has these lines:
```
    <CodesignKey>iPhone Developer</CodesignKey>
    <CodesignProvision>
    </CodesignProvision>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <CodesignExtraArgs />
    <CodesignResourceRules />
```

Any ideas what I am doing wrong?

**Comment by RhomGit** [comment]
Thanks for the response @jennyf19 .

I have switched everything over to the latest v2.2.0-preview and the results are as follows:

**WPF - Windows 10 (.NET Framework 4.6.2 w/ .netstandard2.0 backend)**
Works correctly.

**Android - Android Emulator - Android 8.0 API 26**
Trying to go anywhere near PublicClientApplication raises this:
System.MissingMethodException: System.Threading.Tasks.Task`1<Microsoft.Identity.Client.AuthenticationResult> Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(System.Collections.Generic.IEnumerable`1<string>,Microsoft.Identity.Client.IAccount)\n  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <43dbbdc147f2482093d8409abb04c233>:0 \n


**iOS - iPhone Simulator - iPhone 8 iOS 12.0**
Trying to auth silently _correctly_ returns a MsalUiRequiredException:
`authResult = await pca.AcquireTokenSilentAsync(AuthB2C.scopes, firstAccount);`
"Microsoft.Identity.Client.MsalUiRequiredException: Null account was passed in AcquiretokenSilent API. Pass in an account object or call acquireToken to authenticate.\n  at Microsoft.Identity.Client.ClientApplicationBase+<AcquireTokenSilentCommonAsync>d__34.MoveNext () [0x0002b] in  


Trying to auth with a ui return this exception:
`authResult = await pca.AcquireTokenAsync(AuthB2C.scopes, firstAccount);`
"System.NullReferenceException: Object reference not set to an instance of an object\n  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenForUserCommonAsync>d__23.MoveNext () [0x0003f] in <3d9ffb4972634b74a3bbe55d03a0c0a6>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Fra
meworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 \n  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenAsync>d__9.MoveNext () [0x0009b] in <3d9ffb4972634b74a3bbe55d03a0c0a6>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotificat
ion (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 \n  at B2i.MSALInterop.Auth+<Connect>d__11.MoveNext () [0x00222] in C:\\B2i\\B2iDev4\\B2i.MSALInterop\\Auth.cs:75 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks
.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 \n  at B2i.Ext.Mobile
Kernel.Pipeline+<SignInToAzure>d__17.MoveNext () [0x0002e] in C:\\B2i\\B2iDev4\\B2i.MobileKernel.v2\\Pipeline.cs:204 "

**Comment by jennyf19** [comment]
@RhomGit - Thanks for the additional info.
Are you setting up the UIParent correctly for [iOS and Android](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#choosing-between-embedded-web-browser-or-system-browser-on-xamarinios)?

Here's an example for [iOS](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/master/UserDetailsClient/UserDetailsClient.iOS/AppDelegate.cs#L28) and one for [Android](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/master/UserDetailsClient/UserDetailsClient.Droid/MainActivity.cs#L23).

**Comment by RhomGit** [comment]
Thanks @jennyf19 ,  I had copied the `result = await app.AcquireTokenAsync(scopes, firstAccount); ` code from https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released and didn't realise that it wasn't actually passing in the UIParent anymore (whoops). The examples you linked were helpful, I have added it in as the 3rd parameter and now v2.2.0-preview successfully authenticates on all 3 platforms, thanks very much.

**Comment by jmprieur** [comment]
Thanks for confirming, @RhomGit !

**Comment by jennyf19** [comment]
Thanks @RhomGit - glad you got it working and the links were helpful.

**Comment by stanleywailers** [comment]
@jennyf19  sorry but **IOS** and **Android** examples are not availables

**Comment by jmprieur** [comment]
@stanleywailers : did you look at https://github.com/azure-samples/active-directory-xamarin-native-v2 ?
