### ISSUE TITLE
TokenCacheAccessor on iOS uses "com.microsoft.adalcache" as its default keychain group

### ISSUE THREAD

**Issue by DaRosenberg** [AzureAD/microsoft-authentication-library-for-dotnet#634]
**Which Version of MSAL are you using ?**
MSAL 2.2.0-preview

**Which platform has the issue?**
Xamarin.iOS

**What authentication flow has the issue?**
Mobile

**Expected behavior**
If a key chain security group is not explicitly set by the application, the expectation is that the `TokenCacheAccessor `would use `NSBundle.MainBundle.BundleIdentifier` as the default value.

**Actual behavior**
Instead the `TokenCacheAccessor `uses `DefaultKeychainGroup = "com.microsoft.adalcache"` as its default value and this remains configured unless explicitly set by the application, causing the token cache to not work (which is silently ignored as reported in #633).

**Possible Solution**
Change the `TokenCacheAccessor `constructor to use the `GetBundleId()` as its default value for keychain group. This would most often produce the desired result by default.

**Comment by jmprieur** [comment]
@DaRosenberg : we are using the following `"com.microsoft.adalcache"` keychain group in order to have SSO between Xamarin.iOS apps and Native iOS apps written with MSAL.iOS (or ADAL.iOS as a matter of fact). This is something that some customers have requested.

you can always set the key chain security group to `"NSBundle.MainBundle.BundleIdentifier"`

Closing this issue as won't fix. Feel free to reopen if you disagree.

**Comment by DaRosenberg** [comment]
@jmprieur I don't have permission to re-open, but I would like to. :)

I disagree for the following reasons:

1. If the intention is for apps from the *same vendor* to have SSO between them, then the keychain group name should be scoped to that vendor and for that we instead have the team ID. So if this is the scenario you are intending to solve, then this default value should be prefixed with the team ID (as [documented here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-ios-specificities#enable-token-cache-sharing-across-ios-applications)), in addition to the string "com.microsoft.adalcache" (which, by itself, is too generic/broadly scoped).
1. This is a breaking change that causes apps which don't explicitly set the keychain group, and which worked in earlier versions of MSAL, to no longer work. Would be better IMO if the default was to simply use the bundle ID, and then for apps that want SSO they can explicitly opt into that by setting a broader keychain group in their Entitlements.plist file, and on the PublicClientApplication instance.
1. In any case, the default value "com.microsoft.adalcache" is too broad, because it would imply that we somehow want SSO between all apps on the device that happen to use ADAL/MSAL - even if they are from completely different vendors - which makes no sense IMO, because they would likely be using different token issuers (e.g. different instances of AAD/B2C) so the tokens could not be re-used between them anyway.

**Comment by henrik-me** [comment]
@DaRosenberg @jmprieur : This was chosen as iOS native has been using this as the default setting for a very long time. We have been prioritizing default alignment with the native library higher than previous MSAL's for which the format has also changed and thus SSO will not work either. It is highly recommended that developers change this value and align the value across all their apps.
