### ISSUE TITLE
Make AcquireTokenAsync cancellable by passing CancellationToken

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#635]
*Created from the corresponding feature request in ADAL.NET (ADAL.NET#[1306](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1306)), raised by @marnilss*

**Is your feature request related to a problem? Please describe.**
When doing broker assisted logins (MS Authenticator) in an App, and the user cancels the login process by pressing Home button on device and then reactivating the App, the App is hung waiting for the AcquireTokenAsync to return.

**Describe the solution you'd like**
Make it possible to pass a CancellationToken in the request to AcquireTokenAsync

**Describe alternatives you've considered**
Alternatively a new method on the AuthenticationContinuationHelper, like AbortBroker(), to cancel the hanging/pending authentication call waiting for broker to reactivate with AuthenticationContinuationHelper.SetBrokerContinuationEventArgs(...).

I have found a workaround on this by crafting a special url like https://dummypath?error=...&error_description=.... and pass it to AuthenticationContinuationHelper.SetBrokerContinuationEventArgs().

**Additional context**
Using broker assisted (SSO) with MS Authenticator and Azure AD with ADAL i iOS app.

**Comment by bgavrilMS** [comment]
@jmprieur - this is a great feature to add and should be added to all our async methods. API design standards for async APIs state that they should all have an overload taking a Cancellation Token.

**Comment by jmprieur** [comment]
@MarkZuber (for memory): something we'll do systematically with the builder-based AcquireTokenXXX

**Comment by MarkZuber** [comment]
> @MarkZuber (for memory): something we'll do systematically with the builder-based AcquireTokenXXX

@jmprieur -- agreed.  I don't think a work item for full plumbing of CancellationToken was added to that work item list I sent you.  Can you please add it when you file them?

**Comment by jmprieur** [comment]
Done part of MSAL 3.x

**Comment by jennyf19** [comment]
Fixed in [MSAL 3.0.0-preview release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.0-preview)
