### ISSUE TITLE
Token serialization not possible on Public Client for .net core

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#637]
---
name: Bug report
about: Create a report to help us improve

---

**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
 MSAL 2.2.0

**Which platform has the issue?**

net core

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ x ] WIA
    * [ x ] U/P
    * [ x ] Device code flow (browserless)
* [ ] Mobile
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**

You can't new up a PublicClientApplication taking a TokenCache param. So TokenCache serialization is not possible on netcore. Only in-memory cache will work.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1307

**Comment by bgavrilMS** [comment]
Issue has been fixed.
