### ISSUE TITLE
Bad exceptions on both ADAL and MSAL on IWA when not on corporate network

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#640]
---
name: Bug report
about: Create a report to help us improve

---

**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
2.2.0-preview

**Which platform has the issue?**
netcore (but most likely also net desktop and UWP)

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ x ] WIA
    * [ ] U/P
    * [ ] Device code flow (browserless)
* [ ] Mobile
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**

1. Try IWA with a federated user, for example one of the lab users (e.g. user 7)

**Expected behavior**
An service exception that showcases the error code and the status code (401 Forbidden) 

**Actual behavior**
A client exception that wraps a service exception.

Note: since this code is shared between ADAL and MSAL, changing the exception behavior would introduce a small breaking change in ADAL, so please also consider "won' fix".

Example exception when using MSAL: 

Federated service at   https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed   returned error: ID3242: The security token could not be authenticated or   authorized. ---> Microsoft.Identity.Client.MsalServiceException: Federated   service at https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed   returned error: ID3242: The security token could not be authenticated or   authorize...
--

**Comment by jmprieur** [comment]
@henrik-me : this is not great but I think we can live with just documenting it?

**Comment by henrik-me** [comment]
@bgavrilMS @jmprieur : Should be possible to have separate exception on ADAL vs. MSAL. In case we actually can figure out what to throw instead. Also it could inherit from the same exception ensuring we do not break existing clients. E.g. a FederatedServiceException which inherits from the ServiceException?

**Comment by bgavrilMS** [comment]
@henrik-me - not sure that we need an extra exception type here, I was thinking that throwing a client exception here is a bug, it should be a service exception. This is a breaking change.

**Comment by jmprieur** [comment]
@bgavrilMS : As you are testing the managed/federated scenarios, I thought we'd want to reconsider this issue: Is it something we've made progress on with all our refactorings? or does it still need to be adressed.

**Comment by bgavrilMS** [comment]
I don't think the latest refactgoring made any changes here.

**Comment by henrik-me** [comment]
@bgavrilMS @jmprieur : Was this ever re-tested? I suggest won't fix given MSAL has shipped and it would probably be a breaking change if we need to change type?

**Comment by jennyf19** [comment]
Included in [4.3.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.3.0) release
