### ISSUE TITLE
Device code flow was available in ADAL.NET for Xamarin.Android. Its no longer in MSAL.NET

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#642]
**Which Version of MSAL are you using ?**
MSAL.NET 2.2.1-preview

**Which platform has the issue?**
Xamarin android

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] WIA
    * [ ] U/P
    * [x] Device code flow (browserless)
* [ ] Mobile
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**
Observe the public APIs of ADAL.NET and MSAL.NET for the Xamarin.Android platform

**Expected behavior**
Device code flow is available in MSAL.NET Xamarin.Android (it was in ADAL.NET Xamarin.Android). The scenarios are iOT.

**Actual behavior**
Device code flow is not yet available in MSAL.NET Xamarin.Android

**Comment by jennyf19** [comment]
Done by @MarkZuber in this [PR](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1335) tested w/Android and iOS
