### ISSUE TITLE
With certificate pinning, HttpRequestException when calling AcquireTokenAsync from Xamarin Forms 

### ISSUE THREAD

**Issue by marilag** [AzureAD/microsoft-authentication-library-for-dotnet#644]
Using MSAL 1.x with B2C (still in the process of upgrading to 2.x). In our production app, we intermittently receive HTTPRequestException - An error occurred while sending the request, when calling AcquireTokenAsync. Sometimes, it resolves by restarting the app but sometimes it doesn't. Sometimes, turning Internet on/off fixes it. All other network calls from our app and other apps work, except MSAL. 

I'm not sure if this is related to the library but thanks for any help.

**Comment by jennyf19** [comment]
@marilag Could you try with [Msal2.2.1](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.2.1) and let us know if the problem continues. Which platform (iOS/Android/UWP) are you getting this issue with? Can you include the [MSAL logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#sample-for-logging-in-msal-2x)?

**Comment by jmprieur** [comment]
Thanks for the update @marilag. Closing the issue as external, and updated the title
Feel free to share your solution in this issue when you find it (so that it helps other customers)
