### ISSUE TITLE
ADAL flexibility to dynamically specify the Client/App ID is required

### ISSUE THREAD

**Issue by pangar-ms** [AzureAD/microsoft-authentication-library-for-dotnet#645]
**Is your feature request related to a problem? Please describe.**
Ours is a companion app, where one client app can talk to different service instances deployed in customer Azure subscription. Currently we have a way to pair single application to any instance and complete authentication. With MSAL client Id is embedded in config hence will not be able to change it dynamically as was possible in ADAL. 
As per my understanding multitenant application will not work us as we need access to resource which are deployed in customer subscription.

**Describe the solution you'd like**
Need same flexibility as in ADAL to dynamically configure Client ID for authentication.

**Describe alternatives you've considered**
Continue with ADAL.

**Comment by jmprieur** [comment]
@pangar-ms : I don't understand why multi tenant would not work for you. Is it because your app is working in several clouds?

Worse case you could always maintain a dictionary of ClientApplicationBase keyed by ClientId?

**Comment by jmprieur** [comment]
@pangar-ms : please close this issue if you are satisfied with the answer.

**Comment by pangar-ms** [comment]
Thanks after making web application multi tenant it is working now.
