### ISSUE TITLE
Could not load type of field 'Microsoft.Identity.Core.UI.WebviewBase:asWebAuthenticationSession'

### ISSUE THREAD

**Issue by AlexSchuetz** [AzureAD/microsoft-authentication-library-for-dotnet#646]
Version: MSAL 2.2.0-preview and MSAL 2.2.1-preview
Platform: Xamarin.IOS
Authentication flow: Mobile
SDKs:

- Xamarin.Apple SDK: 4.11.0.756
- Xamarin.Android SDK: 9.0.0.19

Nuget-Packages:

- Xamarin.Forms 3.2.0.871581

Calling `App.AuthenticationClient.AcquireTokenAsync(Constants.Scopes, App.UiParent)` throws the following exception on IOS:

```
Could not set up parent class, due to:
	Could not load type of field 'Microsoft.Identity.Core.UI.WebviewBase:asWebAuthenticationSession' (5) due to:
	Could not resolve type with token 0100004d
		(from typeref,
		class/assembly AuthenticationServices.ASWebAuthenticationSession,
		Xamarin.iOS,
		Version=0.0.0.0,
		Culture=neutral,
		PublicKeyToken=84e04ff9cfb79065) assembly:Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065 type:AuthenticationServices.ASWebAuthenticationSession member:
		(null) signature:<none> assembly:(...)/Microsoft.Identity.Client.dll type:WebviewBase member:(null) signature:<none>
```

On android everything works as expected.

Since today the app doesn't even compile with the follwoing error:
`Failed to resolve "AuthenticationServices.ASWebAuthenticationSession" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065`

**Comment by jmprieur** [comment]
@AlexSchuetz 
Did you make sure that you have installed the latest Visual Studio 2017 (15.8.7 for windows) and at least XCode 10 on the Mac to get the classes needed to run ASWebAuthenticationSession (ex. AuthenticationServices)

**Comment by AlexSchuetz** [comment]
My setup:
On Windows I have Visual Studio 15.8.2 installed
On my remote MAC I have XCode 10 (10A255) and Visual Studio 2017 for MAC (7.6.9)

**Comment by AlexSchuetz** [comment]
I did the following updates:

- Visual Studio 2017 (Windows) 15.8.2 -> 15.8.7
- Xamarin.IOS (Mac) ->12.0.0.15 (Did that before without updateing Visual Studio on Windows, but remote connection changed it back again. Now the remote connection works with the new version)

I also changed the SDK Version of the IOS-Project from "default" to "12.0".

The compiler error disappeared now.
The runtime exception has gone as well.

Thank you very much Jean-Marc for pointing out the actual version. I really checked updates everywhere except for Visual Studio itself.

**Comment by jmprieur** [comment]
Thanks for confirming it worked, @AlexSchuetz
closing this issue.
BTW, I've also highlighted this issue a bit more (added boldface) in the [Troubleshooting](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Pre-requisites-to-build-ADAL.NET-and-MSAL.NET#troubleshooting) section of pre-requisites.
