### ISSUE TITLE
TokenCache.Clear internal Api  does not clear persistent version of Adal cache 

### ISSUE THREAD

**Issue by SomkaPe** [AzureAD/microsoft-authentication-library-for-dotnet#651]
TokenCache.Clear internal API does not clear persistent  Adal cache - only Msal persistent  cache cleared.

Root cause:
"onAfter" delegate is not called (only in memory representation of Adal cache is cleared).

**Comment by jennyf19** [comment]
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).
