### ISSUE TITLE
RemoveAdalUser internal API does not remove all relevant Adal cache entities (migrarion form adalv3 to adalv4 to msal2 scenario)

### ISSUE THREAD

**Issue by SomkaPe** [AzureAD/microsoft-authentication-library-for-dotnet#652]
RemoveAdalUser internal API  remove users only by accountId.
This approach does not work for next scenario:
if you get AT for res1 in adal v3 than migrate to adal v4 and get token to res2 you will have next state of the cache:
for the same Account you have one entity in adal cache in adalv3 format (no client info)
another entity in adal v4 format (with client info).
So you have two Adal cache entities for the same account .

If you migrate to Msal and call get accounts api one Account object will be returned.
If you call Remove account it will remove only V4 adal entity , so next call to get accounts will return same account object (this time with id null)

So remove account api will not remove account .

RemoveAdalUser api should remove users by accountId and by displayableId ( to cover scenario of
migrarion form adalv3 to adalv4 to msal2)

**Comment by jennyf19** [comment]
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).
