### ISSUE TITLE
NullPoinetEx in RemoveMsalAccount and RemoveAdalUser  when adalv3 account passed

### ISSUE THREAD

**Issue by SomkaPe** [AzureAD/microsoft-authentication-library-for-dotnet#653]
NullPoinetEx in RemoveMsalAccount (Msal) - when adalv3 account passed
NullPoinetEx in RemoveAdalUser (Msal) - when adalv3 account passed

adalv3 account - has null account Id because it is derived from client info, which is not requested in adal v3

**Comment by jennyf19** [comment]
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).
