### ISSUE TITLE
TokenCacheSerializeHelper.DeserializeUnifiedCache does not clear in memory version of cache Instead int appends it

### ISSUE THREAD

**Issue by SomkaPe** [AzureAD/microsoft-authentication-library-for-dotnet#654]
TokenCacheSerializeHelper.DeserializeUnifiedCache does not clear in memory version of cache so it is appending it instead.

it is an issue when persisted cache is shared by few app.
If persisted cache is cleared by app 1, and than app 2  read  persistent cache -  cache entities stored in memory will be be kept so cache clear operation by app 1 will be ignored by app 2

**Comment by jennyf19** [comment]
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).
