### ISSUE TITLE
On NetCore, the token cache is always shared 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#656]
---
name: Bug report
about: Create a report to help us improve

---

**Which Version of MSAL are you using ?**
dev and MSAL 2.3.0

**Which platform has the issue?**
netcore

**What authentication flow has the issue?**
Both Public and Confidential clients. All flows that use a token cache.
    
**Repro**
1. Create 2 ConfidentialClient or PublicClients objects. On each one, create a new TokenCache. Do not configure serialization.
2. Acquire a token with the first object. 
3. Look at the token cache of the second object

**Expected behavior**
The second object should have 0 tokens in the cache. This is the behaviour on net45.

**Actual behavior**
The second object has the same number of tokens as the first one.  

**Possible Solution**
It seems that on netcore the token cache is inadvertently shared between all objects, even if the user specified new TokenCache. The behaviour of netcore should be identical to net45 in this case.

**Additional context/ Logs / Screenshots**
This behaviour is captured by many unit tests, but we are only running ut on net45. TokenCacheTests and 
 ConfidentialClientApplicationTests mostly fail on netcore. I have ignored them - once this bug is fixed they must be re-enabled.

Note: the bug is in core, in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/core/src/Platforms/netcore/NetCorePlatformProxy.cs#L115 (see that it's creating a singleton whereas on net45 it's creating a new object every time). This affects ADAL as well. Haven't looked at the other platforms

**Comment by henrik-me** [comment]
Just discussed with Petro. Pls. validate the scenario where we have both an application cache and a user cache. This may be an issue on other platforms as well. @SomkaPe has additional details.

**Comment by henrik-me** [comment]
Fix is in the repo. Will be part of the next release
