### ISSUE TITLE
AcquireTokenWithDeviceCodeAsync should respect AAD API version, (send either code or device_code)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#658]
**Is your feature request related to a problem? Please describe.**
For device code flow, MSAL.NET currently sends `code` whereas the OAuth2.0's standard wants `device_code`.

During the deployment, both should be supported based on AAD's expectations

**Comment by jennyf19** [comment]
fixed in [2.3.1-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.3.1)
