### ISSUE TITLE
ADAL vs. MSAL AuthenticationResult AccessToken Different

### ISSUE THREAD

**Issue by myokeeh** [AzureAD/microsoft-authentication-library-for-dotnet#660]
I've noticed that the `AccessToken` from `AuthenticationResult` from ADAL vs. MSAL are different.

Why? Any way to have MSAL return `AccessToken` as ADAL would?

Context:

Using Azure App Services, `LoginAsync` works with the access token from ADAL, but not the one from MSAL.

**Comment by jmprieur** [comment]
@myokeeh : do you have detailed repro steps that we could follow to understand what is your expected result and what you observe? For the moment, I don't understand your question.

MSAL does return an access token (AuthenticationResult.AccessToken). MSAL.NET does all what ADAL.NET does and more in the sense that it's capable of returning an Azure AD v2.0 token in the case the scopes you use correspond to a v2.0 resource.

**Comment by myokeeh** [comment]
Expected behavior is a successfull log-in to Azure App Services using the AccessToken.

This works:
```
    AuthenticationContext ac = new AuthenticationContext(authority);
                                    Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult adalar = await ac.AcquireTokenAsync(resourceId, clientId,
                                    new Uri(redirectUri),
                                    new PlatformParameters(PromptBehavior.Always, false),
                                    UserIdentifier.AnyUser,
                                    "domain_hint=test1.com");
                                payload = new JObject
                                {
                                    ["access_token"] = adalar.AccessToken
                                };
                        mobileServiceClient.CurrentUser = await mobileServiceClient.LoginAsync(MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory, payload);
```

This does not work (Exception at LoginAsync):
   ```
 PublicClientApplication pca = new PublicClientApplication(clientId)
                                {
                                    RedirectUri = redirectUri
                                };
                                string[] scopes = { "User.Read" };
                                IUser user = pca.Users.FirstOrDefault();
                                Microsoft.Identity.Client.AuthenticationResult msalar = await pca.AcquireTokenAsync(
                                    scopes, user, UIBehavior.ForceLogin, "domain_hint=test1.com");
                                payload = new JObject
                                {
                                    ["access_token"] = msalar.AccessToken
                                };
mobileServiceClient.LoginAsync(MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory, payload);
```

**Comment by jmprieur** [comment]
@myokeeh : what was the resourceId in ADAL.NET? Is it a Web API ? I see that you have used scopes = {"User.Read"} which is for reading the profile of the use who signed-in in the app. 

If it's a web API, you might want to try string[] scopes = { resourceId+"/user_impersonation"}

For more details, please read: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal and in particular on scopes for a V1 application: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#scopes-for-a-v10-application

**Comment by argtechnologies** [comment]
hi @jmprieur  
Even after using /user_impersonation, i get the error "You do not have permission to view this directory or page." The access token works fine in postman when used as a bearer token to access a web api. I am using it in a xamarin android app.
Any help would really make my day.

**Comment by jmprieur** [comment]
@trwalke would you know?
