### ISSUE TITLE
Could not resolve type with token 010000dd (from typeref, class/assembly Microsoft.Identity.Client.ClientCredential

### ISSUE THREAD

**Issue by teelinmaloney** [AzureAD/microsoft-authentication-library-for-dotnet#663]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
2.3.1-preview

**Which platform has the issue?**
Xamarin android, Xamarin iOS

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username / Password
    * [ ] Device code flow (browserless)
* Mobile
    * [x] Xamarin.iOS
    * [x] Xamarin.Android
    * [ ] UWP
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO
* Daemon App
    * [ ] Client credentials
    
Other? - please describe;

**What is the identity provider ?**
* [x] Azure AD
* [ ] Azure AD B2C

If B2C, what social identity did you use?

**Repro**

```csharp
class MyService {
    ClientCredentials appCredentials = new ClientCredential(Constants.AppAuthentication.ClientSecret);
    ConfidentialClientApplication cca = new ConfidentialClientApplication(
                Constants.AppAuthentication.ClientId, 
                $"{Constants.AppAuthentication.Authority}/oauth2/authorize", 
                "urn:ietf:wg:oauth:2.0:oob", appCredentials, null, null);
}
```

**Expected behavior**
Expect to be able to instantiate ClientCredentials and ConfidentialClientApplication

**Actual behavior**
Runtime error occurs when instantiating class containing a ClientCredential variable in iOS and Android apps.

Could not load type of field ‘MyService:appCredentials' (0) due to: Could not resolve type with token 010000dd (from typeref, class/assembly Microsoft.Identity.Client.ClientCredential, Microsoft.Identity.Client, Version=2.3.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae) assembly:Microsoft.Identity.Client, Version=2.3.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae type:Microsoft.Identity.Client.ClientCredential member:(null) signature:<none>

**Possible Solution**

**Additional context/ Logs / Screenshots**
At first I thought this could be related to NuGet caching, however, we've tried multiple versions of the library (2.x.x+), cleaned/rebuilt/restarted/etc., with no luck. Tried on multiple machines as well. I am able to successfully use this code running a LinqPad script on windows, however, when running the Xamarin app in either the iOS sim or Android sim, the exception will be thrown when the class is instantiated.
Also, we are using a PublicClientApplication in the same app without any issues.

**Comment by jmprieur** [comment]
@teelinmaloney : the authority **should not** contain "/oauth2/authorize". What you have expressed is the authorize endpoint of the authority.
Use the following as the second parameter of the constructor
```CSharp
$"{Constants.AppAuthentication.Authority}
```

**Comment by teelinmaloney** [comment]
@jmprieur In this case the code never even makes it that far. Take the following example:
```
class MyService {
    public async Task<string> AcquireTokenAsync() {
        var creds = new ClientCredential("secret"); // set a breakpoint here
        // ... instantiate ConfidentialClientApplication
    }
}

var service = new MyService();
await service.AcquireTokenAsync(); // throws type load exception, breakpoint never hit
```

**Comment by bgavrilMS** [comment]
@teelinmaloney - ConfidentialClient is not supported on iOS and Android - only the public client. The fact that it appears on Intellisense is a bug - I assume that your auth code is in the "shared" assembly, which is a NetStandard assembly. The Netstandard assembly exposes ConfidentialClient, so that it can be used in .net core applications. On iOS and Android we should throw PlatformNotSupportedException. @jmprieur to prioritize the bug. 

@teelinmaloney - Does your scenario require a non-interactive auth flow? If your app is ok with popping up the browser, then please use PublicClientApplication.

**Comment by teelinmaloney** [comment]
@bgavrilMS You are correct, it is within the shared assembly. We do require the use of non-interactive auth flow as this is for a service account which the user should not need to interact with. We were using the ADAL library before to accomplish this however we were hoping to be able to consolidate down to a single library. The PCA instance that we're using authorizes the user using B2C. Is there any plan to support this in the future?

**Comment by bgavrilMS** [comment]
@teelinmaloney - the ADAL method you are using is not meant for mobile apps. I've obsoleted it just now, all the other overloads were obsolete on mobile. As you can see, this isn't for technical reasons, i.e. the flows work fine, but for security reasons. You can read more about this here: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Right-usage-of-confidential-client-flows

We do not plan to expose the ConfidentialClient on mobile platforms on MSAL. Both me and @jmprieur are happy to assist you to choose the right flow for your scenario, if you could describe what you are trying to do. Generally, you should make your mobile app access a protected API, and the middleware protected API can use the ClientCredential flow to access the resource.

**Comment by teelinmaloney** [comment]
@bgavrilMS Thanks for the clarification. We're connecting to the Dynamics CRM API, which requires either a licensed user or application user to authenticate. If our mobile users were licensed in Dynamics, we'd be able to use an interactive flow, however, since they are not licensed (e.g., users outside the organization), we need to communicate with the API using a non-interactive application user. After reading the post you provided, it makes sense that having the secret on the device would be a potential security issue. Given this scenario, are there any approaches you'd suggest that can accomplish what we need non-interactively and without standing up another service to proxy the requests?

**Comment by bgavrilMS** [comment]
I would consider having a WebApi in the middle. Users / mobile apps connect to the WebApi, performing interactive flow. The WebApi connects to Dynamics using ClientCredentials (i.e. application wide grants). We have a sample showing how to protect a WebApi and how to access it here https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2

@jmprieur can also chime in / confirm this is a reasonable approach

**Comment by jmprieur** [comment]
yes, for this scenario that's the best approach.
Closing this issue. Knowing that we want to improve the exceptions (to an answer to the initial question See #679)
