### ISSUE TITLE
Unhandled Exception: MsalClientException:  Chrome is not installed on the device

### ISSUE THREAD

**Issue by AlexSchuetz** [AzureAD/microsoft-authentication-library-for-dotnet#664]
**Which Version of MSAL are you using ?**
MSAL 2.3.0-preview

**Which platform has the issue?**
xamarin android

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username / Password
    * [ ] Device code flow (browserless)
* Mobile
    * [ ] Xamarin.iOS
    * [x] Xamarin.Android
    * [ ] UWP
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO
* Daemon App
    * [ ] Client credentials

**What is the identity provider ?**
* [ ] Azure AD
* [x] Azure AD B2C

If B2C, what social identity did you use?
Google

**Repro**
If I am running on a device where chrome is not installed an unhandled(!) exception is thrown if `AcquireTokenAsync` is called inside of `try { ... } catch (Exception ex) { ... }`
 
**Expected behavior**
Loginscreen should be presented in a browser and all exceptions should be "catchable".

**Actual behavior**
This unhandled exception is thrown:
```
Unhandled Exception:

Microsoft.Identity.Client.MsalClientException:  Chrome is not installed on the device, cannot proceed with authentication 
```
**Possible Solution**
Use the default installed browser.

**Comment by AlexSchuetz** [comment]
I also tried **MSAL 2.3.1-preview**

**Comment by jmprieur** [comment]
@AlexSchuetz 
We have the code in dev to fix this. We need to release it
cc: @jennyf19 @henrik-me

**Comment by AlexSchuetz** [comment]
Do you have a schedule for this? We need to move to production soon 😅

**Comment by jmprieur** [comment]
@AlexSchuetz : is it an option for you to [build](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Pre-requisites-to-build-ADAL.NET-and-MSAL.NET) MSAL.NET and try-out if this solves your issue?

**Comment by AlexSchuetz** [comment]
@jmprieur Still have to fix some issues myself ;) But I will have a look at it. Do I need to build the MSAL.sln?

**Comment by jmprieur** [comment]
@AlexSchuetz : the dev branch. and yes, this is MSAL.sln.

**Comment by AlexSchuetz** [comment]
@jmprieur I am sorry. At the moment I don't have the spare time to test this.

**Comment by jmprieur** [comment]
no issues @AlexSchuetz. Thanks for the update. We should release in the near future

**Comment by jennyf19** [comment]
@AlexSchuetz 
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).

**Comment by AlexSchuetz** [comment]
UNfortunately the issue seems not to be fixed completely in 2.4.0-preview. The exception is gone and I get the login screen, but after logging in I don't get redirected to my app. Instead I see a black window (standard browser) containing my app-package in the navigation bar.

My redirect-url doesn't follow "msal{appid}://auth" but "myapp{appid}://auth" this hasn't been a problem until now.

**Comment by AlexSchuetz** [comment]
Strange thing: On the login screen (default browser with API 6.0) the navigation bar show the following url:

`https://login.microsoftonline.com/<tenant>.onmicrosoft.com/oauth2/authorize?client_id=<...>&redirect_uri=https%3a%2f%2flogin.microsoftonline.com%2fte%2f<tenant>.onmicrosoft.com%2foauth2%2fauthresp&response_type=id_token&scope=email+openid&response_mode=query&nonce=zWO%2fbsXSlzUc7QOn0VHTRg%3d%3d&nux=1&nca=1&domain_hint=<tenant>.onmicrosoft.com&prompt=select_account&mkt=en-US&lc=1033&state=StateProperties%3deyJTSUQiOiJ4LW1zLWNwaW0tcmM6ZDU0YjY0MjktNTNjZC00MDUyLTgxOTAtZTU5ZGNjYzBlM2JmIiwiVElEIjoiOGNmMzk1ZDEtYzc1NS00ZjYxLTgyYjQtZjk1YTdmMTQyMTA4In0`

which includes the redirect-uri: **https://login.microsoftonline.com/te/<tenant>.onmicrosoft.com/oauth2/authresp** which is not the redirect-uri that I configured on PublicClientApplication.

**Comment by AlexSchuetz** [comment]
@jmprieur Unfortunately I cannot give you any hints on how the B2C tenant is configured, since I am no admin for this tenant. I just can provide the parameters I am using to configure MSAL:

```csharp
public const string ApplicationID = "<appid>";
public const string Tenant = "<tenant>.onmicrosoft.com";
public static readonly string PolicySignUpSignIn = "B2C_1_APP_LOGIN";
public static readonly string AuthorityBase = $"https://login.microsoftonline.com/tfp/{Tenant}/";
public static readonly string Authority = $"{AuthorityBase}{PolicySignUpSignIn}";
public static readonly string RedirectUrl = $"<myprefix>{ApplicationID}://auth";
...

AuthenticationClient = new PublicClientApplication(
            AuthenticationConstants.ApplicationID,
            AuthenticationConstants.Authority)
            {
                RedirectUri = AuthenticationConstants.RedirectUrl
            };

...

AuthenticationResult authResult = 
                            await App.AuthenticationClient.AcquireTokenAsync(AuthenticationConstants.Scopes, App.UiParent);
```

**Comment by jmprieur** [comment]
oh! this works fine with Chrome, but not with the other browser.
Which browser is it? Did you see this page? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Android-system-browser
cc: @jennyf19

**Comment by AlexSchuetz** [comment]
@jmprieur Thanks for the link. I tested with the standard browser on Android 6.0 (the blue world globe) and no other browsers installed.

**Comment by jmprieur** [comment]
@jennyf19 is it something you tested? do we want to update the table?
