### ISSUE TITLE
AADSTS65002: Consent between first party applications and resources must be configured via preauthorization.

### ISSUE THREAD

**Issue by DevKumar4Git** [AzureAD/microsoft-authentication-library-for-dotnet#668]
While trying to use AcquireTokenWithDeviceCodeAsync with msal 2.3.1 preview, I am hitting this issue while login to https://microsoft.com/devicelogin with auth code. I am using a console app on .net core.

**Comment by jmprieur** [comment]
@DevKumar4Git :  sent you an email with the explanation, as this is a first party specific error.
