### ISSUE TITLE
Send client_info=1 parameter on token endpoint.

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#67]
We need to send client_info=1 parameter on token endpoint to get uid, utid. Update cache model to use uid/utid as a key instead of home oid.

**Comment by abhishek58g** [comment]
In this feature we would be taking the attribute of home oid from id_token to client info(Profile scope would be renamed to Client Info).Presently in MSAL we get home_id from id_token and we would be modifying this design.home_id would now be obtained from client_info.This would be a better design as it would avoid developers from taking dependencies on it.
