### ISSUE TITLE
CI tool warns about breaking changes in the public API

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#670]
**Is your feature request related to a problem? Please describe.**
We want to know when there are API breaking changes

**Describe the solution you'd like**
Identity Model Extensions for .NET have a tool to do that
- CI tool breaks the CI build when the PR proposes a breaking change in the public API
- CI tool issues a warning when the PR proposes a (non-breaking) change in the public API

**Comment by jmprieur** [comment]
@GeoK @brentschmaltz @mafurman as discussed.

**Comment by henrik-me** [comment]
@jmprieur : let's prioritize completing this? (easier sign-off on releasees)

**Comment by brentschmaltz** [comment]
OK @GeoK put together the Wilson work.

**Comment by henrik-me** [comment]
Will pick up later. Un-assigning form Travis

**Comment by jennyf19** [comment]
closing, as old.
