### ISSUE TITLE
No help exists for the MSAL.PS PowerShell cmdlets

### ISSUE THREAD

**Issue by AspenForester** [AzureAD/microsoft-authentication-library-for-dotnet#671]
### Documentation Related To Component:
Help for MSAL.PS cmdlets

### Please check those that apply

- [ ] typo
- [X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [X] needs example

### Description Of The Issue
Please provide an example that demonstrates each of the of Parameter Sets for each of the cmdlets.
Thank you!

**Comment by henrik-me** [comment]
@AspenForester : Can you pls. point to the PowerShell cmdlets you are referring to? This team doesn't ship any powershell cmdlets, however perhaps with a pointer to the exact scripts we can find the missing information.

**Comment by anmolkarol** [comment]
https://www.powershellgallery.com/packages/MSAL.PS/1.1.4.1

**Comment by jmprieur** [comment]
@anmolkarol 
We (MSAL.NET team) don't own this PowerShell module (which BTW seems to use an old version of MSAL.NET) did you try to [contact its owners](https://www.powershellgallery.com/users/account/LogOn?ReturnUrl=%2Fpackages%2FMSAL.PS%2F1.1.4.1%2FContactOwners) ?

Closing as external
