### ISSUE TITLE
Add support for SecureString in .netcore

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#674]
**Is your feature request related to a problem? Please describe.**
The feature is tied to improving security of the library. Adding SecureString well help with that.
See Customer ask here:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1026

**Describe the solution you'd like**
Add SecureString for the ClientSecrets and for password in .netcore (similar to how it's done in .net). It should be considered to add SecureString for the ClientSecret as well.

Suggested approach is described in the issue mentioned above.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1026

**Comment by bgavrilMS** [comment]
This is done. SecureString is now supported by all our platforms: 

- on .netcore ,net desktop and .net standard  in order to support U/P
- on Android, iOS and UWP in order to be able to throw a nice PlatformNotImpl exception

**Comment by djj0809** [comment]
@bgavrilMS  Hey, I noticed there is no ConfidentialClientApplicationBuilder.WithClientSecret(SecureString) available, is this not implemented or did I miss something?

**Comment by bgavrilMS** [comment]
Hi @djj0809 - you are right, this was only implemented for the ROPC / Username+Password authentication flow.

Please raise a feature request if you need this, but note that .net is moving away from SecureString https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netframework-4.8#remarks .. The potential security gains are very small, essentially MSAL will keep the secret in memory as a SecureString for an extra few milliseconds, but once it has to send an HTTP request, it will transform it into a string.

**Comment by djj0809** [comment]
> Hi @djj0809 - you are right, this was only implemented for the ROPC / Username+Password authentication flow.
> 
> Please raise a feature request if you need this, but note that .net is moving away from SecureString https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netframework-4.8#remarks .. The potential security gains are very small, essentially MSAL will keep the secret in memory as a SecureString for an extra few milliseconds, but once it has to send an HTTP request, it will transform it into a string.

Really thanks for your advice, and the link is quite helpful. I'll consider to use other approaches.
