### ISSUE TITLE
MSAL 2.0 deprecates IUser but IAccount methods documented are not implemented

### ISSUE THREAD

**Issue by Journeyman42** [AzureAD/microsoft-authentication-library-for-dotnet#677]
---
name: Bug report
about: Create a report to help us improve

---

**Which Version of MSAL are you using ?**

2.3.1

**Which platform has the issue?**

Xamarin Forms (all)

**What authentication flow has the issue?**

* Mobile
    * [ ] Xamarin.iOS
    * [ ] Xamarin.Android

**What is the identity provider ?**

* [ ] Azure AD B2C

If B2C, what social identity did you use?

Email

**Repro**

Documentation states IUser has been deprecated and replaced with IAccount

Samples show a method FirstOrDefault() which is not available in the library

How do use IAccount if IUser is no longer supported yet the library hasn't fully implemented IAccount pls?

**Comment by bgavrilMS** [comment]
FirstOrDefault is not part of MSAL, it is part of System.Linq. 

```cs
using System.Collections.Generic;
using System.Linq;


namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            IEnumerable<string> collection = new[] { "foo", "bar", "baz" };
            string first = collection.FirstOrDefault(); // returns "foo" but if the collection were empty, it would return null (default of string)

            if (first == null)
            {
                // do stuff
            }
            else
            {
                // do some other stuff
            }
        }

       
    }
}

```

**Comment by Journeyman42** [comment]
Please ignore, beginner error

**Comment by bgavrilMS** [comment]
No prob :)
