### ISSUE TITLE
Standardize IPublicClientApplication

### ISSUE THREAD

**Issue by dansiegel** [AzureAD/microsoft-authentication-library-for-dotnet#679]
# Description

An interface should define a common contract that is available across all Target Frameworks. By using compiler directives to change the API, this further makes the library untestable for mobile applications as methods that exist in netstandard simply do not exist in netcore unit tests. 

Note that the idea of a contract does not mean that each method is expected to also be implemented on a specific Target Framework. By providing this common contract this means that I may have an implementation in netstandard library like:

```cs
var result = await pca.AquireTokenAsync(scopes, account, uiParent);
```

This would then allow me to mock AquireTokenAsync and properly test my code... As a side note AuthenticationResult needs to be opened up as the only way I have of creating an instance to return in a unit test is with an insane amount of reflection.

**Comment by bgavrilMS** [comment]
@dansiegel - thank you opening these issues, this is great feedback. 

I opened a separate issue for AuthenticationResult: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/682 - let's keep this one focused on the IPublicClient interface. 

We've discussed internally several approaches to improving the experience when using the api across multiple platforms and across netstandard. The 2 main conflicting scenarios are: 

- Entry point into the app is NetCore, but auth code is in written into a NetStandard assembly. On these platforms we do not currently support PublicClient
- Xamarin app with 3 heads (iOS, Android and UWP), with auth code (mostly) in NetStandard assembly. On these platforms we do not support ConfidentialClient (and never will)

So in fact, IPublicClient interface would have nothing if it were an intersection of all platforms. 

The main proposal that we are thinking of is: 

- Add a superset of all functionality to the NetStandard implementation. IPublicClient interface on netstandard will have all methods
- Use reference assemblies to hide some of these functionalities when developers target specific platforms (for example, hide an iOS specific property in the iOS tfm). 
- Throw PlatformNotImplemented exception in the actual assemblies or, in some cases, do nothing, in the implementation assemblies.

How does this sound? Would it improve the experience and testability?

**Comment by dansiegel** [comment]
@bgavrilMS Personally I don't think there should be any bait/switch on the signature of the interface regardless of platform. While I find it a shame that there is no intent to implement authentication with credentials on iOS/Android, I also understand it.

Whether my actual code is in a netstandard library or actually on iOS I would still expect to see this method signature on the interface with a thrown Platform Not Implemented exception.

I realize beyond the scope of the authentication methods, there were some properties I noticed that are part of the interface depending on which platform you are on. I might suggest that if they aren't universally needed, are they really something that even belong as part of the interface, and not simply something that is part of the implementing class.

**Comment by bgavrilMS** [comment]
Thanks @dansiegel, that makes sense. I'll prototype a version with bait/switch and without and see the implications. 

We will not implement Confidential Client flows on mobile platforms because that would lead to a security issue, i.e. there is not secure way of deploying a secret to a mobile app and the OAuth spec reinforces this. Otherwise, it would be just a matter of enabling them ...

I'll have a look at making sure our interfaces are in sync with the objects, via unit tests. Currently we run unit tests only on net45 and netcore; getting the unit tests on other platforms proved too complex / unstable.

**Comment by dansiegel** [comment]
I'd be happy to setup a call sometime to discuss the Confidential Client flow issue. I'm not sure that I would make the jump to there is no secure way of embedding an application secret. 

Any yes the testing tools for iOS and Android need a lot of work before they can be truly usable.

**Comment by bgavrilMS** [comment]
Sounds good @dansiegel - I plan to take a look at all these changes next week, so that might be a good time to talk. Should I send you an invite for sometimes next week ?

**Comment by dansiegel** [comment]
I will have some time on Monday/Wednesday. Feel free to send over an invite dsiegel@avantipoint.com

**Comment by jmprieur** [comment]
This is now solved in [MSAL.NET 2.6.0](https://aka.ms/msal-net-2-6)
