### ISSUE TITLE
Microsoft.Identity.Client missing reference

### ISSUE THREAD

**Issue by hannespreishuber** [AzureAD/microsoft-authentication-library-for-dotnet#680]
ASP.NET webforms website VB.NET (not a project)
.net 4.6.2
installed  via nuget (placed in bin)
microsoft.identity.client 2.4 preview
(tried also earlier)

Private Property _tokenCache As TokenCache

TokenCache is unknown
also object browser doens't show complete dll

my intend is to create a prototype for adding items from a website to teams/planner- the sample code is from hell

**Comment by hannespreishuber** [comment]
after 8 h nuget package uninstall install 
I stuck on 
System.IdentityModel.Tokens.ISecurityTokenValidator assembly could not be load

**Comment by bgavrilMS** [comment]
Hi @hannespreishuber 

Please follow the template for logging issues ... Could you give a code sample of what you are trying to do? 

Also, what sample are you following that you are finding problematic?

TokenCache is part of the public API, I can see it with dotPeek, most of our samples use it and the code shows it is public:

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/msal/src/Microsoft.Identity.Client/TokenCache.cs

**Comment by jmprieur** [comment]
ISecurityTokenValidator is part of [Identity Model Extensions for .NET](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/), not MSAL.NET. We'd really need to see some code, @hannespreishuber

**Comment by hannespreishuber** [comment]
thanks for help, it is a bigger project, where I added the azureAD instead ASP.net membership- worked- then I added the dll for Microsoft Graph, got 1st error in code, removed everything and added again packages.  Now i have a compilation error, not related to code 


Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Reference.svcmap: Der Typ "System.IdentityModel.Tokens.ISecurityTokenValidator" in der Assembly "System.IdentityModel.Tokens.Jwt, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" konnte nicht geladen werden.		App_WebReferences/CheckVatServiceReference1/		



<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="bootstrap" version="4.1.3" targetFramework="net462" />
  <package id="EntityFramework" version="6.2.0" targetFramework="net462" />
  <package id="EntityFramework.de" version="6.2.0" targetFramework="net462" />
  <package id="FontAwesome" version="4.7.0" targetFramework="net462" />
  <package id="jQuery" version="3.3.1" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.Core.de" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.de" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb.de" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.6" targetFramework="net462" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net462" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net462" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.1" targetFramework="net462" />
  <package id="Microsoft.Graph" version="1.12.0" targetFramework="net462" />
  <package id="Microsoft.Graph.Core" version="1.12.0" targetFramework="net462" />
  <package id="Microsoft.Identity.Client" version="2.4.0-preview" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Logging" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols.WsFederation" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Tokens.Saml" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Xml" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.Owin" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.de" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Host.SystemWeb.de" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security.Cookies" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.ReportingServices.ReportViewerControl.WebForms" version="150.900.148" targetFramework="net462" />
  <package id="Microsoft.SqlServer.Types" version="14.0.1016.290" targetFramework="net462" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net462" />
  <package id="Owin" version="1.0" targetFramework="net462" />
  <package id="popper.js" version="1.14.3" targetFramework="net462" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.3.0" targetFramework="net462" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net462" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net462" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net462" />
</packages>

**Comment by jmprieur** [comment]
@hannespreishuber : please ensure that all the Microsoft.IdentityModel. nuget packages have the same version. Closing this issue from here (MSAL.NET) as external. Feel free to open a question in  [Identity Model Extensions for .NET](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/)
