### ISSUE TITLE
Contributors are confused by master / dev branches

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#684]
---
name: Bug report
about: Create a report to help us improve

---

Contributors have reported that our branch naming and branch housekeeping is confusing. Namely: 

1. We have a master branch that is severely outdated. "master" is the git default, so people instinctively go there. We should get rid of master because we decided not to follow the "git flow" branching strategy, so there is no value in having master. OR (preffered) we should get rid of "dev" and have the team work on "master" instead

2. There are a ton of branches in the "root" repository, that are confusing. We should only keep the bare minimum, i.e. dev and adalv3dev, plus the branches prefixed by individual contributor's aliases.

**Comment by henrik-me** [comment]
Suggestion, (ADAL repo): 
Remove/Delete master
rename dev to master 
rename adalv3dev to adalv3-master. 
Remove unused branches

Not sure though this brings the clarity. As we have already described what is where in the read.me file.

**Comment by henrik-me** [comment]
Seems very related to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/648

**Comment by jmprieur** [comment]
@bgavrilMS : proposing to close this issue if you agree.

**Comment by bgavrilMS** [comment]
I think we should still do this at least for MSAL. Either move to the master branch, or delete it completely.
