### ISSUE TITLE
UIParent doesn't work on Android 4.4

### ISSUE THREAD

**Issue by bryans2k** [AzureAD/microsoft-authentication-library-for-dotnet#685]
**Which Version of MSAL are you using ?**
2.4.0-preview

**Which platform has the issue?**
xamarin android

**What authentication flow has the issue?**
* Mobile
    * [X ] Xamarin.Android
    
Other? - please describe;

**What is the identity provider ?**
* [X] Azure AD

```csharp
protected override void OnCreate(Bundle savedInstanceState)
{
    TabLayoutResource = Resource.Layout.Tabbar;
    ToolbarResource = Resource.Layout.Toolbar;

    base.OnCreate(savedInstanceState);
    global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
    LoadApplication(new App());
    App.UiParent = new UIParent(this);
}
```

**Expected behavior**
When ran on an Android 4.4 AVD after authenticating I expected to return to the Xamarin App instance. This works as expected on Android 8.1 but not Android 4.4.

**Actual behavior**
It returns to the Android default MainActivity instead.

**Comment by jmprieur** [comment]
See also https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/54 for repro steps.
cc: @jennyf19

**Comment by bgavrilMS** [comment]
This is no longer actual as we have refactored this API in msal 3.x and have validated this scenario.
