### ISSUE TITLE
MSAL performance degradation in .NET Framework compared to .NET Core

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#687]
Issue opened in [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1406)

**Comment by jmprieur** [comment]
Fixed with PR https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1407

**Comment by jennyf19** [comment]
Release [2.4.1](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.1)
