### ISSUE TITLE
b2clogin.com with embedded webview and Google auth not allowed

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#688]
## For tracking purposes

**Expected behavior**

Can use embedded webview for authentication with Google in B2C scenario using `{tenant}.b2clogin.com` as authority

**Actual behavior**
[Google auth](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) does not work with embedded webview
![image](https://user-images.githubusercontent.com/19942418/48745441-66a50700-ec20-11e8-9744-b413faae92e0.png)

**Possible Solution**
Use system browser only with Google auth
See if b2clogin.com can be trusted w/login.msol.com

**Comment by jmprieur** [comment]
Closing as external
