### ISSUE TITLE
RedirectUrl is opened in Safari instead of app

### ISSUE THREAD

**Issue by AlexSchuetz** [AzureAD/microsoft-authentication-library-for-dotnet#689]
**Which Version of MSAL are you using ?**
MSAL 2.5.0-preview

**Which platform has the issue?**
xamarin iOS 9 and 10

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username / Password
    * [ ] Device code flow (browserless)
* Mobile
    * [X] Xamarin.iOS
    * [ ] Xamarin.Android
    * [ ] UWP
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO
* Daemon App
    * [ ] Client credentials
    
Other? - please describe;

**What is the identity provider ?**
* [ ] Azure AD
* [X] Azure AD B2C

If B2C, what social identity did you use?
configured by customer

**Repro**

Authenticating works in Simulator with OS version 12.
On OS version 9 and 10 the authentication screen is displayed correctly. I also can enter the credentials, but on submit I get the following message: "Safari cannot open the page because the address is invalid".

On next try I don't even have to enter credentials, but the result is the same.

It seems like the redirect url ("myprefix{appid}://auth") gets opened in safari.

**Expected behavior**
Should return to app after the correct credentials are supplied.

**Actual behavior**
Shows the message "Safari cannot open the page because the address is invalid" and the Loginpage doesn't close.

**Comment by jmprieur** [comment]
@AlexSchuetz :  Did you try to enable the embedded web view? 
See [Choosing between embedded web browser or system browser on Xamarin.iOS](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#choosing-between-embedded-web-browser-or-system-browser-on-xamarinios)

**Comment by AlexSchuetz** [comment]
I was looking for a way to use the webview, but didn't look at this
constructor.

This did the trick. Thanks a lot.

Am Mi., 21. Nov. 2018, 16:20 hat Jean-Marc Prieur <notifications@github.com>
geschrieben:

**Comment by jmprieur** [comment]
Thanks for the update @AlexSchuetz. 
Closing the issue.
