### ISSUE TITLE
Device code flow and token cache

### ISSUE THREAD

**Issue by jnevins-gcm** [AzureAD/microsoft-authentication-library-for-dotnet#691]
Is token caching using the device code flow supported?

I’m seeing behavior such that my device code callback fires on every request, even after deserializing a cache that should already have cached a previously retrieved token.

**Comment by bgavrilMS** [comment]
Hi @jnevins-gcm - please follow the template when you open an issue. 

Can I see a sample of you code? I think you are not calling AcquireTokenSilent - in MSAL, the pattern for acquiring tokens is to check the cache explicitly. I updated the sample code on our wiki to reflect this: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow

**Comment by jnevins-gcm** [comment]
That was it!

Sorry and thanks for the quick response

**Comment by bgavrilMS** [comment]
No problem, glad it worked!
