### ISSUE TITLE
Xamarin ios - Webview not showing password autofill - B2C

### ISSUE THREAD

**Issue by WilliamWatterson86** [AzureAD/microsoft-authentication-library-for-dotnet#692]
---
name: Bug report
about: Create a report to help us improve

---

**Which Version of MSAL are you using ?**
MSAL 2.2.1-preview

**Which platform has the issue?**

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username / Password
    * [ ] Device code flow (browserless)
* Mobile
    * [X ] Xamarin.iOS
    * [ ] Xamarin.Android
    * [ ] UWP
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO
* Daemon App
    * [ ] Client credentials
    
Other? - please describe;

**What is the identity provider ?**
* [ ] Azure AD
* [X] Azure AD B2C

If B2C, what social identity did you use?
Local 

**Repro**
I'm not sure if this is something that a webview in iOS can even do, but I have recently switched from showing the normal safari window when logging in/registering to using the built in webview.  (App.UiParent = new UIParent(true);)  But since doing that iOS does not show suggested passwords (iOS 12) or show the password autofill options.  Is there something extra I need to do when using the built in webview to enable this?

**Expected behavior**
Webview would show the autofill options for password entry and suggest password in iOS 12.

**Actual behavior**
Webview does not show autofill options (using normal safari login shows this)

**Additional context/ Logs / Screenshots**
Screenshots below show login and register using normal safari window.  As you can see, suggested passwords and autofill are showing as expected.

![image](https://user-images.githubusercontent.com/32571925/49002164-b884ea00-f156-11e8-8919-0216dd56bb02.png)

![image](https://user-images.githubusercontent.com/32571925/49002177-c89cc980-f156-11e8-85f7-f148632bbcac.png)

Screenshots below show login and register through webview - here you can see suggested and auto fill passwords do not show up.

![image](https://user-images.githubusercontent.com/32571925/49002216-e702c500-f156-11e8-8bcf-551a88e5cd9f.png)

![image](https://user-images.githubusercontent.com/32571925/49002241-f8e46800-f156-11e8-85c5-87daefc486d8.png)

**Comment by jmprieur** [comment]
Thanks for your feedback.
This is by design: the embedded web browser is a web control, and does not provide the full experience you see with the system browser when the system browser adds completion, secret management etc …

Normally the embedded web view adapts the best to the OS. Which version of iOS are you running on?

**Comment by WilliamWatterson86** [comment]
Ok thanks for replying @jmprieur  - I thought this might be expected with the webview.  The version I have tried with is iOS 12.1.  There is an overall "Passwords" button as shown in the screenshot above.  So the user will just have to tap that and select which password they want to use.  The password suggestions dont come up.

**Comment by jmprieur** [comment]
@jennyf19 do you think that there would be options to set on the embedded web view to enable these features?

**Comment by jennyf19** [comment]
@jmprieur is correct, this is a limitation with embedded webview.

**Comment by jennyf19** [comment]
@WilliamWatterson86 We'll make an update here if anything changes. We're looking into this with our iOS team, but things don't look promising at the moment.
