### ISSUE TITLE
Android Blank Screen On WLAN

### ISSUE THREAD

**Issue by YUVRAJ1912** [AzureAD/microsoft-authentication-library-for-dotnet#696]
Hey,

I am trying to run ADAL code on Xamarin android with 4.4.1 version but I get blank screen on WLAN. Where as working fine with mobile network. I get below message on application output and shows blank screen.

I get [InputMethodManager] [IMM] startInputInner - mService.startInputOrWindowGainedFocus
[VideoCapabilities] Unsupported mime video/sorenson
[InputTransport] Input channel constructed: fd=146
[InputTransport] Input channel destroyed: fd=89
[ViewRootImpl@64491d9[MainActivity]] mHardwareRenderer.destroy()#1
[ViewRootImpl@64491d9[MainActivity]] Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
[cr_BindingManager] Cannot call determinedVisibility() - never saw a connection for the pid: 9957
[cr_BindingManager] Cannot call determinedVisibility() - never saw a connection for the pid: 9957

**Comment by jmprieur** [comment]
@YUVRAJ1912, If this is an ADAL issue, can you please raise it in the [ADAL repo](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet) (here this is MSAL).
Also can you please follow the template that we provide? there is not enough information here for us to be able to help you.

**Comment by jennyf19** [comment]
@YUVRAJ1912 closing, as appears to be an adal issue. Please open an issue there as jmprieur points out, or reopen w/additional information. Please use the latest version of the library, 3.0.8. Thanks.
