### ISSUE TITLE
Add code in Webview renderer to allow Target="_blank" to work for iOS

### ISSUE THREAD

**Issue by WilliamWatterson86** [AzureAD/microsoft-authentication-library-for-dotnet#712]
**Is your feature request related to a problem? Please describe.**
I have a Xamarin app.  In my B2C pages I have a hyperlink included at the bottom which redirects to our website and terms and conditions.  I have recently moved to using the built in WebView rather than launching the Safairi browser.  However, a webview cannot seem to use Target="_blank" to launch the hyperlink in a new browser window.  

**Describe the solution you'd like**
Would there by any way that you could alter an event of the webview to check for a _blank tag and launch the url requested in a new external browser window in Safari?  The _blank tag works well in the Android version of my app. 

**Describe alternatives you've considered**
For now I have just removed the _blank tag from the hyperlink.  But this means the webpage replaces the whole login page inside the webview and there dosent seem to be a way back to the login page.  Clicking cancel at the top of the webview cancels and returns to my app.  This would be frustrating for the user if they had filled out all their information and then tapped on the hyperlink.

**Comment by jmprieur** [comment]
@WilliamWatterson86 
@jennyf19 will confirm, but I think it's a limitation of the iOS browser control (as it works on Android).

Out of curiosity, what specificities of the embedded web view do you need (that prevents you to use the system browser?). In the case of B2C, if your users want to sign-off with google, I believe that might not be able to (See  #688)

**Comment by WilliamWatterson86** [comment]
The main reason I want to use the embedded web view is so I can use Xamarin UI Test to run automated tests on the app. If I use the normal browser the UI tests do not recognise the elements on the login page so I can’t automate the tap on the username and password fields and I need to login to use the app even in the UI tests

**Comment by jmprieur** [comment]
@bgavrilMS, @trwalke  : would you have recommendations for @WilliamWatterson86 on how to test a Xamarin UI app with system browser?

**Comment by bgavrilMS** [comment]
I believe we also use the embedded browser in our Xamarin UI Tests. @trwalke can confirm and provide his insight on the iOS automation

**Comment by trwalke** [comment]
I am not sure if it is possible on app center using the xamarin.uitest framework. We are trying to use the system browser for our testing but it never works. So far, we have had to stick with the embedded webview

**Comment by jmprieur** [comment]
Closing as the answers were provided
