### ISSUE TITLE
Script error on login page "Unable to get property 'reject'".

### ISSUE THREAD

**Issue by 23W** [AzureAD/microsoft-authentication-library-for-dotnet#716]
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

v2.4.0-preview
v2.5.0-preview

**Which platform has the issue?**

net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**What is the identity provider ?**
* [x] Azure AD
* [ ] Azure AD B2C

**Repro**

```csharp
string AppKey = "...My App Key...";

string[] AppScopes =
{
    // Users' scopes
    "User.ReadBasic.All",
    "User.Read",

    // Files' scopes
    "Files.ReadWrite",
    "Files.ReadWrite.All",
};

byte[] tokensStream = null;

var tokenCache = new TokenCache();
tokenCache.SetAfterAccess((TokenCacheNotificationArgs args) =>
{
    if (args.TokenCache.HasStateChanged)
    {
        lock (locker)
        {
            tokensStream = args.TokenCache.Serialize();
        }
    }
});

tokenCache.SetBeforeAccess((TokenCacheNotificationArgs args) =>
{
    lock (locker)
    {
        args.TokenCache.Deserialize(tokensStream);
    }
});

const string DefaultAuthority = "https://login.microsoftonline.com/common/";
var App = new PublicClientApplication(AppKey, DefaultAuthority, tokenCache);

var authResult = await App.AcquireTokenAsync(AppScopes, string.Empty, UIBehavior.ForceLogin, string.Empty);
var accessToken = authResult.AccessToken;
```

**Expected behavior**
Login Form should work without JScript error.

**Actual behavior**
Call `PublicClientApplication.AcquireTokenAsync` shows login form with JScript error: "Unable to get property 'reject' of undefined or null reference." Script URL: https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8395.17/content/cdnbundles/oldconvergedlogin_pcore.min_z2qsp8b10e2xrib0uwoksg2.js
See screenshot bellow.
If user continues execution by pressing "Yes", login finished with valid access token.

**Possible Solution**

**Additional context/ Logs / Screenshots**
![image-2018-12-10-18-23-06-959](https://user-images.githubusercontent.com/11534020/49758864-acf20100-fcc8-11e8-8470-0960417db2ea.png)

**Comment by jmprieur** [comment]
@23W 
this issue is not actionable:
1) we don't know which app topology you are using.
2) we don't know if you are using B2C or not.

Please re-word your issue using the template we provide.

**Comment by 23W** [comment]
@jmprieur 
Thanks, I've updated issue.

**Comment by jmprieur** [comment]
Thanks @23W 
there is an issue on the service side (AAD Login Page). It's fixed, but still need to be rolled out.
Leaving the issue open until it's deployed.

**Comment by 23W** [comment]
Thanks

**Comment by LucasLibis** [comment]
Hello,

I still encounter the same issue. Does the fix need more time to be rolled-out?

![image 1](https://user-images.githubusercontent.com/2340039/50094567-c4bf0d00-0213-11e9-86c1-a3fcb51f5328.png)

Thanks

**Comment by jmprieur** [comment]
you are right. I asked the service team and it has not been fully rolled out yet. 
It should be completed by end of the (Redmond) day.

**Comment by 23W** [comment]
@jmprieur , sorry do you have some information when it will be fixed?

**Comment by vartika29** [comment]
Hi,

Even I am facing the same issue. Sorry but is the issue fixed now?

Thanks

**Comment by LucasLibis** [comment]
Hello,

The issue seems to be solved since this morning

**Comment by jmprieur** [comment]
Thanks for the update @LucasLibis
