### ISSUE TITLE
[Question] How do I impersonate a user with ConfidentialClientApplication without knowing the user's password.

### ISSUE THREAD

**Issue by thchuong-x11** [AzureAD/microsoft-authentication-library-for-dotnet#741]
### Description Of The Issue
I am working on an application where I need access to data of users within my Azure AD without having to know the user's password.

I don't know if that is possible using `ConfidentialClientApplication`.

I have read the documentation of 'On-behalf-of' flow https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow but I have an impression that this flow still needs the user to authenticate himself on another service.

Thanks.

**Comment by jmprieur** [comment]
you could not know the user's password, but have the user sign-in and consent in a public client application that acquires a token for your confidential client application that, then, can call another API on behalf of the user?
.

**Comment by dallancarr** [comment]
@thchuong-x11 this is predicated on storing and retrieving the user's password. Which is something you want to avoid.

**Comment by thchuong-x11** [comment]
Understood.
Thank you very much.
