### ISSUE TITLE
iOS build fails due to issue with iOS SDK when resolving authentication classes

### ISSUE THREAD

**Issue by naxxxel** [AzureAD/microsoft-authentication-library-for-dotnet#758]
**Which Version of ADAL are you using ?**
MSAL 2.6.2
Probably originally caused in 2.2 (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-2.2.0-released#xamarinios-now-leverage-the-best-web-view-depending-on-the-os-version)
Xamarin.Forms 2.5.0.122203

**Which platform has the issue?**
Xamarin iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**
- clone the official MSAL xamarin sample application (https://github.com/Azure-Samples/active-directory-xamarin-native-v2)
- Build the project on the hosted macOS agent in azure pipelines

**Expected behavior**
Build should work

**Actual behavior**
Build fails
`2019-01-07T09:23:47.0205350Z   MTOUCH : error MT2002: Failed to resolve "AuthenticationServices.ASWebAuthenticationSession" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" [/Users/vsts/agent/2.144.0/work/1/s/active-directory-xamarin-native-v2-master/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj]
`

**Possible Solution**
See https://developercommunity.visualstudio.com/content/problem/363357/error-failed-to-resolve-authenticationservicesaswe.html

> Madhuri Gummalla [MSFT] · 4 days ago 0   Share
> We have determined this is a bug in either MSAL or Xamarin. MSAL introduced this in their 2.2-preview release:
> https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-2.2.0-released#xamarinios-now-leverage-the-best-web-view-depending-on-the-os-version
> As you can see, they started to integrate ASWebAuthenticationSession when running iOS 12, however it looks like they are trying to use this class even when we are building with iOS 11.4 sdk. We can't pinpoint the bug to msal or Xamarin without knowing the code base.
> Workarounds -
> - Use the script provided in the solution. The script basically setups the host build to run iOS 12 sdk.
> - Downgrade to 2.1.0-preview version of MSAL

> Yang Cao (VSNC) [MSFT] · Dec 19, 2018 at 09:12 PM
> I followed this issue and got a build to work with this step. This looks like a Xamarin version issue. I got the SYMLINK by listing /Library/Frameworks folder.
> script: |
    `echo "Setting mono version to 5.12.0"
    SYMLINK=5_12_0_XC10_PRE
    MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
    echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
    echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
    echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
    echo "Appending AppleSdkRoot to Settings.plist"
    mkdir -p /Users/vsts/Library/Preferences/Xamarin
    cd /Users/vsts/Library/Preferences/Xamarin
    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"https://www.apple.com/DTDs/PropertyList-1.0.dtd\"><plist version=\"1.0\"><dict><key>AppleSdkRoot</key><string>/Applications/Xcode_10.app</string></dict></plist>" >> Settings.plist
    echo "Setting Xcode version to 10 for Visual Studio for Mac"
    sudo xcode-select -s /Applications/Xcode_10.app/Contents/Developer
    sudo xcodebuild -showsdks
    sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0_XC10_PRE
  displayName: 'Select the Xamarin SDK version'
  enabled: true`

**Additional context/ Logs / Screenshots**
Full build log attached (created with MSAL 2.4.0 - but error is the same with MSAL 2.6.2)
[50595-build.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/2732128/50595-build.zip)

**Comment by naxxxel** [comment]
> Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later. 

So maybe you can wait it out if you prefer..

**Comment by jennyf19** [comment]
@naxxxel have you followed the [troubleshooting guidelines](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Pre-requisites-to-build-ADAL.NET-and-MSAL.NET#troubleshooting). For ASWebAuthenticationSession to work, you need to have XCode10 on the Mac and latest VS (at least 15.8.7).

**Comment by naxxxel** [comment]
@jennyf19 thanks, altough this only mentions the simulator. Also, in our scenario XCode10 is installed. However, the build is done with iOS 11 SDK due to some system configuration.

=> If MSAL >=2.2 does not support building against iOS 11 SDK, you can close this.

**Comment by jennyf19** [comment]
@naxxxel Closing, as you will need iOS 12.1 sdk.
