### ISSUE TITLE
use of AcquireTokenByUsernamePasswordAsync for msa signin fails

### ISSUE THREAD

**Issue by myusrn** [AzureAD/microsoft-authentication-library-for-dotnet#763]
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
MSAL v2.6.2

**Which platform has the issue?**

netcore 2.1 and netfx 4.6.1 

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [X] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**

```csharp
PublicClientApplication app = new PublicClientApplication(clientId, $"{signinBaseAddress}/{tenantId}/"); // also tried not specifying authority which is same as authority = $"{signinBaseAddress}/common/"
var accounts = await app.GetAccountsAsync();
var securePassword = new NetworkCredential("", password).SecurePassword;
var authResult = await app.AcquireTokenByUsernamePasswordAsync(scopes, username, securePassword);
```

**Expected behavior**
Expected a successful result when I use a microsoft account [msa] username/password credential set given azuread public client app registration has `"signInAudience": "AzureADandPersonalMicrosoftAccount",` configured.  I do get successful result if I use an azuread work or school account [wsa] username/password credential set.

**Actual behavior**
Throws an `MsalException` with message `Response status code does not indicate success: 406 (NotAcceptable).`.  I looked in https://aka.ms/msal-net-up [ -> https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication ] and found no comments on this result and how to address it.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screenshots. Logging is described at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net

**Comment by myusrn** [comment]
@bgavrilMS, thanks for response and related details.

I'm not able to use interactive authentication in this case. When you add Msal Microsoft.Identity.Client to a xUnit .net core unit / integration test project the `AcquireTokenAsync()` method is not exposed.  

Presumably the nuget package has logic that knows when its being used in a non-UI based project environment and so that method is blocked.  Even if it wasn't blocked it wouldn't work in this case because when you tell the "Web Performance and Load Test" project via $(SolutionDir)*.testsettings to execute *.webtest, and *.loadtest groupings of oauth secured web api tests, to execute in the cloud using azure devops cloud load test execution support there isn't an interactive UI story.  

I need ability to auth and acquire token for MSA test account in order to exercise tests for the different claim sets that are in place for that user versus WSA test accounts.  I'd propose this issue be reopened and that support for this is enabled but only in context of a mstest/nUnit/xUnit unit & integration test project environment.

If support for `AcquireTokenByUsernamePasswordAsync()` of MSA test accounts in these scenarios won't be enabled what is the recommended solution for this scenario, that I author a set of http requests to acquire it w/o use of Msal help like postman does?  This doesn't seem like something we would want people doing either.

**Comment by bgavrilMS** [comment]
@myusrn - thank you for the detailed scenario, it's great that you take testing so seriously and we need to make it easier for people to test and provide guidance. 

AcquireTokenAsync does not (yet) exist on .net core because .net core does not have any UI functionality. .NET classic however will pop-up a browser hosted in a WinForm panel. Is it possible for you to switch your unit test project from being .net core to it being .net classic? 

MSA will never allow U/P authentication. Also, as far as I know, there is no technical way of "conditional implementation" (i.e. expose this method only if from test).

**Comment by myusrn** [comment]
@bgavrilMS switching my unit test project from .net core to .net framework would mean having to switch them all from vs17/vs19 xUnit project type to the mstest based unit [ & integration ] project type.  

If msa folks will never allow u/p authentication, even in the case of a unit & integration test project case with perhaps some guards around how frequently it gets called, i'm guessing this means setting up scratch apps to capture valid oauth tokens when needed and apply those to .net core based unit test projects at the start of any period of running tests.  

Not sure how the postman folks are doing it but as I recall they asked me for msa u/p credentials once and from then on used cached copy of those along with public client id & secret to support re-acquiring oauth tokens based on msa account as needed.  

Perhaps there is something about that testing oriented environment that is worth looking at as something that might be replicated in vs17/19 test explorer and .net core based mstest, nUnit and xUnit test projects looking to leverage msal for msa test account integration test calls.

**Comment by bgavrilMS** [comment]
Hi @myusrn . A few thoughts: 

1. xUnit supports both .net core and .net classic. Just go edit the csproj file and change the TargetFramework to a .net classic framework (e.g. "net46"). I just tried it in VS 2019 and it works fine.

![image](https://user-images.githubusercontent.com/12273384/50897628-998ba000-1404-11e9-9a50-5a090330956a.png)

This being said, you did not specify what platform and flavour is your project under test. Is it an asp.net core project? You cannot add a .net core reference to a .net classic project. 

2. What does your test do ? Fetch an access token and then call protected APIs ? Or a more compex E2E, where you start from your website, authenticate and verify that a certain page can be reached? Do you use Selenium?

3. If you switch to interactive authentication, how are you going to manipulate the web ui that pops up? Selenium?

4. Consider using Device Code Flow, which will also get you an access token and it is very easy to automate with Selenium (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow). You can check out how I automated this in a test: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/tests/Microsoft.Identity.Test.Integration/SeleniumTests/DeviceCodeFlowIntegrationTest.cs#L81

**Comment by myusrn** [comment]
@bgavrilMS, thanks for the continued followup on how to address this scenario

wrt 1.  didn't know I could do that but in this case I am unit & integration testing asp.net core web api implementations that include some .net core class libraries they reference

wrt 2.  currently I use a separate app to do signin and token acquisitions for three different web api endpoint audience Uri's I need to test.  I apply those to the xUnit .net core projects appsettings.json file which buys me an hours worth of testing before I have to repeat this process.  Likewise for the "web performance and load test" project *.webtests where I have web test plugin that pulls those access tokens from an appsettings.json project I maintain in that environment.  I was trying to switch to msal acquired tokens for specific work or school account [wsa] and microsoft account [msa] test accounts, with relevant application role assignments for tests, these hourly manual steps.  I was keeping test account username & password credentials in an appsettings.User.json file which I have .gitignore configured to not include in checkins so that sensitive data never ends up in source repos. 

wrt 3. interactive popups is not really an option specifically in the web performance and load test project *.loadtest runs of defined *.webtests given these are remotely executed in azure devops cloud load testing service environment on a worldwide set of distributed agents.  Right now I am only doing automated unit, integration and load tests against azure function app, web app and container hosted asp.net core web api deployments.  Handling a coded mvc/spa web UI test leveraging selenium framework and involving openid connect [oidc] signin flows that result in site issued session access_token cookies is not a scenario I've had to tackle just yet.  For that case i'd be inclined to create some test startup code that automates a single oidc signin to acquire session access_token cookie and share use of that access_token cookie with all the coded mvc/spa web UI tests that need it versus having every test try and navigated an oidc signin flow.

wrt 4.  I saw the `PublicClientApplication.AcquireTokenWithDeviceCodeAsync()` but didn't assume it allowed me to acquire bearer or cookie access tokens with test wsa/msa specific properties and claim sets.  Thanks for the heads up on this and reference urls including example for coded mvc/spa web UI test driven by selenium.  Looking at the first reference url it suggests this api still has an interactive step to go to the device code signin page and enter device code that was provide . . . which perhaps the second reference url you shared outlines how to automate.

**Comment by bgavrilMS** [comment]
Got it now, thanks. 

Firstly, I did some investigation and it turns out MSA does not support Device Code Flow, but I believe they plan to fix it (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/728#issuecomment-452787875)

With regards to your scenario, the reason you only get ~1h out of your tokens is because the access token does indeed have 1h expiration. The refresh token (to which you do not have access to directly), has a much more generous 90 day expiration. 

So now the question is - how do you get to the refresh token? You can do it by sharing the token cache between your helper app that does interactive auth, and your test projects. See [here ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token) about acquirinng a token from the token cache (this is silent, no ui) and here about token cache [serialization](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token) - you can just serialize to a plain text file that both apps share.

**Comment by myusrn** [comment]
@bgavrilMS thanks the device code flow seems like localhost releavent strategy for acquiring bearer token w/o having to provide unit & integration tests access to a test user's credentials.  The ability for refresh token to make the Microsoft.com/devicelogon code entry process a once every 90days experience really is significant especially if they are eventually going to also add msa support.

That said in my vs17 15.9.5 [ / vs19 16.0.0 preview 1.1 ] xUnit .net core test project environment I've tested using both AcquireTokenSilentAsync w/ AcquireTokenByUsernamePasswordAsync MsalUiRequiredException fallback and AcquireTokenSilentAsync w/ AcquireTokenWithDeviceCodeAsync MsalUiRequiredException fallback flows.  

In both cases every time I rerun the [Fact] or [Theory] unit/integration test that makes these msal calls to acquire a token for the same work or school account [wsa] test account the AcquireTokenSilentAsync throws the MsalUiRequiredException requiring me to then execute the token acquisition using username/password credentials or device code flow signin.  

This suggests that msal is not caching the refresh token at all, let alone 90 days, for use during followup AcquireTokenSilentAsync calls correct?

**Comment by jmprieur** [comment]
@myusrn 
MSAL only provide an implementation for the token cache serialization on Mobile platforms. For .NET Desktop and .NET Core (which I understand your tests are), you need to provide a custom token cache serialization. This is explained in : https://aka.ms/msal-net-token-cache-serialization

**Comment by myusrn** [comment]
@jmprieur thanks for the response and pointer to article on token cache including code for simple file based one.  

I'm guessing that the [Msal]TokenCacheHelper.cs use of System.Security.Cryptography.ProtectData for creating a local disk secured file to contain refresh tokens is going to be machine specific.  In other words i'm not going to be able to run a set of "Web Performance and Load Test" *.webtest and *.loadtest definitions on my localhost using a WebTestPlugin for msal AcquireTokenSilentAsync w/ AcquireTokenByUsernamePasswordAsync/AcquireTokenWithDeviceCodeAsync MsalUiRequiredException handler fallback to populate a file cache with test account refresh token(s) for specific audienceUris and then include that file in the azure devops deployment and execution of *.webtest and *.loadtest definitions where they will find user token cache file with refresh tokens, good for 90days, to do silent token acquisitions.

**Comment by bgavrilMS** [comment]
For testing, you don't need to call the ProtectData APIs, just read/write to a plain file. Try to get it working on a single machine first. 

If you need the token cache to be available across multiple machines, perhaps you should write it to a file share, or to some other storage mechanism that is cross-machine, such as a database or a redis cache. 

The cache is not machine specific, so as long as you are using the same clientID, it should work.

**Comment by jmprieur** [comment]
@myusrn : are you happy with the answer. do you want to close the issue? (I think this diverged a bit from the original question :) )

**Comment by myusrn** [comment]
@jmprieur yes i'll close issue with this comment.  My take away is that device code flow should eventually include support for test msa token acquisitions  Related to that a redis or unencrypted file other user token cache implementation can be used to enable non-interactive token acquisitions for test msa [ and wsa ] accounts during localhost and cloud load test scenarios.

**Comment by myusrn** [comment]
fyi, just published https://github.com/myusrn/dnccore nuget package which has .net core compatible File [ configurable path and protected or unprotected ] TokenCache and Redis TokeCache implementation.  Intention is for with msft authentication library [msa] PublicClientApplication() and ConfidentialClientApplication() in released app and unit/integration/load test case scenarios that were discussed above.
```
FileTokenCache.GetUserCache(/* cacheFilePath: "d://temp//my.msalcache.bin", cacheFileProtect: false */)
RedisTokenCache.GetAppOrUserCache(uniqueId)
```
