### ISSUE TITLE
App kept switch back to login screen with every tap after successfully login

### ISSUE THREAD

**Issue by cherici-simone** [AzureAD/microsoft-authentication-library-for-dotnet#787]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 2.6.2

**Which platform has the issue?**
xamarin forms (iOS)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;
App Store Connect reject everytime my app with: "Your app kept switch back to login screen with every tap after successfully login".
I follow step by step the examples. I also integrate AppCenter and this is the stack error when Apple test the app:
`Microsoft.Identity.Client.Internal.Requests
InteractiveRequest.VerifyAuthorizationResult ()
Microsoft.Identity.Client.Internal.Requests
InteractiveRequest+<PreTokenRequestAsync>d__9.MoveNext ()
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
Microsoft.Identity.Client.Internal.Requests
RequestBase+<RunAsync>d__33.MoveNext ()
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult ()
Microsoft.Identity.Client
PublicClientApplication+<AcquireTokenForLoginHintCommonAsync>d__17.MoveNext ()
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult ()
Microsoft.Identity.Client
PublicClientApplication+<AcquireTokenAsync>d__9.MoveNext ()
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
TaskAwaiter`1[TResult].GetResult ()`

**Comment by jmprieur** [comment]
@cherici-simone : can you please share repro steps? or code snippets? 
did you follow the instructions in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-ios-specificities ?

**Comment by jennyf19** [comment]
@cherici-simone can you provide the above information?

**Comment by bgavrilMS** [comment]
No more info, closing.
