### ISSUE TITLE
IByRefreshToken api needs to be implemented for ClientCredential Flow to store application tokens

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#796]
**Which Version of MSAL are you using ?**
Latest

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
Refresh token flow Via IByRefreshToken API

**Expected behavior**
The AcquireTokenByRefreshToken method should be able to support application tokens

**Actual behavior**
Only user token are supported

**Comment by bgavrilMS** [comment]
This was implemented
