### ISSUE TITLE
IByRefreshToken API is exposed on mobile platforms which are not supported.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#797]
**Which Version of MSAL are you using ?**
Latest

**Which platform has the issue?**
UWP, xamarin android, xamarin iOS

**What authentication flow has the issue?**
IByRefreshTokenFlow

**Expected behavior**
Should not be accessable on mobile platforms

**Actual behavior**
the api is accessable

**Comment by jmprieur** [comment]
Fixed in 3.0

**Comment by jennyf19** [comment]
Fixed in [MSAL 3.0.0-preview release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.0-preview)
