### ISSUE TITLE
Documentation/Samples need updating for current API

### ISSUE THREAD

**Issue by phatcher** [AzureAD/microsoft-authentication-library-for-dotnet#805]
### Documentation Related To Component:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ x] documentation needs clarification
- [x ] error(s) in example
- [ ] needs example

### Description Of The Issue
Documentation is based on an obsolete version of the API e.g. using HasStateChanged which has been deprecated.

Similarly the example projects have not been update e.g. https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-v2/blob/master/WebApp/Models/MSALSessionCache.cs

**Comment by bgavrilMS** [comment]
Yes, thank you @phatcher - we are updating our samples with the new MSAL 3.x but it will take a bit of time. 

I've moved HasStateChanged from the TokenCache to the args that you get in the BeforeAccess, AfterAccess etc. It's now read-only.

**Comment by jmprieur** [comment]
Closing as all samples were fixed as well as the wiki.

**Comment by phatcher** [comment]
@jmprieur If I go to that repository I can't see a aspnet2-2 branch - is it public?

**Comment by jmprieur** [comment]
Oops … you are right … wrong sample I meant this one: 
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/aspnetcore2-2-signInAndCallGraph

I had missed the one you referenced (and confused it with the other) as, by its name I thought it was just signing-in users. anyway it's fixed as well
