### ISSUE TITLE
Access Token Signature validation fails

### ISSUE THREAD

**Issue by mcetkovsky** [AzureAD/microsoft-authentication-library-for-dotnet#812]
**Which Version of MSAL are you using ?**
2.7.0

**Which platform has the issue?**
.NET 4.6 / Win 10 1809

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

**Repro**

```csharp
var Application = new PublicClientApplication(
                                         ClientId, 
                                         "https://login.microsoftonline.com/organizations/");
var account = await Application.GetAccountsAsync()).FirstOrDefault();
var scopes = new[] { "user.read" };
var result = await Application.AcquireTokenAsync(scopes).ConfigureAwait(false);
var accessToken = result.AccessToken;
```

1. Provide a `ClientId` value, put breakpoint to the last line, run the code and sign in to Azure.
2. Grab the `accessToken` value and put it into the `Encoded` field at https://jwt.io/
3. Write down the `kid` value shown in the `Decode/header` field. Note: The tested tokens used `RS256` algorithm.
4. Open https://login.windows.net/common/discovery/keys, find the `kid` value and grab the appropriate `x5c` string value.
5. Open a new file (call it `cert.cer`) and write in it

```
-----BEGIN CERTIFICATE-----
the grabbed x5c string value
-----END CERTIFICATE-----
```

6. Run `openssl x509 -pubkey -in cert.cer -text -noout` command and grab the public key

    `-----BEGIN PUBLIC KEY … END PUBLIC KEY-----`

7. Paste the public key into the `VERIFY SIGNATURE/Public key` field on the already opened https://jwt.io/
8. Notice that it show `invalid signature` bellow the `Encoded` field.

The token was also tested using PHP openssl extension (via [this](https://github.com/TheNetworg/oauth2-azure), [this](https://github.com/thephpleague/oauth2-client) and [this](https://github.com/firebase/php-jwt) library chain) and it also fails signature verification.

**Expected behavior**
The signature verification succeeds and the signature is considered valid.

**Actual behavior**
The signature verification fails that the signature is considered invalid.

**Comment by jmprieur** [comment]
@mcetkovsky what scope do you request? is it for Graph?
if this is for graph, did you consider the nonce?
adding @brentschmaltz

**Comment by mcetkovsky** [comment]
The token is consumed by the PHP server only to call https://graph.windows.net/me?api-version=1.6 to retrieves user's userPrincipalName. The signature verification is being performed before placing this call.
The client mentioned "user.read" scope and receives a token with `scp` set to `Directory.Read.All User.Read profile openid email`.
Yes, there is a nonce in the header.

**Comment by jmprieur** [comment]
@mcetkovsky if this is a token for AAD Graph, it's only meant to be validated by the AAD Graph (which knows how to validate it). It's not for your PHP Web API (which should not even try to look at it). IF you had issues with a token for your own Web API that would be different.
Note that it's a good token, but it has a nonce, which is used to prevent replay scenarios (where you’d store the token and would replay it to access the graph from a different machine/app, for instance). In that case the JWT is signed differently. If you are interested in more details, you can have a look at the [Identity Model Extension for .NET](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) open source library. The [Validating Tokens](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/ValidatingTokens) wiki page provides a few pointers. @brentschmaltz can elaborate

In any case this is not an MSAL.NET issue. I would therefore recommend you close this issue if you agree (we can still continue the discussion: I also monitor closed issues)

**Comment by jmprieur** [comment]
@mcetkovsky the right way of doing would be:
- have your .NET client request a token **for your PHP Web API**, not for the Graph. You Web API could therefore validate the token, and look at the tid. (You'll get a token for your Web API so you can look into it). You can then apply your logic to check the tenant.
- then your Web API should use the [On Behalf Of](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow) flow to acquire, from the token for your Web API, a token for the graph.

Note that if you change the application manifest of your Web API to set the `accessTokenAcceptedVersion` to 2, you won't even need to call the Graph as the token will contain the `prefered_username` claim, which is the users email address.
Note that the application registration to make that work is a bit complex. We have a sample that explains this (the Web API is in .NET though). See: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

**Comment by mcetkovsky** [comment]
The Web site is in PHP.

**Comment by jmprieur** [comment]
your Web Site has a clientID that you obtained by registering your application in https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredAppsPreview (or through PowerShell). If you change accessTokenAcceptedVersion  to 2, your Web API will now get v2.0 tokens, which will directly contain the prefered_username claim.

**Comment by mcetkovsky** [comment]
I finally see, the `manifest` refers to a Azure AD app registration rather than to a .NET manifest. I'll play with it a bit.

**Comment by jmprieur** [comment]
closing as agreed. but feel free to keep commenting

**Comment by mcetkovsky** [comment]
I am almost done. However, I get an `Your access token has expired. Please renew it before submitting the request.` error when calling `https://graph.windows.net/me?api-version=1.6` with the token I get from the `on_behalf_of` flow.

1. .NET app requests a token for a web-api's `access_as_user` scope and pass the token to the web app.
2. The web app successfully verify the token signature and values.
3. The web app calls `https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token` providing the received token as `assertion` while requesting scope `openid email`.
4. The web app receives its own token with expiration in about an hour.
5. The app tries to call `https://graph.windows.net/me?api-version=1.6` using that token.

The server returns `Your access token has expired. Please renew it before submitting the request.`. 

What did I wrong?

**Comment by jmprieur** [comment]
For the issue with the issuer, this is expected as `sts.windows.net` is an alias of `login.windows.net` and `login.microsoftlonline.com`.

If you look at what is returned in https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize, you'll notice that the json blob has a property named metadata which returns all the clouds supported by Azure AD. For each cloud there is a property named `aliases` which contains all the aliases for a given issuer. For login.microsoftonline.com, you'll find: 
```JSon
      "aliases": [ "login.microsoftonline.com", "login.windows.net", "login.microsoft.com", "sts.windows.net" ]
```

**Comment by mcetkovsky** [comment]
I have failed to find a documentation how to use the discovery/instance url (Google returns no result when searching for that url). 

It seems to require some values of `version` and (`authorization_endpoint` or `issuer`) parameters. It also contains `common` in its url which is usually used for non-tenant specific calls. 

I wonder whether what does the `version` means, whether I should put a specific `tenant` instead of `common` and whether it can provide me a list of issuer aliases for a specific `issuer` (I get in tokens) I provide as a query parameter. Unfortunately, I was unable to get it working. I am getting `Unknown or invalid instance.` when I attempt to provide an `issuer` query parameter.

PS: I am still expiriencing the `token has expired` issue.

**Comment by mcetkovsky** [comment]
Neither I found what does `cloud_graph_host_name` and `msgraph_host` means in the `openid-configuration` endpoint. I searched for `cloud_graph_host_name site:docs.microsoft.com` but did not found any useful hit. I wonder whether I can use these values to build an Graph API url instead of hard-coding `graph.windows.net` in the code.

**Comment by jmprieur** [comment]
@mcetkovsky 
for your token expired issue:
1. you should request a token for a web-api's .default scope (GUID_for_your_web_API/.default)
3. I suggest that you call the Microsoft Graph instead of the Azure AD graph. You probably want to request "user.read". MSAL.NET also requests openid profile offline_access (but this is to manage the cache, I don't think you need them.
4. then you want to call `https://graph.microsoft.com/v1.0/me`. See https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0

You are right the cloud_graph_host_name is the host for **Microsoft** Graph (which is https://graph.microsof.com in the Microsoft Azure public cloud, and might be different in national and sovereign clouds)

> Note that the Microsoft Graph (graph.microsof.com) is different from the Azure AD graph (graph.windows.net). It's recommended that you use Microsoft Graph.

**Comment by mcetkovsky** [comment]
Its quite challenging to translate `token expired` into its actual meaning `you have not requested a token for this scope`.

It works now. I just still wonder how does the https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize works as I mentioned in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/812#issuecomment-456811528.

**Comment by jmprieur** [comment]
I agree with you @mcetkovsky 
I'll raise a bug against Azure AD for the error message.

how did you make it work? did you only request User.Read?

**Comment by mcetkovsky** [comment]
Yes, I request `https://graph.microsoft.com/User.Read`. However, I failed to get a list of scopes in docs but I managed to get the list from the `Add a permission` action in the Azure portal.

If you can guide me through the discovery/instance endpoint or point me to the right doc page, so I understand how to use it properly, I would make the issuer check in the code aware of aliases.

**Comment by jmprieur** [comment]
I'm confused, @mcetkovsky : isn't https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/812#issuecomment-456791675 enough guidance?

**Comment by mcetkovsky** [comment]
It was somewhat enough. However, I was trying to find an official docs or specification of this endpoint so I can study details. I failed to find any. The only thing I found are official libraries like [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/Microsoft.Identity.Client/Instance/AadInstanceDiscovery.cs).

While playing with that endpoint I discovered that it `Expected exactly one of 'issuer' and 'authorization_endpoint'` (the endpoint shows this error if I remove the `authorization_endpoint` parameter). This message suggest there is an `issuer` parameter supported so I was wondering what does it do and whether it might fit me.

**Comment by jmprieur** [comment]
I have not found any doc either, @mcetkovsky 
I'll ask our protocol team about documenting this. Also, I'll try to figure out how to use issuer.

**Comment by mcetkovsky** [comment]
Thanks @jmprieur, you helped a lot.

**Comment by coolthejackal** [comment]
> @mcetkovsky is there a 'nonce' in the JwtHeader?

when I saw your comment I realized that I was confusing the accessToken with the idToken.
