### ISSUE TITLE
Allow for building the project using OSX / VS Code

### ISSUE THREAD

**Issue by devigned** [AzureAD/microsoft-authentication-library-for-dotnet#818]
**Is your feature request related to a problem? Please describe.**
When attempting to contribute to the project using OSX it is very difficult to configure / build the project.

**Describe the solution you'd like**
It would be great if the project could build under OSX using cmd line or VS Code. Preferably, just be able to run `dotnet restore` and `dotnet build`. Clearly, this would not include full framework stuff.

**Describe alternatives you've considered**
The only alternative I can see is to run on Windows using VS (per the contributor guidelines).

**Comment by bgavrilMS** [comment]
Hi David, 

Thank you for considering contributing! I updated our wiki based on your feedback  https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Build-and-Test

MSAL is a multi-target library so you need to use `msbuild` command line, which is able to build Xamarin and UWP. `dotnet` only targets .Net Core. 

VS for Mac unfortunately does not understand multi-target frameworks well and it is a pain to use it on MSAL. VS Code will try to use the `dotnet` command so you are seeing errors. 

On OSX, my guidance would be to use VS Code purely as an editor and build from the command line. Alternatively, rewrite your tasks.json and launch.json to use msbuild (if you manage to do it, please share it with us and we will add it to the wiki)

**Comment by bgavrilMS** [comment]
Will close , please don't hesitate to come back to this this issue.
