### ISSUE TITLE
MSAL.Net Cache is backward and forward compatible

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#82]
**Why?**
To enable an easy migration of applications using ADAL.Net to MSAL.Net, we'd want the cache to be backward and forward compatible in both libraries.

**What?**
MSAL.Net should be able to: 
- read ADAL.NET v3.0 cache blobs and migrate refresh tokens to MSAL cache format.
- write both ADAL.NET v3.0 blob format and MSAL.NET Json format.
- Add a test where HasStateChanged is false due to the token not in the cache, thus not deleted, thus no state changed (See #252)
- RequestParams should not be passed in the token cache. request classes must pass exact information to the methods (#317)

**Comment by jmprieur** [comment]
Done.
See https://aka.ms/msal-net-2-released
