### ISSUE TITLE
Ensure we send client headers to the user realm end-point

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-dotnet#820]
**Is your feature request related to a problem? Please describe.**
AAD is not able to tell which library is calling the user realm end-point. We should ensure AAD has this information available allowing them to inform us should our calls not succeed.

**Describe the solution you'd like**
Add client sku, etc. headers to all the calls we make to the AAD user realm end-point.

**Additional context**
See conversation related to DektopSSO

**Comment by jennyf19** [comment]
Fixed in [MSAL 3.0.0-preview release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.0-preview)
