### ISSUE TITLE
`Build and test` wiki page needs to be updated

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#823]
**Which Version of MSAL are you using ?**
MSAL 2.5.7

Other? - please describe;
The wiki page helping contributors building and testing MSAL.NET still references the ADAL.NET page. This is no longer correct as we have moved MSAL back to its own repo in December 2018.

**Repro**
Go to [Build & test MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/build-and-test)

**Expected behavior**
I see instructions on how to build and test MSAL.NET

**Actual behavior**
the wiki page still points to [Building ADAL and MSAL](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Pre-requisites-to-build-ADAL.NET-and-MSAL.NET). The build steps for ADAL and MSAL are very similar however the solution files and folders mentioned are not named as what is mentioned in the wiki page.

**Comment by bgavrilMS** [comment]
Done.
