### ISSUE TITLE
Multiple entries in ADAL cache when migrating to MSAL

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#842]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 2.7 and ADAL 4.5

**Platform**
all 

**Repro**

1. Create an app upgrade scenario. Scopes set to  "https://graph.windows.net/.default" and Resource set to "https://graph.windows.net"
2. Get a token with ADAL interactively
3. Get a token with MSAL silently (ok)
4. Have a look in the ADAL cache via the public TokenCache.ReadItem()

**Expected behavior**
A single entry.

**Actual behavior**
Two entries: 
- one has Resource = "https://graph.windows.net" and looks valid
- second one has AT set to null, same user and "https://graph.windows.net/User.Read https://graph.windows.net/.default" 

Note sure about the application impact, I am not getting any exceptions. Easiest to repro is using the dev UWP sample.

**Comment by jmprieur** [comment]
This is a theorical problem.
Let's close it.
