### ISSUE TITLE
Migrate from 1.1.0-preview to 2.7.0

### ISSUE THREAD

**Issue by ajtruckle** [AzureAD/microsoft-authentication-library-for-dotnet#843]
Are there any code breaking changes if I update my Nuget Packer from 1.1.0-preview to 2.7.0?

Thank you.

**Comment by MarkZuber** [comment]
There has been quite a bit of change between 1.1.0-preview and 2.7.0.  We have migration aids in the code and samples to help with the v1-v2 migration.  You can also see specifics about the API differential here:

https://www.fuget.org/packages/Microsoft.Identity.Client/2.7.0/lib/netstandard1.3/diff/1.1.0-preview/

**Comment by jennyf19** [comment]
@ajtruckle See this [blog post](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released#changes-in-msalnet-between-1x-and-2x) with details on how/what to change from v1 to v2.

**Comment by ajtruckle** [comment]
Thanks for the link. It is a bit concerning that I read:

"The supported platforms were modernized<https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released#modernization-of-the-platforms-supported-by-msalnet>, dropping support for Windows and Windows Phone 8/8.1, and supporting .NET core explicitly"

My application supports Windows 8.1 with the latest service pack. Is this telling me I will drop support for Windows 8.1 if I upgrade?

________________________________

**Comment by MarkZuber** [comment]
No.  That's dropping support for Windows Phone 8 and Windows Phone 8.1.   Windows desktop is supported for Win7 and up.

**Comment by ajtruckle** [comment]
@MarkZuber OK, but it does state:

> As in ADAL.NET, the platforms supported in MSAL.NET were modernized:
> 
> Support for **Windows 8/8.1** and Windows Phone 8/8.1 was removed

**Comment by MarkZuber** [comment]
Oh, I see the confusion.  That's Windows 8/8.1 UWP.  We only support UWP apps on Win10 and above.  But we support desktop (.net framework 4.5) on win7 and above.

**Comment by ajtruckle** [comment]
Ah. Ok. Phew. Looks like I will have to try it out then. My application is fairly simple and allows user to connect to calendar to delete and create calendar events.

If I get compile errors I assume I can come here. 👍

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jennyf19** [comment]
@ajtruckle yes...let us know if you run into any issues. Feel free to open another issue, or ping us here.

**Comment by MarkZuber** [comment]
I'm going to close out this issue for now.  Please re-open this or open a new issue if you have future concerns/questions.
