### ISSUE TITLE
//tokencache.hasstatechanged

### ISSUE THREAD

**Issue by ajtruckle** [AzureAD/microsoft-authentication-library-for-dotnet#845]
Using 2.7.0 I have this warning:

> 'TokenCache.HasStateChanged' is obsolete: 'Please use the equivalent flag TokenCacheNotificationArgs.HasStateChanged, which indicates if the operation triggering the notification is modifying the cache or not. Setting the flag is not required.'

My current code:

`if (args.TokenCache.HasStateChanged)`

Is there a new `TokenCacheHelper `class?

**Comment by jmprieur** [comment]
Just use `args.HasStateChanged`

From which sample did you copy your TokenCacheHelper class.
@bgavrilMS : we need to update all the samples ...

**Comment by ajtruckle** [comment]
Alas, it was in 2017 so I don't remember. Here is the file. It is flagging several warnings:

https://www.dropbox.com/s/a0tx85ozob0uzwb/TokenCacheHelper.cs?dl=0

**Comment by ajtruckle** [comment]
I made the change but there is a second issue here:

```
       public static void AfterAccessNotification(TokenCacheNotificationArgs args)
        {
            // if the access operation resulted in a cache update
            if (args.HasStateChanged)
            {
                lock (FileLock)
                {
                    // reflect changesgs in the persistent store
                    File.WriteAllBytes(CacheFilePath, args.TokenCache.Serialize());
                    // once the write operationtakes place restore the HasStateChanged bit to filse
                    args.TokenCache.HasStateChanged = false;
                }
            }
        }
```

This bit fails `args.TokenCache.HasStateChanged = false;`.

**Comment by jmprieur** [comment]
you can safely remove this bit. it's not used by MSAL

**Comment by bgavrilMS** [comment]
Please delete that line `args.TokenCache.HasStateChanged = false;` - you no longer need to set this flag.
