### ISSUE TITLE
2.7.0 Explicit binding warning

### ISSUE THREAD

**Issue by ajtruckle** [AzureAD/microsoft-authentication-library-for-dotnet#847]
With 2.7.0 I now get a explicit binding warning:

The explicit binding redirect on "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" conflicts with an autogenerated binding redirect. Consider removing it from the application configuration file or disabling autogenerated binding redirects. The build will replace it with: "<bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" xmlns="urn:schemas-microsoft-com:asm.v1" />".	

Not sure if this issue is directly related to your library.

**Comment by bgavrilMS** [comment]
You could try to take a dependency on System.Net.Http directly from your app, that ussually takes care of diamond dependencies.

**Comment by ajtruckle** [comment]
How do I do this?

________________________________

**Comment by bgavrilMS** [comment]
Using Visual Studio, open NuGet package manager. Search for System.Net.Http. Install it to your project. See if it builds.

**Comment by ajtruckle** [comment]
It is already installed. v 4.3.4.

________________________________

**Comment by jmprieur** [comment]
@ajtruckle : you probably have other dependencies. I suggest you look at the output (in the combo-box named NuGet) which will tell you more about what to do
