### ISSUE TITLE
Xamarin dependencies are out of date

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#849]
1. Create a new XForms app with the latest official Visual Studio 
2. Take a reference on MSAL from the iOS and Android heads
3. Build

Actual: build errors because of diamond dependencies - MSAL uses xamarin dependnecies version 27.0.2 but the new app uses version 27.0.2.1; 

Expected: it should build with 0 warnings and errors

Note: this has already been fixed by a a user in ADAL 

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/commit/4c7daa420acc581b741c474b7d3db652046d0fd7

**Comment by jmprieur** [comment]
@henrik-me that's some low hanging fruit, which will avoid a supportability storm. I'd take it ASAP.

**Comment by MarkZuber** [comment]
This PR is waiting on our decision about Net461 since it also updates our desktop version.  I'd also like to get final answers on whether we can move to netcoreapp2.0 and whether we want to update netstandard version for v3.x so we can do this in one fell swoop.

**Comment by jmprieur** [comment]
I've requested more info from the .NET team …

**Comment by bgavrilMS** [comment]
Oren has advised several times that we can easily move to NetCore 2 since most of our users are there and NetCore <2 is deprecated. Are technical reasons to do move, e.g. new APIs that we need to use etc.

I strongly advise against moving to NetStandard 3 because of XForms. Today, if you create an XForms project it will generate a shared project that targets NetStandard 2.0; This means that developers will not be able to take a dependency on MSAL. .Net Core 3 SDK is still in preview and production apps will not take it. Note that we can support both NetStandard1 and NetStandard3 if needed.

I would actually advise against moving to NetStandard 2.0 as well unless we have a reason to do it. A lot of XForms app out there have shared projects that still target older versions of NetStandard, most notably 1.6; We can of course tell our users to upgrade, but it will impact supportability.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by MarkZuber** [comment]
NetCore2 would let us all have the same versions of many of the packages (see our nuget update/consolidate area in libsandsamples.sln).  NetStandard should be able to stay on 1.3 or maybe we move it to 1.4 which aligns directly with net 461.  We should definitely not move to netcore 3 or netstandard 3 since that hasn't even shipped yet and adoption is low.

**Comment by jmprieur** [comment]
@jennyf19 is it fixed?

**Comment by jennyf19** [comment]
@jmprieur the PR was merged with the changes.

**Comment by jennyf19** [comment]
Fixed in [MSAL 3.0.0-preview release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.0-preview)
