### ISSUE TITLE
MSAL Upgrade: AcquireTokenForClientAsync  System.Security.Cryptography.CryptographicException : Key not valid for use in specified state

### ISSUE THREAD

**Issue by baywet** [AzureAD/microsoft-authentication-library-for-dotnet#857]
**Which Version of MSAL are you using ?**
2.7.0

**Platform**
Azure App Service, (webjob), dot net classic 4.7.

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO
    * [x] Application only with certificate

**Is this a new or existing app?**
c. This is a new app or experiment
I originally started with MSAL and had to downgrade to ADAL to workaround the issue.

**Repro**

```csharp
var cac = new ClientAssertionCertificate(certProvider.AppCertificate); //your x509 certificate loaded in via the current user/my store, loaded in the azure web app SSL settings
var clientCredentials = new ClientCredential(cac);
var app = new ConfidentialClientApplication(clientId, $"https://login.microsoftonline.com/{tenantName}.onmicrosoft.com", "https://daemon", clientCredentials, new TokenCache(), new TokenCache());
var result = await app.AcquireTokenForClientAsync(new List<string> { $"{applicationUrl}/.default" });
```

**Expected behavior**
The code to execute properly, especially since it works when debugging locally.

**Actual behavior**
Getting the following exception
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.ProcessQueueMessage ---> System.Security.Cryptography.CryptographicException : Key not valid for use in specified state. at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) at System.Security.Cryptography.Utils._ExportKey(SafeKeyHandle hKey,Int32 blobType,Object cspObject) at System.Security.Cryptography.RSACryptoServiceProvider.ExportParameters(Boolean includePrivateParameters) at System.Security.Cryptography.RSA.ToXmlString(Boolean includePrivateParameters) at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.GetCryptoProviderForSha256(X509Certificate2 certificate) at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message,X509Certificate2 certificate) at Microsoft.Identity.Client.ClientAssertionCertificate.Sign(String message) at Microsoft.Identity.Client.Internal.Jwt.JsonWebToken.Sign(ClientAssertionCertificate credential,Boolean sendCertificate) at Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters.ToParameters() at async Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters,CancellationToken cancellationToken) at async Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken) at async Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken) at async Microsoft.Identity.Client.ConfidentialClientApplication.AcquireTokenForClientCommonAsync(IEnumerable`1 scopes,Boolean forceRefresh,ApiIds apiId,Boolean sendCertificate) at async Microsoft.Identity.Client.ConfidentialClientApplication.AcquireTokenForClientAsync(??) at async SiteCreationSharePoint.ProvisioningService.GetClientContext(String sharePointUrl,String applicationUrl)
```

**Additional context/ Logs / Screenshots**
The equivalent code with ADAL works
```csharp
 var authority = $"https://login.windows.net/{tenantId}/";
 var authContext = new AuthenticationContext(authority);
 var host = new Uri(sharePointUrl);
 var resourceId = host.Scheme + "://" + host.Host + "/";
 var clientAssertionCertificate = new ClientAssertionCertificate(clientId, certProvider.AppCertificate);
 var result = await authContext.AcquireTokenAsync(resourceId, clientAssertionCertificate);
```

**Comment by jmprieur** [comment]
Where does your certificate come from, @baywet  ? how do you get it?
I've noticed that for instance when loading a certificate from a file, one needs to use 

```CSharp
var certificate = new X509Certificate2(@"path\cert.pfx", 
                                                             "password", 
                                                              X509KeyStorageFlags.EphemeralKeySet);
```

note the **X509KeyStorageFlags.EphemeralKeySet**

**Comment by baywet** [comment]
Salut Jean-Marc!
In both cases the code to get the certificate is the same and loads it from the store:
(isolated in a different class, but I'll put the code here for reference)
```CSharp
var storeName = StoreName.My;
                    var storeLocation = StoreLocation.CurrentUser;

                    var certStore = new X509Store(storeName, storeLocation);
                    certStore.Open(OpenFlags.ReadOnly);

                    var certCollection = certStore.Certificates.Find(
                        X509FindType.FindByThumbprint,
                        _certThumbPrint,
                        false);

                    // Get the first cert with the thumbprint
                    if (certCollection.Count > 0)
                    {
                        _appCertificate = certCollection[0];
                    }
                    certStore.Close();

                return _appCertificate;
```

**Comment by jmprieur** [comment]
@brentschmaltz @GeoK @mafurman : do you have an idea of what could happen?
cc: @henrik-me @bgavrilMS @MarkZuber @jennyf19 @trwalke

**Comment by henrik-me** [comment]
Will try to reproduce. 
@baywet Assuming that the .net version targeted for the two scenarios is the same and also expecting the cert being the same.
This should work the same on both ADAL and MSAL.

**Comment by baywet** [comment]
@henrik-me : yes the only changes between the working and non-working scenario are ADAL => MSAL and the changes in code I mentionned.
I do have the project on my end, if you can't repro, let me know if you need me to clean it up and put it somewhere.

**Comment by henrik-me** [comment]
@baywet : I've tried what you mentioned. Using ADAL 4.5 and MSAL 2.7 in the same console app getting tokens for an app I have hosted on my local box and calling that local service with the AT returned. I run ADAL and MSAL side by side and make the same calls. Both works. From what I can see I'm doing exactly what you are doing. I have tried running the app both with .NET 4.5 and .NET 4.7. If you have a repro solution, that seems to be the next step for me to try out.

**Comment by baywet** [comment]
Hey @henrik-me 
Here is the repro:
- Create a self signed certificate (I added the script I'm using to the archive)
- upload the private certificate to the web app using the SSL settings section
- Create an azure web app (windows)
- Register an application on AAD with permissions granted to SharePoint online, add the certificate as an authentication method
- Set the following app settings to the web app (you have examples in the app config): tenantName, tenantId, clientId, certificateThumbPrint, siteCollectionPath
- Set the additional app settings to the web app: AzureWebJobsDashboard, AzureWebJobsStorage connection strings. WEBSITE_LOAD_CERTIFICATES to *

Local debug always work in both scenarios.
Online execution works with adal, fails with msal. You can test taht by right click on the project in VS, publish as webjob and target your azure web app. And then going to https://webappname.scm.azurewebsites.net/azurejobs/#/jobs/continuous/SiteCreationSharePoint
You can toggle the output which should give you the s
[SiteCreationSharePoint.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/2842460/SiteCreationSharePoint.zip)
ite name in the logs.
Now if you want to test msal, just replace the nuget, comment out L33-38 and uncomment L41-44. (note you'll have references to resolve). Publish again and refresh the output of the webjob, you'll see the exception coming up.

Let me know if you need more information
[SiteCreationSharePoint.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/2842461/SiteCreationSharePoint.zip)

**Comment by henrik-me** [comment]
@baywet We are now on v4. Do you still see this issue? If it is would be great if you can help with a simplified repro.

Please re-open of you still see this issue and would like us to investigate further. Please when re-opening assist with a simplified repro.

**Comment by baywet** [comment]
@henrik-me thanks for the follow up. Upgraded to 4.1.0 and it seems to be working properly so far.
