### ISSUE TITLE
IIssuerSecurityTokenProvider not available in newer versions of Microsoft.Owin.Security

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-dotnet#871]
### Please check those that apply

- [ ] typo
- [x ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ x] needs example

### Description Of The Issue
Hello,  There is no example of using OAuthBearerAuthenticationOptions with Microsoft.Owin.Security.* 4.0.

The sample uses 3.0
https://github.com/AzureADQuickStarts/AppModelv2-NativeClient-DotNet/tree/complete/TodoListService

it seems that **IIssuerSecurityTokenProvider** is no longer a part of new versions of 
Microsoft.Owin.Security.Jwt;
https://github.com/AzureADQuickStarts/AppModelv2-NativeClient-DotNet/blob/complete/TodoListService/App_Start/OpenIdConnectSecurityTokenProvider.cs

**Comment by jmprieur** [comment]
@jrmcdona in Web APIs, you should use JwtBearerToken, not OAuth.
Proposing to close this one as 
1) we had the conversation in the sample itself
2) this is an ASP.NET / Microsoft Identity Extension for .NET issue, not an MSAL.NET issue
