### ISSUE TITLE
Microsoft.Identity.Client.srclink missing

### ISSUE THREAD

**Issue by pdeliot** [AzureAD/microsoft-authentication-library-for-dotnet#875]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 2.7.0

**Platform**
UWP

Error when generating native binary while creating store package. 

 Generating fixups for native code
4>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.1\tools\Microsoft.NetNative.targets(792,5): error : RHBIND : error RHB0007: Could not load input file 'Microsoft.Identity.Client.srclink'.
4>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.1\tools\Microsoft.NetNative.targets(792,5): error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x86.microsoft.net.native.compiler\2.2.1\tools\x86\ilc\Tools\rhbind.exe @"C:\Temp\KNX Dashboard 4\KNXDashboard(UWP)\obj\x86\Release\ilc\intermediate\rhbindargs.KNX Dashboard.rsp"' returned exit code 7
===
This was not occuring with oldest versions (sorry I do not have the build).

**Comment by jmprieur** [comment]
@pdeliot 
do you please have repro steps that we could follow?

**Comment by pdeliot** [comment]
Working on the repro.
I’m fighting to simplify the project and keep the beahvior.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Jean-Marc Prieur<mailto:notifications@github.com>
Envoyé le :lundi 18 février 2019 16:55
À : AzureAD/microsoft-authentication-library-for-dotnet<mailto:microsoft-authentication-library-for-dotnet@noreply.github.com>
Cc : Pascal Deliot<mailto:pascal@deliot.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [AzureAD/microsoft-authentication-library-for-dotnet] Microsoft.Identity.Client.srclink missing (#875)


@pdeliot<https://github.com/pdeliot>
do you please have repro steps that we could follow?

**Comment by pdeliot** [comment]
I've rebuilt a full development environnement and the issue is not more occurring.
Closing the issue.
