### ISSUE TITLE
Enable ROPC in mobile platforms

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#882]
**Is your feature request related to a problem? Please describe.**
Even if we strongly discourage it, some B2C customers want to be able to provide their own UI to get username and passwords. This is currently disabled in mobile platforms (Xamarin, UWP)

**Describe the solution you'd like**
Enable ROPC in Xamarin.iOS, Xamarin.Android and UWP

**Comment by jmprieur** [comment]
@henrik-me as discussed, per Yordan's guidance.

**Comment by bgavrilMS** [comment]
Not needed for 3.0.4 - we need to focus on features and fixes that affect the public API only so that we can remove the -preview tag.

Unless this is done @jennyf19 ?

**Comment by jennyf19** [comment]
@bgavrilMS this is already done. this this [pr](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/935)

**Comment by bgavrilMS** [comment]
Yes, I remember this as well.

**Comment by jmprieur** [comment]
moving back to 3.0.3 then, since it's in?

**Comment by jennyf19** [comment]
@jmprieur yes...thought we did that Thursday. thank you.

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
