### ISSUE TITLE
[PMA] The sign in dialog does not scale properly

### ISSUE THREAD

**Issue by atiqhaqu** [AzureAD/microsoft-authentication-library-for-dotnet#907]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

We are currently using ADAL, but the issue likely is in newest ADAL as well.

**Platform**

net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
b

**Repro**
We are filing this bug, as it is related to the sign in dialog in VS. Once we move to MSAL, we will be using the MSAL UI. So we will need this bug fixed at that point. So the repro steps are not accurate at this point. Its not a bug that need to be fixed immediately, but needs to be fixed when VS moves to MSAL.

0. Have PMA turned on in VS w/ 100% primary, 200% secondary
1. Launch VS
2. Open Team Explorer/Manage Connections
3. Connect to vstfdevdiv:8080
 
**Expected behavior**
 The sign in page is the correct size

**Actual behavior**
 It's too small

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

![image](https://user-images.githubusercontent.com/20782650/53278877-f3001380-36c0-11e9-91af-93d588235f22.png)

This bug is part of the effort to make all VS UI work properly with PMA. We would like this fixed by 16.1, which will coincide with the time when VS plans to move to MSAL.

**Comment by bgavrilMS** [comment]
What is PMA?

**Comment by jmprieur** [comment]
@bgavrilMS : PMA = Per Monitor Awareness

**Comment by jmprieur** [comment]
@jmprieur for investigation

**Comment by jmprieur** [comment]
This is a key pillar for VS 16.

**Comment by rub8n** [comment]
This blog post will give you an quick overview as well as how to enable PMA in the IDE: 
https://devblogs.microsoft.com/visualstudio/a-better-multi-monitor-experience-with-visual-studio-2019/

**Comment by jmprieur** [comment]
thanks @rub8n !

**Comment by jmprieur** [comment]
See https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode?view=netcore-3.0#System_Windows_Forms_Application_SetHighDpiMode_System_Windows_Forms_HighDpiMode_

I propose to do this at the same time we support .NET Core 3.0
cc: @henrik-me @MarkZuber

**Comment by jmprieur** [comment]
@henrik-me to decide if we take for 4.9

**Comment by jmprieur** [comment]
Will do after supporting .NET Core 3.0 in embedded web view

**Comment by bgavrilMS** [comment]
Is this even doable on net45?

**Comment by jennyf19** [comment]
@henrik-me  update on this? ;)

**Comment by bgavrilMS** [comment]
Please use WAM.
