### ISSUE TITLE
The MSAL.NET nuget package should reference the Microsoft identity platform for developers

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#909]
**Which Version of MSAL are you using ?**
3.0.0-preview

**Platform**
Any

**Repro**
Go to https://www.nuget.org/packages/Microsoft.Identity.Client/

*Expected behavior**
The description mentions Microsoft identity platform for developers

**Actual behavior**
It mentions Azure AD v2.0

**Comment by jennyf19** [comment]
Fixed in [MSAL 3.0.0-preview release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.0-preview)
