### ISSUE TITLE
UserTokenCache.Clear does not log out the user

### ISSUE THREAD

**Issue by HectorMeneses333** [AzureAD/microsoft-authentication-library-for-dotnet#92]
Hi,

I'm using the following to logout a user
            App.PCApplication.UserTokenCache.Clear(App.PCApplication.ClientId);

However, when I restart the login sequence by calling:
    ar = await App.PCApplication.AcquireTokenAsync(...)

MSAL does not show the sign in page... instead it returns right away and let the user continue to the next page... 

Is there something else I need to do to sign out the user??

thanks! 
Hector

**Comment by kpanwar** [comment]
SignOut simply clears out the user state in the cache. Library does not clear out browser cookies.
