### ISSUE TITLE
Update Nuget metadata, e.g. Nuget licenseUrl element deprecated, update packaging to specify the license in the package

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#921]
**Which Version of MSAL are you using ?**
MSAL 3.0.0-preview

**Repro**
When publishing nuget package for release, we get a warning from nuget.org:

We found the following issue(s):
<licenseUrl> element will be deprecated, please consider switching to specifying the license in the package. https://aka.ms/deprecateLicenseUrl

We recommend that you fix these issues and upload a new package. 

**Expected behavior**
No warning when uploading the nuget package

**Comment by jmprieur** [comment]
OK for me

**Comment by jennyf19** [comment]
Included in [MSAL.NET 3.0.6-preview release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.6-preview)
