### ISSUE TITLE
Claims should affect the token acquisition operations, not the apps?

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#930]
**Which Version of MSAL are you using ?**
MSAL.NET 3.0.0

**Platform**
all

**What authentication flow has the issue?**
all

**Repro**
Look at AbstractApplicationBuilder. 
**Expected behavior**
.WithClaims shoud only apply to methods, not the full app?
what is the scenario.

**Actual behavior**
there is a .WithClaim member (as well as in ApplicaitonOptions and in IAppConfig)

**Comment by jmprieur** [comment]
@henrik-me @MarkZuber @bgavrilMS @jennyf19 @trwalke @shoatman 
I cannot figure out a scenario where claims would be applied at the app level?

**Comment by jennyf19** [comment]
@jmprieur I think you are right. having it at the AT builder level makes sense. Why would it be on the app level? Usually, you'll get the claims back and need to include them in the next AT call, so makes sense to have it there.

**Comment by jmprieur** [comment]
@henrik-me who is on point to fix it in 3.1?
cc: @jennyf19

**Comment by henrik-me** [comment]
This seems like a std. effort to cleanup the v3 API. Will discuss who when we are ready to pick this up. Anyone can fix it afaik.

**Comment by jennyf19** [comment]
@henrik-me @jmprieur on it.
