### ISSUE TITLE
Sign up flow missing information for Edit Profile

### ISSUE THREAD

**Issue by DaveBrickley** [AzureAD/microsoft-authentication-library-for-dotnet#940]
**Which Version of MSAL are you using ?**

2.7.1

**Platform**
xamarin android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Username Password

**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

authenticationResult = await ADB2CClient.AcquireTokenAsync(Scopes, firstAccount, UIBehavior.SelectAccount, string.Empty, null, AuthorityEditProfile, App.UiParent);

**Actual behavior**

Functionality works in that I can bind above to a button, however the page that is returned is hard for users to follow

1. It contains two fields which are for username and password, but without labels so you wouldn't know
2. Further confused by an error message displayed within the email text box

**Possible Solution**

1. Label the text fields correct as Username / Email, and Password
2. Display the email address from the profile, not the error message
![screenshot 2019-03-04 at 19 55 55](https://user-images.githubusercontent.com/45126043/53759223-b5b53600-3eb7-11e9-9512-e836b727f8e5.png)

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by jmprieur** [comment]
@DaveBrickley : isn't this enough: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#special-case-of-editprofile-and-resetpassword-policies ?

**Comment by DaveBrickley** [comment]
@jmprieur Thanks for the speedy response, however the link you've given me is to an MSAL 3.0 example?

If I go to the MSAL 2.x page link, it shows a similar example but using AcquireTokenAsync, and then refers to GetUserByPolicy which is not appearing for me when I attempt to clone the example in context of my code, for example

```
public static PublicClientApplication ADB2CClient { get; private set; }
accounts = await ADB2CClient.GetAccountsAsync();
firstAccount = accounts.FirstOrDefault();
IAccount me = await ADB2CClient.GetAccountAsync(firstAccount.HomeAccountId.Identifier)

var authResult = await ADB2CClient.AcquireTokenAsync(scopes:Scopes, account:GetUserByPolicy
```

The only options after 'account' are GetAccessToken, GetDisplayName and a couple of others

**Comment by jmprieur** [comment]
Hello @DaveBrickley 
Did you see this sample: https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/blob/master/active-directory-b2c-wpf/MainWindow.xaml.cs ?

**Comment by DaveBrickley** [comment]
@jmprieur 
The only difference I can see in how you're initialising PublicClientApplication from the way I have is that you've got a separate class, TokenCacheHelper, which you include a reference to

But having looked through the source of that, I'm none the wiser how that provides access to GetUserByPolicy I'm afraid

Just to make absolutely clear, is GetUserByPolicy a component of MSAL, or some other library?

**Comment by DaveBrickley** [comment]
@jmprieur 

Please see attached screen shot to further illustrate
![screenshot 2019-03-05 at 21 02 57](https://user-images.githubusercontent.com/45126043/53837457-84f20100-3f8a-11e9-893c-116e110966e1.png)

**Comment by DaveBrickley** [comment]
@jmprieur 

FIXED

I'm really sorry, I read your samples and I finally figured it out from that, yes this totally sorts my problem, sorry for all the questions

**Comment by jmprieur** [comment]
no worries, @DaveBrickley 
thanks for the update.

Do you think that we could be clearer? would you advise we change something?

**Comment by DaveBrickley** [comment]
@jmprieur 

Depends, for a more experienced developer might be fine, for a relative newbie it was really confusing

Going right back to when I started using MSAL, I was firing off various tickets because I couldn't access the B2C profile information from the token

This seemed really strange, because you'd have thought it was a primary use case

I ended up using MSAL in app and ADAL in API to work around this, passing the Object ID from the token to achieve what I needed

However, now looking through the additional link you've sent me to, I'm wondering if that whole issue could have been avoided had I noticed the authority change to use the b2c domain?

In terms of my latest problem, it might be nicer for people in this position in future if the ability to specifiy the B2C element as part of the main library, rather than having to write a method to do it?
