### ISSUE TITLE
Improve documentation for Xamarin Android ownerWindow and improve exception with null ownerWindow

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#942]
### Documentation Related To Component:
In Msal v3, developers must pass in an Activity for the ownerWindow on Android. 
For example:
```CSharp
result = await App.MsalPublicClient.AcquireTokenInteractive(App.Scopes, App.AndroidActivity).ExecuteAsync();
```
However, if null is passed in to the ownerWindow, the following error is thrown: 
`Unhandled Exception:
System.PlatformNotSupportedException: Possible Cause: If you are using an XForms app, or generally a netstandard assembly, make sure you add a reference to Microsoft.Identity.Client.dll from each platform assembly (e.g. UWP, Android, iOS), not just from the common netstandard assembly`

The error should be something like:
`On the Android platform the ownerWindow cannot be null. An Activity must be passed to the ownerWindow in the AcquireTokenInteractive Call. Please see https://aka.ms -something cool for more details and a code sample`

### Please check those that apply

- [ ] typo
- [X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [X] needs example

See related [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/941)

**Comment by jmprieur** [comment]
@jennyf19 the fact that the exception is not explicit seems a bug as well?
cc: @henrik-me  ?

**Comment by bgavrilMS** [comment]
I think this is a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/918 but I agree that the exception also needs to be fixed.

**Comment by jennyf19** [comment]
confirmed that when passing in a null ownerWindow on Android, we throw a correct exception w/a clear error message: InvalidOperationException: Activity is required for parent object on Android.

Closing, as I think @bgavrilMS  is right and the second part of this issue is a duplicate.
