### ISSUE TITLE
Reintroduce .WithExtraQueryParameters(string)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#946]
**Is your feature request related to a problem? Please describe.**
Some partners have provided libraries wrapping ADAL / MSAL, and they are provided a string for the extra query parameters. We now require a dictionary.

**Describe the solution you'd like**
.WithExtraQueryParameters(string)

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/950
