### ISSUE TITLE
AbstractApplicationBuilder gives users no way to provide an existing TokenCache

### ISSUE THREAD

**Issue by cormacpayne** [AzureAD/microsoft-authentication-library-for-dotnet#949]
**Is your feature request related to a problem? Please describe.**

When instantiating a `PublicClientApplication` without the new fluent API in MSAL 3.0.0-preview, you were able to provide an existing `TokenCache` object as an argument of the constructor. However, the new `PublicClientApplicationBuilder` provides no mechanism to use that same `TokenCache` for the created `PublicClientApplication`.

The `TokenCache` we were previously using is nested inside a wrapper object which defines the location of the cache on the user's machine, but with the builder, we need to define the file path again and re-implement the `SetAfterAccess` and `SetBeforeAccess` methods to correctly read from/write to this cache. It would be great if there was a method in the `AbstractApplicationBuilder` class called `WithTokenCache` that allowed us to provide an existing cache to use for the constructed `PublicClientApplication`.

**Describe the solution you'd like**

```cs
var publicClient = PublicClientApplicationBuilder.Create(_clientId)
                                                 .WithAuthority(_authority)
                                                 .WithTokenCache(_tokenCache)
                                                 .Build();
```

**Describe alternatives you've considered**

Currently, we need to do the following:

```cs
var publicClient = PublicClientApplicationBuilder.Create(_clientId)
                                                 .WithAuthority(_authority)
                                                 .Build();
var filePath = "...redefining the path..."
publicClient.UserTokenCache.SetAfterAccess(notificationArgs =>
{
    if (notificationArgs.HasStateChanged)
    {
        // mechanism to write to filePath defined above
    }
});
publicClient.UserTokenCache.SetBeforeAccess(notificationArgs =>
{
    // mechanism to read from filePath defined above
});
```

Both of these methods are already defined in our class that wraps the `TokenCache` we pass around, so it would be great if we didn't have to redefine the methods and determine the path to the cache (and expose it to outside classes that shouldn't know about it).

**Additional context**

N/A

**Comment by jmprieur** [comment]
@cormacpayne 

Interestingly, in an early version of MSAL 3.0.0-preview, we had the .WithUserTokenCache() and .WithAppTokenCache() methods, however, we have chosen to remove them and have the builder instantiate the cache because cache in general is a domain where we want to provide out of the box token cache serialization implementations in the future (and even if they would still implement the `ITokenCache` interface, the implementation would not be `TokenCache`).

**Comment by jmprieur** [comment]
@cormacpayne : can we close this ?

**Comment by cormacpayne** [comment]
@jmprieur yes we can 😁
