### ISSUE TITLE
SourceLink is no longer available in MSAL 3.0.0 preview

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#953]
**Which Version of MSAL are you using ?**
 MSAL 3.0.0-preview 

**Platform**
all

**Repro**

1. Open MSAL 2.7.1 and MSAL 3.0.0-preview nupkg with NuGet packgae explorer
2. Navigate and double click on a DLL
3. Observe "Embedded PDB data" on 2.7.1 as having links to GitHub - this is SourceLink

**Expected behavior**
Msal 3 should also have SourceLink

**Actual behavior**
Msal 3 does not seem to have SourceLink

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
