### ISSUE TITLE
Xamarin.Android: User cannot login with Edge browser

### ISSUE THREAD

**Issue by tipa** [AzureAD/microsoft-authentication-library-for-dotnet#958]
**Which Version of MSAL are you using ?**
MSAL 3.0.0-preview

**Platform**
Xamarin.Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL

**Repro**
- Chrome disabled on the device
- Edge set as standard browser
- clientApplication.AcquireTokenAsync(Scopes, new UIParent(activity))
(tested on Samsung Galaxy J6)

**Expected behavior**
User can log in and give the app the needed permissions
According to this page, it should work: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Android-system-browser

**Actual behavior**
Use can sign in (enter email & password), but on the permission page (app needs you to confirm its permissions to...), when clicking "yes", the app does not react. There is also no error. Nothing happens. The user needs to cancel the login UI

**Comment by danieldobalian** [comment]
Hey!

Thanks for highlighting this issue, we are aware of an issue with the Edge app being used as a CustomTab and are working on a fix with the Edge team. We'll keep this thread update with a fix.

**Comment by henrik-me** [comment]
Please follow the progress via the link provided above and re-open if you believe there is anything we can help with.
