### ISSUE TITLE
OperationCancelled Exception in CustomWebUI can throw error related to Android

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#961]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 3.0.0-preview 

**Repro**

When a CustomWebUI flow is cancelled, the error message contains messaging around "if you're not an Android device..." and this isn't Android specific.  Need to clean up messaging.

**Comment by henrik-me** [comment]
@jennyf19 : link related item?

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/986

**Comment by jennyf19** [comment]
@henrik-me [related issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/727)
