### ISSUE TITLE
MSAL - Angular don't give JWT token with aud(audience) of Azure Active Directory Graph Api instead it gives for Microsoft graph api

### ISSUE THREAD

**Issue by komal-allscripts** [AzureAD/microsoft-authentication-library-for-dotnet#968]
**Which Version of MSAL are you using ?**
"@azure/msal-angular": "^0.1.2

**Platform**
Angular 7, typescript

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ *] Integrated Windows Auth
    * [* ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
We are creating a new Application which is going in production soon.

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
When set the protectedResourceMap as Azure Active Directory graph api, it should give token with aud 'https://sts.windows.net/', but instead it gives token with aud 'https://graph.microsoft.com'.

**Actual behavior**
When set the protectedResourceMap as Azure Active Directory graph api, it should give token with aud 'https://sts.windows.net/', but instead it gives token with aud 'https://graph.microsoft.com'.

Also when i use this token with actual Azure Active Directory graph api call, it gives error of Token expired. 

using below typescript code to get the token ; 

 public async getAccessToken(endpointUri: string): Promise<boolean> {

    this.accessToken = '';
    const scopes = this.msalService.getScopesForEndpoint(endpointUri);

    return new Promise<boolean>((resolve, reject) => {
      this.msalService.acquireTokenSilent(scopes)

        .then(accessToken => {
          this.accessToken = accessToken;
          resolve(true);
          // tslint:disable-next-line: promise-function-async
        }).catch(() => {

          return this.msalService.acquireTokenPopup(scopes)
            .then(token => {

              this.accessToken = token;
              resolve(true);

            })
            .catch((error) => {
              reject(new Error(error));
            });
        });
    });
  }

**Possible Solution**

**Additional context/ Logs / Screenshots**

**Comment by komal-allscripts** [comment]
Please look into this issue asap

**Comment by jmprieur** [comment]
@komal-allscripts : 
Also are you sure that you meant 'https://sts.windows.net/' ? not 'https://graph.windows.net/' for Azure AD Graph? 
 'https://sts.windows.net/' is the same as `https://login.microsoftonline.com`: this is the URL of the Security Token Service (Azure AD), not the Graph

BTW, if using  'https://graph.windows.net/' does not fix your use you need to re-create this issue on MSAL.js (https://github.com/AzureAD/microsoft-authentication-library-for-js). 
This is the MSAL.NET repository



cc: @navyasric

**Comment by komal-allscripts** [comment]
hey sorry not ''https://sts.windows.net/' but it is 'https://graph.windows.net/'
