### ISSUE TITLE
PublicClientApplicationBuilder.CreateWithApplicationOptions does not respect the audience

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#969]
**Which Version of MSAL are you using ?**
MSAL 3.0.0-preview

**Platform**
Any (for instance desktop)

**What authentication flow has the issue?**
Any (this is app config)

Other? - please describe;

**Repro**

```csharp
PublicClientApplicationOptions options = new PublicClientApplicationOptions();
options.AzureCloudInstance = AzureCloudInstance.AzurePublic;
options.AadAuthorityAudience = AadAuthorityAudience.AzureAdMultipleOrgs;
options.ClientId = "ebe2ab4d-12b3-4446-8480-5c3828d04c50";

var app = PublicClientApplicationBuilder.CreateWithApplicationOptions(options)
                                                 .Build();
string authority = app.Authority;
```

**Expected behavior**
`authority` should be `https://login.microsoftonline.com/organizations/`

**Actual behavior**
whereas it is `https://login.microsoftonline.com/common/`

**Note that**
If we override the options with 
`.WithAuthority(options.AzureCloudInstance, AadAuthorityAudience.AzureAdMultipleOrgs)`, this works correctly ...

**Important**
When this bug is fixed, please remove the work around in the following samples:
- [(https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2](https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2/blob/db1941a634228585f6badc658d8228e0f35dc538/up-console/Program.cs#L60)
- [(https://github.com/Azure-Samples/active-directory-dotnet-iwa-v2](https://github.com/Azure-Samples/active-directory-dotnet-iwa-v2/blob/4a5e277049d5d4cdfde88a13bc5df2c27377b6ef/iwa-console/Program.cs#L60)

**Comment by jmprieur** [comment]
@MarkZuber @bgavrilMS @henrik-me @jennyf19 @trwalke

**Comment by henrik-me** [comment]
seems like we are missing a test :)
