### ISSUE TITLE
Azue AD B2C GetAccountsAsync returns 0 accounts v 3.0 preview

### ISSUE THREAD

**Issue by tstevanovic** [AzureAD/microsoft-authentication-library-for-dotnet#974]
**Which Version of MSAL are you using ?**
MSAL 3.0.0-preview 

**Platform**
xamarin UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)

Other? - please describe;

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**
    public static string Tenant = "XXXX.onmicrosoft.com";
        public static string ClientID = "UID";
 public static string PolicySignUpSignIn = "b2c_1_defaultflow";
    public static string AuthorityBase = $"https://login.microsoftonline.com/tfp/{Tenant}/";
        public static string Authority = $"{AuthorityBase}{PolicySignUpSignIn}";

PCA = PublicClientApplicationBuilder.Create(ClientId)
        .WithB2CAuthority(Authority)
       .WithRedirectUri($"msal{ClientID}://auth")
        .Build();

 IEnumerable<IAccount> accounts = await PCA.GetAccountsAsync();

**Expected behavior**
Should return 2 Accounts as previous version. It is a B2C AD application, with previous version works fine. The init of PCA was done by using new documentation 

**Actual behavior**
It returns 0 Accounts.

**Comment by jennyf19** [comment]
@tstevanovic How are you setting up the AcquireToken Interactive calls? Can you paste the code here, like you did above w/the public client. thanks.

**Comment by tstevanovic** [comment]
`IEnumerable<IAccount> accounts = await PCA.GetAccountsAsync();

            AuthenticationResult result = null;

            try
            {
                try
                {
                    result = await MobileAuth.PCA.AcquireTokenSilentAsync(
                        Scopes, GetAccountByPolicy(accounts, PolicySignUpSignIn), Authority, false);
                }
                catch (MsalUiRequiredException e)
                {
                    await UserDialogs.Instance.AlertAsync(e.Message, "Error", "Ok");

                    //if (e.ErrorCode == MsalError.FailedToRefreshToken || e.ErrorCode == MsalError.CodeExpired)
                    //{
                    result = await MobileAuth.PCA.AcquireTokenAsync(Scopes, GetAccountByPolicy(accounts, PolicySignUpSignIn), UiParent);
                    //}

                    
                }
                catch (MsalServiceException e)
                {
                    // Exception: AdalServiceException 
                    // Represents an error produced by the STS. 
                    // e.ErrorCode contains the error code and description, which can be used for debugging. 
                    // NOTE: Do not code a dependency on the contents of the error description, as it can change over time.

                    // Action: Case 2, not resolvable with an interactive request.
                    // Attempt retry after a timed interval or user action.

                    await UserDialogs.Instance.AlertAsync(e.Message, "Error", "Ok");

                    if (e.ErrorCode == MsalError.FailedToRefreshToken || e.ErrorCode == MsalError.CodeExpired)
                    {
                        result = await MobileAuth.PCA.AcquireTokenAsync(Scopes, GetAccountByPolicy(accounts, PolicySignUpSignIn), UiParent);
                    }

                    

                }

                catch (MsalException e)
                {
                    // Exception: AdalException 
                    // Represents a library exception generated by ADAL .NET. 
                    // e.ErrorCode contains the error code. 

                    // Action: Case 2, not resolvable with an interactive request.
                    // Attempt retry after a timed interval or user action.
                    // Example Error: network_not_available, default case.

                    await UserDialogs.Instance.AlertAsync(e.Message, "Error", "Ok");
                }
                catch (Exception e)
                {
                    // Exception: AdalSilentTokenAcquisitionException
                    // Caused when there are no tokens in the cache or a required refresh failed. 

                    // Action: Case 1, resolvable with an interactive request. 

                    await UserDialogs.Instance.AlertAsync(e.Message, "Error", "Ok");
                }`

I am aware I can change the AcquireToken code to new syntax, but the IEnumerable<IAccount> accounts = await PCA.GetAccountsAsync(); returns 0 accounts before I was able to get to change other code, throwing null exception at passing the call AcquireToken as no Accounts found.

**Comment by jennyf19** [comment]
@tstevanovic I was unable to repro this issue. Can you send us [logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#with-msalnet-3x)?

You might consider updating the acquire token code to the new builder pattern as well and see if that makes a difference.

**Comment by tstevanovic** [comment]
I installed MSAL 3.0.2-preview and updated to new builder acquire token pattern and it worked. 

Thanks for your help.

**Comment by jennyf19** [comment]
@tstevanovic thanks for the update. We are in the process of removing the v2 api, so probably best to update now anyway.
