### ISSUE TITLE
Add InternalsVisibleTo for Microsoft.Identity.Extensions* and Microsoft.Identity.WebExtensions*

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-dotnet#975]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 3.0.0-preview

Microsoft.Identity.Extensions and Microsoft.Identity.WebExtensions will need access to Logging/Telemetry possibly and such it needs InternalsVisible access.

**Comment by jmprieur** [comment]
@MarkZuber : wan't this in 3.0.1?

**Comment by MarkZuber** [comment]
yes.  this is in 3.0.1.  milestone marked.
