### ISSUE TITLE
Send x-app-name and x-app-ver to query URLs

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#978]
**Is your feature request related to a problem? Please describe.**
See [add client app name and version to authorization and token requests](https://identitydivision.visualstudio.com/DefaultCollection/DevEx/_git/AuthLibrariesApiReview?path=%2FClientAppNameVersion%2Foverview.md&version=GBdev) for why and what.

**What to do?**
1. In the `ApplicationOptions` class, add two string properties;
  - `ClientName` 
  - `ClientVersion`
- Obsolete the `Component` property (which was combining ClientName and Version

2. If the developer does not provide the `ClientName` and `ClientVersion`, these are computed with values from the OS. In the case of .NET we can probably use the Assembly attributes.

3. Append the client name and version to the following parameters when making authorization and token requests:
- `x-app-name`
- `x-app-ver`

`.WithApplicationInformation(string clientName, string clientVersion)`

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1044

**Comment by jennyf19** [comment]
included in [msal 3.0.3-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/3.0.3-preview)
