### ISSUE TITLE
SubError property on MsalServiceException should be noted with an "Experimental" message,

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#979]
**Is your feature request related to a problem? Please describe.**
The SubError property on MsalServiceException should be noted with an "Experimental" message, as the way it's going to be reported in the future might change

**Describe the solution you'd like**
An obsolete attribute (as these produce warnings), indicating that this property is experimental and the way to surface error details might change in the future … for details https://aka.ms/msal-net-suberror

**Comment by jmprieur** [comment]
@henrik-me FYI

**Comment by henrik-me** [comment]
Triage: Make the field internal for now. Workaround for experimenting is using the Body.
