### ISSUE TITLE
Product definition\naming clarification

### ISSUE THREAD

**Issue by ksp2018** [AzureAD/microsoft-authentication-library-for-dotnet#981]
### Documentation Related To Component:
Product definition\naming clarification for MSAL

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
With MSAL in any other programming language\framework, MSAL being a package is simple - its a package named MSAL that you download and hit the ground running. With .Net and .Net Core, this is does not appear to be so. If I am tracking correctly, then MSAL is downloaded from Nuget in a package called Microsoft.Identity.Client. However, if I follow the link, https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg, I connect to AAD via OpenId and v2 endpoints, however at not point is Microsoft.Identity.Client ever installed. This actually appears to be very similar code as would be generated using the "Work and School" authentication from the .Net Core Web MVC project template. It doesn't seem like Microsoft.Identity.Client is used for signing in users, just for more complex functionality like calling graph. So my questions are:

- Is MSAL just the Single Microsoft.Identity.Client package or if I follow the tutorial am I still using the MSAL product? 
- Is MSAL indeed just for doing things like using graph? If so, then what product is being used for the actual signing in.
- Is this indeed the same set of libraries that are used form the project template w,hen work and school authentication is selected? If not what is the different?'
- Specifically what nuget packages/versions constitute the MSAL library for .net? 

Thank you in advance - these questions will go a long way in our enterprise documentation.

**Comment by ksp2018** [comment]
Any update on this?

**Comment by bgavrilMS** [comment]
@jmprieur can clarify but if you only need to login to your website, you do not need MSAL, as that sample shows. 

MSAL is used to fetch tokens for accessing protected APIs, such as the graph, or your own APIs. 
MSAL on NuGet: https://www.nuget.org/packages/Microsoft.Identity.Client/

Scenarios that MSAL is covering: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/scenarios
