### ISSUE TITLE
RedirectUri should be case sensitive

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#983]
**Which Version of MSAL are you using ?**
All.

**Platform**
All, but specifically iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
Affects apps that use mixed casing in their BundleId and are using broker

**Repro**

BundleId is:
`com.company.MyCatApp`

RedirectUri is:
`msauth.com.company.MyCatApp://auth`

MSAL will most likely throw a
`MsalServiceException: source application bundle identifier should be same as the redirect URI domain`

**Expected behavior**
Since BundleId is case sensitive from Apple's perspective AND according to OpenId spec, "The URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider, with the matching performed as described in Section 6.2.1 of [RFC3986] (Simple String Comparison). ", MSAL should send the redirectUri exactly as the customer has registered it. 

**Actual behavior**
MSAL accepts a string as a redirectUri, but later converts it to Uri, which lowercases the input. According to the [spec](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netframework-4.7.2#remarks), new Uri() will automatically lowercase the value passed in, so MSAL is handling a lowercased redirectUri. When sending this value to broker, it does not match a BundleId that has uppercase letters.

**Possible Solution**
Team needs to discuss how to handle this. 

**Additional context/ Logs / Screenshots**
[Related ADAL issue](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1345)

**Comment by bgavrilMS** [comment]
@jennyf19 - how many customers are affected by this? Is it customary to use a BundleId with capital letters? I think not, the namespace like notation of a bundle id (e.g. com.microsoft.myapp), which is also used in Java, is by convention case insensitive. 

As you point out, an URI is case insensitive / lowecase. 

Can you we mark this as "by design" and add a "known limitation" to the wiki?

**Comment by bgavrilMS** [comment]
Not needed for 3.0.4 - we need to focus on features and fixes that affect the public API only so that we can remove the -preview tag.

**Comment by jennyf19** [comment]
@bgavrilMS I'm also working w/the iOS team so the broker can handle this and not us.

**Comment by jmprieur** [comment]
@jennyf19 : did you have some update from the iOS team?

**Comment by jennyf19** [comment]
@jmprieur no update, but based on how our Uris are formed in C#, i'm going to push back on the iOS team to handle upper/lower case bundleIds. Will follow up with them this week. Going to close, as I think the fix should be in broker.

**Comment by jmprieur** [comment]
Thanks for the update, @jennyf19
