### ISSUE TITLE
Allow reading items in token cache independent of client application

### ISSUE THREAD

**Issue by cormacpayne** [AzureAD/microsoft-authentication-library-for-dotnet#998]
**Is your feature request related to a problem? Please describe.**

In Azure PowerShell, our goal is to grab all of the accounts from any given MSAL token cache in order to populate the contexts (account id / subscription / tenant structure) that we use to make calls to Azure. If a user writes to a shared token cache using another application, and then comes over to Azure PowerShell, we have no way of reading the token cache without knowing the tenants (and client ids for now) used to create the key for the accounts in the cache -- we could get _some_ of the tenants from saved contexts if the user has used Azure PowerShell previously, but if it's their first time using it, we have no information about the tenants the user has access to. It would be nice to have a method, similar to ADAL's [`TokenCache.ReadItems()`](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/3ebfe7104e2ab783b6c8c88a50709833e25e7325/src/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.cs#L340), to enable this functionality without having to instantiate a client application with a tenant and client id.

**Describe the solution you'd like**

A mechanism for reading a token cache without needing to know about a tenant id (or client id for now), either with a similar `ReadItems()` method in a token cache helper class, or having the ability to instantiate a `PublicClientApplication` object without needing to provide a tenant or client id to make these generic calls.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by cormacpayne** [comment]
@jmprieur @henrik-me @bgavrilMS @jennyf19 let me know if you need any additional information about my scenario -- I'd be happy to sync up offline about this.

CC: @devigned

**Comment by jennyf19** [comment]
@MarkZuber

**Comment by cormacpayne** [comment]
Quick update: I did a little more testing around this area to determine what I get back from the `GetAccountsAsync()` call in different scenarios, and here's what I found:

In all scenarios, I'm instantiating the `PublicClientApplication` as follows:

```cs
var authority = "https://login.microsoftonline.com/" + tenantId;
var tempClient = new PublicClientApplication(clientId, authority, tokenCache);
```

The `tokenCache` is always pointing to the same `msal.cache` file that isn't changed during testing. The `tenantId` and `clientId` variables will change as outlined below.

The cache is instantiated with four different accounts from what I can tell (under the "Account" section of the file):

| Username                                   | Realm      |
| --------------------------------   | ---------  |
| corm@microsoft.com                   | common |
| corm@microsoft.com                   | Tenant A |
| corm@microsoft.com                   | Tenant B |
| foobar@csptest.onmicrosoft.com | Tenant C |

(I can provide the actual cache offline if needed)

To read the accounts from the cache, I run the following:

```cs
var accounts = tempClient.GetAccountsAsync()
                    .ConfigureAwait(false)
                    .GetAwaiter()
                    .GetResult();
```

The first time I read the accounts, I have `tenantId` set to "common", and I receive the following accounts:

- Account 1
    - Environment: https://login.microsoftonline.com
    - HomeAccountId:
        - AccountId: {{expected value}}
        - ObjectId: {{expected value}}
        - TenantId: Tenant A
    - Username: corm@microsoft.com

- Account 2
    - Environment: https://login.microsoftonline.com
    - HomeAccountId:
        - AccountId: {{expected value}}
        - ObjectId: {{expected value}}
        - TenantId: Tenant C
    - Username: foobar@csptest.onmicrosoft.com

The second time I read the accounts, I have `tenantId` set to "Tenant A", and I receive the same two accounts as above (with the same values for each property). The same thing also happens when I try it with "Tenant B" and "Tenant C". I then went ahead and changed one of the digits in the `clientId` that we were using, and I continued to receive the same two accounts.

Does the `GetAccountsAsync()` call do any filtering over the parameters provided to the client application? I still feel that we should have a separate method (similar to the `ReadItems()` method that was in the ADAL token cache class) that will allow us to read over accounts in a given token cache, along with some filtering over these specific properties. Let me know if you have any questions and I'll be happy to sync up offline about this!

**Comment by jmprieur** [comment]
@cormacpayne 
What would you think of us exposing, on an account, a collection of TenantProfile which would contain information about the tenant for which we got a token for the given account? (it would have a local AccountId).

Would something like what is in the following UML diagram fulfil your needs? (knowing that today we only have the members written in blue fontface)
![image](https://user-images.githubusercontent.com/13203188/55132625-401c3e80-50e0-11e9-8173-475ee2a29364.png)

**Comment by jmprieur** [comment]
cc: @henrik-me

**Comment by bgavrilMS** [comment]
Will consider as part of the tenant profiles improvement.
